CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('anp', 'ଅଁଗୀକା');
INSERT INTO "country" ("id", "name") VALUES ('ak', 'ଅକନ୍');
INSERT INTO "country" ("id", "name") VALUES ('und', 'ଅଜଣା ଏବଂ ଅବୈଧ ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('ady', 'ଅଦ୍ୟଘେ');
INSERT INTO "country" ("id", "name") VALUES ('aa', 'ଅଫାର୍');
INSERT INTO "country" ("id", "name") VALUES ('ae', 'ଅବେସ୍ତନ');
INSERT INTO "country" ("id", "name") VALUES ('de_AT', 'ଅଷ୍ଟ୍ରିଆନ୍ ଜର୍ମାନ');
INSERT INTO "country" ("id", "name") VALUES ('en_AU', 'ଅଷ୍ଟ୍ରେଲିଆନ୍ ଇଁରାଜୀ');
INSERT INTO "country" ("id", "name") VALUES ('aus', 'ଅଷ୍ଟ୍ରେଲିଆନ୍ ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('map', 'ଅଷ୍ଟ୍ରୋନେସିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('ain', 'ଆଇନୁ');
INSERT INTO "country" ("id", "name") VALUES ('is', 'ଆଇସଲାଣ୍ଡିକ୍');
INSERT INTO "country" ("id", "name") VALUES ('akk', 'ଆକାଡିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('ach', 'ଆକୋଲି');
INSERT INTO "country" ("id", "name") VALUES ('ace', 'ଆଚାଇନୀଜ୍');
INSERT INTO "country" ("id", "name") VALUES ('az', 'ଆଜେରବାଇଜାନି');
INSERT INTO "country" ("id", "name") VALUES ('cch', 'ଆତ୍ସମ୍');
INSERT INTO "country" ("id", "name") VALUES ('ath', 'ଆଥପାସ୍କାନ୍ ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('ada', 'ଆଦାଙ୍ଗେମ୍');
INSERT INTO "country" ("id", "name") VALUES ('apa', 'ଆପାଚୀ ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('af', 'ଆଫ୍ରିକାନସ୍');
INSERT INTO "country" ("id", "name") VALUES ('afh', 'ଆଫ୍ରିହିଲି');
INSERT INTO "country" ("id", "name") VALUES ('afa', 'ଆଫ୍ରୋ ଏସିଆଟିକ୍ ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('ab', 'ଆବ୍ଖାଜିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('av', 'ଆଭାରିକ୍');
INSERT INTO "country" ("id", "name") VALUES ('am', 'ଆମହାରକି');
INSERT INTO "country" ("id", "name") VALUES ('ar', 'ଆରବିକ୍');
INSERT INTO "country" ("id", "name") VALUES ('arn', 'ଆରାଉକାନିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('arp', 'ଆରାପାହୋ');
INSERT INTO "country" ("id", "name") VALUES ('arc', 'ଆରାମାଇକ୍');
INSERT INTO "country" ("id", "name") VALUES ('rup', 'ଆରୋମାନିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('an', 'ଆର୍ଗୋନୀ');
INSERT INTO "country" ("id", "name") VALUES ('hy', 'ଆର୍ମେନିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('arw', 'ଆରୱକ');
INSERT INTO "country" ("id", "name") VALUES ('sq', 'ଆଲବାନିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('ale', 'ଆଲେଇଟୁ');
INSERT INTO "country" ("id", "name") VALUES ('tut', 'ଆଲ୍ଟିକ୍ ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('ast', 'ଆଷ୍ଟୁରିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('as', 'ଆସାମୀ');
INSERT INTO "country" ("id", "name") VALUES ('ay', 'ଆୟମାରା');
INSERT INTO "country" ("id", "name") VALUES ('awa', 'ଆୱାଧି');
INSERT INTO "country" ("id", "name") VALUES ('inh', 'ଇଁଙ୍ଗୁଶ୍');
INSERT INTO "country" ("id", "name") VALUES ('cpe', 'ଇଁରାଜୀ ଆଧାରିତ କ୍ରେଓଲ୍ କିମ୍ବା ପିଜିନ୍');
INSERT INTO "country" ("id", "name") VALUES ('en', 'ଇଂରାଜୀ');
INSERT INTO "country" ("id", "name") VALUES ('ig', 'ଇଗ୍ବୋ');
INSERT INTO "country" ("id", "name") VALUES ('ijo', 'ଇଜୋ');
INSERT INTO "country" ("id", "name") VALUES ('it', 'ଇଟାଲିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('io', 'ଇଡୋ');
INSERT INTO "country" ("id", "name") VALUES ('inc', 'ଇଣ୍ଡିକ୍ ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('ine', 'ଇଣ୍ଡୋ-ୟୁରୋପୀୟ ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('id', 'ଇଣ୍ଡୋନେସିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('iu', 'ଇନକୀଟୁତ୍');
INSERT INTO "country" ("id", "name") VALUES ('smn', 'ଇନାରୀ ସାମି');
INSERT INTO "country" ("id", "name") VALUES ('ik', 'ଇନୁପିୟାକ୍');
INSERT INTO "country" ("id", "name") VALUES ('iba', 'ଇବାନ୍');
INSERT INTO "country" ("id", "name") VALUES ('ira', 'ଇରାନୀ ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('ga', 'ଇରିସ୍');
INSERT INTO "country" ("id", "name") VALUES ('iro', 'ଇରୋକ୍ୱୋୟାନ୍ ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('ie', 'ଇର୍ଣ୍ଟରଲିଙ୍ଗୁଇ');
INSERT INTO "country" ("id", "name") VALUES ('ia', 'ଇର୍ଣ୍ଟଲିଙ୍ଗୁଆ');
INSERT INTO "country" ("id", "name") VALUES ('ilo', 'ଇଲୋକୋ');
INSERT INTO "country" ("id", "name") VALUES ('ee', 'ଇୱେ');
INSERT INTO "country" ("id", "name") VALUES ('ewo', 'ଇୱୋଣ୍ଡୋ');
INSERT INTO "country" ("id", "name") VALUES ('uz', 'ଉଜବେକ୍');
INSERT INTO "country" ("id", "name") VALUES ('nai', 'ଉତ୍ତର ଆମେରିକା ଇଣ୍ଡିଆନ୍ ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('nd', 'ଉତ୍ତର ନେଡବେଲେ');
INSERT INTO "country" ("id", "name") VALUES ('frr', 'ଉତ୍ତର ଫ୍ରିସିୟାନ୍');
INSERT INTO "country" ("id", "name") VALUES ('se', 'ଉତ୍ତର ସାମି');
INSERT INTO "country" ("id", "name") VALUES ('nso', 'ଉତ୍ତରୀ ସୋଥୋ');
INSERT INTO "country" ("id", "name") VALUES ('udm', 'ଉଦମୂର୍ତ୍ତ');
INSERT INTO "country" ("id", "name") VALUES ('hsb', 'ଉପର ସର୍ବିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('umb', 'ଉମ୍ବୁଣ୍ଡୁ');
INSERT INTO "country" ("id", "name") VALUES ('ur', 'ଉର୍ଦ୍ଦୁ');
INSERT INTO "country" ("id", "name") VALUES ('eka', 'ଏକାଜୁକ୍');
INSERT INTO "country" ("id", "name") VALUES ('nqo', 'ଏନ୍କୋ');
INSERT INTO "country" ("id", "name") VALUES ('efi', 'ଏଫିକ୍');
INSERT INTO "country" ("id", "name") VALUES ('myv', 'ଏର୍ଜୟା');
INSERT INTO "country" ("id", "name") VALUES ('elx', 'ଏଲାମାଇଟ୍');
INSERT INTO "country" ("id", "name") VALUES ('alg', 'ଏଲ୍ଗୋନକ୍ବିନା ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('et', 'ଏସ୍ତୋନିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('eo', 'ଏସ୍ପାରେଣ୍ଟୋ');
INSERT INTO "country" ("id", "name") VALUES ('oj', 'ଓଜିୱା');
INSERT INTO "country" ("id", "name") VALUES ('ota', 'ଓଟ୍ଟୋମନ୍ ତୁର୍କିସ୍');
INSERT INTO "country" ("id", "name") VALUES ('oto', 'ଓଟ୍ଟୋମିଆନ୍ ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('or', 'ଓଡ଼ିଆ');
INSERT INTO "country" ("id", "name") VALUES ('om', 'ଓରୋମୋ');
INSERT INTO "country" ("id", "name") VALUES ('oc', 'ଓସିଟାନ୍');
INSERT INTO "country" ("id", "name") VALUES ('os', 'ଓସେଟିକ୍');
INSERT INTO "country" ("id", "name") VALUES ('kg', 'କଙ୍ଗୋ');
INSERT INTO "country" ("id", "name") VALUES ('kac', 'କଚିନ୍');
INSERT INTO "country" ("id", "name") VALUES ('kr', 'କନୁରୀ');
INSERT INTO "country" ("id", "name") VALUES ('kn', 'କନ୍ନଡ');
INSERT INTO "country" ("id", "name") VALUES ('cop', 'କପ୍ଟିକ୍');
INSERT INTO "country" ("id", "name") VALUES ('kab', 'କବାଇଲ୍');
INSERT INTO "country" ("id", "name") VALUES ('kam', 'କମ୍ବା');
INSERT INTO "country" ("id", "name") VALUES ('krc', 'କରାଚୟ-ବଲ୍କାର');
INSERT INTO "country" ("id", "name") VALUES ('cau', 'କାକୋଶୀ ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('kk', 'କାଜାକ୍');
INSERT INTO "country" ("id", "name") VALUES ('bs', 'କାଟଲାନ୍');
INSERT INTO "country" ("id", "name") VALUES ('ca', 'କାଟାଲାନ୍');
INSERT INTO "country" ("id", "name") VALUES ('cad', 'କାଡୋ');
INSERT INTO "country" ("id", "name") VALUES ('en_CA', 'କାନାଡିଆନ୍ ଇଁରାଜୀ');
INSERT INTO "country" ("id", "name") VALUES ('fr_CA', 'କାନାଡିଆନ୍ ଫ୍ରେଞ୍ଚ');
INSERT INTO "country" ("id", "name") VALUES ('kbd', 'କାବାର୍ଡିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('kaa', 'କାରା-କଲ୍ପକ୍');
INSERT INTO "country" ("id", "name") VALUES ('car', 'କାରିବ୍');
INSERT INTO "country" ("id", "name") VALUES ('kar', 'କାରେନ୍');
INSERT INTO "country" ("id", "name") VALUES ('krl', 'କାରେଲିୟାନ୍');
INSERT INTO "country" ("id", "name") VALUES ('xal', 'କାଲ୍ମୀକ୍');
INSERT INTO "country" ("id", "name") VALUES ('csb', 'କାଶୁବିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('ks', 'କାଶ୍ମିରୀ');
INSERT INTO "country" ("id", "name") VALUES ('kaw', 'କାୱି');
INSERT INTO "country" ("id", "name") VALUES ('rw', 'କିନ୍ୟାରୱାଣ୍ଡା');
INSERT INTO "country" ("id", "name") VALUES ('kmb', 'କିମ୍ବୁଣ୍ଡୁ');
INSERT INTO "country" ("id", "name") VALUES ('ky', 'କିରଗିଜ୍');
INSERT INTO "country" ("id", "name") VALUES ('ki', 'କୀକୁୟୁ');
INSERT INTO "country" ("id", "name") VALUES ('kut', 'କୁତେନାଉ');
INSERT INTO "country" ("id", "name") VALUES ('kum', 'କୁମୀକ୍');
INSERT INTO "country" ("id", "name") VALUES ('kru', 'କୁରୁଖ');
INSERT INTO "country" ("id", "name") VALUES ('ku', 'କୁର୍ଦ୍ଦିଶ୍');
INSERT INTO "country" ("id", "name") VALUES ('cus', 'କୁଶିତିକ୍ ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('art', 'କୃତ୍ରିମ ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('cel', 'କେଲ୍ଟ ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('kpe', 'କୈପେଲେ');
INSERT INTO "country" ("id", "name") VALUES ('kok', 'କୋନକାନୀ');
INSERT INTO "country" ("id", "name") VALUES ('kv', 'କୋମି');
INSERT INTO "country" ("id", "name") VALUES ('ko', 'କୋରିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('kfo', 'କୋରୋ');
INSERT INTO "country" ("id", "name") VALUES ('kw', 'କୋର୍ନିସ୍');
INSERT INTO "country" ("id", "name") VALUES ('co', 'କୋର୍ସିକାନ୍');
INSERT INTO "country" ("id", "name") VALUES ('kos', 'କୋସରୈନ୍');
INSERT INTO "country" ("id", "name") VALUES ('zxx', 'କୌଣସି ଲିଙ୍ଗୁଇଷ୍ଟ ସାମଗ୍ରୀ ନାହିଁ');
INSERT INTO "country" ("id", "name") VALUES ('cr', 'କ୍ରୀ');
INSERT INTO "country" ("id", "name") VALUES ('mus', 'କ୍ରୀକ୍');
INSERT INTO "country" ("id", "name") VALUES ('crh', 'କ୍ରୀମିନ୍ ତୁର୍କୀସ୍');
INSERT INTO "country" ("id", "name") VALUES ('kro', 'କ୍ରୁ');
INSERT INTO "country" ("id", "name") VALUES ('crp', 'କ୍ରେଓଲ୍ କିମ୍ବା ପିଜିନ୍');
INSERT INTO "country" ("id", "name") VALUES ('hr', 'କ୍ରୋଆଟିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('syc', 'କ୍ଲାସିକାଲ୍ ସିରିକ୍');
INSERT INTO "country" ("id", "name") VALUES ('tlh', 'କ୍ଲିଙ୍ଗନ୍');
INSERT INTO "country" ("id", "name") VALUES ('kj', 'କ୍ୱାନ୍ୟାମ୍');
INSERT INTO "country" ("id", "name") VALUES ('qu', 'କ୍ୱେଚୁଆ');
INSERT INTO "country" ("id", "name") VALUES ('kha', 'ଖାସୀ');
INSERT INTO "country" ("id", "name") VALUES ('kho', 'ଖୋତାନୀଜ୍');
INSERT INTO "country" ("id", "name") VALUES ('xh', 'ଖୋସା');
INSERT INTO "country" ("id", "name") VALUES ('khi', 'ଖୋସୀୟାନ୍ ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('km', 'ଖ୍ମେର୍');
INSERT INTO "country" ("id", "name") VALUES ('lg', 'ଗନ୍ଦା');
INSERT INTO "country" ("id", "name") VALUES ('gba', 'ଗବାୟା');
INSERT INTO "country" ("id", "name") VALUES ('gaa', 'ଗା');
INSERT INTO "country" ("id", "name") VALUES ('gl', 'ଗାଲସିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('gay', 'ଗାୟୋ');
INSERT INTO "country" ("id", "name") VALUES ('gez', 'ଗୀଜ୍');
INSERT INTO "country" ("id", "name") VALUES ('gn', 'ଗୁଆରାନୀ');
INSERT INTO "country" ("id", "name") VALUES ('gu', 'ଗୁଜୁରାଟୀ');
INSERT INTO "country" ("id", "name") VALUES ('gon', 'ଗୋଣ୍ଡି');
INSERT INTO "country" ("id", "name") VALUES ('got', 'ଗୋଥିକ୍');
INSERT INTO "country" ("id", "name") VALUES ('gor', 'ଗୋରୋଣ୍ଟାଲୋ');
INSERT INTO "country" ("id", "name") VALUES ('el', 'ଗ୍ରୀକ୍');
INSERT INTO "country" ("id", "name") VALUES ('kl', 'ଗ୍ରୀନଲାଣ୍ଡିକ୍');
INSERT INTO "country" ("id", "name") VALUES ('grb', 'ଗ୍ରେବୋ');
INSERT INTO "country" ("id", "name") VALUES ('cu', 'ଚର୍ଚ୍ଚ ସ୍ଲାଭିକ୍');
INSERT INTO "country" ("id", "name") VALUES ('zh', 'ଚାଇନୀଜ୍');
INSERT INTO "country" ("id", "name") VALUES ('cmc', 'ଚାମିକ୍ ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('ch', 'ଚାମୋରୋ');
INSERT INTO "country" ("id", "name") VALUES ('chn', 'ଚିନୁକ୍ ଜାରଗାଁନ୍');
INSERT INTO "country" ("id", "name") VALUES ('chp', 'ଚିପେୱାନ୍');
INSERT INTO "country" ("id", "name") VALUES ('chb', 'ଚିବ୍ଚା');
INSERT INTO "country" ("id", "name") VALUES ('chk', 'ଚୁକୀସେ');
INSERT INTO "country" ("id", "name") VALUES ('cv', 'ଚୁଭାଶ୍');
INSERT INTO "country" ("id", "name") VALUES ('cs', 'ଚେକ୍');
INSERT INTO "country" ("id", "name") VALUES ('ce', 'ଚେଚନ୍');
INSERT INTO "country" ("id", "name") VALUES ('chy', 'ଚେଚେନା');
INSERT INTO "country" ("id", "name") VALUES ('chr', 'ଚେରୋକୀ');
INSERT INTO "country" ("id", "name") VALUES ('cho', 'ଚୋଟୱା');
INSERT INTO "country" ("id", "name") VALUES ('chg', 'ଛଗତାଇ');
INSERT INTO "country" ("id", "name") VALUES ('ka', 'ଜର୍ଜିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('gem', 'ଜର୍ମାନିକ୍ ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('de', 'ଜର୍ମାନ୍');
INSERT INTO "country" ("id", "name") VALUES ('zza', 'ଜାଜା');
INSERT INTO "country" ("id", "name") VALUES ('znd', 'ଜାଣ୍ଡେ');
INSERT INTO "country" ("id", "name") VALUES ('ja', 'ଜାପାନୀଜ୍');
INSERT INTO "country" ("id", "name") VALUES ('zap', 'ଜାପୋଟେକ୍');
INSERT INTO "country" ("id", "name") VALUES ('jv', 'ଜାଭାନୀଜ୍');
INSERT INTO "country" ("id", "name") VALUES ('gil', 'ଜିବ୍ରାଟୀଜ୍');
INSERT INTO "country" ("id", "name") VALUES ('za', 'ଜୁଆଙ୍ଗ');
INSERT INTO "country" ("id", "name") VALUES ('jrb', 'ଜୁଡେଓ-ଆରବୀକ୍');
INSERT INTO "country" ("id", "name") VALUES ('jpr', 'ଜୁଡେଓ-ପର୍ସିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('zun', 'ଜୁନୀ');
INSERT INTO "country" ("id", "name") VALUES ('zu', 'ଜୁଲୁ');
INSERT INTO "country" ("id", "name") VALUES ('zen', 'ଜେନାଗା');
INSERT INTO "country" ("id", "name") VALUES ('kaj', 'ଜ୍ଜୁ');
INSERT INTO "country" ("id", "name") VALUES ('nzi', 'ଞ୍ଜିମା');
INSERT INTO "country" ("id", "name") VALUES ('tig', 'ଟାଇଗ୍ରେ');
INSERT INTO "country" ("id", "name") VALUES ('tl', 'ଟାଗାଲଗ୍');
INSERT INTO "country" ("id", "name") VALUES ('tup', 'ଟୁପି ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('tum', 'ଟୁମ୍ବୁକା');
INSERT INTO "country" ("id", "name") VALUES ('tkl', 'ଟୋକେଲାଉ');
INSERT INTO "country" ("id", "name") VALUES ('tpi', 'ଟୋକ୍ ପିସିନ୍');
INSERT INTO "country" ("id", "name") VALUES ('to', 'ଟୋଙ୍ଗା');
INSERT INTO "country" ("id", "name") VALUES ('ti', 'ଟ୍ରିଗିନିଆ');
INSERT INTO "country" ("id", "name") VALUES ('nl', 'ଡଚ୍');
INSERT INTO "country" ("id", "name") VALUES ('dak', 'ଡାକୋଟା');
INSERT INTO "country" ("id", "name") VALUES ('da', 'ଡାନ୍ନିସ୍');
INSERT INTO "country" ("id", "name") VALUES ('dar', 'ଡାରାଗ୍ୱା');
INSERT INTO "country" ("id", "name") VALUES ('day', 'ଡାୟକ୍');
INSERT INTO "country" ("id", "name") VALUES ('dv', 'ଡିଭେହୀ');
INSERT INTO "country" ("id", "name") VALUES ('dua', 'ଡୁଆନା');
INSERT INTO "country" ("id", "name") VALUES ('dyu', 'ଡୁଆଲା');
INSERT INTO "country" ("id", "name") VALUES ('del', 'ଡେଲାୱେର୍');
INSERT INTO "country" ("id", "name") VALUES ('dgr', 'ଡୋଗ୍ରିବ୍');
INSERT INTO "country" ("id", "name") VALUES ('doi', 'ଡୋଗ୍ରୀ');
INSERT INTO "country" ("id", "name") VALUES ('ng', 'ଡୋଙ୍ଗା');
INSERT INTO "country" ("id", "name") VALUES ('tai', 'ତାଇ ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('tg', 'ତାଜିକ୍');
INSERT INTO "country" ("id", "name") VALUES ('tt', 'ତାତାର୍');
INSERT INTO "country" ("id", "name") VALUES ('tmh', 'ତାମାଶେକ୍');
INSERT INTO "country" ("id", "name") VALUES ('ta', 'ତାମିଲ୍');
INSERT INTO "country" ("id", "name") VALUES ('ty', 'ତାହିତିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('bo', 'ତିବେତାନ୍');
INSERT INTO "country" ("id", "name") VALUES ('tem', 'ତିମନେ');
INSERT INTO "country" ("id", "name") VALUES ('tsi', 'ତିସିମିସିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('tiv', 'ତୀଭ୍');
INSERT INTO "country" ("id", "name") VALUES ('tvl', 'ତୁଭାଲୁ');
INSERT INTO "country" ("id", "name") VALUES ('tyv', 'ତୁଭିନିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('tk', 'ତୁର୍କମେନ୍');
INSERT INTO "country" ("id", "name") VALUES ('tr', 'ତୁର୍କିସ୍');
INSERT INTO "country" ("id", "name") VALUES ('tet', 'ତେତୁମ୍');
INSERT INTO "country" ("id", "name") VALUES ('ter', 'ତେରେନୋ');
INSERT INTO "country" ("id", "name") VALUES ('te', 'ତେଲୁଗୁ');
INSERT INTO "country" ("id", "name") VALUES ('tli', 'ତ୍ଲିଙ୍ଗିଟ୍');
INSERT INTO "country" ("id", "name") VALUES ('kcg', 'ତ୍ୟାପ୍');
INSERT INTO "country" ("id", "name") VALUES ('tw', 'ତ୍ୱି');
INSERT INTO "country" ("id", "name") VALUES ('th', 'ଥାଇ');
INSERT INTO "country" ("id", "name") VALUES ('sai', 'ଦକ୍ଷିଣ ଆମେରିକା ଇଣ୍ଡିଆନ୍ ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('alt', 'ଦକ୍ଷିଣ ଆଲ୍ଟାଇ');
INSERT INTO "country" ("id", "name") VALUES ('nr', 'ଦକ୍ଷିଣ ନେଡବେଲେ');
INSERT INTO "country" ("id", "name") VALUES ('sma', 'ଦକ୍ଷିଣ ସାମି');
INSERT INTO "country" ("id", "name") VALUES ('din', 'ଦିଙ୍କା');
INSERT INTO "country" ("id", "name") VALUES ('dra', 'ଦ୍ରାବିଡିଆନ୍ ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('no', 'ନରୱେଜିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('nn', 'ନରୱେଜିଆନ୍ ନିୟୋର୍ସ୍କ');
INSERT INTO "country" ("id", "name") VALUES ('nb', 'ନରୱେଜିଆନ୍ ବୋକମଲ୍');
INSERT INTO "country" ("id", "name") VALUES ('nic', 'ନାଇଜର୍-କୋର୍ଡୋଫୌନିୟାନ୍ ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('na', 'ନାଉରୁ');
INSERT INTO "country" ("id", "name") VALUES ('nah', 'ନାଉହାତି');
INSERT INTO "country" ("id", "name") VALUES ('nv', 'ନାଭାଜୋ');
INSERT INTO "country" ("id", "name") VALUES ('dsb', 'ନିଚଳା ସର୍ବିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('ny', 'ନିୟାଞ୍ଜ');
INSERT INTO "country" ("id", "name") VALUES ('niu', 'ନିୟୁଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('nap', 'ନୀପୋଲିଟାନ୍');
INSERT INTO "country" ("id", "name") VALUES ('ssa', 'ନୀଲ୍ ସାହାରି ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('nia', 'ନୀୟାସ୍');
INSERT INTO "country" ("id", "name") VALUES ('ne', 'ନେପାଳୀ');
INSERT INTO "country" ("id", "name") VALUES ('new', 'ନେୱାରୀ');
INSERT INTO "country" ("id", "name") VALUES ('nog', 'ନୋଗାଇ');
INSERT INTO "country" ("id", "name") VALUES ('nyn', 'ନ୍ୟାନକୋଲ୍');
INSERT INTO "country" ("id", "name") VALUES ('nym', 'ନ୍ୟାମୱେଜୀ');
INSERT INTO "country" ("id", "name") VALUES ('nyo', 'ନ୍ୟାରୋ');
INSERT INTO "country" ("id", "name") VALUES ('tog', 'ନ୍ୟାସା ଟୋଙ୍ଗୋ');
INSERT INTO "country" ("id", "name") VALUES ('nub', 'ନ୍ୟୁବିଆନ୍ ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('pa', 'ପଞ୍ଜାବୀ');
INSERT INTO "country" ("id", "name") VALUES ('pt', 'ପର୍ତ୍ତୁଗ୍ରୀଜ୍');
INSERT INTO "country" ("id", "name") VALUES ('cpp', 'ପର୍ତ୍ତୁଗ୍ରୀଜ୍ ଆଧାରିତ କ୍ରେଓଲ୍ କିମ୍ବା ପିଜିନ୍');
INSERT INTO "country" ("id", "name") VALUES ('fa', 'ପର୍ସିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('fy', 'ପଶ୍ଚିମ ଫ୍ରିସିୟନ୍');
INSERT INTO "country" ("id", "name") VALUES ('pag', 'ପାଙ୍ଗାସିନିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('pap', 'ପାପିୟାମିଣ୍ଟୋ');
INSERT INTO "country" ("id", "name") VALUES ('paa', 'ପାପୁଆନ୍ ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('pam', 'ପାମ୍ପାଙ୍ଗା');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hant', 'ପାରମ୍ପରିକ ଚାଇନୀଜ୍');
INSERT INTO "country" ("id", "name") VALUES ('nwc', 'ପାରମ୍ପରିକ ନେୱାରୀ');
INSERT INTO "country" ("id", "name") VALUES ('pau', 'ପାଲାଉଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('pi', 'ପାଲି');
INSERT INTO "country" ("id", "name") VALUES ('ps', 'ପାସ୍ତୋ');
INSERT INTO "country" ("id", "name") VALUES ('pal', 'ପାହ୍ଲାଭି');
INSERT INTO "country" ("id", "name") VALUES ('ang', 'ପୁରୁଣା ଇଁରାଜୀ');
INSERT INTO "country" ("id", "name") VALUES ('sga', 'ପୁରୁଣା ଇରିଶ୍');
INSERT INTO "country" ("id", "name") VALUES ('non', 'ପୁରୁଣା ନର୍ସ');
INSERT INTO "country" ("id", "name") VALUES ('peo', 'ପୁରୁଣା ପର୍ସିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('pro', 'ପୁରୁଣା ପ୍ରେଭେନେସିଆଲ୍');
INSERT INTO "country" ("id", "name") VALUES ('fro', 'ପୁରୁଣା ଫ୍ରେଞ୍ଚ');
INSERT INTO "country" ("id", "name") VALUES ('goh', 'ପୁରୁଣା ହାଇ ଜର୍ମାନ୍');
INSERT INTO "country" ("id", "name") VALUES ('frs', 'ପୂର୍ବ ଫ୍ରିସିୟାନ୍');
INSERT INTO "country" ("id", "name") VALUES ('pl', 'ପୋଲିଶ୍');
INSERT INTO "country" ("id", "name") VALUES ('pon', 'ପୋହପିଏନ୍');
INSERT INTO "country" ("id", "name") VALUES ('pra', 'ପ୍ରାକୃତ ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('egy', 'ପ୍ରାଚୀନ୍ ମିଶିରି');
INSERT INTO "country" ("id", "name") VALUES ('grc', 'ପ୍ରାଚୀନ୍ ୟୁନାନୀ');
INSERT INTO "country" ("id", "name") VALUES ('fon', 'ଫନ୍');
INSERT INTO "country" ("id", "name") VALUES ('fan', 'ଫାଙ୍ଗ');
INSERT INTO "country" ("id", "name") VALUES ('fat', 'ଫାଣ୍ଟି');
INSERT INTO "country" ("id", "name") VALUES ('fiu', 'ଫାଣ୍ଟିଫିନ୍ନୋ-ଉଗ୍ରୀଆନ୍ ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('fo', 'ଫାରୋଏସେ');
INSERT INTO "country" ("id", "name") VALUES ('fj', 'ଫିଜି');
INSERT INTO "country" ("id", "name") VALUES ('fi', 'ଫିନ୍ନିସ୍');
INSERT INTO "country" ("id", "name") VALUES ('phi', 'ଫିଲିପାଇନ୍ ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('fil', 'ଫିଲିପିନୋ');
INSERT INTO "country" ("id", "name") VALUES ('ff', 'ଫୁଲାହ');
INSERT INTO "country" ("id", "name") VALUES ('phn', 'ଫୋନେସିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('fur', 'ଫ୍ରିୟୁଲୀୟାନ୍');
INSERT INTO "country" ("id", "name") VALUES ('fr', 'ଫ୍ରେଞ୍ଚ');
INSERT INTO "country" ("id", "name") VALUES ('cpf', 'ଫ୍ରେଞ୍ଚ ଆଧାରିତ କ୍ରେଓଲ୍ କିମ୍ବା ପିଜିନ୍');
INSERT INTO "country" ("id", "name") VALUES ('nl_BE', 'ଫ୍ଲେମିଶ୍');
INSERT INTO "country" ("id", "name") VALUES ('bn', 'ବଙ୍ଗାଳୀ');
INSERT INTO "country" ("id", "name") VALUES ('bai', 'ବମିଲେକେ ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('my', 'ବର୍ମୀଜ୍');
INSERT INTO "country" ("id", "name") VALUES ('ba', 'ବଶଖିର୍');
INSERT INTO "country" ("id", "name") VALUES ('btk', 'ବାଟାକ୍');
INSERT INTO "country" ("id", "name") VALUES ('bnt', 'ବାଣ୍ଟୁ');
INSERT INTO "country" ("id", "name") VALUES ('bad', 'ବାନ୍ଦା');
INSERT INTO "country" ("id", "name") VALUES ('bm', 'ବାମ୍ବାରା');
INSERT INTO "country" ("id", "name") VALUES ('bat', 'ବାଲାଟିକ୍ ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('ban', 'ବାଲିନୀଜ୍');
INSERT INTO "country" ("id", "name") VALUES ('bal', 'ବାଲୁଚି');
INSERT INTO "country" ("id", "name") VALUES ('bas', 'ବାସା');
INSERT INTO "country" ("id", "name") VALUES ('eu', 'ବାସ୍କ୍ୱି');
INSERT INTO "country" ("id", "name") VALUES ('bik', 'ବିକୋଲ୍');
INSERT INTO "country" ("id", "name") VALUES ('bla', 'ବିକ୍ସିକା');
INSERT INTO "country" ("id", "name") VALUES ('bin', 'ବିନି');
INSERT INTO "country" ("id", "name") VALUES ('mis', 'ବିବିଧ ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('mul', 'ବିବିଧ ଭାଷାମାନ');
INSERT INTO "country" ("id", "name") VALUES ('bi', 'ବିସଲାମା');
INSERT INTO "country" ("id", "name") VALUES ('bh', 'ବିହାରୀ');
INSERT INTO "country" ("id", "name") VALUES ('bug', 'ବୁଗୀନୀଜ୍');
INSERT INTO "country" ("id", "name") VALUES ('bua', 'ବୁରିଆଟ୍');
INSERT INTO "country" ("id", "name") VALUES ('bg', 'ବୁଲଗେରିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('bej', 'ବେଜା');
INSERT INTO "country" ("id", "name") VALUES ('bem', 'ବେମ୍ବା');
INSERT INTO "country" ("id", "name") VALUES ('ber', 'ବେରବର୍');
INSERT INTO "country" ("id", "name") VALUES ('be', 'ବେଲାରୁଷିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('vo', 'ବୋଲାପୁକ');
INSERT INTO "country" ("id", "name") VALUES ('pt_BR', 'ବ୍ରାଜିଲିଆନ୍ ପର୍ତ୍ତୁଗୀଜ୍');
INSERT INTO "country" ("id", "name") VALUES ('bra', 'ବ୍ରାଜ୍');
INSERT INTO "country" ("id", "name") VALUES ('en_GB', 'ବ୍ରିଟିଶ୍ ଇଁରାଜୀ');
INSERT INTO "country" ("id", "name") VALUES ('br', 'ବ୍ରେଟନ୍');
INSERT INTO "country" ("id", "name") VALUES ('byn', 'ବ୍ଲିନ୍');
INSERT INTO "country" ("id", "name") VALUES ('zbl', 'ବ୍ଲିସିମ୍ବଲସ୍');
INSERT INTO "country" ("id", "name") VALUES ('vai', 'ଭାଇ');
INSERT INTO "country" ("id", "name") VALUES ('vi', 'ଭିଏତନାମିଜ୍');
INSERT INTO "country" ("id", "name") VALUES ('dz', 'ଭୂଟାନୀ');
INSERT INTO "country" ("id", "name") VALUES ('ve', 'ଭେଣ୍ଡା');
INSERT INTO "country" ("id", "name") VALUES ('bho', 'ଭୋଜପୁରୀ');
INSERT INTO "country" ("id", "name") VALUES ('vot', 'ଭୋଟିକ୍');
INSERT INTO "country" ("id", "name") VALUES ('mkh', 'ମଁନ୍-ଖ୍ମେର୍ ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('mak', 'ମକାସର୍');
INSERT INTO "country" ("id", "name") VALUES ('lol', 'ମଙ୍ଗୋ');
INSERT INTO "country" ("id", "name") VALUES ('mn', 'ମଙ୍ଗୋଲିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('mni', 'ମଣିପୁରୀ');
INSERT INTO "country" ("id", "name") VALUES ('cai', 'ମଧ୍ୟ ଆମେରିକା ଭାରତୀୟ ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('enm', 'ମଧ୍ୟ ଇଁରାଜୀ');
INSERT INTO "country" ("id", "name") VALUES ('mga', 'ମଧ୍ୟ ଇରିଶ୍');
INSERT INTO "country" ("id", "name") VALUES ('dum', 'ମଧ୍ୟ ପର୍ତ୍ତୁଗାଲୀ');
INSERT INTO "country" ("id", "name") VALUES ('frm', 'ମଧ୍ୟ ଫ୍ରେଞ୍ଚ');
INSERT INTO "country" ("id", "name") VALUES ('mno', 'ମନୋବୋ ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('mdr', 'ମନ୍ଦାର');
INSERT INTO "country" ("id", "name") VALUES ('mr', 'ମରାଠୀ');
INSERT INTO "country" ("id", "name") VALUES ('gv', 'ମାଁକ୍ସ');
INSERT INTO "country" ("id", "name") VALUES ('mi', 'ମାଓରୀ');
INSERT INTO "country" ("id", "name") VALUES ('mk', 'ମାକଡୋନିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('mag', 'ମାଗାହୀ');
INSERT INTO "country" ("id", "name") VALUES ('mnc', 'ମାଞ୍ଚୁ');
INSERT INTO "country" ("id", "name") VALUES ('man', 'ମାଣ୍ଡିଙ୍ଗୋ');
INSERT INTO "country" ("id", "name") VALUES ('mad', 'ମାଦୁରୀସ୍');
INSERT INTO "country" ("id", "name") VALUES ('chm', 'ମାରୀ');
INSERT INTO "country" ("id", "name") VALUES ('mh', 'ମାର୍ଶାଲୀଜ୍');
INSERT INTO "country" ("id", "name") VALUES ('mwr', 'ମାରୱାରୀ');
INSERT INTO "country" ("id", "name") VALUES ('mt', 'ମାଲଟୀଜ୍');
INSERT INTO "country" ("id", "name") VALUES ('mg', 'ମାଲାଗାସୀ');
INSERT INTO "country" ("id", "name") VALUES ('ml', 'ମାଲାୟଲମ୍');
INSERT INTO "country" ("id", "name") VALUES ('ms', 'ମାଲୟ');
INSERT INTO "country" ("id", "name") VALUES ('mas', 'ମାସାଇ');
INSERT INTO "country" ("id", "name") VALUES ('myn', 'ମାୟା ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('mic', 'ମିକମୌକ୍');
INSERT INTO "country" ("id", "name") VALUES ('gmh', 'ମିଡିଲ୍ ହାଇ ଜର୍ମାନ୍');
INSERT INTO "country" ("id", "name") VALUES ('min', 'ମିନାଙ୍ଗାବାଉ');
INSERT INTO "country" ("id", "name") VALUES ('mwl', 'ମିରାଣ୍ଡିଜ୍');
INSERT INTO "country" ("id", "name") VALUES ('mun', 'ମୁଣ୍ଡା ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('root', 'ମୂଳ');
INSERT INTO "country" ("id", "name") VALUES ('men', 'ମେଣ୍ଡେ');
INSERT INTO "country" ("id", "name") VALUES ('mai', 'ମୈଥିଳୀ');
INSERT INTO "country" ("id", "name") VALUES ('mdf', 'ମୋକ୍ଷ');
INSERT INTO "country" ("id", "name") VALUES ('mo', 'ମୋଲଡୋଭିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('mos', 'ମୋସି');
INSERT INTO "country" ("id", "name") VALUES ('moh', 'ମୋହୌକ');
INSERT INTO "country" ("id", "name") VALUES ('ru', 'ରଷିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('raj', 'ରାଜସ୍ଥାନୀ');
INSERT INTO "country" ("id", "name") VALUES ('rap', 'ରାପାନୁଇ');
INSERT INTO "country" ("id", "name") VALUES ('rar', 'ରାରୋତୋଙ୍ଗନ୍');
INSERT INTO "country" ("id", "name") VALUES ('rn', 'ରୁଣ୍ଡି');
INSERT INTO "country" ("id", "name") VALUES ('rm', 'ରେହେଟୋ-ରୋମାନ୍ସ');
INSERT INTO "country" ("id", "name") VALUES ('rom', 'ରୋମାନି');
INSERT INTO "country" ("id", "name") VALUES ('ro', 'ରୋମାନିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('roa', 'ରୋମାନ୍ସ ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('lb', 'ଲକ୍ସେମବର୍ଗିସ୍');
INSERT INTO "country" ("id", "name") VALUES ('lo', 'ଲାଓ');
INSERT INTO "country" ("id", "name") VALUES ('lv', 'ଲାଟଭିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('la', 'ଲାଟିନ୍');
INSERT INTO "country" ("id", "name") VALUES ('es_419', 'ଲାଟିନ୍ ଆମେରିକାନ୍ ସ୍ପାନିଶ୍');
INSERT INTO "country" ("id", "name") VALUES ('lad', 'ଲାଦିନୋ');
INSERT INTO "country" ("id", "name") VALUES ('lam', 'ଲାମ୍ବା');
INSERT INTO "country" ("id", "name") VALUES ('lah', 'ଲାହାଣ୍ଡା');
INSERT INTO "country" ("id", "name") VALUES ('ln', 'ଲିଙ୍ଗାଲା');
INSERT INTO "country" ("id", "name") VALUES ('lt', 'ଲିଥୁଆନିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('li', 'ଲିମ୍ବୁର୍ଗିସ୍');
INSERT INTO "country" ("id", "name") VALUES ('lui', 'ଲୁଇସେନୋ');
INSERT INTO "country" ("id", "name") VALUES ('luo', 'ଲୁଓ');
INSERT INTO "country" ("id", "name") VALUES ('lun', 'ଲୁଣ୍ଡା');
INSERT INTO "country" ("id", "name") VALUES ('lua', 'ଲୁବା-ଲୁଲୁଆ');
INSERT INTO "country" ("id", "name") VALUES ('smj', 'ଲୁଲେ ସାମି');
INSERT INTO "country" ("id", "name") VALUES ('lus', 'ଲୁସାଉ');
INSERT INTO "country" ("id", "name") VALUES ('lez', 'ଲେଜଗିୟାନ୍');
INSERT INTO "country" ("id", "name") VALUES ('pt_PT', 'ଲେବେରିଆନ୍ ପର୍ତ୍ତୁଗୀଜ୍');
INSERT INTO "country" ("id", "name") VALUES ('es_ES', 'ଲେବେରିଆନ୍ ସ୍ପାନିଶ୍');
INSERT INTO "country" ("id", "name") VALUES ('nds', 'ଲୋ ଜର୍ମାନ୍');
INSERT INTO "country" ("id", "name") VALUES ('jbo', 'ଲୋଜବାନ୍');
INSERT INTO "country" ("id", "name") VALUES ('loz', 'ଲୋଜି');
INSERT INTO "country" ("id", "name") VALUES ('lu', 'ଲ୍ୟୁବା-କାଟାଙ୍ଗା');
INSERT INTO "country" ("id", "name") VALUES ('sal', 'ଶଲୀସନ୍ ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('shn', 'ଶାନ୍');
INSERT INTO "country" ("id", "name") VALUES ('srn', 'ଶାରାନା ଟୋଙ୍ଗୋ');
INSERT INTO "country" ("id", "name") VALUES ('sus', 'ଶୁଶୁ');
INSERT INTO "country" ("id", "name") VALUES ('srr', 'ଶେରେର୍');
INSERT INTO "country" ("id", "name") VALUES ('sn', 'ଶୋନା');
INSERT INTO "country" ("id", "name") VALUES ('sa', 'ସଂସ୍କୃତ');
INSERT INTO "country" ("id", "name") VALUES ('sad', 'ସଣ୍ଡାୱେ');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hans', 'ସରଳିକରଣ ଚାଇନୀଜ୍');
INSERT INTO "country" ("id", "name") VALUES ('sc', 'ସର୍ଦିନିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('sr', 'ସର୍ବିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('wen', 'ସର୍ବିଆନ୍ ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('sh', 'ସର୍ବୋ-କ୍ରୋଆଟିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('sgn', 'ସାଙ୍କେତିକ ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('sg', 'ସାଙ୍ଗୋ');
INSERT INTO "country" ("id", "name") VALUES ('sat', 'ସାନ୍ତାଳି');
INSERT INTO "country" ("id", "name") VALUES ('smi', 'ସାମି ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('sm', 'ସାମୋଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('sam', 'ସାମୌରିଟନ୍ ଆରମାଇକ୍');
INSERT INTO "country" ("id", "name") VALUES ('sla', 'ସାଲ୍ଭିକ୍ ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('sas', 'ସାସାକ୍');
INSERT INTO "country" ("id", "name") VALUES ('si', 'ସିଂହଳ');
INSERT INTO "country" ("id", "name") VALUES ('sio', 'ସିଓନ୍ ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('ii', 'ସିଚୁଆନ୍ ୟୀ');
INSERT INTO "country" ("id", "name") VALUES ('sid', 'ସିଦାମୋ');
INSERT INTO "country" ("id", "name") VALUES ('sit', 'ସିନୋ-ତିବ୍ବେତାନ୍ ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('sd', 'ସିନ୍ଧୀ');
INSERT INTO "country" ("id", "name") VALUES ('syr', 'ସିରିକ୍');
INSERT INTO "country" ("id", "name") VALUES ('scn', 'ସିଶିଲିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('ceb', 'ସୀବୁଆନୋ');
INSERT INTO "country" ("id", "name") VALUES ('suk', 'ସୁକୁମା');
INSERT INTO "country" ("id", "name") VALUES ('su', 'ସୁଦାନୀଜ୍');
INSERT INTO "country" ("id", "name") VALUES ('sux', 'ସୁମେରିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('sem', 'ସେମିଟିକ୍ ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('sel', 'ସେଲ୍କପ୍');
INSERT INTO "country" ("id", "name") VALUES ('st', 'ସେସୋଥୋ');
INSERT INTO "country" ("id", "name") VALUES ('tn', 'ସେସ୍ବାନା');
INSERT INTO "country" ("id", "name") VALUES ('ts', 'ସୋଂଗା');
INSERT INTO "country" ("id", "name") VALUES ('sog', 'ସୋଗଡିଏନ୍');
INSERT INTO "country" ("id", "name") VALUES ('son', 'ସୋଙ୍ଘାଇ');
INSERT INTO "country" ("id", "name") VALUES ('snk', 'ସୋନିଙ୍କେ');
INSERT INTO "country" ("id", "name") VALUES ('so', 'ସୋମାଲିଆ');
INSERT INTO "country" ("id", "name") VALUES ('sco', 'ସ୍କଟସ୍');
INSERT INTO "country" ("id", "name") VALUES ('gd', 'ସ୍କଟିସ୍ ଗାଏଲିକ୍');
INSERT INTO "country" ("id", "name") VALUES ('sms', 'ସ୍କୋଲ୍ଟ ସାମୀ');
INSERT INTO "country" ("id", "name") VALUES ('es', 'ସ୍ପାନିସ୍');
INSERT INTO "country" ("id", "name") VALUES ('ss', 'ସ୍ବାତୀ');
INSERT INTO "country" ("id", "name") VALUES ('gwi', 'ସ୍ବିଚ୍ ଇନ୍');
INSERT INTO "country" ("id", "name") VALUES ('gsw', 'ସ୍ବିସ୍ ଜର୍ମାନ୍');
INSERT INTO "country" ("id", "name") VALUES ('fr_CH', 'ସ୍ବିସ୍ ଫ୍ରେଞ୍ଚ୍');
INSERT INTO "country" ("id", "name") VALUES ('de_CH', 'ସ୍ବିସ୍ ହାଇ ଜର୍ମାନ୍');
INSERT INTO "country" ("id", "name") VALUES ('den', 'ସ୍ଲେଭ୍');
INSERT INTO "country" ("id", "name") VALUES ('sk', 'ସ୍ଲୋଭାକ୍');
INSERT INTO "country" ("id", "name") VALUES ('sl', 'ସ୍ଲୋଭେନିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('sw', 'ସ୍ୱାହିଲ୍');
INSERT INTO "country" ("id", "name") VALUES ('sv', 'ସ୍ୱେଡିସ୍');
INSERT INTO "country" ("id", "name") VALUES ('hmn', 'ହଁଙ୍ଗ');
INSERT INTO "country" ("id", "name") VALUES ('hu', 'ହଙ୍ଗେରିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('hai', 'ହାଇଡା');
INSERT INTO "country" ("id", "name") VALUES ('haw', 'ହାୱାଇନ୍');
INSERT INTO "country" ("id", "name") VALUES ('hit', 'ହିତୀତେ');
INSERT INTO "country" ("id", "name") VALUES ('hi', 'ହିନ୍ଦୀ');
INSERT INTO "country" ("id", "name") VALUES ('him', 'ହିମାଚଳୀ');
INSERT INTO "country" ("id", "name") VALUES ('ho', 'ହିରି ମୋଟୁ');
INSERT INTO "country" ("id", "name") VALUES ('hil', 'ହିଲିଗୈନନ୍');
INSERT INTO "country" ("id", "name") VALUES ('hup', 'ହୁପା');
INSERT INTO "country" ("id", "name") VALUES ('he', 'ହେବ୍ର୍ୟୁ');
INSERT INTO "country" ("id", "name") VALUES ('hz', 'ହେରେରୋ');
INSERT INTO "country" ("id", "name") VALUES ('ht', 'ହୈତାୟିନ୍');
INSERT INTO "country" ("id", "name") VALUES ('ha', 'ହୌସା');
INSERT INTO "country" ("id", "name") VALUES ('yao', 'ୟାଓ');
INSERT INTO "country" ("id", "name") VALUES ('sah', 'ୟାକୁଟ୍');
INSERT INTO "country" ("id", "name") VALUES ('yap', 'ୟାପୀସ୍');
INSERT INTO "country" ("id", "name") VALUES ('yi', 'ୟିଡିସ୍');
INSERT INTO "country" ("id", "name") VALUES ('en_US', 'ୟୁ.ଏସ୍. ଇଁରାଜୀ');
INSERT INTO "country" ("id", "name") VALUES ('uk', 'ୟୁକ୍ରାନିଆନ୍');
INSERT INTO "country" ("id", "name") VALUES ('uga', 'ୟୁଗୋରଟିକ୍');
INSERT INTO "country" ("id", "name") VALUES ('ug', 'ୟୁଘୁର୍');
INSERT INTO "country" ("id", "name") VALUES ('ypk', 'ୟୁପିକ୍ ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('yo', 'ୟୋରୁବା');
INSERT INTO "country" ("id", "name") VALUES ('wak', 'ୱାକଶନ୍ ଭାଷା');
INSERT INTO "country" ("id", "name") VALUES ('war', 'ୱାରୈ');
INSERT INTO "country" ("id", "name") VALUES ('wal', 'ୱାଲମୋ');
INSERT INTO "country" ("id", "name") VALUES ('wa', 'ୱାଲୁନ୍');
INSERT INTO "country" ("id", "name") VALUES ('was', 'ୱାସୋ');
INSERT INTO "country" ("id", "name") VALUES ('cy', 'ୱେଲ୍ସ');
INSERT INTO "country" ("id", "name") VALUES ('wo', 'ୱୋଲଫ୍');
INSERT INTO "country" ("id", "name") VALUES ('osa', 'ୱୌସେଜ୍');
