CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('gaa', '가어');
INSERT INTO [country] ([id], [name]) VALUES ('gay', '가요어');
INSERT INTO [country] ([id], [name]) VALUES ('lg', '간다어');
INSERT INTO [country] ([id], [name]) VALUES ('gl', '갈리시아어');
INSERT INTO [country] ([id], [name]) VALUES ('grb', '게르보어');
INSERT INTO [country] ([id], [name]) VALUES ('gez', '게이즈어');
INSERT INTO [country] ([id], [name]) VALUES ('und', '결정되지않음');
INSERT INTO [country] ([id], [name]) VALUES ('goh', '고대 고지 독일어');
INSERT INTO [country] ([id], [name]) VALUES ('ang', '고대 영어');
INSERT INTO [country] ([id], [name]) VALUES ('peo', '고대 페르시아어');
INSERT INTO [country] ([id], [name]) VALUES ('fro', '고대 프랑스어');
INSERT INTO [country] ([id], [name]) VALUES ('pro', '고대 프로방스어');
INSERT INTO [country] ([id], [name]) VALUES ('gor', '고론탈로어');
INSERT INTO [country] ([id], [name]) VALUES ('de_CH', '고지 독일어 (스위스)');
INSERT INTO [country] ([id], [name]) VALUES ('hsb', '고지 소르비아어');
INSERT INTO [country] ([id], [name]) VALUES ('got', '고트어');
INSERT INTO [country] ([id], [name]) VALUES ('gon', '곤디어');
INSERT INTO [country] ([id], [name]) VALUES ('gn', '과라니어');
INSERT INTO [country] ([id], [name]) VALUES ('cu', '교회 슬라브어');
INSERT INTO [country] ([id], [name]) VALUES ('gu', '구자라트어');
INSERT INTO [country] ([id], [name]) VALUES ('ka', '그루지야어');
INSERT INTO [country] ([id], [name]) VALUES ('el', '그리스어');
INSERT INTO [country] ([id], [name]) VALUES ('grc', '그리스어, 고대 (1453년 까지)');
INSERT INTO [country] ([id], [name]) VALUES ('kl', '그린란드어');
INSERT INTO [country] ([id], [name]) VALUES ('gba', '그바야어');
INSERT INTO [country] ([id], [name]) VALUES ('gwi', '그위친어');
INSERT INTO [country] ([id], [name]) VALUES ('art', '기계어 (기타)');
INSERT INTO [country] ([id], [name]) VALUES ('mis', '기타 언어');
INSERT INTO [country] ([id], [name]) VALUES ('nv', '나바호어');
INSERT INTO [country] ([id], [name]) VALUES ('na', '나우루어');
INSERT INTO [country] ([id], [name]) VALUES ('nah', '나우아틀어');
INSERT INTO [country] ([id], [name]) VALUES ('nap', '나폴리어');
INSERT INTO [country] ([id], [name]) VALUES ('map', '남도어');
INSERT INTO [country] ([id], [name]) VALUES ('sma', '남부 사미어');
INSERT INTO [country] ([id], [name]) VALUES ('alt', '남부 알타이어');
INSERT INTO [country] ([id], [name]) VALUES ('af', '남아공 공용어');
INSERT INTO [country] ([id], [name]) VALUES ('sai', '남아메리카 인디언어 (기타)');
INSERT INTO [country] ([id], [name]) VALUES ('nl', '네덜란드어');
INSERT INTO [country] ([id], [name]) VALUES ('new', '네와르어');
INSERT INTO [country] ([id], [name]) VALUES ('nwc', '네와르어 (고전)');
INSERT INTO [country] ([id], [name]) VALUES ('ne', '네팔어');
INSERT INTO [country] ([id], [name]) VALUES ('nog', '노가이어');
INSERT INTO [country] ([id], [name]) VALUES ('non', '노르웨이, 고대');
INSERT INTO [country] ([id], [name]) VALUES ('no', '노르웨이어');
INSERT INTO [country] ([id], [name]) VALUES ('nn', '노르웨이어(니노르스크)');
INSERT INTO [country] ([id], [name]) VALUES ('nub', '누비안어');
INSERT INTO [country] ([id], [name]) VALUES ('nyo', '뉴로어');
INSERT INTO [country] ([id], [name]) VALUES ('ng', '느동가어');
INSERT INTO [country] ([id], [name]) VALUES ('nzi', '느지마어');
INSERT INTO [country] ([id], [name]) VALUES ('ssa', '니로-사하람어 (기타)');
INSERT INTO [country] ([id], [name]) VALUES ('nia', '니아스어');
INSERT INTO [country] ([id], [name]) VALUES ('ny', '니안자어; 치츄어; 츄어');
INSERT INTO [country] ([id], [name]) VALUES ('nyn', '니안콜어');
INSERT INTO [country] ([id], [name]) VALUES ('nym', '니암웨지어');
INSERT INTO [country] ([id], [name]) VALUES ('niu', '니웨언어');
INSERT INTO [country] ([id], [name]) VALUES ('nic', '니제르 - 코르도파니아어 (기타)');
INSERT INTO [country] ([id], [name]) VALUES ('dar', '다르그와어');
INSERT INTO [country] ([id], [name]) VALUES ('day', '다야크어');
INSERT INTO [country] ([id], [name]) VALUES ('mul', '다중 언어');
INSERT INTO [country] ([id], [name]) VALUES ('dak', '다코타어');
INSERT INTO [country] ([id], [name]) VALUES ('da', '덴마크어');
INSERT INTO [country] ([id], [name]) VALUES ('del', '델라웨어어');
INSERT INTO [country] ([id], [name]) VALUES ('dgr', '도그리브어');
INSERT INTO [country] ([id], [name]) VALUES ('doi', '도그리어');
INSERT INTO [country] ([id], [name]) VALUES ('de', '독일어');
INSERT INTO [country] ([id], [name]) VALUES ('gem', '독일어 (기타)');
INSERT INTO [country] ([id], [name]) VALUES ('gsw', '독일어 (스위스)');
INSERT INTO [country] ([id], [name]) VALUES ('de_AT', '독일어 (오스트리아)');
INSERT INTO [country] ([id], [name]) VALUES ('frs', '동부 프리슬란드어');
INSERT INTO [country] ([id], [name]) VALUES ('dra', '드라비다어 (기타)');
INSERT INTO [country] ([id], [name]) VALUES ('dua', '드와라어');
INSERT INTO [country] ([id], [name]) VALUES ('dyu', '드율라어');
INSERT INTO [country] ([id], [name]) VALUES ('dv', '디베히어');
INSERT INTO [country] ([id], [name]) VALUES ('din', '딩카어');
INSERT INTO [country] ([id], [name]) VALUES ('lad', '라디노어');
INSERT INTO [country] ([id], [name]) VALUES ('rar', '라로통가어');
INSERT INTO [country] ([id], [name]) VALUES ('lo', '라오어');
INSERT INTO [country] ([id], [name]) VALUES ('raj', '라자스탄어');
INSERT INTO [country] ([id], [name]) VALUES ('lv', '라트비아어');
INSERT INTO [country] ([id], [name]) VALUES ('la', '라틴어');
INSERT INTO [country] ([id], [name]) VALUES ('rap', '라파뉴이');
INSERT INTO [country] ([id], [name]) VALUES ('lah', '라한다어');
INSERT INTO [country] ([id], [name]) VALUES ('lam', '람바어');
INSERT INTO [country] ([id], [name]) VALUES ('ru', '러시아어');
INSERT INTO [country] ([id], [name]) VALUES ('lez', '레즈기안어');
INSERT INTO [country] ([id], [name]) VALUES ('rm', '레토로만어');
INSERT INTO [country] ([id], [name]) VALUES ('roa', '로망스어 (기타)');
INSERT INTO [country] ([id], [name]) VALUES ('jbo', '로반어');
INSERT INTO [country] ([id], [name]) VALUES ('loz', '로지어');
INSERT INTO [country] ([id], [name]) VALUES ('ro', '루마니아어');
INSERT INTO [country] ([id], [name]) VALUES ('lua', '루바-룰루아어');
INSERT INTO [country] ([id], [name]) VALUES ('lu', '루바-카탄가어');
INSERT INTO [country] ([id], [name]) VALUES ('lus', '루샤이어');
INSERT INTO [country] ([id], [name]) VALUES ('luo', '루오어');
INSERT INTO [country] ([id], [name]) VALUES ('lui', '루이세노어');
INSERT INTO [country] ([id], [name]) VALUES ('lb', '룩셈부르크어');
INSERT INTO [country] ([id], [name]) VALUES ('lun', '룬다어');
INSERT INTO [country] ([id], [name]) VALUES ('rn', '룬디어');
INSERT INTO [country] ([id], [name]) VALUES ('smj', '룰레 사미어');
INSERT INTO [country] ([id], [name]) VALUES ('rw', '르완다어');
INSERT INTO [country] ([id], [name]) VALUES ('lt', '리투아니아어');
INSERT INTO [country] ([id], [name]) VALUES ('li', '림버거어');
INSERT INTO [country] ([id], [name]) VALUES ('ln', '링갈라어');
INSERT INTO [country] ([id], [name]) VALUES ('mag', '마가히');
INSERT INTO [country] ([id], [name]) VALUES ('mno', '마노보어');
INSERT INTO [country] ([id], [name]) VALUES ('mni', '마니푸리어');
INSERT INTO [country] ([id], [name]) VALUES ('mg', '마다가스카르어');
INSERT INTO [country] ([id], [name]) VALUES ('mad', '마두라어');
INSERT INTO [country] ([id], [name]) VALUES ('mr', '마라티어');
INSERT INTO [country] ([id], [name]) VALUES ('mwr', '마르와리어');
INSERT INTO [country] ([id], [name]) VALUES ('chm', '마리어');
INSERT INTO [country] ([id], [name]) VALUES ('mas', '마사이어');
INSERT INTO [country] ([id], [name]) VALUES ('mh', '마셜제도어');
INSERT INTO [country] ([id], [name]) VALUES ('myn', '마야어');
INSERT INTO [country] ([id], [name]) VALUES ('mi', '마오리어');
INSERT INTO [country] ([id], [name]) VALUES ('mai', '마이틸리');
INSERT INTO [country] ([id], [name]) VALUES ('mak', '마카사어');
INSERT INTO [country] ([id], [name]) VALUES ('mk', '마케도니아어');
INSERT INTO [country] ([id], [name]) VALUES ('mdr', '만다르어');
INSERT INTO [country] ([id], [name]) VALUES ('man', '만딩고어');
INSERT INTO [country] ([id], [name]) VALUES ('mnc', '만주어');
INSERT INTO [country] ([id], [name]) VALUES ('ml', '말라얄람어');
INSERT INTO [country] ([id], [name]) VALUES ('ms', '말레이어');
INSERT INTO [country] ([id], [name]) VALUES ('gv', '맹크스어');
INSERT INTO [country] ([id], [name]) VALUES ('men', '멘데어');
INSERT INTO [country] ([id], [name]) VALUES ('mos', '모시어');
INSERT INTO [country] ([id], [name]) VALUES ('mdf', '모크샤어');
INSERT INTO [country] ([id], [name]) VALUES ('moh', '모호크어');
INSERT INTO [country] ([id], [name]) VALUES ('mkh', '몬크메르어 (기타)');
INSERT INTO [country] ([id], [name]) VALUES ('mo', '몰도바어');
INSERT INTO [country] ([id], [name]) VALUES ('mt', '몰타어');
INSERT INTO [country] ([id], [name]) VALUES ('mn', '몽고어');
INSERT INTO [country] ([id], [name]) VALUES ('lol', '몽구어');
INSERT INTO [country] ([id], [name]) VALUES ('mun', '문다어');
INSERT INTO [country] ([id], [name]) VALUES ('min', '미낭카바우');
INSERT INTO [country] ([id], [name]) VALUES ('mwl', '미란데어');
INSERT INTO [country] ([id], [name]) VALUES ('mic', '미크맥어');
INSERT INTO [country] ([id], [name]) VALUES ('bai', '바밀레케어족');
INSERT INTO [country] ([id], [name]) VALUES ('bas', '바사어');
INSERT INTO [country] ([id], [name]) VALUES ('ba', '바슈키르어');
INSERT INTO [country] ([id], [name]) VALUES ('eu', '바스크어');
INSERT INTO [country] ([id], [name]) VALUES ('vai', '바이어');
INSERT INTO [country] ([id], [name]) VALUES ('btk', '바타크어');
INSERT INTO [country] ([id], [name]) VALUES ('bad', '반다어');
INSERT INTO [country] ([id], [name]) VALUES ('bnt', '반투어');
INSERT INTO [country] ([id], [name]) VALUES ('bal', '발루치어');
INSERT INTO [country] ([id], [name]) VALUES ('ban', '발리어');
INSERT INTO [country] ([id], [name]) VALUES ('bat', '발트어 (기타)');
INSERT INTO [country] ([id], [name]) VALUES ('bm', '밤바라어');
INSERT INTO [country] ([id], [name]) VALUES ('my', '버마어');
INSERT INTO [country] ([id], [name]) VALUES ('ber', '베르베르어');
INSERT INTO [country] ([id], [name]) VALUES ('bej', '베자어');
INSERT INTO [country] ([id], [name]) VALUES ('vi', '베트남어');
INSERT INTO [country] ([id], [name]) VALUES ('ve', '벤다어');
INSERT INTO [country] ([id], [name]) VALUES ('be', '벨로루시어');
INSERT INTO [country] ([id], [name]) VALUES ('bem', '벰바어');
INSERT INTO [country] ([id], [name]) VALUES ('bn', '벵골어');
INSERT INTO [country] ([id], [name]) VALUES ('bs', '보스니아어');
INSERT INTO [country] ([id], [name]) VALUES ('nb', '보크말 노르웨이어');
INSERT INTO [country] ([id], [name]) VALUES ('vot', '보틱어');
INSERT INTO [country] ([id], [name]) VALUES ('vo', '볼라퓌크어');
INSERT INTO [country] ([id], [name]) VALUES ('bug', '부기어');
INSERT INTO [country] ([id], [name]) VALUES ('bua', '부리아타');
INSERT INTO [country] ([id], [name]) VALUES ('se', '북부 사미어');
INSERT INTO [country] ([id], [name]) VALUES ('frr', '북부 프리슬란드어');
INSERT INTO [country] ([id], [name]) VALUES ('nai', '북아메리카 인디언어 (기타)');
INSERT INTO [country] ([id], [name]) VALUES ('bg', '불가리아어');
INSERT INTO [country] ([id], [name]) VALUES ('bra', '브라지어');
INSERT INTO [country] ([id], [name]) VALUES ('br', '브르타뉴어');
INSERT INTO [country] ([id], [name]) VALUES ('byn', '브린어');
INSERT INTO [country] ([id], [name]) VALUES ('zbl', '블리스 심볼');
INSERT INTO [country] ([id], [name]) VALUES ('bin', '비니어');
INSERT INTO [country] ([id], [name]) VALUES ('bi', '비슬라마어');
INSERT INTO [country] ([id], [name]) VALUES ('bik', '비콜어');
INSERT INTO [country] ([id], [name]) VALUES ('bh', '비하르어');
INSERT INTO [country] ([id], [name]) VALUES ('sc', '사르디니아어');
INSERT INTO [country] ([id], [name]) VALUES ('sam', '사마리아 아랍어');
INSERT INTO [country] ([id], [name]) VALUES ('sm', '사모아어');
INSERT INTO [country] ([id], [name]) VALUES ('smi', '사미어 (기타)');
INSERT INTO [country] ([id], [name]) VALUES ('sas', '사사크어');
INSERT INTO [country] ([id], [name]) VALUES ('zap', '사포테크어');
INSERT INTO [country] ([id], [name]) VALUES ('sg', '산고어');
INSERT INTO [country] ([id], [name]) VALUES ('sad', '산다웨어');
INSERT INTO [country] ([id], [name]) VALUES ('sa', '산스크리트어');
INSERT INTO [country] ([id], [name]) VALUES ('sat', '산탈리어');
INSERT INTO [country] ([id], [name]) VALUES ('sal', '샐리시어어');
INSERT INTO [country] ([id], [name]) VALUES ('chy', '샤이엔어');
INSERT INTO [country] ([id], [name]) VALUES ('shn', '샨어');
INSERT INTO [country] ([id], [name]) VALUES ('srr', '세레르어');
INSERT INTO [country] ([id], [name]) VALUES ('sh', '세르비아-크로아티아어');
INSERT INTO [country] ([id], [name]) VALUES ('sr', '세르비아어');
INSERT INTO [country] ([id], [name]) VALUES ('ceb', '세부아노어');
INSERT INTO [country] ([id], [name]) VALUES ('tn', '세츠와나어');
INSERT INTO [country] ([id], [name]) VALUES ('sel', '셀쿠프어');
INSERT INTO [country] ([id], [name]) VALUES ('sem', '셈어 (기타)');
INSERT INTO [country] ([id], [name]) VALUES ('sog', '소그디엔어');
INSERT INTO [country] ([id], [name]) VALUES ('snk', '소닌케어');
INSERT INTO [country] ([id], [name]) VALUES ('wen', '소르브어');
INSERT INTO [country] ([id], [name]) VALUES ('so', '소말리아어');
INSERT INTO [country] ([id], [name]) VALUES ('st', '소토어 (남부)');
INSERT INTO [country] ([id], [name]) VALUES ('nso', '소토어 (북부)');
INSERT INTO [country] ([id], [name]) VALUES ('son', '송가이족어');
INSERT INTO [country] ([id], [name]) VALUES ('sn', '쇼나어');
INSERT INTO [country] ([id], [name]) VALUES ('sux', '수메르어');
INSERT INTO [country] ([id], [name]) VALUES ('sus', '수수어');
INSERT INTO [country] ([id], [name]) VALUES ('sio', '수족어');
INSERT INTO [country] ([id], [name]) VALUES ('suk', '수쿠마족어');
INSERT INTO [country] ([id], [name]) VALUES ('sgn', '수화');
INSERT INTO [country] ([id], [name]) VALUES ('su', '순다어');
INSERT INTO [country] ([id], [name]) VALUES ('srn', '스라난 통가어');
INSERT INTO [country] ([id], [name]) VALUES ('si', '스리랑카어');
INSERT INTO [country] ([id], [name]) VALUES ('sw', '스와힐리어');
INSERT INTO [country] ([id], [name]) VALUES ('sv', '스웨덴어');
INSERT INTO [country] ([id], [name]) VALUES ('gd', '스코틀랜드 게일어');
INSERT INTO [country] ([id], [name]) VALUES ('sco', '스코틀랜드어');
INSERT INTO [country] ([id], [name]) VALUES ('sms', '스콜트 사미어');
INSERT INTO [country] ([id], [name]) VALUES ('es', '스페인어');
INSERT INTO [country] ([id], [name]) VALUES ('es_ES', '스페인어 (이베리아)');
INSERT INTO [country] ([id], [name]) VALUES ('den', '슬라브어');
INSERT INTO [country] ([id], [name]) VALUES ('sla', '슬라브어 (기타)');
INSERT INTO [country] ([id], [name]) VALUES ('sk', '슬로바키아어');
INSERT INTO [country] ([id], [name]) VALUES ('sl', '슬로베니아어');
INSERT INTO [country] ([id], [name]) VALUES ('sid', '시다모어');
INSERT INTO [country] ([id], [name]) VALUES ('syr', '시리아어');
INSERT INTO [country] ([id], [name]) VALUES ('syc', '시리아어 (고전)');
INSERT INTO [country] ([id], [name]) VALUES ('ss', '시스와티어');
INSERT INTO [country] ([id], [name]) VALUES ('scn', '시칠리아어');
INSERT INTO [country] ([id], [name]) VALUES ('bla', '식시카어');
INSERT INTO [country] ([id], [name]) VALUES ('sd', '신디어');
INSERT INTO [country] ([id], [name]) VALUES ('ii', '쓰촨 이어');
INSERT INTO [country] ([id], [name]) VALUES ('ady', '아닥헤어');
INSERT INTO [country] ([id], [name]) VALUES ('ada', '아당메어');
INSERT INTO [country] ([id], [name]) VALUES ('an', '아라곤어');
INSERT INTO [country] ([id], [name]) VALUES ('arw', '아라와크어');
INSERT INTO [country] ([id], [name]) VALUES ('arn', '아라우칸어');
INSERT INTO [country] ([id], [name]) VALUES ('arp', '아라파호어');
INSERT INTO [country] ([id], [name]) VALUES ('arc', '아람어');
INSERT INTO [country] ([id], [name]) VALUES ('ar', '아랍어');
INSERT INTO [country] ([id], [name]) VALUES ('rup', '아로마니아어');
INSERT INTO [country] ([id], [name]) VALUES ('hy', '아르메니아어');
INSERT INTO [country] ([id], [name]) VALUES ('av', '아바릭어');
INSERT INTO [country] ([id], [name]) VALUES ('ae', '아베스타어');
INSERT INTO [country] ([id], [name]) VALUES ('cch', '아삼어');
INSERT INTO [country] ([id], [name]) VALUES ('as', '아샘어');
INSERT INTO [country] ([id], [name]) VALUES ('ast', '아스투리아어');
INSERT INTO [country] ([id], [name]) VALUES ('afa', '아시아-아프리카어 (기타)');
INSERT INTO [country] ([id], [name]) VALUES ('awa', '아와히어');
INSERT INTO [country] ([id], [name]) VALUES ('ain', '아이누어');
INSERT INTO [country] ([id], [name]) VALUES ('ay', '아이마라어');
INSERT INTO [country] ([id], [name]) VALUES ('is', '아이슬란드어');
INSERT INTO [country] ([id], [name]) VALUES ('ht', '아이티어');
INSERT INTO [country] ([id], [name]) VALUES ('sga', '아일랜드, 고대 (900년 까지)');
INSERT INTO [country] ([id], [name]) VALUES ('ga', '아일랜드어');
INSERT INTO [country] ([id], [name]) VALUES ('mga', '아일랜드어, 중세 (900-1200)');
INSERT INTO [country] ([id], [name]) VALUES ('znd', '아잔데족어');
INSERT INTO [country] ([id], [name]) VALUES ('az', '아제르바이잔어');
INSERT INTO [country] ([id], [name]) VALUES ('ace', '아체어');
INSERT INTO [country] ([id], [name]) VALUES ('akk', '아카드어');
INSERT INTO [country] ([id], [name]) VALUES ('ak', '아칸어');
INSERT INTO [country] ([id], [name]) VALUES ('ach', '아콜리어');
INSERT INTO [country] ([id], [name]) VALUES ('ath', '아타파스카어군');
INSERT INTO [country] ([id], [name]) VALUES ('aa', '아파르어');
INSERT INTO [country] ([id], [name]) VALUES ('apa', '아파치어');
INSERT INTO [country] ([id], [name]) VALUES ('afh', '아프리히리어');
INSERT INTO [country] ([id], [name]) VALUES ('alg', '알공킨어족');
INSERT INTO [country] ([id], [name]) VALUES ('ale', '알류트어');
INSERT INTO [country] ([id], [name]) VALUES ('sq', '알바니아어');
INSERT INTO [country] ([id], [name]) VALUES ('tut', '알타이제어 (기타)');
INSERT INTO [country] ([id], [name]) VALUES ('am', '암하라어');
INSERT INTO [country] ([id], [name]) VALUES ('ab', '압카즈어');
INSERT INTO [country] ([id], [name]) VALUES ('anp', '앙가어');
INSERT INTO [country] ([id], [name]) VALUES ('yao', '야오족어');
INSERT INTO [country] ([id], [name]) VALUES ('sah', '야큐트어');
INSERT INTO [country] ([id], [name]) VALUES ('ypk', '야픽어');
INSERT INTO [country] ([id], [name]) VALUES ('yap', '얍페세어');
INSERT INTO [country] ([id], [name]) VALUES ('root', '어근');
INSERT INTO [country] ([id], [name]) VALUES ('et', '에스토니아어');
INSERT INTO [country] ([id], [name]) VALUES ('eo', '에스페란토어');
INSERT INTO [country] ([id], [name]) VALUES ('ee', '에웨어');
INSERT INTO [country] ([id], [name]) VALUES ('elx', '엘람어');
INSERT INTO [country] ([id], [name]) VALUES ('myv', '엘즈야어');
INSERT INTO [country] ([id], [name]) VALUES ('en', '영어');
INSERT INTO [country] ([id], [name]) VALUES ('en_US', '영어 (미국식)');
INSERT INTO [country] ([id], [name]) VALUES ('en_GB', '영어 (영국식)');
INSERT INTO [country] ([id], [name]) VALUES ('en_CA', '영어 (캐나다)');
INSERT INTO [country] ([id], [name]) VALUES ('en_AU', '영어 (호주)');
INSERT INTO [country] ([id], [name]) VALUES ('enm', '영어, 중세 (1100-1500)');
INSERT INTO [country] ([id], [name]) VALUES ('om', '오로모어 (아판)');
INSERT INTO [country] ([id], [name]) VALUES ('or', '오리야어');
INSERT INTO [country] ([id], [name]) VALUES ('osa', '오세이지어');
INSERT INTO [country] ([id], [name]) VALUES ('os', '오세트어');
INSERT INTO [country] ([id], [name]) VALUES ('aus', '오스트레일리아어족');
INSERT INTO [country] ([id], [name]) VALUES ('oj', '오지브웨이어');
INSERT INTO [country] ([id], [name]) VALUES ('oc', '오크어');
INSERT INTO [country] ([id], [name]) VALUES ('oto', '오토미안어');
INSERT INTO [country] ([id], [name]) VALUES ('wo', '올로프어');
INSERT INTO [country] ([id], [name]) VALUES ('wal', '와라모어');
INSERT INTO [country] ([id], [name]) VALUES ('war', '와라이어');
INSERT INTO [country] ([id], [name]) VALUES ('was', '와쇼어');
INSERT INTO [country] ([id], [name]) VALUES ('wak', '와카샨어');
INSERT INTO [country] ([id], [name]) VALUES ('wa', '왈론어');
INSERT INTO [country] ([id], [name]) VALUES ('yo', '요루바어');
INSERT INTO [country] ([id], [name]) VALUES ('udm', '우드말트어');
INSERT INTO [country] ([id], [name]) VALUES ('ur', '우르두어');
INSERT INTO [country] ([id], [name]) VALUES ('uz', '우즈베크어');
INSERT INTO [country] ([id], [name]) VALUES ('uk', '우크라이나어');
INSERT INTO [country] ([id], [name]) VALUES ('cy', '웨일스어');
INSERT INTO [country] ([id], [name]) VALUES ('ug', '위구르어');
INSERT INTO [country] ([id], [name]) VALUES ('uga', '유가리틱어');
INSERT INTO [country] ([id], [name]) VALUES ('jrb', '유대-아라비아어');
INSERT INTO [country] ([id], [name]) VALUES ('jpr', '유대-페르시아어');
INSERT INTO [country] ([id], [name]) VALUES ('umb', '윤번두어');
INSERT INTO [country] ([id], [name]) VALUES ('nr', '은데벨레어(남부)');
INSERT INTO [country] ([id], [name]) VALUES ('nd', '은데벨레어(북부)');
INSERT INTO [country] ([id], [name]) VALUES ('nqo', '응코어');
INSERT INTO [country] ([id], [name]) VALUES ('ig', '이그보어');
INSERT INTO [country] ([id], [name]) VALUES ('smn', '이나리 사미어');
INSERT INTO [country] ([id], [name]) VALUES ('ik', '이누피아크어');
INSERT INTO [country] ([id], [name]) VALUES ('iu', '이눅티투트어');
INSERT INTO [country] ([id], [name]) VALUES ('io', '이도어');
INSERT INTO [country] ([id], [name]) VALUES ('yi', '이디시어');
INSERT INTO [country] ([id], [name]) VALUES ('ira', '이란어 [ira]');
INSERT INTO [country] ([id], [name]) VALUES ('iro', '이러쿼이어');
INSERT INTO [country] ([id], [name]) VALUES ('ilo', '이로코어');
INSERT INTO [country] ([id], [name]) VALUES ('iba', '이반어');
INSERT INTO [country] ([id], [name]) VALUES ('ewo', '이원도어');
INSERT INTO [country] ([id], [name]) VALUES ('ijo', '이조어');
INSERT INTO [country] ([id], [name]) VALUES ('egy', '이집트어 (고대)');
INSERT INTO [country] ([id], [name]) VALUES ('eka', '이카죽어');
INSERT INTO [country] ([id], [name]) VALUES ('it', '이탈리아어');
INSERT INTO [country] ([id], [name]) VALUES ('efi', '이픽어');
INSERT INTO [country] ([id], [name]) VALUES ('inh', '인귀시어');
INSERT INTO [country] ([id], [name]) VALUES ('id', '인도네시아어');
INSERT INTO [country] ([id], [name]) VALUES ('inc', '인도어 (기타)');
INSERT INTO [country] ([id], [name]) VALUES ('ine', '인도유럽어 (기타)');
INSERT INTO [country] ([id], [name]) VALUES ('ia', '인테르링구아 (국제보조어협회)');
INSERT INTO [country] ([id], [name]) VALUES ('ie', '인테르링구에');
INSERT INTO [country] ([id], [name]) VALUES ('ja', '일본어');
INSERT INTO [country] ([id], [name]) VALUES ('jv', '자바어');
INSERT INTO [country] ([id], [name]) VALUES ('zza', '자자어');
INSERT INTO [country] ([id], [name]) VALUES ('nds', '저지 독일어');
INSERT INTO [country] ([id], [name]) VALUES ('dsb', '저지 소르비아어');
INSERT INTO [country] ([id], [name]) VALUES ('zen', '제나가어');
INSERT INTO [country] ([id], [name]) VALUES ('dz', '종카어');
INSERT INTO [country] ([id], [name]) VALUES ('zun', '주니어');
INSERT INTO [country] ([id], [name]) VALUES ('za', '주앙어');
INSERT INTO [country] ([id], [name]) VALUES ('zu', '줄루어');
INSERT INTO [country] ([id], [name]) VALUES ('sit', '중국 티베트 어족');
INSERT INTO [country] ([id], [name]) VALUES ('zh', '중국어');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hant', '중국어 (번체)');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hans', '중국어(간체)');
INSERT INTO [country] ([id], [name]) VALUES ('es_419', '중남미 스페인어');
INSERT INTO [country] ([id], [name]) VALUES ('gmh', '중세 고지 독일어');
INSERT INTO [country] ([id], [name]) VALUES ('dum', '중세 네덜란드어');
INSERT INTO [country] ([id], [name]) VALUES ('frm', '중세 프랑스어');
INSERT INTO [country] ([id], [name]) VALUES ('cai', '중앙 아메리카 인디안어 (기타)');
INSERT INTO [country] ([id], [name]) VALUES ('rom', '집시어');
INSERT INTO [country] ([id], [name]) VALUES ('chg', '차가타이어');
INSERT INTO [country] ([id], [name]) VALUES ('ch', '차모로어');
INSERT INTO [country] ([id], [name]) VALUES ('cmc', '참어군');
INSERT INTO [country] ([id], [name]) VALUES ('chr', '체로키어');
INSERT INTO [country] ([id], [name]) VALUES ('ce', '체첸어');
INSERT INTO [country] ([id], [name]) VALUES ('cs', '체코어');
INSERT INTO [country] ([id], [name]) VALUES ('cho', '촉토어');
INSERT INTO [country] ([id], [name]) VALUES ('ts', '총가어');
INSERT INTO [country] ([id], [name]) VALUES ('cv', '추바시어');
INSERT INTO [country] ([id], [name]) VALUES ('chk', '추크어');
INSERT INTO [country] ([id], [name]) VALUES ('chn', '치누크어와 영어 프랑스어의 혼성어');
INSERT INTO [country] ([id], [name]) VALUES ('chb', '치브차어');
INSERT INTO [country] ([id], [name]) VALUES ('chp', '치페우얀');
INSERT INTO [country] ([id], [name]) VALUES ('kn', '카나다어');
INSERT INTO [country] ([id], [name]) VALUES ('cad', '카도어');
INSERT INTO [country] ([id], [name]) VALUES ('krc', '카라챠이-발카르어');
INSERT INTO [country] ([id], [name]) VALUES ('kaa', '카라칼파크어');
INSERT INTO [country] ([id], [name]) VALUES ('kar', '카렌어');
INSERT INTO [country] ([id], [name]) VALUES ('krl', '카렐리야어');
INSERT INTO [country] ([id], [name]) VALUES ('car', '카리브어');
INSERT INTO [country] ([id], [name]) VALUES ('kbd', '카바르디어');
INSERT INTO [country] ([id], [name]) VALUES ('ks', '카슈미르어');
INSERT INTO [country] ([id], [name]) VALUES ('csb', '카슈비아어');
INSERT INTO [country] ([id], [name]) VALUES ('kha', '카시어');
INSERT INTO [country] ([id], [name]) VALUES ('kaw', '카위어');
INSERT INTO [country] ([id], [name]) VALUES ('kk', '카자흐어');
INSERT INTO [country] ([id], [name]) VALUES ('kac', '카친어');
INSERT INTO [country] ([id], [name]) VALUES ('ca', '카탈로니아어');
INSERT INTO [country] ([id], [name]) VALUES ('cau', '카프카스어 (기타)');
INSERT INTO [country] ([id], [name]) VALUES ('kr', '칸누리어');
INSERT INTO [country] ([id], [name]) VALUES ('xal', '칼미크어');
INSERT INTO [country] ([id], [name]) VALUES ('kam', '캄바어');
INSERT INTO [country] ([id], [name]) VALUES ('km', '캄보디아어');
INSERT INTO [country] ([id], [name]) VALUES ('kab', '커바일어');
INSERT INTO [country] ([id], [name]) VALUES ('qu', '케추아어');
INSERT INTO [country] ([id], [name]) VALUES ('cel', '켈트어 (기타)');
INSERT INTO [country] ([id], [name]) VALUES ('kfo', '코로어');
INSERT INTO [country] ([id], [name]) VALUES ('co', '코르시카어');
INSERT INTO [country] ([id], [name]) VALUES ('kv', '코미어');
INSERT INTO [country] ([id], [name]) VALUES ('xh', '코사어');
INSERT INTO [country] ([id], [name]) VALUES ('kos', '코스라이엔어');
INSERT INTO [country] ([id], [name]) VALUES ('khi', '코이산어 (기타)');
INSERT INTO [country] ([id], [name]) VALUES ('kok', '코카니어');
INSERT INTO [country] ([id], [name]) VALUES ('kw', '콘월어');
INSERT INTO [country] ([id], [name]) VALUES ('cop', '콥트어');
INSERT INTO [country] ([id], [name]) VALUES ('kg', '콩고어');
INSERT INTO [country] ([id], [name]) VALUES ('ku', '쿠르드어');
INSERT INTO [country] ([id], [name]) VALUES ('kru', '쿠르크어');
INSERT INTO [country] ([id], [name]) VALUES ('kum', '쿠믹어');
INSERT INTO [country] ([id], [name]) VALUES ('cus', '쿠시어족');
INSERT INTO [country] ([id], [name]) VALUES ('kj', '쿠안야마어');
INSERT INTO [country] ([id], [name]) VALUES ('kut', '쿠테네어');
INSERT INTO [country] ([id], [name]) VALUES ('hr', '크로아티아어');
INSERT INTO [country] ([id], [name]) VALUES ('kro', '크루어');
INSERT INTO [country] ([id], [name]) VALUES ('crh', '크리민 터키어; 크리민 타타르어');
INSERT INTO [country] ([id], [name]) VALUES ('cr', '크리어');
INSERT INTO [country] ([id], [name]) VALUES ('crp', '크리올어 및 피진어 (기타)');
INSERT INTO [country] ([id], [name]) VALUES ('cpe', '크리올어 및 피진어 (영어를 기반으로 한 기타)');
INSERT INTO [country] ([id], [name]) VALUES ('cpp', '크리올어 및 피진어 (포르투갈어를 기반으로 한 기타)');
INSERT INTO [country] ([id], [name]) VALUES ('cpf', '크리올어 및 피진어 (프랑스어를 기반으로 한 기타)');
INSERT INTO [country] ([id], [name]) VALUES ('mus', '크리크어');
INSERT INTO [country] ([id], [name]) VALUES ('kpe', '크펠레어');
INSERT INTO [country] ([id], [name]) VALUES ('tlh', '클링온어');
INSERT INTO [country] ([id], [name]) VALUES ('ky', '키르기스어');
INSERT INTO [country] ([id], [name]) VALUES ('gil', '키리바시어');
INSERT INTO [country] ([id], [name]) VALUES ('ki', '키쿠유어');
INSERT INTO [country] ([id], [name]) VALUES ('kmb', '킴분두어');
INSERT INTO [country] ([id], [name]) VALUES ('tl', '타갈로그어');
INSERT INTO [country] ([id], [name]) VALUES ('tmh', '타마섹어');
INSERT INTO [country] ([id], [name]) VALUES ('ta', '타밀어');
INSERT INTO [country] ([id], [name]) VALUES ('tg', '타지키스탄어');
INSERT INTO [country] ([id], [name]) VALUES ('tt', '타타르어');
INSERT INTO [country] ([id], [name]) VALUES ('ty', '타히티어');
INSERT INTO [country] ([id], [name]) VALUES ('th', '태국어');
INSERT INTO [country] ([id], [name]) VALUES ('tai', '태국어 (기타)');
INSERT INTO [country] ([id], [name]) VALUES ('tr', '터키어');
INSERT INTO [country] ([id], [name]) VALUES ('ota', '터키어, 오스만 (1500-1928)');
INSERT INTO [country] ([id], [name]) VALUES ('ter', '테레노어');
INSERT INTO [country] ([id], [name]) VALUES ('tet', '테툼어');
INSERT INTO [country] ([id], [name]) VALUES ('te', '텔루구어');
INSERT INTO [country] ([id], [name]) VALUES ('tkl', '토켈라우제도어');
INSERT INTO [country] ([id], [name]) VALUES ('tpi', '토크 피신어');
INSERT INTO [country] ([id], [name]) VALUES ('to', '통가어');
INSERT INTO [country] ([id], [name]) VALUES ('tog', '통가어 (니아살랜드)');
INSERT INTO [country] ([id], [name]) VALUES ('tk', '투르크멘어');
INSERT INTO [country] ([id], [name]) VALUES ('tvl', '투발루어');
INSERT INTO [country] ([id], [name]) VALUES ('tyv', '투비니안어');
INSERT INTO [country] ([id], [name]) VALUES ('tup', '투피어');
INSERT INTO [country] ([id], [name]) VALUES ('tum', '툼부카어');
INSERT INTO [country] ([id], [name]) VALUES ('tsi', '트심시안어');
INSERT INTO [country] ([id], [name]) VALUES ('tw', '트위어');
INSERT INTO [country] ([id], [name]) VALUES ('tli', '틀링깃족어');
INSERT INTO [country] ([id], [name]) VALUES ('tig', '티그레어');
INSERT INTO [country] ([id], [name]) VALUES ('ti', '티그리냐어');
INSERT INTO [country] ([id], [name]) VALUES ('bo', '티베트어');
INSERT INTO [country] ([id], [name]) VALUES ('tiv', '티비어');
INSERT INTO [country] ([id], [name]) VALUES ('tem', '팀니어');
INSERT INTO [country] ([id], [name]) VALUES ('pau', '파라우안어');
INSERT INTO [country] ([id], [name]) VALUES ('ps', '파시토어 (푸시토)');
INSERT INTO [country] ([id], [name]) VALUES ('paa', '파푸아어 (기타)');
INSERT INTO [country] ([id], [name]) VALUES ('pap', '파피아먼토어');
INSERT INTO [country] ([id], [name]) VALUES ('pag', '판가시난어');
INSERT INTO [country] ([id], [name]) VALUES ('fat', '판티어');
INSERT INTO [country] ([id], [name]) VALUES ('pal', '팔레비어');
INSERT INTO [country] ([id], [name]) VALUES ('pi', '팔리어');
INSERT INTO [country] ([id], [name]) VALUES ('pam', '팜팡가어');
INSERT INTO [country] ([id], [name]) VALUES ('fan', '팡그어');
INSERT INTO [country] ([id], [name]) VALUES ('pa', '펀잡어');
INSERT INTO [country] ([id], [name]) VALUES ('phn', '페니키아어');
INSERT INTO [country] ([id], [name]) VALUES ('fo', '페로어');
INSERT INTO [country] ([id], [name]) VALUES ('fa', '페르시아어');
INSERT INTO [country] ([id], [name]) VALUES ('pt', '포르투갈어');
INSERT INTO [country] ([id], [name]) VALUES ('pt_BR', '포르투갈어 (브라질)');
INSERT INTO [country] ([id], [name]) VALUES ('pt_PT', '포르투갈어 (이베리아)');
INSERT INTO [country] ([id], [name]) VALUES ('fon', '폰어');
INSERT INTO [country] ([id], [name]) VALUES ('pl', '폴란드어');
INSERT INTO [country] ([id], [name]) VALUES ('pon', '폼페이어');
INSERT INTO [country] ([id], [name]) VALUES ('ff', '풀라어');
INSERT INTO [country] ([id], [name]) VALUES ('pra', '프라크리트어');
INSERT INTO [country] ([id], [name]) VALUES ('fr', '프랑스어');
INSERT INTO [country] ([id], [name]) VALUES ('fr_CH', '프랑스어 (스위스)');
INSERT INTO [country] ([id], [name]) VALUES ('fr_CA', '프랑스어 (캐나다)');
INSERT INTO [country] ([id], [name]) VALUES ('fur', '프리우리안어');
INSERT INTO [country] ([id], [name]) VALUES ('fy', '프리지아어');
INSERT INTO [country] ([id], [name]) VALUES ('nl_BE', '플라망어');
INSERT INTO [country] ([id], [name]) VALUES ('fiu', '피노우그리아어 (기타)');
INSERT INTO [country] ([id], [name]) VALUES ('fj', '피지어');
INSERT INTO [country] ([id], [name]) VALUES ('fi', '핀란드어');
INSERT INTO [country] ([id], [name]) VALUES ('fil', '필리핀어');
INSERT INTO [country] ([id], [name]) VALUES ('phi', '필리핀어 (기타)');
INSERT INTO [country] ([id], [name]) VALUES ('haw', '하와이어');
INSERT INTO [country] ([id], [name]) VALUES ('ha', '하우사어');
INSERT INTO [country] ([id], [name]) VALUES ('hai', '하이다어');
INSERT INTO [country] ([id], [name]) VALUES ('hit', '하타이트어');
INSERT INTO [country] ([id], [name]) VALUES ('ko', '한국어');
INSERT INTO [country] ([id], [name]) VALUES ('hu', '헝가리어');
INSERT INTO [country] ([id], [name]) VALUES ('hz', '헤레로어');
INSERT INTO [country] ([id], [name]) VALUES ('hil', '헤리가뇬어');
INSERT INTO [country] ([id], [name]) VALUES ('bho', '호즈푸리어');
INSERT INTO [country] ([id], [name]) VALUES ('kho', '호탄어');
INSERT INTO [country] ([id], [name]) VALUES ('hup', '후파어');
INSERT INTO [country] ([id], [name]) VALUES ('ho', '히리 모투어');
INSERT INTO [country] ([id], [name]) VALUES ('him', '히마차리어');
INSERT INTO [country] ([id], [name]) VALUES ('hmn', '히몸어');
INSERT INTO [country] ([id], [name]) VALUES ('he', '히브리어');
INSERT INTO [country] ([id], [name]) VALUES ('hi', '힌디어');
