CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('ace', 'acehgiella');
INSERT INTO [country] ([id], [name]) VALUES ('af', 'afrikánsagiella');
INSERT INTO [country] ([id], [name]) VALUES ('sq', 'albánagiella');
INSERT INTO [country] ([id], [name]) VALUES ('smn', 'anárašgiella');
INSERT INTO [country] ([id], [name]) VALUES ('apa', 'apacheš giella');
INSERT INTO [country] ([id], [name]) VALUES ('an', 'aragoniagiella');
INSERT INTO [country] ([id], [name]) VALUES ('hy', 'armeenagiella');
INSERT INTO [country] ([id], [name]) VALUES ('ar', 'arábagiella');
INSERT INTO [country] ([id], [name]) VALUES ('ast', 'asturiagiella');
INSERT INTO [country] ([id], [name]) VALUES ('bn', 'bengalgiella');
INSERT INTO [country] ([id], [name]) VALUES ('ang', 'boares eaŋgalasgiella');
INSERT INTO [country] ([id], [name]) VALUES ('bs', 'bosniagiella');
INSERT INTO [country] ([id], [name]) VALUES ('br', 'bretonagiella');
INSERT INTO [country] ([id], [name]) VALUES ('bg', 'bulgáriagiella');
INSERT INTO [country] ([id], [name]) VALUES ('co', 'corsicagiella');
INSERT INTO [country] ([id], [name]) VALUES ('se', 'davvisámegiella');
INSERT INTO [country] ([id], [name]) VALUES ('de', 'duiskkagiella');
INSERT INTO [country] ([id], [name]) VALUES ('da', 'dánskkagiella');
INSERT INTO [country] ([id], [name]) VALUES ('no', 'dárogiella');
INSERT INTO [country] ([id], [name]) VALUES ('en', 'eaŋgalsgiella');
INSERT INTO [country] ([id], [name]) VALUES ('myv', 'ersagiella');
INSERT INTO [country] ([id], [name]) VALUES ('et', 'esttegiella');
INSERT INTO [country] ([id], [name]) VALUES ('fo', 'fearagiella');
INSERT INTO [country] ([id], [name]) VALUES ('fiu', 'fenno-ugrálaš giella');
INSERT INTO [country] ([id], [name]) VALUES ('fr', 'fránskkagiella');
INSERT INTO [country] ([id], [name]) VALUES ('gem', 'germánalaš gielat');
INSERT INTO [country] ([id], [name]) VALUES ('nb', 'girjedárogiella');
INSERT INTO [country] ([id], [name]) VALUES ('el', 'greikkagiella');
INSERT INTO [country] ([id], [name]) VALUES ('gu', 'gujaratagiella');
INSERT INTO [country] ([id], [name]) VALUES ('krl', 'gárjilgiella');
INSERT INTO [country] ([id], [name]) VALUES ('hi', 'hindigiella');
INSERT INTO [country] ([id], [name]) VALUES ('nl', 'hollánddagiella');
INSERT INTO [country] ([id], [name]) VALUES ('ga', 'iirragiella');
INSERT INTO [country] ([id], [name]) VALUES ('is', 'islánddagiella');
INSERT INTO [country] ([id], [name]) VALUES ('it', 'itáliagiella');
INSERT INTO [country] ([id], [name]) VALUES ('ja', 'japánagiella');
INSERT INTO [country] ([id], [name]) VALUES ('smj', 'julevsámegiella');
INSERT INTO [country] ([id], [name]) VALUES ('ca', 'katalánagiella');
INSERT INTO [country] ([id], [name]) VALUES ('cel', 'kelttalaš gielat');
INSERT INTO [country] ([id], [name]) VALUES ('zh', 'kiinnágiella');
INSERT INTO [country] ([id], [name]) VALUES ('kv', 'komigiella');
INSERT INTO [country] ([id], [name]) VALUES ('kw', 'kornagiella');
INSERT INTO [country] ([id], [name]) VALUES ('hr', 'kroátiagiella');
INSERT INTO [country] ([id], [name]) VALUES ('lt', 'liettuvagiella');
INSERT INTO [country] ([id], [name]) VALUES ('sma', 'lullisámegiella');
INSERT INTO [country] ([id], [name]) VALUES ('lb', 'luxemburggagiella');
INSERT INTO [country] ([id], [name]) VALUES ('la', 'láhtengiella');
INSERT INTO [country] ([id], [name]) VALUES ('lv', 'látviagiella');
INSERT INTO [country] ([id], [name]) VALUES ('mk', 'makedoniagiella');
INSERT INTO [country] ([id], [name]) VALUES ('gv', 'manksgiella');
INSERT INTO [country] ([id], [name]) VALUES ('chm', 'marigiella');
INSERT INTO [country] ([id], [name]) VALUES ('mdf', 'mokšagiella');
INSERT INTO [country] ([id], [name]) VALUES ('sms', 'nuortalašgiella');
INSERT INTO [country] ([id], [name]) VALUES ('fy', 'oarjifriisagiella');
INSERT INTO [country] ([id], [name]) VALUES ('oc', 'oksitánagiella');
INSERT INTO [country] ([id], [name]) VALUES ('nn', 'ođđadárogiella');
INSERT INTO [country] ([id], [name]) VALUES ('fa', 'persijagiella');
INSERT INTO [country] ([id], [name]) VALUES ('pl', 'polskkagiella');
INSERT INTO [country] ([id], [name]) VALUES ('pt', 'portugálagiella');
INSERT INTO [country] ([id], [name]) VALUES ('rm', 'retorománagiella');
INSERT INTO [country] ([id], [name]) VALUES ('roa', 'románalaš gielat');
INSERT INTO [country] ([id], [name]) VALUES ('ro', 'romániagiella');
INSERT INTO [country] ([id], [name]) VALUES ('ru', 'ruoššagiella');
INSERT INTO [country] ([id], [name]) VALUES ('sv', 'ruoŧagiella');
INSERT INTO [country] ([id], [name]) VALUES ('sc', 'sardigiella');
INSERT INTO [country] ([id], [name]) VALUES ('sel', 'selkupagiella');
INSERT INTO [country] ([id], [name]) VALUES ('sr', 'serbiagiella');
INSERT INTO [country] ([id], [name]) VALUES ('scn', 'sisiliagiella');
INSERT INTO [country] ([id], [name]) VALUES ('sl', 'slovenagiella');
INSERT INTO [country] ([id], [name]) VALUES ('sk', 'slovákiagiella');
INSERT INTO [country] ([id], [name]) VALUES ('wen', 'sorbigiella');
INSERT INTO [country] ([id], [name]) VALUES ('es', 'spánskkagiella');
INSERT INTO [country] ([id], [name]) VALUES ('fi', 'suomagiella');
INSERT INTO [country] ([id], [name]) VALUES ('smi', 'sámegielat');
INSERT INTO [country] ([id], [name]) VALUES ('udm', 'udmurtagiella');
INSERT INTO [country] ([id], [name]) VALUES ('uk', 'ukrainagiella');
INSERT INTO [country] ([id], [name]) VALUES ('wa', 'vallonagiella');
INSERT INTO [country] ([id], [name]) VALUES ('be', 'vilges-ruoššagiella');
INSERT INTO [country] ([id], [name]) VALUES ('cs', 'čeahkagiella');
