CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('ak', 'అకాన్');
INSERT INTO "country" ("id", "name") VALUES ('ach', 'అకోలి');
INSERT INTO "country" ("id", "name") VALUES ('akk', 'అక్కాడియాన్');
INSERT INTO "country" ("id", "name") VALUES ('az', 'అజర్బైజాని');
INSERT INTO "country" ("id", "name") VALUES ('cch', 'అట్సామ్');
INSERT INTO "country" ("id", "name") VALUES ('ada', 'అడాంగ్మే');
INSERT INTO "country" ("id", "name") VALUES ('ady', 'అడిగాబ్జే');
INSERT INTO "country" ("id", "name") VALUES ('hsb', 'అప్పర్ సోర్బియన్');
INSERT INTO "country" ("id", "name") VALUES ('apa', 'అప్పాచి భాష');
INSERT INTO "country" ("id", "name") VALUES ('aa', 'అఫార్');
INSERT INTO "country" ("id", "name") VALUES ('afh', 'అఫ్రిహిలి');
INSERT INTO "country" ("id", "name") VALUES ('ab', 'అబ్ఖాజియన్');
INSERT INTO "country" ("id", "name") VALUES ('am', 'అమ్హారిక్');
INSERT INTO "country" ("id", "name") VALUES ('an', 'అరగోనిస్');
INSERT INTO "country" ("id", "name") VALUES ('ar', 'అరబిక్');
INSERT INTO "country" ("id", "name") VALUES ('arp', 'అరాపాహో');
INSERT INTO "country" ("id", "name") VALUES ('arc', 'అరామేక్');
INSERT INTO "country" ("id", "name") VALUES ('arw', 'అరావాక్');
INSERT INTO "country" ("id", "name") VALUES ('arn', 'అరౌకేనియన్');
INSERT INTO "country" ("id", "name") VALUES ('ale', 'అలియుట్');
INSERT INTO "country" ("id", "name") VALUES ('sq', 'అల్బేనియన్');
INSERT INTO "country" ("id", "name") VALUES ('awa', 'అవధి');
INSERT INTO "country" ("id", "name") VALUES ('av', 'అవారిక్');
INSERT INTO "country" ("id", "name") VALUES ('ae', 'అవేస్టాన్');
INSERT INTO "country" ("id", "name") VALUES ('ast', 'అస్టురియాన్');
INSERT INTO "country" ("id", "name") VALUES ('as', 'అస్సామీస్');
INSERT INTO "country" ("id", "name") VALUES ('anp', 'ఆంగిక');
INSERT INTO "country" ("id", "name") VALUES ('en', 'ఆంగ్లం');
INSERT INTO "country" ("id", "name") VALUES ('cpe', 'ఆంగ్లం ఆధారిత క్రియోల్ లేదా పిగ్డిన్');
INSERT INTO "country" ("id", "name") VALUES ('oc', 'ఆక్సిటాన్');
INSERT INTO "country" ("id", "name") VALUES ('ace', 'ఆఖినీస్');
INSERT INTO "country" ("id", "name") VALUES ('ath', 'ఆతాపాస్కన్ భాష');
INSERT INTO "country" ("id", "name") VALUES ('af', 'ఆఫ్రికాన్స్');
INSERT INTO "country" ("id", "name") VALUES ('afa', 'ఆఫ్రో-ఆశియా భాష');
INSERT INTO "country" ("id", "name") VALUES ('rup', 'ఆరోమేనియన్');
INSERT INTO "country" ("id", "name") VALUES ('hy', 'ఆర్మేనియన్');
INSERT INTO "country" ("id", "name") VALUES ('alg', 'ఆల్గొంక్వియన్ భాష');
INSERT INTO "country" ("id", "name") VALUES ('tut', 'ఆల్టియాక్ భాష');
INSERT INTO "country" ("id", "name") VALUES ('en_AU', 'ఆస్ట్రేలియన్ ఇంగ్లీష్');
INSERT INTO "country" ("id", "name") VALUES ('de_AT', 'ఆస్ట్రేలియన్ జర్మన్');
INSERT INTO "country" ("id", "name") VALUES ('aus', 'ఆస్ట్రేలియన్ భాష');
INSERT INTO "country" ("id", "name") VALUES ('map', 'ఆస్ట్రోనిశియన్');
INSERT INTO "country" ("id", "name") VALUES ('inh', 'ఇంగుష్');
INSERT INTO "country" ("id", "name") VALUES ('ie', 'ఇంటర్ లింగ్');
INSERT INTO "country" ("id", "name") VALUES ('ia', 'ఇంటర్లింగువా');
INSERT INTO "country" ("id", "name") VALUES ('ine', 'ఇండో-ఐరోపియన్ భాష');
INSERT INTO "country" ("id", "name") VALUES ('id', 'ఇండోనిషియ');
INSERT INTO "country" ("id", "name") VALUES ('ig', 'ఇగ్బో');
INSERT INTO "country" ("id", "name") VALUES ('it', 'ఇటాలియన్');
INSERT INTO "country" ("id", "name") VALUES ('smn', 'ఇనారి సామి');
INSERT INTO "country" ("id", "name") VALUES ('iu', 'ఇనుక్టిటుట్');
INSERT INTO "country" ("id", "name") VALUES ('ik', 'ఇనూపైఏక్');
INSERT INTO "country" ("id", "name") VALUES ('ira', 'ఇరానియన్ భాష');
INSERT INTO "country" ("id", "name") VALUES ('iro', 'ఇరోక్వియన్ భాష');
INSERT INTO "country" ("id", "name") VALUES ('ee', 'ఇవే');
INSERT INTO "country" ("id", "name") VALUES ('zxx', 'ఈ లిపి లేదు');
INSERT INTO "country" ("id", "name") VALUES ('io', 'ఈడౌ');
INSERT INTO "country" ("id", "name") VALUES ('et', 'ఈస్టొనియన్');
INSERT INTO "country" ("id", "name") VALUES ('uga', 'ఉగారిటిక్');
INSERT INTO "country" ("id", "name") VALUES ('uz', 'ఉజ్బెక్');
INSERT INTO "country" ("id", "name") VALUES ('udm', 'ఉడ్ముర్ట్');
INSERT INTO "country" ("id", "name") VALUES ('nai', 'ఉత్తర అమెరికా ఇండియన్ భాష');
INSERT INTO "country" ("id", "name") VALUES ('nd', 'ఉత్తర దెబెలె');
INSERT INTO "country" ("id", "name") VALUES ('frr', 'ఉత్తర ఫ్రిసియన్');
INSERT INTO "country" ("id", "name") VALUES ('se', 'ఉత్తర సామి');
INSERT INTO "country" ("id", "name") VALUES ('nso', 'ఉత్తర సోతో');
INSERT INTO "country" ("id", "name") VALUES ('umb', 'ఉమ్బుండు');
INSERT INTO "country" ("id", "name") VALUES ('ug', 'ఉయ్ఘుర్');
INSERT INTO "country" ("id", "name") VALUES ('ur', 'ఉర్దూ');
INSERT INTO "country" ("id", "name") VALUES ('efi', 'ఎఫిక్');
INSERT INTO "country" ("id", "name") VALUES ('myv', 'ఎర్జియా');
INSERT INTO "country" ("id", "name") VALUES ('elx', 'ఎలామైట్');
INSERT INTO "country" ("id", "name") VALUES ('ewo', 'ఎవోండొ');
INSERT INTO "country" ("id", "name") VALUES ('eo', 'ఎస్పరెన్టొ');
INSERT INTO "country" ("id", "name") VALUES ('eka', 'ఏకాజక్');
INSERT INTO "country" ("id", "name") VALUES ('ijo', 'ఐజో');
INSERT INTO "country" ("id", "name") VALUES ('ain', 'ఐను');
INSERT INTO "country" ("id", "name") VALUES ('iba', 'ఐబాన్');
INSERT INTO "country" ("id", "name") VALUES ('pt_PT', 'ఐబీరియన్ పోర్చుగీస్');
INSERT INTO "country" ("id", "name") VALUES ('es_ES', 'ఐబీరియెన్ స్పానిష్');
INSERT INTO "country" ("id", "name") VALUES ('ay', 'ఐమారా');
INSERT INTO "country" ("id", "name") VALUES ('ilo', 'ఐయోకో');
INSERT INTO "country" ("id", "name") VALUES ('ga', 'ఐరిష్');
INSERT INTO "country" ("id", "name") VALUES ('is', 'ఐస్లాండిక్');
INSERT INTO "country" ("id", "name") VALUES ('oto', 'ఒటోమియన్ భాష');
INSERT INTO "country" ("id", "name") VALUES ('ota', 'ఒట్టోమన్ టర్కిష్');
INSERT INTO "country" ("id", "name") VALUES ('or', 'ఒరియా');
INSERT INTO "country" ("id", "name") VALUES ('om', 'ఒరోమో');
INSERT INTO "country" ("id", "name") VALUES ('osa', 'ఒసాజ్');
INSERT INTO "country" ("id", "name") VALUES ('os', 'ఒసేటిక్');
INSERT INTO "country" ("id", "name") VALUES ('kam', 'కంబా');
INSERT INTO "country" ("id", "name") VALUES ('kn', 'కన్నడ');
INSERT INTO "country" ("id", "name") VALUES ('kbd', 'కబార్డియన్');
INSERT INTO "country" ("id", "name") VALUES ('krc', 'కరచే-బల్కార్');
INSERT INTO "country" ("id", "name") VALUES ('kar', 'కరెన్');
INSERT INTO "country" ("id", "name") VALUES ('krl', 'కరేలియన్');
INSERT INTO "country" ("id", "name") VALUES ('ku', 'కర్డిష్');
INSERT INTO "country" ("id", "name") VALUES ('kl', 'కలాల్లిసూట్');
INSERT INTO "country" ("id", "name") VALUES ('xal', 'కల్మిక్');
INSERT INTO "country" ("id", "name") VALUES ('csb', 'కషుబియన్');
INSERT INTO "country" ("id", "name") VALUES ('kg', 'కాంగో');
INSERT INTO "country" ("id", "name") VALUES ('yue', 'కాంటనీస్');
INSERT INTO "country" ("id", "name") VALUES ('kac', 'కాచిన్');
INSERT INTO "country" ("id", "name") VALUES ('kk', 'కాజాక్');
INSERT INTO "country" ("id", "name") VALUES ('kr', 'కానురి');
INSERT INTO "country" ("id", "name") VALUES ('kab', 'కాబిల్');
INSERT INTO "country" ("id", "name") VALUES ('kaa', 'కారా-కల్పాక్');
INSERT INTO "country" ("id", "name") VALUES ('co', 'కార్సికన్');
INSERT INTO "country" ("id", "name") VALUES ('kaw', 'కావి');
INSERT INTO "country" ("id", "name") VALUES ('ks', 'కాశ్మీరి');
INSERT INTO "country" ("id", "name") VALUES ('ki', 'కికుయు');
INSERT INTO "country" ("id", "name") VALUES ('rw', 'కిన్యర్వాండా');
INSERT INTO "country" ("id", "name") VALUES ('kmb', 'కిమ్బుండు');
INSERT INTO "country" ("id", "name") VALUES ('ky', 'కిర్గిజ్');
INSERT INTO "country" ("id", "name") VALUES ('kut', 'కుటేనై');
INSERT INTO "country" ("id", "name") VALUES ('kum', 'కుమ్యిక్');
INSERT INTO "country" ("id", "name") VALUES ('cus', 'కుషిటిక్ భాష');
INSERT INTO "country" ("id", "name") VALUES ('kru', 'కూరుఖ్');
INSERT INTO "country" ("id", "name") VALUES ('kro', 'కృ');
INSERT INTO "country" ("id", "name") VALUES ('art', 'కృత్రిమ భాష');
INSERT INTO "country" ("id", "name") VALUES ('ca', 'కెటలాన్');
INSERT INTO "country" ("id", "name") VALUES ('en_CA', 'కెనడియన్ ఇంగ్లీష్');
INSERT INTO "country" ("id", "name") VALUES ('fr_CA', 'కెనేడియెన్ ఫ్రెంచ్');
INSERT INTO "country" ("id", "name") VALUES ('qu', 'కెషుయా');
INSERT INTO "country" ("id", "name") VALUES ('cad', 'కేడ్డో');
INSERT INTO "country" ("id", "name") VALUES ('car', 'కేరిబ్');
INSERT INTO "country" ("id", "name") VALUES ('kok', 'కొంకణి');
INSERT INTO "country" ("id", "name") VALUES ('swb', 'కొమొరియన్');
INSERT INTO "country" ("id", "name") VALUES ('ko', 'కొరియన్');
INSERT INTO "country" ("id", "name") VALUES ('cau', 'కోకేషియన్ భాష');
INSERT INTO "country" ("id", "name") VALUES ('cop', 'కోప్టిక్');
INSERT INTO "country" ("id", "name") VALUES ('kv', 'కోమి');
INSERT INTO "country" ("id", "name") VALUES ('kfo', 'కోరో');
INSERT INTO "country" ("id", "name") VALUES ('kw', 'కోర్నిష్');
INSERT INTO "country" ("id", "name") VALUES ('kos', 'కోస్రేయన్');
INSERT INTO "country" ("id", "name") VALUES ('cr', 'క్రి');
INSERT INTO "country" ("id", "name") VALUES ('crh', 'క్రిమియన్ టర్కిష్');
INSERT INTO "country" ("id", "name") VALUES ('crp', 'క్రియోల్ లేదా పిగ్డిన్');
INSERT INTO "country" ("id", "name") VALUES ('mus', 'క్రీక్');
INSERT INTO "country" ("id", "name") VALUES ('hr', 'క్రొయెషియన్');
INSERT INTO "country" ("id", "name") VALUES ('tlh', 'క్లింగన్');
INSERT INTO "country" ("id", "name") VALUES ('kj', 'క్వాన్యామ');
INSERT INTO "country" ("id", "name") VALUES ('kho', 'ఖటోనీస్');
INSERT INTO "country" ("id", "name") VALUES ('km', 'ఖమ్ర్');
INSERT INTO "country" ("id", "name") VALUES ('kha', 'ఖాసి');
INSERT INTO "country" ("id", "name") VALUES ('khi', 'ఖోఇసన్ భాష');
INSERT INTO "country" ("id", "name") VALUES ('gaa', 'గా');
INSERT INTO "country" ("id", "name") VALUES ('lg', 'గాండా');
INSERT INTO "country" ("id", "name") VALUES ('gay', 'గాయో');
INSERT INTO "country" ("id", "name") VALUES ('gil', 'గిల్బర్టీస్');
INSERT INTO "country" ("id", "name") VALUES ('gu', 'గుజరాతి');
INSERT INTO "country" ("id", "name") VALUES ('gn', 'గురాని');
INSERT INTO "country" ("id", "name") VALUES ('gl', 'గెలిషియన్');
INSERT INTO "country" ("id", "name") VALUES ('gon', 'గోండి');
INSERT INTO "country" ("id", "name") VALUES ('got', 'గోథిక్');
INSERT INTO "country" ("id", "name") VALUES ('gor', 'గోరోంటలా');
INSERT INTO "country" ("id", "name") VALUES ('gba', 'గ్బాయా');
INSERT INTO "country" ("id", "name") VALUES ('el', 'గ్రీక్');
INSERT INTO "country" ("id", "name") VALUES ('grb', 'గ్రేబో');
INSERT INTO "country" ("id", "name") VALUES ('gwi', 'గ్విచిన్');
INSERT INTO "country" ("id", "name") VALUES ('de', 'ఙర్మన్');
INSERT INTO "country" ("id", "name") VALUES ('ch', 'చమర్రో');
INSERT INTO "country" ("id", "name") VALUES ('cu', 'చర్చ స్లావిక్');
INSERT INTO "country" ("id", "name") VALUES ('chg', 'చాగటై');
INSERT INTO "country" ("id", "name") VALUES ('cmc', 'చామిక్ భాష');
INSERT INTO "country" ("id", "name") VALUES ('chn', 'చినూక్ జార్గన్');
INSERT INTO "country" ("id", "name") VALUES ('chp', 'చిపెవ్యాన్');
INSERT INTO "country" ("id", "name") VALUES ('chb', 'చిబ్చా');
INSERT INTO "country" ("id", "name") VALUES ('chr', 'చిరోకి');
INSERT INTO "country" ("id", "name") VALUES ('cv', 'చువాష్');
INSERT INTO "country" ("id", "name") VALUES ('chk', 'చూకిస్');
INSERT INTO "country" ("id", "name") VALUES ('cs', 'చెక్');
INSERT INTO "country" ("id", "name") VALUES ('ce', 'చెచెన్');
INSERT INTO "country" ("id", "name") VALUES ('chy', 'చేయేన్');
INSERT INTO "country" ("id", "name") VALUES ('oj', 'చేవా');
INSERT INTO "country" ("id", "name") VALUES ('zh', 'చైనీస్');
INSERT INTO "country" ("id", "name") VALUES ('cho', 'చొచ్కతావ్');
INSERT INTO "country" ("id", "name") VALUES ('znd', 'జండే');
INSERT INTO "country" ("id", "name") VALUES ('zap', 'జపోటెక్');
INSERT INTO "country" ("id", "name") VALUES ('gem', 'జర్మేనిక్ భాష');
INSERT INTO "country" ("id", "name") VALUES ('zza', 'జాజా');
INSERT INTO "country" ("id", "name") VALUES ('ja', 'జాపనీస్');
INSERT INTO "country" ("id", "name") VALUES ('ka', 'జార్జియన్');
INSERT INTO "country" ("id", "name") VALUES ('jv', 'జావనీస్');
INSERT INTO "country" ("id", "name") VALUES ('gez', 'జీజ్');
INSERT INTO "country" ("id", "name") VALUES ('nzi', 'జీమా');
INSERT INTO "country" ("id", "name") VALUES ('zun', 'జుని');
INSERT INTO "country" ("id", "name") VALUES ('za', 'జువాన్');
INSERT INTO "country" ("id", "name") VALUES ('zu', 'జూలూ');
INSERT INTO "country" ("id", "name") VALUES ('zen', 'జెనాగా');
INSERT INTO "country" ("id", "name") VALUES ('dz', 'జొన్ఖా');
INSERT INTO "country" ("id", "name") VALUES ('jrb', 'జ్యుడియో-అరబిక్');
INSERT INTO "country" ("id", "name") VALUES ('jpr', 'జ్యుడియో-పర్షియన్');
INSERT INTO "country" ("id", "name") VALUES ('kaj', 'జ్యూ');
INSERT INTO "country" ("id", "name") VALUES ('tum', 'టంబుక');
INSERT INTO "country" ("id", "name") VALUES ('tr', 'టర్కిష్');
INSERT INTO "country" ("id", "name") VALUES ('tt', 'టాటర్');
INSERT INTO "country" ("id", "name") VALUES ('tmh', 'టామషేక్');
INSERT INTO "country" ("id", "name") VALUES ('tem', 'టింనే');
INSERT INTO "country" ("id", "name") VALUES ('bo', 'టిబెటన్');
INSERT INTO "country" ("id", "name") VALUES ('tiv', 'టివ్');
INSERT INTO "country" ("id", "name") VALUES ('tig', 'టీగ్రె');
INSERT INTO "country" ("id", "name") VALUES ('tup', 'టుపి భాష');
INSERT INTO "country" ("id", "name") VALUES ('tvl', 'టువాలు');
INSERT INTO "country" ("id", "name") VALUES ('tyv', 'టువినియన్');
INSERT INTO "country" ("id", "name") VALUES ('ter', 'టెరెనో');
INSERT INTO "country" ("id", "name") VALUES ('tet', 'టేటం');
INSERT INTO "country" ("id", "name") VALUES ('tai', 'టై భాష');
INSERT INTO "country" ("id", "name") VALUES ('to', 'టోంగా');
INSERT INTO "country" ("id", "name") VALUES ('tkl', 'టోకెలావ్');
INSERT INTO "country" ("id", "name") VALUES ('tpi', 'టోక్ పిసిన్');
INSERT INTO "country" ("id", "name") VALUES ('kcg', 'ట్యాప్');
INSERT INTO "country" ("id", "name") VALUES ('tw', 'ట్వి');
INSERT INTO "country" ("id", "name") VALUES ('dak', 'డకోటా');
INSERT INTO "country" ("id", "name") VALUES ('nl', 'డచ్');
INSERT INTO "country" ("id", "name") VALUES ('dar', 'డార్గ్వా');
INSERT INTO "country" ("id", "name") VALUES ('din', 'డింకా');
INSERT INTO "country" ("id", "name") VALUES ('del', 'డెలావేర్');
INSERT INTO "country" ("id", "name") VALUES ('da', 'డేనిష్');
INSERT INTO "country" ("id", "name") VALUES ('doi', 'డోగ్రి');
INSERT INTO "country" ("id", "name") VALUES ('dgr', 'డోగ్రిబ్');
INSERT INTO "country" ("id", "name") VALUES ('dyu', 'డ్యులా');
INSERT INTO "country" ("id", "name") VALUES ('tl', 'తగలోగ్');
INSERT INTO "country" ("id", "name") VALUES ('ta', 'తమిళము');
INSERT INTO "country" ("id", "name") VALUES ('ty', 'తహితియన్');
INSERT INTO "country" ("id", "name") VALUES ('tg', 'తాజిక్');
INSERT INTO "country" ("id", "name") VALUES ('ti', 'తిగ్రిన్యా');
INSERT INTO "country" ("id", "name") VALUES ('tk', 'తుర్కమెన్');
INSERT INTO "country" ("id", "name") VALUES ('frs', 'తూర్పు ఫ్రిసియన్');
INSERT INTO "country" ("id", "name") VALUES ('und', 'తెలియని లేదా చెల్లని భాష');
INSERT INTO "country" ("id", "name") VALUES ('te', 'తెలుగు');
INSERT INTO "country" ("id", "name") VALUES ('th', 'థాయ్');
INSERT INTO "country" ("id", "name") VALUES ('sai', 'దక్షిణ అమెరికా ఇండియన్ భాష');
INSERT INTO "country" ("id", "name") VALUES ('alt', 'దక్షిణ ఆల్టై');
INSERT INTO "country" ("id", "name") VALUES ('nr', 'దక్షిణ దెబెలె');
INSERT INTO "country" ("id", "name") VALUES ('sma', 'దక్షిణ సామి');
INSERT INTO "country" ("id", "name") VALUES ('st', 'దక్షిణ సోతో');
INSERT INTO "country" ("id", "name") VALUES ('day', 'దయక్');
INSERT INTO "country" ("id", "name") VALUES ('dv', 'దివేహి');
INSERT INTO "country" ("id", "name") VALUES ('dua', 'దుఆలా');
INSERT INTO "country" ("id", "name") VALUES ('ng', 'దోంగా');
INSERT INTO "country" ("id", "name") VALUES ('dra', 'ద్రవిడియన్ భాష');
INSERT INTO "country" ("id", "name") VALUES ('nv', 'నవాహో');
INSERT INTO "country" ("id", "name") VALUES ('no', 'నార్విజియాన్');
INSERT INTO "country" ("id", "name") VALUES ('nn', 'నార్విజియాన్ న్యోర్స్క్');
INSERT INTO "country" ("id", "name") VALUES ('nb', 'నార్వీజియన్ బొక్మాల్');
INSERT INTO "country" ("id", "name") VALUES ('nah', 'నాహుఅటిల్');
INSERT INTO "country" ("id", "name") VALUES ('nyo', 'నిఓరో');
INSERT INTO "country" ("id", "name") VALUES ('nap', 'నియాపోలిటన్');
INSERT INTO "country" ("id", "name") VALUES ('nia', 'నియాస్');
INSERT INTO "country" ("id", "name") VALUES ('niu', 'నియూఇయాన్');
INSERT INTO "country" ("id", "name") VALUES ('ssa', 'నీలో సహారా భాష');
INSERT INTO "country" ("id", "name") VALUES ('nub', 'నూబియన్ భాష');
INSERT INTO "country" ("id", "name") VALUES ('new', 'నెవారి');
INSERT INTO "country" ("id", "name") VALUES ('ne', 'నేపాలి');
INSERT INTO "country" ("id", "name") VALUES ('nic', 'నైజర్- కోర్దోఫియన్ భాష');
INSERT INTO "country" ("id", "name") VALUES ('nog', 'నోగై');
INSERT INTO "country" ("id", "name") VALUES ('na', 'నౌరు');
INSERT INTO "country" ("id", "name") VALUES ('nqo', 'న్కో');
INSERT INTO "country" ("id", "name") VALUES ('nym', 'న్యంవేజి');
INSERT INTO "country" ("id", "name") VALUES ('nyn', 'న్యాన్కోలె');
INSERT INTO "country" ("id", "name") VALUES ('ny', 'న్యాన్జా');
INSERT INTO "country" ("id", "name") VALUES ('tog', 'న్యాసా టోన్గా');
INSERT INTO "country" ("id", "name") VALUES ('pag', 'పంగా సినాన్');
INSERT INTO "country" ("id", "name") VALUES ('pa', 'పంజాబీ');
INSERT INTO "country" ("id", "name") VALUES ('pam', 'పంపగ్న');
INSERT INTO "country" ("id", "name") VALUES ('pap', 'పపియమేంటో');
INSERT INTO "country" ("id", "name") VALUES ('fa', 'పర్షియన్');
INSERT INTO "country" ("id", "name") VALUES ('fy', 'పశ్చిమ ఫ్రిసియన్');
INSERT INTO "country" ("id", "name") VALUES ('pal', 'పహ్లావి');
INSERT INTO "country" ("id", "name") VALUES ('paa', 'పాపుఅన్ భాష');
INSERT INTO "country" ("id", "name") VALUES ('pi', 'పాలీ');
INSERT INTO "country" ("id", "name") VALUES ('pau', 'పాలుఆన్');
INSERT INTO "country" ("id", "name") VALUES ('ps', 'పాష్టో');
INSERT INTO "country" ("id", "name") VALUES ('kpe', 'పెల్లే');
INSERT INTO "country" ("id", "name") VALUES ('pt', 'పోర్చుగీస్');
INSERT INTO "country" ("id", "name") VALUES ('cpp', 'పోర్చుగీస్ -ఆధారిత క్రియోల్ లేదా పిగ్డిన్');
INSERT INTO "country" ("id", "name") VALUES ('pl', 'పోలిష్');
INSERT INTO "country" ("id", "name") VALUES ('pon', 'పోహ్న్పెయన్');
INSERT INTO "country" ("id", "name") VALUES ('pra', 'ప్రాక్రిత్ భాష');
INSERT INTO "country" ("id", "name") VALUES ('non', 'ప్రాచిన నోర్స్');
INSERT INTO "country" ("id", "name") VALUES ('ang', 'ప్రాచీన ఆగ్లం');
INSERT INTO "country" ("id", "name") VALUES ('egy', 'ప్రాచీన ఇజిప్షియన్');
INSERT INTO "country" ("id", "name") VALUES ('sga', 'ప్రాచీన ఐరిష్');
INSERT INTO "country" ("id", "name") VALUES ('grc', 'ప్రాచీన గ్రీక్');
INSERT INTO "country" ("id", "name") VALUES ('peo', 'ప్రాచీన పర్షియన్');
INSERT INTO "country" ("id", "name") VALUES ('fro', 'ప్రాచీన ప్రెంచ్');
INSERT INTO "country" ("id", "name") VALUES ('pro', 'ప్రాచీన ప్రోవెంసాల్');
INSERT INTO "country" ("id", "name") VALUES ('goh', 'ప్రాచీన హై జర్మన్');
INSERT INTO "country" ("id", "name") VALUES ('cpf', 'ప్రెంచ్ -ఆధారిత క్రియోల్ లేదా పిగ్డిన్');
INSERT INTO "country" ("id", "name") VALUES ('fan', 'ఫాంగ్');
INSERT INTO "country" ("id", "name") VALUES ('fat', 'ఫాంటి');
INSERT INTO "country" ("id", "name") VALUES ('fon', 'ఫాన్');
INSERT INTO "country" ("id", "name") VALUES ('fo', 'ఫారొఈస్');
INSERT INTO "country" ("id", "name") VALUES ('fj', 'ఫిజియన్');
INSERT INTO "country" ("id", "name") VALUES ('fi', 'ఫిన్నిష్');
INSERT INTO "country" ("id", "name") VALUES ('fiu', 'ఫిన్నో- యుగ్రియన్ భాష');
INSERT INTO "country" ("id", "name") VALUES ('fil', 'ఫిలిపినో');
INSERT INTO "country" ("id", "name") VALUES ('phi', 'ఫిలిప్పీన్ భాష');
INSERT INTO "country" ("id", "name") VALUES ('phn', 'ఫోనికన్');
INSERT INTO "country" ("id", "name") VALUES ('ff', 'ఫ్యుల');
INSERT INTO "country" ("id", "name") VALUES ('fur', 'ఫ్రియులియన్');
INSERT INTO "country" ("id", "name") VALUES ('fr', 'ఫ్రెంచ్');
INSERT INTO "country" ("id", "name") VALUES ('nl_BE', 'ఫ్లెమిష్');
INSERT INTO "country" ("id", "name") VALUES ('bnt', 'బంటు');
INSERT INTO "country" ("id", "name") VALUES ('bm', 'బంబారా');
INSERT INTO "country" ("id", "name") VALUES ('btk', 'బటక్');
INSERT INTO "country" ("id", "name") VALUES ('bai', 'బమిలేకే భాష');
INSERT INTO "country" ("id", "name") VALUES ('my', 'బర్మీస్');
INSERT INTO "country" ("id", "name") VALUES ('bg', 'బల్గేరియన్');
INSERT INTO "country" ("id", "name") VALUES ('ba', 'బష్కిర్');
INSERT INTO "country" ("id", "name") VALUES ('bas', 'బసా');
INSERT INTO "country" ("id", "name") VALUES ('bad', 'బాండా');
INSERT INTO "country" ("id", "name") VALUES ('ban', 'బాలినీస్');
INSERT INTO "country" ("id", "name") VALUES ('bal', 'బాలుచి');
INSERT INTO "country" ("id", "name") VALUES ('bat', 'బాల్టిక్ భాష');
INSERT INTO "country" ("id", "name") VALUES ('eu', 'బాస్క్');
INSERT INTO "country" ("id", "name") VALUES ('bs', 'బాస్నియన్');
INSERT INTO "country" ("id", "name") VALUES ('bik', 'బికోల్');
INSERT INTO "country" ("id", "name") VALUES ('bin', 'బిని');
INSERT INTO "country" ("id", "name") VALUES ('bi', 'బిస్లామా');
INSERT INTO "country" ("id", "name") VALUES ('bh', 'బిహారి');
INSERT INTO "country" ("id", "name") VALUES ('bua', 'బురియట్');
INSERT INTO "country" ("id", "name") VALUES ('bn', 'బెంగాలి');
INSERT INTO "country" ("id", "name") VALUES ('bem', 'బెంబా');
INSERT INTO "country" ("id", "name") VALUES ('ber', 'బెర్బెర్');
INSERT INTO "country" ("id", "name") VALUES ('be', 'బెలరుశియన్');
INSERT INTO "country" ("id", "name") VALUES ('bej', 'బేజా');
INSERT INTO "country" ("id", "name") VALUES ('bug', 'బ్యుగినిస్');
INSERT INTO "country" ("id", "name") VALUES ('bra', 'బ్రాజ్');
INSERT INTO "country" ("id", "name") VALUES ('en_GB', 'బ్రిటిష్ ఇంగ్లీష్');
INSERT INTO "country" ("id", "name") VALUES ('pt_BR', 'బ్రెజీలియన్ పోర్చుగీస్');
INSERT INTO "country" ("id", "name") VALUES ('br', 'బ్రెటన్');
INSERT INTO "country" ("id", "name") VALUES ('byn', 'బ్లిన్');
INSERT INTO "country" ("id", "name") VALUES ('zbl', 'బ్లిసింబల్స్');
INSERT INTO "country" ("id", "name") VALUES ('inc', 'భారతీయ భాష');
INSERT INTO "country" ("id", "name") VALUES ('bho', 'భోజ్ పూరి');
INSERT INTO "country" ("id", "name") VALUES ('gv', 'మంకస్');
INSERT INTO "country" ("id", "name") VALUES ('mn', 'మంగోలియన్');
INSERT INTO "country" ("id", "name") VALUES ('mnc', 'మంచు');
INSERT INTO "country" ("id", "name") VALUES ('mdr', 'మండార్');
INSERT INTO "country" ("id", "name") VALUES ('man', 'మండింగో');
INSERT INTO "country" ("id", "name") VALUES ('mak', 'మకాసార్');
INSERT INTO "country" ("id", "name") VALUES ('mag', 'మగాహి');
INSERT INTO "country" ("id", "name") VALUES ('mni', 'మణిపూరి');
INSERT INTO "country" ("id", "name") VALUES ('cai', 'మధ్య అమెరికెన్ ఇండియన్ భాష');
INSERT INTO "country" ("id", "name") VALUES ('enm', 'మధ్యమ ఆంగ్లం');
INSERT INTO "country" ("id", "name") VALUES ('mga', 'మధ్యమ ఐరిష్');
INSERT INTO "country" ("id", "name") VALUES ('dum', 'మధ్యమ డచ్');
INSERT INTO "country" ("id", "name") VALUES ('frm', 'మధ్యమ ప్రెంచ్');
INSERT INTO "country" ("id", "name") VALUES ('gmh', 'మధ్యమ హై జర్మన్');
INSERT INTO "country" ("id", "name") VALUES ('mno', 'మనోబో భాష');
INSERT INTO "country" ("id", "name") VALUES ('mi', 'మయోరి');
INSERT INTO "country" ("id", "name") VALUES ('mr', 'మరాటి');
INSERT INTO "country" ("id", "name") VALUES ('ml', 'మలయాళం');
INSERT INTO "country" ("id", "name") VALUES ('ms', 'మలేయ్');
INSERT INTO "country" ("id", "name") VALUES ('mk', 'మసడోనియన్');
INSERT INTO "country" ("id", "name") VALUES ('mad', 'మాదురీస్');
INSERT INTO "country" ("id", "name") VALUES ('myn', 'మాయన్ భాష');
INSERT INTO "country" ("id", "name") VALUES ('chm', 'మారి');
INSERT INTO "country" ("id", "name") VALUES ('mwr', 'మార్వాడి');
INSERT INTO "country" ("id", "name") VALUES ('mh', 'మార్షలీస్');
INSERT INTO "country" ("id", "name") VALUES ('mg', 'మాలాగసి');
INSERT INTO "country" ("id", "name") VALUES ('mt', 'మాల్టీస్');
INSERT INTO "country" ("id", "name") VALUES ('mas', 'మాసాయి');
INSERT INTO "country" ("id", "name") VALUES ('mic', 'మికమాక్');
INSERT INTO "country" ("id", "name") VALUES ('min', 'మినాంగ్కాబో');
INSERT INTO "country" ("id", "name") VALUES ('mwl', 'మిరాండిస్');
INSERT INTO "country" ("id", "name") VALUES ('mis', 'మిశ్రమ భాష');
INSERT INTO "country" ("id", "name") VALUES ('mun', 'ముండ భాష');
INSERT INTO "country" ("id", "name") VALUES ('men', 'మెండే');
INSERT INTO "country" ("id", "name") VALUES ('mai', 'మైథిలి');
INSERT INTO "country" ("id", "name") VALUES ('lol', 'మొంగో');
INSERT INTO "country" ("id", "name") VALUES ('mdf', 'మొక్షా');
INSERT INTO "country" ("id", "name") VALUES ('mo', 'మొల్డావియన్');
INSERT INTO "country" ("id", "name") VALUES ('hmn', 'మోంగ్');
INSERT INTO "country" ("id", "name") VALUES ('mkh', 'మోన్-ఖ్మేర్ భాష');
INSERT INTO "country" ("id", "name") VALUES ('mos', 'మోస్సి');
INSERT INTO "country" ("id", "name") VALUES ('moh', 'మోహుక్');
INSERT INTO "country" ("id", "name") VALUES ('yao', 'యాఒ');
INSERT INTO "country" ("id", "name") VALUES ('sah', 'యాకుట్');
INSERT INTO "country" ("id", "name") VALUES ('yap', 'యాపిస్');
INSERT INTO "country" ("id", "name") VALUES ('yi', 'యిడ్డిష్');
INSERT INTO "country" ("id", "name") VALUES ('en_US', 'యు.ఎస్ ఇంగ్లీష్');
INSERT INTO "country" ("id", "name") VALUES ('uk', 'యుక్రేనియాన్');
INSERT INTO "country" ("id", "name") VALUES ('ypk', 'యుపిక్ భాష');
INSERT INTO "country" ("id", "name") VALUES ('yo', 'యోరుబా');
INSERT INTO "country" ("id", "name") VALUES ('rn', 'రండి');
INSERT INTO "country" ("id", "name") VALUES ('ru', 'రష్యన్');
INSERT INTO "country" ("id", "name") VALUES ('raj', 'రాజస్తాని');
INSERT INTO "country" ("id", "name") VALUES ('rap', 'రాపన్యుయి');
INSERT INTO "country" ("id", "name") VALUES ('rar', 'రారోటొంగాన్');
INSERT INTO "country" ("id", "name") VALUES ('root', 'రూట్');
INSERT INTO "country" ("id", "name") VALUES ('ro', 'రోమానియన్');
INSERT INTO "country" ("id", "name") VALUES ('rom', 'రోమానీ');
INSERT INTO "country" ("id", "name") VALUES ('roa', 'రోమాన్స్ భాష');
INSERT INTO "country" ("id", "name") VALUES ('rm', 'ర్హెతో-రోమాన్స్');
INSERT INTO "country" ("id", "name") VALUES ('lo', 'లాఓ');
INSERT INTO "country" ("id", "name") VALUES ('lam', 'లాంబా');
INSERT INTO "country" ("id", "name") VALUES ('la', 'లాటిన్');
INSERT INTO "country" ("id", "name") VALUES ('es_419', 'లాటిన్ అమెరికెన్ స్పానిష్');
INSERT INTO "country" ("id", "name") VALUES ('lv', 'లాట్వియన్');
INSERT INTO "country" ("id", "name") VALUES ('lad', 'లాడినో');
INSERT INTO "country" ("id", "name") VALUES ('lah', 'లాహండా');
INSERT INTO "country" ("id", "name") VALUES ('ln', 'లింగాల');
INSERT INTO "country" ("id", "name") VALUES ('tli', 'లింగిట్');
INSERT INTO "country" ("id", "name") VALUES ('lt', 'లిథుయేనియన్');
INSERT INTO "country" ("id", "name") VALUES ('li', 'లిమ్బర్గిష్');
INSERT INTO "country" ("id", "name") VALUES ('lui', 'లుఇసేనో');
INSERT INTO "country" ("id", "name") VALUES ('lun', 'లుండా');
INSERT INTO "country" ("id", "name") VALUES ('lb', 'లుక్సంబర్గిష్');
INSERT INTO "country" ("id", "name") VALUES ('smj', 'లులే సామి');
INSERT INTO "country" ("id", "name") VALUES ('luo', 'లువో');
INSERT INTO "country" ("id", "name") VALUES ('lus', 'లుషై');
INSERT INTO "country" ("id", "name") VALUES ('lu', 'లూబ-కటాంగ');
INSERT INTO "country" ("id", "name") VALUES ('lua', 'లూబా- లులుయా');
INSERT INTO "country" ("id", "name") VALUES ('lez', 'లేజ్ఘియన్');
INSERT INTO "country" ("id", "name") VALUES ('nds', 'లో జర్మన్');
INSERT INTO "country" ("id", "name") VALUES ('loz', 'లోజి');
INSERT INTO "country" ("id", "name") VALUES ('jbo', 'లోజ్బాన్');
INSERT INTO "country" ("id", "name") VALUES ('dsb', 'లోవర్ సోర్బియన్');
INSERT INTO "country" ("id", "name") VALUES ('wak', 'వాక్షన్ భాష');
INSERT INTO "country" ("id", "name") VALUES ('vai', 'వాయి');
INSERT INTO "country" ("id", "name") VALUES ('war', 'వారే');
INSERT INTO "country" ("id", "name") VALUES ('wal', 'వాలామో');
INSERT INTO "country" ("id", "name") VALUES ('wa', 'వాలూన్');
INSERT INTO "country" ("id", "name") VALUES ('was', 'వాషో');
INSERT INTO "country" ("id", "name") VALUES ('vi', 'వియత్నామీస్');
INSERT INTO "country" ("id", "name") VALUES ('ve', 'వెండా');
INSERT INTO "country" ("id", "name") VALUES ('cy', 'వెల్ష్');
INSERT INTO "country" ("id", "name") VALUES ('wo', 'వొలాఫ్');
INSERT INTO "country" ("id", "name") VALUES ('vot', 'వోటిక్');
INSERT INTO "country" ("id", "name") VALUES ('vo', 'వోలాపుక్');
INSERT INTO "country" ("id", "name") VALUES ('tsi', 'శింషీయన్');
INSERT INTO "country" ("id", "name") VALUES ('ii', 'శిషువన్ ఈ');
INSERT INTO "country" ("id", "name") VALUES ('shn', 'షాన్');
INSERT INTO "country" ("id", "name") VALUES ('sio', 'షిఒయన్ భాష');
INSERT INTO "country" ("id", "name") VALUES ('sn', 'షోన');
INSERT INTO "country" ("id", "name") VALUES ('xh', 'షోసా');
INSERT INTO "country" ("id", "name") VALUES ('sgn', 'సంజ్ఞ భాష');
INSERT INTO "country" ("id", "name") VALUES ('sat', 'సంటాలి');
INSERT INTO "country" ("id", "name") VALUES ('sad', 'సండావి');
INSERT INTO "country" ("id", "name") VALUES ('sa', 'సంసృతం');
INSERT INTO "country" ("id", "name") VALUES ('sam', 'సమారిటన్ అరమేక్');
INSERT INTO "country" ("id", "name") VALUES ('sm', 'సమోవన్');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hans', 'సరళీకృత చైనీస్');
INSERT INTO "country" ("id", "name") VALUES ('sas', 'ససక్');
INSERT INTO "country" ("id", "name") VALUES ('sg', 'సాంగో');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hant', 'సాంప్రదాయ చైనీస్');
INSERT INTO "country" ("id", "name") VALUES ('nwc', 'సాంప్రదాయ న్యుఆరి');
INSERT INTO "country" ("id", "name") VALUES ('syc', 'సాంప్రదాయ సిరియాక్');
INSERT INTO "country" ("id", "name") VALUES ('smi', 'సామి భాష');
INSERT INTO "country" ("id", "name") VALUES ('sc', 'సార్డీనియన్');
INSERT INTO "country" ("id", "name") VALUES ('sal', 'సాలిషాన్ భాష');
INSERT INTO "country" ("id", "name") VALUES ('sd', 'సింధీ');
INSERT INTO "country" ("id", "name") VALUES ('si', 'సింహాల');
INSERT INTO "country" ("id", "name") VALUES ('bla', 'సిక్ సికా');
INSERT INTO "country" ("id", "name") VALUES ('sid', 'సిడామో');
INSERT INTO "country" ("id", "name") VALUES ('syr', 'సిరియాక్');
INSERT INTO "country" ("id", "name") VALUES ('scn', 'సిసిలియన్');
INSERT INTO "country" ("id", "name") VALUES ('suk', 'సుకుమా');
INSERT INTO "country" ("id", "name") VALUES ('su', 'సుడానీస్');
INSERT INTO "country" ("id", "name") VALUES ('sux', 'సుమేరియాన్');
INSERT INTO "country" ("id", "name") VALUES ('sus', 'సుసు');
INSERT INTO "country" ("id", "name") VALUES ('tn', 'సెటస్వానా');
INSERT INTO "country" ("id", "name") VALUES ('sem', 'సెమిటిక్ భాష');
INSERT INTO "country" ("id", "name") VALUES ('srr', 'సెరేర్');
INSERT INTO "country" ("id", "name") VALUES ('sr', 'సెర్బియన్');
INSERT INTO "country" ("id", "name") VALUES ('cel', 'సెల్టిక్ భాష');
INSERT INTO "country" ("id", "name") VALUES ('ceb', 'సేబుఆనో');
INSERT INTO "country" ("id", "name") VALUES ('sh', 'సేర్బో-క్రొయేషియన్');
INSERT INTO "country" ("id", "name") VALUES ('sel', 'సేల్కప్');
INSERT INTO "country" ("id", "name") VALUES ('sit', 'సైనో- టిబిటన్ భాష');
INSERT INTO "country" ("id", "name") VALUES ('son', 'సొంఘై');
INSERT INTO "country" ("id", "name") VALUES ('ts', 'సోంగా');
INSERT INTO "country" ("id", "name") VALUES ('sog', 'సోగ్డియన్');
INSERT INTO "country" ("id", "name") VALUES ('snk', 'సోనింకి');
INSERT INTO "country" ("id", "name") VALUES ('so', 'సోమాలి');
INSERT INTO "country" ("id", "name") VALUES ('wen', 'సోర్బియన్ భాష');
INSERT INTO "country" ("id", "name") VALUES ('gd', 'స్కాటిష్ గేలిక్');
INSERT INTO "country" ("id", "name") VALUES ('sco', 'స్కాట్స్');
INSERT INTO "country" ("id", "name") VALUES ('sms', 'స్కోల్ట్ సామి');
INSERT INTO "country" ("id", "name") VALUES ('es', 'స్పానిష్');
INSERT INTO "country" ("id", "name") VALUES ('srn', 'స్రానన్ టోనగో');
INSERT INTO "country" ("id", "name") VALUES ('sla', 'స్లావిక్ భాష');
INSERT INTO "country" ("id", "name") VALUES ('den', 'స్లేవ్');
INSERT INTO "country" ("id", "name") VALUES ('sk', 'స్లోవాక్');
INSERT INTO "country" ("id", "name") VALUES ('sl', 'స్లోవేనియాన్');
INSERT INTO "country" ("id", "name") VALUES ('ss', 'స్వాతి');
INSERT INTO "country" ("id", "name") VALUES ('sw', 'స్వాహిలి');
INSERT INTO "country" ("id", "name") VALUES ('gsw', 'స్విస్ జర్మన్');
INSERT INTO "country" ("id", "name") VALUES ('fr_CH', 'స్విస్ ఫ్రెంచ్');
INSERT INTO "country" ("id", "name") VALUES ('de_CH', 'స్విస్ హై జర్మన్');
INSERT INTO "country" ("id", "name") VALUES ('sv', 'స్వీడిష్');
INSERT INTO "country" ("id", "name") VALUES ('hu', 'హన్గేరియన్');
INSERT INTO "country" ("id", "name") VALUES ('haw', 'హవాయియన్');
INSERT INTO "country" ("id", "name") VALUES ('hi', 'హిందీ');
INSERT INTO "country" ("id", "name") VALUES ('hit', 'హిట్టిటే');
INSERT INTO "country" ("id", "name") VALUES ('him', 'హిమాచలి');
INSERT INTO "country" ("id", "name") VALUES ('ho', 'హిరి మోటు');
INSERT INTO "country" ("id", "name") VALUES ('hz', 'హిరేరో');
INSERT INTO "country" ("id", "name") VALUES ('hil', 'హిలి గేయినోన్');
INSERT INTO "country" ("id", "name") VALUES ('he', 'హీబ్రు');
INSERT INTO "country" ("id", "name") VALUES ('hup', 'హుపా');
INSERT INTO "country" ("id", "name") VALUES ('hai', 'హైడా');
INSERT INTO "country" ("id", "name") VALUES ('ht', 'హైయేతియన్');
INSERT INTO "country" ("id", "name") VALUES ('ha', 'హౌసా');
