CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('ab', 'Abchaasch');
INSERT INTO `country` (`id`, `name`) VALUES ('ace', 'Aceh');
INSERT INTO `country` (`id`, `name`) VALUES ('ach', 'Acholi');
INSERT INTO `country` (`id`, `name`) VALUES ('ada', 'Adangme');
INSERT INTO `country` (`id`, `name`) VALUES ('ady', 'Adygeisch');
INSERT INTO `country` (`id`, `name`) VALUES ('aa', 'Afar');
INSERT INTO `country` (`id`, `name`) VALUES ('afh', 'Afrihili');
INSERT INTO `country` (`id`, `name`) VALUES ('af', 'Afrikaansch');
INSERT INTO `country` (`id`, `name`) VALUES ('afa', 'Afro-Asiaatsche Spraken');
INSERT INTO `country` (`id`, `name`) VALUES ('ain', 'Ainu');
INSERT INTO `country` (`id`, `name`) VALUES ('ak', 'Akan');
INSERT INTO `country` (`id`, `name`) VALUES ('akk', 'Akkadsch');
INSERT INTO `country` (`id`, `name`) VALUES ('sq', 'Albaansch');
INSERT INTO `country` (`id`, `name`) VALUES ('ale', 'Aleutsch');
INSERT INTO `country` (`id`, `name`) VALUES ('alg', 'Algonkin-Spraken');
INSERT INTO `country` (`id`, `name`) VALUES ('tut', 'Altaische Spraken');
INSERT INTO `country` (`id`, `name`) VALUES ('en_US', 'Amerikaansch Engelsch');
INSERT INTO `country` (`id`, `name`) VALUES ('am', 'Amhaarsch');
INSERT INTO `country` (`id`, `name`) VALUES ('anp', 'Angika');
INSERT INTO `country` (`id`, `name`) VALUES ('apa', 'Apache');
INSERT INTO `country` (`id`, `name`) VALUES ('ar', 'Araabsch');
INSERT INTO `country` (`id`, `name`) VALUES ('an', 'Aragoneesch');
INSERT INTO `country` (`id`, `name`) VALUES ('arc', 'Aramääsch');
INSERT INTO `country` (`id`, `name`) VALUES ('arp', 'Arapaho');
INSERT INTO `country` (`id`, `name`) VALUES ('arn', 'Araukaansch');
INSERT INTO `country` (`id`, `name`) VALUES ('arw', 'Arawak-Spraken');
INSERT INTO `country` (`id`, `name`) VALUES ('hy', 'Armeensch');
INSERT INTO `country` (`id`, `name`) VALUES ('rup', 'Aromuunsch');
INSERT INTO `country` (`id`, `name`) VALUES ('az', 'Aserbaidschaansch');
INSERT INTO `country` (`id`, `name`) VALUES ('as', 'Assameesch');
INSERT INTO `country` (`id`, `name`) VALUES ('ast', 'Asturiaansch');
INSERT INTO `country` (`id`, `name`) VALUES ('ath', 'Athabasksche Spraken');
INSERT INTO `country` (`id`, `name`) VALUES ('cch', 'Atsam');
INSERT INTO `country` (`id`, `name`) VALUES ('en_AU', 'Austraalsch Engelsch');
INSERT INTO `country` (`id`, `name`) VALUES ('aus', 'Austraalsche Spraken');
INSERT INTO `country` (`id`, `name`) VALUES ('map', 'Austroneesche Spraken');
INSERT INTO `country` (`id`, `name`) VALUES ('ae', 'Avestsch');
INSERT INTO `country` (`id`, `name`) VALUES ('av', 'Awaarsch');
INSERT INTO `country` (`id`, `name`) VALUES ('awa', 'Awadhi');
INSERT INTO `country` (`id`, `name`) VALUES ('ay', 'Aymara');
INSERT INTO `country` (`id`, `name`) VALUES ('ban', 'Balineesch');
INSERT INTO `country` (`id`, `name`) VALUES ('bat', 'Baltsche Spraken');
INSERT INTO `country` (`id`, `name`) VALUES ('bm', 'Bambara');
INSERT INTO `country` (`id`, `name`) VALUES ('bai', 'Bamileke');
INSERT INTO `country` (`id`, `name`) VALUES ('bad', 'Banda');
INSERT INTO `country` (`id`, `name`) VALUES ('bnt', 'Bantuspraken');
INSERT INTO `country` (`id`, `name`) VALUES ('bas', 'Basaa');
INSERT INTO `country` (`id`, `name`) VALUES ('ba', 'Baschkiersch');
INSERT INTO `country` (`id`, `name`) VALUES ('eu', 'Basksch');
INSERT INTO `country` (`id`, `name`) VALUES ('btk', 'Batak');
INSERT INTO `country` (`id`, `name`) VALUES ('bej', 'Bedscha');
INSERT INTO `country` (`id`, `name`) VALUES ('bal', 'Belutschisch');
INSERT INTO `country` (`id`, `name`) VALUES ('bem', 'Bemba');
INSERT INTO `country` (`id`, `name`) VALUES ('bn', 'Bengaalsch');
INSERT INTO `country` (`id`, `name`) VALUES ('ber', 'Berberspraken');
INSERT INTO `country` (`id`, `name`) VALUES ('bho', 'Bhodschpuri');
INSERT INTO `country` (`id`, `name`) VALUES ('dz', 'Bhutaansch');
INSERT INTO `country` (`id`, `name`) VALUES ('bh', 'Bihaarsch');
INSERT INTO `country` (`id`, `name`) VALUES ('bik', 'Bikol');
INSERT INTO `country` (`id`, `name`) VALUES ('bin', 'Bini');
INSERT INTO `country` (`id`, `name`) VALUES ('my', 'Birmaansch');
INSERT INTO `country` (`id`, `name`) VALUES ('bi', 'Bislama');
INSERT INTO `country` (`id`, `name`) VALUES ('byn', 'Blin');
INSERT INTO `country` (`id`, `name`) VALUES ('zbl', 'Bliss-Symbolen');
INSERT INTO `country` (`id`, `name`) VALUES ('bs', 'Bosnisch');
INSERT INTO `country` (`id`, `name`) VALUES ('bra', 'Braj-Bhakha');
INSERT INTO `country` (`id`, `name`) VALUES ('pt_BR', 'Brasiliaansch Portugeesch');
INSERT INTO `country` (`id`, `name`) VALUES ('br', 'Bretoonsch');
INSERT INTO `country` (`id`, `name`) VALUES ('en_GB', 'Brietsch Engelsch');
INSERT INTO `country` (`id`, `name`) VALUES ('bug', 'Bugineesch');
INSERT INTO `country` (`id`, `name`) VALUES ('bg', 'Bulgaarsch');
INSERT INTO `country` (`id`, `name`) VALUES ('bua', 'Burjaatsch');
INSERT INTO `country` (`id`, `name`) VALUES ('hsb', 'Böversorbsch');
INSERT INTO `country` (`id`, `name`) VALUES ('cad', 'Caddo');
INSERT INTO `country` (`id`, `name`) VALUES ('ceb', 'Cebuano');
INSERT INTO `country` (`id`, `name`) VALUES ('cmc', 'Cham-Spraken');
INSERT INTO `country` (`id`, `name`) VALUES ('ch', 'Chamorro');
INSERT INTO `country` (`id`, `name`) VALUES ('chr', 'Cherokee');
INSERT INTO `country` (`id`, `name`) VALUES ('chy', 'Cheyenne');
INSERT INTO `country` (`id`, `name`) VALUES ('chb', 'Chibcha-Spraken');
INSERT INTO `country` (`id`, `name`) VALUES ('zh', 'Chineesch');
INSERT INTO `country` (`id`, `name`) VALUES ('chn', 'Chinook');
INSERT INTO `country` (`id`, `name`) VALUES ('chp', 'Chipewyan');
INSERT INTO `country` (`id`, `name`) VALUES ('cho', 'Choctaw');
INSERT INTO `country` (`id`, `name`) VALUES ('cr', 'Cree');
INSERT INTO `country` (`id`, `name`) VALUES ('day', 'Dajak');
INSERT INTO `country` (`id`, `name`) VALUES ('dak', 'Dakota');
INSERT INTO `country` (`id`, `name`) VALUES ('dar', 'Dargiensch');
INSERT INTO `country` (`id`, `name`) VALUES ('del', 'Delaware');
INSERT INTO `country` (`id`, `name`) VALUES ('din', 'Dinka');
INSERT INTO `country` (`id`, `name`) VALUES ('doi', 'Dogri');
INSERT INTO `country` (`id`, `name`) VALUES ('dgr', 'Dogrib');
INSERT INTO `country` (`id`, `name`) VALUES ('dra', 'Drawiedsche Spraken');
INSERT INTO `country` (`id`, `name`) VALUES ('dua', 'Duala');
INSERT INTO `country` (`id`, `name`) VALUES ('dyu', 'Dyula');
INSERT INTO `country` (`id`, `name`) VALUES ('da', 'Däänsch');
INSERT INTO `country` (`id`, `name`) VALUES ('de', 'Düütsch');
INSERT INTO `country` (`id`, `name`) VALUES ('et', 'Eestnisch');
INSERT INTO `country` (`id`, `name`) VALUES ('efi', 'Efik');
INSERT INTO `country` (`id`, `name`) VALUES ('eka', 'Ekajuk');
INSERT INTO `country` (`id`, `name`) VALUES ('elx', 'Elaamsch');
INSERT INTO `country` (`id`, `name`) VALUES ('tvl', 'Elliceaansch');
INSERT INTO `country` (`id`, `name`) VALUES ('en', 'Engelsch');
INSERT INTO `country` (`id`, `name`) VALUES ('myv', 'Erzya');
INSERT INTO `country` (`id`, `name`) VALUES ('eo', 'Esperanto');
INSERT INTO `country` (`id`, `name`) VALUES ('ee', 'Ewe');
INSERT INTO `country` (`id`, `name`) VALUES ('ewo', 'Ewondo');
INSERT INTO `country` (`id`, `name`) VALUES ('fat', 'Fanti');
INSERT INTO `country` (`id`, `name`) VALUES ('fj', 'Fidschiaansch');
INSERT INTO `country` (`id`, `name`) VALUES ('fiu', 'Finnougrische Spraken');
INSERT INTO `country` (`id`, `name`) VALUES ('fi', 'Finnsch');
INSERT INTO `country` (`id`, `name`) VALUES ('nl_BE', 'Fläämsch');
INSERT INTO `country` (`id`, `name`) VALUES ('fon', 'Fon');
INSERT INTO `country` (`id`, `name`) VALUES ('fr', 'Franzöösch');
INSERT INTO `country` (`id`, `name`) VALUES ('fur', 'Friuulsch');
INSERT INTO `country` (`id`, `name`) VALUES ('ff', 'Ful');
INSERT INTO `country` (`id`, `name`) VALUES ('fo', 'Färöösch');
INSERT INTO `country` (`id`, `name`) VALUES ('gaa', 'Ga');
INSERT INTO `country` (`id`, `name`) VALUES ('gl', 'Galizisch');
INSERT INTO `country` (`id`, `name`) VALUES ('lg', 'Ganda');
INSERT INTO `country` (`id`, `name`) VALUES ('gay', 'Gayo');
INSERT INTO `country` (`id`, `name`) VALUES ('gba', 'Gbaya');
INSERT INTO `country` (`id`, `name`) VALUES ('gez', 'Geez');
INSERT INTO `country` (`id`, `name`) VALUES ('ka', 'Georgsch');
INSERT INTO `country` (`id`, `name`) VALUES ('gem', 'Germaansche Spraken');
INSERT INTO `country` (`id`, `name`) VALUES ('gil', 'Gilberteesch');
INSERT INTO `country` (`id`, `name`) VALUES ('gon', 'Gondi');
INSERT INTO `country` (`id`, `name`) VALUES ('got', 'Gootsch');
INSERT INTO `country` (`id`, `name`) VALUES ('gor', 'Gorontalo');
INSERT INTO `country` (`id`, `name`) VALUES ('grb', 'Grebo');
INSERT INTO `country` (`id`, `name`) VALUES ('el', 'Greeksch');
INSERT INTO `country` (`id`, `name`) VALUES ('kl', 'Gröönlandsch');
INSERT INTO `country` (`id`, `name`) VALUES ('gn', 'Guarani');
INSERT INTO `country` (`id`, `name`) VALUES ('gu', 'Gujarati');
INSERT INTO `country` (`id`, `name`) VALUES ('hai', 'Haida');
INSERT INTO `country` (`id`, `name`) VALUES ('ht', 'Haitiaansch-Kreoolsch');
INSERT INTO `country` (`id`, `name`) VALUES ('ha', 'Haussa');
INSERT INTO `country` (`id`, `name`) VALUES ('haw', 'Hawaiiaansch');
INSERT INTO `country` (`id`, `name`) VALUES ('he', 'Hebrääsch');
INSERT INTO `country` (`id`, `name`) VALUES ('hz', 'Herero');
INSERT INTO `country` (`id`, `name`) VALUES ('hit', 'Hethitsch');
INSERT INTO `country` (`id`, `name`) VALUES ('hil', 'Hiligaynon');
INSERT INTO `country` (`id`, `name`) VALUES ('him', 'Himachali');
INSERT INTO `country` (`id`, `name`) VALUES ('hi', 'Hindi');
INSERT INTO `country` (`id`, `name`) VALUES ('ho', 'Hiri-Motu');
INSERT INTO `country` (`id`, `name`) VALUES ('hup', 'Hupa');
INSERT INTO `country` (`id`, `name`) VALUES ('iba', 'Iban');
INSERT INTO `country` (`id`, `name`) VALUES ('pt_PT', 'Ibeersch Portugeesch');
INSERT INTO `country` (`id`, `name`) VALUES ('es_ES', 'Ibeersch Spaansch');
INSERT INTO `country` (`id`, `name`) VALUES ('io', 'Ido');
INSERT INTO `country` (`id`, `name`) VALUES ('ga', 'Iersch');
INSERT INTO `country` (`id`, `name`) VALUES ('is', 'Ieslandsch');
INSERT INTO `country` (`id`, `name`) VALUES ('ig', 'Igbo');
INSERT INTO `country` (`id`, `name`) VALUES ('ijo', 'Ijo');
INSERT INTO `country` (`id`, `name`) VALUES ('ilo', 'Ilokano');
INSERT INTO `country` (`id`, `name`) VALUES ('smn', 'Inari-Lappsch');
INSERT INTO `country` (`id`, `name`) VALUES ('nai', 'Indianerspraken in Noordamerika');
INSERT INTO `country` (`id`, `name`) VALUES ('sai', 'Indianerspraken in Süüdamerika');
INSERT INTO `country` (`id`, `name`) VALUES ('cai', 'Indianerspraken in Zentralamerika');
INSERT INTO `country` (`id`, `name`) VALUES ('inc', 'Indoarische Spraken');
INSERT INTO `country` (`id`, `name`) VALUES ('ine', 'Indogermaansche Spraken');
INSERT INTO `country` (`id`, `name`) VALUES ('id', 'Indoneesch');
INSERT INTO `country` (`id`, `name`) VALUES ('inh', 'Ingusch’sch');
INSERT INTO `country` (`id`, `name`) VALUES ('ia', 'Interlingua');
INSERT INTO `country` (`id`, `name`) VALUES ('ie', 'Interlingue');
INSERT INTO `country` (`id`, `name`) VALUES ('iu', 'Inuktitut');
INSERT INTO `country` (`id`, `name`) VALUES ('ik', 'Inupiak');
INSERT INTO `country` (`id`, `name`) VALUES ('ira', 'Iraansche Spraken');
INSERT INTO `country` (`id`, `name`) VALUES ('iro', 'Irokeesche Spraken');
INSERT INTO `country` (`id`, `name`) VALUES ('it', 'Italieensch');
INSERT INTO `country` (`id`, `name`) VALUES ('sah', 'Jakuutsch');
INSERT INTO `country` (`id`, `name`) VALUES ('ja', 'Japaansch');
INSERT INTO `country` (`id`, `name`) VALUES ('jv', 'Javaansch');
INSERT INTO `country` (`id`, `name`) VALUES ('yi', 'Jiddisch');
INSERT INTO `country` (`id`, `name`) VALUES ('kaj', 'Jju');
INSERT INTO `country` (`id`, `name`) VALUES ('jrb', 'Jöödsch-Araabsch');
INSERT INTO `country` (`id`, `name`) VALUES ('jpr', 'Jöödsch-Pers’sch');
INSERT INTO `country` (`id`, `name`) VALUES ('kbd', 'Kabardiensch');
INSERT INTO `country` (`id`, `name`) VALUES ('kab', 'Kabyylsch');
INSERT INTO `country` (`id`, `name`) VALUES ('kac', 'Kachin');
INSERT INTO `country` (`id`, `name`) VALUES ('xal', 'Kalmücksch');
INSERT INTO `country` (`id`, `name`) VALUES ('kam', 'Kamba');
INSERT INTO `country` (`id`, `name`) VALUES ('km', 'Kambodschaansch');
INSERT INTO `country` (`id`, `name`) VALUES ('en_CA', 'Kanaadsch Engelsch');
INSERT INTO `country` (`id`, `name`) VALUES ('fr_CA', 'Kanaadsch Franzöösch');
INSERT INTO `country` (`id`, `name`) VALUES ('kn', 'Kannada');
INSERT INTO `country` (`id`, `name`) VALUES ('kr', 'Kanuursch');
INSERT INTO `country` (`id`, `name`) VALUES ('kaa', 'Karakalpaksch');
INSERT INTO `country` (`id`, `name`) VALUES ('krc', 'Karatschaisch-Balkaarsch');
INSERT INTO `country` (`id`, `name`) VALUES ('krl', 'Kareelsch');
INSERT INTO `country` (`id`, `name`) VALUES ('kar', 'Kareensch');
INSERT INTO `country` (`id`, `name`) VALUES ('car', 'Kariebsche Spraken');
INSERT INTO `country` (`id`, `name`) VALUES ('cu', 'Karkenslaavsch');
INSERT INTO `country` (`id`, `name`) VALUES ('kk', 'Kasach’sch');
INSERT INTO `country` (`id`, `name`) VALUES ('ks', 'Kaschmiersch');
INSERT INTO `country` (`id`, `name`) VALUES ('csb', 'Kaschuubsch');
INSERT INTO `country` (`id`, `name`) VALUES ('ca', 'Katalaansch');
INSERT INTO `country` (`id`, `name`) VALUES ('cau', 'Kaukaasche Spraken');
INSERT INTO `country` (`id`, `name`) VALUES ('kaw', 'Kawi');
INSERT INTO `country` (`id`, `name`) VALUES ('zxx', 'Keen Spraakinhold');
INSERT INTO `country` (`id`, `name`) VALUES ('cel', 'Keltsche Spraken');
INSERT INTO `country` (`id`, `name`) VALUES ('kha', 'Khasi');
INSERT INTO `country` (`id`, `name`) VALUES ('khi', 'Khoisan-Spraken');
INSERT INTO `country` (`id`, `name`) VALUES ('ki', 'Kikuyu');
INSERT INTO `country` (`id`, `name`) VALUES ('kmb', 'Kimbundu');
INSERT INTO `country` (`id`, `name`) VALUES ('ky', 'Kirgiesch');
INSERT INTO `country` (`id`, `name`) VALUES ('tlh', 'Klingoonsch');
INSERT INTO `country` (`id`, `name`) VALUES ('kv', 'Komi');
INSERT INTO `country` (`id`, `name`) VALUES ('kg', 'Kongo');
INSERT INTO `country` (`id`, `name`) VALUES ('kok', 'Konkani');
INSERT INTO `country` (`id`, `name`) VALUES ('kw', 'Koornsch');
INSERT INTO `country` (`id`, `name`) VALUES ('co', 'Koorsch');
INSERT INTO `country` (`id`, `name`) VALUES ('cop', 'Koptsch');
INSERT INTO `country` (`id`, `name`) VALUES ('ko', 'Koreaansch');
INSERT INTO `country` (`id`, `name`) VALUES ('kfo', 'Koro');
INSERT INTO `country` (`id`, `name`) VALUES ('kos', 'Kosraeaansch');
INSERT INTO `country` (`id`, `name`) VALUES ('kpe', 'Kpelle');
INSERT INTO `country` (`id`, `name`) VALUES ('cpe', 'Kreoolsch-Engelsche Spraken');
INSERT INTO `country` (`id`, `name`) VALUES ('cpf', 'Kreoolsch-Franzöösche Spraken');
INSERT INTO `country` (`id`, `name`) VALUES ('cpp', 'Kreoolsch-Portugeesche Spraken');
INSERT INTO `country` (`id`, `name`) VALUES ('crp', 'Kreoolsche Spraken');
INSERT INTO `country` (`id`, `name`) VALUES ('crh', 'Krimtataarsch');
INSERT INTO `country` (`id`, `name`) VALUES ('hr', 'Kroaatsch');
INSERT INTO `country` (`id`, `name`) VALUES ('kro', 'Kru-Spraken');
INSERT INTO `country` (`id`, `name`) VALUES ('kum', 'Kumücksch');
INSERT INTO `country` (`id`, `name`) VALUES ('art', 'Kunstspraken');
INSERT INTO `country` (`id`, `name`) VALUES ('ku', 'Kurdsch');
INSERT INTO `country` (`id`, `name`) VALUES ('cus', 'Kuschietsche Spraken');
INSERT INTO `country` (`id`, `name`) VALUES ('gwi', 'Kutchin');
INSERT INTO `country` (`id`, `name`) VALUES ('kut', 'Kutenai');
INSERT INTO `country` (`id`, `name`) VALUES ('kj', 'Kwanyama');
INSERT INTO `country` (`id`, `name`) VALUES ('lad', 'Ladiensch');
INSERT INTO `country` (`id`, `name`) VALUES ('lah', 'Lahnda');
INSERT INTO `country` (`id`, `name`) VALUES ('lam', 'Lamba');
INSERT INTO `country` (`id`, `name`) VALUES ('lo', 'Laootsch');
INSERT INTO `country` (`id`, `name`) VALUES ('smi', 'Lappsch');
INSERT INTO `country` (`id`, `name`) VALUES ('es_419', 'Latienamerikaansch Spaansch');
INSERT INTO `country` (`id`, `name`) VALUES ('la', 'Latiensch');
INSERT INTO `country` (`id`, `name`) VALUES ('lez', 'Lesgisch');
INSERT INTO `country` (`id`, `name`) VALUES ('lv', 'Lettsch');
INSERT INTO `country` (`id`, `name`) VALUES ('li', 'Limborgsch');
INSERT INTO `country` (`id`, `name`) VALUES ('ln', 'Lingala');
INSERT INTO `country` (`id`, `name`) VALUES ('lt', 'Litausch');
INSERT INTO `country` (`id`, `name`) VALUES ('jbo', 'Lojban');
INSERT INTO `country` (`id`, `name`) VALUES ('lu', 'Luba');
INSERT INTO `country` (`id`, `name`) VALUES ('lua', 'Luba-Lulua');
INSERT INTO `country` (`id`, `name`) VALUES ('lui', 'Luiseno');
INSERT INTO `country` (`id`, `name`) VALUES ('smj', 'Lule-Lappsch');
INSERT INTO `country` (`id`, `name`) VALUES ('lun', 'Lunda');
INSERT INTO `country` (`id`, `name`) VALUES ('luo', 'Luo');
INSERT INTO `country` (`id`, `name`) VALUES ('lus', 'Lushai');
INSERT INTO `country` (`id`, `name`) VALUES ('lb', 'Luxemborgsch');
INSERT INTO `country` (`id`, `name`) VALUES ('mg', 'Madagassisch');
INSERT INTO `country` (`id`, `name`) VALUES ('mad', 'Madureesch');
INSERT INTO `country` (`id`, `name`) VALUES ('mag', 'Magahi');
INSERT INTO `country` (`id`, `name`) VALUES ('mai', 'Maithili');
INSERT INTO `country` (`id`, `name`) VALUES ('mak', 'Makassarsch');
INSERT INTO `country` (`id`, `name`) VALUES ('ms', 'Malaisch');
INSERT INTO `country` (`id`, `name`) VALUES ('ml', 'Malayalam');
INSERT INTO `country` (`id`, `name`) VALUES ('dv', 'Maledievsch');
INSERT INTO `country` (`id`, `name`) VALUES ('mt', 'Malteesch');
INSERT INTO `country` (`id`, `name`) VALUES ('mdr', 'Mandareesch');
INSERT INTO `country` (`id`, `name`) VALUES ('man', 'Manding');
INSERT INTO `country` (`id`, `name`) VALUES ('mnc', 'Mandschuursch');
INSERT INTO `country` (`id`, `name`) VALUES ('mni', 'Manipuri');
INSERT INTO `country` (`id`, `name`) VALUES ('mno', 'Manobo');
INSERT INTO `country` (`id`, `name`) VALUES ('gv', 'Manx');
INSERT INTO `country` (`id`, `name`) VALUES ('mi', 'Maori');
INSERT INTO `country` (`id`, `name`) VALUES ('mr', 'Marathi');
INSERT INTO `country` (`id`, `name`) VALUES ('chm', 'Mari');
INSERT INTO `country` (`id`, `name`) VALUES ('mh', 'Marschalleesch');
INSERT INTO `country` (`id`, `name`) VALUES ('mwr', 'Marwari');
INSERT INTO `country` (`id`, `name`) VALUES ('mas', 'Massai');
INSERT INTO `country` (`id`, `name`) VALUES ('myn', 'Maya-Spraken');
INSERT INTO `country` (`id`, `name`) VALUES ('mk', 'Mazedoonsch');
INSERT INTO `country` (`id`, `name`) VALUES ('umb', 'Mbundu');
INSERT INTO `country` (`id`, `name`) VALUES ('mul', 'Mehrsprakig');
INSERT INTO `country` (`id`, `name`) VALUES ('men', 'Mende');
INSERT INTO `country` (`id`, `name`) VALUES ('hmn', 'Miao-Spraken');
INSERT INTO `country` (`id`, `name`) VALUES ('mic', 'Micmac');
INSERT INTO `country` (`id`, `name`) VALUES ('enm', 'Middelengelsch');
INSERT INTO `country` (`id`, `name`) VALUES ('frm', 'Middelfranzöösch');
INSERT INTO `country` (`id`, `name`) VALUES ('gmh', 'Middelhoochdüütsch');
INSERT INTO `country` (`id`, `name`) VALUES ('mga', 'Middeliersch');
INSERT INTO `country` (`id`, `name`) VALUES ('dum', 'Middelnedderlandsch');
INSERT INTO `country` (`id`, `name`) VALUES ('pal', 'Middelpers’sch');
INSERT INTO `country` (`id`, `name`) VALUES ('min', 'Minangkabau');
INSERT INTO `country` (`id`, `name`) VALUES ('mwl', 'Mirandeesch');
INSERT INTO `country` (`id`, `name`) VALUES ('moh', 'Mohawk');
INSERT INTO `country` (`id`, `name`) VALUES ('mdf', 'Mokscha');
INSERT INTO `country` (`id`, `name`) VALUES ('mo', 'Moldaawsch');
INSERT INTO `country` (`id`, `name`) VALUES ('mkh', 'Mon-Khmer-Spraken');
INSERT INTO `country` (`id`, `name`) VALUES ('lol', 'Mongo');
INSERT INTO `country` (`id`, `name`) VALUES ('mn', 'Mongoolsch');
INSERT INTO `country` (`id`, `name`) VALUES ('mos', 'Mossi');
INSERT INTO `country` (`id`, `name`) VALUES ('mun', 'Munda-Spraken');
INSERT INTO `country` (`id`, `name`) VALUES ('mus', 'Muskogee-Spraken');
INSERT INTO `country` (`id`, `name`) VALUES ('nah', 'Nahuatl');
INSERT INTO `country` (`id`, `name`) VALUES ('na', 'Nauruusch');
INSERT INTO `country` (`id`, `name`) VALUES ('nv', 'Navajo');
INSERT INTO `country` (`id`, `name`) VALUES ('ng', 'Ndonga');
INSERT INTO `country` (`id`, `name`) VALUES ('nap', 'Neapolitaansch');
INSERT INTO `country` (`id`, `name`) VALUES ('nl', 'Nedderlandsch');
INSERT INTO `country` (`id`, `name`) VALUES ('dsb', 'Neddersorbsch');
INSERT INTO `country` (`id`, `name`) VALUES ('ne', 'Nepaleesch');
INSERT INTO `country` (`id`, `name`) VALUES ('new', 'Newari');
INSERT INTO `country` (`id`, `name`) VALUES ('nia', 'Nias');
INSERT INTO `country` (`id`, `name`) VALUES ('nic', 'Nigerkordofaansche Spraken');
INSERT INTO `country` (`id`, `name`) VALUES ('ssa', 'Nilosaharaansche Spraken');
INSERT INTO `country` (`id`, `name`) VALUES ('niu', 'Niue');
INSERT INTO `country` (`id`, `name`) VALUES ('nog', 'Nogai');
INSERT INTO `country` (`id`, `name`) VALUES ('nd', 'Noord-Ndebele');
INSERT INTO `country` (`id`, `name`) VALUES ('se', 'Noord-Saamsch');
INSERT INTO `country` (`id`, `name`) VALUES ('nso', 'Noord-Sotho');
INSERT INTO `country` (`id`, `name`) VALUES ('frr', 'Noordfreesch');
INSERT INTO `country` (`id`, `name`) VALUES ('no', 'Norweegsch');
INSERT INTO `country` (`id`, `name`) VALUES ('nb', 'Norweegsch Bokmål');
INSERT INTO `country` (`id`, `name`) VALUES ('nn', 'Norweegsch Nynorsk');
INSERT INTO `country` (`id`, `name`) VALUES ('nub', 'Nuubsche Spraken');
INSERT INTO `country` (`id`, `name`) VALUES ('nym', 'Nyamwezi');
INSERT INTO `country` (`id`, `name`) VALUES ('ny', 'Nyanja');
INSERT INTO `country` (`id`, `name`) VALUES ('nyn', 'Nyankole');
INSERT INTO `country` (`id`, `name`) VALUES ('nyo', 'Nyoro');
INSERT INTO `country` (`id`, `name`) VALUES ('nzi', 'Nzima');
INSERT INTO `country` (`id`, `name`) VALUES ('nqo', 'N’Ko');
INSERT INTO `country` (`id`, `name`) VALUES ('oj', 'Ojibwa');
INSERT INTO `country` (`id`, `name`) VALUES ('oc', 'Okzitaansch');
INSERT INTO `country` (`id`, `name`) VALUES ('sga', 'Oold-Iersch');
INSERT INTO `country` (`id`, `name`) VALUES ('nwc', 'Oold-Newari');
INSERT INTO `country` (`id`, `name`) VALUES ('syc', 'Oold-Syyrsch');
INSERT INTO `country` (`id`, `name`) VALUES ('ang', 'Ooldengelsch');
INSERT INTO `country` (`id`, `name`) VALUES ('fro', 'Ooldfranzöösch');
INSERT INTO `country` (`id`, `name`) VALUES ('grc', 'Ooldgreeksch');
INSERT INTO `country` (`id`, `name`) VALUES ('goh', 'Ooldhoochdüütsch');
INSERT INTO `country` (`id`, `name`) VALUES ('non', 'Ooldnoorsch');
INSERT INTO `country` (`id`, `name`) VALUES ('peo', 'Ooldpers’sch');
INSERT INTO `country` (`id`, `name`) VALUES ('pro', 'Ooldprovenzaalsch');
INSERT INTO `country` (`id`, `name`) VALUES ('rap', 'Oosterinsel-Spraak');
INSERT INTO `country` (`id`, `name`) VALUES ('kru', 'Oraon');
INSERT INTO `country` (`id`, `name`) VALUES ('or', 'Orija');
INSERT INTO `country` (`id`, `name`) VALUES ('om', 'Oromo');
INSERT INTO `country` (`id`, `name`) VALUES ('osa', 'Osage');
INSERT INTO `country` (`id`, `name`) VALUES ('ota', 'Osmaansch');
INSERT INTO `country` (`id`, `name`) VALUES ('os', 'Ossetsch');
INSERT INTO `country` (`id`, `name`) VALUES ('oto', 'Otomangue-Spraken');
INSERT INTO `country` (`id`, `name`) VALUES ('pau', 'Palausch');
INSERT INTO `country` (`id`, `name`) VALUES ('pi', 'Pali');
INSERT INTO `country` (`id`, `name`) VALUES ('pam', 'Pampanggan');
INSERT INTO `country` (`id`, `name`) VALUES ('pa', 'Pandschabsch');
INSERT INTO `country` (`id`, `name`) VALUES ('pag', 'Pangasinan');
INSERT INTO `country` (`id`, `name`) VALUES ('fan', 'Pangwe');
INSERT INTO `country` (`id`, `name`) VALUES ('pap', 'Papiamento');
INSERT INTO `country` (`id`, `name`) VALUES ('paa', 'Papuaspraken');
INSERT INTO `country` (`id`, `name`) VALUES ('ps', 'Paschtu');
INSERT INTO `country` (`id`, `name`) VALUES ('fa', 'Pers’sch');
INSERT INTO `country` (`id`, `name`) VALUES ('fil', 'Philippiensch');
INSERT INTO `country` (`id`, `name`) VALUES ('phi', 'Philippinen-Austroneesche Spraken');
INSERT INTO `country` (`id`, `name`) VALUES ('phn', 'Phönieksch');
INSERT INTO `country` (`id`, `name`) VALUES ('nds', 'Plattdüütsch');
INSERT INTO `country` (`id`, `name`) VALUES ('pon', 'Ponapeaansch');
INSERT INTO `country` (`id`, `name`) VALUES ('pl', 'Poolsch');
INSERT INTO `country` (`id`, `name`) VALUES ('pt', 'Portugeesch');
INSERT INTO `country` (`id`, `name`) VALUES ('pra', 'Prakrit');
INSERT INTO `country` (`id`, `name`) VALUES ('qu', 'Quechua');
INSERT INTO `country` (`id`, `name`) VALUES ('raj', 'Rajasthani');
INSERT INTO `country` (`id`, `name`) VALUES ('rar', 'Rarotongaansch');
INSERT INTO `country` (`id`, `name`) VALUES ('roa', 'Romaansche Spraken');
INSERT INTO `country` (`id`, `name`) VALUES ('rom', 'Romani');
INSERT INTO `country` (`id`, `name`) VALUES ('loz', 'Rotse');
INSERT INTO `country` (`id`, `name`) VALUES ('rw', 'Ruandsch');
INSERT INTO `country` (`id`, `name`) VALUES ('ro', 'Rumäänsch');
INSERT INTO `country` (`id`, `name`) VALUES ('rn', 'Rundi');
INSERT INTO `country` (`id`, `name`) VALUES ('ru', 'Russ’sch');
INSERT INTO `country` (`id`, `name`) VALUES ('rm', 'Rätoromaansch');
INSERT INTO `country` (`id`, `name`) VALUES ('kho', 'Saaksch');
INSERT INTO `country` (`id`, `name`) VALUES ('sal', 'Salish');
INSERT INTO `country` (`id`, `name`) VALUES ('sam', 'Samaritaansch');
INSERT INTO `country` (`id`, `name`) VALUES ('sm', 'Samoaansch');
INSERT INTO `country` (`id`, `name`) VALUES ('sad', 'Sandawe');
INSERT INTO `country` (`id`, `name`) VALUES ('sg', 'Sango');
INSERT INTO `country` (`id`, `name`) VALUES ('sa', 'Sanskrit');
INSERT INTO `country` (`id`, `name`) VALUES ('sat', 'Santali');
INSERT INTO `country` (`id`, `name`) VALUES ('sc', 'Sardsch');
INSERT INTO `country` (`id`, `name`) VALUES ('sas', 'Sasak');
INSERT INTO `country` (`id`, `name`) VALUES ('frs', 'Saterfreesch');
INSERT INTO `country` (`id`, `name`) VALUES ('shn', 'Schan');
INSERT INTO `country` (`id`, `name`) VALUES ('sn', 'Schona');
INSERT INTO `country` (`id`, `name`) VALUES ('sco', 'Schottsch');
INSERT INTO `country` (`id`, `name`) VALUES ('gd', 'Schottsch Gäälsch');
INSERT INTO `country` (`id`, `name`) VALUES ('sel', 'Selkupsch');
INSERT INTO `country` (`id`, `name`) VALUES ('sem', 'Semietsche Spraken');
INSERT INTO `country` (`id`, `name`) VALUES ('sr', 'Serbsch');
INSERT INTO `country` (`id`, `name`) VALUES ('srr', 'Serer');
INSERT INTO `country` (`id`, `name`) VALUES ('ii', 'Sichuan Yi');
INSERT INTO `country` (`id`, `name`) VALUES ('sid', 'Sidamo');
INSERT INTO `country` (`id`, `name`) VALUES ('bla', 'Siksika');
INSERT INTO `country` (`id`, `name`) VALUES ('sd', 'Sindhi');
INSERT INTO `country` (`id`, `name`) VALUES ('si', 'Singhaleesch');
INSERT INTO `country` (`id`, `name`) VALUES ('sit', 'Sinotibeetsche Spraken');
INSERT INTO `country` (`id`, `name`) VALUES ('sio', 'Sioux-Spraken');
INSERT INTO `country` (`id`, `name`) VALUES ('scn', 'Siziliaansch');
INSERT INTO `country` (`id`, `name`) VALUES ('sms', 'Skolt-Lappsch');
INSERT INTO `country` (`id`, `name`) VALUES ('sla', 'Slaavsche Spraken');
INSERT INTO `country` (`id`, `name`) VALUES ('den', 'Slave');
INSERT INTO `country` (`id`, `name`) VALUES ('sk', 'Slowaaksch');
INSERT INTO `country` (`id`, `name`) VALUES ('sl', 'Sloweensch');
INSERT INTO `country` (`id`, `name`) VALUES ('sog', 'Sogdisch');
INSERT INTO `country` (`id`, `name`) VALUES ('so', 'Somaalsch');
INSERT INTO `country` (`id`, `name`) VALUES ('son', 'Songhai');
INSERT INTO `country` (`id`, `name`) VALUES ('snk', 'Soninke');
INSERT INTO `country` (`id`, `name`) VALUES ('wen', 'Sorbsch');
INSERT INTO `country` (`id`, `name`) VALUES ('es', 'Spaansch');
INSERT INTO `country` (`id`, `name`) VALUES ('sw', 'Suaheli');
INSERT INTO `country` (`id`, `name`) VALUES ('suk', 'Sukuma');
INSERT INTO `country` (`id`, `name`) VALUES ('sux', 'Sumersch');
INSERT INTO `country` (`id`, `name`) VALUES ('su', 'Sundaneesch');
INSERT INTO `country` (`id`, `name`) VALUES ('srn', 'Surinaamsch');
INSERT INTO `country` (`id`, `name`) VALUES ('sus', 'Susu');
INSERT INTO `country` (`id`, `name`) VALUES ('ss', 'Swazi');
INSERT INTO `country` (`id`, `name`) VALUES ('sv', 'Sweedsch');
INSERT INTO `country` (`id`, `name`) VALUES ('fr_CH', 'Swiezer Franzöösch');
INSERT INTO `country` (`id`, `name`) VALUES ('de_CH', 'Swiezer Hoochdüütsch');
INSERT INTO `country` (`id`, `name`) VALUES ('gsw', 'Swiezerdüütsch');
INSERT INTO `country` (`id`, `name`) VALUES ('syr', 'Syyrsch');
INSERT INTO `country` (`id`, `name`) VALUES ('alt', 'Süüd-Altaisch');
INSERT INTO `country` (`id`, `name`) VALUES ('sma', 'Süüd-Lappsch');
INSERT INTO `country` (`id`, `name`) VALUES ('nr', 'Süüd-Ndebele');
INSERT INTO `country` (`id`, `name`) VALUES ('st', 'Süüd-Sotho');
INSERT INTO `country` (`id`, `name`) VALUES ('tg', 'Tadschiksch');
INSERT INTO `country` (`id`, `name`) VALUES ('tl', 'Tagalog');
INSERT INTO `country` (`id`, `name`) VALUES ('ty', 'Tahitsch');
INSERT INTO `country` (`id`, `name`) VALUES ('tmh', 'Tamaschek');
INSERT INTO `country` (`id`, `name`) VALUES ('ta', 'Tamilsch');
INSERT INTO `country` (`id`, `name`) VALUES ('tt', 'Tataarsch');
INSERT INTO `country` (`id`, `name`) VALUES ('sgn', 'Tekenspraken');
INSERT INTO `country` (`id`, `name`) VALUES ('te', 'Telugu');
INSERT INTO `country` (`id`, `name`) VALUES ('tem', 'Temne');
INSERT INTO `country` (`id`, `name`) VALUES ('ter', 'Tereno');
INSERT INTO `country` (`id`, `name`) VALUES ('tet', 'Tetum');
INSERT INTO `country` (`id`, `name`) VALUES ('th', 'Thai');
INSERT INTO `country` (`id`, `name`) VALUES ('tai', 'Thaispraken');
INSERT INTO `country` (`id`, `name`) VALUES ('bo', 'Tibeetsch');
INSERT INTO `country` (`id`, `name`) VALUES ('tig', 'Tigre');
INSERT INTO `country` (`id`, `name`) VALUES ('ti', 'Tigrinja');
INSERT INTO `country` (`id`, `name`) VALUES ('tiv', 'Tiv');
INSERT INTO `country` (`id`, `name`) VALUES ('tli', 'Tlingit');
INSERT INTO `country` (`id`, `name`) VALUES ('tpi', 'Tok Pisin');
INSERT INTO `country` (`id`, `name`) VALUES ('tkl', 'Tokelausch');
INSERT INTO `country` (`id`, `name`) VALUES ('tog', 'Tonga (Nyasa)');
INSERT INTO `country` (`id`, `name`) VALUES ('to', 'Tongaasch');
INSERT INTO `country` (`id`, `name`) VALUES ('zh_Hant', 'Traditschonell Chineesch');
INSERT INTO `country` (`id`, `name`) VALUES ('chk', 'Trukeesch');
INSERT INTO `country` (`id`, `name`) VALUES ('chg', 'Tschagataisch');
INSERT INTO `country` (`id`, `name`) VALUES ('cs', 'Tschech’sch');
INSERT INTO `country` (`id`, `name`) VALUES ('ce', 'Tschetscheensch');
INSERT INTO `country` (`id`, `name`) VALUES ('cv', 'Tschuwasch’sch');
INSERT INTO `country` (`id`, `name`) VALUES ('tsi', 'Tsimshian');
INSERT INTO `country` (`id`, `name`) VALUES ('ts', 'Tsonga');
INSERT INTO `country` (`id`, `name`) VALUES ('tn', 'Tswana');
INSERT INTO `country` (`id`, `name`) VALUES ('tum', 'Tumbuka');
INSERT INTO `country` (`id`, `name`) VALUES ('tup', 'Tupi-Spraken');
INSERT INTO `country` (`id`, `name`) VALUES ('tk', 'Turkmeensch');
INSERT INTO `country` (`id`, `name`) VALUES ('tyv', 'Tuwinsch');
INSERT INTO `country` (`id`, `name`) VALUES ('tw', 'Twi');
INSERT INTO `country` (`id`, `name`) VALUES ('kcg', 'Tyap');
INSERT INTO `country` (`id`, `name`) VALUES ('tr', 'Törksch');
INSERT INTO `country` (`id`, `name`) VALUES ('udm', 'Udmurtsch');
INSERT INTO `country` (`id`, `name`) VALUES ('uga', 'Ugaritsch');
INSERT INTO `country` (`id`, `name`) VALUES ('ug', 'Uiguursch');
INSERT INTO `country` (`id`, `name`) VALUES ('uk', 'Ukrainsch');
INSERT INTO `country` (`id`, `name`) VALUES ('und', 'Unbestimmte Spraak');
INSERT INTO `country` (`id`, `name`) VALUES ('hu', 'Ungaarsch');
INSERT INTO `country` (`id`, `name`) VALUES ('ur', 'Urdu');
INSERT INTO `country` (`id`, `name`) VALUES ('uz', 'Usbeeksch');
INSERT INTO `country` (`id`, `name`) VALUES ('vai', 'Vai');
INSERT INTO `country` (`id`, `name`) VALUES ('ve', 'Venda');
INSERT INTO `country` (`id`, `name`) VALUES ('zh_Hans', 'Vereenfacht Chineesch');
INSERT INTO `country` (`id`, `name`) VALUES ('mis', 'Verschedene Spraken');
INSERT INTO `country` (`id`, `name`) VALUES ('vi', 'Vietnameesch');
INSERT INTO `country` (`id`, `name`) VALUES ('vo', 'Volapük');
INSERT INTO `country` (`id`, `name`) VALUES ('wak', 'Wakashaansch');
INSERT INTO `country` (`id`, `name`) VALUES ('wal', 'Walamo');
INSERT INTO `country` (`id`, `name`) VALUES ('cy', 'Waliesch');
INSERT INTO `country` (`id`, `name`) VALUES ('wa', 'Walloonsch');
INSERT INTO `country` (`id`, `name`) VALUES ('war', 'Waray');
INSERT INTO `country` (`id`, `name`) VALUES ('was', 'Washo');
INSERT INTO `country` (`id`, `name`) VALUES ('fy', 'Westfreesch');
INSERT INTO `country` (`id`, `name`) VALUES ('be', 'Wittruss’sch');
INSERT INTO `country` (`id`, `name`) VALUES ('wo', 'Wolof');
INSERT INTO `country` (`id`, `name`) VALUES ('vot', 'Wootsch');
INSERT INTO `country` (`id`, `name`) VALUES ('root', 'Wortel');
INSERT INTO `country` (`id`, `name`) VALUES ('xh', 'Xhosa');
INSERT INTO `country` (`id`, `name`) VALUES ('yao', 'Yao');
INSERT INTO `country` (`id`, `name`) VALUES ('yap', 'Yapeesch');
INSERT INTO `country` (`id`, `name`) VALUES ('yo', 'Yoruba');
INSERT INTO `country` (`id`, `name`) VALUES ('ypk', 'Yupik');
INSERT INTO `country` (`id`, `name`) VALUES ('znd', 'Zande');
INSERT INTO `country` (`id`, `name`) VALUES ('zap', 'Zapoteeksch');
INSERT INTO `country` (`id`, `name`) VALUES ('zza', 'Zaza');
INSERT INTO `country` (`id`, `name`) VALUES ('zen', 'Zenaga');
INSERT INTO `country` (`id`, `name`) VALUES ('za', 'Zhuang');
INSERT INTO `country` (`id`, `name`) VALUES ('zu', 'Zulu');
INSERT INTO `country` (`id`, `name`) VALUES ('zun', 'Zuni');
INSERT INTO `country` (`id`, `name`) VALUES ('egy', 'Ägyptsch');
INSERT INTO `country` (`id`, `name`) VALUES ('de_AT', 'Öösterrieksch Hoochdüütsch');
