CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('ar', 'erebî');
INSERT INTO [country] ([id], [name]) VALUES ('ja', 'japonî');
INSERT INTO [country] ([id], [name]) VALUES ('ku', 'kurdî');
INSERT INTO [country] ([id], [name]) VALUES ('en', 'îngilîzî');
INSERT INTO [country] ([id], [name]) VALUES ('as', 'ئا سسامی (زوبان)');
INSERT INTO [country] ([id], [name]) VALUES ('az', 'ئازه‌ربایجانی');
INSERT INTO [country] ([id], [name]) VALUES ('sq', 'ئاڵبانی');
INSERT INTO [country] ([id], [name]) VALUES ('de', 'ئاڵمانی');
INSERT INTO [country] ([id], [name]) VALUES ('hy', 'ئه رمه نی');
INSERT INTO [country] ([id], [name]) VALUES ('ie', 'ئه نته ر لينگ (زوبان)');
INSERT INTO [country] ([id], [name]) VALUES ('af', 'ئه‌فریكای');
INSERT INTO [country] ([id], [name]) VALUES ('am', 'ئه‌مهه‌رینجی');
INSERT INTO [country] ([id], [name]) VALUES ('ug', 'ئويخووری');
INSERT INTO [country] ([id], [name]) VALUES ('ur', 'ئۆردو‌و');
INSERT INTO [country] ([id], [name]) VALUES ('or', 'ئۆرییا');
INSERT INTO [country] ([id], [name]) VALUES ('uz', 'ئۆزبه‌كی');
INSERT INTO [country] ([id], [name]) VALUES ('oc', 'ئۆسیتانی');
INSERT INTO [country] ([id], [name]) VALUES ('uk', 'ئۆكراینی');
INSERT INTO [country] ([id], [name]) VALUES ('it', 'ئیتالی');
INSERT INTO [country] ([id], [name]) VALUES ('ga', 'ئیرله‌ندی');
INSERT INTO [country] ([id], [name]) VALUES ('et', 'ئیستۆنی');
INSERT INTO [country] ([id], [name]) VALUES ('is', 'ئیسله‌ندی');
INSERT INTO [country] ([id], [name]) VALUES ('es', 'ئیسپانی');
INSERT INTO [country] ([id], [name]) VALUES ('ia', 'ئینترلینگوی');
INSERT INTO [country] ([id], [name]) VALUES ('eo', 'ئێسپیرانتۆ');
INSERT INTO [country] ([id], [name]) VALUES ('id', 'ئێه‌ندونیزی');
INSERT INTO [country] ([id], [name]) VALUES ('eu', 'باسكی');
INSERT INTO [country] ([id], [name]) VALUES ('br', 'برێتونی');
INSERT INTO [country] ([id], [name]) VALUES ('bn', 'به‌نگلادێشی');
INSERT INTO [country] ([id], [name]) VALUES ('bs', 'بۆسنی');
INSERT INTO [country] ([id], [name]) VALUES ('bg', 'بۆلگاری');
INSERT INTO [country] ([id], [name]) VALUES ('bh', 'بیهاری');
INSERT INTO [country] ([id], [name]) VALUES ('be', 'بێلاڕووسی');
INSERT INTO [country] ([id], [name]) VALUES ('ta', 'تامیلی');
INSERT INTO [country] ([id], [name]) VALUES ('fil', 'تاگالۆگی');
INSERT INTO [country] ([id], [name]) VALUES ('th', 'تایله‌ندی');
INSERT INTO [country] ([id], [name]) VALUES ('tk', 'تروكمانی');
INSERT INTO [country] ([id], [name]) VALUES ('te', 'ته‌لۆگوی');
INSERT INTO [country] ([id], [name]) VALUES ('tr', 'توركی');
INSERT INTO [country] ([id], [name]) VALUES ('tw', 'توی');
INSERT INTO [country] ([id], [name]) VALUES ('ti', 'تیگرینیای');
INSERT INTO [country] ([id], [name]) VALUES ('jv', 'جاڤانی');
INSERT INTO [country] ([id], [name]) VALUES ('da', 'دانماركی');
INSERT INTO [country] ([id], [name]) VALUES ('zu', 'زولو');
INSERT INTO [country] ([id], [name]) VALUES ('sa', 'سانسکريت');
INSERT INTO [country] ([id], [name]) VALUES ('xh', 'سسوسا');
INSERT INTO [country] ([id], [name]) VALUES ('sk', 'سلۆڤاكی');
INSERT INTO [country] ([id], [name]) VALUES ('sl', 'سلۆڤێنی');
INSERT INTO [country] ([id], [name]) VALUES ('sr', 'سه‌ربی');
INSERT INTO [country] ([id], [name]) VALUES ('sw', 'سواهیلی');
INSERT INTO [country] ([id], [name]) VALUES ('su', 'سودانی');
INSERT INTO [country] ([id], [name]) VALUES ('sv', 'سویدی');
INSERT INTO [country] ([id], [name]) VALUES ('sd', 'سيندی(زوبان)');
INSERT INTO [country] ([id], [name]) VALUES ('so', 'سۆمالی');
INSERT INTO [country] ([id], [name]) VALUES ('si', 'سینهه‌لی');
INSERT INTO [country] ([id], [name]) VALUES ('sh', 'سێربۆكرواتی');
INSERT INTO [country] ([id], [name]) VALUES ('st', 'سێسۆتۆ');
INSERT INTO [country] ([id], [name]) VALUES ('fa', 'فارسی');
INSERT INTO [country] ([id], [name]) VALUES ('fy', 'فریسی');
INSERT INTO [country] ([id], [name]) VALUES ('fo', 'فه‌رئۆیی');
INSERT INTO [country] ([id], [name]) VALUES ('fr', 'فه‌رانسی');
INSERT INTO [country] ([id], [name]) VALUES ('fi', 'فینله‌ندی');
INSERT INTO [country] ([id], [name]) VALUES ('ca', 'كاتالۆنی');
INSERT INTO [country] ([id], [name]) VALUES ('hr', 'كرواتی');
INSERT INTO [country] ([id], [name]) VALUES ('ky', 'كرگیزی');
INSERT INTO [country] ([id], [name]) VALUES ('tlh', 'كلینگۆن');
INSERT INTO [country] ([id], [name]) VALUES ('kn', 'كه‌نه‌دایی');
INSERT INTO [country] ([id], [name]) VALUES ('ko', 'كۆری');
INSERT INTO [country] ([id], [name]) VALUES ('la', 'لاتینی');
INSERT INTO [country] ([id], [name]) VALUES ('lo', 'لاو‏ى');
INSERT INTO [country] ([id], [name]) VALUES ('ln', 'لينگالا');
INSERT INTO [country] ([id], [name]) VALUES ('lt', 'لیتوانی');
INSERT INTO [country] ([id], [name]) VALUES ('lv', 'لێتۆنی');
INSERT INTO [country] ([id], [name]) VALUES ('mr', 'ماراتی');
INSERT INTO [country] ([id], [name]) VALUES ('mk', 'ماكێدۆنی');
INSERT INTO [country] ([id], [name]) VALUES ('ml', 'مالایلام');
INSERT INTO [country] ([id], [name]) VALUES ('ms', 'مالیزی');
INSERT INTO [country] ([id], [name]) VALUES ('mt', 'ماڵتایی');
INSERT INTO [country] ([id], [name]) VALUES ('mn', 'مه‌نگۆلی');
INSERT INTO [country] ([id], [name]) VALUES ('no', 'نۆروێژی');
INSERT INTO [country] ([id], [name]) VALUES ('ne', 'نێپالی');
INSERT INTO [country] ([id], [name]) VALUES ('hu', 'هه‌نگاری (مه‌جاری)');
INSERT INTO [country] ([id], [name]) VALUES ('nl', 'هۆڵه‌ندی');
INSERT INTO [country] ([id], [name]) VALUES ('he', 'هیبرێ');
INSERT INTO [country] ([id], [name]) VALUES ('hi', 'هیندی');
INSERT INTO [country] ([id], [name]) VALUES ('cy', 'وێلزی');
INSERT INTO [country] ([id], [name]) VALUES ('ps', 'په‌شتوو');
INSERT INTO [country] ([id], [name]) VALUES ('pa', 'په‌نجابی');
INSERT INTO [country] ([id], [name]) VALUES ('pt_BR', 'پورتوگاڵی (برازیل)');
INSERT INTO [country] ([id], [name]) VALUES ('pt_PT', 'پورتوگاڵی (پورتوگاڵ)');
INSERT INTO [country] ([id], [name]) VALUES ('pt', 'پۆرتۆگالی');
INSERT INTO [country] ([id], [name]) VALUES ('pl', 'پۆڵۆنیایی (له‌هستانی)');
INSERT INTO [country] ([id], [name]) VALUES ('cs', 'چه‌كی');
INSERT INTO [country] ([id], [name]) VALUES ('ru', 'ڕووسی');
INSERT INTO [country] ([id], [name]) VALUES ('ro', 'ڕۆمانی');
INSERT INTO [country] ([id], [name]) VALUES ('vi', 'ڤیه‌تنامی');
INSERT INTO [country] ([id], [name]) VALUES ('km', 'کامبۆجی (زوبان)');
INSERT INTO [country] ([id], [name]) VALUES ('gl', 'گالیسی');
INSERT INTO [country] ([id], [name]) VALUES ('gd', 'گه‌لیكی سكۆتله‌ندی');
INSERT INTO [country] ([id], [name]) VALUES ('gu', 'گوجاراتی');
INSERT INTO [country] ([id], [name]) VALUES ('gn', 'گووارانی');
INSERT INTO [country] ([id], [name]) VALUES ('ka', 'گۆرجستانی');
INSERT INTO [country] ([id], [name]) VALUES ('yi', 'یوددی');
INSERT INTO [country] ([id], [name]) VALUES ('el', 'یۆنانی');
