CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('hy', 'Armenian');
INSERT INTO "country" ("id", "name") VALUES ('as', 'Assamese');
INSERT INTO "country" ("id", "name") VALUES ('km', 'Cambodian');
INSERT INTO "country" ("id", "name") VALUES ('gn', 'Gurani');
INSERT INTO "country" ("id", "name") VALUES ('gd', 'I-Scots Gaelic');
INSERT INTO "country" ("id", "name") VALUES ('kn', 'Ikhanada');
INSERT INTO "country" ("id", "name") VALUES ('sq', 'Isi-Albania');
INSERT INTO "country" ("id", "name") VALUES ('am', 'Isi-Amaharikhi');
INSERT INTO "country" ("id", "name") VALUES ('az', 'Isi-Azebhayijani');
INSERT INTO "country" ("id", "name") VALUES ('eu', 'Isi-Basque');
INSERT INTO "country" ("id", "name") VALUES ('bg', 'Isi-Bulgaria');
INSERT INTO "country" ("id", "name") VALUES ('hr', 'Isi-Croatia');
INSERT INTO "country" ("id", "name") VALUES ('cs', 'Isi-Czech');
INSERT INTO "country" ("id", "name") VALUES ('nl', 'Isi-Dutch');
INSERT INTO "country" ("id", "name") VALUES ('et', 'Isi-Esistoniya');
INSERT INTO "country" ("id", "name") VALUES ('eo', 'Isi-Esperanto');
INSERT INTO "country" ("id", "name") VALUES ('gl', 'Isi-Galashiya');
INSERT INTO "country" ("id", "name") VALUES ('is', 'Isi-Icelandic');
INSERT INTO "country" ("id", "name") VALUES ('id', 'Isi-Indonesia');
INSERT INTO "country" ("id", "name") VALUES ('ga', 'Isi-Irishi');
INSERT INTO "country" ("id", "name") VALUES ('lv', 'Isi-Latvian');
INSERT INTO "country" ("id", "name") VALUES ('lt', 'Isi-Lithuanian');
INSERT INTO "country" ("id", "name") VALUES ('oc', 'Isi-Osithani');
INSERT INTO "country" ("id", "name") VALUES ('sr', 'Isi-Sebhiya');
INSERT INTO "country" ("id", "name") VALUES ('ur', 'Isi-Udu');
INSERT INTO "country" ("id", "name") VALUES ('uk', 'Isi-Ukrain');
INSERT INTO "country" ("id", "name") VALUES ('uz', 'Isi-Uzibheki');
INSERT INTO "country" ("id", "name") VALUES ('be', 'IsiBhelarashiyani');
INSERT INTO "country" ("id", "name") VALUES ('bn', 'IsiBhengali');
INSERT INTO "country" ("id", "name") VALUES ('bh', 'IsiBhihari');
INSERT INTO "country" ("id", "name") VALUES ('bs', 'IsiBhosiniyani');
INSERT INTO "country" ("id", "name") VALUES ('da', 'IsiDenishi');
INSERT INTO "country" ("id", "name") VALUES ('fy', 'IsiFriziyani');
INSERT INTO "country" ("id", "name") VALUES ('el', 'IsiGreki');
INSERT INTO "country" ("id", "name") VALUES ('gu', 'IsiGujarati');
INSERT INTO "country" ("id", "name") VALUES ('hu', 'IsiHangari');
INSERT INTO "country" ("id", "name") VALUES ('he', 'IsiHebheru');
INSERT INTO "country" ("id", "name") VALUES ('ja', 'IsiJaphani');
INSERT INTO "country" ("id", "name") VALUES ('jv', 'IsiJavanisi');
INSERT INTO "country" ("id", "name") VALUES ('ka', 'IsiJojiyani');
INSERT INTO "country" ("id", "name") VALUES ('ca', 'IsiKhathalani');
INSERT INTO "country" ("id", "name") VALUES ('tlh', 'IsiKlingoni');
INSERT INTO "country" ("id", "name") VALUES ('ko', 'IsiKoriya');
INSERT INTO "country" ("id", "name") VALUES ('la', 'IsiLathini');
INSERT INTO "country" ("id", "name") VALUES ('mk', 'IsiMakhedoniya');
INSERT INTO "country" ("id", "name") VALUES ('ml', 'IsiMalayami');
INSERT INTO "country" ("id", "name") VALUES ('ms', 'IsiMalayi');
INSERT INTO "country" ("id", "name") VALUES ('mt', 'IsiMalithize');
INSERT INTO "country" ("id", "name") VALUES ('mr', 'IsiMarathi');
INSERT INTO "country" ("id", "name") VALUES ('ne', 'IsiNepali');
INSERT INTO "country" ("id", "name") VALUES ('nn', 'IsiNowejiyani (Nynorsk)');
INSERT INTO "country" ("id", "name") VALUES ('no', 'IsiNoweyi');
INSERT INTO "country" ("id", "name") VALUES ('fa', 'IsiPheshiyani');
INSERT INTO "country" ("id", "name") VALUES ('pl', 'IsiPholisi');
INSERT INTO "country" ("id", "name") VALUES ('pa', 'IsiPhunjabi');
INSERT INTO "country" ("id", "name") VALUES ('pt', 'IsiPotukezi');
INSERT INTO "country" ("id", "name") VALUES ('pt_PT', 'IsiPotukezi (Ephothugali)');
INSERT INTO "country" ("id", "name") VALUES ('ru', 'IsiRashiya');
INSERT INTO "country" ("id", "name") VALUES ('ro', 'IsiRomani');
INSERT INTO "country" ("id", "name") VALUES ('si', 'IsiSinhalese');
INSERT INTO "country" ("id", "name") VALUES ('sk', 'IsiSlovaki');
INSERT INTO "country" ("id", "name") VALUES ('sl', 'IsiSlovakiyani');
INSERT INTO "country" ("id", "name") VALUES ('su', 'IsiSundanizi');
INSERT INTO "country" ("id", "name") VALUES ('sv', 'IsiSwidishi');
INSERT INTO "country" ("id", "name") VALUES ('fil', 'IsiThagalogi');
INSERT INTO "country" ("id", "name") VALUES ('ta', 'IsiThamil');
INSERT INTO "country" ("id", "name") VALUES ('th', 'IsiThayi');
INSERT INTO "country" ("id", "name") VALUES ('tr', 'IsiThekishi');
INSERT INTO "country" ("id", "name") VALUES ('te', 'IsiThelugu');
INSERT INTO "country" ("id", "name") VALUES ('ti', 'IsiTigrinya');
INSERT INTO "country" ("id", "name") VALUES ('vi', 'IsiVietnamise');
INSERT INTO "country" ("id", "name") VALUES ('cy', 'IsiWelshi');
INSERT INTO "country" ("id", "name") VALUES ('fo', 'Isifaro');
INSERT INTO "country" ("id", "name") VALUES ('pt_BR', 'Isiputukezi (Brazil)');
INSERT INTO "country" ("id", "name") VALUES ('ia', 'Izilimi ezihlangene');
INSERT INTO "country" ("id", "name") VALUES ('ie', 'Izilimu');
INSERT INTO "country" ("id", "name") VALUES ('ky', 'Kyrgyz');
INSERT INTO "country" ("id", "name") VALUES ('lo', 'Laothian');
INSERT INTO "country" ("id", "name") VALUES ('ln', 'Lingala');
INSERT INTO "country" ("id", "name") VALUES ('mn', 'Mongolian');
INSERT INTO "country" ("id", "name") VALUES ('or', 'Oriya');
INSERT INTO "country" ("id", "name") VALUES ('ps', 'Pashto');
INSERT INTO "country" ("id", "name") VALUES ('sa', 'Sanskrit');
INSERT INTO "country" ("id", "name") VALUES ('sh', 'Serbo-Croatian');
INSERT INTO "country" ("id", "name") VALUES ('sd', 'Sindhi');
INSERT INTO "country" ("id", "name") VALUES ('so', 'Somali');
INSERT INTO "country" ("id", "name") VALUES ('tw', 'Twi');
INSERT INTO "country" ("id", "name") VALUES ('ug', 'Uighur');
INSERT INTO "country" ("id", "name") VALUES ('it', 'isItalian');
INSERT INTO "country" ("id", "name") VALUES ('ar', 'isi-Alabhu');
INSERT INTO "country" ("id", "name") VALUES ('af', 'isiBhunu');
INSERT INTO "country" ("id", "name") VALUES ('fi', 'isiFinnish');
INSERT INTO "country" ("id", "name") VALUES ('fr', 'isiFulentshi');
INSERT INTO "country" ("id", "name") VALUES ('hi', 'isiHindi');
INSERT INTO "country" ("id", "name") VALUES ('de', 'isiJalimani');
INSERT INTO "country" ("id", "name") VALUES ('en', 'isiNgisi');
INSERT INTO "country" ("id", "name") VALUES ('es', 'isiSpeyini');
INSERT INTO "country" ("id", "name") VALUES ('st', 'isiSuthu');
INSERT INTO "country" ("id", "name") VALUES ('sw', 'isiSwahili');
INSERT INTO "country" ("id", "name") VALUES ('xh', 'isiXhosa');
INSERT INTO "country" ("id", "name") VALUES ('zu', 'isiZulu');
INSERT INTO "country" ("id", "name") VALUES ('br', 'isihlobo sase Britain');
INSERT INTO "country" ("id", "name") VALUES ('ku', 'ulimu lwama Kudishi');
INSERT INTO "country" ("id", "name") VALUES ('yi', 'ulimu olwi Yidish');
INSERT INTO "country" ("id", "name") VALUES ('tk', 'umuntu wase Turkmenistan.');
