CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('ak', 'Akan');
INSERT INTO `country` (`id`, `name`) VALUES ('am', 'Amharik');
INSERT INTO `country` (`id`, `name`) VALUES ('be', 'Belarusanci');
INSERT INTO `country` (`id`, `name`) VALUES ('bn', 'Bengali');
INSERT INTO `country` (`id`, `name`) VALUES ('bg', 'Bulgaranci');
INSERT INTO `country` (`id`, `name`) VALUES ('my', 'Burmanci');
INSERT INTO `country` (`id`, `name`) VALUES ('fr', 'Faransanci');
INSERT INTO `country` (`id`, `name`) VALUES ('el', 'Girkanci');
INSERT INTO `country` (`id`, `name`) VALUES ('vi', 'Harshen Biyetinam');
INSERT INTO `country` (`id`, `name`) VALUES ('cs', 'Harshen Cak');
INSERT INTO `country` (`id`, `name`) VALUES ('hi', 'Harshen Hindi');
INSERT INTO `country` (`id`, `name`) VALUES ('hu', 'Harshen Hungari');
INSERT INTO `country` (`id`, `name`) VALUES ('id', 'Harshen Indunusiya');
INSERT INTO `country` (`id`, `name`) VALUES ('km', 'Harshen Kimar');
INSERT INTO `country` (`id`, `name`) VALUES ('ko', 'Harshen Koreya');
INSERT INTO `country` (`id`, `name`) VALUES ('ms', 'Harshen Malai');
INSERT INTO `country` (`id`, `name`) VALUES ('pl', 'Harshen Polan');
INSERT INTO `country` (`id`, `name`) VALUES ('pt', 'Harshen Portugal');
INSERT INTO `country` (`id`, `name`) VALUES ('zh', 'Harshen Sin');
INSERT INTO `country` (`id`, `name`) VALUES ('sv', 'Harshen Suwedan');
INSERT INTO `country` (`id`, `name`) VALUES ('tr', 'Harshen Turkiyya');
INSERT INTO `country` (`id`, `name`) VALUES ('ur', 'Harshen Urdu');
INSERT INTO `country` (`id`, `name`) VALUES ('uk', 'Harshen Yukuren');
INSERT INTO `country` (`id`, `name`) VALUES ('zu', 'Harshen Zulu');
INSERT INTO `country` (`id`, `name`) VALUES ('ha', 'Hausa');
INSERT INTO `country` (`id`, `name`) VALUES ('nl', 'Holanci');
INSERT INTO `country` (`id`, `name`) VALUES ('ig', 'Inyamuranci');
INSERT INTO `country` (`id`, `name`) VALUES ('es', 'Ispaniyanci');
INSERT INTO `country` (`id`, `name`) VALUES ('it', 'Italiyanci');
INSERT INTO `country` (`id`, `name`) VALUES ('jv', 'Jabananci');
INSERT INTO `country` (`id`, `name`) VALUES ('de', 'Jamusanci');
INSERT INTO `country` (`id`, `name`) VALUES ('ja', 'Japananci');
INSERT INTO `country` (`id`, `name`) VALUES ('rw', 'Kiniyaruwanda');
INSERT INTO `country` (`id`, `name`) VALUES ('ar', 'Larabci');
INSERT INTO `country` (`id`, `name`) VALUES ('ne', 'Nepali');
INSERT INTO `country` (`id`, `name`) VALUES ('fa', 'Parisanci');
INSERT INTO `country` (`id`, `name`) VALUES ('pa', 'Punjabi');
INSERT INTO `country` (`id`, `name`) VALUES ('ru', 'Rashanci');
INSERT INTO `country` (`id`, `name`) VALUES ('ro', 'Romaniyanci');
INSERT INTO `country` (`id`, `name`) VALUES ('so', 'Somali');
INSERT INTO `country` (`id`, `name`) VALUES ('ta', 'Tamil');
INSERT INTO `country` (`id`, `name`) VALUES ('th', 'Thai');
INSERT INTO `country` (`id`, `name`) VALUES ('en', 'Turanci');
INSERT INTO `country` (`id`, `name`) VALUES ('yo', 'Yarbanci');
