CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('bas', 'Ɓàsàa');
INSERT INTO [country] ([id], [name]) VALUES ('ak', 'Hɔp u akan');
INSERT INTO [country] ([id], [name]) VALUES ('am', 'Hɔp u amhārìk');
INSERT INTO [country] ([id], [name]) VALUES ('ar', 'Hɔp u arâb');
INSERT INTO [country] ([id], [name]) VALUES ('bn', 'Hɔp u bɛŋgàli');
INSERT INTO [country] ([id], [name]) VALUES ('be', 'Hɔp u bièlòrûs');
INSERT INTO [country] ([id], [name]) VALUES ('my', 'Hɔp u birmàn');
INSERT INTO [country] ([id], [name]) VALUES ('bg', 'Hɔp u bûlgâr');
INSERT INTO [country] ([id], [name]) VALUES ('ha', 'Hɔp u ɓausa');
INSERT INTO [country] ([id], [name]) VALUES ('cs', 'Hɔp u cɛ̂k');
INSERT INTO [country] ([id], [name]) VALUES ('el', 'Hɔp u gri ᷇kyà');
INSERT INTO [country] ([id], [name]) VALUES ('hi', 'Hɔp u hindì');
INSERT INTO [country] ([id], [name]) VALUES ('hu', 'Hɔp u hɔŋgrìi');
INSERT INTO [country] ([id], [name]) VALUES ('ig', 'Hɔp u iɓò');
INSERT INTO [country] ([id], [name]) VALUES ('id', 'Hɔp u indònesìà');
INSERT INTO [country] ([id], [name]) VALUES ('it', 'Hɔp u italìà');
INSERT INTO [country] ([id], [name]) VALUES ('de', 'Hɔp u jamân');
INSERT INTO [country] ([id], [name]) VALUES ('zh', 'Hɔp u kinà');
INSERT INTO [country] ([id], [name]) VALUES ('km', 'Hɔp u kmɛ̂r');
INSERT INTO [country] ([id], [name]) VALUES ('ko', 'Hɔp u kɔrēà');
INSERT INTO [country] ([id], [name]) VALUES ('ms', 'Hɔp u makɛ᷆');
INSERT INTO [country] ([id], [name]) VALUES ('ne', 'Hɔp u nepa᷆l');
INSERT INTO [country] ([id], [name]) VALUES ('nl', 'Hɔp u nlɛ̀ndi');
INSERT INTO [country] ([id], [name]) VALUES ('en', 'Hɔp u ŋgisì');
INSERT INTO [country] ([id], [name]) VALUES ('es', 'Hɔp u panyā');
INSERT INTO [country] ([id], [name]) VALUES ('pa', 'Hɔp u pɛnjàbi');
INSERT INTO [country] ([id], [name]) VALUES ('fa', 'Hɔp u pɛrsìà');
INSERT INTO [country] ([id], [name]) VALUES ('pl', 'Hɔp u pɔlɔ̄nà');
INSERT INTO [country] ([id], [name]) VALUES ('pt', 'Hɔp u pɔtɔ̄kì');
INSERT INTO [country] ([id], [name]) VALUES ('fr', 'Hɔp u pulàsi');
INSERT INTO [country] ([id], [name]) VALUES ('rw', 'Hɔp u ruāndà');
INSERT INTO [country] ([id], [name]) VALUES ('ro', 'Hɔp u rùmanìà');
INSERT INTO [country] ([id], [name]) VALUES ('ru', 'Hɔp u ruslànd');
INSERT INTO [country] ([id], [name]) VALUES ('so', 'Hɔp u somàlî');
INSERT INTO [country] ([id], [name]) VALUES ('sv', 'Hɔp u suɛ᷆d');
INSERT INTO [country] ([id], [name]) VALUES ('ta', 'Hɔp u tamu᷆l');
INSERT INTO [country] ([id], [name]) VALUES ('th', 'Hɔp u tây');
INSERT INTO [country] ([id], [name]) VALUES ('tr', 'Hɔp u tûrk');
INSERT INTO [country] ([id], [name]) VALUES ('uk', 'Hɔp u ukrǎnìà');
INSERT INTO [country] ([id], [name]) VALUES ('ur', 'Hɔp u urdù');
INSERT INTO [country] ([id], [name]) VALUES ('vi', 'Hɔp u vyɛ̄dnàm');
INSERT INTO [country] ([id], [name]) VALUES ('ja', 'Hɔp u yapàn');
INSERT INTO [country] ([id], [name]) VALUES ('jv', 'Hɔp u yavà');
INSERT INTO [country] ([id], [name]) VALUES ('yo', 'Hɔp u yorūbà');
INSERT INTO [country] ([id], [name]) VALUES ('zu', 'Hɔp u zulù');
