CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('ab', 'abkaziu');
INSERT INTO `country` (`id`, `name`) VALUES ('af', 'afrikaner');
INSERT INTO `country` (`id`, `name`) VALUES ('ay', 'aimara');
INSERT INTO `country` (`id`, `name`) VALUES ('ak', 'akan');
INSERT INTO `country` (`id`, `name`) VALUES ('de', 'alemãu');
INSERT INTO `country` (`id`, `name`) VALUES ('de_AT', 'alimãu austriaku');
INSERT INTO `country` (`id`, `name`) VALUES ('de_CH', 'altu alimãu suisu');
INSERT INTO `country` (`id`, `name`) VALUES ('am', 'amariku');
INSERT INTO `country` (`id`, `name`) VALUES ('ar', 'arabi');
INSERT INTO `country` (`id`, `name`) VALUES ('as', 'asames');
INSERT INTO `country` (`id`, `name`) VALUES ('ha', 'auza');
INSERT INTO `country` (`id`, `name`) VALUES ('az', 'azerbaijanu');
INSERT INTO `country` (`id`, `name`) VALUES ('bn', 'bengali');
INSERT INTO `country` (`id`, `name`) VALUES ('be', 'bielorusu');
INSERT INTO `country` (`id`, `name`) VALUES ('my', 'birmanes');
INSERT INTO `country` (`id`, `name`) VALUES ('bs', 'bosniu');
INSERT INTO `country` (`id`, `name`) VALUES ('bg', 'bulgaru');
INSERT INTO `country` (`id`, `name`) VALUES ('da', 'dinamarkes');
INSERT INTO `country` (`id`, `name`) VALUES ('nl_BE', 'flamengu');
INSERT INTO `country` (`id`, `name`) VALUES ('fr', 'franses');
INSERT INTO `country` (`id`, `name`) VALUES ('fr_CA', 'franses kanadianu');
INSERT INTO `country` (`id`, `name`) VALUES ('fr_CH', 'franses suisu');
INSERT INTO `country` (`id`, `name`) VALUES ('cy', 'gales');
INSERT INTO `country` (`id`, `name`) VALUES ('el', 'gregu');
INSERT INTO `country` (`id`, `name`) VALUES ('ig', 'ibo');
INSERT INTO `country` (`id`, `name`) VALUES ('hi', 'indi');
INSERT INTO `country` (`id`, `name`) VALUES ('id', 'indoneziu');
INSERT INTO `country` (`id`, `name`) VALUES ('en', 'ingles');
INSERT INTO `country` (`id`, `name`) VALUES ('en_AU', 'ingles australianu');
INSERT INTO `country` (`id`, `name`) VALUES ('en_GB', 'ingles britanuku');
INSERT INTO `country` (`id`, `name`) VALUES ('en_CA', 'ingles kanadianu');
INSERT INTO `country` (`id`, `name`) VALUES ('en_US', 'ingles merkanu');
INSERT INTO `country` (`id`, `name`) VALUES ('yo', 'ioruba');
INSERT INTO `country` (`id`, `name`) VALUES ('it', 'italianu');
INSERT INTO `country` (`id`, `name`) VALUES ('ja', 'japones');
INSERT INTO `country` (`id`, `name`) VALUES ('jv', 'javanes');
INSERT INTO `country` (`id`, `name`) VALUES ('kea', 'kabuverdianu');
INSERT INTO `country` (`id`, `name`) VALUES ('ca', 'katalãu');
INSERT INTO `country` (`id`, `name`) VALUES ('rw', 'kiniaruanda');
INSERT INTO `country` (`id`, `name`) VALUES ('km', 'kmer');
INSERT INTO `country` (`id`, `name`) VALUES ('ko', 'kureanu');
INSERT INTO `country` (`id`, `name`) VALUES ('und', 'lingua diskonxedu');
INSERT INTO `country` (`id`, `name`) VALUES ('ms', 'malaiu');
INSERT INTO `country` (`id`, `name`) VALUES ('ne', 'nepales');
INSERT INTO `country` (`id`, `name`) VALUES ('nl', 'olandes');
INSERT INTO `country` (`id`, `name`) VALUES ('pa', 'pandjabi');
INSERT INTO `country` (`id`, `name`) VALUES ('fa', 'persa');
INSERT INTO `country` (`id`, `name`) VALUES ('pl', 'pulaku');
INSERT INTO `country` (`id`, `name`) VALUES ('pt', 'purtuges');
INSERT INTO `country` (`id`, `name`) VALUES ('pt_BR', 'purtuges brazileru');
INSERT INTO `country` (`id`, `name`) VALUES ('pt_PT', 'purtuges europeu');
INSERT INTO `country` (`id`, `name`) VALUES ('ro', 'rumenu');
INSERT INTO `country` (`id`, `name`) VALUES ('ru', 'rusu');
INSERT INTO `country` (`id`, `name`) VALUES ('so', 'somali');
INSERT INTO `country` (`id`, `name`) VALUES ('es', 'spanhol');
INSERT INTO `country` (`id`, `name`) VALUES ('es_ES', 'spanhol europeu');
INSERT INTO `country` (`id`, `name`) VALUES ('es_419', 'spanhol latinu-merkanu');
INSERT INTO `country` (`id`, `name`) VALUES ('sv', 'sueku');
INSERT INTO `country` (`id`, `name`) VALUES ('th', 'tailandes');
INSERT INTO `country` (`id`, `name`) VALUES ('ta', 'tamil');
INSERT INTO `country` (`id`, `name`) VALUES ('bo', 'tibetanu');
INSERT INTO `country` (`id`, `name`) VALUES ('tr', 'turku');
INSERT INTO `country` (`id`, `name`) VALUES ('cs', 'txeku');
INSERT INTO `country` (`id`, `name`) VALUES ('uk', 'ukranianu');
INSERT INTO `country` (`id`, `name`) VALUES ('hu', 'ungaru');
INSERT INTO `country` (`id`, `name`) VALUES ('ur', 'urdu');
INSERT INTO `country` (`id`, `name`) VALUES ('vi', 'vietnamita');
INSERT INTO `country` (`id`, `name`) VALUES ('zh', 'xines');
INSERT INTO `country` (`id`, `name`) VALUES ('zh_Hans', 'xines simplifikadu');
INSERT INTO `country` (`id`, `name`) VALUES ('zh_Hant', 'xines tradisional');
INSERT INTO `country` (`id`, `name`) VALUES ('zu', 'zulu');
