CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('hy', 'ارمني');
INSERT INTO [country] ([id], [name]) VALUES ('uz', 'ازبکي');
INSERT INTO [country] ([id], [name]) VALUES ('de', 'الماني');
INSERT INTO [country] ([id], [name]) VALUES ('en', 'انګلیسي');
INSERT INTO [country] ([id], [name]) VALUES ('it', 'ایټالوي');
INSERT INTO [country] ([id], [name]) VALUES ('bal', 'بلوڅي');
INSERT INTO [country] ([id], [name]) VALUES ('ps', 'پښتو');
INSERT INTO [country] ([id], [name]) VALUES ('pt', 'پورتګالي');
INSERT INTO [country] ([id], [name]) VALUES ('pl', 'پولنډي');
INSERT INTO [country] ([id], [name]) VALUES ('tt', 'تاتار');
INSERT INTO [country] ([id], [name]) VALUES ('tg', 'تاجک');
INSERT INTO [country] ([id], [name]) VALUES ('tk', 'ترکمني');
INSERT INTO [country] ([id], [name]) VALUES ('ja', 'جاپانی');
INSERT INTO [country] ([id], [name]) VALUES ('zh', 'چیني');
INSERT INTO [country] ([id], [name]) VALUES ('et', 'حبشي');
INSERT INTO [country] ([id], [name]) VALUES ('ru', 'روسي');
INSERT INTO [country] ([id], [name]) VALUES ('sa', 'سنسکریټ');
INSERT INTO [country] ([id], [name]) VALUES ('sv', 'سویډنی');
INSERT INTO [country] ([id], [name]) VALUES ('he', 'عبري');
INSERT INTO [country] ([id], [name]) VALUES ('ar', 'عربي');
INSERT INTO [country] ([id], [name]) VALUES ('fa', 'فارسي');
INSERT INTO [country] ([id], [name]) VALUES ('fr', 'فرانسوي');
INSERT INTO [country] ([id], [name]) VALUES ('fi', 'فینلنډي');
INSERT INTO [country] ([id], [name]) VALUES ('ku', 'کردي');
INSERT INTO [country] ([id], [name]) VALUES ('la', 'لاتیني');
INSERT INTO [country] ([id], [name]) VALUES ('mn', 'مغولي');
INSERT INTO [country] ([id], [name]) VALUES ('mk', 'مقدوني');
INSERT INTO [country] ([id], [name]) VALUES ('ms', 'ملایا');
INSERT INTO [country] ([id], [name]) VALUES ('mg', 'ملغاسي');
INSERT INTO [country] ([id], [name]) VALUES ('ine', 'هند و اروپایي');
INSERT INTO [country] ([id], [name]) VALUES ('hi', 'هندي');
INSERT INTO [country] ([id], [name]) VALUES ('el', 'یوناني');
