CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('ga', 'آئيرِش');
INSERT INTO "country" ("id", "name") VALUES ('az', 'آزربائیجانی');
INSERT INTO "country" ("id", "name") VALUES ('as', 'آسامی');
INSERT INTO "country" ("id", "name") VALUES ('oc', 'آکيٹانی');
INSERT INTO "country" ("id", "name") VALUES ('ur', 'اردو');
INSERT INTO "country" ("id", "name") VALUES ('hy', 'ارمینی');
INSERT INTO "country" ("id", "name") VALUES ('uz', 'ازبک');
INSERT INTO "country" ("id", "name") VALUES ('et', 'اسٹونين');
INSERT INTO "country" ("id", "name") VALUES ('it', 'اطالوی');
INSERT INTO "country" ("id", "name") VALUES ('sq', 'البانی');
INSERT INTO "country" ("id", "name") VALUES ('en_US', 'امریکہ کی انگریزی');
INSERT INTO "country" ("id", "name") VALUES ('am', 'امہاری');
INSERT INTO "country" ("id", "name") VALUES ('ia', 'انٹرلنگوی');
INSERT INTO "country" ("id", "name") VALUES ('id', 'انڈونيثيائی');
INSERT INTO "country" ("id", "name") VALUES ('en', 'انگريزی');
INSERT INTO "country" ("id", "name") VALUES ('or', 'اورِیا');
INSERT INTO "country" ("id", "name") VALUES ('eo', 'ايسپرانٹو');
INSERT INTO "country" ("id", "name") VALUES ('af', 'ايفريکانز');
INSERT INTO "country" ("id", "name") VALUES ('ug', 'اُئِیگُور');
INSERT INTO "country" ("id", "name") VALUES ('eu', 'باسکی');
INSERT INTO "country" ("id", "name") VALUES ('en_GB', 'برطانوی انگریزی');
INSERT INTO "country" ("id", "name") VALUES ('is', 'برفستانی');
INSERT INTO "country" ("id", "name") VALUES ('br', 'برِیٹن');
INSERT INTO "country" ("id", "name") VALUES ('bg', 'بلغاری');
INSERT INTO "country" ("id", "name") VALUES ('bn', 'بنگالی');
INSERT INTO "country" ("id", "name") VALUES ('bs', 'بوسنی');
INSERT INTO "country" ("id", "name") VALUES ('be', 'بيلاروسی');
INSERT INTO "country" ("id", "name") VALUES ('bh', 'بِہاری');
INSERT INTO "country" ("id", "name") VALUES ('ta', 'تامِل');
INSERT INTO "country" ("id", "name") VALUES ('tk', 'ترکمانی');
INSERT INTO "country" ("id", "name") VALUES ('tr', 'ترکی');
INSERT INTO "country" ("id", "name") VALUES ('th', 'تهائی');
INSERT INTO "country" ("id", "name") VALUES ('tw', 'توی');
INSERT INTO "country" ("id", "name") VALUES ('te', 'تيلوگو');
INSERT INTO "country" ("id", "name") VALUES ('ti', 'تگرینی');
INSERT INTO "country" ("id", "name") VALUES ('ka', 'جارجی');
INSERT INTO "country" ("id", "name") VALUES ('jv', 'جاوی');
INSERT INTO "country" ("id", "name") VALUES ('ja', 'جاپانی');
INSERT INTO "country" ("id", "name") VALUES ('de', 'جرمن');
INSERT INTO "country" ("id", "name") VALUES ('xh', 'خوسہ');
INSERT INTO "country" ("id", "name") VALUES ('ru', 'روسی');
INSERT INTO "country" ("id", "name") VALUES ('ro', 'رومنی');
INSERT INTO "country" ("id", "name") VALUES ('zu', 'زُولُو');
INSERT INTO "country" ("id", "name") VALUES ('sh', 'سربو-کروئیشین');
INSERT INTO "country" ("id", "name") VALUES ('sk', 'سلاواکی');
INSERT INTO "country" ("id", "name") VALUES ('sl', 'سلوينی');
INSERT INTO "country" ("id", "name") VALUES ('sd', 'سندھی');
INSERT INTO "country" ("id", "name") VALUES ('si', 'سنہالی');
INSERT INTO "country" ("id", "name") VALUES ('sw', 'سواہیلی');
INSERT INTO "country" ("id", "name") VALUES ('so', 'سومالی');
INSERT INTO "country" ("id", "name") VALUES ('sv', 'سويڈش');
INSERT INTO "country" ("id", "name") VALUES ('sa', 'سَنسکرِت');
INSERT INTO "country" ("id", "name") VALUES ('su', 'سُوڈانی');
INSERT INTO "country" ("id", "name") VALUES ('gd', 'سکاٹ گيلِک');
INSERT INTO "country" ("id", "name") VALUES ('st', 'سیسوتھو');
INSERT INTO "country" ("id", "name") VALUES ('sr', 'صربی');
INSERT INTO "country" ("id", "name") VALUES ('he', 'عبرانی');
INSERT INTO "country" ("id", "name") VALUES ('ar', 'عربی');
INSERT INTO "country" ("id", "name") VALUES ('fa', 'فارسی');
INSERT INTO "country" ("id", "name") VALUES ('fr', 'فرانسيسی');
INSERT INTO "country" ("id", "name") VALUES ('fy', 'فريژين');
INSERT INTO "country" ("id", "name") VALUES ('fi', 'فنّنِش');
INSERT INTO "country" ("id", "name") VALUES ('fo', 'فیروئیز');
INSERT INTO "country" ("id", "name") VALUES ('ku', 'كردش');
INSERT INTO "country" ("id", "name") VALUES ('lo', 'لاؤشِیَن');
INSERT INTO "country" ("id", "name") VALUES ('la', 'لاطينی');
INSERT INTO "country" ("id", "name") VALUES ('lt', 'لتھُواینین');
INSERT INTO "country" ("id", "name") VALUES ('lv', 'ليٹوين');
INSERT INTO "country" ("id", "name") VALUES ('ln', 'لِنگَلا');
INSERT INTO "country" ("id", "name") VALUES ('ms', 'مالائی');
INSERT INTO "country" ("id", "name") VALUES ('ml', 'مالايالم');
INSERT INTO "country" ("id", "name") VALUES ('mt', 'مالٹی');
INSERT INTO "country" ("id", "name") VALUES ('mr', 'مراٹهی');
INSERT INTO "country" ("id", "name") VALUES ('mk', 'مقدونيائی');
INSERT INTO "country" ("id", "name") VALUES ('mn', 'منگؤلی');
INSERT INTO "country" ("id", "name") VALUES ('no', 'نارويجين');
INSERT INTO "country" ("id", "name") VALUES ('nn', 'نورویجینی (نینورسک)');
INSERT INTO "country" ("id", "name") VALUES ('ne', 'نيپالی');
INSERT INTO "country" ("id", "name") VALUES ('vi', 'ويتنامی');
INSERT INTO "country" ("id", "name") VALUES ('cy', 'ويلش');
INSERT INTO "country" ("id", "name") VALUES ('yi', 'يادش');
INSERT INTO "country" ("id", "name") VALUES ('el', 'يونانی');
INSERT INTO "country" ("id", "name") VALUES ('uk', 'يُوکرينی');
INSERT INTO "country" ("id", "name") VALUES ('fil', 'ٹيگالاگی');
INSERT INTO "country" ("id", "name") VALUES ('tl', 'ٹیگا لوگ');
INSERT INTO "country" ("id", "name") VALUES ('pt_PT', 'پرتگالی (پرتگال)');
INSERT INTO "country" ("id", "name") VALUES ('pt_BR', 'پرتگالی (ﺑﺮﺍﺯﻳﻞ)');
INSERT INTO "country" ("id", "name") VALUES ('ps', 'پشتو');
INSERT INTO "country" ("id", "name") VALUES ('pa', 'پنجابی');
INSERT INTO "country" ("id", "name") VALUES ('pl', 'پولستانی');
INSERT INTO "country" ("id", "name") VALUES ('pt', 'پُرتگالی');
INSERT INTO "country" ("id", "name") VALUES ('cs', 'چيک');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hans', 'چینی (آسان کردہ)');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hant', 'چینی (روایتی)');
INSERT INTO "country" ("id", "name") VALUES ('da', 'ڈينش');
INSERT INTO "country" ("id", "name") VALUES ('nl', 'ڈچ');
INSERT INTO "country" ("id", "name") VALUES ('ca', 'کاٹالانين');
INSERT INTO "country" ("id", "name") VALUES ('hr', 'کراتی');
INSERT INTO "country" ("id", "name") VALUES ('ky', 'کرغیزی');
INSERT INTO "country" ("id", "name") VALUES ('tlh', 'کلنگان');
INSERT INTO "country" ("id", "name") VALUES ('km', 'کمبوڈیَن');
INSERT INTO "country" ("id", "name") VALUES ('kn', 'کنّاڈا');
INSERT INTO "country" ("id", "name") VALUES ('ko', 'کورين');
INSERT INTO "country" ("id", "name") VALUES ('gl', 'گاليشيائی');
INSERT INTO "country" ("id", "name") VALUES ('gu', 'گجراتی');
INSERT INTO "country" ("id", "name") VALUES ('gn', 'گُارانی');
INSERT INTO "country" ("id", "name") VALUES ('es', 'ہسپانوی');
INSERT INTO "country" ("id", "name") VALUES ('hi', 'ہندی');
INSERT INTO "country" ("id", "name") VALUES ('hu', 'ہنگیرین');
