CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('ak', 'അകാന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('ach', 'അകോലി');
INSERT INTO [country] ([id], [name]) VALUES ('akk', 'അക്കാഡിയന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('ace', 'അചിനീസ്');
INSERT INTO [country] ([id], [name]) VALUES ('ada', 'അഡാങ്ഗമി');
INSERT INTO [country] ([id], [name]) VALUES ('ady', 'അഡൈഗേ');
INSERT INTO [country] ([id], [name]) VALUES ('ath', 'അതപാസ്കന്‍ ഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('hsb', 'അപ്പര്‍ സോര്‍ബിയന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('apa', 'അപ്പാചേ ഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('aa', 'അഫാര്‍');
INSERT INTO [country] ([id], [name]) VALUES ('ab', 'അബ്ഖാസിയന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('am', 'അമാറിക്');
INSERT INTO [country] ([id], [name]) VALUES ('en_US', 'അമേരിക്കന്‍ ഇംഗ്ലീഷ്');
INSERT INTO [country] ([id], [name]) VALUES ('ain', 'അയിനു');
INSERT INTO [country] ([id], [name]) VALUES ('ay', 'അയ്മാറ');
INSERT INTO [country] ([id], [name]) VALUES ('an', 'അരഗോണീസ്');
INSERT INTO [country] ([id], [name]) VALUES ('arp', 'അരപാഹോ');
INSERT INTO [country] ([id], [name]) VALUES ('arc', 'അരമായഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('hy', 'അര്‍മേനിയന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('ar', 'അറബി');
INSERT INTO [country] ([id], [name]) VALUES ('arw', 'അറാവക്');
INSERT INTO [country] ([id], [name]) VALUES ('und', 'അറിയാത്തതോ നിലവിലില്ലാത്തതോ ആയ ഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('tut', 'അറ്റ്ലാന്‍റിക്ക് ഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('cch', 'അറ്റ്സാം');
INSERT INTO [country] ([id], [name]) VALUES ('ale', 'അലൈട്ട്');
INSERT INTO [country] ([id], [name]) VALUES ('alg', 'അല്‍ഗോണ്‍ക്യന്‍ ഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('sq', 'അല്‍ബേനിയന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('awa', 'അവധി');
INSERT INTO [country] ([id], [name]) VALUES ('ae', 'അവസ്റ്റാന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('av', 'അവാരിക്');
INSERT INTO [country] ([id], [name]) VALUES ('az', 'അസര്‍ബൈജാനി');
INSERT INTO [country] ([id], [name]) VALUES ('sgn', 'ആംഗ്യഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('anp', 'ആന്‍ഗിക');
INSERT INTO [country] ([id], [name]) VALUES ('af', 'ആഫ്രിക്കാന്‍സ്');
INSERT INTO [country] ([id], [name]) VALUES ('afh', 'ആഫ്രിഹിലി');
INSERT INTO [country] ([id], [name]) VALUES ('afa', 'ആഫ്രോ-ഏഷ്യാറ്റിക് ഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('rup', 'ആരോമാനിയന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('arn', 'ആരൗകാനിയന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('as', 'ആസ്സാമീസ്');
INSERT INTO [country] ([id], [name]) VALUES ('en', 'ഇംഗ്ലീഷ്');
INSERT INTO [country] ([id], [name]) VALUES ('cpe', 'ഇംഗ്ലീഷ് അധിഷ്ഠിത മിശ്ര ഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('inh', 'ഇംഗ്വിഷ്');
INSERT INTO [country] ([id], [name]) VALUES ('ig', 'ഇഗ്ബോ');
INSERT INTO [country] ([id], [name]) VALUES ('ijo', 'ഇജോ');
INSERT INTO [country] ([id], [name]) VALUES ('io', 'ഇഡോ');
INSERT INTO [country] ([id], [name]) VALUES ('mis', 'ഇതരഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('smn', 'ഇനാരി സാമി');
INSERT INTO [country] ([id], [name]) VALUES ('iu', 'ഇനുക്റ്റിറ്റട്ട്');
INSERT INTO [country] ([id], [name]) VALUES ('ik', 'ഇനുപിയാക്');
INSERT INTO [country] ([id], [name]) VALUES ('ie', 'ഇന്റര്‍ലിംഗ്വ');
INSERT INTO [country] ([id], [name]) VALUES ('nqo', 'ഇന്‍കോ');
INSERT INTO [country] ([id], [name]) VALUES ('ine', 'ഇന്‍ഡോ-യൂറോപ്യന്‍ ഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('id', 'ഇന്‍ഡോനേഷ്യന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('ia', 'ഇന്‍റര്‍ലിംഗ്വാ');
INSERT INTO [country] ([id], [name]) VALUES ('iba', 'ഇബാന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('pt_PT', 'ഇബേറിയന്‍ പോര്‍ച്ചുഗീസ്');
INSERT INTO [country] ([id], [name]) VALUES ('es_ES', 'ഇബേറിയന്‍ സ്പാനിഷ്');
INSERT INTO [country] ([id], [name]) VALUES ('ira', 'ഇറാനിയന്‍ ഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('iro', 'ഇറോക്വായിയന്‍ ഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('it', 'ഇറ്റാലിയന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('ilo', 'ഇലോകോ');
INSERT INTO [country] ([id], [name]) VALUES ('frs', 'ഈസ്റ്റേണ്‍ ഫ്രിഷ്യന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('umb', 'ഉംബുന്ദു');
INSERT INTO [country] ([id], [name]) VALUES ('uk', 'ഉക്രേനിയന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('uga', 'ഉഗറിട്ടിക്');
INSERT INTO [country] ([id], [name]) VALUES ('udm', 'ഉഡ്മുര്‍ട്ട്');
INSERT INTO [country] ([id], [name]) VALUES ('ug', 'ഉയ്ഘുര്‍');
INSERT INTO [country] ([id], [name]) VALUES ('ur', 'ഉറുദു');
INSERT INTO [country] ([id], [name]) VALUES ('uz', 'ഉസ്ബെക്');
INSERT INTO [country] ([id], [name]) VALUES ('eka', 'എകാജുക്');
INSERT INTO [country] ([id], [name]) VALUES ('efi', 'എഫിക്');
INSERT INTO [country] ([id], [name]) VALUES ('elx', 'എലാമൈറ്റ്');
INSERT INTO [country] ([id], [name]) VALUES ('ewo', 'എവോന്‍ഡോ');
INSERT INTO [country] ([id], [name]) VALUES ('ee', 'എവ്');
INSERT INTO [country] ([id], [name]) VALUES ('eo', 'എസ്പരാന്തോ');
INSERT INTO [country] ([id], [name]) VALUES ('et', 'എസ്റ്റോണിയന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('myv', 'ഏഴ്സ്യ');
INSERT INTO [country] ([id], [name]) VALUES ('ga', 'ഐറിഷ്');
INSERT INTO [country] ([id], [name]) VALUES ('is', 'ഐസ്‌ലാന്‍ഡിക്');
INSERT INTO [country] ([id], [name]) VALUES ('oc', 'ഒക്സിററന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('or', 'ഒറിയ');
INSERT INTO [country] ([id], [name]) VALUES ('om', 'ഒറോമൂ');
INSERT INTO [country] ([id], [name]) VALUES ('osa', 'ഒസേജ്');
INSERT INTO [country] ([id], [name]) VALUES ('os', 'ഒസ്സെറ്റിക്');
INSERT INTO [country] ([id], [name]) VALUES ('oj', 'ഓജിബ്വാ');
INSERT INTO [country] ([id], [name]) VALUES ('ota', 'ഓട്ടോമന്‍ തുര്‍ക്കിഷ്');
INSERT INTO [country] ([id], [name]) VALUES ('oto', 'ഓട്ടോമിയന്‍ ഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('de_AT', 'ഓസ്ട്രിയന്‍ ജര്‍മന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('en_AU', 'ഓസ്ട്രേലിയന്‍ ഇംഗ്ലീഷ്');
INSERT INTO [country] ([id], [name]) VALUES ('aus', 'ഓസ്ട്രേലിയന്‍ ഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('map', 'ഓസ്ട്രോനേഷ്യന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('ast', 'ഓസ്‌ട്രിയന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('kam', 'കംബ');
INSERT INTO [country] ([id], [name]) VALUES ('km', 'കംബോഡിയന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('kr', 'കനൂറി');
INSERT INTO [country] ([id], [name]) VALUES ('en_CA', 'കനേഡിയന്‍ ഇംഗ്ലീഷ്');
INSERT INTO [country] ([id], [name]) VALUES ('fr_CA', 'കനേഡിയന്‍ ഫ്രഞ്ച്');
INSERT INTO [country] ([id], [name]) VALUES ('kn', 'കന്നഡ');
INSERT INTO [country] ([id], [name]) VALUES ('kpe', 'കപെല്ലേ');
INSERT INTO [country] ([id], [name]) VALUES ('kbd', 'കബര്‍ഡിയാന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('kab', 'കബൈല്‍');
INSERT INTO [country] ([id], [name]) VALUES ('ch', 'കമോറോ');
INSERT INTO [country] ([id], [name]) VALUES ('kaa', 'കര-കാല്‍പ്പക്');
INSERT INTO [country] ([id], [name]) VALUES ('krc', 'കരചൈ-ബാല്‍കര്‍');
INSERT INTO [country] ([id], [name]) VALUES ('krl', 'കരീലിയന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('kar', 'കരേന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('ca', 'കറ്റാലന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('kl', 'കലാല്ലിസട്ട്');
INSERT INTO [country] ([id], [name]) VALUES ('xal', 'കല്‍മൈക്');
INSERT INTO [country] ([id], [name]) VALUES ('kk', 'കസാഖ്');
INSERT INTO [country] ([id], [name]) VALUES ('kac', 'കാചിന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('cad', 'കാഡോ');
INSERT INTO [country] ([id], [name]) VALUES ('car', 'കാരിബ്');
INSERT INTO [country] ([id], [name]) VALUES ('kaw', 'കാവി');
INSERT INTO [country] ([id], [name]) VALUES ('ks', 'കാശ്മീരി');
INSERT INTO [country] ([id], [name]) VALUES ('csb', 'കാഷുബിയാന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('ki', 'കികൂയു');
INSERT INTO [country] ([id], [name]) VALUES ('rw', 'കിന്യര്‍വണ്ട');
INSERT INTO [country] ([id], [name]) VALUES ('ky', 'കിര്‍ഗിസ്');
INSERT INTO [country] ([id], [name]) VALUES ('kut', 'കുതേനൈ');
INSERT INTO [country] ([id], [name]) VALUES ('kum', 'കുമൈക്');
INSERT INTO [country] ([id], [name]) VALUES ('kru', 'കുരുഖ്');
INSERT INTO [country] ([id], [name]) VALUES ('ku', 'കുര്‍ദ്ദിഷ്');
INSERT INTO [country] ([id], [name]) VALUES ('cus', 'കുഷിറ്റിക് ഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('art', 'കൃത്രിമഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('cau', 'കൊക്കേഷ്യന്‍ ഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('kok', 'കൊങ്കണി');
INSERT INTO [country] ([id], [name]) VALUES ('ko', 'കൊറിയന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('kos', 'കൊസറേയന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('kg', 'കോംഗോ');
INSERT INTO [country] ([id], [name]) VALUES ('cop', 'കോപ്റ്റിക്');
INSERT INTO [country] ([id], [name]) VALUES ('kv', 'കോമി');
INSERT INTO [country] ([id], [name]) VALUES ('kw', 'കോര്‍ണിഷ്');
INSERT INTO [country] ([id], [name]) VALUES ('kfo', 'കോറോ');
INSERT INTO [country] ([id], [name]) VALUES ('co', 'കോഴ്സിക്കണ്‍');
INSERT INTO [country] ([id], [name]) VALUES ('crh', 'ക്രിമിയന്‍ ടര്‍ക്കിഷ്');
INSERT INTO [country] ([id], [name]) VALUES ('cr', 'ക്രീ');
INSERT INTO [country] ([id], [name]) VALUES ('mus', 'ക്രീക്ക്');
INSERT INTO [country] ([id], [name]) VALUES ('kro', 'ക്രു');
INSERT INTO [country] ([id], [name]) VALUES ('hr', 'ക്രൊയേഷ്യന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('nwc', 'ക്ലാസിക്കല്‍ നേവാരി');
INSERT INTO [country] ([id], [name]) VALUES ('kmb', 'ക്ലിംഗന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('tlh', 'ക്ലിംഗോണ്‍');
INSERT INTO [country] ([id], [name]) VALUES ('kj', 'ക്വാന്യമ');
INSERT INTO [country] ([id], [name]) VALUES ('qu', 'ക്വെച്ചുവ');
INSERT INTO [country] ([id], [name]) VALUES ('xh', 'ഖോസാ');
INSERT INTO [country] ([id], [name]) VALUES ('gba', 'ഗബ്യ');
INSERT INTO [country] ([id], [name]) VALUES ('gay', 'ഗയൊ');
INSERT INTO [country] ([id], [name]) VALUES ('gl', 'ഗലീഷ്യന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('gaa', 'ഗാ');
INSERT INTO [country] ([id], [name]) VALUES ('lg', 'ഗാന്‍ഡ');
INSERT INTO [country] ([id], [name]) VALUES ('gil', 'ഗില്‍ബര്‍സേ');
INSERT INTO [country] ([id], [name]) VALUES ('gez', 'ഗീസ്');
INSERT INTO [country] ([id], [name]) VALUES ('gu', 'ഗുജറാത്തി');
INSERT INTO [country] ([id], [name]) VALUES ('gor', 'ഗൊറോന്‍റാലോ');
INSERT INTO [country] ([id], [name]) VALUES ('gon', 'ഗോണ്ഡി');
INSERT INTO [country] ([id], [name]) VALUES ('got', 'ഗോഥിക്ക്');
INSERT INTO [country] ([id], [name]) VALUES ('grb', 'ഗ്രബൊ');
INSERT INTO [country] ([id], [name]) VALUES ('el', 'ഗ്രീക്ക്');
INSERT INTO [country] ([id], [name]) VALUES ('gn', 'ഗ്വാറാനി');
INSERT INTO [country] ([id], [name]) VALUES ('gwi', 'ഗ്വിച്ച് ഇന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('kha', 'ഘാസി');
INSERT INTO [country] ([id], [name]) VALUES ('khi', 'ഘോയിസന്‍ ഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('kho', 'ഘോറ്റാനേസേ');
INSERT INTO [country] ([id], [name]) VALUES ('chg', 'ചഗതൈ');
INSERT INTO [country] ([id], [name]) VALUES ('cu', 'ചര്‍ച്ച് സ്ലാവിക്');
INSERT INTO [country] ([id], [name]) VALUES ('cmc', 'ചാമിക് ഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('chn', 'ചിനൂഗ്-ജാര്‍ഗണ്‍');
INSERT INTO [country] ([id], [name]) VALUES ('chp', 'ചിപേവ്യന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('chb', 'ചിബ്ച');
INSERT INTO [country] ([id], [name]) VALUES ('chy', 'ചിയേന്നേ');
INSERT INTO [country] ([id], [name]) VALUES ('sit', 'ചീന-ടിബത്തന്‍ ഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('cv', 'ചുവാഷ്');
INSERT INTO [country] ([id], [name]) VALUES ('chk', 'ചൂകീസ്');
INSERT INTO [country] ([id], [name]) VALUES ('cs', 'ചെക്ക്');
INSERT INTO [country] ([id], [name]) VALUES ('ce', 'ചെചന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('chr', 'ചെരോകീ');
INSERT INTO [country] ([id], [name]) VALUES ('zh', 'ചൈനീസ്');
INSERT INTO [country] ([id], [name]) VALUES ('cho', 'ചോക്റ്റാവ്');
INSERT INTO [country] ([id], [name]) VALUES ('ja', 'ജപ്പാനീസ്');
INSERT INTO [country] ([id], [name]) VALUES ('gem', 'ജര്‍മാനിക് ഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('de', 'ജര്‍മ്മന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('jv', 'ജാവാനീസ്');
INSERT INTO [country] ([id], [name]) VALUES ('jrb', 'ജൂഡിയോ-അറബിക്');
INSERT INTO [country] ([id], [name]) VALUES ('jpr', 'ജൂഡിയോ-പേര്‍ഷ്യന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('ka', 'ജോര്‍ജിയന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('kaj', 'ജ്ജു');
INSERT INTO [country] ([id], [name]) VALUES ('tmh', 'ടമഷേക്');
INSERT INTO [country] ([id], [name]) VALUES ('tt', 'ടാട്ടാര്‍');
INSERT INTO [country] ([id], [name]) VALUES ('tem', 'ടിംനേ');
INSERT INTO [country] ([id], [name]) VALUES ('tiv', 'ടിവ്');
INSERT INTO [country] ([id], [name]) VALUES ('ter', 'ടെറേനോ');
INSERT INTO [country] ([id], [name]) VALUES ('tet', 'ടെറ്റും');
INSERT INTO [country] ([id], [name]) VALUES ('tig', 'ടൈഗ്രി');
INSERT INTO [country] ([id], [name]) VALUES ('ti', 'ടൈഗ്രിന്യ');
INSERT INTO [country] ([id], [name]) VALUES ('tkl', 'ടൊക്കേലൗ');
INSERT INTO [country] ([id], [name]) VALUES ('to', 'ടോംഗ');
INSERT INTO [country] ([id], [name]) VALUES ('tpi', 'ടോക് പിസിന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('kcg', 'ട്യാപ്');
INSERT INTO [country] ([id], [name]) VALUES ('tw', 'ട്വി');
INSERT INTO [country] ([id], [name]) VALUES ('dak', 'ഡകോട്ട');
INSERT INTO [country] ([id], [name]) VALUES ('nl', 'ഡച്ച്');
INSERT INTO [country] ([id], [name]) VALUES ('dar', 'ഡര്‍ഗ്വാ');
INSERT INTO [country] ([id], [name]) VALUES ('da', 'ഡാനിഷ്');
INSERT INTO [country] ([id], [name]) VALUES ('doi', 'ഡോഗ്രി');
INSERT INTO [country] ([id], [name]) VALUES ('dgr', 'ഡോഗ്രിബ്');
INSERT INTO [country] ([id], [name]) VALUES ('ng', 'ഡോങ്ക');
INSERT INTO [country] ([id], [name]) VALUES ('tl', 'തഗാലോഗ്');
INSERT INTO [country] ([id], [name]) VALUES ('ta', 'തമിഴ്');
INSERT INTO [country] ([id], [name]) VALUES ('tg', 'താജിക്');
INSERT INTO [country] ([id], [name]) VALUES ('th', 'തായ്');
INSERT INTO [country] ([id], [name]) VALUES ('tai', 'തായ് ഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('ty', 'താഹിതിയന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('bo', 'തിബറ്റന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('tum', 'തുംബുക');
INSERT INTO [country] ([id], [name]) VALUES ('tup', 'തുപി ഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('tr', 'തുര്‍ക്കി');
INSERT INTO [country] ([id], [name]) VALUES ('tk', 'തുര്‍ക്മെന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('tvl', 'തുവാലു');
INSERT INTO [country] ([id], [name]) VALUES ('tyv', 'തുവിനിയന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('st', 'തെക്കന്‍ സോതോ');
INSERT INTO [country] ([id], [name]) VALUES ('te', 'തെലുങ്ക്');
INSERT INTO [country] ([id], [name]) VALUES ('ts', 'ത്സോംഗ');
INSERT INTO [country] ([id], [name]) VALUES ('tn', 'ത്സ്വാന');
INSERT INTO [country] ([id], [name]) VALUES ('sai', 'ദക്ഷിണ അമേരിക്കന്‍ ഇന്‍ഡ്യന്‍ ഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('nr', 'ദക്ഷിണ നെഡിബിള്‍');
INSERT INTO [country] ([id], [name]) VALUES ('day', 'ദയാക്');
INSERT INTO [country] ([id], [name]) VALUES ('del', 'ദലവാരെ');
INSERT INTO [country] ([id], [name]) VALUES ('din', 'ദിന്‍ക');
INSERT INTO [country] ([id], [name]) VALUES ('dv', 'ദിവെഹി');
INSERT INTO [country] ([id], [name]) VALUES ('dra', 'ദ്രാവിഡഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('dua', 'ദ്വാല');
INSERT INTO [country] ([id], [name]) VALUES ('dyu', 'ദ്വൈല');
INSERT INTO [country] ([id], [name]) VALUES ('nv', 'നവാഹൊ');
INSERT INTO [country] ([id], [name]) VALUES ('nah', 'നാഹ്വാള്‍‍ട്ട്');
INSERT INTO [country] ([id], [name]) VALUES ('nia', 'നിയാസ്');
INSERT INTO [country] ([id], [name]) VALUES ('ssa', 'നിളോ-സഹാറന്‍ ഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('nub', 'നുബിയന്‍ ഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('nap', 'നെപ്പോളിറ്റാന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('ne', 'നേപ്പാളി');
INSERT INTO [country] ([id], [name]) VALUES ('new', 'നേവാരി');
INSERT INTO [country] ([id], [name]) VALUES ('nic', 'നൈ‍ജര്‍-കോര്‍‍ഡോഫാനിയന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('nog', 'നോഗൈ');
INSERT INTO [country] ([id], [name]) VALUES ('frr', 'നോര്‍ത്തേന്‍ ഫ്രിഷ്യന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('nso', 'നോര്‍ത്തേന്‍ സോതോ');
INSERT INTO [country] ([id], [name]) VALUES ('nd', 'നോര്‍ത്ത് ഡെബിള്‍');
INSERT INTO [country] ([id], [name]) VALUES ('no', 'നോര്‍വീജിയന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('nn', 'നോര്‍വീജിയന്‍ നൈനോര്‍ക്സ്');
INSERT INTO [country] ([id], [name]) VALUES ('nb', 'നോര്‍വീജിയന്‍ ബുക്‌മല്‍');
INSERT INTO [country] ([id], [name]) VALUES ('ny', 'ന്യന്‍ജ');
INSERT INTO [country] ([id], [name]) VALUES ('nym', 'ന്യാംവേസി');
INSERT INTO [country] ([id], [name]) VALUES ('nyn', 'ന്യാന്‍കലേ');
INSERT INTO [country] ([id], [name]) VALUES ('tog', 'ന്യാസാ ഡോങ്ക');
INSERT INTO [country] ([id], [name]) VALUES ('niu', 'ന്യുവാന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('nyo', 'ന്യോറോ');
INSERT INTO [country] ([id], [name]) VALUES ('na', 'നൗറു');
INSERT INTO [country] ([id], [name]) VALUES ('pag', 'പങ്കാസിനന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('pa', 'പഞ്ചാബി');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hant', 'പരമ്പരാഗത ചൈനീസ്‌');
INSERT INTO [country] ([id], [name]) VALUES ('mul', 'പലഭാഷകള്‍');
INSERT INTO [country] ([id], [name]) VALUES ('pau', 'പലാവുന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('ang', 'പഴയ ഇംഗ്ലീഷ്');
INSERT INTO [country] ([id], [name]) VALUES ('non', 'പഴയ പേര്‍ഷ്യന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('fro', 'പഴയ ഫ്രഞ്ച്');
INSERT INTO [country] ([id], [name]) VALUES ('fy', 'പശ്ചിമ ഫ്രിഷിയന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('ps', 'പഷ്തു');
INSERT INTO [country] ([id], [name]) VALUES ('pam', 'പാംപന്‍ഗ');
INSERT INTO [country] ([id], [name]) VALUES ('pap', 'പാപിയാമെന്‍റൊ');
INSERT INTO [country] ([id], [name]) VALUES ('paa', 'പാപുവാന്‍ ഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('pi', 'പാലി');
INSERT INTO [country] ([id], [name]) VALUES ('pal', 'പാഹ്ലവി');
INSERT INTO [country] ([id], [name]) VALUES ('grc', 'പുരാതന യവന ഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('syc', 'പുരാതന സുറിയാനിഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('fa', 'പേര്‍ഷ്യന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('pon', 'പൊന്‍പിയന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('pt', 'പോര്‍ച്ചുഗീസ്');
INSERT INTO [country] ([id], [name]) VALUES ('cpp', 'പോര്‍ച്ചുഗീസ് അധിഷ്ടിത മിശ്ര ഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('pl', 'പോളിഷ്');
INSERT INTO [country] ([id], [name]) VALUES ('pra', 'പ്രാകൃതം');
INSERT INTO [country] ([id], [name]) VALUES ('egy', 'പ്രാചീന ഈജിപ്ഷ്യന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('goh', 'പ്രാചീന ഉച്ച ജര്‍മന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('sga', 'പ്രാചീന ഐറിഷ്');
INSERT INTO [country] ([id], [name]) VALUES ('peo', 'പ്രാചീന പേര്‍ഷ്യന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('pro', 'പ്രൊവന്‍ഷ്ല്‍');
INSERT INTO [country] ([id], [name]) VALUES ('fan', 'ഫങ്');
INSERT INTO [country] ([id], [name]) VALUES ('fo', 'ഫാറോസ്');
INSERT INTO [country] ([id], [name]) VALUES ('fj', 'ഫിജിയന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('fi', 'ഫിന്നിഷ്');
INSERT INTO [country] ([id], [name]) VALUES ('fiu', 'ഫിന്നോ-ഉഗ്രിയന്‍ ഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('phi', 'ഫിലിപീനി ഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('fil', 'ഫിലിപ്പിനോ');
INSERT INTO [country] ([id], [name]) VALUES ('fat', 'ഫിലിപ്പീനോ');
INSERT INTO [country] ([id], [name]) VALUES ('phn', 'ഫീനിഷ്യന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('ff', 'ഫുല');
INSERT INTO [country] ([id], [name]) VALUES ('fon', 'ഫോന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('fr', 'ഫ്രഞ്ച്');
INSERT INTO [country] ([id], [name]) VALUES ('cpf', 'ഫ്രഞ്ച് അധിഷ്ഠിത മിശ്രഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('fur', 'ഫ്രിയുലിയാന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('nl_BE', 'ഫ്ലമിഷ്');
INSERT INTO [country] ([id], [name]) VALUES ('bn', 'ബംഗാളി');
INSERT INTO [country] ([id], [name]) VALUES ('bm', 'ബംബാറ');
INSERT INTO [country] ([id], [name]) VALUES ('bad', 'ബന്‍ഡ');
INSERT INTO [country] ([id], [name]) VALUES ('my', 'ബര്‍മീസ്');
INSERT INTO [country] ([id], [name]) VALUES ('bal', 'ബലൂചി');
INSERT INTO [country] ([id], [name]) VALUES ('bg', 'ബള്‍ഗേറിയന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('ba', 'ബഷ്ഖിര്‍');
INSERT INTO [country] ([id], [name]) VALUES ('bas', 'ബസ');
INSERT INTO [country] ([id], [name]) VALUES ('bnt', 'ബാന്‌ടു');
INSERT INTO [country] ([id], [name]) VALUES ('bai', 'ബാമിലകേ ഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('btk', 'ബാറ്റക്');
INSERT INTO [country] ([id], [name]) VALUES ('ban', 'ബാലിനീസ്');
INSERT INTO [country] ([id], [name]) VALUES ('bat', 'ബാള്‍ട്ടിക് ഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('eu', 'ബാസ്ക്');
INSERT INTO [country] ([id], [name]) VALUES ('bik', 'ബികോല്‍');
INSERT INTO [country] ([id], [name]) VALUES ('bin', 'ബിനി');
INSERT INTO [country] ([id], [name]) VALUES ('bi', 'ബിസ്‌ലാമ');
INSERT INTO [country] ([id], [name]) VALUES ('bh', 'ബീഹാറി');
INSERT INTO [country] ([id], [name]) VALUES ('bug', 'ബുഗിനീസ്');
INSERT INTO [country] ([id], [name]) VALUES ('bua', 'ബുറിയത്ത്');
INSERT INTO [country] ([id], [name]) VALUES ('bem', 'ബെംബ');
INSERT INTO [country] ([id], [name]) VALUES ('ber', 'ബെര്‍ബര്‍');
INSERT INTO [country] ([id], [name]) VALUES ('bej', 'ബേജ');
INSERT INTO [country] ([id], [name]) VALUES ('be', 'ബൈലോറഷ്യന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('bs', 'ബോസ്നിയന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('bra', 'ബ്രജ്');
INSERT INTO [country] ([id], [name]) VALUES ('br', 'ബ്രറ്റണ്‍');
INSERT INTO [country] ([id], [name]) VALUES ('pt_BR', 'ബ്രസീലിയന്‍ പോര്‍ച്ചുഗീസ്');
INSERT INTO [country] ([id], [name]) VALUES ('en_GB', 'ബ്രിട്ടീഷ് ഇംഗ്ലീഷ്');
INSERT INTO [country] ([id], [name]) VALUES ('byn', 'ബ്ലിന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('zbl', 'ബ്ലിസ്സിംബല്‍സ്');
INSERT INTO [country] ([id], [name]) VALUES ('inc', 'ഭാരതീയഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('zxx', 'ഭാഷേതരം');
INSERT INTO [country] ([id], [name]) VALUES ('dz', 'ഭൂട്ടാനി');
INSERT INTO [country] ([id], [name]) VALUES ('bho', 'ഭോജ്‌പൂരി');
INSERT INTO [country] ([id], [name]) VALUES ('mn', 'മംഗോളിയന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('mak', 'മകാസര്‍');
INSERT INTO [country] ([id], [name]) VALUES ('mag', 'മഗാഹി');
INSERT INTO [country] ([id], [name]) VALUES ('mni', 'മണിപ്പൂരി');
INSERT INTO [country] ([id], [name]) VALUES ('mdr', 'മണ്ഡാര്‍');
INSERT INTO [country] ([id], [name]) VALUES ('man', 'മണ്ഡിന്‍ഗോ');
INSERT INTO [country] ([id], [name]) VALUES ('mad', 'മദുരേസേ');
INSERT INTO [country] ([id], [name]) VALUES ('cai', 'മദ്ധ്യ അമേരിക്കന്‍ ഇന്‍ഡ്യന്‍ ഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('enm', 'മദ്ധ്യ ഇംഗ്ലീഷ്');
INSERT INTO [country] ([id], [name]) VALUES ('gmh', 'മദ്ധ്യ ഉച്ച ജര്‍മന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('mga', 'മദ്ധ്യ ഐറിഷ്');
INSERT INTO [country] ([id], [name]) VALUES ('dum', 'മദ്ധ്യ ഡച്ച്');
INSERT INTO [country] ([id], [name]) VALUES ('frm', 'മദ്ധ്യ ഫ്രഞ്ച്');
INSERT INTO [country] ([id], [name]) VALUES ('mno', 'മനോബോ ഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('mnc', 'മന്‍ചു');
INSERT INTO [country] ([id], [name]) VALUES ('mwr', 'മര്‍വാരി');
INSERT INTO [country] ([id], [name]) VALUES ('mr', 'മറാഠി');
INSERT INTO [country] ([id], [name]) VALUES ('mg', 'മലഗാസി');
INSERT INTO [country] ([id], [name]) VALUES ('ms', 'മലയ');
INSERT INTO [country] ([id], [name]) VALUES ('ml', 'മലയാളം');
INSERT INTO [country] ([id], [name]) VALUES ('mas', 'മസൈ');
INSERT INTO [country] ([id], [name]) VALUES ('gv', 'മാന്‍സ്');
INSERT INTO [country] ([id], [name]) VALUES ('myn', 'മായന്‍ ഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('chm', 'മാരി');
INSERT INTO [country] ([id], [name]) VALUES ('mh', 'മാര്‍ഷല്ലീസ്');
INSERT INTO [country] ([id], [name]) VALUES ('mt', 'മാള്‍ട്ടീസ്');
INSERT INTO [country] ([id], [name]) VALUES ('mk', 'മാസിഡോണിയന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('mic', 'മിക്മാക്');
INSERT INTO [country] ([id], [name]) VALUES ('min', 'മിനാങ്കബൗ');
INSERT INTO [country] ([id], [name]) VALUES ('mwl', 'മിരാന്‍റസേ');
INSERT INTO [country] ([id], [name]) VALUES ('crp', 'മിശ്രഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('mun', 'മുണ്ഡ ഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('root', 'മൂലഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('men', 'മെന്‍ഡെ');
INSERT INTO [country] ([id], [name]) VALUES ('mai', 'മൈഥിലി');
INSERT INTO [country] ([id], [name]) VALUES ('mos', 'മൊസ്സി');
INSERT INTO [country] ([id], [name]) VALUES ('mdf', 'മോക്ഷ');
INSERT INTO [country] ([id], [name]) VALUES ('hmn', 'മോങ്');
INSERT INTO [country] ([id], [name]) VALUES ('lol', 'മോങ്കോ');
INSERT INTO [country] ([id], [name]) VALUES ('mkh', 'മോണ്‍-ഖമര്‍ ഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('mo', 'മോള്‍ഡാവിയന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('moh', 'മോഹാക്');
INSERT INTO [country] ([id], [name]) VALUES ('mi', 'മൗറി');
INSERT INTO [country] ([id], [name]) VALUES ('sah', 'യാകൂട്');
INSERT INTO [country] ([id], [name]) VALUES ('yao', 'യാവോ');
INSERT INTO [country] ([id], [name]) VALUES ('yi', 'യിദ്ദിഷ്');
INSERT INTO [country] ([id], [name]) VALUES ('ypk', 'യുപിക്');
INSERT INTO [country] ([id], [name]) VALUES ('yap', 'യെപ്പീസ്');
INSERT INTO [country] ([id], [name]) VALUES ('yo', 'യൊറൂബാ');
INSERT INTO [country] ([id], [name]) VALUES ('rm', 'രഹയ്ട്ടോ-റോമന്‍സ്');
INSERT INTO [country] ([id], [name]) VALUES ('raj', 'രാജസ്ഥാനി');
INSERT INTO [country] ([id], [name]) VALUES ('rap', 'രാപനൂയി');
INSERT INTO [country] ([id], [name]) VALUES ('rar', 'രാരോടോങ്കന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('ru', 'റഷ്യന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('rn', 'റുണ്ടി');
INSERT INTO [country] ([id], [name]) VALUES ('ro', 'റുമേനിയന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('rom', 'റോമനി');
INSERT INTO [country] ([id], [name]) VALUES ('roa', 'റോമന്‍സ് ഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('lam', 'ലംബ');
INSERT INTO [country] ([id], [name]) VALUES ('lb', 'ലക്സംബര്‍ഗിഷ്');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hans', 'ലളിതചീനഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('luo', 'ലവോ');
INSERT INTO [country] ([id], [name]) VALUES ('lez', 'ലഹ്ഗിയാന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('lah', 'ലഹ്‌ന്‍ഡ');
INSERT INTO [country] ([id], [name]) VALUES ('lad', 'ലാഡിനോ');
INSERT INTO [country] ([id], [name]) VALUES ('lv', 'ലാത്വിയന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('la', 'ലാറ്റിന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('es_419', 'ലാറ്റിന്‍ അമേരിക്കന്‍ സ്പാനിഷ്');
INSERT INTO [country] ([id], [name]) VALUES ('lo', 'ലാവോ');
INSERT INTO [country] ([id], [name]) VALUES ('ln', 'ലിംഗാല');
INSERT INTO [country] ([id], [name]) VALUES ('tli', 'ലിംഗ്വിറ്റ്');
INSERT INTO [country] ([id], [name]) VALUES ('li', 'ലിംബര്‍ഗിഷ്');
INSERT INTO [country] ([id], [name]) VALUES ('lt', 'ലിത്വേനിയന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('lun', 'ലുന്‍ഡ');
INSERT INTO [country] ([id], [name]) VALUES ('lu', 'ലുബ-കറ്റംഗ');
INSERT INTO [country] ([id], [name]) VALUES ('lus', 'ലുഷായി');
INSERT INTO [country] ([id], [name]) VALUES ('lua', 'ലൂബ-ലുലുവ');
INSERT INTO [country] ([id], [name]) VALUES ('lui', 'ലൂയിസെനോ');
INSERT INTO [country] ([id], [name]) VALUES ('smj', 'ലൂലീ സമി');
INSERT INTO [country] ([id], [name]) VALUES ('nds', 'ലോ ജര്‍മന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('jbo', 'ലോജ്ബാന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('dsb', 'ലോവര്‍ സോര്‍ബിയന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('loz', 'ലോസി');
INSERT INTO [country] ([id], [name]) VALUES ('wak', 'വകഷന്‍ ഭാഷകള്‍');
INSERT INTO [country] ([id], [name]) VALUES ('se', 'വടക്കന്‍ സമി');
INSERT INTO [country] ([id], [name]) VALUES ('nai', 'വടക്കേ അമേരിക്കന്‍ ഇന്‍ഡ്യന്‍ ഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('wal', 'വലമൊ');
INSERT INTO [country] ([id], [name]) VALUES ('wa', 'വല്ലൂണ്‍');
INSERT INTO [country] ([id], [name]) VALUES ('war', 'വാരേയ്');
INSERT INTO [country] ([id], [name]) VALUES ('was', 'വാഷൊ');
INSERT INTO [country] ([id], [name]) VALUES ('vi', 'വിയറ്റ്നാമീസ്');
INSERT INTO [country] ([id], [name]) VALUES ('ve', 'വെന്ദ');
INSERT INTO [country] ([id], [name]) VALUES ('cy', 'വെല്‍ഷ്');
INSERT INTO [country] ([id], [name]) VALUES ('vai', 'വൈ');
INSERT INTO [country] ([id], [name]) VALUES ('wo', 'വൊളോഫ്');
INSERT INTO [country] ([id], [name]) VALUES ('vot', 'വോട്ടിക്');
INSERT INTO [country] ([id], [name]) VALUES ('vo', 'വോളാപുക്');
INSERT INTO [country] ([id], [name]) VALUES ('srn', 'ശ്രാനന്‍ ഡോങ്കോ');
INSERT INTO [country] ([id], [name]) VALUES ('shn', 'ഷാന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('ii', 'ഷുവാന്‍യി');
INSERT INTO [country] ([id], [name]) VALUES ('sn', 'ഷോണാ');
INSERT INTO [country] ([id], [name]) VALUES ('sa', 'സംസ്കൃതം');
INSERT INTO [country] ([id], [name]) VALUES ('alt', 'സതേണ്‍ അള്‍ട്ടായി');
INSERT INTO [country] ([id], [name]) VALUES ('sma', 'സതേണ്‍ സമി');
INSERT INTO [country] ([id], [name]) VALUES ('sat', 'സന്താലി');
INSERT INTO [country] ([id], [name]) VALUES ('sam', 'സമരിയാക്കാരുടെ അരമായ');
INSERT INTO [country] ([id], [name]) VALUES ('smi', 'സമി ഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('sm', 'സമോവന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('sc', 'സര്‍ഡിനിയാന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('sas', 'സസാക്');
INSERT INTO [country] ([id], [name]) VALUES ('sg', 'സാങ്കോ');
INSERT INTO [country] ([id], [name]) VALUES ('znd', 'സാന്ദെ');
INSERT INTO [country] ([id], [name]) VALUES ('sad', 'സാന്‍ഡവേ');
INSERT INTO [country] ([id], [name]) VALUES ('zap', 'സാപ്പോടെക്');
INSERT INTO [country] ([id], [name]) VALUES ('sal', 'സാലിഷാന്‍ ഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('zza', 'സാസാ');
INSERT INTO [country] ([id], [name]) VALUES ('tsi', 'സിംഷ്യന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('si', 'സിംഹള');
INSERT INTO [country] ([id], [name]) VALUES ('bla', 'സിക്സിക');
INSERT INTO [country] ([id], [name]) VALUES ('sid', 'സിഡാമോ');
INSERT INTO [country] ([id], [name]) VALUES ('sd', 'സിന്ധി');
INSERT INTO [country] ([id], [name]) VALUES ('nzi', 'സിമ');
INSERT INTO [country] ([id], [name]) VALUES ('sio', 'സിവോന്‍ ഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('scn', 'സിസിലിയന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('suk', 'സുകുമ');
INSERT INTO [country] ([id], [name]) VALUES ('su', 'സുഡാനീസ്');
INSERT INTO [country] ([id], [name]) VALUES ('zun', 'സുനി');
INSERT INTO [country] ([id], [name]) VALUES ('sux', 'സുമേരിയന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('syr', 'സുറിയാനി');
INSERT INTO [country] ([id], [name]) VALUES ('zu', 'സുലു');
INSERT INTO [country] ([id], [name]) VALUES ('sus', 'സുസു');
INSERT INTO [country] ([id], [name]) VALUES ('zen', 'സെനഗ');
INSERT INTO [country] ([id], [name]) VALUES ('ceb', 'സെബുവാനോ');
INSERT INTO [country] ([id], [name]) VALUES ('sem', 'സെമറ്റിക് ഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('sr', 'സെര്‍ബിയന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('sh', 'സെര്‍ബോ-ക്രൊയേഷ്യന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('srr', 'സെറര്‍');
INSERT INTO [country] ([id], [name]) VALUES ('sel', 'സെല്‍കപ്');
INSERT INTO [country] ([id], [name]) VALUES ('cel', 'സെല്‍റ്റിക് ഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('son', 'സോംഗൈ');
INSERT INTO [country] ([id], [name]) VALUES ('sog', 'സോജിഡിയന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('snk', 'സോണിന്‍കെ');
INSERT INTO [country] ([id], [name]) VALUES ('so', 'സോമാലി');
INSERT INTO [country] ([id], [name]) VALUES ('wen', 'സോര്‍ബിയന്‍ ഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('gd', 'സ്കോട്ടിഷ് ഗൈലിക്');
INSERT INTO [country] ([id], [name]) VALUES ('sco', 'സ്കോട്സ്');
INSERT INTO [country] ([id], [name]) VALUES ('sms', 'സ്കോള്‍ട്ട് സമി');
INSERT INTO [country] ([id], [name]) VALUES ('es', 'സ്പാനിഷ്');
INSERT INTO [country] ([id], [name]) VALUES ('sla', 'സ്ലേവിക് ഭാഷ');
INSERT INTO [country] ([id], [name]) VALUES ('den', 'സ്ലേവ്');
INSERT INTO [country] ([id], [name]) VALUES ('sk', 'സ്ലോവാക്ക്');
INSERT INTO [country] ([id], [name]) VALUES ('sl', 'സ്ലോവേനിയന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('za', 'സ്വാംഗ്');
INSERT INTO [country] ([id], [name]) VALUES ('ss', 'സ്വാറ്റി');
INSERT INTO [country] ([id], [name]) VALUES ('sw', 'സ്വാഹിലി');
INSERT INTO [country] ([id], [name]) VALUES ('de_CH', 'സ്വിസ് ഉച്ച ജര്‍മന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('gsw', 'സ്വിസ് ജര്‍മന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('fr_CH', 'സ്വിസ് ഫ്രഞ്ച്');
INSERT INTO [country] ([id], [name]) VALUES ('sv', 'സ്വീഡിഷ്');
INSERT INTO [country] ([id], [name]) VALUES ('hu', 'ഹംഗേറിയന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('haw', 'ഹവായിയന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('hi', 'ഹിന്ദി');
INSERT INTO [country] ([id], [name]) VALUES ('him', 'ഹിമാചലി');
INSERT INTO [country] ([id], [name]) VALUES ('ho', 'ഹിരി മോതു');
INSERT INTO [country] ([id], [name]) VALUES ('hit', 'ഹിറ്റൈറ്റേ');
INSERT INTO [country] ([id], [name]) VALUES ('hil', 'ഹിലിഗയ്നോണ്‍');
INSERT INTO [country] ([id], [name]) VALUES ('he', 'ഹീബ്രു');
INSERT INTO [country] ([id], [name]) VALUES ('hup', 'ഹൂപ');
INSERT INTO [country] ([id], [name]) VALUES ('ht', 'ഹെയ്തിയന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('hz', 'ഹെരേരൊ');
INSERT INTO [country] ([id], [name]) VALUES ('hai', 'ഹൈഡ');
INSERT INTO [country] ([id], [name]) VALUES ('ha', 'ഹൗസ');
