CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('ab', 'Abkazijski');
INSERT INTO "country" ("id", "name") VALUES ('ace', 'Ačineski');
INSERT INTO "country" ("id", "name") VALUES ('ada', 'Adangmejski');
INSERT INTO "country" ("id", "name") VALUES ('ady', 'Adigejski');
INSERT INTO "country" ("id", "name") VALUES ('aa', 'Afarski');
INSERT INTO "country" ("id", "name") VALUES ('afh', 'Afrihili');
INSERT INTO "country" ("id", "name") VALUES ('af', 'Afrikanerski');
INSERT INTO "country" ("id", "name") VALUES ('afa', 'Afro-azijatski');
INSERT INTO "country" ("id", "name") VALUES ('ain', 'Ainu');
INSERT INTO "country" ("id", "name") VALUES ('ay', 'Ajmara');
INSERT INTO "country" ("id", "name") VALUES ('akk', 'Akadijski');
INSERT INTO "country" ("id", "name") VALUES ('ak', 'Akan');
INSERT INTO "country" ("id", "name") VALUES ('ach', 'Akoli');
INSERT INTO "country" ("id", "name") VALUES ('sq', 'Albanski');
INSERT INTO "country" ("id", "name") VALUES ('alg', 'Algonkvijanski jezik');
INSERT INTO "country" ("id", "name") VALUES ('tut', 'Altaički jezik');
INSERT INTO "country" ("id", "name") VALUES ('ale', 'Aljut');
INSERT INTO "country" ("id", "name") VALUES ('am', 'Amharski');
INSERT INTO "country" ("id", "name") VALUES ('anp', 'Angika');
INSERT INTO "country" ("id", "name") VALUES ('apa', 'Apački jezik');
INSERT INTO "country" ("id", "name") VALUES ('an', 'Aragonežanski');
INSERT INTO "country" ("id", "name") VALUES ('arp', 'Arapaho');
INSERT INTO "country" ("id", "name") VALUES ('ar', 'Arapski');
INSERT INTO "country" ("id", "name") VALUES ('arw', 'Aravak');
INSERT INTO "country" ("id", "name") VALUES ('arc', 'Armajski');
INSERT INTO "country" ("id", "name") VALUES ('arn', 'Arokanijski');
INSERT INTO "country" ("id", "name") VALUES ('rup', 'Aromanijski');
INSERT INTO "country" ("id", "name") VALUES ('as', 'Asemijski');
INSERT INTO "country" ("id", "name") VALUES ('ast', 'Asturijski');
INSERT INTO "country" ("id", "name") VALUES ('ath', 'Atapaskan');
INSERT INTO "country" ("id", "name") VALUES ('cch', 'Atsam');
INSERT INTO "country" ("id", "name") VALUES ('en_AU', 'Australijski engleski');
INSERT INTO "country" ("id", "name") VALUES ('aus', 'Australijski jezik');
INSERT INTO "country" ("id", "name") VALUES ('de_AT', 'Austrijski nemački');
INSERT INTO "country" ("id", "name") VALUES ('map', 'Austronežanski');
INSERT INTO "country" ("id", "name") VALUES ('awa', 'Avadhi');
INSERT INTO "country" ("id", "name") VALUES ('av', 'Avarski');
INSERT INTO "country" ("id", "name") VALUES ('ae', 'Avestanski');
INSERT INTO "country" ("id", "name") VALUES ('az', 'Azerbejdžanski');
INSERT INTO "country" ("id", "name") VALUES ('ban', 'Balinezijski');
INSERT INTO "country" ("id", "name") VALUES ('bat', 'Baltički jezik');
INSERT INTO "country" ("id", "name") VALUES ('bal', 'Baluči');
INSERT INTO "country" ("id", "name") VALUES ('bm', 'Bambara');
INSERT INTO "country" ("id", "name") VALUES ('bai', 'Bamileke');
INSERT INTO "country" ("id", "name") VALUES ('bad', 'Banda');
INSERT INTO "country" ("id", "name") VALUES ('bnt', 'Bantu');
INSERT INTO "country" ("id", "name") VALUES ('bas', 'Basa');
INSERT INTO "country" ("id", "name") VALUES ('eu', 'Baskijski');
INSERT INTO "country" ("id", "name") VALUES ('ba', 'Baškir');
INSERT INTO "country" ("id", "name") VALUES ('btk', 'Batak');
INSERT INTO "country" ("id", "name") VALUES ('bej', 'Beja');
INSERT INTO "country" ("id", "name") VALUES ('be', 'Beloruski');
INSERT INTO "country" ("id", "name") VALUES ('bem', 'Bemba');
INSERT INTO "country" ("id", "name") VALUES ('bn', 'Bengalski');
INSERT INTO "country" ("id", "name") VALUES ('ber', 'Berber');
INSERT INTO "country" ("id", "name") VALUES ('zxx', 'Bez lingvističkog sadržaja');
INSERT INTO "country" ("id", "name") VALUES ('bh', 'Biharski');
INSERT INTO "country" ("id", "name") VALUES ('bik', 'Bikol');
INSERT INTO "country" ("id", "name") VALUES ('bin', 'Bini');
INSERT INTO "country" ("id", "name") VALUES ('bi', 'Bislama');
INSERT INTO "country" ("id", "name") VALUES ('byn', 'Blin');
INSERT INTO "country" ("id", "name") VALUES ('zbl', 'Blisimboli');
INSERT INTO "country" ("id", "name") VALUES ('bho', 'Bojpuri');
INSERT INTO "country" ("id", "name") VALUES ('bs', 'Bosanski');
INSERT INTO "country" ("id", "name") VALUES ('bra', 'Braj');
INSERT INTO "country" ("id", "name") VALUES ('pt_BR', 'Brazilski portugalski');
INSERT INTO "country" ("id", "name") VALUES ('br', 'Bretonski');
INSERT INTO "country" ("id", "name") VALUES ('en_GB', 'Britanski engleski');
INSERT INTO "country" ("id", "name") VALUES ('bg', 'Bugarski');
INSERT INTO "country" ("id", "name") VALUES ('bug', 'Buginežanskii');
INSERT INTO "country" ("id", "name") VALUES ('bua', 'Buriat');
INSERT INTO "country" ("id", "name") VALUES ('my', 'Burmanski');
INSERT INTO "country" ("id", "name") VALUES ('ceb', 'Cebuano');
INSERT INTO "country" ("id", "name") VALUES ('chg', 'Čagatai');
INSERT INTO "country" ("id", "name") VALUES ('ch', 'Čamoro');
INSERT INTO "country" ("id", "name") VALUES ('cmc', 'Čamski jezik');
INSERT INTO "country" ("id", "name") VALUES ('ce', 'Čečenski');
INSERT INTO "country" ("id", "name") VALUES ('chy', 'Čejenski');
INSERT INTO "country" ("id", "name") VALUES ('chr', 'Čeroki');
INSERT INTO "country" ("id", "name") VALUES ('cs', 'Češki');
INSERT INTO "country" ("id", "name") VALUES ('chb', 'Čibča');
INSERT INTO "country" ("id", "name") VALUES ('chn', 'Činukski');
INSERT INTO "country" ("id", "name") VALUES ('chp', 'Čipvijanski');
INSERT INTO "country" ("id", "name") VALUES ('cho', 'Čoktavski');
INSERT INTO "country" ("id", "name") VALUES ('chk', 'Čukeski');
INSERT INTO "country" ("id", "name") VALUES ('cv', 'Čuvaški');
INSERT INTO "country" ("id", "name") VALUES ('day', 'Dajaški');
INSERT INTO "country" ("id", "name") VALUES ('dak', 'Dakota');
INSERT INTO "country" ("id", "name") VALUES ('da', 'Danski');
INSERT INTO "country" ("id", "name") VALUES ('dar', 'Dargva');
INSERT INTO "country" ("id", "name") VALUES ('del', 'Delaver');
INSERT INTO "country" ("id", "name") VALUES ('din', 'Dinka');
INSERT INTO "country" ("id", "name") VALUES ('dv', 'Divehijski');
INSERT INTO "country" ("id", "name") VALUES ('doi', 'Dogri');
INSERT INTO "country" ("id", "name") VALUES ('dgr', 'Dogrib');
INSERT INTO "country" ("id", "name") VALUES ('dra', 'Dravidijski jezik');
INSERT INTO "country" ("id", "name") VALUES ('dua', 'Duala');
INSERT INTO "country" ("id", "name") VALUES ('gez', 'Džiz');
INSERT INTO "country" ("id", "name") VALUES ('dz', 'Džonga');
INSERT INTO "country" ("id", "name") VALUES ('dyu', 'Đula');
INSERT INTO "country" ("id", "name") VALUES ('efi', 'Efikski');
INSERT INTO "country" ("id", "name") VALUES ('eka', 'Ekajuk');
INSERT INTO "country" ("id", "name") VALUES ('elx', 'Elamitski');
INSERT INTO "country" ("id", "name") VALUES ('en', 'Engleski');
INSERT INTO "country" ("id", "name") VALUES ('en_US', 'Engleski (SAD)');
INSERT INTO "country" ("id", "name") VALUES ('myv', 'Erzija');
INSERT INTO "country" ("id", "name") VALUES ('eo', 'Esperanto');
INSERT INTO "country" ("id", "name") VALUES ('et', 'Estonski');
INSERT INTO "country" ("id", "name") VALUES ('ee', 'Eve');
INSERT INTO "country" ("id", "name") VALUES ('ewo', 'Evondo');
INSERT INTO "country" ("id", "name") VALUES ('fan', 'Fang');
INSERT INTO "country" ("id", "name") VALUES ('fat', 'Fanti');
INSERT INTO "country" ("id", "name") VALUES ('fo', 'Farski');
INSERT INTO "country" ("id", "name") VALUES ('phn', 'Feničanski');
INSERT INTO "country" ("id", "name") VALUES ('fj', 'Fidžijski');
INSERT INTO "country" ("id", "name") VALUES ('fil', 'Filipinski');
INSERT INTO "country" ("id", "name") VALUES ('phi', 'Filipinski jezik');
INSERT INTO "country" ("id", "name") VALUES ('fi', 'Finski');
INSERT INTO "country" ("id", "name") VALUES ('nl_BE', 'Flamanski');
INSERT INTO "country" ("id", "name") VALUES ('fon', 'Fon');
INSERT INTO "country" ("id", "name") VALUES ('fr', 'Francuski');
INSERT INTO "country" ("id", "name") VALUES ('fur', 'Friulijski');
INSERT INTO "country" ("id", "name") VALUES ('fy', 'Frizijski');
INSERT INTO "country" ("id", "name") VALUES ('ff', 'Fulah');
INSERT INTO "country" ("id", "name") VALUES ('gaa', 'Ga');
INSERT INTO "country" ("id", "name") VALUES ('gay', 'Gajo');
INSERT INTO "country" ("id", "name") VALUES ('gl', 'Galski');
INSERT INTO "country" ("id", "name") VALUES ('lg', 'Ganda');
INSERT INTO "country" ("id", "name") VALUES ('gba', 'Gbaja');
INSERT INTO "country" ("id", "name") VALUES ('gem', 'Germanski jezik');
INSERT INTO "country" ("id", "name") VALUES ('gil', 'Gilbertški');
INSERT INTO "country" ("id", "name") VALUES ('gon', 'Gondi');
INSERT INTO "country" ("id", "name") VALUES ('hsb', 'Gornji sorbijski');
INSERT INTO "country" ("id", "name") VALUES ('gor', 'Gorontalo');
INSERT INTO "country" ("id", "name") VALUES ('got', 'Gotski');
INSERT INTO "country" ("id", "name") VALUES ('el', 'Grčki');
INSERT INTO "country" ("id", "name") VALUES ('grb', 'Grebo');
INSERT INTO "country" ("id", "name") VALUES ('ka', 'Gruzijski');
INSERT INTO "country" ("id", "name") VALUES ('gu', 'Gudžarati');
INSERT INTO "country" ("id", "name") VALUES ('gn', 'Gvarani');
INSERT INTO "country" ("id", "name") VALUES ('gwi', 'Gvich\'in');
INSERT INTO "country" ("id", "name") VALUES ('ht', 'Haićanski');
INSERT INTO "country" ("id", "name") VALUES ('hai', 'Haida');
INSERT INTO "country" ("id", "name") VALUES ('ha', 'Hausa');
INSERT INTO "country" ("id", "name") VALUES ('haw', 'Havajski');
INSERT INTO "country" ("id", "name") VALUES ('he', 'Hebrejski');
INSERT INTO "country" ("id", "name") VALUES ('hz', 'Herero');
INSERT INTO "country" ("id", "name") VALUES ('hil', 'Hiligajnon');
INSERT INTO "country" ("id", "name") VALUES ('him', 'Himačali');
INSERT INTO "country" ("id", "name") VALUES ('hi', 'Hindi');
INSERT INTO "country" ("id", "name") VALUES ('ho', 'Hiri Motu');
INSERT INTO "country" ("id", "name") VALUES ('hit', 'Hitite');
INSERT INTO "country" ("id", "name") VALUES ('hmn', 'Hmong');
INSERT INTO "country" ("id", "name") VALUES ('nl', 'Holandski');
INSERT INTO "country" ("id", "name") VALUES ('hr', 'Hrvatski');
INSERT INTO "country" ("id", "name") VALUES ('hup', 'Hupa');
INSERT INTO "country" ("id", "name") VALUES ('iba', 'Iban');
INSERT INTO "country" ("id", "name") VALUES ('pt_PT', 'Iberijski portugalski');
INSERT INTO "country" ("id", "name") VALUES ('es_ES', 'Iberijski španski');
INSERT INTO "country" ("id", "name") VALUES ('io', 'Ido');
INSERT INTO "country" ("id", "name") VALUES ('ig', 'Igbo');
INSERT INTO "country" ("id", "name") VALUES ('ijo', 'Ijo');
INSERT INTO "country" ("id", "name") VALUES ('ilo', 'Iloko');
INSERT INTO "country" ("id", "name") VALUES ('smn', 'Inari sami');
INSERT INTO "country" ("id", "name") VALUES ('inc', 'Indik');
INSERT INTO "country" ("id", "name") VALUES ('ine', 'Indo-evropski jezik');
INSERT INTO "country" ("id", "name") VALUES ('id', 'Indonezijski');
INSERT INTO "country" ("id", "name") VALUES ('inh', 'Ingušetski');
INSERT INTO "country" ("id", "name") VALUES ('ia', 'Interlingva');
INSERT INTO "country" ("id", "name") VALUES ('ie', 'Interlingve');
INSERT INTO "country" ("id", "name") VALUES ('iu', 'Inuktitut');
INSERT INTO "country" ("id", "name") VALUES ('ik', 'Inupiak');
INSERT INTO "country" ("id", "name") VALUES ('ira', 'Iranski jezik');
INSERT INTO "country" ("id", "name") VALUES ('iro', 'Irokvojanski');
INSERT INTO "country" ("id", "name") VALUES ('ga', 'Irski');
INSERT INTO "country" ("id", "name") VALUES ('is', 'Islandski');
INSERT INTO "country" ("id", "name") VALUES ('frs', 'Istočni frizijski');
INSERT INTO "country" ("id", "name") VALUES ('it', 'Italijanski');
INSERT INTO "country" ("id", "name") VALUES ('sah', 'Jakut');
INSERT INTO "country" ("id", "name") VALUES ('yao', 'Jao');
INSERT INTO "country" ("id", "name") VALUES ('ja', 'Japanski');
INSERT INTO "country" ("id", "name") VALUES ('yap', 'Japeški');
INSERT INTO "country" ("id", "name") VALUES ('jv', 'Javanski');
INSERT INTO "country" ("id", "name") VALUES ('hy', 'Jermenski');
INSERT INTO "country" ("id", "name") VALUES ('cai', 'Jezik centralno-američkih Indijanaca');
INSERT INTO "country" ("id", "name") VALUES ('sai', 'Jezik južno-američkih Indijanaca');
INSERT INTO "country" ("id", "name") VALUES ('nai', 'Jezik severno-američkih Indijanaca');
INSERT INTO "country" ("id", "name") VALUES ('sgn', 'Jezik znakova');
INSERT INTO "country" ("id", "name") VALUES ('yi', 'Jidiš');
INSERT INTO "country" ("id", "name") VALUES ('yo', 'Jorubanski');
INSERT INTO "country" ("id", "name") VALUES ('jrb', 'Judeo-arapski');
INSERT INTO "country" ("id", "name") VALUES ('jpr', 'Judeo-persijski');
INSERT INTO "country" ("id", "name") VALUES ('ypk', 'Jupik');
INSERT INTO "country" ("id", "name") VALUES ('alt', 'Južni altai');
INSERT INTO "country" ("id", "name") VALUES ('nr', 'Južni ndebele');
INSERT INTO "country" ("id", "name") VALUES ('sma', 'Južni sami');
INSERT INTO "country" ("id", "name") VALUES ('kbd', 'Kabardijski');
INSERT INTO "country" ("id", "name") VALUES ('kab', 'Kabile');
INSERT INTO "country" ("id", "name") VALUES ('kac', 'Kačin');
INSERT INTO "country" ("id", "name") VALUES ('cad', 'Kado');
INSERT INTO "country" ("id", "name") VALUES ('kl', 'Kalalisutski');
INSERT INTO "country" ("id", "name") VALUES ('xal', 'Kalmik');
INSERT INTO "country" ("id", "name") VALUES ('kam', 'Kamba');
INSERT INTO "country" ("id", "name") VALUES ('kn', 'Kanada');
INSERT INTO "country" ("id", "name") VALUES ('en_CA', 'Kanadski engleski');
INSERT INTO "country" ("id", "name") VALUES ('fr_CA', 'Kanadski francuski');
INSERT INTO "country" ("id", "name") VALUES ('kr', 'Kanuri');
INSERT INTO "country" ("id", "name") VALUES ('kaa', 'Kara-kalpaški');
INSERT INTO "country" ("id", "name") VALUES ('krc', 'Karačaj-balkar');
INSERT INTO "country" ("id", "name") VALUES ('krl', 'Karelijski');
INSERT INTO "country" ("id", "name") VALUES ('kar', 'Karenski');
INSERT INTO "country" ("id", "name") VALUES ('car', 'Karipski');
INSERT INTO "country" ("id", "name") VALUES ('kha', 'Kasi');
INSERT INTO "country" ("id", "name") VALUES ('ks', 'Kašmiri');
INSERT INTO "country" ("id", "name") VALUES ('csb', 'Kašubijanski');
INSERT INTO "country" ("id", "name") VALUES ('ca', 'Katalonski');
INSERT INTO "country" ("id", "name") VALUES ('kaw', 'Kavi');
INSERT INTO "country" ("id", "name") VALUES ('cau', 'Kavkaski');
INSERT INTO "country" ("id", "name") VALUES ('cel', 'Keltski jezik');
INSERT INTO "country" ("id", "name") VALUES ('xh', 'Khosa');
INSERT INTO "country" ("id", "name") VALUES ('ki', 'Kikuju');
INSERT INTO "country" ("id", "name") VALUES ('kmb', 'Kimbundu');
INSERT INTO "country" ("id", "name") VALUES ('zh', 'Kineski');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hans', 'Kineski (pojednostavljen)');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hant', 'Kineski (tradicionalni)');
INSERT INTO "country" ("id", "name") VALUES ('rw', 'Kinjarvanda');
INSERT INTO "country" ("id", "name") VALUES ('ky', 'Kirgiski');
INSERT INTO "country" ("id", "name") VALUES ('nwc', 'Klasični nevari');
INSERT INTO "country" ("id", "name") VALUES ('syc', 'Klasični sirijski');
INSERT INTO "country" ("id", "name") VALUES ('tlh', 'Klingonski');
INSERT INTO "country" ("id", "name") VALUES ('km', 'Kmerski');
INSERT INTO "country" ("id", "name") VALUES ('khi', 'Koisanski jezik');
INSERT INTO "country" ("id", "name") VALUES ('kv', 'Komi');
INSERT INTO "country" ("id", "name") VALUES ('kg', 'Kongo');
INSERT INTO "country" ("id", "name") VALUES ('kok', 'Konkani');
INSERT INTO "country" ("id", "name") VALUES ('cop', 'Koptski');
INSERT INTO "country" ("id", "name") VALUES ('ko', 'Korejski');
INSERT INTO "country" ("id", "name") VALUES ('kw', 'Korniški');
INSERT INTO "country" ("id", "name") VALUES ('kfo', 'Koro');
INSERT INTO "country" ("id", "name") VALUES ('co', 'Korzikanski');
INSERT INTO "country" ("id", "name") VALUES ('kos', 'Kosreanski');
INSERT INTO "country" ("id", "name") VALUES ('kho', 'Kotanizijski');
INSERT INTO "country" ("id", "name") VALUES ('kk', 'Kozački');
INSERT INTO "country" ("id", "name") VALUES ('kpe', 'Kpele');
INSERT INTO "country" ("id", "name") VALUES ('crp', 'kreolski ili pidžin');
INSERT INTO "country" ("id", "name") VALUES ('cpp', 'Kreolski ili pidžin baziran na portugalskom');
INSERT INTO "country" ("id", "name") VALUES ('cpe', 'Kreolski ili pidžin zasnovan na engleskom');
INSERT INTO "country" ("id", "name") VALUES ('cpf', 'Kreolski ili pidžin zasnovan na francuskom');
INSERT INTO "country" ("id", "name") VALUES ('cr', 'Kri');
INSERT INTO "country" ("id", "name") VALUES ('crh', 'Krimeanski turski');
INSERT INTO "country" ("id", "name") VALUES ('mus', 'Kriški');
INSERT INTO "country" ("id", "name") VALUES ('kro', 'Kru');
INSERT INTO "country" ("id", "name") VALUES ('kj', 'Kuanjama');
INSERT INTO "country" ("id", "name") VALUES ('kum', 'Kumik');
INSERT INTO "country" ("id", "name") VALUES ('ku', 'Kurdski');
INSERT INTO "country" ("id", "name") VALUES ('kru', 'Kurukh');
INSERT INTO "country" ("id", "name") VALUES ('cus', 'Kušitički jezik');
INSERT INTO "country" ("id", "name") VALUES ('kut', 'Kutenai');
INSERT INTO "country" ("id", "name") VALUES ('qu', 'Kvenča');
INSERT INTO "country" ("id", "name") VALUES ('lad', 'Ladino');
INSERT INTO "country" ("id", "name") VALUES ('lam', 'Lamba');
INSERT INTO "country" ("id", "name") VALUES ('lah', 'Landa');
INSERT INTO "country" ("id", "name") VALUES ('lo', 'Laoški');
INSERT INTO "country" ("id", "name") VALUES ('es_419', 'Latino-američki španski');
INSERT INTO "country" ("id", "name") VALUES ('la', 'Latinski');
INSERT INTO "country" ("id", "name") VALUES ('lv', 'Letonski');
INSERT INTO "country" ("id", "name") VALUES ('lez', 'Lezgian');
INSERT INTO "country" ("id", "name") VALUES ('li', 'Limburgiš');
INSERT INTO "country" ("id", "name") VALUES ('ln', 'Lingala');
INSERT INTO "country" ("id", "name") VALUES ('lt', 'Litvanski');
INSERT INTO "country" ("id", "name") VALUES ('jbo', 'Lojban');
INSERT INTO "country" ("id", "name") VALUES ('loz', 'Lozi');
INSERT INTO "country" ("id", "name") VALUES ('lu', 'Luba-katanga');
INSERT INTO "country" ("id", "name") VALUES ('lua', 'Luba-lulua');
INSERT INTO "country" ("id", "name") VALUES ('lui', 'Luiseno');
INSERT INTO "country" ("id", "name") VALUES ('lb', 'Luksemburški');
INSERT INTO "country" ("id", "name") VALUES ('smj', 'Lule sami');
INSERT INTO "country" ("id", "name") VALUES ('lun', 'Lunda');
INSERT INTO "country" ("id", "name") VALUES ('luo', 'Luo');
INSERT INTO "country" ("id", "name") VALUES ('lus', 'Lušai');
INSERT INTO "country" ("id", "name") VALUES ('mad', 'Madureški');
INSERT INTO "country" ("id", "name") VALUES ('hu', 'Mađarski');
INSERT INTO "country" ("id", "name") VALUES ('mag', 'Magahi');
INSERT INTO "country" ("id", "name") VALUES ('moh', 'Mahavski');
INSERT INTO "country" ("id", "name") VALUES ('mai', 'Maitili');
INSERT INTO "country" ("id", "name") VALUES ('myn', 'Majanski jezik');
INSERT INTO "country" ("id", "name") VALUES ('mak', 'Makasar');
INSERT INTO "country" ("id", "name") VALUES ('mk', 'Makedonski');
INSERT INTO "country" ("id", "name") VALUES ('mg', 'Malagazijski');
INSERT INTO "country" ("id", "name") VALUES ('ml', 'Malajalam');
INSERT INTO "country" ("id", "name") VALUES ('ms', 'Malajski');
INSERT INTO "country" ("id", "name") VALUES ('mnc', 'Manču');
INSERT INTO "country" ("id", "name") VALUES ('mdr', 'Mandar');
INSERT INTO "country" ("id", "name") VALUES ('man', 'Mandingo');
INSERT INTO "country" ("id", "name") VALUES ('mni', 'Manipuri');
INSERT INTO "country" ("id", "name") VALUES ('gv', 'Manks');
INSERT INTO "country" ("id", "name") VALUES ('mno', 'Manobo jezik');
INSERT INTO "country" ("id", "name") VALUES ('mi', 'Maorski');
INSERT INTO "country" ("id", "name") VALUES ('mr', 'Marati');
INSERT INTO "country" ("id", "name") VALUES ('chm', 'Mari');
INSERT INTO "country" ("id", "name") VALUES ('mh', 'Maršalski');
INSERT INTO "country" ("id", "name") VALUES ('mwr', 'Marvari');
INSERT INTO "country" ("id", "name") VALUES ('mas', 'Masai');
INSERT INTO "country" ("id", "name") VALUES ('mt', 'Melteški');
INSERT INTO "country" ("id", "name") VALUES ('men', 'Mende');
INSERT INTO "country" ("id", "name") VALUES ('mic', 'Mikmak');
INSERT INTO "country" ("id", "name") VALUES ('min', 'Minangkabau');
INSERT INTO "country" ("id", "name") VALUES ('mwl', 'Mirandeški');
INSERT INTO "country" ("id", "name") VALUES ('mdf', 'Mokša');
INSERT INTO "country" ("id", "name") VALUES ('mo', 'Moldavski');
INSERT INTO "country" ("id", "name") VALUES ('mkh', 'Mon-kmerski jezik');
INSERT INTO "country" ("id", "name") VALUES ('lol', 'Mongo');
INSERT INTO "country" ("id", "name") VALUES ('mn', 'Mongolski');
INSERT INTO "country" ("id", "name") VALUES ('mos', 'Mosi');
INSERT INTO "country" ("id", "name") VALUES ('mun', 'Munda jezik');
INSERT INTO "country" ("id", "name") VALUES ('nqo', 'N’ko');
INSERT INTO "country" ("id", "name") VALUES ('nah', 'Nahuatl');
INSERT INTO "country" ("id", "name") VALUES ('na', 'Nauru');
INSERT INTO "country" ("id", "name") VALUES ('nv', 'Navaho');
INSERT INTO "country" ("id", "name") VALUES ('ng', 'Ndonga');
INSERT INTO "country" ("id", "name") VALUES ('nap', 'Neapolitanski');
INSERT INTO "country" ("id", "name") VALUES ('de', 'Nemački');
INSERT INTO "country" ("id", "name") VALUES ('ne', 'Nepalski');
INSERT INTO "country" ("id", "name") VALUES ('und', 'Nepoznat ili nevažeći jezik');
INSERT INTO "country" ("id", "name") VALUES ('new', 'Nevari');
INSERT INTO "country" ("id", "name") VALUES ('nia', 'Nias');
INSERT INTO "country" ("id", "name") VALUES ('nic', 'Niger-kordofanijski jezik');
INSERT INTO "country" ("id", "name") VALUES ('ssa', 'Nilo-saharski jezik');
INSERT INTO "country" ("id", "name") VALUES ('nds', 'Niski nemački');
INSERT INTO "country" ("id", "name") VALUES ('dsb', 'Niski Sorbijanski');
INSERT INTO "country" ("id", "name") VALUES ('niu', 'Niuean');
INSERT INTO "country" ("id", "name") VALUES ('nog', 'Nogai');
INSERT INTO "country" ("id", "name") VALUES ('no', 'Norveški');
INSERT INTO "country" ("id", "name") VALUES ('nb', 'Norveški bokmål');
INSERT INTO "country" ("id", "name") VALUES ('nn', 'Norveški njorsk');
INSERT INTO "country" ("id", "name") VALUES ('nub', 'Nubijski jezik');
INSERT INTO "country" ("id", "name") VALUES ('nzi', 'Nzima');
INSERT INTO "country" ("id", "name") VALUES ('nym', 'Njamvezi');
INSERT INTO "country" ("id", "name") VALUES ('nyn', 'Njankole');
INSERT INTO "country" ("id", "name") VALUES ('ny', 'Njanja');
INSERT INTO "country" ("id", "name") VALUES ('tog', 'Njasa tonga');
INSERT INTO "country" ("id", "name") VALUES ('nyo', 'Njoro');
INSERT INTO "country" ("id", "name") VALUES ('oj', 'Ojibva');
INSERT INTO "country" ("id", "name") VALUES ('or', 'Orijski');
INSERT INTO "country" ("id", "name") VALUES ('om', 'Oromo');
INSERT INTO "country" ("id", "name") VALUES ('osa', 'Osage');
INSERT INTO "country" ("id", "name") VALUES ('os', 'Osetski');
INSERT INTO "country" ("id", "name") VALUES ('oto', 'Otomanski jezik');
INSERT INTO "country" ("id", "name") VALUES ('ota', 'Otomanski turski');
INSERT INTO "country" ("id", "name") VALUES ('pal', 'Pahlavi');
INSERT INTO "country" ("id", "name") VALUES ('pau', 'Palauanski');
INSERT INTO "country" ("id", "name") VALUES ('pi', 'Pali');
INSERT INTO "country" ("id", "name") VALUES ('pam', 'Pampanga');
INSERT INTO "country" ("id", "name") VALUES ('pa', 'Pandžabski');
INSERT INTO "country" ("id", "name") VALUES ('pag', 'Pangasinski');
INSERT INTO "country" ("id", "name") VALUES ('pap', 'Papiamento');
INSERT INTO "country" ("id", "name") VALUES ('paa', 'Papuanski jezik');
INSERT INTO "country" ("id", "name") VALUES ('ps', 'Paštunski');
INSERT INTO "country" ("id", "name") VALUES ('fa', 'Persijski');
INSERT INTO "country" ("id", "name") VALUES ('pl', 'Poljski');
INSERT INTO "country" ("id", "name") VALUES ('pon', 'Ponpejski');
INSERT INTO "country" ("id", "name") VALUES ('pt', 'Portugalski');
INSERT INTO "country" ("id", "name") VALUES ('pra', 'Prakritski jezik');
INSERT INTO "country" ("id", "name") VALUES ('oc', 'Provansalski');
INSERT INTO "country" ("id", "name") VALUES ('raj', 'Rađastani');
INSERT INTO "country" ("id", "name") VALUES ('rap', 'Rapanui');
INSERT INTO "country" ("id", "name") VALUES ('rar', 'Rarotongan');
INSERT INTO "country" ("id", "name") VALUES ('mis', 'Razni jezici');
INSERT INTO "country" ("id", "name") VALUES ('rm', 'Reto-Romanski');
INSERT INTO "country" ("id", "name") VALUES ('rom', 'Romani');
INSERT INTO "country" ("id", "name") VALUES ('roa', 'Romanski jezik');
INSERT INTO "country" ("id", "name") VALUES ('ro', 'Rumunski');
INSERT INTO "country" ("id", "name") VALUES ('root', 'Run');
INSERT INTO "country" ("id", "name") VALUES ('rn', 'Rundi');
INSERT INTO "country" ("id", "name") VALUES ('ru', 'Ruski');
INSERT INTO "country" ("id", "name") VALUES ('sal', 'Sališanski jezik');
INSERT INTO "country" ("id", "name") VALUES ('sam', 'Samaritanski aramejski');
INSERT INTO "country" ("id", "name") VALUES ('smi', 'Sami jezik');
INSERT INTO "country" ("id", "name") VALUES ('sm', 'Samoanski');
INSERT INTO "country" ("id", "name") VALUES ('sad', 'Sandave');
INSERT INTO "country" ("id", "name") VALUES ('sg', 'Sango');
INSERT INTO "country" ("id", "name") VALUES ('sa', 'Sanskrit');
INSERT INTO "country" ("id", "name") VALUES ('sat', 'Santali');
INSERT INTO "country" ("id", "name") VALUES ('sc', 'Sardinijski');
INSERT INTO "country" ("id", "name") VALUES ('sas', 'Sasak');
INSERT INTO "country" ("id", "name") VALUES ('sel', 'Selkap');
INSERT INTO "country" ("id", "name") VALUES ('sem', 'Semitski jezik');
INSERT INTO "country" ("id", "name") VALUES ('srr', 'Serer');
INSERT INTO "country" ("id", "name") VALUES ('st', 'Sesoto');
INSERT INTO "country" ("id", "name") VALUES ('nd', 'Severni ndebele');
INSERT INTO "country" ("id", "name") VALUES ('se', 'Severni sami');
INSERT INTO "country" ("id", "name") VALUES ('nso', 'Severni soto');
INSERT INTO "country" ("id", "name") VALUES ('frr', 'Severno-frizijski');
INSERT INTO "country" ("id", "name") VALUES ('scn', 'Sicilijanski');
INSERT INTO "country" ("id", "name") VALUES ('ii', 'Sičuan ji');
INSERT INTO "country" ("id", "name") VALUES ('sid', 'Sidamo');
INSERT INTO "country" ("id", "name") VALUES ('bla', 'Siksika');
INSERT INTO "country" ("id", "name") VALUES ('sd', 'Sindi');
INSERT INTO "country" ("id", "name") VALUES ('si', 'Singaleski');
INSERT INTO "country" ("id", "name") VALUES ('sit', 'Sino-tibetanski jezik');
INSERT INTO "country" ("id", "name") VALUES ('syr', 'Sirijski');
INSERT INTO "country" ("id", "name") VALUES ('sio', 'Siuanski jezik');
INSERT INTO "country" ("id", "name") VALUES ('sms', 'Skoltski jezik');
INSERT INTO "country" ("id", "name") VALUES ('den', 'Slavski');
INSERT INTO "country" ("id", "name") VALUES ('sk', 'Slovački');
INSERT INTO "country" ("id", "name") VALUES ('sl', 'Slovenački');
INSERT INTO "country" ("id", "name") VALUES ('sla', 'Slovenski jezik');
INSERT INTO "country" ("id", "name") VALUES ('sog', 'Sodžijenski');
INSERT INTO "country" ("id", "name") VALUES ('so', 'Somalski');
INSERT INTO "country" ("id", "name") VALUES ('son', 'Songai');
INSERT INTO "country" ("id", "name") VALUES ('snk', 'Soninke');
INSERT INTO "country" ("id", "name") VALUES ('wen', 'Sorbijanski jezik');
INSERT INTO "country" ("id", "name") VALUES ('srn', 'Srananski tongo');
INSERT INTO "country" ("id", "name") VALUES ('enm', 'Srednji engleski');
INSERT INTO "country" ("id", "name") VALUES ('frm', 'Srednji francuski');
INSERT INTO "country" ("id", "name") VALUES ('dum', 'Srednji holandski');
INSERT INTO "country" ("id", "name") VALUES ('mga', 'Srednji irski');
INSERT INTO "country" ("id", "name") VALUES ('gmh', 'Srednji visoki nemački');
INSERT INTO "country" ("id", "name") VALUES ('sr', 'Srpski');
INSERT INTO "country" ("id", "name") VALUES ('sh', 'Srpskohrvatski');
INSERT INTO "country" ("id", "name") VALUES ('non', 'Stari norski');
INSERT INTO "country" ("id", "name") VALUES ('egy', 'Staroegipatski');
INSERT INTO "country" ("id", "name") VALUES ('ang', 'Staroengleski');
INSERT INTO "country" ("id", "name") VALUES ('fro', 'Starofrancuski');
INSERT INTO "country" ("id", "name") VALUES ('grc', 'Starogrčki');
INSERT INTO "country" ("id", "name") VALUES ('sga', 'Staroirski');
INSERT INTO "country" ("id", "name") VALUES ('goh', 'Staronemački');
INSERT INTO "country" ("id", "name") VALUES ('peo', 'Staropersijski');
INSERT INTO "country" ("id", "name") VALUES ('pro', 'Staroprovansalski');
INSERT INTO "country" ("id", "name") VALUES ('cu', 'Staroslovenski');
INSERT INTO "country" ("id", "name") VALUES ('su', 'Sudanski');
INSERT INTO "country" ("id", "name") VALUES ('suk', 'Sukuma');
INSERT INTO "country" ("id", "name") VALUES ('sux', 'Sumerski');
INSERT INTO "country" ("id", "name") VALUES ('sus', 'Susu');
INSERT INTO "country" ("id", "name") VALUES ('sw', 'Svahili');
INSERT INTO "country" ("id", "name") VALUES ('ss', 'Svati');
INSERT INTO "country" ("id", "name") VALUES ('shn', 'Šan');
INSERT INTO "country" ("id", "name") VALUES ('sco', 'Škotski');
INSERT INTO "country" ("id", "name") VALUES ('gd', 'Škotski Galski');
INSERT INTO "country" ("id", "name") VALUES ('sn', 'Šona');
INSERT INTO "country" ("id", "name") VALUES ('es', 'Španski');
INSERT INTO "country" ("id", "name") VALUES ('fr_CH', 'Švajcarski francuski');
INSERT INTO "country" ("id", "name") VALUES ('de_CH', 'Švajcarski visoki nemački');
INSERT INTO "country" ("id", "name") VALUES ('gsw', 'Švajcarsko nemački');
INSERT INTO "country" ("id", "name") VALUES ('sv', 'Švedski');
INSERT INTO "country" ("id", "name") VALUES ('tg', 'Tađik');
INSERT INTO "country" ("id", "name") VALUES ('tl', 'Tagalski');
INSERT INTO "country" ("id", "name") VALUES ('ty', 'Tahićanski');
INSERT INTO "country" ("id", "name") VALUES ('tai', 'Tai jezik');
INSERT INTO "country" ("id", "name") VALUES ('th', 'Tajlandski');
INSERT INTO "country" ("id", "name") VALUES ('tmh', 'Tamašek');
INSERT INTO "country" ("id", "name") VALUES ('ta', 'Tamilski');
INSERT INTO "country" ("id", "name") VALUES ('tt', 'Tatarski');
INSERT INTO "country" ("id", "name") VALUES ('te', 'Telugu');
INSERT INTO "country" ("id", "name") VALUES ('ter', 'Tereno');
INSERT INTO "country" ("id", "name") VALUES ('tet', 'Tetum');
INSERT INTO "country" ("id", "name") VALUES ('bo', 'Tibetanski');
INSERT INTO "country" ("id", "name") VALUES ('tig', 'Tigre');
INSERT INTO "country" ("id", "name") VALUES ('ti', 'Tigrinja');
INSERT INTO "country" ("id", "name") VALUES ('tem', 'Timne');
INSERT INTO "country" ("id", "name") VALUES ('tiv', 'Tiv');
INSERT INTO "country" ("id", "name") VALUES ('kcg', 'Tjap');
INSERT INTO "country" ("id", "name") VALUES ('tli', 'Tlingit');
INSERT INTO "country" ("id", "name") VALUES ('tpi', 'Tok pisin');
INSERT INTO "country" ("id", "name") VALUES ('tkl', 'Tokelau');
INSERT INTO "country" ("id", "name") VALUES ('to', 'Tonga');
INSERT INTO "country" ("id", "name") VALUES ('tsi', 'Tsimšian');
INSERT INTO "country" ("id", "name") VALUES ('ts', 'Tsonga');
INSERT INTO "country" ("id", "name") VALUES ('tn', 'Tsvana');
INSERT INTO "country" ("id", "name") VALUES ('tum', 'Tumbuka');
INSERT INTO "country" ("id", "name") VALUES ('tup', 'Tupi jezik');
INSERT INTO "country" ("id", "name") VALUES ('tk', 'Turkmenski');
INSERT INTO "country" ("id", "name") VALUES ('tr', 'Turski');
INSERT INTO "country" ("id", "name") VALUES ('tvl', 'Tuvalu');
INSERT INTO "country" ("id", "name") VALUES ('tyv', 'Tuvinijski');
INSERT INTO "country" ("id", "name") VALUES ('tw', 'Tvi');
INSERT INTO "country" ("id", "name") VALUES ('udm', 'Udmurt');
INSERT INTO "country" ("id", "name") VALUES ('uga', 'Ugaritski');
INSERT INTO "country" ("id", "name") VALUES ('fiu', 'Ugro-finski jezik');
INSERT INTO "country" ("id", "name") VALUES ('ug', 'Ujgurski');
INSERT INTO "country" ("id", "name") VALUES ('uk', 'Ukrajinski');
INSERT INTO "country" ("id", "name") VALUES ('umb', 'Umbundu');
INSERT INTO "country" ("id", "name") VALUES ('ur', 'Urdu');
INSERT INTO "country" ("id", "name") VALUES ('uz', 'Uzbečki');
INSERT INTO "country" ("id", "name") VALUES ('vai', 'Vai');
INSERT INTO "country" ("id", "name") VALUES ('wak', 'Vakašanski jezik');
INSERT INTO "country" ("id", "name") VALUES ('wal', 'Valamo');
INSERT INTO "country" ("id", "name") VALUES ('wa', 'Valun');
INSERT INTO "country" ("id", "name") VALUES ('war', 'Varej');
INSERT INTO "country" ("id", "name") VALUES ('was', 'Vašo');
INSERT INTO "country" ("id", "name") VALUES ('cy', 'Velški');
INSERT INTO "country" ("id", "name") VALUES ('ve', 'Venda');
INSERT INTO "country" ("id", "name") VALUES ('art', 'Veštački');
INSERT INTO "country" ("id", "name") VALUES ('vi', 'Vijetnamski');
INSERT INTO "country" ("id", "name") VALUES ('vo', 'Volapük');
INSERT INTO "country" ("id", "name") VALUES ('wo', 'Volof');
INSERT INTO "country" ("id", "name") VALUES ('vot', 'Votski');
INSERT INTO "country" ("id", "name") VALUES ('znd', 'Zande');
INSERT INTO "country" ("id", "name") VALUES ('zap', 'Zapotečki');
INSERT INTO "country" ("id", "name") VALUES ('zza', 'Zaza');
INSERT INTO "country" ("id", "name") VALUES ('zen', 'Zenaga');
INSERT INTO "country" ("id", "name") VALUES ('za', 'Zuang');
INSERT INTO "country" ("id", "name") VALUES ('zu', 'Zulu');
INSERT INTO "country" ("id", "name") VALUES ('zun', 'Zuni');
INSERT INTO "country" ("id", "name") VALUES ('kaj', 'Žju');
INSERT INTO "country" ("id", "name") VALUES ('yue', 'Кантонски');
INSERT INTO "country" ("id", "name") VALUES ('swb', 'Коморски');
