CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('ab', 'Abkhaz');
INSERT INTO "country" ("id", "name") VALUES ('ace', 'Aceh');
INSERT INTO "country" ("id", "name") VALUES ('ach', 'Acholi');
INSERT INTO "country" ("id", "name") VALUES ('ada', 'Adangme');
INSERT INTO "country" ("id", "name") VALUES ('ady', 'Adygei');
INSERT INTO "country" ("id", "name") VALUES ('aa', 'Afar');
INSERT INTO "country" ("id", "name") VALUES ('afh', 'Afrihili');
INSERT INTO "country" ("id", "name") VALUES ('af', 'Afrikaans');
INSERT INTO "country" ("id", "name") VALUES ('ain', 'Ainu');
INSERT INTO "country" ("id", "name") VALUES ('ak', 'Akan');
INSERT INTO "country" ("id", "name") VALUES ('akk', 'Akkadien');
INSERT INTO "country" ("id", "name") VALUES ('sq', 'Albanian');
INSERT INTO "country" ("id", "name") VALUES ('ale', 'Aleut');
INSERT INTO "country" ("id", "name") VALUES ('tut', 'Altai');
INSERT INTO "country" ("id", "name") VALUES ('alt', 'Altai Selatan');
INSERT INTO "country" ("id", "name") VALUES ('am', 'Amharik');
INSERT INTO "country" ("id", "name") VALUES ('anp', 'Angika');
INSERT INTO "country" ("id", "name") VALUES ('ar', 'Arab');
INSERT INTO "country" ("id", "name") VALUES ('an', 'Aragon');
INSERT INTO "country" ("id", "name") VALUES ('arc', 'Aram');
INSERT INTO "country" ("id", "name") VALUES ('sam', 'Aram Samaria');
INSERT INTO "country" ("id", "name") VALUES ('arp', 'Arapaho');
INSERT INTO "country" ("id", "name") VALUES ('arn', 'Araukan');
INSERT INTO "country" ("id", "name") VALUES ('arw', 'Arawak');
INSERT INTO "country" ("id", "name") VALUES ('hy', 'Armenia');
INSERT INTO "country" ("id", "name") VALUES ('as', 'Assam');
INSERT INTO "country" ("id", "name") VALUES ('ast', 'Astur');
INSERT INTO "country" ("id", "name") VALUES ('asa', 'Asu');
INSERT INTO "country" ("id", "name") VALUES ('cch', 'Atsam');
INSERT INTO "country" ("id", "name") VALUES ('map', 'Austronesia');
INSERT INTO "country" ("id", "name") VALUES ('av', 'Avar');
INSERT INTO "country" ("id", "name") VALUES ('ae', 'Avestan');
INSERT INTO "country" ("id", "name") VALUES ('awa', 'Awadhi');
INSERT INTO "country" ("id", "name") VALUES ('ay', 'Aymara');
INSERT INTO "country" ("id", "name") VALUES ('az', 'Azerbaijan');
INSERT INTO "country" ("id", "name") VALUES ('alg', 'Bahasa Algonquia');
INSERT INTO "country" ("id", "name") VALUES ('cmc', 'Bahasa Chamik');
INSERT INTO "country" ("id", "name") VALUES ('cu', 'Bahasa Gereja Slavonia');
INSERT INTO "country" ("id", "name") VALUES ('id', 'Bahasa Indonesia');
INSERT INTO "country" ("id", "name") VALUES ('sgn', 'Bahasa Isyarat');
INSERT INTO "country" ("id", "name") VALUES ('mis', 'Bahasa Lain-lain');
INSERT INTO "country" ("id", "name") VALUES ('mus', 'Bahasa Muskogee');
INSERT INTO "country" ("id", "name") VALUES ('und', 'Bahasa Tidak Dikenal');
INSERT INTO "country" ("id", "name") VALUES ('ban', 'Bali');
INSERT INTO "country" ("id", "name") VALUES ('bal', 'Baluchi');
INSERT INTO "country" ("id", "name") VALUES ('bm', 'Bambara');
INSERT INTO "country" ("id", "name") VALUES ('bad', 'Banda');
INSERT INTO "country" ("id", "name") VALUES ('bnt', 'Bantu');
INSERT INTO "country" ("id", "name") VALUES ('bas', 'Basa');
INSERT INTO "country" ("id", "name") VALUES ('ba', 'Bashkir');
INSERT INTO "country" ("id", "name") VALUES ('eu', 'Basque');
INSERT INTO "country" ("id", "name") VALUES ('btk', 'Batak');
INSERT INTO "country" ("id", "name") VALUES ('bej', 'Beja');
INSERT INTO "country" ("id", "name") VALUES ('nl', 'Belanda');
INSERT INTO "country" ("id", "name") VALUES ('dum', 'Belanda Tengah');
INSERT INTO "country" ("id", "name") VALUES ('be', 'Belarusia');
INSERT INTO "country" ("id", "name") VALUES ('bem', 'Bemba');
INSERT INTO "country" ("id", "name") VALUES ('bez', 'Bena');
INSERT INTO "country" ("id", "name") VALUES ('bn', 'Bengali');
INSERT INTO "country" ("id", "name") VALUES ('bho', 'Bhojpur');
INSERT INTO "country" ("id", "name") VALUES ('bh', 'Bihari');
INSERT INTO "country" ("id", "name") VALUES ('bik', 'Bikol');
INSERT INTO "country" ("id", "name") VALUES ('bin', 'Bini');
INSERT INTO "country" ("id", "name") VALUES ('bi', 'Bislama');
INSERT INTO "country" ("id", "name") VALUES ('byn', 'Blin');
INSERT INTO "country" ("id", "name") VALUES ('brx', 'Bodo');
INSERT INTO "country" ("id", "name") VALUES ('nb', 'Bokmål Norwegia');
INSERT INTO "country" ("id", "name") VALUES ('bs', 'Bosnia');
INSERT INTO "country" ("id", "name") VALUES ('bra', 'Braj');
INSERT INTO "country" ("id", "name") VALUES ('br', 'Breton');
INSERT INTO "country" ("id", "name") VALUES ('art', 'Buatan (Lainnya)');
INSERT INTO "country" ("id", "name") VALUES ('bug', 'Bugis');
INSERT INTO "country" ("id", "name") VALUES ('bg', 'Bulgaria');
INSERT INTO "country" ("id", "name") VALUES ('bua', 'Buriat');
INSERT INTO "country" ("id", "name") VALUES ('my', 'Burma');
INSERT INTO "country" ("id", "name") VALUES ('ceb', 'Cebuano');
INSERT INTO "country" ("id", "name") VALUES ('cel', 'Celtic (Lainnya)');
INSERT INTO "country" ("id", "name") VALUES ('chg', 'Chagatai');
INSERT INTO "country" ("id", "name") VALUES ('ch', 'Chamorro');
INSERT INTO "country" ("id", "name") VALUES ('ce', 'Chechen');
INSERT INTO "country" ("id", "name") VALUES ('chr', 'Cherokee');
INSERT INTO "country" ("id", "name") VALUES ('cs', 'Cheska');
INSERT INTO "country" ("id", "name") VALUES ('chy', 'Cheyenne');
INSERT INTO "country" ("id", "name") VALUES ('chb', 'Chibcha');
INSERT INTO "country" ("id", "name") VALUES ('chp', 'Chipewyan');
INSERT INTO "country" ("id", "name") VALUES ('chk', 'Chuuke');
INSERT INTO "country" ("id", "name") VALUES ('cv', 'Chuvash');
INSERT INTO "country" ("id", "name") VALUES ('dak', 'Dakota');
INSERT INTO "country" ("id", "name") VALUES ('da', 'Dansk');
INSERT INTO "country" ("id", "name") VALUES ('dar', 'Dargwa');
INSERT INTO "country" ("id", "name") VALUES ('day', 'Dayak');
INSERT INTO "country" ("id", "name") VALUES ('del', 'Delaware');
INSERT INTO "country" ("id", "name") VALUES ('din', 'Dinka');
INSERT INTO "country" ("id", "name") VALUES ('dv', 'Divehi');
INSERT INTO "country" ("id", "name") VALUES ('doi', 'Dogri');
INSERT INTO "country" ("id", "name") VALUES ('dgr', 'Dogrib');
INSERT INTO "country" ("id", "name") VALUES ('dua', 'Duala');
INSERT INTO "country" ("id", "name") VALUES ('dyu', 'Dyula');
INSERT INTO "country" ("id", "name") VALUES ('dz', 'Dzongkha');
INSERT INTO "country" ("id", "name") VALUES ('efi', 'Efik');
INSERT INTO "country" ("id", "name") VALUES ('eka', 'Ekajuk');
INSERT INTO "country" ("id", "name") VALUES ('elx', 'Elam');
INSERT INTO "country" ("id", "name") VALUES ('ebu', 'Embu');
INSERT INTO "country" ("id", "name") VALUES ('myv', 'Erza');
INSERT INTO "country" ("id", "name") VALUES ('eo', 'Esperanto');
INSERT INTO "country" ("id", "name") VALUES ('et', 'Estonian');
INSERT INTO "country" ("id", "name") VALUES ('ee', 'Ewe');
INSERT INTO "country" ("id", "name") VALUES ('ewo', 'Ewondo');
INSERT INTO "country" ("id", "name") VALUES ('fan', 'Fang');
INSERT INTO "country" ("id", "name") VALUES ('fat', 'Fanti');
INSERT INTO "country" ("id", "name") VALUES ('fo', 'Faro');
INSERT INTO "country" ("id", "name") VALUES ('fj', 'Fiji');
INSERT INTO "country" ("id", "name") VALUES ('fil', 'Filipina');
INSERT INTO "country" ("id", "name") VALUES ('nl_BE', 'Flemish');
INSERT INTO "country" ("id", "name") VALUES ('fon', 'Fon');
INSERT INTO "country" ("id", "name") VALUES ('fy', 'Frisia Barat');
INSERT INTO "country" ("id", "name") VALUES ('frs', 'Frisia Timur');
INSERT INTO "country" ("id", "name") VALUES ('frr', 'Frisia Utara');
INSERT INTO "country" ("id", "name") VALUES ('fur', 'Friuli');
INSERT INTO "country" ("id", "name") VALUES ('ff', 'Fulah');
INSERT INTO "country" ("id", "name") VALUES ('phn', 'Funisia');
INSERT INTO "country" ("id", "name") VALUES ('gaa', 'Ga');
INSERT INTO "country" ("id", "name") VALUES ('gd', 'Gaelik Skotlandia');
INSERT INTO "country" ("id", "name") VALUES ('gl', 'Galisia');
INSERT INTO "country" ("id", "name") VALUES ('lg', 'Ganda');
INSERT INTO "country" ("id", "name") VALUES ('gay', 'Gayo');
INSERT INTO "country" ("id", "name") VALUES ('gba', 'Gbaya');
INSERT INTO "country" ("id", "name") VALUES ('gez', 'Geez');
INSERT INTO "country" ("id", "name") VALUES ('ka', 'Georgia');
INSERT INTO "country" ("id", "name") VALUES ('gil', 'Gilbert');
INSERT INTO "country" ("id", "name") VALUES ('gon', 'Gondi');
INSERT INTO "country" ("id", "name") VALUES ('gor', 'Gorontalo');
INSERT INTO "country" ("id", "name") VALUES ('got', 'Gothik');
INSERT INTO "country" ("id", "name") VALUES ('grb', 'Grebo');
INSERT INTO "country" ("id", "name") VALUES ('gn', 'Guarani');
INSERT INTO "country" ("id", "name") VALUES ('gu', 'Gujarati');
INSERT INTO "country" ("id", "name") VALUES ('gwi', 'Gwich\'in');
INSERT INTO "country" ("id", "name") VALUES ('hai', 'Haida');
INSERT INTO "country" ("id", "name") VALUES ('ht', 'Haiti');
INSERT INTO "country" ("id", "name") VALUES ('ha', 'Hausa');
INSERT INTO "country" ("id", "name") VALUES ('haw', 'Hawaii');
INSERT INTO "country" ("id", "name") VALUES ('hz', 'Herero');
INSERT INTO "country" ("id", "name") VALUES ('hil', 'Hiligaynon');
INSERT INTO "country" ("id", "name") VALUES ('him', 'Himachali');
INSERT INTO "country" ("id", "name") VALUES ('hi', 'Hindi');
INSERT INTO "country" ("id", "name") VALUES ('ho', 'Hiri Motu');
INSERT INTO "country" ("id", "name") VALUES ('hit', 'Hitit');
INSERT INTO "country" ("id", "name") VALUES ('hmn', 'Hmong');
INSERT INTO "country" ("id", "name") VALUES ('hu', 'Hungaria');
INSERT INTO "country" ("id", "name") VALUES ('hup', 'Hupa');
INSERT INTO "country" ("id", "name") VALUES ('iba', 'Iban');
INSERT INTO "country" ("id", "name") VALUES ('he', 'Ibrani');
INSERT INTO "country" ("id", "name") VALUES ('jrb', 'Ibrani-Arab');
INSERT INTO "country" ("id", "name") VALUES ('jpr', 'Ibrani-Persia');
INSERT INTO "country" ("id", "name") VALUES ('io', 'Ido');
INSERT INTO "country" ("id", "name") VALUES ('ig', 'Igbo');
INSERT INTO "country" ("id", "name") VALUES ('ijo', 'Ijo');
INSERT INTO "country" ("id", "name") VALUES ('ilo', 'Iloko');
INSERT INTO "country" ("id", "name") VALUES ('smn', 'Inari Sami');
INSERT INTO "country" ("id", "name") VALUES ('cai', 'India Amerika Tengah (Lainnnya)');
INSERT INTO "country" ("id", "name") VALUES ('en', 'Inggris');
INSERT INTO "country" ("id", "name") VALUES ('en_US', 'Inggris A.S.');
INSERT INTO "country" ("id", "name") VALUES ('en_AU', 'Inggris Australia');
INSERT INTO "country" ("id", "name") VALUES ('en_GB', 'Inggris Inggris');
INSERT INTO "country" ("id", "name") VALUES ('en_CA', 'Inggris Kanada');
INSERT INTO "country" ("id", "name") VALUES ('ang', 'Inggris Kuno (kl.450-1100)');
INSERT INTO "country" ("id", "name") VALUES ('enm', 'Inggris, Abad Pertengahan (1100-1500)');
INSERT INTO "country" ("id", "name") VALUES ('inh', 'Ingushetia');
INSERT INTO "country" ("id", "name") VALUES ('ia', 'Interlingua');
INSERT INTO "country" ("id", "name") VALUES ('ie', 'Interlingue');
INSERT INTO "country" ("id", "name") VALUES ('iu', 'Inuktitut');
INSERT INTO "country" ("id", "name") VALUES ('ik', 'Inupiak');
INSERT INTO "country" ("id", "name") VALUES ('ga', 'Irlandia');
INSERT INTO "country" ("id", "name") VALUES ('mga', 'Irlandia Abad Pertengahan (900-1200)');
INSERT INTO "country" ("id", "name") VALUES ('sga', 'Irlandia Kuno');
INSERT INTO "country" ("id", "name") VALUES ('is', 'Islandia');
INSERT INTO "country" ("id", "name") VALUES ('it', 'Italia');
INSERT INTO "country" ("id", "name") VALUES ('chn', 'Jargon Chinook');
INSERT INTO "country" ("id", "name") VALUES ('jv', 'Jawa');
INSERT INTO "country" ("id", "name") VALUES ('ja', 'Jepang');
INSERT INTO "country" ("id", "name") VALUES ('de', 'Jerman');
INSERT INTO "country" ("id", "name") VALUES ('de_AT', 'Jerman Austria');
INSERT INTO "country" ("id", "name") VALUES ('goh', 'Jerman Kuno (kl.750-1050)');
INSERT INTO "country" ("id", "name") VALUES ('nds', 'Jerman Rendah');
INSERT INTO "country" ("id", "name") VALUES ('gsw', 'Jerman Swiss');
INSERT INTO "country" ("id", "name") VALUES ('de_CH', 'Jerman Tinggi Swiss');
INSERT INTO "country" ("id", "name") VALUES ('gmh', 'Jerman, Abad Pertengahan (kl.1050-1500)');
INSERT INTO "country" ("id", "name") VALUES ('gem', 'Jermanik (Lainnya)');
INSERT INTO "country" ("id", "name") VALUES ('kaj', 'Jju');
INSERT INTO "country" ("id", "name") VALUES ('kbd', 'Kabardi');
INSERT INTO "country" ("id", "name") VALUES ('kea', 'Kabuverdianu');
INSERT INTO "country" ("id", "name") VALUES ('kab', 'Kabyle');
INSERT INTO "country" ("id", "name") VALUES ('kac', 'Kachin');
INSERT INTO "country" ("id", "name") VALUES ('cad', 'Kado');
INSERT INTO "country" ("id", "name") VALUES ('kl', 'Kalaallisut');
INSERT INTO "country" ("id", "name") VALUES ('xal', 'Kalmuk');
INSERT INTO "country" ("id", "name") VALUES ('kam', 'Kamba');
INSERT INTO "country" ("id", "name") VALUES ('kn', 'Kannada');
INSERT INTO "country" ("id", "name") VALUES ('yue', 'Kanton');
INSERT INTO "country" ("id", "name") VALUES ('kr', 'Kanuri');
INSERT INTO "country" ("id", "name") VALUES ('kaa', 'Kara-Kalpak');
INSERT INTO "country" ("id", "name") VALUES ('krc', 'Karachai Balkar');
INSERT INTO "country" ("id", "name") VALUES ('krl', 'Karelia');
INSERT INTO "country" ("id", "name") VALUES ('kar', 'Karen');
INSERT INTO "country" ("id", "name") VALUES ('car', 'Karib');
INSERT INTO "country" ("id", "name") VALUES ('ks', 'Kashmir');
INSERT INTO "country" ("id", "name") VALUES ('csb', 'Kashubia');
INSERT INTO "country" ("id", "name") VALUES ('ca', 'Katalan');
INSERT INTO "country" ("id", "name") VALUES ('kaw', 'Kawi');
INSERT INTO "country" ("id", "name") VALUES ('kk', 'Kazakh');
INSERT INTO "country" ("id", "name") VALUES ('kha', 'Khasi');
INSERT INTO "country" ("id", "name") VALUES ('km', 'Khmer');
INSERT INTO "country" ("id", "name") VALUES ('kho', 'Khotan');
INSERT INTO "country" ("id", "name") VALUES ('ki', 'Kikuyu');
INSERT INTO "country" ("id", "name") VALUES ('kmb', 'Kimbundu');
INSERT INTO "country" ("id", "name") VALUES ('rw', 'Kinyarwanda');
INSERT INTO "country" ("id", "name") VALUES ('ky', 'Kirgiz');
INSERT INTO "country" ("id", "name") VALUES ('tlh', 'Klingon');
INSERT INTO "country" ("id", "name") VALUES ('cho', 'Koktaw');
INSERT INTO "country" ("id", "name") VALUES ('kv', 'Komi');
INSERT INTO "country" ("id", "name") VALUES ('swb', 'Komoria');
INSERT INTO "country" ("id", "name") VALUES ('kg', 'Kongo');
INSERT INTO "country" ("id", "name") VALUES ('kok', 'Konkani');
INSERT INTO "country" ("id", "name") VALUES ('cop', 'Koptik');
INSERT INTO "country" ("id", "name") VALUES ('ko', 'Korea');
INSERT INTO "country" ("id", "name") VALUES ('kw', 'Kornish');
INSERT INTO "country" ("id", "name") VALUES ('kfo', 'Koro');
INSERT INTO "country" ("id", "name") VALUES ('co', 'Korsika');
INSERT INTO "country" ("id", "name") VALUES ('kos', 'Kosre');
INSERT INTO "country" ("id", "name") VALUES ('kpe', 'Kpelle');
INSERT INTO "country" ("id", "name") VALUES ('cr', 'Kree');
INSERT INTO "country" ("id", "name") VALUES ('crp', 'Kreol dan Pijin Lain');
INSERT INTO "country" ("id", "name") VALUES ('cpe', 'Kreol dan Pijin Lain berbasis Inggris');
INSERT INTO "country" ("id", "name") VALUES ('cpp', 'Kreol dan Pijin Lain berbasis Portugis');
INSERT INTO "country" ("id", "name") VALUES ('hr', 'Kroasia');
INSERT INTO "country" ("id", "name") VALUES ('kro', 'Kru');
INSERT INTO "country" ("id", "name") VALUES ('kj', 'Kuanyama');
INSERT INTO "country" ("id", "name") VALUES ('kum', 'Kumyk');
INSERT INTO "country" ("id", "name") VALUES ('ku', 'Kurdi');
INSERT INTO "country" ("id", "name") VALUES ('kru', 'Kuruk');
INSERT INTO "country" ("id", "name") VALUES ('kut', 'Kutenai');
INSERT INTO "country" ("id", "name") VALUES ('lad', 'Ladino');
INSERT INTO "country" ("id", "name") VALUES ('lah', 'Lahnda');
INSERT INTO "country" ("id", "name") VALUES ('lam', 'Lamba');
INSERT INTO "country" ("id", "name") VALUES ('lo', 'Lao');
INSERT INTO "country" ("id", "name") VALUES ('la', 'Latin');
INSERT INTO "country" ("id", "name") VALUES ('lv', 'Latvia');
INSERT INTO "country" ("id", "name") VALUES ('lez', 'Lezghia');
INSERT INTO "country" ("id", "name") VALUES ('li', 'Limburgia');
INSERT INTO "country" ("id", "name") VALUES ('ln', 'Lingala');
INSERT INTO "country" ("id", "name") VALUES ('lt', 'Lithuania');
INSERT INTO "country" ("id", "name") VALUES ('jbo', 'Lojban');
INSERT INTO "country" ("id", "name") VALUES ('loz', 'Lozi');
INSERT INTO "country" ("id", "name") VALUES ('lu', 'Luba-Katanga');
INSERT INTO "country" ("id", "name") VALUES ('lua', 'Luba-Lulua');
INSERT INTO "country" ("id", "name") VALUES ('lui', 'Luiseno');
INSERT INTO "country" ("id", "name") VALUES ('smj', 'Lule Sami');
INSERT INTO "country" ("id", "name") VALUES ('lun', 'Lunda');
INSERT INTO "country" ("id", "name") VALUES ('luo', 'Luo');
INSERT INTO "country" ("id", "name") VALUES ('lus', 'Lushai');
INSERT INTO "country" ("id", "name") VALUES ('lb', 'Luxembourg');
INSERT INTO "country" ("id", "name") VALUES ('mad', 'Madura');
INSERT INTO "country" ("id", "name") VALUES ('mag', 'Magahi');
INSERT INTO "country" ("id", "name") VALUES ('mai', 'Maithili');
INSERT INTO "country" ("id", "name") VALUES ('mak', 'Makassar');
INSERT INTO "country" ("id", "name") VALUES ('rup', 'Makedo-Rumania');
INSERT INTO "country" ("id", "name") VALUES ('mk', 'Makedonia');
INSERT INTO "country" ("id", "name") VALUES ('mg', 'Malagasi');
INSERT INTO "country" ("id", "name") VALUES ('ms', 'Malay');
INSERT INTO "country" ("id", "name") VALUES ('ml', 'Malayalam');
INSERT INTO "country" ("id", "name") VALUES ('mt', 'Malta');
INSERT INTO "country" ("id", "name") VALUES ('mnc', 'Manchuria');
INSERT INTO "country" ("id", "name") VALUES ('mdr', 'Mandar');
INSERT INTO "country" ("id", "name") VALUES ('zh', 'Mandarin');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hans', 'Mandarin (aksara sederhana)');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hant', 'Mandarin (aksara tradisional)');
INSERT INTO "country" ("id", "name") VALUES ('man', 'Mandingo');
INSERT INTO "country" ("id", "name") VALUES ('mni', 'Manipur');
INSERT INTO "country" ("id", "name") VALUES ('gv', 'Manx');
INSERT INTO "country" ("id", "name") VALUES ('mi', 'Maori');
INSERT INTO "country" ("id", "name") VALUES ('mr', 'Marathi');
INSERT INTO "country" ("id", "name") VALUES ('chm', 'Mari');
INSERT INTO "country" ("id", "name") VALUES ('mh', 'Marshall');
INSERT INTO "country" ("id", "name") VALUES ('mwr', 'Marwari');
INSERT INTO "country" ("id", "name") VALUES ('mas', 'Masai');
INSERT INTO "country" ("id", "name") VALUES ('men', 'Mende');
INSERT INTO "country" ("id", "name") VALUES ('egy', 'Mesir Kuno');
INSERT INTO "country" ("id", "name") VALUES ('mic', 'Mikmak');
INSERT INTO "country" ("id", "name") VALUES ('min', 'Minangkabau');
INSERT INTO "country" ("id", "name") VALUES ('mwl', 'Miranda');
INSERT INTO "country" ("id", "name") VALUES ('moh', 'Mohawk');
INSERT INTO "country" ("id", "name") VALUES ('mdf', 'Moksha');
INSERT INTO "country" ("id", "name") VALUES ('mo', 'Moldavian');
INSERT INTO "country" ("id", "name") VALUES ('mkh', 'Mon-Khmer (Lainnya)');
INSERT INTO "country" ("id", "name") VALUES ('lol', 'Mongo');
INSERT INTO "country" ("id", "name") VALUES ('mn', 'Mongolian');
INSERT INTO "country" ("id", "name") VALUES ('mos', 'Mossi');
INSERT INTO "country" ("id", "name") VALUES ('nqo', 'N\'Ko');
INSERT INTO "country" ("id", "name") VALUES ('nah', 'Nahuatl');
INSERT INTO "country" ("id", "name") VALUES ('na', 'Nauru');
INSERT INTO "country" ("id", "name") VALUES ('nv', 'Navajo');
INSERT INTO "country" ("id", "name") VALUES ('nr', 'Ndebele Selatan');
INSERT INTO "country" ("id", "name") VALUES ('nd', 'Ndebele Utara');
INSERT INTO "country" ("id", "name") VALUES ('ng', 'Ndonga');
INSERT INTO "country" ("id", "name") VALUES ('nap', 'Neapolitan');
INSERT INTO "country" ("id", "name") VALUES ('ne', 'Nepal');
INSERT INTO "country" ("id", "name") VALUES ('new', 'Newari');
INSERT INTO "country" ("id", "name") VALUES ('nwc', 'Newari Klasik');
INSERT INTO "country" ("id", "name") VALUES ('nia', 'Nias');
INSERT INTO "country" ("id", "name") VALUES ('niu', 'Niuea');
INSERT INTO "country" ("id", "name") VALUES ('nog', 'Nogai');
INSERT INTO "country" ("id", "name") VALUES ('non', 'Norse Kuno');
INSERT INTO "country" ("id", "name") VALUES ('se', 'Northern Sami');
INSERT INTO "country" ("id", "name") VALUES ('no', 'Norwegian');
INSERT INTO "country" ("id", "name") VALUES ('nn', 'Norwegian Nynorsk');
INSERT INTO "country" ("id", "name") VALUES ('nym', 'Nyamwezi');
INSERT INTO "country" ("id", "name") VALUES ('ny', 'Nyanja');
INSERT INTO "country" ("id", "name") VALUES ('nyn', 'Nyankole');
INSERT INTO "country" ("id", "name") VALUES ('tog', 'Nyasa Tonga');
INSERT INTO "country" ("id", "name") VALUES ('nyo', 'Nyoro');
INSERT INTO "country" ("id", "name") VALUES ('nzi', 'Nzima');
INSERT INTO "country" ("id", "name") VALUES ('oj', 'Ojibwa');
INSERT INTO "country" ("id", "name") VALUES ('or', 'Oriya');
INSERT INTO "country" ("id", "name") VALUES ('om', 'Oromo');
INSERT INTO "country" ("id", "name") VALUES ('osa', 'Osage');
INSERT INTO "country" ("id", "name") VALUES ('oc', 'Ositania');
INSERT INTO "country" ("id", "name") VALUES ('os', 'Ossetia');
INSERT INTO "country" ("id", "name") VALUES ('pal', 'Pahlevi');
INSERT INTO "country" ("id", "name") VALUES ('pau', 'Palau');
INSERT INTO "country" ("id", "name") VALUES ('pi', 'Pali');
INSERT INTO "country" ("id", "name") VALUES ('pam', 'Pampanga');
INSERT INTO "country" ("id", "name") VALUES ('pag', 'Pangasina');
INSERT INTO "country" ("id", "name") VALUES ('pap', 'Papiamento');
INSERT INTO "country" ("id", "name") VALUES ('ps', 'Pashto');
INSERT INTO "country" ("id", "name") VALUES ('fr', 'Perancis');
INSERT INTO "country" ("id", "name") VALUES ('fro', 'Perancis Kuno (842-kl.1400)');
INSERT INTO "country" ("id", "name") VALUES ('frm', 'Perancis, Abad Pertengahan (kl.1400-1600)');
INSERT INTO "country" ("id", "name") VALUES ('fa', 'Persia');
INSERT INTO "country" ("id", "name") VALUES ('peo', 'Persia Kuno (kl.600-400 SM.)');
INSERT INTO "country" ("id", "name") VALUES ('pon', 'Pohnpeia');
INSERT INTO "country" ("id", "name") VALUES ('pl', 'Polandia');
INSERT INTO "country" ("id", "name") VALUES ('pt', 'Portugis');
INSERT INTO "country" ("id", "name") VALUES ('pt_PT', 'Portugis (Iberia)');
INSERT INTO "country" ("id", "name") VALUES ('pt_BR', 'Portugis Brasil');
INSERT INTO "country" ("id", "name") VALUES ('fr_CA', 'Prancis Kanada');
INSERT INTO "country" ("id", "name") VALUES ('fr_CH', 'Prancis Swiss');
INSERT INTO "country" ("id", "name") VALUES ('pro', 'Provençal Lama');
INSERT INTO "country" ("id", "name") VALUES ('pa', 'Punjabi');
INSERT INTO "country" ("id", "name") VALUES ('qu', 'Quechua');
INSERT INTO "country" ("id", "name") VALUES ('raj', 'Rajasthani');
INSERT INTO "country" ("id", "name") VALUES ('rap', 'Rapanui');
INSERT INTO "country" ("id", "name") VALUES ('rar', 'Rarotonga');
INSERT INTO "country" ("id", "name") VALUES ('rm', 'Reto-Roman');
INSERT INTO "country" ("id", "name") VALUES ('rom', 'Romani');
INSERT INTO "country" ("id", "name") VALUES ('root', 'Root');
INSERT INTO "country" ("id", "name") VALUES ('ro', 'Rumania');
INSERT INTO "country" ("id", "name") VALUES ('afa', 'Rumpun Bahasa Afro-Asia');
INSERT INTO "country" ("id", "name") VALUES ('apa', 'Rumpun Bahasa Apache');
INSERT INTO "country" ("id", "name") VALUES ('ath', 'Rumpun Bahasa Athapaska');
INSERT INTO "country" ("id", "name") VALUES ('aus', 'Rumpun Bahasa Australia');
INSERT INTO "country" ("id", "name") VALUES ('bat', 'Rumpun Bahasa Baltik');
INSERT INTO "country" ("id", "name") VALUES ('bai', 'Rumpun Bahasa Bamileke');
INSERT INTO "country" ("id", "name") VALUES ('ber', 'Rumpun Bahasa Berber');
INSERT INTO "country" ("id", "name") VALUES ('dra', 'Rumpun Bahasa Dravidia');
INSERT INTO "country" ("id", "name") VALUES ('phi', 'Rumpun Bahasa Filipina');
INSERT INTO "country" ("id", "name") VALUES ('fiu', 'Rumpun Bahasa Finno-Ugrik');
INSERT INTO "country" ("id", "name") VALUES ('sai', 'Rumpun Bahasa Indian Amerika Selatan');
INSERT INTO "country" ("id", "name") VALUES ('nai', 'Rumpun Bahasa Indian Amerika Utara');
INSERT INTO "country" ("id", "name") VALUES ('inc', 'Rumpun Bahasa Indik');
INSERT INTO "country" ("id", "name") VALUES ('ine', 'Rumpun Bahasa Indo-Eropa');
INSERT INTO "country" ("id", "name") VALUES ('ira', 'Rumpun Bahasa Iran');
INSERT INTO "country" ("id", "name") VALUES ('iro', 'Rumpun Bahasa Iroquis');
INSERT INTO "country" ("id", "name") VALUES ('cau', 'Rumpun Bahasa Kaukasia');
INSERT INTO "country" ("id", "name") VALUES ('khi', 'Rumpun Bahasa Khoisa');
INSERT INTO "country" ("id", "name") VALUES ('cus', 'Rumpun Bahasa Kush');
INSERT INTO "country" ("id", "name") VALUES ('mno', 'Rumpun Bahasa Manobo');
INSERT INTO "country" ("id", "name") VALUES ('myn', 'Rumpun Bahasa Maya');
INSERT INTO "country" ("id", "name") VALUES ('mun', 'Rumpun Bahasa Munda');
INSERT INTO "country" ("id", "name") VALUES ('nic', 'Rumpun Bahasa Niger-Kordofania');
INSERT INTO "country" ("id", "name") VALUES ('ssa', 'Rumpun Bahasa Nilo-Sahara');
INSERT INTO "country" ("id", "name") VALUES ('nub', 'Rumpun Bahasa Nubia');
INSERT INTO "country" ("id", "name") VALUES ('oto', 'Rumpun Bahasa Otomia');
INSERT INTO "country" ("id", "name") VALUES ('paa', 'Rumpun Bahasa Papua');
INSERT INTO "country" ("id", "name") VALUES ('pra', 'Rumpun Bahasa Prakrit');
INSERT INTO "country" ("id", "name") VALUES ('roa', 'Rumpun Bahasa Roman');
INSERT INTO "country" ("id", "name") VALUES ('sal', 'Rumpun Bahasa Salisha');
INSERT INTO "country" ("id", "name") VALUES ('smi', 'Rumpun Bahasa Sami');
INSERT INTO "country" ("id", "name") VALUES ('sem', 'Rumpun Bahasa Semit');
INSERT INTO "country" ("id", "name") VALUES ('sit', 'Rumpun Bahasa Sino-Tibet');
INSERT INTO "country" ("id", "name") VALUES ('sio', 'Rumpun Bahasa Sioux');
INSERT INTO "country" ("id", "name") VALUES ('sla', 'Rumpun Bahasa Slavik');
INSERT INTO "country" ("id", "name") VALUES ('wen', 'Rumpun Bahasa Sorbia');
INSERT INTO "country" ("id", "name") VALUES ('tai', 'Rumpun Bahasa Tai');
INSERT INTO "country" ("id", "name") VALUES ('tup', 'Rumpun Bahasa Tupi');
INSERT INTO "country" ("id", "name") VALUES ('wak', 'Rumpun Bahasa Wakasha');
INSERT INTO "country" ("id", "name") VALUES ('ypk', 'Rumpun Bahasa Yupik');
INSERT INTO "country" ("id", "name") VALUES ('rn', 'Rundi');
INSERT INTO "country" ("id", "name") VALUES ('ru', 'Rusia');
INSERT INTO "country" ("id", "name") VALUES ('sah', 'Sakha');
INSERT INTO "country" ("id", "name") VALUES ('sma', 'Sami Selatan');
INSERT INTO "country" ("id", "name") VALUES ('sm', 'Samoan');
INSERT INTO "country" ("id", "name") VALUES ('sad', 'Sandawe');
INSERT INTO "country" ("id", "name") VALUES ('sg', 'Sango');
INSERT INTO "country" ("id", "name") VALUES ('sa', 'Sansekerta');
INSERT INTO "country" ("id", "name") VALUES ('sat', 'Santali');
INSERT INTO "country" ("id", "name") VALUES ('sc', 'Sardinia');
INSERT INTO "country" ("id", "name") VALUES ('sas', 'Sasak');
INSERT INTO "country" ("id", "name") VALUES ('sel', 'Selkup');
INSERT INTO "country" ("id", "name") VALUES ('sr', 'Serb');
INSERT INTO "country" ("id", "name") VALUES ('sh', 'Serbo-Croatian');
INSERT INTO "country" ("id", "name") VALUES ('srr', 'Serer');
INSERT INTO "country" ("id", "name") VALUES ('shn', 'Shan');
INSERT INTO "country" ("id", "name") VALUES ('sn', 'Shona');
INSERT INTO "country" ("id", "name") VALUES ('ii', 'Sichuan Yi');
INSERT INTO "country" ("id", "name") VALUES ('sid', 'Sidamo');
INSERT INTO "country" ("id", "name") VALUES ('bla', 'Siksika');
INSERT INTO "country" ("id", "name") VALUES ('sd', 'Sindhi');
INSERT INTO "country" ("id", "name") VALUES ('si', 'Sinhala');
INSERT INTO "country" ("id", "name") VALUES ('scn', 'Sisilia');
INSERT INTO "country" ("id", "name") VALUES ('sms', 'Skolt Sami');
INSERT INTO "country" ("id", "name") VALUES ('sco', 'Skotlandia');
INSERT INTO "country" ("id", "name") VALUES ('den', 'Slave');
INSERT INTO "country" ("id", "name") VALUES ('sl', 'Slovenia');
INSERT INTO "country" ("id", "name") VALUES ('sk', 'Slowakia');
INSERT INTO "country" ("id", "name") VALUES ('sog', 'Sogdien');
INSERT INTO "country" ("id", "name") VALUES ('so', 'Somali');
INSERT INTO "country" ("id", "name") VALUES ('son', 'Songhai');
INSERT INTO "country" ("id", "name") VALUES ('snk', 'Soninke');
INSERT INTO "country" ("id", "name") VALUES ('hsb', 'Sorbia Atas');
INSERT INTO "country" ("id", "name") VALUES ('dsb', 'Sorbia Rendah');
INSERT INTO "country" ("id", "name") VALUES ('st', 'Sotho Selatan');
INSERT INTO "country" ("id", "name") VALUES ('nso', 'Sotho Utara');
INSERT INTO "country" ("id", "name") VALUES ('es', 'Spanyol');
INSERT INTO "country" ("id", "name") VALUES ('es_ES', 'Spanyol (Iberia)');
INSERT INTO "country" ("id", "name") VALUES ('es_419', 'Spanyol Amerika Latin');
INSERT INTO "country" ("id", "name") VALUES ('srn', 'Sranan Tongo');
INSERT INTO "country" ("id", "name") VALUES ('suk', 'Sukuma');
INSERT INTO "country" ("id", "name") VALUES ('sux', 'Sumeria');
INSERT INTO "country" ("id", "name") VALUES ('su', 'Sunda');
INSERT INTO "country" ("id", "name") VALUES ('fi', 'Suomi');
INSERT INTO "country" ("id", "name") VALUES ('syr', 'Suriah');
INSERT INTO "country" ("id", "name") VALUES ('sus', 'Susu');
INSERT INTO "country" ("id", "name") VALUES ('sw', 'Swahili');
INSERT INTO "country" ("id", "name") VALUES ('ss', 'Swati');
INSERT INTO "country" ("id", "name") VALUES ('sv', 'Swedia');
INSERT INTO "country" ("id", "name") VALUES ('tl', 'Tagalog');
INSERT INTO "country" ("id", "name") VALUES ('ty', 'Tahiti');
INSERT INTO "country" ("id", "name") VALUES ('tg', 'Tajik');
INSERT INTO "country" ("id", "name") VALUES ('tmh', 'Tamashek');
INSERT INTO "country" ("id", "name") VALUES ('ta', 'Tamil');
INSERT INTO "country" ("id", "name") VALUES ('tt', 'Tatar');
INSERT INTO "country" ("id", "name") VALUES ('crh', 'Tatar Krimea');
INSERT INTO "country" ("id", "name") VALUES ('te', 'Telugu');
INSERT INTO "country" ("id", "name") VALUES ('ter', 'Tereno');
INSERT INTO "country" ("id", "name") VALUES ('tet', 'Tetun');
INSERT INTO "country" ("id", "name") VALUES ('th', 'Thai');
INSERT INTO "country" ("id", "name") VALUES ('bo', 'Tibet');
INSERT INTO "country" ("id", "name") VALUES ('zxx', 'Tidak ada konten linguistik');
INSERT INTO "country" ("id", "name") VALUES ('tig', 'Tigre');
INSERT INTO "country" ("id", "name") VALUES ('ti', 'Tigrinya');
INSERT INTO "country" ("id", "name") VALUES ('tem', 'Timne');
INSERT INTO "country" ("id", "name") VALUES ('tiv', 'Tiv');
INSERT INTO "country" ("id", "name") VALUES ('tli', 'Tlingit');
INSERT INTO "country" ("id", "name") VALUES ('tpi', 'Tok Pisin');
INSERT INTO "country" ("id", "name") VALUES ('tkl', 'Tokelau');
INSERT INTO "country" ("id", "name") VALUES ('to', 'Tonga');
INSERT INTO "country" ("id", "name") VALUES ('tsi', 'Tsimshia');
INSERT INTO "country" ("id", "name") VALUES ('ts', 'Tsonga');
INSERT INTO "country" ("id", "name") VALUES ('tn', 'Tswana');
INSERT INTO "country" ("id", "name") VALUES ('tum', 'Tumbuka');
INSERT INTO "country" ("id", "name") VALUES ('tr', 'Turki');
INSERT INTO "country" ("id", "name") VALUES ('ota', 'Turki Osmani');
INSERT INTO "country" ("id", "name") VALUES ('tk', 'Turkmen');
INSERT INTO "country" ("id", "name") VALUES ('tvl', 'Tuvalu');
INSERT INTO "country" ("id", "name") VALUES ('tyv', 'Tuvinia');
INSERT INTO "country" ("id", "name") VALUES ('tw', 'Twi');
INSERT INTO "country" ("id", "name") VALUES ('kcg', 'Tyap');
INSERT INTO "country" ("id", "name") VALUES ('udm', 'Udmurt');
INSERT INTO "country" ("id", "name") VALUES ('uga', 'Ugarit');
INSERT INTO "country" ("id", "name") VALUES ('ug', 'Uighur');
INSERT INTO "country" ("id", "name") VALUES ('uk', 'Ukraina');
INSERT INTO "country" ("id", "name") VALUES ('umb', 'Umbundu');
INSERT INTO "country" ("id", "name") VALUES ('ur', 'Urdu');
INSERT INTO "country" ("id", "name") VALUES ('uz', 'Uzbek');
INSERT INTO "country" ("id", "name") VALUES ('vai', 'Vai');
INSERT INTO "country" ("id", "name") VALUES ('ve', 'Venda');
INSERT INTO "country" ("id", "name") VALUES ('vi', 'Vietnam');
INSERT INTO "country" ("id", "name") VALUES ('vo', 'Volapük');
INSERT INTO "country" ("id", "name") VALUES ('vot', 'Votia');
INSERT INTO "country" ("id", "name") VALUES ('wal', 'Walamo');
INSERT INTO "country" ("id", "name") VALUES ('wa', 'Walloon');
INSERT INTO "country" ("id", "name") VALUES ('war', 'Warai');
INSERT INTO "country" ("id", "name") VALUES ('was', 'Washo');
INSERT INTO "country" ("id", "name") VALUES ('cy', 'Welsh');
INSERT INTO "country" ("id", "name") VALUES ('wo', 'Wolof');
INSERT INTO "country" ("id", "name") VALUES ('xh', 'Xhosa');
INSERT INTO "country" ("id", "name") VALUES ('yao', 'Yao');
INSERT INTO "country" ("id", "name") VALUES ('yap', 'Yapois');
INSERT INTO "country" ("id", "name") VALUES ('yi', 'Yiddish');
INSERT INTO "country" ("id", "name") VALUES ('yo', 'Yoruba');
INSERT INTO "country" ("id", "name") VALUES ('el', 'Yunani');
INSERT INTO "country" ("id", "name") VALUES ('grc', 'Yunani Kuno (sd 1453)');
INSERT INTO "country" ("id", "name") VALUES ('znd', 'Zande');
INSERT INTO "country" ("id", "name") VALUES ('zap', 'Zapotek');
INSERT INTO "country" ("id", "name") VALUES ('zza', 'Zaza');
INSERT INTO "country" ("id", "name") VALUES ('zen', 'Zenaga');
INSERT INTO "country" ("id", "name") VALUES ('za', 'Zhuang');
INSERT INTO "country" ("id", "name") VALUES ('zu', 'Zulu');
INSERT INTO "country" ("id", "name") VALUES ('zun', 'Zuni');
