CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('af', 'Afrikaans');
INSERT INTO `country` (`id`, `name`) VALUES ('sq', 'Albanees');
INSERT INTO `country` (`id`, `name`) VALUES ('am', 'Amharies');
INSERT INTO `country` (`id`, `name`) VALUES ('afa', 'Ander Afro-Asiaties');
INSERT INTO `country` (`id`, `name`) VALUES ('bat', 'Ander Balties');
INSERT INTO `country` (`id`, `name`) VALUES ('gem', 'Ander Germaans');
INSERT INTO `country` (`id`, `name`) VALUES ('ine', 'Ander Indo-Europees');
INSERT INTO `country` (`id`, `name`) VALUES ('cel', 'Ander Kelties');
INSERT INTO `country` (`id`, `name`) VALUES ('khi', 'Ander Khoi-San');
INSERT INTO `country` (`id`, `name`) VALUES ('art', 'Ander Kunsmatig');
INSERT INTO `country` (`id`, `name`) VALUES ('sem', 'Ander Semities');
INSERT INTO `country` (`id`, `name`) VALUES ('sla', 'Ander Slawies');
INSERT INTO `country` (`id`, `name`) VALUES ('egy', 'Antieke Egipties');
INSERT INTO `country` (`id`, `name`) VALUES ('grc', 'Antieke Grieks');
INSERT INTO `country` (`id`, `name`) VALUES ('ar', 'Arabies');
INSERT INTO `country` (`id`, `name`) VALUES ('arc', 'Aramees');
INSERT INTO `country` (`id`, `name`) VALUES ('hy', 'Armeens');
INSERT INTO `country` (`id`, `name`) VALUES ('az', 'Aserbeidjaans');
INSERT INTO `country` (`id`, `name`) VALUES ('as', 'Assamees');
INSERT INTO `country` (`id`, `name`) VALUES ('bnt', 'Bantoe');
INSERT INTO `country` (`id`, `name`) VALUES ('eu', 'Baskies');
INSERT INTO `country` (`id`, `name`) VALUES ('bn', 'Bengaals');
INSERT INTO `country` (`id`, `name`) VALUES ('ber', 'Berbers');
INSERT INTO `country` (`id`, `name`) VALUES ('bh', 'Bihari');
INSERT INTO `country` (`id`, `name`) VALUES ('my', 'Birmaans');
INSERT INTO `country` (`id`, `name`) VALUES ('bs', 'Bosnies');
INSERT INTO `country` (`id`, `name`) VALUES ('pt_BR', 'Brasiliaanse Portugees');
INSERT INTO `country` (`id`, `name`) VALUES ('br', 'Bretons');
INSERT INTO `country` (`id`, `name`) VALUES ('bg', 'Bulgaars');
INSERT INTO `country` (`id`, `name`) VALUES ('chr', 'Cherokees');
INSERT INTO `country` (`id`, `name`) VALUES ('da', 'Deens');
INSERT INTO `country` (`id`, `name`) VALUES ('de', 'Duits');
INSERT INTO `country` (`id`, `name`) VALUES ('en', 'Engels');
INSERT INTO `country` (`id`, `name`) VALUES ('eo', 'Esperanto');
INSERT INTO `country` (`id`, `name`) VALUES ('et', 'Estnies');
INSERT INTO `country` (`id`, `name`) VALUES ('fo', 'Faroëes');
INSERT INTO `country` (`id`, `name`) VALUES ('phn', 'Fenisies');
INSERT INTO `country` (`id`, `name`) VALUES ('fj', 'Fidjiaans');
INSERT INTO `country` (`id`, `name`) VALUES ('fil', 'Filippyns');
INSERT INTO `country` (`id`, `name`) VALUES ('fi', 'Fins');
INSERT INTO `country` (`id`, `name`) VALUES ('fr', 'Frans');
INSERT INTO `country` (`id`, `name`) VALUES ('fy', 'Fries');
INSERT INTO `country` (`id`, `name`) VALUES ('gl', 'Galicies');
INSERT INTO `country` (`id`, `name`) VALUES ('sgn', 'Gebaretaal');
INSERT INTO `country` (`id`, `name`) VALUES ('ka', 'Georgies');
INSERT INTO `country` (`id`, `name`) VALUES ('got', 'Goties');
INSERT INTO `country` (`id`, `name`) VALUES ('el', 'Grieks');
INSERT INTO `country` (`id`, `name`) VALUES ('gn', 'Guarani');
INSERT INTO `country` (`id`, `name`) VALUES ('gu', 'Gujarati');
INSERT INTO `country` (`id`, `name`) VALUES ('he', 'Hebreeus');
INSERT INTO `country` (`id`, `name`) VALUES ('hit', 'Hetities');
INSERT INTO `country` (`id`, `name`) VALUES ('hi', 'Hindi');
INSERT INTO `country` (`id`, `name`) VALUES ('hu', 'Hongaars');
INSERT INTO `country` (`id`, `name`) VALUES ('ga', 'Iers');
INSERT INTO `country` (`id`, `name`) VALUES ('id', 'Indonesies');
INSERT INTO `country` (`id`, `name`) VALUES ('ia', 'Interlingua');
INSERT INTO `country` (`id`, `name`) VALUES ('ie', 'Interlingue');
INSERT INTO `country` (`id`, `name`) VALUES ('it', 'Italiaans');
INSERT INTO `country` (`id`, `name`) VALUES ('ja', 'Japannees');
INSERT INTO `country` (`id`, `name`) VALUES ('jv', 'Javaans');
INSERT INTO `country` (`id`, `name`) VALUES ('yi', 'Jiddisj');
INSERT INTO `country` (`id`, `name`) VALUES ('kn', 'Kannada');
INSERT INTO `country` (`id`, `name`) VALUES ('ca', 'Katalaans');
INSERT INTO `country` (`id`, `name`) VALUES ('cu', 'Kerkslawies');
INSERT INTO `country` (`id`, `name`) VALUES ('km', 'Khmer');
INSERT INTO `country` (`id`, `name`) VALUES ('ky', 'Kirgisies');
INSERT INTO `country` (`id`, `name`) VALUES ('tlh', 'Klingon');
INSERT INTO `country` (`id`, `name`) VALUES ('ku', 'Koerdies');
INSERT INTO `country` (`id`, `name`) VALUES ('cop', 'Kopties');
INSERT INTO `country` (`id`, `name`) VALUES ('ko', 'Koreaans');
INSERT INTO `country` (`id`, `name`) VALUES ('kw', 'Kornies');
INSERT INTO `country` (`id`, `name`) VALUES ('hr', 'Kroaties');
INSERT INTO `country` (`id`, `name`) VALUES ('lo', 'Laotanees');
INSERT INTO `country` (`id`, `name`) VALUES ('la', 'Latyn');
INSERT INTO `country` (`id`, `name`) VALUES ('es_419', 'Latyns-Amerikaanse Spaans');
INSERT INTO `country` (`id`, `name`) VALUES ('lv', 'Letties');
INSERT INTO `country` (`id`, `name`) VALUES ('li', 'Limburgs');
INSERT INTO `country` (`id`, `name`) VALUES ('ln', 'Lingala');
INSERT INTO `country` (`id`, `name`) VALUES ('lt', 'Litaus');
INSERT INTO `country` (`id`, `name`) VALUES ('mk', 'Macedonies');
INSERT INTO `country` (`id`, `name`) VALUES ('mr', 'Mahratti');
INSERT INTO `country` (`id`, `name`) VALUES ('ml', 'Malabaars');
INSERT INTO `country` (`id`, `name`) VALUES ('ms', 'Maleisies');
INSERT INTO `country` (`id`, `name`) VALUES ('mg', 'Malgassies');
INSERT INTO `country` (`id`, `name`) VALUES ('mt', 'Maltees');
INSERT INTO `country` (`id`, `name`) VALUES ('gv', 'Manx');
INSERT INTO `country` (`id`, `name`) VALUES ('mas', 'Masai');
INSERT INTO `country` (`id`, `name`) VALUES ('mn', 'Mongalees');
INSERT INTO `country` (`id`, `name`) VALUES ('nl', 'Nederlands');
INSERT INTO `country` (`id`, `name`) VALUES ('ne', 'Nepalees');
INSERT INTO `country` (`id`, `name`) VALUES ('nd', 'Noord-Ndebele');
INSERT INTO `country` (`id`, `name`) VALUES ('no', 'Noors');
INSERT INTO `country` (`id`, `name`) VALUES ('nn', 'Noorweegse Nynorsk');
INSERT INTO `country` (`id`, `name`) VALUES ('oc', 'Occitaans');
INSERT INTO `country` (`id`, `name`) VALUES ('uk', 'Oekraïens');
INSERT INTO `country` (`id`, `name`) VALUES ('ur', 'Oerdoe');
INSERT INTO `country` (`id`, `name`) VALUES ('uz', 'Oesbekies');
INSERT INTO `country` (`id`, `name`) VALUES ('und', 'Onbepaald');
INSERT INTO `country` (`id`, `name`) VALUES ('or', 'Oria');
INSERT INTO `country` (`id`, `name`) VALUES ('pa', 'Pandjabi');
INSERT INTO `country` (`id`, `name`) VALUES ('ps', 'Pasjtoe');
INSERT INTO `country` (`id`, `name`) VALUES ('fa', 'Persies');
INSERT INTO `country` (`id`, `name`) VALUES ('pl', 'Pools');
INSERT INTO `country` (`id`, `name`) VALUES ('pt', 'Portugees');
INSERT INTO `country` (`id`, `name`) VALUES ('ro', 'Roemeens');
INSERT INTO `country` (`id`, `name`) VALUES ('ru', 'Russies');
INSERT INTO `country` (`id`, `name`) VALUES ('sa', 'Sanskrit');
INSERT INTO `country` (`id`, `name`) VALUES ('nso', 'Sepedi');
INSERT INTO `country` (`id`, `name`) VALUES ('sr', 'Serwies');
INSERT INTO `country` (`id`, `name`) VALUES ('sh', 'Serwo-Kroaties');
INSERT INTO `country` (`id`, `name`) VALUES ('sn', 'Shona');
INSERT INTO `country` (`id`, `name`) VALUES ('sd', 'Sindhi');
INSERT INTO `country` (`id`, `name`) VALUES ('si', 'Singalees');
INSERT INTO `country` (`id`, `name`) VALUES ('zh', 'Sjinees');
INSERT INTO `country` (`id`, `name`) VALUES ('sco', 'Skots');
INSERT INTO `country` (`id`, `name`) VALUES ('gd', 'Skots-Gaelies');
INSERT INTO `country` (`id`, `name`) VALUES ('sk', 'Slowaaks');
INSERT INTO `country` (`id`, `name`) VALUES ('sl', 'Sloweens');
INSERT INTO `country` (`id`, `name`) VALUES ('su', 'Soedanees');
INSERT INTO `country` (`id`, `name`) VALUES ('so', 'Somalies');
INSERT INTO `country` (`id`, `name`) VALUES ('es', 'Spaans');
INSERT INTO `country` (`id`, `name`) VALUES ('nr', 'Suid-Ndebele');
INSERT INTO `country` (`id`, `name`) VALUES ('st', 'Suid-Sotho');
INSERT INTO `country` (`id`, `name`) VALUES ('sw', 'Swahili');
INSERT INTO `country` (`id`, `name`) VALUES ('ss', 'Swazi');
INSERT INTO `country` (`id`, `name`) VALUES ('sv', 'Sweeds');
INSERT INTO `country` (`id`, `name`) VALUES ('ta', 'Tamil');
INSERT INTO `country` (`id`, `name`) VALUES ('te', 'Telugees');
INSERT INTO `country` (`id`, `name`) VALUES ('th', 'Thais');
INSERT INTO `country` (`id`, `name`) VALUES ('ti', 'Tigrinya');
INSERT INTO `country` (`id`, `name`) VALUES ('zh_Hant', 'Tradisionele Sjinees');
INSERT INTO `country` (`id`, `name`) VALUES ('cs', 'Tsjeggies');
INSERT INTO `country` (`id`, `name`) VALUES ('ts', 'Tsonga');
INSERT INTO `country` (`id`, `name`) VALUES ('tn', 'Tswana');
INSERT INTO `country` (`id`, `name`) VALUES ('tk', 'Turkmeens');
INSERT INTO `country` (`id`, `name`) VALUES ('tr', 'Turks');
INSERT INTO `country` (`id`, `name`) VALUES ('tw', 'Twi');
INSERT INTO `country` (`id`, `name`) VALUES ('ug', 'Uighoers');
INSERT INTO `country` (`id`, `name`) VALUES ('mul', 'Veelvuldige tale');
INSERT INTO `country` (`id`, `name`) VALUES ('ve', 'Venda');
INSERT INTO `country` (`id`, `name`) VALUES ('zh_Hans', 'Vereenvoudigde Sjinees');
INSERT INTO `country` (`id`, `name`) VALUES ('vi', 'Viëtnamees');
INSERT INTO `country` (`id`, `name`) VALUES ('nl_BE', 'Vlaams');
INSERT INTO `country` (`id`, `name`) VALUES ('cy', 'Wallies');
INSERT INTO `country` (`id`, `name`) VALUES ('be', 'Wit-Russies');
INSERT INTO `country` (`id`, `name`) VALUES ('xh', 'Xhosa');
INSERT INTO `country` (`id`, `name`) VALUES ('is', 'Yslands');
INSERT INTO `country` (`id`, `name`) VALUES ('zu', 'Zoeloe');
INSERT INTO `country` (`id`, `name`) VALUES ('kru', 'kru');
