CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('ab', 'ابقازیان');
INSERT INTO [country] ([id], [name]) VALUES ('ur', 'اردو');
INSERT INTO [country] ([id], [name]) VALUES ('hy', 'ارمینی');
INSERT INTO [country] ([id], [name]) VALUES ('uz', 'ازبیک');
INSERT INTO [country] ([id], [name]) VALUES ('et', 'اسٹونين');
INSERT INTO [country] ([id], [name]) VALUES ('it', 'اطالوی');
INSERT INTO [country] ([id], [name]) VALUES ('ig', 'اِگبو');
INSERT INTO [country] ([id], [name]) VALUES ('sq', 'البانی');
INSERT INTO [country] ([id], [name]) VALUES ('en_US', 'امریکی انگریزی');
INSERT INTO [country] ([id], [name]) VALUES ('am', 'امہاری');
INSERT INTO [country] ([id], [name]) VALUES ('ia', 'انٹرلنگوی');
INSERT INTO [country] ([id], [name]) VALUES ('id', 'انڈونيثيائی');
INSERT INTO [country] ([id], [name]) VALUES ('en', 'انگريزی');
INSERT INTO [country] ([id], [name]) VALUES ('or', 'اورِیا');
INSERT INTO [country] ([id], [name]) VALUES ('os', 'اوسیٹک');
INSERT INTO [country] ([id], [name]) VALUES ('efi', 'ایفِک');
INSERT INTO [country] ([id], [name]) VALUES ('ay', 'ایمارا');
INSERT INTO [country] ([id], [name]) VALUES ('eo', 'ايسپرانٹو');
INSERT INTO [country] ([id], [name]) VALUES ('af', 'ايفريکانز');
INSERT INTO [country] ([id], [name]) VALUES ('az', 'آزربائیجانی');
INSERT INTO [country] ([id], [name]) VALUES ('as', 'آسامی');
INSERT INTO [country] ([id], [name]) VALUES ('de_AT', 'آسٹریائی جرمن');
INSERT INTO [country] ([id], [name]) VALUES ('en_AU', 'آسٹریلیائی انگریزی');
INSERT INTO [country] ([id], [name]) VALUES ('oc', 'آکيٹانی');
INSERT INTO [country] ([id], [name]) VALUES ('es_ES', 'آئبریائی ہسپانوی');
INSERT INTO [country] ([id], [name]) VALUES ('is', 'آئس لینڈ کا باشندہ');
INSERT INTO [country] ([id], [name]) VALUES ('ga', 'آئيرِش');
INSERT INTO [country] ([id], [name]) VALUES ('eu', 'باسکی');
INSERT INTO [country] ([id], [name]) VALUES ('pt_BR', 'برازیلی پرتگالی');
INSERT INTO [country] ([id], [name]) VALUES ('en_GB', 'برطانوی انگریزی');
INSERT INTO [country] ([id], [name]) VALUES ('my', 'برمی');
INSERT INTO [country] ([id], [name]) VALUES ('br', 'برِیٹن');
INSERT INTO [country] ([id], [name]) VALUES ('bg', 'بلغاری');
INSERT INTO [country] ([id], [name]) VALUES ('bn', 'بنگالی');
INSERT INTO [country] ([id], [name]) VALUES ('bs', 'بوسنی');
INSERT INTO [country] ([id], [name]) VALUES ('bh', 'بِہاری');
INSERT INTO [country] ([id], [name]) VALUES ('be', 'بيلاروسی');
INSERT INTO [country] ([id], [name]) VALUES ('pt', 'پُرتگالی');
INSERT INTO [country] ([id], [name]) VALUES ('pt_PT', 'پرتگالی (پرتگال)');
INSERT INTO [country] ([id], [name]) VALUES ('ps', 'پشتو');
INSERT INTO [country] ([id], [name]) VALUES ('pa', 'پنجابی');
INSERT INTO [country] ([id], [name]) VALUES ('pl', 'پولستانی');
INSERT INTO [country] ([id], [name]) VALUES ('tt', 'تاتار');
INSERT INTO [country] ([id], [name]) VALUES ('tg', 'تاجک');
INSERT INTO [country] ([id], [name]) VALUES ('ty', 'تاہیتی');
INSERT INTO [country] ([id], [name]) VALUES ('bo', 'تبتی');
INSERT INTO [country] ([id], [name]) VALUES ('tk', 'ترکمان');
INSERT INTO [country] ([id], [name]) VALUES ('tr', 'ترکی');
INSERT INTO [country] ([id], [name]) VALUES ('ta', 'تمل');
INSERT INTO [country] ([id], [name]) VALUES ('te', 'تیلگو');
INSERT INTO [country] ([id], [name]) VALUES ('th', 'تھائی');
INSERT INTO [country] ([id], [name]) VALUES ('ti', 'ٹگرینیا');
INSERT INTO [country] ([id], [name]) VALUES ('tpi', 'ٹوک پِسِن');
INSERT INTO [country] ([id], [name]) VALUES ('to', 'ٹونگا');
INSERT INTO [country] ([id], [name]) VALUES ('tet', 'ٹیٹم');
INSERT INTO [country] ([id], [name]) VALUES ('fil', 'ٹيگالاگی');
INSERT INTO [country] ([id], [name]) VALUES ('ja', 'جاپانی');
INSERT INTO [country] ([id], [name]) VALUES ('ka', 'جارجی');
INSERT INTO [country] ([id], [name]) VALUES ('jv', 'جاوی');
INSERT INTO [country] ([id], [name]) VALUES ('de', 'جرمن');
INSERT INTO [country] ([id], [name]) VALUES ('st', 'جنوبی سوتھو');
INSERT INTO [country] ([id], [name]) VALUES ('zh', 'چینی');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hans', 'چینی (آسان کردہ)');
INSERT INTO [country] ([id], [name]) VALUES ('cs', 'چيک');
INSERT INTO [country] ([id], [name]) VALUES ('nl', 'ڈچ');
INSERT INTO [country] ([id], [name]) VALUES ('dv', 'ڈیویہی');
INSERT INTO [country] ([id], [name]) VALUES ('da', 'ڈينش');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hant', 'روایتی چینی');
INSERT INTO [country] ([id], [name]) VALUES ('ru', 'روسی');
INSERT INTO [country] ([id], [name]) VALUES ('rm', 'رومانش');
INSERT INTO [country] ([id], [name]) VALUES ('ro', 'رومنی');
INSERT INTO [country] ([id], [name]) VALUES ('rn', 'رونڈی');
INSERT INTO [country] ([id], [name]) VALUES ('zu', 'زولو');
INSERT INTO [country] ([id], [name]) VALUES ('ts', 'زونگا');
INSERT INTO [country] ([id], [name]) VALUES ('xh', 'ژوسا');
INSERT INTO [country] ([id], [name]) VALUES ('dz', 'ژونگکھا');
INSERT INTO [country] ([id], [name]) VALUES ('sm', 'ساموآن');
INSERT INTO [country] ([id], [name]) VALUES ('sg', 'سانگو');
INSERT INTO [country] ([id], [name]) VALUES ('sh', 'سربو-کروئیشین');
INSERT INTO [country] ([id], [name]) VALUES ('gd', 'سکاٹ گيلِک');
INSERT INTO [country] ([id], [name]) VALUES ('sk', 'سلوواک');
INSERT INTO [country] ([id], [name]) VALUES ('sl', 'سلووینیائی');
INSERT INTO [country] ([id], [name]) VALUES ('sd', 'سندھی');
INSERT INTO [country] ([id], [name]) VALUES ('su', 'سنڈانیز');
INSERT INTO [country] ([id], [name]) VALUES ('sa', 'سَنسکرِت');
INSERT INTO [country] ([id], [name]) VALUES ('si', 'سنہالا');
INSERT INTO [country] ([id], [name]) VALUES ('ss', 'سواتی');
INSERT INTO [country] ([id], [name]) VALUES ('sw', 'سواحلی');
INSERT INTO [country] ([id], [name]) VALUES ('tn', 'سوانا');
INSERT INTO [country] ([id], [name]) VALUES ('sv', 'سویڈش');
INSERT INTO [country] ([id], [name]) VALUES ('gsw', 'سوئس جرمن');
INSERT INTO [country] ([id], [name]) VALUES ('fr_CH', 'سوئس فرینچ');
INSERT INTO [country] ([id], [name]) VALUES ('de_CH', 'سوئس ہائی جرمن');
INSERT INTO [country] ([id], [name]) VALUES ('nd', 'شمالی دبیل');
INSERT INTO [country] ([id], [name]) VALUES ('se', 'شمالی سامی');
INSERT INTO [country] ([id], [name]) VALUES ('nso', 'شمالی سوتھو');
INSERT INTO [country] ([id], [name]) VALUES ('sn', 'شونا');
INSERT INTO [country] ([id], [name]) VALUES ('sr', 'صربی');
INSERT INTO [country] ([id], [name]) VALUES ('so', 'صومالی');
INSERT INTO [country] ([id], [name]) VALUES ('he', 'عبرانی');
INSERT INTO [country] ([id], [name]) VALUES ('ar', 'عربی');
INSERT INTO [country] ([id], [name]) VALUES ('fa', 'فارسی');
INSERT INTO [country] ([id], [name]) VALUES ('fj', 'فجی کا باشندہ');
INSERT INTO [country] ([id], [name]) VALUES ('fr', 'فرانسيسی');
INSERT INTO [country] ([id], [name]) VALUES ('nl_BE', 'فلیمِش');
INSERT INTO [country] ([id], [name]) VALUES ('fi', 'فنّنِش');
INSERT INTO [country] ([id], [name]) VALUES ('fo', 'فیروئیز');
INSERT INTO [country] ([id], [name]) VALUES ('kk', 'قزاخ');
INSERT INTO [country] ([id], [name]) VALUES ('ca', 'کاٹالانين');
INSERT INTO [country] ([id], [name]) VALUES ('hr', 'کراتی');
INSERT INTO [country] ([id], [name]) VALUES ('ku', 'کردش');
INSERT INTO [country] ([id], [name]) VALUES ('ky', 'کرغیزی');
INSERT INTO [country] ([id], [name]) VALUES ('ks', 'کشمیری');
INSERT INTO [country] ([id], [name]) VALUES ('tlh', 'کلنگان');
INSERT INTO [country] ([id], [name]) VALUES ('km', 'کمبوڈیَن');
INSERT INTO [country] ([id], [name]) VALUES ('kn', 'کنّاڈا');
INSERT INTO [country] ([id], [name]) VALUES ('ko', 'کورين');
INSERT INTO [country] ([id], [name]) VALUES ('qu', 'کویچوآ');
INSERT INTO [country] ([id], [name]) VALUES ('zxx', 'کوئی لسانی مواد نہیں');
INSERT INTO [country] ([id], [name]) VALUES ('rw', 'کینیاروانڈا');
INSERT INTO [country] ([id], [name]) VALUES ('en_CA', 'کینیڈین انگریزی');
INSERT INTO [country] ([id], [name]) VALUES ('fr_CA', 'کینیڈین فرانسیسی');
INSERT INTO [country] ([id], [name]) VALUES ('gn', 'گُارانی');
INSERT INTO [country] ([id], [name]) VALUES ('gl', 'گاليشيائی');
INSERT INTO [country] ([id], [name]) VALUES ('gu', 'گجراتی');
INSERT INTO [country] ([id], [name]) VALUES ('es_419', 'لاطینی امریکی ہسپانوی');
INSERT INTO [country] ([id], [name]) VALUES ('la', 'لاطينی');
INSERT INTO [country] ([id], [name]) VALUES ('lo', 'لاؤشِیَن');
INSERT INTO [country] ([id], [name]) VALUES ('lt', 'لتھُواینین');
INSERT INTO [country] ([id], [name]) VALUES ('lb', 'لگژمبرگ کا باشندہ');
INSERT INTO [country] ([id], [name]) VALUES ('ln', 'لِنگَلا');
INSERT INTO [country] ([id], [name]) VALUES ('lv', 'ليٹوين');
INSERT INTO [country] ([id], [name]) VALUES ('ms', 'مالائی');
INSERT INTO [country] ([id], [name]) VALUES ('ml', 'مالايالم');
INSERT INTO [country] ([id], [name]) VALUES ('mt', 'مالٹی');
INSERT INTO [country] ([id], [name]) VALUES ('mi', 'ماؤری');
INSERT INTO [country] ([id], [name]) VALUES ('mr', 'مراٹهی');
INSERT INTO [country] ([id], [name]) VALUES ('fy', 'مغربی فریسیئن');
INSERT INTO [country] ([id], [name]) VALUES ('mk', 'مقدونيائی');
INSERT INTO [country] ([id], [name]) VALUES ('mg', 'ملاگاسی');
INSERT INTO [country] ([id], [name]) VALUES ('mn', 'منگؤلی');
INSERT INTO [country] ([id], [name]) VALUES ('nb', 'نارویجین بوکمل');
INSERT INTO [country] ([id], [name]) VALUES ('no', 'نارويجين');
INSERT INTO [country] ([id], [name]) VALUES ('und', 'نامعلوم زبان');
INSERT INTO [country] ([id], [name]) VALUES ('nn', 'نورویجینی (نینورسک)');
INSERT INTO [country] ([id], [name]) VALUES ('ny', 'نیانجا');
INSERT INTO [country] ([id], [name]) VALUES ('ne', 'نيپالی');
INSERT INTO [country] ([id], [name]) VALUES ('wo', 'وولوف');
INSERT INTO [country] ([id], [name]) VALUES ('vi', 'ویتنامی');
INSERT INTO [country] ([id], [name]) VALUES ('cy', 'ویلش');
INSERT INTO [country] ([id], [name]) VALUES ('ve', 'وینڈا');
INSERT INTO [country] ([id], [name]) VALUES ('es', 'ہسپانوی');
INSERT INTO [country] ([id], [name]) VALUES ('hi', 'ہندی');
INSERT INTO [country] ([id], [name]) VALUES ('hu', 'ہنگیرین');
INSERT INTO [country] ([id], [name]) VALUES ('haw', 'ہوائی کا باشندہ');
INSERT INTO [country] ([id], [name]) VALUES ('ha', 'ہؤسا');
INSERT INTO [country] ([id], [name]) VALUES ('ht', 'ہیتی');
INSERT INTO [country] ([id], [name]) VALUES ('yo', 'یوروبا');
INSERT INTO [country] ([id], [name]) VALUES ('uk', 'یوکرینیائی');
INSERT INTO [country] ([id], [name]) VALUES ('ug', 'یوئگہر');
INSERT INTO [country] ([id], [name]) VALUES ('el', 'يونانی');
