CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('to', 'Тонга');
INSERT INTO [country] ([id], [name]) VALUES ('ab', 'абхазька');
INSERT INTO [country] ([id], [name]) VALUES ('awa', 'авадхі');
INSERT INTO [country] ([id], [name]) VALUES ('av', 'аварська');
INSERT INTO [country] ([id], [name]) VALUES ('ae', 'авестійська');
INSERT INTO [country] ([id], [name]) VALUES ('aus', 'австралійські мови');
INSERT INTO [country] ([id], [name]) VALUES ('map', 'австронезійська мова');
INSERT INTO [country] ([id], [name]) VALUES ('ada', 'адангме');
INSERT INTO [country] ([id], [name]) VALUES ('ady', 'адигейська');
INSERT INTO [country] ([id], [name]) VALUES ('az', 'азербайджанська');
INSERT INTO [country] ([id], [name]) VALUES ('ay', 'аймара');
INSERT INTO [country] ([id], [name]) VALUES ('ain', 'айнська');
INSERT INTO [country] ([id], [name]) VALUES ('ak', 'акан');
INSERT INTO [country] ([id], [name]) VALUES ('akk', 'аккадська');
INSERT INTO [country] ([id], [name]) VALUES ('sq', 'албанська');
INSERT INTO [country] ([id], [name]) VALUES ('alg', 'алгонкінські мови');
INSERT INTO [country] ([id], [name]) VALUES ('ale', 'алеутська');
INSERT INTO [country] ([id], [name]) VALUES ('tut', 'алтайська мова');
INSERT INTO [country] ([id], [name]) VALUES ('am', 'амхарська');
INSERT INTO [country] ([id], [name]) VALUES ('cpe', 'англо-креольські та піджінізовані англійські мови');
INSERT INTO [country] ([id], [name]) VALUES ('en', 'англійська');
INSERT INTO [country] ([id], [name]) VALUES ('en_US', 'англійська США');
INSERT INTO [country] ([id], [name]) VALUES ('en_AU', 'англійська австралійська');
INSERT INTO [country] ([id], [name]) VALUES ('en_GB', 'англійська британська');
INSERT INTO [country] ([id], [name]) VALUES ('en_CA', 'англійська канадська');
INSERT INTO [country] ([id], [name]) VALUES ('anp', 'ангіка');
INSERT INTO [country] ([id], [name]) VALUES ('apa', 'апачі мови');
INSERT INTO [country] ([id], [name]) VALUES ('ar', 'арабська');
INSERT INTO [country] ([id], [name]) VALUES ('arw', 'аравакська');
INSERT INTO [country] ([id], [name]) VALUES ('an', 'арагонська');
INSERT INTO [country] ([id], [name]) VALUES ('arc', 'арамейська');
INSERT INTO [country] ([id], [name]) VALUES ('arp', 'арапахо');
INSERT INTO [country] ([id], [name]) VALUES ('arn', 'арауканська');
INSERT INTO [country] ([id], [name]) VALUES ('rup', 'арумунська');
INSERT INTO [country] ([id], [name]) VALUES ('as', 'ассамська');
INSERT INTO [country] ([id], [name]) VALUES ('ast', 'астурська');
INSERT INTO [country] ([id], [name]) VALUES ('ath', 'атапаскські мови');
INSERT INTO [country] ([id], [name]) VALUES ('cch', 'атсам');
INSERT INTO [country] ([id], [name]) VALUES ('aa', 'афарська');
INSERT INTO [country] ([id], [name]) VALUES ('af', 'африкаанс');
INSERT INTO [country] ([id], [name]) VALUES ('afh', 'африхілі');
INSERT INTO [country] ([id], [name]) VALUES ('afa', 'афро-азійська мова');
INSERT INTO [country] ([id], [name]) VALUES ('ace', 'ачехська');
INSERT INTO [country] ([id], [name]) VALUES ('ach', 'ачолі');
INSERT INTO [country] ([id], [name]) VALUES ('bat', 'балтійська мова');
INSERT INTO [country] ([id], [name]) VALUES ('bal', 'балучі');
INSERT INTO [country] ([id], [name]) VALUES ('ban', 'балійська');
INSERT INTO [country] ([id], [name]) VALUES ('bm', 'бамбара');
INSERT INTO [country] ([id], [name]) VALUES ('bai', 'бамілеке мови');
INSERT INTO [country] ([id], [name]) VALUES ('bad', 'банда');
INSERT INTO [country] ([id], [name]) VALUES ('bnt', 'банту');
INSERT INTO [country] ([id], [name]) VALUES ('bas', 'баса');
INSERT INTO [country] ([id], [name]) VALUES ('eu', 'басків');
INSERT INTO [country] ([id], [name]) VALUES ('btk', 'батак');
INSERT INTO [country] ([id], [name]) VALUES ('ba', 'башкирська');
INSERT INTO [country] ([id], [name]) VALUES ('bej', 'беджа');
INSERT INTO [country] ([id], [name]) VALUES ('bem', 'бемба');
INSERT INTO [country] ([id], [name]) VALUES ('bn', 'бенгальська');
INSERT INTO [country] ([id], [name]) VALUES ('ber', 'берберська');
INSERT INTO [country] ([id], [name]) VALUES ('byn', 'блін');
INSERT INTO [country] ([id], [name]) VALUES ('zbl', 'блісса мова');
INSERT INTO [country] ([id], [name]) VALUES ('bg', 'болгарська');
INSERT INTO [country] ([id], [name]) VALUES ('bs', 'боснійська');
INSERT INTO [country] ([id], [name]) VALUES ('bra', 'брадж');
INSERT INTO [country] ([id], [name]) VALUES ('br', 'бретонська');
INSERT INTO [country] ([id], [name]) VALUES ('bug', 'бугійська');
INSERT INTO [country] ([id], [name]) VALUES ('bua', 'бурятська');
INSERT INTO [country] ([id], [name]) VALUES ('bho', 'бходжпурі');
INSERT INTO [country] ([id], [name]) VALUES ('bik', 'бікольська');
INSERT INTO [country] ([id], [name]) VALUES ('be', 'білоруська');
INSERT INTO [country] ([id], [name]) VALUES ('bin', 'біні');
INSERT INTO [country] ([id], [name]) VALUES ('my', 'бірманська');
INSERT INTO [country] ([id], [name]) VALUES ('bi', 'біслама');
INSERT INTO [country] ([id], [name]) VALUES ('bh', 'біхарі');
INSERT INTO [country] ([id], [name]) VALUES ('vi', 'вʼєтнамська');
INSERT INTO [country] ([id], [name]) VALUES ('wak', 'вакашські мови');
INSERT INTO [country] ([id], [name]) VALUES ('wal', 'валамо');
INSERT INTO [country] ([id], [name]) VALUES ('wa', 'валлонська');
INSERT INTO [country] ([id], [name]) VALUES ('cy', 'валлійська');
INSERT INTO [country] ([id], [name]) VALUES ('war', 'варай');
INSERT INTO [country] ([id], [name]) VALUES ('was', 'вашо');
INSERT INTO [country] ([id], [name]) VALUES ('vai', 'ваї');
INSERT INTO [country] ([id], [name]) VALUES ('ve', 'венда');
INSERT INTO [country] ([id], [name]) VALUES ('hsb', 'верхньолужицька');
INSERT INTO [country] ([id], [name]) VALUES ('de_CH', 'верхньонімецька швейцарська');
INSERT INTO [country] ([id], [name]) VALUES ('vot', 'водська');
INSERT INTO [country] ([id], [name]) VALUES ('vo', 'волап’юк');
INSERT INTO [country] ([id], [name]) VALUES ('wo', 'волоф');
INSERT INTO [country] ([id], [name]) VALUES ('hy', 'вірменська');
INSERT INTO [country] ([id], [name]) VALUES ('gaa', 'га');
INSERT INTO [country] ([id], [name]) VALUES ('haw', 'гавайська');
INSERT INTO [country] ([id], [name]) VALUES ('gd', 'гаельська');
INSERT INTO [country] ([id], [name]) VALUES ('gay', 'гайо');
INSERT INTO [country] ([id], [name]) VALUES ('gl', 'галісійська');
INSERT INTO [country] ([id], [name]) VALUES ('lg', 'ганда');
INSERT INTO [country] ([id], [name]) VALUES ('ht', 'гаїтянська');
INSERT INTO [country] ([id], [name]) VALUES ('gba', 'гбайя');
INSERT INTO [country] ([id], [name]) VALUES ('hz', 'гереро');
INSERT INTO [country] ([id], [name]) VALUES ('gem', 'германська мова');
INSERT INTO [country] ([id], [name]) VALUES ('nl', 'голландська');
INSERT INTO [country] ([id], [name]) VALUES ('gon', 'гонді');
INSERT INTO [country] ([id], [name]) VALUES ('gor', 'горонтало');
INSERT INTO [country] ([id], [name]) VALUES ('got', 'готська');
INSERT INTO [country] ([id], [name]) VALUES ('grb', 'гребо');
INSERT INTO [country] ([id], [name]) VALUES ('el', 'грецька');
INSERT INTO [country] ([id], [name]) VALUES ('ka', 'грузинська');
INSERT INTO [country] ([id], [name]) VALUES ('gn', 'гуарані');
INSERT INTO [country] ([id], [name]) VALUES ('gu', 'гуджараті');
INSERT INTO [country] ([id], [name]) VALUES ('gez', 'гєез');
INSERT INTO [country] ([id], [name]) VALUES ('gil', 'гільбертська');
INSERT INTO [country] ([id], [name]) VALUES ('hi', 'гінді');
INSERT INTO [country] ([id], [name]) VALUES ('ang', 'давньоанглійська');
INSERT INTO [country] ([id], [name]) VALUES ('goh', 'давньоверхньонімецька');
INSERT INTO [country] ([id], [name]) VALUES ('grc', 'давньогрецька');
INSERT INTO [country] ([id], [name]) VALUES ('non', 'давньонорвезька');
INSERT INTO [country] ([id], [name]) VALUES ('peo', 'давньоперська');
INSERT INTO [country] ([id], [name]) VALUES ('pro', 'давньопровансальська');
INSERT INTO [country] ([id], [name]) VALUES ('fro', 'давньофранцузька');
INSERT INTO [country] ([id], [name]) VALUES ('egy', 'давньоєгипетська');
INSERT INTO [country] ([id], [name]) VALUES ('sga', 'давньоірландська');
INSERT INTO [country] ([id], [name]) VALUES ('dak', 'дакота');
INSERT INTO [country] ([id], [name]) VALUES ('da', 'данська');
INSERT INTO [country] ([id], [name]) VALUES ('dar', 'даргінська');
INSERT INTO [country] ([id], [name]) VALUES ('day', 'даяк');
INSERT INTO [country] ([id], [name]) VALUES ('mul', 'декілька мов');
INSERT INTO [country] ([id], [name]) VALUES ('del', 'делаварська');
INSERT INTO [country] ([id], [name]) VALUES ('dz', 'дзонг-ке');
INSERT INTO [country] ([id], [name]) VALUES ('dgr', 'догрибська');
INSERT INTO [country] ([id], [name]) VALUES ('doi', 'догрі');
INSERT INTO [country] ([id], [name]) VALUES ('dra', 'дравідійська мова');
INSERT INTO [country] ([id], [name]) VALUES ('dua', 'дуала');
INSERT INTO [country] ([id], [name]) VALUES ('dv', 'дівехі');
INSERT INTO [country] ([id], [name]) VALUES ('din', 'дінка');
INSERT INTO [country] ([id], [name]) VALUES ('dyu', 'діула');
INSERT INTO [country] ([id], [name]) VALUES ('ee', 'еве');
INSERT INTO [country] ([id], [name]) VALUES ('ewo', 'евондо');
INSERT INTO [country] ([id], [name]) VALUES ('eka', 'екаджук');
INSERT INTO [country] ([id], [name]) VALUES ('elx', 'еламська');
INSERT INTO [country] ([id], [name]) VALUES ('myv', 'ерзя');
INSERT INTO [country] ([id], [name]) VALUES ('eo', 'есперанто');
INSERT INTO [country] ([id], [name]) VALUES ('et', 'естонська');
INSERT INTO [country] ([id], [name]) VALUES ('efi', 'ефік');
INSERT INTO [country] ([id], [name]) VALUES ('zza', 'зазакі');
INSERT INTO [country] ([id], [name]) VALUES ('znd', 'занде');
INSERT INTO [country] ([id], [name]) VALUES ('zen', 'зенага');
INSERT INTO [country] ([id], [name]) VALUES ('sgn', 'знакові мови');
INSERT INTO [country] ([id], [name]) VALUES ('zu', 'зулуська');
INSERT INTO [country] ([id], [name]) VALUES ('zun', 'зуньї');
INSERT INTO [country] ([id], [name]) VALUES ('yo', 'йоруба');
INSERT INTO [country] ([id], [name]) VALUES ('kaj', 'йю');
INSERT INTO [country] ([id], [name]) VALUES ('kbd', 'кабардинська');
INSERT INTO [country] ([id], [name]) VALUES ('kab', 'кабильська');
INSERT INTO [country] ([id], [name]) VALUES ('cau', 'кавказька мова');
INSERT INTO [country] ([id], [name]) VALUES ('kaw', 'каві');
INSERT INTO [country] ([id], [name]) VALUES ('cad', 'каддо');
INSERT INTO [country] ([id], [name]) VALUES ('kk', 'казахська');
INSERT INTO [country] ([id], [name]) VALUES ('kl', 'калааллісут');
INSERT INTO [country] ([id], [name]) VALUES ('xal', 'калмицька');
INSERT INTO [country] ([id], [name]) VALUES ('kam', 'камба');
INSERT INTO [country] ([id], [name]) VALUES ('kn', 'каннада');
INSERT INTO [country] ([id], [name]) VALUES ('kr', 'канурі');
INSERT INTO [country] ([id], [name]) VALUES ('kaa', 'каракалпацька');
INSERT INTO [country] ([id], [name]) VALUES ('krc', 'карачаєво-балкарська');
INSERT INTO [country] ([id], [name]) VALUES ('krl', 'карельська');
INSERT INTO [country] ([id], [name]) VALUES ('kar', 'каренська');
INSERT INTO [country] ([id], [name]) VALUES ('car', 'карібська');
INSERT INTO [country] ([id], [name]) VALUES ('ca', 'каталонська');
INSERT INTO [country] ([id], [name]) VALUES ('kac', 'качін');
INSERT INTO [country] ([id], [name]) VALUES ('ks', 'кашмірська');
INSERT INTO [country] ([id], [name]) VALUES ('csb', 'кашубська');
INSERT INTO [country] ([id], [name]) VALUES ('cel', 'кельтська мова');
INSERT INTO [country] ([id], [name]) VALUES ('qu', 'кечуа');
INSERT INTO [country] ([id], [name]) VALUES ('ky', 'киргизька');
INSERT INTO [country] ([id], [name]) VALUES ('zh', 'китайська');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hans', 'китайська спрощена');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hant', 'китайська традиційна');
INSERT INTO [country] ([id], [name]) VALUES ('sit', 'китайсько-тибетські мови');
INSERT INTO [country] ([id], [name]) VALUES ('tlh', 'клінгон');
INSERT INTO [country] ([id], [name]) VALUES ('khi', 'койсанські мови');
INSERT INTO [country] ([id], [name]) VALUES ('kv', 'комі');
INSERT INTO [country] ([id], [name]) VALUES ('kok', 'конкані');
INSERT INTO [country] ([id], [name]) VALUES ('kg', 'конґолезька');
INSERT INTO [country] ([id], [name]) VALUES ('cop', 'коптська');
INSERT INTO [country] ([id], [name]) VALUES ('ko', 'корейська');
INSERT INTO [country] ([id], [name]) VALUES ('kw', 'корнійська');
INSERT INTO [country] ([id], [name]) VALUES ('kfo', 'коро');
INSERT INTO [country] ([id], [name]) VALUES ('co', 'корсиканська');
INSERT INTO [country] ([id], [name]) VALUES ('root', 'корінь');
INSERT INTO [country] ([id], [name]) VALUES ('kos', 'косрае');
INSERT INTO [country] ([id], [name]) VALUES ('kpe', 'кпеллє');
INSERT INTO [country] ([id], [name]) VALUES ('crp', 'креольські та піджінізовані мови');
INSERT INTO [country] ([id], [name]) VALUES ('crh', 'кримськотатарська');
INSERT INTO [country] ([id], [name]) VALUES ('kro', 'кру');
INSERT INTO [country] ([id], [name]) VALUES ('cr', 'крі');
INSERT INTO [country] ([id], [name]) VALUES ('mus', 'крік');
INSERT INTO [country] ([id], [name]) VALUES ('kum', 'кумицька');
INSERT INTO [country] ([id], [name]) VALUES ('kj', 'кунама');
INSERT INTO [country] ([id], [name]) VALUES ('ku', 'курдська');
INSERT INTO [country] ([id], [name]) VALUES ('kru', 'курукх');
INSERT INTO [country] ([id], [name]) VALUES ('kut', 'кутенаї');
INSERT INTO [country] ([id], [name]) VALUES ('gwi', 'кучін');
INSERT INTO [country] ([id], [name]) VALUES ('cus', 'кушітська мова');
INSERT INTO [country] ([id], [name]) VALUES ('kha', 'кхасі');
INSERT INTO [country] ([id], [name]) VALUES ('km', 'кхмерська');
INSERT INTO [country] ([id], [name]) VALUES ('xh', 'кхоса');
INSERT INTO [country] ([id], [name]) VALUES ('ki', 'кікуйю');
INSERT INTO [country] ([id], [name]) VALUES ('kmb', 'кімбунду');
INSERT INTO [country] ([id], [name]) VALUES ('rw', 'кіньяруанда');
INSERT INTO [country] ([id], [name]) VALUES ('lad', 'ладіно');
INSERT INTO [country] ([id], [name]) VALUES ('lam', 'ламба');
INSERT INTO [country] ([id], [name]) VALUES ('lah', 'ланда');
INSERT INTO [country] ([id], [name]) VALUES ('lo', 'лаоська');
INSERT INTO [country] ([id], [name]) VALUES ('lv', 'латвійська');
INSERT INTO [country] ([id], [name]) VALUES ('es_419', 'латиноамериканська іспанська');
INSERT INTO [country] ([id], [name]) VALUES ('la', 'латинська');
INSERT INTO [country] ([id], [name]) VALUES ('lez', 'лезгінська');
INSERT INTO [country] ([id], [name]) VALUES ('lt', 'литовська');
INSERT INTO [country] ([id], [name]) VALUES ('jbo', 'ложбан');
INSERT INTO [country] ([id], [name]) VALUES ('loz', 'лозі');
INSERT INTO [country] ([id], [name]) VALUES ('lu', 'луба-катанга');
INSERT INTO [country] ([id], [name]) VALUES ('lua', 'луба-лулуа');
INSERT INTO [country] ([id], [name]) VALUES ('wen', 'лужицькі мови');
INSERT INTO [country] ([id], [name]) VALUES ('lun', 'лунда');
INSERT INTO [country] ([id], [name]) VALUES ('luo', 'луо');
INSERT INTO [country] ([id], [name]) VALUES ('lus', 'лушей');
INSERT INTO [country] ([id], [name]) VALUES ('lui', 'луїсеньо');
INSERT INTO [country] ([id], [name]) VALUES ('lb', 'люксембурзька');
INSERT INTO [country] ([id], [name]) VALUES ('li', 'лімбургійська');
INSERT INTO [country] ([id], [name]) VALUES ('ln', 'лінгала');
INSERT INTO [country] ([id], [name]) VALUES ('moh', 'магавк');
INSERT INTO [country] ([id], [name]) VALUES ('mag', 'магадхі');
INSERT INTO [country] ([id], [name]) VALUES ('mad', 'мадурська');
INSERT INTO [country] ([id], [name]) VALUES ('mai', 'майтхілі');
INSERT INTO [country] ([id], [name]) VALUES ('myn', 'майя мови');
INSERT INTO [country] ([id], [name]) VALUES ('mak', 'макасарська');
INSERT INTO [country] ([id], [name]) VALUES ('mk', 'македонська');
INSERT INTO [country] ([id], [name]) VALUES ('mg', 'малагасійська');
INSERT INTO [country] ([id], [name]) VALUES ('ms', 'малайська');
INSERT INTO [country] ([id], [name]) VALUES ('ml', 'малайялам');
INSERT INTO [country] ([id], [name]) VALUES ('mt', 'мальтійська');
INSERT INTO [country] ([id], [name]) VALUES ('mdr', 'мандарська');
INSERT INTO [country] ([id], [name]) VALUES ('man', 'мандінго');
INSERT INTO [country] ([id], [name]) VALUES ('mno', 'манобо мови');
INSERT INTO [country] ([id], [name]) VALUES ('mnc', 'манчжурська');
INSERT INTO [country] ([id], [name]) VALUES ('mni', 'маніпурі');
INSERT INTO [country] ([id], [name]) VALUES ('mi', 'маорі');
INSERT INTO [country] ([id], [name]) VALUES ('mr', 'маратхі');
INSERT INTO [country] ([id], [name]) VALUES ('mwr', 'марварі');
INSERT INTO [country] ([id], [name]) VALUES ('mh', 'маршалльська');
INSERT INTO [country] ([id], [name]) VALUES ('chm', 'марійська');
INSERT INTO [country] ([id], [name]) VALUES ('mas', 'масаї');
INSERT INTO [country] ([id], [name]) VALUES ('men', 'менде');
INSERT INTO [country] ([id], [name]) VALUES ('gv', 'менкська');
INSERT INTO [country] ([id], [name]) VALUES ('mdf', 'мокша');
INSERT INTO [country] ([id], [name]) VALUES ('mo', 'молдавська');
INSERT INTO [country] ([id], [name]) VALUES ('mkh', 'мон-кхмерські мови');
INSERT INTO [country] ([id], [name]) VALUES ('lol', 'монго');
INSERT INTO [country] ([id], [name]) VALUES ('mn', 'монгольська');
INSERT INTO [country] ([id], [name]) VALUES ('mos', 'моссі');
INSERT INTO [country] ([id], [name]) VALUES ('mun', 'мунда мови');
INSERT INTO [country] ([id], [name]) VALUES ('mic', 'мікмак');
INSERT INTO [country] ([id], [name]) VALUES ('min', 'мінангкабау');
INSERT INTO [country] ([id], [name]) VALUES ('mwl', 'мірандська');
INSERT INTO [country] ([id], [name]) VALUES ('nv', 'навахо');
INSERT INTO [country] ([id], [name]) VALUES ('na', 'науру');
INSERT INTO [country] ([id], [name]) VALUES ('nah', 'нахуатль');
INSERT INTO [country] ([id], [name]) VALUES ('nr', 'ндебелє південна');
INSERT INTO [country] ([id], [name]) VALUES ('nd', 'ндебелє північна');
INSERT INTO [country] ([id], [name]) VALUES ('ng', 'ндонга');
INSERT INTO [country] ([id], [name]) VALUES ('nap', 'неаполітанська');
INSERT INTO [country] ([id], [name]) VALUES ('new', 'неварі');
INSERT INTO [country] ([id], [name]) VALUES ('nwc', 'неварі класична');
INSERT INTO [country] ([id], [name]) VALUES ('und', 'невизначена мова');
INSERT INTO [country] ([id], [name]) VALUES ('zxx', 'немає мовного вмісту');
INSERT INTO [country] ([id], [name]) VALUES ('ne', 'непальська');
INSERT INTO [country] ([id], [name]) VALUES ('nzi', 'нзіма');
INSERT INTO [country] ([id], [name]) VALUES ('dsb', 'нижньолужицька');
INSERT INTO [country] ([id], [name]) VALUES ('nds', 'нижньонімецька');
INSERT INTO [country] ([id], [name]) VALUES ('nqo', 'нко');
INSERT INTO [country] ([id], [name]) VALUES ('nog', 'ногайська');
INSERT INTO [country] ([id], [name]) VALUES ('no', 'норвезька');
INSERT INTO [country] ([id], [name]) VALUES ('nb', 'норвезька букмол');
INSERT INTO [country] ([id], [name]) VALUES ('nn', 'норвезька нюнорськ');
INSERT INTO [country] ([id], [name]) VALUES ('nub', 'нубійські мови');
INSERT INTO [country] ([id], [name]) VALUES ('nyo', 'ньоро');
INSERT INTO [country] ([id], [name]) VALUES ('nym', 'ньямвезі');
INSERT INTO [country] ([id], [name]) VALUES ('ny', 'ньянджа');
INSERT INTO [country] ([id], [name]) VALUES ('nyn', 'ньянколе');
INSERT INTO [country] ([id], [name]) VALUES ('tog', 'ньяса тонга');
INSERT INTO [country] ([id], [name]) VALUES ('nia', 'ніаська');
INSERT INTO [country] ([id], [name]) VALUES ('ssa', 'ніло-сахарські мови');
INSERT INTO [country] ([id], [name]) VALUES ('de', 'німецька');
INSERT INTO [country] ([id], [name]) VALUES ('de_AT', 'німецька австрійська');
INSERT INTO [country] ([id], [name]) VALUES ('gsw', 'німецька швейцарська');
INSERT INTO [country] ([id], [name]) VALUES ('niu', 'ніуе');
INSERT INTO [country] ([id], [name]) VALUES ('nic', 'ніґеро-кордофанські мови');
INSERT INTO [country] ([id], [name]) VALUES ('oj', 'оджібва');
INSERT INTO [country] ([id], [name]) VALUES ('oc', 'окитан');
INSERT INTO [country] ([id], [name]) VALUES ('om', 'оромо');
INSERT INTO [country] ([id], [name]) VALUES ('or', 'орія');
INSERT INTO [country] ([id], [name]) VALUES ('osa', 'осейдж');
INSERT INTO [country] ([id], [name]) VALUES ('os', 'осетинська');
INSERT INTO [country] ([id], [name]) VALUES ('ota', 'османська');
INSERT INTO [country] ([id], [name]) VALUES ('oto', 'отомі мови');
INSERT INTO [country] ([id], [name]) VALUES ('pau', 'палауанська');
INSERT INTO [country] ([id], [name]) VALUES ('pi', 'палі');
INSERT INTO [country] ([id], [name]) VALUES ('pam', 'пампанга');
INSERT INTO [country] ([id], [name]) VALUES ('pag', 'пангасінанська');
INSERT INTO [country] ([id], [name]) VALUES ('pa', 'панджабі');
INSERT INTO [country] ([id], [name]) VALUES ('paa', 'папуаські мови');
INSERT INTO [country] ([id], [name]) VALUES ('pap', 'пап’яменто');
INSERT INTO [country] ([id], [name]) VALUES ('fa', 'перська');
INSERT INTO [country] ([id], [name]) VALUES ('pal', 'пехлеві');
INSERT INTO [country] ([id], [name]) VALUES ('pl', 'польська');
INSERT INTO [country] ([id], [name]) VALUES ('pon', 'понапе');
INSERT INTO [country] ([id], [name]) VALUES ('pt', 'португальська');
INSERT INTO [country] ([id], [name]) VALUES ('pt_BR', 'португальська бразильська');
INSERT INTO [country] ([id], [name]) VALUES ('pt_PT', 'португальська іберійська');
INSERT INTO [country] ([id], [name]) VALUES ('cpp', 'португальсько-креольські та піджінізовані португальські мови');
INSERT INTO [country] ([id], [name]) VALUES ('pra', 'пракріті мови');
INSERT INTO [country] ([id], [name]) VALUES ('ps', 'пушту');
INSERT INTO [country] ([id], [name]) VALUES ('alt', 'південноалтайська');
INSERT INTO [country] ([id], [name]) VALUES ('sai', 'південноамериканських індіанців мови');
INSERT INTO [country] ([id], [name]) VALUES ('nai', 'північноамериканських індіанців мови');
INSERT INTO [country] ([id], [name]) VALUES ('raj', 'раджастхані');
INSERT INTO [country] ([id], [name]) VALUES ('rap', 'рапануї');
INSERT INTO [country] ([id], [name]) VALUES ('rar', 'раротонга');
INSERT INTO [country] ([id], [name]) VALUES ('rm', 'ретороманська');
INSERT INTO [country] ([id], [name]) VALUES ('roa', 'романські мови');
INSERT INTO [country] ([id], [name]) VALUES ('ru', 'російська');
INSERT INTO [country] ([id], [name]) VALUES ('ro', 'румунська');
INSERT INTO [country] ([id], [name]) VALUES ('rn', 'рунді');
INSERT INTO [country] ([id], [name]) VALUES ('smj', 'саамська луле');
INSERT INTO [country] ([id], [name]) VALUES ('sma', 'саамська південна');
INSERT INTO [country] ([id], [name]) VALUES ('se', 'саамська північна');
INSERT INTO [country] ([id], [name]) VALUES ('sms', 'саамська скольт');
INSERT INTO [country] ([id], [name]) VALUES ('smn', 'саамська інарі');
INSERT INTO [country] ([id], [name]) VALUES ('smi', 'саамські мови');
INSERT INTO [country] ([id], [name]) VALUES ('sal', 'салішські мови');
INSERT INTO [country] ([id], [name]) VALUES ('sam', 'самаритянська арамейська');
INSERT INTO [country] ([id], [name]) VALUES ('sm', 'самоанська');
INSERT INTO [country] ([id], [name]) VALUES ('sg', 'санго');
INSERT INTO [country] ([id], [name]) VALUES ('sad', 'сандаве');
INSERT INTO [country] ([id], [name]) VALUES ('sa', 'санскрит');
INSERT INTO [country] ([id], [name]) VALUES ('sat', 'сантальська');
INSERT INTO [country] ([id], [name]) VALUES ('zap', 'сапотекська');
INSERT INTO [country] ([id], [name]) VALUES ('sc', 'сардинська');
INSERT INTO [country] ([id], [name]) VALUES ('sas', 'сасакська');
INSERT INTO [country] ([id], [name]) VALUES ('ceb', 'себуанська');
INSERT INTO [country] ([id], [name]) VALUES ('sel', 'селькупська');
INSERT INTO [country] ([id], [name]) VALUES ('sem', 'семітські мови');
INSERT INTO [country] ([id], [name]) VALUES ('sr', 'сербська');
INSERT INTO [country] ([id], [name]) VALUES ('sh', 'сербсько-хорватська');
INSERT INTO [country] ([id], [name]) VALUES ('enm', 'середньоанглійська');
INSERT INTO [country] ([id], [name]) VALUES ('gmh', 'середньоверхньонімецька');
INSERT INTO [country] ([id], [name]) VALUES ('dum', 'середньонідерландська');
INSERT INTO [country] ([id], [name]) VALUES ('frm', 'середньофранцузька');
INSERT INTO [country] ([id], [name]) VALUES ('mga', 'середньоірландська');
INSERT INTO [country] ([id], [name]) VALUES ('srr', 'серер');
INSERT INTO [country] ([id], [name]) VALUES ('si', 'сингальська');
INSERT INTO [country] ([id], [name]) VALUES ('syr', 'сирійська');
INSERT INTO [country] ([id], [name]) VALUES ('syc', 'сирійська класична');
INSERT INTO [country] ([id], [name]) VALUES ('scn', 'сицилійська');
INSERT INTO [country] ([id], [name]) VALUES ('ii', 'сичуань');
INSERT INTO [country] ([id], [name]) VALUES ('den', 'слейв');
INSERT INTO [country] ([id], [name]) VALUES ('sk', 'словацька');
INSERT INTO [country] ([id], [name]) VALUES ('sl', 'словенська');
INSERT INTO [country] ([id], [name]) VALUES ('sla', 'слов’янські мови');
INSERT INTO [country] ([id], [name]) VALUES ('sog', 'согдійська');
INSERT INTO [country] ([id], [name]) VALUES ('so', 'сомалі');
INSERT INTO [country] ([id], [name]) VALUES ('son', 'сонгай');
INSERT INTO [country] ([id], [name]) VALUES ('snk', 'сонінке');
INSERT INTO [country] ([id], [name]) VALUES ('st', 'сото південна');
INSERT INTO [country] ([id], [name]) VALUES ('nso', 'сото північна');
INSERT INTO [country] ([id], [name]) VALUES ('srn', 'сранан тонго');
INSERT INTO [country] ([id], [name]) VALUES ('sw', 'суахілі');
INSERT INTO [country] ([id], [name]) VALUES ('suk', 'сукума');
INSERT INTO [country] ([id], [name]) VALUES ('su', 'сунданська');
INSERT INTO [country] ([id], [name]) VALUES ('sus', 'сусу');
INSERT INTO [country] ([id], [name]) VALUES ('sid', 'сідамо');
INSERT INTO [country] ([id], [name]) VALUES ('bla', 'сіксіка');
INSERT INTO [country] ([id], [name]) VALUES ('sd', 'сіндхі');
INSERT INTO [country] ([id], [name]) VALUES ('ss', 'сісваті');
INSERT INTO [country] ([id], [name]) VALUES ('sio', 'сіу мови');
INSERT INTO [country] ([id], [name]) VALUES ('tl', 'тагальська');
INSERT INTO [country] ([id], [name]) VALUES ('tg', 'таджицька');
INSERT INTO [country] ([id], [name]) VALUES ('th', 'тайська');
INSERT INTO [country] ([id], [name]) VALUES ('tai', 'тайські мови');
INSERT INTO [country] ([id], [name]) VALUES ('tmh', 'тамашек');
INSERT INTO [country] ([id], [name]) VALUES ('ta', 'тамільська');
INSERT INTO [country] ([id], [name]) VALUES ('tt', 'татарська');
INSERT INTO [country] ([id], [name]) VALUES ('ty', 'таїтянська');
INSERT INTO [country] ([id], [name]) VALUES ('tw', 'тві');
INSERT INTO [country] ([id], [name]) VALUES ('te', 'телугу');
INSERT INTO [country] ([id], [name]) VALUES ('tem', 'темне');
INSERT INTO [country] ([id], [name]) VALUES ('ter', 'терено');
INSERT INTO [country] ([id], [name]) VALUES ('tet', 'тетум');
INSERT INTO [country] ([id], [name]) VALUES ('bo', 'тибетська');
INSERT INTO [country] ([id], [name]) VALUES ('tig', 'тигре');
INSERT INTO [country] ([id], [name]) VALUES ('ti', 'тигріні');
INSERT INTO [country] ([id], [name]) VALUES ('tli', 'тлінгіт');
INSERT INTO [country] ([id], [name]) VALUES ('tpi', 'ток-пісін');
INSERT INTO [country] ([id], [name]) VALUES ('tkl', 'токелау');
INSERT INTO [country] ([id], [name]) VALUES ('tn', 'тсвана');
INSERT INTO [country] ([id], [name]) VALUES ('ts', 'тсонга');
INSERT INTO [country] ([id], [name]) VALUES ('tvl', 'тувалу');
INSERT INTO [country] ([id], [name]) VALUES ('tyv', 'тувинська');
INSERT INTO [country] ([id], [name]) VALUES ('tum', 'тумбука');
INSERT INTO [country] ([id], [name]) VALUES ('tup', 'тупі');
INSERT INTO [country] ([id], [name]) VALUES ('tr', 'турецька');
INSERT INTO [country] ([id], [name]) VALUES ('tk', 'туркменська');
INSERT INTO [country] ([id], [name]) VALUES ('kcg', 'тіап');
INSERT INTO [country] ([id], [name]) VALUES ('tiv', 'тів');
INSERT INTO [country] ([id], [name]) VALUES ('uga', 'угаритська');
INSERT INTO [country] ([id], [name]) VALUES ('hu', 'угорська');
INSERT INTO [country] ([id], [name]) VALUES ('udm', 'удмуртська');
INSERT INTO [country] ([id], [name]) VALUES ('uz', 'узбецька');
INSERT INTO [country] ([id], [name]) VALUES ('ug', 'уйгурська');
INSERT INTO [country] ([id], [name]) VALUES ('uk', 'українська');
INSERT INTO [country] ([id], [name]) VALUES ('umb', 'умбунду');
INSERT INTO [country] ([id], [name]) VALUES ('ur', 'урду');
INSERT INTO [country] ([id], [name]) VALUES ('fan', 'фанг');
INSERT INTO [country] ([id], [name]) VALUES ('fat', 'фанті');
INSERT INTO [country] ([id], [name]) VALUES ('fo', 'фарерська');
INSERT INTO [country] ([id], [name]) VALUES ('nl_BE', 'фламандська');
INSERT INTO [country] ([id], [name]) VALUES ('fon', 'фон');
INSERT INTO [country] ([id], [name]) VALUES ('cpf', 'франко-креольські та піджінізовані франкофонні мови');
INSERT INTO [country] ([id], [name]) VALUES ('fr', 'французька');
INSERT INTO [country] ([id], [name]) VALUES ('fr_CA', 'французька канадська');
INSERT INTO [country] ([id], [name]) VALUES ('fr_CH', 'французька швейцарська');
INSERT INTO [country] ([id], [name]) VALUES ('fy', 'фризька');
INSERT INTO [country] ([id], [name]) VALUES ('frr', 'фризька північна');
INSERT INTO [country] ([id], [name]) VALUES ('frs', 'фризька східна');
INSERT INTO [country] ([id], [name]) VALUES ('fur', 'фріульська');
INSERT INTO [country] ([id], [name]) VALUES ('ff', 'фула');
INSERT INTO [country] ([id], [name]) VALUES ('fj', 'фіджі');
INSERT INTO [country] ([id], [name]) VALUES ('fil', 'філіппінська');
INSERT INTO [country] ([id], [name]) VALUES ('phi', 'філіппінські мови');
INSERT INTO [country] ([id], [name]) VALUES ('fiu', 'фінно-угорські мови');
INSERT INTO [country] ([id], [name]) VALUES ('fi', 'фінська');
INSERT INTO [country] ([id], [name]) VALUES ('phn', 'фінікійсько-пунічна');
INSERT INTO [country] ([id], [name]) VALUES ('hai', 'хайда');
INSERT INTO [country] ([id], [name]) VALUES ('cmc', 'хамітські мови');
INSERT INTO [country] ([id], [name]) VALUES ('ha', 'хауса');
INSERT INTO [country] ([id], [name]) VALUES ('hmn', 'хмонг');
INSERT INTO [country] ([id], [name]) VALUES ('hr', 'хорватська');
INSERT INTO [country] ([id], [name]) VALUES ('kho', 'хотаносакська');
INSERT INTO [country] ([id], [name]) VALUES ('hup', 'хупа');
INSERT INTO [country] ([id], [name]) VALUES ('hil', 'хілігайнон');
INSERT INTO [country] ([id], [name]) VALUES ('him', 'хімачалі');
INSERT INTO [country] ([id], [name]) VALUES ('ho', 'хірі-моту');
INSERT INTO [country] ([id], [name]) VALUES ('hit', 'хітіті');
INSERT INTO [country] ([id], [name]) VALUES ('cai', 'центральноамериканьских індіанців мова');
INSERT INTO [country] ([id], [name]) VALUES ('cu', 'церковнослов’янська');
INSERT INTO [country] ([id], [name]) VALUES ('rom', 'циганська');
INSERT INTO [country] ([id], [name]) VALUES ('tsi', 'цимшиан');
INSERT INTO [country] ([id], [name]) VALUES ('chg', 'чагатайська');
INSERT INTO [country] ([id], [name]) VALUES ('ch', 'чаморро');
INSERT INTO [country] ([id], [name]) VALUES ('chy', 'чейєнн');
INSERT INTO [country] ([id], [name]) VALUES ('chr', 'черокі');
INSERT INTO [country] ([id], [name]) VALUES ('cs', 'чеська');
INSERT INTO [country] ([id], [name]) VALUES ('ce', 'чеченська');
INSERT INTO [country] ([id], [name]) VALUES ('za', 'чжуан');
INSERT INTO [country] ([id], [name]) VALUES ('chn', 'чинук жаргон');
INSERT INTO [country] ([id], [name]) VALUES ('cho', 'чокто');
INSERT INTO [country] ([id], [name]) VALUES ('cv', 'чуваська');
INSERT INTO [country] ([id], [name]) VALUES ('chk', 'чуукська');
INSERT INTO [country] ([id], [name]) VALUES ('chb', 'чібча');
INSERT INTO [country] ([id], [name]) VALUES ('chp', 'чіпев’ян');
INSERT INTO [country] ([id], [name]) VALUES ('shn', 'шанська');
INSERT INTO [country] ([id], [name]) VALUES ('sv', 'шведська');
INSERT INTO [country] ([id], [name]) VALUES ('sn', 'шона');
INSERT INTO [country] ([id], [name]) VALUES ('sco', 'шотландська');
INSERT INTO [country] ([id], [name]) VALUES ('art', 'штучна мова');
INSERT INTO [country] ([id], [name]) VALUES ('sux', 'шумерська');
INSERT INTO [country] ([id], [name]) VALUES ('ypk', 'юпік мови');
INSERT INTO [country] ([id], [name]) VALUES ('jv', 'яванська');
INSERT INTO [country] ([id], [name]) VALUES ('sah', 'якутська');
INSERT INTO [country] ([id], [name]) VALUES ('yao', 'яо');
INSERT INTO [country] ([id], [name]) VALUES ('yap', 'яп');
INSERT INTO [country] ([id], [name]) VALUES ('ja', 'японська');
INSERT INTO [country] ([id], [name]) VALUES ('iba', 'ібанська');
INSERT INTO [country] ([id], [name]) VALUES ('es_ES', 'іберійська іспанська');
INSERT INTO [country] ([id], [name]) VALUES ('he', 'іврит');
INSERT INTO [country] ([id], [name]) VALUES ('ig', 'ігбо');
INSERT INTO [country] ([id], [name]) VALUES ('ijo', 'іджо');
INSERT INTO [country] ([id], [name]) VALUES ('yi', 'ідиш');
INSERT INTO [country] ([id], [name]) VALUES ('io', 'ідо');
INSERT INTO [country] ([id], [name]) VALUES ('ilo', 'ілоканська');
INSERT INTO [country] ([id], [name]) VALUES ('inh', 'інгуська');
INSERT INTO [country] ([id], [name]) VALUES ('id', 'індонезійська');
INSERT INTO [country] ([id], [name]) VALUES ('ine', 'індоєвропейські мови');
INSERT INTO [country] ([id], [name]) VALUES ('inc', 'індійські мови');
INSERT INTO [country] ([id], [name]) VALUES ('ia', 'інтерлінгва');
INSERT INTO [country] ([id], [name]) VALUES ('ie', 'інтерлінгве');
INSERT INTO [country] ([id], [name]) VALUES ('iu', 'інуктітут');
INSERT INTO [country] ([id], [name]) VALUES ('ik', 'інупіак');
INSERT INTO [country] ([id], [name]) VALUES ('mis', 'інші мови');
INSERT INTO [country] ([id], [name]) VALUES ('ira', 'іранська');
INSERT INTO [country] ([id], [name]) VALUES ('ga', 'ірландська');
INSERT INTO [country] ([id], [name]) VALUES ('iro', 'ірокезькі мови');
INSERT INTO [country] ([id], [name]) VALUES ('is', 'ісландська');
INSERT INTO [country] ([id], [name]) VALUES ('es', 'іспанська');
INSERT INTO [country] ([id], [name]) VALUES ('it', 'італійська');
INSERT INTO [country] ([id], [name]) VALUES ('jrb', 'іудео-арабська');
INSERT INTO [country] ([id], [name]) VALUES ('jpr', 'іудео-перська');
