CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('ab', 'abkhasisk');
INSERT INTO [country] ([id], [name]) VALUES ('ace', 'achinesisk');
INSERT INTO [country] ([id], [name]) VALUES ('ach', 'acoli');
INSERT INTO [country] ([id], [name]) VALUES ('ada', 'adangme');
INSERT INTO [country] ([id], [name]) VALUES ('ady', 'adyghe');
INSERT INTO [country] ([id], [name]) VALUES ('aa', 'afar');
INSERT INTO [country] ([id], [name]) VALUES ('afh', 'afrihili');
INSERT INTO [country] ([id], [name]) VALUES ('af', 'afrikaans');
INSERT INTO [country] ([id], [name]) VALUES ('afa', 'afro-asiatisk sprog');
INSERT INTO [country] ([id], [name]) VALUES ('ain', 'ainu');
INSERT INTO [country] ([id], [name]) VALUES ('ak', 'akan');
INSERT INTO [country] ([id], [name]) VALUES ('akk', 'akkadisk');
INSERT INTO [country] ([id], [name]) VALUES ('sq', 'albansk');
INSERT INTO [country] ([id], [name]) VALUES ('ale', 'aleutisk');
INSERT INTO [country] ([id], [name]) VALUES ('alg', 'algonkisk sprog');
INSERT INTO [country] ([id], [name]) VALUES ('tut', 'altaisk sprog');
INSERT INTO [country] ([id], [name]) VALUES ('en_US', 'amerikansk engelsk');
INSERT INTO [country] ([id], [name]) VALUES ('am', 'amharisk');
INSERT INTO [country] ([id], [name]) VALUES ('anp', 'angika');
INSERT INTO [country] ([id], [name]) VALUES ('apa', 'apachesprog');
INSERT INTO [country] ([id], [name]) VALUES ('ar', 'arabisk');
INSERT INTO [country] ([id], [name]) VALUES ('an', 'aragonesisk');
INSERT INTO [country] ([id], [name]) VALUES ('arc', 'aramæisk');
INSERT INTO [country] ([id], [name]) VALUES ('arp', 'arapaho');
INSERT INTO [country] ([id], [name]) VALUES ('arn', 'araukansk');
INSERT INTO [country] ([id], [name]) VALUES ('arw', 'arawak');
INSERT INTO [country] ([id], [name]) VALUES ('hy', 'armensk');
INSERT INTO [country] ([id], [name]) VALUES ('rup', 'arumænsk');
INSERT INTO [country] ([id], [name]) VALUES ('az', 'aserbajdsjansk');
INSERT INTO [country] ([id], [name]) VALUES ('as', 'assamesisk');
INSERT INTO [country] ([id], [name]) VALUES ('ast', 'asturisk');
INSERT INTO [country] ([id], [name]) VALUES ('asa', 'asu');
INSERT INTO [country] ([id], [name]) VALUES ('den', 'athapaskisk');
INSERT INTO [country] ([id], [name]) VALUES ('ath', 'athapaskisk sprog');
INSERT INTO [country] ([id], [name]) VALUES ('cch', 'atsam');
INSERT INTO [country] ([id], [name]) VALUES ('en_AU', 'australsk engelsk');
INSERT INTO [country] ([id], [name]) VALUES ('aus', 'australsk sprog');
INSERT INTO [country] ([id], [name]) VALUES ('map', 'austronesisk sprog');
INSERT INTO [country] ([id], [name]) VALUES ('av', 'avarisk');
INSERT INTO [country] ([id], [name]) VALUES ('ae', 'avestan');
INSERT INTO [country] ([id], [name]) VALUES ('awa', 'awadhi');
INSERT INTO [country] ([id], [name]) VALUES ('ay', 'aymara');
INSERT INTO [country] ([id], [name]) VALUES ('ban', 'balinesisk');
INSERT INTO [country] ([id], [name]) VALUES ('bat', 'baltisk sprog');
INSERT INTO [country] ([id], [name]) VALUES ('bal', 'baluchi');
INSERT INTO [country] ([id], [name]) VALUES ('bm', 'bambara');
INSERT INTO [country] ([id], [name]) VALUES ('bai', 'bamilekisk sprog');
INSERT INTO [country] ([id], [name]) VALUES ('bad', 'banda');
INSERT INTO [country] ([id], [name]) VALUES ('bnt', 'bantu');
INSERT INTO [country] ([id], [name]) VALUES ('bas', 'basa');
INSERT INTO [country] ([id], [name]) VALUES ('ba', 'bashkir');
INSERT INTO [country] ([id], [name]) VALUES ('eu', 'baskisk');
INSERT INTO [country] ([id], [name]) VALUES ('btk', 'batak');
INSERT INTO [country] ([id], [name]) VALUES ('bej', 'beja');
INSERT INTO [country] ([id], [name]) VALUES ('bem', 'bemba');
INSERT INTO [country] ([id], [name]) VALUES ('bez', 'bena');
INSERT INTO [country] ([id], [name]) VALUES ('bn', 'bengalsk');
INSERT INTO [country] ([id], [name]) VALUES ('ber', 'berberisk');
INSERT INTO [country] ([id], [name]) VALUES ('bho', 'bhojpuri');
INSERT INTO [country] ([id], [name]) VALUES ('bh', 'bihari');
INSERT INTO [country] ([id], [name]) VALUES ('bik', 'bikol');
INSERT INTO [country] ([id], [name]) VALUES ('bin', 'bini');
INSERT INTO [country] ([id], [name]) VALUES ('bi', 'bislama');
INSERT INTO [country] ([id], [name]) VALUES ('byn', 'blin');
INSERT INTO [country] ([id], [name]) VALUES ('zbl', 'blissymboler');
INSERT INTO [country] ([id], [name]) VALUES ('bs', 'bosnisk');
INSERT INTO [country] ([id], [name]) VALUES ('bra', 'braj');
INSERT INTO [country] ([id], [name]) VALUES ('pt_BR', 'brasiliansk portugisisk');
INSERT INTO [country] ([id], [name]) VALUES ('br', 'bretonsk');
INSERT INTO [country] ([id], [name]) VALUES ('en_GB', 'britisk engelsk');
INSERT INTO [country] ([id], [name]) VALUES ('bug', 'buginesisk');
INSERT INTO [country] ([id], [name]) VALUES ('bg', 'bulgarsk');
INSERT INTO [country] ([id], [name]) VALUES ('bua', 'buriatisk');
INSERT INTO [country] ([id], [name]) VALUES ('my', 'burmesisk');
INSERT INTO [country] ([id], [name]) VALUES ('cad', 'caddo');
INSERT INTO [country] ([id], [name]) VALUES ('en_CA', 'canadisk engelsk');
INSERT INTO [country] ([id], [name]) VALUES ('fr_CA', 'canadisk fransk');
INSERT INTO [country] ([id], [name]) VALUES ('car', 'caribisk');
INSERT INTO [country] ([id], [name]) VALUES ('es_ES', 'castiliansk spansk');
INSERT INTO [country] ([id], [name]) VALUES ('ca', 'catalansk');
INSERT INTO [country] ([id], [name]) VALUES ('ceb', 'cebuano');
INSERT INTO [country] ([id], [name]) VALUES ('chg', 'chagatai');
INSERT INTO [country] ([id], [name]) VALUES ('cmc', 'chamiske sprog');
INSERT INTO [country] ([id], [name]) VALUES ('ch', 'chamorro');
INSERT INTO [country] ([id], [name]) VALUES ('chr', 'cherokee');
INSERT INTO [country] ([id], [name]) VALUES ('chy', 'cheyenne');
INSERT INTO [country] ([id], [name]) VALUES ('chb', 'chibcha');
INSERT INTO [country] ([id], [name]) VALUES ('chn', 'chinook');
INSERT INTO [country] ([id], [name]) VALUES ('chp', 'chipewyan');
INSERT INTO [country] ([id], [name]) VALUES ('cho', 'choctaw');
INSERT INTO [country] ([id], [name]) VALUES ('chk', 'chuukese');
INSERT INTO [country] ([id], [name]) VALUES ('cv', 'chuvash');
INSERT INTO [country] ([id], [name]) VALUES ('kw', 'cornisk');
INSERT INTO [country] ([id], [name]) VALUES ('cr', 'cree');
INSERT INTO [country] ([id], [name]) VALUES ('mus', 'creek');
INSERT INTO [country] ([id], [name]) VALUES ('dak', 'dakota');
INSERT INTO [country] ([id], [name]) VALUES ('da', 'dansk');
INSERT INTO [country] ([id], [name]) VALUES ('dar', 'dargwa');
INSERT INTO [country] ([id], [name]) VALUES ('day', 'dayak');
INSERT INTO [country] ([id], [name]) VALUES ('del', 'delaware');
INSERT INTO [country] ([id], [name]) VALUES ('din', 'dinka');
INSERT INTO [country] ([id], [name]) VALUES ('dv', 'divehi');
INSERT INTO [country] ([id], [name]) VALUES ('mis', 'diverse sprog');
INSERT INTO [country] ([id], [name]) VALUES ('doi', 'dogri');
INSERT INTO [country] ([id], [name]) VALUES ('dgr', 'dogrib');
INSERT INTO [country] ([id], [name]) VALUES ('dra', 'dravidisk sprog');
INSERT INTO [country] ([id], [name]) VALUES ('dua', 'duala');
INSERT INTO [country] ([id], [name]) VALUES ('dyu', 'dyula');
INSERT INTO [country] ([id], [name]) VALUES ('dz', 'dzongkha');
INSERT INTO [country] ([id], [name]) VALUES ('efi', 'efik');
INSERT INTO [country] ([id], [name]) VALUES ('eka', 'ekajuk');
INSERT INTO [country] ([id], [name]) VALUES ('elx', 'elamitisk');
INSERT INTO [country] ([id], [name]) VALUES ('en', 'engelsk');
INSERT INTO [country] ([id], [name]) VALUES ('cpe', 'engelsk baseret kreolsk eller pidgin');
INSERT INTO [country] ([id], [name]) VALUES ('myv', 'erzya');
INSERT INTO [country] ([id], [name]) VALUES ('eo', 'esperanto');
INSERT INTO [country] ([id], [name]) VALUES ('et', 'estisk');
INSERT INTO [country] ([id], [name]) VALUES ('ee', 'ewe');
INSERT INTO [country] ([id], [name]) VALUES ('ewo', 'ewondo');
INSERT INTO [country] ([id], [name]) VALUES ('fan', 'fang');
INSERT INTO [country] ([id], [name]) VALUES ('fat', 'fanti');
INSERT INTO [country] ([id], [name]) VALUES ('fj', 'fijiansk');
INSERT INTO [country] ([id], [name]) VALUES ('fil', 'filippinsk');
INSERT INTO [country] ([id], [name]) VALUES ('phi', 'filippinsk sprog');
INSERT INTO [country] ([id], [name]) VALUES ('fi', 'finsk');
INSERT INTO [country] ([id], [name]) VALUES ('fiu', 'finsk-ugrisk sprog');
INSERT INTO [country] ([id], [name]) VALUES ('nl_BE', 'flamsk');
INSERT INTO [country] ([id], [name]) VALUES ('fon', 'fon');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hans', 'forenklet kinesisk');
INSERT INTO [country] ([id], [name]) VALUES ('fr', 'fransk');
INSERT INTO [country] ([id], [name]) VALUES ('cpf', 'fransk baseret kreolsk eller pidginsprog');
INSERT INTO [country] ([id], [name]) VALUES ('fy', 'frisisk');
INSERT INTO [country] ([id], [name]) VALUES ('fur', 'friulian');
INSERT INTO [country] ([id], [name]) VALUES ('ff', 'fulah');
INSERT INTO [country] ([id], [name]) VALUES ('fo', 'færøsk');
INSERT INTO [country] ([id], [name]) VALUES ('phn', 'fønikisk');
INSERT INTO [country] ([id], [name]) VALUES ('gaa', 'ga');
INSERT INTO [country] ([id], [name]) VALUES ('gl', 'galicisk');
INSERT INTO [country] ([id], [name]) VALUES ('lg', 'ganda');
INSERT INTO [country] ([id], [name]) VALUES ('gay', 'gayo');
INSERT INTO [country] ([id], [name]) VALUES ('gba', 'gbaya');
INSERT INTO [country] ([id], [name]) VALUES ('gez', 'geez');
INSERT INTO [country] ([id], [name]) VALUES ('ka', 'georgisk');
INSERT INTO [country] ([id], [name]) VALUES ('gem', 'germansk sprog');
INSERT INTO [country] ([id], [name]) VALUES ('gil', 'gilbertesisk');
INSERT INTO [country] ([id], [name]) VALUES ('gon', 'gondi');
INSERT INTO [country] ([id], [name]) VALUES ('gor', 'gorontalo');
INSERT INTO [country] ([id], [name]) VALUES ('got', 'gotisk');
INSERT INTO [country] ([id], [name]) VALUES ('grb', 'grebo');
INSERT INTO [country] ([id], [name]) VALUES ('el', 'græsk');
INSERT INTO [country] ([id], [name]) VALUES ('kl', 'grønlandsk');
INSERT INTO [country] ([id], [name]) VALUES ('gn', 'guarani');
INSERT INTO [country] ([id], [name]) VALUES ('gu', 'gujarati');
INSERT INTO [country] ([id], [name]) VALUES ('gwi', 'gwichin');
INSERT INTO [country] ([id], [name]) VALUES ('hai', 'haida');
INSERT INTO [country] ([id], [name]) VALUES ('ht', 'haitisk');
INSERT INTO [country] ([id], [name]) VALUES ('ha', 'hausa');
INSERT INTO [country] ([id], [name]) VALUES ('haw', 'hawaiiansk');
INSERT INTO [country] ([id], [name]) VALUES ('he', 'hebraisk');
INSERT INTO [country] ([id], [name]) VALUES ('hz', 'herero');
INSERT INTO [country] ([id], [name]) VALUES ('hil', 'hiligaynon');
INSERT INTO [country] ([id], [name]) VALUES ('him', 'himachali');
INSERT INTO [country] ([id], [name]) VALUES ('hi', 'hindi');
INSERT INTO [country] ([id], [name]) VALUES ('ho', 'hirimotu');
INSERT INTO [country] ([id], [name]) VALUES ('hit', 'hittitisk');
INSERT INTO [country] ([id], [name]) VALUES ('hmn', 'hmong');
INSERT INTO [country] ([id], [name]) VALUES ('nl', 'hollandsk');
INSERT INTO [country] ([id], [name]) VALUES ('hup', 'hupa');
INSERT INTO [country] ([id], [name]) VALUES ('be', 'hviderussisk');
INSERT INTO [country] ([id], [name]) VALUES ('iba', 'iban');
INSERT INTO [country] ([id], [name]) VALUES ('pt_PT', 'iberisk portugisisk');
INSERT INTO [country] ([id], [name]) VALUES ('io', 'ido');
INSERT INTO [country] ([id], [name]) VALUES ('ig', 'igbo');
INSERT INTO [country] ([id], [name]) VALUES ('ijo', 'ijo');
INSERT INTO [country] ([id], [name]) VALUES ('ilo', 'iloko');
INSERT INTO [country] ([id], [name]) VALUES ('smn', 'inari sami');
INSERT INTO [country] ([id], [name]) VALUES ('inc', 'indisk sprog');
INSERT INTO [country] ([id], [name]) VALUES ('ine', 'indo-europæisk sprog');
INSERT INTO [country] ([id], [name]) VALUES ('id', 'indonesisk');
INSERT INTO [country] ([id], [name]) VALUES ('inh', 'ingush');
INSERT INTO [country] ([id], [name]) VALUES ('ia', 'interlingua');
INSERT INTO [country] ([id], [name]) VALUES ('ie', 'interlingue');
INSERT INTO [country] ([id], [name]) VALUES ('zxx', 'intet sprogligt indhold');
INSERT INTO [country] ([id], [name]) VALUES ('iu', 'inuktitut');
INSERT INTO [country] ([id], [name]) VALUES ('ik', 'inupiaq');
INSERT INTO [country] ([id], [name]) VALUES ('ira', 'iransk sprog');
INSERT INTO [country] ([id], [name]) VALUES ('iro', 'irokesisk sprog');
INSERT INTO [country] ([id], [name]) VALUES ('ga', 'irsk');
INSERT INTO [country] ([id], [name]) VALUES ('is', 'islandsk');
INSERT INTO [country] ([id], [name]) VALUES ('it', 'italiensk');
INSERT INTO [country] ([id], [name]) VALUES ('ja', 'japansk');
INSERT INTO [country] ([id], [name]) VALUES ('jv', 'javanesisk');
INSERT INTO [country] ([id], [name]) VALUES ('yi', 'jiddisch');
INSERT INTO [country] ([id], [name]) VALUES ('kaj', 'jju');
INSERT INTO [country] ([id], [name]) VALUES ('jrb', 'jødisk-arabisk');
INSERT INTO [country] ([id], [name]) VALUES ('jpr', 'jødisk-persisk');
INSERT INTO [country] ([id], [name]) VALUES ('kbd', 'kabardian');
INSERT INTO [country] ([id], [name]) VALUES ('kab', 'kabyle');
INSERT INTO [country] ([id], [name]) VALUES ('kac', 'kachin');
INSERT INTO [country] ([id], [name]) VALUES ('xal', 'kalmyk');
INSERT INTO [country] ([id], [name]) VALUES ('kam', 'kamba');
INSERT INTO [country] ([id], [name]) VALUES ('kn', 'kannaresisk');
INSERT INTO [country] ([id], [name]) VALUES ('yue', 'kantonesisk');
INSERT INTO [country] ([id], [name]) VALUES ('kr', 'kanuri');
INSERT INTO [country] ([id], [name]) VALUES ('kea', 'kapverdisk');
INSERT INTO [country] ([id], [name]) VALUES ('kaa', 'karakalpakisk');
INSERT INTO [country] ([id], [name]) VALUES ('krc', 'karatjai-balkar');
INSERT INTO [country] ([id], [name]) VALUES ('krl', 'karelsk');
INSERT INTO [country] ([id], [name]) VALUES ('kar', 'karen');
INSERT INTO [country] ([id], [name]) VALUES ('kk', 'kasakhisk');
INSERT INTO [country] ([id], [name]) VALUES ('ks', 'kashmiri');
INSERT INTO [country] ([id], [name]) VALUES ('csb', 'kasjubisk');
INSERT INTO [country] ([id], [name]) VALUES ('cau', 'kaukasisk sprog');
INSERT INTO [country] ([id], [name]) VALUES ('kaw', 'kawi');
INSERT INTO [country] ([id], [name]) VALUES ('cel', 'keltisk sprog');
INSERT INTO [country] ([id], [name]) VALUES ('kha', 'khasi');
INSERT INTO [country] ([id], [name]) VALUES ('km', 'khmer');
INSERT INTO [country] ([id], [name]) VALUES ('khi', 'khoisansprog');
INSERT INTO [country] ([id], [name]) VALUES ('kho', 'khotanesisk');
INSERT INTO [country] ([id], [name]) VALUES ('ebu', 'kiembu');
INSERT INTO [country] ([id], [name]) VALUES ('ki', 'kikuyu');
INSERT INTO [country] ([id], [name]) VALUES ('kmb', 'kimbundu');
INSERT INTO [country] ([id], [name]) VALUES ('zh', 'kinesisk');
INSERT INTO [country] ([id], [name]) VALUES ('rw', 'kinyarwanda');
INSERT INTO [country] ([id], [name]) VALUES ('ky', 'kirgisisk');
INSERT INTO [country] ([id], [name]) VALUES ('cu', 'kirkeslavisk');
INSERT INTO [country] ([id], [name]) VALUES ('nwc', 'klassisk newarisk');
INSERT INTO [country] ([id], [name]) VALUES ('syc', 'klassisk syrisk');
INSERT INTO [country] ([id], [name]) VALUES ('tlh', 'klingon');
INSERT INTO [country] ([id], [name]) VALUES ('kv', 'komi');
INSERT INTO [country] ([id], [name]) VALUES ('kg', 'kongo');
INSERT INTO [country] ([id], [name]) VALUES ('kok', 'konkani');
INSERT INTO [country] ([id], [name]) VALUES ('cop', 'koptisk');
INSERT INTO [country] ([id], [name]) VALUES ('ko', 'koreansk');
INSERT INTO [country] ([id], [name]) VALUES ('kfo', 'koro');
INSERT INTO [country] ([id], [name]) VALUES ('co', 'korsikansk');
INSERT INTO [country] ([id], [name]) VALUES ('kos', 'kosraean');
INSERT INTO [country] ([id], [name]) VALUES ('kpe', 'kpelle');
INSERT INTO [country] ([id], [name]) VALUES ('crp', 'kreolsk eller pidginsprog');
INSERT INTO [country] ([id], [name]) VALUES ('crh', 'krim tyrkisk');
INSERT INTO [country] ([id], [name]) VALUES ('hr', 'kroatisk');
INSERT INTO [country] ([id], [name]) VALUES ('kro', 'kru');
INSERT INTO [country] ([id], [name]) VALUES ('kj', 'kuanyama');
INSERT INTO [country] ([id], [name]) VALUES ('art', 'kunstsprog');
INSERT INTO [country] ([id], [name]) VALUES ('ku', 'kurdisk');
INSERT INTO [country] ([id], [name]) VALUES ('kru', 'kurukh');
INSERT INTO [country] ([id], [name]) VALUES ('cus', 'kusjitisk sprog');
INSERT INTO [country] ([id], [name]) VALUES ('kut', 'kutenaj');
INSERT INTO [country] ([id], [name]) VALUES ('kum', 'kymyk');
INSERT INTO [country] ([id], [name]) VALUES ('lad', 'ladino');
INSERT INTO [country] ([id], [name]) VALUES ('lah', 'lahnda');
INSERT INTO [country] ([id], [name]) VALUES ('lam', 'lamba');
INSERT INTO [country] ([id], [name]) VALUES ('lo', 'laotisk');
INSERT INTO [country] ([id], [name]) VALUES ('la', 'latin');
INSERT INTO [country] ([id], [name]) VALUES ('es_419', 'latinamerikansk spansk');
INSERT INTO [country] ([id], [name]) VALUES ('lv', 'lettisk');
INSERT INTO [country] ([id], [name]) VALUES ('lez', 'lezghian');
INSERT INTO [country] ([id], [name]) VALUES ('li', 'limburgsk');
INSERT INTO [country] ([id], [name]) VALUES ('ln', 'lingala');
INSERT INTO [country] ([id], [name]) VALUES ('lt', 'litauisk');
INSERT INTO [country] ([id], [name]) VALUES ('jbo', 'lojban');
INSERT INTO [country] ([id], [name]) VALUES ('loz', 'lozi');
INSERT INTO [country] ([id], [name]) VALUES ('lu', 'luba-Katanga');
INSERT INTO [country] ([id], [name]) VALUES ('lua', 'luba-Lulua');
INSERT INTO [country] ([id], [name]) VALUES ('lui', 'luiseno');
INSERT INTO [country] ([id], [name]) VALUES ('smj', 'lule sami');
INSERT INTO [country] ([id], [name]) VALUES ('lun', 'lunda');
INSERT INTO [country] ([id], [name]) VALUES ('luo', 'luo');
INSERT INTO [country] ([id], [name]) VALUES ('lus', 'lushai');
INSERT INTO [country] ([id], [name]) VALUES ('lb', 'luxembourgsk');
INSERT INTO [country] ([id], [name]) VALUES ('mad', 'madurese');
INSERT INTO [country] ([id], [name]) VALUES ('mag', 'magahi');
INSERT INTO [country] ([id], [name]) VALUES ('mai', 'maithili');
INSERT INTO [country] ([id], [name]) VALUES ('mak', 'makasar');
INSERT INTO [country] ([id], [name]) VALUES ('mk', 'makedonsk');
INSERT INTO [country] ([id], [name]) VALUES ('mg', 'malagasy');
INSERT INTO [country] ([id], [name]) VALUES ('ms', 'malay');
INSERT INTO [country] ([id], [name]) VALUES ('ml', 'malayalam');
INSERT INTO [country] ([id], [name]) VALUES ('mt', 'maltesisk');
INSERT INTO [country] ([id], [name]) VALUES ('mnc', 'manchu');
INSERT INTO [country] ([id], [name]) VALUES ('mdr', 'mandar');
INSERT INTO [country] ([id], [name]) VALUES ('man', 'mandingo');
INSERT INTO [country] ([id], [name]) VALUES ('mni', 'manipuri');
INSERT INTO [country] ([id], [name]) VALUES ('mno', 'manobo sprog');
INSERT INTO [country] ([id], [name]) VALUES ('gv', 'manx');
INSERT INTO [country] ([id], [name]) VALUES ('mi', 'maori');
INSERT INTO [country] ([id], [name]) VALUES ('mr', 'marathisk');
INSERT INTO [country] ([id], [name]) VALUES ('chm', 'mari');
INSERT INTO [country] ([id], [name]) VALUES ('mh', 'marshallese');
INSERT INTO [country] ([id], [name]) VALUES ('mwr', 'marwari');
INSERT INTO [country] ([id], [name]) VALUES ('mas', 'masai');
INSERT INTO [country] ([id], [name]) VALUES ('myn', 'mayasprog');
INSERT INTO [country] ([id], [name]) VALUES ('cai', 'mellemamerikansk indiansk sprog');
INSERT INTO [country] ([id], [name]) VALUES ('men', 'mende');
INSERT INTO [country] ([id], [name]) VALUES ('mic', 'micmac');
INSERT INTO [country] ([id], [name]) VALUES ('enm', 'middelengelsk');
INSERT INTO [country] ([id], [name]) VALUES ('frm', 'middelfransk');
INSERT INTO [country] ([id], [name]) VALUES ('dum', 'middelhollandsk');
INSERT INTO [country] ([id], [name]) VALUES ('gmh', 'middelhøjtysk');
INSERT INTO [country] ([id], [name]) VALUES ('mga', 'middelirsk');
INSERT INTO [country] ([id], [name]) VALUES ('min', 'minangkabau');
INSERT INTO [country] ([id], [name]) VALUES ('mwl', 'mirandesisk');
INSERT INTO [country] ([id], [name]) VALUES ('moh', 'mohawk');
INSERT INTO [country] ([id], [name]) VALUES ('mdf', 'moksha');
INSERT INTO [country] ([id], [name]) VALUES ('mo', 'moldovisk');
INSERT INTO [country] ([id], [name]) VALUES ('mkh', 'mon-khmer sprog');
INSERT INTO [country] ([id], [name]) VALUES ('lol', 'mongo');
INSERT INTO [country] ([id], [name]) VALUES ('mn', 'mongolsk');
INSERT INTO [country] ([id], [name]) VALUES ('mos', 'mossi');
INSERT INTO [country] ([id], [name]) VALUES ('mun', 'mundasprog');
INSERT INTO [country] ([id], [name]) VALUES ('nqo', 'n-ko');
INSERT INTO [country] ([id], [name]) VALUES ('nah', 'nahuatl');
INSERT INTO [country] ([id], [name]) VALUES ('na', 'nauru');
INSERT INTO [country] ([id], [name]) VALUES ('nv', 'navajo');
INSERT INTO [country] ([id], [name]) VALUES ('ng', 'ndonga');
INSERT INTO [country] ([id], [name]) VALUES ('nap', 'neapolitansk');
INSERT INTO [country] ([id], [name]) VALUES ('dsb', 'nedersorbisk');
INSERT INTO [country] ([id], [name]) VALUES ('nds', 'nedertysk');
INSERT INTO [country] ([id], [name]) VALUES ('ne', 'nepalesisk');
INSERT INTO [country] ([id], [name]) VALUES ('new', 'newari');
INSERT INTO [country] ([id], [name]) VALUES ('nia', 'nias');
INSERT INTO [country] ([id], [name]) VALUES ('nic', 'Niger-Congo sprog');
INSERT INTO [country] ([id], [name]) VALUES ('ssa', 'nilo-saharansk sprog');
INSERT INTO [country] ([id], [name]) VALUES ('niu', 'niuean');
INSERT INTO [country] ([id], [name]) VALUES ('nog', 'nogai');
INSERT INTO [country] ([id], [name]) VALUES ('nai', 'nordamerikansk indiansk sprog');
INSERT INTO [country] ([id], [name]) VALUES ('frr', 'nordfrisisk');
INSERT INTO [country] ([id], [name]) VALUES ('nd', 'nordndebele');
INSERT INTO [country] ([id], [name]) VALUES ('se', 'nordsamisk');
INSERT INTO [country] ([id], [name]) VALUES ('nso', 'nordsotho');
INSERT INTO [country] ([id], [name]) VALUES ('no', 'norsk');
INSERT INTO [country] ([id], [name]) VALUES ('nb', 'norsk bokmål');
INSERT INTO [country] ([id], [name]) VALUES ('nub', 'nubisk sprog');
INSERT INTO [country] ([id], [name]) VALUES ('nym', 'nyamwezi');
INSERT INTO [country] ([id], [name]) VALUES ('ny', 'nyanja');
INSERT INTO [country] ([id], [name]) VALUES ('nyn', 'nyankole');
INSERT INTO [country] ([id], [name]) VALUES ('tog', 'nyasa tongansk');
INSERT INTO [country] ([id], [name]) VALUES ('nn', 'nynorsk');
INSERT INTO [country] ([id], [name]) VALUES ('nyo', 'nyoro sprog');
INSERT INTO [country] ([id], [name]) VALUES ('nzi', 'nzima');
INSERT INTO [country] ([id], [name]) VALUES ('oc', 'occitansk');
INSERT INTO [country] ([id], [name]) VALUES ('oj', 'ojibwa');
INSERT INTO [country] ([id], [name]) VALUES ('egy', 'oldegyptisk');
INSERT INTO [country] ([id], [name]) VALUES ('ang', 'oldengelsk');
INSERT INTO [country] ([id], [name]) VALUES ('fro', 'oldfransk');
INSERT INTO [country] ([id], [name]) VALUES ('grc', 'oldgræsk');
INSERT INTO [country] ([id], [name]) VALUES ('goh', 'oldhøjtysk');
INSERT INTO [country] ([id], [name]) VALUES ('sga', 'oldirsk');
INSERT INTO [country] ([id], [name]) VALUES ('non', 'oldislandsk');
INSERT INTO [country] ([id], [name]) VALUES ('peo', 'oldpersisk');
INSERT INTO [country] ([id], [name]) VALUES ('pro', 'oldprovencalsk');
INSERT INTO [country] ([id], [name]) VALUES ('luy', 'olulujia');
INSERT INTO [country] ([id], [name]) VALUES ('or', 'oriya');
INSERT INTO [country] ([id], [name]) VALUES ('om', 'oromo');
INSERT INTO [country] ([id], [name]) VALUES ('osa', 'osage');
INSERT INTO [country] ([id], [name]) VALUES ('ota', 'osmannisk-tyrkisk');
INSERT INTO [country] ([id], [name]) VALUES ('os', 'ossetisk');
INSERT INTO [country] ([id], [name]) VALUES ('oto', 'otomi sprog');
INSERT INTO [country] ([id], [name]) VALUES ('pal', 'pahlavi');
INSERT INTO [country] ([id], [name]) VALUES ('pau', 'palauansk');
INSERT INTO [country] ([id], [name]) VALUES ('pi', 'pali');
INSERT INTO [country] ([id], [name]) VALUES ('pam', 'pampanga');
INSERT INTO [country] ([id], [name]) VALUES ('pag', 'pangasinan');
INSERT INTO [country] ([id], [name]) VALUES ('pap', 'papiamento');
INSERT INTO [country] ([id], [name]) VALUES ('paa', 'papua-australsk sprog');
INSERT INTO [country] ([id], [name]) VALUES ('ps', 'pashto');
INSERT INTO [country] ([id], [name]) VALUES ('fa', 'persisk');
INSERT INTO [country] ([id], [name]) VALUES ('pl', 'polsk');
INSERT INTO [country] ([id], [name]) VALUES ('pon', 'ponape');
INSERT INTO [country] ([id], [name]) VALUES ('pt', 'portugisisk');
INSERT INTO [country] ([id], [name]) VALUES ('cpp', 'portugisisk baseret kreolsk eller pidginsprog');
INSERT INTO [country] ([id], [name]) VALUES ('pra', 'prakritsprog');
INSERT INTO [country] ([id], [name]) VALUES ('pa', 'punjabi');
INSERT INTO [country] ([id], [name]) VALUES ('qu', 'quechua');
INSERT INTO [country] ([id], [name]) VALUES ('raj', 'rajasthani');
INSERT INTO [country] ([id], [name]) VALUES ('rap', 'rapanui');
INSERT INTO [country] ([id], [name]) VALUES ('rar', 'rarotongan');
INSERT INTO [country] ([id], [name]) VALUES ('rom', 'romani');
INSERT INTO [country] ([id], [name]) VALUES ('roa', 'romansk sprog');
INSERT INTO [country] ([id], [name]) VALUES ('root', 'rot');
INSERT INTO [country] ([id], [name]) VALUES ('ro', 'rumænsk');
INSERT INTO [country] ([id], [name]) VALUES ('rn', 'rundi');
INSERT INTO [country] ([id], [name]) VALUES ('ru', 'russisk');
INSERT INTO [country] ([id], [name]) VALUES ('rm', 'rætoromansk');
INSERT INTO [country] ([id], [name]) VALUES ('sal', 'salikisk sprog');
INSERT INTO [country] ([id], [name]) VALUES ('sam', 'samaritansk');
INSERT INTO [country] ([id], [name]) VALUES ('smi', 'samisk sprog');
INSERT INTO [country] ([id], [name]) VALUES ('sm', 'samoansk');
INSERT INTO [country] ([id], [name]) VALUES ('sad', 'sandawe');
INSERT INTO [country] ([id], [name]) VALUES ('sg', 'sango');
INSERT INTO [country] ([id], [name]) VALUES ('sa', 'sanskrit');
INSERT INTO [country] ([id], [name]) VALUES ('sat', 'santali');
INSERT INTO [country] ([id], [name]) VALUES ('sc', 'sardinsk');
INSERT INTO [country] ([id], [name]) VALUES ('sas', 'sasak');
INSERT INTO [country] ([id], [name]) VALUES ('de_CH', 'schweizerhøjtysk');
INSERT INTO [country] ([id], [name]) VALUES ('gsw', 'schweizertysk');
INSERT INTO [country] ([id], [name]) VALUES ('fr_CH', 'schweizisk fransk');
INSERT INTO [country] ([id], [name]) VALUES ('sel', 'selkupisk');
INSERT INTO [country] ([id], [name]) VALUES ('sem', 'semitisk sprog');
INSERT INTO [country] ([id], [name]) VALUES ('sr', 'serbisk');
INSERT INTO [country] ([id], [name]) VALUES ('sh', 'serbokroatisk');
INSERT INTO [country] ([id], [name]) VALUES ('srr', 'serer');
INSERT INTO [country] ([id], [name]) VALUES ('shn', 'shan');
INSERT INTO [country] ([id], [name]) VALUES ('swb', 'shimaore');
INSERT INTO [country] ([id], [name]) VALUES ('sn', 'shona');
INSERT INTO [country] ([id], [name]) VALUES ('ii', 'sichuan yi');
INSERT INTO [country] ([id], [name]) VALUES ('scn', 'siciliansk');
INSERT INTO [country] ([id], [name]) VALUES ('sid', 'sidamo');
INSERT INTO [country] ([id], [name]) VALUES ('bla', 'siksika');
INSERT INTO [country] ([id], [name]) VALUES ('sd', 'sindhi');
INSERT INTO [country] ([id], [name]) VALUES ('si', 'singalesisk');
INSERT INTO [country] ([id], [name]) VALUES ('sit', 'sino-tibetansk sprog');
INSERT INTO [country] ([id], [name]) VALUES ('sio', 'sioux sprog');
INSERT INTO [country] ([id], [name]) VALUES ('sms', 'skolt sami');
INSERT INTO [country] ([id], [name]) VALUES ('sco', 'skotsk');
INSERT INTO [country] ([id], [name]) VALUES ('gd', 'skotsk gælisk');
INSERT INTO [country] ([id], [name]) VALUES ('sla', 'slavisk sprog');
INSERT INTO [country] ([id], [name]) VALUES ('sk', 'slovakisk');
INSERT INTO [country] ([id], [name]) VALUES ('sl', 'slovensk');
INSERT INTO [country] ([id], [name]) VALUES ('sog', 'sogdiansk');
INSERT INTO [country] ([id], [name]) VALUES ('so', 'somalisk');
INSERT INTO [country] ([id], [name]) VALUES ('son', 'songhai');
INSERT INTO [country] ([id], [name]) VALUES ('snk', 'soninke');
INSERT INTO [country] ([id], [name]) VALUES ('es', 'spansk');
INSERT INTO [country] ([id], [name]) VALUES ('srn', 'sranan tongo');
INSERT INTO [country] ([id], [name]) VALUES ('suk', 'sukuma');
INSERT INTO [country] ([id], [name]) VALUES ('sux', 'sumerisk');
INSERT INTO [country] ([id], [name]) VALUES ('su', 'sundanesisk');
INSERT INTO [country] ([id], [name]) VALUES ('sus', 'susu');
INSERT INTO [country] ([id], [name]) VALUES ('sv', 'svensk');
INSERT INTO [country] ([id], [name]) VALUES ('sw', 'swahili');
INSERT INTO [country] ([id], [name]) VALUES ('ss', 'swati');
INSERT INTO [country] ([id], [name]) VALUES ('alt', 'sydaltaisk');
INSERT INTO [country] ([id], [name]) VALUES ('sai', 'sydamerikansk indiansk sprog');
INSERT INTO [country] ([id], [name]) VALUES ('nr', 'sydndebele');
INSERT INTO [country] ([id], [name]) VALUES ('sma', 'sydsamisk');
INSERT INTO [country] ([id], [name]) VALUES ('st', 'sydsotho');
INSERT INTO [country] ([id], [name]) VALUES ('syr', 'syrisk');
INSERT INTO [country] ([id], [name]) VALUES ('tl', 'tagalog');
INSERT INTO [country] ([id], [name]) VALUES ('ty', 'tahitiansk');
INSERT INTO [country] ([id], [name]) VALUES ('tg', 'tajik');
INSERT INTO [country] ([id], [name]) VALUES ('tmh', 'tamashek');
INSERT INTO [country] ([id], [name]) VALUES ('ta', 'tamilsk');
INSERT INTO [country] ([id], [name]) VALUES ('tt', 'tatarisk');
INSERT INTO [country] ([id], [name]) VALUES ('sgn', 'tegnsprog');
INSERT INTO [country] ([id], [name]) VALUES ('te', 'telugu');
INSERT INTO [country] ([id], [name]) VALUES ('tem', 'temne');
INSERT INTO [country] ([id], [name]) VALUES ('ter', 'tereno');
INSERT INTO [country] ([id], [name]) VALUES ('tet', 'tetum');
INSERT INTO [country] ([id], [name]) VALUES ('th', 'thailandsk');
INSERT INTO [country] ([id], [name]) VALUES ('tai', 'thaisprog');
INSERT INTO [country] ([id], [name]) VALUES ('bo', 'tibetansk');
INSERT INTO [country] ([id], [name]) VALUES ('tig', 'tigre');
INSERT INTO [country] ([id], [name]) VALUES ('ti', 'tigrinya');
INSERT INTO [country] ([id], [name]) VALUES ('tiv', 'tivi');
INSERT INTO [country] ([id], [name]) VALUES ('cs', 'tjekkisk');
INSERT INTO [country] ([id], [name]) VALUES ('ce', 'tjetjensk');
INSERT INTO [country] ([id], [name]) VALUES ('tli', 'tlingit');
INSERT INTO [country] ([id], [name]) VALUES ('tpi', 'tok pisin');
INSERT INTO [country] ([id], [name]) VALUES ('tkl', 'tokelau');
INSERT INTO [country] ([id], [name]) VALUES ('to', 'tongansk');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hant', 'traditionelt kinesisk');
INSERT INTO [country] ([id], [name]) VALUES ('tsi', 'tsimshisk');
INSERT INTO [country] ([id], [name]) VALUES ('ts', 'tsonga');
INSERT INTO [country] ([id], [name]) VALUES ('tn', 'tswana');
INSERT INTO [country] ([id], [name]) VALUES ('tum', 'tumbuka');
INSERT INTO [country] ([id], [name]) VALUES ('tup', 'tupisprog');
INSERT INTO [country] ([id], [name]) VALUES ('tk', 'turkmensk');
INSERT INTO [country] ([id], [name]) VALUES ('tvl', 'tuvalu');
INSERT INTO [country] ([id], [name]) VALUES ('tyv', 'tuvinian');
INSERT INTO [country] ([id], [name]) VALUES ('tw', 'twi');
INSERT INTO [country] ([id], [name]) VALUES ('kcg', 'tyap');
INSERT INTO [country] ([id], [name]) VALUES ('tr', 'tyrkisk');
INSERT INTO [country] ([id], [name]) VALUES ('de', 'tysk');
INSERT INTO [country] ([id], [name]) VALUES ('udm', 'udmurt');
INSERT INTO [country] ([id], [name]) VALUES ('uga', 'ugaristisk');
INSERT INTO [country] ([id], [name]) VALUES ('ug', 'uigurisk');
INSERT INTO [country] ([id], [name]) VALUES ('und', 'ukendt sprog');
INSERT INTO [country] ([id], [name]) VALUES ('uk', 'ukrainsk');
INSERT INTO [country] ([id], [name]) VALUES ('umb', 'umbundu');
INSERT INTO [country] ([id], [name]) VALUES ('hu', 'ungarsk');
INSERT INTO [country] ([id], [name]) VALUES ('ur', 'urdu');
INSERT INTO [country] ([id], [name]) VALUES ('uz', 'usbekisk');
INSERT INTO [country] ([id], [name]) VALUES ('vai', 'vai');
INSERT INTO [country] ([id], [name]) VALUES ('wa', 'vallonsk');
INSERT INTO [country] ([id], [name]) VALUES ('ve', 'venda');
INSERT INTO [country] ([id], [name]) VALUES ('wen', 'vendisk sprog');
INSERT INTO [country] ([id], [name]) VALUES ('vi', 'vietnamesisk');
INSERT INTO [country] ([id], [name]) VALUES ('vo', 'volapyk');
INSERT INTO [country] ([id], [name]) VALUES ('vot', 'votisk');
INSERT INTO [country] ([id], [name]) VALUES ('wak', 'wakashansk sprog');
INSERT INTO [country] ([id], [name]) VALUES ('wal', 'walamo');
INSERT INTO [country] ([id], [name]) VALUES ('cy', 'walisisk');
INSERT INTO [country] ([id], [name]) VALUES ('war', 'waray');
INSERT INTO [country] ([id], [name]) VALUES ('was', 'washo');
INSERT INTO [country] ([id], [name]) VALUES ('wo', 'wolof');
INSERT INTO [country] ([id], [name]) VALUES ('xh', 'xhosa');
INSERT INTO [country] ([id], [name]) VALUES ('sah', 'yakut');
INSERT INTO [country] ([id], [name]) VALUES ('yao', 'yao');
INSERT INTO [country] ([id], [name]) VALUES ('yo', 'yoruba');
INSERT INTO [country] ([id], [name]) VALUES ('ypk', 'yupisk sprog');
INSERT INTO [country] ([id], [name]) VALUES ('znd', 'zande');
INSERT INTO [country] ([id], [name]) VALUES ('zap', 'zapotec');
INSERT INTO [country] ([id], [name]) VALUES ('zza', 'zaza');
INSERT INTO [country] ([id], [name]) VALUES ('zen', 'zenaga');
INSERT INTO [country] ([id], [name]) VALUES ('za', 'zhuang');
INSERT INTO [country] ([id], [name]) VALUES ('zu', 'zulu');
INSERT INTO [country] ([id], [name]) VALUES ('zun', 'zuni');
INSERT INTO [country] ([id], [name]) VALUES ('frs', 'østfrisisk');
INSERT INTO [country] ([id], [name]) VALUES ('de_AT', 'østrigsk tysk');
INSERT INTO [country] ([id], [name]) VALUES ('hsb', 'øvresorbisk');
