CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('kln', 'Kalenjin');
INSERT INTO "country" ("id", "name") VALUES ('ak', 'kutitab Aka');
INSERT INTO "country" ("id", "name") VALUES ('am', 'kutitab Amariek');
INSERT INTO "country" ("id", "name") VALUES ('ar', 'kutitab Arabuk');
INSERT INTO "country" ("id", "name") VALUES ('be', 'kutitab Belarusa');
INSERT INTO "country" ("id", "name") VALUES ('bn', 'kutitab Bengali');
INSERT INTO "country" ("id", "name") VALUES ('nl', 'kutitab Boa');
INSERT INTO "country" ("id", "name") VALUES ('bg', 'kutitab Bulgaria');
INSERT INTO "country" ("id", "name") VALUES ('my', 'kutitab Burma');
INSERT INTO "country" ("id", "name") VALUES ('cs', 'kutitab Chek');
INSERT INTO "country" ("id", "name") VALUES ('de', 'kutitab Chermani');
INSERT INTO "country" ("id", "name") VALUES ('zh', 'kutitab China');
INSERT INTO "country" ("id", "name") VALUES ('es', 'kutitab Espianik');
INSERT INTO "country" ("id", "name") VALUES ('el', 'kutitab Greece');
INSERT INTO "country" ("id", "name") VALUES ('hu', 'kutitab Hangari');
INSERT INTO "country" ("id", "name") VALUES ('ha', 'kutitab Hausa');
INSERT INTO "country" ("id", "name") VALUES ('ig', 'kutitab Igbo');
INSERT INTO "country" ("id", "name") VALUES ('id', 'kutitab Indonesia');
INSERT INTO "country" ("id", "name") VALUES ('km', 'kutitab Kher nebo Kwen');
INSERT INTO "country" ("id", "name") VALUES ('fr', 'kutitab Kifaransa');
INSERT INTO "country" ("id", "name") VALUES ('rw', 'kutitab Kinyarwanda');
INSERT INTO "country" ("id", "name") VALUES ('ko', 'kutitab Korea');
INSERT INTO "country" ("id", "name") VALUES ('hi', 'kutitab Maindiik');
INSERT INTO "country" ("id", "name") VALUES ('ms', 'kutitab Malay');
INSERT INTO "country" ("id", "name") VALUES ('ne', 'kutitab Nepali');
INSERT INTO "country" ("id", "name") VALUES ('fa', 'kutitab Persia');
INSERT INTO "country" ("id", "name") VALUES ('pt', 'kutitab Portugal');
INSERT INTO "country" ("id", "name") VALUES ('pa', 'kutitab Punjab');
INSERT INTO "country" ("id", "name") VALUES ('ro', 'kutitab Romaniek');
INSERT INTO "country" ("id", "name") VALUES ('ru', 'kutitab Russia');
INSERT INTO "country" ("id", "name") VALUES ('so', 'kutitab Somaliek');
INSERT INTO "country" ("id", "name") VALUES ('sv', 'kutitab Sweden');
INSERT INTO "country" ("id", "name") VALUES ('it', 'kutitab Talianek');
INSERT INTO "country" ("id", "name") VALUES ('ta', 'kutitab Tamil');
INSERT INTO "country" ("id", "name") VALUES ('th', 'kutitab Thailand');
INSERT INTO "country" ("id", "name") VALUES ('tr', 'kutitab Turkey');
INSERT INTO "country" ("id", "name") VALUES ('en', 'kutitab Uingeresa');
INSERT INTO "country" ("id", "name") VALUES ('uk', 'kutitab Ukraine');
INSERT INTO "country" ("id", "name") VALUES ('ur', 'kutitab Urdu');
INSERT INTO "country" ("id", "name") VALUES ('vi', 'kutitab Vietnam');
INSERT INTO "country" ("id", "name") VALUES ('yo', 'kutitab Yoruba');
INSERT INTO "country" ("id", "name") VALUES ('zu', 'kutitab Zulu');
INSERT INTO "country" ("id", "name") VALUES ('ja', 'kutitap Japan');
INSERT INTO "country" ("id", "name") VALUES ('jv', 'kutitap Javanese');
INSERT INTO "country" ("id", "name") VALUES ('pl', 'kutitap Poland');
