CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('ar', 'අරාබි');
INSERT INTO [country] ([id], [name]) VALUES ('hy', 'ආර්මේනියානු');
INSERT INTO [country] ([id], [name]) VALUES ('en_US', 'ඇමෙරිකානු ඉංග්‍රීසි');
INSERT INTO [country] ([id], [name]) VALUES ('en', 'ඉංග්‍රීසි');
INSERT INTO [country] ([id], [name]) VALUES ('it', 'ඉතාලි');
INSERT INTO [country] ([id], [name]) VALUES ('de_AT', 'ඔස්ට්‍රියානු ජර්මන්');
INSERT INTO [country] ([id], [name]) VALUES ('en_AU', 'ඕස්ට්‍රේලියානු ඉංග්‍රීසි');
INSERT INTO [country] ([id], [name]) VALUES ('kn', 'කණ්ණඩ');
INSERT INTO [country] ([id], [name]) VALUES ('en_CA', 'කැනේඩියානු ඉංග්‍රීසි');
INSERT INTO [country] ([id], [name]) VALUES ('fr_CA', 'කැනේඩියානු ප්‍රංශ');
INSERT INTO [country] ([id], [name]) VALUES ('ko', 'කොරියානු');
INSERT INTO [country] ([id], [name]) VALUES ('gu', 'ගුජරාටි');
INSERT INTO [country] ([id], [name]) VALUES ('el', 'ග්‍රීක');
INSERT INTO [country] ([id], [name]) VALUES ('zh', 'චීන');
INSERT INTO [country] ([id], [name]) VALUES ('ja', 'ජපන්');
INSERT INTO [country] ([id], [name]) VALUES ('de', 'ජර්මන්');
INSERT INTO [country] ([id], [name]) VALUES ('bo', 'ටිබෙට්');
INSERT INTO [country] ([id], [name]) VALUES ('th', 'තායි');
INSERT INTO [country] ([id], [name]) VALUES ('tr', 'තුර්කි');
INSERT INTO [country] ([id], [name]) VALUES ('dv', 'දිවෙහි');
INSERT INTO [country] ([id], [name]) VALUES ('ta', 'දෙමළ');
INSERT INTO [country] ([id], [name]) VALUES ('fa', 'පර්සියානු');
INSERT INTO [country] ([id], [name]) VALUES ('pt', 'පෘතුගීසි');
INSERT INTO [country] ([id], [name]) VALUES ('pl', 'පෝලන්ත');
INSERT INTO [country] ([id], [name]) VALUES ('fr', 'ප්‍රංශ');
INSERT INTO [country] ([id], [name]) VALUES ('bn', 'බෙංගලි');
INSERT INTO [country] ([id], [name]) VALUES ('en_GB', 'බ්‍රිතාන්‍ය ඉංග්‍රීසින්‍ය');
INSERT INTO [country] ([id], [name]) VALUES ('ms', 'මැලේ');
INSERT INTO [country] ([id], [name]) VALUES ('ru', 'රුසියානු');
INSERT INTO [country] ([id], [name]) VALUES ('la', 'ලතින්');
INSERT INTO [country] ([id], [name]) VALUES ('nl', 'ලන්දේසි');
INSERT INTO [country] ([id], [name]) VALUES ('sa', 'සංස්කෘත');
INSERT INTO [country] ([id], [name]) VALUES ('si', 'සිංහල');
INSERT INTO [country] ([id], [name]) VALUES ('es', 'ස්පාඤ්ඤ');
INSERT INTO [country] ([id], [name]) VALUES ('hu', 'හන්ගේරියානු');
INSERT INTO [country] ([id], [name]) VALUES ('hi', 'හින්දි');
INSERT INTO [country] ([id], [name]) VALUES ('he', 'හීබෲ');
