CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('af', 'Afirkanci');
INSERT INTO "country" ("id", "name") VALUES ('am', 'Amharic');
INSERT INTO "country" ("id", "name") VALUES ('hy', 'Armeniyanci');
INSERT INTO "country" ("id", "name") VALUES ('as', 'Asamisanci');
INSERT INTO "country" ("id", "name") VALUES ('az', 'Azerbaijanci');
INSERT INTO "country" ("id", "name") VALUES ('gl', 'Bagalike');
INSERT INTO "country" ("id", "name") VALUES ('hi', 'Bahinde');
INSERT INTO "country" ("id", "name") VALUES ('sl', 'Basulabe');
INSERT INTO "country" ("id", "name") VALUES ('sk', 'Basulake');
INSERT INTO "country" ("id", "name") VALUES ('tr', 'Baturke');
INSERT INTO "country" ("id", "name") VALUES ('xh', 'Bazosa');
INSERT INTO "country" ("id", "name") VALUES ('zu', 'Bazule');
INSERT INTO "country" ("id", "name") VALUES ('be', 'Belarushiyanci');
INSERT INTO "country" ("id", "name") VALUES ('bh', 'Bihari');
INSERT INTO "country" ("id", "name") VALUES ('bs', 'Bosniyanci');
INSERT INTO "country" ("id", "name") VALUES ('bg', 'Bulgeriyan');
INSERT INTO "country" ("id", "name") VALUES ('br', 'Buretananci');
INSERT INTO "country" ("id", "name") VALUES ('sq', 'D\'an/\'Yar Kabilar Albaniya');
INSERT INTO "country" ("id", "name") VALUES ('eo', 'D\'an/\'Yar Kabilar Andalus');
INSERT INTO "country" ("id", "name") VALUES ('ne', 'D\'an/\'Yar Kabilar Nepal');
INSERT INTO "country" ("id", "name") VALUES ('ta', 'D\'an/\'Yar Kabilar Tamil');
INSERT INTO "country" ("id", "name") VALUES ('te', 'D\'an/\'Yar Kabilar Telug');
INSERT INTO "country" ("id", "name") VALUES ('ga', 'Dan Ailan');
INSERT INTO "country" ("id", "name") VALUES ('bn', 'Dan Bengal');
INSERT INTO "country" ("id", "name") VALUES ('fil', 'Dan Filifin');
INSERT INTO "country" ("id", "name") VALUES ('la', 'Dan Kabilar Latin');
INSERT INTO "country" ("id", "name") VALUES ('ms', 'Dan Kabilar Male');
INSERT INTO "country" ("id", "name") VALUES ('mk', 'Dan Masedoniya');
INSERT INTO "country" ("id", "name") VALUES ('uk', 'Dan Ukirain');
INSERT INTO "country" ("id", "name") VALUES ('pa', 'Dan/\'Yar Garin Punjab');
INSERT INTO "country" ("id", "name") VALUES ('eu', 'Dan/\'Yar Kabilar Bas');
INSERT INTO "country" ("id", "name") VALUES ('kn', 'Dan/\'Yar Kabilar Kannada');
INSERT INTO "country" ("id", "name") VALUES ('da', 'Danish');
INSERT INTO "country" ("id", "name") VALUES ('fr', 'Faranshi');
INSERT INTO "country" ("id", "name") VALUES ('fo', 'Faroese');
INSERT INTO "country" ("id", "name") VALUES ('pt_BR', 'Fotigis (Burazil)');
INSERT INTO "country" ("id", "name") VALUES ('el', 'Girkanci');
INSERT INTO "country" ("id", "name") VALUES ('gu', 'Gujarati');
INSERT INTO "country" ("id", "name") VALUES ('gn', 'Guwaraniyanci');
INSERT INTO "country" ("id", "name") VALUES ('ha', 'Haoussa');
INSERT INTO "country" ("id", "name") VALUES ('ar', 'Harshen Larabci');
INSERT INTO "country" ("id", "name") VALUES ('mt', 'Harshen Maltis');
INSERT INTO "country" ("id", "name") VALUES ('sw', 'Harshen Suwahili');
INSERT INTO "country" ("id", "name") VALUES ('hu', 'Hongeriyanci');
INSERT INTO "country" ("id", "name") VALUES ('id', 'Indonesiyan');
INSERT INTO "country" ("id", "name") VALUES ('ie', 'Intagulanci');
INSERT INTO "country" ("id", "name") VALUES ('et', 'Istoniyanci');
INSERT INTO "country" ("id", "name") VALUES ('it', 'Italiyanci');
INSERT INTO "country" ("id", "name") VALUES ('ja', 'Jafananci');
INSERT INTO "country" ("id", "name") VALUES ('de', 'Jamusanchi');
INSERT INTO "country" ("id", "name") VALUES ('jv', 'Javanisanci');
INSERT INTO "country" ("id", "name") VALUES ('ka', 'Jojiyanci');
INSERT INTO "country" ("id", "name") VALUES ('vi', 'K\'abilan Biyetnam');
INSERT INTO "country" ("id", "name") VALUES ('fy', 'K\'abilan Firsi');
INSERT INTO "country" ("id", "name") VALUES ('mr', 'K\'abilan Marathi');
INSERT INTO "country" ("id", "name") VALUES ('gd', 'K\'abilan Scots Gaelic');
INSERT INTO "country" ("id", "name") VALUES ('ml', 'Kabilar Maleyalam');
INSERT INTO "country" ("id", "name") VALUES ('cy', 'Kabilar Welsh');
INSERT INTO "country" ("id", "name") VALUES ('km', 'Kambodiyanci');
INSERT INTO "country" ("id", "name") VALUES ('ca', 'Kataloniyanci');
INSERT INTO "country" ("id", "name") VALUES ('ky', 'Kirgizanci');
INSERT INTO "country" ("id", "name") VALUES ('tlh', 'Klingon');
INSERT INTO "country" ("id", "name") VALUES ('ku', 'Kurdanci');
INSERT INTO "country" ("id", "name") VALUES ('hr', 'Kuroshiyan');
INSERT INTO "country" ("id", "name") VALUES ('sh', 'Kuroweshiyancin-Sabiya');
INSERT INTO "country" ("id", "name") VALUES ('lo', 'Laothian');
INSERT INTO "country" ("id", "name") VALUES ('lv', 'Latbiyanci');
INSERT INTO "country" ("id", "name") VALUES ('ln', 'Lingala');
INSERT INTO "country" ("id", "name") VALUES ('lt', 'Lituweniyanci');
INSERT INTO "country" ("id", "name") VALUES ('mn', 'Mongolian');
INSERT INTO "country" ("id", "name") VALUES ('es', 'Mutanen Espanya');
INSERT INTO "country" ("id", "name") VALUES ('or', 'Oriyanci');
INSERT INTO "country" ("id", "name") VALUES ('oc', 'Ositanci');
INSERT INTO "country" ("id", "name") VALUES ('ps', 'Pashtanci');
INSERT INTO "country" ("id", "name") VALUES ('fa', 'Persian');
INSERT INTO "country" ("id", "name") VALUES ('ru', 'Rashanci');
INSERT INTO "country" ("id", "name") VALUES ('ro', 'Romaniyanci');
INSERT INTO "country" ("id", "name") VALUES ('sr', 'Sabiyan');
INSERT INTO "country" ("id", "name") VALUES ('st', 'Sesotanci');
INSERT INTO "country" ("id", "name") VALUES ('sd', 'Sindiyanci');
INSERT INTO "country" ("id", "name") VALUES ('si', 'Sinhalanci');
INSERT INTO "country" ("id", "name") VALUES ('so', 'Somaali');
INSERT INTO "country" ("id", "name") VALUES ('su', 'Sundanese');
INSERT INTO "country" ("id", "name") VALUES ('th', 'Tayanci');
INSERT INTO "country" ("id", "name") VALUES ('ti', 'Tigriyanci');
INSERT INTO "country" ("id", "name") VALUES ('tw', 'Tiwiniyanci');
INSERT INTO "country" ("id", "name") VALUES ('tk', 'Tukmenistanci');
INSERT INTO "country" ("id", "name") VALUES ('en', 'Turanci');
INSERT INTO "country" ("id", "name") VALUES ('ug', 'Ugiranci');
INSERT INTO "country" ("id", "name") VALUES ('ur', 'Urdu');
INSERT INTO "country" ("id", "name") VALUES ('uz', 'Uzbek');
INSERT INTO "country" ("id", "name") VALUES ('he', 'Yahudanci');
INSERT INTO "country" ("id", "name") VALUES ('ia', 'Yare Tsakanin Kasashe');
INSERT INTO "country" ("id", "name") VALUES ('cs', 'Yaren Jamhuriyar Cek');
INSERT INTO "country" ("id", "name") VALUES ('nn', 'Yaren Kasar Norway');
INSERT INTO "country" ("id", "name") VALUES ('pt_PT', 'Yaren Kasar Portugal');
INSERT INTO "country" ("id", "name") VALUES ('fi', 'Yaren mutanen Finland');
INSERT INTO "country" ("id", "name") VALUES ('nl', 'Yaren mutanen Holland');
INSERT INTO "country" ("id", "name") VALUES ('is', 'Yaren mutanen Iceland');
INSERT INTO "country" ("id", "name") VALUES ('ko', 'Yaren mutanen Koriya');
INSERT INTO "country" ("id", "name") VALUES ('no', 'Yaren mutanen Norway');
INSERT INTO "country" ("id", "name") VALUES ('pl', 'Yaren mutanen Poland');
INSERT INTO "country" ("id", "name") VALUES ('pt', 'Yaren mutanen Portugal');
INSERT INTO "country" ("id", "name") VALUES ('sv', 'Yaren mutanen Sweden');
INSERT INTO "country" ("id", "name") VALUES ('sa', 'sanskrit');
