CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('ak', 'akan');
INSERT INTO "country" ("id", "name") VALUES ('de', 'alman');
INSERT INTO "country" ("id", "name") VALUES ('am', 'amarik');
INSERT INTO "country" ("id", "name") VALUES ('en', 'angle');
INSERT INTO "country" ("id", "name") VALUES ('ar', 'arab');
INSERT INTO "country" ("id", "name") VALUES ('bn', 'bengali');
INSERT INTO "country" ("id", "name") VALUES ('be', 'bieloris');
INSERT INTO "country" ("id", "name") VALUES ('bg', 'bilgar');
INSERT INTO "country" ("id", "name") VALUES ('my', 'birman');
INSERT INTO "country" ("id", "name") VALUES ('es', 'espagnol');
INSERT INTO "country" ("id", "name") VALUES ('fr', 'franse');
INSERT INTO "country" ("id", "name") VALUES ('el', 'grek');
INSERT INTO "country" ("id", "name") VALUES ('ha', 'haoussa');
INSERT INTO "country" ("id", "name") VALUES ('hi', 'hindi');
INSERT INTO "country" ("id", "name") VALUES ('hu', 'hongrwa');
INSERT INTO "country" ("id", "name") VALUES ('ig', 'igbo');
INSERT INTO "country" ("id", "name") VALUES ('uk', 'ikrenien');
INSERT INTO "country" ("id", "name") VALUES ('id', 'indonezien');
INSERT INTO "country" ("id", "name") VALUES ('it', 'italien');
INSERT INTO "country" ("id", "name") VALUES ('km', 'khmer, santral');
INSERT INTO "country" ("id", "name") VALUES ('ko', 'koreen');
INSERT INTO "country" ("id", "name") VALUES ('mfe', 'kreol morisien');
INSERT INTO "country" ("id", "name") VALUES ('ms', 'male');
INSERT INTO "country" ("id", "name") VALUES ('ne', 'nepale');
INSERT INTO "country" ("id", "name") VALUES ('nl', 'olande');
INSERT INTO "country" ("id", "name") VALUES ('ur', 'ourdou');
INSERT INTO "country" ("id", "name") VALUES ('pa', 'penjabi');
INSERT INTO "country" ("id", "name") VALUES ('fa', 'persan');
INSERT INTO "country" ("id", "name") VALUES ('pl', 'polone');
INSERT INTO "country" ("id", "name") VALUES ('pt', 'portige');
INSERT INTO "country" ("id", "name") VALUES ('ru', 'ris');
INSERT INTO "country" ("id", "name") VALUES ('ro', 'roumin');
INSERT INTO "country" ("id", "name") VALUES ('rw', 'rwanda');
INSERT INTO "country" ("id", "name") VALUES ('zh', 'sinwa, mandarin');
INSERT INTO "country" ("id", "name") VALUES ('so', 'somali');
INSERT INTO "country" ("id", "name") VALUES ('sv', 'swedwa');
INSERT INTO "country" ("id", "name") VALUES ('ta', 'tamoul');
INSERT INTO "country" ("id", "name") VALUES ('cs', 'tchek');
INSERT INTO "country" ("id", "name") VALUES ('th', 'thaï');
INSERT INTO "country" ("id", "name") VALUES ('tr', 'tirk');
INSERT INTO "country" ("id", "name") VALUES ('vi', 'vietnamien');
INSERT INTO "country" ("id", "name") VALUES ('yo', 'yoruba');
INSERT INTO "country" ("id", "name") VALUES ('ja', 'zapone');
INSERT INTO "country" ("id", "name") VALUES ('jv', 'zavane');
INSERT INTO "country" ("id", "name") VALUES ('zu', 'zoulou');
