CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('ab', 'abxazca');
INSERT INTO "country" ("id", "name") VALUES ('ada', 'adangme dili');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hans', 'adi çincə');
INSERT INTO "country" ("id", "name") VALUES ('ady', 'aduge dili');
INSERT INTO "country" ("id", "name") VALUES ('aa', 'afarca');
INSERT INTO "country" ("id", "name") VALUES ('afh', 'afrihili dili');
INSERT INTO "country" ("id", "name") VALUES ('af', 'Afrikaanca');
INSERT INTO "country" ("id", "name") VALUES ('afa', 'afro-aziat dili');
INSERT INTO "country" ("id", "name") VALUES ('akk', 'akadianca');
INSERT INTO "country" ("id", "name") VALUES ('ak', 'akanca');
INSERT INTO "country" ("id", "name") VALUES ('ace', 'akin dili');
INSERT INTO "country" ("id", "name") VALUES ('ach', 'akoli dili');
INSERT INTO "country" ("id", "name") VALUES ('sq', 'Albanca');
INSERT INTO "country" ("id", "name") VALUES ('ale', 'aleutca');
INSERT INTO "country" ("id", "name") VALUES ('alg', 'algonguyan dili');
INSERT INTO "country" ("id", "name") VALUES ('gem', 'Alman dili');
INSERT INTO "country" ("id", "name") VALUES ('de', 'almanca');
INSERT INTO "country" ("id", "name") VALUES ('de_AT', 'almanca (AT)');
INSERT INTO "country" ("id", "name") VALUES ('tut', 'altaik dili');
INSERT INTO "country" ("id", "name") VALUES ('am', 'amarikcə');
INSERT INTO "country" ("id", "name") VALUES ('anp', 'angikə dili');
INSERT INTO "country" ("id", "name") VALUES ('apa', 'apaçi dili');
INSERT INTO "country" ("id", "name") VALUES ('an', 'aragonca');
INSERT INTO "country" ("id", "name") VALUES ('arc', 'aramik dili');
INSERT INTO "country" ("id", "name") VALUES ('arp', 'arapaho dili');
INSERT INTO "country" ("id", "name") VALUES ('arn', 'araukanca');
INSERT INTO "country" ("id", "name") VALUES ('arw', 'aravakça');
INSERT INTO "country" ("id", "name") VALUES ('rup', 'aromanca');
INSERT INTO "country" ("id", "name") VALUES ('ast', 'asturicə');
INSERT INTO "country" ("id", "name") VALUES ('nds', 'aşağı almanca');
INSERT INTO "country" ("id", "name") VALUES ('dsb', 'aşağı sorbca');
INSERT INTO "country" ("id", "name") VALUES ('ath', 'atapaskanca');
INSERT INTO "country" ("id", "name") VALUES ('cch', 'atsamca');
INSERT INTO "country" ("id", "name") VALUES ('awa', 'avadicə');
INSERT INTO "country" ("id", "name") VALUES ('av', 'avarikcə');
INSERT INTO "country" ("id", "name") VALUES ('ae', 'avestanca');
INSERT INTO "country" ("id", "name") VALUES ('aus', 'avstraliyca');
INSERT INTO "country" ("id", "name") VALUES ('map', 'avstronezicə');
INSERT INTO "country" ("id", "name") VALUES ('ay', 'aymarca');
INSERT INTO "country" ("id", "name") VALUES ('ain', 'aynuca');
INSERT INTO "country" ("id", "name") VALUES ('az', 'azərbaycanca');
INSERT INTO "country" ("id", "name") VALUES ('ban', 'balincə');
INSERT INTO "country" ("id", "name") VALUES ('bat', 'baltik dili');
INSERT INTO "country" ("id", "name") VALUES ('bal', 'baluc dili');
INSERT INTO "country" ("id", "name") VALUES ('bm', 'bambara dili');
INSERT INTO "country" ("id", "name") VALUES ('bai', 'bamilek dili');
INSERT INTO "country" ("id", "name") VALUES ('bad', 'banda dili');
INSERT INTO "country" ("id", "name") VALUES ('bnt', 'bantu dili');
INSERT INTO "country" ("id", "name") VALUES ('bas', 'basa dili');
INSERT INTO "country" ("id", "name") VALUES ('eu', 'bask dili');
INSERT INTO "country" ("id", "name") VALUES ('ba', 'başkir dili');
INSERT INTO "country" ("id", "name") VALUES ('btk', 'batak dili');
INSERT INTO "country" ("id", "name") VALUES ('bej', 'beja dili');
INSERT INTO "country" ("id", "name") VALUES ('be', 'belarusca');
INSERT INTO "country" ("id", "name") VALUES ('bem', 'bemba dili');
INSERT INTO "country" ("id", "name") VALUES ('bn', 'Benqal dili');
INSERT INTO "country" ("id", "name") VALUES ('ber', 'berber dili');
INSERT INTO "country" ("id", "name") VALUES ('bho', 'bxoçpuri dili');
INSERT INTO "country" ("id", "name") VALUES ('bh', 'biharicə');
INSERT INTO "country" ("id", "name") VALUES ('bik', 'bikolca');
INSERT INTO "country" ("id", "name") VALUES ('byn', 'bilincə');
INSERT INTO "country" ("id", "name") VALUES ('und', 'bilinməyən vəya gəcərsiz dil');
INSERT INTO "country" ("id", "name") VALUES ('bin', 'bini dili');
INSERT INTO "country" ("id", "name") VALUES ('bi', 'bislama dili');
INSERT INTO "country" ("id", "name") VALUES ('zbl', 'blisimbols dili');
INSERT INTO "country" ("id", "name") VALUES ('bg', 'bolqarca');
INSERT INTO "country" ("id", "name") VALUES ('bs', 'bosniya dili');
INSERT INTO "country" ("id", "name") VALUES ('bra', 'braj dili');
INSERT INTO "country" ("id", "name") VALUES ('br', 'Bretonca');
INSERT INTO "country" ("id", "name") VALUES ('bug', 'bugin dili');
INSERT INTO "country" ("id", "name") VALUES ('my', 'burmis dili');
INSERT INTO "country" ("id", "name") VALUES ('bua', 'buryat dili');
INSERT INTO "country" ("id", "name") VALUES ('alt', 'cənub altay dili');
INSERT INTO "country" ("id", "name") VALUES ('sai', 'cənub amerika yerli dili');
INSERT INTO "country" ("id", "name") VALUES ('nr', 'cənub ndebele dili');
INSERT INTO "country" ("id", "name") VALUES ('sma', 'cənub sami dili');
INSERT INTO "country" ("id", "name") VALUES ('chg', 'çağatay dili');
INSERT INTO "country" ("id", "name") VALUES ('cmc', 'çamik dili');
INSERT INTO "country" ("id", "name") VALUES ('ch', 'çamoro dili');
INSERT INTO "country" ("id", "name") VALUES ('ce', 'çeçen dili');
INSERT INTO "country" ("id", "name") VALUES ('cs', 'çex dili');
INSERT INTO "country" ("id", "name") VALUES ('mis', 'çeşitli diller');
INSERT INTO "country" ("id", "name") VALUES ('chy', 'çeyen dili');
INSERT INTO "country" ("id", "name") VALUES ('chb', 'çibçə dili');
INSERT INTO "country" ("id", "name") VALUES ('zh', 'çincə');
INSERT INTO "country" ("id", "name") VALUES ('chn', 'çinuk ləhçəsi');
INSERT INTO "country" ("id", "name") VALUES ('chp', 'çipevyan dili');
INSERT INTO "country" ("id", "name") VALUES ('chr', 'çiroki dili');
INSERT INTO "country" ("id", "name") VALUES ('cho', 'çoktau dili');
INSERT INTO "country" ("id", "name") VALUES ('chk', 'çukiz dili');
INSERT INTO "country" ("id", "name") VALUES ('cv', 'çuvaş dili');
INSERT INTO "country" ("id", "name") VALUES ('dak', 'dakota dili');
INSERT INTO "country" ("id", "name") VALUES ('da', 'danimarka dili');
INSERT INTO "country" ("id", "name") VALUES ('dar', 'darqva dili');
INSERT INTO "country" ("id", "name") VALUES ('day', 'dayak dili');
INSERT INTO "country" ("id", "name") VALUES ('del', 'delaver dili');
INSERT INTO "country" ("id", "name") VALUES ('inc', 'diqər hint dili');
INSERT INTO "country" ("id", "name") VALUES ('din', 'dinka dili');
INSERT INTO "country" ("id", "name") VALUES ('dv', 'diveh dili');
INSERT INTO "country" ("id", "name") VALUES ('doi', 'doqri dili');
INSERT INTO "country" ("id", "name") VALUES ('dgr', 'doqrib dili');
INSERT INTO "country" ("id", "name") VALUES ('dra', 'dravid dili');
INSERT INTO "country" ("id", "name") VALUES ('dua', 'duala dili');
INSERT INTO "country" ("id", "name") VALUES ('dyu', 'dyula dili');
INSERT INTO "country" ("id", "name") VALUES ('dz', 'dzonqa dili');
INSERT INTO "country" ("id", "name") VALUES ('efi', 'efik dili');
INSERT INTO "country" ("id", "name") VALUES ('eka', 'ekacuk dili');
INSERT INTO "country" ("id", "name") VALUES ('elx', 'elamit dili');
INSERT INTO "country" ("id", "name") VALUES ('hy', 'Ermənicə');
INSERT INTO "country" ("id", "name") VALUES ('myv', 'erzya dili');
INSERT INTO "country" ("id", "name") VALUES ('eo', 'esperanto dili');
INSERT INTO "country" ("id", "name") VALUES ('et', 'estonca');
INSERT INTO "country" ("id", "name") VALUES ('ee', 'eve dili');
INSERT INTO "country" ("id", "name") VALUES ('ewo', 'evondo dili');
INSERT INTO "country" ("id", "name") VALUES ('ar', 'Ərəbcə');
INSERT INTO "country" ("id", "name") VALUES ('fan', 'fang dili');
INSERT INTO "country" ("id", "name") VALUES ('fat', 'fanti dili');
INSERT INTO "country" ("id", "name") VALUES ('fo', 'farer dili');
INSERT INTO "country" ("id", "name") VALUES ('fa', 'farsca');
INSERT INTO "country" ("id", "name") VALUES ('fj', 'fiji dili');
INSERT INTO "country" ("id", "name") VALUES ('phi', 'filipin dili');
INSERT INTO "country" ("id", "name") VALUES ('fiu', 'fin-uğri dili');
INSERT INTO "country" ("id", "name") VALUES ('fi', 'fincə');
INSERT INTO "country" ("id", "name") VALUES ('nl_BE', 'flem dili');
INSERT INTO "country" ("id", "name") VALUES ('fon', 'fon dili');
INSERT INTO "country" ("id", "name") VALUES ('phn', 'foyenik dili');
INSERT INTO "country" ("id", "name") VALUES ('cpf', 'fransız kreol dili');
INSERT INTO "country" ("id", "name") VALUES ('fr', 'fransızca');
INSERT INTO "country" ("id", "name") VALUES ('fr_CA', 'fransızca (CA)');
INSERT INTO "country" ("id", "name") VALUES ('fy', 'frisk dili');
INSERT INTO "country" ("id", "name") VALUES ('fur', 'friul dili');
INSERT INTO "country" ("id", "name") VALUES ('ff', 'fula dili');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hant', 'gələnəksəl çincə');
INSERT INTO "country" ("id", "name") VALUES ('got', 'gotça');
INSERT INTO "country" ("id", "name") VALUES ('gu', 'gujarati dili');
INSERT INTO "country" ("id", "name") VALUES ('ka', 'gürcü dili');
INSERT INTO "country" ("id", "name") VALUES ('ht', 'haiti dili');
INSERT INTO "country" ("id", "name") VALUES ('ha', 'Hausa dili');
INSERT INTO "country" ("id", "name") VALUES ('hai', 'hayda dili');
INSERT INTO "country" ("id", "name") VALUES ('hz', 'Herer dili');
INSERT INTO "country" ("id", "name") VALUES ('hil', 'hiliqaynon dili');
INSERT INTO "country" ("id", "name") VALUES ('him', 'himaçali dili');
INSERT INTO "country" ("id", "name") VALUES ('hi', 'hindi dili');
INSERT INTO "country" ("id", "name") VALUES ('ine', 'hint-yevropa dili');
INSERT INTO "country" ("id", "name") VALUES ('ho', 'hiri motu dili');
INSERT INTO "country" ("id", "name") VALUES ('hit', 'hittit dili');
INSERT INTO "country" ("id", "name") VALUES ('nl', 'hollandca');
INSERT INTO "country" ("id", "name") VALUES ('hup', 'hupa dili');
INSERT INTO "country" ("id", "name") VALUES ('kha', 'xazi dili');
INSERT INTO "country" ("id", "name") VALUES ('hr', 'xorvatca');
INSERT INTO "country" ("id", "name") VALUES ('xh', 'xosa dili');
INSERT INTO "country" ("id", "name") VALUES ('kho', 'xotan dili');
INSERT INTO "country" ("id", "name") VALUES ('khi', 'xoyzan dili');
INSERT INTO "country" ("id", "name") VALUES ('iba', 'iban dili');
INSERT INTO "country" ("id", "name") VALUES ('pt_PT', 'İber portuqalca');
INSERT INTO "country" ("id", "name") VALUES ('es_ES', 'iber-ispanca');
INSERT INTO "country" ("id", "name") VALUES ('ijo', 'ico dili');
INSERT INTO "country" ("id", "name") VALUES ('io', 'ido dili');
INSERT INTO "country" ("id", "name") VALUES ('ig', 'iqbo dili');
INSERT INTO "country" ("id", "name") VALUES ('ilo', 'iloko dili');
INSERT INTO "country" ("id", "name") VALUES ('smn', 'inari sami');
INSERT INTO "country" ("id", "name") VALUES ('id', 'indoneziya dili');
INSERT INTO "country" ("id", "name") VALUES ('en', 'ingiliscə');
INSERT INTO "country" ("id", "name") VALUES ('en_US', 'ingiliscə (ABŞ)');
INSERT INTO "country" ("id", "name") VALUES ('en_AU', 'ingiliscə (AU)');
INSERT INTO "country" ("id", "name") VALUES ('en_CA', 'ingiliscə (CA)');
INSERT INTO "country" ("id", "name") VALUES ('en_GB', 'ingiliscə (GB)');
INSERT INTO "country" ("id", "name") VALUES ('cpe', 'inglis kreol dili');
INSERT INTO "country" ("id", "name") VALUES ('inh', 'inquş dili');
INSERT INTO "country" ("id", "name") VALUES ('ia', 'interlingua dili');
INSERT INTO "country" ("id", "name") VALUES ('ie', 'interlingue dili');
INSERT INTO "country" ("id", "name") VALUES ('iu', 'inuktikut dili');
INSERT INTO "country" ("id", "name") VALUES ('ik', 'inupiaq dili');
INSERT INTO "country" ("id", "name") VALUES ('ira', 'iranca');
INSERT INTO "country" ("id", "name") VALUES ('ga', 'irlandca');
INSERT INTO "country" ("id", "name") VALUES ('iro', 'irokuay dili');
INSERT INTO "country" ("id", "name") VALUES ('is', 'isləndcə');
INSERT INTO "country" ("id", "name") VALUES ('es', 'ispanca');
INSERT INTO "country" ("id", "name") VALUES ('gsw', 'isveç almanca');
INSERT INTO "country" ("id", "name") VALUES ('fr_CH', 'isveç fransızca');
INSERT INTO "country" ("id", "name") VALUES ('de_CH', 'isveç yüksək almancası');
INSERT INTO "country" ("id", "name") VALUES ('sv', 'isveçcə');
INSERT INTO "country" ("id", "name") VALUES ('sgn', 'işarət dili');
INSERT INTO "country" ("id", "name") VALUES ('it', 'italyanca');
INSERT INTO "country" ("id", "name") VALUES ('sem', 'ivrit dili');
INSERT INTO "country" ("id", "name") VALUES ('he', 'ivritcə');
INSERT INTO "country" ("id", "name") VALUES ('kaj', 'ju dili');
INSERT INTO "country" ("id", "name") VALUES ('jrb', 'jude-ərəbcə');
INSERT INTO "country" ("id", "name") VALUES ('jpr', 'judo-farsca');
INSERT INTO "country" ("id", "name") VALUES ('za', 'juənq dili');
INSERT INTO "country" ("id", "name") VALUES ('kbd', 'kabardca');
INSERT INTO "country" ("id", "name") VALUES ('kab', 'kabule dili');
INSERT INTO "country" ("id", "name") VALUES ('kac', 'kaçinca');
INSERT INTO "country" ("id", "name") VALUES ('cad', 'kado dili');
INSERT INTO "country" ("id", "name") VALUES ('kl', 'kalalisut dili');
INSERT INTO "country" ("id", "name") VALUES ('xal', 'kalmıqca');
INSERT INTO "country" ("id", "name") VALUES ('kam', 'kamba dili');
INSERT INTO "country" ("id", "name") VALUES ('km', 'kambodiya dili');
INSERT INTO "country" ("id", "name") VALUES ('kn', 'kannada dili');
INSERT INTO "country" ("id", "name") VALUES ('kr', 'kanur dili');
INSERT INTO "country" ("id", "name") VALUES ('krl', 'karelyan dili');
INSERT INTO "country" ("id", "name") VALUES ('kar', 'karen dili');
INSERT INTO "country" ("id", "name") VALUES ('car', 'karib dili');
INSERT INTO "country" ("id", "name") VALUES ('csb', 'kaşubyan dili');
INSERT INTO "country" ("id", "name") VALUES ('ca', 'katalanca');
INSERT INTO "country" ("id", "name") VALUES ('kaw', 'kavi dili');
INSERT INTO "country" ("id", "name") VALUES ('ceb', 'kebuano dili');
INSERT INTO "country" ("id", "name") VALUES ('cel', 'kelt dili');
INSERT INTO "country" ("id", "name") VALUES ('ks', 'kəşmir dili');
INSERT INTO "country" ("id", "name") VALUES ('ki', 'kikuyu dili');
INSERT INTO "country" ("id", "name") VALUES ('cu', 'kilsə slav dili');
INSERT INTO "country" ("id", "name") VALUES ('kmb', 'kimbundu dili');
INSERT INTO "country" ("id", "name") VALUES ('rw', 'kinyarvanda dili');
INSERT INTO "country" ("id", "name") VALUES ('tlh', 'klinqon');
INSERT INTO "country" ("id", "name") VALUES ('kv', 'komi dili');
INSERT INTO "country" ("id", "name") VALUES ('kok', 'konkan dili');
INSERT INTO "country" ("id", "name") VALUES ('kg', 'konqo dili');
INSERT INTO "country" ("id", "name") VALUES ('cop', 'kopt dili');
INSERT INTO "country" ("id", "name") VALUES ('ko', 'koreya dili');
INSERT INTO "country" ("id", "name") VALUES ('kw', 'korniş dili');
INSERT INTO "country" ("id", "name") VALUES ('kfo', 'koro dili');
INSERT INTO "country" ("id", "name") VALUES ('co', 'korsikan dili');
INSERT INTO "country" ("id", "name") VALUES ('kos', 'kosreyan dili');
INSERT INTO "country" ("id", "name") VALUES ('kpe', 'kpelle dili');
INSERT INTO "country" ("id", "name") VALUES ('crp', 'kreol dili');
INSERT INTO "country" ("id", "name") VALUES ('crh', 'krım türkçə');
INSERT INTO "country" ("id", "name") VALUES ('cr', 'kri dili');
INSERT INTO "country" ("id", "name") VALUES ('mus', 'krik dili');
INSERT INTO "country" ("id", "name") VALUES ('kro', 'kru dili');
INSERT INTO "country" ("id", "name") VALUES ('kj', 'kuanyama dili');
INSERT INTO "country" ("id", "name") VALUES ('qu', 'kuechya dili');
INSERT INTO "country" ("id", "name") VALUES ('kum', 'kumuk dili');
INSERT INTO "country" ("id", "name") VALUES ('kru', 'kurux dili');
INSERT INTO "country" ("id", "name") VALUES ('cus', 'kuşitik dili');
INSERT INTO "country" ("id", "name") VALUES ('kut', 'kutenay dili');
INSERT INTO "country" ("id", "name") VALUES ('ku', 'kürdcə');
INSERT INTO "country" ("id", "name") VALUES ('gaa', 'qa dili');
INSERT INTO "country" ("id", "name") VALUES ('gba', 'qabaya dili');
INSERT INTO "country" ("id", "name") VALUES ('gl', 'qalisian dili');
INSERT INTO "country" ("id", "name") VALUES ('lg', 'qanda dili');
INSERT INTO "country" ("id", "name") VALUES ('kaa', 'qara-qalpaq dili');
INSERT INTO "country" ("id", "name") VALUES ('krc', 'qaraçay-balkar dili');
INSERT INTO "country" ("id", "name") VALUES ('haw', 'Qavayca');
INSERT INTO "country" ("id", "name") VALUES ('cau', 'qavqaz dili');
INSERT INTO "country" ("id", "name") VALUES ('gay', 'qayo dili');
INSERT INTO "country" ("id", "name") VALUES ('kk', 'qazax dili');
INSERT INTO "country" ("id", "name") VALUES ('gez', 'qez dili');
INSERT INTO "country" ("id", "name") VALUES ('goh', 'qədimi almanca');
INSERT INTO "country" ("id", "name") VALUES ('peo', 'qədimi farsca');
INSERT INTO "country" ("id", "name") VALUES ('fro', 'qədimi fransızca');
INSERT INTO "country" ("id", "name") VALUES ('ang', 'qədimi ingiliscə');
INSERT INTO "country" ("id", "name") VALUES ('sga', 'qədimi irlandca');
INSERT INTO "country" ("id", "name") VALUES ('egy', 'qədimi misir dili');
INSERT INTO "country" ("id", "name") VALUES ('non', 'qədimi norsca');
INSERT INTO "country" ("id", "name") VALUES ('pro', 'qədimi provensialca');
INSERT INTO "country" ("id", "name") VALUES ('grc', 'qədimi yunanca');
INSERT INTO "country" ("id", "name") VALUES ('ky', 'qırğızca');
INSERT INTO "country" ("id", "name") VALUES ('gil', 'qilbert gili');
INSERT INTO "country" ("id", "name") VALUES ('gon', 'qondi dili');
INSERT INTO "country" ("id", "name") VALUES ('gor', 'qorontalo dili');
INSERT INTO "country" ("id", "name") VALUES ('grb', 'qrebo dili');
INSERT INTO "country" ("id", "name") VALUES ('gn', 'quaranicə');
INSERT INTO "country" ("id", "name") VALUES ('gwi', 'qviçin dili');
INSERT INTO "country" ("id", "name") VALUES ('lad', 'ladin dili');
INSERT INTO "country" ("id", "name") VALUES ('lah', 'laxnda dili');
INSERT INTO "country" ("id", "name") VALUES ('lam', 'lamba dili');
INSERT INTO "country" ("id", "name") VALUES ('lo', 'laos dili');
INSERT INTO "country" ("id", "name") VALUES ('es_419', 'latın amerika ispancası');
INSERT INTO "country" ("id", "name") VALUES ('la', 'latınca');
INSERT INTO "country" ("id", "name") VALUES ('lv', 'latışca');
INSERT INTO "country" ("id", "name") VALUES ('lez', 'ləzqi dili');
INSERT INTO "country" ("id", "name") VALUES ('li', 'limburqiş dili');
INSERT INTO "country" ("id", "name") VALUES ('ln', 'Linqala dili');
INSERT INTO "country" ("id", "name") VALUES ('lt', 'litva dili');
INSERT INTO "country" ("id", "name") VALUES ('jbo', 'loğban dili');
INSERT INTO "country" ("id", "name") VALUES ('loz', 'lozi dili');
INSERT INTO "country" ("id", "name") VALUES ('lu', 'luba-katanqa dili');
INSERT INTO "country" ("id", "name") VALUES ('lua', 'luba-lulua dili');
INSERT INTO "country" ("id", "name") VALUES ('lb', 'luksemburq dili');
INSERT INTO "country" ("id", "name") VALUES ('smj', 'lule sami dili');
INSERT INTO "country" ("id", "name") VALUES ('lun', 'lunda dili');
INSERT INTO "country" ("id", "name") VALUES ('luo', 'luo dili');
INSERT INTO "country" ("id", "name") VALUES ('lus', 'lushayca');
INSERT INTO "country" ("id", "name") VALUES ('lui', 'luyseno dili');
INSERT INTO "country" ("id", "name") VALUES ('hu', 'macarca');
INSERT INTO "country" ("id", "name") VALUES ('mad', 'maduriz dili');
INSERT INTO "country" ("id", "name") VALUES ('mai', 'maitili dili');
INSERT INTO "country" ("id", "name") VALUES ('mak', 'makasar dili');
INSERT INTO "country" ("id", "name") VALUES ('mk', 'makedoniya dili');
INSERT INTO "country" ("id", "name") VALUES ('mag', 'maqahi dili');
INSERT INTO "country" ("id", "name") VALUES ('mg', 'malaqas dili');
INSERT INTO "country" ("id", "name") VALUES ('ml', 'malayalamca');
INSERT INTO "country" ("id", "name") VALUES ('ms', 'malayca');
INSERT INTO "country" ("id", "name") VALUES ('mt', 'malta dili');
INSERT INTO "country" ("id", "name") VALUES ('mnc', 'mançu dili');
INSERT INTO "country" ("id", "name") VALUES ('mdr', 'mandar dili');
INSERT INTO "country" ("id", "name") VALUES ('mni', 'manipüri dili');
INSERT INTO "country" ("id", "name") VALUES ('gv', 'manks dili');
INSERT INTO "country" ("id", "name") VALUES ('mno', 'manobo dili');
INSERT INTO "country" ("id", "name") VALUES ('mi', 'maori dili');
INSERT INTO "country" ("id", "name") VALUES ('mr', 'marati dili');
INSERT INTO "country" ("id", "name") VALUES ('chm', 'mari dili');
INSERT INTO "country" ("id", "name") VALUES ('mh', 'marşal dili');
INSERT INTO "country" ("id", "name") VALUES ('mwr', 'maruari dili');
INSERT INTO "country" ("id", "name") VALUES ('mas', 'masay dili');
INSERT INTO "country" ("id", "name") VALUES ('myn', 'maya dili');
INSERT INTO "country" ("id", "name") VALUES ('men', 'mende dili');
INSERT INTO "country" ("id", "name") VALUES ('man', 'məndinqo dili');
INSERT INTO "country" ("id", "name") VALUES ('cai', 'mərkəzi amerika indus dili');
INSERT INTO "country" ("id", "name") VALUES ('mic', 'mikmak dili');
INSERT INTO "country" ("id", "name") VALUES ('min', 'minanqkaban dili');
INSERT INTO "country" ("id", "name") VALUES ('mwl', 'mirand dili');
INSERT INTO "country" ("id", "name") VALUES ('moh', 'moxak dili');
INSERT INTO "country" ("id", "name") VALUES ('mdf', 'mokşa dili');
INSERT INTO "country" ("id", "name") VALUES ('mo', 'moldavca');
INSERT INTO "country" ("id", "name") VALUES ('mkh', 'mon-xmer dili');
INSERT INTO "country" ("id", "name") VALUES ('hmn', 'monq dili');
INSERT INTO "country" ("id", "name") VALUES ('lol', 'monqo dili');
INSERT INTO "country" ("id", "name") VALUES ('mn', 'monqolca');
INSERT INTO "country" ("id", "name") VALUES ('mos', 'mosi dili');
INSERT INTO "country" ("id", "name") VALUES ('mun', 'munda dili');
INSERT INTO "country" ("id", "name") VALUES ('nah', 'nahuatl dili');
INSERT INTO "country" ("id", "name") VALUES ('na', 'nauru dili');
INSERT INTO "country" ("id", "name") VALUES ('nv', 'navayo dili');
INSERT INTO "country" ("id", "name") VALUES ('nap', 'neapolital dili');
INSERT INTO "country" ("id", "name") VALUES ('ne', 'nepalca');
INSERT INTO "country" ("id", "name") VALUES ('new', 'nevari dili');
INSERT INTO "country" ("id", "name") VALUES ('nic', 'niger-kordofyan dili');
INSERT INTO "country" ("id", "name") VALUES ('ssa', 'nilo-sahara dili');
INSERT INTO "country" ("id", "name") VALUES ('tog', 'niyasa tonga dili');
INSERT INTO "country" ("id", "name") VALUES ('nyo', 'niyoro dili');
INSERT INTO "country" ("id", "name") VALUES ('niu', 'niyuan dili');
INSERT INTO "country" ("id", "name") VALUES ('nzi', 'nizima dili');
INSERT INTO "country" ("id", "name") VALUES ('nqo', 'nqo dili');
INSERT INTO "country" ("id", "name") VALUES ('ng', 'nqonka dili');
INSERT INTO "country" ("id", "name") VALUES ('nog', 'noqay dili');
INSERT INTO "country" ("id", "name") VALUES ('nb', 'norvec bokmal dili');
INSERT INTO "country" ("id", "name") VALUES ('no', 'norveç dili');
INSERT INTO "country" ("id", "name") VALUES ('nn', 'norveç ninorsk dili');
INSERT INTO "country" ("id", "name") VALUES ('nub', 'nubiy dili');
INSERT INTO "country" ("id", "name") VALUES ('nym', 'nyamvezi dili');
INSERT INTO "country" ("id", "name") VALUES ('ny', 'nyanca dili');
INSERT INTO "country" ("id", "name") VALUES ('nyn', 'nyankol dili');
INSERT INTO "country" ("id", "name") VALUES ('nia', 'nyas dili');
INSERT INTO "country" ("id", "name") VALUES ('oj', 'ocibva dili');
INSERT INTO "country" ("id", "name") VALUES ('oc', 'oksitanca');
INSERT INTO "country" ("id", "name") VALUES ('or', 'Oriyə dili');
INSERT INTO "country" ("id", "name") VALUES ('om', 'oromo dili');
INSERT INTO "country" ("id", "name") VALUES ('frm', 'ortacaq fransızca');
INSERT INTO "country" ("id", "name") VALUES ('dum', 'ortacaq hollandca');
INSERT INTO "country" ("id", "name") VALUES ('enm', 'ortacaq ingiliscə');
INSERT INTO "country" ("id", "name") VALUES ('mga', 'ortacaq irlandca');
INSERT INTO "country" ("id", "name") VALUES ('gmh', 'ortacaq yüksək almanca');
INSERT INTO "country" ("id", "name") VALUES ('osa', 'osage dili');
INSERT INTO "country" ("id", "name") VALUES ('os', 'osetik dili');
INSERT INTO "country" ("id", "name") VALUES ('ota', 'osman dili');
INSERT INTO "country" ("id", "name") VALUES ('oto', 'otomian dili');
INSERT INTO "country" ("id", "name") VALUES ('uz', 'özbəkcə');
INSERT INTO "country" ("id", "name") VALUES ('pal', 'paxlavi dili');
INSERT INTO "country" ("id", "name") VALUES ('pau', 'palayanca');
INSERT INTO "country" ("id", "name") VALUES ('pi', 'pali dili');
INSERT INTO "country" ("id", "name") VALUES ('pam', 'pampanqa dili');
INSERT INTO "country" ("id", "name") VALUES ('pag', 'panqasinan dili');
INSERT INTO "country" ("id", "name") VALUES ('paa', 'papua dili');
INSERT INTO "country" ("id", "name") VALUES ('pap', 'papyamento dili');
INSERT INTO "country" ("id", "name") VALUES ('pl', 'Polish dili');
INSERT INTO "country" ("id", "name") VALUES ('pon', 'ponpeyan dili');
INSERT INTO "country" ("id", "name") VALUES ('cpp', 'portugal kreol dili');
INSERT INTO "country" ("id", "name") VALUES ('pt', 'portuqalca');
INSERT INTO "country" ("id", "name") VALUES ('pra', 'prakrit dili');
INSERT INTO "country" ("id", "name") VALUES ('pa', 'puncab dili');
INSERT INTO "country" ("id", "name") VALUES ('ps', 'Puştu dili');
INSERT INTO "country" ("id", "name") VALUES ('raj', 'racastan dili');
INSERT INTO "country" ("id", "name") VALUES ('rap', 'rapanu dili');
INSERT INTO "country" ("id", "name") VALUES ('rar', 'rarotonqan dili');
INSERT INTO "country" ("id", "name") VALUES ('rom', 'roman dili');
INSERT INTO "country" ("id", "name") VALUES ('ro', 'rumın');
INSERT INTO "country" ("id", "name") VALUES ('rn', 'rundi dili');
INSERT INTO "country" ("id", "name") VALUES ('ru', 'rusca');
INSERT INTO "country" ("id", "name") VALUES ('root', 'rut dili');
INSERT INTO "country" ("id", "name") VALUES ('sal', 'salişan dili');
INSERT INTO "country" ("id", "name") VALUES ('sam', 'samaritan dili');
INSERT INTO "country" ("id", "name") VALUES ('sm', 'samoa dili');
INSERT INTO "country" ("id", "name") VALUES ('sad', 'sandave dili');
INSERT INTO "country" ("id", "name") VALUES ('sg', 'sanqo dili');
INSERT INTO "country" ("id", "name") VALUES ('sa', 'Sanskrit dili');
INSERT INTO "country" ("id", "name") VALUES ('sat', 'santal dili');
INSERT INTO "country" ("id", "name") VALUES ('sc', 'sardin dili');
INSERT INTO "country" ("id", "name") VALUES ('sas', 'sasak dili');
INSERT INTO "country" ("id", "name") VALUES ('sel', 'selkup dili');
INSERT INTO "country" ("id", "name") VALUES ('sr', 'serb dili');
INSERT INTO "country" ("id", "name") VALUES ('sh', 'serb-xorvatca');
INSERT INTO "country" ("id", "name") VALUES ('srr', 'serer dilii');
INSERT INTO "country" ("id", "name") VALUES ('st', 'Sesoto dili');
INSERT INTO "country" ("id", "name") VALUES ('smi', 'səmi dili');
INSERT INTO "country" ("id", "name") VALUES ('ii', 'siçuan yi dili');
INSERT INTO "country" ("id", "name") VALUES ('sid', 'sidamo dili');
INSERT INTO "country" ("id", "name") VALUES ('bla', 'siksikə dili');
INSERT INTO "country" ("id", "name") VALUES ('tsi', 'simşyan dili');
INSERT INTO "country" ("id", "name") VALUES ('sd', 'sindhi dili');
INSERT INTO "country" ("id", "name") VALUES ('si', 'sinhaliscə');
INSERT INTO "country" ("id", "name") VALUES ('sit', 'sino-tibet dili');
INSERT INTO "country" ("id", "name") VALUES ('sio', 'sioyan dili');
INSERT INTO "country" ("id", "name") VALUES ('syr', 'siryak dili');
INSERT INTO "country" ("id", "name") VALUES ('scn', 'sisili dili');
INSERT INTO "country" ("id", "name") VALUES ('sms', 'skolt dili');
INSERT INTO "country" ("id", "name") VALUES ('gd', 'skot gaelik dili');
INSERT INTO "country" ("id", "name") VALUES ('sco', 'skots dili');
INSERT INTO "country" ("id", "name") VALUES ('sla', 'slav dili');
INSERT INTO "country" ("id", "name") VALUES ('den', 'slavey');
INSERT INTO "country" ("id", "name") VALUES ('sk', 'slovakca');
INSERT INTO "country" ("id", "name") VALUES ('sl', 'slovencə');
INSERT INTO "country" ("id", "name") VALUES ('sog', 'soqdiyen dili');
INSERT INTO "country" ("id", "name") VALUES ('so', 'somali dili');
INSERT INTO "country" ("id", "name") VALUES ('snk', 'soninke dili');
INSERT INTO "country" ("id", "name") VALUES ('ts', 'sonqa dili');
INSERT INTO "country" ("id", "name") VALUES ('son', 'sonqay dili');
INSERT INTO "country" ("id", "name") VALUES ('wen', 'sorb dili');
INSERT INTO "country" ("id", "name") VALUES ('srn', 'sranan tonqo dili');
INSERT INTO "country" ("id", "name") VALUES ('sw', 'suahilicə');
INSERT INTO "country" ("id", "name") VALUES ('suk', 'sukuma dili');
INSERT INTO "country" ("id", "name") VALUES ('sux', 'sumeryan dili');
INSERT INTO "country" ("id", "name") VALUES ('su', 'sundanca');
INSERT INTO "country" ("id", "name") VALUES ('art', 'suni dil');
INSERT INTO "country" ("id", "name") VALUES ('sus', 'susu dili');
INSERT INTO "country" ("id", "name") VALUES ('tn', 'svana dili');
INSERT INTO "country" ("id", "name") VALUES ('ss', 'svati dili');
INSERT INTO "country" ("id", "name") VALUES ('shn', 'şan dili');
INSERT INTO "country" ("id", "name") VALUES ('nai', 'şimal amerika yerli dili');
INSERT INTO "country" ("id", "name") VALUES ('frr', 'şimal fris dili');
INSERT INTO "country" ("id", "name") VALUES ('nd', 'şimal ndebele dili');
INSERT INTO "country" ("id", "name") VALUES ('se', 'şimal sami dili');
INSERT INTO "country" ("id", "name") VALUES ('nso', 'şimal soto dili');
INSERT INTO "country" ("id", "name") VALUES ('sn', 'şona dili');
INSERT INTO "country" ("id", "name") VALUES ('tg', 'tacik dili');
INSERT INTO "country" ("id", "name") VALUES ('ty', 'taxiti dili');
INSERT INTO "country" ("id", "name") VALUES ('tl', 'taqaloq dili');
INSERT INTO "country" ("id", "name") VALUES ('fil', 'taqaloqca');
INSERT INTO "country" ("id", "name") VALUES ('tmh', 'tamaşek dili');
INSERT INTO "country" ("id", "name") VALUES ('ta', 'tamilcə');
INSERT INTO "country" ("id", "name") VALUES ('tt', 'tatarca');
INSERT INTO "country" ("id", "name") VALUES ('tai', 'tay dili');
INSERT INTO "country" ("id", "name") VALUES ('th', 'tayca');
INSERT INTO "country" ("id", "name") VALUES ('te', 'teluqu dili');
INSERT INTO "country" ("id", "name") VALUES ('ter', 'tereno dili');
INSERT INTO "country" ("id", "name") VALUES ('tet', 'tetum dili');
INSERT INTO "country" ("id", "name") VALUES ('bo', 'tibet dili');
INSERT INTO "country" ("id", "name") VALUES ('tig', 'tiqre dili');
INSERT INTO "country" ("id", "name") VALUES ('ti', 'tiqrin dili');
INSERT INTO "country" ("id", "name") VALUES ('tem', 'timne dili');
INSERT INTO "country" ("id", "name") VALUES ('tiv', 'tiv dili');
INSERT INTO "country" ("id", "name") VALUES ('kcg', 'tiyap dili');
INSERT INTO "country" ("id", "name") VALUES ('tli', 'tlinqit dili');
INSERT INTO "country" ("id", "name") VALUES ('tpi', 'tok pisin dili');
INSERT INTO "country" ("id", "name") VALUES ('tkl', 'tokelay dili');
INSERT INTO "country" ("id", "name") VALUES ('to', 'tonqa dili');
INSERT INTO "country" ("id", "name") VALUES ('tum', 'tumbuka dili');
INSERT INTO "country" ("id", "name") VALUES ('tup', 'tupi dili');
INSERT INTO "country" ("id", "name") VALUES ('tvl', 'tuvalu dili');
INSERT INTO "country" ("id", "name") VALUES ('tyv', 'tuvinyan dili');
INSERT INTO "country" ("id", "name") VALUES ('tr', 'türkcə');
INSERT INTO "country" ("id", "name") VALUES ('tk', 'türkməncə');
INSERT INTO "country" ("id", "name") VALUES ('tw', 'Tvi dili');
INSERT INTO "country" ("id", "name") VALUES ('udm', 'udmurt dili');
INSERT INTO "country" ("id", "name") VALUES ('cy', 'uelscə');
INSERT INTO "country" ("id", "name") VALUES ('uk', 'ukraynaca');
INSERT INTO "country" ("id", "name") VALUES ('uga', 'uqaritik dili');
INSERT INTO "country" ("id", "name") VALUES ('umb', 'umbundu dili');
INSERT INTO "country" ("id", "name") VALUES ('ur', 'urduca');
INSERT INTO "country" ("id", "name") VALUES ('ug', 'uyğurca');
INSERT INTO "country" ("id", "name") VALUES ('wak', 'vakaşan dili');
INSERT INTO "country" ("id", "name") VALUES ('wal', 'valamo dili');
INSERT INTO "country" ("id", "name") VALUES ('wa', 'valun dili');
INSERT INTO "country" ("id", "name") VALUES ('war', 'varay dili');
INSERT INTO "country" ("id", "name") VALUES ('was', 'vaşo dili');
INSERT INTO "country" ("id", "name") VALUES ('vai', 'vay dili');
INSERT INTO "country" ("id", "name") VALUES ('ve', 'venda dili');
INSERT INTO "country" ("id", "name") VALUES ('vo', 'volapük dili');
INSERT INTO "country" ("id", "name") VALUES ('wo', 'volof dili');
INSERT INTO "country" ("id", "name") VALUES ('vot', 'votik dili');
INSERT INTO "country" ("id", "name") VALUES ('vi', 'vyetnamca');
INSERT INTO "country" ("id", "name") VALUES ('yi', 'Yahudi dili');
INSERT INTO "country" ("id", "name") VALUES ('sah', 'yakut dili');
INSERT INTO "country" ("id", "name") VALUES ('yao', 'yao dili');
INSERT INTO "country" ("id", "name") VALUES ('yap', 'yapiz dili');
INSERT INTO "country" ("id", "name") VALUES ('ja', 'yaponca');
INSERT INTO "country" ("id", "name") VALUES ('jv', 'yavaca dili');
INSERT INTO "country" ("id", "name") VALUES ('yo', 'yoruba dili');
INSERT INTO "country" ("id", "name") VALUES ('hsb', 'yuxarı sorbca');
INSERT INTO "country" ("id", "name") VALUES ('el', 'yunanca');
INSERT INTO "country" ("id", "name") VALUES ('ypk', 'yupik dili');
INSERT INTO "country" ("id", "name") VALUES ('znd', 'zande dili');
INSERT INTO "country" ("id", "name") VALUES ('zap', 'zapotek dili');
INSERT INTO "country" ("id", "name") VALUES ('zza', 'zaza dili');
INSERT INTO "country" ("id", "name") VALUES ('zen', 'zenaqa dili');
INSERT INTO "country" ("id", "name") VALUES ('zu', 'zulu dili');
INSERT INTO "country" ("id", "name") VALUES ('zun', 'zuni dili');
