CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('de', 'aleman');
INSERT INTO "country" ("id", "name") VALUES ('en', 'anglés');
INSERT INTO "country" ("id", "name") VALUES ('ar', 'arabi');
INSERT INTO "country" ("id", "name") VALUES ('hy', 'armèni');
INSERT INTO "country" ("id", "name") VALUES ('az', 'azerbaijani');
INSERT INTO "country" ("id", "name") VALUES ('ber', 'berbèr');
INSERT INTO "country" ("id", "name") VALUES ('br', 'breton');
INSERT INTO "country" ("id", "name") VALUES ('eu', 'bàscol');
INSERT INTO "country" ("id", "name") VALUES ('ca', 'catalan');
INSERT INTO "country" ("id", "name") VALUES ('zh', 'chinés');
INSERT INTO "country" ("id", "name") VALUES ('da', 'danés');
INSERT INTO "country" ("id", "name") VALUES ('he', 'ebreu');
INSERT INTO "country" ("id", "name") VALUES ('es', 'espanhòl');
INSERT INTO "country" ("id", "name") VALUES ('phn', 'fenician');
INSERT INTO "country" ("id", "name") VALUES ('nl_BE', 'flamenc');
INSERT INTO "country" ("id", "name") VALUES ('fr', 'francés');
INSERT INTO "country" ("id", "name") VALUES ('frm', 'francés mejan');
INSERT INTO "country" ("id", "name") VALUES ('el', 'grec');
INSERT INTO "country" ("id", "name") VALUES ('grc', 'grec ancian');
INSERT INTO "country" ("id", "name") VALUES ('it', 'italian');
INSERT INTO "country" ("id", "name") VALUES ('la', 'latin');
INSERT INTO "country" ("id", "name") VALUES ('art', 'lenga artificiala');
INSERT INTO "country" ("id", "name") VALUES ('cel', 'lenga celtica');
INSERT INTO "country" ("id", "name") VALUES ('roa', 'lenga romança');
INSERT INTO "country" ("id", "name") VALUES ('oc', 'occitan');
INSERT INTO "country" ("id", "name") VALUES ('pro', 'occitan ancian');
INSERT INTO "country" ("id", "name") VALUES ('pt', 'portugués');
