CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('ab', 'Abkhazian');
INSERT INTO [country] ([id], [name]) VALUES ('af', 'Afrikaans');
INSERT INTO [country] ([id], [name]) VALUES ('sq', 'Albanian');
INSERT INTO [country] ([id], [name]) VALUES ('de', 'Aleman');
INSERT INTO [country] ([id], [name]) VALUES ('am', 'Amharic');
INSERT INTO [country] ([id], [name]) VALUES ('ar', 'Arabic');
INSERT INTO [country] ([id], [name]) VALUES ('hy', 'Armenian');
INSERT INTO [country] ([id], [name]) VALUES ('as', 'Assamese');
INSERT INTO [country] ([id], [name]) VALUES ('de_AT', 'Austrian German');
INSERT INTO [country] ([id], [name]) VALUES ('ay', 'Aymara');
INSERT INTO [country] ([id], [name]) VALUES ('az', 'Azerbaijani');
INSERT INTO [country] ([id], [name]) VALUES ('eu', 'Basque');
INSERT INTO [country] ([id], [name]) VALUES ('be', 'Belarusian');
INSERT INTO [country] ([id], [name]) VALUES ('bn', 'Bengali; Bangla');
INSERT INTO [country] ([id], [name]) VALUES ('bh', 'Bihari');
INSERT INTO [country] ([id], [name]) VALUES ('bs', 'Bosnian');
INSERT INTO [country] ([id], [name]) VALUES ('br', 'Breton');
INSERT INTO [country] ([id], [name]) VALUES ('bg', 'Bulgarian');
INSERT INTO [country] ([id], [name]) VALUES ('my', 'Burmese');
INSERT INTO [country] ([id], [name]) VALUES ('en_CA', 'Canadian English');
INSERT INTO [country] ([id], [name]) VALUES ('fr_CA', 'Canadian French');
INSERT INTO [country] ([id], [name]) VALUES ('yue', 'Cantonese');
INSERT INTO [country] ([id], [name]) VALUES ('ca', 'Catalan');
INSERT INTO [country] ([id], [name]) VALUES ('zh', 'Chinese');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hans', 'Chinese (pinasimple)');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hant', 'Chinese (tradisyunal)');
INSERT INTO [country] ([id], [name]) VALUES ('swb', 'Comorian');
INSERT INTO [country] ([id], [name]) VALUES ('hr', 'Croatian');
INSERT INTO [country] ([id], [name]) VALUES ('cs', 'Czech');
INSERT INTO [country] ([id], [name]) VALUES ('da', 'Danish');
INSERT INTO [country] ([id], [name]) VALUES ('dv', 'Divehi');
INSERT INTO [country] ([id], [name]) VALUES ('dz', 'Dzongkha');
INSERT INTO [country] ([id], [name]) VALUES ('efi', 'Efik');
INSERT INTO [country] ([id], [name]) VALUES ('es', 'Espanyol');
INSERT INTO [country] ([id], [name]) VALUES ('es_ES', 'Espanyol sa Iberia');
INSERT INTO [country] ([id], [name]) VALUES ('es_419', 'Espanyol sa Latin America');
INSERT INTO [country] ([id], [name]) VALUES ('eo', 'Esperanto');
INSERT INTO [country] ([id], [name]) VALUES ('et', 'Estonian');
INSERT INTO [country] ([id], [name]) VALUES ('fo', 'Faroeso');
INSERT INTO [country] ([id], [name]) VALUES ('fj', 'Fijian');
INSERT INTO [country] ([id], [name]) VALUES ('fil', 'Filipino');
INSERT INTO [country] ([id], [name]) VALUES ('fi', 'Finnish');
INSERT INTO [country] ([id], [name]) VALUES ('nl_BE', 'Flemish');
INSERT INTO [country] ([id], [name]) VALUES ('gl', 'Galician');
INSERT INTO [country] ([id], [name]) VALUES ('ka', 'Georgian');
INSERT INTO [country] ([id], [name]) VALUES ('el', 'Griyego');
INSERT INTO [country] ([id], [name]) VALUES ('gn', 'Guarani');
INSERT INTO [country] ([id], [name]) VALUES ('gu', 'Gujarati');
INSERT INTO [country] ([id], [name]) VALUES ('ht', 'Haitian');
INSERT INTO [country] ([id], [name]) VALUES ('ha', 'Hausa');
INSERT INTO [country] ([id], [name]) VALUES ('haw', 'Hawaiian');
INSERT INTO [country] ([id], [name]) VALUES ('he', 'Hebreo');
INSERT INTO [country] ([id], [name]) VALUES ('hi', 'Hindi');
INSERT INTO [country] ([id], [name]) VALUES ('hu', 'Hungarian');
INSERT INTO [country] ([id], [name]) VALUES ('is', 'Icelandic');
INSERT INTO [country] ([id], [name]) VALUES ('ig', 'Igbo');
INSERT INTO [country] ([id], [name]) VALUES ('id', 'Indonesian');
INSERT INTO [country] ([id], [name]) VALUES ('ia', 'Interlingua');
INSERT INTO [country] ([id], [name]) VALUES ('ie', 'Interlingue');
INSERT INTO [country] ([id], [name]) VALUES ('en', 'Ingles');
INSERT INTO [country] ([id], [name]) VALUES ('en_GB', 'Ingles (UK)');
INSERT INTO [country] ([id], [name]) VALUES ('en_AU', 'Ingles sa Australia');
INSERT INTO [country] ([id], [name]) VALUES ('en_US', 'Ingles sa U.S.');
INSERT INTO [country] ([id], [name]) VALUES ('ga', 'Irish');
INSERT INTO [country] ([id], [name]) VALUES ('it', 'Italyano');
INSERT INTO [country] ([id], [name]) VALUES ('ja', 'Japanese');
INSERT INTO [country] ([id], [name]) VALUES ('jv', 'Javanese');
INSERT INTO [country] ([id], [name]) VALUES ('kn', 'Kannada');
INSERT INTO [country] ([id], [name]) VALUES ('ks', 'Kashmiri');
INSERT INTO [country] ([id], [name]) VALUES ('kk', 'Kazakh');
INSERT INTO [country] ([id], [name]) VALUES ('km', 'Khmer');
INSERT INTO [country] ([id], [name]) VALUES ('rw', 'Kinyarwanda');
INSERT INTO [country] ([id], [name]) VALUES ('ky', 'Kirghiz');
INSERT INTO [country] ([id], [name]) VALUES ('tlh', 'Klingon');
INSERT INTO [country] ([id], [name]) VALUES ('ko', 'Korean');
INSERT INTO [country] ([id], [name]) VALUES ('ku', 'Kurdish');
INSERT INTO [country] ([id], [name]) VALUES ('lo', 'Lao');
INSERT INTO [country] ([id], [name]) VALUES ('la', 'Latin');
INSERT INTO [country] ([id], [name]) VALUES ('lv', 'Latvian');
INSERT INTO [country] ([id], [name]) VALUES ('ln', 'Lingala');
INSERT INTO [country] ([id], [name]) VALUES ('lt', 'Lithuanian');
INSERT INTO [country] ([id], [name]) VALUES ('lb', 'Luxembourgish');
INSERT INTO [country] ([id], [name]) VALUES ('mk', 'Macedonian');
INSERT INTO [country] ([id], [name]) VALUES ('mg', 'Malagasy');
INSERT INTO [country] ([id], [name]) VALUES ('ms', 'Malay');
INSERT INTO [country] ([id], [name]) VALUES ('ml', 'Malayalam');
INSERT INTO [country] ([id], [name]) VALUES ('mt', 'Maltese');
INSERT INTO [country] ([id], [name]) VALUES ('mi', 'Maori');
INSERT INTO [country] ([id], [name]) VALUES ('mr', 'Marathi');
INSERT INTO [country] ([id], [name]) VALUES ('mn', 'Mongolian');
INSERT INTO [country] ([id], [name]) VALUES ('ne', 'Nepali');
INSERT INTO [country] ([id], [name]) VALUES ('nd', 'North Ndebele');
INSERT INTO [country] ([id], [name]) VALUES ('se', 'Northern Sami');
INSERT INTO [country] ([id], [name]) VALUES ('nso', 'Northern Sotho');
INSERT INTO [country] ([id], [name]) VALUES ('no', 'Norwegian');
INSERT INTO [country] ([id], [name]) VALUES ('nb', 'Norwegian Bokmål');
INSERT INTO [country] ([id], [name]) VALUES ('nn', 'Norwegian Nynorsk');
INSERT INTO [country] ([id], [name]) VALUES ('ny', 'Nyanja');
INSERT INTO [country] ([id], [name]) VALUES ('oc', 'Occitan');
INSERT INTO [country] ([id], [name]) VALUES ('nl', 'Olandes');
INSERT INTO [country] ([id], [name]) VALUES ('or', 'Oriya');
INSERT INTO [country] ([id], [name]) VALUES ('os', 'Ossetic');
INSERT INTO [country] ([id], [name]) VALUES ('ps', 'Pashto');
INSERT INTO [country] ([id], [name]) VALUES ('fa', 'Persian');
INSERT INTO [country] ([id], [name]) VALUES ('pl', 'Polish');
INSERT INTO [country] ([id], [name]) VALUES ('pt', 'Portuges');
INSERT INTO [country] ([id], [name]) VALUES ('pt_BR', 'Portuges sa Brazil');
INSERT INTO [country] ([id], [name]) VALUES ('pt_PT', 'Portuges sa Iberia');
INSERT INTO [country] ([id], [name]) VALUES ('fr', 'Pranses');
INSERT INTO [country] ([id], [name]) VALUES ('pa', 'Punjabi');
INSERT INTO [country] ([id], [name]) VALUES ('qu', 'Quechua');
INSERT INTO [country] ([id], [name]) VALUES ('rm', 'Rhaeto-Romance');
INSERT INTO [country] ([id], [name]) VALUES ('ro', 'Romanian');
INSERT INTO [country] ([id], [name]) VALUES ('rn', 'Rundi');
INSERT INTO [country] ([id], [name]) VALUES ('ru', 'Russian');
INSERT INTO [country] ([id], [name]) VALUES ('sm', 'Samoan');
INSERT INTO [country] ([id], [name]) VALUES ('sa', 'Sanskrit');
INSERT INTO [country] ([id], [name]) VALUES ('sg', 'Sango');
INSERT INTO [country] ([id], [name]) VALUES ('gd', 'Scots Gaelic');
INSERT INTO [country] ([id], [name]) VALUES ('sr', 'Serbian');
INSERT INTO [country] ([id], [name]) VALUES ('sh', 'Serbo-Croatian');
INSERT INTO [country] ([id], [name]) VALUES ('sn', 'Shona');
INSERT INTO [country] ([id], [name]) VALUES ('sd', 'Sindhi');
INSERT INTO [country] ([id], [name]) VALUES ('si', 'Sinhala');
INSERT INTO [country] ([id], [name]) VALUES ('sk', 'Slovak');
INSERT INTO [country] ([id], [name]) VALUES ('sl', 'Slovenian');
INSERT INTO [country] ([id], [name]) VALUES ('so', 'Somali');
INSERT INTO [country] ([id], [name]) VALUES ('st', 'Southern Sotho');
INSERT INTO [country] ([id], [name]) VALUES ('su', 'Sundanese');
INSERT INTO [country] ([id], [name]) VALUES ('sw', 'Swahili');
INSERT INTO [country] ([id], [name]) VALUES ('ss', 'Swati');
INSERT INTO [country] ([id], [name]) VALUES ('sv', 'Swedish');
INSERT INTO [country] ([id], [name]) VALUES ('fr_CH', 'Swiss French');
INSERT INTO [country] ([id], [name]) VALUES ('gsw', 'Swiss German');
INSERT INTO [country] ([id], [name]) VALUES ('de_CH', 'Swiss High German');
INSERT INTO [country] ([id], [name]) VALUES ('ty', 'Tahitian');
INSERT INTO [country] ([id], [name]) VALUES ('tg', 'Tajik');
INSERT INTO [country] ([id], [name]) VALUES ('ta', 'Tamil');
INSERT INTO [country] ([id], [name]) VALUES ('tt', 'Tatar');
INSERT INTO [country] ([id], [name]) VALUES ('te', 'Telugu');
INSERT INTO [country] ([id], [name]) VALUES ('tet', 'Tetum');
INSERT INTO [country] ([id], [name]) VALUES ('th', 'Thai');
INSERT INTO [country] ([id], [name]) VALUES ('bo', 'Tibetan');
INSERT INTO [country] ([id], [name]) VALUES ('ti', 'Tigrinya');
INSERT INTO [country] ([id], [name]) VALUES ('tpi', 'Tok Pisin');
INSERT INTO [country] ([id], [name]) VALUES ('to', 'Tonga');
INSERT INTO [country] ([id], [name]) VALUES ('ts', 'Tsonga');
INSERT INTO [country] ([id], [name]) VALUES ('tn', 'Tswana');
INSERT INTO [country] ([id], [name]) VALUES ('tr', 'Turkish');
INSERT INTO [country] ([id], [name]) VALUES ('tk', 'Turkmen');
INSERT INTO [country] ([id], [name]) VALUES ('ug', 'Uighur');
INSERT INTO [country] ([id], [name]) VALUES ('uk', 'Ukranian');
INSERT INTO [country] ([id], [name]) VALUES ('ur', 'Urdu');
INSERT INTO [country] ([id], [name]) VALUES ('uz', 'Uzbek');
INSERT INTO [country] ([id], [name]) VALUES ('ve', 'Venda');
INSERT INTO [country] ([id], [name]) VALUES ('vi', 'Vietnamese');
INSERT INTO [country] ([id], [name]) VALUES ('zxx', 'Walang nilalamang linguistic');
INSERT INTO [country] ([id], [name]) VALUES ('cy', 'Welsh');
INSERT INTO [country] ([id], [name]) VALUES ('fy', 'Western Frisian');
INSERT INTO [country] ([id], [name]) VALUES ('wo', 'Wolof');
INSERT INTO [country] ([id], [name]) VALUES ('xh', 'Xhosa');
INSERT INTO [country] ([id], [name]) VALUES ('yo', 'Yoruba');
INSERT INTO [country] ([id], [name]) VALUES ('zu', 'Zulu');
