CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('anp', 'અંગીકા');
INSERT INTO "country" ("id", "name") VALUES ('en', 'અંગ્રેજી');
INSERT INTO "country" ("id", "name") VALUES ('cpe', 'અંગ્રેજી આધારિત ક્રેઓલ અથવા પિજિન');
INSERT INTO "country" ("id", "name") VALUES ('ak', 'અકન');
INSERT INTO "country" ("id", "name") VALUES ('ach', 'અકોલી');
INSERT INTO "country" ("id", "name") VALUES ('akk', 'અક્કાદીયાન');
INSERT INTO "country" ("id", "name") VALUES ('ace', 'અચીની');
INSERT INTO "country" ("id", "name") VALUES ('und', 'અજ્ઞાત અથવા અમાન્ય ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('az', 'અઝરબૈજાની');
INSERT INTO "country" ("id", "name") VALUES ('cch', 'અત્સમ');
INSERT INTO "country" ("id", "name") VALUES ('ath', 'અથાપાસ્કાન ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('ada', 'અદાંગ્મી');
INSERT INTO "country" ("id", "name") VALUES ('ady', 'અદિઘે');
INSERT INTO "country" ("id", "name") VALUES ('apa', 'અપાચે ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('hsb', 'અપ્પર સોર્બિયન');
INSERT INTO "country" ("id", "name") VALUES ('aa', 'અફાર');
INSERT INTO "country" ("id", "name") VALUES ('afh', 'અફ્રિહિલી');
INSERT INTO "country" ("id", "name") VALUES ('afa', 'અફ્રો-એશિયાટીક ભાષાઓ');
INSERT INTO "country" ("id", "name") VALUES ('ab', 'અબખાજિયન');
INSERT INTO "country" ("id", "name") VALUES ('ar', 'અરબી');
INSERT INTO "country" ("id", "name") VALUES ('arp', 'અરાપાહો');
INSERT INTO "country" ("id", "name") VALUES ('arw', 'અરાવક');
INSERT INTO "country" ("id", "name") VALUES ('rup', 'અરોમેનિયન');
INSERT INTO "country" ("id", "name") VALUES ('an', 'અર્ગોનીઝ');
INSERT INTO "country" ("id", "name") VALUES ('arc', 'અર્માઇક');
INSERT INTO "country" ("id", "name") VALUES ('ale', 'અલેઉત');
INSERT INTO "country" ("id", "name") VALUES ('tut', 'અલ્ટેઇક ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('sq', 'અલ્બેનિયન');
INSERT INTO "country" ("id", "name") VALUES ('awa', 'અવધી');
INSERT INTO "country" ("id", "name") VALUES ('av', 'અવેરિક');
INSERT INTO "country" ("id", "name") VALUES ('ae', 'અવેસ્તન');
INSERT INTO "country" ("id", "name") VALUES ('ast', 'અસ્તુરિયન');
INSERT INTO "country" ("id", "name") VALUES ('ga', 'આઇરિશ');
INSERT INTO "country" ("id", "name") VALUES ('is', 'આઇસલેન્ડિક');
INSERT INTO "country" ("id", "name") VALUES ('af', 'આફ્રિકન્સ');
INSERT INTO "country" ("id", "name") VALUES ('ay', 'આયમારા');
INSERT INTO "country" ("id", "name") VALUES ('hy', 'આર્મેનિયન');
INSERT INTO "country" ("id", "name") VALUES ('as', 'આસામી');
INSERT INTO "country" ("id", "name") VALUES ('inh', 'ઇંગુશ');
INSERT INTO "country" ("id", "name") VALUES ('ie', 'ઇંટરલિંગ');
INSERT INTO "country" ("id", "name") VALUES ('ia', 'ઇંટરલિંગુઆ');
INSERT INTO "country" ("id", "name") VALUES ('ine', 'ઇંડો-યુરોપીયન ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('ug', 'ઇગુર');
INSERT INTO "country" ("id", "name") VALUES ('ijo', 'ઇજો');
INSERT INTO "country" ("id", "name") VALUES ('it', 'ઇટાલિયન');
INSERT INTO "country" ("id", "name") VALUES ('io', 'ઇડૌ');
INSERT INTO "country" ("id", "name") VALUES ('smn', 'ઇનારી સામી');
INSERT INTO "country" ("id", "name") VALUES ('iu', 'ઇનુકિટૂટ');
INSERT INTO "country" ("id", "name") VALUES ('ik', 'ઇનુપિયાક');
INSERT INTO "country" ("id", "name") VALUES ('id', 'ઇન્ડોનેશિયન');
INSERT INTO "country" ("id", "name") VALUES ('iba', 'ઇબાન');
INSERT INTO "country" ("id", "name") VALUES ('pt_PT', 'ઇબેરિયન પોર્ટુગીઝ');
INSERT INTO "country" ("id", "name") VALUES ('es_ES', 'ઇબેરિયન સ્પેનિશ');
INSERT INTO "country" ("id", "name") VALUES ('ira', 'ઇરાની ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('iro', 'ઇરોક્વોઇયન ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('ilo', 'ઇલોકો');
INSERT INTO "country" ("id", "name") VALUES ('ee', 'ઇવે');
INSERT INTO "country" ("id", "name") VALUES ('ewo', 'ઇવોન્ડો');
INSERT INTO "country" ("id", "name") VALUES ('uz', 'ઉઝ્બેક');
INSERT INTO "country" ("id", "name") VALUES ('or', 'ઉડિયા');
INSERT INTO "country" ("id", "name") VALUES ('nd', 'ઉતર દેબેલ');
INSERT INTO "country" ("id", "name") VALUES ('nai', 'ઉતરી અમેરીકન ઇંડિયન ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('nso', 'ઉતરી સોથો');
INSERT INTO "country" ("id", "name") VALUES ('udm', 'ઉદમુર્ત');
INSERT INTO "country" ("id", "name") VALUES ('umb', 'ઉમ્બુન્ડૂ');
INSERT INTO "country" ("id", "name") VALUES ('ur', 'ઉર્દુ');
INSERT INTO "country" ("id", "name") VALUES ('eka', 'એકાજુક');
INSERT INTO "country" ("id", "name") VALUES ('nqo', 'એન\'કો');
INSERT INTO "country" ("id", "name") VALUES ('ain', 'એનૂ');
INSERT INTO "country" ("id", "name") VALUES ('efi', 'એફિક');
INSERT INTO "country" ("id", "name") VALUES ('am', 'એમ્હારિક');
INSERT INTO "country" ("id", "name") VALUES ('arn', 'એરોકૈનિયન');
INSERT INTO "country" ("id", "name") VALUES ('myv', 'એર્ઝયા');
INSERT INTO "country" ("id", "name") VALUES ('elx', 'એલામાઇટ');
INSERT INTO "country" ("id", "name") VALUES ('alg', 'એલ્ગોક્વિયન ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('et', 'એસ્ટોનિયન');
INSERT INTO "country" ("id", "name") VALUES ('eo', 'એસ્પેરાન્ટો');
INSERT INTO "country" ("id", "name") VALUES ('oc', 'ઑકીટન');
INSERT INTO "country" ("id", "name") VALUES ('oj', 'ઓઝિંબ્વા');
INSERT INTO "country" ("id", "name") VALUES ('ota', 'ઓટોમાન તુર્કિશ');
INSERT INTO "country" ("id", "name") VALUES ('oto', 'ઓટોમિયન ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('om', 'ઓરોમો');
INSERT INTO "country" ("id", "name") VALUES ('osa', 'ઓસેજ');
INSERT INTO "country" ("id", "name") VALUES ('de_AT', 'ઓસ્ટ્રિઅન જર્મન');
INSERT INTO "country" ("id", "name") VALUES ('en_AU', 'ઓસ્ટ્રેલિયન અંગ્રેજી');
INSERT INTO "country" ("id", "name") VALUES ('aus', 'ઓસ્ટ્રેલિયન ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('map', 'ઓસ્ટ્રોનેશિયન');
INSERT INTO "country" ("id", "name") VALUES ('os', 'ઓસ્સેટિક');
INSERT INTO "country" ("id", "name") VALUES ('kk', 'કઝાક');
INSERT INTO "country" ("id", "name") VALUES ('cad', 'કડ્ડો');
INSERT INTO "country" ("id", "name") VALUES ('ca', 'કતલાન');
INSERT INTO "country" ("id", "name") VALUES ('kr', 'કનુરી');
INSERT INTO "country" ("id", "name") VALUES ('kn', 'કન્નડા');
INSERT INTO "country" ("id", "name") VALUES ('kab', 'કબાઇલ');
INSERT INTO "country" ("id", "name") VALUES ('kbd', 'કબાર્ડિયન');
INSERT INTO "country" ("id", "name") VALUES ('kam', 'કમ્બા');
INSERT INTO "country" ("id", "name") VALUES ('krc', 'કરાચય-બલ્કાર');
INSERT INTO "country" ("id", "name") VALUES ('car', 'કરિબ');
INSERT INTO "country" ("id", "name") VALUES ('krl', 'કરેલિયન');
INSERT INTO "country" ("id", "name") VALUES ('kl', 'કલાલ્લિસુત');
INSERT INTO "country" ("id", "name") VALUES ('ks', 'કશ્મીરી');
INSERT INTO "country" ("id", "name") VALUES ('cau', 'કાકેશિયન ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('kac', 'કાચિન');
INSERT INTO "country" ("id", "name") VALUES ('kaa', 'કારા-કલ્પક');
INSERT INTO "country" ("id", "name") VALUES ('kar', 'કારેન');
INSERT INTO "country" ("id", "name") VALUES ('xal', 'કાલ્મિક');
INSERT INTO "country" ("id", "name") VALUES ('kaw', 'કાવી');
INSERT INTO "country" ("id", "name") VALUES ('csb', 'કાશુબિયન');
INSERT INTO "country" ("id", "name") VALUES ('ki', 'કિકુયૂ');
INSERT INTO "country" ("id", "name") VALUES ('rw', 'કિન્યારવાન્ડા');
INSERT INTO "country" ("id", "name") VALUES ('kmb', 'કિમ્બન્દુ');
INSERT INTO "country" ("id", "name") VALUES ('ky', 'કિરગીઝ');
INSERT INTO "country" ("id", "name") VALUES ('kut', 'કુતેનાઇ');
INSERT INTO "country" ("id", "name") VALUES ('kum', 'કુમીક');
INSERT INTO "country" ("id", "name") VALUES ('kru', 'કુરૂખ');
INSERT INTO "country" ("id", "name") VALUES ('ku', 'કુર્દિશ');
INSERT INTO "country" ("id", "name") VALUES ('cus', 'કુશિતિક ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('art', 'કૃત્રિમ ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('en_CA', 'કેનેડિયન ફ્રેંચ');
INSERT INTO "country" ("id", "name") VALUES ('ch', 'કેમોરો');
INSERT INTO "country" ("id", "name") VALUES ('kok', 'કોંકણી');
INSERT INTO "country" ("id", "name") VALUES ('kg', 'કોંગો');
INSERT INTO "country" ("id", "name") VALUES ('zxx', 'કોઇ ભાષાશાસ્ત્રીય સામગ્રી નથી');
INSERT INTO "country" ("id", "name") VALUES ('cop', 'કોપ્ટિક');
INSERT INTO "country" ("id", "name") VALUES ('kv', 'કોમી');
INSERT INTO "country" ("id", "name") VALUES ('ko', 'કોરિયન');
INSERT INTO "country" ("id", "name") VALUES ('kfo', 'કોરો');
INSERT INTO "country" ("id", "name") VALUES ('kw', 'કોર્નિશ');
INSERT INTO "country" ("id", "name") VALUES ('co', 'કોર્સિકન');
INSERT INTO "country" ("id", "name") VALUES ('kos', 'કોસરિયન');
INSERT INTO "country" ("id", "name") VALUES ('kpe', 'ક્પેલ્લે');
INSERT INTO "country" ("id", "name") VALUES ('mus', 'ક્રિક');
INSERT INTO "country" ("id", "name") VALUES ('crh', 'ક્રિમીન તુર્કી');
INSERT INTO "country" ("id", "name") VALUES ('cr', 'ક્રી');
INSERT INTO "country" ("id", "name") VALUES ('kro', 'ક્રૂ');
INSERT INTO "country" ("id", "name") VALUES ('crp', 'ક્રેઓલ અથવા પિજિન');
INSERT INTO "country" ("id", "name") VALUES ('hr', 'ક્રોએશિયન');
INSERT INTO "country" ("id", "name") VALUES ('tlh', 'ક્લિંગન');
INSERT INTO "country" ("id", "name") VALUES ('kj', 'ક્વાન્યામા');
INSERT INTO "country" ("id", "name") VALUES ('qu', 'ક્વેચુઆ');
INSERT INTO "country" ("id", "name") VALUES ('kha', 'ખાસી');
INSERT INTO "country" ("id", "name") VALUES ('kho', 'ખોતાનીસ');
INSERT INTO "country" ("id", "name") VALUES ('xh', 'ખોસા');
INSERT INTO "country" ("id", "name") VALUES ('khi', 'ખોસિયન ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('km', 'ખ્મેર');
INSERT INTO "country" ("id", "name") VALUES ('gaa', 'ગા');
INSERT INTO "country" ("id", "name") VALUES ('lg', 'ગાંડા');
INSERT INTO "country" ("id", "name") VALUES ('gay', 'ગાયો');
INSERT INTO "country" ("id", "name") VALUES ('gez', 'ગીઝ');
INSERT INTO "country" ("id", "name") VALUES ('gn', 'ગુઆરાની');
INSERT INTO "country" ("id", "name") VALUES ('gu', 'ગુજરાતી');
INSERT INTO "country" ("id", "name") VALUES ('gl', 'ગેલિશિયન');
INSERT INTO "country" ("id", "name") VALUES ('gon', 'ગોંડી');
INSERT INTO "country" ("id", "name") VALUES ('got', 'ગોથિક');
INSERT INTO "country" ("id", "name") VALUES ('gor', 'ગોરોન્તાલો');
INSERT INTO "country" ("id", "name") VALUES ('el', 'ગ્રીક');
INSERT INTO "country" ("id", "name") VALUES ('grb', 'ગ્રેબો');
INSERT INTO "country" ("id", "name") VALUES ('gwi', 'ગ્વિચ\'ઇન');
INSERT INTO "country" ("id", "name") VALUES ('cu', 'ચર્ચ સ્લાવિક');
INSERT INTO "country" ("id", "name") VALUES ('zh', 'ચાઇનીઝ');
INSERT INTO "country" ("id", "name") VALUES ('cmc', 'ચાર્મિક ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('chn', 'ચિનૂક જાર્ગન');
INSERT INTO "country" ("id", "name") VALUES ('chb', 'ચિબ્ચા');
INSERT INTO "country" ("id", "name") VALUES ('sit', 'ચીની-ટિબેટી ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('chk', 'ચૂકીસે');
INSERT INTO "country" ("id", "name") VALUES ('cv', 'ચૂવાશ');
INSERT INTO "country" ("id", "name") VALUES ('cs', 'ચેક');
INSERT INTO "country" ("id", "name") VALUES ('ce', 'ચેચન');
INSERT INTO "country" ("id", "name") VALUES ('cho', 'ચોક્તૌ');
INSERT INTO "country" ("id", "name") VALUES ('chg', 'છગાતાઇ');
INSERT INTO "country" ("id", "name") VALUES ('de', 'જર્મન');
INSERT INTO "country" ("id", "name") VALUES ('gem', 'જર્મેનિક ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('ja', 'જાપાનીઝ');
INSERT INTO "country" ("id", "name") VALUES ('jv', 'જાવાનીસ');
INSERT INTO "country" ("id", "name") VALUES ('gil', 'જિલ્બરટીઝ');
INSERT INTO "country" ("id", "name") VALUES ('jrb', 'જુદેઓ-અરબી');
INSERT INTO "country" ("id", "name") VALUES ('jpr', 'જુદેઓ-પર્શિયન');
INSERT INTO "country" ("id", "name") VALUES ('ang', 'જુની અંગ્રેજી');
INSERT INTO "country" ("id", "name") VALUES ('pro', 'જુની પ્રોવેન્સલ');
INSERT INTO "country" ("id", "name") VALUES ('sga', 'જૂની આયરિશ');
INSERT INTO "country" ("id", "name") VALUES ('non', 'જૂની નોર્સ');
INSERT INTO "country" ("id", "name") VALUES ('peo', 'જૂની પર્શિયન');
INSERT INTO "country" ("id", "name") VALUES ('fro', 'જૂની ફ્રેંચ');
INSERT INTO "country" ("id", "name") VALUES ('goh', 'જૂની હાઇ જર્મન');
INSERT INTO "country" ("id", "name") VALUES ('kaj', 'જ્જુ');
INSERT INTO "country" ("id", "name") VALUES ('ka', 'જ્યોર્જિઅન');
INSERT INTO "country" ("id", "name") VALUES ('znd', 'ઝન્ડે');
INSERT INTO "country" ("id", "name") VALUES ('zza', 'ઝાઝા');
INSERT INTO "country" ("id", "name") VALUES ('za', 'ઝુઆગ');
INSERT INTO "country" ("id", "name") VALUES ('zu', 'ઝુલુ');
INSERT INTO "country" ("id", "name") VALUES ('zun', 'ઝૂની');
INSERT INTO "country" ("id", "name") VALUES ('zen', 'ઝેનાગા');
INSERT INTO "country" ("id", "name") VALUES ('zap', 'ઝેપોટેક');
INSERT INTO "country" ("id", "name") VALUES ('dz', 'ઝોંગખા');
INSERT INTO "country" ("id", "name") VALUES ('tr', 'ટર્કીશ');
INSERT INTO "country" ("id", "name") VALUES ('ti', 'ટાઇગ્રિનિયા');
INSERT INTO "country" ("id", "name") VALUES ('tig', 'ટાઇગ્રે');
INSERT INTO "country" ("id", "name") VALUES ('tl', 'ટાગાલોગ');
INSERT INTO "country" ("id", "name") VALUES ('tem', 'ટિમ્ને');
INSERT INTO "country" ("id", "name") VALUES ('tyv', 'ટુવીનિયન');
INSERT INTO "country" ("id", "name") VALUES ('to', 'ટોંગા');
INSERT INTO "country" ("id", "name") VALUES ('tpi', 'ટોક પિસિન');
INSERT INTO "country" ("id", "name") VALUES ('tup', 'ટ્યૂપી ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('tw', 'ટ્વાઇ');
INSERT INTO "country" ("id", "name") VALUES ('nl', 'ડચ');
INSERT INTO "country" ("id", "name") VALUES ('da', 'ડેનિશ');
INSERT INTO "country" ("id", "name") VALUES ('dgr', 'ડોગ્રિબ');
INSERT INTO "country" ("id", "name") VALUES ('doi', 'ડોગ્રી');
INSERT INTO "country" ("id", "name") VALUES ('ng', 'ડોન્ગા');
INSERT INTO "country" ("id", "name") VALUES ('dyu', 'ડ્યુલા');
INSERT INTO "country" ("id", "name") VALUES ('tt', 'તતાર');
INSERT INTO "country" ("id", "name") VALUES ('ta', 'તમિલ');
INSERT INTO "country" ("id", "name") VALUES ('tum', 'તમ્બૂકા');
INSERT INTO "country" ("id", "name") VALUES ('tai', 'તાઇ ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('tg', 'તાજીક');
INSERT INTO "country" ("id", "name") VALUES ('tmh', 'તામાશેખ');
INSERT INTO "country" ("id", "name") VALUES ('ty', 'તાહિતિયન');
INSERT INTO "country" ("id", "name") VALUES ('bo', 'તિબેટી');
INSERT INTO "country" ("id", "name") VALUES ('tiv', 'તિવ');
INSERT INTO "country" ("id", "name") VALUES ('tk', 'તુર્કમેન');
INSERT INTO "country" ("id", "name") VALUES ('tvl', 'તુવાલુ');
INSERT INTO "country" ("id", "name") VALUES ('tet', 'તેતુમ');
INSERT INTO "country" ("id", "name") VALUES ('ter', 'તેરેનો');
INSERT INTO "country" ("id", "name") VALUES ('te', 'તેલુગુ');
INSERT INTO "country" ("id", "name") VALUES ('tkl', 'તોકેલાઉ');
INSERT INTO "country" ("id", "name") VALUES ('kcg', 'ત્યાપ');
INSERT INTO "country" ("id", "name") VALUES ('tn', 'ત્સ્વાના');
INSERT INTO "country" ("id", "name") VALUES ('th', 'થાઈ');
INSERT INTO "country" ("id", "name") VALUES ('sai', 'દક્ષિણ અમેરીકન ઇંડિયન ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('alt', 'દક્ષિણ અલ્તાઇ');
INSERT INTO "country" ("id", "name") VALUES ('nr', 'દક્ષિણ દેબેલ');
INSERT INTO "country" ("id", "name") VALUES ('sma', 'દક્ષિણ સામી');
INSERT INTO "country" ("id", "name") VALUES ('dak', 'દાકોતા');
INSERT INTO "country" ("id", "name") VALUES ('day', 'દાયક');
INSERT INTO "country" ("id", "name") VALUES ('dar', 'દાર્ગવા');
INSERT INTO "country" ("id", "name") VALUES ('din', 'દિન્કા');
INSERT INTO "country" ("id", "name") VALUES ('dv', 'દિવેહી');
INSERT INTO "country" ("id", "name") VALUES ('dua', 'દુઆલા');
INSERT INTO "country" ("id", "name") VALUES ('del', 'દેલેવેર');
INSERT INTO "country" ("id", "name") VALUES ('dra', 'દ્રવિડિઅન ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('nah', 'નહઆત્લ');
INSERT INTO "country" ("id", "name") VALUES ('nic', 'નાઇગર-કોર્ડોફેનિયન ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('na', 'નાઉરૂ');
INSERT INTO "country" ("id", "name") VALUES ('nv', 'નાવાજો');
INSERT INTO "country" ("id", "name") VALUES ('dsb', 'નિમ્ન સોર્બિયન');
INSERT INTO "country" ("id", "name") VALUES ('nia', 'નિયાસ');
INSERT INTO "country" ("id", "name") VALUES ('niu', 'નિયુઆન');
INSERT INTO "country" ("id", "name") VALUES ('ssa', 'નીલો-સહારન ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('ne', 'નેપાળી');
INSERT INTO "country" ("id", "name") VALUES ('nap', 'નેપોલિટાન');
INSERT INTO "country" ("id", "name") VALUES ('new', 'નેવારી');
INSERT INTO "country" ("id", "name") VALUES ('se', 'નૉર્થન સામી');
INSERT INTO "country" ("id", "name") VALUES ('no', 'નૉર્વેજીયન');
INSERT INTO "country" ("id", "name") VALUES ('nn', 'નૉર્વેજીયન નાયનૉર્સ્ક');
INSERT INTO "country" ("id", "name") VALUES ('nog', 'નોગાઇ');
INSERT INTO "country" ("id", "name") VALUES ('frr', 'નોર્ધર્ન ફ્રિશિયન');
INSERT INTO "country" ("id", "name") VALUES ('nb', 'નોર્વેજીયન બોકમાલ');
INSERT INTO "country" ("id", "name") VALUES ('nzi', 'ન્ઝિમા');
INSERT INTO "country" ("id", "name") VALUES ('nyn', 'ન્યાનકોલ');
INSERT INTO "country" ("id", "name") VALUES ('ny', 'ન્યાન્જા');
INSERT INTO "country" ("id", "name") VALUES ('nym', 'ન્યામવેઝી');
INSERT INTO "country" ("id", "name") VALUES ('tog', 'ન્યાસા ટોન્ગા');
INSERT INTO "country" ("id", "name") VALUES ('nub', 'ન્યુબિયાન ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('nyo', 'ન્યોરો');
INSERT INTO "country" ("id", "name") VALUES ('pag', 'પંગાસીનાન');
INSERT INTO "country" ("id", "name") VALUES ('pa', 'પંજાબી');
INSERT INTO "country" ("id", "name") VALUES ('pam', 'પમ્પાન્ગા');
INSERT INTO "country" ("id", "name") VALUES ('nwc', 'પરંપરાગત નેવારી');
INSERT INTO "country" ("id", "name") VALUES ('syc', 'પરંપરાગત સિરિએક');
INSERT INTO "country" ("id", "name") VALUES ('fa', 'પર્શિયન');
INSERT INTO "country" ("id", "name") VALUES ('pau', 'પલાઉઆન');
INSERT INTO "country" ("id", "name") VALUES ('fy', 'પશ્ચિમી ફ્રિશિયન');
INSERT INTO "country" ("id", "name") VALUES ('ps', 'પશ્તો');
INSERT INTO "country" ("id", "name") VALUES ('pal', 'પહલવી');
INSERT INTO "country" ("id", "name") VALUES ('pap', 'પાપિયામેન્ટો');
INSERT INTO "country" ("id", "name") VALUES ('paa', 'પાપુન ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hant', 'પારંપરિક ચિની');
INSERT INTO "country" ("id", "name") VALUES ('cpp', 'પાર્ટુગીઝ આધારિત ક્રેઓલ અથવા પિજિન');
INSERT INTO "country" ("id", "name") VALUES ('pi', 'પાલી');
INSERT INTO "country" ("id", "name") VALUES ('frs', 'પૂર્વ ફ્રિશિયન');
INSERT INTO "country" ("id", "name") VALUES ('pt', 'પોર્ટુગીઝ');
INSERT INTO "country" ("id", "name") VALUES ('pl', 'પોલીશ');
INSERT INTO "country" ("id", "name") VALUES ('pon', 'પોહપિએન');
INSERT INTO "country" ("id", "name") VALUES ('pra', 'પ્રક્રૃત ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('egy', 'પ્રાચીન ઇજીપ્શિયન');
INSERT INTO "country" ("id", "name") VALUES ('grc', 'પ્રાચીન ગ્રીક');
INSERT INTO "country" ("id", "name") VALUES ('fat', 'ફન્ટી');
INSERT INTO "country" ("id", "name") VALUES ('fj', 'ફિજીયન');
INSERT INTO "country" ("id", "name") VALUES ('fi', 'ફિનિશ');
INSERT INTO "country" ("id", "name") VALUES ('fiu', 'ફિન્નો-ઉગ્રીયન ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('fil', 'ફિલિપિનો');
INSERT INTO "country" ("id", "name") VALUES ('phi', 'ફિલિપીની ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('ff', 'ફુલાહ');
INSERT INTO "country" ("id", "name") VALUES ('fan', 'ફેંગ');
INSERT INTO "country" ("id", "name") VALUES ('fon', 'ફોન');
INSERT INTO "country" ("id", "name") VALUES ('phn', 'ફોનિશિયન');
INSERT INTO "country" ("id", "name") VALUES ('fo', 'ફોરિસ્ત');
INSERT INTO "country" ("id", "name") VALUES ('fur', 'ફ્રિયુલિયાન');
INSERT INTO "country" ("id", "name") VALUES ('cpf', 'ફ્રેંચ આધારિત ક્રેઓલ અથવા પિજિન');
INSERT INTO "country" ("id", "name") VALUES ('fr', 'ફ્રેન્ચ');
INSERT INTO "country" ("id", "name") VALUES ('nl_BE', 'ફ્લેમિશ');
INSERT INTO "country" ("id", "name") VALUES ('bn', 'બંગાળી');
INSERT INTO "country" ("id", "name") VALUES ('bug', 'બગિનીસ');
INSERT INTO "country" ("id", "name") VALUES ('btk', 'બતાક');
INSERT INTO "country" ("id", "name") VALUES ('bnt', 'બન્ટુ');
INSERT INTO "country" ("id", "name") VALUES ('bai', 'બમિલેકે ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('ber', 'બર્બર');
INSERT INTO "country" ("id", "name") VALUES ('my', 'બર્મીઝ');
INSERT INTO "country" ("id", "name") VALUES ('bal', 'બલૂચી');
INSERT INTO "country" ("id", "name") VALUES ('bg', 'બલ્ગેરિયન');
INSERT INTO "country" ("id", "name") VALUES ('ba', 'બષ્ખિર');
INSERT INTO "country" ("id", "name") VALUES ('bas', 'બસા');
INSERT INTO "country" ("id", "name") VALUES ('mul', 'બહુવિધ ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('bad', 'બાંદા');
INSERT INTO "country" ("id", "name") VALUES ('bm', 'બામ્બારા');
INSERT INTO "country" ("id", "name") VALUES ('gba', 'બાયા');
INSERT INTO "country" ("id", "name") VALUES ('ban', 'બાલિનીસ');
INSERT INTO "country" ("id", "name") VALUES ('bat', 'બાલ્ટિક ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('eu', 'બાસ્ક');
INSERT INTO "country" ("id", "name") VALUES ('bik', 'બિકોલ');
INSERT INTO "country" ("id", "name") VALUES ('bin', 'બિની');
INSERT INTO "country" ("id", "name") VALUES ('bi', 'બિસ્લામા');
INSERT INTO "country" ("id", "name") VALUES ('bh', 'બિહારી');
INSERT INTO "country" ("id", "name") VALUES ('bua', 'બુરિયાત');
INSERT INTO "country" ("id", "name") VALUES ('bej', 'બેજા');
INSERT INTO "country" ("id", "name") VALUES ('bem', 'બેમ્બા');
INSERT INTO "country" ("id", "name") VALUES ('be', 'બેલારુશિયન');
INSERT INTO "country" ("id", "name") VALUES ('bs', 'બોસ્નિયન');
INSERT INTO "country" ("id", "name") VALUES ('bra', 'બ્રજ');
INSERT INTO "country" ("id", "name") VALUES ('pt_BR', 'બ્રાઝિલીયન પોર્ટુગીઝ');
INSERT INTO "country" ("id", "name") VALUES ('en_GB', 'બ્રિટિશ અંગ્રેજી');
INSERT INTO "country" ("id", "name") VALUES ('br', 'બ્રેટોન');
INSERT INTO "country" ("id", "name") VALUES ('byn', 'બ્લિન');
INSERT INTO "country" ("id", "name") VALUES ('zbl', 'બ્લિસિમ્બોલ્સ');
INSERT INTO "country" ("id", "name") VALUES ('inc', 'ભારતીય ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('bho', 'ભોજપુરી');
INSERT INTO "country" ("id", "name") VALUES ('mdr', 'મંડાર');
INSERT INTO "country" ("id", "name") VALUES ('mak', 'મકાસર');
INSERT INTO "country" ("id", "name") VALUES ('mag', 'મગહી');
INSERT INTO "country" ("id", "name") VALUES ('cai', 'મધ્ય અમેરિકન ઇંડિયન ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('dum', 'મધ્ય ડચ');
INSERT INTO "country" ("id", "name") VALUES ('gmh', 'મધ્ય હાઇ જર્મન');
INSERT INTO "country" ("id", "name") VALUES ('mni', 'મનિપૂરી');
INSERT INTO "country" ("id", "name") VALUES ('mno', 'મનોબો ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('man', 'મન્ડિન્ગો');
INSERT INTO "country" ("id", "name") VALUES ('mr', 'મરાઠી');
INSERT INTO "country" ("id", "name") VALUES ('ms', 'મલય');
INSERT INTO "country" ("id", "name") VALUES ('ml', 'મલયાલમ');
INSERT INTO "country" ("id", "name") VALUES ('mg', 'મલાગસી');
INSERT INTO "country" ("id", "name") VALUES ('mas', 'મસાઇ');
INSERT INTO "country" ("id", "name") VALUES ('gv', 'માંક્સ');
INSERT INTO "country" ("id", "name") VALUES ('mi', 'માઓરી');
INSERT INTO "country" ("id", "name") VALUES ('mad', 'માદુરીસ');
INSERT INTO "country" ("id", "name") VALUES ('mnc', 'માન્ચુ');
INSERT INTO "country" ("id", "name") VALUES ('myn', 'માયા ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('mwr', 'મારવાડી');
INSERT INTO "country" ("id", "name") VALUES ('chm', 'મારી');
INSERT INTO "country" ("id", "name") VALUES ('mh', 'માર્શલીઝ');
INSERT INTO "country" ("id", "name") VALUES ('mt', 'માલ્ટિઝ');
INSERT INTO "country" ("id", "name") VALUES ('mic', 'મિકમેક');
INSERT INTO "country" ("id", "name") VALUES ('enm', 'મિડિલ અંગ્રેજી');
INSERT INTO "country" ("id", "name") VALUES ('mga', 'મિડિલ આઇરિશ');
INSERT INTO "country" ("id", "name") VALUES ('frm', 'મિડિલ ફ્રેંચ');
INSERT INTO "country" ("id", "name") VALUES ('min', 'મિનાંગ્કાબાઉ');
INSERT INTO "country" ("id", "name") VALUES ('mwl', 'મિરાંડી');
INSERT INTO "country" ("id", "name") VALUES ('mun', 'મુન્ડા ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('root', 'મૂલ');
INSERT INTO "country" ("id", "name") VALUES ('men', 'મેન્ડે');
INSERT INTO "country" ("id", "name") VALUES ('mk', 'મેસેડોનિયન');
INSERT INTO "country" ("id", "name") VALUES ('mai', 'મૈથિલી');
INSERT INTO "country" ("id", "name") VALUES ('hmn', 'મોંગ');
INSERT INTO "country" ("id", "name") VALUES ('mn', 'મોંગોલિયન');
INSERT INTO "country" ("id", "name") VALUES ('mdf', 'મોક્ષ');
INSERT INTO "country" ("id", "name") VALUES ('lol', 'મોગો');
INSERT INTO "country" ("id", "name") VALUES ('mkh', 'મોન-ખ્મેર ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('mo', 'મોલડાવિયન');
INSERT INTO "country" ("id", "name") VALUES ('mos', 'મોસ્સી');
INSERT INTO "country" ("id", "name") VALUES ('moh', 'મોહૌક');
INSERT INTO "country" ("id", "name") VALUES ('yao', 'યાઓ');
INSERT INTO "country" ("id", "name") VALUES ('sah', 'યાકૂત');
INSERT INTO "country" ("id", "name") VALUES ('yap', 'યાપીસ');
INSERT INTO "country" ("id", "name") VALUES ('yi', 'યીદ્દીશ');
INSERT INTO "country" ("id", "name") VALUES ('en_US', 'યુ એસ અંગ્રેજી');
INSERT INTO "country" ("id", "name") VALUES ('uk', 'યુક્રેનિયન');
INSERT INTO "country" ("id", "name") VALUES ('uga', 'યુગેરિટિક');
INSERT INTO "country" ("id", "name") VALUES ('ypk', 'યૂપિક ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('yo', 'યોરૂબા');
INSERT INTO "country" ("id", "name") VALUES ('ru', 'રશિયન');
INSERT INTO "country" ("id", "name") VALUES ('rm', 'રહેટો રોમાન્સ');
INSERT INTO "country" ("id", "name") VALUES ('raj', 'રાજસ્થાની');
INSERT INTO "country" ("id", "name") VALUES ('rap', 'રાપાનુઇ');
INSERT INTO "country" ("id", "name") VALUES ('rar', 'રારોટોંગન');
INSERT INTO "country" ("id", "name") VALUES ('rn', 'રૂન્દી');
INSERT INTO "country" ("id", "name") VALUES ('roa', 'રોમાંસ ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('ro', 'રોમાનિયન');
INSERT INTO "country" ("id", "name") VALUES ('rom', 'રોમાની');
INSERT INTO "country" ("id", "name") VALUES ('lb', 'લક્ઝેમબર્ગિશ');
INSERT INTO "country" ("id", "name") VALUES ('lo', 'લાઓથિયન');
INSERT INTO "country" ("id", "name") VALUES ('lv', 'લાતવિયન');
INSERT INTO "country" ("id", "name") VALUES ('lad', 'લાદીનો');
INSERT INTO "country" ("id", "name") VALUES ('lam', 'લામ્બા');
INSERT INTO "country" ("id", "name") VALUES ('lah', 'લાહન્ડા');
INSERT INTO "country" ("id", "name") VALUES ('ln', 'લિંગાલા');
INSERT INTO "country" ("id", "name") VALUES ('tli', 'લિંગિત');
INSERT INTO "country" ("id", "name") VALUES ('li', 'લિંબૂર્ગિશ');
INSERT INTO "country" ("id", "name") VALUES ('lt', 'લિથુનિયન');
INSERT INTO "country" ("id", "name") VALUES ('lui', 'લુઇસેનો');
INSERT INTO "country" ("id", "name") VALUES ('lun', 'લુન્ડા');
INSERT INTO "country" ("id", "name") VALUES ('lus', 'લુશાઇ');
INSERT INTO "country" ("id", "name") VALUES ('lua', 'લૂબા-લુલુઆ');
INSERT INTO "country" ("id", "name") VALUES ('lez', 'લેઝધીયન');
INSERT INTO "country" ("id", "name") VALUES ('la', 'લેટિન');
INSERT INTO "country" ("id", "name") VALUES ('es_419', 'લેટિન અમેરિકન સ્પેનિશ');
INSERT INTO "country" ("id", "name") VALUES ('nds', 'લો જર્મન');
INSERT INTO "country" ("id", "name") VALUES ('jbo', 'લોજ્બાન');
INSERT INTO "country" ("id", "name") VALUES ('loz', 'લોઝી');
INSERT INTO "country" ("id", "name") VALUES ('luo', 'લ્યુઓ');
INSERT INTO "country" ("id", "name") VALUES ('smj', 'લ્યુલ સામી');
INSERT INTO "country" ("id", "name") VALUES ('lu', 'લ્યૂબા કટાંગા');
INSERT INTO "country" ("id", "name") VALUES ('wal', 'વલામો');
INSERT INTO "country" ("id", "name") VALUES ('vai', 'વાઇ');
INSERT INTO "country" ("id", "name") VALUES ('wak', 'વાકાશન ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('war', 'વારે');
INSERT INTO "country" ("id", "name") VALUES ('wa', 'વાલૂન');
INSERT INTO "country" ("id", "name") VALUES ('was', 'વાશો');
INSERT INTO "country" ("id", "name") VALUES ('vi', 'વિયેતનામીસ');
INSERT INTO "country" ("id", "name") VALUES ('mis', 'વિવિધ ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('ve', 'વેન્દા');
INSERT INTO "country" ("id", "name") VALUES ('cy', 'વેલ્શ');
INSERT INTO "country" ("id", "name") VALUES ('vot', 'વોટિક');
INSERT INTO "country" ("id", "name") VALUES ('vo', 'વોલાપુક');
INSERT INTO "country" ("id", "name") VALUES ('wo', 'વોલોફ');
INSERT INTO "country" ("id", "name") VALUES ('chp', 'શિપેવ્યાન');
INSERT INTO "country" ("id", "name") VALUES ('shn', 'શેન');
INSERT INTO "country" ("id", "name") VALUES ('chy', 'શેયેન્ન');
INSERT INTO "country" ("id", "name") VALUES ('chr', 'શેરોકી');
INSERT INTO "country" ("id", "name") VALUES ('sn', 'શોના');
INSERT INTO "country" ("id", "name") VALUES ('su', 'સંડેનીઝ');
INSERT INTO "country" ("id", "name") VALUES ('sat', 'સંતાલી');
INSERT INTO "country" ("id", "name") VALUES ('sa', 'સંસ્કૃત');
INSERT INTO "country" ("id", "name") VALUES ('st', 'સદર્ન સોથો');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hans', 'સરળીકૃત ચિની');
INSERT INTO "country" ("id", "name") VALUES ('sr', 'સર્બિયન');
INSERT INTO "country" ("id", "name") VALUES ('sh', 'સર્બો-ક્રોએશિયન');
INSERT INTO "country" ("id", "name") VALUES ('sal', 'સલીશન ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('sgn', 'સાંકેતિક ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('sg', 'સાંગો');
INSERT INTO "country" ("id", "name") VALUES ('sam', 'સામરિટાન અરેમિક');
INSERT INTO "country" ("id", "name") VALUES ('smi', 'સામી ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('sm', 'સામોન');
INSERT INTO "country" ("id", "name") VALUES ('sc', 'સાર્દિનિયન');
INSERT INTO "country" ("id", "name") VALUES ('sas', 'સાસાક');
INSERT INTO "country" ("id", "name") VALUES ('sd', 'સિંધી');
INSERT INTO "country" ("id", "name") VALUES ('si', 'સિંહલી');
INSERT INTO "country" ("id", "name") VALUES ('sio', 'સિઉઆન ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('bla', 'સિક્સિકા');
INSERT INTO "country" ("id", "name") VALUES ('ii', 'સિચુઆન યી');
INSERT INTO "country" ("id", "name") VALUES ('sid', 'સિદામો');
INSERT INTO "country" ("id", "name") VALUES ('ceb', 'સિબુઆનો');
INSERT INTO "country" ("id", "name") VALUES ('tsi', 'સિમ્શિયન');
INSERT INTO "country" ("id", "name") VALUES ('syr', 'સિરિએક');
INSERT INTO "country" ("id", "name") VALUES ('scn', 'સિસિલિયાન');
INSERT INTO "country" ("id", "name") VALUES ('suk', 'સુકુમા');
INSERT INTO "country" ("id", "name") VALUES ('sux', 'સુમેરિયન');
INSERT INTO "country" ("id", "name") VALUES ('sus', 'સુસુ');
INSERT INTO "country" ("id", "name") VALUES ('sem', 'સેમિટિક ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('srr', 'સેરેર');
INSERT INTO "country" ("id", "name") VALUES ('sel', 'સેલ્કપ');
INSERT INTO "country" ("id", "name") VALUES ('cel', 'સેલ્ટિક ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('ts', 'સોંગા');
INSERT INTO "country" ("id", "name") VALUES ('sad', 'સોંડવે');
INSERT INTO "country" ("id", "name") VALUES ('sog', 'સોગ્ડિએન');
INSERT INTO "country" ("id", "name") VALUES ('snk', 'સોનિન્કે');
INSERT INTO "country" ("id", "name") VALUES ('son', 'સોન્ઘાઇ');
INSERT INTO "country" ("id", "name") VALUES ('so', 'સોમાલી');
INSERT INTO "country" ("id", "name") VALUES ('wen', 'સોર્બિયન ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('sco', 'સ્કોટ્સ');
INSERT INTO "country" ("id", "name") VALUES ('gd', 'સ્કોટ્સ ગેલિક');
INSERT INTO "country" ("id", "name") VALUES ('sms', 'સ્કોલ્ટ સામી');
INSERT INTO "country" ("id", "name") VALUES ('es', 'સ્પેનિશ');
INSERT INTO "country" ("id", "name") VALUES ('srn', 'સ્રાનન ટોન્ગો');
INSERT INTO "country" ("id", "name") VALUES ('den', 'સ્લેવ');
INSERT INTO "country" ("id", "name") VALUES ('sla', 'સ્લોવિક ભાષા');
INSERT INTO "country" ("id", "name") VALUES ('sk', 'સ્લોવૅક');
INSERT INTO "country" ("id", "name") VALUES ('sl', 'સ્લોવેનિયન');
INSERT INTO "country" ("id", "name") VALUES ('ss', 'સ્વાતી');
INSERT INTO "country" ("id", "name") VALUES ('sw', 'સ્વાહિલી');
INSERT INTO "country" ("id", "name") VALUES ('gsw', 'સ્વિસ જર્મન');
INSERT INTO "country" ("id", "name") VALUES ('fr_CH', 'સ્વિસ ફ્રેંચ');
INSERT INTO "country" ("id", "name") VALUES ('de_CH', 'સ્વિસ હાય જર્મન');
INSERT INTO "country" ("id", "name") VALUES ('sv', 'સ્વીડિશ');
INSERT INTO "country" ("id", "name") VALUES ('hu', 'હંગેરિયન');
INSERT INTO "country" ("id", "name") VALUES ('haw', 'હાવાઇયન');
INSERT INTO "country" ("id", "name") VALUES ('hit', 'હિટ્ટિતે');
INSERT INTO "country" ("id", "name") VALUES ('hi', 'હિન્દી');
INSERT INTO "country" ("id", "name") VALUES ('him', 'હિમાચલી');
INSERT INTO "country" ("id", "name") VALUES ('ho', 'હિરી મોટૂ');
INSERT INTO "country" ("id", "name") VALUES ('hil', 'હિલિગેનોન');
INSERT INTO "country" ("id", "name") VALUES ('he', 'હીબ્રુ');
INSERT INTO "country" ("id", "name") VALUES ('hup', 'હૂપા');
INSERT INTO "country" ("id", "name") VALUES ('hz', 'હેરેરો');
INSERT INTO "country" ("id", "name") VALUES ('hai', 'હૈડા');
INSERT INTO "country" ("id", "name") VALUES ('ht', 'હૈતીયન');
INSERT INTO "country" ("id", "name") VALUES ('ha', 'હૌસા');
