CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('hu', 'ሀንጋሪኛ');
INSERT INTO "country" ("id", "name") VALUES ('lt', 'ሊቱአኒየን');
INSERT INTO "country" ("id", "name") VALUES ('lv', 'ላቲቪያን');
INSERT INTO "country" ("id", "name") VALUES ('la', 'ላቲንኛ');
INSERT INTO "country" ("id", "name") VALUES ('hi', 'ሕንደኛ');
INSERT INTO "country" ("id", "name") VALUES ('ml', 'ማላያላምኛ');
INSERT INTO "country" ("id", "name") VALUES ('ms', 'ማላይኛ');
INSERT INTO "country" ("id", "name") VALUES ('mt', 'ማልቲስኛ');
INSERT INTO "country" ("id", "name") VALUES ('mr', 'ማራቲኛ');
INSERT INTO "country" ("id", "name") VALUES ('mk', 'ማክዶኒኛ');
INSERT INTO "country" ("id", "name") VALUES ('ru', 'ራሽኛ');
INSERT INTO "country" ("id", "name") VALUES ('ro', 'ሮማኒያን');
INSERT INTO "country" ("id", "name") VALUES ('sr', 'ሰርቢኛ');
INSERT INTO "country" ("id", "name") VALUES ('sh', 'ሰርቦ- ክሮዊታን');
INSERT INTO "country" ("id", "name") VALUES ('st', 'ሰሴቶ');
INSERT INTO "country" ("id", "name") VALUES ('sw', 'ሰዋሂሊኛ');
INSERT INTO "country" ("id", "name") VALUES ('su', 'ሱዳንኛ');
INSERT INTO "country" ("id", "name") VALUES ('sk', 'ስሎቨክኛ');
INSERT INTO "country" ("id", "name") VALUES ('sl', 'ስቁቪኛ');
INSERT INTO "country" ("id", "name") VALUES ('si', 'ስንሃልኛ');
INSERT INTO "country" ("id", "name") VALUES ('sv', 'ስዊድንኛ');
INSERT INTO "country" ("id", "name") VALUES ('es', 'ስፓኒሽ');
INSERT INTO "country" ("id", "name") VALUES ('bn', 'በንጋሊኛ');
INSERT INTO "country" ("id", "name") VALUES ('bg', 'ቡልጋሪኛ');
INSERT INTO "country" ("id", "name") VALUES ('bh', 'ቢሃሪ');
INSERT INTO "country" ("id", "name") VALUES ('eu', 'ባስክኛ');
INSERT INTO "country" ("id", "name") VALUES ('be', 'ቤላራሻኛ');
INSERT INTO "country" ("id", "name") VALUES ('br', 'ብሬቶን');
INSERT INTO "country" ("id", "name") VALUES ('bs', 'ቦስኒያን');
INSERT INTO "country" ("id", "name") VALUES ('vi', 'ቪትናምኛ');
INSERT INTO "country" ("id", "name") VALUES ('te', 'ተሉጉኛ');
INSERT INTO "country" ("id", "name") VALUES ('tr', 'ቱርከኛ');
INSERT INTO "country" ("id", "name") VALUES ('ta', 'ታሚልኛ');
INSERT INTO "country" ("id", "name") VALUES ('th', 'ታይኛ');
INSERT INTO "country" ("id", "name") VALUES ('fil', 'ታጋሎገኛ');
INSERT INTO "country" ("id", "name") VALUES ('tw', 'ትዊ');
INSERT INTO "country" ("id", "name") VALUES ('ti', 'ትግርኛ');
INSERT INTO "country" ("id", "name") VALUES ('cs', 'ቼክኛ');
INSERT INTO "country" ("id", "name") VALUES ('tk', 'ናይ ቱርኪ ሰብዓይ (ቱርካዊ)');
INSERT INTO "country" ("id", "name") VALUES ('ne', 'ኔፖሊኛ');
INSERT INTO "country" ("id", "name") VALUES ('nn', 'ኖርዌይኛ (ናይ ኝኖርስክ)');
INSERT INTO "country" ("id", "name") VALUES ('no', 'ኖርዌጂያን');
INSERT INTO "country" ("id", "name") VALUES ('sq', 'አልቤኒኛ');
INSERT INTO "country" ("id", "name") VALUES ('am', 'አምሐረኛ');
INSERT INTO "country" ("id", "name") VALUES ('az', 'አዜርባይጃንኛ');
INSERT INTO "country" ("id", "name") VALUES ('ga', 'አይሪሽ');
INSERT INTO "country" ("id", "name") VALUES ('is', 'አይስላንደኛ');
INSERT INTO "country" ("id", "name") VALUES ('af', 'አፍሪቃንሰኛ');
INSERT INTO "country" ("id", "name") VALUES ('ur', 'ኡርዱኛ');
INSERT INTO "country" ("id", "name") VALUES ('uz', 'ኡዝበክኛ');
INSERT INTO "country" ("id", "name") VALUES ('ia', 'ኢንቴር ቋንቋ');
INSERT INTO "country" ("id", "name") VALUES ('et', 'ኤስቶኒአን');
INSERT INTO "country" ("id", "name") VALUES ('eo', 'ኤስፐራንቶ');
INSERT INTO "country" ("id", "name") VALUES ('gd', 'እስኮትስ ጌልክኛ');
INSERT INTO "country" ("id", "name") VALUES ('id', 'እንዶኑሲኛ');
INSERT INTO "country" ("id", "name") VALUES ('en', 'እንግሊዝኛ');
INSERT INTO "country" ("id", "name") VALUES ('or', 'ኦሪያ');
INSERT INTO "country" ("id", "name") VALUES ('oc', 'ኦኪታንኛ');
INSERT INTO "country" ("id", "name") VALUES ('ku', 'ኩርድሽ');
INSERT INTO "country" ("id", "name") VALUES ('ky', 'ኪሩጋዚ');
INSERT INTO "country" ("id", "name") VALUES ('kn', 'ካማደኛ');
INSERT INTO "country" ("id", "name") VALUES ('ca', 'ካታላን');
INSERT INTO "country" ("id", "name") VALUES ('tlh', 'ክሊንግኦንኛ');
INSERT INTO "country" ("id", "name") VALUES ('hr', 'ክሮሽያንኛ');
INSERT INTO "country" ("id", "name") VALUES ('ko', 'ኮሪያኛ');
INSERT INTO "country" ("id", "name") VALUES ('cy', 'ወልሽ');
INSERT INTO "country" ("id", "name") VALUES ('ar', 'ዓረበኛ');
INSERT INTO "country" ("id", "name") VALUES ('he', 'ዕብራስጥ');
INSERT INTO "country" ("id", "name") VALUES ('zu', 'ዙሉኛ');
INSERT INTO "country" ("id", "name") VALUES ('xh', 'ዞሳኛ');
INSERT INTO "country" ("id", "name") VALUES ('uk', 'ዩክረኒኛ');
INSERT INTO "country" ("id", "name") VALUES ('yi', 'ዪዲሽ');
INSERT INTO "country" ("id", "name") VALUES ('nl', 'ደች');
INSERT INTO "country" ("id", "name") VALUES ('da', 'ዴኒሽ');
INSERT INTO "country" ("id", "name") VALUES ('de', 'ጀርመን');
INSERT INTO "country" ("id", "name") VALUES ('jv', 'ጃቫንኛ');
INSERT INTO "country" ("id", "name") VALUES ('ja', 'ጃፓንኛ');
INSERT INTO "country" ("id", "name") VALUES ('gu', 'ጉጃራቲኛ');
INSERT INTO "country" ("id", "name") VALUES ('ka', 'ጊዮርጊያኛ');
INSERT INTO "country" ("id", "name") VALUES ('gl', 'ጋለቪኛ');
INSERT INTO "country" ("id", "name") VALUES ('el', 'ግሪከኛ');
INSERT INTO "country" ("id", "name") VALUES ('gn', 'ጓራኒ');
INSERT INTO "country" ("id", "name") VALUES ('it', 'ጣሊያንኛ');
INSERT INTO "country" ("id", "name") VALUES ('fr', 'ፈረንሳይኛ');
INSERT INTO "country" ("id", "name") VALUES ('fi', 'ፊኒሽ');
INSERT INTO "country" ("id", "name") VALUES ('fo', 'ፋሮኛ');
INSERT INTO "country" ("id", "name") VALUES ('fy', 'ፍሪሰኛ');
INSERT INTO "country" ("id", "name") VALUES ('fa', 'ፐርሲያኛ');
INSERT INTO "country" ("id", "name") VALUES ('pa', 'ፑንጃቢኛ');
INSERT INTO "country" ("id", "name") VALUES ('ps', 'ፓሽቶ');
INSERT INTO "country" ("id", "name") VALUES ('pl', 'ፖሊሽ');
INSERT INTO "country" ("id", "name") VALUES ('pt', 'ፖርቱጋሊኛ');
INSERT INTO "country" ("id", "name") VALUES ('pt_BR', 'ፖርቱጋልኛ (ናይ ብራዚል)');
INSERT INTO "country" ("id", "name") VALUES ('pt_PT', 'ፖርቱጋልኛ (ናይ ፖርቱጋል)');
