CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('sq', 'Afaan Albaniyaa');
INSERT INTO [country] ([id], [name]) VALUES ('ga', 'Afaan Ayirishii');
INSERT INTO [country] ([id], [name]) VALUES ('az', 'Afaan Azerbaijani');
INSERT INTO [country] ([id], [name]) VALUES ('bn', 'Afaan Baangladeshi');
INSERT INTO [country] ([id], [name]) VALUES ('eu', 'Afaan Baskuu');
INSERT INTO [country] ([id], [name]) VALUES ('be', 'Afaan Belarusia');
INSERT INTO [country] ([id], [name]) VALUES ('bh', 'Afaan Bihari');
INSERT INTO [country] ([id], [name]) VALUES ('bs', 'Afaan Bosniyaa');
INSERT INTO [country] ([id], [name]) VALUES ('bg', 'Afaan Bulgariya');
INSERT INTO [country] ([id], [name]) VALUES ('hr', 'Afaan Croatian');
INSERT INTO [country] ([id], [name]) VALUES ('cs', 'Afaan Czech');
INSERT INTO [country] ([id], [name]) VALUES ('nl', 'Afaan Dachii');
INSERT INTO [country] ([id], [name]) VALUES ('da', 'Afaan Deenmaark');
INSERT INTO [country] ([id], [name]) VALUES ('eo', 'Afaan Esperantoo');
INSERT INTO [country] ([id], [name]) VALUES ('fr', 'Afaan Faransaayii');
INSERT INTO [country] ([id], [name]) VALUES ('fo', 'Afaan Faroese');
INSERT INTO [country] ([id], [name]) VALUES ('fi', 'Afaan Fiilaandi');
INSERT INTO [country] ([id], [name]) VALUES ('fil', 'Afaan Filippinii');
INSERT INTO [country] ([id], [name]) VALUES ('fy', 'Afaan Firisiyaani');
INSERT INTO [country] ([id], [name]) VALUES ('gl', 'Afaan Galishii');
INSERT INTO [country] ([id], [name]) VALUES ('ka', 'Afaan Georgian');
INSERT INTO [country] ([id], [name]) VALUES ('el', 'Afaan Giriiki');
INSERT INTO [country] ([id], [name]) VALUES ('gn', 'Afaan Guarani');
INSERT INTO [country] ([id], [name]) VALUES ('gu', 'Afaan Gujarati');
INSERT INTO [country] ([id], [name]) VALUES ('hu', 'Afaan Hangaari');
INSERT INTO [country] ([id], [name]) VALUES ('he', 'Afaan Hebrew');
INSERT INTO [country] ([id], [name]) VALUES ('hi', 'Afaan Hindii');
INSERT INTO [country] ([id], [name]) VALUES ('id', 'Afaan Indoneziya');
INSERT INTO [country] ([id], [name]) VALUES ('sl', 'Afaan Islovaniyaa');
INSERT INTO [country] ([id], [name]) VALUES ('es', 'Afaan Ispeen');
INSERT INTO [country] ([id], [name]) VALUES ('et', 'Afaan Istooniya');
INSERT INTO [country] ([id], [name]) VALUES ('ja', 'Afaan Japanii');
INSERT INTO [country] ([id], [name]) VALUES ('de', 'Afaan Jarmanii');
INSERT INTO [country] ([id], [name]) VALUES ('jv', 'Afaan Java');
INSERT INTO [country] ([id], [name]) VALUES ('kn', 'Afaan Kannada');
INSERT INTO [country] ([id], [name]) VALUES ('ca', 'Afaan Katalaa');
INSERT INTO [country] ([id], [name]) VALUES ('tlh', 'Afaan Kilingon');
INSERT INTO [country] ([id], [name]) VALUES ('ko', 'Afaan Korea');
INSERT INTO [country] ([id], [name]) VALUES ('la', 'Afaan Laatini');
INSERT INTO [country] ([id], [name]) VALUES ('lv', 'Afaan Lativiyaa');
INSERT INTO [country] ([id], [name]) VALUES ('lt', 'Afaan Liituniyaa');
INSERT INTO [country] ([id], [name]) VALUES ('mk', 'Afaan Macedooniyaa');
INSERT INTO [country] ([id], [name]) VALUES ('mt', 'Afaan Maltesii');
INSERT INTO [country] ([id], [name]) VALUES ('mr', 'Afaan Maratii');
INSERT INTO [country] ([id], [name]) VALUES ('ne', 'Afaan Nepalii');
INSERT INTO [country] ([id], [name]) VALUES ('nn', 'Afaan Norwegian');
INSERT INTO [country] ([id], [name]) VALUES ('no', 'Afaan Norweyii');
INSERT INTO [country] ([id], [name]) VALUES ('oc', 'Afaan Occit');
INSERT INTO [country] ([id], [name]) VALUES ('fa', 'Afaan Persia');
INSERT INTO [country] ([id], [name]) VALUES ('pl', 'Afaan Polandii');
INSERT INTO [country] ([id], [name]) VALUES ('pt_BR', 'Afaan Portugali (Braazil)');
INSERT INTO [country] ([id], [name]) VALUES ('pt', 'Afaan Porchugaal');
INSERT INTO [country] ([id], [name]) VALUES ('pt_PT', 'Afaan Protuguese');
INSERT INTO [country] ([id], [name]) VALUES ('pa', 'Afaan Punjabii');
INSERT INTO [country] ([id], [name]) VALUES ('ro', 'Afaan Romaniyaa');
INSERT INTO [country] ([id], [name]) VALUES ('ru', 'Afaan Rushiyaa');
INSERT INTO [country] ([id], [name]) VALUES ('sr', 'Afaan Serbiya');
INSERT INTO [country] ([id], [name]) VALUES ('am', 'Afaan Sidaamaa');
INSERT INTO [country] ([id], [name]) VALUES ('si', 'Afaan Sinhalese');
INSERT INTO [country] ([id], [name]) VALUES ('sk', 'Afaan Slovak');
INSERT INTO [country] ([id], [name]) VALUES ('su', 'Afaan Sudaanii');
INSERT INTO [country] ([id], [name]) VALUES ('sv', 'Afaan Suwidiin');
INSERT INTO [country] ([id], [name]) VALUES ('ta', 'Afaan Tamilii');
INSERT INTO [country] ([id], [name]) VALUES ('th', 'Afaan Tayii');
INSERT INTO [country] ([id], [name]) VALUES ('te', 'Afaan Telugu');
INSERT INTO [country] ([id], [name]) VALUES ('ti', 'Afaan Tigiree');
INSERT INTO [country] ([id], [name]) VALUES ('tr', 'Afaan Turkii');
INSERT INTO [country] ([id], [name]) VALUES ('uk', 'Afaan Ukreenii');
INSERT INTO [country] ([id], [name]) VALUES ('ur', 'Afaan Urdu');
INSERT INTO [country] ([id], [name]) VALUES ('uz', 'Afaan Uzbek');
INSERT INTO [country] ([id], [name]) VALUES ('vi', 'Afaan Veetinam');
INSERT INTO [country] ([id], [name]) VALUES ('it', 'Afaan Xaaliyaani');
INSERT INTO [country] ([id], [name]) VALUES ('xh', 'Afaan Xhosa');
INSERT INTO [country] ([id], [name]) VALUES ('zu', 'Afaan Zuulu');
INSERT INTO [country] ([id], [name]) VALUES ('af', 'Afrikoota');
INSERT INTO [country] ([id], [name]) VALUES ('ar', 'Arabiffaa');
INSERT INTO [country] ([id], [name]) VALUES ('is', 'Ayiislandiffaa');
INSERT INTO [country] ([id], [name]) VALUES ('en', 'Ingliffa');
INSERT INTO [country] ([id], [name]) VALUES ('ia', 'Interlingua');
INSERT INTO [country] ([id], [name]) VALUES ('tk', 'Lammii Turkii');
INSERT INTO [country] ([id], [name]) VALUES ('ms', 'Malaayiffaa');
INSERT INTO [country] ([id], [name]) VALUES ('ml', 'Malayaalamiffaa');
INSERT INTO [country] ([id], [name]) VALUES ('om', 'Oromoo');
INSERT INTO [country] ([id], [name]) VALUES ('gd', 'Scots Gaelic');
INSERT INTO [country] ([id], [name]) VALUES ('sw', 'Suwahilii');
INSERT INTO [country] ([id], [name]) VALUES ('cy', 'Welishiffaa');
INSERT INTO [country] ([id], [name]) VALUES ('zh', 'Chinese');
