CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('ak', 'अकन');
INSERT INTO `country` (`id`, `name`) VALUES ('akk', 'अकाडिनी');
INSERT INTO `country` (`id`, `name`) VALUES ('ach', 'अकोली');
INSERT INTO `country` (`id`, `name`) VALUES ('anp', 'अंगीका');
INSERT INTO `country` (`id`, `name`) VALUES ('en', 'अंग्रेज़ी');
INSERT INTO `country` (`id`, `name`) VALUES ('en_US', 'अंग्रेज़ी (अमरिकी)');
INSERT INTO `country` (`id`, `name`) VALUES ('en_AU', 'अंग्रेज़ी (ऑस्ट्रेलिया का)');
INSERT INTO `country` (`id`, `name`) VALUES ('en_CA', 'अंग्रेज़ी (कनाडाई)');
INSERT INTO `country` (`id`, `name`) VALUES ('en_GB', 'अंग्रेजी (ब्रिटिश)');
INSERT INTO `country` (`id`, `name`) VALUES ('ace', 'अचेहनी');
INSERT INTO `country` (`id`, `name`) VALUES ('az', 'अज़रबैजानी');
INSERT INTO `country` (`id`, `name`) VALUES ('und', 'अज्ञात या अवैध भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('ada', 'अडांगमे');
INSERT INTO `country` (`id`, `name`) VALUES ('ady', 'अडीगे');
INSERT INTO `country` (`id`, `name`) VALUES ('ath', 'अथापास्कन् भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('apa', 'अपाची भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('af', 'अफ्रीकी');
INSERT INTO `country` (`id`, `name`) VALUES ('afh', 'अफ्रीहीली');
INSERT INTO `country` (`id`, `name`) VALUES ('afa', 'अफ्रो-एशियाई भाषाएँ');
INSERT INTO `country` (`id`, `name`) VALUES ('ab', 'अब्खाज़ियन्');
INSERT INTO `country` (`id`, `name`) VALUES ('am', 'अम्हारिक्');
INSERT INTO `country` (`id`, `name`) VALUES ('ar', 'अरबी');
INSERT INTO `country` (`id`, `name`) VALUES ('hy', 'अरमेनियन्');
INSERT INTO `country` (`id`, `name`) VALUES ('arp', 'अरापाहो');
INSERT INTO `country` (`id`, `name`) VALUES ('arc', 'अरामाईक');
INSERT INTO `country` (`id`, `name`) VALUES ('arw', 'अरावाक');
INSERT INTO `country` (`id`, `name`) VALUES ('alg', 'अलगौनकीन');
INSERT INTO `country` (`id`, `name`) VALUES ('ale', 'अलुट');
INSERT INTO `country` (`id`, `name`) VALUES ('awa', 'अवधी');
INSERT INTO `country` (`id`, `name`) VALUES ('ae', 'अवस्तन्');
INSERT INTO `country` (`id`, `name`) VALUES ('av', 'अवारिक्');
INSERT INTO `country` (`id`, `name`) VALUES ('as', 'असामी');
INSERT INTO `country` (`id`, `name`) VALUES ('ga', 'आईरिश');
INSERT INTO `country` (`id`, `name`) VALUES ('is', 'आईस्लैंडिक्');
INSERT INTO `country` (`id`, `name`) VALUES ('cch', 'आत्सम');
INSERT INTO `country` (`id`, `name`) VALUES ('ay', 'आयमारा');
INSERT INTO `country` (`id`, `name`) VALUES ('rup', 'आरोमानी');
INSERT INTO `country` (`id`, `name`) VALUES ('an', 'आर्गोनी');
INSERT INTO `country` (`id`, `name`) VALUES ('sq', 'आल्बेनियन्');
INSERT INTO `country` (`id`, `name`) VALUES ('ik', 'इनुपियाक़्');
INSERT INTO `country` (`id`, `name`) VALUES ('iu', 'इनूक्टीटूत्');
INSERT INTO `country` (`id`, `name`) VALUES ('id', 'इन्डोनेशियन्');
INSERT INTO `country` (`id`, `name`) VALUES ('inh', 'ईंगुष');
INSERT INTO `country` (`id`, `name`) VALUES ('ig', 'ईग्बो');
INSERT INTO `country` (`id`, `name`) VALUES ('ijo', 'ईजो');
INSERT INTO `country` (`id`, `name`) VALUES ('it', 'ईटालियन्');
INSERT INTO `country` (`id`, `name`) VALUES ('io', 'ईडो');
INSERT INTO `country` (`id`, `name`) VALUES ('ine', 'ईंडो यूरोपी भाषाएँ');
INSERT INTO `country` (`id`, `name`) VALUES ('smn', 'ईनारी सामी');
INSERT INTO `country` (`id`, `name`) VALUES ('ia', 'ईन्टरलिंग्वा');
INSERT INTO `country` (`id`, `name`) VALUES ('ie', 'ईन्टरलिंग्वे');
INSERT INTO `country` (`id`, `name`) VALUES ('iba', 'ईबान्');
INSERT INTO `country` (`id`, `name`) VALUES ('ira', 'ईरानी भाषाएँ');
INSERT INTO `country` (`id`, `name`) VALUES ('iro', 'ईरोक़्वाईअन');
INSERT INTO `country` (`id`, `name`) VALUES ('ilo', 'ईलोको');
INSERT INTO `country` (`id`, `name`) VALUES ('es_ES', 'ईवेरियाई स्पैनिश');
INSERT INTO `country` (`id`, `name`) VALUES ('ug', 'उईग़ुर');
INSERT INTO `country` (`id`, `name`) VALUES ('uga', 'उगारिती');
INSERT INTO `country` (`id`, `name`) VALUES ('de_CH', 'उच्च स्तरिय स्वीस जर्मन');
INSERT INTO `country` (`id`, `name`) VALUES ('uz', 'उज़बेक्');
INSERT INTO `country` (`id`, `name`) VALUES ('udm', 'उड़मुर्त');
INSERT INTO `country` (`id`, `name`) VALUES ('or', 'उड़िया');
INSERT INTO `country` (`id`, `name`) VALUES ('nai', 'उत्तर अमरिकी भाषाएँ');
INSERT INTO `country` (`id`, `name`) VALUES ('nd', 'उत्तर न्दबेले');
INSERT INTO `country` (`id`, `name`) VALUES ('frr', 'उत्तरी फ्रीज़ियन्');
INSERT INTO `country` (`id`, `name`) VALUES ('se', 'उत्तरी सामी');
INSERT INTO `country` (`id`, `name`) VALUES ('umb', 'उंबुंडु');
INSERT INTO `country` (`id`, `name`) VALUES ('hsb', 'ऊपरी सौर्बियन');
INSERT INTO `country` (`id`, `name`) VALUES ('ur', 'ऊर्दु');
INSERT INTO `country` (`id`, `name`) VALUES ('eka', 'एकाजुक');
INSERT INTO `country` (`id`, `name`) VALUES ('efi', 'एफीक्');
INSERT INTO `country` (`id`, `name`) VALUES ('elx', 'एलामी');
INSERT INTO `country` (`id`, `name`) VALUES ('ee', 'एवे');
INSERT INTO `country` (`id`, `name`) VALUES ('ewo', 'एवौंडो');
INSERT INTO `country` (`id`, `name`) VALUES ('eo', 'एस्पेरान्तो');
INSERT INTO `country` (`id`, `name`) VALUES ('ain', 'ऐनू');
INSERT INTO `country` (`id`, `name`) VALUES ('myv', 'ऐर्ज़िया');
INSERT INTO `country` (`id`, `name`) VALUES ('et', 'ऐस्टोनियन्');
INSERT INTO `country` (`id`, `name`) VALUES ('oc', 'ओक्सीतान');
INSERT INTO `country` (`id`, `name`) VALUES ('oto', 'ओटोमानी');
INSERT INTO `country` (`id`, `name`) VALUES ('om', 'ओरोमो (अफ़ान)');
INSERT INTO `country` (`id`, `name`) VALUES ('osa', 'ओसेज');
INSERT INTO `country` (`id`, `name`) VALUES ('os', 'ओस्सेटी');
INSERT INTO `country` (`id`, `name`) VALUES ('oj', 'ओहीबवा');
INSERT INTO `country` (`id`, `name`) VALUES ('aus', 'औस्ट्रेलियाई भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('map', 'औस्ट्रोनेसी');
INSERT INTO `country` (`id`, `name`) VALUES ('kac', 'कचीन्');
INSERT INTO `country` (`id`, `name`) VALUES ('kk', 'क़ज़ाख़्');
INSERT INTO `country` (`id`, `name`) VALUES ('kr', 'कनुरी');
INSERT INTO `country` (`id`, `name`) VALUES ('kn', 'कन्नड्');
INSERT INTO `country` (`id`, `name`) VALUES ('kam', 'कंबा');
INSERT INTO `country` (`id`, `name`) VALUES ('kbd', 'कबार्डी भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('krc', 'कराचय् बलकार्');
INSERT INTO `country` (`id`, `name`) VALUES ('kar', 'करेन्');
INSERT INTO `country` (`id`, `name`) VALUES ('krl', 'करेलियन्');
INSERT INTO `country` (`id`, `name`) VALUES ('kl', 'कलालीसुत');
INSERT INTO `country` (`id`, `name`) VALUES ('ks', 'कश्मिरी');
INSERT INTO `country` (`id`, `name`) VALUES ('cau', 'काकौशी भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('ca', 'कातालान्');
INSERT INTO `country` (`id`, `name`) VALUES ('cad', 'काद्दौ');
INSERT INTO `country` (`id`, `name`) VALUES ('kab', 'काबील्');
INSERT INTO `country` (`id`, `name`) VALUES ('kaa', 'कारा कलपक');
INSERT INTO `country` (`id`, `name`) VALUES ('car', 'कारीब्');
INSERT INTO `country` (`id`, `name`) VALUES ('xal', 'कालमीक');
INSERT INTO `country` (`id`, `name`) VALUES ('kaw', 'कावी');
INSERT INTO `country` (`id`, `name`) VALUES ('csb', 'काशुबियान्');
INSERT INTO `country` (`id`, `name`) VALUES ('ki', 'किकुयु');
INSERT INTO `country` (`id`, `name`) VALUES ('rw', 'किन्यारुआण्डा');
INSERT INTO `country` (`id`, `name`) VALUES ('ky', 'किरग़ीज़्');
INSERT INTO `country` (`id`, `name`) VALUES ('rn', 'किरून्दी');
INSERT INTO `country` (`id`, `name`) VALUES ('kmb', 'कींबुंडु');
INSERT INTO `country` (`id`, `name`) VALUES ('kj', 'कुआनयामा');
INSERT INTO `country` (`id`, `name`) VALUES ('kut', 'कुतेनाई');
INSERT INTO `country` (`id`, `name`) VALUES ('kum', 'कुमीक्');
INSERT INTO `country` (`id`, `name`) VALUES ('kru', 'कुरुख़्');
INSERT INTO `country` (`id`, `name`) VALUES ('ku', 'कुर्दी');
INSERT INTO `country` (`id`, `name`) VALUES ('cus', 'कुशीतीक् भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('art', 'कृत्रिम भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('cel', 'केल्ट भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('kg', 'कॉंगो');
INSERT INTO `country` (`id`, `name`) VALUES ('cop', 'कॉप्टीक्');
INSERT INTO `country` (`id`, `name`) VALUES ('kok', 'कोंकणी');
INSERT INTO `country` (`id`, `name`) VALUES ('kv', 'कोमी');
INSERT INTO `country` (`id`, `name`) VALUES ('ko', 'कोरीयन्');
INSERT INTO `country` (`id`, `name`) VALUES ('kfo', 'कोरो');
INSERT INTO `country` (`id`, `name`) VALUES ('co', 'कोर्सीकन्');
INSERT INTO `country` (`id`, `name`) VALUES ('kos', 'कोस्राईयन्');
INSERT INTO `country` (`id`, `name`) VALUES ('kw', 'कौर्नवॉली');
INSERT INTO `country` (`id`, `name`) VALUES ('kpe', 'क्पेले');
INSERT INTO `country` (`id`, `name`) VALUES ('cr', 'क्री');
INSERT INTO `country` (`id`, `name`) VALUES ('mus', 'क्रीक');
INSERT INTO `country` (`id`, `name`) VALUES ('kro', 'क्रु');
INSERT INTO `country` (`id`, `name`) VALUES ('cpe', 'क्रेओल् (अंग्रेजी आधारीत)');
INSERT INTO `country` (`id`, `name`) VALUES ('cpp', 'क्रेओल् (पुर्तुगी आधारीत)');
INSERT INTO `country` (`id`, `name`) VALUES ('cpf', 'क्रेओल् (फ़्रानसीसी आधारीत)');
INSERT INTO `country` (`id`, `name`) VALUES ('crp', 'क्रेओल् या पीड्जीन');
INSERT INTO `country` (`id`, `name`) VALUES ('hr', 'क्रोएशन्');
INSERT INTO `country` (`id`, `name`) VALUES ('tlh', 'क्लींगदन');
INSERT INTO `country` (`id`, `name`) VALUES ('qu', 'क्वेचुआ');
INSERT INTO `country` (`id`, `name`) VALUES ('kha', 'ख़ासी');
INSERT INTO `country` (`id`, `name`) VALUES ('khi', 'खोईसान् भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('kho', 'ख़ोतानी');
INSERT INTO `country` (`id`, `name`) VALUES ('xh', 'ख़ोसा');
INSERT INTO `country` (`id`, `name`) VALUES ('km', 'ख्मेर');
INSERT INTO `country` (`id`, `name`) VALUES ('gaa', 'गा');
INSERT INTO `country` (`id`, `name`) VALUES ('lg', 'गांडा');
INSERT INTO `country` (`id`, `name`) VALUES ('gon', 'गाँडी');
INSERT INTO `country` (`id`, `name`) VALUES ('gay', 'गायो');
INSERT INTO `country` (`id`, `name`) VALUES ('gez', 'गीज़्');
INSERT INTO `country` (`id`, `name`) VALUES ('gil', 'गीलबर्टी');
INSERT INTO `country` (`id`, `name`) VALUES ('gn', 'गुआरानी');
INSERT INTO `country` (`id`, `name`) VALUES ('gu', 'गुजराती');
INSERT INTO `country` (`id`, `name`) VALUES ('gl', 'गैलिशियन्');
INSERT INTO `country` (`id`, `name`) VALUES ('got', 'गॉथिक');
INSERT INTO `country` (`id`, `name`) VALUES ('gor', 'गोरंटालो');
INSERT INTO `country` (`id`, `name`) VALUES ('gba', 'ग्बाया');
INSERT INTO `country` (`id`, `name`) VALUES ('el', 'ग्रीक');
INSERT INTO `country` (`id`, `name`) VALUES ('grb', 'ग्रेबो');
INSERT INTO `country` (`id`, `name`) VALUES ('gwi', 'ग्वीचलीन');
INSERT INTO `country` (`id`, `name`) VALUES ('chg', 'चगताई');
INSERT INTO `country` (`id`, `name`) VALUES ('cu', 'चर्च स्लाविक्');
INSERT INTO `country` (`id`, `name`) VALUES ('cmc', 'चामीक्');
INSERT INTO `country` (`id`, `name`) VALUES ('ch', 'चामोरो');
INSERT INTO `country` (`id`, `name`) VALUES ('chp', 'चिपेवियान्');
INSERT INTO `country` (`id`, `name`) VALUES ('zh', 'चीनी');
INSERT INTO `country` (`id`, `name`) VALUES ('zh_Hant', 'चीनी (पारम्परिक)');
INSERT INTO `country` (`id`, `name`) VALUES ('zh_Hans', 'चीनी (सरलीकृत)');
INSERT INTO `country` (`id`, `name`) VALUES ('chn', 'चीनूक् जार्गन्');
INSERT INTO `country` (`id`, `name`) VALUES ('chb', 'चीबचा');
INSERT INTO `country` (`id`, `name`) VALUES ('chr', 'चीरोकी');
INSERT INTO `country` (`id`, `name`) VALUES ('sgn', 'चीह्न भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('chk', 'चुकेसे');
INSERT INTO `country` (`id`, `name`) VALUES ('cv', 'चुवाश्');
INSERT INTO `country` (`id`, `name`) VALUES ('cs', 'चेक्');
INSERT INTO `country` (`id`, `name`) VALUES ('ce', 'चेचेन्');
INSERT INTO `country` (`id`, `name`) VALUES ('ceb', 'चेबुआनो');
INSERT INTO `country` (`id`, `name`) VALUES ('cho', 'चौक्टो');
INSERT INTO `country` (`id`, `name`) VALUES ('de', 'ज़र्मन');
INSERT INTO `country` (`id`, `name`) VALUES ('de_AT', 'जर्मन (ऑस्ट्रिया)');
INSERT INTO `country` (`id`, `name`) VALUES ('gem', 'जर्मनी भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('zza', 'ज़ाज़ा');
INSERT INTO `country` (`id`, `name`) VALUES ('znd', 'ज़ांडे');
INSERT INTO `country` (`id`, `name`) VALUES ('ja', 'जापानी');
INSERT INTO `country` (`id`, `name`) VALUES ('zap', 'ज़ापोतेक');
INSERT INTO `country` (`id`, `name`) VALUES ('jv', 'जावानीस');
INSERT INTO `country` (`id`, `name`) VALUES ('kaj', 'जु');
INSERT INTO `country` (`id`, `name`) VALUES ('za', 'ज़ुआंग');
INSERT INTO `country` (`id`, `name`) VALUES ('zun', 'ज़ुनी');
INSERT INTO `country` (`id`, `name`) VALUES ('zu', 'ज़ुलू');
INSERT INTO `country` (`id`, `name`) VALUES ('zen', 'ज़ेनागा');
INSERT INTO `country` (`id`, `name`) VALUES ('ka', 'जॉर्जियन्');
INSERT INTO `country` (`id`, `name`) VALUES ('tt', 'टाटर्');
INSERT INTO `country` (`id`, `name`) VALUES ('ty', 'टाहिटि');
INSERT INTO `country` (`id`, `name`) VALUES ('tig', 'टीग्रे');
INSERT INTO `country` (`id`, `name`) VALUES ('tiv', 'टीव्');
INSERT INTO `country` (`id`, `name`) VALUES ('tum', 'टुँबुका');
INSERT INTO `country` (`id`, `name`) VALUES ('tvl', 'टुवालु');
INSERT INTO `country` (`id`, `name`) VALUES ('tyv', 'टुवी');
INSERT INTO `country` (`id`, `name`) VALUES ('to', 'टॉंगा');
INSERT INTO `country` (`id`, `name`) VALUES ('tkl', 'टोकेलौ');
INSERT INTO `country` (`id`, `name`) VALUES ('tli', 'ट्लिंगीत');
INSERT INTO `country` (`id`, `name`) VALUES ('tw', 'ट्वी');
INSERT INTO `country` (`id`, `name`) VALUES ('dak', 'डकौटा');
INSERT INTO `country` (`id`, `name`) VALUES ('nl', 'डच्');
INSERT INTO `country` (`id`, `name`) VALUES ('day', 'डयाक्');
INSERT INTO `country` (`id`, `name`) VALUES ('din', 'डींगका');
INSERT INTO `country` (`id`, `name`) VALUES ('dua', 'डुआला');
INSERT INTO `country` (`id`, `name`) VALUES ('da', 'डैनीश्');
INSERT INTO `country` (`id`, `name`) VALUES ('doi', 'डोगरी');
INSERT INTO `country` (`id`, `name`) VALUES ('dgr', 'डोगरीब्');
INSERT INTO `country` (`id`, `name`) VALUES ('tmh', 'तमाशेक');
INSERT INTO `country` (`id`, `name`) VALUES ('ta', 'तमिळ');
INSERT INTO `country` (`id`, `name`) VALUES ('tai', 'ताई');
INSERT INTO `country` (`id`, `name`) VALUES ('tl', 'तागालोग');
INSERT INTO `country` (`id`, `name`) VALUES ('tg', 'ताजिक्');
INSERT INTO `country` (`id`, `name`) VALUES ('ti', 'तिग्रीन्या');
INSERT INTO `country` (`id`, `name`) VALUES ('bo', 'तिब्बती');
INSERT INTO `country` (`id`, `name`) VALUES ('tem', 'तीमने');
INSERT INTO `country` (`id`, `name`) VALUES ('tup', 'तुपी');
INSERT INTO `country` (`id`, `name`) VALUES ('tk', 'तुर्कमेन');
INSERT INTO `country` (`id`, `name`) VALUES ('tr', 'तुर्की');
INSERT INTO `country` (`id`, `name`) VALUES ('ota', 'तुर्की ओटोमान');
INSERT INTO `country` (`id`, `name`) VALUES ('crh', 'तुर्की क्रिमिया');
INSERT INTO `country` (`id`, `name`) VALUES ('tet', 'तेतुम');
INSERT INTO `country` (`id`, `name`) VALUES ('ter', 'तेरेनो');
INSERT INTO `country` (`id`, `name`) VALUES ('te', 'तेलुगु');
INSERT INTO `country` (`id`, `name`) VALUES ('tpi', 'तोक पिसीन');
INSERT INTO `country` (`id`, `name`) VALUES ('kcg', 'त्याप्');
INSERT INTO `country` (`id`, `name`) VALUES ('tsi', 'त्सीमशीआन्');
INSERT INTO `country` (`id`, `name`) VALUES ('tn', 'त्स्वाना');
INSERT INTO `country` (`id`, `name`) VALUES ('th', 'थाई');
INSERT INTO `country` (`id`, `name`) VALUES ('sai', 'दक्षिणी अमरिकी भाषाएँ');
INSERT INTO `country` (`id`, `name`) VALUES ('nr', 'दक्षिणी न्दबेले');
INSERT INTO `country` (`id`, `name`) VALUES ('dar', 'दर्गवा');
INSERT INTO `country` (`id`, `name`) VALUES ('del', 'दलावार्');
INSERT INTO `country` (`id`, `name`) VALUES ('dv', 'दीवेही');
INSERT INTO `country` (`id`, `name`) VALUES ('dyu', 'द्युआला');
INSERT INTO `country` (`id`, `name`) VALUES ('dra', 'द्रविड् भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('na', 'नाऊरू');
INSERT INTO `country` (`id`, `name`) VALUES ('nv', 'नावाहो');
INSERT INTO `country` (`id`, `name`) VALUES ('nah', 'नाहुआतल्');
INSERT INTO `country` (`id`, `name`) VALUES ('nic', 'निगेर कोर्डोफियान भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('nia', 'नियास');
INSERT INTO `country` (`id`, `name`) VALUES ('niu', 'नियुइआन');
INSERT INTO `country` (`id`, `name`) VALUES ('nds', 'नीजी स्तरिय जर्मन');
INSERT INTO `country` (`id`, `name`) VALUES ('ssa', 'नील सहारा भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('nub', 'नुबियन');
INSERT INTO `country` (`id`, `name`) VALUES ('nap', 'नेआपोलिटन');
INSERT INTO `country` (`id`, `name`) VALUES ('ne', 'नेपाली');
INSERT INTO `country` (`id`, `name`) VALUES ('new', 'नेवारी');
INSERT INTO `country` (`id`, `name`) VALUES ('nn', 'नॉर्वेजियन् नीनॉर्स्क्');
INSERT INTO `country` (`id`, `name`) VALUES ('no', 'नॉर्वेजीयन्');
INSERT INTO `country` (`id`, `name`) VALUES ('nog', 'नोगाई');
INSERT INTO `country` (`id`, `name`) VALUES ('nb', 'नोर्वेगी बोकमाल');
INSERT INTO `country` (`id`, `name`) VALUES ('nqo', 'न्गको');
INSERT INTO `country` (`id`, `name`) VALUES ('nzi', 'न्ज़ीमा');
INSERT INTO `country` (`id`, `name`) VALUES ('ng', 'न्डोंगा');
INSERT INTO `country` (`id`, `name`) VALUES ('nyn', 'न्यानकोले');
INSERT INTO `country` (`id`, `name`) VALUES ('ny', 'न्यानजा');
INSERT INTO `country` (`id`, `name`) VALUES ('nym', 'न्यामवेज़ी');
INSERT INTO `country` (`id`, `name`) VALUES ('tog', 'न्यासा टॉंगा');
INSERT INTO `country` (`id`, `name`) VALUES ('nyo', 'न्यौरो');
INSERT INTO `country` (`id`, `name`) VALUES ('ps', 'पख़्तु');
INSERT INTO `country` (`id`, `name`) VALUES ('pa', 'पंजाबी');
INSERT INTO `country` (`id`, `name`) VALUES ('pam', 'पंपंगा');
INSERT INTO `country` (`id`, `name`) VALUES ('fy', 'पश्चीमी फ्रीज़ियन्');
INSERT INTO `country` (`id`, `name`) VALUES ('sma', 'पश्चीमी सामी');
INSERT INTO `country` (`id`, `name`) VALUES ('pal', 'पहलवी');
INSERT INTO `country` (`id`, `name`) VALUES ('pag', 'पांगासीनन');
INSERT INTO `country` (`id`, `name`) VALUES ('pap', 'पापीआमेन्तो');
INSERT INTO `country` (`id`, `name`) VALUES ('paa', 'पापुअन');
INSERT INTO `country` (`id`, `name`) VALUES ('syc', 'पारंपरीक सिरिआक');
INSERT INTO `country` (`id`, `name`) VALUES ('pau', 'पालाऊ');
INSERT INTO `country` (`id`, `name`) VALUES ('pi', 'पाली');
INSERT INTO `country` (`id`, `name`) VALUES ('ang', 'पुरानी अंग्रेज़ी');
INSERT INTO `country` (`id`, `name`) VALUES ('sga', 'पुरानी आईरीश');
INSERT INTO `country` (`id`, `name`) VALUES ('goh', 'पुरानी उच्चस्तरी जर्मन');
INSERT INTO `country` (`id`, `name`) VALUES ('nwc', 'पुरानी नेवारी');
INSERT INTO `country` (`id`, `name`) VALUES ('non', 'पुरानी नॉर्स्');
INSERT INTO `country` (`id`, `name`) VALUES ('pro', 'पुरानी प्रोवाँसाल');
INSERT INTO `country` (`id`, `name`) VALUES ('peo', 'पुरानी फ़ारसी');
INSERT INTO `country` (`id`, `name`) VALUES ('fro', 'पुरानी फ्रांसीसी');
INSERT INTO `country` (`id`, `name`) VALUES ('pt', 'पुर्तगाली');
INSERT INTO `country` (`id`, `name`) VALUES ('frs', 'पूर्वी फ्रीज़ियन्');
INSERT INTO `country` (`id`, `name`) VALUES ('pl', 'पोलिश');
INSERT INTO `country` (`id`, `name`) VALUES ('pon', 'पोहनपी');
INSERT INTO `country` (`id`, `name`) VALUES ('pra', 'प्राकृत');
INSERT INTO `country` (`id`, `name`) VALUES ('egy', 'प्राचीन मिस्री');
INSERT INTO `country` (`id`, `name`) VALUES ('grc', 'प्राचीन यूनानी');
INSERT INTO `country` (`id`, `name`) VALUES ('fan', 'फाँग्');
INSERT INTO `country` (`id`, `name`) VALUES ('fat', 'फाँटी');
INSERT INTO `country` (`id`, `name`) VALUES ('fa', 'फार्सी');
INSERT INTO `country` (`id`, `name`) VALUES ('fi', 'फिनिश्');
INSERT INTO `country` (`id`, `name`) VALUES ('fo', 'फिरोज़ी');
INSERT INTO `country` (`id`, `name`) VALUES ('fil', 'फिलिपिनो');
INSERT INTO `country` (`id`, `name`) VALUES ('fj', 'फ़ीजी');
INSERT INTO `country` (`id`, `name`) VALUES ('phn', 'फीनीसी');
INSERT INTO `country` (`id`, `name`) VALUES ('fiu', 'फीनो-ऊग्री भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('phi', 'फ़ीलीपीनी');
INSERT INTO `country` (`id`, `name`) VALUES ('ff', 'फुलाह्');
INSERT INTO `country` (`id`, `name`) VALUES ('fon', 'फोन');
INSERT INTO `country` (`id`, `name`) VALUES ('fr', 'फ्रांसीसी');
INSERT INTO `country` (`id`, `name`) VALUES ('fr_CA', 'फ्रांसीसी (कनाडाई)');
INSERT INTO `country` (`id`, `name`) VALUES ('fr_CH', 'फ्रांसीसी (स्वीस)');
INSERT INTO `country` (`id`, `name`) VALUES ('fur', 'फ्रीउलीअन्');
INSERT INTO `country` (`id`, `name`) VALUES ('nl_BE', 'फ्लेमी');
INSERT INTO `country` (`id`, `name`) VALUES ('bn', 'बंगला');
INSERT INTO `country` (`id`, `name`) VALUES ('brx', 'बड़ो');
INSERT INTO `country` (`id`, `name`) VALUES ('bad', 'बंदा');
INSERT INTO `country` (`id`, `name`) VALUES ('ber', 'बरबर्');
INSERT INTO `country` (`id`, `name`) VALUES ('my', 'बर्मी');
INSERT INTO `country` (`id`, `name`) VALUES ('bal', 'बलूची');
INSERT INTO `country` (`id`, `name`) VALUES ('bg', 'बल्गैरियन्');
INSERT INTO `country` (`id`, `name`) VALUES ('bat', 'बल्टीक भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('ba', 'बशख़िर्');
INSERT INTO `country` (`id`, `name`) VALUES ('bnt', 'बाँटु');
INSERT INTO `country` (`id`, `name`) VALUES ('btk', 'बातक');
INSERT INTO `country` (`id`, `name`) VALUES ('bm', 'बांबारा');
INSERT INTO `country` (`id`, `name`) VALUES ('bai', 'बामीलेके');
INSERT INTO `country` (`id`, `name`) VALUES ('ban', 'बालिनी');
INSERT INTO `country` (`id`, `name`) VALUES ('eu', 'बास्क्');
INSERT INTO `country` (`id`, `name`) VALUES ('bas', 'बास्क़्');
INSERT INTO `country` (`id`, `name`) VALUES ('bik', 'बिकोल्');
INSERT INTO `country` (`id`, `name`) VALUES ('bin', 'बिनी');
INSERT INTO `country` (`id`, `name`) VALUES ('bi', 'बिस्लामा');
INSERT INTO `country` (`id`, `name`) VALUES ('bh', 'बिहारी');
INSERT INTO `country` (`id`, `name`) VALUES ('bug', 'बुगीनी');
INSERT INTO `country` (`id`, `name`) VALUES ('bua', 'बुरियात');
INSERT INTO `country` (`id`, `name`) VALUES ('bej', 'बेजा');
INSERT INTO `country` (`id`, `name`) VALUES ('bem', 'बेंबा');
INSERT INTO `country` (`id`, `name`) VALUES ('be', 'बैलोरूसियन्');
INSERT INTO `country` (`id`, `name`) VALUES ('bs', 'बोस्नियाई');
INSERT INTO `country` (`id`, `name`) VALUES ('bra', 'ब्रज');
INSERT INTO `country` (`id`, `name`) VALUES ('br', 'ब्रटों');
INSERT INTO `country` (`id`, `name`) VALUES ('byn', 'ब्लीन');
INSERT INTO `country` (`id`, `name`) VALUES ('zbl', 'ब्लीस चिन्ह');
INSERT INTO `country` (`id`, `name`) VALUES ('inc', 'भारतीय भाषाएँ');
INSERT INTO `country` (`id`, `name`) VALUES ('dz', 'भुटानी');
INSERT INTO `country` (`id`, `name`) VALUES ('bho', 'भोजपुरी');
INSERT INTO `country` (`id`, `name`) VALUES ('mak', 'मक्सर');
INSERT INTO `country` (`id`, `name`) VALUES ('mag', 'मघी');
INSERT INTO `country` (`id`, `name`) VALUES ('mni', 'मणीपुरी');
INSERT INTO `country` (`id`, `name`) VALUES ('mdr', 'मंदार');
INSERT INTO `country` (`id`, `name`) VALUES ('enm', 'मध्य अंग्रेज़ी');
INSERT INTO `country` (`id`, `name`) VALUES ('cai', 'मध्य अमरिकी भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('mga', 'मध्य आईरीश भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('gmh', 'मध्य उच्चस्तरी जर्मन');
INSERT INTO `country` (`id`, `name`) VALUES ('dum', 'मध्य डच');
INSERT INTO `country` (`id`, `name`) VALUES ('frm', 'मध्य फ्रांसीसी');
INSERT INTO `country` (`id`, `name`) VALUES ('mr', 'मराठी');
INSERT INTO `country` (`id`, `name`) VALUES ('ml', 'मलयालम');
INSERT INTO `country` (`id`, `name`) VALUES ('ms', 'मलाय');
INSERT INTO `country` (`id`, `name`) VALUES ('mas', 'मसाई');
INSERT INTO `country` (`id`, `name`) VALUES ('mi', 'माओरी');
INSERT INTO `country` (`id`, `name`) VALUES ('mnc', 'मांचु');
INSERT INTO `country` (`id`, `name`) VALUES ('man', 'मांडींगो');
INSERT INTO `country` (`id`, `name`) VALUES ('mad', 'मादुरी');
INSERT INTO `country` (`id`, `name`) VALUES ('mno', 'मानोबो');
INSERT INTO `country` (`id`, `name`) VALUES ('myn', 'माया भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('mwr', 'मारवाड़ी');
INSERT INTO `country` (`id`, `name`) VALUES ('chm', 'मारी');
INSERT INTO `country` (`id`, `name`) VALUES ('mh', 'मार्शली');
INSERT INTO `country` (`id`, `name`) VALUES ('mt', 'मालटीज़्');
INSERT INTO `country` (`id`, `name`) VALUES ('mg', 'मालागासी');
INSERT INTO `country` (`id`, `name`) VALUES ('min', 'मिनंगकाबाउ');
INSERT INTO `country` (`id`, `name`) VALUES ('mic', 'मीकमाक');
INSERT INTO `country` (`id`, `name`) VALUES ('mwl', 'मीरांडी');
INSERT INTO `country` (`id`, `name`) VALUES ('mun', 'मुंडा');
INSERT INTO `country` (`id`, `name`) VALUES ('men', 'मेंदे');
INSERT INTO `country` (`id`, `name`) VALUES ('gv', 'मैंक्स');
INSERT INTO `country` (`id`, `name`) VALUES ('mai', 'मैथीली');
INSERT INTO `country` (`id`, `name`) VALUES ('mk', 'मैसेडोनियन्');
INSERT INTO `country` (`id`, `name`) VALUES ('mdf', 'मोक्षा');
INSERT INTO `country` (`id`, `name`) VALUES ('lol', 'मोंगो');
INSERT INTO `country` (`id`, `name`) VALUES ('mn', 'मोंगोलियन');
INSERT INTO `country` (`id`, `name`) VALUES ('mkh', 'मोन ख्मेर');
INSERT INTO `country` (`id`, `name`) VALUES ('mo', 'मोल्डेवियन्');
INSERT INTO `country` (`id`, `name`) VALUES ('mos', 'मोस्सी');
INSERT INTO `country` (`id`, `name`) VALUES ('moh', 'मोहोक');
INSERT INTO `country` (`id`, `name`) VALUES ('sah', 'यकुट्');
INSERT INTO `country` (`id`, `name`) VALUES ('jrb', 'यहुदी अरबी');
INSERT INTO `country` (`id`, `name`) VALUES ('jpr', 'यहुदी फ़ारसी');
INSERT INTO `country` (`id`, `name`) VALUES ('yao', 'याओ');
INSERT INTO `country` (`id`, `name`) VALUES ('yap', 'यापीज़');
INSERT INTO `country` (`id`, `name`) VALUES ('yi', 'यीद्दीश');
INSERT INTO `country` (`id`, `name`) VALUES ('ypk', 'युपीक भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('uk', 'यूक्रेनियन्');
INSERT INTO `country` (`id`, `name`) VALUES ('yo', 'योरूबा');
INSERT INTO `country` (`id`, `name`) VALUES ('raj', 'राजस्थानी');
INSERT INTO `country` (`id`, `name`) VALUES ('rap', 'रापानुई');
INSERT INTO `country` (`id`, `name`) VALUES ('rar', 'रारोटोंगा');
INSERT INTO `country` (`id`, `name`) VALUES ('zxx', 'रिक्त');
INSERT INTO `country` (`id`, `name`) VALUES ('root', 'रुट');
INSERT INTO `country` (`id`, `name`) VALUES ('rom', 'रुमानी');
INSERT INTO `country` (`id`, `name`) VALUES ('ru', 'रुसी');
INSERT INTO `country` (`id`, `name`) VALUES ('ro', 'रूमानीयन्');
INSERT INTO `country` (`id`, `name`) VALUES ('rm', 'रेह्टो-रोमान्स');
INSERT INTO `country` (`id`, `name`) VALUES ('roa', 'रोमान्स्');
INSERT INTO `country` (`id`, `name`) VALUES ('lo', 'लाओसीयन्');
INSERT INTO `country` (`id`, `name`) VALUES ('lv', 'लाटवियन् (लैट्टीश)');
INSERT INTO `country` (`id`, `name`) VALUES ('lad', 'लाड़ीनो');
INSERT INTO `country` (`id`, `name`) VALUES ('lam', 'लांबा');
INSERT INTO `country` (`id`, `name`) VALUES ('lah', 'लाह्डां');
INSERT INTO `country` (`id`, `name`) VALUES ('ln', 'लिंगाला');
INSERT INTO `country` (`id`, `name`) VALUES ('lt', 'लिथुआनियन्');
INSERT INTO `country` (`id`, `name`) VALUES ('li', 'लींबुर्गी');
INSERT INTO `country` (`id`, `name`) VALUES ('lui', 'लुईसेनो');
INSERT INTO `country` (`id`, `name`) VALUES ('luo', 'लुओ');
INSERT INTO `country` (`id`, `name`) VALUES ('lb', 'लुक्समबुर्गी');
INSERT INTO `country` (`id`, `name`) VALUES ('lun', 'लुंडा');
INSERT INTO `country` (`id`, `name`) VALUES ('lu', 'लुबा कटांगा');
INSERT INTO `country` (`id`, `name`) VALUES ('lua', 'लुबा लुलुआ');
INSERT INTO `country` (`id`, `name`) VALUES ('smj', 'लुले सामी');
INSERT INTO `country` (`id`, `name`) VALUES ('lus', 'लुशाई');
INSERT INTO `country` (`id`, `name`) VALUES ('lez', 'लेज़गीयान');
INSERT INTO `country` (`id`, `name`) VALUES ('es_419', 'लैटिन अमरिकी स्पैनिश');
INSERT INTO `country` (`id`, `name`) VALUES ('la', 'लैटीन्');
INSERT INTO `country` (`id`, `name`) VALUES ('jbo', 'लोजबान');
INSERT INTO `country` (`id`, `name`) VALUES ('loz', 'लोज़ी');
INSERT INTO `country` (`id`, `name`) VALUES ('vai', 'वाई');
INSERT INTO `country` (`id`, `name`) VALUES ('wak', 'वाकाशान');
INSERT INTO `country` (`id`, `name`) VALUES ('war', 'वारय');
INSERT INTO `country` (`id`, `name`) VALUES ('wal', 'वालामो');
INSERT INTO `country` (`id`, `name`) VALUES ('wa', 'वालुन');
INSERT INTO `country` (`id`, `name`) VALUES ('was', 'वाशो');
INSERT INTO `country` (`id`, `name`) VALUES ('vi', 'वियेतनामी');
INSERT INTO `country` (`id`, `name`) VALUES ('ve', 'वेंडा');
INSERT INTO `country` (`id`, `name`) VALUES ('cy', 'वैल्श्');
INSERT INTO `country` (`id`, `name`) VALUES ('vot', 'वोटीक');
INSERT INTO `country` (`id`, `name`) VALUES ('vo', 'वोलापोक');
INSERT INTO `country` (`id`, `name`) VALUES ('wo', 'वोलोफ');
INSERT INTO `country` (`id`, `name`) VALUES ('shn', 'शान');
INSERT INTO `country` (`id`, `name`) VALUES ('chy', 'शायान्');
INSERT INTO `country` (`id`, `name`) VALUES ('sn', 'शोना');
INSERT INTO `country` (`id`, `name`) VALUES ('sad', 'संडावे');
INSERT INTO `country` (`id`, `name`) VALUES ('sat', 'संताली');
INSERT INTO `country` (`id`, `name`) VALUES ('sam', 'समारीती आरामाईक़');
INSERT INTO `country` (`id`, `name`) VALUES ('sr', 'सर्बियन्');
INSERT INTO `country` (`id`, `name`) VALUES ('sh', 'सर्बो-क्रोएशन्');
INSERT INTO `country` (`id`, `name`) VALUES ('sal', 'सलीशान');
INSERT INTO `country` (`id`, `name`) VALUES ('sa', 'संस्कृत्');
INSERT INTO `country` (`id`, `name`) VALUES ('sg', 'सांग्रो');
INSERT INTO `country` (`id`, `name`) VALUES ('smi', 'सामी');
INSERT INTO `country` (`id`, `name`) VALUES ('sm', 'सामोअन');
INSERT INTO `country` (`id`, `name`) VALUES ('sc', 'सार्दीनी');
INSERT INTO `country` (`id`, `name`) VALUES ('sas', 'सासक');
INSERT INTO `country` (`id`, `name`) VALUES ('sd', 'सिंधी');
INSERT INTO `country` (`id`, `name`) VALUES ('syr', 'सिरिआक');
INSERT INTO `country` (`id`, `name`) VALUES ('sio', 'सीऊआन');
INSERT INTO `country` (`id`, `name`) VALUES ('bla', 'सीकसीका');
INSERT INTO `country` (`id`, `name`) VALUES ('ii', 'सीचुआन् यी');
INSERT INTO `country` (`id`, `name`) VALUES ('sid', 'सीदामो');
INSERT INTO `country` (`id`, `name`) VALUES ('sit', 'सीनो तिब्बती भाषाएँ');
INSERT INTO `country` (`id`, `name`) VALUES ('scn', 'सीसीलीअन');
INSERT INTO `country` (`id`, `name`) VALUES ('si', 'सींहाला');
INSERT INTO `country` (`id`, `name`) VALUES ('suk', 'सुकुमा');
INSERT INTO `country` (`id`, `name`) VALUES ('su', 'सुन्दानी');
INSERT INTO `country` (`id`, `name`) VALUES ('sux', 'सुमेरिअन');
INSERT INTO `country` (`id`, `name`) VALUES ('sus', 'सुसु');
INSERT INTO `country` (`id`, `name`) VALUES ('srr', 'सेरेर');
INSERT INTO `country` (`id`, `name`) VALUES ('sel', 'सेलकुप');
INSERT INTO `country` (`id`, `name`) VALUES ('sem', 'सैमीटीक भाषाएँ');
INSERT INTO `country` (`id`, `name`) VALUES ('sog', 'सोगडीयन');
INSERT INTO `country` (`id`, `name`) VALUES ('ts', 'सोंगा');
INSERT INTO `country` (`id`, `name`) VALUES ('son', 'सोंघाई');
INSERT INTO `country` (`id`, `name`) VALUES ('snk', 'सोनिंगके');
INSERT INTO `country` (`id`, `name`) VALUES ('so', 'सोमाली');
INSERT INTO `country` (`id`, `name`) VALUES ('dsb', 'सोर्बियन्');
INSERT INTO `country` (`id`, `name`) VALUES ('wen', 'सोर्बीयन');
INSERT INTO `country` (`id`, `name`) VALUES ('sco', 'स्कॉट');
INSERT INTO `country` (`id`, `name`) VALUES ('gd', 'स्कॉट्स् गैलिक्');
INSERT INTO `country` (`id`, `name`) VALUES ('sms', 'स्कोल्ट् सामी');
INSERT INTO `country` (`id`, `name`) VALUES ('es', 'स्पैनिश');
INSERT INTO `country` (`id`, `name`) VALUES ('srn', 'स्रनान् टॉंगो');
INSERT INTO `country` (`id`, `name`) VALUES ('sla', 'स्लाव्');
INSERT INTO `country` (`id`, `name`) VALUES ('den', 'स्लेव्');
INSERT INTO `country` (`id`, `name`) VALUES ('sk', 'स्लोवाक्');
INSERT INTO `country` (`id`, `name`) VALUES ('sl', 'स्लोवेनियन्');
INSERT INTO `country` (`id`, `name`) VALUES ('ss', 'स्वाटि');
INSERT INTO `country` (`id`, `name`) VALUES ('sw', 'स्वाहिली');
INSERT INTO `country` (`id`, `name`) VALUES ('sv', 'स्वीडिश');
INSERT INTO `country` (`id`, `name`) VALUES ('gsw', 'स्वीस जर्मन');
INSERT INTO `country` (`id`, `name`) VALUES ('hai', 'हईडा');
INSERT INTO `country` (`id`, `name`) VALUES ('ha', 'हउसा');
INSERT INTO `country` (`id`, `name`) VALUES ('hu', 'हंगैरीयन्');
INSERT INTO `country` (`id`, `name`) VALUES ('haw', 'हवाईअन');
INSERT INTO `country` (`id`, `name`) VALUES ('ht', 'हाईशीयन्');
INSERT INTO `country` (`id`, `name`) VALUES ('hi', 'हिंदी');
INSERT INTO `country` (`id`, `name`) VALUES ('he', 'हिब्रु');
INSERT INTO `country` (`id`, `name`) VALUES ('him', 'हिमांचली');
INSERT INTO `country` (`id`, `name`) VALUES ('hit', 'हीत्ती');
INSERT INTO `country` (`id`, `name`) VALUES ('ho', 'हीरी मोटु');
INSERT INTO `country` (`id`, `name`) VALUES ('hil', 'हीलीगैनोन');
INSERT INTO `country` (`id`, `name`) VALUES ('hup', 'हूपा');
INSERT INTO `country` (`id`, `name`) VALUES ('hz', 'हेरेरो');
INSERT INTO `country` (`id`, `name`) VALUES ('hmn', 'ह्मौंग');
