CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('aa', 'afar');
INSERT INTO [country] ([id], [name]) VALUES ('af', 'afrikaans');
INSERT INTO [country] ([id], [name]) VALUES ('sq', 'albanês');
INSERT INTO [country] ([id], [name]) VALUES ('am', 'amaric');
INSERT INTO [country] ([id], [name]) VALUES ('an', 'aragonês');
INSERT INTO [country] ([id], [name]) VALUES ('arc', 'aramaic');
INSERT INTO [country] ([id], [name]) VALUES ('ar', 'arap');
INSERT INTO [country] ([id], [name]) VALUES ('hy', 'armen');
INSERT INTO [country] ([id], [name]) VALUES ('as', 'assamês');
INSERT INTO [country] ([id], [name]) VALUES ('ast', 'asturian');
INSERT INTO [country] ([id], [name]) VALUES ('map', 'austronesian');
INSERT INTO [country] ([id], [name]) VALUES ('av', 'avar');
INSERT INTO [country] ([id], [name]) VALUES ('ae', 'avestan');
INSERT INTO [country] ([id], [name]) VALUES ('ay', 'aymarà');
INSERT INTO [country] ([id], [name]) VALUES ('az', 'azerbaijani');
INSERT INTO [country] ([id], [name]) VALUES ('nds', 'bas todesc');
INSERT INTO [country] ([id], [name]) VALUES ('eu', 'basc');
INSERT INTO [country] ([id], [name]) VALUES ('bn', 'bengalês');
INSERT INTO [country] ([id], [name]) VALUES ('be', 'bielorùs');
INSERT INTO [country] ([id], [name]) VALUES ('bs', 'bosniac');
INSERT INTO [country] ([id], [name]) VALUES ('br', 'breton');
INSERT INTO [country] ([id], [name]) VALUES ('bg', 'bulgar');
INSERT INTO [country] ([id], [name]) VALUES ('ca', 'catalan');
INSERT INTO [country] ([id], [name]) VALUES ('cs', 'cec');
INSERT INTO [country] ([id], [name]) VALUES ('ce', 'cecen');
INSERT INTO [country] ([id], [name]) VALUES ('ch', 'chamorro');
INSERT INTO [country] ([id], [name]) VALUES ('zh', 'cinês');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hans', 'cinês semplificât');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hant', 'cinês tradizionâl');
INSERT INTO [country] ([id], [name]) VALUES ('cop', 'coptic');
INSERT INTO [country] ([id], [name]) VALUES ('ko', 'corean');
INSERT INTO [country] ([id], [name]) VALUES ('kw', 'cornualiês');
INSERT INTO [country] ([id], [name]) VALUES ('co', 'cors');
INSERT INTO [country] ([id], [name]) VALUES ('hr', 'cravuat');
INSERT INTO [country] ([id], [name]) VALUES ('cr', 'cree');
INSERT INTO [country] ([id], [name]) VALUES ('ku', 'curd');
INSERT INTO [country] ([id], [name]) VALUES ('da', 'danês');
INSERT INTO [country] ([id], [name]) VALUES ('he', 'ebraic');
INSERT INTO [country] ([id], [name]) VALUES ('eo', 'esperanto');
INSERT INTO [country] ([id], [name]) VALUES ('et', 'eston');
INSERT INTO [country] ([id], [name]) VALUES ('fo', 'faroês');
INSERT INTO [country] ([id], [name]) VALUES ('fi', 'finlandês');
INSERT INTO [country] ([id], [name]) VALUES ('fj', 'fizian');
INSERT INTO [country] ([id], [name]) VALUES ('fr', 'francês');
INSERT INTO [country] ([id], [name]) VALUES ('fy', 'frisian');
INSERT INTO [country] ([id], [name]) VALUES ('ff', 'fulah');
INSERT INTO [country] ([id], [name]) VALUES ('fur', 'furlan');
INSERT INTO [country] ([id], [name]) VALUES ('ga', 'gaelic irlandês');
INSERT INTO [country] ([id], [name]) VALUES ('gd', 'gaelic scozês');
INSERT INTO [country] ([id], [name]) VALUES ('gl', 'galizian');
INSERT INTO [country] ([id], [name]) VALUES ('cy', 'galês');
INSERT INTO [country] ([id], [name]) VALUES ('ja', 'gjaponês');
INSERT INTO [country] ([id], [name]) VALUES ('ka', 'gjeorgjian');
INSERT INTO [country] ([id], [name]) VALUES ('got', 'gotic');
INSERT INTO [country] ([id], [name]) VALUES ('el', 'grêc');
INSERT INTO [country] ([id], [name]) VALUES ('ht', 'haitian');
INSERT INTO [country] ([id], [name]) VALUES ('hi', 'hindi');
INSERT INTO [country] ([id], [name]) VALUES ('io', 'ido');
INSERT INTO [country] ([id], [name]) VALUES ('und', 'indeterminade');
INSERT INTO [country] ([id], [name]) VALUES ('id', 'indonesian');
INSERT INTO [country] ([id], [name]) VALUES ('en', 'inglês');
INSERT INTO [country] ([id], [name]) VALUES ('iu', 'inuktitut');
INSERT INTO [country] ([id], [name]) VALUES ('ik', 'inupiaq');
INSERT INTO [country] ([id], [name]) VALUES ('is', 'islandês');
INSERT INTO [country] ([id], [name]) VALUES ('kl', 'kalaallisut');
INSERT INTO [country] ([id], [name]) VALUES ('kn', 'kannada');
INSERT INTO [country] ([id], [name]) VALUES ('kk', 'kazac');
INSERT INTO [country] ([id], [name]) VALUES ('km', 'khmer');
INSERT INTO [country] ([id], [name]) VALUES ('lad', 'ladin');
INSERT INTO [country] ([id], [name]) VALUES ('la', 'latin');
INSERT INTO [country] ([id], [name]) VALUES ('apa', 'lenghe Apache');
INSERT INTO [country] ([id], [name]) VALUES ('cel', 'lenghe celtiche');
INSERT INTO [country] ([id], [name]) VALUES ('gem', 'lenghe gjermaniche');
INSERT INTO [country] ([id], [name]) VALUES ('ine', 'lenghe indo-europeane');
INSERT INTO [country] ([id], [name]) VALUES ('roa', 'lenghe romanze');
INSERT INTO [country] ([id], [name]) VALUES ('sla', 'lenghe sclave');
INSERT INTO [country] ([id], [name]) VALUES ('myn', 'lenghis Maya');
INSERT INTO [country] ([id], [name]) VALUES ('aus', 'lenghis australianis');
INSERT INTO [country] ([id], [name]) VALUES ('mul', 'lenghis multiplis');
INSERT INTO [country] ([id], [name]) VALUES ('mis', 'lenghis variis');
INSERT INTO [country] ([id], [name]) VALUES ('lv', 'leton');
INSERT INTO [country] ([id], [name]) VALUES ('li', 'limburghês');
INSERT INTO [country] ([id], [name]) VALUES ('ln', 'lingala');
INSERT INTO [country] ([id], [name]) VALUES ('lt', 'lituan');
INSERT INTO [country] ([id], [name]) VALUES ('lb', 'lussemburghês');
INSERT INTO [country] ([id], [name]) VALUES ('mk', 'macedon');
INSERT INTO [country] ([id], [name]) VALUES ('ml', 'malayalam');
INSERT INTO [country] ([id], [name]) VALUES ('mt', 'maltês');
INSERT INTO [country] ([id], [name]) VALUES ('ms', 'malês');
INSERT INTO [country] ([id], [name]) VALUES ('gv', 'manx');
INSERT INTO [country] ([id], [name]) VALUES ('mi', 'maori');
INSERT INTO [country] ([id], [name]) VALUES ('mr', 'marathi');
INSERT INTO [country] ([id], [name]) VALUES ('mwl', 'mirandês');
INSERT INTO [country] ([id], [name]) VALUES ('mo', 'moldâf');
INSERT INTO [country] ([id], [name]) VALUES ('mn', 'mongul');
INSERT INTO [country] ([id], [name]) VALUES ('nap', 'napoletan');
INSERT INTO [country] ([id], [name]) VALUES ('nv', 'navajo');
INSERT INTO [country] ([id], [name]) VALUES ('ne', 'nepalês');
INSERT INTO [country] ([id], [name]) VALUES ('no', 'norvegjês');
INSERT INTO [country] ([id], [name]) VALUES ('nb', 'norvegjês bokmål');
INSERT INTO [country] ([id], [name]) VALUES ('nn', 'norvegjês nynorsk');
INSERT INTO [country] ([id], [name]) VALUES ('oc', 'ocitan');
INSERT INTO [country] ([id], [name]) VALUES ('nl', 'olandês');
INSERT INTO [country] ([id], [name]) VALUES ('hu', 'ongjarês');
INSERT INTO [country] ([id], [name]) VALUES ('os', 'osetic');
INSERT INTO [country] ([id], [name]) VALUES ('pap', 'papiamento');
INSERT INTO [country] ([id], [name]) VALUES ('ps', 'pashto');
INSERT INTO [country] ([id], [name]) VALUES ('fa', 'persian');
INSERT INTO [country] ([id], [name]) VALUES ('pl', 'polac');
INSERT INTO [country] ([id], [name]) VALUES ('pt', 'portughês');
INSERT INTO [country] ([id], [name]) VALUES ('pt_BR', 'portughês brasilian');
INSERT INTO [country] ([id], [name]) VALUES ('pa', 'punjabi');
INSERT INTO [country] ([id], [name]) VALUES ('qu', 'quechua');
INSERT INTO [country] ([id], [name]) VALUES ('ro', 'romen');
INSERT INTO [country] ([id], [name]) VALUES ('rm', 'rumanç');
INSERT INTO [country] ([id], [name]) VALUES ('ru', 'rus');
INSERT INTO [country] ([id], [name]) VALUES ('se', 'sami setentrionâl');
INSERT INTO [country] ([id], [name]) VALUES ('sm', 'samoan');
INSERT INTO [country] ([id], [name]) VALUES ('sa', 'sanscrit');
INSERT INTO [country] ([id], [name]) VALUES ('sc', 'sardegnûl');
INSERT INTO [country] ([id], [name]) VALUES ('den', 'sclâf');
INSERT INTO [country] ([id], [name]) VALUES ('cu', 'sclâf de glesie');
INSERT INTO [country] ([id], [name]) VALUES ('sco', 'scozês');
INSERT INTO [country] ([id], [name]) VALUES ('sr', 'serp');
INSERT INTO [country] ([id], [name]) VALUES ('scn', 'sicilian');
INSERT INTO [country] ([id], [name]) VALUES ('si', 'sinalês');
INSERT INTO [country] ([id], [name]) VALUES ('sd', 'sindhi');
INSERT INTO [country] ([id], [name]) VALUES ('sk', 'slovac');
INSERT INTO [country] ([id], [name]) VALUES ('sl', 'sloven');
INSERT INTO [country] ([id], [name]) VALUES ('so', 'somal');
INSERT INTO [country] ([id], [name]) VALUES ('es', 'spagnûl');
INSERT INTO [country] ([id], [name]) VALUES ('sux', 'sumeric');
INSERT INTO [country] ([id], [name]) VALUES ('sv', 'svedês');
INSERT INTO [country] ([id], [name]) VALUES ('sw', 'swahili');
INSERT INTO [country] ([id], [name]) VALUES ('tl', 'tagalog');
INSERT INTO [country] ([id], [name]) VALUES ('tg', 'tagic');
INSERT INTO [country] ([id], [name]) VALUES ('ty', 'tahitian');
INSERT INTO [country] ([id], [name]) VALUES ('it', 'talian');
INSERT INTO [country] ([id], [name]) VALUES ('ta', 'tamil');
INSERT INTO [country] ([id], [name]) VALUES ('tt', 'tartar');
INSERT INTO [country] ([id], [name]) VALUES ('te', 'telegu');
INSERT INTO [country] ([id], [name]) VALUES ('tet', 'tetum');
INSERT INTO [country] ([id], [name]) VALUES ('th', 'thai');
INSERT INTO [country] ([id], [name]) VALUES ('bo', 'tibetan');
INSERT INTO [country] ([id], [name]) VALUES ('de', 'todesc');
INSERT INTO [country] ([id], [name]) VALUES ('tr', 'turc');
INSERT INTO [country] ([id], [name]) VALUES ('ota', 'turc otoman');
INSERT INTO [country] ([id], [name]) VALUES ('uk', 'ucrain');
INSERT INTO [country] ([id], [name]) VALUES ('ur', 'urdu');
INSERT INTO [country] ([id], [name]) VALUES ('uz', 'uzbec');
INSERT INTO [country] ([id], [name]) VALUES ('wa', 'valon');
INSERT INTO [country] ([id], [name]) VALUES ('egy', 'vieri egjizian');
INSERT INTO [country] ([id], [name]) VALUES ('fro', 'vieri francês');
INSERT INTO [country] ([id], [name]) VALUES ('grc', 'vieri grêc');
INSERT INTO [country] ([id], [name]) VALUES ('ang', 'vieri inglês');
INSERT INTO [country] ([id], [name]) VALUES ('sga', 'vieri irlandês');
INSERT INTO [country] ([id], [name]) VALUES ('non', 'vieri norvegjês');
INSERT INTO [country] ([id], [name]) VALUES ('peo', 'vieri persian');
INSERT INTO [country] ([id], [name]) VALUES ('pro', 'vieri provenzâl');
INSERT INTO [country] ([id], [name]) VALUES ('vi', 'vietnamite');
INSERT INTO [country] ([id], [name]) VALUES ('yi', 'yiddish');
INSERT INTO [country] ([id], [name]) VALUES ('zu', 'zulu');
