CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('anp', 'अंगिका');
INSERT INTO "country" ("id", "name") VALUES ('ak', 'अकन');
INSERT INTO "country" ("id", "name") VALUES ('ach', 'अकोली');
INSERT INTO "country" ("id", "name") VALUES ('akk', 'अक्कादिआन');
INSERT INTO "country" ("id", "name") VALUES ('ace', 'अचीनी');
INSERT INTO "country" ("id", "name") VALUES ('und', 'अज्ञात वा अवैध भाषा');
INSERT INTO "country" ("id", "name") VALUES ('az', 'अझरबैजानी');
INSERT INTO "country" ("id", "name") VALUES ('ada', 'अडांग्मे');
INSERT INTO "country" ("id", "name") VALUES ('ady', 'अडिघे');
INSERT INTO "country" ("id", "name") VALUES ('cch', 'अत्सम');
INSERT INTO "country" ("id", "name") VALUES ('apa', 'अपाचे भाषा');
INSERT INTO "country" ("id", "name") VALUES ('hsb', 'अप्पर सॉर्बियन');
INSERT INTO "country" ("id", "name") VALUES ('aa', 'अफार');
INSERT INTO "country" ("id", "name") VALUES ('af', 'अफ्रिकान्स');
INSERT INTO "country" ("id", "name") VALUES ('afh', 'अफ्रिहिली');
INSERT INTO "country" ("id", "name") VALUES ('afa', 'अफ्रो-अशियाई भाषा');
INSERT INTO "country" ("id", "name") VALUES ('ab', 'अबखेजियन');
INSERT INTO "country" ("id", "name") VALUES ('nwc', 'अभिजात नेवारी');
INSERT INTO "country" ("id", "name") VALUES ('syc', 'अभिजात सिरियाक');
INSERT INTO "country" ("id", "name") VALUES ('am', 'अम्हारिक');
INSERT INTO "country" ("id", "name") VALUES ('ar', 'अरबी');
INSERT INTO "country" ("id", "name") VALUES ('arp', 'अराफाओ');
INSERT INTO "country" ("id", "name") VALUES ('arw', 'अरावक');
INSERT INTO "country" ("id", "name") VALUES ('rup', 'अरोमानियन');
INSERT INTO "country" ("id", "name") VALUES ('an', 'अर्गोनीज');
INSERT INTO "country" ("id", "name") VALUES ('ale', 'अलेउत');
INSERT INTO "country" ("id", "name") VALUES ('tut', 'अल्टॅइक भाषा');
INSERT INTO "country" ("id", "name") VALUES ('sq', 'अल्बानियन');
INSERT INTO "country" ("id", "name") VALUES ('awa', 'अवधी');
INSERT INTO "country" ("id", "name") VALUES ('ae', 'अवेस्तन');
INSERT INTO "country" ("id", "name") VALUES ('ast', 'अस्तुरियन');
INSERT INTO "country" ("id", "name") VALUES ('ath', 'अ‍ॅथापास्कान भाषा');
INSERT INTO "country" ("id", "name") VALUES ('arc', 'अ‍ॅरेमाइक');
INSERT INTO "country" ("id", "name") VALUES ('arn', 'अ‍ॅरॉकॅनियन');
INSERT INTO "country" ("id", "name") VALUES ('alg', 'अ‍ॅल्गोक्वियन भाषा');
INSERT INTO "country" ("id", "name") VALUES ('av', 'अ‍ॅव्हेरिक');
INSERT INTO "country" ("id", "name") VALUES ('is', 'आईसलँडिक');
INSERT INTO "country" ("id", "name") VALUES ('ga', 'आयरिश');
INSERT INTO "country" ("id", "name") VALUES ('hy', 'आर्मेनियन');
INSERT INTO "country" ("id", "name") VALUES ('as', 'आसामी');
INSERT INTO "country" ("id", "name") VALUES ('inh', 'इंगुश');
INSERT INTO "country" ("id", "name") VALUES ('en', 'इंग्रजी');
INSERT INTO "country" ("id", "name") VALUES ('cpe', 'इंग्रजी-आधारित क्रेओल वा पिजिन');
INSERT INTO "country" ("id", "name") VALUES ('ine', 'इंडो-युरोपीयन भाषा');
INSERT INTO "country" ("id", "name") VALUES ('id', 'इंडोनेशियन');
INSERT INTO "country" ("id", "name") VALUES ('ijo', 'इजो');
INSERT INTO "country" ("id", "name") VALUES ('it', 'इटालियन');
INSERT INTO "country" ("id", "name") VALUES ('io', 'इडौ');
INSERT INTO "country" ("id", "name") VALUES ('smn', 'इनारी सामी');
INSERT INTO "country" ("id", "name") VALUES ('iu', 'इनुकिटुट्');
INSERT INTO "country" ("id", "name") VALUES ('ik', 'इनूपियाक');
INSERT INTO "country" ("id", "name") VALUES ('ie', 'इन्टरलिंग');
INSERT INTO "country" ("id", "name") VALUES ('ia', 'इन्टरलिंग्वा');
INSERT INTO "country" ("id", "name") VALUES ('iba', 'इबान');
INSERT INTO "country" ("id", "name") VALUES ('pt_PT', 'इबेरियन पोर्तुगीज');
INSERT INTO "country" ("id", "name") VALUES ('es_ES', 'इबेरियन स्पॅनिश');
INSERT INTO "country" ("id", "name") VALUES ('iro', 'इरोक्वोइयन भाषा');
INSERT INTO "country" ("id", "name") VALUES ('ilo', 'इलोको');
INSERT INTO "country" ("id", "name") VALUES ('ee', 'इवे');
INSERT INTO "country" ("id", "name") VALUES ('ewo', 'इवोन्डो');
INSERT INTO "country" ("id", "name") VALUES ('et', 'इस्टोनियन');
INSERT INTO "country" ("id", "name") VALUES ('ig', 'ईग्बो');
INSERT INTO "country" ("id", "name") VALUES ('ira', 'ईराणी भाषा');
INSERT INTO "country" ("id", "name") VALUES ('ug', 'उईघुर');
INSERT INTO "country" ("id", "name") VALUES ('uz', 'उझ्बेक');
INSERT INTO "country" ("id", "name") VALUES ('or', 'उडिया');
INSERT INTO "country" ("id", "name") VALUES ('nai', 'उत्तरी अमेरीकी इंडियन भाषा');
INSERT INTO "country" ("id", "name") VALUES ('nd', 'उत्तरी देबेली');
INSERT INTO "country" ("id", "name") VALUES ('frr', 'उत्तरी फ्रिशियन');
INSERT INTO "country" ("id", "name") VALUES ('nso', 'उत्तरी सोथो');
INSERT INTO "country" ("id", "name") VALUES ('udm', 'उदमुर्त');
INSERT INTO "country" ("id", "name") VALUES ('umb', 'उम्बुन्डु');
INSERT INTO "country" ("id", "name") VALUES ('ur', 'उर्दू');
INSERT INTO "country" ("id", "name") VALUES ('mul', 'एकविध भाषा');
INSERT INTO "country" ("id", "name") VALUES ('eka', 'एकाजुक');
INSERT INTO "country" ("id", "name") VALUES ('nqo', 'एन्को');
INSERT INTO "country" ("id", "name") VALUES ('efi', 'एफिक');
INSERT INTO "country" ("id", "name") VALUES ('myv', 'एर्झ्या');
INSERT INTO "country" ("id", "name") VALUES ('elx', 'एलामाइट');
INSERT INTO "country" ("id", "name") VALUES ('eo', 'एस्परान्टो');
INSERT INTO "country" ("id", "name") VALUES ('ain', 'ऐनू');
INSERT INTO "country" ("id", "name") VALUES ('ay', 'ऐमरा');
INSERT INTO "country" ("id", "name") VALUES ('oc', 'ऑक्सिटान');
INSERT INTO "country" ("id", "name") VALUES ('de_AT', 'ऑस्ट्रियन जर्मन');
INSERT INTO "country" ("id", "name") VALUES ('en_AU', 'ऑस्ट्रेलियन इंग्रजी');
INSERT INTO "country" ("id", "name") VALUES ('aus', 'ऑस्ट्रेलियन भाषा');
INSERT INTO "country" ("id", "name") VALUES ('map', 'ऑस्ट्रोनेशियन');
INSERT INTO "country" ("id", "name") VALUES ('oj', 'ओजिब्वा');
INSERT INTO "country" ("id", "name") VALUES ('ota', 'ओटोमान तुर्किश');
INSERT INTO "country" ("id", "name") VALUES ('oto', 'ओटोमियन भाषा');
INSERT INTO "country" ("id", "name") VALUES ('om', 'ओरोमो');
INSERT INTO "country" ("id", "name") VALUES ('vo', 'ओलापुक');
INSERT INTO "country" ("id", "name") VALUES ('osa', 'ओसेज');
INSERT INTO "country" ("id", "name") VALUES ('os', 'ओस्सेटिक');
INSERT INTO "country" ("id", "name") VALUES ('kk', 'कझाक');
INSERT INTO "country" ("id", "name") VALUES ('kr', 'कनुरी');
INSERT INTO "country" ("id", "name") VALUES ('kn', 'कन्नड');
INSERT INTO "country" ("id", "name") VALUES ('kab', 'कबाइल');
INSERT INTO "country" ("id", "name") VALUES ('kbd', 'कबार्डियन');
INSERT INTO "country" ("id", "name") VALUES ('kam', 'कम्बा');
INSERT INTO "country" ("id", "name") VALUES ('krc', 'कराचय-बाल्कर');
INSERT INTO "country" ("id", "name") VALUES ('krl', 'करेलियन');
INSERT INTO "country" ("id", "name") VALUES ('kl', 'कलाल्लिसुत');
INSERT INTO "country" ("id", "name") VALUES ('kg', 'काँगो');
INSERT INTO "country" ("id", "name") VALUES ('kac', 'काचिन');
INSERT INTO "country" ("id", "name") VALUES ('kaa', 'कारा-कल्पक');
INSERT INTO "country" ("id", "name") VALUES ('kar', 'कारेन');
INSERT INTO "country" ("id", "name") VALUES ('xal', 'काल्मिक');
INSERT INTO "country" ("id", "name") VALUES ('kaw', 'कावी');
INSERT INTO "country" ("id", "name") VALUES ('csb', 'काशुबियन');
INSERT INTO "country" ("id", "name") VALUES ('ks', 'काश्मीरी');
INSERT INTO "country" ("id", "name") VALUES ('ki', 'किकुयू');
INSERT INTO "country" ("id", "name") VALUES ('rw', 'किन्यार्वान्डा');
INSERT INTO "country" ("id", "name") VALUES ('kmb', 'किम्बन्दु');
INSERT INTO "country" ("id", "name") VALUES ('ky', 'किरगीझ');
INSERT INTO "country" ("id", "name") VALUES ('kut', 'कुतेनाई');
INSERT INTO "country" ("id", "name") VALUES ('kum', 'कुमीक');
INSERT INTO "country" ("id", "name") VALUES ('kru', 'कुरूख');
INSERT INTO "country" ("id", "name") VALUES ('ku', 'कुर्दिश');
INSERT INTO "country" ("id", "name") VALUES ('cus', 'कुशितिक भाषा');
INSERT INTO "country" ("id", "name") VALUES ('art', 'कृत्रिम भाषा');
INSERT INTO "country" ("id", "name") VALUES ('ca', 'कॅटलान');
INSERT INTO "country" ("id", "name") VALUES ('cad', 'कॅड्डो');
INSERT INTO "country" ("id", "name") VALUES ('en_CA', 'कॅनेडियन इंग्रजी');
INSERT INTO "country" ("id", "name") VALUES ('fr_CA', 'कॅनेडियन फ्रेंच');
INSERT INTO "country" ("id", "name") VALUES ('ch', 'कॅमोरो');
INSERT INTO "country" ("id", "name") VALUES ('car', 'कॅरिब');
INSERT INTO "country" ("id", "name") VALUES ('cel', 'केल्टिक भाषा');
INSERT INTO "country" ("id", "name") VALUES ('cau', 'कॉकेशियन भाषा');
INSERT INTO "country" ("id", "name") VALUES ('cop', 'कॉप्टिक');
INSERT INTO "country" ("id", "name") VALUES ('kok', 'कोंकणी');
INSERT INTO "country" ("id", "name") VALUES ('kv', 'कोमी');
INSERT INTO "country" ("id", "name") VALUES ('ko', 'कोरियन');
INSERT INTO "country" ("id", "name") VALUES ('kfo', 'कोरो');
INSERT INTO "country" ("id", "name") VALUES ('kw', 'कोर्निश');
INSERT INTO "country" ("id", "name") VALUES ('co', 'कोर्सिकन');
INSERT INTO "country" ("id", "name") VALUES ('kos', 'कोसरियन');
INSERT INTO "country" ("id", "name") VALUES ('kpe', 'क्पेल्ले');
INSERT INTO "country" ("id", "name") VALUES ('crh', 'क्राइमीन तुर्की');
INSERT INTO "country" ("id", "name") VALUES ('cr', 'क्री');
INSERT INTO "country" ("id", "name") VALUES ('mus', 'क्रीक');
INSERT INTO "country" ("id", "name") VALUES ('kro', 'क्रू');
INSERT INTO "country" ("id", "name") VALUES ('crp', 'क्रेओल वा पिजिन');
INSERT INTO "country" ("id", "name") VALUES ('hr', 'क्रोएशियन');
INSERT INTO "country" ("id", "name") VALUES ('tlh', 'क्लिंगॉन');
INSERT INTO "country" ("id", "name") VALUES ('kj', 'क्वान्यामा');
INSERT INTO "country" ("id", "name") VALUES ('qu', 'क्वेचुआ');
INSERT INTO "country" ("id", "name") VALUES ('kha', 'खासी');
INSERT INTO "country" ("id", "name") VALUES ('kho', 'खोतानीस');
INSERT INTO "country" ("id", "name") VALUES ('xh', 'खोसा');
INSERT INTO "country" ("id", "name") VALUES ('khi', 'खोसियन भाषा');
INSERT INTO "country" ("id", "name") VALUES ('km', 'ख्मेर');
INSERT INTO "country" ("id", "name") VALUES ('gaa', 'गा');
INSERT INTO "country" ("id", "name") VALUES ('gon', 'गाँडी');
INSERT INTO "country" ("id", "name") VALUES ('lg', 'गांडा');
INSERT INTO "country" ("id", "name") VALUES ('gay', 'गायो');
INSERT INTO "country" ("id", "name") VALUES ('gez', 'गीझ');
INSERT INTO "country" ("id", "name") VALUES ('gn', 'गुआरनी');
INSERT INTO "country" ("id", "name") VALUES ('gu', 'गुजराती');
INSERT INTO "country" ("id", "name") VALUES ('gl', 'गॅलिशियन');
INSERT INTO "country" ("id", "name") VALUES ('got', 'गॉथिक');
INSERT INTO "country" ("id", "name") VALUES ('gor', 'गोरोन्तालो');
INSERT INTO "country" ("id", "name") VALUES ('el', 'ग्रीक');
INSERT INTO "country" ("id", "name") VALUES ('grb', 'ग्रेबो');
INSERT INTO "country" ("id", "name") VALUES ('gwi', 'ग्विच\'इन');
INSERT INTO "country" ("id", "name") VALUES ('cu', 'चर्च स्लाव्हिक');
INSERT INTO "country" ("id", "name") VALUES ('cmc', 'चामिक भाषा');
INSERT INTO "country" ("id", "name") VALUES ('chn', 'चिनूक जारगॉन');
INSERT INTO "country" ("id", "name") VALUES ('chb', 'चिब्चा');
INSERT INTO "country" ("id", "name") VALUES ('zh', 'चीनी');
INSERT INTO "country" ("id", "name") VALUES ('sit', 'चीनी-तिबेटी भाषा');
INSERT INTO "country" ("id", "name") VALUES ('chk', 'चूकीसे');
INSERT INTO "country" ("id", "name") VALUES ('cv', 'चूवाश');
INSERT INTO "country" ("id", "name") VALUES ('ce', 'चेचन');
INSERT INTO "country" ("id", "name") VALUES ('chr', 'चेरूकी');
INSERT INTO "country" ("id", "name") VALUES ('cho', 'चोक्तौ');
INSERT INTO "country" ("id", "name") VALUES ('chg', 'छगाताई');
INSERT INTO "country" ("id", "name") VALUES ('ja', 'जपानी');
INSERT INTO "country" ("id", "name") VALUES ('de', 'जर्मन');
INSERT INTO "country" ("id", "name") VALUES ('gem', 'जर्मनिक भाषा');
INSERT INTO "country" ("id", "name") VALUES ('jv', 'जावनीस्');
INSERT INTO "country" ("id", "name") VALUES ('gil', 'जिल्बरटीज');
INSERT INTO "country" ("id", "name") VALUES ('jrb', 'जुदेओ-अरबी');
INSERT INTO "country" ("id", "name") VALUES ('jpr', 'जुदेओ-फारसी');
INSERT INTO "country" ("id", "name") VALUES ('ka', 'जॉर्जियन');
INSERT INTO "country" ("id", "name") VALUES ('kaj', 'ज्जु');
INSERT INTO "country" ("id", "name") VALUES ('znd', 'झन्डे');
INSERT INTO "country" ("id", "name") VALUES ('zza', 'झाझा');
INSERT INTO "country" ("id", "name") VALUES ('za', 'झुआंग');
INSERT INTO "country" ("id", "name") VALUES ('zun', 'झुनी');
INSERT INTO "country" ("id", "name") VALUES ('zu', 'झुलू');
INSERT INTO "country" ("id", "name") VALUES ('cs', 'झेक');
INSERT INTO "country" ("id", "name") VALUES ('zen', 'झेनान्गा');
INSERT INTO "country" ("id", "name") VALUES ('zap', 'झेपोटेक');
INSERT INTO "country" ("id", "name") VALUES ('dz', 'झोंगखा');
INSERT INTO "country" ("id", "name") VALUES ('tig', 'टाइग्रे');
INSERT INTO "country" ("id", "name") VALUES ('tl', 'टागालोग');
INSERT INTO "country" ("id", "name") VALUES ('ti', 'टिग्रिन्या');
INSERT INTO "country" ("id", "name") VALUES ('tem', 'टिम्ने');
INSERT INTO "country" ("id", "name") VALUES ('tvl', 'टुवालु');
INSERT INTO "country" ("id", "name") VALUES ('tyv', 'टुवीनियन');
INSERT INTO "country" ("id", "name") VALUES ('to', 'टोंगा');
INSERT INTO "country" ("id", "name") VALUES ('tpi', 'टोक पिसिन');
INSERT INTO "country" ("id", "name") VALUES ('tkl', 'टोकेलाऊ');
INSERT INTO "country" ("id", "name") VALUES ('tup', 'ट्यूपी भाषा');
INSERT INTO "country" ("id", "name") VALUES ('tw', 'ट्वी');
INSERT INTO "country" ("id", "name") VALUES ('nl', 'डच');
INSERT INTO "country" ("id", "name") VALUES ('da', 'डॅनिश');
INSERT INTO "country" ("id", "name") VALUES ('del', 'डेलॅवेयर');
INSERT INTO "country" ("id", "name") VALUES ('ng', 'डोंगा');
INSERT INTO "country" ("id", "name") VALUES ('doi', 'डोगरी');
INSERT INTO "country" ("id", "name") VALUES ('dgr', 'डोग्रिब');
INSERT INTO "country" ("id", "name") VALUES ('dyu', 'ड्युला');
INSERT INTO "country" ("id", "name") VALUES ('tt', 'ततार');
INSERT INTO "country" ("id", "name") VALUES ('ta', 'तमिळ');
INSERT INTO "country" ("id", "name") VALUES ('tum', 'तम्बूका');
INSERT INTO "country" ("id", "name") VALUES ('tai', 'ताई भाषा');
INSERT INTO "country" ("id", "name") VALUES ('tg', 'ताजिक');
INSERT INTO "country" ("id", "name") VALUES ('tmh', 'तामाशेक');
INSERT INTO "country" ("id", "name") VALUES ('ty', 'ताहितीयन');
INSERT INTO "country" ("id", "name") VALUES ('bo', 'तिबेटी');
INSERT INTO "country" ("id", "name") VALUES ('tiv', 'तिव');
INSERT INTO "country" ("id", "name") VALUES ('tk', 'तुर्कमेन');
INSERT INTO "country" ("id", "name") VALUES ('tr', 'तुर्की');
INSERT INTO "country" ("id", "name") VALUES ('tet', 'तेतुम');
INSERT INTO "country" ("id", "name") VALUES ('ter', 'तेरेनो');
INSERT INTO "country" ("id", "name") VALUES ('te', 'तेलगू');
INSERT INTO "country" ("id", "name") VALUES ('kcg', 'त्याप');
INSERT INTO "country" ("id", "name") VALUES ('tn', 'त्स्वाना');
INSERT INTO "country" ("id", "name") VALUES ('th', 'थाई');
INSERT INTO "country" ("id", "name") VALUES ('sai', 'दक्षिण अमेरीकी इंडियन भाषा');
INSERT INTO "country" ("id", "name") VALUES ('alt', 'दक्षिणात्य अल्ताई');
INSERT INTO "country" ("id", "name") VALUES ('nr', 'दक्षिणात्य देबेली');
INSERT INTO "country" ("id", "name") VALUES ('sma', 'दक्षिणात्य सामी');
INSERT INTO "country" ("id", "name") VALUES ('dak', 'दाकोता');
INSERT INTO "country" ("id", "name") VALUES ('day', 'दायक');
INSERT INTO "country" ("id", "name") VALUES ('dar', 'दार्गवा');
INSERT INTO "country" ("id", "name") VALUES ('din', 'दिन्का');
INSERT INTO "country" ("id", "name") VALUES ('dv', 'दिवेही');
INSERT INTO "country" ("id", "name") VALUES ('dua', 'दुआला');
INSERT INTO "country" ("id", "name") VALUES ('dra', 'द्रविडी भाषा');
INSERT INTO "country" ("id", "name") VALUES ('na', 'नउरू');
INSERT INTO "country" ("id", "name") VALUES ('nah', 'नहुआत्ल');
INSERT INTO "country" ("id", "name") VALUES ('nic', 'नाइजर-कॉर्डोफॅनियन भाषा');
INSERT INTO "country" ("id", "name") VALUES ('nv', 'नावाजो');
INSERT INTO "country" ("id", "name") VALUES ('dsb', 'निम्न सोर्बियन');
INSERT INTO "country" ("id", "name") VALUES ('nia', 'नियास');
INSERT INTO "country" ("id", "name") VALUES ('niu', 'नियुआन');
INSERT INTO "country" ("id", "name") VALUES ('ssa', 'निलो-सहारन भाषा');
INSERT INTO "country" ("id", "name") VALUES ('ne', 'नेपाळी');
INSERT INTO "country" ("id", "name") VALUES ('nap', 'नेपोलिटान');
INSERT INTO "country" ("id", "name") VALUES ('new', 'नेवारी');
INSERT INTO "country" ("id", "name") VALUES ('se', 'नॉर्दन सामी');
INSERT INTO "country" ("id", "name") VALUES ('nn', 'नॉर्वेजियन न्योर्स्क');
INSERT INTO "country" ("id", "name") VALUES ('nb', 'नॉर्वेजियन बोकमाल');
INSERT INTO "country" ("id", "name") VALUES ('nog', 'नोगाई');
INSERT INTO "country" ("id", "name") VALUES ('no', 'नोर्वेजियन');
INSERT INTO "country" ("id", "name") VALUES ('nzi', 'न्झिमा');
INSERT INTO "country" ("id", "name") VALUES ('nyn', 'न्यानकोल');
INSERT INTO "country" ("id", "name") VALUES ('ny', 'न्यान्जा');
INSERT INTO "country" ("id", "name") VALUES ('nym', 'न्यामवेझी');
INSERT INTO "country" ("id", "name") VALUES ('tog', 'न्यासा टोन्गा');
INSERT INTO "country" ("id", "name") VALUES ('nub', 'न्युबियान भाषा');
INSERT INTO "country" ("id", "name") VALUES ('nyo', 'न्योरो');
INSERT INTO "country" ("id", "name") VALUES ('pag', 'पंगासीनान');
INSERT INTO "country" ("id", "name") VALUES ('pa', 'पंजाबी');
INSERT INTO "country" ("id", "name") VALUES ('ps', 'पश्तो');
INSERT INTO "country" ("id", "name") VALUES ('pal', 'पहलवी');
INSERT INTO "country" ("id", "name") VALUES ('pap', 'पापियामेन्टो');
INSERT INTO "country" ("id", "name") VALUES ('paa', 'पापुन भाषा');
INSERT INTO "country" ("id", "name") VALUES ('pam', 'पाम्पान्गा');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hant', 'पारंपारिक चीनी');
INSERT INTO "country" ("id", "name") VALUES ('pau', 'पालाउआन');
INSERT INTO "country" ("id", "name") VALUES ('pi', 'पाली');
INSERT INTO "country" ("id", "name") VALUES ('fy', 'पाश्चात्य फ्रिशियन');
INSERT INTO "country" ("id", "name") VALUES ('sga', 'पुरातन आयरिश');
INSERT INTO "country" ("id", "name") VALUES ('ang', 'पुरातन इंग्रजी');
INSERT INTO "country" ("id", "name") VALUES ('non', 'पुरातन नॉर्स');
INSERT INTO "country" ("id", "name") VALUES ('pro', 'पुरातन प्रोव्हेन्सल');
INSERT INTO "country" ("id", "name") VALUES ('peo', 'पुरातन फारसी');
INSERT INTO "country" ("id", "name") VALUES ('fro', 'पुरातन फ्रेंच');
INSERT INTO "country" ("id", "name") VALUES ('goh', 'पुरातन हाइ जर्मन');
INSERT INTO "country" ("id", "name") VALUES ('pt', 'पोर्तुगीज');
INSERT INTO "country" ("id", "name") VALUES ('cpp', 'पोर्तुगीज-आधारित क्रेओल या पिजिन');
INSERT INTO "country" ("id", "name") VALUES ('pl', 'पोलिश');
INSERT INTO "country" ("id", "name") VALUES ('pon', 'पोह्नपियन');
INSERT INTO "country" ("id", "name") VALUES ('frs', 'पौर्वात्य फ्रिशियन');
INSERT INTO "country" ("id", "name") VALUES ('pra', 'प्राकृत भाषा');
INSERT INTO "country" ("id", "name") VALUES ('egy', 'प्राचीन इजिप्शियन');
INSERT INTO "country" ("id", "name") VALUES ('grc', 'प्राचीन ग्रीक');
INSERT INTO "country" ("id", "name") VALUES ('fan', 'फँग');
INSERT INTO "country" ("id", "name") VALUES ('fat', 'फन्टी');
INSERT INTO "country" ("id", "name") VALUES ('fo', 'फरोइए');
INSERT INTO "country" ("id", "name") VALUES ('fa', 'फारसी');
INSERT INTO "country" ("id", "name") VALUES ('fj', 'फिजीयन');
INSERT INTO "country" ("id", "name") VALUES ('fi', 'फिन्निश');
INSERT INTO "country" ("id", "name") VALUES ('fiu', 'फिन्नो-उग्रीयन भाषा');
INSERT INTO "country" ("id", "name") VALUES ('fil', 'फिलिपिनो');
INSERT INTO "country" ("id", "name") VALUES ('phi', 'फिलिपीनी भाषा');
INSERT INTO "country" ("id", "name") VALUES ('ff', 'फुलाह');
INSERT INTO "country" ("id", "name") VALUES ('fon', 'फॉन');
INSERT INTO "country" ("id", "name") VALUES ('phn', 'फोनिशियन');
INSERT INTO "country" ("id", "name") VALUES ('fur', 'फ्रियुलियान');
INSERT INTO "country" ("id", "name") VALUES ('fr', 'फ्रेंच');
INSERT INTO "country" ("id", "name") VALUES ('cpf', 'फ्रेंच-आधारित क्रेओल वा पिजिन');
INSERT INTO "country" ("id", "name") VALUES ('nl_BE', 'फ्लेमिश');
INSERT INTO "country" ("id", "name") VALUES ('bn', 'बंगाली');
INSERT INTO "country" ("id", "name") VALUES ('bug', 'बगिनीस');
INSERT INTO "country" ("id", "name") VALUES ('btk', 'बटाक');
INSERT INTO "country" ("id", "name") VALUES ('bnt', 'बन्टु');
INSERT INTO "country" ("id", "name") VALUES ('bai', 'बमिलेके भाषा');
INSERT INTO "country" ("id", "name") VALUES ('ber', 'बर्बर');
INSERT INTO "country" ("id", "name") VALUES ('my', 'बर्मी');
INSERT INTO "country" ("id", "name") VALUES ('bal', 'बलुची');
INSERT INTO "country" ("id", "name") VALUES ('bg', 'बल्गेरियन');
INSERT INTO "country" ("id", "name") VALUES ('ba', 'बष्किर');
INSERT INTO "country" ("id", "name") VALUES ('bas', 'बसा');
INSERT INTO "country" ("id", "name") VALUES ('bad', 'बांदा');
INSERT INTO "country" ("id", "name") VALUES ('bm', 'बाम्बारा');
INSERT INTO "country" ("id", "name") VALUES ('gba', 'बाया');
INSERT INTO "country" ("id", "name") VALUES ('ban', 'बालिनीस');
INSERT INTO "country" ("id", "name") VALUES ('bat', 'बाल्टिक भाषा');
INSERT INTO "country" ("id", "name") VALUES ('eu', 'बास्क');
INSERT INTO "country" ("id", "name") VALUES ('bik', 'बिकोल');
INSERT INTO "country" ("id", "name") VALUES ('bin', 'बिनी');
INSERT INTO "country" ("id", "name") VALUES ('bi', 'बिस्लामा');
INSERT INTO "country" ("id", "name") VALUES ('bh', 'बिहारी');
INSERT INTO "country" ("id", "name") VALUES ('bua', 'बुरियात');
INSERT INTO "country" ("id", "name") VALUES ('bej', 'बेजा');
INSERT INTO "country" ("id", "name") VALUES ('bem', 'बेम्बा');
INSERT INTO "country" ("id", "name") VALUES ('be', 'बेलारुशियन');
INSERT INTO "country" ("id", "name") VALUES ('bs', 'बोस्नियन');
INSERT INTO "country" ("id", "name") VALUES ('bra', 'ब्रज');
INSERT INTO "country" ("id", "name") VALUES ('pt_BR', 'ब्राझिलियन पोर्तुगीज');
INSERT INTO "country" ("id", "name") VALUES ('en_GB', 'ब्रिटिश इंग्रजी');
INSERT INTO "country" ("id", "name") VALUES ('br', 'ब्रेटन');
INSERT INTO "country" ("id", "name") VALUES ('byn', 'ब्लिन');
INSERT INTO "country" ("id", "name") VALUES ('zbl', 'ब्लिसिम्बॉल्स');
INSERT INTO "country" ("id", "name") VALUES ('inc', 'भारतीय भाषा');
INSERT INTO "country" ("id", "name") VALUES ('zxx', 'भाषावैज्ञानिक सामग्री नाही');
INSERT INTO "country" ("id", "name") VALUES ('bho', 'भोजपुरी');
INSERT INTO "country" ("id", "name") VALUES ('mn', 'मंगोलियन');
INSERT INTO "country" ("id", "name") VALUES ('mdr', 'मंडार');
INSERT INTO "country" ("id", "name") VALUES ('mak', 'मकस्सर');
INSERT INTO "country" ("id", "name") VALUES ('mag', 'मगही');
INSERT INTO "country" ("id", "name") VALUES ('mni', 'मणिपुरी');
INSERT INTO "country" ("id", "name") VALUES ('cai', 'मध्य अमेरिकी इंडियन भाषा');
INSERT INTO "country" ("id", "name") VALUES ('mno', 'मनोबो भाषा');
INSERT INTO "country" ("id", "name") VALUES ('man', 'मन्डिन्गो');
INSERT INTO "country" ("id", "name") VALUES ('mr', 'मराठी');
INSERT INTO "country" ("id", "name") VALUES ('ms', 'मलय');
INSERT INTO "country" ("id", "name") VALUES ('mg', 'मलागसी');
INSERT INTO "country" ("id", "name") VALUES ('ml', 'मल्याळम');
INSERT INTO "country" ("id", "name") VALUES ('mas', 'मसाई');
INSERT INTO "country" ("id", "name") VALUES ('hmn', 'माँग');
INSERT INTO "country" ("id", "name") VALUES ('gv', 'मांक्स');
INSERT INTO "country" ("id", "name") VALUES ('mi', 'माओरी');
INSERT INTO "country" ("id", "name") VALUES ('mad', 'मादुरीस');
INSERT INTO "country" ("id", "name") VALUES ('mnc', 'मान्चु');
INSERT INTO "country" ("id", "name") VALUES ('myn', 'माया भाषा');
INSERT INTO "country" ("id", "name") VALUES ('mwr', 'मारवाडी');
INSERT INTO "country" ("id", "name") VALUES ('chm', 'मारी');
INSERT INTO "country" ("id", "name") VALUES ('mh', 'मार्शलीज');
INSERT INTO "country" ("id", "name") VALUES ('mt', 'माल्टिज्');
INSERT INTO "country" ("id", "name") VALUES ('mic', 'मिकमॅक');
INSERT INTO "country" ("id", "name") VALUES ('mga', 'मिडल आयरिश');
INSERT INTO "country" ("id", "name") VALUES ('enm', 'मिडल इंग्रजी');
INSERT INTO "country" ("id", "name") VALUES ('dum', 'मिडल डच');
INSERT INTO "country" ("id", "name") VALUES ('frm', 'मिडल फ्रेंच');
INSERT INTO "country" ("id", "name") VALUES ('gmh', 'मिडल हाय जर्मन');
INSERT INTO "country" ("id", "name") VALUES ('min', 'मिनांग्काबाउ');
INSERT INTO "country" ("id", "name") VALUES ('mwl', 'मिरांडिज्');
INSERT INTO "country" ("id", "name") VALUES ('mun', 'मुन्डा भाषा');
INSERT INTO "country" ("id", "name") VALUES ('mk', 'मॅसेडोनियन');
INSERT INTO "country" ("id", "name") VALUES ('men', 'मेन्डे');
INSERT INTO "country" ("id", "name") VALUES ('mai', 'मैथिली');
INSERT INTO "country" ("id", "name") VALUES ('mkh', 'मॉन-ख्मेर भाषा');
INSERT INTO "country" ("id", "name") VALUES ('lol', 'मोंगो');
INSERT INTO "country" ("id", "name") VALUES ('mdf', 'मोक्ष');
INSERT INTO "country" ("id", "name") VALUES ('mo', 'मोल्डाव्हियन');
INSERT INTO "country" ("id", "name") VALUES ('mos', 'मोस्सी');
INSERT INTO "country" ("id", "name") VALUES ('moh', 'मोहॉक');
INSERT INTO "country" ("id", "name") VALUES ('yao', 'याओ');
INSERT INTO "country" ("id", "name") VALUES ('sah', 'याकूत');
INSERT INTO "country" ("id", "name") VALUES ('yap', 'यापीस');
INSERT INTO "country" ("id", "name") VALUES ('yi', 'यिद्दिश');
INSERT INTO "country" ("id", "name") VALUES ('uk', 'युक्रेनियन');
INSERT INTO "country" ("id", "name") VALUES ('uga', 'युगॅरिटिक');
INSERT INTO "country" ("id", "name") VALUES ('en_US', 'यू. एस. इंग्रजी');
INSERT INTO "country" ("id", "name") VALUES ('ypk', 'यूपिक भाषा');
INSERT INTO "country" ("id", "name") VALUES ('yo', 'योरुबा');
INSERT INTO "country" ("id", "name") VALUES ('ru', 'रशियन');
INSERT INTO "country" ("id", "name") VALUES ('raj', 'राजस्थानी');
INSERT INTO "country" ("id", "name") VALUES ('rap', 'रापानुई');
INSERT INTO "country" ("id", "name") VALUES ('rar', 'रारोटोंगन');
INSERT INTO "country" ("id", "name") VALUES ('rn', 'रुन्दी');
INSERT INTO "country" ("id", "name") VALUES ('root', 'रूट');
INSERT INTO "country" ("id", "name") VALUES ('roa', 'रोमांस भाषा');
INSERT INTO "country" ("id", "name") VALUES ('ro', 'रोमानियन');
INSERT INTO "country" ("id", "name") VALUES ('rom', 'रोमानी');
INSERT INTO "country" ("id", "name") VALUES ('rm', 'र्‍हाएटो-रोमांस');
INSERT INTO "country" ("id", "name") VALUES ('lb', 'लक्झेंबर्गिश');
INSERT INTO "country" ("id", "name") VALUES ('lo', 'लाओ');
INSERT INTO "country" ("id", "name") VALUES ('lv', 'लाट्‌वियन');
INSERT INTO "country" ("id", "name") VALUES ('lad', 'लादीनो');
INSERT INTO "country" ("id", "name") VALUES ('lam', 'लाम्बा');
INSERT INTO "country" ("id", "name") VALUES ('lah', 'लाह्न्डा');
INSERT INTO "country" ("id", "name") VALUES ('ln', 'लिंगाला');
INSERT INTO "country" ("id", "name") VALUES ('tli', 'लिंगित');
INSERT INTO "country" ("id", "name") VALUES ('li', 'लिंबूर्गिश');
INSERT INTO "country" ("id", "name") VALUES ('lt', 'लिथुआनियन');
INSERT INTO "country" ("id", "name") VALUES ('lui', 'लुइसेनो');
INSERT INTO "country" ("id", "name") VALUES ('lun', 'लुन्डा');
INSERT INTO "country" ("id", "name") VALUES ('lus', 'लुशाई');
INSERT INTO "country" ("id", "name") VALUES ('lua', 'लूबा-लुलुआ');
INSERT INTO "country" ("id", "name") VALUES ('la', 'लॅटिन');
INSERT INTO "country" ("id", "name") VALUES ('es_419', 'लॅटिन अमेरिकन स्पॅनिश');
INSERT INTO "country" ("id", "name") VALUES ('lez', 'लेझ्घीयन');
INSERT INTO "country" ("id", "name") VALUES ('nds', 'लो जर्मन');
INSERT INTO "country" ("id", "name") VALUES ('jbo', 'लोज्बान');
INSERT INTO "country" ("id", "name") VALUES ('loz', 'लोझी');
INSERT INTO "country" ("id", "name") VALUES ('luo', 'ल्युओ');
INSERT INTO "country" ("id", "name") VALUES ('smj', 'ल्युल सामी');
INSERT INTO "country" ("id", "name") VALUES ('lu', 'ल्यूबा-कटांगा');
INSERT INTO "country" ("id", "name") VALUES ('wal', 'वलामो');
INSERT INTO "country" ("id", "name") VALUES ('vai', 'वाई');
INSERT INTO "country" ("id", "name") VALUES ('wak', 'वाकाशन भाषा');
INSERT INTO "country" ("id", "name") VALUES ('war', 'वारे');
INSERT INTO "country" ("id", "name") VALUES ('wa', 'वालून');
INSERT INTO "country" ("id", "name") VALUES ('was', 'वाशो');
INSERT INTO "country" ("id", "name") VALUES ('mis', 'विविध भाषा');
INSERT INTO "country" ("id", "name") VALUES ('cy', 'वेल्श');
INSERT INTO "country" ("id", "name") VALUES ('vot', 'वॉटिक');
INSERT INTO "country" ("id", "name") VALUES ('wo', 'वोलोफ');
INSERT INTO "country" ("id", "name") VALUES ('vi', 'व्हिएतनामी');
INSERT INTO "country" ("id", "name") VALUES ('ve', 'व्हेंदा');
INSERT INTO "country" ("id", "name") VALUES ('chp', 'शिपेव्यान');
INSERT INTO "country" ("id", "name") VALUES ('shn', 'शॅन');
INSERT INTO "country" ("id", "name") VALUES ('chy', 'शेयेन्न');
INSERT INTO "country" ("id", "name") VALUES ('sn', 'शोना');
INSERT INTO "country" ("id", "name") VALUES ('sad', 'सँडवे');
INSERT INTO "country" ("id", "name") VALUES ('sat', 'संताली');
INSERT INTO "country" ("id", "name") VALUES ('sa', 'संस्कृत');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hans', 'सरलीकृत चीनी');
INSERT INTO "country" ("id", "name") VALUES ('sc', 'सर्दिनियन');
INSERT INTO "country" ("id", "name") VALUES ('sr', 'सर्बियन');
INSERT INTO "country" ("id", "name") VALUES ('sh', 'सर्बो-क्रोएशियन');
INSERT INTO "country" ("id", "name") VALUES ('sal', 'सलीशन भाषा');
INSERT INTO "country" ("id", "name") VALUES ('sgn', 'सांकेतिक भाषा');
INSERT INTO "country" ("id", "name") VALUES ('sg', 'सांगो');
INSERT INTO "country" ("id", "name") VALUES ('sam', 'सामरिटान अरॅमिक');
INSERT INTO "country" ("id", "name") VALUES ('smi', 'सामी भाषा');
INSERT INTO "country" ("id", "name") VALUES ('sm', 'सामोअन');
INSERT INTO "country" ("id", "name") VALUES ('sas', 'सासाक');
INSERT INTO "country" ("id", "name") VALUES ('sd', 'सिंधी');
INSERT INTO "country" ("id", "name") VALUES ('si', 'सिंहली');
INSERT INTO "country" ("id", "name") VALUES ('sio', 'सिउआन भाषा');
INSERT INTO "country" ("id", "name") VALUES ('bla', 'सिक्सिका');
INSERT INTO "country" ("id", "name") VALUES ('ii', 'सिचुआन यी');
INSERT INTO "country" ("id", "name") VALUES ('sid', 'सिदामो');
INSERT INTO "country" ("id", "name") VALUES ('ceb', 'सिबुआनो');
INSERT INTO "country" ("id", "name") VALUES ('tsi', 'सिम्शियन');
INSERT INTO "country" ("id", "name") VALUES ('syr', 'सिरियाक');
INSERT INTO "country" ("id", "name") VALUES ('scn', 'सिसिलियन');
INSERT INTO "country" ("id", "name") VALUES ('su', 'सुंदानीज');
INSERT INTO "country" ("id", "name") VALUES ('suk', 'सुकुमा');
INSERT INTO "country" ("id", "name") VALUES ('sux', 'सुमेरियन');
INSERT INTO "country" ("id", "name") VALUES ('sus', 'सुसु');
INSERT INTO "country" ("id", "name") VALUES ('sem', 'सेमिटिक भाषा');
INSERT INTO "country" ("id", "name") VALUES ('srr', 'सेरेर');
INSERT INTO "country" ("id", "name") VALUES ('sel', 'सेल्कप');
INSERT INTO "country" ("id", "name") VALUES ('st', 'सेसोथो');
INSERT INTO "country" ("id", "name") VALUES ('wen', 'सॉर्बियन भाषा');
INSERT INTO "country" ("id", "name") VALUES ('ts', 'सोंगा');
INSERT INTO "country" ("id", "name") VALUES ('sog', 'सोग्डिएन');
INSERT INTO "country" ("id", "name") VALUES ('snk', 'सोनिन्के');
INSERT INTO "country" ("id", "name") VALUES ('son', 'सोन्घाई');
INSERT INTO "country" ("id", "name") VALUES ('so', 'सोमाली');
INSERT INTO "country" ("id", "name") VALUES ('sco', 'स्कॉट्स');
INSERT INTO "country" ("id", "name") VALUES ('gd', 'स्कॉट्स गेलिक');
INSERT INTO "country" ("id", "name") VALUES ('sms', 'स्कोल्ट सामी');
INSERT INTO "country" ("id", "name") VALUES ('es', 'स्पॅनिश');
INSERT INTO "country" ("id", "name") VALUES ('srn', 'स्रानान टॉन्गो');
INSERT INTO "country" ("id", "name") VALUES ('den', 'स्लाव्ह');
INSERT INTO "country" ("id", "name") VALUES ('sla', 'स्लाव्हिक भाषा');
INSERT INTO "country" ("id", "name") VALUES ('sk', 'स्लोव्हाक');
INSERT INTO "country" ("id", "name") VALUES ('sl', 'स्लोव्हेनियन');
INSERT INTO "country" ("id", "name") VALUES ('ss', 'स्वाती');
INSERT INTO "country" ("id", "name") VALUES ('sw', 'स्वाहिली');
INSERT INTO "country" ("id", "name") VALUES ('gsw', 'स्विस जर्मन');
INSERT INTO "country" ("id", "name") VALUES ('fr_CH', 'स्विस फ्रेंच');
INSERT INTO "country" ("id", "name") VALUES ('de_CH', 'स्विस हाय जर्मन');
INSERT INTO "country" ("id", "name") VALUES ('sv', 'स्वीडिश');
INSERT INTO "country" ("id", "name") VALUES ('hu', 'हंगेरियन');
INSERT INTO "country" ("id", "name") VALUES ('hz', 'हरेरो');
INSERT INTO "country" ("id", "name") VALUES ('haw', 'हवाईयन');
INSERT INTO "country" ("id", "name") VALUES ('hi', 'हिंदी');
INSERT INTO "country" ("id", "name") VALUES ('hit', 'हिट्टिते');
INSERT INTO "country" ("id", "name") VALUES ('he', 'हिब्रू');
INSERT INTO "country" ("id", "name") VALUES ('him', 'हिमाचली');
INSERT INTO "country" ("id", "name") VALUES ('ho', 'हिरी मॉटू');
INSERT INTO "country" ("id", "name") VALUES ('hil', 'हिलीगेनॉन');
INSERT INTO "country" ("id", "name") VALUES ('hup', 'हूपा');
INSERT INTO "country" ("id", "name") VALUES ('hai', 'हैडा');
INSERT INTO "country" ("id", "name") VALUES ('ht', 'हैतीयन');
INSERT INTO "country" ("id", "name") VALUES ('ha', 'हौसा');
