CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('ab', 'abház');
INSERT INTO [country] ([id], [name]) VALUES ('ace', 'achinéz');
INSERT INTO [country] ([id], [name]) VALUES ('ada', 'adangme');
INSERT INTO [country] ([id], [name]) VALUES ('ady', 'adyghe');
INSERT INTO [country] ([id], [name]) VALUES ('aa', 'afar');
INSERT INTO [country] ([id], [name]) VALUES ('afh', 'afrihili');
INSERT INTO [country] ([id], [name]) VALUES ('af', 'afrikaans');
INSERT INTO [country] ([id], [name]) VALUES ('afa', 'afroázsiai nyelv');
INSERT INTO [country] ([id], [name]) VALUES ('ain', 'ainu');
INSERT INTO [country] ([id], [name]) VALUES ('ay', 'ajmara');
INSERT INTO [country] ([id], [name]) VALUES ('ak', 'akan');
INSERT INTO [country] ([id], [name]) VALUES ('akk', 'akkád');
INSERT INTO [country] ([id], [name]) VALUES ('ach', 'akoli');
INSERT INTO [country] ([id], [name]) VALUES ('sq', 'albán');
INSERT INTO [country] ([id], [name]) VALUES ('ale', 'aleut');
INSERT INTO [country] ([id], [name]) VALUES ('alg', 'algonkin nyelv');
INSERT INTO [country] ([id], [name]) VALUES ('dsb', 'alsó szorb');
INSERT INTO [country] ([id], [name]) VALUES ('nds', 'alsónémet');
INSERT INTO [country] ([id], [name]) VALUES ('tut', 'altáji nyelv');
INSERT INTO [country] ([id], [name]) VALUES ('en_US', 'amerikai angol');
INSERT INTO [country] ([id], [name]) VALUES ('am', 'amhara');
INSERT INTO [country] ([id], [name]) VALUES ('anp', 'angika');
INSERT INTO [country] ([id], [name]) VALUES ('en', 'angol');
INSERT INTO [country] ([id], [name]) VALUES ('apa', 'apacs nyelvek');
INSERT INTO [country] ([id], [name]) VALUES ('ar', 'arab');
INSERT INTO [country] ([id], [name]) VALUES ('an', 'aragonéz');
INSERT INTO [country] ([id], [name]) VALUES ('arc', 'arámi');
INSERT INTO [country] ([id], [name]) VALUES ('arp', 'arapaho');
INSERT INTO [country] ([id], [name]) VALUES ('arn', 'araucani');
INSERT INTO [country] ([id], [name]) VALUES ('arw', 'aravak');
INSERT INTO [country] ([id], [name]) VALUES ('rup', 'aromán');
INSERT INTO [country] ([id], [name]) VALUES ('asa', 'asu');
INSERT INTO [country] ([id], [name]) VALUES ('as', 'asszámi');
INSERT INTO [country] ([id], [name]) VALUES ('ast', 'asztúr');
INSERT INTO [country] ([id], [name]) VALUES ('ath', 'atapaszkan nyelvek');
INSERT INTO [country] ([id], [name]) VALUES ('cch', 'atszam');
INSERT INTO [country] ([id], [name]) VALUES ('en_AU', 'ausztrál angol');
INSERT INTO [country] ([id], [name]) VALUES ('aus', 'ausztrál nyelvek');
INSERT INTO [country] ([id], [name]) VALUES ('map', 'ausztronéz');
INSERT INTO [country] ([id], [name]) VALUES ('av', 'avar');
INSERT INTO [country] ([id], [name]) VALUES ('ae', 'avesztán');
INSERT INTO [country] ([id], [name]) VALUES ('awa', 'awádi');
INSERT INTO [country] ([id], [name]) VALUES ('az', 'azerbajdzsáni');
INSERT INTO [country] ([id], [name]) VALUES ('ban', 'balinéz');
INSERT INTO [country] ([id], [name]) VALUES ('bat', 'balti nyelv');
INSERT INTO [country] ([id], [name]) VALUES ('bal', 'balucsi');
INSERT INTO [country] ([id], [name]) VALUES ('bm', 'bambara');
INSERT INTO [country] ([id], [name]) VALUES ('bai', 'bamileke nyelvek');
INSERT INTO [country] ([id], [name]) VALUES ('bad', 'banda');
INSERT INTO [country] ([id], [name]) VALUES ('bnt', 'bantu');
INSERT INTO [country] ([id], [name]) VALUES ('ba', 'baskír');
INSERT INTO [country] ([id], [name]) VALUES ('bas', 'basza');
INSERT INTO [country] ([id], [name]) VALUES ('eu', 'baszk');
INSERT INTO [country] ([id], [name]) VALUES ('btk', 'batak');
INSERT INTO [country] ([id], [name]) VALUES ('bej', 'bedzsa');
INSERT INTO [country] ([id], [name]) VALUES ('be', 'belorusz');
INSERT INTO [country] ([id], [name]) VALUES ('bem', 'bemba');
INSERT INTO [country] ([id], [name]) VALUES ('bez', 'bena');
INSERT INTO [country] ([id], [name]) VALUES ('bn', 'bengáli');
INSERT INTO [country] ([id], [name]) VALUES ('ber', 'berber');
INSERT INTO [country] ([id], [name]) VALUES ('bh', 'bihari');
INSERT INTO [country] ([id], [name]) VALUES ('bik', 'bikol');
INSERT INTO [country] ([id], [name]) VALUES ('bin', 'bini');
INSERT INTO [country] ([id], [name]) VALUES ('bi', 'bislama');
INSERT INTO [country] ([id], [name]) VALUES ('byn', 'blin');
INSERT INTO [country] ([id], [name]) VALUES ('zbl', 'Bliss jelképrendszer');
INSERT INTO [country] ([id], [name]) VALUES ('brx', 'bodo');
INSERT INTO [country] ([id], [name]) VALUES ('bho', 'bodzspuri');
INSERT INTO [country] ([id], [name]) VALUES ('bg', 'bolgár');
INSERT INTO [country] ([id], [name]) VALUES ('bs', 'bosnyák');
INSERT INTO [country] ([id], [name]) VALUES ('bra', 'braj');
INSERT INTO [country] ([id], [name]) VALUES ('pt_BR', 'brazíliai portugál');
INSERT INTO [country] ([id], [name]) VALUES ('br', 'breton');
INSERT INTO [country] ([id], [name]) VALUES ('en_GB', 'brit angol');
INSERT INTO [country] ([id], [name]) VALUES ('bug', 'buginéz');
INSERT INTO [country] ([id], [name]) VALUES ('bua', 'burját');
INSERT INTO [country] ([id], [name]) VALUES ('my', 'burmai');
INSERT INTO [country] ([id], [name]) VALUES ('dz', 'butáni');
INSERT INTO [country] ([id], [name]) VALUES ('cad', 'caddo');
INSERT INTO [country] ([id], [name]) VALUES ('ceb', 'cebui');
INSERT INTO [country] ([id], [name]) VALUES ('swb', 'comorei');
INSERT INTO [country] ([id], [name]) VALUES ('ts', 'conga');
INSERT INTO [country] ([id], [name]) VALUES ('chg', 'csagatáj');
INSERT INTO [country] ([id], [name]) VALUES ('cmc', 'csam nyelv');
INSERT INTO [country] ([id], [name]) VALUES ('ch', 'csamoró');
INSERT INTO [country] ([id], [name]) VALUES ('ce', 'csecsen');
INSERT INTO [country] ([id], [name]) VALUES ('cs', 'cseh');
INSERT INTO [country] ([id], [name]) VALUES ('chy', 'csejen');
INSERT INTO [country] ([id], [name]) VALUES ('chr', 'cseroki');
INSERT INTO [country] ([id], [name]) VALUES ('chb', 'csibcsa');
INSERT INTO [country] ([id], [name]) VALUES ('tsi', 'csimsiáni');
INSERT INTO [country] ([id], [name]) VALUES ('chn', 'csinuk zsargon');
INSERT INTO [country] ([id], [name]) VALUES ('chp', 'csipevé');
INSERT INTO [country] ([id], [name]) VALUES ('cho', 'csoktó');
INSERT INTO [country] ([id], [name]) VALUES ('chk', 'csukéz');
INSERT INTO [country] ([id], [name]) VALUES ('cv', 'csuvas');
INSERT INTO [country] ([id], [name]) VALUES ('day', 'dajak');
INSERT INTO [country] ([id], [name]) VALUES ('dak', 'dakota');
INSERT INTO [country] ([id], [name]) VALUES ('da', 'dán');
INSERT INTO [country] ([id], [name]) VALUES ('dar', 'dargva');
INSERT INTO [country] ([id], [name]) VALUES ('alt', 'dél-altaji');
INSERT INTO [country] ([id], [name]) VALUES ('sai', 'dél-amerikai indián nyelv');
INSERT INTO [country] ([id], [name]) VALUES ('del', 'delavár');
INSERT INTO [country] ([id], [name]) VALUES ('nr', 'déli ndebele');
INSERT INTO [country] ([id], [name]) VALUES ('sma', 'déli számi');
INSERT INTO [country] ([id], [name]) VALUES ('din', 'dinka');
INSERT INTO [country] ([id], [name]) VALUES ('dyu', 'diula');
INSERT INTO [country] ([id], [name]) VALUES ('dv', 'divehi');
INSERT INTO [country] ([id], [name]) VALUES ('doi', 'dogri');
INSERT INTO [country] ([id], [name]) VALUES ('dgr', 'dogrib');
INSERT INTO [country] ([id], [name]) VALUES ('dua', 'duala');
INSERT INTO [country] ([id], [name]) VALUES ('efi', 'efik');
INSERT INTO [country] ([id], [name]) VALUES ('cpe', 'egyéb angol alapú kreol és pidgin');
INSERT INTO [country] ([id], [name]) VALUES ('dra', 'egyéb dravida');
INSERT INTO [country] ([id], [name]) VALUES ('cpf', 'egyéb francia alapú kreol és pidgin');
INSERT INTO [country] ([id], [name]) VALUES ('inc', 'egyéb indiai');
INSERT INTO [country] ([id], [name]) VALUES ('cau', 'egyéb kaukázusi');
INSERT INTO [country] ([id], [name]) VALUES ('cel', 'egyéb kelta');
INSERT INTO [country] ([id], [name]) VALUES ('khi', 'egyéb koiszan');
INSERT INTO [country] ([id], [name]) VALUES ('cai', 'egyéb közép-amerikai indián');
INSERT INTO [country] ([id], [name]) VALUES ('mkh', 'egyéb mon-khmer');
INSERT INTO [country] ([id], [name]) VALUES ('mis', 'egyéb nyelvek');
INSERT INTO [country] ([id], [name]) VALUES ('sem', 'egyéb szemita');
INSERT INTO [country] ([id], [name]) VALUES ('cu', 'egyházi szláv');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hans', 'egyszerűsített kínai');
INSERT INTO [country] ([id], [name]) VALUES ('eka', 'ekadzsuk');
INSERT INTO [country] ([id], [name]) VALUES ('elx', 'elamit');
INSERT INTO [country] ([id], [name]) VALUES ('ebu', 'embu');
INSERT INTO [country] ([id], [name]) VALUES ('myv', 'erzjány');
INSERT INTO [country] ([id], [name]) VALUES ('nai', 'észak-amerikai indián nyelv');
INSERT INTO [country] ([id], [name]) VALUES ('frr', 'északi fríz');
INSERT INTO [country] ([id], [name]) VALUES ('nd', 'északi ndebele');
INSERT INTO [country] ([id], [name]) VALUES ('se', 'északi számi');
INSERT INTO [country] ([id], [name]) VALUES ('nso', 'északi szotó');
INSERT INTO [country] ([id], [name]) VALUES ('eo', 'eszperantó');
INSERT INTO [country] ([id], [name]) VALUES ('et', 'észt');
INSERT INTO [country] ([id], [name]) VALUES ('ee', 'eve');
INSERT INTO [country] ([id], [name]) VALUES ('ewo', 'evondo');
INSERT INTO [country] ([id], [name]) VALUES ('fan', 'fang');
INSERT INTO [country] ([id], [name]) VALUES ('fat', 'fanti');
INSERT INTO [country] ([id], [name]) VALUES ('hsb', 'felső szorb');
INSERT INTO [country] ([id], [name]) VALUES ('fo', 'feröeri');
INSERT INTO [country] ([id], [name]) VALUES ('fj', 'fidzsi');
INSERT INTO [country] ([id], [name]) VALUES ('fil', 'filippínó');
INSERT INTO [country] ([id], [name]) VALUES ('fi', 'finn');
INSERT INTO [country] ([id], [name]) VALUES ('fiu', 'finnugor nyelv');
INSERT INTO [country] ([id], [name]) VALUES ('nl_BE', 'flamand');
INSERT INTO [country] ([id], [name]) VALUES ('fon', 'fon');
INSERT INTO [country] ([id], [name]) VALUES ('phn', 'főniciai');
INSERT INTO [country] ([id], [name]) VALUES ('fr', 'francia');
INSERT INTO [country] ([id], [name]) VALUES ('fur', 'friuli');
INSERT INTO [country] ([id], [name]) VALUES ('fy', 'fríz');
INSERT INTO [country] ([id], [name]) VALUES ('ff', 'fulani');
INSERT INTO [country] ([id], [name]) VALUES ('phi', 'Fülöp-szigeteki nyelv');
INSERT INTO [country] ([id], [name]) VALUES ('gaa', 'ga');
INSERT INTO [country] ([id], [name]) VALUES ('gay', 'gajo');
INSERT INTO [country] ([id], [name]) VALUES ('gl', 'galíciai');
INSERT INTO [country] ([id], [name]) VALUES ('lg', 'ganda');
INSERT INTO [country] ([id], [name]) VALUES ('gba', 'gbaja');
INSERT INTO [country] ([id], [name]) VALUES ('gez', 'geez');
INSERT INTO [country] ([id], [name]) VALUES ('gem', 'germán nyelv');
INSERT INTO [country] ([id], [name]) VALUES ('gon', 'gondi');
INSERT INTO [country] ([id], [name]) VALUES ('gor', 'gorontalo');
INSERT INTO [country] ([id], [name]) VALUES ('got', 'gót');
INSERT INTO [country] ([id], [name]) VALUES ('el', 'görög');
INSERT INTO [country] ([id], [name]) VALUES ('grb', 'grebó');
INSERT INTO [country] ([id], [name]) VALUES ('kl', 'grönlandi');
INSERT INTO [country] ([id], [name]) VALUES ('ka', 'grúz');
INSERT INTO [country] ([id], [name]) VALUES ('gn', 'guarani');
INSERT INTO [country] ([id], [name]) VALUES ('gu', 'gudzsarati');
INSERT INTO [country] ([id], [name]) VALUES ('gwi', 'gvicsin');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hant', 'hagyományos kínai');
INSERT INTO [country] ([id], [name]) VALUES ('hai', 'haida');
INSERT INTO [country] ([id], [name]) VALUES ('ht', 'haiti');
INSERT INTO [country] ([id], [name]) VALUES ('ha', 'hausza');
INSERT INTO [country] ([id], [name]) VALUES ('haw', 'hawaii');
INSERT INTO [country] ([id], [name]) VALUES ('he', 'héber');
INSERT INTO [country] ([id], [name]) VALUES ('hz', 'herero');
INSERT INTO [country] ([id], [name]) VALUES ('hil', 'hiligajnon');
INSERT INTO [country] ([id], [name]) VALUES ('him', 'himaháli');
INSERT INTO [country] ([id], [name]) VALUES ('hi', 'hindi');
INSERT INTO [country] ([id], [name]) VALUES ('ho', 'hiri motu');
INSERT INTO [country] ([id], [name]) VALUES ('hit', 'hittite');
INSERT INTO [country] ([id], [name]) VALUES ('hmn', 'hmong');
INSERT INTO [country] ([id], [name]) VALUES ('nl', 'holland');
INSERT INTO [country] ([id], [name]) VALUES ('hr', 'horvát');
INSERT INTO [country] ([id], [name]) VALUES ('xh', 'hosza');
INSERT INTO [country] ([id], [name]) VALUES ('hup', 'hupa');
INSERT INTO [country] ([id], [name]) VALUES ('iba', 'iban');
INSERT INTO [country] ([id], [name]) VALUES ('pt_PT', 'ibériai portugál');
INSERT INTO [country] ([id], [name]) VALUES ('es_ES', 'ibériai spanyol');
INSERT INTO [country] ([id], [name]) VALUES ('io', 'idó');
INSERT INTO [country] ([id], [name]) VALUES ('ijo', 'idzsó');
INSERT INTO [country] ([id], [name]) VALUES ('ig', 'igbó');
INSERT INTO [country] ([id], [name]) VALUES ('gil', 'ikiribati');
INSERT INTO [country] ([id], [name]) VALUES ('ilo', 'ilokó');
INSERT INTO [country] ([id], [name]) VALUES ('smn', 'inar sami');
INSERT INTO [country] ([id], [name]) VALUES ('ine', 'indoeurópai nyelv');
INSERT INTO [country] ([id], [name]) VALUES ('id', 'indonéz');
INSERT INTO [country] ([id], [name]) VALUES ('inh', 'ingus');
INSERT INTO [country] ([id], [name]) VALUES ('ie', 'interlingue');
INSERT INTO [country] ([id], [name]) VALUES ('ia', 'interlingva');
INSERT INTO [country] ([id], [name]) VALUES ('iu', 'inuktitut');
INSERT INTO [country] ([id], [name]) VALUES ('ik', 'inupiak');
INSERT INTO [country] ([id], [name]) VALUES ('ga', 'ír');
INSERT INTO [country] ([id], [name]) VALUES ('ira', 'iráni');
INSERT INTO [country] ([id], [name]) VALUES ('iro', 'irokéz nyelvek');
INSERT INTO [country] ([id], [name]) VALUES ('und', 'ismeretlen vagy érvénytelen nyelv');
INSERT INTO [country] ([id], [name]) VALUES ('is', 'izlandi');
INSERT INTO [country] ([id], [name]) VALUES ('sah', 'jakut');
INSERT INTO [country] ([id], [name]) VALUES ('yao', 'jaó');
INSERT INTO [country] ([id], [name]) VALUES ('ja', 'japán');
INSERT INTO [country] ([id], [name]) VALUES ('yap', 'japi');
INSERT INTO [country] ([id], [name]) VALUES ('jv', 'jávai');
INSERT INTO [country] ([id], [name]) VALUES ('sgn', 'jelnyelv');
INSERT INTO [country] ([id], [name]) VALUES ('yi', 'jiddis');
INSERT INTO [country] ([id], [name]) VALUES ('kaj', 'jju');
INSERT INTO [country] ([id], [name]) VALUES ('yo', 'joruba');
INSERT INTO [country] ([id], [name]) VALUES ('ypk', 'jupik nyelv');
INSERT INTO [country] ([id], [name]) VALUES ('kbd', 'kabardi');
INSERT INTO [country] ([id], [name]) VALUES ('kab', 'kabije');
INSERT INTO [country] ([id], [name]) VALUES ('kea', 'kabuverdianu');
INSERT INTO [country] ([id], [name]) VALUES ('kac', 'kacsin');
INSERT INTO [country] ([id], [name]) VALUES ('xal', 'kalmük');
INSERT INTO [country] ([id], [name]) VALUES ('kam', 'kamba');
INSERT INTO [country] ([id], [name]) VALUES ('km', 'kambodzsai');
INSERT INTO [country] ([id], [name]) VALUES ('en_CA', 'kanadai angol');
INSERT INTO [country] ([id], [name]) VALUES ('fr_CA', 'kanadai francia');
INSERT INTO [country] ([id], [name]) VALUES ('kn', 'kannada');
INSERT INTO [country] ([id], [name]) VALUES ('yue', 'kantoni');
INSERT INTO [country] ([id], [name]) VALUES ('kr', 'kanuri');
INSERT INTO [country] ([id], [name]) VALUES ('kaa', 'kara-kalpak');
INSERT INTO [country] ([id], [name]) VALUES ('krc', 'karacsáj-balkár');
INSERT INTO [country] ([id], [name]) VALUES ('krl', 'karelai');
INSERT INTO [country] ([id], [name]) VALUES ('kar', 'karen');
INSERT INTO [country] ([id], [name]) VALUES ('car', 'karib');
INSERT INTO [country] ([id], [name]) VALUES ('ks', 'kásmíri');
INSERT INTO [country] ([id], [name]) VALUES ('csb', 'kasub');
INSERT INTO [country] ([id], [name]) VALUES ('kha', 'kaszi');
INSERT INTO [country] ([id], [name]) VALUES ('ca', 'katalán');
INSERT INTO [country] ([id], [name]) VALUES ('kaw', 'kawi');
INSERT INTO [country] ([id], [name]) VALUES ('kk', 'kazah');
INSERT INTO [country] ([id], [name]) VALUES ('qu', 'kecsua');
INSERT INTO [country] ([id], [name]) VALUES ('frs', 'keleti fríz');
INSERT INTO [country] ([id], [name]) VALUES ('ki', 'kikuju');
INSERT INTO [country] ([id], [name]) VALUES ('kmb', 'kimbundu');
INSERT INTO [country] ([id], [name]) VALUES ('zh', 'kínai');
INSERT INTO [country] ([id], [name]) VALUES ('ky', 'kirgiz');
INSERT INTO [country] ([id], [name]) VALUES ('rw', 'kiruanda');
INSERT INTO [country] ([id], [name]) VALUES ('rn', 'kirundi');
INSERT INTO [country] ([id], [name]) VALUES ('nwc', 'klasszikus newari');
INSERT INTO [country] ([id], [name]) VALUES ('syc', 'klasszikus szír');
INSERT INTO [country] ([id], [name]) VALUES ('tlh', 'klingon');
INSERT INTO [country] ([id], [name]) VALUES ('sms', 'koltta lapp');
INSERT INTO [country] ([id], [name]) VALUES ('kv', 'komi');
INSERT INTO [country] ([id], [name]) VALUES ('kg', 'kongo');
INSERT INTO [country] ([id], [name]) VALUES ('kok', 'konkani');
INSERT INTO [country] ([id], [name]) VALUES ('cop', 'kopt');
INSERT INTO [country] ([id], [name]) VALUES ('ko', 'koreai');
INSERT INTO [country] ([id], [name]) VALUES ('kw', 'korni');
INSERT INTO [country] ([id], [name]) VALUES ('kfo', 'koro');
INSERT INTO [country] ([id], [name]) VALUES ('co', 'korzikai');
INSERT INTO [country] ([id], [name]) VALUES ('kos', 'kosrei');
INSERT INTO [country] ([id], [name]) VALUES ('kho', 'kotanéz');
INSERT INTO [country] ([id], [name]) VALUES ('enm', 'közép angol');
INSERT INTO [country] ([id], [name]) VALUES ('gmh', 'közép felső német');
INSERT INTO [country] ([id], [name]) VALUES ('frm', 'közép francia');
INSERT INTO [country] ([id], [name]) VALUES ('dum', 'közép holland');
INSERT INTO [country] ([id], [name]) VALUES ('mga', 'közép ír');
INSERT INTO [country] ([id], [name]) VALUES ('kpe', 'kpelle');
INSERT INTO [country] ([id], [name]) VALUES ('crp', 'kreol és pidzsin');
INSERT INTO [country] ([id], [name]) VALUES ('cr', 'krí');
INSERT INTO [country] ([id], [name]) VALUES ('mus', 'krík');
INSERT INTO [country] ([id], [name]) VALUES ('crh', 'krími tatár');
INSERT INTO [country] ([id], [name]) VALUES ('kro', 'kru');
INSERT INTO [country] ([id], [name]) VALUES ('kj', 'kuanyama');
INSERT INTO [country] ([id], [name]) VALUES ('kum', 'kumük');
INSERT INTO [country] ([id], [name]) VALUES ('ku', 'kurd');
INSERT INTO [country] ([id], [name]) VALUES ('kru', 'kuruh');
INSERT INTO [country] ([id], [name]) VALUES ('cus', 'kusita nyelv');
INSERT INTO [country] ([id], [name]) VALUES ('kut', 'kutenai');
INSERT INTO [country] ([id], [name]) VALUES ('lad', 'ladino');
INSERT INTO [country] ([id], [name]) VALUES ('lah', 'lahnda');
INSERT INTO [country] ([id], [name]) VALUES ('lam', 'lamba');
INSERT INTO [country] ([id], [name]) VALUES ('lo', 'laoszi');
INSERT INTO [country] ([id], [name]) VALUES ('smi', 'lapp nyelv');
INSERT INTO [country] ([id], [name]) VALUES ('la', 'latin');
INSERT INTO [country] ([id], [name]) VALUES ('es_419', 'latin-amerikai spanyol');
INSERT INTO [country] ([id], [name]) VALUES ('pl', 'lengyel');
INSERT INTO [country] ([id], [name]) VALUES ('lv', 'lett');
INSERT INTO [country] ([id], [name]) VALUES ('lez', 'lezg');
INSERT INTO [country] ([id], [name]) VALUES ('li', 'limburgi');
INSERT INTO [country] ([id], [name]) VALUES ('ln', 'lingala');
INSERT INTO [country] ([id], [name]) VALUES ('lt', 'litván');
INSERT INTO [country] ([id], [name]) VALUES ('jbo', 'lojban');
INSERT INTO [country] ([id], [name]) VALUES ('loz', 'lozi');
INSERT INTO [country] ([id], [name]) VALUES ('lu', 'luba-katanga');
INSERT INTO [country] ([id], [name]) VALUES ('lua', 'luba-lulua');
INSERT INTO [country] ([id], [name]) VALUES ('lui', 'luiseno');
INSERT INTO [country] ([id], [name]) VALUES ('luy', 'lujia');
INSERT INTO [country] ([id], [name]) VALUES ('smj', 'lule számi');
INSERT INTO [country] ([id], [name]) VALUES ('lun', 'lunda');
INSERT INTO [country] ([id], [name]) VALUES ('luo', 'luo');
INSERT INTO [country] ([id], [name]) VALUES ('lus', 'lushai');
INSERT INTO [country] ([id], [name]) VALUES ('lb', 'luxemburgi');
INSERT INTO [country] ([id], [name]) VALUES ('mk', 'macedón');
INSERT INTO [country] ([id], [name]) VALUES ('mad', 'madurai');
INSERT INTO [country] ([id], [name]) VALUES ('mag', 'magahi');
INSERT INTO [country] ([id], [name]) VALUES ('hu', 'magyar');
INSERT INTO [country] ([id], [name]) VALUES ('mai', 'maithili');
INSERT INTO [country] ([id], [name]) VALUES ('myn', 'maja nyelvek');
INSERT INTO [country] ([id], [name]) VALUES ('mak', 'makaszar');
INSERT INTO [country] ([id], [name]) VALUES ('ms', 'maláj');
INSERT INTO [country] ([id], [name]) VALUES ('ml', 'malajálam');
INSERT INTO [country] ([id], [name]) VALUES ('mg', 'málgas');
INSERT INTO [country] ([id], [name]) VALUES ('mt', 'máltai');
INSERT INTO [country] ([id], [name]) VALUES ('gv', 'Man-szigeti');
INSERT INTO [country] ([id], [name]) VALUES ('mdr', 'mandar');
INSERT INTO [country] ([id], [name]) VALUES ('man', 'mandingó');
INSERT INTO [country] ([id], [name]) VALUES ('mnc', 'mandzsu');
INSERT INTO [country] ([id], [name]) VALUES ('mni', 'manipuri');
INSERT INTO [country] ([id], [name]) VALUES ('mno', 'manobó nyelvek');
INSERT INTO [country] ([id], [name]) VALUES ('mi', 'maori');
INSERT INTO [country] ([id], [name]) VALUES ('mr', 'marathi');
INSERT INTO [country] ([id], [name]) VALUES ('chm', 'mari');
INSERT INTO [country] ([id], [name]) VALUES ('mh', 'marshalli');
INSERT INTO [country] ([id], [name]) VALUES ('mwr', 'marvari');
INSERT INTO [country] ([id], [name]) VALUES ('mas', 'masai');
INSERT INTO [country] ([id], [name]) VALUES ('men', 'mende');
INSERT INTO [country] ([id], [name]) VALUES ('art', 'mesterséges nyelv');
INSERT INTO [country] ([id], [name]) VALUES ('mic', 'mikmak');
INSERT INTO [country] ([id], [name]) VALUES ('min', 'minangkabau');
INSERT INTO [country] ([id], [name]) VALUES ('mwl', 'mirandéz');
INSERT INTO [country] ([id], [name]) VALUES ('moh', 'mohawk');
INSERT INTO [country] ([id], [name]) VALUES ('mdf', 'moksán');
INSERT INTO [country] ([id], [name]) VALUES ('mo', 'moldvai');
INSERT INTO [country] ([id], [name]) VALUES ('lol', 'mongó');
INSERT INTO [country] ([id], [name]) VALUES ('mn', 'mongol');
INSERT INTO [country] ([id], [name]) VALUES ('mos', 'moszi');
INSERT INTO [country] ([id], [name]) VALUES ('mun', 'munda nyelvek');
INSERT INTO [country] ([id], [name]) VALUES ('nqo', 'n''kó');
INSERT INTO [country] ([id], [name]) VALUES ('nah', 'nahuati');
INSERT INTO [country] ([id], [name]) VALUES ('nap', 'nápolyi');
INSERT INTO [country] ([id], [name]) VALUES ('na', 'naurui');
INSERT INTO [country] ([id], [name]) VALUES ('nv', 'navahó');
INSERT INTO [country] ([id], [name]) VALUES ('ng', 'ndonga');
INSERT INTO [country] ([id], [name]) VALUES ('de', 'német');
INSERT INTO [country] ([id], [name]) VALUES ('ne', 'nepáli');
INSERT INTO [country] ([id], [name]) VALUES ('new', 'nevari');
INSERT INTO [country] ([id], [name]) VALUES ('nia', 'nias');
INSERT INTO [country] ([id], [name]) VALUES ('nic', 'niger-kordofan nyelv');
INSERT INTO [country] ([id], [name]) VALUES ('ssa', 'nílusi-szaharai nyelv');
INSERT INTO [country] ([id], [name]) VALUES ('zxx', 'nincs nyelvészeti tartalom');
INSERT INTO [country] ([id], [name]) VALUES ('niu', 'niui');
INSERT INTO [country] ([id], [name]) VALUES ('nog', 'nogaj');
INSERT INTO [country] ([id], [name]) VALUES ('no', 'norvég');
INSERT INTO [country] ([id], [name]) VALUES ('nb', 'norvég bokmal');
INSERT INTO [country] ([id], [name]) VALUES ('nn', 'norvég nynorsk');
INSERT INTO [country] ([id], [name]) VALUES ('nub', 'núbiai nyelv');
INSERT INTO [country] ([id], [name]) VALUES ('nzi', 'nzima');
INSERT INTO [country] ([id], [name]) VALUES ('nym', 'nyamvézi');
INSERT INTO [country] ([id], [name]) VALUES ('ny', 'nyanja');
INSERT INTO [country] ([id], [name]) VALUES ('nyn', 'nyankole');
INSERT INTO [country] ([id], [name]) VALUES ('tog', 'nyasa tonga');
INSERT INTO [country] ([id], [name]) VALUES ('nyo', 'nyoró');
INSERT INTO [country] ([id], [name]) VALUES ('ang', 'óangol');
INSERT INTO [country] ([id], [name]) VALUES ('egy', 'óegyiptomi');
INSERT INTO [country] ([id], [name]) VALUES ('goh', 'ófelső német');
INSERT INTO [country] ([id], [name]) VALUES ('fro', 'ófrancia');
INSERT INTO [country] ([id], [name]) VALUES ('grc', 'ógörög');
INSERT INTO [country] ([id], [name]) VALUES ('sga', 'óír');
INSERT INTO [country] ([id], [name]) VALUES ('oj', 'ojibva');
INSERT INTO [country] ([id], [name]) VALUES ('oc', 'okszitán');
INSERT INTO [country] ([id], [name]) VALUES ('it', 'olasz');
INSERT INTO [country] ([id], [name]) VALUES ('peo', 'óperzsa');
INSERT INTO [country] ([id], [name]) VALUES ('pro', 'óprovánszi');
INSERT INTO [country] ([id], [name]) VALUES ('or', 'orija');
INSERT INTO [country] ([id], [name]) VALUES ('om', 'oromói');
INSERT INTO [country] ([id], [name]) VALUES ('ru', 'orosz');
INSERT INTO [country] ([id], [name]) VALUES ('osa', 'osage');
INSERT INTO [country] ([id], [name]) VALUES ('non', 'óskandináv');
INSERT INTO [country] ([id], [name]) VALUES ('os', 'oszét');
INSERT INTO [country] ([id], [name]) VALUES ('de_AT', 'osztrák német');
INSERT INTO [country] ([id], [name]) VALUES ('oto', 'otomi nyelv');
INSERT INTO [country] ([id], [name]) VALUES ('ota', 'ottomán török');
INSERT INTO [country] ([id], [name]) VALUES ('hy', 'örmény');
INSERT INTO [country] ([id], [name]) VALUES ('root', 'ősi');
INSERT INTO [country] ([id], [name]) VALUES ('pal', 'pahlavi');
INSERT INTO [country] ([id], [name]) VALUES ('pau', 'palaui');
INSERT INTO [country] ([id], [name]) VALUES ('pi', 'pali');
INSERT INTO [country] ([id], [name]) VALUES ('pam', 'pampangan');
INSERT INTO [country] ([id], [name]) VALUES ('pa', 'pandzsábi');
INSERT INTO [country] ([id], [name]) VALUES ('pag', 'pangaszinan');
INSERT INTO [country] ([id], [name]) VALUES ('pap', 'papiamentó');
INSERT INTO [country] ([id], [name]) VALUES ('paa', 'pápuai nyelv');
INSERT INTO [country] ([id], [name]) VALUES ('ps', 'pastu');
INSERT INTO [country] ([id], [name]) VALUES ('fa', 'perzsa');
INSERT INTO [country] ([id], [name]) VALUES ('pon', 'pohnpei');
INSERT INTO [country] ([id], [name]) VALUES ('pt', 'portugál');
INSERT INTO [country] ([id], [name]) VALUES ('cpp', 'portugál alapú kreol vagy pidgin');
INSERT INTO [country] ([id], [name]) VALUES ('pra', 'prakrit nyelvek');
INSERT INTO [country] ([id], [name]) VALUES ('raj', 'radzsasztáni');
INSERT INTO [country] ([id], [name]) VALUES ('rap', 'rapanui');
INSERT INTO [country] ([id], [name]) VALUES ('rar', 'rarotongai');
INSERT INTO [country] ([id], [name]) VALUES ('rm', 'réto-román');
INSERT INTO [country] ([id], [name]) VALUES ('rom', 'roma');
INSERT INTO [country] ([id], [name]) VALUES ('ro', 'román');
INSERT INTO [country] ([id], [name]) VALUES ('roa', 'román nyelv');
INSERT INTO [country] ([id], [name]) VALUES ('rof', 'rombo');
INSERT INTO [country] ([id], [name]) VALUES ('rwk', 'rwo');
INSERT INTO [country] ([id], [name]) VALUES ('shn', 'san');
INSERT INTO [country] ([id], [name]) VALUES ('sas', 'sasak');
INSERT INTO [country] ([id], [name]) VALUES ('bla', 'siksika');
INSERT INTO [country] ([id], [name]) VALUES ('sit', 'sinotibeti nyelv');
INSERT INTO [country] ([id], [name]) VALUES ('sco', 'skót');
INSERT INTO [country] ([id], [name]) VALUES ('gd', 'skót gael');
INSERT INTO [country] ([id], [name]) VALUES ('sog', 'sogdien');
INSERT INTO [country] ([id], [name]) VALUES ('sn', 'sona');
INSERT INTO [country] ([id], [name]) VALUES ('es', 'spanyol');
INSERT INTO [country] ([id], [name]) VALUES ('sux', 'sumér');
INSERT INTO [country] ([id], [name]) VALUES ('de_CH', 'svájci felnémet');
INSERT INTO [country] ([id], [name]) VALUES ('fr_CH', 'svájci francia');
INSERT INTO [country] ([id], [name]) VALUES ('gsw', 'svájci német');
INSERT INTO [country] ([id], [name]) VALUES ('sv', 'svéd');
INSERT INTO [country] ([id], [name]) VALUES ('sam', 'szamaritánus arámi');
INSERT INTO [country] ([id], [name]) VALUES ('sm', 'szamoai');
INSERT INTO [country] ([id], [name]) VALUES ('sad', 'szandave');
INSERT INTO [country] ([id], [name]) VALUES ('sg', 'szangó');
INSERT INTO [country] ([id], [name]) VALUES ('sa', 'szanszkrit');
INSERT INTO [country] ([id], [name]) VALUES ('sat', 'szantáli');
INSERT INTO [country] ([id], [name]) VALUES ('sc', 'szardíniai');
INSERT INTO [country] ([id], [name]) VALUES ('ii', 'szecsuán ji');
INSERT INTO [country] ([id], [name]) VALUES ('tn', 'szecsuáni');
INSERT INTO [country] ([id], [name]) VALUES ('sal', 'szelis nyelv');
INSERT INTO [country] ([id], [name]) VALUES ('sr', 'szerb');
INSERT INTO [country] ([id], [name]) VALUES ('sh', 'szerbhorvát');
INSERT INTO [country] ([id], [name]) VALUES ('srr', 'szerer');
INSERT INTO [country] ([id], [name]) VALUES ('st', 'szeszotó');
INSERT INTO [country] ([id], [name]) VALUES ('scn', 'szicíliai');
INSERT INTO [country] ([id], [name]) VALUES ('sid', 'szidamó');
INSERT INTO [country] ([id], [name]) VALUES ('sd', 'szindhi');
INSERT INTO [country] ([id], [name]) VALUES ('si', 'szingaléz');
INSERT INTO [country] ([id], [name]) VALUES ('syr', 'szíriai');
INSERT INTO [country] ([id], [name]) VALUES ('ss', 'sziszuati');
INSERT INTO [country] ([id], [name]) VALUES ('sio', 'sziú nyelvek');
INSERT INTO [country] ([id], [name]) VALUES ('sla', 'szláv nyelv');
INSERT INTO [country] ([id], [name]) VALUES ('den', 'szlevi');
INSERT INTO [country] ([id], [name]) VALUES ('sk', 'szlovák');
INSERT INTO [country] ([id], [name]) VALUES ('sl', 'szlovén');
INSERT INTO [country] ([id], [name]) VALUES ('so', 'szomáliai');
INSERT INTO [country] ([id], [name]) VALUES ('son', 'szongai');
INSERT INTO [country] ([id], [name]) VALUES ('snk', 'szoninke');
INSERT INTO [country] ([id], [name]) VALUES ('wen', 'szorb nyelvek');
INSERT INTO [country] ([id], [name]) VALUES ('sel', 'szölkup');
INSERT INTO [country] ([id], [name]) VALUES ('srn', 'szranai tongó');
INSERT INTO [country] ([id], [name]) VALUES ('sw', 'szuahéli');
INSERT INTO [country] ([id], [name]) VALUES ('suk', 'szukuma');
INSERT INTO [country] ([id], [name]) VALUES ('su', 'szundanéz');
INSERT INTO [country] ([id], [name]) VALUES ('sus', 'szuszu');
INSERT INTO [country] ([id], [name]) VALUES ('tg', 'tadzsik');
INSERT INTO [country] ([id], [name]) VALUES ('tl', 'tagalog');
INSERT INTO [country] ([id], [name]) VALUES ('ty', 'tahiti');
INSERT INTO [country] ([id], [name]) VALUES ('tmh', 'tamasek');
INSERT INTO [country] ([id], [name]) VALUES ('ta', 'tamil');
INSERT INTO [country] ([id], [name]) VALUES ('tt', 'tatár');
INSERT INTO [country] ([id], [name]) VALUES ('te', 'telugu');
INSERT INTO [country] ([id], [name]) VALUES ('tem', 'temne');
INSERT INTO [country] ([id], [name]) VALUES ('ter', 'terenó');
INSERT INTO [country] ([id], [name]) VALUES ('tet', 'tetum');
INSERT INTO [country] ([id], [name]) VALUES ('th', 'thai');
INSERT INTO [country] ([id], [name]) VALUES ('tai', 'thai nyelv');
INSERT INTO [country] ([id], [name]) VALUES ('bo', 'tibeti');
INSERT INTO [country] ([id], [name]) VALUES ('tig', 'tigré');
INSERT INTO [country] ([id], [name]) VALUES ('ti', 'tigrinja');
INSERT INTO [country] ([id], [name]) VALUES ('tiv', 'tiv');
INSERT INTO [country] ([id], [name]) VALUES ('tli', 'tlingit');
INSERT INTO [country] ([id], [name]) VALUES ('tpi', 'tok pisin');
INSERT INTO [country] ([id], [name]) VALUES ('tkl', 'tokelaui');
INSERT INTO [country] ([id], [name]) VALUES ('to', 'tonga');
INSERT INTO [country] ([id], [name]) VALUES ('tr', 'török');
INSERT INTO [country] ([id], [name]) VALUES ('tum', 'tumbuka');
INSERT INTO [country] ([id], [name]) VALUES ('tup', 'tupi nyelv');
INSERT INTO [country] ([id], [name]) VALUES ('tyv', 'tuvai');
INSERT INTO [country] ([id], [name]) VALUES ('tvl', 'tuvalu');
INSERT INTO [country] ([id], [name]) VALUES ('tk', 'türkmén');
INSERT INTO [country] ([id], [name]) VALUES ('tw', 'twi');
INSERT INTO [country] ([id], [name]) VALUES ('kcg', 'tyap');
INSERT INTO [country] ([id], [name]) VALUES ('udm', 'udmurt');
INSERT INTO [country] ([id], [name]) VALUES ('uga', 'ugariti');
INSERT INTO [country] ([id], [name]) VALUES ('ug', 'ujgur');
INSERT INTO [country] ([id], [name]) VALUES ('uk', 'ukrán');
INSERT INTO [country] ([id], [name]) VALUES ('umb', 'umbundu');
INSERT INTO [country] ([id], [name]) VALUES ('ur', 'urdu');
INSERT INTO [country] ([id], [name]) VALUES ('uz', 'üzbég');
INSERT INTO [country] ([id], [name]) VALUES ('vai', 'vai');
INSERT INTO [country] ([id], [name]) VALUES ('wak', 'vakas nyelv');
INSERT INTO [country] ([id], [name]) VALUES ('wal', 'valamo');
INSERT INTO [country] ([id], [name]) VALUES ('wa', 'vallon');
INSERT INTO [country] ([id], [name]) VALUES ('war', 'varaó');
INSERT INTO [country] ([id], [name]) VALUES ('was', 'vasó');
INSERT INTO [country] ([id], [name]) VALUES ('ve', 'venda');
INSERT INTO [country] ([id], [name]) VALUES ('vi', 'vietnami');
INSERT INTO [country] ([id], [name]) VALUES ('vo', 'volapük');
INSERT INTO [country] ([id], [name]) VALUES ('wo', 'volof');
INSERT INTO [country] ([id], [name]) VALUES ('vot', 'votják');
INSERT INTO [country] ([id], [name]) VALUES ('cy', 'walesi');
INSERT INTO [country] ([id], [name]) VALUES ('wae', 'walser');
INSERT INTO [country] ([id], [name]) VALUES ('znd', 'zande');
INSERT INTO [country] ([id], [name]) VALUES ('zap', 'zapoték');
INSERT INTO [country] ([id], [name]) VALUES ('zza', 'zaza');
INSERT INTO [country] ([id], [name]) VALUES ('zen', 'zenaga');
INSERT INTO [country] ([id], [name]) VALUES ('zu', 'zulu');
INSERT INTO [country] ([id], [name]) VALUES ('zun', 'zuni');
INSERT INTO [country] ([id], [name]) VALUES ('jrb', 'zsidó-arab');
INSERT INTO [country] ([id], [name]) VALUES ('jpr', 'zsidó-perzsa');
INSERT INTO [country] ([id], [name]) VALUES ('za', 'zsuang');
