CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('anp', 'अंगिका');
INSERT INTO `country` (`id`, `name`) VALUES ('en_AU', 'अंग्रेज़ी (ऑस्ट्रेलिया)');
INSERT INTO `country` (`id`, `name`) VALUES ('en_US', 'अंग्रेज़ी अमेरीकी');
INSERT INTO `country` (`id`, `name`) VALUES ('en_CA', 'अंग्रेज़ी(कनाडाई)');
INSERT INTO `country` (`id`, `name`) VALUES ('en', 'अंग्रेजी');
INSERT INTO `country` (`id`, `name`) VALUES ('cpe', 'अंग्रेजी आधारित क्रेओल या पिजिन');
INSERT INTO `country` (`id`, `name`) VALUES ('en_GB', 'अंग्रेजी(ब्रिटिश)');
INSERT INTO `country` (`id`, `name`) VALUES ('ak', 'अकन');
INSERT INTO `country` (`id`, `name`) VALUES ('ach', 'अकोली');
INSERT INTO `country` (`id`, `name`) VALUES ('akk', 'अक्केदिअन');
INSERT INTO `country` (`id`, `name`) VALUES ('ace', 'अचाइनीस');
INSERT INTO `country` (`id`, `name`) VALUES ('az', 'अज़रबैंजानी');
INSERT INTO `country` (`id`, `name`) VALUES ('und', 'अज्ञात या अवैध भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('cch', 'अत्सम');
INSERT INTO `country` (`id`, `name`) VALUES ('ath', 'अथापास्कान भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('ada', 'अदान्गमे');
INSERT INTO `country` (`id`, `name`) VALUES ('ady', 'अदिघे');
INSERT INTO `country` (`id`, `name`) VALUES ('apa', 'अपाचे भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('aa', 'अफ़ार');
INSERT INTO `country` (`id`, `name`) VALUES ('afh', 'अफ्रिहिली');
INSERT INTO `country` (`id`, `name`) VALUES ('af', 'अफ्रीकी');
INSERT INTO `country` (`id`, `name`) VALUES ('afa', 'अफ्रो-एशियाई भाषाएँ');
INSERT INTO `country` (`id`, `name`) VALUES ('ab', 'अब्खाज़ियन्');
INSERT INTO `country` (`id`, `name`) VALUES ('am', 'अम्हारिक्');
INSERT INTO `country` (`id`, `name`) VALUES ('ar', 'अरबी');
INSERT INTO `country` (`id`, `name`) VALUES ('hy', 'अरमेनियन्');
INSERT INTO `country` (`id`, `name`) VALUES ('arp', 'अराफाओ');
INSERT INTO `country` (`id`, `name`) VALUES ('arw', 'अरावक');
INSERT INTO `country` (`id`, `name`) VALUES ('rup', 'अरोमानियन');
INSERT INTO `country` (`id`, `name`) VALUES ('an', 'अर्गोनी');
INSERT INTO `country` (`id`, `name`) VALUES ('ale', 'अलेउत');
INSERT INTO `country` (`id`, `name`) VALUES ('tut', 'अल्तैक भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('sq', 'अल्बेनियन्');
INSERT INTO `country` (`id`, `name`) VALUES ('awa', 'अवधी');
INSERT INTO `country` (`id`, `name`) VALUES ('av', 'अवेरिक');
INSERT INTO `country` (`id`, `name`) VALUES ('ae', 'अवेस्तन');
INSERT INTO `country` (`id`, `name`) VALUES ('as', 'असामी');
INSERT INTO `country` (`id`, `name`) VALUES ('ast', 'अस्तुरियन');
INSERT INTO `country` (`id`, `name`) VALUES ('is', 'आईस्लैंडिक्');
INSERT INTO `country` (`id`, `name`) VALUES ('ay', 'आयमारा');
INSERT INTO `country` (`id`, `name`) VALUES ('ga', 'आयरिश');
INSERT INTO `country` (`id`, `name`) VALUES ('aus', 'आस्ट्रेलियाई भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('inh', 'इंगुश');
INSERT INTO `country` (`id`, `name`) VALUES ('ine', 'इंडो-युरोपीय भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('ijo', 'इजो');
INSERT INTO `country` (`id`, `name`) VALUES ('io', 'इडौ');
INSERT INTO `country` (`id`, `name`) VALUES ('it', 'इतालवी');
INSERT INTO `country` (`id`, `name`) VALUES ('smn', 'इनारी सामी');
INSERT INTO `country` (`id`, `name`) VALUES ('ik', 'इनुपियाक्');
INSERT INTO `country` (`id`, `name`) VALUES ('iu', 'इनूकीटूत्');
INSERT INTO `country` (`id`, `name`) VALUES ('id', 'इन्डोनेशियाई');
INSERT INTO `country` (`id`, `name`) VALUES ('iba', 'इबान');
INSERT INTO `country` (`id`, `name`) VALUES ('iro', 'इरोक्युओइयन भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('ilo', 'इलोको');
INSERT INTO `country` (`id`, `name`) VALUES ('ewo', 'इवोन्डो');
INSERT INTO `country` (`id`, `name`) VALUES ('ig', 'ईग्बो');
INSERT INTO `country` (`id`, `name`) VALUES ('ia', 'ईन्टरलिंगुआ');
INSERT INTO `country` (`id`, `name`) VALUES ('ie', 'ईन्टरलिंगुइ');
INSERT INTO `country` (`id`, `name`) VALUES ('ira', 'ईरानी भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('ee', 'ईवे');
INSERT INTO `country` (`id`, `name`) VALUES ('pt_PT', 'ईवेरियाई पुर्तगाली');
INSERT INTO `country` (`id`, `name`) VALUES ('es_ES', 'ईवेरियाई स्पेनिश');
INSERT INTO `country` (`id`, `name`) VALUES ('ug', 'उईघुर');
INSERT INTO `country` (`id`, `name`) VALUES ('uz', 'उज़्बेक');
INSERT INTO `country` (`id`, `name`) VALUES ('or', 'उड़िया');
INSERT INTO `country` (`id`, `name`) VALUES ('nai', 'उत्तरी अमेरीकी इंडियन भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('nd', 'उत्तरी देबेल');
INSERT INTO `country` (`id`, `name`) VALUES ('frr', 'उत्तरी फ्रीसीयन');
INSERT INTO `country` (`id`, `name`) VALUES ('nso', 'उत्तरी सोथो');
INSERT INTO `country` (`id`, `name`) VALUES ('udm', 'उदमुर्त');
INSERT INTO `country` (`id`, `name`) VALUES ('umb', 'उम्बुन्डु');
INSERT INTO `country` (`id`, `name`) VALUES ('ur', 'उर्दू');
INSERT INTO `country` (`id`, `name`) VALUES ('hsb', 'ऊपरी सॉर्बियन');
INSERT INTO `country` (`id`, `name`) VALUES ('eka', 'एकाजुक');
INSERT INTO `country` (`id`, `name`) VALUES ('nqo', 'एन्को');
INSERT INTO `country` (`id`, `name`) VALUES ('efi', 'एफिक');
INSERT INTO `country` (`id`, `name`) VALUES ('arn', 'एरोकैनियन');
INSERT INTO `country` (`id`, `name`) VALUES ('myv', 'एर्ज़या');
INSERT INTO `country` (`id`, `name`) VALUES ('elx', 'एलामाइट');
INSERT INTO `country` (`id`, `name`) VALUES ('alg', 'एल्गोनक्युइअन भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('eo', 'एस्पेरान्तो');
INSERT INTO `country` (`id`, `name`) VALUES ('ain', 'ऐनू');
INSERT INTO `country` (`id`, `name`) VALUES ('arc', 'ऐरेमेक');
INSERT INTO `country` (`id`, `name`) VALUES ('et', 'ऐस्तोनियन्');
INSERT INTO `country` (`id`, `name`) VALUES ('map', 'ऑस्ट्रोनेशियन');
INSERT INTO `country` (`id`, `name`) VALUES ('oj', 'ओजिब्वा');
INSERT INTO `country` (`id`, `name`) VALUES ('ota', 'ओटोमान तुर्किश');
INSERT INTO `country` (`id`, `name`) VALUES ('oto', 'ओटोमियन भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('om', 'ओरोमो');
INSERT INTO `country` (`id`, `name`) VALUES ('oc', 'ओसीटान');
INSERT INTO `country` (`id`, `name`) VALUES ('osa', 'ओसेज');
INSERT INTO `country` (`id`, `name`) VALUES ('os', 'ओस्सेटिक');
INSERT INTO `country` (`id`, `name`) VALUES ('kk', 'कज़ाख');
INSERT INTO `country` (`id`, `name`) VALUES ('kr', 'कनुरी');
INSERT INTO `country` (`id`, `name`) VALUES ('kn', 'कन्नड़');
INSERT INTO `country` (`id`, `name`) VALUES ('kab', 'कबाइल');
INSERT INTO `country` (`id`, `name`) VALUES ('kbd', 'कबार्डियन');
INSERT INTO `country` (`id`, `name`) VALUES ('ch', 'कमोरो');
INSERT INTO `country` (`id`, `name`) VALUES ('kam', 'कम्बा');
INSERT INTO `country` (`id`, `name`) VALUES ('krc', 'कराचय-बल्कार');
INSERT INTO `country` (`id`, `name`) VALUES ('krl', 'करेलियन');
INSERT INTO `country` (`id`, `name`) VALUES ('ks', 'कश्मीरी');
INSERT INTO `country` (`id`, `name`) VALUES ('kac', 'काचिन');
INSERT INTO `country` (`id`, `name`) VALUES ('ca', 'कातालान');
INSERT INTO `country` (`id`, `name`) VALUES ('kaa', 'कारा-कल्पक');
INSERT INTO `country` (`id`, `name`) VALUES ('kar', 'कारेन');
INSERT INTO `country` (`id`, `name`) VALUES ('xal', 'काल्मिक');
INSERT INTO `country` (`id`, `name`) VALUES ('kaw', 'कावी');
INSERT INTO `country` (`id`, `name`) VALUES ('csb', 'काशुबियन');
INSERT INTO `country` (`id`, `name`) VALUES ('ki', 'किकुयू');
INSERT INTO `country` (`id`, `name`) VALUES ('rw', 'किन्यारवाण्डा');
INSERT INTO `country` (`id`, `name`) VALUES ('kmb', 'किम्बन्दु');
INSERT INTO `country` (`id`, `name`) VALUES ('ky', 'किरघिज़');
INSERT INTO `country` (`id`, `name`) VALUES ('kut', 'कुतेनाई');
INSERT INTO `country` (`id`, `name`) VALUES ('kum', 'कुमीक');
INSERT INTO `country` (`id`, `name`) VALUES ('ku', 'कुरदीश');
INSERT INTO `country` (`id`, `name`) VALUES ('kru', 'कुरूख');
INSERT INTO `country` (`id`, `name`) VALUES ('cus', 'कुशितिक भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('art', 'कृत्रिम भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('cel', 'केल्टिक भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('cad', 'कैड्डो');
INSERT INTO `country` (`id`, `name`) VALUES ('km', 'कैम्बोडियन्');
INSERT INTO `country` (`id`, `name`) VALUES ('car', 'कैरिब');
INSERT INTO `country` (`id`, `name`) VALUES ('cau', 'कॉकेशियन भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('cop', 'कॉप्टिक');
INSERT INTO `country` (`id`, `name`) VALUES ('kok', 'कोंकणी');
INSERT INTO `country` (`id`, `name`) VALUES ('kg', 'कोंगो');
INSERT INTO `country` (`id`, `name`) VALUES ('zxx', 'कोई लिंग्विस्ट सामग्री नहीं');
INSERT INTO `country` (`id`, `name`) VALUES ('kv', 'कोमी');
INSERT INTO `country` (`id`, `name`) VALUES ('ko', 'कोरीयन्');
INSERT INTO `country` (`id`, `name`) VALUES ('kfo', 'कोरो');
INSERT INTO `country` (`id`, `name`) VALUES ('kw', 'कोर्निश');
INSERT INTO `country` (`id`, `name`) VALUES ('co', 'कोर्सीकन');
INSERT INTO `country` (`id`, `name`) VALUES ('kos', 'कोसरैन');
INSERT INTO `country` (`id`, `name`) VALUES ('kpe', 'क्पेल्लै');
INSERT INTO `country` (`id`, `name`) VALUES ('cr', 'क्री');
INSERT INTO `country` (`id`, `name`) VALUES ('mus', 'क्रीक');
INSERT INTO `country` (`id`, `name`) VALUES ('crh', 'क्रीमीन तुर्की');
INSERT INTO `country` (`id`, `name`) VALUES ('kro', 'क्रु');
INSERT INTO `country` (`id`, `name`) VALUES ('crp', 'क्रेओल या पिजिन');
INSERT INTO `country` (`id`, `name`) VALUES ('hr', 'क्रोएशन्');
INSERT INTO `country` (`id`, `name`) VALUES ('syc', 'क्लासिकल सिरिएक');
INSERT INTO `country` (`id`, `name`) VALUES ('tlh', 'क्लिंगन');
INSERT INTO `country` (`id`, `name`) VALUES ('kj', 'क्वान्यामा');
INSERT INTO `country` (`id`, `name`) VALUES ('qu', 'क्वेशुआ');
INSERT INTO `country` (`id`, `name`) VALUES ('kha', 'खासी');
INSERT INTO `country` (`id`, `name`) VALUES ('khi', 'खोइसन भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('kho', 'खोतानीस');
INSERT INTO `country` (`id`, `name`) VALUES ('gaa', 'गा');
INSERT INTO `country` (`id`, `name`) VALUES ('gon', 'गाँडी');
INSERT INTO `country` (`id`, `name`) VALUES ('lg', 'गांडा');
INSERT INTO `country` (`id`, `name`) VALUES ('gay', 'गायो');
INSERT INTO `country` (`id`, `name`) VALUES ('gil', 'गिल्बरतीस');
INSERT INTO `country` (`id`, `name`) VALUES ('gez', 'गीज़');
INSERT INTO `country` (`id`, `name`) VALUES ('gn', 'गुआरानी');
INSERT INTO `country` (`id`, `name`) VALUES ('gu', 'गुज़राती');
INSERT INTO `country` (`id`, `name`) VALUES ('gl', 'गैलिशियन्');
INSERT INTO `country` (`id`, `name`) VALUES ('got', 'गॉथिक');
INSERT INTO `country` (`id`, `name`) VALUES ('gor', 'गोरोन्तालो');
INSERT INTO `country` (`id`, `name`) VALUES ('gba', 'ग्बाया');
INSERT INTO `country` (`id`, `name`) VALUES ('el', 'ग्रीक');
INSERT INTO `country` (`id`, `name`) VALUES ('kl', 'ग्रीनलैंडिक');
INSERT INTO `country` (`id`, `name`) VALUES ('grb', 'ग्रेबो');
INSERT INTO `country` (`id`, `name`) VALUES ('gwi', 'ग्विच\'इन');
INSERT INTO `country` (`id`, `name`) VALUES ('cu', 'चर्च साल्विक');
INSERT INTO `country` (`id`, `name`) VALUES ('chn', 'चिनूक जारगॉन');
INSERT INTO `country` (`id`, `name`) VALUES ('chb', 'चिब्चा');
INSERT INTO `country` (`id`, `name`) VALUES ('zh', 'चीनी');
INSERT INTO `country` (`id`, `name`) VALUES ('zh_Hant', 'चीनी (पारम्परिक)');
INSERT INTO `country` (`id`, `name`) VALUES ('zh_Hans', 'चीनी (सरलीकृत)');
INSERT INTO `country` (`id`, `name`) VALUES ('sit', 'चीनी-तिब्ब्ती भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('chk', 'चूकीस');
INSERT INTO `country` (`id`, `name`) VALUES ('cv', 'चूवाश');
INSERT INTO `country` (`id`, `name`) VALUES ('cs', 'चेक');
INSERT INTO `country` (`id`, `name`) VALUES ('ce', 'चेचन');
INSERT INTO `country` (`id`, `name`) VALUES ('cho', 'चोक्तौ');
INSERT INTO `country` (`id`, `name`) VALUES ('chg', 'छगाताई');
INSERT INTO `country` (`id`, `name`) VALUES ('de_AT', 'जर्मन (ऑस्ट्रिया)');
INSERT INTO `country` (`id`, `name`) VALUES ('gem', 'जर्मनिक भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('znd', 'ज़न्डे');
INSERT INTO `country` (`id`, `name`) VALUES ('de', 'ज़र्मन');
INSERT INTO `country` (`id`, `name`) VALUES ('zza', 'ज़ाज़ा');
INSERT INTO `country` (`id`, `name`) VALUES ('za', 'ज़ुआंग');
INSERT INTO `country` (`id`, `name`) VALUES ('zu', 'ज़ुलू');
INSERT INTO `country` (`id`, `name`) VALUES ('zun', 'ज़ूनी');
INSERT INTO `country` (`id`, `name`) VALUES ('zen', 'ज़ेनान्गा');
INSERT INTO `country` (`id`, `name`) VALUES ('zap', 'ज़ेपोटेक');
INSERT INTO `country` (`id`, `name`) VALUES ('dz', 'ज़ोन्गखा');
INSERT INTO `country` (`id`, `name`) VALUES ('ja', 'जापानी');
INSERT INTO `country` (`id`, `name`) VALUES ('jv', 'जावानीस');
INSERT INTO `country` (`id`, `name`) VALUES ('jrb', 'जुदेओ-अरेबिक');
INSERT INTO `country` (`id`, `name`) VALUES ('jpr', 'जुदेओ-पर्शियन');
INSERT INTO `country` (`id`, `name`) VALUES ('ka', 'जॉर्जीयन्');
INSERT INTO `country` (`id`, `name`) VALUES ('kaj', 'ज्जु');
INSERT INTO `country` (`id`, `name`) VALUES ('tig', 'टाइग्रे');
INSERT INTO `country` (`id`, `name`) VALUES ('tt', 'टाटर');
INSERT INTO `country` (`id`, `name`) VALUES ('tem', 'टिम्ने');
INSERT INTO `country` (`id`, `name`) VALUES ('to', 'टोंगा');
INSERT INTO `country` (`id`, `name`) VALUES ('tpi', 'टोक पिसिन');
INSERT INTO `country` (`id`, `name`) VALUES ('tup', 'ट्यूपी भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('tw', 'ट्वी');
INSERT INTO `country` (`id`, `name`) VALUES ('nl', 'डच्');
INSERT INTO `country` (`id`, `name`) VALUES ('del', 'डिलैवेयर');
INSERT INTO `country` (`id`, `name`) VALUES ('da', 'डैनीश');
INSERT INTO `country` (`id`, `name`) VALUES ('dgr', 'डोग्रिब');
INSERT INTO `country` (`id`, `name`) VALUES ('doi', 'डोग्री');
INSERT INTO `country` (`id`, `name`) VALUES ('ng', 'डोन्गा');
INSERT INTO `country` (`id`, `name`) VALUES ('dyu', 'ड्युला');
INSERT INTO `country` (`id`, `name`) VALUES ('ta', 'तमिल');
INSERT INTO `country` (`id`, `name`) VALUES ('tum', 'तम्बूका');
INSERT INTO `country` (`id`, `name`) VALUES ('tai', 'ताई भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('tl', 'तागालोग');
INSERT INTO `country` (`id`, `name`) VALUES ('tg', 'ताजिक्');
INSERT INTO `country` (`id`, `name`) VALUES ('tmh', 'तामाशेक');
INSERT INTO `country` (`id`, `name`) VALUES ('ty', 'ताहितियन');
INSERT INTO `country` (`id`, `name`) VALUES ('ti', 'तिग्रीन्या');
INSERT INTO `country` (`id`, `name`) VALUES ('bo', 'तिब्बती');
INSERT INTO `country` (`id`, `name`) VALUES ('tiv', 'तिव');
INSERT INTO `country` (`id`, `name`) VALUES ('tk', 'तुक्रमेन');
INSERT INTO `country` (`id`, `name`) VALUES ('tr', 'तुर्की');
INSERT INTO `country` (`id`, `name`) VALUES ('tvl', 'तुवालु');
INSERT INTO `country` (`id`, `name`) VALUES ('tyv', 'तुवीनियन');
INSERT INTO `country` (`id`, `name`) VALUES ('tet', 'तेतुम');
INSERT INTO `country` (`id`, `name`) VALUES ('ter', 'तेरेनो');
INSERT INTO `country` (`id`, `name`) VALUES ('te', 'तेलेगु');
INSERT INTO `country` (`id`, `name`) VALUES ('tkl', 'तोकेलाऊ');
INSERT INTO `country` (`id`, `name`) VALUES ('kcg', 'त्याप');
INSERT INTO `country` (`id`, `name`) VALUES ('tli', 'त्लिंगित');
INSERT INTO `country` (`id`, `name`) VALUES ('tsi', 'त्सिमीशियन');
INSERT INTO `country` (`id`, `name`) VALUES ('th', 'थाई');
INSERT INTO `country` (`id`, `name`) VALUES ('sai', 'दक्षिण अमेरीकी इंडियन भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('nr', 'दक्षिण देबेल');
INSERT INTO `country` (`id`, `name`) VALUES ('sma', 'दक्षिण सामी');
INSERT INTO `country` (`id`, `name`) VALUES ('alt', 'दक्षिणी अल्ताई');
INSERT INTO `country` (`id`, `name`) VALUES ('dak', 'दाकोता');
INSERT INTO `country` (`id`, `name`) VALUES ('day', 'दायक');
INSERT INTO `country` (`id`, `name`) VALUES ('dar', 'दार्गवा');
INSERT INTO `country` (`id`, `name`) VALUES ('din', 'दिन्का');
INSERT INTO `country` (`id`, `name`) VALUES ('dv', 'दिवेही');
INSERT INTO `country` (`id`, `name`) VALUES ('dua', 'दुआला');
INSERT INTO `country` (`id`, `name`) VALUES ('dra', 'द्रविण भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('nah', 'नहुआत्ल');
INSERT INTO `country` (`id`, `name`) VALUES ('nic', 'नाइगर-कोर्डोफैनियन भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('na', 'नाउरू');
INSERT INTO `country` (`id`, `name`) VALUES ('no', 'नार्वेजियन');
INSERT INTO `country` (`id`, `name`) VALUES ('nv', 'नावाजो');
INSERT INTO `country` (`id`, `name`) VALUES ('nds', 'निचला जर्मन');
INSERT INTO `country` (`id`, `name`) VALUES ('dsb', 'निचला सॉर्बियन');
INSERT INTO `country` (`id`, `name`) VALUES ('nia', 'नियास');
INSERT INTO `country` (`id`, `name`) VALUES ('niu', 'नियुआन');
INSERT INTO `country` (`id`, `name`) VALUES ('nap', 'नीपोलिटन');
INSERT INTO `country` (`id`, `name`) VALUES ('ssa', 'नील सहारी भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('ne', 'नेपाली');
INSERT INTO `country` (`id`, `name`) VALUES ('new', 'नेवाड़ी');
INSERT INTO `country` (`id`, `name`) VALUES ('se', 'नॉर्दन सामी');
INSERT INTO `country` (`id`, `name`) VALUES ('nn', 'नॉर्वेजियन नाइनोर्स्क');
INSERT INTO `country` (`id`, `name`) VALUES ('nb', 'नॉर्वेजियन बोकमाल');
INSERT INTO `country` (`id`, `name`) VALUES ('nog', 'नोगाई');
INSERT INTO `country` (`id`, `name`) VALUES ('nzi', 'न्ज़ीमा');
INSERT INTO `country` (`id`, `name`) VALUES ('nyn', 'न्यानकोल');
INSERT INTO `country` (`id`, `name`) VALUES ('ny', 'न्यानजा');
INSERT INTO `country` (`id`, `name`) VALUES ('nym', 'न्यामवेज़ी');
INSERT INTO `country` (`id`, `name`) VALUES ('tog', 'न्यासा टोन्गा');
INSERT INTO `country` (`id`, `name`) VALUES ('nub', 'न्युबियान भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('nyo', 'न्योरो');
INSERT INTO `country` (`id`, `name`) VALUES ('pag', 'पंगासीनान');
INSERT INTO `country` (`id`, `name`) VALUES ('pa', 'पंजाबी');
INSERT INTO `country` (`id`, `name`) VALUES ('fa', 'पर्शियन्');
INSERT INTO `country` (`id`, `name`) VALUES ('pau', 'पलोउआन');
INSERT INTO `country` (`id`, `name`) VALUES ('fy', 'पश्चिमी फ़्रिसियाई');
INSERT INTO `country` (`id`, `name`) VALUES ('pap', 'पापियामेन्टो');
INSERT INTO `country` (`id`, `name`) VALUES ('paa', 'पापुआन भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('pam', 'पाम्पान्गा');
INSERT INTO `country` (`id`, `name`) VALUES ('nwc', 'पारम्परिक नेवारी');
INSERT INTO `country` (`id`, `name`) VALUES ('pi', 'पाली');
INSERT INTO `country` (`id`, `name`) VALUES ('pal', 'पाह्लावी');
INSERT INTO `country` (`id`, `name`) VALUES ('goh', 'पुरातन हाइ जर्मन');
INSERT INTO `country` (`id`, `name`) VALUES ('non', 'पुराना नॉर्स');
INSERT INTO `country` (`id`, `name`) VALUES ('ang', 'पुरानी अंग्रेज़ी');
INSERT INTO `country` (`id`, `name`) VALUES ('sga', 'पुरानी आइरिश');
INSERT INTO `country` (`id`, `name`) VALUES ('pro', 'पुरानी प्रोवेन्सल');
INSERT INTO `country` (`id`, `name`) VALUES ('peo', 'पुरानी फारसी');
INSERT INTO `country` (`id`, `name`) VALUES ('fro', 'पुरानी फ्रांसीसी');
INSERT INTO `country` (`id`, `name`) VALUES ('pt', 'पुर्तगाली');
INSERT INTO `country` (`id`, `name`) VALUES ('pt_BR', 'पुर्तगाली (ब्राज़ील)');
INSERT INTO `country` (`id`, `name`) VALUES ('cpp', 'पुर्तगाली आधारित क्रेओल या पिजिन');
INSERT INTO `country` (`id`, `name`) VALUES ('frs', 'पूर्वी फ्रीसीयन');
INSERT INTO `country` (`id`, `name`) VALUES ('pl', 'पॉलिश');
INSERT INTO `country` (`id`, `name`) VALUES ('ps', 'पॉशतो');
INSERT INTO `country` (`id`, `name`) VALUES ('pon', 'पोह्नपिएन');
INSERT INTO `country` (`id`, `name`) VALUES ('pra', 'प्राकृत');
INSERT INTO `country` (`id`, `name`) VALUES ('egy', 'प्राचीन मिस्री');
INSERT INTO `country` (`id`, `name`) VALUES ('grc', 'प्राचीन यूनानी');
INSERT INTO `country` (`id`, `name`) VALUES ('fat', 'फन्टी');
INSERT INTO `country` (`id`, `name`) VALUES ('fj', 'फ़ीजी');
INSERT INTO `country` (`id`, `name`) VALUES ('fr_CA', 'फ़्रेंच(कनाडाई)');
INSERT INTO `country` (`id`, `name`) VALUES ('fi', 'फिनिश');
INSERT INTO `country` (`id`, `name`) VALUES ('fiu', 'फिन्नो-उग्रीयन भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('fo', 'फिरोज़ी');
INSERT INTO `country` (`id`, `name`) VALUES ('fil', 'फिलिपिनो');
INSERT INTO `country` (`id`, `name`) VALUES ('phi', 'फिलिपीन भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('ff', 'फुलाह');
INSERT INTO `country` (`id`, `name`) VALUES ('fan', 'फैन्ग');
INSERT INTO `country` (`id`, `name`) VALUES ('fon', 'फॉन');
INSERT INTO `country` (`id`, `name`) VALUES ('phn', 'फोएनिशियन');
INSERT INTO `country` (`id`, `name`) VALUES ('fur', 'फ्रीयुलीयान');
INSERT INTO `country` (`id`, `name`) VALUES ('fr', 'फ्रेंच');
INSERT INTO `country` (`id`, `name`) VALUES ('cpf', 'फ्रेंच आधारित क्रेओल या पिजिन');
INSERT INTO `country` (`id`, `name`) VALUES ('bn', 'बँगाली');
INSERT INTO `country` (`id`, `name`) VALUES ('bug', 'बगिनीस');
INSERT INTO `country` (`id`, `name`) VALUES ('btk', 'बताक');
INSERT INTO `country` (`id`, `name`) VALUES ('bnt', 'बन्तु');
INSERT INTO `country` (`id`, `name`) VALUES ('bai', 'बमिलेके भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('ber', 'बरबर');
INSERT INTO `country` (`id`, `name`) VALUES ('my', 'बर्लिस');
INSERT INTO `country` (`id`, `name`) VALUES ('bal', 'बलूची');
INSERT INTO `country` (`id`, `name`) VALUES ('bg', 'बल्गेरियाई');
INSERT INTO `country` (`id`, `name`) VALUES ('ba', 'बशख़िर');
INSERT INTO `country` (`id`, `name`) VALUES ('bas', 'बसा');
INSERT INTO `country` (`id`, `name`) VALUES ('bad', 'बांदा');
INSERT INTO `country` (`id`, `name`) VALUES ('bm', 'बाम्बारा');
INSERT INTO `country` (`id`, `name`) VALUES ('ban', 'बालिनीस');
INSERT INTO `country` (`id`, `name`) VALUES ('bat', 'बाल्टिक भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('eu', 'बास्क्');
INSERT INTO `country` (`id`, `name`) VALUES ('bik', 'बिकोल');
INSERT INTO `country` (`id`, `name`) VALUES ('bin', 'बिनी');
INSERT INTO `country` (`id`, `name`) VALUES ('bi', 'बिस्लामा');
INSERT INTO `country` (`id`, `name`) VALUES ('bh', 'बिहारी');
INSERT INTO `country` (`id`, `name`) VALUES ('bua', 'बुरियात');
INSERT INTO `country` (`id`, `name`) VALUES ('bej', 'बेजा');
INSERT INTO `country` (`id`, `name`) VALUES ('bem', 'बेम्बा');
INSERT INTO `country` (`id`, `name`) VALUES ('be', 'बैलोरूशियन्');
INSERT INTO `country` (`id`, `name`) VALUES ('bs', 'बोस्नियाई');
INSERT INTO `country` (`id`, `name`) VALUES ('bra', 'ब्रज');
INSERT INTO `country` (`id`, `name`) VALUES ('br', 'ब्रेटन');
INSERT INTO `country` (`id`, `name`) VALUES ('byn', 'ब्लिन');
INSERT INTO `country` (`id`, `name`) VALUES ('zbl', 'ब्लिसिम्बॉल्स');
INSERT INTO `country` (`id`, `name`) VALUES ('inc', 'भारतीय भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('bho', 'भोजपुरी');
INSERT INTO `country` (`id`, `name`) VALUES ('mn', 'मंगोलीयाई');
INSERT INTO `country` (`id`, `name`) VALUES ('mdr', 'मंधार');
INSERT INTO `country` (`id`, `name`) VALUES ('mak', 'मकासर');
INSERT INTO `country` (`id`, `name`) VALUES ('mag', 'मगाही');
INSERT INTO `country` (`id`, `name`) VALUES ('mni', 'मणिपूरी');
INSERT INTO `country` (`id`, `name`) VALUES ('cai', 'मध्य अमेरिकी इंडियन भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('dum', 'मध्य पुर्तगाली');
INSERT INTO `country` (`id`, `name`) VALUES ('gmh', 'मध्यकालीन हाइ जर्मन');
INSERT INTO `country` (`id`, `name`) VALUES ('mno', 'मनोबो भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('mnc', 'मन्चु');
INSERT INTO `country` (`id`, `name`) VALUES ('man', 'मन्डिन्गो');
INSERT INTO `country` (`id`, `name`) VALUES ('mr', 'मराठी');
INSERT INTO `country` (`id`, `name`) VALUES ('ms', 'मलय');
INSERT INTO `country` (`id`, `name`) VALUES ('ml', 'मलयालम');
INSERT INTO `country` (`id`, `name`) VALUES ('mas', 'मसाई');
INSERT INTO `country` (`id`, `name`) VALUES ('mad', 'मादुरीस');
INSERT INTO `country` (`id`, `name`) VALUES ('myn', 'माया भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('mwr', 'मारवाड़ी');
INSERT INTO `country` (`id`, `name`) VALUES ('chm', 'मारी');
INSERT INTO `country` (`id`, `name`) VALUES ('mh', 'मार्शलीज़');
INSERT INTO `country` (`id`, `name`) VALUES ('mt', 'मालटिस्');
INSERT INTO `country` (`id`, `name`) VALUES ('mg', 'मालागासी');
INSERT INTO `country` (`id`, `name`) VALUES ('mic', 'मिकमैक');
INSERT INTO `country` (`id`, `name`) VALUES ('enm', 'मिडिल अंग्रजी');
INSERT INTO `country` (`id`, `name`) VALUES ('mga', 'मिडिल आइरिश');
INSERT INTO `country` (`id`, `name`) VALUES ('frm', 'मिडिल फ्रेंच');
INSERT INTO `country` (`id`, `name`) VALUES ('min', 'मिनांग्काबाउ');
INSERT INTO `country` (`id`, `name`) VALUES ('mwl', 'मिरांडी');
INSERT INTO `country` (`id`, `name`) VALUES ('mun', 'मुन्डा भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('mi', 'मेओरी');
INSERT INTO `country` (`id`, `name`) VALUES ('men', 'मेन्डे');
INSERT INTO `country` (`id`, `name`) VALUES ('gv', 'मैंक्स');
INSERT INTO `country` (`id`, `name`) VALUES ('mai', 'मैथिली');
INSERT INTO `country` (`id`, `name`) VALUES ('mk', 'मैसेडोनियन्');
INSERT INTO `country` (`id`, `name`) VALUES ('mkh', 'मॉन-ख्मेर भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('lol', 'मोंगो');
INSERT INTO `country` (`id`, `name`) VALUES ('mdf', 'मोक्ष');
INSERT INTO `country` (`id`, `name`) VALUES ('mo', 'मोलडावियन्');
INSERT INTO `country` (`id`, `name`) VALUES ('mos', 'मोस्सी');
INSERT INTO `country` (`id`, `name`) VALUES ('moh', 'मोहौक');
INSERT INTO `country` (`id`, `name`) VALUES ('yao', 'याओ');
INSERT INTO `country` (`id`, `name`) VALUES ('sah', 'याकूत');
INSERT INTO `country` (`id`, `name`) VALUES ('yap', 'यापीस');
INSERT INTO `country` (`id`, `name`) VALUES ('uga', 'युगैरिटिक');
INSERT INTO `country` (`id`, `name`) VALUES ('uk', 'यूक्रेनी');
INSERT INTO `country` (`id`, `name`) VALUES ('ypk', 'यूपिक भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('yi', 'येहुदी');
INSERT INTO `country` (`id`, `name`) VALUES ('yo', 'योरूबा');
INSERT INTO `country` (`id`, `name`) VALUES ('rm', 'रहेय्टो-रोमान्स');
INSERT INTO `country` (`id`, `name`) VALUES ('raj', 'राजस्थानी');
INSERT INTO `country` (`id`, `name`) VALUES ('rap', 'रापानुई');
INSERT INTO `country` (`id`, `name`) VALUES ('rar', 'रारोतोंगन');
INSERT INTO `country` (`id`, `name`) VALUES ('rn', 'रुन्दी');
INSERT INTO `country` (`id`, `name`) VALUES ('root', 'रूट');
INSERT INTO `country` (`id`, `name`) VALUES ('ru', 'रूसी');
INSERT INTO `country` (`id`, `name`) VALUES ('roa', 'रोमांस भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('ro', 'रोमानियाई');
INSERT INTO `country` (`id`, `name`) VALUES ('rom', 'रोमानी');
INSERT INTO `country` (`id`, `name`) VALUES ('lb', 'लक्ष्ज़ेमबर्गिश');
INSERT INTO `country` (`id`, `name`) VALUES ('lo', 'लाओथीयन्');
INSERT INTO `country` (`id`, `name`) VALUES ('lv', 'लातवी');
INSERT INTO `country` (`id`, `name`) VALUES ('lad', 'लादीनो');
INSERT INTO `country` (`id`, `name`) VALUES ('lam', 'लाम्बा');
INSERT INTO `country` (`id`, `name`) VALUES ('lah', 'लाह्न्डा');
INSERT INTO `country` (`id`, `name`) VALUES ('ln', 'लिंगाला');
INSERT INTO `country` (`id`, `name`) VALUES ('li', 'लिंबर्गिश');
INSERT INTO `country` (`id`, `name`) VALUES ('lt', 'लिथुनियन्');
INSERT INTO `country` (`id`, `name`) VALUES ('lui', 'लुइसेनो');
INSERT INTO `country` (`id`, `name`) VALUES ('lun', 'लुन्डा');
INSERT INTO `country` (`id`, `name`) VALUES ('lus', 'लुशाई');
INSERT INTO `country` (`id`, `name`) VALUES ('lez', 'लेज़्घीयन');
INSERT INTO `country` (`id`, `name`) VALUES ('es_419', 'लेटिन अमेरिकी स्पेनिश');
INSERT INTO `country` (`id`, `name`) VALUES ('la', 'लैटीन');
INSERT INTO `country` (`id`, `name`) VALUES ('loz', 'लोज़ी');
INSERT INTO `country` (`id`, `name`) VALUES ('jbo', 'लोज्बान');
INSERT INTO `country` (`id`, `name`) VALUES ('luo', 'ल्युओ');
INSERT INTO `country` (`id`, `name`) VALUES ('smj', 'ल्युल सामी');
INSERT INTO `country` (`id`, `name`) VALUES ('lu', 'ल्यूबा-कटांगा');
INSERT INTO `country` (`id`, `name`) VALUES ('lua', 'ल्यूबा-लुलुआ');
INSERT INTO `country` (`id`, `name`) VALUES ('wal', 'वलामो');
INSERT INTO `country` (`id`, `name`) VALUES ('vai', 'वाई');
INSERT INTO `country` (`id`, `name`) VALUES ('wak', 'वाकाशन भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('war', 'वारै');
INSERT INTO `country` (`id`, `name`) VALUES ('wa', 'वाल्लून');
INSERT INTO `country` (`id`, `name`) VALUES ('was', 'वाशो');
INSERT INTO `country` (`id`, `name`) VALUES ('vi', 'वियेतनामी');
INSERT INTO `country` (`id`, `name`) VALUES ('mis', 'विविध भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('mul', 'विविध भाषाएँ');
INSERT INTO `country` (`id`, `name`) VALUES ('ve', 'वेन्दा');
INSERT INTO `country` (`id`, `name`) VALUES ('cy', 'वेल्श');
INSERT INTO `country` (`id`, `name`) VALUES ('vot', 'वॉटिक');
INSERT INTO `country` (`id`, `name`) VALUES ('vo', 'वोलापुक');
INSERT INTO `country` (`id`, `name`) VALUES ('wo', 'वोलोफ');
INSERT INTO `country` (`id`, `name`) VALUES ('si', 'शिंघालीस्');
INSERT INTO `country` (`id`, `name`) VALUES ('chp', 'शिपेव्यान');
INSERT INTO `country` (`id`, `name`) VALUES ('chy', 'शेयेन्न');
INSERT INTO `country` (`id`, `name`) VALUES ('chr', 'शेरूकी');
INSERT INTO `country` (`id`, `name`) VALUES ('shn', 'शैन');
INSERT INTO `country` (`id`, `name`) VALUES ('cmc', 'शैमिक भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('xh', 'षोसा');
INSERT INTO `country` (`id`, `name`) VALUES ('sat', 'संताली');
INSERT INTO `country` (`id`, `name`) VALUES ('sa', 'संस्कृत');
INSERT INTO `country` (`id`, `name`) VALUES ('sad', 'सन्डावे');
INSERT INTO `country` (`id`, `name`) VALUES ('sr', 'सर्बियन्');
INSERT INTO `country` (`id`, `name`) VALUES ('sal', 'सलीशन भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('sgn', 'सांकेतिक भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('sg', 'सांगो');
INSERT INTO `country` (`id`, `name`) VALUES ('smi', 'सामी भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('sam', 'सामैरिटन अरैमिक');
INSERT INTO `country` (`id`, `name`) VALUES ('sm', 'सामोन');
INSERT INTO `country` (`id`, `name`) VALUES ('sc', 'सार्दिनियन');
INSERT INTO `country` (`id`, `name`) VALUES ('sas', 'सासाक');
INSERT INTO `country` (`id`, `name`) VALUES ('sio', 'सिउआन भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('bla', 'सिक्सिका');
INSERT INTO `country` (`id`, `name`) VALUES ('ii', 'सिचुआन यी');
INSERT INTO `country` (`id`, `name`) VALUES ('sid', 'सिदामो');
INSERT INTO `country` (`id`, `name`) VALUES ('sd', 'सिन्धी');
INSERT INTO `country` (`id`, `name`) VALUES ('ceb', 'सिबुआनो');
INSERT INTO `country` (`id`, `name`) VALUES ('syr', 'सिरिएक');
INSERT INTO `country` (`id`, `name`) VALUES ('scn', 'सिसिलियन');
INSERT INTO `country` (`id`, `name`) VALUES ('su', 'सुंडानी');
INSERT INTO `country` (`id`, `name`) VALUES ('suk', 'सुकुमा');
INSERT INTO `country` (`id`, `name`) VALUES ('sux', 'सुमेरियन');
INSERT INTO `country` (`id`, `name`) VALUES ('sus', 'सुसु');
INSERT INTO `country` (`id`, `name`) VALUES ('tn', 'सेत्स्वाना');
INSERT INTO `country` (`id`, `name`) VALUES ('sem', 'सेमिटिक भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('srr', 'सेरेर');
INSERT INTO `country` (`id`, `name`) VALUES ('sh', 'सेर्बो-क्रोएशन्');
INSERT INTO `country` (`id`, `name`) VALUES ('sel', 'सेल्कप');
INSERT INTO `country` (`id`, `name`) VALUES ('st', 'सेसोथो');
INSERT INTO `country` (`id`, `name`) VALUES ('wen', 'सॉर्बियन भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('ts', 'सोंगा');
INSERT INTO `country` (`id`, `name`) VALUES ('sog', 'सोग्डिएन');
INSERT INTO `country` (`id`, `name`) VALUES ('sn', 'सोणा');
INSERT INTO `country` (`id`, `name`) VALUES ('snk', 'सोनिन्के');
INSERT INTO `country` (`id`, `name`) VALUES ('son', 'सोन्घाई');
INSERT INTO `country` (`id`, `name`) VALUES ('so', 'सोमाली');
INSERT INTO `country` (`id`, `name`) VALUES ('gd', 'स्काट्स् गायेलिक्');
INSERT INTO `country` (`id`, `name`) VALUES ('sco', 'स्कॉट्स');
INSERT INTO `country` (`id`, `name`) VALUES ('sms', 'स्कोल्ट सामी');
INSERT INTO `country` (`id`, `name`) VALUES ('es', 'स्पेनिश');
INSERT INTO `country` (`id`, `name`) VALUES ('srn', 'स्रानान टॉन्गो');
INSERT INTO `country` (`id`, `name`) VALUES ('den', 'स्लेव');
INSERT INTO `country` (`id`, `name`) VALUES ('sk', 'स्लोवाक्');
INSERT INTO `country` (`id`, `name`) VALUES ('sla', 'स्लोवियाई भाषा');
INSERT INTO `country` (`id`, `name`) VALUES ('sl', 'स्लोवेनियन्');
INSERT INTO `country` (`id`, `name`) VALUES ('ss', 'स्वाती');
INSERT INTO `country` (`id`, `name`) VALUES ('sw', 'स्वाहिली');
INSERT INTO `country` (`id`, `name`) VALUES ('sv', 'स्विडिश');
INSERT INTO `country` (`id`, `name`) VALUES ('gsw', 'स्विस जर्मन');
INSERT INTO `country` (`id`, `name`) VALUES ('hu', 'हंगेरी');
INSERT INTO `country` (`id`, `name`) VALUES ('hz', 'हरैरो');
INSERT INTO `country` (`id`, `name`) VALUES ('haw', 'हावाइयन');
INSERT INTO `country` (`id`, `name`) VALUES ('hit', 'हिताइत');
INSERT INTO `country` (`id`, `name`) VALUES ('hi', 'हिन्दी');
INSERT INTO `country` (`id`, `name`) VALUES ('him', 'हिमाचली');
INSERT INTO `country` (`id`, `name`) VALUES ('ho', 'हिरी मोटू');
INSERT INTO `country` (`id`, `name`) VALUES ('hil', 'हिलिगेनन');
INSERT INTO `country` (`id`, `name`) VALUES ('he', 'हीब्रू');
INSERT INTO `country` (`id`, `name`) VALUES ('hup', 'हूपा');
INSERT INTO `country` (`id`, `name`) VALUES ('hai', 'हैडा');
INSERT INTO `country` (`id`, `name`) VALUES ('ht', 'हैतीयन');
INSERT INTO `country` (`id`, `name`) VALUES ('ha', 'होउसा');
INSERT INTO `country` (`id`, `name`) VALUES ('hmn', 'ह्मॉंग');
