CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('ab', 'Абказијски');
INSERT INTO `country` (`id`, `name`) VALUES ('awa', 'Авадхи');
INSERT INTO `country` (`id`, `name`) VALUES ('av', 'Аварски');
INSERT INTO `country` (`id`, `name`) VALUES ('ae', 'Авестански');
INSERT INTO `country` (`id`, `name`) VALUES ('ada', 'Адангмејски');
INSERT INTO `country` (`id`, `name`) VALUES ('ady', 'Адигејски');
INSERT INTO `country` (`id`, `name`) VALUES ('az', 'Азербејџански');
INSERT INTO `country` (`id`, `name`) VALUES ('ain', 'Аину');
INSERT INTO `country` (`id`, `name`) VALUES ('ay', 'ајмара');
INSERT INTO `country` (`id`, `name`) VALUES ('akk', 'Акадијски');
INSERT INTO `country` (`id`, `name`) VALUES ('ak', 'Акан');
INSERT INTO `country` (`id`, `name`) VALUES ('ach', 'Аколи');
INSERT INTO `country` (`id`, `name`) VALUES ('sq', 'Албански');
INSERT INTO `country` (`id`, `name`) VALUES ('alg', 'Алгонквијански језик');
INSERT INTO `country` (`id`, `name`) VALUES ('tut', 'Алтаички језик');
INSERT INTO `country` (`id`, `name`) VALUES ('ale', 'Аљут');
INSERT INTO `country` (`id`, `name`) VALUES ('am', 'Амхарски');
INSERT INTO `country` (`id`, `name`) VALUES ('anp', 'Ангика');
INSERT INTO `country` (`id`, `name`) VALUES ('apa', 'Апачки језик');
INSERT INTO `country` (`id`, `name`) VALUES ('arw', 'Аравак');
INSERT INTO `country` (`id`, `name`) VALUES ('an', 'Арагонежански');
INSERT INTO `country` (`id`, `name`) VALUES ('arp', 'Арапахо');
INSERT INTO `country` (`id`, `name`) VALUES ('ar', 'Арапски');
INSERT INTO `country` (`id`, `name`) VALUES ('arc', 'Армајски');
INSERT INTO `country` (`id`, `name`) VALUES ('arn', 'Ароканијски');
INSERT INTO `country` (`id`, `name`) VALUES ('rup', 'Ароманијски');
INSERT INTO `country` (`id`, `name`) VALUES ('as', 'Асемијски');
INSERT INTO `country` (`id`, `name`) VALUES ('ast', 'Астуријски');
INSERT INTO `country` (`id`, `name`) VALUES ('ath', 'Атапаскан');
INSERT INTO `country` (`id`, `name`) VALUES ('cch', 'Атсамски');
INSERT INTO `country` (`id`, `name`) VALUES ('en_AU', 'Аустралијски енглески');
INSERT INTO `country` (`id`, `name`) VALUES ('aus', 'Аустралијски језик');
INSERT INTO `country` (`id`, `name`) VALUES ('de_AT', 'Аустријски немачки');
INSERT INTO `country` (`id`, `name`) VALUES ('map', 'Аустронежански');
INSERT INTO `country` (`id`, `name`) VALUES ('aa', 'Афарски');
INSERT INTO `country` (`id`, `name`) VALUES ('af', 'Африканерски');
INSERT INTO `country` (`id`, `name`) VALUES ('afh', 'Африхили');
INSERT INTO `country` (`id`, `name`) VALUES ('afa', 'Афро-азијатски');
INSERT INTO `country` (`id`, `name`) VALUES ('ace', 'Ачинески');
INSERT INTO `country` (`id`, `name`) VALUES ('ban', 'Балинезијски');
INSERT INTO `country` (`id`, `name`) VALUES ('bat', 'Балтички језик');
INSERT INTO `country` (`id`, `name`) VALUES ('bal', 'Балучи');
INSERT INTO `country` (`id`, `name`) VALUES ('bm', 'Бамбара');
INSERT INTO `country` (`id`, `name`) VALUES ('bai', 'Бамилеке');
INSERT INTO `country` (`id`, `name`) VALUES ('bad', 'Банда');
INSERT INTO `country` (`id`, `name`) VALUES ('bnt', 'Банту');
INSERT INTO `country` (`id`, `name`) VALUES ('bas', 'Баса');
INSERT INTO `country` (`id`, `name`) VALUES ('eu', 'Баскијски');
INSERT INTO `country` (`id`, `name`) VALUES ('btk', 'Батак');
INSERT INTO `country` (`id`, `name`) VALUES ('ba', 'Башкир');
INSERT INTO `country` (`id`, `name`) VALUES ('zxx', 'Без лингвистичког садржаја');
INSERT INTO `country` (`id`, `name`) VALUES ('bej', 'Беја');
INSERT INTO `country` (`id`, `name`) VALUES ('be', 'Белоруски');
INSERT INTO `country` (`id`, `name`) VALUES ('bem', 'Бемба');
INSERT INTO `country` (`id`, `name`) VALUES ('bn', 'Бенгласки');
INSERT INTO `country` (`id`, `name`) VALUES ('ber', 'Бербер');
INSERT INTO `country` (`id`, `name`) VALUES ('bik', 'Бикол');
INSERT INTO `country` (`id`, `name`) VALUES ('bin', 'Бини');
INSERT INTO `country` (`id`, `name`) VALUES ('bi', 'Бислама');
INSERT INTO `country` (`id`, `name`) VALUES ('bh', 'Бихарски');
INSERT INTO `country` (`id`, `name`) VALUES ('byn', 'Блин');
INSERT INTO `country` (`id`, `name`) VALUES ('zbl', 'Блисимболи');
INSERT INTO `country` (`id`, `name`) VALUES ('bho', 'Бојпури');
INSERT INTO `country` (`id`, `name`) VALUES ('bs', 'Босански');
INSERT INTO `country` (`id`, `name`) VALUES ('pt_BR', 'Бразилски португалски');
INSERT INTO `country` (`id`, `name`) VALUES ('bra', 'Брај');
INSERT INTO `country` (`id`, `name`) VALUES ('br', 'Бретонски');
INSERT INTO `country` (`id`, `name`) VALUES ('en_GB', 'Британски енглески');
INSERT INTO `country` (`id`, `name`) VALUES ('bg', 'Бугарски');
INSERT INTO `country` (`id`, `name`) VALUES ('bug', 'Бугинежански');
INSERT INTO `country` (`id`, `name`) VALUES ('bua', 'Буриат');
INSERT INTO `country` (`id`, `name`) VALUES ('my', 'Бурмански');
INSERT INTO `country` (`id`, `name`) VALUES ('vai', 'Ваи');
INSERT INTO `country` (`id`, `name`) VALUES ('wak', 'Вакашански језик');
INSERT INTO `country` (`id`, `name`) VALUES ('wal', 'Валамо');
INSERT INTO `country` (`id`, `name`) VALUES ('wa', 'Валун');
INSERT INTO `country` (`id`, `name`) VALUES ('war', 'Варај');
INSERT INTO `country` (`id`, `name`) VALUES ('was', 'Вашо');
INSERT INTO `country` (`id`, `name`) VALUES ('cy', 'Велшки');
INSERT INTO `country` (`id`, `name`) VALUES ('ve', 'Венда');
INSERT INTO `country` (`id`, `name`) VALUES ('art', 'Вештачки');
INSERT INTO `country` (`id`, `name`) VALUES ('vi', 'Вијетнамски');
INSERT INTO `country` (`id`, `name`) VALUES ('vo', 'Волапук');
INSERT INTO `country` (`id`, `name`) VALUES ('wo', 'Волоф');
INSERT INTO `country` (`id`, `name`) VALUES ('vot', 'Вотски');
INSERT INTO `country` (`id`, `name`) VALUES ('gaa', 'Га');
INSERT INTO `country` (`id`, `name`) VALUES ('gay', 'Гајо');
INSERT INTO `country` (`id`, `name`) VALUES ('gl', 'Галски');
INSERT INTO `country` (`id`, `name`) VALUES ('lg', 'Ганда');
INSERT INTO `country` (`id`, `name`) VALUES ('gba', 'Гбаја');
INSERT INTO `country` (`id`, `name`) VALUES ('gn', 'Гварани');
INSERT INTO `country` (`id`, `name`) VALUES ('gwi', 'Гвич\'ин');
INSERT INTO `country` (`id`, `name`) VALUES ('gem', 'Германски језик');
INSERT INTO `country` (`id`, `name`) VALUES ('gil', 'Гилбертшки');
INSERT INTO `country` (`id`, `name`) VALUES ('gon', 'Гонди');
INSERT INTO `country` (`id`, `name`) VALUES ('hsb', 'Горњи сорбијски');
INSERT INTO `country` (`id`, `name`) VALUES ('gor', 'Горонтало');
INSERT INTO `country` (`id`, `name`) VALUES ('got', 'Готски');
INSERT INTO `country` (`id`, `name`) VALUES ('grb', 'Гребо');
INSERT INTO `country` (`id`, `name`) VALUES ('ka', 'Грузијски');
INSERT INTO `country` (`id`, `name`) VALUES ('el', 'Грчки');
INSERT INTO `country` (`id`, `name`) VALUES ('gu', 'Гуџарати');
INSERT INTO `country` (`id`, `name`) VALUES ('day', 'Дајашки');
INSERT INTO `country` (`id`, `name`) VALUES ('dak', 'Дакота');
INSERT INTO `country` (`id`, `name`) VALUES ('da', 'Дански');
INSERT INTO `country` (`id`, `name`) VALUES ('dra', 'Дарвидијски језик');
INSERT INTO `country` (`id`, `name`) VALUES ('dar', 'Даргва');
INSERT INTO `country` (`id`, `name`) VALUES ('del', 'Делавер');
INSERT INTO `country` (`id`, `name`) VALUES ('dv', 'Дивехијски');
INSERT INTO `country` (`id`, `name`) VALUES ('din', 'Динка');
INSERT INTO `country` (`id`, `name`) VALUES ('doi', 'Догри');
INSERT INTO `country` (`id`, `name`) VALUES ('dgr', 'Догриб');
INSERT INTO `country` (`id`, `name`) VALUES ('dua', 'Дуала');
INSERT INTO `country` (`id`, `name`) VALUES ('kaj', 'Ђу');
INSERT INTO `country` (`id`, `name`) VALUES ('dyu', 'Ђула');
INSERT INTO `country` (`id`, `name`) VALUES ('ee', 'Еве');
INSERT INTO `country` (`id`, `name`) VALUES ('ewo', 'Евондо');
INSERT INTO `country` (`id`, `name`) VALUES ('eka', 'Екајук');
INSERT INTO `country` (`id`, `name`) VALUES ('elx', 'Еламитски');
INSERT INTO `country` (`id`, `name`) VALUES ('en', 'Енглески');
INSERT INTO `country` (`id`, `name`) VALUES ('myv', 'Ерзија');
INSERT INTO `country` (`id`, `name`) VALUES ('eo', 'Есперанто');
INSERT INTO `country` (`id`, `name`) VALUES ('et', 'Естонски');
INSERT INTO `country` (`id`, `name`) VALUES ('efi', 'Ефикски');
INSERT INTO `country` (`id`, `name`) VALUES ('za', 'Жуанг');
INSERT INTO `country` (`id`, `name`) VALUES ('zza', 'Заза');
INSERT INTO `country` (`id`, `name`) VALUES ('znd', 'Занде');
INSERT INTO `country` (`id`, `name`) VALUES ('zap', 'Запотечки');
INSERT INTO `country` (`id`, `name`) VALUES ('zen', 'Зенага');
INSERT INTO `country` (`id`, `name`) VALUES ('sgn', 'Знаковни језик');
INSERT INTO `country` (`id`, `name`) VALUES ('zu', 'Зулу');
INSERT INTO `country` (`id`, `name`) VALUES ('zun', 'Зуни');
INSERT INTO `country` (`id`, `name`) VALUES ('iba', 'Ибан');
INSERT INTO `country` (`id`, `name`) VALUES ('pt_PT', 'Иберијски португалски');
INSERT INTO `country` (`id`, `name`) VALUES ('es_ES', 'Иберијски шпански');
INSERT INTO `country` (`id`, `name`) VALUES ('ig', 'Игбо');
INSERT INTO `country` (`id`, `name`) VALUES ('io', 'Идо');
INSERT INTO `country` (`id`, `name`) VALUES ('ijo', 'Ијо');
INSERT INTO `country` (`id`, `name`) VALUES ('ilo', 'Илоко');
INSERT INTO `country` (`id`, `name`) VALUES ('smn', 'Инари сами');
INSERT INTO `country` (`id`, `name`) VALUES ('inh', 'Ингвишки');
INSERT INTO `country` (`id`, `name`) VALUES ('inc', 'Индик');
INSERT INTO `country` (`id`, `name`) VALUES ('ine', 'Индо-европски језик');
INSERT INTO `country` (`id`, `name`) VALUES ('id', 'Индонежански');
INSERT INTO `country` (`id`, `name`) VALUES ('ia', 'Интерлингва');
INSERT INTO `country` (`id`, `name`) VALUES ('iu', 'Инуктитут');
INSERT INTO `country` (`id`, `name`) VALUES ('ira', 'Ирански језик');
INSERT INTO `country` (`id`, `name`) VALUES ('iro', 'Ироквојански');
INSERT INTO `country` (`id`, `name`) VALUES ('ga', 'Ирски');
INSERT INTO `country` (`id`, `name`) VALUES ('is', 'Исландски');
INSERT INTO `country` (`id`, `name`) VALUES ('frs', 'Источни фризијски');
INSERT INTO `country` (`id`, `name`) VALUES ('it', 'Италијански');
INSERT INTO `country` (`id`, `name`) VALUES ('jv', 'Јавански');
INSERT INTO `country` (`id`, `name`) VALUES ('sah', 'Јакут');
INSERT INTO `country` (`id`, `name`) VALUES ('yao', 'Јао');
INSERT INTO `country` (`id`, `name`) VALUES ('ja', 'Јапански');
INSERT INTO `country` (`id`, `name`) VALUES ('yap', 'Јапешки');
INSERT INTO `country` (`id`, `name`) VALUES ('sai', 'Језик јужноамеричких Индијанаца');
INSERT INTO `country` (`id`, `name`) VALUES ('nai', 'Језик северноамеричких Индијанаца');
INSERT INTO `country` (`id`, `name`) VALUES ('hy', 'Јерменски');
INSERT INTO `country` (`id`, `name`) VALUES ('yi', 'Јидиш');
INSERT INTO `country` (`id`, `name`) VALUES ('yo', 'Јоруба');
INSERT INTO `country` (`id`, `name`) VALUES ('jrb', 'Јудео-арапски');
INSERT INTO `country` (`id`, `name`) VALUES ('jpr', 'Јудео-персијски');
INSERT INTO `country` (`id`, `name`) VALUES ('alt', 'Јужни алтаи');
INSERT INTO `country` (`id`, `name`) VALUES ('nr', 'Јужни ндебеле');
INSERT INTO `country` (`id`, `name`) VALUES ('sma', 'Јужни сами');
INSERT INTO `country` (`id`, `name`) VALUES ('ypk', 'Јупик');
INSERT INTO `country` (`id`, `name`) VALUES ('kbd', 'Кабардијски');
INSERT INTO `country` (`id`, `name`) VALUES ('kab', 'Кабиле');
INSERT INTO `country` (`id`, `name`) VALUES ('kaw', 'Кави');
INSERT INTO `country` (`id`, `name`) VALUES ('cau', 'Кавкаски');
INSERT INTO `country` (`id`, `name`) VALUES ('cad', 'Кадо');
INSERT INTO `country` (`id`, `name`) VALUES ('kl', 'Калалисут');
INSERT INTO `country` (`id`, `name`) VALUES ('xal', 'Калмик');
INSERT INTO `country` (`id`, `name`) VALUES ('kam', 'Камба');
INSERT INTO `country` (`id`, `name`) VALUES ('kn', 'Канада');
INSERT INTO `country` (`id`, `name`) VALUES ('en_CA', 'Канадски енглески');
INSERT INTO `country` (`id`, `name`) VALUES ('fr_CA', 'Канадски француски');
INSERT INTO `country` (`id`, `name`) VALUES ('yue', 'Кантонски');
INSERT INTO `country` (`id`, `name`) VALUES ('kr', 'Канури');
INSERT INTO `country` (`id`, `name`) VALUES ('kaa', 'Кара-калпашки');
INSERT INTO `country` (`id`, `name`) VALUES ('krc', 'Карачај-балкар');
INSERT INTO `country` (`id`, `name`) VALUES ('krl', 'Карелијски');
INSERT INTO `country` (`id`, `name`) VALUES ('kar', 'Каренски');
INSERT INTO `country` (`id`, `name`) VALUES ('car', 'Карипски');
INSERT INTO `country` (`id`, `name`) VALUES ('kha', 'Каси');
INSERT INTO `country` (`id`, `name`) VALUES ('ca', 'Каталонски');
INSERT INTO `country` (`id`, `name`) VALUES ('kac', 'Качин');
INSERT INTO `country` (`id`, `name`) VALUES ('ks', 'Кашмирски');
INSERT INTO `country` (`id`, `name`) VALUES ('csb', 'Кашубијански');
INSERT INTO `country` (`id`, `name`) VALUES ('qu', 'Квенча');
INSERT INTO `country` (`id`, `name`) VALUES ('cel', 'Келтски');
INSERT INTO `country` (`id`, `name`) VALUES ('ki', 'Кикују');
INSERT INTO `country` (`id`, `name`) VALUES ('kmb', 'Кимбунду');
INSERT INTO `country` (`id`, `name`) VALUES ('zh', 'Кинески');
INSERT INTO `country` (`id`, `name`) VALUES ('zh_Hans', 'Кинески (поједностављен)');
INSERT INTO `country` (`id`, `name`) VALUES ('zh_Hant', 'Кинески (традиционални)');
INSERT INTO `country` (`id`, `name`) VALUES ('rw', 'Кинјаруанда');
INSERT INTO `country` (`id`, `name`) VALUES ('ky', 'Киргиски');
INSERT INTO `country` (`id`, `name`) VALUES ('nwc', 'Класични невари');
INSERT INTO `country` (`id`, `name`) VALUES ('syc', 'Класични сиријски');
INSERT INTO `country` (`id`, `name`) VALUES ('tlh', 'Клингонски');
INSERT INTO `country` (`id`, `name`) VALUES ('km', 'Кмерски');
INSERT INTO `country` (`id`, `name`) VALUES ('kk', 'Козачки');
INSERT INTO `country` (`id`, `name`) VALUES ('khi', 'Коисански језик');
INSERT INTO `country` (`id`, `name`) VALUES ('kv', 'Коми');
INSERT INTO `country` (`id`, `name`) VALUES ('swb', 'Коморски');
INSERT INTO `country` (`id`, `name`) VALUES ('kg', 'Конго');
INSERT INTO `country` (`id`, `name`) VALUES ('kok', 'Конкани');
INSERT INTO `country` (`id`, `name`) VALUES ('cop', 'Коптски');
INSERT INTO `country` (`id`, `name`) VALUES ('ko', 'Корејски');
INSERT INTO `country` (`id`, `name`) VALUES ('co', 'Корзикански');
INSERT INTO `country` (`id`, `name`) VALUES ('kw', 'Корнишки');
INSERT INTO `country` (`id`, `name`) VALUES ('kfo', 'Коро');
INSERT INTO `country` (`id`, `name`) VALUES ('kos', 'Косреански');
INSERT INTO `country` (`id`, `name`) VALUES ('kho', 'Котанешки');
INSERT INTO `country` (`id`, `name`) VALUES ('kpe', 'Кпеле');
INSERT INTO `country` (`id`, `name`) VALUES ('crp', 'креолски или пиџин');
INSERT INTO `country` (`id`, `name`) VALUES ('cpp', 'Креолски или пиџин базиран на португалском');
INSERT INTO `country` (`id`, `name`) VALUES ('cpe', 'Креолски или пиџин заснован на енглеском');
INSERT INTO `country` (`id`, `name`) VALUES ('cpf', 'Креолски или пиџин заснован на француском');
INSERT INTO `country` (`id`, `name`) VALUES ('cr', 'Кри');
INSERT INTO `country` (`id`, `name`) VALUES ('crh', 'Кримеански турски');
INSERT INTO `country` (`id`, `name`) VALUES ('mus', 'Кришки');
INSERT INTO `country` (`id`, `name`) VALUES ('kro', 'Кру');
INSERT INTO `country` (`id`, `name`) VALUES ('xh', 'Ксхоса');
INSERT INTO `country` (`id`, `name`) VALUES ('kj', 'Куањама');
INSERT INTO `country` (`id`, `name`) VALUES ('kum', 'Кумик');
INSERT INTO `country` (`id`, `name`) VALUES ('ku', 'Курдски');
INSERT INTO `country` (`id`, `name`) VALUES ('kru', 'Курукх');
INSERT INTO `country` (`id`, `name`) VALUES ('kut', 'Кутенаи');
INSERT INTO `country` (`id`, `name`) VALUES ('cus', 'Кушитички језик');
INSERT INTO `country` (`id`, `name`) VALUES ('lad', 'Ладино');
INSERT INTO `country` (`id`, `name`) VALUES ('lam', 'Ламба');
INSERT INTO `country` (`id`, `name`) VALUES ('lah', 'Ланда');
INSERT INTO `country` (`id`, `name`) VALUES ('lo', 'Лаоски');
INSERT INTO `country` (`id`, `name`) VALUES ('es_419', 'Латино-амерички шпански');
INSERT INTO `country` (`id`, `name`) VALUES ('la', 'Латински');
INSERT INTO `country` (`id`, `name`) VALUES ('lez', 'Лезгиан');
INSERT INTO `country` (`id`, `name`) VALUES ('lv', 'Летонски');
INSERT INTO `country` (`id`, `name`) VALUES ('li', 'Лимбургиш');
INSERT INTO `country` (`id`, `name`) VALUES ('ln', 'Лингала');
INSERT INTO `country` (`id`, `name`) VALUES ('lt', 'Литвански');
INSERT INTO `country` (`id`, `name`) VALUES ('loz', 'Лози');
INSERT INTO `country` (`id`, `name`) VALUES ('jbo', 'Лојбан');
INSERT INTO `country` (`id`, `name`) VALUES ('lu', 'Луба-катанга');
INSERT INTO `country` (`id`, `name`) VALUES ('lua', 'Луба-лулуа');
INSERT INTO `country` (`id`, `name`) VALUES ('lui', 'Луисено');
INSERT INTO `country` (`id`, `name`) VALUES ('lb', 'Луксембуршки');
INSERT INTO `country` (`id`, `name`) VALUES ('smj', 'Луле сами');
INSERT INTO `country` (`id`, `name`) VALUES ('lun', 'Лунда');
INSERT INTO `country` (`id`, `name`) VALUES ('luo', 'Луо');
INSERT INTO `country` (`id`, `name`) VALUES ('lus', 'Лушаи');
INSERT INTO `country` (`id`, `name`) VALUES ('mag', 'Магахи');
INSERT INTO `country` (`id`, `name`) VALUES ('mad', 'Мадурешки');
INSERT INTO `country` (`id`, `name`) VALUES ('hu', 'Мађарски');
INSERT INTO `country` (`id`, `name`) VALUES ('mai', 'Маитили');
INSERT INTO `country` (`id`, `name`) VALUES ('myn', 'Мајански језик');
INSERT INTO `country` (`id`, `name`) VALUES ('mak', 'Макасар');
INSERT INTO `country` (`id`, `name`) VALUES ('mk', 'Македонски');
INSERT INTO `country` (`id`, `name`) VALUES ('mg', 'Малагасијски');
INSERT INTO `country` (`id`, `name`) VALUES ('ml', 'Малајалам');
INSERT INTO `country` (`id`, `name`) VALUES ('ms', 'Малајски');
INSERT INTO `country` (`id`, `name`) VALUES ('mdr', 'Мандар');
INSERT INTO `country` (`id`, `name`) VALUES ('man', 'Мандинго');
INSERT INTO `country` (`id`, `name`) VALUES ('mni', 'Манипури');
INSERT INTO `country` (`id`, `name`) VALUES ('gv', 'Манкс');
INSERT INTO `country` (`id`, `name`) VALUES ('mno', 'Манобо језик');
INSERT INTO `country` (`id`, `name`) VALUES ('mnc', 'Манчу');
INSERT INTO `country` (`id`, `name`) VALUES ('mi', 'Маорски');
INSERT INTO `country` (`id`, `name`) VALUES ('mr', 'Марати');
INSERT INTO `country` (`id`, `name`) VALUES ('mwr', 'Марвари');
INSERT INTO `country` (`id`, `name`) VALUES ('chm', 'Мари');
INSERT INTO `country` (`id`, `name`) VALUES ('mh', 'Маршалски');
INSERT INTO `country` (`id`, `name`) VALUES ('mas', 'Масаи');
INSERT INTO `country` (`id`, `name`) VALUES ('moh', 'Махавски');
INSERT INTO `country` (`id`, `name`) VALUES ('ie', 'Међујезички');
INSERT INTO `country` (`id`, `name`) VALUES ('mt', 'Мелтешки');
INSERT INTO `country` (`id`, `name`) VALUES ('men', 'Менде');
INSERT INTO `country` (`id`, `name`) VALUES ('mic', 'Микмак');
INSERT INTO `country` (`id`, `name`) VALUES ('min', 'Минангкабау');
INSERT INTO `country` (`id`, `name`) VALUES ('mwl', 'Мирандешки');
INSERT INTO `country` (`id`, `name`) VALUES ('mdf', 'Мокша');
INSERT INTO `country` (`id`, `name`) VALUES ('mo', 'Молдавски');
INSERT INTO `country` (`id`, `name`) VALUES ('mkh', 'Мон-кмерски језик');
INSERT INTO `country` (`id`, `name`) VALUES ('lol', 'Монго');
INSERT INTO `country` (`id`, `name`) VALUES ('mn', 'Монголски');
INSERT INTO `country` (`id`, `name`) VALUES ('mos', 'Моси');
INSERT INTO `country` (`id`, `name`) VALUES ('mun', 'Мунда језик');
INSERT INTO `country` (`id`, `name`) VALUES ('nqo', 'Н’ко');
INSERT INTO `country` (`id`, `name`) VALUES ('nv', 'Навахо');
INSERT INTO `country` (`id`, `name`) VALUES ('na', 'Науру');
INSERT INTO `country` (`id`, `name`) VALUES ('nah', 'Нахуатл');
INSERT INTO `country` (`id`, `name`) VALUES ('ng', 'Ндонга');
INSERT INTO `country` (`id`, `name`) VALUES ('nap', 'Неаполитански');
INSERT INTO `country` (`id`, `name`) VALUES ('new', 'Невари');
INSERT INTO `country` (`id`, `name`) VALUES ('de', 'Немачки');
INSERT INTO `country` (`id`, `name`) VALUES ('ne', 'Непалски');
INSERT INTO `country` (`id`, `name`) VALUES ('und', 'Непознат или неважећи језик');
INSERT INTO `country` (`id`, `name`) VALUES ('nzi', 'Нзима');
INSERT INTO `country` (`id`, `name`) VALUES ('nia', 'Ниас');
INSERT INTO `country` (`id`, `name`) VALUES ('nic', 'Нигер-кордофанијски језик');
INSERT INTO `country` (`id`, `name`) VALUES ('ssa', 'Нило-сахарски језик');
INSERT INTO `country` (`id`, `name`) VALUES ('nds', 'Ниски немачки');
INSERT INTO `country` (`id`, `name`) VALUES ('dsb', 'Ниски сорбијански');
INSERT INTO `country` (`id`, `name`) VALUES ('niu', 'Ниуеан');
INSERT INTO `country` (`id`, `name`) VALUES ('nog', 'Ногаи');
INSERT INTO `country` (`id`, `name`) VALUES ('no', 'Норвешки');
INSERT INTO `country` (`id`, `name`) VALUES ('nb', 'Норвешки бокмал');
INSERT INTO `country` (`id`, `name`) VALUES ('nn', 'Норвешки њорск');
INSERT INTO `country` (`id`, `name`) VALUES ('nub', 'Нубијски језик');
INSERT INTO `country` (`id`, `name`) VALUES ('nym', 'Њамвези');
INSERT INTO `country` (`id`, `name`) VALUES ('nyn', 'Њанколе');
INSERT INTO `country` (`id`, `name`) VALUES ('ny', 'Њања');
INSERT INTO `country` (`id`, `name`) VALUES ('tog', 'Њаса тонга');
INSERT INTO `country` (`id`, `name`) VALUES ('nyo', 'Њоро');
INSERT INTO `country` (`id`, `name`) VALUES ('oj', 'Ојибва');
INSERT INTO `country` (`id`, `name`) VALUES ('or', 'Оријски');
INSERT INTO `country` (`id`, `name`) VALUES ('om', 'Оромо');
INSERT INTO `country` (`id`, `name`) VALUES ('osa', 'Осаге');
INSERT INTO `country` (`id`, `name`) VALUES ('os', 'Осетски');
INSERT INTO `country` (`id`, `name`) VALUES ('oto', 'Отомански језик');
INSERT INTO `country` (`id`, `name`) VALUES ('ota', 'Отомански турски');
INSERT INTO `country` (`id`, `name`) VALUES ('pau', 'Палауански');
INSERT INTO `country` (`id`, `name`) VALUES ('pi', 'Пали');
INSERT INTO `country` (`id`, `name`) VALUES ('pam', 'Пампанга');
INSERT INTO `country` (`id`, `name`) VALUES ('pag', 'Пангасински');
INSERT INTO `country` (`id`, `name`) VALUES ('pa', 'Панџабски');
INSERT INTO `country` (`id`, `name`) VALUES ('pap', 'Папиаменто');
INSERT INTO `country` (`id`, `name`) VALUES ('paa', 'Папуански језик');
INSERT INTO `country` (`id`, `name`) VALUES ('pal', 'Пахлави');
INSERT INTO `country` (`id`, `name`) VALUES ('ps', 'Паштунски');
INSERT INTO `country` (`id`, `name`) VALUES ('fa', 'Персијски');
INSERT INTO `country` (`id`, `name`) VALUES ('pl', 'Пољски');
INSERT INTO `country` (`id`, `name`) VALUES ('pon', 'Понпејски');
INSERT INTO `country` (`id`, `name`) VALUES ('pt', 'Португалски');
INSERT INTO `country` (`id`, `name`) VALUES ('pra', 'Пракритски');
INSERT INTO `country` (`id`, `name`) VALUES ('oc', 'Провансалски');
INSERT INTO `country` (`id`, `name`) VALUES ('raj', 'Рађастани');
INSERT INTO `country` (`id`, `name`) VALUES ('mis', 'Разни језици');
INSERT INTO `country` (`id`, `name`) VALUES ('rap', 'Рапануи');
INSERT INTO `country` (`id`, `name`) VALUES ('rar', 'Раротонган');
INSERT INTO `country` (`id`, `name`) VALUES ('rm', 'Рето-Романски');
INSERT INTO `country` (`id`, `name`) VALUES ('rom', 'Романи');
INSERT INTO `country` (`id`, `name`) VALUES ('roa', 'Романски језик');
INSERT INTO `country` (`id`, `name`) VALUES ('ro', 'Румунски');
INSERT INTO `country` (`id`, `name`) VALUES ('rn', 'Рунди');
INSERT INTO `country` (`id`, `name`) VALUES ('ru', 'Руски');
INSERT INTO `country` (`id`, `name`) VALUES ('root', 'Рут');
INSERT INTO `country` (`id`, `name`) VALUES ('en_US', 'САД енглески');
INSERT INTO `country` (`id`, `name`) VALUES ('sal', 'Салишански језик');
INSERT INTO `country` (`id`, `name`) VALUES ('sam', 'Самаритански арамејски');
INSERT INTO `country` (`id`, `name`) VALUES ('smi', 'Сами језик');
INSERT INTO `country` (`id`, `name`) VALUES ('sm', 'Самоански');
INSERT INTO `country` (`id`, `name`) VALUES ('sg', 'Санго');
INSERT INTO `country` (`id`, `name`) VALUES ('sad', 'Сандаве');
INSERT INTO `country` (`id`, `name`) VALUES ('sa', 'Санскрит');
INSERT INTO `country` (`id`, `name`) VALUES ('sat', 'Сантали');
INSERT INTO `country` (`id`, `name`) VALUES ('sc', 'Сардињаски');
INSERT INTO `country` (`id`, `name`) VALUES ('sas', 'Сасак');
INSERT INTO `country` (`id`, `name`) VALUES ('ss', 'Свати');
INSERT INTO `country` (`id`, `name`) VALUES ('sw', 'Свахили');
INSERT INTO `country` (`id`, `name`) VALUES ('nd', 'Северни ндебеле');
INSERT INTO `country` (`id`, `name`) VALUES ('se', 'Северни сами');
INSERT INTO `country` (`id`, `name`) VALUES ('nso', 'Северни сото');
INSERT INTO `country` (`id`, `name`) VALUES ('frr', 'Северно-фризијски');
INSERT INTO `country` (`id`, `name`) VALUES ('sel', 'Селкап');
INSERT INTO `country` (`id`, `name`) VALUES ('sem', 'Семитски језик');
INSERT INTO `country` (`id`, `name`) VALUES ('srr', 'Серер');
INSERT INTO `country` (`id`, `name`) VALUES ('st', 'Сесото');
INSERT INTO `country` (`id`, `name`) VALUES ('sid', 'Сидамо');
INSERT INTO `country` (`id`, `name`) VALUES ('si', 'Сингалески');
INSERT INTO `country` (`id`, `name`) VALUES ('sd', 'Синди');
INSERT INTO `country` (`id`, `name`) VALUES ('sit', 'Сино-тибетански језик');
INSERT INTO `country` (`id`, `name`) VALUES ('syr', 'Сиријски');
INSERT INTO `country` (`id`, `name`) VALUES ('bla', 'Сисика');
INSERT INTO `country` (`id`, `name`) VALUES ('sio', 'Сиуански језик');
INSERT INTO `country` (`id`, `name`) VALUES ('scn', 'Сицилијански');
INSERT INTO `country` (`id`, `name`) VALUES ('ii', 'Сичуан ји');
INSERT INTO `country` (`id`, `name`) VALUES ('sms', 'Сколтски језик');
INSERT INTO `country` (`id`, `name`) VALUES ('den', 'Славски');
INSERT INTO `country` (`id`, `name`) VALUES ('sk', 'Словачки');
INSERT INTO `country` (`id`, `name`) VALUES ('sl', 'Словеначки');
INSERT INTO `country` (`id`, `name`) VALUES ('sla', 'Словенски језик');
INSERT INTO `country` (`id`, `name`) VALUES ('so', 'Сомалски');
INSERT INTO `country` (`id`, `name`) VALUES ('son', 'Сонгаи');
INSERT INTO `country` (`id`, `name`) VALUES ('snk', 'Сонинке');
INSERT INTO `country` (`id`, `name`) VALUES ('wen', 'Сорбијански језик');
INSERT INTO `country` (`id`, `name`) VALUES ('sog', 'Соџијенски');
INSERT INTO `country` (`id`, `name`) VALUES ('srn', 'Сранански тонго');
INSERT INTO `country` (`id`, `name`) VALUES ('gmh', 'Средњи високи немачки');
INSERT INTO `country` (`id`, `name`) VALUES ('enm', 'Средњи енглески');
INSERT INTO `country` (`id`, `name`) VALUES ('mga', 'Средњи ирски');
INSERT INTO `country` (`id`, `name`) VALUES ('frm', 'Средњи француски');
INSERT INTO `country` (`id`, `name`) VALUES ('dum', 'Средњи холандски');
INSERT INTO `country` (`id`, `name`) VALUES ('sr', 'Српски');
INSERT INTO `country` (`id`, `name`) VALUES ('sh', 'Српскохрватски');
INSERT INTO `country` (`id`, `name`) VALUES ('non', 'Стари норски');
INSERT INTO `country` (`id`, `name`) VALUES ('grc', 'Старогрчки');
INSERT INTO `country` (`id`, `name`) VALUES ('egy', 'Староегипатски');
INSERT INTO `country` (`id`, `name`) VALUES ('ang', 'Староенглески');
INSERT INTO `country` (`id`, `name`) VALUES ('sga', 'Староирски');
INSERT INTO `country` (`id`, `name`) VALUES ('goh', 'Старонемачки');
INSERT INTO `country` (`id`, `name`) VALUES ('peo', 'Староперсијски');
INSERT INTO `country` (`id`, `name`) VALUES ('pro', 'Старопровансалски');
INSERT INTO `country` (`id`, `name`) VALUES ('cu', 'Старословенски');
INSERT INTO `country` (`id`, `name`) VALUES ('fro', 'Старофранцуски');
INSERT INTO `country` (`id`, `name`) VALUES ('su', 'Судански');
INSERT INTO `country` (`id`, `name`) VALUES ('suk', 'Сукума');
INSERT INTO `country` (`id`, `name`) VALUES ('sux', 'Сумерски');
INSERT INTO `country` (`id`, `name`) VALUES ('sus', 'Сусу');
INSERT INTO `country` (`id`, `name`) VALUES ('fil', 'Тагалог');
INSERT INTO `country` (`id`, `name`) VALUES ('tl', 'Тагалски');
INSERT INTO `country` (`id`, `name`) VALUES ('tg', 'Тађик');
INSERT INTO `country` (`id`, `name`) VALUES ('tai', 'Таи језик');
INSERT INTO `country` (`id`, `name`) VALUES ('th', 'Тајландски');
INSERT INTO `country` (`id`, `name`) VALUES ('tmh', 'Тамашек');
INSERT INTO `country` (`id`, `name`) VALUES ('ta', 'Тамилски');
INSERT INTO `country` (`id`, `name`) VALUES ('tt', 'Татарски');
INSERT INTO `country` (`id`, `name`) VALUES ('ty', 'Тахићански');
INSERT INTO `country` (`id`, `name`) VALUES ('tw', 'Тви');
INSERT INTO `country` (`id`, `name`) VALUES ('te', 'Телугу');
INSERT INTO `country` (`id`, `name`) VALUES ('ter', 'Терено');
INSERT INTO `country` (`id`, `name`) VALUES ('tet', 'Тетум');
INSERT INTO `country` (`id`, `name`) VALUES ('bo', 'Тибетански');
INSERT INTO `country` (`id`, `name`) VALUES ('tiv', 'Тив');
INSERT INTO `country` (`id`, `name`) VALUES ('tig', 'Тигре');
INSERT INTO `country` (`id`, `name`) VALUES ('ti', 'Тигриња');
INSERT INTO `country` (`id`, `name`) VALUES ('tem', 'Тимне');
INSERT INTO `country` (`id`, `name`) VALUES ('kcg', 'Тјап');
INSERT INTO `country` (`id`, `name`) VALUES ('tli', 'Тлингит');
INSERT INTO `country` (`id`, `name`) VALUES ('tpi', 'Ток Писин');
INSERT INTO `country` (`id`, `name`) VALUES ('tkl', 'Токелау');
INSERT INTO `country` (`id`, `name`) VALUES ('to', 'Тонга');
INSERT INTO `country` (`id`, `name`) VALUES ('tn', 'Тсвана');
INSERT INTO `country` (`id`, `name`) VALUES ('tsi', 'Тсимшиан');
INSERT INTO `country` (`id`, `name`) VALUES ('ts', 'Тсонга');
INSERT INTO `country` (`id`, `name`) VALUES ('tvl', 'Тувалу');
INSERT INTO `country` (`id`, `name`) VALUES ('tyv', 'Тувинијски');
INSERT INTO `country` (`id`, `name`) VALUES ('tum', 'Тумбука');
INSERT INTO `country` (`id`, `name`) VALUES ('tup', 'Тупи језик');
INSERT INTO `country` (`id`, `name`) VALUES ('tk', 'Туркменски');
INSERT INTO `country` (`id`, `name`) VALUES ('tr', 'Турски');
INSERT INTO `country` (`id`, `name`) VALUES ('uga', 'Угаритски');
INSERT INTO `country` (`id`, `name`) VALUES ('fiu', 'Угро-фински');
INSERT INTO `country` (`id`, `name`) VALUES ('udm', 'Удмурт');
INSERT INTO `country` (`id`, `name`) VALUES ('uz', 'Узбечки');
INSERT INTO `country` (`id`, `name`) VALUES ('ug', 'Ујгурски');
INSERT INTO `country` (`id`, `name`) VALUES ('uk', 'Украјински');
INSERT INTO `country` (`id`, `name`) VALUES ('umb', 'Умбунду');
INSERT INTO `country` (`id`, `name`) VALUES ('ik', 'Унупиак');
INSERT INTO `country` (`id`, `name`) VALUES ('ur', 'Урду');
INSERT INTO `country` (`id`, `name`) VALUES ('fan', 'Фанг');
INSERT INTO `country` (`id`, `name`) VALUES ('fat', 'Фанти');
INSERT INTO `country` (`id`, `name`) VALUES ('fo', 'Фарски');
INSERT INTO `country` (`id`, `name`) VALUES ('phn', 'Феничански');
INSERT INTO `country` (`id`, `name`) VALUES ('fj', 'Фиджијски');
INSERT INTO `country` (`id`, `name`) VALUES ('phi', 'Филипински језик');
INSERT INTO `country` (`id`, `name`) VALUES ('fi', 'Фински');
INSERT INTO `country` (`id`, `name`) VALUES ('nl_BE', 'Фламански');
INSERT INTO `country` (`id`, `name`) VALUES ('fon', 'Фон');
INSERT INTO `country` (`id`, `name`) VALUES ('fr', 'Француски');
INSERT INTO `country` (`id`, `name`) VALUES ('fy', 'Фризијски');
INSERT INTO `country` (`id`, `name`) VALUES ('fur', 'Фриулијски');
INSERT INTO `country` (`id`, `name`) VALUES ('ff', 'Фулах');
INSERT INTO `country` (`id`, `name`) VALUES ('haw', 'Хавајски');
INSERT INTO `country` (`id`, `name`) VALUES ('hai', 'Хаида');
INSERT INTO `country` (`id`, `name`) VALUES ('ht', 'Хаитски');
INSERT INTO `country` (`id`, `name`) VALUES ('ha', 'Хауса');
INSERT INTO `country` (`id`, `name`) VALUES ('he', 'Хебрејски');
INSERT INTO `country` (`id`, `name`) VALUES ('hz', 'Хереро');
INSERT INTO `country` (`id`, `name`) VALUES ('hil', 'Хилигајнон');
INSERT INTO `country` (`id`, `name`) VALUES ('him', 'Химачали');
INSERT INTO `country` (`id`, `name`) VALUES ('hi', 'Хинди');
INSERT INTO `country` (`id`, `name`) VALUES ('ho', 'Хири Моту');
INSERT INTO `country` (`id`, `name`) VALUES ('hit', 'Хитите');
INSERT INTO `country` (`id`, `name`) VALUES ('hmn', 'Хмонг');
INSERT INTO `country` (`id`, `name`) VALUES ('nl', 'Холандски');
INSERT INTO `country` (`id`, `name`) VALUES ('hr', 'Хрватски');
INSERT INTO `country` (`id`, `name`) VALUES ('hup', 'Хупа');
INSERT INTO `country` (`id`, `name`) VALUES ('ceb', 'Цебуано');
INSERT INTO `country` (`id`, `name`) VALUES ('cai', 'Централно амерички Индијански језик');
INSERT INTO `country` (`id`, `name`) VALUES ('chg', 'Чагатаи');
INSERT INTO `country` (`id`, `name`) VALUES ('ch', 'Чаморо');
INSERT INTO `country` (`id`, `name`) VALUES ('cmc', 'Чамски језик');
INSERT INTO `country` (`id`, `name`) VALUES ('chy', 'Чејенски');
INSERT INTO `country` (`id`, `name`) VALUES ('chr', 'Чероки');
INSERT INTO `country` (`id`, `name`) VALUES ('ce', 'Чеченски');
INSERT INTO `country` (`id`, `name`) VALUES ('cs', 'Чешки');
INSERT INTO `country` (`id`, `name`) VALUES ('chb', 'Чибча');
INSERT INTO `country` (`id`, `name`) VALUES ('chn', 'Чинукски');
INSERT INTO `country` (`id`, `name`) VALUES ('chp', 'Чипвијански');
INSERT INTO `country` (`id`, `name`) VALUES ('cho', 'Чоктавски');
INSERT INTO `country` (`id`, `name`) VALUES ('cv', 'Чувашки');
INSERT INTO `country` (`id`, `name`) VALUES ('chk', 'Чукески');
INSERT INTO `country` (`id`, `name`) VALUES ('gez', 'Џиз');
INSERT INTO `country` (`id`, `name`) VALUES ('dz', 'Џонга');
INSERT INTO `country` (`id`, `name`) VALUES ('shn', 'Шан');
INSERT INTO `country` (`id`, `name`) VALUES ('de_CH', 'Швајцарски високи немачки');
INSERT INTO `country` (`id`, `name`) VALUES ('gsw', 'Швајцарски немачки');
INSERT INTO `country` (`id`, `name`) VALUES ('fr_CH', 'Швајцарски француски');
INSERT INTO `country` (`id`, `name`) VALUES ('sv', 'Шведски');
INSERT INTO `country` (`id`, `name`) VALUES ('sco', 'Шкотски');
INSERT INTO `country` (`id`, `name`) VALUES ('gd', 'Шкотски Галски');
INSERT INTO `country` (`id`, `name`) VALUES ('sn', 'Шона');
INSERT INTO `country` (`id`, `name`) VALUES ('es', 'Шпански');
