CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('ab', 'abhaski');
INSERT INTO [country] ([id], [name]) VALUES ('ace', 'achinese');
INSERT INTO [country] ([id], [name]) VALUES ('ach', 'acoli');
INSERT INTO [country] ([id], [name]) VALUES ('ada', 'adangme');
INSERT INTO [country] ([id], [name]) VALUES ('ady', 'adigejski');
INSERT INTO [country] ([id], [name]) VALUES ('aa', 'afarski');
INSERT INTO [country] ([id], [name]) VALUES ('afh', 'afrihili');
INSERT INTO [country] ([id], [name]) VALUES ('af', 'afrikaans');
INSERT INTO [country] ([id], [name]) VALUES ('ain', 'ainu');
INSERT INTO [country] ([id], [name]) VALUES ('ak', 'akanski');
INSERT INTO [country] ([id], [name]) VALUES ('akk', 'akkadian');
INSERT INTO [country] ([id], [name]) VALUES ('sq', 'albanski');
INSERT INTO [country] ([id], [name]) VALUES ('ale', 'aleutski');
INSERT INTO [country] ([id], [name]) VALUES ('alg', 'algonquian');
INSERT INTO [country] ([id], [name]) VALUES ('tut', 'altajski');
INSERT INTO [country] ([id], [name]) VALUES ('am', 'amharik');
INSERT INTO [country] ([id], [name]) VALUES ('anp', 'angika');
INSERT INTO [country] ([id], [name]) VALUES ('apa', 'apaški');
INSERT INTO [country] ([id], [name]) VALUES ('an', 'aragonski');
INSERT INTO [country] ([id], [name]) VALUES ('arc', 'aramejski');
INSERT INTO [country] ([id], [name]) VALUES ('arp', 'arapaho');
INSERT INTO [country] ([id], [name]) VALUES ('ar', 'arapski');
INSERT INTO [country] ([id], [name]) VALUES ('arn', 'araukanski');
INSERT INTO [country] ([id], [name]) VALUES ('arw', 'arawak');
INSERT INTO [country] ([id], [name]) VALUES ('hy', 'armenski');
INSERT INTO [country] ([id], [name]) VALUES ('rup', 'aromunski');
INSERT INTO [country] ([id], [name]) VALUES ('as', 'asamski');
INSERT INTO [country] ([id], [name]) VALUES ('ast', 'asturijski');
INSERT INTO [country] ([id], [name]) VALUES ('ath', 'athapascan');
INSERT INTO [country] ([id], [name]) VALUES ('cch', 'atsam');
INSERT INTO [country] ([id], [name]) VALUES ('aus', 'australski');
INSERT INTO [country] ([id], [name]) VALUES ('de_AT', 'austrijski njemački');
INSERT INTO [country] ([id], [name]) VALUES ('map', 'austronezijski');
INSERT INTO [country] ([id], [name]) VALUES ('av', 'avarski');
INSERT INTO [country] ([id], [name]) VALUES ('ae', 'avestan');
INSERT INTO [country] ([id], [name]) VALUES ('awa', 'awadhi');
INSERT INTO [country] ([id], [name]) VALUES ('ay', 'aymara');
INSERT INTO [country] ([id], [name]) VALUES ('az', 'azerbajdžanski');
INSERT INTO [country] ([id], [name]) VALUES ('ban', 'balinezijski');
INSERT INTO [country] ([id], [name]) VALUES ('bat', 'baltički');
INSERT INTO [country] ([id], [name]) VALUES ('bal', 'baluchi');
INSERT INTO [country] ([id], [name]) VALUES ('bm', 'bambara');
INSERT INTO [country] ([id], [name]) VALUES ('bai', 'bamileke');
INSERT INTO [country] ([id], [name]) VALUES ('bad', 'banda');
INSERT INTO [country] ([id], [name]) VALUES ('bnt', 'bantu');
INSERT INTO [country] ([id], [name]) VALUES ('bas', 'basa');
INSERT INTO [country] ([id], [name]) VALUES ('eu', 'baskijski');
INSERT INTO [country] ([id], [name]) VALUES ('ba', 'baškirski');
INSERT INTO [country] ([id], [name]) VALUES ('btk', 'batak');
INSERT INTO [country] ([id], [name]) VALUES ('bej', 'beja');
INSERT INTO [country] ([id], [name]) VALUES ('bem', 'bemba');
INSERT INTO [country] ([id], [name]) VALUES ('bn', 'bengalski');
INSERT INTO [country] ([id], [name]) VALUES ('ber', 'berberski');
INSERT INTO [country] ([id], [name]) VALUES ('zxx', 'bez jezičnog sadržaja');
INSERT INTO [country] ([id], [name]) VALUES ('bho', 'bhojpuri');
INSERT INTO [country] ([id], [name]) VALUES ('bh', 'bihari');
INSERT INTO [country] ([id], [name]) VALUES ('bik', 'bikol');
INSERT INTO [country] ([id], [name]) VALUES ('bin', 'bini');
INSERT INTO [country] ([id], [name]) VALUES ('bi', 'bislama');
INSERT INTO [country] ([id], [name]) VALUES ('be', 'bjeloruski');
INSERT INTO [country] ([id], [name]) VALUES ('byn', 'blin');
INSERT INTO [country] ([id], [name]) VALUES ('zbl', 'blissymbols');
INSERT INTO [country] ([id], [name]) VALUES ('bs', 'bosanski');
INSERT INTO [country] ([id], [name]) VALUES ('bra', 'braj');
INSERT INTO [country] ([id], [name]) VALUES ('pt_BR', 'brazilski portugalski');
INSERT INTO [country] ([id], [name]) VALUES ('br', 'bretonski');
INSERT INTO [country] ([id], [name]) VALUES ('bg', 'bugarski');
INSERT INTO [country] ([id], [name]) VALUES ('bug', 'buginski');
INSERT INTO [country] ([id], [name]) VALUES ('bua', 'buriat');
INSERT INTO [country] ([id], [name]) VALUES ('my', 'burmanski');
INSERT INTO [country] ([id], [name]) VALUES ('cad', 'caddo');
INSERT INTO [country] ([id], [name]) VALUES ('ceb', 'cebuano');
INSERT INTO [country] ([id], [name]) VALUES ('chg', 'chagatai');
INSERT INTO [country] ([id], [name]) VALUES ('cmc', 'chamic');
INSERT INTO [country] ([id], [name]) VALUES ('ch', 'chamorro');
INSERT INTO [country] ([id], [name]) VALUES ('chb', 'chibcha');
INSERT INTO [country] ([id], [name]) VALUES ('chn', 'chinook žargon');
INSERT INTO [country] ([id], [name]) VALUES ('chp', 'chipewyan');
INSERT INTO [country] ([id], [name]) VALUES ('cho', 'choctaw');
INSERT INTO [country] ([id], [name]) VALUES ('chk', 'chuukese');
INSERT INTO [country] ([id], [name]) VALUES ('cv', 'chuvash');
INSERT INTO [country] ([id], [name]) VALUES ('cr', 'cree');
INSERT INTO [country] ([id], [name]) VALUES ('mus', 'creek');
INSERT INTO [country] ([id], [name]) VALUES ('cu', 'crkvenoslavenski');
INSERT INTO [country] ([id], [name]) VALUES ('tn', 'cvana');
INSERT INTO [country] ([id], [name]) VALUES ('ce', 'čečenski');
INSERT INTO [country] ([id], [name]) VALUES ('chy', 'čejenski');
INSERT INTO [country] ([id], [name]) VALUES ('chr', 'čeroki');
INSERT INTO [country] ([id], [name]) VALUES ('cs', 'češki');
INSERT INTO [country] ([id], [name]) VALUES ('dak', 'dakota jezik');
INSERT INTO [country] ([id], [name]) VALUES ('da', 'danski');
INSERT INTO [country] ([id], [name]) VALUES ('dar', 'dargwa');
INSERT INTO [country] ([id], [name]) VALUES ('day', 'dayak');
INSERT INTO [country] ([id], [name]) VALUES ('del', 'delavarski');
INSERT INTO [country] ([id], [name]) VALUES ('din', 'dinka');
INSERT INTO [country] ([id], [name]) VALUES ('dv', 'divehi');
INSERT INTO [country] ([id], [name]) VALUES ('doi', 'dogri');
INSERT INTO [country] ([id], [name]) VALUES ('dgr', 'dogrib');
INSERT INTO [country] ([id], [name]) VALUES ('nds', 'donjonjemački');
INSERT INTO [country] ([id], [name]) VALUES ('dra', 'dravidski');
INSERT INTO [country] ([id], [name]) VALUES ('dua', 'duala');
INSERT INTO [country] ([id], [name]) VALUES ('dyu', 'dyula');
INSERT INTO [country] ([id], [name]) VALUES ('dz', 'dzongkha');
INSERT INTO [country] ([id], [name]) VALUES ('efi', 'efik');
INSERT INTO [country] ([id], [name]) VALUES ('eka', 'ekajuk');
INSERT INTO [country] ([id], [name]) VALUES ('elx', 'elamitski');
INSERT INTO [country] ([id], [name]) VALUES ('en', 'engleski');
INSERT INTO [country] ([id], [name]) VALUES ('cpe', 'engleski - na osnovi kreolskog ili pidgin');
INSERT INTO [country] ([id], [name]) VALUES ('en_US', 'engleski (američki)');
INSERT INTO [country] ([id], [name]) VALUES ('en_AU', 'engleski (australski)');
INSERT INTO [country] ([id], [name]) VALUES ('en_GB', 'engleski (britanski)');
INSERT INTO [country] ([id], [name]) VALUES ('enm', 'engleski, srednji');
INSERT INTO [country] ([id], [name]) VALUES ('eo', 'esperanto');
INSERT INTO [country] ([id], [name]) VALUES ('et', 'estonijski');
INSERT INTO [country] ([id], [name]) VALUES ('ee', 'ewe');
INSERT INTO [country] ([id], [name]) VALUES ('ewo', 'ewondo');
INSERT INTO [country] ([id], [name]) VALUES ('fan', 'fang');
INSERT INTO [country] ([id], [name]) VALUES ('fat', 'fanti');
INSERT INTO [country] ([id], [name]) VALUES ('fo', 'faroanski');
INSERT INTO [country] ([id], [name]) VALUES ('phn', 'fenički');
INSERT INTO [country] ([id], [name]) VALUES ('fj', 'fidžijski');
INSERT INTO [country] ([id], [name]) VALUES ('fil', 'filipino');
INSERT INTO [country] ([id], [name]) VALUES ('phi', 'filipinski');
INSERT INTO [country] ([id], [name]) VALUES ('fi', 'finski');
INSERT INTO [country] ([id], [name]) VALUES ('nl_BE', 'flamanski');
INSERT INTO [country] ([id], [name]) VALUES ('fon', 'fon');
INSERT INTO [country] ([id], [name]) VALUES ('fr', 'francuski');
INSERT INTO [country] ([id], [name]) VALUES ('cpf', 'francuski - na osnovi kreolskog ili pidgin');
INSERT INTO [country] ([id], [name]) VALUES ('frm', 'francuski, srednji');
INSERT INTO [country] ([id], [name]) VALUES ('fur', 'friulski');
INSERT INTO [country] ([id], [name]) VALUES ('fy', 'frizijski');
INSERT INTO [country] ([id], [name]) VALUES ('ff', 'fulah');
INSERT INTO [country] ([id], [name]) VALUES ('gaa', 'ga');
INSERT INTO [country] ([id], [name]) VALUES ('gl', 'galicijski');
INSERT INTO [country] ([id], [name]) VALUES ('lg', 'ganda');
INSERT INTO [country] ([id], [name]) VALUES ('gay', 'gayo');
INSERT INTO [country] ([id], [name]) VALUES ('gba', 'gbaya');
INSERT INTO [country] ([id], [name]) VALUES ('gem', 'germanski');
INSERT INTO [country] ([id], [name]) VALUES ('gil', 'gilbertski');
INSERT INTO [country] ([id], [name]) VALUES ('gon', 'gondi');
INSERT INTO [country] ([id], [name]) VALUES ('hsb', 'gornjolužički');
INSERT INTO [country] ([id], [name]) VALUES ('de_CH', 'gornjonjemački (švicarski)');
INSERT INTO [country] ([id], [name]) VALUES ('gor', 'gorontalo');
INSERT INTO [country] ([id], [name]) VALUES ('got', 'gothic');
INSERT INTO [country] ([id], [name]) VALUES ('el', 'grčki');
INSERT INTO [country] ([id], [name]) VALUES ('grb', 'grebo');
INSERT INTO [country] ([id], [name]) VALUES ('ka', 'gruzijski');
INSERT INTO [country] ([id], [name]) VALUES ('gn', 'guarani');
INSERT INTO [country] ([id], [name]) VALUES ('gu', 'gujarati');
INSERT INTO [country] ([id], [name]) VALUES ('gwi', 'gwich''in');
INSERT INTO [country] ([id], [name]) VALUES ('hai', 'haidi');
INSERT INTO [country] ([id], [name]) VALUES ('ha', 'hausa');
INSERT INTO [country] ([id], [name]) VALUES ('haw', 'havajski');
INSERT INTO [country] ([id], [name]) VALUES ('he', 'hebrejski');
INSERT INTO [country] ([id], [name]) VALUES ('hz', 'herero');
INSERT INTO [country] ([id], [name]) VALUES ('hit', 'hetitski');
INSERT INTO [country] ([id], [name]) VALUES ('hil', 'hiligaynon');
INSERT INTO [country] ([id], [name]) VALUES ('him', 'himachali');
INSERT INTO [country] ([id], [name]) VALUES ('hi', 'hindski');
INSERT INTO [country] ([id], [name]) VALUES ('ho', 'hiri motu');
INSERT INTO [country] ([id], [name]) VALUES ('hmn', 'hmong');
INSERT INTO [country] ([id], [name]) VALUES ('hr', 'hrvatski');
INSERT INTO [country] ([id], [name]) VALUES ('hup', 'hupa');
INSERT INTO [country] ([id], [name]) VALUES ('iba', 'iban');
INSERT INTO [country] ([id], [name]) VALUES ('es_ES', 'iberski španjolski');
INSERT INTO [country] ([id], [name]) VALUES ('io', 'ido');
INSERT INTO [country] ([id], [name]) VALUES ('ig', 'igbo');
INSERT INTO [country] ([id], [name]) VALUES ('ijo', 'ijo');
INSERT INTO [country] ([id], [name]) VALUES ('ilo', 'iloko');
INSERT INTO [country] ([id], [name]) VALUES ('smn', 'inari sami');
INSERT INTO [country] ([id], [name]) VALUES ('inc', 'indijski');
INSERT INTO [country] ([id], [name]) VALUES ('ine', 'indoeuropski');
INSERT INTO [country] ([id], [name]) VALUES ('id', 'indonezijski');
INSERT INTO [country] ([id], [name]) VALUES ('inh', 'ingušetski');
INSERT INTO [country] ([id], [name]) VALUES ('ie', 'interligua');
INSERT INTO [country] ([id], [name]) VALUES ('ia', 'interlingua');
INSERT INTO [country] ([id], [name]) VALUES ('iu', 'inuktitut');
INSERT INTO [country] ([id], [name]) VALUES ('ik', 'inupiaq');
INSERT INTO [country] ([id], [name]) VALUES ('ira', 'iranski');
INSERT INTO [country] ([id], [name]) VALUES ('iro', 'irokeški');
INSERT INTO [country] ([id], [name]) VALUES ('ga', 'irski');
INSERT INTO [country] ([id], [name]) VALUES ('mga', 'irski, srednji');
INSERT INTO [country] ([id], [name]) VALUES ('is', 'islandski');
INSERT INTO [country] ([id], [name]) VALUES ('frs', 'istočnofrizijski');
INSERT INTO [country] ([id], [name]) VALUES ('sah', 'jakutski');
INSERT INTO [country] ([id], [name]) VALUES ('ja', 'japanski');
INSERT INTO [country] ([id], [name]) VALUES ('yap', 'japski');
INSERT INTO [country] ([id], [name]) VALUES ('jv', 'javanski');
INSERT INTO [country] ([id], [name]) VALUES ('sai', 'jezik južnoameričkih Indijanaca');
INSERT INTO [country] ([id], [name]) VALUES ('nai', 'jezik sjevernoameričkih Indijanaca');
INSERT INTO [country] ([id], [name]) VALUES ('cai', 'jezik srednjoameričkih Indijanaca');
INSERT INTO [country] ([id], [name]) VALUES ('yi', 'jidiš');
INSERT INTO [country] ([id], [name]) VALUES ('yo', 'joruba');
INSERT INTO [country] ([id], [name]) VALUES ('jrb', 'judejsko-arapski');
INSERT INTO [country] ([id], [name]) VALUES ('jpr', 'judejsko-perzijski');
INSERT INTO [country] ([id], [name]) VALUES ('alt', 'južni altai');
INSERT INTO [country] ([id], [name]) VALUES ('nr', 'južni ndebele');
INSERT INTO [country] ([id], [name]) VALUES ('se', 'južni sami');
INSERT INTO [country] ([id], [name]) VALUES ('kbd', 'kabardian');
INSERT INTO [country] ([id], [name]) VALUES ('kab', 'kabyle');
INSERT INTO [country] ([id], [name]) VALUES ('kac', 'kachin');
INSERT INTO [country] ([id], [name]) VALUES ('kaj', 'kaje');
INSERT INTO [country] ([id], [name]) VALUES ('kl', 'kalaallisut');
INSERT INTO [country] ([id], [name]) VALUES ('xal', 'kalmyk');
INSERT INTO [country] ([id], [name]) VALUES ('kam', 'kamba');
INSERT INTO [country] ([id], [name]) VALUES ('en_CA', 'kanadski engleski');
INSERT INTO [country] ([id], [name]) VALUES ('fr_CA', 'kanadski francuski');
INSERT INTO [country] ([id], [name]) VALUES ('kn', 'kannadski');
INSERT INTO [country] ([id], [name]) VALUES ('yue', 'kantonski');
INSERT INTO [country] ([id], [name]) VALUES ('kr', 'kanuri');
INSERT INTO [country] ([id], [name]) VALUES ('kaa', 'kara-kalpak');
INSERT INTO [country] ([id], [name]) VALUES ('krc', 'karachay-balkar');
INSERT INTO [country] ([id], [name]) VALUES ('krl', 'karelijski');
INSERT INTO [country] ([id], [name]) VALUES ('kar', 'karen');
INSERT INTO [country] ([id], [name]) VALUES ('car', 'karipski');
INSERT INTO [country] ([id], [name]) VALUES ('ks', 'kašmirski');
INSERT INTO [country] ([id], [name]) VALUES ('csb', 'kašupski');
INSERT INTO [country] ([id], [name]) VALUES ('ca', 'katalonski');
INSERT INTO [country] ([id], [name]) VALUES ('cau', 'kavkaski');
INSERT INTO [country] ([id], [name]) VALUES ('kaw', 'kawi');
INSERT INTO [country] ([id], [name]) VALUES ('kk', 'kazaški');
INSERT INTO [country] ([id], [name]) VALUES ('cel', 'keltski');
INSERT INTO [country] ([id], [name]) VALUES ('kha', 'khasi');
INSERT INTO [country] ([id], [name]) VALUES ('kho', 'khotanese');
INSERT INTO [country] ([id], [name]) VALUES ('ki', 'kikuyu');
INSERT INTO [country] ([id], [name]) VALUES ('kmb', 'kimbundu');
INSERT INTO [country] ([id], [name]) VALUES ('zh', 'kineski');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hans', 'kineski (pojednostavljeni)');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hant', 'kineski (tradicionalni)');
INSERT INTO [country] ([id], [name]) VALUES ('rw', 'kinyarwanda');
INSERT INTO [country] ([id], [name]) VALUES ('ky', 'kirgiški');
INSERT INTO [country] ([id], [name]) VALUES ('nwc', 'klasični newari');
INSERT INTO [country] ([id], [name]) VALUES ('syc', 'klasični sirski');
INSERT INTO [country] ([id], [name]) VALUES ('tlh', 'klingonski');
INSERT INTO [country] ([id], [name]) VALUES ('km', 'kmerski');
INSERT INTO [country] ([id], [name]) VALUES ('nb', 'književni norveški');
INSERT INTO [country] ([id], [name]) VALUES ('khi', 'kojsanski');
INSERT INTO [country] ([id], [name]) VALUES ('kv', 'komi');
INSERT INTO [country] ([id], [name]) VALUES ('swb', 'komorski');
INSERT INTO [country] ([id], [name]) VALUES ('kg', 'kongo');
INSERT INTO [country] ([id], [name]) VALUES ('kok', 'konkani');
INSERT INTO [country] ([id], [name]) VALUES ('cop', 'koptski');
INSERT INTO [country] ([id], [name]) VALUES ('ko', 'korejski');
INSERT INTO [country] ([id], [name]) VALUES ('root', 'korijenski');
INSERT INTO [country] ([id], [name]) VALUES ('kw', 'kornski');
INSERT INTO [country] ([id], [name]) VALUES ('kfo', 'koro');
INSERT INTO [country] ([id], [name]) VALUES ('co', 'korzički');
INSERT INTO [country] ([id], [name]) VALUES ('kpe', 'kpelle');
INSERT INTO [country] ([id], [name]) VALUES ('ht', 'kreolski');
INSERT INTO [country] ([id], [name]) VALUES ('crp', 'kreolski ili pidgin');
INSERT INTO [country] ([id], [name]) VALUES ('cpp', 'kreolski ili pidgin na osnovi portugalskog');
INSERT INTO [country] ([id], [name]) VALUES ('crh', 'krimski turski');
INSERT INTO [country] ([id], [name]) VALUES ('kro', 'kru');
INSERT INTO [country] ([id], [name]) VALUES ('kj', 'kuanyama');
INSERT INTO [country] ([id], [name]) VALUES ('kum', 'kumyk');
INSERT INTO [country] ([id], [name]) VALUES ('ku', 'kurdski');
INSERT INTO [country] ([id], [name]) VALUES ('kru', 'kuruški');
INSERT INTO [country] ([id], [name]) VALUES ('cus', 'kušitski');
INSERT INTO [country] ([id], [name]) VALUES ('kut', 'kutenai');
INSERT INTO [country] ([id], [name]) VALUES ('lad', 'ladino');
INSERT INTO [country] ([id], [name]) VALUES ('lah', 'lahnda');
INSERT INTO [country] ([id], [name]) VALUES ('lam', 'lamba');
INSERT INTO [country] ([id], [name]) VALUES ('lo', 'laoski');
INSERT INTO [country] ([id], [name]) VALUES ('la', 'latinski');
INSERT INTO [country] ([id], [name]) VALUES ('lv', 'latvijski');
INSERT INTO [country] ([id], [name]) VALUES ('lez', 'lezgiški');
INSERT INTO [country] ([id], [name]) VALUES ('li', 'limburgish');
INSERT INTO [country] ([id], [name]) VALUES ('ln', 'lingala');
INSERT INTO [country] ([id], [name]) VALUES ('lt', 'litvanski');
INSERT INTO [country] ([id], [name]) VALUES ('jbo', 'lojban');
INSERT INTO [country] ([id], [name]) VALUES ('loz', 'lozi');
INSERT INTO [country] ([id], [name]) VALUES ('lu', 'luba-katanga');
INSERT INTO [country] ([id], [name]) VALUES ('lua', 'luba-lulua');
INSERT INTO [country] ([id], [name]) VALUES ('lui', 'luiseno');
INSERT INTO [country] ([id], [name]) VALUES ('lb', 'luksemburški');
INSERT INTO [country] ([id], [name]) VALUES ('smj', 'lule sami');
INSERT INTO [country] ([id], [name]) VALUES ('lun', 'lunda');
INSERT INTO [country] ([id], [name]) VALUES ('luo', 'luo');
INSERT INTO [country] ([id], [name]) VALUES ('lus', 'lushai');
INSERT INTO [country] ([id], [name]) VALUES ('wen', 'lužički');
INSERT INTO [country] ([id], [name]) VALUES ('dsb', 'lužičkosrpski');
INSERT INTO [country] ([id], [name]) VALUES ('mad', 'madurski');
INSERT INTO [country] ([id], [name]) VALUES ('hu', 'mađarski');
INSERT INTO [country] ([id], [name]) VALUES ('mag', 'magahi');
INSERT INTO [country] ([id], [name]) VALUES ('mai', 'maithili');
INSERT INTO [country] ([id], [name]) VALUES ('myn', 'majanski');
INSERT INTO [country] ([id], [name]) VALUES ('mak', 'makasar');
INSERT INTO [country] ([id], [name]) VALUES ('mk', 'makedonski');
INSERT INTO [country] ([id], [name]) VALUES ('ml', 'malajalamski');
INSERT INTO [country] ([id], [name]) VALUES ('ms', 'malajski');
INSERT INTO [country] ([id], [name]) VALUES ('mg', 'malgaški');
INSERT INTO [country] ([id], [name]) VALUES ('mt', 'malteški');
INSERT INTO [country] ([id], [name]) VALUES ('mdr', 'mandar');
INSERT INTO [country] ([id], [name]) VALUES ('man', 'mandingo');
INSERT INTO [country] ([id], [name]) VALUES ('mnc', 'mandžurski');
INSERT INTO [country] ([id], [name]) VALUES ('mni', 'manipurski');
INSERT INTO [country] ([id], [name]) VALUES ('mno', 'manobo');
INSERT INTO [country] ([id], [name]) VALUES ('gv', 'manx');
INSERT INTO [country] ([id], [name]) VALUES ('mi', 'maorski');
INSERT INTO [country] ([id], [name]) VALUES ('mr', 'marathi');
INSERT INTO [country] ([id], [name]) VALUES ('chm', 'mari');
INSERT INTO [country] ([id], [name]) VALUES ('mh', 'maršalski');
INSERT INTO [country] ([id], [name]) VALUES ('mwr', 'marwari');
INSERT INTO [country] ([id], [name]) VALUES ('mas', 'masajski');
INSERT INTO [country] ([id], [name]) VALUES ('men', 'mende');
INSERT INTO [country] ([id], [name]) VALUES ('mic', 'micmac');
INSERT INTO [country] ([id], [name]) VALUES ('min', 'minangkabau');
INSERT INTO [country] ([id], [name]) VALUES ('mwl', 'mirandski');
INSERT INTO [country] ([id], [name]) VALUES ('moh', 'mohawk');
INSERT INTO [country] ([id], [name]) VALUES ('mdf', 'moksha');
INSERT INTO [country] ([id], [name]) VALUES ('mo', 'moldavski');
INSERT INTO [country] ([id], [name]) VALUES ('lol', 'mongo');
INSERT INTO [country] ([id], [name]) VALUES ('mn', 'mongolski');
INSERT INTO [country] ([id], [name]) VALUES ('myv', 'mordvinski');
INSERT INTO [country] ([id], [name]) VALUES ('mos', 'mossi');
INSERT INTO [country] ([id], [name]) VALUES ('mun', 'munda');
INSERT INTO [country] ([id], [name]) VALUES ('nqo', 'n''ko');
INSERT INTO [country] ([id], [name]) VALUES ('nah', 'nahuatl');
INSERT INTO [country] ([id], [name]) VALUES ('nap', 'napolitanski');
INSERT INTO [country] ([id], [name]) VALUES ('kos', 'naurski');
INSERT INTO [country] ([id], [name]) VALUES ('na', 'nauru');
INSERT INTO [country] ([id], [name]) VALUES ('nv', 'navajo');
INSERT INTO [country] ([id], [name]) VALUES ('ng', 'ndonga');
INSERT INTO [country] ([id], [name]) VALUES ('ne', 'nepalski');
INSERT INTO [country] ([id], [name]) VALUES ('und', 'nepoznati ili nevažeći jezik');
INSERT INTO [country] ([id], [name]) VALUES ('new', 'newari');
INSERT INTO [country] ([id], [name]) VALUES ('nia', 'nias');
INSERT INTO [country] ([id], [name]) VALUES ('nic', 'nigersko-kordofanski');
INSERT INTO [country] ([id], [name]) VALUES ('ssa', 'nilo-saharski');
INSERT INTO [country] ([id], [name]) VALUES ('niu', 'niujski');
INSERT INTO [country] ([id], [name]) VALUES ('nl', 'nizozemski');
INSERT INTO [country] ([id], [name]) VALUES ('dum', 'nizozemski, srednji');
INSERT INTO [country] ([id], [name]) VALUES ('nog', 'nogajski');
INSERT INTO [country] ([id], [name]) VALUES ('no', 'norveški');
INSERT INTO [country] ([id], [name]) VALUES ('nn', 'novonorveški');
INSERT INTO [country] ([id], [name]) VALUES ('nub', 'nubijski');
INSERT INTO [country] ([id], [name]) VALUES ('nym', 'nyamwezi');
INSERT INTO [country] ([id], [name]) VALUES ('nyn', 'nyankole');
INSERT INTO [country] ([id], [name]) VALUES ('ny', 'nyanja');
INSERT INTO [country] ([id], [name]) VALUES ('tog', 'nyasa tonga');
INSERT INTO [country] ([id], [name]) VALUES ('nyo', 'nyoro');
INSERT INTO [country] ([id], [name]) VALUES ('nzi', 'nzima');
INSERT INTO [country] ([id], [name]) VALUES ('de', 'njemački');
INSERT INTO [country] ([id], [name]) VALUES ('gmh', 'njemački, srednji visoki');
INSERT INTO [country] ([id], [name]) VALUES ('oj', 'ojibwa');
INSERT INTO [country] ([id], [name]) VALUES ('oc', 'okcitanski');
INSERT INTO [country] ([id], [name]) VALUES ('or', 'orijski');
INSERT INTO [country] ([id], [name]) VALUES ('om', 'oromski');
INSERT INTO [country] ([id], [name]) VALUES ('osa', 'osage');
INSERT INTO [country] ([id], [name]) VALUES ('os', 'osetski');
INSERT INTO [country] ([id], [name]) VALUES ('afa', 'ostali afričko-azijski');
INSERT INTO [country] ([id], [name]) VALUES ('mis', 'ostali jezici');
INSERT INTO [country] ([id], [name]) VALUES ('oto', 'otomijski');
INSERT INTO [country] ([id], [name]) VALUES ('pal', 'pahlavi');
INSERT INTO [country] ([id], [name]) VALUES ('pau', 'palauanski');
INSERT INTO [country] ([id], [name]) VALUES ('pi', 'pali');
INSERT INTO [country] ([id], [name]) VALUES ('pam', 'pampanga');
INSERT INTO [country] ([id], [name]) VALUES ('pag', 'pangasinan');
INSERT INTO [country] ([id], [name]) VALUES ('pap', 'papiamento');
INSERT INTO [country] ([id], [name]) VALUES ('paa', 'papuanski');
INSERT INTO [country] ([id], [name]) VALUES ('ps', 'paštu');
INSERT INTO [country] ([id], [name]) VALUES ('fa', 'perzijski');
INSERT INTO [country] ([id], [name]) VALUES ('pon', 'pohnpeian');
INSERT INTO [country] ([id], [name]) VALUES ('pl', 'poljski');
INSERT INTO [country] ([id], [name]) VALUES ('pt', 'portugalski');
INSERT INTO [country] ([id], [name]) VALUES ('pt_PT', 'portugalski (iberijski)');
INSERT INTO [country] ([id], [name]) VALUES ('pra', 'prakrit');
INSERT INTO [country] ([id], [name]) VALUES ('pa', 'punjabi');
INSERT INTO [country] ([id], [name]) VALUES ('qu', 'quechua');
INSERT INTO [country] ([id], [name]) VALUES ('raj', 'rajasthani');
INSERT INTO [country] ([id], [name]) VALUES ('rap', 'rapa nui');
INSERT INTO [country] ([id], [name]) VALUES ('rar', 'rarotonški');
INSERT INTO [country] ([id], [name]) VALUES ('rm', 'retoromanski');
INSERT INTO [country] ([id], [name]) VALUES ('roa', 'romanski');
INSERT INTO [country] ([id], [name]) VALUES ('rom', 'romski');
INSERT INTO [country] ([id], [name]) VALUES ('ro', 'rumunjski');
INSERT INTO [country] ([id], [name]) VALUES ('rn', 'rundi');
INSERT INTO [country] ([id], [name]) VALUES ('ru', 'ruski');
INSERT INTO [country] ([id], [name]) VALUES ('sal', 'salishan');
INSERT INTO [country] ([id], [name]) VALUES ('sam', 'samarijanski aramejski');
INSERT INTO [country] ([id], [name]) VALUES ('smi', 'sami');
INSERT INTO [country] ([id], [name]) VALUES ('sm', 'samoanski');
INSERT INTO [country] ([id], [name]) VALUES ('sad', 'sandawe');
INSERT INTO [country] ([id], [name]) VALUES ('sg', 'sango');
INSERT INTO [country] ([id], [name]) VALUES ('sa', 'sanskrtski');
INSERT INTO [country] ([id], [name]) VALUES ('sat', 'santali');
INSERT INTO [country] ([id], [name]) VALUES ('sc', 'sardski');
INSERT INTO [country] ([id], [name]) VALUES ('sas', 'sasak');
INSERT INTO [country] ([id], [name]) VALUES ('sel', 'selkupski');
INSERT INTO [country] ([id], [name]) VALUES ('sem', 'semitic');
INSERT INTO [country] ([id], [name]) VALUES ('srr', 'serer');
INSERT INTO [country] ([id], [name]) VALUES ('st', 'sesotski');
INSERT INTO [country] ([id], [name]) VALUES ('shn', 'shan');
INSERT INTO [country] ([id], [name]) VALUES ('sn', 'shona');
INSERT INTO [country] ([id], [name]) VALUES ('ii', 'sichuan yi');
INSERT INTO [country] ([id], [name]) VALUES ('scn', 'sicilijski');
INSERT INTO [country] ([id], [name]) VALUES ('sid', 'sidamo');
INSERT INTO [country] ([id], [name]) VALUES ('bla', 'siksika');
INSERT INTO [country] ([id], [name]) VALUES ('sd', 'sindhi');
INSERT INTO [country] ([id], [name]) VALUES ('si', 'singaleški');
INSERT INTO [country] ([id], [name]) VALUES ('sit', 'sino-tibetski');
INSERT INTO [country] ([id], [name]) VALUES ('sio', 'siouan');
INSERT INTO [country] ([id], [name]) VALUES ('syr', 'sirijski');
INSERT INTO [country] ([id], [name]) VALUES ('nd', 'sjeverni ndebele');
INSERT INTO [country] ([id], [name]) VALUES ('sma', 'sjeverni sami');
INSERT INTO [country] ([id], [name]) VALUES ('nso', 'sjeverni sotho');
INSERT INTO [country] ([id], [name]) VALUES ('frr', 'sjevernofrizijski');
INSERT INTO [country] ([id], [name]) VALUES ('sms', 'skolt sami');
INSERT INTO [country] ([id], [name]) VALUES ('den', 'slave');
INSERT INTO [country] ([id], [name]) VALUES ('sla', 'slavenski');
INSERT INTO [country] ([id], [name]) VALUES ('sk', 'slovački');
INSERT INTO [country] ([id], [name]) VALUES ('sl', 'slovenski');
INSERT INTO [country] ([id], [name]) VALUES ('sog', 'sogdien');
INSERT INTO [country] ([id], [name]) VALUES ('so', 'somalski');
INSERT INTO [country] ([id], [name]) VALUES ('son', 'songhai');
INSERT INTO [country] ([id], [name]) VALUES ('snk', 'soninke');
INSERT INTO [country] ([id], [name]) VALUES ('srn', 'sranan tongo');
INSERT INTO [country] ([id], [name]) VALUES ('sr', 'srpski');
INSERT INTO [country] ([id], [name]) VALUES ('sh', 'srpsko-hrvatski');
INSERT INTO [country] ([id], [name]) VALUES ('egy', 'staroegipatski');
INSERT INTO [country] ([id], [name]) VALUES ('ang', 'staroengleski');
INSERT INTO [country] ([id], [name]) VALUES ('gez', 'staroetiopski');
INSERT INTO [country] ([id], [name]) VALUES ('fro', 'starofrancuski');
INSERT INTO [country] ([id], [name]) VALUES ('grc', 'starogrčki');
INSERT INTO [country] ([id], [name]) VALUES ('sga', 'staroirski');
INSERT INTO [country] ([id], [name]) VALUES ('non', 'staronorveški');
INSERT INTO [country] ([id], [name]) VALUES ('goh', 'staronjemački, visoki');
INSERT INTO [country] ([id], [name]) VALUES ('peo', 'staroperzijski');
INSERT INTO [country] ([id], [name]) VALUES ('pro', 'staroprovansalski');
INSERT INTO [country] ([id], [name]) VALUES ('suk', 'sukuma');
INSERT INTO [country] ([id], [name]) VALUES ('sux', 'sumerski');
INSERT INTO [country] ([id], [name]) VALUES ('su', 'sundanski');
INSERT INTO [country] ([id], [name]) VALUES ('sus', 'susu');
INSERT INTO [country] ([id], [name]) VALUES ('sw', 'svahili');
INSERT INTO [country] ([id], [name]) VALUES ('ss', 'svati');
INSERT INTO [country] ([id], [name]) VALUES ('sco', 'škotski');
INSERT INTO [country] ([id], [name]) VALUES ('gd', 'škotski-galski');
INSERT INTO [country] ([id], [name]) VALUES ('es', 'španjolski');
INSERT INTO [country] ([id], [name]) VALUES ('es_419', 'španjolski (latinoamerički)');
INSERT INTO [country] ([id], [name]) VALUES ('sv', 'švedski');
INSERT INTO [country] ([id], [name]) VALUES ('fr_CH', 'švicarski francuski');
INSERT INTO [country] ([id], [name]) VALUES ('gsw', 'švicarski njemački');
INSERT INTO [country] ([id], [name]) VALUES ('tl', 'tagalog');
INSERT INTO [country] ([id], [name]) VALUES ('ty', 'tahićanski');
INSERT INTO [country] ([id], [name]) VALUES ('tg', 'tajik');
INSERT INTO [country] ([id], [name]) VALUES ('th', 'tajlandski');
INSERT INTO [country] ([id], [name]) VALUES ('tai', 'tajski');
INSERT INTO [country] ([id], [name]) VALUES ('it', 'talijanski');
INSERT INTO [country] ([id], [name]) VALUES ('tmh', 'tamashek');
INSERT INTO [country] ([id], [name]) VALUES ('ta', 'tamilski');
INSERT INTO [country] ([id], [name]) VALUES ('tt', 'tatarski');
INSERT INTO [country] ([id], [name]) VALUES ('te', 'telugu');
INSERT INTO [country] ([id], [name]) VALUES ('tem', 'temne');
INSERT INTO [country] ([id], [name]) VALUES ('ter', 'tereno');
INSERT INTO [country] ([id], [name]) VALUES ('tet', 'tetum');
INSERT INTO [country] ([id], [name]) VALUES ('bo', 'tibetanski');
INSERT INTO [country] ([id], [name]) VALUES ('ti', 'tigrinya');
INSERT INTO [country] ([id], [name]) VALUES ('tig', 'tigriški');
INSERT INTO [country] ([id], [name]) VALUES ('tiv', 'tiv');
INSERT INTO [country] ([id], [name]) VALUES ('tli', 'tlingit');
INSERT INTO [country] ([id], [name]) VALUES ('tpi', 'tok pisin');
INSERT INTO [country] ([id], [name]) VALUES ('tkl', 'tokelaunski');
INSERT INTO [country] ([id], [name]) VALUES ('to', 'tonga');
INSERT INTO [country] ([id], [name]) VALUES ('tsi', 'tsimshian');
INSERT INTO [country] ([id], [name]) VALUES ('ts', 'tsonga');
INSERT INTO [country] ([id], [name]) VALUES ('tum', 'tumbuka');
INSERT INTO [country] ([id], [name]) VALUES ('tup', 'tupi');
INSERT INTO [country] ([id], [name]) VALUES ('tk', 'turkmenski');
INSERT INTO [country] ([id], [name]) VALUES ('tr', 'turski');
INSERT INTO [country] ([id], [name]) VALUES ('ota', 'turski - otomanski');
INSERT INTO [country] ([id], [name]) VALUES ('tvl', 'tuvaluanski');
INSERT INTO [country] ([id], [name]) VALUES ('tyv', 'tuvinian');
INSERT INTO [country] ([id], [name]) VALUES ('tw', 'twi');
INSERT INTO [country] ([id], [name]) VALUES ('kcg', 'tyap');
INSERT INTO [country] ([id], [name]) VALUES ('udm', 'udmurtski');
INSERT INTO [country] ([id], [name]) VALUES ('uga', 'ugaritski');
INSERT INTO [country] ([id], [name]) VALUES ('fiu', 'ugro-finski jezik');
INSERT INTO [country] ([id], [name]) VALUES ('ug', 'uighur');
INSERT INTO [country] ([id], [name]) VALUES ('uk', 'ukrajinski');
INSERT INTO [country] ([id], [name]) VALUES ('umb', 'umbundu');
INSERT INTO [country] ([id], [name]) VALUES ('art', 'umjetni jezik');
INSERT INTO [country] ([id], [name]) VALUES ('ur', 'urdski');
INSERT INTO [country] ([id], [name]) VALUES ('uz', 'uzbečki');
INSERT INTO [country] ([id], [name]) VALUES ('vai', 'vai');
INSERT INTO [country] ([id], [name]) VALUES ('wa', 'valonski');
INSERT INTO [country] ([id], [name]) VALUES ('cy', 'velški');
INSERT INTO [country] ([id], [name]) VALUES ('ve', 'venda');
INSERT INTO [country] ([id], [name]) VALUES ('vi', 'vijetnamski');
INSERT INTO [country] ([id], [name]) VALUES ('vo', 'volapük');
INSERT INTO [country] ([id], [name]) VALUES ('vot', 'votic');
INSERT INTO [country] ([id], [name]) VALUES ('wak', 'wakashan');
INSERT INTO [country] ([id], [name]) VALUES ('wal', 'walamo');
INSERT INTO [country] ([id], [name]) VALUES ('war', 'waray');
INSERT INTO [country] ([id], [name]) VALUES ('was', 'washo');
INSERT INTO [country] ([id], [name]) VALUES ('wo', 'wolof');
INSERT INTO [country] ([id], [name]) VALUES ('xh', 'xhosa');
INSERT INTO [country] ([id], [name]) VALUES ('yao', 'yao');
INSERT INTO [country] ([id], [name]) VALUES ('ypk', 'yupik');
INSERT INTO [country] ([id], [name]) VALUES ('znd', 'zande');
INSERT INTO [country] ([id], [name]) VALUES ('zap', 'zapotec');
INSERT INTO [country] ([id], [name]) VALUES ('zza', 'zazaki');
INSERT INTO [country] ([id], [name]) VALUES ('zen', 'zenaga');
INSERT INTO [country] ([id], [name]) VALUES ('za', 'zhuang');
INSERT INTO [country] ([id], [name]) VALUES ('sgn', 'znakovni jezik');
INSERT INTO [country] ([id], [name]) VALUES ('zu', 'zulu');
INSERT INTO [country] ([id], [name]) VALUES ('zun', 'zuni');
