CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('ab', 'abkhaziagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('af', 'afrikaangbe');
INSERT INTO `country` (`id`, `name`) VALUES ('sq', 'albaniagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('am', 'amhariagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('st', 'anyiehe sothogbe');
INSERT INTO `country` (`id`, `name`) VALUES ('ar', 'arabiagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('hy', 'armeniagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('asa', 'asagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('as', 'assamegbe');
INSERT INTO `country` (`id`, `name`) VALUES ('en_AU', 'australiatɔwo ƒe yevugbe');
INSERT INTO `country` (`id`, `name`) VALUES ('de_AT', 'austriatɔwo ƒe germaniagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('ay', 'aymargbe');
INSERT INTO `country` (`id`, `name`) VALUES ('az', 'azerbaijangbe');
INSERT INTO `country` (`id`, `name`) VALUES ('bm', 'bambaragbe');
INSERT INTO `country` (`id`, `name`) VALUES ('eu', 'basqugbe');
INSERT INTO `country` (`id`, `name`) VALUES ('be', 'belarusiagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('bem', 'bembagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('bez', 'benagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('bn', 'bengalgbe');
INSERT INTO `country` (`id`, `name`) VALUES ('zh_Hant', 'blema tsainagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('ak', 'blugbe');
INSERT INTO `country` (`id`, `name`) VALUES ('brx', 'bodogbe');
INSERT INTO `country` (`id`, `name`) VALUES ('bs', 'bosniagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('pt_BR', 'braziltɔwo ƒe portugalgbe');
INSERT INTO `country` (`id`, `name`) VALUES ('br', 'bretongbe');
INSERT INTO `country` (`id`, `name`) VALUES ('en_GB', 'britaintɔwo ƒe yevugbe');
INSERT INTO `country` (`id`, `name`) VALUES ('bg', 'bulgariagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('my', 'burmagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('yue', 'cantongbe');
INSERT INTO `country` (`id`, `name`) VALUES ('kea', 'cape verdegbe');
INSERT INTO `country` (`id`, `name`) VALUES ('da', 'denmarkgbe');
INSERT INTO `country` (`id`, `name`) VALUES ('dv', 'divehgbe');
INSERT INTO `country` (`id`, `name`) VALUES ('ja', 'dzapangbe');
INSERT INTO `country` (`id`, `name`) VALUES ('jv', 'dzavangbe');
INSERT INTO `country` (`id`, `name`) VALUES ('nd', 'dziehe ndebelegbe');
INSERT INTO `country` (`id`, `name`) VALUES ('se', 'dziehe samigbe');
INSERT INTO `country` (`id`, `name`) VALUES ('nso', 'dziehe sothogbe');
INSERT INTO `country` (`id`, `name`) VALUES ('dz', 'dzongkhagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('efi', 'efigbe');
INSERT INTO `country` (`id`, `name`) VALUES ('ebu', 'embugbe');
INSERT INTO `country` (`id`, `name`) VALUES ('eo', 'esperantogbe');
INSERT INTO `country` (`id`, `name`) VALUES ('et', 'estoniagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('ee', 'eʋegbe');
INSERT INTO `country` (`id`, `name`) VALUES ('fj', 'fidzigbe');
INSERT INTO `country` (`id`, `name`) VALUES ('fil', 'filipingbe');
INSERT INTO `country` (`id`, `name`) VALUES ('fi', 'finlanɖgbe');
INSERT INTO `country` (`id`, `name`) VALUES ('nl_BE', 'flemiagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('fr', 'fransegbe');
INSERT INTO `country` (`id`, `name`) VALUES ('gl', 'galatagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('zxx', 'gbegbɔgblɔ manɔmee');
INSERT INTO `country` (`id`, `name`) VALUES ('und', 'gbegbɔgblɔ manya');
INSERT INTO `country` (`id`, `name`) VALUES ('de', 'germaniagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('ka', 'gɔgiagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('el', 'grisigbe');
INSERT INTO `country` (`id`, `name`) VALUES ('gn', 'guarangbe');
INSERT INTO `country` (`id`, `name`) VALUES ('gu', 'gujarati');
INSERT INTO `country` (`id`, `name`) VALUES ('ht', 'haitigbe');
INSERT INTO `country` (`id`, `name`) VALUES ('ha', 'hausagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('haw', 'hawaigbe');
INSERT INTO `country` (`id`, `name`) VALUES ('he', 'hebrigbe');
INSERT INTO `country` (`id`, `name`) VALUES ('hi', 'hindigbe');
INSERT INTO `country` (`id`, `name`) VALUES ('nl', 'hɔlandgbe');
INSERT INTO `country` (`id`, `name`) VALUES ('hu', 'hungarigbe');
INSERT INTO `country` (`id`, `name`) VALUES ('pt_PT', 'iberiatɔwo ƒe portugalgbe');
INSERT INTO `country` (`id`, `name`) VALUES ('es_ES', 'iberiatɔwo ƒe spaniagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('is', 'icelanɖgbe');
INSERT INTO `country` (`id`, `name`) VALUES ('ig', 'igbogbe');
INSERT INTO `country` (`id`, `name`) VALUES ('id', 'indonesiagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('ga', 'irelanɖgbe');
INSERT INTO `country` (`id`, `name`) VALUES ('it', 'italiagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('fr_CA', 'kanadatɔwo ƒe fransegbe');
INSERT INTO `country` (`id`, `name`) VALUES ('en_CA', 'kanadatɔwo ƒe yevugbe');
INSERT INTO `country` (`id`, `name`) VALUES ('kn', 'kannadagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('ks', 'kashmirgbe');
INSERT INTO `country` (`id`, `name`) VALUES ('ca', 'katalagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('kk', 'kazakhstangbe');
INSERT INTO `country` (`id`, `name`) VALUES ('km', 'khmergbe');
INSERT INTO `country` (`id`, `name`) VALUES ('zh', 'kinagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('ky', 'kirghistangbe');
INSERT INTO `country` (`id`, `name`) VALUES ('swb', 'komorogbe');
INSERT INTO `country` (`id`, `name`) VALUES ('ko', 'koreagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('hr', 'kroatiagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('ku', 'kurdiagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('qu', 'kwetsuagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('lah', 'lahndagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('lb', 'laksembɔggbe');
INSERT INTO `country` (`id`, `name`) VALUES ('lo', 'laogbe');
INSERT INTO `country` (`id`, `name`) VALUES ('la', 'latin');
INSERT INTO `country` (`id`, `name`) VALUES ('es_419', 'latin amerikatɔwo ƒe spaniagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('lv', 'latviagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('ln', 'lingala');
INSERT INTO `country` (`id`, `name`) VALUES ('lt', 'lithuaniagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('luy', 'luyiagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('mk', 'makedoniagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('mg', 'malagasegbe');
INSERT INTO `country` (`id`, `name`) VALUES ('ml', 'malayagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('ms', 'malaygbe');
INSERT INTO `country` (`id`, `name`) VALUES ('mt', 'maltagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('mi', 'maorgbe');
INSERT INTO `country` (`id`, `name`) VALUES ('mr', 'marathiagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('mn', 'mongoliagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('ne', 'nepalgbe');
INSERT INTO `country` (`id`, `name`) VALUES ('no', 'nɔweigbe');
INSERT INTO `country` (`id`, `name`) VALUES ('nb', 'nɔweigbe bokmål');
INSERT INTO `country` (`id`, `name`) VALUES ('nn', 'nɔweigbe ninɔsk');
INSERT INTO `country` (`id`, `name`) VALUES ('ny', 'nyanjagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('or', 'oriyagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('os', 'ossetiagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('ps', 'pashtogbe');
INSERT INTO `country` (`id`, `name`) VALUES ('fa', 'persiagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('pl', 'polandgbe');
INSERT INTO `country` (`id`, `name`) VALUES ('pt', 'pɔtugalgbe');
INSERT INTO `country` (`id`, `name`) VALUES ('pa', 'pundzabgbe');
INSERT INTO `country` (`id`, `name`) VALUES ('ro', 'romaniagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('rm', 'romanshgbe');
INSERT INTO `country` (`id`, `name`) VALUES ('rof', 'rombogbe');
INSERT INTO `country` (`id`, `name`) VALUES ('ru', 'rɔtsiagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('rn', 'rundigbe');
INSERT INTO `country` (`id`, `name`) VALUES ('rw', 'ruwandagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('rwk', 'rwagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('sah', 'sakagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('sm', 'samoagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('sg', 'sangogbe');
INSERT INTO `country` (`id`, `name`) VALUES ('sa', 'sanskrigbe');
INSERT INTO `country` (`id`, `name`) VALUES ('sr', 'serbiagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('sh', 'serbo-croatiagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('sn', 'shonagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('sd', 'sindhgbe');
INSERT INTO `country` (`id`, `name`) VALUES ('si', 'sinhalgbe');
INSERT INTO `country` (`id`, `name`) VALUES ('sk', 'slovakiagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('sl', 'sloveniagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('so', 'somaliagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('es', 'spaniagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('su', 'sudangbe');
INSERT INTO `country` (`id`, `name`) VALUES ('sw', 'swahili');
INSERT INTO `country` (`id`, `name`) VALUES ('ss', 'swatgbe');
INSERT INTO `country` (`id`, `name`) VALUES ('sv', 'swedengbe');
INSERT INTO `country` (`id`, `name`) VALUES ('de_CH', 'swizerlanɖ germaniagbe kɔkɔtɔ');
INSERT INTO `country` (`id`, `name`) VALUES ('fr_CH', 'swizerlanɖtɔwo ƒe fransegbe');
INSERT INTO `country` (`id`, `name`) VALUES ('gsw', 'swizerlanɖtɔwo ƒe germaniagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('tg', 'tadzikistangbe');
INSERT INTO `country` (`id`, `name`) VALUES ('tl', 'tagalogbe');
INSERT INTO `country` (`id`, `name`) VALUES ('ty', 'tahitigbe');
INSERT INTO `country` (`id`, `name`) VALUES ('th', 'tailandgbe');
INSERT INTO `country` (`id`, `name`) VALUES ('ta', 'tamilgbe');
INSERT INTO `country` (`id`, `name`) VALUES ('te', 'telegugbe');
INSERT INTO `country` (`id`, `name`) VALUES ('tet', 'tetumgbe');
INSERT INTO `country` (`id`, `name`) VALUES ('tr', 'tɛkigbe');
INSERT INTO `country` (`id`, `name`) VALUES ('tk', 'tɛkmengbe');
INSERT INTO `country` (`id`, `name`) VALUES ('bo', 'tibetagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('ti', 'tigrinyagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('tpi', 'tok pisigbe');
INSERT INTO `country` (`id`, `name`) VALUES ('to', 'tongagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('zh_Hans', 'tsainagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('cs', 'tsɛkgbe');
INSERT INTO `country` (`id`, `name`) VALUES ('ts', 'tsongagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('tn', 'tswanagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('en_US', 'u.s.dukɔmetɔwo ƒe yevugbe');
INSERT INTO `country` (`id`, `name`) VALUES ('ug', 'uighurgbe');
INSERT INTO `country` (`id`, `name`) VALUES ('uk', 'ukraingbe');
INSERT INTO `country` (`id`, `name`) VALUES ('ur', 'urdugbe');
INSERT INTO `country` (`id`, `name`) VALUES ('uz', 'uzbekistangbe');
INSERT INTO `country` (`id`, `name`) VALUES ('ve', 'vendagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('vi', 'vietnamgbe');
INSERT INTO `country` (`id`, `name`) VALUES ('cy', 'walesgbe');
INSERT INTO `country` (`id`, `name`) VALUES ('wae', 'walsegbe');
INSERT INTO `country` (`id`, `name`) VALUES ('wo', 'wolofgbe');
INSERT INTO `country` (`id`, `name`) VALUES ('xh', 'xhosagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('en', 'yevugbe');
INSERT INTO `country` (`id`, `name`) VALUES ('yo', 'yorubagbe');
INSERT INTO `country` (`id`, `name`) VALUES ('zu', 'zulugbe');
