CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('ab', 'abkhazo');
INSERT INTO "country" ("id", "name") VALUES ('af', 'afrikaans');
INSERT INTO "country" ("id", "name") VALUES ('ay', 'aimará');
INSERT INTO "country" ("id", "name") VALUES ('sq', 'albanés');
INSERT INTO "country" ("id", "name") VALUES ('de', 'alemán');
INSERT INTO "country" ("id", "name") VALUES ('de_AT', 'alemán de austria');
INSERT INTO "country" ("id", "name") VALUES ('gsw', 'alemán suízo');
INSERT INTO "country" ("id", "name") VALUES ('de_CH', 'alto alemán suízo');
INSERT INTO "country" ("id", "name") VALUES ('am', 'amárico');
INSERT INTO "country" ("id", "name") VALUES ('ar', 'árabe');
INSERT INTO "country" ("id", "name") VALUES ('an', 'aragonés');
INSERT INTO "country" ("id", "name") VALUES ('arc', 'arameo');
INSERT INTO "country" ("id", "name") VALUES ('hy', 'armenio');
INSERT INTO "country" ("id", "name") VALUES ('as', 'assamés');
INSERT INTO "country" ("id", "name") VALUES ('ast', 'asturiano');
INSERT INTO "country" ("id", "name") VALUES ('az', 'azerbaiano');
INSERT INTO "country" ("id", "name") VALUES ('bn', 'bengalí');
INSERT INTO "country" ("id", "name") VALUES ('be', 'bielorruso');
INSERT INTO "country" ("id", "name") VALUES ('bh', 'bihariano');
INSERT INTO "country" ("id", "name") VALUES ('my', 'birmano');
INSERT INTO "country" ("id", "name") VALUES ('bs', 'bosnio');
INSERT INTO "country" ("id", "name") VALUES ('br', 'bretón');
INSERT INTO "country" ("id", "name") VALUES ('bg', 'búlgaro');
INSERT INTO "country" ("id", "name") VALUES ('ks', 'cachemir');
INSERT INTO "country" ("id", "name") VALUES ('km', 'cambodiano');
INSERT INTO "country" ("id", "name") VALUES ('kk', 'casaco');
INSERT INTO "country" ("id", "name") VALUES ('es_ES', 'castelán');
INSERT INTO "country" ("id", "name") VALUES ('ca', 'catalán');
INSERT INTO "country" ("id", "name") VALUES ('cs', 'checo');
INSERT INTO "country" ("id", "name") VALUES ('ny', 'chewa');
INSERT INTO "country" ("id", "name") VALUES ('zh', 'chinés');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hans', 'chinés simplificado');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hant', 'chinés tradicional');
INSERT INTO "country" ("id", "name") VALUES ('si', 'cingalés');
INSERT INTO "country" ("id", "name") VALUES ('tlh', 'clingon');
INSERT INTO "country" ("id", "name") VALUES ('ko', 'coreano');
INSERT INTO "country" ("id", "name") VALUES ('hr', 'croata');
INSERT INTO "country" ("id", "name") VALUES ('da', 'dinamarqués');
INSERT INTO "country" ("id", "name") VALUES ('dv', 'divehi');
INSERT INTO "country" ("id", "name") VALUES ('dz', 'dzongkha');
INSERT INTO "country" ("id", "name") VALUES ('cu', 'eslavo eclesiástico');
INSERT INTO "country" ("id", "name") VALUES ('sk', 'eslovaco');
INSERT INTO "country" ("id", "name") VALUES ('sl', 'esloveno');
INSERT INTO "country" ("id", "name") VALUES ('es', 'español');
INSERT INTO "country" ("id", "name") VALUES ('es_419', 'español latinoamericano');
INSERT INTO "country" ("id", "name") VALUES ('eo', 'esperanto');
INSERT INTO "country" ("id", "name") VALUES ('et', 'estoniano');
INSERT INTO "country" ("id", "name") VALUES ('eu', 'éuscaro');
INSERT INTO "country" ("id", "name") VALUES ('egy', 'exipcio antigo');
INSERT INTO "country" ("id", "name") VALUES ('fo', 'faroés');
INSERT INTO "country" ("id", "name") VALUES ('fil', 'filipino');
INSERT INTO "country" ("id", "name") VALUES ('fi', 'finés');
INSERT INTO "country" ("id", "name") VALUES ('fj', 'fixiano');
INSERT INTO "country" ("id", "name") VALUES ('nl_BE', 'flamenco');
INSERT INTO "country" ("id", "name") VALUES ('fr', 'francés');
INSERT INTO "country" ("id", "name") VALUES ('fr_CA', 'francés canadiano');
INSERT INTO "country" ("id", "name") VALUES ('fr_CH', 'francés suízo');
INSERT INTO "country" ("id", "name") VALUES ('fy', 'frisón');
INSERT INTO "country" ("id", "name") VALUES ('gd', 'gaélico escocés');
INSERT INTO "country" ("id", "name") VALUES ('gl', 'galego');
INSERT INTO "country" ("id", "name") VALUES ('cy', 'galés');
INSERT INTO "country" ("id", "name") VALUES ('el', 'grego');
INSERT INTO "country" ("id", "name") VALUES ('grc', 'grego antigo');
INSERT INTO "country" ("id", "name") VALUES ('gn', 'guaraní');
INSERT INTO "country" ("id", "name") VALUES ('gu', 'guxaratiano');
INSERT INTO "country" ("id", "name") VALUES ('ht', 'haitiano');
INSERT INTO "country" ("id", "name") VALUES ('ha', 'hausa');
INSERT INTO "country" ("id", "name") VALUES ('haw', 'hawaiano');
INSERT INTO "country" ("id", "name") VALUES ('he', 'hebreo');
INSERT INTO "country" ("id", "name") VALUES ('hi', 'hindi');
INSERT INTO "country" ("id", "name") VALUES ('nl', 'holandés');
INSERT INTO "country" ("id", "name") VALUES ('hu', 'húngaro');
INSERT INTO "country" ("id", "name") VALUES ('efi', 'ibibio');
INSERT INTO "country" ("id", "name") VALUES ('ig', 'ibo');
INSERT INTO "country" ("id", "name") VALUES ('id', 'indonesio');
INSERT INTO "country" ("id", "name") VALUES ('en', 'inglés');
INSERT INTO "country" ("id", "name") VALUES ('en_US', 'inglés americano');
INSERT INTO "country" ("id", "name") VALUES ('en_AU', 'inglés australiano');
INSERT INTO "country" ("id", "name") VALUES ('en_GB', 'inglés británico');
INSERT INTO "country" ("id", "name") VALUES ('en_CA', 'inglés canadiano');
INSERT INTO "country" ("id", "name") VALUES ('ia', 'interlingua');
INSERT INTO "country" ("id", "name") VALUES ('yo', 'ioruba');
INSERT INTO "country" ("id", "name") VALUES ('ga', 'irlandés');
INSERT INTO "country" ("id", "name") VALUES ('is', 'islandés');
INSERT INTO "country" ("id", "name") VALUES ('it', 'italiano');
INSERT INTO "country" ("id", "name") VALUES ('kn', 'kannada');
INSERT INTO "country" ("id", "name") VALUES ('ku', 'kurdo');
INSERT INTO "country" ("id", "name") VALUES ('ky', 'kyrgiz');
INSERT INTO "country" ("id", "name") VALUES ('lo', 'laotiano');
INSERT INTO "country" ("id", "name") VALUES ('la', 'latín');
INSERT INTO "country" ("id", "name") VALUES ('lv', 'letón');
INSERT INTO "country" ("id", "name") VALUES ('ln', 'lingala');
INSERT INTO "country" ("id", "name") VALUES ('afa', 'lingua afro-asiática');
INSERT INTO "country" ("id", "name") VALUES ('alg', 'lingua algonquina');
INSERT INTO "country" ("id", "name") VALUES ('tut', 'lingua altaica');
INSERT INTO "country" ("id", "name") VALUES ('apa', 'lingua apache');
INSERT INTO "country" ("id", "name") VALUES ('art', 'lingua artificial');
INSERT INTO "country" ("id", "name") VALUES ('aus', 'lingua australiana');
INSERT INTO "country" ("id", "name") VALUES ('bat', 'lingua báltica');
INSERT INTO "country" ("id", "name") VALUES ('cau', 'lingua caucásica');
INSERT INTO "country" ("id", "name") VALUES ('cel', 'lingua céltica');
INSERT INTO "country" ("id", "name") VALUES ('sgn', 'lingua de signos');
INSERT INTO "country" ("id", "name") VALUES ('und', 'lingua descoñecida ou non válida');
INSERT INTO "country" ("id", "name") VALUES ('ssa', 'lingua do nilo-sáhara');
INSERT INTO "country" ("id", "name") VALUES ('sla', 'lingua eslávica');
INSERT INTO "country" ("id", "name") VALUES ('phi', 'lingua filipina');
INSERT INTO "country" ("id", "name") VALUES ('fiu', 'lingua finno-úgrica');
INSERT INTO "country" ("id", "name") VALUES ('cai', 'lingua india centroamericana');
INSERT INTO "country" ("id", "name") VALUES ('nai', 'lingua india norteamericana');
INSERT INTO "country" ("id", "name") VALUES ('sai', 'lingua india sudamericana');
INSERT INTO "country" ("id", "name") VALUES ('inc', 'lingua índica');
INSERT INTO "country" ("id", "name") VALUES ('ine', 'lingua indoeuropea');
INSERT INTO "country" ("id", "name") VALUES ('mis', 'lingua miscelánea');
INSERT INTO "country" ("id", "name") VALUES ('nub', 'lingua nubia');
INSERT INTO "country" ("id", "name") VALUES ('roa', 'lingua románica');
INSERT INTO "country" ("id", "name") VALUES ('sem', 'lingua semita');
INSERT INTO "country" ("id", "name") VALUES ('gem', 'lingua xermánica');
INSERT INTO "country" ("id", "name") VALUES ('lt', 'lituano');
INSERT INTO "country" ("id", "name") VALUES ('lb', 'luxemburgués');
INSERT INTO "country" ("id", "name") VALUES ('mk', 'macedonio');
INSERT INTO "country" ("id", "name") VALUES ('ml', 'malabar');
INSERT INTO "country" ("id", "name") VALUES ('ms', 'malaio');
INSERT INTO "country" ("id", "name") VALUES ('mg', 'malgaxe');
INSERT INTO "country" ("id", "name") VALUES ('mt', 'maltés');
INSERT INTO "country" ("id", "name") VALUES ('mi', 'maorí');
INSERT INTO "country" ("id", "name") VALUES ('mr', 'marathi');
INSERT INTO "country" ("id", "name") VALUES ('mn', 'mongol');
INSERT INTO "country" ("id", "name") VALUES ('nd', 'ndebele do norte');
INSERT INTO "country" ("id", "name") VALUES ('ne', 'nepalí');
INSERT INTO "country" ("id", "name") VALUES ('no', 'noruegués');
INSERT INTO "country" ("id", "name") VALUES ('nb', 'noruegués bokmal');
INSERT INTO "country" ("id", "name") VALUES ('nn', 'noruegués nynorsk');
INSERT INTO "country" ("id", "name") VALUES ('oc', 'occitano');
INSERT INTO "country" ("id", "name") VALUES ('or', 'oriya');
INSERT INTO "country" ("id", "name") VALUES ('os', 'osetio');
INSERT INTO "country" ("id", "name") VALUES ('ps', 'paxtún');
INSERT INTO "country" ("id", "name") VALUES ('fa', 'persa');
INSERT INTO "country" ("id", "name") VALUES ('pl', 'polaco');
INSERT INTO "country" ("id", "name") VALUES ('pt', 'portugués');
INSERT INTO "country" ("id", "name") VALUES ('pt_BR', 'portugués brasileiro');
INSERT INTO "country" ("id", "name") VALUES ('pt_PT', 'portugués ibérico');
INSERT INTO "country" ("id", "name") VALUES ('pa', 'punjabi');
INSERT INTO "country" ("id", "name") VALUES ('qu', 'quechua');
INSERT INTO "country" ("id", "name") VALUES ('rm', 'romanche');
INSERT INTO "country" ("id", "name") VALUES ('ro', 'romanés');
INSERT INTO "country" ("id", "name") VALUES ('rw', 'ruandés');
INSERT INTO "country" ("id", "name") VALUES ('rn', 'rundi');
INSERT INTO "country" ("id", "name") VALUES ('ru', 'ruso');
INSERT INTO "country" ("id", "name") VALUES ('se', 'sami do norte');
INSERT INTO "country" ("id", "name") VALUES ('sm', 'samoano');
INSERT INTO "country" ("id", "name") VALUES ('sg', 'sango');
INSERT INTO "country" ("id", "name") VALUES ('sa', 'sánscrito');
INSERT INTO "country" ("id", "name") VALUES ('zxx', 'sen contido lingüístico');
INSERT INTO "country" ("id", "name") VALUES ('sr', 'serbio');
INSERT INTO "country" ("id", "name") VALUES ('sh', 'serbocroata');
INSERT INTO "country" ("id", "name") VALUES ('st', 'sesoto');
INSERT INTO "country" ("id", "name") VALUES ('sn', 'shona');
INSERT INTO "country" ("id", "name") VALUES ('sd', 'sindhi');
INSERT INTO "country" ("id", "name") VALUES ('so', 'somalí');
INSERT INTO "country" ("id", "name") VALUES ('su', 'sondanés');
INSERT INTO "country" ("id", "name") VALUES ('sv', 'sueco');
INSERT INTO "country" ("id", "name") VALUES ('sw', 'swahili');
INSERT INTO "country" ("id", "name") VALUES ('ss', 'swati');
INSERT INTO "country" ("id", "name") VALUES ('tl', 'tagalo');
INSERT INTO "country" ("id", "name") VALUES ('ty', 'tahitiano');
INSERT INTO "country" ("id", "name") VALUES ('th', 'tailandés');
INSERT INTO "country" ("id", "name") VALUES ('ta', 'tamil');
INSERT INTO "country" ("id", "name") VALUES ('tt', 'tártaro');
INSERT INTO "country" ("id", "name") VALUES ('tg', 'taxico');
INSERT INTO "country" ("id", "name") VALUES ('te', 'telugu');
INSERT INTO "country" ("id", "name") VALUES ('tet', 'tetún');
INSERT INTO "country" ("id", "name") VALUES ('bo', 'tibetano');
INSERT INTO "country" ("id", "name") VALUES ('ti', 'tigriña');
INSERT INTO "country" ("id", "name") VALUES ('tpi', 'tok pisin');
INSERT INTO "country" ("id", "name") VALUES ('to', 'tongano');
INSERT INTO "country" ("id", "name") VALUES ('tn', 'tswana');
INSERT INTO "country" ("id", "name") VALUES ('tr', 'turco');
INSERT INTO "country" ("id", "name") VALUES ('tk', 'turcomano');
INSERT INTO "country" ("id", "name") VALUES ('uk', 'ucraíno');
INSERT INTO "country" ("id", "name") VALUES ('ug', 'uigur');
INSERT INTO "country" ("id", "name") VALUES ('ur', 'urdú');
INSERT INTO "country" ("id", "name") VALUES ('uz', 'uzbeco');
INSERT INTO "country" ("id", "name") VALUES ('ve', 'venda');
INSERT INTO "country" ("id", "name") VALUES ('vi', 'vietnamita');
INSERT INTO "country" ("id", "name") VALUES ('wo', 'wólof');
INSERT INTO "country" ("id", "name") VALUES ('ja', 'xaponés');
INSERT INTO "country" ("id", "name") VALUES ('jv', 'xavanés');
INSERT INTO "country" ("id", "name") VALUES ('ka', 'xeorxiano');
INSERT INTO "country" ("id", "name") VALUES ('xh', 'xhosa');
INSERT INTO "country" ("id", "name") VALUES ('ts', 'xitsonga');
INSERT INTO "country" ("id", "name") VALUES ('yi', 'yiddish');
INSERT INTO "country" ("id", "name") VALUES ('zu', 'zulú');
