CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('ab', 'אבחזית');
INSERT INTO "country" ("id", "name") VALUES ('ae', 'אבסטן');
INSERT INTO "country" ("id", "name") VALUES ('ady', 'אדיגית');
INSERT INTO "country" ("id", "name") VALUES ('uga', 'אוגריתית');
INSERT INTO "country" ("id", "name") VALUES ('awa', 'אוואדית');
INSERT INTO "country" ("id", "name") VALUES ('uz', 'אוזבקית');
INSERT INTO "country" ("id", "name") VALUES ('ug', 'אויגהור');
INSERT INTO "country" ("id", "name") VALUES ('os', 'אוסטית');
INSERT INTO "country" ("id", "name") VALUES ('map', 'אוסטרונזית');
INSERT INTO "country" ("id", "name") VALUES ('oc', 'אוקסיטנית');
INSERT INTO "country" ("id", "name") VALUES ('uk', 'אוקראינית');
INSERT INTO "country" ("id", "name") VALUES ('ur', 'אורדו');
INSERT INTO "country" ("id", "name") VALUES ('or', 'אוריה');
INSERT INTO "country" ("id", "name") VALUES ('az', 'אזרית');
INSERT INTO "country" ("id", "name") VALUES ('ig', 'איגבו');
INSERT INTO "country" ("id", "name") VALUES ('io', 'אידו');
INSERT INTO "country" ("id", "name") VALUES ('it', 'איטלקית');
INSERT INTO "country" ("id", "name") VALUES ('ay', 'איימארית');
INSERT INTO "country" ("id", "name") VALUES ('inh', 'אינגושית');
INSERT INTO "country" ("id", "name") VALUES ('id', 'אינדונזית');
INSERT INTO "country" ("id", "name") VALUES ('ain', 'אינו');
INSERT INTO "country" ("id", "name") VALUES ('iu', 'אינוקטיטוט');
INSERT INTO "country" ("id", "name") VALUES ('ie', 'אינטרלינגה');
INSERT INTO "country" ("id", "name") VALUES ('ia', '‏אינטרלינגואה');
INSERT INTO "country" ("id", "name") VALUES ('is', 'איסלנדית');
INSERT INTO "country" ("id", "name") VALUES ('ga', 'אירית');
INSERT INTO "country" ("id", "name") VALUES ('sga', 'אירית עתיקה');
INSERT INTO "country" ("id", "name") VALUES ('mga', 'אירית תיכונה');
INSERT INTO "country" ("id", "name") VALUES ('akk', 'אכדית');
INSERT INTO "country" ("id", "name") VALUES ('sq', 'אלבנית');
INSERT INTO "country" ("id", "name") VALUES ('am', 'אמהרית');
INSERT INTO "country" ("id", "name") VALUES ('en', 'אנגלית');
INSERT INTO "country" ("id", "name") VALUES ('en_AU', 'אנגלית אוסטרלית');
INSERT INTO "country" ("id", "name") VALUES ('en_US', 'אנגלית אמריקנית');
INSERT INTO "country" ("id", "name") VALUES ('en_GB', 'אנגלית בריטית');
INSERT INTO "country" ("id", "name") VALUES ('ang', 'אנגלית עתיקה');
INSERT INTO "country" ("id", "name") VALUES ('en_CA', 'אנגלית קנדית');
INSERT INTO "country" ("id", "name") VALUES ('enm', 'אנגלית תיכונה');
INSERT INTO "country" ("id", "name") VALUES ('as', 'אסאמית');
INSERT INTO "country" ("id", "name") VALUES ('et', 'אסטונית');
INSERT INTO "country" ("id", "name") VALUES ('ast', 'אסטורית');
INSERT INTO "country" ("id", "name") VALUES ('eo', 'אספרנטו');
INSERT INTO "country" ("id", "name") VALUES ('aa', 'אפארית');
INSERT INTO "country" ("id", "name") VALUES ('efi', 'אפיק');
INSERT INTO "country" ("id", "name") VALUES ('afh', 'אפריהילי');
INSERT INTO "country" ("id", "name") VALUES ('af', 'אפריקאנס');
INSERT INTO "country" ("id", "name") VALUES ('ak', 'אקאן');
INSERT INTO "country" ("id", "name") VALUES ('rup', 'ארומנית');
INSERT INTO "country" ("id", "name") VALUES ('arc', 'ארמית');
INSERT INTO "country" ("id", "name") VALUES ('sam', 'ארמית שומרונית');
INSERT INTO "country" ("id", "name") VALUES ('hy', 'ארמנית');
INSERT INTO "country" ("id", "name") VALUES ('bal', 'באלוצ׳י');
INSERT INTO "country" ("id", "name") VALUES ('bg', 'בולגרית');
INSERT INTO "country" ("id", "name") VALUES ('bs', 'בוסנית');
INSERT INTO "country" ("id", "name") VALUES ('my', 'בורמזית');
INSERT INTO "country" ("id", "name") VALUES ('bej', 'בז׳ה');
INSERT INTO "country" ("id", "name") VALUES ('bh', 'ביהארי');
INSERT INTO "country" ("id", "name") VALUES ('bi', 'ביסלמה');
INSERT INTO "country" ("id", "name") VALUES ('be', 'בלארוסית');
INSERT INTO "country" ("id", "name") VALUES ('ban', 'בלינזית');
INSERT INTO "country" ("id", "name") VALUES ('bn', 'בנגלית');
INSERT INTO "country" ("id", "name") VALUES ('bnt', 'בנטו');
INSERT INTO "country" ("id", "name") VALUES ('eu', 'בסקית');
INSERT INTO "country" ("id", "name") VALUES ('ber', 'ברברית');
INSERT INTO "country" ("id", "name") VALUES ('br', 'ברטונית');
INSERT INTO "country" ("id", "name") VALUES ('ba', 'בשקירית');
INSERT INTO "country" ("id", "name") VALUES ('wo', 'ג׳ולוף');
INSERT INTO "country" ("id", "name") VALUES ('gd', 'גאלית סקוטית');
INSERT INTO "country" ("id", "name") VALUES ('gn', 'גוארני');
INSERT INTO "country" ("id", "name") VALUES ('gu', 'גוג׳ראטית');
INSERT INTO "country" ("id", "name") VALUES ('gon', 'גונדי');
INSERT INTO "country" ("id", "name") VALUES ('got', 'גותית');
INSERT INTO "country" ("id", "name") VALUES ('ka', 'גיאורגית');
INSERT INTO "country" ("id", "name") VALUES ('gl', 'גליציאנית');
INSERT INTO "country" ("id", "name") VALUES ('gez', 'געז');
INSERT INTO "country" ("id", "name") VALUES ('de', 'גרמנית');
INSERT INTO "country" ("id", "name") VALUES ('de_AT', 'גרמנית אוסטרית');
INSERT INTO "country" ("id", "name") VALUES ('gsw', 'גרמנית שוויצרית');
INSERT INTO "country" ("id", "name") VALUES ('de_CH', 'גרמנית שוויצרית (גבוהה)');
INSERT INTO "country" ("id", "name") VALUES ('nds', 'גרמנית תחתית');
INSERT INTO "country" ("id", "name") VALUES ('doi', 'דוגרי');
INSERT INTO "country" ("id", "name") VALUES ('dz', 'דזונקה');
INSERT INTO "country" ("id", "name") VALUES ('dv', 'דיבהי');
INSERT INTO "country" ("id", "name") VALUES ('del', 'דלאוור');
INSERT INTO "country" ("id", "name") VALUES ('da', 'דנית');
INSERT INTO "country" ("id", "name") VALUES ('dak', 'דקוטה');
INSERT INTO "country" ("id", "name") VALUES ('ha', 'האוסה');
INSERT INTO "country" ("id", "name") VALUES ('ht', 'האיטית');
INSERT INTO "country" ("id", "name") VALUES ('ho', 'הארי מוטו');
INSERT INTO "country" ("id", "name") VALUES ('haw', 'הוואית');
INSERT INTO "country" ("id", "name") VALUES ('nl', 'הולנדית');
INSERT INTO "country" ("id", "name") VALUES ('dum', 'הולנדית תיכונה');
INSERT INTO "country" ("id", "name") VALUES ('hu', 'הונגרית');
INSERT INTO "country" ("id", "name") VALUES ('hi', 'הינדי');
INSERT INTO "country" ("id", "name") VALUES ('vo', '‏וולאפיק');
INSERT INTO "country" ("id", "name") VALUES ('cy', 'וולשית');
INSERT INTO "country" ("id", "name") VALUES ('ve', 'וונדה');
INSERT INTO "country" ("id", "name") VALUES ('vi', 'ויאטנמית');
INSERT INTO "country" ("id", "name") VALUES ('zap', 'זאפוטק');
INSERT INTO "country" ("id", "name") VALUES ('zu', 'זולו');
INSERT INTO "country" ("id", "name") VALUES ('zen', 'זנאגה');
INSERT INTO "country" ("id", "name") VALUES ('hit', 'חיתית');
INSERT INTO "country" ("id", "name") VALUES ('tg', 'טג׳יקית');
INSERT INTO "country" ("id", "name") VALUES ('tl', 'טגלוג');
INSERT INTO "country" ("id", "name") VALUES ('ty', 'טהיטית');
INSERT INTO "country" ("id", "name") VALUES ('tw', 'טווי');
INSERT INTO "country" ("id", "name") VALUES ('to', 'טונגאית');
INSERT INTO "country" ("id", "name") VALUES ('tpi', 'טוק פיסין');
INSERT INTO "country" ("id", "name") VALUES ('tr', 'טורקית');
INSERT INTO "country" ("id", "name") VALUES ('ota', 'טורקית עותומנית');
INSERT INTO "country" ("id", "name") VALUES ('tk', 'טורקמנית');
INSERT INTO "country" ("id", "name") VALUES ('tet', 'טטום');
INSERT INTO "country" ("id", "name") VALUES ('tt', 'טטרית');
INSERT INTO "country" ("id", "name") VALUES ('crh', 'טטרית של קרים');
INSERT INTO "country" ("id", "name") VALUES ('bo', 'טיבטית');
INSERT INTO "country" ("id", "name") VALUES ('ti', 'טיגרינאית');
INSERT INTO "country" ("id", "name") VALUES ('te', 'טלוגו');
INSERT INTO "country" ("id", "name") VALUES ('ta', 'טמילית');
INSERT INTO "country" ("id", "name") VALUES ('ts', 'טסונגה');
INSERT INTO "country" ("id", "name") VALUES ('jv', 'יאוונית');
INSERT INTO "country" ("id", "name") VALUES ('yap', 'יאפזית');
INSERT INTO "country" ("id", "name") VALUES ('el', 'יוונית');
INSERT INTO "country" ("id", "name") VALUES ('grc', 'יוונית עתיקה');
INSERT INTO "country" ("id", "name") VALUES ('yo', 'יורובה');
INSERT INTO "country" ("id", "name") VALUES ('yi', 'יידיש');
INSERT INTO "country" ("id", "name") VALUES ('ja', 'יפנית');
INSERT INTO "country" ("id", "name") VALUES ('ku', 'כורדית');
INSERT INTO "country" ("id", "name") VALUES ('lo', 'לאית');
INSERT INTO "country" ("id", "name") VALUES ('se', 'לאפית צפונית');
INSERT INTO "country" ("id", "name") VALUES ('lad', 'לדינו');
INSERT INTO "country" ("id", "name") VALUES ('lb', 'לוקסמבורגית');
INSERT INTO "country" ("id", "name") VALUES ('lv', 'לטבית');
INSERT INTO "country" ("id", "name") VALUES ('la', 'לטינית');
INSERT INTO "country" ("id", "name") VALUES ('lt', 'ליטאית');
INSERT INTO "country" ("id", "name") VALUES ('ln', 'לינגלה');
INSERT INTO "country" ("id", "name") VALUES ('zxx', 'ללא תוכן לשוני');
INSERT INTO "country" ("id", "name") VALUES ('mag', 'מאגאהית');
INSERT INTO "country" ("id", "name") VALUES ('mi', 'מאורית');
INSERT INTO "country" ("id", "name") VALUES ('myn', 'מאיה');
INSERT INTO "country" ("id", "name") VALUES ('mai', 'מאיטילית');
INSERT INTO "country" ("id", "name") VALUES ('gv', 'מאנית');
INSERT INTO "country" ("id", "name") VALUES ('mas', 'מאסאית');
INSERT INTO "country" ("id", "name") VALUES ('mo', 'מולדבית');
INSERT INTO "country" ("id", "name") VALUES ('mn', 'מונגולית');
INSERT INTO "country" ("id", "name") VALUES ('ml', 'מלאיאלם');
INSERT INTO "country" ("id", "name") VALUES ('ms', 'מלאית');
INSERT INTO "country" ("id", "name") VALUES ('mg', 'מלגשית');
INSERT INTO "country" ("id", "name") VALUES ('mt', 'מלטית');
INSERT INTO "country" ("id", "name") VALUES ('mni', 'מניפורית');
INSERT INTO "country" ("id", "name") VALUES ('egy', 'מצרית עתיקה');
INSERT INTO "country" ("id", "name") VALUES ('mk', 'מקדונית');
INSERT INTO "country" ("id", "name") VALUES ('mr', 'מרטהי');
INSERT INTO "country" ("id", "name") VALUES ('nah', 'נאהואטל');
INSERT INTO "country" ("id", "name") VALUES ('na', 'נאורית');
INSERT INTO "country" ("id", "name") VALUES ('nv', 'נבחו');
INSERT INTO "country" ("id", "name") VALUES ('nwc', 'נווארית קלאסית');
INSERT INTO "country" ("id", "name") VALUES ('no', 'נורבגית');
INSERT INTO "country" ("id", "name") VALUES ('nn', 'נורבגית חדשה');
INSERT INTO "country" ("id", "name") VALUES ('nb', '‏נורבגית ספרותית');
INSERT INTO "country" ("id", "name") VALUES ('non', '‏נורדית עתיקה');
INSERT INTO "country" ("id", "name") VALUES ('ny', 'ניאנג\'ה');
INSERT INTO "country" ("id", "name") VALUES ('ne', 'נפאלית');
INSERT INTO "country" ("id", "name") VALUES ('nap', 'נפוליטנית');
INSERT INTO "country" ("id", "name") VALUES ('sat', 'סאנטלי');
INSERT INTO "country" ("id", "name") VALUES ('su', 'סודנית');
INSERT INTO "country" ("id", "name") VALUES ('sw', 'סווהילית');
INSERT INTO "country" ("id", "name") VALUES ('nso', 'סוטו הצפונית');
INSERT INTO "country" ("id", "name") VALUES ('so', 'סומלית');
INSERT INTO "country" ("id", "name") VALUES ('syr', 'סורית');
INSERT INTO "country" ("id", "name") VALUES ('sid', 'סידמו');
INSERT INTO "country" ("id", "name") VALUES ('sd', 'סינדהית');
INSERT INTO "country" ("id", "name") VALUES ('si', 'סינהלה');
INSERT INTO "country" ("id", "name") VALUES ('zh', 'סינית');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hans', 'סינית (מפושטת)');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hant', 'סינית מסורתית');
INSERT INTO "country" ("id", "name") VALUES ('ss', 'סיסוואטי');
INSERT INTO "country" ("id", "name") VALUES ('scn', 'סיציליאנית');
INSERT INTO "country" ("id", "name") VALUES ('den', 'סלאבית');
INSERT INTO "country" ("id", "name") VALUES ('cu', 'סלאבית כנסייתית עתיקה');
INSERT INTO "country" ("id", "name") VALUES ('sl', 'סלובנית');
INSERT INTO "country" ("id", "name") VALUES ('sk', 'סלובקית');
INSERT INTO "country" ("id", "name") VALUES ('sm', 'סמואית');
INSERT INTO "country" ("id", "name") VALUES ('sg', 'סנגו');
INSERT INTO "country" ("id", "name") VALUES ('sa', 'סנסקריט');
INSERT INTO "country" ("id", "name") VALUES ('st', 'ססות׳ו');
INSERT INTO "country" ("id", "name") VALUES ('es', 'ספרדית');
INSERT INTO "country" ("id", "name") VALUES ('es_ES', 'ספרדית איברית');
INSERT INTO "country" ("id", "name") VALUES ('es_419', 'ספרדית לטינו־אמריקאית');
INSERT INTO "country" ("id", "name") VALUES ('sco', 'סקוטית');
INSERT INTO "country" ("id", "name") VALUES ('sh', 'סרבו-קרואטית');
INSERT INTO "country" ("id", "name") VALUES ('sr', 'סרבית');
INSERT INTO "country" ("id", "name") VALUES ('sc', 'סרדינית');
INSERT INTO "country" ("id", "name") VALUES ('he', 'עברית');
INSERT INTO "country" ("id", "name") VALUES ('elx', 'עילמית');
INSERT INTO "country" ("id", "name") VALUES ('ar', 'ערבית');
INSERT INTO "country" ("id", "name") VALUES ('jrb', 'ערבית יהודית');
INSERT INTO "country" ("id", "name") VALUES ('fo', 'פארואזית');
INSERT INTO "country" ("id", "name") VALUES ('ps', 'פאשטו');
INSERT INTO "country" ("id", "name") VALUES ('pl', 'פולנית');
INSERT INTO "country" ("id", "name") VALUES ('pt_BR', 'פורטוגזית ברזילאית');
INSERT INTO "country" ("id", "name") VALUES ('pt', 'פורטוגלית');
INSERT INTO "country" ("id", "name") VALUES ('pt_PT', 'פורטוגלית אירופית');
INSERT INTO "country" ("id", "name") VALUES ('fj', 'פיג׳ית');
INSERT INTO "country" ("id", "name") VALUES ('fil', 'פיליפינית');
INSERT INTO "country" ("id", "name") VALUES ('fi', 'פינית');
INSERT INTO "country" ("id", "name") VALUES ('nl_BE', 'פלמית');
INSERT INTO "country" ("id", "name") VALUES ('pa', 'פנג׳אבית');
INSERT INTO "country" ("id", "name") VALUES ('phn', 'פניקית');
INSERT INTO "country" ("id", "name") VALUES ('fy', 'פריזית');
INSERT INTO "country" ("id", "name") VALUES ('frr', 'פריזית צפונית');
INSERT INTO "country" ("id", "name") VALUES ('fa', 'פרסית');
INSERT INTO "country" ("id", "name") VALUES ('jpr', 'פרסית יהודית');
INSERT INTO "country" ("id", "name") VALUES ('peo', 'פרסית עתיקה');
INSERT INTO "country" ("id", "name") VALUES ('chg', 'צ׳אגאטאי');
INSERT INTO "country" ("id", "name") VALUES ('cs', 'צ׳כית');
INSERT INTO "country" ("id", "name") VALUES ('ce', 'צ׳צ׳נית');
INSERT INTO "country" ("id", "name") VALUES ('chr', 'צ׳רוקי');
INSERT INTO "country" ("id", "name") VALUES ('tn', 'צוואנה');
INSERT INTO "country" ("id", "name") VALUES ('nd', 'צפון נדבלה');
INSERT INTO "country" ("id", "name") VALUES ('fr', 'צרפתית');
INSERT INTO "country" ("id", "name") VALUES ('fro', 'צרפתית עתיקה');
INSERT INTO "country" ("id", "name") VALUES ('fr_CA', 'צרפתית קנדית');
INSERT INTO "country" ("id", "name") VALUES ('fr_CH', 'צרפתית שוויצרית');
INSERT INTO "country" ("id", "name") VALUES ('frm', 'צרפתית תיכונה');
INSERT INTO "country" ("id", "name") VALUES ('cad', 'קאדו');
INSERT INTO "country" ("id", "name") VALUES ('kl', 'קאלאליסוטית');
INSERT INTO "country" ("id", "name") VALUES ('ceb', 'קבואנו');
INSERT INTO "country" ("id", "name") VALUES ('kab', 'קבילה');
INSERT INTO "country" ("id", "name") VALUES ('cop', 'קופטית');
INSERT INTO "country" ("id", "name") VALUES ('ko', 'קוריאנית');
INSERT INTO "country" ("id", "name") VALUES ('kw', 'קורנית');
INSERT INTO "country" ("id", "name") VALUES ('co', 'קורסיקנית');
INSERT INTO "country" ("id", "name") VALUES ('kk', 'קזחית');
INSERT INTO "country" ("id", "name") VALUES ('ca', 'קטלאנית');
INSERT INTO "country" ("id", "name") VALUES ('rw', 'קינירואנדה');
INSERT INTO "country" ("id", "name") VALUES ('ky', 'קירגיזית');
INSERT INTO "country" ("id", "name") VALUES ('rn', 'קירונדי');
INSERT INTO "country" ("id", "name") VALUES ('tlh', 'קלינגון');
INSERT INTO "country" ("id", "name") VALUES ('km', 'קמרית');
INSERT INTO "country" ("id", "name") VALUES ('kn', 'קנאדה');
INSERT INTO "country" ("id", "name") VALUES ('yue', 'קנטונזית');
INSERT INTO "country" ("id", "name") VALUES ('xh', 'קסוסה');
INSERT INTO "country" ("id", "name") VALUES ('qu', 'קצ\'ואה');
INSERT INTO "country" ("id", "name") VALUES ('hr', 'קרואטית');
INSERT INTO "country" ("id", "name") VALUES ('ks', 'קשמירית');
INSERT INTO "country" ("id", "name") VALUES ('raj', 'ראג׳סטן');
INSERT INTO "country" ("id", "name") VALUES ('rom', 'רומאנית');
INSERT INTO "country" ("id", "name") VALUES ('rm', 'רומאנש');
INSERT INTO "country" ("id", "name") VALUES ('ro', 'רומנית');
INSERT INTO "country" ("id", "name") VALUES ('ru', 'רוסית');
INSERT INTO "country" ("id", "name") VALUES ('sv', 'שוודית');
INSERT INTO "country" ("id", "name") VALUES ('sux', 'שומרית');
INSERT INTO "country" ("id", "name") VALUES ('sn', 'שונה');
INSERT INTO "country" ("id", "name") VALUES ('aus', 'שפה אוסטרלית');
INSERT INTO "country" ("id", "name") VALUES ('mis', 'שפה אחרת');
INSERT INTO "country" ("id", "name") VALUES ('sai', 'שפה אינדיאנית דרום אמריקאית');
INSERT INTO "country" ("id", "name") VALUES ('cai', 'שפה אינדיאנית מרכז-אמריקאית');
INSERT INTO "country" ("id", "name") VALUES ('nai', 'שפה אינדיאנית צפון-אמריקאית');
INSERT INTO "country" ("id", "name") VALUES ('ira', 'שפה איראנית');
INSERT INTO "country" ("id", "name") VALUES ('apa', 'שפה אפאצ׳ית');
INSERT INTO "country" ("id", "name") VALUES ('afa', 'שפה אפרו-אסייתית');
INSERT INTO "country" ("id", "name") VALUES ('gem', 'שפה גרמאנית');
INSERT INTO "country" ("id", "name") VALUES ('ine', 'שפה הודו-אירופית');
INSERT INTO "country" ("id", "name") VALUES ('und', 'שפה לא ידועה או לא תקפה');
INSERT INTO "country" ("id", "name") VALUES ('art', 'שפה מלאכותית');
INSERT INTO "country" ("id", "name") VALUES ('sit', 'שפה סינו־טיבטית');
INSERT INTO "country" ("id", "name") VALUES ('sla', 'שפה סלאבית');
INSERT INTO "country" ("id", "name") VALUES ('phi', 'שפה פיליפינית');
INSERT INTO "country" ("id", "name") VALUES ('cau', 'שפה קווקזית');
INSERT INTO "country" ("id", "name") VALUES ('cel', 'שפה קלטית');
INSERT INTO "country" ("id", "name") VALUES ('crp', 'שפה קראולית או פידג׳אנית');
INSERT INTO "country" ("id", "name") VALUES ('sem', 'שפה שמית');
INSERT INTO "country" ("id", "name") VALUES ('bat', 'שפות בלטיות');
INSERT INTO "country" ("id", "name") VALUES ('nub', 'שפות נבטיות');
INSERT INTO "country" ("id", "name") VALUES ('smi', 'שפת סאמי');
INSERT INTO "country" ("id", "name") VALUES ('sgn', 'שפת סימנים');
INSERT INTO "country" ("id", "name") VALUES ('th', 'תאי');
