CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('ab', 'Abkhazian');
INSERT INTO `country` (`id`, `name`) VALUES ('ace', 'Achinese');
INSERT INTO `country` (`id`, `name`) VALUES ('ach', 'Acoli');
INSERT INTO `country` (`id`, `name`) VALUES ('ada', 'Adangme');
INSERT INTO `country` (`id`, `name`) VALUES ('ady', 'Adyghe');
INSERT INTO `country` (`id`, `name`) VALUES ('aa', 'Afar');
INSERT INTO `country` (`id`, `name`) VALUES ('afh', 'Afrihili');
INSERT INTO `country` (`id`, `name`) VALUES ('af', 'Afrikaans');
INSERT INTO `country` (`id`, `name`) VALUES ('afa', 'Afro-Asiatic Language');
INSERT INTO `country` (`id`, `name`) VALUES ('ain', 'Ainu');
INSERT INTO `country` (`id`, `name`) VALUES ('ak', 'Akan');
INSERT INTO `country` (`id`, `name`) VALUES ('akk', 'Akkadian');
INSERT INTO `country` (`id`, `name`) VALUES ('sq', 'Albanian');
INSERT INTO `country` (`id`, `name`) VALUES ('ale', 'Aleut');
INSERT INTO `country` (`id`, `name`) VALUES ('alg', 'Algonquian Language');
INSERT INTO `country` (`id`, `name`) VALUES ('tut', 'Altaic Language');
INSERT INTO `country` (`id`, `name`) VALUES ('am', 'Amharic');
INSERT INTO `country` (`id`, `name`) VALUES ('egy', 'Ancient Egyptian');
INSERT INTO `country` (`id`, `name`) VALUES ('grc', 'Ancient Greek');
INSERT INTO `country` (`id`, `name`) VALUES ('anp', 'Angika');
INSERT INTO `country` (`id`, `name`) VALUES ('apa', 'Apache Language');
INSERT INTO `country` (`id`, `name`) VALUES ('ar', 'Arabic');
INSERT INTO `country` (`id`, `name`) VALUES ('an', 'Aragonese');
INSERT INTO `country` (`id`, `name`) VALUES ('arc', 'Aramaic');
INSERT INTO `country` (`id`, `name`) VALUES ('arp', 'Arapaho');
INSERT INTO `country` (`id`, `name`) VALUES ('arn', 'Araucanian');
INSERT INTO `country` (`id`, `name`) VALUES ('arw', 'Arawak');
INSERT INTO `country` (`id`, `name`) VALUES ('hy', 'Armenian');
INSERT INTO `country` (`id`, `name`) VALUES ('rup', 'Aromanian');
INSERT INTO `country` (`id`, `name`) VALUES ('art', 'Artificial Language');
INSERT INTO `country` (`id`, `name`) VALUES ('as', 'Assamese');
INSERT INTO `country` (`id`, `name`) VALUES ('ast', 'Asturian');
INSERT INTO `country` (`id`, `name`) VALUES ('ath', 'Athapascan Language');
INSERT INTO `country` (`id`, `name`) VALUES ('cch', 'Atsam');
INSERT INTO `country` (`id`, `name`) VALUES ('en_AU', 'Australian English');
INSERT INTO `country` (`id`, `name`) VALUES ('aus', 'Australian Language');
INSERT INTO `country` (`id`, `name`) VALUES ('de_AT', 'Austrian German');
INSERT INTO `country` (`id`, `name`) VALUES ('map', 'Austronesian Language');
INSERT INTO `country` (`id`, `name`) VALUES ('av', 'Avaric');
INSERT INTO `country` (`id`, `name`) VALUES ('ae', 'Avestan');
INSERT INTO `country` (`id`, `name`) VALUES ('awa', 'Awadhi');
INSERT INTO `country` (`id`, `name`) VALUES ('ay', 'Aymara');
INSERT INTO `country` (`id`, `name`) VALUES ('az', 'Azerbaijani');
INSERT INTO `country` (`id`, `name`) VALUES ('ban', 'Balinese');
INSERT INTO `country` (`id`, `name`) VALUES ('bat', 'Baltic Language');
INSERT INTO `country` (`id`, `name`) VALUES ('bal', 'Baluchi');
INSERT INTO `country` (`id`, `name`) VALUES ('bm', 'Bambara');
INSERT INTO `country` (`id`, `name`) VALUES ('bai', 'Bamileke Language');
INSERT INTO `country` (`id`, `name`) VALUES ('bad', 'Banda');
INSERT INTO `country` (`id`, `name`) VALUES ('bnt', 'Bantu');
INSERT INTO `country` (`id`, `name`) VALUES ('bas', 'Basa');
INSERT INTO `country` (`id`, `name`) VALUES ('ba', 'Bashkir');
INSERT INTO `country` (`id`, `name`) VALUES ('eu', 'Basque');
INSERT INTO `country` (`id`, `name`) VALUES ('btk', 'Batak');
INSERT INTO `country` (`id`, `name`) VALUES ('bej', 'Beja');
INSERT INTO `country` (`id`, `name`) VALUES ('be', 'Belarusian');
INSERT INTO `country` (`id`, `name`) VALUES ('bem', 'Bemba');
INSERT INTO `country` (`id`, `name`) VALUES ('bn', 'Bengali');
INSERT INTO `country` (`id`, `name`) VALUES ('ber', 'Berber');
INSERT INTO `country` (`id`, `name`) VALUES ('bho', 'Bhojpuri');
INSERT INTO `country` (`id`, `name`) VALUES ('bh', 'Bihari');
INSERT INTO `country` (`id`, `name`) VALUES ('bik', 'Bikol');
INSERT INTO `country` (`id`, `name`) VALUES ('bin', 'Bini');
INSERT INTO `country` (`id`, `name`) VALUES ('bi', 'Bislama');
INSERT INTO `country` (`id`, `name`) VALUES ('byn', 'Blin');
INSERT INTO `country` (`id`, `name`) VALUES ('zbl', 'Blissymbols');
INSERT INTO `country` (`id`, `name`) VALUES ('bs', 'Bosnian');
INSERT INTO `country` (`id`, `name`) VALUES ('bra', 'Braj');
INSERT INTO `country` (`id`, `name`) VALUES ('pt_BR', 'Brazilian Portuguese');
INSERT INTO `country` (`id`, `name`) VALUES ('br', 'Breton');
INSERT INTO `country` (`id`, `name`) VALUES ('en_GB', 'British English');
INSERT INTO `country` (`id`, `name`) VALUES ('bug', 'Buginese');
INSERT INTO `country` (`id`, `name`) VALUES ('bg', 'Bulgarian');
INSERT INTO `country` (`id`, `name`) VALUES ('bua', 'Buriat');
INSERT INTO `country` (`id`, `name`) VALUES ('my', 'Burmese');
INSERT INTO `country` (`id`, `name`) VALUES ('cad', 'Caddo');
INSERT INTO `country` (`id`, `name`) VALUES ('en_CA', 'Canadian English');
INSERT INTO `country` (`id`, `name`) VALUES ('fr_CA', 'Canadian French');
INSERT INTO `country` (`id`, `name`) VALUES ('car', 'Carib');
INSERT INTO `country` (`id`, `name`) VALUES ('ca', 'Catalan');
INSERT INTO `country` (`id`, `name`) VALUES ('cau', 'Caucasian Language');
INSERT INTO `country` (`id`, `name`) VALUES ('ceb', 'Cebuano');
INSERT INTO `country` (`id`, `name`) VALUES ('cel', 'Celtic Language');
INSERT INTO `country` (`id`, `name`) VALUES ('cai', 'Central American Indian Language');
INSERT INTO `country` (`id`, `name`) VALUES ('chg', 'Chagatai');
INSERT INTO `country` (`id`, `name`) VALUES ('cmc', 'Chamic Language');
INSERT INTO `country` (`id`, `name`) VALUES ('ch', 'Chamorro');
INSERT INTO `country` (`id`, `name`) VALUES ('ce', 'Chechen');
INSERT INTO `country` (`id`, `name`) VALUES ('chr', 'Cherokee');
INSERT INTO `country` (`id`, `name`) VALUES ('chy', 'Cheyenne');
INSERT INTO `country` (`id`, `name`) VALUES ('chb', 'Chibcha');
INSERT INTO `country` (`id`, `name`) VALUES ('zh', 'Chinese');
INSERT INTO `country` (`id`, `name`) VALUES ('chn', 'Chinook Jargon');
INSERT INTO `country` (`id`, `name`) VALUES ('chp', 'Chipewyan');
INSERT INTO `country` (`id`, `name`) VALUES ('cho', 'Choctaw');
INSERT INTO `country` (`id`, `name`) VALUES ('cu', 'Church Slavic');
INSERT INTO `country` (`id`, `name`) VALUES ('chk', 'Chuukese');
INSERT INTO `country` (`id`, `name`) VALUES ('cv', 'Chuvash');
INSERT INTO `country` (`id`, `name`) VALUES ('nwc', 'Classical Newari');
INSERT INTO `country` (`id`, `name`) VALUES ('syc', 'Classical Syriac');
INSERT INTO `country` (`id`, `name`) VALUES ('cop', 'Coptic');
INSERT INTO `country` (`id`, `name`) VALUES ('kw', 'Cornish');
INSERT INTO `country` (`id`, `name`) VALUES ('co', 'Corsican');
INSERT INTO `country` (`id`, `name`) VALUES ('cr', 'Cree');
INSERT INTO `country` (`id`, `name`) VALUES ('mus', 'Creek');
INSERT INTO `country` (`id`, `name`) VALUES ('crp', 'Creole or Pidgin');
INSERT INTO `country` (`id`, `name`) VALUES ('crh', 'Crimean Turkish');
INSERT INTO `country` (`id`, `name`) VALUES ('hr', 'Croatian');
INSERT INTO `country` (`id`, `name`) VALUES ('cus', 'Cushitic Language');
INSERT INTO `country` (`id`, `name`) VALUES ('cs', 'Czech');
INSERT INTO `country` (`id`, `name`) VALUES ('dak', 'Dakota');
INSERT INTO `country` (`id`, `name`) VALUES ('da', 'Danish');
INSERT INTO `country` (`id`, `name`) VALUES ('dar', 'Dargwa');
INSERT INTO `country` (`id`, `name`) VALUES ('day', 'Dayak');
INSERT INTO `country` (`id`, `name`) VALUES ('del', 'Delaware');
INSERT INTO `country` (`id`, `name`) VALUES ('din', 'Dinka');
INSERT INTO `country` (`id`, `name`) VALUES ('dv', 'Divehi');
INSERT INTO `country` (`id`, `name`) VALUES ('doi', 'Dogri');
INSERT INTO `country` (`id`, `name`) VALUES ('dgr', 'Dogrib');
INSERT INTO `country` (`id`, `name`) VALUES ('dra', 'Dravidian Language');
INSERT INTO `country` (`id`, `name`) VALUES ('dua', 'Duala');
INSERT INTO `country` (`id`, `name`) VALUES ('nl', 'Dutch');
INSERT INTO `country` (`id`, `name`) VALUES ('dyu', 'Dyula');
INSERT INTO `country` (`id`, `name`) VALUES ('dz', 'Dzongkha');
INSERT INTO `country` (`id`, `name`) VALUES ('frs', 'Eastern Frisian');
INSERT INTO `country` (`id`, `name`) VALUES ('efi', 'Efik');
INSERT INTO `country` (`id`, `name`) VALUES ('eka', 'Ekajuk');
INSERT INTO `country` (`id`, `name`) VALUES ('elx', 'Elamite');
INSERT INTO `country` (`id`, `name`) VALUES ('en', 'English');
INSERT INTO `country` (`id`, `name`) VALUES ('cpe', 'English-based Creole or Pidgin');
INSERT INTO `country` (`id`, `name`) VALUES ('myv', 'Erzya');
INSERT INTO `country` (`id`, `name`) VALUES ('eo', 'Esperanto');
INSERT INTO `country` (`id`, `name`) VALUES ('et', 'Estonian');
INSERT INTO `country` (`id`, `name`) VALUES ('ee', 'Ewe');
INSERT INTO `country` (`id`, `name`) VALUES ('ewo', 'Ewondo');
INSERT INTO `country` (`id`, `name`) VALUES ('fan', 'Fang');
INSERT INTO `country` (`id`, `name`) VALUES ('fat', 'Fanti');
INSERT INTO `country` (`id`, `name`) VALUES ('fo', 'Faroese');
INSERT INTO `country` (`id`, `name`) VALUES ('fj', 'Fijian');
INSERT INTO `country` (`id`, `name`) VALUES ('fil', 'Filipino');
INSERT INTO `country` (`id`, `name`) VALUES ('fi', 'Finnish');
INSERT INTO `country` (`id`, `name`) VALUES ('fiu', 'Finno-Ugrian Language');
INSERT INTO `country` (`id`, `name`) VALUES ('nl_BE', 'Flemish');
INSERT INTO `country` (`id`, `name`) VALUES ('fon', 'Fon');
INSERT INTO `country` (`id`, `name`) VALUES ('fr', 'French');
INSERT INTO `country` (`id`, `name`) VALUES ('cpf', 'French-based Creole or Pidgin');
INSERT INTO `country` (`id`, `name`) VALUES ('fur', 'Friulian');
INSERT INTO `country` (`id`, `name`) VALUES ('ff', 'Fulah');
INSERT INTO `country` (`id`, `name`) VALUES ('gaa', 'Ga');
INSERT INTO `country` (`id`, `name`) VALUES ('gl', 'Galician');
INSERT INTO `country` (`id`, `name`) VALUES ('lg', 'Ganda');
INSERT INTO `country` (`id`, `name`) VALUES ('gay', 'Gayo');
INSERT INTO `country` (`id`, `name`) VALUES ('gba', 'Gbaya');
INSERT INTO `country` (`id`, `name`) VALUES ('gez', 'Geez');
INSERT INTO `country` (`id`, `name`) VALUES ('ka', 'Georgian');
INSERT INTO `country` (`id`, `name`) VALUES ('de', 'German');
INSERT INTO `country` (`id`, `name`) VALUES ('gem', 'Germanic Language');
INSERT INTO `country` (`id`, `name`) VALUES ('gil', 'Gilbertese');
INSERT INTO `country` (`id`, `name`) VALUES ('gon', 'Gondi');
INSERT INTO `country` (`id`, `name`) VALUES ('gor', 'Gorontalo');
INSERT INTO `country` (`id`, `name`) VALUES ('got', 'Gothic');
INSERT INTO `country` (`id`, `name`) VALUES ('grb', 'Grebo');
INSERT INTO `country` (`id`, `name`) VALUES ('el', 'Greek');
INSERT INTO `country` (`id`, `name`) VALUES ('gn', 'Guarani');
INSERT INTO `country` (`id`, `name`) VALUES ('gu', 'Gujarati');
INSERT INTO `country` (`id`, `name`) VALUES ('gwi', 'Gwichʼin');
INSERT INTO `country` (`id`, `name`) VALUES ('hai', 'Haida');
INSERT INTO `country` (`id`, `name`) VALUES ('ht', 'Haitian');
INSERT INTO `country` (`id`, `name`) VALUES ('ha', 'Hausa');
INSERT INTO `country` (`id`, `name`) VALUES ('haw', 'Hawaiian');
INSERT INTO `country` (`id`, `name`) VALUES ('he', 'Hebrew');
INSERT INTO `country` (`id`, `name`) VALUES ('hz', 'Herero');
INSERT INTO `country` (`id`, `name`) VALUES ('hil', 'Hiligaynon');
INSERT INTO `country` (`id`, `name`) VALUES ('him', 'Himachali');
INSERT INTO `country` (`id`, `name`) VALUES ('hi', 'Hindi');
INSERT INTO `country` (`id`, `name`) VALUES ('ho', 'Hiri Motu');
INSERT INTO `country` (`id`, `name`) VALUES ('hit', 'Hittite');
INSERT INTO `country` (`id`, `name`) VALUES ('hmn', 'Hmong');
INSERT INTO `country` (`id`, `name`) VALUES ('hu', 'Hungarian');
INSERT INTO `country` (`id`, `name`) VALUES ('hup', 'Hupa');
INSERT INTO `country` (`id`, `name`) VALUES ('iba', 'Iban');
INSERT INTO `country` (`id`, `name`) VALUES ('pt_PT', 'Iberian Portuguese');
INSERT INTO `country` (`id`, `name`) VALUES ('es_ES', 'Iberian Spanish');
INSERT INTO `country` (`id`, `name`) VALUES ('is', 'Icelandic');
INSERT INTO `country` (`id`, `name`) VALUES ('io', 'Ido');
INSERT INTO `country` (`id`, `name`) VALUES ('ig', 'Igbo');
INSERT INTO `country` (`id`, `name`) VALUES ('ijo', 'Ijo');
INSERT INTO `country` (`id`, `name`) VALUES ('ilo', 'Iloko');
INSERT INTO `country` (`id`, `name`) VALUES ('smn', 'Inari Sami');
INSERT INTO `country` (`id`, `name`) VALUES ('inc', 'Indic Language');
INSERT INTO `country` (`id`, `name`) VALUES ('ine', 'Indo-European Language');
INSERT INTO `country` (`id`, `name`) VALUES ('id', 'Indonesian');
INSERT INTO `country` (`id`, `name`) VALUES ('inh', 'Ingush');
INSERT INTO `country` (`id`, `name`) VALUES ('ia', 'Interlingua');
INSERT INTO `country` (`id`, `name`) VALUES ('ie', 'Interlingue');
INSERT INTO `country` (`id`, `name`) VALUES ('iu', 'Inuktitut');
INSERT INTO `country` (`id`, `name`) VALUES ('ik', 'Inupiaq');
INSERT INTO `country` (`id`, `name`) VALUES ('ira', 'Iranian Language');
INSERT INTO `country` (`id`, `name`) VALUES ('ga', 'Irish');
INSERT INTO `country` (`id`, `name`) VALUES ('iro', 'Iroquoian Language');
INSERT INTO `country` (`id`, `name`) VALUES ('it', 'Italian');
INSERT INTO `country` (`id`, `name`) VALUES ('ja', 'Japanese');
INSERT INTO `country` (`id`, `name`) VALUES ('jv', 'Javanese');
INSERT INTO `country` (`id`, `name`) VALUES ('kaj', 'Jju');
INSERT INTO `country` (`id`, `name`) VALUES ('jrb', 'Judeo-Arabic');
INSERT INTO `country` (`id`, `name`) VALUES ('jpr', 'Judeo-Persian');
INSERT INTO `country` (`id`, `name`) VALUES ('kbd', 'Kabardian');
INSERT INTO `country` (`id`, `name`) VALUES ('kab', 'Kabyle');
INSERT INTO `country` (`id`, `name`) VALUES ('kac', 'Kachin');
INSERT INTO `country` (`id`, `name`) VALUES ('kl', 'Kalaallisut');
INSERT INTO `country` (`id`, `name`) VALUES ('xal', 'Kalmyk');
INSERT INTO `country` (`id`, `name`) VALUES ('kam', 'Kamba');
INSERT INTO `country` (`id`, `name`) VALUES ('kn', 'Kannada');
INSERT INTO `country` (`id`, `name`) VALUES ('kr', 'Kanuri');
INSERT INTO `country` (`id`, `name`) VALUES ('kaa', 'Kara-Kalpak');
INSERT INTO `country` (`id`, `name`) VALUES ('krc', 'Karachay-Balkar');
INSERT INTO `country` (`id`, `name`) VALUES ('krl', 'Karelian');
INSERT INTO `country` (`id`, `name`) VALUES ('kar', 'Karen');
INSERT INTO `country` (`id`, `name`) VALUES ('ks', 'Kashmiri');
INSERT INTO `country` (`id`, `name`) VALUES ('csb', 'Kashubian');
INSERT INTO `country` (`id`, `name`) VALUES ('kaw', 'Kawi');
INSERT INTO `country` (`id`, `name`) VALUES ('kk', 'Kazakh');
INSERT INTO `country` (`id`, `name`) VALUES ('kha', 'Khasi');
INSERT INTO `country` (`id`, `name`) VALUES ('km', 'Khmer');
INSERT INTO `country` (`id`, `name`) VALUES ('khi', 'Khoisan Language');
INSERT INTO `country` (`id`, `name`) VALUES ('kho', 'Khotanese');
INSERT INTO `country` (`id`, `name`) VALUES ('ki', 'Kikuyu');
INSERT INTO `country` (`id`, `name`) VALUES ('kmb', 'Kimbundu');
INSERT INTO `country` (`id`, `name`) VALUES ('rw', 'Kinyarwanda');
INSERT INTO `country` (`id`, `name`) VALUES ('ky', 'Kirghiz');
INSERT INTO `country` (`id`, `name`) VALUES ('tlh', 'Klingon');
INSERT INTO `country` (`id`, `name`) VALUES ('kv', 'Komi');
INSERT INTO `country` (`id`, `name`) VALUES ('kg', 'Kongo');
INSERT INTO `country` (`id`, `name`) VALUES ('kok', 'Konkani');
INSERT INTO `country` (`id`, `name`) VALUES ('ko', 'Korean');
INSERT INTO `country` (`id`, `name`) VALUES ('kfo', 'Koro');
INSERT INTO `country` (`id`, `name`) VALUES ('kos', 'Kosraean');
INSERT INTO `country` (`id`, `name`) VALUES ('kpe', 'Kpelle');
INSERT INTO `country` (`id`, `name`) VALUES ('kro', 'Kru');
INSERT INTO `country` (`id`, `name`) VALUES ('kj', 'Kuanyama');
INSERT INTO `country` (`id`, `name`) VALUES ('kum', 'Kumyk');
INSERT INTO `country` (`id`, `name`) VALUES ('ku', 'Kurdish');
INSERT INTO `country` (`id`, `name`) VALUES ('kru', 'Kurukh');
INSERT INTO `country` (`id`, `name`) VALUES ('kut', 'Kutenai');
INSERT INTO `country` (`id`, `name`) VALUES ('lad', 'Ladino');
INSERT INTO `country` (`id`, `name`) VALUES ('lah', 'Lahnda');
INSERT INTO `country` (`id`, `name`) VALUES ('lam', 'Lamba');
INSERT INTO `country` (`id`, `name`) VALUES ('lo', 'Lao');
INSERT INTO `country` (`id`, `name`) VALUES ('la', 'Latin');
INSERT INTO `country` (`id`, `name`) VALUES ('es_419', 'Latin American Spanish');
INSERT INTO `country` (`id`, `name`) VALUES ('lv', 'Latvian');
INSERT INTO `country` (`id`, `name`) VALUES ('lez', 'Lezghian');
INSERT INTO `country` (`id`, `name`) VALUES ('li', 'Limburgish');
INSERT INTO `country` (`id`, `name`) VALUES ('ln', 'Lingala');
INSERT INTO `country` (`id`, `name`) VALUES ('lt', 'Lithuanian');
INSERT INTO `country` (`id`, `name`) VALUES ('jbo', 'Lojban');
INSERT INTO `country` (`id`, `name`) VALUES ('nds', 'Low German');
INSERT INTO `country` (`id`, `name`) VALUES ('dsb', 'Lower Sorbian');
INSERT INTO `country` (`id`, `name`) VALUES ('loz', 'Lozi');
INSERT INTO `country` (`id`, `name`) VALUES ('lu', 'Luba-Katanga');
INSERT INTO `country` (`id`, `name`) VALUES ('lua', 'Luba-Lulua');
INSERT INTO `country` (`id`, `name`) VALUES ('lui', 'Luiseno');
INSERT INTO `country` (`id`, `name`) VALUES ('smj', 'Lule Sami');
INSERT INTO `country` (`id`, `name`) VALUES ('lun', 'Lunda');
INSERT INTO `country` (`id`, `name`) VALUES ('luo', 'Luo');
INSERT INTO `country` (`id`, `name`) VALUES ('lus', 'Lushai');
INSERT INTO `country` (`id`, `name`) VALUES ('lb', 'Luxembourgish');
INSERT INTO `country` (`id`, `name`) VALUES ('mk', 'Macedonian');
INSERT INTO `country` (`id`, `name`) VALUES ('mad', 'Madurese');
INSERT INTO `country` (`id`, `name`) VALUES ('mag', 'Magahi');
INSERT INTO `country` (`id`, `name`) VALUES ('mai', 'Maithili');
INSERT INTO `country` (`id`, `name`) VALUES ('mak', 'Makasar');
INSERT INTO `country` (`id`, `name`) VALUES ('mg', 'Malagasy');
INSERT INTO `country` (`id`, `name`) VALUES ('ms', 'Malay');
INSERT INTO `country` (`id`, `name`) VALUES ('ml', 'Malayalam');
INSERT INTO `country` (`id`, `name`) VALUES ('mt', 'Maltese');
INSERT INTO `country` (`id`, `name`) VALUES ('mnc', 'Manchu');
INSERT INTO `country` (`id`, `name`) VALUES ('mdr', 'Mandar');
INSERT INTO `country` (`id`, `name`) VALUES ('man', 'Mandingo');
INSERT INTO `country` (`id`, `name`) VALUES ('mni', 'Manipuri');
INSERT INTO `country` (`id`, `name`) VALUES ('mno', 'Manobo Language');
INSERT INTO `country` (`id`, `name`) VALUES ('gv', 'Manx');
INSERT INTO `country` (`id`, `name`) VALUES ('mi', 'Maori');
INSERT INTO `country` (`id`, `name`) VALUES ('mr', 'Marathi');
INSERT INTO `country` (`id`, `name`) VALUES ('chm', 'Mari');
INSERT INTO `country` (`id`, `name`) VALUES ('mh', 'Marshallese');
INSERT INTO `country` (`id`, `name`) VALUES ('mwr', 'Marwari');
INSERT INTO `country` (`id`, `name`) VALUES ('mas', 'Masai');
INSERT INTO `country` (`id`, `name`) VALUES ('myn', 'Mayan Language');
INSERT INTO `country` (`id`, `name`) VALUES ('men', 'Mende');
INSERT INTO `country` (`id`, `name`) VALUES ('mic', 'Micmac');
INSERT INTO `country` (`id`, `name`) VALUES ('dum', 'Middle Dutch');
INSERT INTO `country` (`id`, `name`) VALUES ('enm', 'Middle English');
INSERT INTO `country` (`id`, `name`) VALUES ('frm', 'Middle French');
INSERT INTO `country` (`id`, `name`) VALUES ('gmh', 'Middle High German');
INSERT INTO `country` (`id`, `name`) VALUES ('mga', 'Middle Irish');
INSERT INTO `country` (`id`, `name`) VALUES ('min', 'Minangkabau');
INSERT INTO `country` (`id`, `name`) VALUES ('mwl', 'Mirandese');
INSERT INTO `country` (`id`, `name`) VALUES ('mis', 'Miscellaneous Language');
INSERT INTO `country` (`id`, `name`) VALUES ('moh', 'Mohawk');
INSERT INTO `country` (`id`, `name`) VALUES ('mdf', 'Moksha');
INSERT INTO `country` (`id`, `name`) VALUES ('mo', 'Moldavian');
INSERT INTO `country` (`id`, `name`) VALUES ('mkh', 'Mon-Khmer Language');
INSERT INTO `country` (`id`, `name`) VALUES ('lol', 'Mongo');
INSERT INTO `country` (`id`, `name`) VALUES ('mn', 'Mongolian');
INSERT INTO `country` (`id`, `name`) VALUES ('mfe', 'Morisyen');
INSERT INTO `country` (`id`, `name`) VALUES ('mos', 'Mossi');
INSERT INTO `country` (`id`, `name`) VALUES ('mul', 'Multiple Languages');
INSERT INTO `country` (`id`, `name`) VALUES ('mun', 'Munda Language');
INSERT INTO `country` (`id`, `name`) VALUES ('nah', 'Nahuatl');
INSERT INTO `country` (`id`, `name`) VALUES ('na', 'Nauru');
INSERT INTO `country` (`id`, `name`) VALUES ('nv', 'Navajo');
INSERT INTO `country` (`id`, `name`) VALUES ('ng', 'Ndonga');
INSERT INTO `country` (`id`, `name`) VALUES ('nap', 'Neapolitan');
INSERT INTO `country` (`id`, `name`) VALUES ('ne', 'Nepali');
INSERT INTO `country` (`id`, `name`) VALUES ('new', 'Newari');
INSERT INTO `country` (`id`, `name`) VALUES ('nia', 'Nias');
INSERT INTO `country` (`id`, `name`) VALUES ('nic', 'Niger-Kordofanian Language');
INSERT INTO `country` (`id`, `name`) VALUES ('ssa', 'Nilo-Saharan Language');
INSERT INTO `country` (`id`, `name`) VALUES ('niu', 'Niuean');
INSERT INTO `country` (`id`, `name`) VALUES ('zxx', 'No linguistic content');
INSERT INTO `country` (`id`, `name`) VALUES ('nog', 'Nogai');
INSERT INTO `country` (`id`, `name`) VALUES ('nai', 'North American Indian Language');
INSERT INTO `country` (`id`, `name`) VALUES ('nd', 'North Ndebele');
INSERT INTO `country` (`id`, `name`) VALUES ('frr', 'Northern Frisian');
INSERT INTO `country` (`id`, `name`) VALUES ('se', 'Northern Sami');
INSERT INTO `country` (`id`, `name`) VALUES ('nso', 'Northern Sotho');
INSERT INTO `country` (`id`, `name`) VALUES ('no', 'Norwegian');
INSERT INTO `country` (`id`, `name`) VALUES ('nb', 'Norwegian Bokmål');
INSERT INTO `country` (`id`, `name`) VALUES ('nn', 'Norwegian Nynorsk');
INSERT INTO `country` (`id`, `name`) VALUES ('nub', 'Nubian Language');
INSERT INTO `country` (`id`, `name`) VALUES ('nym', 'Nyamwezi');
INSERT INTO `country` (`id`, `name`) VALUES ('ny', 'Nyanja');
INSERT INTO `country` (`id`, `name`) VALUES ('nyn', 'Nyankole');
INSERT INTO `country` (`id`, `name`) VALUES ('tog', 'Nyasa Tonga');
INSERT INTO `country` (`id`, `name`) VALUES ('nyo', 'Nyoro');
INSERT INTO `country` (`id`, `name`) VALUES ('nzi', 'Nzima');
INSERT INTO `country` (`id`, `name`) VALUES ('nqo', 'N’Ko');
INSERT INTO `country` (`id`, `name`) VALUES ('oc', 'Occitan');
INSERT INTO `country` (`id`, `name`) VALUES ('oj', 'Ojibwa');
INSERT INTO `country` (`id`, `name`) VALUES ('ang', 'Old English');
INSERT INTO `country` (`id`, `name`) VALUES ('fro', 'Old French');
INSERT INTO `country` (`id`, `name`) VALUES ('goh', 'Old High German');
INSERT INTO `country` (`id`, `name`) VALUES ('sga', 'Old Irish');
INSERT INTO `country` (`id`, `name`) VALUES ('non', 'Old Norse');
INSERT INTO `country` (`id`, `name`) VALUES ('peo', 'Old Persian');
INSERT INTO `country` (`id`, `name`) VALUES ('pro', 'Old Provençal');
INSERT INTO `country` (`id`, `name`) VALUES ('or', 'Oriya');
INSERT INTO `country` (`id`, `name`) VALUES ('om', 'Oromo');
INSERT INTO `country` (`id`, `name`) VALUES ('osa', 'Osage');
INSERT INTO `country` (`id`, `name`) VALUES ('os', 'Ossetic');
INSERT INTO `country` (`id`, `name`) VALUES ('oto', 'Otomian Language');
INSERT INTO `country` (`id`, `name`) VALUES ('ota', 'Ottoman Turkish');
INSERT INTO `country` (`id`, `name`) VALUES ('pal', 'Pahlavi');
INSERT INTO `country` (`id`, `name`) VALUES ('pau', 'Palauan');
INSERT INTO `country` (`id`, `name`) VALUES ('pi', 'Pali');
INSERT INTO `country` (`id`, `name`) VALUES ('pam', 'Pampanga');
INSERT INTO `country` (`id`, `name`) VALUES ('pag', 'Pangasinan');
INSERT INTO `country` (`id`, `name`) VALUES ('pap', 'Papiamento');
INSERT INTO `country` (`id`, `name`) VALUES ('paa', 'Papuan Language');
INSERT INTO `country` (`id`, `name`) VALUES ('ps', 'Pashto');
INSERT INTO `country` (`id`, `name`) VALUES ('fa', 'Persian');
INSERT INTO `country` (`id`, `name`) VALUES ('phi', 'Philippine Language');
INSERT INTO `country` (`id`, `name`) VALUES ('phn', 'Phoenician');
INSERT INTO `country` (`id`, `name`) VALUES ('pon', 'Pohnpeian');
INSERT INTO `country` (`id`, `name`) VALUES ('pl', 'Polish');
INSERT INTO `country` (`id`, `name`) VALUES ('pt', 'Portuguese');
INSERT INTO `country` (`id`, `name`) VALUES ('cpp', 'Portuguese-based Creole or Pidgin');
INSERT INTO `country` (`id`, `name`) VALUES ('pra', 'Prakrit Language');
INSERT INTO `country` (`id`, `name`) VALUES ('pa', 'Punjabi');
INSERT INTO `country` (`id`, `name`) VALUES ('qu', 'Quechua');
INSERT INTO `country` (`id`, `name`) VALUES ('raj', 'Rajasthani');
INSERT INTO `country` (`id`, `name`) VALUES ('rap', 'Rapanui');
INSERT INTO `country` (`id`, `name`) VALUES ('rar', 'Rarotongan');
INSERT INTO `country` (`id`, `name`) VALUES ('rm', 'Rhaeto-Romance');
INSERT INTO `country` (`id`, `name`) VALUES ('roa', 'Romance Language');
INSERT INTO `country` (`id`, `name`) VALUES ('ro', 'Romanian');
INSERT INTO `country` (`id`, `name`) VALUES ('rom', 'Romany');
INSERT INTO `country` (`id`, `name`) VALUES ('root', 'Root');
INSERT INTO `country` (`id`, `name`) VALUES ('rn', 'Rundi');
INSERT INTO `country` (`id`, `name`) VALUES ('ru', 'Russian');
INSERT INTO `country` (`id`, `name`) VALUES ('sal', 'Salishan Language');
INSERT INTO `country` (`id`, `name`) VALUES ('sam', 'Samaritan Aramaic');
INSERT INTO `country` (`id`, `name`) VALUES ('smi', 'Sami Language');
INSERT INTO `country` (`id`, `name`) VALUES ('sm', 'Samoan');
INSERT INTO `country` (`id`, `name`) VALUES ('sad', 'Sandawe');
INSERT INTO `country` (`id`, `name`) VALUES ('sg', 'Sango');
INSERT INTO `country` (`id`, `name`) VALUES ('sa', 'Sanskrit');
INSERT INTO `country` (`id`, `name`) VALUES ('sat', 'Santali');
INSERT INTO `country` (`id`, `name`) VALUES ('sc', 'Sardinian');
INSERT INTO `country` (`id`, `name`) VALUES ('sas', 'Sasak');
INSERT INTO `country` (`id`, `name`) VALUES ('sco', 'Scots');
INSERT INTO `country` (`id`, `name`) VALUES ('gd', 'Scottish Gaelic');
INSERT INTO `country` (`id`, `name`) VALUES ('sel', 'Selkup');
INSERT INTO `country` (`id`, `name`) VALUES ('sem', 'Semitic Language');
INSERT INTO `country` (`id`, `name`) VALUES ('sr', 'Serbian');
INSERT INTO `country` (`id`, `name`) VALUES ('sh', 'Serbo-Croatian');
INSERT INTO `country` (`id`, `name`) VALUES ('srr', 'Serer');
INSERT INTO `country` (`id`, `name`) VALUES ('shn', 'Shan');
INSERT INTO `country` (`id`, `name`) VALUES ('sn', 'Shona');
INSERT INTO `country` (`id`, `name`) VALUES ('ii', 'Sichuan Yi');
INSERT INTO `country` (`id`, `name`) VALUES ('scn', 'Sicilian');
INSERT INTO `country` (`id`, `name`) VALUES ('sid', 'Sidamo');
INSERT INTO `country` (`id`, `name`) VALUES ('sgn', 'Sign Language');
INSERT INTO `country` (`id`, `name`) VALUES ('bla', 'Siksika');
INSERT INTO `country` (`id`, `name`) VALUES ('zh_Hans', 'Simplified Chinese');
INSERT INTO `country` (`id`, `name`) VALUES ('sd', 'Sindhi');
INSERT INTO `country` (`id`, `name`) VALUES ('si', 'Sinhala');
INSERT INTO `country` (`id`, `name`) VALUES ('sit', 'Sino-Tibetan Language');
INSERT INTO `country` (`id`, `name`) VALUES ('sio', 'Siouan Language');
INSERT INTO `country` (`id`, `name`) VALUES ('sms', 'Skolt Sami');
INSERT INTO `country` (`id`, `name`) VALUES ('den', 'Slave');
INSERT INTO `country` (`id`, `name`) VALUES ('sla', 'Slavic Language');
INSERT INTO `country` (`id`, `name`) VALUES ('sk', 'Slovak');
INSERT INTO `country` (`id`, `name`) VALUES ('sl', 'Slovenian');
INSERT INTO `country` (`id`, `name`) VALUES ('sog', 'Sogdien');
INSERT INTO `country` (`id`, `name`) VALUES ('so', 'Somali');
INSERT INTO `country` (`id`, `name`) VALUES ('son', 'Songhai');
INSERT INTO `country` (`id`, `name`) VALUES ('snk', 'Soninke');
INSERT INTO `country` (`id`, `name`) VALUES ('wen', 'Sorbian Language');
INSERT INTO `country` (`id`, `name`) VALUES ('sai', 'South American Indian Language');
INSERT INTO `country` (`id`, `name`) VALUES ('nr', 'South Ndebele');
INSERT INTO `country` (`id`, `name`) VALUES ('alt', 'Southern Altai');
INSERT INTO `country` (`id`, `name`) VALUES ('sma', 'Southern Sami');
INSERT INTO `country` (`id`, `name`) VALUES ('st', 'Southern Sotho');
INSERT INTO `country` (`id`, `name`) VALUES ('es', 'Spanish');
INSERT INTO `country` (`id`, `name`) VALUES ('srn', 'Sranan Tongo');
INSERT INTO `country` (`id`, `name`) VALUES ('suk', 'Sukuma');
INSERT INTO `country` (`id`, `name`) VALUES ('sux', 'Sumerian');
INSERT INTO `country` (`id`, `name`) VALUES ('su', 'Sundanese');
INSERT INTO `country` (`id`, `name`) VALUES ('sus', 'Susu');
INSERT INTO `country` (`id`, `name`) VALUES ('sw', 'Swahili');
INSERT INTO `country` (`id`, `name`) VALUES ('ss', 'Swati');
INSERT INTO `country` (`id`, `name`) VALUES ('sv', 'Swedish');
INSERT INTO `country` (`id`, `name`) VALUES ('fr_CH', 'Swiss French');
INSERT INTO `country` (`id`, `name`) VALUES ('gsw', 'Swiss German');
INSERT INTO `country` (`id`, `name`) VALUES ('de_CH', 'Swiss High German');
INSERT INTO `country` (`id`, `name`) VALUES ('syr', 'Syriac');
INSERT INTO `country` (`id`, `name`) VALUES ('tl', 'Tagalog');
INSERT INTO `country` (`id`, `name`) VALUES ('ty', 'Tahitian');
INSERT INTO `country` (`id`, `name`) VALUES ('tai', 'Tai Language');
INSERT INTO `country` (`id`, `name`) VALUES ('tg', 'Tajik');
INSERT INTO `country` (`id`, `name`) VALUES ('tmh', 'Tamashek');
INSERT INTO `country` (`id`, `name`) VALUES ('ta', 'Tamil');
INSERT INTO `country` (`id`, `name`) VALUES ('trv', 'Taroko');
INSERT INTO `country` (`id`, `name`) VALUES ('tt', 'Tatar');
INSERT INTO `country` (`id`, `name`) VALUES ('te', 'Telugu');
INSERT INTO `country` (`id`, `name`) VALUES ('ter', 'Tereno');
INSERT INTO `country` (`id`, `name`) VALUES ('tet', 'Tetum');
INSERT INTO `country` (`id`, `name`) VALUES ('th', 'Thai');
INSERT INTO `country` (`id`, `name`) VALUES ('bo', 'Tibetan');
INSERT INTO `country` (`id`, `name`) VALUES ('tig', 'Tigre');
INSERT INTO `country` (`id`, `name`) VALUES ('ti', 'Tigrinya');
INSERT INTO `country` (`id`, `name`) VALUES ('tem', 'Timne');
INSERT INTO `country` (`id`, `name`) VALUES ('tiv', 'Tiv');
INSERT INTO `country` (`id`, `name`) VALUES ('tli', 'Tlingit');
INSERT INTO `country` (`id`, `name`) VALUES ('tpi', 'Tok Pisin');
INSERT INTO `country` (`id`, `name`) VALUES ('tkl', 'Tokelau');
INSERT INTO `country` (`id`, `name`) VALUES ('to', 'Tonga');
INSERT INTO `country` (`id`, `name`) VALUES ('zh_Hant', 'Traditional Chinese');
INSERT INTO `country` (`id`, `name`) VALUES ('tsi', 'Tsimshian');
INSERT INTO `country` (`id`, `name`) VALUES ('ts', 'Tsonga');
INSERT INTO `country` (`id`, `name`) VALUES ('tn', 'Tswana');
INSERT INTO `country` (`id`, `name`) VALUES ('tum', 'Tumbuka');
INSERT INTO `country` (`id`, `name`) VALUES ('tup', 'Tupi Language');
INSERT INTO `country` (`id`, `name`) VALUES ('tr', 'Turkish');
INSERT INTO `country` (`id`, `name`) VALUES ('tk', 'Turkmen');
INSERT INTO `country` (`id`, `name`) VALUES ('tvl', 'Tuvalu');
INSERT INTO `country` (`id`, `name`) VALUES ('tyv', 'Tuvinian');
INSERT INTO `country` (`id`, `name`) VALUES ('tw', 'Twi');
INSERT INTO `country` (`id`, `name`) VALUES ('kcg', 'Tyap');
INSERT INTO `country` (`id`, `name`) VALUES ('en_US', 'U.S. English');
INSERT INTO `country` (`id`, `name`) VALUES ('udm', 'Udmurt');
INSERT INTO `country` (`id`, `name`) VALUES ('uga', 'Ugaritic');
INSERT INTO `country` (`id`, `name`) VALUES ('ug', 'Uighur');
INSERT INTO `country` (`id`, `name`) VALUES ('uk', 'Ukrainian');
INSERT INTO `country` (`id`, `name`) VALUES ('umb', 'Umbundu');
INSERT INTO `country` (`id`, `name`) VALUES ('und', 'Unknown or Invalid Language');
INSERT INTO `country` (`id`, `name`) VALUES ('hsb', 'Upper Sorbian');
INSERT INTO `country` (`id`, `name`) VALUES ('ur', 'Urdu');
INSERT INTO `country` (`id`, `name`) VALUES ('uz', 'Uzbek');
INSERT INTO `country` (`id`, `name`) VALUES ('vai', 'Vai');
INSERT INTO `country` (`id`, `name`) VALUES ('ve', 'Venda');
INSERT INTO `country` (`id`, `name`) VALUES ('vi', 'Vietnamese');
INSERT INTO `country` (`id`, `name`) VALUES ('vo', 'Volapük');
INSERT INTO `country` (`id`, `name`) VALUES ('vot', 'Votic');
INSERT INTO `country` (`id`, `name`) VALUES ('wak', 'Wakashan Language');
INSERT INTO `country` (`id`, `name`) VALUES ('wal', 'Walamo');
INSERT INTO `country` (`id`, `name`) VALUES ('wa', 'Walloon');
INSERT INTO `country` (`id`, `name`) VALUES ('war', 'Waray');
INSERT INTO `country` (`id`, `name`) VALUES ('was', 'Washo');
INSERT INTO `country` (`id`, `name`) VALUES ('cy', 'Welsh');
INSERT INTO `country` (`id`, `name`) VALUES ('fy', 'Western Frisian');
INSERT INTO `country` (`id`, `name`) VALUES ('wo', 'Wolof');
INSERT INTO `country` (`id`, `name`) VALUES ('xh', 'Xhosa');
INSERT INTO `country` (`id`, `name`) VALUES ('sah', 'Yakut');
INSERT INTO `country` (`id`, `name`) VALUES ('yao', 'Yao');
INSERT INTO `country` (`id`, `name`) VALUES ('yap', 'Yapese');
INSERT INTO `country` (`id`, `name`) VALUES ('yi', 'Yiddish');
INSERT INTO `country` (`id`, `name`) VALUES ('yo', 'Yoruba');
INSERT INTO `country` (`id`, `name`) VALUES ('ypk', 'Yupik Language');
INSERT INTO `country` (`id`, `name`) VALUES ('znd', 'Zande');
INSERT INTO `country` (`id`, `name`) VALUES ('zap', 'Zapotec');
INSERT INTO `country` (`id`, `name`) VALUES ('zza', 'Zaza');
INSERT INTO `country` (`id`, `name`) VALUES ('zen', 'Zenaga');
INSERT INTO `country` (`id`, `name`) VALUES ('za', 'Zhuang');
INSERT INTO `country` (`id`, `name`) VALUES ('zu', 'Zulu');
INSERT INTO `country` (`id`, `name`) VALUES ('zun', 'Zuni');
