CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('fr', 'lea fakafalanisē');
INSERT INTO "country" ("id", "name") VALUES ('fi', 'lea fakafinilani');
INSERT INTO "country" ("id", "name") VALUES ('fj', 'lea fakafisi');
INSERT INTO "country" ("id", "name") VALUES ('haw', 'lea fakahauaiʻi');
INSERT INTO "country" ("id", "name") VALUES ('sm', 'lea fakahaʻamoa');
INSERT INTO "country" ("id", "name") VALUES ('he', 'lea fakahepelū');
INSERT INTO "country" ("id", "name") VALUES ('nl', 'lea fakaholani');
INSERT INTO "country" ("id", "name") VALUES ('el', 'lea fakakalisi');
INSERT INTO "country" ("id", "name") VALUES ('grc', 'lea fakakalisimuʻa');
INSERT INTO "country" ("id", "name") VALUES ('gil', 'lea fakakilipasi');
INSERT INTO "country" ("id", "name") VALUES ('ko', 'lea fakakōlea');
INSERT INTO "country" ("id", "name") VALUES ('rar', 'lea fakalalotonga');
INSERT INTO "country" ("id", "name") VALUES ('rap', 'lea fakalapanui');
INSERT INTO "country" ("id", "name") VALUES ('la', 'lea fakalatina');
INSERT INTO "country" ("id", "name") VALUES ('ru', 'lea fakalusia');
INSERT INTO "country" ("id", "name") VALUES ('ms', 'lea fakamalei');
INSERT INTO "country" ("id", "name") VALUES ('mi', 'lea fakamauli');
INSERT INTO "country" ("id", "name") VALUES ('mh', 'lea fakamāsolo');
INSERT INTO "country" ("id", "name") VALUES ('na', 'lea fakanaulu');
INSERT INTO "country" ("id", "name") VALUES ('niu', 'lea fakaniuē');
INSERT INTO "country" ("id", "name") VALUES ('no', 'lea fakanoauē');
INSERT INTO "country" ("id", "name") VALUES ('my', 'lea fakapema');
INSERT INTO "country" ("id", "name") VALUES ('en', 'lea fakapilitānia');
INSERT INTO "country" ("id", "name") VALUES ('pt', 'lea fakapotukali');
INSERT INTO "country" ("id", "name") VALUES ('pt_BR', 'lea fakapotukali-palāsili');
INSERT INTO "country" ("id", "name") VALUES ('fa', 'lea fakapēsia');
INSERT INTO "country" ("id", "name") VALUES ('es', 'lea fakasepeni');
INSERT INTO "country" ("id", "name") VALUES ('zh', 'lea fakasiaina');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hans', 'lea fakasiaina fakangofua');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hant', 'lea fakasiaina tukufakaholo');
INSERT INTO "country" ("id", "name") VALUES ('de', 'lea fakasiamane');
INSERT INTO "country" ("id", "name") VALUES ('ja', 'lea fakasiapani');
INSERT INTO "country" ("id", "name") VALUES ('sco', 'lea fakasikotilani');
INSERT INTO "country" ("id", "name") VALUES ('sv', 'lea fakasueteni');
INSERT INTO "country" ("id", "name") VALUES ('ty', 'lea fakatahisi');
INSERT INTO "country" ("id", "name") VALUES ('tr', 'lea fakatoake');
INSERT INTO "country" ("id", "name") VALUES ('tkl', 'lea fakatokelau');
INSERT INTO "country" ("id", "name") VALUES ('to', 'lea fakatonga');
INSERT INTO "country" ("id", "name") VALUES ('tvl', 'lea fakatūvalu');
INSERT INTO "country" ("id", "name") VALUES ('ga', 'lea fakaʻaealani');
INSERT INTO "country" ("id", "name") VALUES ('ar', 'lea fakaʻalepea');
INSERT INTO "country" ("id", "name") VALUES ('sgn', 'lea fakaʻilonga');
INSERT INTO "country" ("id", "name") VALUES ('it', 'lea fakaʻītali');
INSERT INTO "country" ("id", "name") VALUES ('art', 'lea faʻu pē kehe');
INSERT INTO "country" ("id", "name") VALUES ('mis', 'lea kehekehe');
INSERT INTO "country" ("id", "name") VALUES ('und', 'lea taʻeʻiloa');
INSERT INTO "country" ("id", "name") VALUES ('zxx', 'ʻikai ha lea');
