CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('gaa', 'གཱ་སྐད།');
INSERT INTO [country] ([id], [name]) VALUES ('gu', 'གུཇ་རཱཏི་སྐད།');
INSERT INTO [country] ([id], [name]) VALUES ('it', 'དབྱི་ཏ་་ལའི་མི།');
INSERT INTO [country] ([id], [name]) VALUES ('ne', 'ནེ་པ་ལི');
INSERT INTO [country] ([id], [name]) VALUES ('pt_BR', 'པ་ཞའི་མི།  ཕི་ཐོ་ཡའི་མི།');
INSERT INTO [country] ([id], [name]) VALUES ('bo', 'པོད་སྐད་');
INSERT INTO [country] ([id], [name]) VALUES ('pt', 'ཕི་ཐོ་ཡའི།');
INSERT INTO [country] ([id], [name]) VALUES ('und', 'མིའི་ཤེས་རྟོགས་མ་བྱུང་བ། ཡང་ན་ཆད་ལྷག་ཅན་གྱི་སྐད་བརྡ།');
INSERT INTO [country] ([id], [name]) VALUES ('es', 'ཞི་པན་ཡའི།');
INSERT INTO [country] ([id], [name]) VALUES ('zza', 'ཟ་ཟཱ་སྐད།');
INSERT INTO [country] ([id], [name]) VALUES ('zun', 'ཟུ་ནི་སྐད།');
INSERT INTO [country] ([id], [name]) VALUES ('zu', 'ཟུ་ལུ་སྐད།');
INSERT INTO [country] ([id], [name]) VALUES ('zen', 'ཟེ་ན་གཱ་སྐད།');
INSERT INTO [country] ([id], [name]) VALUES ('de', 'འཇར་མན་གྱི།');
INSERT INTO [country] ([id], [name]) VALUES ('ja', 'རི་པིན་སྐད་');
INSERT INTO [country] ([id], [name]) VALUES ('zh', 'རྒྱ་སྐད་');
INSERT INTO [country] ([id], [name]) VALUES ('dz', 'རྫོང་ཁ');
INSERT INTO [country] ([id], [name]) VALUES ('la', 'ལེ་ཊིན་སྐད།');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hans', 'སྟབས་བརྡའི།  ཀྲུང་གོའི།');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hant', 'སྲོལ་རྒྱུན་གྱི།');
INSERT INTO [country] ([id], [name]) VALUES ('hi', 'ཧིན་དི');
INSERT INTO [country] ([id], [name]) VALUES ('fr', 'ཧྥ་རན་སིའི་།');
INSERT INTO [country] ([id], [name]) VALUES ('en', 'ཨིང་ལིཤ་སྐད།');
INSERT INTO [country] ([id], [name]) VALUES ('en_CA', 'ཨིང་ལིཤ་སྐད། (ཁེ་ན་ཌ་)');
INSERT INTO [country] ([id], [name]) VALUES ('en_GB', 'ཨིང་ལིཤ་སྐད། (རྦི་རི་ཊིཤ་)');
INSERT INTO [country] ([id], [name]) VALUES ('en_US', 'ཨིང་ལིཤ་སྐད། (ཨ་རི་)');
INSERT INTO [country] ([id], [name]) VALUES ('ru', 'ཨུ་རུ་སུ་སྐད་');
