CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('zxx', 'Nessun contenuto linguistico');
INSERT INTO "country" ("id", "name") VALUES ('ab', 'abkhazian');
INSERT INTO "country" ("id", "name") VALUES ('akk', 'accado');
INSERT INTO "country" ("id", "name") VALUES ('ace', 'accinese');
INSERT INTO "country" ("id", "name") VALUES ('ach', 'acioli');
INSERT INTO "country" ("id", "name") VALUES ('ada', 'adangme');
INSERT INTO "country" ("id", "name") VALUES ('ady', 'adyghe');
INSERT INTO "country" ("id", "name") VALUES ('aa', 'afar');
INSERT INTO "country" ("id", "name") VALUES ('afh', 'afrihili');
INSERT INTO "country" ("id", "name") VALUES ('af', 'afrikaans');
INSERT INTO "country" ("id", "name") VALUES ('ain', 'ainu');
INSERT INTO "country" ("id", "name") VALUES ('ak', 'akan');
INSERT INTO "country" ("id", "name") VALUES ('sq', 'albanese');
INSERT INTO "country" ("id", "name") VALUES ('ale', 'aleuto');
INSERT INTO "country" ("id", "name") VALUES ('alt', 'altai meridionale');
INSERT INTO "country" ("id", "name") VALUES ('hsb', 'alto sorabo');
INSERT INTO "country" ("id", "name") VALUES ('de_CH', 'alto tedesco svizzero');
INSERT INTO "country" ("id", "name") VALUES ('am', 'amarico');
INSERT INTO "country" ("id", "name") VALUES ('anp', 'angika');
INSERT INTO "country" ("id", "name") VALUES ('ar', 'arabo');
INSERT INTO "country" ("id", "name") VALUES ('an', 'aragonese');
INSERT INTO "country" ("id", "name") VALUES ('arc', 'aramaico');
INSERT INTO "country" ("id", "name") VALUES ('sam', 'aramaico samaritano');
INSERT INTO "country" ("id", "name") VALUES ('arp', 'arapaho');
INSERT INTO "country" ("id", "name") VALUES ('arn', 'araucano');
INSERT INTO "country" ("id", "name") VALUES ('hy', 'armeno');
INSERT INTO "country" ("id", "name") VALUES ('arw', 'aruaco');
INSERT INTO "country" ("id", "name") VALUES ('rup', 'arumeno');
INSERT INTO "country" ("id", "name") VALUES ('as', 'assamese');
INSERT INTO "country" ("id", "name") VALUES ('ast', 'asturiano');
INSERT INTO "country" ("id", "name") VALUES ('cch', 'atsam');
INSERT INTO "country" ("id", "name") VALUES ('map', 'austronesiano');
INSERT INTO "country" ("id", "name") VALUES ('av', 'avaro');
INSERT INTO "country" ("id", "name") VALUES ('ae', 'avestan');
INSERT INTO "country" ("id", "name") VALUES ('awa', 'awadhi');
INSERT INTO "country" ("id", "name") VALUES ('ay', 'aymara');
INSERT INTO "country" ("id", "name") VALUES ('az', 'azerbaigiano');
INSERT INTO "country" ("id", "name") VALUES ('ban', 'balinese');
INSERT INTO "country" ("id", "name") VALUES ('bm', 'bambara');
INSERT INTO "country" ("id", "name") VALUES ('bad', 'banda');
INSERT INTO "country" ("id", "name") VALUES ('bnt', 'bantu');
INSERT INTO "country" ("id", "name") VALUES ('bas', 'basa');
INSERT INTO "country" ("id", "name") VALUES ('ba', 'baschiro');
INSERT INTO "country" ("id", "name") VALUES ('eu', 'basco');
INSERT INTO "country" ("id", "name") VALUES ('dsb', 'basso sorabo');
INSERT INTO "country" ("id", "name") VALUES ('nds', 'basso tedesco');
INSERT INTO "country" ("id", "name") VALUES ('btk', 'batak');
INSERT INTO "country" ("id", "name") VALUES ('bej', 'begia');
INSERT INTO "country" ("id", "name") VALUES ('bal', 'beluci');
INSERT INTO "country" ("id", "name") VALUES ('bn', 'bengalese');
INSERT INTO "country" ("id", "name") VALUES ('ber', 'berbero');
INSERT INTO "country" ("id", "name") VALUES ('bho', 'bhojpuri');
INSERT INTO "country" ("id", "name") VALUES ('bik', 'bicol');
INSERT INTO "country" ("id", "name") VALUES ('be', 'bielorusso');
INSERT INTO "country" ("id", "name") VALUES ('bh', 'bihari');
INSERT INTO "country" ("id", "name") VALUES ('bin', 'bini');
INSERT INTO "country" ("id", "name") VALUES ('my', 'birmano');
INSERT INTO "country" ("id", "name") VALUES ('bi', 'bislama');
INSERT INTO "country" ("id", "name") VALUES ('byn', 'blin');
INSERT INTO "country" ("id", "name") VALUES ('bs', 'bosniaco');
INSERT INTO "country" ("id", "name") VALUES ('bra', 'braj');
INSERT INTO "country" ("id", "name") VALUES ('br', 'bretone');
INSERT INTO "country" ("id", "name") VALUES ('bug', 'bugi');
INSERT INTO "country" ("id", "name") VALUES ('bg', 'bulgaro');
INSERT INTO "country" ("id", "name") VALUES ('bua', 'buriat');
INSERT INTO "country" ("id", "name") VALUES ('cad', 'caddo');
INSERT INTO "country" ("id", "name") VALUES ('krl', 'careliano');
INSERT INTO "country" ("id", "name") VALUES ('car', 'caribico');
INSERT INTO "country" ("id", "name") VALUES ('ca', 'catalano');
INSERT INTO "country" ("id", "name") VALUES ('ceb', 'cebuano');
INSERT INTO "country" ("id", "name") VALUES ('ce', 'ceceno');
INSERT INTO "country" ("id", "name") VALUES ('cs', 'ceco');
INSERT INTO "country" ("id", "name") VALUES ('cel', 'celtica altra lingua');
INSERT INTO "country" ("id", "name") VALUES ('ch', 'chamorro');
INSERT INTO "country" ("id", "name") VALUES ('chr', 'cherokee');
INSERT INTO "country" ("id", "name") VALUES ('chy', 'cheyenne');
INSERT INTO "country" ("id", "name") VALUES ('chb', 'chibcha');
INSERT INTO "country" ("id", "name") VALUES ('chp', 'chipewyan');
INSERT INTO "country" ("id", "name") VALUES ('cho', 'choctaw');
INSERT INTO "country" ("id", "name") VALUES ('chk', 'chuukese');
INSERT INTO "country" ("id", "name") VALUES ('cv', 'chuvash');
INSERT INTO "country" ("id", "name") VALUES ('tw', 'ci');
INSERT INTO "country" ("id", "name") VALUES ('chg', 'ciagataico');
INSERT INTO "country" ("id", "name") VALUES ('zh', 'cinese');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hans', 'cinese semplificato');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hant', 'cinese tradizionale');
INSERT INTO "country" ("id", "name") VALUES ('cop', 'copto');
INSERT INTO "country" ("id", "name") VALUES ('ko', 'coreano');
INSERT INTO "country" ("id", "name") VALUES ('kw', 'cornico');
INSERT INTO "country" ("id", "name") VALUES ('co', 'corso');
INSERT INTO "country" ("id", "name") VALUES ('cr', 'cree');
INSERT INTO "country" ("id", "name") VALUES ('mus', 'creek');
INSERT INTO "country" ("id", "name") VALUES ('crp', 'creolo o pidgin');
INSERT INTO "country" ("id", "name") VALUES ('cpf', 'creolo o pidgin basati sul francese');
INSERT INTO "country" ("id", "name") VALUES ('cpp', 'creolo o pidgin basati sul portoghese');
INSERT INTO "country" ("id", "name") VALUES ('cpe', 'creolo o pidgin basati sull\'inglese');
INSERT INTO "country" ("id", "name") VALUES ('hr', 'croato');
INSERT INTO "country" ("id", "name") VALUES ('ku', 'curdo');
INSERT INTO "country" ("id", "name") VALUES ('dak', 'dakota');
INSERT INTO "country" ("id", "name") VALUES ('da', 'danese');
INSERT INTO "country" ("id", "name") VALUES ('dar', 'dargwa');
INSERT INTO "country" ("id", "name") VALUES ('day', 'dayak');
INSERT INTO "country" ("id", "name") VALUES ('del', 'delaware');
INSERT INTO "country" ("id", "name") VALUES ('din', 'dinca');
INSERT INTO "country" ("id", "name") VALUES ('dyu', 'diula');
INSERT INTO "country" ("id", "name") VALUES ('dv', 'divehi');
INSERT INTO "country" ("id", "name") VALUES ('doi', 'dogri');
INSERT INTO "country" ("id", "name") VALUES ('dgr', 'dogrib');
INSERT INTO "country" ("id", "name") VALUES ('dua', 'duala');
INSERT INTO "country" ("id", "name") VALUES ('dz', 'dzongkha');
INSERT INTO "country" ("id", "name") VALUES ('he', 'ebraico');
INSERT INTO "country" ("id", "name") VALUES ('efi', 'efik');
INSERT INTO "country" ("id", "name") VALUES ('egy', 'egiziano antico');
INSERT INTO "country" ("id", "name") VALUES ('eka', 'ekajuka');
INSERT INTO "country" ("id", "name") VALUES ('elx', 'elamitico');
INSERT INTO "country" ("id", "name") VALUES ('myv', 'erzya');
INSERT INTO "country" ("id", "name") VALUES ('eo', 'esperanto');
INSERT INTO "country" ("id", "name") VALUES ('et', 'estone');
INSERT INTO "country" ("id", "name") VALUES ('ee', 'ewe');
INSERT INTO "country" ("id", "name") VALUES ('ewo', 'ewondo');
INSERT INTO "country" ("id", "name") VALUES ('fan', 'fang');
INSERT INTO "country" ("id", "name") VALUES ('fat', 'fanti');
INSERT INTO "country" ("id", "name") VALUES ('fo', 'faroese');
INSERT INTO "country" ("id", "name") VALUES ('phn', 'fenicio');
INSERT INTO "country" ("id", "name") VALUES ('nl_BE', 'fiammingo belga');
INSERT INTO "country" ("id", "name") VALUES ('fj', 'figiano');
INSERT INTO "country" ("id", "name") VALUES ('fil', 'filippino');
INSERT INTO "country" ("id", "name") VALUES ('fi', 'finlandese');
INSERT INTO "country" ("id", "name") VALUES ('fr', 'francese');
INSERT INTO "country" ("id", "name") VALUES ('fro', 'francese antico');
INSERT INTO "country" ("id", "name") VALUES ('fr_CA', 'francese canadese');
INSERT INTO "country" ("id", "name") VALUES ('frm', 'francese medio');
INSERT INTO "country" ("id", "name") VALUES ('fr_CH', 'francese svizzero');
INSERT INTO "country" ("id", "name") VALUES ('fy', 'frisone');
INSERT INTO "country" ("id", "name") VALUES ('frr', 'frisone settentrionale');
INSERT INTO "country" ("id", "name") VALUES ('fur', 'friulano');
INSERT INTO "country" ("id", "name") VALUES ('ff', 'fulah');
INSERT INTO "country" ("id", "name") VALUES ('gaa', 'ga');
INSERT INTO "country" ("id", "name") VALUES ('gd', 'gaelico scozzese');
INSERT INTO "country" ("id", "name") VALUES ('gl', 'galiziano');
INSERT INTO "country" ("id", "name") VALUES ('cy', 'gallese');
INSERT INTO "country" ("id", "name") VALUES ('lg', 'ganda');
INSERT INTO "country" ("id", "name") VALUES ('gay', 'gayo');
INSERT INTO "country" ("id", "name") VALUES ('gba', 'gbaya');
INSERT INTO "country" ("id", "name") VALUES ('gez', 'geez');
INSERT INTO "country" ("id", "name") VALUES ('ka', 'georgiano');
INSERT INTO "country" ("id", "name") VALUES ('grb', 'gerbo');
INSERT INTO "country" ("id", "name") VALUES ('chn', 'gergo chinook');
INSERT INTO "country" ("id", "name") VALUES ('ja', 'giapponese');
INSERT INTO "country" ("id", "name") VALUES ('jv', 'giavanese');
INSERT INTO "country" ("id", "name") VALUES ('gil', 'gilbertese');
INSERT INTO "country" ("id", "name") VALUES ('jrb', 'giudeo arabo');
INSERT INTO "country" ("id", "name") VALUES ('jpr', 'giudeo persiano');
INSERT INTO "country" ("id", "name") VALUES ('gon', 'gondi');
INSERT INTO "country" ("id", "name") VALUES ('gor', 'gorontalo');
INSERT INTO "country" ("id", "name") VALUES ('got', 'gotico');
INSERT INTO "country" ("id", "name") VALUES ('el', 'greco');
INSERT INTO "country" ("id", "name") VALUES ('grc', 'greco antico');
INSERT INTO "country" ("id", "name") VALUES ('gn', 'guarana');
INSERT INTO "country" ("id", "name") VALUES ('gu', 'gujarati');
INSERT INTO "country" ("id", "name") VALUES ('gwi', 'gwichʼin');
INSERT INTO "country" ("id", "name") VALUES ('hai', 'haida');
INSERT INTO "country" ("id", "name") VALUES ('ht', 'haitiano');
INSERT INTO "country" ("id", "name") VALUES ('ha', 'haussa');
INSERT INTO "country" ("id", "name") VALUES ('haw', 'hawaiano');
INSERT INTO "country" ("id", "name") VALUES ('hz', 'herero');
INSERT INTO "country" ("id", "name") VALUES ('hil', 'hiligayna');
INSERT INTO "country" ("id", "name") VALUES ('him', 'himachali');
INSERT INTO "country" ("id", "name") VALUES ('hi', 'hindi');
INSERT INTO "country" ("id", "name") VALUES ('ho', 'hiri motu');
INSERT INTO "country" ("id", "name") VALUES ('hit', 'hittite');
INSERT INTO "country" ("id", "name") VALUES ('hmn', 'hmong');
INSERT INTO "country" ("id", "name") VALUES ('hup', 'hupa');
INSERT INTO "country" ("id", "name") VALUES ('iba', 'iban');
INSERT INTO "country" ("id", "name") VALUES ('io', 'ido');
INSERT INTO "country" ("id", "name") VALUES ('ig', 'igbo');
INSERT INTO "country" ("id", "name") VALUES ('ilo', 'ilocano');
INSERT INTO "country" ("id", "name") VALUES ('id', 'indonesiano');
INSERT INTO "country" ("id", "name") VALUES ('en', 'inglese');
INSERT INTO "country" ("id", "name") VALUES ('en_US', 'inglese americano');
INSERT INTO "country" ("id", "name") VALUES ('ang', 'inglese antico');
INSERT INTO "country" ("id", "name") VALUES ('en_AU', 'inglese australiano');
INSERT INTO "country" ("id", "name") VALUES ('en_GB', 'inglese britannico');
INSERT INTO "country" ("id", "name") VALUES ('en_CA', 'inglese canadese');
INSERT INTO "country" ("id", "name") VALUES ('enm', 'inglese medio');
INSERT INTO "country" ("id", "name") VALUES ('inh', 'ingush');
INSERT INTO "country" ("id", "name") VALUES ('ia', 'interlingua');
INSERT INTO "country" ("id", "name") VALUES ('ie', 'interlingue');
INSERT INTO "country" ("id", "name") VALUES ('iu', 'inuktitut');
INSERT INTO "country" ("id", "name") VALUES ('ik', 'inupiak');
INSERT INTO "country" ("id", "name") VALUES ('ira', 'iraniana');
INSERT INTO "country" ("id", "name") VALUES ('ga', 'irlandese');
INSERT INTO "country" ("id", "name") VALUES ('sga', 'irlandese antico');
INSERT INTO "country" ("id", "name") VALUES ('mga', 'irlandese medio');
INSERT INTO "country" ("id", "name") VALUES ('is', 'islandese');
INSERT INTO "country" ("id", "name") VALUES ('it', 'italiano');
INSERT INTO "country" ("id", "name") VALUES ('kbd', 'kabardia');
INSERT INTO "country" ("id", "name") VALUES ('kab', 'kabyle');
INSERT INTO "country" ("id", "name") VALUES ('kac', 'kachin');
INSERT INTO "country" ("id", "name") VALUES ('kaj', 'kai');
INSERT INTO "country" ("id", "name") VALUES ('kl', 'kalaallisut');
INSERT INTO "country" ("id", "name") VALUES ('xal', 'kalmyk');
INSERT INTO "country" ("id", "name") VALUES ('kam', 'kamba');
INSERT INTO "country" ("id", "name") VALUES ('kn', 'kannada');
INSERT INTO "country" ("id", "name") VALUES ('kr', 'kanuri');
INSERT INTO "country" ("id", "name") VALUES ('kaa', 'kara-kalpak');
INSERT INTO "country" ("id", "name") VALUES ('krc', 'karachay-Balkar');
INSERT INTO "country" ("id", "name") VALUES ('kar', 'karen');
INSERT INTO "country" ("id", "name") VALUES ('ks', 'kashmiri');
INSERT INTO "country" ("id", "name") VALUES ('csb', 'kashubian');
INSERT INTO "country" ("id", "name") VALUES ('kaw', 'kawi');
INSERT INTO "country" ("id", "name") VALUES ('kk', 'kazako');
INSERT INTO "country" ("id", "name") VALUES ('kfo', 'kfo');
INSERT INTO "country" ("id", "name") VALUES ('kha', 'khasi');
INSERT INTO "country" ("id", "name") VALUES ('km', 'khmer');
INSERT INTO "country" ("id", "name") VALUES ('kho', 'khotanese');
INSERT INTO "country" ("id", "name") VALUES ('ki', 'kikuyu');
INSERT INTO "country" ("id", "name") VALUES ('kmb', 'kimbundu');
INSERT INTO "country" ("id", "name") VALUES ('rw', 'kinyarwanda');
INSERT INTO "country" ("id", "name") VALUES ('ky', 'kirghiso');
INSERT INTO "country" ("id", "name") VALUES ('tlh', 'klingon');
INSERT INTO "country" ("id", "name") VALUES ('kv', 'komi');
INSERT INTO "country" ("id", "name") VALUES ('kg', 'kongo');
INSERT INTO "country" ("id", "name") VALUES ('kok', 'konkani');
INSERT INTO "country" ("id", "name") VALUES ('kos', 'kosraean');
INSERT INTO "country" ("id", "name") VALUES ('kpe', 'kpelle');
INSERT INTO "country" ("id", "name") VALUES ('kro', 'kru');
INSERT INTO "country" ("id", "name") VALUES ('kj', 'kuanyama');
INSERT INTO "country" ("id", "name") VALUES ('kum', 'kumyk');
INSERT INTO "country" ("id", "name") VALUES ('kru', 'kurukh');
INSERT INTO "country" ("id", "name") VALUES ('kut', 'kutenai');
INSERT INTO "country" ("id", "name") VALUES ('lad', 'ladino');
INSERT INTO "country" ("id", "name") VALUES ('lah', 'lahnda');
INSERT INTO "country" ("id", "name") VALUES ('lam', 'lamba');
INSERT INTO "country" ("id", "name") VALUES ('lo', 'lao');
INSERT INTO "country" ("id", "name") VALUES ('la', 'latino');
INSERT INTO "country" ("id", "name") VALUES ('lv', 'lettone');
INSERT INTO "country" ("id", "name") VALUES ('lez', 'lezghian');
INSERT INTO "country" ("id", "name") VALUES ('li', 'limburgese');
INSERT INTO "country" ("id", "name") VALUES ('ln', 'lingala');
INSERT INTO "country" ("id", "name") VALUES ('afa', 'lingua afroasiatica');
INSERT INTO "country" ("id", "name") VALUES ('tut', 'lingua altaica');
INSERT INTO "country" ("id", "name") VALUES ('art', 'lingua artificiale');
INSERT INTO "country" ("id", "name") VALUES ('bat', 'lingua baltica');
INSERT INTO "country" ("id", "name") VALUES ('cau', 'lingua caucasica');
INSERT INTO "country" ("id", "name") VALUES ('cus', 'lingua cuscitica');
INSERT INTO "country" ("id", "name") VALUES ('dra', 'lingua dravidica');
INSERT INTO "country" ("id", "name") VALUES ('phi', 'lingua filippina');
INSERT INTO "country" ("id", "name") VALUES ('gem', 'lingua germanica');
INSERT INTO "country" ("id", "name") VALUES ('und', 'lingua imprecisata');
INSERT INTO "country" ("id", "name") VALUES ('inc', 'lingua indiana');
INSERT INTO "country" ("id", "name") VALUES ('nai', 'lingua indiana del Nord America');
INSERT INTO "country" ("id", "name") VALUES ('sai', 'lingua indiana del Sud America');
INSERT INTO "country" ("id", "name") VALUES ('cai', 'lingua indiana dell\'America Centrale');
INSERT INTO "country" ("id", "name") VALUES ('ine', 'lingua indoeuropea');
INSERT INTO "country" ("id", "name") VALUES ('khi', 'lingua khoisan');
INSERT INTO "country" ("id", "name") VALUES ('mkh', 'lingua mon-khmer');
INSERT INTO "country" ("id", "name") VALUES ('mun', 'lingua munda');
INSERT INTO "country" ("id", "name") VALUES ('nic', 'lingua niger-cordofan');
INSERT INTO "country" ("id", "name") VALUES ('ssa', 'lingua nilo-sahariana');
INSERT INTO "country" ("id", "name") VALUES ('paa', 'lingua papuana');
INSERT INTO "country" ("id", "name") VALUES ('rm', 'lingua rhaeto-romance');
INSERT INTO "country" ("id", "name") VALUES ('roa', 'lingua romanza');
INSERT INTO "country" ("id", "name") VALUES ('smi', 'lingua sami');
INSERT INTO "country" ("id", "name") VALUES ('sem', 'lingua semitica');
INSERT INTO "country" ("id", "name") VALUES ('sit', 'lingua sino-tibetana');
INSERT INTO "country" ("id", "name") VALUES ('sla', 'lingua slava');
INSERT INTO "country" ("id", "name") VALUES ('tai', 'lingua tailandese');
INSERT INTO "country" ("id", "name") VALUES ('fiu', 'lingua ungrofinnica');
INSERT INTO "country" ("id", "name") VALUES ('alg', 'lingue algonchine');
INSERT INTO "country" ("id", "name") VALUES ('apa', 'lingue apache');
INSERT INTO "country" ("id", "name") VALUES ('ath', 'lingue athabaska');
INSERT INTO "country" ("id", "name") VALUES ('aus', 'lingue australiane');
INSERT INTO "country" ("id", "name") VALUES ('bai', 'lingue bamileke');
INSERT INTO "country" ("id", "name") VALUES ('cmc', 'lingue chamic');
INSERT INTO "country" ("id", "name") VALUES ('mis', 'lingue diverse');
INSERT INTO "country" ("id", "name") VALUES ('iro', 'lingue irochesi');
INSERT INTO "country" ("id", "name") VALUES ('myn', 'lingue maya');
INSERT INTO "country" ("id", "name") VALUES ('oto', 'lingue otomi');
INSERT INTO "country" ("id", "name") VALUES ('sal', 'lingue salish');
INSERT INTO "country" ("id", "name") VALUES ('sgn', 'lingue sign');
INSERT INTO "country" ("id", "name") VALUES ('sio', 'lingue sioux');
INSERT INTO "country" ("id", "name") VALUES ('tup', 'lingue tupi');
INSERT INTO "country" ("id", "name") VALUES ('wak', 'lingue wakash');
INSERT INTO "country" ("id", "name") VALUES ('ypk', 'lingue yupik');
INSERT INTO "country" ("id", "name") VALUES ('lt', 'lituano');
INSERT INTO "country" ("id", "name") VALUES ('jbo', 'lojban');
INSERT INTO "country" ("id", "name") VALUES ('lol', 'lolo bantu');
INSERT INTO "country" ("id", "name") VALUES ('loz', 'lozi');
INSERT INTO "country" ("id", "name") VALUES ('lu', 'luba-katanga');
INSERT INTO "country" ("id", "name") VALUES ('lua', 'luba-lulua');
INSERT INTO "country" ("id", "name") VALUES ('lui', 'luiseno');
INSERT INTO "country" ("id", "name") VALUES ('lun', 'lunda');
INSERT INTO "country" ("id", "name") VALUES ('luo', 'luo');
INSERT INTO "country" ("id", "name") VALUES ('lus', 'lushai');
INSERT INTO "country" ("id", "name") VALUES ('lb', 'lussemburghese');
INSERT INTO "country" ("id", "name") VALUES ('mk', 'macedone');
INSERT INTO "country" ("id", "name") VALUES ('mad', 'madurese');
INSERT INTO "country" ("id", "name") VALUES ('mag', 'magahi');
INSERT INTO "country" ("id", "name") VALUES ('mai', 'maithili');
INSERT INTO "country" ("id", "name") VALUES ('mak', 'makasar');
INSERT INTO "country" ("id", "name") VALUES ('ml', 'malayalam');
INSERT INTO "country" ("id", "name") VALUES ('ms', 'malese');
INSERT INTO "country" ("id", "name") VALUES ('mg', 'malgascio');
INSERT INTO "country" ("id", "name") VALUES ('mt', 'maltese');
INSERT INTO "country" ("id", "name") VALUES ('mnc', 'manchu');
INSERT INTO "country" ("id", "name") VALUES ('mdr', 'mandar');
INSERT INTO "country" ("id", "name") VALUES ('man', 'mandingo');
INSERT INTO "country" ("id", "name") VALUES ('mni', 'manipuri');
INSERT INTO "country" ("id", "name") VALUES ('mno', 'manobo');
INSERT INTO "country" ("id", "name") VALUES ('gv', 'manx');
INSERT INTO "country" ("id", "name") VALUES ('mi', 'maori');
INSERT INTO "country" ("id", "name") VALUES ('mr', 'marathi');
INSERT INTO "country" ("id", "name") VALUES ('chm', 'mari');
INSERT INTO "country" ("id", "name") VALUES ('mh', 'marshallese');
INSERT INTO "country" ("id", "name") VALUES ('mwr', 'marwari');
INSERT INTO "country" ("id", "name") VALUES ('mas', 'masai');
INSERT INTO "country" ("id", "name") VALUES ('umb', 'mbundu');
INSERT INTO "country" ("id", "name") VALUES ('min', 'menangkabau');
INSERT INTO "country" ("id", "name") VALUES ('men', 'mende');
INSERT INTO "country" ("id", "name") VALUES ('mic', 'micmac');
INSERT INTO "country" ("id", "name") VALUES ('mwl', 'mirandese');
INSERT INTO "country" ("id", "name") VALUES ('moh', 'mohawk');
INSERT INTO "country" ("id", "name") VALUES ('mdf', 'moksha');
INSERT INTO "country" ("id", "name") VALUES ('mo', 'moldavo');
INSERT INTO "country" ("id", "name") VALUES ('mn', 'mongolo');
INSERT INTO "country" ("id", "name") VALUES ('mos', 'mossi');
INSERT INTO "country" ("id", "name") VALUES ('mul', 'multilingua');
INSERT INTO "country" ("id", "name") VALUES ('nqo', 'n\'ko');
INSERT INTO "country" ("id", "name") VALUES ('nah', 'nahuatl');
INSERT INTO "country" ("id", "name") VALUES ('nap', 'napoletano');
INSERT INTO "country" ("id", "name") VALUES ('na', 'nauru');
INSERT INTO "country" ("id", "name") VALUES ('nv', 'navajo');
INSERT INTO "country" ("id", "name") VALUES ('nd', 'ndebele del nord');
INSERT INTO "country" ("id", "name") VALUES ('nr', 'ndebele del sud');
INSERT INTO "country" ("id", "name") VALUES ('ng', 'ndonga');
INSERT INTO "country" ("id", "name") VALUES ('ne', 'nepalese');
INSERT INTO "country" ("id", "name") VALUES ('new', 'newari');
INSERT INTO "country" ("id", "name") VALUES ('nwc', 'newari classico');
INSERT INTO "country" ("id", "name") VALUES ('nia', 'nias');
INSERT INTO "country" ("id", "name") VALUES ('niu', 'niue');
INSERT INTO "country" ("id", "name") VALUES ('nog', 'nogai');
INSERT INTO "country" ("id", "name") VALUES ('non', 'norse antico');
INSERT INTO "country" ("id", "name") VALUES ('no', 'norvegese');
INSERT INTO "country" ("id", "name") VALUES ('nb', 'norvegese bokmal');
INSERT INTO "country" ("id", "name") VALUES ('nn', 'norvegese nynorsk');
INSERT INTO "country" ("id", "name") VALUES ('nub', 'nubiano');
INSERT INTO "country" ("id", "name") VALUES ('nym', 'nyamwezi');
INSERT INTO "country" ("id", "name") VALUES ('ny', 'nyanja');
INSERT INTO "country" ("id", "name") VALUES ('nyn', 'nyankole');
INSERT INTO "country" ("id", "name") VALUES ('tog', 'nyasa del Tonga');
INSERT INTO "country" ("id", "name") VALUES ('nyo', 'nyoro');
INSERT INTO "country" ("id", "name") VALUES ('nzi', 'nzima');
INSERT INTO "country" ("id", "name") VALUES ('oc', 'occitano');
INSERT INTO "country" ("id", "name") VALUES ('oj', 'ojibwa');
INSERT INTO "country" ("id", "name") VALUES ('nl', 'olandese');
INSERT INTO "country" ("id", "name") VALUES ('dum', 'olandese medio');
INSERT INTO "country" ("id", "name") VALUES ('or', 'oriya');
INSERT INTO "country" ("id", "name") VALUES ('om', 'oromo');
INSERT INTO "country" ("id", "name") VALUES ('osa', 'osage');
INSERT INTO "country" ("id", "name") VALUES ('os', 'ossetico');
INSERT INTO "country" ("id", "name") VALUES ('pal', 'pahlavi');
INSERT INTO "country" ("id", "name") VALUES ('pau', 'palau');
INSERT INTO "country" ("id", "name") VALUES ('pi', 'pali');
INSERT INTO "country" ("id", "name") VALUES ('pam', 'pampanga');
INSERT INTO "country" ("id", "name") VALUES ('pag', 'pangasinan');
INSERT INTO "country" ("id", "name") VALUES ('pap', 'papiamento');
INSERT INTO "country" ("id", "name") VALUES ('ps', 'pashto');
INSERT INTO "country" ("id", "name") VALUES ('fa', 'persiano');
INSERT INTO "country" ("id", "name") VALUES ('peo', 'persiano antico');
INSERT INTO "country" ("id", "name") VALUES ('pl', 'polacco');
INSERT INTO "country" ("id", "name") VALUES ('pon', 'ponape');
INSERT INTO "country" ("id", "name") VALUES ('pt', 'portoghese');
INSERT INTO "country" ("id", "name") VALUES ('pt_BR', 'portoghese brasiliano');
INSERT INTO "country" ("id", "name") VALUES ('pt_PT', 'portoghese del Portogallo');
INSERT INTO "country" ("id", "name") VALUES ('pra', 'pracrito');
INSERT INTO "country" ("id", "name") VALUES ('pro', 'provenzale antico');
INSERT INTO "country" ("id", "name") VALUES ('pa', 'punjabi');
INSERT INTO "country" ("id", "name") VALUES ('qu', 'quechua');
INSERT INTO "country" ("id", "name") VALUES ('raj', 'rajasthani');
INSERT INTO "country" ("id", "name") VALUES ('rap', 'rapanui');
INSERT INTO "country" ("id", "name") VALUES ('rar', 'rarotonga');
INSERT INTO "country" ("id", "name") VALUES ('rom', 'romani');
INSERT INTO "country" ("id", "name") VALUES ('root', 'root');
INSERT INTO "country" ("id", "name") VALUES ('ro', 'rumeno');
INSERT INTO "country" ("id", "name") VALUES ('rn', 'rundi');
INSERT INTO "country" ("id", "name") VALUES ('ru', 'russo');
INSERT INTO "country" ("id", "name") VALUES ('se', 'sami del nord');
INSERT INTO "country" ("id", "name") VALUES ('sma', 'sami del sud');
INSERT INTO "country" ("id", "name") VALUES ('smn', 'sami inari');
INSERT INTO "country" ("id", "name") VALUES ('smj', 'sami lule');
INSERT INTO "country" ("id", "name") VALUES ('sms', 'sami skolt');
INSERT INTO "country" ("id", "name") VALUES ('sm', 'samoano');
INSERT INTO "country" ("id", "name") VALUES ('sad', 'sandawe');
INSERT INTO "country" ("id", "name") VALUES ('sg', 'sango');
INSERT INTO "country" ("id", "name") VALUES ('sa', 'sanscrito');
INSERT INTO "country" ("id", "name") VALUES ('sat', 'santali');
INSERT INTO "country" ("id", "name") VALUES ('sc', 'sardo');
INSERT INTO "country" ("id", "name") VALUES ('sas', 'sasak');
INSERT INTO "country" ("id", "name") VALUES ('sco', 'scozzese');
INSERT INTO "country" ("id", "name") VALUES ('sel', 'selkup');
INSERT INTO "country" ("id", "name") VALUES ('sr', 'serbo');
INSERT INTO "country" ("id", "name") VALUES ('sh', 'serbo-croato');
INSERT INTO "country" ("id", "name") VALUES ('srr', 'serer');
INSERT INTO "country" ("id", "name") VALUES ('shn', 'shan');
INSERT INTO "country" ("id", "name") VALUES ('sn', 'shona');
INSERT INTO "country" ("id", "name") VALUES ('ii', 'sichuan yi');
INSERT INTO "country" ("id", "name") VALUES ('scn', 'siciliano');
INSERT INTO "country" ("id", "name") VALUES ('sid', 'sidamo');
INSERT INTO "country" ("id", "name") VALUES ('bla', 'siksika');
INSERT INTO "country" ("id", "name") VALUES ('sd', 'sindhi');
INSERT INTO "country" ("id", "name") VALUES ('si', 'singalese');
INSERT INTO "country" ("id", "name") VALUES ('syr', 'siriaco');
INSERT INTO "country" ("id", "name") VALUES ('den', 'slave');
INSERT INTO "country" ("id", "name") VALUES ('cu', 'slavo della Chiesa');
INSERT INTO "country" ("id", "name") VALUES ('sk', 'slovacco');
INSERT INTO "country" ("id", "name") VALUES ('sl', 'sloveno');
INSERT INTO "country" ("id", "name") VALUES ('sog', 'sogdiano');
INSERT INTO "country" ("id", "name") VALUES ('so', 'somalo');
INSERT INTO "country" ("id", "name") VALUES ('son', 'songhai');
INSERT INTO "country" ("id", "name") VALUES ('snk', 'soninke');
INSERT INTO "country" ("id", "name") VALUES ('wen', 'sorabo');
INSERT INTO "country" ("id", "name") VALUES ('nso', 'sotho del nord');
INSERT INTO "country" ("id", "name") VALUES ('st', 'sotho del sud');
INSERT INTO "country" ("id", "name") VALUES ('es', 'spagnolo');
INSERT INTO "country" ("id", "name") VALUES ('es_ES', 'spagnolo della Spagna');
INSERT INTO "country" ("id", "name") VALUES ('es_419', 'spagnolo latinoamericano');
INSERT INTO "country" ("id", "name") VALUES ('srn', 'sranan tongo');
INSERT INTO "country" ("id", "name") VALUES ('suk', 'sukuma');
INSERT INTO "country" ("id", "name") VALUES ('sux', 'sumero');
INSERT INTO "country" ("id", "name") VALUES ('su', 'sundanese');
INSERT INTO "country" ("id", "name") VALUES ('sus', 'susu');
INSERT INTO "country" ("id", "name") VALUES ('sv', 'svedese');
INSERT INTO "country" ("id", "name") VALUES ('sw', 'swahili');
INSERT INTO "country" ("id", "name") VALUES ('ss', 'swati');
INSERT INTO "country" ("id", "name") VALUES ('tl', 'tagalog');
INSERT INTO "country" ("id", "name") VALUES ('tg', 'tagicco');
INSERT INTO "country" ("id", "name") VALUES ('ty', 'taitiano');
INSERT INTO "country" ("id", "name") VALUES ('tmh', 'tamashek');
INSERT INTO "country" ("id", "name") VALUES ('ta', 'tamil');
INSERT INTO "country" ("id", "name") VALUES ('tt', 'tatarico');
INSERT INTO "country" ("id", "name") VALUES ('de', 'tedesco');
INSERT INTO "country" ("id", "name") VALUES ('goh', 'tedesco antico alto');
INSERT INTO "country" ("id", "name") VALUES ('de_AT', 'tedesco austriaco');
INSERT INTO "country" ("id", "name") VALUES ('gmh', 'tedesco medio alto');
INSERT INTO "country" ("id", "name") VALUES ('gsw', 'tedesco svizzero');
INSERT INTO "country" ("id", "name") VALUES ('te', 'telugu');
INSERT INTO "country" ("id", "name") VALUES ('tem', 'temne');
INSERT INTO "country" ("id", "name") VALUES ('ter', 'tereno');
INSERT INTO "country" ("id", "name") VALUES ('tet', 'tetum');
INSERT INTO "country" ("id", "name") VALUES ('th', 'thai');
INSERT INTO "country" ("id", "name") VALUES ('bo', 'tibetano');
INSERT INTO "country" ("id", "name") VALUES ('tig', 'tigre');
INSERT INTO "country" ("id", "name") VALUES ('ti', 'tigrinya');
INSERT INTO "country" ("id", "name") VALUES ('tiv', 'tiv');
INSERT INTO "country" ("id", "name") VALUES ('tli', 'tlingit');
INSERT INTO "country" ("id", "name") VALUES ('tpi', 'tok pisin');
INSERT INTO "country" ("id", "name") VALUES ('tkl', 'tokelau');
INSERT INTO "country" ("id", "name") VALUES ('to', 'tonga');
INSERT INTO "country" ("id", "name") VALUES ('tsi', 'tsimshian');
INSERT INTO "country" ("id", "name") VALUES ('ts', 'tsonga');
INSERT INTO "country" ("id", "name") VALUES ('tn', 'tswana');
INSERT INTO "country" ("id", "name") VALUES ('tum', 'tumbuka');
INSERT INTO "country" ("id", "name") VALUES ('tr', 'turco');
INSERT INTO "country" ("id", "name") VALUES ('crh', 'turco crimeo');
INSERT INTO "country" ("id", "name") VALUES ('ota', 'turco ottomano');
INSERT INTO "country" ("id", "name") VALUES ('tk', 'turcomanno');
INSERT INTO "country" ("id", "name") VALUES ('tvl', 'tuvalu');
INSERT INTO "country" ("id", "name") VALUES ('tyv', 'tuvinian');
INSERT INTO "country" ("id", "name") VALUES ('kcg', 'tyap');
INSERT INTO "country" ("id", "name") VALUES ('uk', 'ucraino');
INSERT INTO "country" ("id", "name") VALUES ('udm', 'udmurt');
INSERT INTO "country" ("id", "name") VALUES ('uga', 'ugaritico');
INSERT INTO "country" ("id", "name") VALUES ('ug', 'uigurico');
INSERT INTO "country" ("id", "name") VALUES ('hu', 'ungherese');
INSERT INTO "country" ("id", "name") VALUES ('ur', 'urdu');
INSERT INTO "country" ("id", "name") VALUES ('uz', 'usbeco');
INSERT INTO "country" ("id", "name") VALUES ('vai', 'vai');
INSERT INTO "country" ("id", "name") VALUES ('wa', 'vallone');
INSERT INTO "country" ("id", "name") VALUES ('ve', 'venda');
INSERT INTO "country" ("id", "name") VALUES ('vi', 'vietnamita');
INSERT INTO "country" ("id", "name") VALUES ('vo', 'volapük');
INSERT INTO "country" ("id", "name") VALUES ('wo', 'volof');
INSERT INTO "country" ("id", "name") VALUES ('vot', 'voto');
INSERT INTO "country" ("id", "name") VALUES ('wal', 'walamo');
INSERT INTO "country" ("id", "name") VALUES ('war', 'waray');
INSERT INTO "country" ("id", "name") VALUES ('was', 'washo');
INSERT INTO "country" ("id", "name") VALUES ('bem', 'wemba');
INSERT INTO "country" ("id", "name") VALUES ('xh', 'xosa');
INSERT INTO "country" ("id", "name") VALUES ('sah', 'yakut');
INSERT INTO "country" ("id", "name") VALUES ('yao', 'yao (bantu)');
INSERT INTO "country" ("id", "name") VALUES ('yap', 'yapese');
INSERT INTO "country" ("id", "name") VALUES ('yi', 'yiddish');
INSERT INTO "country" ("id", "name") VALUES ('yo', 'yoruba');
INSERT INTO "country" ("id", "name") VALUES ('znd', 'zande');
INSERT INTO "country" ("id", "name") VALUES ('zap', 'zapotec');
INSERT INTO "country" ("id", "name") VALUES ('zza', 'zaza');
INSERT INTO "country" ("id", "name") VALUES ('zen', 'zenaga');
INSERT INTO "country" ("id", "name") VALUES ('za', 'zhuang');
INSERT INTO "country" ("id", "name") VALUES ('zu', 'zulu');
INSERT INTO "country" ("id", "name") VALUES ('zun', 'zuni');
