CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('en_AU', 'австралиялық ағылшын тілі');
INSERT INTO "country" ("id", "name") VALUES ('de_AT', 'австриялық неміс тілі');
INSERT INTO "country" ("id", "name") VALUES ('en', 'ағылшын тілі');
INSERT INTO "country" ("id", "name") VALUES ('en_US', 'АҚШ ағылшын тілі');
INSERT INTO "country" ("id", "name") VALUES ('und', 'белгісіз тіл');
INSERT INTO "country" ("id", "name") VALUES ('pt_BR', 'бразилиялық португал тілі');
INSERT INTO "country" ("id", "name") VALUES ('en_GB', 'британиялық ағылшын тілі');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hant', 'дәстүрлік қытай тілі');
INSERT INTO "country" ("id", "name") VALUES ('ja', 'жапон тілі');
INSERT INTO "country" ("id", "name") VALUES ('es_ES', 'ибериялық испан тілі');
INSERT INTO "country" ("id", "name") VALUES ('pt_PT', 'ибериялық португал тілі');
INSERT INTO "country" ("id", "name") VALUES ('es', 'испан тілі');
INSERT INTO "country" ("id", "name") VALUES ('it', 'итальян тілі');
INSERT INTO "country" ("id", "name") VALUES ('en_CA', 'канадалық ағылшын тілі');
INSERT INTO "country" ("id", "name") VALUES ('fr_CA', 'канадалық француз тілі');
INSERT INTO "country" ("id", "name") VALUES ('kk', 'қазақ тілі');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hans', 'қарапайым қытай тілі');
INSERT INTO "country" ("id", "name") VALUES ('zh', 'қытай тілі');
INSERT INTO "country" ("id", "name") VALUES ('es_419', 'Латин Америкалық испан тілі');
INSERT INTO "country" ("id", "name") VALUES ('de', 'неміс тілі');
INSERT INTO "country" ("id", "name") VALUES ('ru', 'орыс тілі');
INSERT INTO "country" ("id", "name") VALUES ('pt', 'португал тілі');
INSERT INTO "country" ("id", "name") VALUES ('fr', 'француз тілі');
INSERT INTO "country" ("id", "name") VALUES ('de_CH', 'швейцариялық ұлы неміс тілі');
INSERT INTO "country" ("id", "name") VALUES ('fr_CH', 'швейцариялық француз тілі');
