CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('ab', 'Abchasisch');
INSERT INTO `country` (`id`, `name`) VALUES ('ace', 'Aceh');
INSERT INTO `country` (`id`, `name`) VALUES ('ach', 'Acholi');
INSERT INTO `country` (`id`, `name`) VALUES ('ada', 'Adangme');
INSERT INTO `country` (`id`, `name`) VALUES ('ady', 'Adygai');
INSERT INTO `country` (`id`, `name`) VALUES ('aa', 'Afar');
INSERT INTO `country` (`id`, `name`) VALUES ('afh', 'Afrihili');
INSERT INTO `country` (`id`, `name`) VALUES ('af', 'Afrikaans');
INSERT INTO `country` (`id`, `name`) VALUES ('afa', 'Afro-Asiatischi Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('ain', 'Ainu');
INSERT INTO `country` (`id`, `name`) VALUES ('ak', 'Akan');
INSERT INTO `country` (`id`, `name`) VALUES ('akk', 'Akkadisch');
INSERT INTO `country` (`id`, `name`) VALUES ('sq', 'Albanisch');
INSERT INTO `country` (`id`, `name`) VALUES ('ale', 'Aleutisch');
INSERT INTO `country` (`id`, `name`) VALUES ('alg', 'Algonkin-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('nwc', 'Alt-Newari');
INSERT INTO `country` (`id`, `name`) VALUES ('tut', 'Altaischi Schpraachä');
INSERT INTO `country` (`id`, `name`) VALUES ('fro', 'Altfranzösisch');
INSERT INTO `country` (`id`, `name`) VALUES ('grc', 'Altgriechisch');
INSERT INTO `country` (`id`, `name`) VALUES ('goh', 'Althochtüütsch');
INSERT INTO `country` (`id`, `name`) VALUES ('sga', 'Altirisch');
INSERT INTO `country` (`id`, `name`) VALUES ('non', 'Altnordisch');
INSERT INTO `country` (`id`, `name`) VALUES ('peo', 'Altpersisch');
INSERT INTO `country` (`id`, `name`) VALUES ('pro', 'Altprovenzalisch');
INSERT INTO `country` (`id`, `name`) VALUES ('syc', 'Altsyrisch');
INSERT INTO `country` (`id`, `name`) VALUES ('egy', 'Altägyptisch');
INSERT INTO `country` (`id`, `name`) VALUES ('ang', 'Altänglisch');
INSERT INTO `country` (`id`, `name`) VALUES ('en_US', 'Amerikanischs Änglisch');
INSERT INTO `country` (`id`, `name`) VALUES ('am', 'Amharisch');
INSERT INTO `country` (`id`, `name`) VALUES ('mis', 'Anderi Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('anp', 'Angika');
INSERT INTO `country` (`id`, `name`) VALUES ('apa', 'Apache-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('ar', 'Arabisch');
INSERT INTO `country` (`id`, `name`) VALUES ('an', 'Aragonesisch');
INSERT INTO `country` (`id`, `name`) VALUES ('arc', 'Aramääisch');
INSERT INTO `country` (`id`, `name`) VALUES ('arp', 'Arapaho');
INSERT INTO `country` (`id`, `name`) VALUES ('arn', 'Araukanisch');
INSERT INTO `country` (`id`, `name`) VALUES ('arw', 'Arawak');
INSERT INTO `country` (`id`, `name`) VALUES ('hy', 'Armenisch');
INSERT INTO `country` (`id`, `name`) VALUES ('rup', 'Aromunisch');
INSERT INTO `country` (`id`, `name`) VALUES ('ast', 'Aschturianisch');
INSERT INTO `country` (`id`, `name`) VALUES ('az', 'Aserbaidschanisch');
INSERT INTO `country` (`id`, `name`) VALUES ('as', 'Assamesisch');
INSERT INTO `country` (`id`, `name`) VALUES ('ath', 'Athapaskischi Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('cch', 'Atsam');
INSERT INTO `country` (`id`, `name`) VALUES ('aus', 'Auschtralischi Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('en_AU', 'Auschtralischs Änglisch');
INSERT INTO `country` (`id`, `name`) VALUES ('map', 'Auschtroneesischi Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('ae', 'Avestisch');
INSERT INTO `country` (`id`, `name`) VALUES ('awa', 'Awadhi');
INSERT INTO `country` (`id`, `name`) VALUES ('av', 'Awarisch');
INSERT INTO `country` (`id`, `name`) VALUES ('ay', 'Aymara');
INSERT INTO `country` (`id`, `name`) VALUES ('ban', 'Balinesisch');
INSERT INTO `country` (`id`, `name`) VALUES ('bat', 'Baltischi Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('bm', 'Bambara');
INSERT INTO `country` (`id`, `name`) VALUES ('bai', 'Bamileke');
INSERT INTO `country` (`id`, `name`) VALUES ('bad', 'Banda');
INSERT INTO `country` (`id`, `name`) VALUES ('bnt', 'Bantu');
INSERT INTO `country` (`id`, `name`) VALUES ('bas', 'Basaa');
INSERT INTO `country` (`id`, `name`) VALUES ('ba', 'Baschkirisch');
INSERT INTO `country` (`id`, `name`) VALUES ('eu', 'Baskisch');
INSERT INTO `country` (`id`, `name`) VALUES ('btk', 'Batak');
INSERT INTO `country` (`id`, `name`) VALUES ('bej', 'Bedauye');
INSERT INTO `country` (`id`, `name`) VALUES ('bal', 'Belutschisch');
INSERT INTO `country` (`id`, `name`) VALUES ('bem', 'Bemba');
INSERT INTO `country` (`id`, `name`) VALUES ('bn', 'Bengalisch');
INSERT INTO `country` (`id`, `name`) VALUES ('bho', 'Bhodschpuri');
INSERT INTO `country` (`id`, `name`) VALUES ('bh', 'Bihaarisch');
INSERT INTO `country` (`id`, `name`) VALUES ('bik', 'Bikolisch');
INSERT INTO `country` (`id`, `name`) VALUES ('bin', 'Bini');
INSERT INTO `country` (`id`, `name`) VALUES ('my', 'Birmanisch');
INSERT INTO `country` (`id`, `name`) VALUES ('bi', 'Bislama');
INSERT INTO `country` (`id`, `name`) VALUES ('bla', 'Blackfoot-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('byn', 'Blin');
INSERT INTO `country` (`id`, `name`) VALUES ('zbl', 'Bliss-Symbool');
INSERT INTO `country` (`id`, `name`) VALUES ('bs', 'Bosnisch');
INSERT INTO `country` (`id`, `name`) VALUES ('bra', 'Braj-Bhakha');
INSERT INTO `country` (`id`, `name`) VALUES ('pt_BR', 'Brasilianischs Portugiisisch');
INSERT INTO `country` (`id`, `name`) VALUES ('en_GB', 'Britischs Änglisch');
INSERT INTO `country` (`id`, `name`) VALUES ('br', 'Brötoonisch');
INSERT INTO `country` (`id`, `name`) VALUES ('bug', 'Bugineesisch');
INSERT INTO `country` (`id`, `name`) VALUES ('bg', 'Bulgaarisch');
INSERT INTO `country` (`id`, `name`) VALUES ('bua', 'Burjatisch');
INSERT INTO `country` (`id`, `name`) VALUES ('ber', 'Bärberisch');
INSERT INTO `country` (`id`, `name`) VALUES ('cad', 'Caddo');
INSERT INTO `country` (`id`, `name`) VALUES ('ceb', 'Cebuano');
INSERT INTO `country` (`id`, `name`) VALUES ('cmc', 'Chamischi Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('ch', 'Chamorro');
INSERT INTO `country` (`id`, `name`) VALUES ('chr', 'Cherokee');
INSERT INTO `country` (`id`, `name`) VALUES ('ny', 'Chewa-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('chy', 'Cheyenne');
INSERT INTO `country` (`id`, `name`) VALUES ('cu', 'Chileslawisch');
INSERT INTO `country` (`id`, `name`) VALUES ('zh', 'Chineesisch');
INSERT INTO `country` (`id`, `name`) VALUES ('chn', 'Chinook');
INSERT INTO `country` (`id`, `name`) VALUES ('chp', 'Chipewyan');
INSERT INTO `country` (`id`, `name`) VALUES ('cho', 'Choctaw');
INSERT INTO `country` (`id`, `name`) VALUES ('cr', 'Cree');
INSERT INTO `country` (`id`, `name`) VALUES ('del', 'Delaware-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('dz', 'Dschongkha');
INSERT INTO `country` (`id`, `name`) VALUES ('et', 'Eestnisch');
INSERT INTO `country` (`id`, `name`) VALUES ('efi', 'Efikisch');
INSERT INTO `country` (`id`, `name`) VALUES ('eka', 'Ekajuk');
INSERT INTO `country` (`id`, `name`) VALUES ('elx', 'Elamisch');
INSERT INTO `country` (`id`, `name`) VALUES ('tvl', 'Elliceanisch');
INSERT INTO `country` (`id`, `name`) VALUES ('myv', 'Erzya');
INSERT INTO `country` (`id`, `name`) VALUES ('eo', 'Eschperanto');
INSERT INTO `country` (`id`, `name`) VALUES ('ee', 'Ewe');
INSERT INTO `country` (`id`, `name`) VALUES ('ewo', 'Ewondo');
INSERT INTO `country` (`id`, `name`) VALUES ('fat', 'Fanti-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('fj', 'Fidschianisch');
INSERT INTO `country` (`id`, `name`) VALUES ('fil', 'Filipino');
INSERT INTO `country` (`id`, `name`) VALUES ('fi', 'Finnisch');
INSERT INTO `country` (`id`, `name`) VALUES ('fiu', 'Finno-ugrischi Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('nl_BE', 'Fläämisch');
INSERT INTO `country` (`id`, `name`) VALUES ('fon', 'Fon');
INSERT INTO `country` (`id`, `name`) VALUES ('fr', 'Französisch');
INSERT INTO `country` (`id`, `name`) VALUES ('cpf', 'Französisch-basierts Kreol oder Pidgin');
INSERT INTO `country` (`id`, `name`) VALUES ('fy', 'Friesisch');
INSERT INTO `country` (`id`, `name`) VALUES ('fur', 'Friulisch');
INSERT INTO `country` (`id`, `name`) VALUES ('ff', 'Ful');
INSERT INTO `country` (`id`, `name`) VALUES ('fo', 'Färöisch');
INSERT INTO `country` (`id`, `name`) VALUES ('gaa', 'Ga');
INSERT INTO `country` (`id`, `name`) VALUES ('gl', 'Galizisch');
INSERT INTO `country` (`id`, `name`) VALUES ('lg', 'Ganda-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('gay', 'Gayo');
INSERT INTO `country` (`id`, `name`) VALUES ('gba', 'Gbaya');
INSERT INTO `country` (`id`, `name`) VALUES ('sgn', 'Gebäärdeschpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('gez', 'Geez');
INSERT INTO `country` (`id`, `name`) VALUES ('ka', 'Georgisch');
INSERT INTO `country` (`id`, `name`) VALUES ('gem', 'Germanischi Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('gil', 'Gilbertesisch');
INSERT INTO `country` (`id`, `name`) VALUES ('gon', 'Gondi');
INSERT INTO `country` (`id`, `name`) VALUES ('got', 'Gotisch');
INSERT INTO `country` (`id`, `name`) VALUES ('grb', 'Grebo');
INSERT INTO `country` (`id`, `name`) VALUES ('el', 'Griechisch');
INSERT INTO `country` (`id`, `name`) VALUES ('kl', 'Gröönländisch');
INSERT INTO `country` (`id`, `name`) VALUES ('gn', 'Guarani');
INSERT INTO `country` (`id`, `name`) VALUES ('gu', 'Gujarati');
INSERT INTO `country` (`id`, `name`) VALUES ('hai', 'Haida');
INSERT INTO `country` (`id`, `name`) VALUES ('ht', 'Haitisch');
INSERT INTO `country` (`id`, `name`) VALUES ('ha', 'Haussa');
INSERT INTO `country` (`id`, `name`) VALUES ('haw', 'Hawaiianisch');
INSERT INTO `country` (`id`, `name`) VALUES ('he', 'Hebräisch');
INSERT INTO `country` (`id`, `name`) VALUES ('hz', 'Herero');
INSERT INTO `country` (`id`, `name`) VALUES ('hit', 'Hethitisch');
INSERT INTO `country` (`id`, `name`) VALUES ('hil', 'Hiligaynonisch');
INSERT INTO `country` (`id`, `name`) VALUES ('him', 'Himatschalisch');
INSERT INTO `country` (`id`, `name`) VALUES ('hi', 'Hindi');
INSERT INTO `country` (`id`, `name`) VALUES ('ho', 'Hiri-Motu');
INSERT INTO `country` (`id`, `name`) VALUES ('hup', 'Hupa');
INSERT INTO `country` (`id`, `name`) VALUES ('iba', 'Ibanisch');
INSERT INTO `country` (`id`, `name`) VALUES ('es_ES', 'Ibeerischs Schpanisch');
INSERT INTO `country` (`id`, `name`) VALUES ('pt_PT', 'Iberischs Portugiisisch');
INSERT INTO `country` (`id`, `name`) VALUES ('io', 'Ido');
INSERT INTO `country` (`id`, `name`) VALUES ('ig', 'Igbo');
INSERT INTO `country` (`id`, `name`) VALUES ('ga', 'Iirisch');
INSERT INTO `country` (`id`, `name`) VALUES ('is', 'Iisländisch');
INSERT INTO `country` (`id`, `name`) VALUES ('ijo', 'Ijo');
INSERT INTO `country` (`id`, `name`) VALUES ('ilo', 'Ilokano');
INSERT INTO `country` (`id`, `name`) VALUES ('smn', 'Inari-Samisch');
INSERT INTO `country` (`id`, `name`) VALUES ('inc', 'Indoarischi Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('ine', 'Indogermanischi Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('id', 'Indonesisch');
INSERT INTO `country` (`id`, `name`) VALUES ('inh', 'Inguschisch');
INSERT INTO `country` (`id`, `name`) VALUES ('ia', 'Interlingua');
INSERT INTO `country` (`id`, `name`) VALUES ('ie', 'Interlingue');
INSERT INTO `country` (`id`, `name`) VALUES ('iu', 'Inukitut');
INSERT INTO `country` (`id`, `name`) VALUES ('ik', 'Inupiak');
INSERT INTO `country` (`id`, `name`) VALUES ('ira', 'Iranischi Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('iro', 'Irokesischi Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('it', 'Italiänisch');
INSERT INTO `country` (`id`, `name`) VALUES ('sah', 'Jakutisch');
INSERT INTO `country` (`id`, `name`) VALUES ('ja', 'Japanisch');
INSERT INTO `country` (`id`, `name`) VALUES ('jv', 'Javanisch');
INSERT INTO `country` (`id`, `name`) VALUES ('yi', 'Jiddisch');
INSERT INTO `country` (`id`, `name`) VALUES ('kaj', 'Jju');
INSERT INTO `country` (`id`, `name`) VALUES ('jrb', 'Jüüdisch-Arabisch');
INSERT INTO `country` (`id`, `name`) VALUES ('jpr', 'Jüüdisch-Persisch');
INSERT INTO `country` (`id`, `name`) VALUES ('kbd', 'Kabardinisch');
INSERT INTO `country` (`id`, `name`) VALUES ('kab', 'Kabylisch');
INSERT INTO `country` (`id`, `name`) VALUES ('kac', 'Kachin-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('xal', 'Kalmückisch');
INSERT INTO `country` (`id`, `name`) VALUES ('kam', 'Kamba');
INSERT INTO `country` (`id`, `name`) VALUES ('km', 'Kambodschanisch');
INSERT INTO `country` (`id`, `name`) VALUES ('fr_CA', 'Kanadischs Französisch');
INSERT INTO `country` (`id`, `name`) VALUES ('en_CA', 'Kanadischs Änglisch');
INSERT INTO `country` (`id`, `name`) VALUES ('kn', 'Kannada');
INSERT INTO `country` (`id`, `name`) VALUES ('kr', 'Kanuri-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('kaa', 'Karakalpakisch');
INSERT INTO `country` (`id`, `name`) VALUES ('krc', 'Karatschaiisch-Balkarisch');
INSERT INTO `country` (`id`, `name`) VALUES ('krl', 'Karelisch');
INSERT INTO `country` (`id`, `name`) VALUES ('kar', 'Karenisch');
INSERT INTO `country` (`id`, `name`) VALUES ('car', 'Kariibisch');
INSERT INTO `country` (`id`, `name`) VALUES ('kk', 'Kasachisch');
INSERT INTO `country` (`id`, `name`) VALUES ('ks', 'Kaschmirisch');
INSERT INTO `country` (`id`, `name`) VALUES ('csb', 'Kaschubisch');
INSERT INTO `country` (`id`, `name`) VALUES ('ca', 'Katalaanisch');
INSERT INTO `country` (`id`, `name`) VALUES ('cau', 'Kaukaasisch');
INSERT INTO `country` (`id`, `name`) VALUES ('kaw', 'Kawi');
INSERT INTO `country` (`id`, `name`) VALUES ('cel', 'Keltischi Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('kha', 'Khasisch');
INSERT INTO `country` (`id`, `name`) VALUES ('khi', 'Khoisanisch');
INSERT INTO `country` (`id`, `name`) VALUES ('mag', 'Khotta');
INSERT INTO `country` (`id`, `name`) VALUES ('ki', 'Kikuyu-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('kmb', 'Kimbundu-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('ky', 'Kirgiisisch');
INSERT INTO `country` (`id`, `name`) VALUES ('tlh', 'Klingonisch');
INSERT INTO `country` (`id`, `name`) VALUES ('kv', 'Komi-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('kg', 'Kongolesisch');
INSERT INTO `country` (`id`, `name`) VALUES ('kok', 'Konkani');
INSERT INTO `country` (`id`, `name`) VALUES ('cop', 'Koptisch');
INSERT INTO `country` (`id`, `name`) VALUES ('ko', 'Koreaanisch');
INSERT INTO `country` (`id`, `name`) VALUES ('kw', 'Kornisch');
INSERT INTO `country` (`id`, `name`) VALUES ('kfo', 'Koro');
INSERT INTO `country` (`id`, `name`) VALUES ('co', 'Korsisch');
INSERT INTO `country` (`id`, `name`) VALUES ('kos', 'Kosraeanisch');
INSERT INTO `country` (`id`, `name`) VALUES ('kpe', 'Kpelle-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('crp', 'Kreol oder Pidgin');
INSERT INTO `country` (`id`, `name`) VALUES ('crh', 'Krimtatarisch');
INSERT INTO `country` (`id`, `name`) VALUES ('hr', 'Kroazisch');
INSERT INTO `country` (`id`, `name`) VALUES ('kro', 'Kru-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('kum', 'Kumükisch');
INSERT INTO `country` (`id`, `name`) VALUES ('ku', 'Kurdisch');
INSERT INTO `country` (`id`, `name`) VALUES ('cus', 'Kuschitischi Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('gwi', 'Kutchinisch');
INSERT INTO `country` (`id`, `name`) VALUES ('kut', 'Kutenai-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('kj', 'Kwanyama');
INSERT INTO `country` (`id`, `name`) VALUES ('zxx', 'Kän schpraachliche Inhalt');
INSERT INTO `country` (`id`, `name`) VALUES ('art', 'Künschtlichi Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('lad', 'Ladino');
INSERT INTO `country` (`id`, `name`) VALUES ('lah', 'Lahndanisch');
INSERT INTO `country` (`id`, `name`) VALUES ('lam', 'Lambanisch');
INSERT INTO `country` (`id`, `name`) VALUES ('lo', 'Laozisch');
INSERT INTO `country` (`id`, `name`) VALUES ('la', 'Latiin');
INSERT INTO `country` (`id`, `name`) VALUES ('es_419', 'Latiinamerikanischs Schpanisch');
INSERT INTO `country` (`id`, `name`) VALUES ('lez', 'Lesgisch');
INSERT INTO `country` (`id`, `name`) VALUES ('lv', 'Lettisch');
INSERT INTO `country` (`id`, `name`) VALUES ('li', 'Limburgisch');
INSERT INTO `country` (`id`, `name`) VALUES ('ln', 'Lingala');
INSERT INTO `country` (`id`, `name`) VALUES ('lt', 'Litauisch');
INSERT INTO `country` (`id`, `name`) VALUES ('jbo', 'Lojbanisch');
INSERT INTO `country` (`id`, `name`) VALUES ('lu', 'Luba');
INSERT INTO `country` (`id`, `name`) VALUES ('lua', 'Luba-Lulua');
INSERT INTO `country` (`id`, `name`) VALUES ('lui', 'Luiseno-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('smj', 'Lule-Samisch');
INSERT INTO `country` (`id`, `name`) VALUES ('lun', 'Lunda-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('luo', 'Luo-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('lus', 'Lushai-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('lb', 'Luxemburgisch');
INSERT INTO `country` (`id`, `name`) VALUES ('mg', 'Madagassisch');
INSERT INTO `country` (`id`, `name`) VALUES ('mad', 'Maduresisch');
INSERT INTO `country` (`id`, `name`) VALUES ('mai', 'Maithili');
INSERT INTO `country` (`id`, `name`) VALUES ('mak', 'Makassarisch');
INSERT INTO `country` (`id`, `name`) VALUES ('ms', 'Malaiisch');
INSERT INTO `country` (`id`, `name`) VALUES ('ml', 'Malayalam');
INSERT INTO `country` (`id`, `name`) VALUES ('dv', 'Malediivisch');
INSERT INTO `country` (`id`, `name`) VALUES ('mt', 'Maltesisch');
INSERT INTO `country` (`id`, `name`) VALUES ('mdr', 'Mandaresisch');
INSERT INTO `country` (`id`, `name`) VALUES ('man', 'Manding-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('mnc', 'Mandschurisch');
INSERT INTO `country` (`id`, `name`) VALUES ('mno', 'Manobo-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('gv', 'Manx-Gäälisch');
INSERT INTO `country` (`id`, `name`) VALUES ('mi', 'Maori');
INSERT INTO `country` (`id`, `name`) VALUES ('mr', 'Marathi');
INSERT INTO `country` (`id`, `name`) VALUES ('mh', 'Marschallesisch');
INSERT INTO `country` (`id`, `name`) VALUES ('mwr', 'Marwarisch');
INSERT INTO `country` (`id`, `name`) VALUES ('mas', 'Massai-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('myn', 'Maya-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('mk', 'Mazedonisch');
INSERT INTO `country` (`id`, `name`) VALUES ('umb', 'Mbundu-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('mul', 'Mehrschpraachig');
INSERT INTO `country` (`id`, `name`) VALUES ('mni', 'Meithei-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('men', 'Mende-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('hmn', 'Miao');
INSERT INTO `country` (`id`, `name`) VALUES ('mic', 'Micmac-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('min', 'Minangkabau-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('mwl', 'Mirandesisch');
INSERT INTO `country` (`id`, `name`) VALUES ('frm', 'Mittelfranzösisch');
INSERT INTO `country` (`id`, `name`) VALUES ('gmh', 'Mittelhochtüütsch');
INSERT INTO `country` (`id`, `name`) VALUES ('mga', 'Mittelirisch');
INSERT INTO `country` (`id`, `name`) VALUES ('dum', 'Mittelniderländisch');
INSERT INTO `country` (`id`, `name`) VALUES ('pal', 'Mittelpersisch');
INSERT INTO `country` (`id`, `name`) VALUES ('enm', 'Mittelänglisch');
INSERT INTO `country` (`id`, `name`) VALUES ('moh', 'Mohawk-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('mdf', 'Mokschamordwinisch');
INSERT INTO `country` (`id`, `name`) VALUES ('mo', 'Moldawisch');
INSERT INTO `country` (`id`, `name`) VALUES ('mkh', 'Mon-Khmer-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('lol', 'Mongo');
INSERT INTO `country` (`id`, `name`) VALUES ('mn', 'Mongolisch');
INSERT INTO `country` (`id`, `name`) VALUES ('gor', 'Mongondou');
INSERT INTO `country` (`id`, `name`) VALUES ('mos', 'Mossi-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('mun', 'Munda-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('mus', 'Muskogee-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('nah', 'Nahuatl');
INSERT INTO `country` (`id`, `name`) VALUES ('na', 'Nauruisch');
INSERT INTO `country` (`id`, `name`) VALUES ('nv', 'Navajo-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('ng', 'Ndonga');
INSERT INTO `country` (`id`, `name`) VALUES ('nap', 'Neapolitanisch');
INSERT INTO `country` (`id`, `name`) VALUES ('ne', 'Nepalesisch');
INSERT INTO `country` (`id`, `name`) VALUES ('tpi', 'Neumelanesisch');
INSERT INTO `country` (`id`, `name`) VALUES ('new', 'Newarisch');
INSERT INTO `country` (`id`, `name`) VALUES ('nia', 'Nias-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('nl', 'Niderländisch');
INSERT INTO `country` (`id`, `name`) VALUES ('dsb', 'Nidersorbisch');
INSERT INTO `country` (`id`, `name`) VALUES ('nds', 'Nidertüütsch');
INSERT INTO `country` (`id`, `name`) VALUES ('nic', 'Nigerkordofanischi Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('ssa', 'Nilosaharanischi Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('niu', 'Niue-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('nog', 'Nogaisch');
INSERT INTO `country` (`id`, `name`) VALUES ('nd', 'Nord-Ndebele-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('se', 'Nord-Samisch');
INSERT INTO `country` (`id`, `name`) VALUES ('nso', 'Nord-Sotho-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('nai', 'Nordamerikanischi Indianersprach');
INSERT INTO `country` (`id`, `name`) VALUES ('frr', 'Nordfriesisch');
INSERT INTO `country` (`id`, `name`) VALUES ('no', 'Norwegisch');
INSERT INTO `country` (`id`, `name`) VALUES ('nb', 'Norwegisch Bokmål');
INSERT INTO `country` (`id`, `name`) VALUES ('nn', 'Norwegisch Nynorsk');
INSERT INTO `country` (`id`, `name`) VALUES ('nub', 'Nubischi Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('nym', 'Nyamwezi-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('nyn', 'Nyankole');
INSERT INTO `country` (`id`, `name`) VALUES ('nyo', 'Nyoro');
INSERT INTO `country` (`id`, `name`) VALUES ('nzi', 'Nzima');
INSERT INTO `country` (`id`, `name`) VALUES ('nqo', 'N’Ko');
INSERT INTO `country` (`id`, `name`) VALUES ('hsb', 'Obersorbisch');
INSERT INTO `country` (`id`, `name`) VALUES ('oj', 'Ojibwa-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('oc', 'Okzitanisch');
INSERT INTO `country` (`id`, `name`) VALUES ('kru', 'Oraon-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('or', 'Orija');
INSERT INTO `country` (`id`, `name`) VALUES ('om', 'Oromo');
INSERT INTO `country` (`id`, `name`) VALUES ('osa', 'Osage-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('rap', 'Oschterinsel-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('frs', 'Oschtfriesisch');
INSERT INTO `country` (`id`, `name`) VALUES ('ota', 'Osmanisch');
INSERT INTO `country` (`id`, `name`) VALUES ('os', 'Ossezisch');
INSERT INTO `country` (`id`, `name`) VALUES ('oto', 'Otomangue-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('pau', 'Palau');
INSERT INTO `country` (`id`, `name`) VALUES ('pi', 'Pali');
INSERT INTO `country` (`id`, `name`) VALUES ('pam', 'Pampanggan-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('pa', 'Pandschabisch');
INSERT INTO `country` (`id`, `name`) VALUES ('pag', 'Pangasinanisch');
INSERT INTO `country` (`id`, `name`) VALUES ('fan', 'Pangwe-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('pap', 'Papiamento');
INSERT INTO `country` (`id`, `name`) VALUES ('paa', 'Papua-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('ps', 'Paschtu');
INSERT INTO `country` (`id`, `name`) VALUES ('fa', 'Persisch');
INSERT INTO `country` (`id`, `name`) VALUES ('phi', 'Philippine-Austronesischi Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('phn', 'Phönikisch');
INSERT INTO `country` (`id`, `name`) VALUES ('pl', 'Polnisch');
INSERT INTO `country` (`id`, `name`) VALUES ('pon', 'Ponapeanisch');
INSERT INTO `country` (`id`, `name`) VALUES ('cpp', 'Portugiesisch-basierts Kreol oder Pidgin');
INSERT INTO `country` (`id`, `name`) VALUES ('pt', 'Portugiisisch');
INSERT INTO `country` (`id`, `name`) VALUES ('pra', 'Prakrit');
INSERT INTO `country` (`id`, `name`) VALUES ('qu', 'Quechua');
INSERT INTO `country` (`id`, `name`) VALUES ('raj', 'Rajasthani');
INSERT INTO `country` (`id`, `name`) VALUES ('rar', 'Rarotonganisch');
INSERT INTO `country` (`id`, `name`) VALUES ('roa', 'Romanischi Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('root', 'Root');
INSERT INTO `country` (`id`, `name`) VALUES ('loz', 'Rotse-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('rw', 'Ruandisch');
INSERT INTO `country` (`id`, `name`) VALUES ('ro', 'Rumänisch');
INSERT INTO `country` (`id`, `name`) VALUES ('rn', 'Rundi-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('ru', 'Russisch');
INSERT INTO `country` (`id`, `name`) VALUES ('rm', 'Rätoromanisch');
INSERT INTO `country` (`id`, `name`) VALUES ('kho', 'Sakisch');
INSERT INTO `country` (`id`, `name`) VALUES ('sal', 'Salish-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('sam', 'Samaritanisch');
INSERT INTO `country` (`id`, `name`) VALUES ('smi', 'Samisch');
INSERT INTO `country` (`id`, `name`) VALUES ('sm', 'Samoanisch');
INSERT INTO `country` (`id`, `name`) VALUES ('sad', 'Sandawe-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('sg', 'Sango');
INSERT INTO `country` (`id`, `name`) VALUES ('sa', 'Sanschkrit');
INSERT INTO `country` (`id`, `name`) VALUES ('sat', 'Santali');
INSERT INTO `country` (`id`, `name`) VALUES ('sc', 'Sardisch');
INSERT INTO `country` (`id`, `name`) VALUES ('sas', 'Sasak');
INSERT INTO `country` (`id`, `name`) VALUES ('shn', 'Schan-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('sn', 'Schhona');
INSERT INTO `country` (`id`, `name`) VALUES ('sco', 'Schottisch');
INSERT INTO `country` (`id`, `name`) VALUES ('gd', 'Schottisch-Gäälisch');
INSERT INTO `country` (`id`, `name`) VALUES ('es', 'Schpanisch');
INSERT INTO `country` (`id`, `name`) VALUES ('sv', 'Schwedisch');
INSERT INTO `country` (`id`, `name`) VALUES ('fr_CH', 'Schwiizer Französisch');
INSERT INTO `country` (`id`, `name`) VALUES ('de_CH', 'Schwiizer Hochtüütsch');
INSERT INTO `country` (`id`, `name`) VALUES ('gsw', 'Schwiizertüütsch');
INSERT INTO `country` (`id`, `name`) VALUES ('sel', 'Selkupisch');
INSERT INTO `country` (`id`, `name`) VALUES ('sem', 'Semitischi Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('sr', 'Serbisch');
INSERT INTO `country` (`id`, `name`) VALUES ('sh', 'Serbo-Kroatisch');
INSERT INTO `country` (`id`, `name`) VALUES ('srr', 'Serer-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('ii', 'Sezuanischs Yi');
INSERT INTO `country` (`id`, `name`) VALUES ('sid', 'Sidamo');
INSERT INTO `country` (`id`, `name`) VALUES ('sd', 'Sindhi');
INSERT INTO `country` (`id`, `name`) VALUES ('si', 'Singhalesisch');
INSERT INTO `country` (`id`, `name`) VALUES ('sit', 'Sinotibetischi Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('sio', 'Sioux-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('scn', 'Sizilianisch');
INSERT INTO `country` (`id`, `name`) VALUES ('sms', 'Skolt-Samisch');
INSERT INTO `country` (`id`, `name`) VALUES ('den', 'Slavey');
INSERT INTO `country` (`id`, `name`) VALUES ('sla', 'Slawischi Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('sk', 'Slowakisch');
INSERT INTO `country` (`id`, `name`) VALUES ('sl', 'Slowenisch');
INSERT INTO `country` (`id`, `name`) VALUES ('sog', 'Sogdisch');
INSERT INTO `country` (`id`, `name`) VALUES ('so', 'Somali');
INSERT INTO `country` (`id`, `name`) VALUES ('son', 'Songhai-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('snk', 'Soninke-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('wen', 'Sorbisch');
INSERT INTO `country` (`id`, `name`) VALUES ('srn', 'Srananisch');
INSERT INTO `country` (`id`, `name`) VALUES ('sw', 'Suaheli');
INSERT INTO `country` (`id`, `name`) VALUES ('suk', 'Sukuma-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('sux', 'Sumerisch');
INSERT INTO `country` (`id`, `name`) VALUES ('su', 'Sundanesisch');
INSERT INTO `country` (`id`, `name`) VALUES ('sus', 'Susu');
INSERT INTO `country` (`id`, `name`) VALUES ('ss', 'Swazi');
INSERT INTO `country` (`id`, `name`) VALUES ('syr', 'Syrisch');
INSERT INTO `country` (`id`, `name`) VALUES ('alt', 'Süüd-Altaisch');
INSERT INTO `country` (`id`, `name`) VALUES ('nr', 'Süüd-Ndebele-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('sma', 'Süüd-Samisch');
INSERT INTO `country` (`id`, `name`) VALUES ('st', 'Süüd-Sotho-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('sai', 'Süüdamerikanischi Indianerschpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('tg', 'Tadschikisch');
INSERT INTO `country` (`id`, `name`) VALUES ('tl', 'Tagalog');
INSERT INTO `country` (`id`, `name`) VALUES ('ty', 'Tahitisch');
INSERT INTO `country` (`id`, `name`) VALUES ('day', 'Tajakisch');
INSERT INTO `country` (`id`, `name`) VALUES ('dak', 'Takota');
INSERT INTO `country` (`id`, `name`) VALUES ('tmh', 'Tamaseq');
INSERT INTO `country` (`id`, `name`) VALUES ('ta', 'Tamilisch');
INSERT INTO `country` (`id`, `name`) VALUES ('dar', 'Targiinisch');
INSERT INTO `country` (`id`, `name`) VALUES ('tt', 'Tatarisch');
INSERT INTO `country` (`id`, `name`) VALUES ('te', 'Telugu');
INSERT INTO `country` (`id`, `name`) VALUES ('tem', 'Temne');
INSERT INTO `country` (`id`, `name`) VALUES ('ter', 'Tereno-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('tet', 'Tetum-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('th', 'Thailändisch');
INSERT INTO `country` (`id`, `name`) VALUES ('tai', 'Thaischpraache');
INSERT INTO `country` (`id`, `name`) VALUES ('bo', 'Tibeetisch');
INSERT INTO `country` (`id`, `name`) VALUES ('tig', 'Tigre');
INSERT INTO `country` (`id`, `name`) VALUES ('ti', 'Tigrinja');
INSERT INTO `country` (`id`, `name`) VALUES ('din', 'Tinka');
INSERT INTO `country` (`id`, `name`) VALUES ('dyu', 'Tiula');
INSERT INTO `country` (`id`, `name`) VALUES ('tiv', 'Tiv-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('tli', 'Tlingit-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('doi', 'Togri');
INSERT INTO `country` (`id`, `name`) VALUES ('dgr', 'Togrib');
INSERT INTO `country` (`id`, `name`) VALUES ('tkl', 'Tokelauanisch');
INSERT INTO `country` (`id`, `name`) VALUES ('to', 'Tongaisch');
INSERT INTO `country` (`id`, `name`) VALUES ('zh_Hant', 'Tradizionells Chineesisch');
INSERT INTO `country` (`id`, `name`) VALUES ('dra', 'Trawidischi Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('chk', 'Trukesisch');
INSERT INTO `country` (`id`, `name`) VALUES ('chg', 'Tschagataisch');
INSERT INTO `country` (`id`, `name`) VALUES ('cs', 'Tschechisch');
INSERT INTO `country` (`id`, `name`) VALUES ('chm', 'Tscheremissisch');
INSERT INTO `country` (`id`, `name`) VALUES ('ce', 'Tschetscheenisch');
INSERT INTO `country` (`id`, `name`) VALUES ('chb', 'Tschibtscha');
INSERT INTO `country` (`id`, `name`) VALUES ('cv', 'Tschuwaschisch');
INSERT INTO `country` (`id`, `name`) VALUES ('tsi', 'Tsimshian-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('ts', 'Tsonga');
INSERT INTO `country` (`id`, `name`) VALUES ('tog', 'Tsonga-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('tn', 'Tswana-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('dua', 'Tuala');
INSERT INTO `country` (`id`, `name`) VALUES ('tum', 'Tumbuka-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('tup', 'Tupi-Schpraache');
INSERT INTO `country` (`id`, `name`) VALUES ('tk', 'Turkmenisch');
INSERT INTO `country` (`id`, `name`) VALUES ('tyv', 'Tuwinisch');
INSERT INTO `country` (`id`, `name`) VALUES ('tw', 'Twi');
INSERT INTO `country` (`id`, `name`) VALUES ('kcg', 'Tyap');
INSERT INTO `country` (`id`, `name`) VALUES ('da', 'Tänisch');
INSERT INTO `country` (`id`, `name`) VALUES ('tr', 'Türkisch');
INSERT INTO `country` (`id`, `name`) VALUES ('de', 'Tüütsch');
INSERT INTO `country` (`id`, `name`) VALUES ('udm', 'Udmurtisch');
INSERT INTO `country` (`id`, `name`) VALUES ('uga', 'Ugaritisch');
INSERT INTO `country` (`id`, `name`) VALUES ('ug', 'Uigurisch');
INSERT INTO `country` (`id`, `name`) VALUES ('uk', 'Ukrainisch');
INSERT INTO `country` (`id`, `name`) VALUES ('und', 'Unbeschtimmti Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('hu', 'Ungarisch');
INSERT INTO `country` (`id`, `name`) VALUES ('ur', 'Urdu');
INSERT INTO `country` (`id`, `name`) VALUES ('uz', 'Usbekisch');
INSERT INTO `country` (`id`, `name`) VALUES ('vai', 'Vai-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('ve', 'Venda-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('zh_Hans', 'Veräifachts Chineesisch');
INSERT INTO `country` (`id`, `name`) VALUES ('vi', 'Vietnamesisch');
INSERT INTO `country` (`id`, `name`) VALUES ('vo', 'Volapük');
INSERT INTO `country` (`id`, `name`) VALUES ('wak', 'Wakashanisch');
INSERT INTO `country` (`id`, `name`) VALUES ('wal', 'Walamo-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('cy', 'Walisisch');
INSERT INTO `country` (`id`, `name`) VALUES ('wa', 'Wallonisch');
INSERT INTO `country` (`id`, `name`) VALUES ('war', 'Waray');
INSERT INTO `country` (`id`, `name`) VALUES ('was', 'Washo-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('be', 'Wiissrussisch');
INSERT INTO `country` (`id`, `name`) VALUES ('wo', 'Wolof');
INSERT INTO `country` (`id`, `name`) VALUES ('vot', 'Wotisch');
INSERT INTO `country` (`id`, `name`) VALUES ('xh', 'Xhosa');
INSERT INTO `country` (`id`, `name`) VALUES ('yao', 'Yao-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('yap', 'Yapesisch');
INSERT INTO `country` (`id`, `name`) VALUES ('yo', 'Yoruba');
INSERT INTO `country` (`id`, `name`) VALUES ('ypk', 'Yupik-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('znd', 'Zande-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('zap', 'Zapotekisch');
INSERT INTO `country` (`id`, `name`) VALUES ('zza', 'Zaza');
INSERT INTO `country` (`id`, `name`) VALUES ('zen', 'Zenaga');
INSERT INTO `country` (`id`, `name`) VALUES ('cai', 'Zentralamerikanischi Indianerschpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('za', 'Zhuang');
INSERT INTO `country` (`id`, `name`) VALUES ('rom', 'Zigüünerschpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('zu', 'Zulu');
INSERT INTO `country` (`id`, `name`) VALUES ('zun', 'Zuni-Schpraach');
INSERT INTO `country` (`id`, `name`) VALUES ('en', 'Änglisch');
INSERT INTO `country` (`id`, `name`) VALUES ('cpe', 'Änglisch-basierts Kreol oder Pidgin');
INSERT INTO `country` (`id`, `name`) VALUES ('de_AT', 'Öschtriichischs Tüütsch');
