CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('kv', 'Коми');
INSERT INTO "country" ("id", "name") VALUES ('ab', 'абхазски');
INSERT INTO "country" ("id", "name") VALUES ('awa', 'авади');
INSERT INTO "country" ("id", "name") VALUES ('av', 'аварски');
INSERT INTO "country" ("id", "name") VALUES ('ae', 'авестски');
INSERT INTO "country" ("id", "name") VALUES ('en_AU', 'австралийски английски');
INSERT INTO "country" ("id", "name") VALUES ('aus', 'австралийски езици');
INSERT INTO "country" ("id", "name") VALUES ('de_AT', 'австрийски немски');
INSERT INTO "country" ("id", "name") VALUES ('map', 'австронезийски');
INSERT INTO "country" ("id", "name") VALUES ('ada', 'адангме');
INSERT INTO "country" ("id", "name") VALUES ('ady', 'адиге');
INSERT INTO "country" ("id", "name") VALUES ('az', 'азърбайджански');
INSERT INTO "country" ("id", "name") VALUES ('ay', 'аймара');
INSERT INTO "country" ("id", "name") VALUES ('ain', 'айну');
INSERT INTO "country" ("id", "name") VALUES ('akk', 'акадски');
INSERT INTO "country" ("id", "name") VALUES ('ak', 'акан');
INSERT INTO "country" ("id", "name") VALUES ('ach', 'аколи');
INSERT INTO "country" ("id", "name") VALUES ('sq', 'албански');
INSERT INTO "country" ("id", "name") VALUES ('alg', 'алгонквин');
INSERT INTO "country" ("id", "name") VALUES ('ale', 'алеутски');
INSERT INTO "country" ("id", "name") VALUES ('tut', 'алтайски');
INSERT INTO "country" ("id", "name") VALUES ('en_US', 'американски английски');
INSERT INTO "country" ("id", "name") VALUES ('am', 'амхарски');
INSERT INTO "country" ("id", "name") VALUES ('anp', 'ангика');
INSERT INTO "country" ("id", "name") VALUES ('en', 'английски');
INSERT INTO "country" ("id", "name") VALUES ('ar', 'арабски');
INSERT INTO "country" ("id", "name") VALUES ('arw', 'аравак');
INSERT INTO "country" ("id", "name") VALUES ('an', 'арагонски');
INSERT INTO "country" ("id", "name") VALUES ('arc', 'арамейски');
INSERT INTO "country" ("id", "name") VALUES ('arp', 'арапахо');
INSERT INTO "country" ("id", "name") VALUES ('hy', 'арменски');
INSERT INTO "country" ("id", "name") VALUES ('rup', 'арумънски');
INSERT INTO "country" ("id", "name") VALUES ('as', 'асамски');
INSERT INTO "country" ("id", "name") VALUES ('ast', 'астурски');
INSERT INTO "country" ("id", "name") VALUES ('ath', 'атабаски езици');
INSERT INTO "country" ("id", "name") VALUES ('cch', 'атсам');
INSERT INTO "country" ("id", "name") VALUES ('aa', 'афар');
INSERT INTO "country" ("id", "name") VALUES ('af', 'африканс');
INSERT INTO "country" ("id", "name") VALUES ('afh', 'африхили');
INSERT INTO "country" ("id", "name") VALUES ('afa', 'афро-азиатски');
INSERT INTO "country" ("id", "name") VALUES ('ace', 'ачински');
INSERT INTO "country" ("id", "name") VALUES ('ban', 'балинейски');
INSERT INTO "country" ("id", "name") VALUES ('bat', 'балтийски');
INSERT INTO "country" ("id", "name") VALUES ('bal', 'балучи');
INSERT INTO "country" ("id", "name") VALUES ('bm', 'бамбара');
INSERT INTO "country" ("id", "name") VALUES ('bai', 'бамикеле');
INSERT INTO "country" ("id", "name") VALUES ('bad', 'банда');
INSERT INTO "country" ("id", "name") VALUES ('bnt', 'банту');
INSERT INTO "country" ("id", "name") VALUES ('bas', 'баса');
INSERT INTO "country" ("id", "name") VALUES ('eu', 'баски');
INSERT INTO "country" ("id", "name") VALUES ('btk', 'батак');
INSERT INTO "country" ("id", "name") VALUES ('ba', 'башкирски');
INSERT INTO "country" ("id", "name") VALUES ('zxx', 'без лингвистично съдържание');
INSERT INTO "country" ("id", "name") VALUES ('be', 'беларуски');
INSERT INTO "country" ("id", "name") VALUES ('bem', 'бемба');
INSERT INTO "country" ("id", "name") VALUES ('bn', 'бенгалски');
INSERT INTO "country" ("id", "name") VALUES ('ber', 'берберски');
INSERT INTO "country" ("id", "name") VALUES ('bej', 'бея');
INSERT INTO "country" ("id", "name") VALUES ('bik', 'биколски');
INSERT INTO "country" ("id", "name") VALUES ('byn', 'биленски');
INSERT INTO "country" ("id", "name") VALUES ('bin', 'бини');
INSERT INTO "country" ("id", "name") VALUES ('my', 'бирмански');
INSERT INTO "country" ("id", "name") VALUES ('bi', 'бислама');
INSERT INTO "country" ("id", "name") VALUES ('bh', 'бихари');
INSERT INTO "country" ("id", "name") VALUES ('zbl', 'блис символи');
INSERT INTO "country" ("id", "name") VALUES ('bho', 'божпури');
INSERT INTO "country" ("id", "name") VALUES ('bs', 'босненски');
INSERT INTO "country" ("id", "name") VALUES ('bra', 'брадж');
INSERT INTO "country" ("id", "name") VALUES ('br', 'бретонски');
INSERT INTO "country" ("id", "name") VALUES ('en_GB', 'британски английски');
INSERT INTO "country" ("id", "name") VALUES ('bug', 'бугински');
INSERT INTO "country" ("id", "name") VALUES ('bua', 'бурятски');
INSERT INTO "country" ("id", "name") VALUES ('bg', 'български');
INSERT INTO "country" ("id", "name") VALUES ('vai', 'ваи');
INSERT INTO "country" ("id", "name") VALUES ('wak', 'вакашански език');
INSERT INTO "country" ("id", "name") VALUES ('wal', 'валамо');
INSERT INTO "country" ("id", "name") VALUES ('wa', 'валонски');
INSERT INTO "country" ("id", "name") VALUES ('war', 'варай');
INSERT INTO "country" ("id", "name") VALUES ('ve', 'венда');
INSERT INTO "country" ("id", "name") VALUES ('vi', 'виетнамски');
INSERT INTO "country" ("id", "name") VALUES ('vo', 'волапюк');
INSERT INTO "country" ("id", "name") VALUES ('wo', 'волоф');
INSERT INTO "country" ("id", "name") VALUES ('vot', 'вотик');
INSERT INTO "country" ("id", "name") VALUES ('gaa', 'га');
INSERT INTO "country" ("id", "name") VALUES ('gay', 'гайо');
INSERT INTO "country" ("id", "name") VALUES ('gl', 'галисийски');
INSERT INTO "country" ("id", "name") VALUES ('lg', 'ганда');
INSERT INTO "country" ("id", "name") VALUES ('gba', 'гбая');
INSERT INTO "country" ("id", "name") VALUES ('gwi', 'гвичин');
INSERT INTO "country" ("id", "name") VALUES ('gem', 'германски');
INSERT INTO "country" ("id", "name") VALUES ('gez', 'гииз');
INSERT INTO "country" ("id", "name") VALUES ('gil', 'гилбертски');
INSERT INTO "country" ("id", "name") VALUES ('gon', 'гонди');
INSERT INTO "country" ("id", "name") VALUES ('hsb', 'горносербски');
INSERT INTO "country" ("id", "name") VALUES ('gor', 'горонтало');
INSERT INTO "country" ("id", "name") VALUES ('got', 'готически');
INSERT INTO "country" ("id", "name") VALUES ('grb', 'гребо');
INSERT INTO "country" ("id", "name") VALUES ('kl', 'гренландски ескимоски');
INSERT INTO "country" ("id", "name") VALUES ('ka', 'грузински');
INSERT INTO "country" ("id", "name") VALUES ('el', 'гръцки');
INSERT INTO "country" ("id", "name") VALUES ('gn', 'гуарани');
INSERT INTO "country" ("id", "name") VALUES ('gu', 'гуджарати');
INSERT INTO "country" ("id", "name") VALUES ('dak', 'дакотски');
INSERT INTO "country" ("id", "name") VALUES ('dar', 'даргва');
INSERT INTO "country" ("id", "name") VALUES ('da', 'датски');
INSERT INTO "country" ("id", "name") VALUES ('day', 'даякски');
INSERT INTO "country" ("id", "name") VALUES ('del', 'делауер');
INSERT INTO "country" ("id", "name") VALUES ('dz', 'дзонха');
INSERT INTO "country" ("id", "name") VALUES ('dv', 'дивехи');
INSERT INTO "country" ("id", "name") VALUES ('din', 'динка');
INSERT INTO "country" ("id", "name") VALUES ('dyu', 'диула');
INSERT INTO "country" ("id", "name") VALUES ('doi', 'догри');
INSERT INTO "country" ("id", "name") VALUES ('dgr', 'догриб');
INSERT INTO "country" ("id", "name") VALUES ('nds', 'долносаксонски');
INSERT INTO "country" ("id", "name") VALUES ('dsb', 'долносербски');
INSERT INTO "country" ("id", "name") VALUES ('dra', 'дравидски езици');
INSERT INTO "country" ("id", "name") VALUES ('grc', 'древногръцки');
INSERT INTO "country" ("id", "name") VALUES ('mis', 'други езици');
INSERT INTO "country" ("id", "name") VALUES ('dua', 'дуала');
INSERT INTO "country" ("id", "name") VALUES ('ewo', 'евондо');
INSERT INTO "country" ("id", "name") VALUES ('jrb', 'еврейско-арабски');
INSERT INTO "country" ("id", "name") VALUES ('jpr', 'еврейско-персийски');
INSERT INTO "country" ("id", "name") VALUES ('egy', 'египетски');
INSERT INTO "country" ("id", "name") VALUES ('sio', 'език сиу');
INSERT INTO "country" ("id", "name") VALUES ('khi', 'езици коисан');
INSERT INTO "country" ("id", "name") VALUES ('apa', 'езици на апахите');
INSERT INTO "country" ("id", "name") VALUES ('eka', 'екажук');
INSERT INTO "country" ("id", "name") VALUES ('elx', 'еламитски');
INSERT INTO "country" ("id", "name") VALUES ('myv', 'ерзиа');
INSERT INTO "country" ("id", "name") VALUES ('eo', 'есперанто');
INSERT INTO "country" ("id", "name") VALUES ('et', 'естонски');
INSERT INTO "country" ("id", "name") VALUES ('ee', 'еуе');
INSERT INTO "country" ("id", "name") VALUES ('efi', 'ефик');
INSERT INTO "country" ("id", "name") VALUES ('chn', 'жаргон чинуук');
INSERT INTO "country" ("id", "name") VALUES ('sgn', 'жестомимичен език');
INSERT INTO "country" ("id", "name") VALUES ('kaj', 'жжи');
INSERT INTO "country" ("id", "name") VALUES ('zza', 'заза');
INSERT INTO "country" ("id", "name") VALUES ('znd', 'занде');
INSERT INTO "country" ("id", "name") VALUES ('zap', 'запотек');
INSERT INTO "country" ("id", "name") VALUES ('zen', 'зенага');
INSERT INTO "country" ("id", "name") VALUES ('za', 'зуанг');
INSERT INTO "country" ("id", "name") VALUES ('zu', 'зулуски');
INSERT INTO "country" ("id", "name") VALUES ('zun', 'зуни');
INSERT INTO "country" ("id", "name") VALUES ('iba', 'ибан');
INSERT INTO "country" ("id", "name") VALUES ('es_ES', 'иберийски испански');
INSERT INTO "country" ("id", "name") VALUES ('he', 'иврит');
INSERT INTO "country" ("id", "name") VALUES ('ig', 'игбо');
INSERT INTO "country" ("id", "name") VALUES ('ijo', 'иджо');
INSERT INTO "country" ("id", "name") VALUES ('yi', 'идиш');
INSERT INTO "country" ("id", "name") VALUES ('io', 'идо');
INSERT INTO "country" ("id", "name") VALUES ('art', 'изкуствен');
INSERT INTO "country" ("id", "name") VALUES ('frs', 'източен фризски');
INSERT INTO "country" ("id", "name") VALUES ('ilo', 'илоко');
INSERT INTO "country" ("id", "name") VALUES ('smn', 'инари-саамски');
INSERT INTO "country" ("id", "name") VALUES ('inh', 'ингушетски');
INSERT INTO "country" ("id", "name") VALUES ('inc', 'индийска група');
INSERT INTO "country" ("id", "name") VALUES ('ine', 'индо-европейски');
INSERT INTO "country" ("id", "name") VALUES ('id', 'индонезийски');
INSERT INTO "country" ("id", "name") VALUES ('ia', 'интерлингва');
INSERT INTO "country" ("id", "name") VALUES ('iu', 'инуктитут');
INSERT INTO "country" ("id", "name") VALUES ('ik', 'инупиак');
INSERT INTO "country" ("id", "name") VALUES ('ira', 'ирански');
INSERT INTO "country" ("id", "name") VALUES ('ga', 'ирландски');
INSERT INTO "country" ("id", "name") VALUES ('iro', 'ироквиански езици');
INSERT INTO "country" ("id", "name") VALUES ('is', 'исландски');
INSERT INTO "country" ("id", "name") VALUES ('es', 'испански');
INSERT INTO "country" ("id", "name") VALUES ('it', 'италиански');
INSERT INTO "country" ("id", "name") VALUES ('yo', 'йоруба');
INSERT INTO "country" ("id", "name") VALUES ('kbd', 'кабардиан');
INSERT INTO "country" ("id", "name") VALUES ('kab', 'кабилски');
INSERT INTO "country" ("id", "name") VALUES ('kaw', 'кави');
INSERT INTO "country" ("id", "name") VALUES ('cau', 'кавказски');
INSERT INTO "country" ("id", "name") VALUES ('cad', 'каддо');
INSERT INTO "country" ("id", "name") VALUES ('kk', 'казахски');
INSERT INTO "country" ("id", "name") VALUES ('xal', 'калмик');
INSERT INTO "country" ("id", "name") VALUES ('kam', 'камба');
INSERT INTO "country" ("id", "name") VALUES ('en_CA', 'канадски английски');
INSERT INTO "country" ("id", "name") VALUES ('fr_CA', 'канадски френски');
INSERT INTO "country" ("id", "name") VALUES ('kn', 'каннада');
INSERT INTO "country" ("id", "name") VALUES ('kr', 'канури');
INSERT INTO "country" ("id", "name") VALUES ('kaa', 'каракалпашки');
INSERT INTO "country" ("id", "name") VALUES ('krc', 'карачай-балкарски');
INSERT INTO "country" ("id", "name") VALUES ('krl', 'карелски');
INSERT INTO "country" ("id", "name") VALUES ('kar', 'каренски');
INSERT INTO "country" ("id", "name") VALUES ('car', 'карибски');
INSERT INTO "country" ("id", "name") VALUES ('ca', 'каталонски');
INSERT INTO "country" ("id", "name") VALUES ('kac', 'качински');
INSERT INTO "country" ("id", "name") VALUES ('ks', 'кашмирски');
INSERT INTO "country" ("id", "name") VALUES ('csb', 'кашубски');
INSERT INTO "country" ("id", "name") VALUES ('kj', 'кваняма');
INSERT INTO "country" ("id", "name") VALUES ('cel', 'келтски');
INSERT INTO "country" ("id", "name") VALUES ('qu', 'кечуа');
INSERT INTO "country" ("id", "name") VALUES ('ki', 'кикуйу');
INSERT INTO "country" ("id", "name") VALUES ('kmb', 'кимбунду');
INSERT INTO "country" ("id", "name") VALUES ('rw', 'киняруанда');
INSERT INTO "country" ("id", "name") VALUES ('ky', 'киргизски');
INSERT INTO "country" ("id", "name") VALUES ('zh', 'китайски');
INSERT INTO "country" ("id", "name") VALUES ('nwc', 'класически невари');
INSERT INTO "country" ("id", "name") VALUES ('syc', 'класически сирийски');
INSERT INTO "country" ("id", "name") VALUES ('tlh', 'клингон');
INSERT INTO "country" ("id", "name") VALUES ('kg', 'конгоански');
INSERT INTO "country" ("id", "name") VALUES ('kok', 'конкани');
INSERT INTO "country" ("id", "name") VALUES ('cop', 'коптски');
INSERT INTO "country" ("id", "name") VALUES ('ko', 'корейски');
INSERT INTO "country" ("id", "name") VALUES ('kw', 'корнуолски келтски');
INSERT INTO "country" ("id", "name") VALUES ('kfo', 'коро');
INSERT INTO "country" ("id", "name") VALUES ('co', 'корсикански');
INSERT INTO "country" ("id", "name") VALUES ('kos', 'косраен');
INSERT INTO "country" ("id", "name") VALUES ('kho', 'котски');
INSERT INTO "country" ("id", "name") VALUES ('kpe', 'кпеле');
INSERT INTO "country" ("id", "name") VALUES ('cpf', 'креолски и пиджин от френски');
INSERT INTO "country" ("id", "name") VALUES ('cpe', 'креолски или пиджин от английски');
INSERT INTO "country" ("id", "name") VALUES ('cpp', 'креолски или пиджин от португалски');
INSERT INTO "country" ("id", "name") VALUES ('crp', 'креолски или пиджини');
INSERT INTO "country" ("id", "name") VALUES ('cr', 'крии');
INSERT INTO "country" ("id", "name") VALUES ('mus', 'крик');
INSERT INTO "country" ("id", "name") VALUES ('crh', 'кримскотатарски');
INSERT INTO "country" ("id", "name") VALUES ('kro', 'кру');
INSERT INTO "country" ("id", "name") VALUES ('xh', 'ксоса');
INSERT INTO "country" ("id", "name") VALUES ('kum', 'кумикски');
INSERT INTO "country" ("id", "name") VALUES ('kru', 'курук');
INSERT INTO "country" ("id", "name") VALUES ('kut', 'кутенай');
INSERT INTO "country" ("id", "name") VALUES ('cus', 'кушитски езици');
INSERT INTO "country" ("id", "name") VALUES ('kha', 'кхаси');
INSERT INTO "country" ("id", "name") VALUES ('km', 'кхмерски');
INSERT INTO "country" ("id", "name") VALUES ('ku', 'кюрдски');
INSERT INTO "country" ("id", "name") VALUES ('lad', 'ладино');
INSERT INTO "country" ("id", "name") VALUES ('lam', 'ламба');
INSERT INTO "country" ("id", "name") VALUES ('lo', 'лаоски');
INSERT INTO "country" ("id", "name") VALUES ('lv', 'латвийски');
INSERT INTO "country" ("id", "name") VALUES ('es_419', 'латиноамерикански испански');
INSERT INTO "country" ("id", "name") VALUES ('la', 'латински');
INSERT INTO "country" ("id", "name") VALUES ('lah', 'лахнда');
INSERT INTO "country" ("id", "name") VALUES ('lez', 'лезгински');
INSERT INTO "country" ("id", "name") VALUES ('li', 'лимбургски');
INSERT INTO "country" ("id", "name") VALUES ('ln', 'лингала');
INSERT INTO "country" ("id", "name") VALUES ('lt', 'литовски');
INSERT INTO "country" ("id", "name") VALUES ('jbo', 'лоджбан');
INSERT INTO "country" ("id", "name") VALUES ('loz', 'лози');
INSERT INTO "country" ("id", "name") VALUES ('lu', 'луба катанга');
INSERT INTO "country" ("id", "name") VALUES ('lua', 'луба-лулуа');
INSERT INTO "country" ("id", "name") VALUES ('wen', 'лужишки език');
INSERT INTO "country" ("id", "name") VALUES ('lui', 'луисеньо');
INSERT INTO "country" ("id", "name") VALUES ('smj', 'луле-саамски');
INSERT INTO "country" ("id", "name") VALUES ('lun', 'лунда');
INSERT INTO "country" ("id", "name") VALUES ('luo', 'луо');
INSERT INTO "country" ("id", "name") VALUES ('lus', 'лушаи');
INSERT INTO "country" ("id", "name") VALUES ('lb', 'люксембургски');
INSERT INTO "country" ("id", "name") VALUES ('mag', 'магахи');
INSERT INTO "country" ("id", "name") VALUES ('mad', 'мадурски');
INSERT INTO "country" ("id", "name") VALUES ('mai', 'майтхили');
INSERT INTO "country" ("id", "name") VALUES ('myn', 'майя език');
INSERT INTO "country" ("id", "name") VALUES ('mak', 'макасар');
INSERT INTO "country" ("id", "name") VALUES ('mk', 'македонски');
INSERT INTO "country" ("id", "name") VALUES ('ms', 'малайски');
INSERT INTO "country" ("id", "name") VALUES ('ml', 'малаялам');
INSERT INTO "country" ("id", "name") VALUES ('mg', 'малгашки');
INSERT INTO "country" ("id", "name") VALUES ('mt', 'малтийски');
INSERT INTO "country" ("id", "name") VALUES ('mdr', 'мандар');
INSERT INTO "country" ("id", "name") VALUES ('man', 'мандинго');
INSERT INTO "country" ("id", "name") VALUES ('mni', 'манипури');
INSERT INTO "country" ("id", "name") VALUES ('gv', 'манкски');
INSERT INTO "country" ("id", "name") VALUES ('mno', 'манобо');
INSERT INTO "country" ("id", "name") VALUES ('mnc', 'манчжурски');
INSERT INTO "country" ("id", "name") VALUES ('mi', 'маорски');
INSERT INTO "country" ("id", "name") VALUES ('arn', 'мапуче');
INSERT INTO "country" ("id", "name") VALUES ('mr', 'маратхи');
INSERT INTO "country" ("id", "name") VALUES ('mwr', 'марвари');
INSERT INTO "country" ("id", "name") VALUES ('chm', 'марийски');
INSERT INTO "country" ("id", "name") VALUES ('mh', 'маршалезе');
INSERT INTO "country" ("id", "name") VALUES ('mas', 'масайски');
INSERT INTO "country" ("id", "name") VALUES ('men', 'менде');
INSERT INTO "country" ("id", "name") VALUES ('mic', 'микмак');
INSERT INTO "country" ("id", "name") VALUES ('min', 'минангбау');
INSERT INTO "country" ("id", "name") VALUES ('mwl', 'мирандийски');
INSERT INTO "country" ("id", "name") VALUES ('mul', 'многоезични');
INSERT INTO "country" ("id", "name") VALUES ('mdf', 'мокша');
INSERT INTO "country" ("id", "name") VALUES ('mo', 'молдовски');
INSERT INTO "country" ("id", "name") VALUES ('mkh', 'мон-кхмерски език');
INSERT INTO "country" ("id", "name") VALUES ('lol', 'монго');
INSERT INTO "country" ("id", "name") VALUES ('mn', 'монголски');
INSERT INTO "country" ("id", "name") VALUES ('mos', 'моси');
INSERT INTO "country" ("id", "name") VALUES ('moh', 'мохавк');
INSERT INTO "country" ("id", "name") VALUES ('mun', 'мунда');
INSERT INTO "country" ("id", "name") VALUES ('nv', 'навахо');
INSERT INTO "country" ("id", "name") VALUES ('na', 'науру');
INSERT INTO "country" ("id", "name") VALUES ('nah', 'нахуатл');
INSERT INTO "country" ("id", "name") VALUES ('ng', 'ндонга');
INSERT INTO "country" ("id", "name") VALUES ('nap', 'неаполитански');
INSERT INTO "country" ("id", "name") VALUES ('new', 'неварски');
INSERT INTO "country" ("id", "name") VALUES ('de', 'немски');
INSERT INTO "country" ("id", "name") VALUES ('und', 'неопределен');
INSERT INTO "country" ("id", "name") VALUES ('ne', 'непалски');
INSERT INTO "country" ("id", "name") VALUES ('nzi', 'нзима');
INSERT INTO "country" ("id", "name") VALUES ('nym', 'ниамвези');
INSERT INTO "country" ("id", "name") VALUES ('nyn', 'нианколе');
INSERT INTO "country" ("id", "name") VALUES ('tog', 'нианса тонга');
INSERT INTO "country" ("id", "name") VALUES ('nia', 'ниас');
INSERT INTO "country" ("id", "name") VALUES ('nic', 'нигер-кордофански');
INSERT INTO "country" ("id", "name") VALUES ('ssa', 'нило-сахарски език');
INSERT INTO "country" ("id", "name") VALUES ('niu', 'ниуеан');
INSERT INTO "country" ("id", "name") VALUES ('nog', 'ногаи');
INSERT INTO "country" ("id", "name") VALUES ('no', 'норвежки');
INSERT INTO "country" ("id", "name") VALUES ('nb', 'норвежки бокмал');
INSERT INTO "country" ("id", "name") VALUES ('nub', 'нубийски езици');
INSERT INTO "country" ("id", "name") VALUES ('nyo', 'нуоро');
INSERT INTO "country" ("id", "name") VALUES ('nqo', 'н’ко');
INSERT INTO "country" ("id", "name") VALUES ('oj', 'оджибва');
INSERT INTO "country" ("id", "name") VALUES ('ie', 'оксидентал');
INSERT INTO "country" ("id", "name") VALUES ('oc', 'окситански');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hans', 'опростен китайски');
INSERT INTO "country" ("id", "name") VALUES ('or', 'ория');
INSERT INTO "country" ("id", "name") VALUES ('om', 'оромо');
INSERT INTO "country" ("id", "name") VALUES ('osa', 'оседжи');
INSERT INTO "country" ("id", "name") VALUES ('os', 'осетски');
INSERT INTO "country" ("id", "name") VALUES ('ota', 'отомански турски');
INSERT INTO "country" ("id", "name") VALUES ('pau', 'палауан');
INSERT INTO "country" ("id", "name") VALUES ('pi', 'пали');
INSERT INTO "country" ("id", "name") VALUES ('pam', 'пампанга');
INSERT INTO "country" ("id", "name") VALUES ('pag', 'пангасинан');
INSERT INTO "country" ("id", "name") VALUES ('pap', 'папиаменту');
INSERT INTO "country" ("id", "name") VALUES ('paa', 'папуаски');
INSERT INTO "country" ("id", "name") VALUES ('pa', 'пенджабски');
INSERT INTO "country" ("id", "name") VALUES ('fa', 'персийски');
INSERT INTO "country" ("id", "name") VALUES ('pal', 'пехлевийски');
INSERT INTO "country" ("id", "name") VALUES ('pl', 'полски');
INSERT INTO "country" ("id", "name") VALUES ('pt', 'португалски');
INSERT INTO "country" ("id", "name") VALUES ('pon', 'похнпеиан');
INSERT INTO "country" ("id", "name") VALUES ('pra', 'пракритски език');
INSERT INTO "country" ("id", "name") VALUES ('pro', 'провансалски');
INSERT INTO "country" ("id", "name") VALUES ('ps', 'пущу');
INSERT INTO "country" ("id", "name") VALUES ('raj', 'раджастански');
INSERT INTO "country" ("id", "name") VALUES ('rap', 'рапа нуи');
INSERT INTO "country" ("id", "name") VALUES ('rar', 'рапотонган');
INSERT INTO "country" ("id", "name") VALUES ('rm', 'реторомански');
INSERT INTO "country" ("id", "name") VALUES ('roa', 'романски');
INSERT INTO "country" ("id", "name") VALUES ('root', 'роот');
INSERT INTO "country" ("id", "name") VALUES ('ro', 'румънски');
INSERT INTO "country" ("id", "name") VALUES ('rn', 'рунди');
INSERT INTO "country" ("id", "name") VALUES ('ru', 'руски');
INSERT INTO "country" ("id", "name") VALUES ('smi', 'саамски езици');
INSERT INTO "country" ("id", "name") VALUES ('sal', 'салишански език');
INSERT INTO "country" ("id", "name") VALUES ('sam', 'самаритански арамейски');
INSERT INTO "country" ("id", "name") VALUES ('sm', 'самоански');
INSERT INTO "country" ("id", "name") VALUES ('sg', 'санго');
INSERT INTO "country" ("id", "name") VALUES ('sad', 'сандве');
INSERT INTO "country" ("id", "name") VALUES ('sa', 'санкскритски');
INSERT INTO "country" ("id", "name") VALUES ('sat', 'сантали');
INSERT INTO "country" ("id", "name") VALUES ('sc', 'сардински');
INSERT INTO "country" ("id", "name") VALUES ('sas', 'сасак');
INSERT INTO "country" ("id", "name") VALUES ('ceb', 'себуано');
INSERT INTO "country" ("id", "name") VALUES ('nd', 'северен ндебеле');
INSERT INTO "country" ("id", "name") VALUES ('se', 'северен сами');
INSERT INTO "country" ("id", "name") VALUES ('nso', 'северен сото');
INSERT INTO "country" ("id", "name") VALUES ('frr', 'северен фризски');
INSERT INTO "country" ("id", "name") VALUES ('nai', 'северноамерикански индиански');
INSERT INTO "country" ("id", "name") VALUES ('sel', 'селкуп');
INSERT INTO "country" ("id", "name") VALUES ('sem', 'семитски');
INSERT INTO "country" ("id", "name") VALUES ('srr', 'серер');
INSERT INTO "country" ("id", "name") VALUES ('st', 'сесуто');
INSERT INTO "country" ("id", "name") VALUES ('ii', 'сечуански');
INSERT INTO "country" ("id", "name") VALUES ('sid', 'сидамо');
INSERT INTO "country" ("id", "name") VALUES ('bla', 'сиксика');
INSERT INTO "country" ("id", "name") VALUES ('sd', 'синдхи');
INSERT INTO "country" ("id", "name") VALUES ('sit', 'синотибетски');
INSERT INTO "country" ("id", "name") VALUES ('si', 'синхалски');
INSERT INTO "country" ("id", "name") VALUES ('syr', 'сирийски');
INSERT INTO "country" ("id", "name") VALUES ('scn', 'сицилиански');
INSERT INTO "country" ("id", "name") VALUES ('sms', 'сколт-саамски');
INSERT INTO "country" ("id", "name") VALUES ('sla', 'славянски');
INSERT INTO "country" ("id", "name") VALUES ('den', 'слейви');
INSERT INTO "country" ("id", "name") VALUES ('sk', 'словашки');
INSERT INTO "country" ("id", "name") VALUES ('sl', 'словенски');
INSERT INTO "country" ("id", "name") VALUES ('sog', 'согдийски');
INSERT INTO "country" ("id", "name") VALUES ('so', 'сомалийски');
INSERT INTO "country" ("id", "name") VALUES ('son', 'сонгхай');
INSERT INTO "country" ("id", "name") VALUES ('snk', 'сонинке');
INSERT INTO "country" ("id", "name") VALUES ('srn', 'сранан тонго');
INSERT INTO "country" ("id", "name") VALUES ('enm', 'средновековен английски');
INSERT INTO "country" ("id", "name") VALUES ('mga', 'средновековен ирландски');
INSERT INTO "country" ("id", "name") VALUES ('gmh', 'средновековен немски');
INSERT INTO "country" ("id", "name") VALUES ('frm', 'средновековен френски');
INSERT INTO "country" ("id", "name") VALUES ('dum', 'средновековен холандски');
INSERT INTO "country" ("id", "name") VALUES ('sr', 'сръбски');
INSERT INTO "country" ("id", "name") VALUES ('ang', 'староанглийски');
INSERT INTO "country" ("id", "name") VALUES ('goh', 'старовисоконемски');
INSERT INTO "country" ("id", "name") VALUES ('sga', 'староирландски');
INSERT INTO "country" ("id", "name") VALUES ('non', 'старонорвежски');
INSERT INTO "country" ("id", "name") VALUES ('peo', 'староперсийски');
INSERT INTO "country" ("id", "name") VALUES ('oto', 'старотурски езици');
INSERT INTO "country" ("id", "name") VALUES ('fro', 'старофренски');
INSERT INTO "country" ("id", "name") VALUES ('ss', 'суази');
INSERT INTO "country" ("id", "name") VALUES ('sw', 'суахили');
INSERT INTO "country" ("id", "name") VALUES ('suk', 'сукума');
INSERT INTO "country" ("id", "name") VALUES ('su', 'сундански');
INSERT INTO "country" ("id", "name") VALUES ('sus', 'сусу');
INSERT INTO "country" ("id", "name") VALUES ('nn', 'съвременен норвежки');
INSERT INTO "country" ("id", "name") VALUES ('sh', 'сърбохърватски');
INSERT INTO "country" ("id", "name") VALUES ('tl', 'тагалог');
INSERT INTO "country" ("id", "name") VALUES ('tg', 'таджикски');
INSERT INTO "country" ("id", "name") VALUES ('th', 'таи');
INSERT INTO "country" ("id", "name") VALUES ('ty', 'таитянски');
INSERT INTO "country" ("id", "name") VALUES ('tai', 'тайландски');
INSERT INTO "country" ("id", "name") VALUES ('tmh', 'тамашек');
INSERT INTO "country" ("id", "name") VALUES ('ta', 'тамилски');
INSERT INTO "country" ("id", "name") VALUES ('tt', 'татарски');
INSERT INTO "country" ("id", "name") VALUES ('te', 'телугу');
INSERT INTO "country" ("id", "name") VALUES ('tem', 'темне');
INSERT INTO "country" ("id", "name") VALUES ('ter', 'терено');
INSERT INTO "country" ("id", "name") VALUES ('tet', 'тетум');
INSERT INTO "country" ("id", "name") VALUES ('bo', 'тибетски');
INSERT INTO "country" ("id", "name") VALUES ('tiv', 'тив');
INSERT INTO "country" ("id", "name") VALUES ('tig', 'тигре');
INSERT INTO "country" ("id", "name") VALUES ('ti', 'тигриня');
INSERT INTO "country" ("id", "name") VALUES ('tli', 'тлингит');
INSERT INTO "country" ("id", "name") VALUES ('tpi', 'ток писин');
INSERT INTO "country" ("id", "name") VALUES ('tkl', 'токелайски');
INSERT INTO "country" ("id", "name") VALUES ('to', 'тонга');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hant', 'традиционен китайски');
INSERT INTO "country" ("id", "name") VALUES ('tn', 'тсвана');
INSERT INTO "country" ("id", "name") VALUES ('ts', 'тсонга');
INSERT INTO "country" ("id", "name") VALUES ('kcg', 'туап');
INSERT INTO "country" ("id", "name") VALUES ('tvl', 'тувалуански');
INSERT INTO "country" ("id", "name") VALUES ('tyv', 'тувински');
INSERT INTO "country" ("id", "name") VALUES ('tw', 'туи');
INSERT INTO "country" ("id", "name") VALUES ('tum', 'тумбука');
INSERT INTO "country" ("id", "name") VALUES ('tup', 'тупи');
INSERT INTO "country" ("id", "name") VALUES ('tk', 'туркменски');
INSERT INTO "country" ("id", "name") VALUES ('tr', 'турски');
INSERT INTO "country" ("id", "name") VALUES ('was', 'уашо');
INSERT INTO "country" ("id", "name") VALUES ('uga', 'угаритски');
INSERT INTO "country" ("id", "name") VALUES ('fiu', 'угрофински');
INSERT INTO "country" ("id", "name") VALUES ('udm', 'удмуртски');
INSERT INTO "country" ("id", "name") VALUES ('cy', 'уелски');
INSERT INTO "country" ("id", "name") VALUES ('uz', 'узбекски');
INSERT INTO "country" ("id", "name") VALUES ('ug', 'уйгурски');
INSERT INTO "country" ("id", "name") VALUES ('uk', 'украински');
INSERT INTO "country" ("id", "name") VALUES ('umb', 'умбунду');
INSERT INTO "country" ("id", "name") VALUES ('hu', 'унгарски');
INSERT INTO "country" ("id", "name") VALUES ('ur', 'урду');
INSERT INTO "country" ("id", "name") VALUES ('fan', 'фанг');
INSERT INTO "country" ("id", "name") VALUES ('fat', 'фанти');
INSERT INTO "country" ("id", "name") VALUES ('fo', 'фарьорски');
INSERT INTO "country" ("id", "name") VALUES ('fj', 'фиджийски');
INSERT INTO "country" ("id", "name") VALUES ('fil', 'филипински');
INSERT INTO "country" ("id", "name") VALUES ('phi', 'филипински (други)');
INSERT INTO "country" ("id", "name") VALUES ('phn', 'финикийски');
INSERT INTO "country" ("id", "name") VALUES ('fi', 'фински');
INSERT INTO "country" ("id", "name") VALUES ('nl_BE', 'фламандски');
INSERT INTO "country" ("id", "name") VALUES ('fon', 'фон');
INSERT INTO "country" ("id", "name") VALUES ('fr', 'френски');
INSERT INTO "country" ("id", "name") VALUES ('fy', 'фризийски');
INSERT INTO "country" ("id", "name") VALUES ('fur', 'фриулиански');
INSERT INTO "country" ("id", "name") VALUES ('ff', 'фула');
INSERT INTO "country" ("id", "name") VALUES ('haw', 'хавайски');
INSERT INTO "country" ("id", "name") VALUES ('ht', 'хаитянски');
INSERT INTO "country" ("id", "name") VALUES ('hai', 'хайда');
INSERT INTO "country" ("id", "name") VALUES ('ha', 'хауза');
INSERT INTO "country" ("id", "name") VALUES ('hz', 'хереро');
INSERT INTO "country" ("id", "name") VALUES ('hil', 'хилигайнон');
INSERT INTO "country" ("id", "name") VALUES ('him', 'химачали');
INSERT INTO "country" ("id", "name") VALUES ('hi', 'хинди');
INSERT INTO "country" ("id", "name") VALUES ('ho', 'хири моту');
INSERT INTO "country" ("id", "name") VALUES ('hit', 'хитски');
INSERT INTO "country" ("id", "name") VALUES ('hmn', 'хмонг');
INSERT INTO "country" ("id", "name") VALUES ('nl', 'холандски');
INSERT INTO "country" ("id", "name") VALUES ('hup', 'хупа');
INSERT INTO "country" ("id", "name") VALUES ('hr', 'хърватски');
INSERT INTO "country" ("id", "name") VALUES ('cai', 'централноамерикански индиански');
INSERT INTO "country" ("id", "name") VALUES ('rom', 'цигански език');
INSERT INTO "country" ("id", "name") VALUES ('tsi', 'цимшиански');
INSERT INTO "country" ("id", "name") VALUES ('cu', 'църковно славянски');
INSERT INTO "country" ("id", "name") VALUES ('chg', 'чагатай');
INSERT INTO "country" ("id", "name") VALUES ('ch', 'чаморо');
INSERT INTO "country" ("id", "name") VALUES ('cmc', 'чамски');
INSERT INTO "country" ("id", "name") VALUES ('chy', 'чейенски');
INSERT INTO "country" ("id", "name") VALUES ('chr', 'чероки');
INSERT INTO "country" ("id", "name") VALUES ('ce', 'чеченски');
INSERT INTO "country" ("id", "name") VALUES ('cs', 'чешки');
INSERT INTO "country" ("id", "name") VALUES ('chb', 'чибча');
INSERT INTO "country" ("id", "name") VALUES ('chp', 'чиипувски');
INSERT INTO "country" ("id", "name") VALUES ('ny', 'чинянджа');
INSERT INTO "country" ("id", "name") VALUES ('cho', 'чокто');
INSERT INTO "country" ("id", "name") VALUES ('cv', 'чувашки');
INSERT INTO "country" ("id", "name") VALUES ('chk', 'чуук');
INSERT INTO "country" ("id", "name") VALUES ('shn', 'шан');
INSERT INTO "country" ("id", "name") VALUES ('sv', 'шведски');
INSERT INTO "country" ("id", "name") VALUES ('de_CH', 'швейцарски горногермански');
INSERT INTO "country" ("id", "name") VALUES ('gsw', 'швейцарски немски');
INSERT INTO "country" ("id", "name") VALUES ('fr_CH', 'швейцарски френски');
INSERT INTO "country" ("id", "name") VALUES ('sn', 'шона');
INSERT INTO "country" ("id", "name") VALUES ('sco', 'шотландски');
INSERT INTO "country" ("id", "name") VALUES ('gd', 'шотландски галски');
INSERT INTO "country" ("id", "name") VALUES ('sux', 'шумерски');
INSERT INTO "country" ("id", "name") VALUES ('nr', 'южен ндебеле');
INSERT INTO "country" ("id", "name") VALUES ('alt', 'южноалтайски');
INSERT INTO "country" ("id", "name") VALUES ('sai', 'южноамерикански индиански');
INSERT INTO "country" ("id", "name") VALUES ('sma', 'южносаамски');
INSERT INTO "country" ("id", "name") VALUES ('ypk', 'юпик');
INSERT INTO "country" ("id", "name") VALUES ('jv', 'явански');
INSERT INTO "country" ("id", "name") VALUES ('sah', 'якутски');
INSERT INTO "country" ("id", "name") VALUES ('yao', 'яо');
INSERT INTO "country" ("id", "name") VALUES ('yap', 'япезе');
INSERT INTO "country" ("id", "name") VALUES ('ja', 'японски');
