CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('ab', 'Abkażjan');
INSERT INTO "country" ("id", "name") VALUES ('ace', 'Aċiniż');
INSERT INTO "country" ("id", "name") VALUES ('ada', 'Adangme');
INSERT INTO "country" ("id", "name") VALUES ('ady', 'Adyghe');
INSERT INTO "country" ("id", "name") VALUES ('aa', 'Afar');
INSERT INTO "country" ("id", "name") VALUES ('afh', 'Afriħili');
INSERT INTO "country" ("id", "name") VALUES ('af', 'Afrikans');
INSERT INTO "country" ("id", "name") VALUES ('afa', 'Afro-Asjatiku (Oħra)');
INSERT INTO "country" ("id", "name") VALUES ('ay', 'Ajmara');
INSERT INTO "country" ("id", "name") VALUES ('ain', 'Ajnu');
INSERT INTO "country" ("id", "name") VALUES ('ak', 'Akan');
INSERT INTO "country" ("id", "name") VALUES ('akk', 'Akkadjen');
INSERT INTO "country" ("id", "name") VALUES ('ach', 'Akoli');
INSERT INTO "country" ("id", "name") VALUES ('sq', 'Albaniż');
INSERT INTO "country" ("id", "name") VALUES ('ale', 'Aleut');
INSERT INTO "country" ("id", "name") VALUES ('tut', 'Altajk (Oħra)');
INSERT INTO "country" ("id", "name") VALUES ('cai', 'Amerika Ċentrali (Oħra)');
INSERT INTO "country" ("id", "name") VALUES ('am', 'Amħariku');
INSERT INTO "country" ("id", "name") VALUES ('anp', 'Angika');
INSERT INTO "country" ("id", "name") VALUES ('an', 'Aragonese');
INSERT INTO "country" ("id", "name") VALUES ('arc', 'Aramajk');
INSERT INTO "country" ("id", "name") VALUES ('arp', 'Arapaħo');
INSERT INTO "country" ("id", "name") VALUES ('arw', 'Arawak');
INSERT INTO "country" ("id", "name") VALUES ('arn', 'Arawkanjan');
INSERT INTO "country" ("id", "name") VALUES ('hy', 'Armenjan');
INSERT INTO "country" ("id", "name") VALUES ('rup', 'Aromanijan');
INSERT INTO "country" ("id", "name") VALUES ('art', 'Artifiċjali (Oħra)');
INSERT INTO "country" ("id", "name") VALUES ('as', 'Assamese');
INSERT INTO "country" ("id", "name") VALUES ('ast', 'Asturian');
INSERT INTO "country" ("id", "name") VALUES ('cch', 'Atsam');
INSERT INTO "country" ("id", "name") VALUES ('av', 'Avarik');
INSERT INTO "country" ("id", "name") VALUES ('ae', 'Avestan');
INSERT INTO "country" ("id", "name") VALUES ('awa', 'Awadħi');
INSERT INTO "country" ("id", "name") VALUES ('map', 'Awstronesjan');
INSERT INTO "country" ("id", "name") VALUES ('az', 'Ażerbajġani');
INSERT INTO "country" ("id", "name") VALUES ('ban', 'Baliniż');
INSERT INTO "country" ("id", "name") VALUES ('bat', 'Baltiku (Oħra)');
INSERT INTO "country" ("id", "name") VALUES ('bal', 'Baluċi');
INSERT INTO "country" ("id", "name") VALUES ('bm', 'Bambara');
INSERT INTO "country" ("id", "name") VALUES ('bad', 'Banda');
INSERT INTO "country" ("id", "name") VALUES ('bnt', 'Bantu');
INSERT INTO "country" ("id", "name") VALUES ('bas', 'Basa');
INSERT INTO "country" ("id", "name") VALUES ('eu', 'Bask');
INSERT INTO "country" ("id", "name") VALUES ('btk', 'Batak');
INSERT INTO "country" ("id", "name") VALUES ('ba', 'Baxkir');
INSERT INTO "country" ("id", "name") VALUES ('ber', 'Beber');
INSERT INTO "country" ("id", "name") VALUES ('bej', 'Beja');
INSERT INTO "country" ("id", "name") VALUES ('be', 'Belarussu');
INSERT INTO "country" ("id", "name") VALUES ('bem', 'Bemba');
INSERT INTO "country" ("id", "name") VALUES ('bn', 'Bengali');
INSERT INTO "country" ("id", "name") VALUES ('bh', 'Biħari');
INSERT INTO "country" ("id", "name") VALUES ('bik', 'Bikol');
INSERT INTO "country" ("id", "name") VALUES ('bin', 'Bini');
INSERT INTO "country" ("id", "name") VALUES ('bi', 'Bislama');
INSERT INTO "country" ("id", "name") VALUES ('byn', 'Blin');
INSERT INTO "country" ("id", "name") VALUES ('bho', 'Bojpuri');
INSERT INTO "country" ("id", "name") VALUES ('nb', 'Bokmahal Norveġiż');
INSERT INTO "country" ("id", "name") VALUES ('bs', 'Bosnijan');
INSERT INTO "country" ("id", "name") VALUES ('bra', 'Braj');
INSERT INTO "country" ("id", "name") VALUES ('br', 'Brenton');
INSERT INTO "country" ("id", "name") VALUES ('bug', 'Buginiż');
INSERT INTO "country" ("id", "name") VALUES ('bg', 'Bulgaru');
INSERT INTO "country" ("id", "name") VALUES ('bua', 'Burjat');
INSERT INTO "country" ("id", "name") VALUES ('my', 'Burmiż');
INSERT INTO "country" ("id", "name") VALUES ('chg', 'Ċagataj');
INSERT INTO "country" ("id", "name") VALUES ('ch', 'Ċamorro');
INSERT INTO "country" ("id", "name") VALUES ('ce', 'Ċeċen');
INSERT INTO "country" ("id", "name") VALUES ('cs', 'Ċek');
INSERT INTO "country" ("id", "name") VALUES ('chr', 'Ċerokij');
INSERT INTO "country" ("id", "name") VALUES ('chb', 'Ċibċa');
INSERT INTO "country" ("id", "name") VALUES ('ny', 'Ċiċewa; Njanġa');
INSERT INTO "country" ("id", "name") VALUES ('zh', 'Ċiniż');
INSERT INTO "country" ("id", "name") VALUES ('chp', 'Ċipewjan');
INSERT INTO "country" ("id", "name") VALUES ('cho', 'Ċostaw');
INSERT INTO "country" ("id", "name") VALUES ('chk', 'Ċukese');
INSERT INTO "country" ("id", "name") VALUES ('cv', 'Ċuvax');
INSERT INTO "country" ("id", "name") VALUES ('nwc', 'Classical Newari');
INSERT INTO "country" ("id", "name") VALUES ('crh', 'Crimean Turkish; Crimean Tatar');
INSERT INTO "country" ("id", "name") VALUES ('day', 'Dajak');
INSERT INTO "country" ("id", "name") VALUES ('dak', 'Dakota');
INSERT INTO "country" ("id", "name") VALUES ('da', 'Daniż');
INSERT INTO "country" ("id", "name") VALUES ('dar', 'Dargwa');
INSERT INTO "country" ("id", "name") VALUES ('del', 'Delawerjan');
INSERT INTO "country" ("id", "name") VALUES ('din', 'Dinka');
INSERT INTO "country" ("id", "name") VALUES ('dv', 'Diveħi');
INSERT INTO "country" ("id", "name") VALUES ('dyu', 'Djula');
INSERT INTO "country" ("id", "name") VALUES ('doi', 'Dogri');
INSERT INTO "country" ("id", "name") VALUES ('dgr', 'Dogrib');
INSERT INTO "country" ("id", "name") VALUES ('dra', 'Dravidjan (Oħra)');
INSERT INTO "country" ("id", "name") VALUES ('dua', 'Dwala');
INSERT INTO "country" ("id", "name") VALUES ('dz', 'Dżongka');
INSERT INTO "country" ("id", "name") VALUES ('he', 'Ebrajk');
INSERT INTO "country" ("id", "name") VALUES ('efi', 'Efik');
INSERT INTO "country" ("id", "name") VALUES ('egy', 'Eġizzjan (Antik)');
INSERT INTO "country" ("id", "name") VALUES ('eka', 'Ekajuk');
INSERT INTO "country" ("id", "name") VALUES ('elx', 'Elamit');
INSERT INTO "country" ("id", "name") VALUES ('myv', 'Erzya');
INSERT INTO "country" ("id", "name") VALUES ('eo', 'Esperanto');
INSERT INTO "country" ("id", "name") VALUES ('et', 'Estonjan');
INSERT INTO "country" ("id", "name") VALUES ('ee', 'Ewe');
INSERT INTO "country" ("id", "name") VALUES ('ewo', 'Ewondo');
INSERT INTO "country" ("id", "name") VALUES ('fan', 'Fang');
INSERT INTO "country" ("id", "name") VALUES ('fat', 'Fanti');
INSERT INTO "country" ("id", "name") VALUES ('fo', 'Fawriż');
INSERT INTO "country" ("id", "name") VALUES ('phn', 'Feniċju');
INSERT INTO "country" ("id", "name") VALUES ('fj', 'Fiġi');
INSERT INTO "country" ("id", "name") VALUES ('phi', 'Filippin (Oħra)');
INSERT INTO "country" ("id", "name") VALUES ('fil', 'Filippino');
INSERT INTO "country" ("id", "name") VALUES ('fi', 'Finlandiż');
INSERT INTO "country" ("id", "name") VALUES ('fiu', 'Finno - Ugrijan');
INSERT INTO "country" ("id", "name") VALUES ('fon', 'Fon');
INSERT INTO "country" ("id", "name") VALUES ('fr', 'Franċiż');
INSERT INTO "country" ("id", "name") VALUES ('fro', 'Franċiż, Antik');
INSERT INTO "country" ("id", "name") VALUES ('frm', 'Franċiż, Medjevali');
INSERT INTO "country" ("id", "name") VALUES ('fur', 'Frijuljan');
INSERT INTO "country" ("id", "name") VALUES ('fy', 'Friżjan');
INSERT INTO "country" ("id", "name") VALUES ('ff', 'Fulaħ');
INSERT INTO "country" ("id", "name") VALUES ('ja', 'Ġappuniż');
INSERT INTO "country" ("id", "name") VALUES ('chn', 'Ġargon taċ-Ċinuk');
INSERT INTO "country" ("id", "name") VALUES ('jv', 'Ġavaniż');
INSERT INTO "country" ("id", "name") VALUES ('grb', 'Ġerbo');
INSERT INTO "country" ("id", "name") VALUES ('gem', 'Ġermaniku (Oħra)');
INSERT INTO "country" ("id", "name") VALUES ('goh', 'Ġermaniku, Antik Pulit');
INSERT INTO "country" ("id", "name") VALUES ('gmh', 'Ġermaniku, Medjevali Pulit');
INSERT INTO "country" ("id", "name") VALUES ('de', 'Ġermaniż');
INSERT INTO "country" ("id", "name") VALUES ('nds', 'Ġermaniż Komuni; Sassonu Komuni');
INSERT INTO "country" ("id", "name") VALUES ('ka', 'Ġorġjan');
INSERT INTO "country" ("id", "name") VALUES ('gaa', 'Ga');
INSERT INTO "country" ("id", "name") VALUES ('gay', 'Gajo');
INSERT INTO "country" ("id", "name") VALUES ('gl', 'Gallegjan');
INSERT INTO "country" ("id", "name") VALUES ('gd', 'Galliku Skoċċiż');
INSERT INTO "country" ("id", "name") VALUES ('lg', 'Ganda');
INSERT INTO "country" ("id", "name") VALUES ('gba', 'Gbaja');
INSERT INTO "country" ("id", "name") VALUES ('gez', 'Geez');
INSERT INTO "country" ("id", "name") VALUES ('gil', 'Gilbertjan');
INSERT INTO "country" ("id", "name") VALUES ('gon', 'Gondi');
INSERT INTO "country" ("id", "name") VALUES ('gor', 'Gorontalo');
INSERT INTO "country" ("id", "name") VALUES ('got', 'Gotiku');
INSERT INTO "country" ("id", "name") VALUES ('el', 'Grieg');
INSERT INTO "country" ("id", "name") VALUES ('grc', 'Grieg, Antik (to 1453)');
INSERT INTO "country" ("id", "name") VALUES ('gu', 'Guġarati');
INSERT INTO "country" ("id", "name") VALUES ('gn', 'Gwarani');
INSERT INTO "country" ("id", "name") VALUES ('gwi', 'Gwiċin');
INSERT INTO "country" ("id", "name") VALUES ('ar', 'Għarbi');
INSERT INTO "country" ("id", "name") VALUES ('root', 'Għerq');
INSERT INTO "country" ("id", "name") VALUES ('ht', 'Haitian');
INSERT INTO "country" ("id", "name") VALUES ('hil', 'Hiligaynon');
INSERT INTO "country" ("id", "name") VALUES ('hai', 'Ħajda');
INSERT INTO "country" ("id", "name") VALUES ('haw', 'Ħawajjan');
INSERT INTO "country" ("id", "name") VALUES ('ha', 'Ħawsa');
INSERT INTO "country" ("id", "name") VALUES ('hz', 'Ħerero');
INSERT INTO "country" ("id", "name") VALUES ('him', 'Ħimaċali');
INSERT INTO "country" ("id", "name") VALUES ('hi', 'Ħindi');
INSERT INTO "country" ("id", "name") VALUES ('ho', 'Ħiri Motu');
INSERT INTO "country" ("id", "name") VALUES ('hit', 'Ħittit');
INSERT INTO "country" ("id", "name") VALUES ('hmn', 'Ħmong');
INSERT INTO "country" ("id", "name") VALUES ('xh', 'Ħoża');
INSERT INTO "country" ("id", "name") VALUES ('hup', 'Ħupa');
INSERT INTO "country" ("id", "name") VALUES ('iba', 'Iban');
INSERT INTO "country" ("id", "name") VALUES ('io', 'Ido');
INSERT INTO "country" ("id", "name") VALUES ('ijo', 'Iġo');
INSERT INTO "country" ("id", "name") VALUES ('ig', 'Igbo');
INSERT INTO "country" ("id", "name") VALUES ('ilo', 'Iloko');
INSERT INTO "country" ("id", "name") VALUES ('smn', 'Inari Sami');
INSERT INTO "country" ("id", "name") VALUES ('und', 'Indeterminat');
INSERT INTO "country" ("id", "name") VALUES ('inc', 'Indjan (Oħra)');
INSERT INTO "country" ("id", "name") VALUES ('sai', 'Indjan tal-Amerika t’Isfel (Oħra)');
INSERT INTO "country" ("id", "name") VALUES ('nai', 'Indjan tal-Amerika ta’ Fuq (Oħra)');
INSERT INTO "country" ("id", "name") VALUES ('ine', 'Indo-Ewropew');
INSERT INTO "country" ("id", "name") VALUES ('id', 'Indoneżjan');
INSERT INTO "country" ("id", "name") VALUES ('en', 'Ingliż');
INSERT INTO "country" ("id", "name") VALUES ('ang', 'Ingliż, Antik');
INSERT INTO "country" ("id", "name") VALUES ('enm', 'Ingliż, Medjevali (1100-1500)');
INSERT INTO "country" ("id", "name") VALUES ('inh', 'Ingush');
INSERT INTO "country" ("id", "name") VALUES ('ia', 'Interlingua');
INSERT INTO "country" ("id", "name") VALUES ('ie', 'Interlingue');
INSERT INTO "country" ("id", "name") VALUES ('iu', 'Inukitut');
INSERT INTO "country" ("id", "name") VALUES ('ik', 'Inupjak');
INSERT INTO "country" ("id", "name") VALUES ('ira', 'Iranjan');
INSERT INTO "country" ("id", "name") VALUES ('ga', 'Irlandiż');
INSERT INTO "country" ("id", "name") VALUES ('sga', 'Irlandiż, Antik (sa l-900)');
INSERT INTO "country" ("id", "name") VALUES ('mga', 'Irlandiż, Medjevali (900-1200)');
INSERT INTO "country" ("id", "name") VALUES ('is', 'Iżlandiż');
INSERT INTO "country" ("id", "name") VALUES ('sah', 'Jakut');
INSERT INTO "country" ("id", "name") VALUES ('yao', 'Jao');
INSERT INTO "country" ("id", "name") VALUES ('yap', 'Japese');
INSERT INTO "country" ("id", "name") VALUES ('yi', 'Jiddix');
INSERT INTO "country" ("id", "name") VALUES ('yo', 'Joruba');
INSERT INTO "country" ("id", "name") VALUES ('kbd', 'Kabardian');
INSERT INTO "country" ("id", "name") VALUES ('kab', 'Kabuljan');
INSERT INTO "country" ("id", "name") VALUES ('kac', 'Kaċin');
INSERT INTO "country" ("id", "name") VALUES ('cad', 'Kaddo');
INSERT INTO "country" ("id", "name") VALUES ('kl', 'Kalallisut');
INSERT INTO "country" ("id", "name") VALUES ('xal', 'Kalmyk');
INSERT INTO "country" ("id", "name") VALUES ('kam', 'Kamba');
INSERT INTO "country" ("id", "name") VALUES ('kn', 'Kannada');
INSERT INTO "country" ("id", "name") VALUES ('kr', 'Kanuri');
INSERT INTO "country" ("id", "name") VALUES ('kaa', 'Kara-Kalpak');
INSERT INTO "country" ("id", "name") VALUES ('krc', 'Karachay-Balkar');
INSERT INTO "country" ("id", "name") VALUES ('kar', 'Karen');
INSERT INTO "country" ("id", "name") VALUES ('car', 'Karib');
INSERT INTO "country" ("id", "name") VALUES ('csb', 'Kashubian');
INSERT INTO "country" ("id", "name") VALUES ('kha', 'Kasi');
INSERT INTO "country" ("id", "name") VALUES ('ca', 'Katalan');
INSERT INTO "country" ("id", "name") VALUES ('kaw', 'Kawi');
INSERT INTO "country" ("id", "name") VALUES ('cau', 'Kawkasu (Oħra)');
INSERT INTO "country" ("id", "name") VALUES ('ks', 'Kaxmiri');
INSERT INTO "country" ("id", "name") VALUES ('kk', 'Każak');
INSERT INTO "country" ("id", "name") VALUES ('qu', 'Keċwa');
INSERT INTO "country" ("id", "name") VALUES ('cel', 'Keltiku (Oħra)');
INSERT INTO "country" ("id", "name") VALUES ('ki', 'Kikuju');
INSERT INTO "country" ("id", "name") VALUES ('kmb', 'Kimbundu');
INSERT INTO "country" ("id", "name") VALUES ('rw', 'Kinjarwanda');
INSERT INTO "country" ("id", "name") VALUES ('ky', 'Kirgiż');
INSERT INTO "country" ("id", "name") VALUES ('tlh', 'Klingon');
INSERT INTO "country" ("id", "name") VALUES ('km', 'Kmer');
INSERT INTO "country" ("id", "name") VALUES ('khi', 'Kojsan');
INSERT INTO "country" ("id", "name") VALUES ('kv', 'Komi');
INSERT INTO "country" ("id", "name") VALUES ('kg', 'Kongo');
INSERT INTO "country" ("id", "name") VALUES ('kok', 'Konkani');
INSERT INTO "country" ("id", "name") VALUES ('cop', 'Koptiku');
INSERT INTO "country" ("id", "name") VALUES ('ko', 'Korejan');
INSERT INTO "country" ("id", "name") VALUES ('kw', 'Korniku');
INSERT INTO "country" ("id", "name") VALUES ('co', 'Korsiku');
INSERT INTO "country" ("id", "name") VALUES ('kos', 'Kosrejan');
INSERT INTO "country" ("id", "name") VALUES ('kho', 'Kotaniż');
INSERT INTO "country" ("id", "name") VALUES ('kpe', 'Kpelle');
INSERT INTO "country" ("id", "name") VALUES ('crp', 'Kreoli u Piġini (Oħra)');
INSERT INTO "country" ("id", "name") VALUES ('cpf', 'Kreoli u Piġini, Bbażat fuq il-Franċiż (Oħra)');
INSERT INTO "country" ("id", "name") VALUES ('cpp', 'Kreoli u Piġini, Bbażat fuq il-Portugiż (Oħra)');
INSERT INTO "country" ("id", "name") VALUES ('cpe', 'Kreoli u Piġini, Bbażat fuq l-Ingliż (Oħra)');
INSERT INTO "country" ("id", "name") VALUES ('mus', 'Kriek');
INSERT INTO "country" ("id", "name") VALUES ('cr', 'Krij');
INSERT INTO "country" ("id", "name") VALUES ('hr', 'Kroat');
INSERT INTO "country" ("id", "name") VALUES ('kro', 'Kru');
INSERT INTO "country" ("id", "name") VALUES ('kj', 'Kuanyama');
INSERT INTO "country" ("id", "name") VALUES ('kum', 'Kumiku');
INSERT INTO "country" ("id", "name") VALUES ('ku', 'Kurdiż');
INSERT INTO "country" ("id", "name") VALUES ('kru', 'Kurusk');
INSERT INTO "country" ("id", "name") VALUES ('kut', 'Kutenaj');
INSERT INTO "country" ("id", "name") VALUES ('cus', 'Kuxtiku (Oħra)');
INSERT INTO "country" ("id", "name") VALUES ('lad', 'Ladino');
INSERT INTO "country" ("id", "name") VALUES ('lam', 'Lamba');
INSERT INTO "country" ("id", "name") VALUES ('lah', 'Landa');
INSERT INTO "country" ("id", "name") VALUES ('lo', 'Lao');
INSERT INTO "country" ("id", "name") VALUES ('la', 'Latin');
INSERT INTO "country" ("id", "name") VALUES ('lv', 'Latvjan (Lettix)');
INSERT INTO "country" ("id", "name") VALUES ('lb', 'Letżburgiż');
INSERT INTO "country" ("id", "name") VALUES ('lez', 'Leżgjan');
INSERT INTO "country" ("id", "name") VALUES ('jrb', 'Lhudi-Għarbi');
INSERT INTO "country" ("id", "name") VALUES ('jpr', 'Lhudi-Persjan');
INSERT INTO "country" ("id", "name") VALUES ('li', 'Limburgish');
INSERT INTO "country" ("id", "name") VALUES ('ln', 'Lingaljan');
INSERT INTO "country" ("id", "name") VALUES ('sgn', 'Lingwa tas-Sinjali');
INSERT INTO "country" ("id", "name") VALUES ('alg', 'Lingwi Algonqwinjani');
INSERT INTO "country" ("id", "name") VALUES ('apa', 'Lingwi Apaċi');
INSERT INTO "country" ("id", "name") VALUES ('ath', 'Lingwi Atabaskani');
INSERT INTO "country" ("id", "name") VALUES ('aus', 'Lingwi Awstraljani');
INSERT INTO "country" ("id", "name") VALUES ('bai', 'Lingwi Bamileke');
INSERT INTO "country" ("id", "name") VALUES ('cmc', 'Lingwi Ċamiki');
INSERT INTO "country" ("id", "name") VALUES ('iro', 'Lingwi Irogwjani');
INSERT INTO "country" ("id", "name") VALUES ('ypk', 'Lingwi Jupiċi');
INSERT INTO "country" ("id", "name") VALUES ('mno', 'Lingwi Manobo');
INSERT INTO "country" ("id", "name") VALUES ('nub', 'Lingwi Nubjani');
INSERT INTO "country" ("id", "name") VALUES ('mis', 'Lingwi Oħra');
INSERT INTO "country" ("id", "name") VALUES ('oto', 'Lingwi Otomjani');
INSERT INTO "country" ("id", "name") VALUES ('pra', 'Lingwi Prakriti');
INSERT INTO "country" ("id", "name") VALUES ('wen', 'Lingwi Sorbjani');
INSERT INTO "country" ("id", "name") VALUES ('sio', 'Lingwi Suwjani');
INSERT INTO "country" ("id", "name") VALUES ('mun', 'Lingwi tal-Munda');
INSERT INTO "country" ("id", "name") VALUES ('wak', 'Lingwi Wakaxani');
INSERT INTO "country" ("id", "name") VALUES ('lt', 'Litwanjan');
INSERT INTO "country" ("id", "name") VALUES ('jbo', 'Lojban');
INSERT INTO "country" ("id", "name") VALUES ('dsb', 'Lower Sorbian');
INSERT INTO "country" ("id", "name") VALUES ('loz', 'Lożi');
INSERT INTO "country" ("id", "name") VALUES ('lu', 'Luba-Katanga');
INSERT INTO "country" ("id", "name") VALUES ('lua', 'Luba-Luluwa');
INSERT INTO "country" ("id", "name") VALUES ('smj', 'Lule Sami');
INSERT INTO "country" ("id", "name") VALUES ('lun', 'Lunda');
INSERT INTO "country" ("id", "name") VALUES ('luo', 'Luwa');
INSERT INTO "country" ("id", "name") VALUES ('lui', 'Luwisinuż');
INSERT INTO "country" ("id", "name") VALUES ('lus', 'Luxaj');
INSERT INTO "country" ("id", "name") VALUES ('mk', 'Maċedonjan');
INSERT INTO "country" ("id", "name") VALUES ('mad', 'Maduriż');
INSERT INTO "country" ("id", "name") VALUES ('mag', 'Magaħi');
INSERT INTO "country" ("id", "name") VALUES ('myn', 'Majan');
INSERT INTO "country" ("id", "name") VALUES ('mai', 'Majtili');
INSERT INTO "country" ("id", "name") VALUES ('mak', 'Makasar');
INSERT INTO "country" ("id", "name") VALUES ('mg', 'Malagażi');
INSERT INTO "country" ("id", "name") VALUES ('ml', 'Malajalam');
INSERT INTO "country" ("id", "name") VALUES ('ms', 'Malajan');
INSERT INTO "country" ("id", "name") VALUES ('mt', 'Malti');
INSERT INTO "country" ("id", "name") VALUES ('mnc', 'Manċurjan');
INSERT INTO "country" ("id", "name") VALUES ('mdr', 'Mandar');
INSERT INTO "country" ("id", "name") VALUES ('man', 'Mandingwan');
INSERT INTO "country" ("id", "name") VALUES ('mni', 'Manipuri');
INSERT INTO "country" ("id", "name") VALUES ('gv', 'Manks');
INSERT INTO "country" ("id", "name") VALUES ('mi', 'Maori');
INSERT INTO "country" ("id", "name") VALUES ('mr', 'Marati');
INSERT INTO "country" ("id", "name") VALUES ('chm', 'Mari');
INSERT INTO "country" ("id", "name") VALUES ('mwr', 'Marwari');
INSERT INTO "country" ("id", "name") VALUES ('mh', 'Marxall');
INSERT INTO "country" ("id", "name") VALUES ('mas', 'Masaj');
INSERT INTO "country" ("id", "name") VALUES ('men', 'Mende');
INSERT INTO "country" ("id", "name") VALUES ('mic', 'Mikmek');
INSERT INTO "country" ("id", "name") VALUES ('min', 'Minangkabaw');
INSERT INTO "country" ("id", "name") VALUES ('mwl', 'Mirandiż');
INSERT INTO "country" ("id", "name") VALUES ('moh', 'Moħak');
INSERT INTO "country" ("id", "name") VALUES ('mdf', 'Moksha');
INSERT INTO "country" ("id", "name") VALUES ('mo', 'Moldavjan');
INSERT INTO "country" ("id", "name") VALUES ('mkh', 'Mon-Kmer (Oħra)');
INSERT INTO "country" ("id", "name") VALUES ('lol', 'Mongo');
INSERT INTO "country" ("id", "name") VALUES ('mn', 'Mongoljan');
INSERT INTO "country" ("id", "name") VALUES ('mos', 'Mossi');
INSERT INTO "country" ("id", "name") VALUES ('nah', 'Naħwatil');
INSERT INTO "country" ("id", "name") VALUES ('nv', 'Navaħo');
INSERT INTO "country" ("id", "name") VALUES ('na', 'Nawuru');
INSERT INTO "country" ("id", "name") VALUES ('nr', 'Ndebele, t’Isfel');
INSERT INTO "country" ("id", "name") VALUES ('nd', 'Ndebele, ta’ Fuq');
INSERT INTO "country" ("id", "name") VALUES ('ng', 'Ndonga');
INSERT INTO "country" ("id", "name") VALUES ('nap', 'Neapolitan');
INSERT INTO "country" ("id", "name") VALUES ('ne', 'Nepaliż');
INSERT INTO "country" ("id", "name") VALUES ('new', 'Newari');
INSERT INTO "country" ("id", "name") VALUES ('nic', 'Niġerjan - Kordofanjan');
INSERT INTO "country" ("id", "name") VALUES ('nia', 'Nijas');
INSERT INTO "country" ("id", "name") VALUES ('niu', 'Nijuwejan');
INSERT INTO "country" ("id", "name") VALUES ('ssa', 'Nilo-Saħaram');
INSERT INTO "country" ("id", "name") VALUES ('nn', 'Ninorsk Norveġiż');
INSERT INTO "country" ("id", "name") VALUES ('nym', 'Njamweżi');
INSERT INTO "country" ("id", "name") VALUES ('nyo', 'Njoro');
INSERT INTO "country" ("id", "name") VALUES ('nog', 'Nogai');
INSERT INTO "country" ("id", "name") VALUES ('no', 'Norveġiż');
INSERT INTO "country" ("id", "name") VALUES ('nyn', 'Nyankole');
INSERT INTO "country" ("id", "name") VALUES ('nzi', 'Nżima');
INSERT INTO "country" ("id", "name") VALUES ('oc', 'Oċċitan');
INSERT INTO "country" ("id", "name") VALUES ('oj', 'Oġibwa');
INSERT INTO "country" ("id", "name") VALUES ('nl', 'Olandiż');
INSERT INTO "country" ("id", "name") VALUES ('dum', 'Olandiż, Medjevali');
INSERT INTO "country" ("id", "name") VALUES ('or', 'Orija');
INSERT INTO "country" ("id", "name") VALUES ('om', 'Oromo (Afan)');
INSERT INTO "country" ("id", "name") VALUES ('osa', 'Osaġjan');
INSERT INTO "country" ("id", "name") VALUES ('os', 'Ossettiku');
INSERT INTO "country" ("id", "name") VALUES ('pal', 'Paħlavi');
INSERT INTO "country" ("id", "name") VALUES ('pau', 'Palawjan');
INSERT INTO "country" ("id", "name") VALUES ('pi', 'Pali');
INSERT INTO "country" ("id", "name") VALUES ('pam', 'Pampamga');
INSERT INTO "country" ("id", "name") VALUES ('pag', 'Pangasinjan');
INSERT INTO "country" ("id", "name") VALUES ('pap', 'Papjamento');
INSERT INTO "country" ("id", "name") VALUES ('paa', 'Papwan (Oħra)');
INSERT INTO "country" ("id", "name") VALUES ('ps', 'Paxtun');
INSERT INTO "country" ("id", "name") VALUES ('fa', 'Persjan');
INSERT INTO "country" ("id", "name") VALUES ('peo', 'Persjan Antik');
INSERT INTO "country" ("id", "name") VALUES ('pl', 'Pollakk');
INSERT INTO "country" ("id", "name") VALUES ('pon', 'Ponpejan');
INSERT INTO "country" ("id", "name") VALUES ('pt', 'Portugiż');
INSERT INTO "country" ("id", "name") VALUES ('pro', 'Provenzal, Antik (sa l-1500)');
INSERT INTO "country" ("id", "name") VALUES ('pa', 'Punġabi');
INSERT INTO "country" ("id", "name") VALUES ('raj', 'Raġastani');
INSERT INTO "country" ("id", "name") VALUES ('rap', 'Rapanwi');
INSERT INTO "country" ("id", "name") VALUES ('rar', 'Rarotongani');
INSERT INTO "country" ("id", "name") VALUES ('rm', 'Reto-Romanz');
INSERT INTO "country" ("id", "name") VALUES ('roa', 'Romanz (Oħra)');
INSERT INTO "country" ("id", "name") VALUES ('ro', 'Rumen');
INSERT INTO "country" ("id", "name") VALUES ('rn', 'Rundi');
INSERT INTO "country" ("id", "name") VALUES ('ru', 'Russu');
INSERT INTO "country" ("id", "name") VALUES ('sal', 'Salixan');
INSERT INTO "country" ("id", "name") VALUES ('smi', 'Sami languages (Other)');
INSERT INTO "country" ("id", "name") VALUES ('se', 'Sami ta’ Fuq');
INSERT INTO "country" ("id", "name") VALUES ('sm', 'Samojan');
INSERT INTO "country" ("id", "name") VALUES ('sam', 'Samritan');
INSERT INTO "country" ("id", "name") VALUES ('sad', 'Sandawe');
INSERT INTO "country" ("id", "name") VALUES ('sg', 'Sango');
INSERT INTO "country" ("id", "name") VALUES ('sa', 'Sanskrit');
INSERT INTO "country" ("id", "name") VALUES ('sat', 'Santali');
INSERT INTO "country" ("id", "name") VALUES ('sc', 'Sardinjan');
INSERT INTO "country" ("id", "name") VALUES ('sas', 'Saska');
INSERT INTO "country" ("id", "name") VALUES ('sel', 'Selkup');
INSERT INTO "country" ("id", "name") VALUES ('sem', 'Semitiku');
INSERT INTO "country" ("id", "name") VALUES ('sr', 'Serb');
INSERT INTO "country" ("id", "name") VALUES ('sh', 'Serbo-Kroat');
INSERT INTO "country" ("id", "name") VALUES ('srr', 'Serer');
INSERT INTO "country" ("id", "name") VALUES ('ceb', 'Sibwano');
INSERT INTO "country" ("id", "name") VALUES ('ii', 'Sichuan Yi');
INSERT INTO "country" ("id", "name") VALUES ('sid', 'Sidamo');
INSERT INTO "country" ("id", "name") VALUES ('bla', 'Siksika');
INSERT INTO "country" ("id", "name") VALUES ('sd', 'Sindi');
INSERT INTO "country" ("id", "name") VALUES ('si', 'Sinħaliż');
INSERT INTO "country" ("id", "name") VALUES ('sit', 'Sino-Tibetjani (Oħra)');
INSERT INTO "country" ("id", "name") VALUES ('syr', 'Sirjan');
INSERT INTO "country" ("id", "name") VALUES ('non', 'Skandinav, Antik');
INSERT INTO "country" ("id", "name") VALUES ('sco', 'Skoċċiż');
INSERT INTO "country" ("id", "name") VALUES ('sms', 'Skolt Sami');
INSERT INTO "country" ("id", "name") VALUES ('den', 'Slav');
INSERT INTO "country" ("id", "name") VALUES ('sla', 'Slavic (Other)');
INSERT INTO "country" ("id", "name") VALUES ('cu', 'Slaviku tal-Knisja');
INSERT INTO "country" ("id", "name") VALUES ('sk', 'Slovakk');
INSERT INTO "country" ("id", "name") VALUES ('sl', 'Sloven');
INSERT INTO "country" ("id", "name") VALUES ('sog', 'Sogdien');
INSERT INTO "country" ("id", "name") VALUES ('so', 'Somali');
INSERT INTO "country" ("id", "name") VALUES ('son', 'Songaj');
INSERT INTO "country" ("id", "name") VALUES ('snk', 'Soninke');
INSERT INTO "country" ("id", "name") VALUES ('st', 'Soto, t’Isfel');
INSERT INTO "country" ("id", "name") VALUES ('nso', 'Soto, ta’ Fuq');
INSERT INTO "country" ("id", "name") VALUES ('sma', 'Southern Sami');
INSERT INTO "country" ("id", "name") VALUES ('es', 'Spanjol');
INSERT INTO "country" ("id", "name") VALUES ('suk', 'Sukuma');
INSERT INTO "country" ("id", "name") VALUES ('sux', 'Sumerjan');
INSERT INTO "country" ("id", "name") VALUES ('su', 'Sundaniż');
INSERT INTO "country" ("id", "name") VALUES ('sus', 'Susu');
INSERT INTO "country" ("id", "name") VALUES ('sv', 'Svediż');
INSERT INTO "country" ("id", "name") VALUES ('sw', 'Swaħili');
INSERT INTO "country" ("id", "name") VALUES ('ss', 'Swati');
INSERT INTO "country" ("id", "name") VALUES ('tg', 'Taġik');
INSERT INTO "country" ("id", "name") VALUES ('tl', 'Tagalog');
INSERT INTO "country" ("id", "name") VALUES ('ty', 'Taħitjan');
INSERT INTO "country" ("id", "name") VALUES ('tai', 'Tai (Oħra)');
INSERT INTO "country" ("id", "name") VALUES ('th', 'Tajlandiż');
INSERT INTO "country" ("id", "name") VALUES ('it', 'Taljan');
INSERT INTO "country" ("id", "name") VALUES ('tmh', 'Tamaxek');
INSERT INTO "country" ("id", "name") VALUES ('ta', 'Tamil');
INSERT INTO "country" ("id", "name") VALUES ('tt', 'Tatar');
INSERT INTO "country" ("id", "name") VALUES ('te', 'Telugu');
INSERT INTO "country" ("id", "name") VALUES ('ter', 'Tereno');
INSERT INTO "country" ("id", "name") VALUES ('tet', 'Tetum');
INSERT INTO "country" ("id", "name") VALUES ('bo', 'Tibetjan');
INSERT INTO "country" ("id", "name") VALUES ('tig', 'Tigre');
INSERT INTO "country" ("id", "name") VALUES ('ti', 'Tigrinja');
INSERT INTO "country" ("id", "name") VALUES ('tem', 'Timne');
INSERT INTO "country" ("id", "name") VALUES ('tiv', 'Tiv');
INSERT INTO "country" ("id", "name") VALUES ('tli', 'Tlingit');
INSERT INTO "country" ("id", "name") VALUES ('tpi', 'Tok Pisin');
INSERT INTO "country" ("id", "name") VALUES ('tkl', 'Tokelau');
INSERT INTO "country" ("id", "name") VALUES ('tog', 'Tonga (Njasa)');
INSERT INTO "country" ("id", "name") VALUES ('to', 'Tongan (Gżejjer ta’ Tonga)');
INSERT INTO "country" ("id", "name") VALUES ('tr', 'Tork');
INSERT INTO "country" ("id", "name") VALUES ('ota', 'Tork (Imperu Ottoman)');
INSERT INTO "country" ("id", "name") VALUES ('ts', 'Tsonga');
INSERT INTO "country" ("id", "name") VALUES ('tum', 'Tumbuka');
INSERT INTO "country" ("id", "name") VALUES ('tup', 'Tupi languages');
INSERT INTO "country" ("id", "name") VALUES ('tk', 'Turkmeni');
INSERT INTO "country" ("id", "name") VALUES ('tvl', 'Tuvalu');
INSERT INTO "country" ("id", "name") VALUES ('tyv', 'Tuvinjan');
INSERT INTO "country" ("id", "name") VALUES ('tw', 'Twi');
INSERT INTO "country" ("id", "name") VALUES ('udm', 'Udmurt');
INSERT INTO "country" ("id", "name") VALUES ('uga', 'Ugaritiku');
INSERT INTO "country" ("id", "name") VALUES ('uk', 'Ukranjan');
INSERT INTO "country" ("id", "name") VALUES ('umb', 'Umbundu');
INSERT INTO "country" ("id", "name") VALUES ('hu', 'Ungeriż');
INSERT INTO "country" ("id", "name") VALUES ('hsb', 'Upper Sorbian');
INSERT INTO "country" ("id", "name") VALUES ('ur', 'Urdu');
INSERT INTO "country" ("id", "name") VALUES ('uz', 'Użbek');
INSERT INTO "country" ("id", "name") VALUES ('vai', 'Vai');
INSERT INTO "country" ("id", "name") VALUES ('ve', 'Venda');
INSERT INTO "country" ("id", "name") VALUES ('vi', 'Vjetnamiż');
INSERT INTO "country" ("id", "name") VALUES ('vo', 'Volapuk');
INSERT INTO "country" ("id", "name") VALUES ('vot', 'Votik');
INSERT INTO "country" ("id", "name") VALUES ('wal', 'Walamo');
INSERT INTO "country" ("id", "name") VALUES ('wa', 'Walloon');
INSERT INTO "country" ("id", "name") VALUES ('war', 'Waraj');
INSERT INTO "country" ("id", "name") VALUES ('was', 'Waxo');
INSERT INTO "country" ("id", "name") VALUES ('cy', 'Welx');
INSERT INTO "country" ("id", "name") VALUES ('ug', 'Wigur');
INSERT INTO "country" ("id", "name") VALUES ('wo', 'Wolof');
INSERT INTO "country" ("id", "name") VALUES ('chy', 'Xajenn');
INSERT INTO "country" ("id", "name") VALUES ('shn', 'Xan');
INSERT INTO "country" ("id", "name") VALUES ('sn', 'Xona');
INSERT INTO "country" ("id", "name") VALUES ('znd', 'Żande');
INSERT INTO "country" ("id", "name") VALUES ('zap', 'Żapotek');
INSERT INTO "country" ("id", "name") VALUES ('zen', 'Żenaga');
INSERT INTO "country" ("id", "name") VALUES ('rom', 'Żingaru');
INSERT INTO "country" ("id", "name") VALUES ('zu', 'Żulu');
INSERT INTO "country" ("id", "name") VALUES ('zun', 'Żuni');
INSERT INTO "country" ("id", "name") VALUES ('za', 'Żwang');
INSERT INTO "country" ("id", "name") VALUES ('tsi', 'Zimxjan');
INSERT INTO "country" ("id", "name") VALUES ('tn', 'Zwana');
