CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('ab', 'Abkasies');
INSERT INTO "country" ("id", "name") VALUES ('af', 'Afrikaans');
INSERT INTO "country" ("id", "name") VALUES ('ak', 'Akan');
INSERT INTO "country" ("id", "name") VALUES ('sq', 'Albanees');
INSERT INTO "country" ("id", "name") VALUES ('en_US', 'Amerikaanse Engels');
INSERT INTO "country" ("id", "name") VALUES ('am', 'Amharies');
INSERT INTO "country" ("id", "name") VALUES ('afa', 'Ander Afro-Asiaties');
INSERT INTO "country" ("id", "name") VALUES ('egy', 'Antieke Egipties');
INSERT INTO "country" ("id", "name") VALUES ('grc', 'Antieke Grieks');
INSERT INTO "country" ("id", "name") VALUES ('ar', 'Arabies');
INSERT INTO "country" ("id", "name") VALUES ('arc', 'Aramees');
INSERT INTO "country" ("id", "name") VALUES ('hy', 'Armeens');
INSERT INTO "country" ("id", "name") VALUES ('as', 'Assamees');
INSERT INTO "country" ("id", "name") VALUES ('en_AU', 'Australiese Engels');
INSERT INTO "country" ("id", "name") VALUES ('ay', 'Aymara');
INSERT INTO "country" ("id", "name") VALUES ('az', 'Azerbeidjaans');
INSERT INTO "country" ("id", "name") VALUES ('eu', 'Baskies');
INSERT INTO "country" ("id", "name") VALUES ('bn', 'Bengaals');
INSERT INTO "country" ("id", "name") VALUES ('my', 'Birmaans');
INSERT INTO "country" ("id", "name") VALUES ('bs', 'Bosnies');
INSERT INTO "country" ("id", "name") VALUES ('pt_BR', 'Brasiliaanse Portugees');
INSERT INTO "country" ("id", "name") VALUES ('en_GB', 'Britse Engels');
INSERT INTO "country" ("id", "name") VALUES ('bg', 'Bulgaars');
INSERT INTO "country" ("id", "name") VALUES ('da', 'Deens');
INSERT INTO "country" ("id", "name") VALUES ('dv', 'Divehi');
INSERT INTO "country" ("id", "name") VALUES ('de', 'Duits');
INSERT INTO "country" ("id", "name") VALUES ('dz', 'Dzongkha');
INSERT INTO "country" ("id", "name") VALUES ('efi', 'Efik');
INSERT INTO "country" ("id", "name") VALUES ('en', 'Engels');
INSERT INTO "country" ("id", "name") VALUES ('eo', 'Esperanto');
INSERT INTO "country" ("id", "name") VALUES ('et', 'Estnies');
INSERT INTO "country" ("id", "name") VALUES ('fo', 'Faroees');
INSERT INTO "country" ("id", "name") VALUES ('fj', 'Fidjiaans');
INSERT INTO "country" ("id", "name") VALUES ('fil', 'Filippyns');
INSERT INTO "country" ("id", "name") VALUES ('fi', 'Fins');
INSERT INTO "country" ("id", "name") VALUES ('fr', 'Frans');
INSERT INTO "country" ("id", "name") VALUES ('gl', 'Galisies');
INSERT INTO "country" ("id", "name") VALUES ('zxx', 'Geen linguistiese inhoud');
INSERT INTO "country" ("id", "name") VALUES ('ka', 'Georgies');
INSERT INTO "country" ("id", "name") VALUES ('gem', 'Germaanse taal');
INSERT INTO "country" ("id", "name") VALUES ('got', 'Goties');
INSERT INTO "country" ("id", "name") VALUES ('el', 'Grieks');
INSERT INTO "country" ("id", "name") VALUES ('gn', 'Guarani');
INSERT INTO "country" ("id", "name") VALUES ('gu', 'Gudjarati');
INSERT INTO "country" ("id", "name") VALUES ('ht', 'Haïtiaans');
INSERT INTO "country" ("id", "name") VALUES ('ha', 'Hausa');
INSERT INTO "country" ("id", "name") VALUES ('haw', 'Hawaies');
INSERT INTO "country" ("id", "name") VALUES ('he', 'Hebreeus');
INSERT INTO "country" ("id", "name") VALUES ('hi', 'Hindi');
INSERT INTO "country" ("id", "name") VALUES ('hu', 'Hongaars');
INSERT INTO "country" ("id", "name") VALUES ('pt_PT', 'Iberiese Portugees');
INSERT INTO "country" ("id", "name") VALUES ('es_ES', 'Iberiese Spaans');
INSERT INTO "country" ("id", "name") VALUES ('ga', 'Iers');
INSERT INTO "country" ("id", "name") VALUES ('ig', 'Igbo');
INSERT INTO "country" ("id", "name") VALUES ('ine', 'Indo-Europese taal');
INSERT INTO "country" ("id", "name") VALUES ('id', 'Indonesies');
INSERT INTO "country" ("id", "name") VALUES ('it', 'Italiaans');
INSERT INTO "country" ("id", "name") VALUES ('ja', 'Japannees');
INSERT INTO "country" ("id", "name") VALUES ('jv', 'Javaans');
INSERT INTO "country" ("id", "name") VALUES ('en_CA', 'Kanadese Engels');
INSERT INTO "country" ("id", "name") VALUES ('fr_CA', 'Kanadese Frans');
INSERT INTO "country" ("id", "name") VALUES ('kn', 'Kannada');
INSERT INTO "country" ("id", "name") VALUES ('ks', 'Kasjmirs');
INSERT INTO "country" ("id", "name") VALUES ('ca', 'Katalaans');
INSERT INTO "country" ("id", "name") VALUES ('kk', 'Kazak');
INSERT INTO "country" ("id", "name") VALUES ('cel', 'Keltiese taal');
INSERT INTO "country" ("id", "name") VALUES ('km', 'Khmer');
INSERT INTO "country" ("id", "name") VALUES ('ky', 'Kirgisies');
INSERT INTO "country" ("id", "name") VALUES ('ku', 'Koerdies');
INSERT INTO "country" ("id", "name") VALUES ('ko', 'Koreaans');
INSERT INTO "country" ("id", "name") VALUES ('hr', 'Kroaties');
INSERT INTO "country" ("id", "name") VALUES ('art', 'Kunsmatige taal');
INSERT INTO "country" ("id", "name") VALUES ('lo', 'Lao');
INSERT INTO "country" ("id", "name") VALUES ('la', 'Latyn');
INSERT INTO "country" ("id", "name") VALUES ('es_419', 'Latyns-Amerikaanse Spaans');
INSERT INTO "country" ("id", "name") VALUES ('lv', 'Letties');
INSERT INTO "country" ("id", "name") VALUES ('ln', 'Lingaals');
INSERT INTO "country" ("id", "name") VALUES ('lt', 'Litaus');
INSERT INTO "country" ("id", "name") VALUES ('lb', 'Luxemburgs');
INSERT INTO "country" ("id", "name") VALUES ('ml', 'Malabaars');
INSERT INTO "country" ("id", "name") VALUES ('ms', 'Maleisies');
INSERT INTO "country" ("id", "name") VALUES ('mg', 'Malgassies');
INSERT INTO "country" ("id", "name") VALUES ('mt', 'Maltees');
INSERT INTO "country" ("id", "name") VALUES ('mi', 'Maori');
INSERT INTO "country" ("id", "name") VALUES ('mr', 'Marathi');
INSERT INTO "country" ("id", "name") VALUES ('mk', 'Masedonies');
INSERT INTO "country" ("id", "name") VALUES ('mn', 'Mongools');
INSERT INTO "country" ("id", "name") VALUES ('nl', 'Nederlands');
INSERT INTO "country" ("id", "name") VALUES ('ne', 'Nepalees');
INSERT INTO "country" ("id", "name") VALUES ('nd', 'Noord-Ndebele');
INSERT INTO "country" ("id", "name") VALUES ('nso', 'Noord-Sotho');
INSERT INTO "country" ("id", "name") VALUES ('se', 'Noordelike Sami');
INSERT INTO "country" ("id", "name") VALUES ('nb', 'Noorse Bokmål');
INSERT INTO "country" ("id", "name") VALUES ('nn', 'Noorweegse Nynorsk');
INSERT INTO "country" ("id", "name") VALUES ('ny', 'Nyanja');
INSERT INTO "country" ("id", "name") VALUES ('uk', 'Oekraïens');
INSERT INTO "country" ("id", "name") VALUES ('ur', 'Oerdoe');
INSERT INTO "country" ("id", "name") VALUES ('uz', 'Oezbeeks');
INSERT INTO "country" ("id", "name") VALUES ('und', 'Onbekende of ongeldige taal');
INSERT INTO "country" ("id", "name") VALUES ('de_AT', 'Oostenrykse Duits');
INSERT INTO "country" ("id", "name") VALUES ('or', 'Oriya');
INSERT INTO "country" ("id", "name") VALUES ('os', 'Osseties');
INSERT INTO "country" ("id", "name") VALUES ('pa', 'Pandjabi');
INSERT INTO "country" ("id", "name") VALUES ('ps', 'Pasjto');
INSERT INTO "country" ("id", "name") VALUES ('fa', 'Persies');
INSERT INTO "country" ("id", "name") VALUES ('pl', 'Pools');
INSERT INTO "country" ("id", "name") VALUES ('pt', 'Portugees');
INSERT INTO "country" ("id", "name") VALUES ('qu', 'Quechua');
INSERT INTO "country" ("id", "name") VALUES ('rm', 'Reto-Romaans');
INSERT INTO "country" ("id", "name") VALUES ('ro', 'Roemeens');
INSERT INTO "country" ("id", "name") VALUES ('rn', 'Rundi');
INSERT INTO "country" ("id", "name") VALUES ('ru', 'Russies');
INSERT INTO "country" ("id", "name") VALUES ('rw', 'Rwandees');
INSERT INTO "country" ("id", "name") VALUES ('sm', 'Samoaans');
INSERT INTO "country" ("id", "name") VALUES ('sg', 'Sango');
INSERT INTO "country" ("id", "name") VALUES ('sa', 'Sanskrit');
INSERT INTO "country" ("id", "name") VALUES ('sr', 'Serwies');
INSERT INTO "country" ("id", "name") VALUES ('sn', 'Shona');
INSERT INTO "country" ("id", "name") VALUES ('sd', 'Sindhi');
INSERT INTO "country" ("id", "name") VALUES ('si', 'Sinhala');
INSERT INTO "country" ("id", "name") VALUES ('zh', 'Sjinees');
INSERT INTO "country" ("id", "name") VALUES ('gd', 'Skotse Gallies');
INSERT INTO "country" ("id", "name") VALUES ('sla', 'Slawiese taal');
INSERT INTO "country" ("id", "name") VALUES ('sk', 'Slowaaks');
INSERT INTO "country" ("id", "name") VALUES ('sl', 'Sloweens');
INSERT INTO "country" ("id", "name") VALUES ('so', 'Somalies');
INSERT INTO "country" ("id", "name") VALUES ('es', 'Spaans');
INSERT INTO "country" ("id", "name") VALUES ('nr', 'Suid-Ndebele');
INSERT INTO "country" ("id", "name") VALUES ('st', 'Suid-Sotho');
INSERT INTO "country" ("id", "name") VALUES ('su', 'Sundanees');
INSERT INTO "country" ("id", "name") VALUES ('sw', 'Swahili');
INSERT INTO "country" ("id", "name") VALUES ('ss', 'Swazi');
INSERT INTO "country" ("id", "name") VALUES ('sv', 'Sweeds');
INSERT INTO "country" ("id", "name") VALUES ('gsw', 'Switserse Duits');
INSERT INTO "country" ("id", "name") VALUES ('fr_CH', 'Switserse Frans');
INSERT INTO "country" ("id", "name") VALUES ('de_CH', 'Switserse hoog-Duits');
INSERT INTO "country" ("id", "name") VALUES ('tg', 'Tadjik');
INSERT INTO "country" ("id", "name") VALUES ('ty', 'Tahities');
INSERT INTO "country" ("id", "name") VALUES ('ta', 'Tamil');
INSERT INTO "country" ("id", "name") VALUES ('tt', 'Tataars');
INSERT INTO "country" ("id", "name") VALUES ('te', 'Telugu');
INSERT INTO "country" ("id", "name") VALUES ('tet', 'Tetum');
INSERT INTO "country" ("id", "name") VALUES ('th', 'Thais');
INSERT INTO "country" ("id", "name") VALUES ('bo', 'Tibettaans');
INSERT INTO "country" ("id", "name") VALUES ('ti', 'Tigrinya');
INSERT INTO "country" ("id", "name") VALUES ('tpi', 'Tok Pisin');
INSERT INTO "country" ("id", "name") VALUES ('to', 'Tonga');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hant', 'Tradisionele Chinees');
INSERT INTO "country" ("id", "name") VALUES ('cs', 'Tsjeggies');
INSERT INTO "country" ("id", "name") VALUES ('ts', 'Tsonga');
INSERT INTO "country" ("id", "name") VALUES ('tn', 'Tswana');
INSERT INTO "country" ("id", "name") VALUES ('tk', 'Turkmeens');
INSERT INTO "country" ("id", "name") VALUES ('tr', 'Turks');
INSERT INTO "country" ("id", "name") VALUES ('ug', 'Uighur');
INSERT INTO "country" ("id", "name") VALUES ('ve', 'Venda');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hans', 'Vereenvoudigde Chinees');
INSERT INTO "country" ("id", "name") VALUES ('vi', 'Viëtnamees');
INSERT INTO "country" ("id", "name") VALUES ('nl_BE', 'Vlaams');
INSERT INTO "country" ("id", "name") VALUES ('cy', 'Wallies');
INSERT INTO "country" ("id", "name") VALUES ('fy', 'Wes-Fries');
INSERT INTO "country" ("id", "name") VALUES ('be', 'Wit-Russies');
INSERT INTO "country" ("id", "name") VALUES ('wo', 'Wolof');
INSERT INTO "country" ("id", "name") VALUES ('xh', 'Xhosa');
INSERT INTO "country" ("id", "name") VALUES ('yo', 'Yoruba');
INSERT INTO "country" ("id", "name") VALUES ('is', 'Yslands');
INSERT INTO "country" ("id", "name") VALUES ('zu', 'Zoeloe');
