CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('el', 'Helene');
INSERT INTO [country] ([id], [name]) VALUES ('he', 'Hebera');
INSERT INTO [country] ([id], [name]) VALUES ('nl', 'Hōlani');
INSERT INTO [country] ([id], [name]) VALUES ('sm', 'Kāmoa');
INSERT INTO [country] ([id], [name]) VALUES ('de', 'Kelemānia');
INSERT INTO [country] ([id], [name]) VALUES ('da', 'Kenemaka');
INSERT INTO [country] ([id], [name]) VALUES ('ja', 'Kepanī');
INSERT INTO [country] ([id], [name]) VALUES ('ko', 'Kōlea');
INSERT INTO [country] ([id], [name]) VALUES ('sv', 'Kuekene');
INSERT INTO [country] ([id], [name]) VALUES ('fr_CH', 'Kuikilani');
INSERT INTO [country] ([id], [name]) VALUES ('gsw', 'Kuikilani Kelemānia');
INSERT INTO [country] ([id], [name]) VALUES ('la', 'Lākina');
INSERT INTO [country] ([id], [name]) VALUES ('ru', 'Lūkia');
INSERT INTO [country] ([id], [name]) VALUES ('mi', 'Māori');
INSERT INTO [country] ([id], [name]) VALUES ('zh', 'Pākē');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hans', 'Pākē Hoʻomaʻalahi ʻia');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hant', 'Pākē Kuʻuna');
INSERT INTO [country] ([id], [name]) VALUES ('fr', 'Palani');
INSERT INTO [country] ([id], [name]) VALUES ('fr_CA', 'Palani Kanakā');
INSERT INTO [country] ([id], [name]) VALUES ('es', 'Paniolo');
INSERT INTO [country] ([id], [name]) VALUES ('en_CA', 'Pelekāne Kanakā');
INSERT INTO [country] ([id], [name]) VALUES ('en_AU', 'Pelekāne Nū Hōlani');
INSERT INTO [country] ([id], [name]) VALUES ('en', 'Pelekānia');
INSERT INTO [country] ([id], [name]) VALUES ('en_GB', 'Pelekānia Pekekāne');
INSERT INTO [country] ([id], [name]) VALUES ('en_US', 'Pelekānia ʻAmelika');
INSERT INTO [country] ([id], [name]) VALUES ('fj', 'Pīkī');
INSERT INTO [country] ([id], [name]) VALUES ('ty', 'Polapola');
INSERT INTO [country] ([id], [name]) VALUES ('pt', 'Pukikī');
INSERT INTO [country] ([id], [name]) VALUES ('pt_BR', 'Pukikī Palakila');
INSERT INTO [country] ([id], [name]) VALUES ('cy', 'Wale');
INSERT INTO [country] ([id], [name]) VALUES ('vi', 'Wiekanama');
INSERT INTO [country] ([id], [name]) VALUES ('ga', 'ʻAiliki');
INSERT INTO [country] ([id], [name]) VALUES ('ar', 'ʻAlapia');
INSERT INTO [country] ([id], [name]) VALUES ('it', 'ʻĪkālia');
INSERT INTO [country] ([id], [name]) VALUES ('und', 'ʻIke ʻole ‘ia a kūpono ʻole paha ka ʻōlelo');
INSERT INTO [country] ([id], [name]) VALUES ('haw', 'ʻŌlelo Hawaiʻi');
INSERT INTO [country] ([id], [name]) VALUES ('to', 'Tonga');
