CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('ab', 'abchaziska');
INSERT INTO `country` (`id`, `name`) VALUES ('ace', 'acehnesiska');
INSERT INTO `country` (`id`, `name`) VALUES ('ach', 'acholi');
INSERT INTO `country` (`id`, `name`) VALUES ('ada', 'adangme');
INSERT INTO `country` (`id`, `name`) VALUES ('ady', 'adygeiska');
INSERT INTO `country` (`id`, `name`) VALUES ('aa', 'afar');
INSERT INTO `country` (`id`, `name`) VALUES ('ps', 'afghanska');
INSERT INTO `country` (`id`, `name`) VALUES ('afh', 'afrihili');
INSERT INTO `country` (`id`, `name`) VALUES ('af', 'afrikaans');
INSERT INTO `country` (`id`, `name`) VALUES ('afa', 'afroasiatiskt språk');
INSERT INTO `country` (`id`, `name`) VALUES ('agq', 'aghem');
INSERT INTO `country` (`id`, `name`) VALUES ('ain', 'ainu');
INSERT INTO `country` (`id`, `name`) VALUES ('ak', 'akan');
INSERT INTO `country` (`id`, `name`) VALUES ('akk', 'akkadiska');
INSERT INTO `country` (`id`, `name`) VALUES ('sq', 'albanska');
INSERT INTO `country` (`id`, `name`) VALUES ('ale', 'aleutiska');
INSERT INTO `country` (`id`, `name`) VALUES ('alg', 'algonkinskt språk');
INSERT INTO `country` (`id`, `name`) VALUES ('tut', 'altaiskt språk');
INSERT INTO `country` (`id`, `name`) VALUES ('en_US', 'amerikansk engelska');
INSERT INTO `country` (`id`, `name`) VALUES ('am', 'amhariska');
INSERT INTO `country` (`id`, `name`) VALUES ('anp', 'angika');
INSERT INTO `country` (`id`, `name`) VALUES ('mis', 'annat språk');
INSERT INTO `country` (`id`, `name`) VALUES ('apa', 'apachespråk');
INSERT INTO `country` (`id`, `name`) VALUES ('ar', 'arabiska');
INSERT INTO `country` (`id`, `name`) VALUES ('an', 'aragonesiska');
INSERT INTO `country` (`id`, `name`) VALUES ('arc', 'arameiska');
INSERT INTO `country` (`id`, `name`) VALUES ('arp', 'arapaho');
INSERT INTO `country` (`id`, `name`) VALUES ('arn', 'araukanska');
INSERT INTO `country` (`id`, `name`) VALUES ('arw', 'arawakiska');
INSERT INTO `country` (`id`, `name`) VALUES ('hy', 'armeniska');
INSERT INTO `country` (`id`, `name`) VALUES ('rup', 'arumänska');
INSERT INTO `country` (`id`, `name`) VALUES ('as', 'assamesiska');
INSERT INTO `country` (`id`, `name`) VALUES ('ast', 'asturiska');
INSERT INTO `country` (`id`, `name`) VALUES ('asa', 'asu');
INSERT INTO `country` (`id`, `name`) VALUES ('ath', 'athapaskiskt språk');
INSERT INTO `country` (`id`, `name`) VALUES ('cch', 'atsam');
INSERT INTO `country` (`id`, `name`) VALUES ('en_AU', 'australisk engelska');
INSERT INTO `country` (`id`, `name`) VALUES ('aus', 'australiskt språk');
INSERT INTO `country` (`id`, `name`) VALUES ('map', 'austronesiskt språk');
INSERT INTO `country` (`id`, `name`) VALUES ('av', 'avariska');
INSERT INTO `country` (`id`, `name`) VALUES ('ae', 'avestiska');
INSERT INTO `country` (`id`, `name`) VALUES ('awa', 'awadhi');
INSERT INTO `country` (`id`, `name`) VALUES ('ay', 'aymara');
INSERT INTO `country` (`id`, `name`) VALUES ('az', 'azerbajdzjanska');
INSERT INTO `country` (`id`, `name`) VALUES ('nah', 'aztekiska');
INSERT INTO `country` (`id`, `name`) VALUES ('ksf', 'bafia');
INSERT INTO `country` (`id`, `name`) VALUES ('ban', 'balinesiska');
INSERT INTO `country` (`id`, `name`) VALUES ('bat', 'baltiskt språk');
INSERT INTO `country` (`id`, `name`) VALUES ('bal', 'baluchiska');
INSERT INTO `country` (`id`, `name`) VALUES ('bm', 'bambara');
INSERT INTO `country` (`id`, `name`) VALUES ('bai', 'bamilekespråk');
INSERT INTO `country` (`id`, `name`) VALUES ('bad', 'bandaspråk');
INSERT INTO `country` (`id`, `name`) VALUES ('bnt', 'bantuspråk');
INSERT INTO `country` (`id`, `name`) VALUES ('bas', 'basa');
INSERT INTO `country` (`id`, `name`) VALUES ('ba', 'basjkiriska');
INSERT INTO `country` (`id`, `name`) VALUES ('eu', 'baskiska');
INSERT INTO `country` (`id`, `name`) VALUES ('btk', 'batak');
INSERT INTO `country` (`id`, `name`) VALUES ('bem', 'bemba');
INSERT INTO `country` (`id`, `name`) VALUES ('bez', 'bena');
INSERT INTO `country` (`id`, `name`) VALUES ('bn', 'bengali');
INSERT INTO `country` (`id`, `name`) VALUES ('ber', 'berberspråk');
INSERT INTO `country` (`id`, `name`) VALUES ('bej', 'beyja');
INSERT INTO `country` (`id`, `name`) VALUES ('bho', 'bhojpuri');
INSERT INTO `country` (`id`, `name`) VALUES ('dz', 'bhutanesiska');
INSERT INTO `country` (`id`, `name`) VALUES ('bh', 'bihari');
INSERT INTO `country` (`id`, `name`) VALUES ('bik', 'bikol');
INSERT INTO `country` (`id`, `name`) VALUES ('bin', 'bini');
INSERT INTO `country` (`id`, `name`) VALUES ('bi', 'bislama');
INSERT INTO `country` (`id`, `name`) VALUES ('byn', 'blin');
INSERT INTO `country` (`id`, `name`) VALUES ('zbl', 'blissymboler');
INSERT INTO `country` (`id`, `name`) VALUES ('brx', 'bodo');
INSERT INTO `country` (`id`, `name`) VALUES ('bs', 'bosniska');
INSERT INTO `country` (`id`, `name`) VALUES ('bra', 'braj');
INSERT INTO `country` (`id`, `name`) VALUES ('pt_BR', 'brasiliansk portugisiska');
INSERT INTO `country` (`id`, `name`) VALUES ('br', 'bretonska');
INSERT INTO `country` (`id`, `name`) VALUES ('en_GB', 'brittisk engelska');
INSERT INTO `country` (`id`, `name`) VALUES ('bug', 'buginesiska');
INSERT INTO `country` (`id`, `name`) VALUES ('bg', 'bulgariska');
INSERT INTO `country` (`id`, `name`) VALUES ('bua', 'burjätiska');
INSERT INTO `country` (`id`, `name`) VALUES ('my', 'burmesiska');
INSERT INTO `country` (`id`, `name`) VALUES ('cad', 'caddo');
INSERT INTO `country` (`id`, `name`) VALUES ('ceb', 'cebuano');
INSERT INTO `country` (`id`, `name`) VALUES ('cai', 'centralamerikanskt indianspråk');
INSERT INTO `country` (`id`, `name`) VALUES ('chg', 'chagatai');
INSERT INTO `country` (`id`, `name`) VALUES ('cmc', 'chamispråk');
INSERT INTO `country` (`id`, `name`) VALUES ('ch', 'chamorro');
INSERT INTO `country` (`id`, `name`) VALUES ('chr', 'cherokesiska');
INSERT INTO `country` (`id`, `name`) VALUES ('chy', 'cheyenne');
INSERT INTO `country` (`id`, `name`) VALUES ('chb', 'chibcha');
INSERT INTO `country` (`id`, `name`) VALUES ('chn', 'chinook');
INSERT INTO `country` (`id`, `name`) VALUES ('chp', 'chipewyan');
INSERT INTO `country` (`id`, `name`) VALUES ('cho', 'choctaw');
INSERT INTO `country` (`id`, `name`) VALUES ('chk', 'chuukesiska');
INSERT INTO `country` (`id`, `name`) VALUES ('cr', 'cree');
INSERT INTO `country` (`id`, `name`) VALUES ('day', 'dajakiska');
INSERT INTO `country` (`id`, `name`) VALUES ('dak', 'dakota');
INSERT INTO `country` (`id`, `name`) VALUES ('da', 'danska');
INSERT INTO `country` (`id`, `name`) VALUES ('dar', 'darginska');
INSERT INTO `country` (`id`, `name`) VALUES ('del', 'delaware');
INSERT INTO `country` (`id`, `name`) VALUES ('din', 'dinka');
INSERT INTO `country` (`id`, `name`) VALUES ('dv', 'divehi');
INSERT INTO `country` (`id`, `name`) VALUES ('doi', 'dogri');
INSERT INTO `country` (`id`, `name`) VALUES ('dgr', 'dogrib');
INSERT INTO `country` (`id`, `name`) VALUES ('dra', 'dravidiskt språk');
INSERT INTO `country` (`id`, `name`) VALUES ('dua', 'duala');
INSERT INTO `country` (`id`, `name`) VALUES ('dyu', 'dyula');
INSERT INTO `country` (`id`, `name`) VALUES ('efi', 'efik');
INSERT INTO `country` (`id`, `name`) VALUES ('eka', 'ekajuk');
INSERT INTO `country` (`id`, `name`) VALUES ('elx', 'elamitiska');
INSERT INTO `country` (`id`, `name`) VALUES ('ebu', 'embu');
INSERT INTO `country` (`id`, `name`) VALUES ('smn', 'enaresamiska');
INSERT INTO `country` (`id`, `name`) VALUES ('en', 'engelska');
INSERT INTO `country` (`id`, `name`) VALUES ('cpe', 'engelskbaserat kreol- eller pidginspråk');
INSERT INTO `country` (`id`, `name`) VALUES ('myv', 'erjya');
INSERT INTO `country` (`id`, `name`) VALUES ('ypk', 'eskimåspråk');
INSERT INTO `country` (`id`, `name`) VALUES ('eo', 'esperanto');
INSERT INTO `country` (`id`, `name`) VALUES ('et', 'estniska');
INSERT INTO `country` (`id`, `name`) VALUES ('gez', 'etiopiska');
INSERT INTO `country` (`id`, `name`) VALUES ('pt_PT', 'europeisk portugisiska');
INSERT INTO `country` (`id`, `name`) VALUES ('es_ES', 'europeisk spanska');
INSERT INTO `country` (`id`, `name`) VALUES ('ee', 'ewe');
INSERT INTO `country` (`id`, `name`) VALUES ('ewo', 'ewondo');
INSERT INTO `country` (`id`, `name`) VALUES ('fan', 'fang');
INSERT INTO `country` (`id`, `name`) VALUES ('fat', 'fanti');
INSERT INTO `country` (`id`, `name`) VALUES ('phn', 'feniciska');
INSERT INTO `country` (`id`, `name`) VALUES ('fj', 'fidjianska');
INSERT INTO `country` (`id`, `name`) VALUES ('fil', 'filippinska');
INSERT INTO `country` (`id`, `name`) VALUES ('phi', 'filippinskt språk');
INSERT INTO `country` (`id`, `name`) VALUES ('fi', 'finska');
INSERT INTO `country` (`id`, `name`) VALUES ('fiu', 'finskugriskt språk');
INSERT INTO `country` (`id`, `name`) VALUES ('nl_BE', 'flamländska');
INSERT INTO `country` (`id`, `name`) VALUES ('fon', 'fonspråket');
INSERT INTO `country` (`id`, `name`) VALUES ('egy', 'fornegyptiska');
INSERT INTO `country` (`id`, `name`) VALUES ('ang', 'fornengelska');
INSERT INTO `country` (`id`, `name`) VALUES ('fro', 'fornfranska');
INSERT INTO `country` (`id`, `name`) VALUES ('grc', 'forngrekiska');
INSERT INTO `country` (`id`, `name`) VALUES ('goh', 'fornhögtyska');
INSERT INTO `country` (`id`, `name`) VALUES ('sga', 'forniriska');
INSERT INTO `country` (`id`, `name`) VALUES ('non', 'fornnordiska');
INSERT INTO `country` (`id`, `name`) VALUES ('peo', 'fornpersiska');
INSERT INTO `country` (`id`, `name`) VALUES ('pro', 'fornprovensalska');
INSERT INTO `country` (`id`, `name`) VALUES ('fr', 'franska');
INSERT INTO `country` (`id`, `name`) VALUES ('cpf', 'franskbaserat kreol- eller pidginspråk');
INSERT INTO `country` (`id`, `name`) VALUES ('fur', 'friulianska');
INSERT INTO `country` (`id`, `name`) VALUES ('ff', 'fulani');
INSERT INTO `country` (`id`, `name`) VALUES ('fo', 'färöiska');
INSERT INTO `country` (`id`, `name`) VALUES ('zh_Hans', 'förenklad kinesiska');
INSERT INTO `country` (`id`, `name`) VALUES ('gaa', 'gã');
INSERT INTO `country` (`id`, `name`) VALUES ('gl', 'galiciska');
INSERT INTO `country` (`id`, `name`) VALUES ('gay', 'gayo');
INSERT INTO `country` (`id`, `name`) VALUES ('gba', 'gbaya');
INSERT INTO `country` (`id`, `name`) VALUES ('ka', 'georgiska');
INSERT INTO `country` (`id`, `name`) VALUES ('gem', 'germanskt språk');
INSERT INTO `country` (`id`, `name`) VALUES ('gil', 'gilbertiska');
INSERT INTO `country` (`id`, `name`) VALUES ('gon', 'gondi');
INSERT INTO `country` (`id`, `name`) VALUES ('gor', 'gorontalo');
INSERT INTO `country` (`id`, `name`) VALUES ('got', 'gotiska');
INSERT INTO `country` (`id`, `name`) VALUES ('grb', 'grebo');
INSERT INTO `country` (`id`, `name`) VALUES ('el', 'grekiska');
INSERT INTO `country` (`id`, `name`) VALUES ('kl', 'grönländska');
INSERT INTO `country` (`id`, `name`) VALUES ('gn', 'guaraní');
INSERT INTO `country` (`id`, `name`) VALUES ('gu', 'gujarati');
INSERT INTO `country` (`id`, `name`) VALUES ('gwi', 'gwichin');
INSERT INTO `country` (`id`, `name`) VALUES ('hai', 'haida');
INSERT INTO `country` (`id`, `name`) VALUES ('ht', 'haitiska');
INSERT INTO `country` (`id`, `name`) VALUES ('ha', 'haussa');
INSERT INTO `country` (`id`, `name`) VALUES ('haw', 'hawaiiska');
INSERT INTO `country` (`id`, `name`) VALUES ('he', 'hebreiska');
INSERT INTO `country` (`id`, `name`) VALUES ('hz', 'herero');
INSERT INTO `country` (`id`, `name`) VALUES ('hit', 'hettitiska');
INSERT INTO `country` (`id`, `name`) VALUES ('hil', 'hiligaynon');
INSERT INTO `country` (`id`, `name`) VALUES ('him', 'himachali');
INSERT INTO `country` (`id`, `name`) VALUES ('hi', 'hindi');
INSERT INTO `country` (`id`, `name`) VALUES ('ho', 'hirimotu');
INSERT INTO `country` (`id`, `name`) VALUES ('hmn', 'hmongspråk');
INSERT INTO `country` (`id`, `name`) VALUES ('hup', 'hupa');
INSERT INTO `country` (`id`, `name`) VALUES ('gd', 'höglandsskotska');
INSERT INTO `country` (`id`, `name`) VALUES ('hsb', 'högsorbiska');
INSERT INTO `country` (`id`, `name`) VALUES ('iba', 'ibanska');
INSERT INTO `country` (`id`, `name`) VALUES ('ig', 'ibo');
INSERT INTO `country` (`id`, `name`) VALUES ('io', 'ido');
INSERT INTO `country` (`id`, `name`) VALUES ('ijo', 'ijospråket');
INSERT INTO `country` (`id`, `name`) VALUES ('ilo', 'iloko');
INSERT INTO `country` (`id`, `name`) VALUES ('inc', 'indiskt språk');
INSERT INTO `country` (`id`, `name`) VALUES ('ine', 'indoeuropeiskt språk');
INSERT INTO `country` (`id`, `name`) VALUES ('id', 'indonesiska');
INSERT INTO `country` (`id`, `name`) VALUES ('zxx', 'inget språkligt innehåll');
INSERT INTO `country` (`id`, `name`) VALUES ('inh', 'ingusjiska');
INSERT INTO `country` (`id`, `name`) VALUES ('ia', 'interlingua');
INSERT INTO `country` (`id`, `name`) VALUES ('ie', 'interlingue');
INSERT INTO `country` (`id`, `name`) VALUES ('iu', 'inuktitut');
INSERT INTO `country` (`id`, `name`) VALUES ('ik', 'inupiak');
INSERT INTO `country` (`id`, `name`) VALUES ('ira', 'iranskt språk');
INSERT INTO `country` (`id`, `name`) VALUES ('ga', 'iriska');
INSERT INTO `country` (`id`, `name`) VALUES ('iro', 'irokesiskt språk');
INSERT INTO `country` (`id`, `name`) VALUES ('is', 'isländska');
INSERT INTO `country` (`id`, `name`) VALUES ('it', 'italienska');
INSERT INTO `country` (`id`, `name`) VALUES ('sah', 'jakutiska');
INSERT INTO `country` (`id`, `name`) VALUES ('ja', 'japanska');
INSERT INTO `country` (`id`, `name`) VALUES ('yap', 'japetiska');
INSERT INTO `country` (`id`, `name`) VALUES ('jv', 'javanesiska');
INSERT INTO `country` (`id`, `name`) VALUES ('yi', 'jiddisch');
INSERT INTO `country` (`id`, `name`) VALUES ('kaj', 'jju');
INSERT INTO `country` (`id`, `name`) VALUES ('dyo', 'jola-fonyi');
INSERT INTO `country` (`id`, `name`) VALUES ('jrb', 'judisk arabiska');
INSERT INTO `country` (`id`, `name`) VALUES ('jpr', 'judisk persiska');
INSERT INTO `country` (`id`, `name`) VALUES ('kbd', 'kabardinska');
INSERT INTO `country` (`id`, `name`) VALUES ('kab', 'kabyliska');
INSERT INTO `country` (`id`, `name`) VALUES ('kac', 'kachin');
INSERT INTO `country` (`id`, `name`) VALUES ('xal', 'kalmuckiska');
INSERT INTO `country` (`id`, `name`) VALUES ('kam', 'kamba');
INSERT INTO `country` (`id`, `name`) VALUES ('km', 'kambodjanska');
INSERT INTO `country` (`id`, `name`) VALUES ('en_CA', 'kanadensisk engelska');
INSERT INTO `country` (`id`, `name`) VALUES ('fr_CA', 'kanadensisk franska');
INSERT INTO `country` (`id`, `name`) VALUES ('kn', 'kannada');
INSERT INTO `country` (`id`, `name`) VALUES ('yue', 'kantonesiska');
INSERT INTO `country` (`id`, `name`) VALUES ('kr', 'kanuri');
INSERT INTO `country` (`id`, `name`) VALUES ('kea', 'kapverdiska');
INSERT INTO `country` (`id`, `name`) VALUES ('krc', 'karachay-balkar');
INSERT INTO `country` (`id`, `name`) VALUES ('kaa', 'karakalpakiska');
INSERT INTO `country` (`id`, `name`) VALUES ('krl', 'karelska');
INSERT INTO `country` (`id`, `name`) VALUES ('kar', 'karenska');
INSERT INTO `country` (`id`, `name`) VALUES ('car', 'karibiska');
INSERT INTO `country` (`id`, `name`) VALUES ('ks', 'kashmiriska');
INSERT INTO `country` (`id`, `name`) VALUES ('csb', 'kasjubiska');
INSERT INTO `country` (`id`, `name`) VALUES ('ca', 'katalanska');
INSERT INTO `country` (`id`, `name`) VALUES ('cau', 'kaukasiskt språk');
INSERT INTO `country` (`id`, `name`) VALUES ('kaw', 'kawi');
INSERT INTO `country` (`id`, `name`) VALUES ('kk', 'kazakiska');
INSERT INTO `country` (`id`, `name`) VALUES ('cel', 'keltiskt språk');
INSERT INTO `country` (`id`, `name`) VALUES ('kha', 'khasi');
INSERT INTO `country` (`id`, `name`) VALUES ('khi', 'khoisanspråk');
INSERT INTO `country` (`id`, `name`) VALUES ('kho', 'khotanesiska');
INSERT INTO `country` (`id`, `name`) VALUES ('kg', 'kikongo');
INSERT INTO `country` (`id`, `name`) VALUES ('ki', 'kikuyu');
INSERT INTO `country` (`id`, `name`) VALUES ('kmb', 'kimbundu');
INSERT INTO `country` (`id`, `name`) VALUES ('zh', 'kinesiska');
INSERT INTO `country` (`id`, `name`) VALUES ('rw', 'kinjarwanda');
INSERT INTO `country` (`id`, `name`) VALUES ('ky', 'kirgisiska');
INSERT INTO `country` (`id`, `name`) VALUES ('yao', 'kiyao');
INSERT INTO `country` (`id`, `name`) VALUES ('nwc', 'klassisk newariska');
INSERT INTO `country` (`id`, `name`) VALUES ('syc', 'klassisk syriska');
INSERT INTO `country` (`id`, `name`) VALUES ('tlh', 'klingonska');
INSERT INTO `country` (`id`, `name`) VALUES ('kv', 'kome');
INSERT INTO `country` (`id`, `name`) VALUES ('kok', 'konkani');
INSERT INTO `country` (`id`, `name`) VALUES ('art', 'konstgjort språk');
INSERT INTO `country` (`id`, `name`) VALUES ('cop', 'koptiska');
INSERT INTO `country` (`id`, `name`) VALUES ('ko', 'koreanska');
INSERT INTO `country` (`id`, `name`) VALUES ('kw', 'korniska');
INSERT INTO `country` (`id`, `name`) VALUES ('kfo', 'koro');
INSERT INTO `country` (`id`, `name`) VALUES ('co', 'korsikanska');
INSERT INTO `country` (`id`, `name`) VALUES ('kos', 'kosreanska');
INSERT INTO `country` (`id`, `name`) VALUES ('kpe', 'kpelle');
INSERT INTO `country` (`id`, `name`) VALUES ('crp', 'kreol- eller pidginspråk');
INSERT INTO `country` (`id`, `name`) VALUES ('crh', 'krimtatariska');
INSERT INTO `country` (`id`, `name`) VALUES ('hr', 'kroatiska');
INSERT INTO `country` (`id`, `name`) VALUES ('kro', 'kru');
INSERT INTO `country` (`id`, `name`) VALUES ('kj', 'kuanyama');
INSERT INTO `country` (`id`, `name`) VALUES ('kum', 'kumykiska');
INSERT INTO `country` (`id`, `name`) VALUES ('ku', 'kurdiska');
INSERT INTO `country` (`id`, `name`) VALUES ('kru', 'kurukh');
INSERT INTO `country` (`id`, `name`) VALUES ('cus', 'kusjitiskt språk');
INSERT INTO `country` (`id`, `name`) VALUES ('kut', 'kutenaj');
INSERT INTO `country` (`id`, `name`) VALUES ('nmg', 'kwasio');
INSERT INTO `country` (`id`, `name`) VALUES ('cu', 'kyrkslaviska');
INSERT INTO `country` (`id`, `name`) VALUES ('lad', 'ladino');
INSERT INTO `country` (`id`, `name`) VALUES ('lah', 'lahnda');
INSERT INTO `country` (`id`, `name`) VALUES ('lam', 'lamba');
INSERT INTO `country` (`id`, `name`) VALUES ('lo', 'laotiska');
INSERT INTO `country` (`id`, `name`) VALUES ('la', 'latin');
INSERT INTO `country` (`id`, `name`) VALUES ('es_419', 'latinamerikansk spanska');
INSERT INTO `country` (`id`, `name`) VALUES ('lv', 'lettiska');
INSERT INTO `country` (`id`, `name`) VALUES ('lez', 'lezghien');
INSERT INTO `country` (`id`, `name`) VALUES ('li', 'limburgiska');
INSERT INTO `country` (`id`, `name`) VALUES ('ln', 'lingala');
INSERT INTO `country` (`id`, `name`) VALUES ('lt', 'litauiska');
INSERT INTO `country` (`id`, `name`) VALUES ('jbo', 'lojban');
INSERT INTO `country` (`id`, `name`) VALUES ('loz', 'lozi');
INSERT INTO `country` (`id`, `name`) VALUES ('lu', 'luba-katanga');
INSERT INTO `country` (`id`, `name`) VALUES ('lua', 'luba-lulua');
INSERT INTO `country` (`id`, `name`) VALUES ('lg', 'luganda');
INSERT INTO `country` (`id`, `name`) VALUES ('luy', 'luhya');
INSERT INTO `country` (`id`, `name`) VALUES ('lui', 'luiseño');
INSERT INTO `country` (`id`, `name`) VALUES ('smj', 'lulesamiska');
INSERT INTO `country` (`id`, `name`) VALUES ('lun', 'lunda');
INSERT INTO `country` (`id`, `name`) VALUES ('luo', 'luo');
INSERT INTO `country` (`id`, `name`) VALUES ('lus', 'lushai');
INSERT INTO `country` (`id`, `name`) VALUES ('lb', 'luxemburgiska');
INSERT INTO `country` (`id`, `name`) VALUES ('dsb', 'lågsorbiska');
INSERT INTO `country` (`id`, `name`) VALUES ('nds', 'lågtyska');
INSERT INTO `country` (`id`, `name`) VALUES ('mad', 'maduresiska');
INSERT INTO `country` (`id`, `name`) VALUES ('mag', 'magahi');
INSERT INTO `country` (`id`, `name`) VALUES ('mai', 'maithili');
INSERT INTO `country` (`id`, `name`) VALUES ('mak', 'makasar');
INSERT INTO `country` (`id`, `name`) VALUES ('mk', 'makedonska');
INSERT INTO `country` (`id`, `name`) VALUES ('mgh', 'makhuwa-meetto');
INSERT INTO `country` (`id`, `name`) VALUES ('mg', 'malagassiska');
INSERT INTO `country` (`id`, `name`) VALUES ('ms', 'malajiska');
INSERT INTO `country` (`id`, `name`) VALUES ('ml', 'malayalam');
INSERT INTO `country` (`id`, `name`) VALUES ('mt', 'maltesiska');
INSERT INTO `country` (`id`, `name`) VALUES ('mnc', 'manchuriska');
INSERT INTO `country` (`id`, `name`) VALUES ('mdr', 'mandar');
INSERT INTO `country` (`id`, `name`) VALUES ('man', 'mande');
INSERT INTO `country` (`id`, `name`) VALUES ('mni', 'manipuri');
INSERT INTO `country` (`id`, `name`) VALUES ('mno', 'manobospråk');
INSERT INTO `country` (`id`, `name`) VALUES ('gv', 'manx');
INSERT INTO `country` (`id`, `name`) VALUES ('mi', 'maori');
INSERT INTO `country` (`id`, `name`) VALUES ('mr', 'marathi');
INSERT INTO `country` (`id`, `name`) VALUES ('chm', 'mari');
INSERT INTO `country` (`id`, `name`) VALUES ('mh', 'marshalliska');
INSERT INTO `country` (`id`, `name`) VALUES ('mwr', 'marwari');
INSERT INTO `country` (`id`, `name`) VALUES ('mas', 'massajiska');
INSERT INTO `country` (`id`, `name`) VALUES ('myn', 'mayaspråk');
INSERT INTO `country` (`id`, `name`) VALUES ('enm', 'medelengelska');
INSERT INTO `country` (`id`, `name`) VALUES ('frm', 'medelfranska');
INSERT INTO `country` (`id`, `name`) VALUES ('gmh', 'medelhögtyska');
INSERT INTO `country` (`id`, `name`) VALUES ('mga', 'medeliriska');
INSERT INTO `country` (`id`, `name`) VALUES ('dum', 'medelnederländska');
INSERT INTO `country` (`id`, `name`) VALUES ('pal', 'medelpersiska');
INSERT INTO `country` (`id`, `name`) VALUES ('men', 'mende');
INSERT INTO `country` (`id`, `name`) VALUES ('mic', 'mic-mac');
INSERT INTO `country` (`id`, `name`) VALUES ('min', 'minangkabau');
INSERT INTO `country` (`id`, `name`) VALUES ('mwl', 'mirandesiska');
INSERT INTO `country` (`id`, `name`) VALUES ('moh', 'mohawk');
INSERT INTO `country` (`id`, `name`) VALUES ('mdf', 'moksja');
INSERT INTO `country` (`id`, `name`) VALUES ('mo', 'moldaviska');
INSERT INTO `country` (`id`, `name`) VALUES ('mkh', 'mon-khmeriskt språk');
INSERT INTO `country` (`id`, `name`) VALUES ('lol', 'mongo');
INSERT INTO `country` (`id`, `name`) VALUES ('mn', 'mongoliska');
INSERT INTO `country` (`id`, `name`) VALUES ('mos', 'mossi');
INSERT INTO `country` (`id`, `name`) VALUES ('mua', 'mundang');
INSERT INTO `country` (`id`, `name`) VALUES ('mun', 'mundaspråk');
INSERT INTO `country` (`id`, `name`) VALUES ('mus', 'muskogee');
INSERT INTO `country` (`id`, `name`) VALUES ('nqo', 'n-kå');
INSERT INTO `country` (`id`, `name`) VALUES ('nap', 'napolitanska');
INSERT INTO `country` (`id`, `name`) VALUES ('na', 'nauru');
INSERT INTO `country` (`id`, `name`) VALUES ('nv', 'navaho');
INSERT INTO `country` (`id`, `name`) VALUES ('ng', 'ndonga');
INSERT INTO `country` (`id`, `name`) VALUES ('nl', 'nederländska');
INSERT INTO `country` (`id`, `name`) VALUES ('ne', 'nepalesiska');
INSERT INTO `country` (`id`, `name`) VALUES ('new', 'newariska');
INSERT INTO `country` (`id`, `name`) VALUES ('nia', 'nias');
INSERT INTO `country` (`id`, `name`) VALUES ('nic', 'Niger-Kongospråk');
INSERT INTO `country` (`id`, `name`) VALUES ('ssa', 'nilosahariskt språk');
INSERT INTO `country` (`id`, `name`) VALUES ('niu', 'niueanska');
INSERT INTO `country` (`id`, `name`) VALUES ('nog', 'nogai');
INSERT INTO `country` (`id`, `name`) VALUES ('nai', 'nordamerikanskt indianspråk');
INSERT INTO `country` (`id`, `name`) VALUES ('frr', 'nordfrisiska');
INSERT INTO `country` (`id`, `name`) VALUES ('nd', 'nordndebele');
INSERT INTO `country` (`id`, `name`) VALUES ('se', 'nordsamiska');
INSERT INTO `country` (`id`, `name`) VALUES ('nso', 'nordsotho');
INSERT INTO `country` (`id`, `name`) VALUES ('no', 'norska');
INSERT INTO `country` (`id`, `name`) VALUES ('nb', 'norskt bokmål');
INSERT INTO `country` (`id`, `name`) VALUES ('nub', 'nubiskt språk');
INSERT INTO `country` (`id`, `name`) VALUES ('nus', 'nuer');
INSERT INTO `country` (`id`, `name`) VALUES ('nym', 'nyamwezi');
INSERT INTO `country` (`id`, `name`) VALUES ('ny', 'nyanja');
INSERT INTO `country` (`id`, `name`) VALUES ('nyn', 'nyankole');
INSERT INTO `country` (`id`, `name`) VALUES ('tog', 'nyasatonganska');
INSERT INTO `country` (`id`, `name`) VALUES ('nn', 'nynorska');
INSERT INTO `country` (`id`, `name`) VALUES ('nyo', 'nyoro');
INSERT INTO `country` (`id`, `name`) VALUES ('nzi', 'nzima');
INSERT INTO `country` (`id`, `name`) VALUES ('und', 'obestämt språk');
INSERT INTO `country` (`id`, `name`) VALUES ('oc', 'occitanska');
INSERT INTO `country` (`id`, `name`) VALUES ('oj', 'odjibwa');
INSERT INTO `country` (`id`, `name`) VALUES ('or', 'oriya');
INSERT INTO `country` (`id`, `name`) VALUES ('om', 'oromo');
INSERT INTO `country` (`id`, `name`) VALUES ('osa', 'osage');
INSERT INTO `country` (`id`, `name`) VALUES ('os', 'ossetiska');
INSERT INTO `country` (`id`, `name`) VALUES ('oto', 'otomispråk');
INSERT INTO `country` (`id`, `name`) VALUES ('ota', 'ottomanska');
INSERT INTO `country` (`id`, `name`) VALUES ('pau', 'palau');
INSERT INTO `country` (`id`, `name`) VALUES ('pi', 'pali');
INSERT INTO `country` (`id`, `name`) VALUES ('pam', 'pampanga');
INSERT INTO `country` (`id`, `name`) VALUES ('pag', 'pangasinan');
INSERT INTO `country` (`id`, `name`) VALUES ('pap', 'papiamento');
INSERT INTO `country` (`id`, `name`) VALUES ('paa', 'papuanskt språk');
INSERT INTO `country` (`id`, `name`) VALUES ('fa', 'persiska');
INSERT INTO `country` (`id`, `name`) VALUES ('pl', 'polska');
INSERT INTO `country` (`id`, `name`) VALUES ('pon', 'ponape');
INSERT INTO `country` (`id`, `name`) VALUES ('pt', 'portugisiska');
INSERT INTO `country` (`id`, `name`) VALUES ('cpp', 'portugisiskbaserat kreol- eller pidginspråk');
INSERT INTO `country` (`id`, `name`) VALUES ('pra', 'prakritspråk');
INSERT INTO `country` (`id`, `name`) VALUES ('pa', 'punjabi');
INSERT INTO `country` (`id`, `name`) VALUES ('qu', 'quechua');
INSERT INTO `country` (`id`, `name`) VALUES ('raj', 'rajasthani');
INSERT INTO `country` (`id`, `name`) VALUES ('rap', 'rapanui');
INSERT INTO `country` (`id`, `name`) VALUES ('rar', 'rarotonganska');
INSERT INTO `country` (`id`, `name`) VALUES ('rom', 'romani');
INSERT INTO `country` (`id`, `name`) VALUES ('roa', 'romanskt språk');
INSERT INTO `country` (`id`, `name`) VALUES ('rof', 'rombo');
INSERT INTO `country` (`id`, `name`) VALUES ('root', 'rot');
INSERT INTO `country` (`id`, `name`) VALUES ('ro', 'rumänska');
INSERT INTO `country` (`id`, `name`) VALUES ('rn', 'rundi');
INSERT INTO `country` (`id`, `name`) VALUES ('rwk', 'rwa');
INSERT INTO `country` (`id`, `name`) VALUES ('ru', 'ryska');
INSERT INTO `country` (`id`, `name`) VALUES ('rm', 'rätoromanska');
INSERT INTO `country` (`id`, `name`) VALUES ('sal', 'salikiskt språk');
INSERT INTO `country` (`id`, `name`) VALUES ('sam', 'samaritanska');
INSERT INTO `country` (`id`, `name`) VALUES ('smi', 'samiskt språk');
INSERT INTO `country` (`id`, `name`) VALUES ('sm', 'samoanska');
INSERT INTO `country` (`id`, `name`) VALUES ('sad', 'sandawe');
INSERT INTO `country` (`id`, `name`) VALUES ('sg', 'sango');
INSERT INTO `country` (`id`, `name`) VALUES ('sbp', 'sangu');
INSERT INTO `country` (`id`, `name`) VALUES ('sa', 'sanskrit');
INSERT INTO `country` (`id`, `name`) VALUES ('sat', 'santali');
INSERT INTO `country` (`id`, `name`) VALUES ('sc', 'sardiska');
INSERT INTO `country` (`id`, `name`) VALUES ('sas', 'sasak');
INSERT INTO `country` (`id`, `name`) VALUES ('gsw', 'schweizertyska');
INSERT INTO `country` (`id`, `name`) VALUES ('fr_CH', 'schweizisk franska');
INSERT INTO `country` (`id`, `name`) VALUES ('de_CH', 'schweizisk högtyska');
INSERT INTO `country` (`id`, `name`) VALUES ('sel', 'selkup');
INSERT INTO `country` (`id`, `name`) VALUES ('sem', 'semitiskt språk');
INSERT INTO `country` (`id`, `name`) VALUES ('sr', 'serbiska');
INSERT INTO `country` (`id`, `name`) VALUES ('sh', 'serbokroatiska');
INSERT INTO `country` (`id`, `name`) VALUES ('srr', 'serer');
INSERT INTO `country` (`id`, `name`) VALUES ('shn', 'shan');
INSERT INTO `country` (`id`, `name`) VALUES ('swb', 'shimaoré');
INSERT INTO `country` (`id`, `name`) VALUES ('sn', 'shona');
INSERT INTO `country` (`id`, `name`) VALUES ('scn', 'sicilianska');
INSERT INTO `country` (`id`, `name`) VALUES ('sid', 'sidamo');
INSERT INTO `country` (`id`, `name`) VALUES ('bla', 'siksika');
INSERT INTO `country` (`id`, `name`) VALUES ('sd', 'sindhi');
INSERT INTO `country` (`id`, `name`) VALUES ('si', 'singalesiska');
INSERT INTO `country` (`id`, `name`) VALUES ('sit', 'sinotibetanskt språk');
INSERT INTO `country` (`id`, `name`) VALUES ('sio', 'siouxspråk');
INSERT INTO `country` (`id`, `name`) VALUES ('sms', 'skoltsamiska');
INSERT INTO `country` (`id`, `name`) VALUES ('sco', 'skotska');
INSERT INTO `country` (`id`, `name`) VALUES ('den', 'slavej');
INSERT INTO `country` (`id`, `name`) VALUES ('sla', 'slaviskt språk');
INSERT INTO `country` (`id`, `name`) VALUES ('sk', 'slovakiska');
INSERT INTO `country` (`id`, `name`) VALUES ('sl', 'slovenska');
INSERT INTO `country` (`id`, `name`) VALUES ('sog', 'sogdiska');
INSERT INTO `country` (`id`, `name`) VALUES ('so', 'somaliska');
INSERT INTO `country` (`id`, `name`) VALUES ('son', 'songhai');
INSERT INTO `country` (`id`, `name`) VALUES ('snk', 'soninke');
INSERT INTO `country` (`id`, `name`) VALUES ('wen', 'sorbiskt språk');
INSERT INTO `country` (`id`, `name`) VALUES ('es', 'spanska');
INSERT INTO `country` (`id`, `name`) VALUES ('srn', 'sranan tongo');
INSERT INTO `country` (`id`, `name`) VALUES ('suk', 'sukuma');
INSERT INTO `country` (`id`, `name`) VALUES ('sux', 'sumeriska');
INSERT INTO `country` (`id`, `name`) VALUES ('su', 'sundanesiska');
INSERT INTO `country` (`id`, `name`) VALUES ('sus', 'susu');
INSERT INTO `country` (`id`, `name`) VALUES ('sv', 'svenska');
INSERT INTO `country` (`id`, `name`) VALUES ('sw', 'swahili');
INSERT INTO `country` (`id`, `name`) VALUES ('ss', 'swati');
INSERT INTO `country` (`id`, `name`) VALUES ('alt', 'sydaltaiska');
INSERT INTO `country` (`id`, `name`) VALUES ('sai', 'sydamerikanskt indianspråk');
INSERT INTO `country` (`id`, `name`) VALUES ('nr', 'sydndebele');
INSERT INTO `country` (`id`, `name`) VALUES ('sma', 'sydsamiska');
INSERT INTO `country` (`id`, `name`) VALUES ('st', 'sydsotho');
INSERT INTO `country` (`id`, `name`) VALUES ('syr', 'syriska');
INSERT INTO `country` (`id`, `name`) VALUES ('ii', 'szezuan i');
INSERT INTO `country` (`id`, `name`) VALUES ('tg', 'tadzjikiska');
INSERT INTO `country` (`id`, `name`) VALUES ('tl', 'tagalog');
INSERT INTO `country` (`id`, `name`) VALUES ('ty', 'tahitiska');
INSERT INTO `country` (`id`, `name`) VALUES ('tmh', 'tamashek');
INSERT INTO `country` (`id`, `name`) VALUES ('ta', 'tamil');
INSERT INTO `country` (`id`, `name`) VALUES ('twq', 'tasawaq');
INSERT INTO `country` (`id`, `name`) VALUES ('tt', 'tatariska');
INSERT INTO `country` (`id`, `name`) VALUES ('sgn', 'teckenspråk');
INSERT INTO `country` (`id`, `name`) VALUES ('te', 'telugiska');
INSERT INTO `country` (`id`, `name`) VALUES ('tem', 'temne');
INSERT INTO `country` (`id`, `name`) VALUES ('ter', 'tereno');
INSERT INTO `country` (`id`, `name`) VALUES ('tet', 'tetum');
INSERT INTO `country` (`id`, `name`) VALUES ('th', 'thailändska');
INSERT INTO `country` (`id`, `name`) VALUES ('tai', 'thaispråk');
INSERT INTO `country` (`id`, `name`) VALUES ('bo', 'tibetanska');
INSERT INTO `country` (`id`, `name`) VALUES ('tig', 'tigré');
INSERT INTO `country` (`id`, `name`) VALUES ('ti', 'tigrinja');
INSERT INTO `country` (`id`, `name`) VALUES ('tiv', 'tivi');
INSERT INTO `country` (`id`, `name`) VALUES ('cs', 'tjeckiska');
INSERT INTO `country` (`id`, `name`) VALUES ('ce', 'tjetjenska');
INSERT INTO `country` (`id`, `name`) VALUES ('cv', 'tjuvasjiska');
INSERT INTO `country` (`id`, `name`) VALUES ('tli', 'tlingit');
INSERT INTO `country` (`id`, `name`) VALUES ('tpi', 'tok pisin');
INSERT INTO `country` (`id`, `name`) VALUES ('tkl', 'tokelauiska');
INSERT INTO `country` (`id`, `name`) VALUES ('to', 'tonganska');
INSERT INTO `country` (`id`, `name`) VALUES ('zh_Hant', 'traditionell kinesiska');
INSERT INTO `country` (`id`, `name`) VALUES ('tsi', 'tsimshian');
INSERT INTO `country` (`id`, `name`) VALUES ('ts', 'tsonga');
INSERT INTO `country` (`id`, `name`) VALUES ('tn', 'tswana');
INSERT INTO `country` (`id`, `name`) VALUES ('tum', 'tumbuka');
INSERT INTO `country` (`id`, `name`) VALUES ('tup', 'tupíspråk');
INSERT INTO `country` (`id`, `name`) VALUES ('tr', 'turkiska');
INSERT INTO `country` (`id`, `name`) VALUES ('tk', 'turkmeniska');
INSERT INTO `country` (`id`, `name`) VALUES ('tvl', 'tuvaluanska');
INSERT INTO `country` (`id`, `name`) VALUES ('tyv', 'tuviniska');
INSERT INTO `country` (`id`, `name`) VALUES ('tw', 'twi');
INSERT INTO `country` (`id`, `name`) VALUES ('kcg', 'tyap');
INSERT INTO `country` (`id`, `name`) VALUES ('de', 'tyska');
INSERT INTO `country` (`id`, `name`) VALUES ('udm', 'udmurtiska');
INSERT INTO `country` (`id`, `name`) VALUES ('uga', 'ugaritiska');
INSERT INTO `country` (`id`, `name`) VALUES ('ug', 'uiguriska');
INSERT INTO `country` (`id`, `name`) VALUES ('uk', 'ukrainska');
INSERT INTO `country` (`id`, `name`) VALUES ('umb', 'umbundu');
INSERT INTO `country` (`id`, `name`) VALUES ('hu', 'ungerska');
INSERT INTO `country` (`id`, `name`) VALUES ('ur', 'urdu');
INSERT INTO `country` (`id`, `name`) VALUES ('uz', 'uzbekiska');
INSERT INTO `country` (`id`, `name`) VALUES ('vai', 'vaj');
INSERT INTO `country` (`id`, `name`) VALUES ('wa', 'vallonska');
INSERT INTO `country` (`id`, `name`) VALUES ('ve', 'venda');
INSERT INTO `country` (`id`, `name`) VALUES ('vi', 'vietnamesiska');
INSERT INTO `country` (`id`, `name`) VALUES ('be', 'vitryska');
INSERT INTO `country` (`id`, `name`) VALUES ('vo', 'volapük');
INSERT INTO `country` (`id`, `name`) VALUES ('vot', 'votiska');
INSERT INTO `country` (`id`, `name`) VALUES ('fy', 'västfrisiska');
INSERT INTO `country` (`id`, `name`) VALUES ('wak', 'wakusjiskt språk');
INSERT INTO `country` (`id`, `name`) VALUES ('wal', 'walamo');
INSERT INTO `country` (`id`, `name`) VALUES ('cy', 'walesiska');
INSERT INTO `country` (`id`, `name`) VALUES ('wae', 'walsertyska');
INSERT INTO `country` (`id`, `name`) VALUES ('war', 'waray');
INSERT INTO `country` (`id`, `name`) VALUES ('was', 'washo');
INSERT INTO `country` (`id`, `name`) VALUES ('wo', 'wolof');
INSERT INTO `country` (`id`, `name`) VALUES ('xh', 'xhosa');
INSERT INTO `country` (`id`, `name`) VALUES ('yav', 'yangben');
INSERT INTO `country` (`id`, `name`) VALUES ('yo', 'yoruba');
INSERT INTO `country` (`id`, `name`) VALUES ('znd', 'zandé');
INSERT INTO `country` (`id`, `name`) VALUES ('zap', 'zapotek');
INSERT INTO `country` (`id`, `name`) VALUES ('dje', 'zarma');
INSERT INTO `country` (`id`, `name`) VALUES ('zza', 'zazaiska');
INSERT INTO `country` (`id`, `name`) VALUES ('zen', 'zenaga');
INSERT INTO `country` (`id`, `name`) VALUES ('za', 'zhuang');
INSERT INTO `country` (`id`, `name`) VALUES ('zu', 'zulu');
INSERT INTO `country` (`id`, `name`) VALUES ('zun', 'zuni');
INSERT INTO `country` (`id`, `name`) VALUES ('de_AT', 'österrikisk tyska');
INSERT INTO `country` (`id`, `name`) VALUES ('frs', 'östfrisiska');
