CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('ak', 'Akâan');
INSERT INTO "country" ("id", "name") VALUES ('am', 'Amarîki');
INSERT INTO "country" ("id", "name") VALUES ('en', 'Anglëe');
INSERT INTO "country" ("id", "name") VALUES ('ar', 'Arâbo');
INSERT INTO "country" ("id", "name") VALUES ('bn', 'Bengäli');
INSERT INTO "country" ("id", "name") VALUES ('be', 'Bielörûsi');
INSERT INTO "country" ("id", "name") VALUES ('bg', 'Bulugäri');
INSERT INTO "country" ("id", "name") VALUES ('it', 'Ênnde');
INSERT INTO "country" ("id", "name") VALUES ('id', 'Enndonezïi');
INSERT INTO "country" ("id", "name") VALUES ('es', 'Espanyöl');
INSERT INTO "country" ("id", "name") VALUES ('fr', 'Farânzi');
INSERT INTO "country" ("id", "name") VALUES ('fa', 'Farsî');
INSERT INTO "country" ("id", "name") VALUES ('el', 'Gerêki');
INSERT INTO "country" ("id", "name") VALUES ('ha', 'Haüsä');
INSERT INTO "country" ("id", "name") VALUES ('hi', 'Hîndi');
INSERT INTO "country" ("id", "name") VALUES ('nl', 'Holandëe');
INSERT INTO "country" ("id", "name") VALUES ('hu', 'Hongruäa');
INSERT INTO "country" ("id", "name") VALUES ('ig', 'Ïgbö');
INSERT INTO "country" ("id", "name") VALUES ('km', 'Kmêre');
INSERT INTO "country" ("id", "name") VALUES ('ko', 'Koreyëen');
INSERT INTO "country" ("id", "name") VALUES ('ms', 'Malëe');
INSERT INTO "country" ("id", "name") VALUES ('my', 'Miamära, Birimäni');
INSERT INTO "country" ("id", "name") VALUES ('ne', 'Nepalëe');
INSERT INTO "country" ("id", "name") VALUES ('pa', 'Penzäbï');
INSERT INTO "country" ("id", "name") VALUES ('pl', 'Polonëe');
INSERT INTO "country" ("id", "name") VALUES ('pt', 'Portugëe, Pûra');
INSERT INTO "country" ("id", "name") VALUES ('rw', 'Ruandäa');
INSERT INTO "country" ("id", "name") VALUES ('ro', 'Rumëen');
INSERT INTO "country" ("id", "name") VALUES ('ru', 'Rûsi');
INSERT INTO "country" ("id", "name") VALUES ('sg', 'Sängö');
INSERT INTO "country" ("id", "name") VALUES ('zh', 'Shinuäa');
INSERT INTO "country" ("id", "name") VALUES ('so', 'Somalïi');
INSERT INTO "country" ("id", "name") VALUES ('sv', 'Sueduäa');
INSERT INTO "country" ("id", "name") VALUES ('ta', 'Tämûli');
INSERT INTO "country" ("id", "name") VALUES ('th', 'Thâi');
INSERT INTO "country" ("id", "name") VALUES ('tr', 'Tûrûku');
INSERT INTO "country" ("id", "name") VALUES ('cs', 'Tyêki');
INSERT INTO "country" ("id", "name") VALUES ('uk', 'Ukrêni');
INSERT INTO "country" ("id", "name") VALUES ('ur', 'Ûrdu');
INSERT INTO "country" ("id", "name") VALUES ('vi', 'Vietnäm');
INSERT INTO "country" ("id", "name") VALUES ('yo', 'Yoruba');
INSERT INTO "country" ("id", "name") VALUES ('de', 'Zâmani');
INSERT INTO "country" ("id", "name") VALUES ('ja', 'Zaponëe');
INSERT INTO "country" ("id", "name") VALUES ('jv', 'Zavanëe');
INSERT INTO "country" ("id", "name") VALUES ('zu', 'Zûlu');
