CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('ay', 'Aimara');
INSERT INTO `country` (`id`, `name`) VALUES ('zxx', 'Hakuna maudhui ya lugha');
INSERT INTO `country` (`id`, `name`) VALUES ('ks', 'Kashmiri');
INSERT INTO `country` (`id`, `name`) VALUES ('ab', 'Kiabkhazi');
INSERT INTO `country` (`id`, `name`) VALUES ('af', 'Kiafrikana');
INSERT INTO `country` (`id`, `name`) VALUES ('is', 'Kiaisilandi');
INSERT INTO `country` (`id`, `name`) VALUES ('fa', 'Kiajemi');
INSERT INTO `country` (`id`, `name`) VALUES ('ak', 'Kiakan');
INSERT INTO `country` (`id`, `name`) VALUES ('sq', 'Kialbania');
INSERT INTO `country` (`id`, `name`) VALUES ('am', 'Kiamhari');
INSERT INTO `country` (`id`, `name`) VALUES ('ar', 'Kiarabu');
INSERT INTO `country` (`id`, `name`) VALUES ('hy', 'Kiarmenia');
INSERT INTO `country` (`id`, `name`) VALUES ('as', 'Kiassam');
INSERT INTO `country` (`id`, `name`) VALUES ('ga', 'Kiayalandi');
INSERT INTO `country` (`id`, `name`) VALUES ('az', 'Kiazabajani');
INSERT INTO `country` (`id`, `name`) VALUES ('bn', 'Kibangla');
INSERT INTO `country` (`id`, `name`) VALUES ('eu', 'Kibasque');
INSERT INTO `country` (`id`, `name`) VALUES ('be', 'Kibelarusi');
INSERT INTO `country` (`id`, `name`) VALUES ('nb', 'Kibokmal cha Norwe');
INSERT INTO `country` (`id`, `name`) VALUES ('bs', 'Kibosnia');
INSERT INTO `country` (`id`, `name`) VALUES ('bg', 'Kibulgaria');
INSERT INTO `country` (`id`, `name`) VALUES ('my', 'Kiburma');
INSERT INTO `country` (`id`, `name`) VALUES ('cs', 'Kicheki');
INSERT INTO `country` (`id`, `name`) VALUES ('zh', 'Kichina');
INSERT INTO `country` (`id`, `name`) VALUES ('zh_Hant', 'Kichina cha Jadi');
INSERT INTO `country` (`id`, `name`) VALUES ('zh_Hans', 'Kichina Rahisi');
INSERT INTO `country` (`id`, `name`) VALUES ('da', 'Kidenmaki');
INSERT INTO `country` (`id`, `name`) VALUES ('dv', 'Kidivehi');
INSERT INTO `country` (`id`, `name`) VALUES ('he', 'Kiebrania');
INSERT INTO `country` (`id`, `name`) VALUES ('efi', 'Kiefiki');
INSERT INTO `country` (`id`, `name`) VALUES ('eo', 'Kiesperanto');
INSERT INTO `country` (`id`, `name`) VALUES ('et', 'Kiestonia');
INSERT INTO `country` (`id`, `name`) VALUES ('fr', 'Kifaransa');
INSERT INTO `country` (`id`, `name`) VALUES ('fr_CA', 'Kifaransa cha Kanada');
INSERT INTO `country` (`id`, `name`) VALUES ('fr_CH', 'Kifaransa cha Uswisi');
INSERT INTO `country` (`id`, `name`) VALUES ('fo', 'Kifaroe');
INSERT INTO `country` (`id`, `name`) VALUES ('fj', 'Kifiji');
INSERT INTO `country` (`id`, `name`) VALUES ('fil', 'Kifilipino');
INSERT INTO `country` (`id`, `name`) VALUES ('fi', 'Kifinlandi');
INSERT INTO `country` (`id`, `name`) VALUES ('nl_BE', 'Kiflemi');
INSERT INTO `country` (`id`, `name`) VALUES ('fy', 'Kifrisia cha Magharibi');
INSERT INTO `country` (`id`, `name`) VALUES ('gd', 'Kigaeli cha Uskoti');
INSERT INTO `country` (`id`, `name`) VALUES ('gl', 'Kigalisia');
INSERT INTO `country` (`id`, `name`) VALUES ('el', 'Kigiriki');
INSERT INTO `country` (`id`, `name`) VALUES ('gn', 'Kiguarani');
INSERT INTO `country` (`id`, `name`) VALUES ('gu', 'Kigujarati');
INSERT INTO `country` (`id`, `name`) VALUES ('ht', 'Kihaiti');
INSERT INTO `country` (`id`, `name`) VALUES ('ha', 'Kihausa');
INSERT INTO `country` (`id`, `name`) VALUES ('haw', 'Kihawai');
INSERT INTO `country` (`id`, `name`) VALUES ('hi', 'Kihindi');
INSERT INTO `country` (`id`, `name`) VALUES ('es', 'Kihispania');
INSERT INTO `country` (`id`, `name`) VALUES ('es_419', 'Kihispania cha Amerika ya Kilatinini');
INSERT INTO `country` (`id`, `name`) VALUES ('es_ES', 'Kihispania cha Iberia');
INSERT INTO `country` (`id`, `name`) VALUES ('nl', 'Kiholanzi');
INSERT INTO `country` (`id`, `name`) VALUES ('hu', 'Kihungari');
INSERT INTO `country` (`id`, `name`) VALUES ('ig', 'Kiigbo');
INSERT INTO `country` (`id`, `name`) VALUES ('id', 'Kiindonesia');
INSERT INTO `country` (`id`, `name`) VALUES ('en', 'Kiingereza');
INSERT INTO `country` (`id`, `name`) VALUES ('en_AU', 'Kiingereza cha Australia');
INSERT INTO `country` (`id`, `name`) VALUES ('en_CA', 'Kiingereza cha Kanada');
INSERT INTO `country` (`id`, `name`) VALUES ('en_US', 'Kiingereza cha Marekani');
INSERT INTO `country` (`id`, `name`) VALUES ('en_GB', 'Kiingereza cha Uingereza');
INSERT INTO `country` (`id`, `name`) VALUES ('it', 'Kiitaliano');
INSERT INTO `country` (`id`, `name`) VALUES ('ja', 'Kijapani');
INSERT INTO `country` (`id`, `name`) VALUES ('jv', 'Kijava');
INSERT INTO `country` (`id`, `name`) VALUES ('de', 'Kijerumani');
INSERT INTO `country` (`id`, `name`) VALUES ('de_AT', 'Kijerumani cha Austria');
INSERT INTO `country` (`id`, `name`) VALUES ('de_CH', 'Kijerumani cha Juu cha Uswisi');
INSERT INTO `country` (`id`, `name`) VALUES ('gsw', 'Kijerumani cha Uswisi');
INSERT INTO `country` (`id`, `name`) VALUES ('ka', 'Kijojia');
INSERT INTO `country` (`id`, `name`) VALUES ('km', 'Kikambodia');
INSERT INTO `country` (`id`, `name`) VALUES ('kn', 'Kikannada');
INSERT INTO `country` (`id`, `name`) VALUES ('ca', 'Kikatalani');
INSERT INTO `country` (`id`, `name`) VALUES ('kk', 'Kikazaki');
INSERT INTO `country` (`id`, `name`) VALUES ('ko', 'Kikorea');
INSERT INTO `country` (`id`, `name`) VALUES ('ku', 'Kikurdi');
INSERT INTO `country` (`id`, `name`) VALUES ('lo', 'Kilaosi');
INSERT INTO `country` (`id`, `name`) VALUES ('lb', 'Kilasembagi');
INSERT INTO `country` (`id`, `name`) VALUES ('la', 'Kilatini');
INSERT INTO `country` (`id`, `name`) VALUES ('lv', 'Kilatvia');
INSERT INTO `country` (`id`, `name`) VALUES ('ln', 'Kilingala');
INSERT INTO `country` (`id`, `name`) VALUES ('lt', 'Kilithuania');
INSERT INTO `country` (`id`, `name`) VALUES ('ml', 'Kimalayalam');
INSERT INTO `country` (`id`, `name`) VALUES ('ms', 'Kimalesia');
INSERT INTO `country` (`id`, `name`) VALUES ('mt', 'Kimalta');
INSERT INTO `country` (`id`, `name`) VALUES ('mr', 'Kimarathi');
INSERT INTO `country` (`id`, `name`) VALUES ('mk', 'Kimasedonia');
INSERT INTO `country` (`id`, `name`) VALUES ('nd', 'Kindebele cha Kaskazini');
INSERT INTO `country` (`id`, `name`) VALUES ('ne', 'Kinepali');
INSERT INTO `country` (`id`, `name`) VALUES ('nn', 'Kinorwe Kipya');
INSERT INTO `country` (`id`, `name`) VALUES ('ny', 'Kinyanja');
INSERT INTO `country` (`id`, `name`) VALUES ('rw', 'Kinyarwanda');
INSERT INTO `country` (`id`, `name`) VALUES ('or', 'Kioriya');
INSERT INTO `country` (`id`, `name`) VALUES ('os', 'Kiosetia');
INSERT INTO `country` (`id`, `name`) VALUES ('ps', 'Kipashto');
INSERT INTO `country` (`id`, `name`) VALUES ('pl', 'Kipolandi');
INSERT INTO `country` (`id`, `name`) VALUES ('pa', 'Kipunjabi');
INSERT INTO `country` (`id`, `name`) VALUES ('pt', 'Kireno');
INSERT INTO `country` (`id`, `name`) VALUES ('pt_BR', 'Kireno cha Brazil');
INSERT INTO `country` (`id`, `name`) VALUES ('pt_PT', 'Kireno cha Iberia');
INSERT INTO `country` (`id`, `name`) VALUES ('ky', 'Kirigizi');
INSERT INTO `country` (`id`, `name`) VALUES ('ro', 'Kiromania');
INSERT INTO `country` (`id`, `name`) VALUES ('rm', 'Kiromanshi');
INSERT INTO `country` (`id`, `name`) VALUES ('rn', 'Kirundi');
INSERT INTO `country` (`id`, `name`) VALUES ('ru', 'Kirusi');
INSERT INTO `country` (`id`, `name`) VALUES ('se', 'Kisami cha Kaskazini');
INSERT INTO `country` (`id`, `name`) VALUES ('sm', 'Kisamoa');
INSERT INTO `country` (`id`, `name`) VALUES ('sg', 'Kisango');
INSERT INTO `country` (`id`, `name`) VALUES ('sa', 'Kisanskriti');
INSERT INTO `country` (`id`, `name`) VALUES ('sr', 'Kiserbia');
INSERT INTO `country` (`id`, `name`) VALUES ('sn', 'Kishona');
INSERT INTO `country` (`id`, `name`) VALUES ('sd', 'Kisindhi');
INSERT INTO `country` (`id`, `name`) VALUES ('si', 'Kisinhala');
INSERT INTO `country` (`id`, `name`) VALUES ('sk', 'Kislovakia');
INSERT INTO `country` (`id`, `name`) VALUES ('sl', 'Kislovenia');
INSERT INTO `country` (`id`, `name`) VALUES ('so', 'Kisomali');
INSERT INTO `country` (`id`, `name`) VALUES ('nso', 'Kisotho cha Kaskazini');
INSERT INTO `country` (`id`, `name`) VALUES ('st', 'Kisotho cha Kusini');
INSERT INTO `country` (`id`, `name`) VALUES ('su', 'Kisunda');
INSERT INTO `country` (`id`, `name`) VALUES ('sw', 'Kiswahili');
INSERT INTO `country` (`id`, `name`) VALUES ('ss', 'Kiswati');
INSERT INTO `country` (`id`, `name`) VALUES ('sv', 'Kiswidi');
INSERT INTO `country` (`id`, `name`) VALUES ('ty', 'Kitahiti');
INSERT INTO `country` (`id`, `name`) VALUES ('th', 'Kitailandi');
INSERT INTO `country` (`id`, `name`) VALUES ('ta', 'Kitamil');
INSERT INTO `country` (`id`, `name`) VALUES ('tt', 'Kitatari');
INSERT INTO `country` (`id`, `name`) VALUES ('te', 'Kitelugu');
INSERT INTO `country` (`id`, `name`) VALUES ('tet', 'Kitetum');
INSERT INTO `country` (`id`, `name`) VALUES ('bo', 'Kitibeti');
INSERT INTO `country` (`id`, `name`) VALUES ('ti', 'Kitigrinya');
INSERT INTO `country` (`id`, `name`) VALUES ('tpi', 'Kitokpisin');
INSERT INTO `country` (`id`, `name`) VALUES ('ts', 'Kitsonga');
INSERT INTO `country` (`id`, `name`) VALUES ('tn', 'Kitswana');
INSERT INTO `country` (`id`, `name`) VALUES ('tr', 'Kituruki');
INSERT INTO `country` (`id`, `name`) VALUES ('tk', 'Kiturukimeni');
INSERT INTO `country` (`id`, `name`) VALUES ('ug', 'Kiuigur');
INSERT INTO `country` (`id`, `name`) VALUES ('uk', 'Kiukrania');
INSERT INTO `country` (`id`, `name`) VALUES ('ur', 'Kiurdu');
INSERT INTO `country` (`id`, `name`) VALUES ('uz', 'Kiuzbeki');
INSERT INTO `country` (`id`, `name`) VALUES ('ve', 'Kivenda');
INSERT INTO `country` (`id`, `name`) VALUES ('vi', 'Kivietinamu');
INSERT INTO `country` (`id`, `name`) VALUES ('cy', 'Kiwelisi');
INSERT INTO `country` (`id`, `name`) VALUES ('xh', 'Kixhosa');
INSERT INTO `country` (`id`, `name`) VALUES ('yo', 'Kiyoruba');
INSERT INTO `country` (`id`, `name`) VALUES ('dz', 'Kizongkha');
INSERT INTO `country` (`id`, `name`) VALUES ('zu', 'Kizulu');
INSERT INTO `country` (`id`, `name`) VALUES ('hr', 'Kroeshia');
INSERT INTO `country` (`id`, `name`) VALUES ('und', 'Lugha Isiyojulikana');
INSERT INTO `country` (`id`, `name`) VALUES ('mg', 'Malagasi');
INSERT INTO `country` (`id`, `name`) VALUES ('mi', 'Maori');
INSERT INTO `country` (`id`, `name`) VALUES ('mn', 'Mongolia');
INSERT INTO `country` (`id`, `name`) VALUES ('qu', 'Quechua');
INSERT INTO `country` (`id`, `name`) VALUES ('tg', 'Tajiki');
INSERT INTO `country` (`id`, `name`) VALUES ('to', 'Tonga');
INSERT INTO `country` (`id`, `name`) VALUES ('wo', 'Wolof');
