CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('nd', 'Bắc Ndebele');
INSERT INTO `country` (`id`, `name`) VALUES ('se', 'Bắc Sami');
INSERT INTO `country` (`id`, `name`) VALUES ('nso', 'Bắc Sotho');
INSERT INTO `country` (`id`, `name`) VALUES ('zxx', 'Không có nội dung ngôn ngữ');
INSERT INTO `country` (`id`, `name`) VALUES ('tet', 'Tetum');
INSERT INTO `country` (`id`, `name`) VALUES ('ar', 'Tiếng A-rập');
INSERT INTO `country` (`id`, `name`) VALUES ('ab', 'Tiếng Abkhazia');
INSERT INTO `country` (`id`, `name`) VALUES ('hy', 'Tiếng Ác-mê-ni');
INSERT INTO `country` (`id`, `name`) VALUES ('az', 'Tiếng Ai-déc-bai-gian');
INSERT INTO `country` (`id`, `name`) VALUES ('ga', 'Tiếng Ai-len');
INSERT INTO `country` (`id`, `name`) VALUES ('is', 'Tiếng Ai-xơ-len');
INSERT INTO `country` (`id`, `name`) VALUES ('am', 'Tiếng Amharic');
INSERT INTO `country` (`id`, `name`) VALUES ('sq', 'Tiếng An-ba-ni');
INSERT INTO `country` (`id`, `name`) VALUES ('en', 'Tiếng Anh');
INSERT INTO `country` (`id`, `name`) VALUES ('en_GB', 'Tiếng Anh (Anh)');
INSERT INTO `country` (`id`, `name`) VALUES ('en_CA', 'Tiếng Anh (Canada)');
INSERT INTO `country` (`id`, `name`) VALUES ('en_US', 'Tiếng Anh (Mỹ)');
INSERT INTO `country` (`id`, `name`) VALUES ('as', 'Tiếng Assam');
INSERT INTO `country` (`id`, `name`) VALUES ('ay', 'Tiếng Aymara');
INSERT INTO `country` (`id`, `name`) VALUES ('pl', 'Tiếng Ba Lan');
INSERT INTO `country` (`id`, `name`) VALUES ('fa', 'Tiếng Ba Tư');
INSERT INTO `country` (`id`, `name`) VALUES ('xh', 'Tiếng Bantu');
INSERT INTO `country` (`id`, `name`) VALUES ('sw', 'Tiếng Bantu (Đông Phi)');
INSERT INTO `country` (`id`, `name`) VALUES ('eu', 'Tiếng Basque');
INSERT INTO `country` (`id`, `name`) VALUES ('bn', 'Tiếng Bengali (Ấn Độ)');
INSERT INTO `country` (`id`, `name`) VALUES ('be', 'Tiếng Bê-la-rút');
INSERT INTO `country` (`id`, `name`) VALUES ('bh', 'Tiếng Bihari');
INSERT INTO `country` (`id`, `name`) VALUES ('pt', 'Tiếng Bồ Đào Nha');
INSERT INTO `country` (`id`, `name`) VALUES ('pt_BR', 'Tiếng Bồ Đào Nha (Braxin)');
INSERT INTO `country` (`id`, `name`) VALUES ('pt_PT', 'Tiếng Bồ Đào Nha (I-bê-ri)');
INSERT INTO `country` (`id`, `name`) VALUES ('br', 'Tiếng Breton');
INSERT INTO `country` (`id`, `name`) VALUES ('bg', 'Tiếng Bun-ga-ri');
INSERT INTO `country` (`id`, `name`) VALUES ('ca', 'Tiếng Ca-ta-lăng');
INSERT INTO `country` (`id`, `name`) VALUES ('km', 'Tiếng Campuchia');
INSERT INTO `country` (`id`, `name`) VALUES ('swb', 'Tiếng Cômo');
INSERT INTO `country` (`id`, `name`) VALUES ('hr', 'Tiếng Crô-a-ti-a');
INSERT INTO `country` (`id`, `name`) VALUES ('dv', 'Tiếng Divehi');
INSERT INTO `country` (`id`, `name`) VALUES ('dz', 'Tiếng Dzongkha');
INSERT INTO `country` (`id`, `name`) VALUES ('da', 'Tiếng Đan Mạch');
INSERT INTO `country` (`id`, `name`) VALUES ('de', 'Tiếng Đức');
INSERT INTO `country` (`id`, `name`) VALUES ('de_CH', 'Tiếng Đức Chuẩn (Thụy Sĩ)');
INSERT INTO `country` (`id`, `name`) VALUES ('gsw', 'Tiếng Đức Thụy Sĩ');
INSERT INTO `country` (`id`, `name`) VALUES ('et', 'Tiếng E-xtô-ni-a');
INSERT INTO `country` (`id`, `name`) VALUES ('efi', 'Tiếng Efik');
INSERT INTO `country` (`id`, `name`) VALUES ('fo', 'Tiếng Faore');
INSERT INTO `country` (`id`, `name`) VALUES ('fj', 'Tiếng Fiji');
INSERT INTO `country` (`id`, `name`) VALUES ('nl_BE', 'Tiếng Flemish');
INSERT INTO `country` (`id`, `name`) VALUES ('fy', 'Tiếng Frisian');
INSERT INTO `country` (`id`, `name`) VALUES ('gl', 'Tiếng Galician');
INSERT INTO `country` (`id`, `name`) VALUES ('ka', 'Tiếng Georgian');
INSERT INTO `country` (`id`, `name`) VALUES ('jv', 'Tiếng Gia-va');
INSERT INTO `country` (`id`, `name`) VALUES ('gn', 'Tiếng Guarani');
INSERT INTO `country` (`id`, `name`) VALUES ('gu', 'Tiếng Gujarati');
INSERT INTO `country` (`id`, `name`) VALUES ('nl', 'Tiếng Hà Lan');
INSERT INTO `country` (`id`, `name`) VALUES ('ht', 'Tiếng Haiti');
INSERT INTO `country` (`id`, `name`) VALUES ('ko', 'Tiếng Hàn Quốc');
INSERT INTO `country` (`id`, `name`) VALUES ('ha', 'Tiếng Hausa');
INSERT INTO `country` (`id`, `name`) VALUES ('haw', 'Tiếng Hawaii');
INSERT INTO `country` (`id`, `name`) VALUES ('he', 'Tiếng Hê-brơ');
INSERT INTO `country` (`id`, `name`) VALUES ('hi', 'Tiếng Hin-đi');
INSERT INTO `country` (`id`, `name`) VALUES ('hu', 'Tiếng Hung-ga-ri');
INSERT INTO `country` (`id`, `name`) VALUES ('el', 'Tiếng Hy Lạp');
INSERT INTO `country` (`id`, `name`) VALUES ('ig', 'Tiếng Igbo');
INSERT INTO `country` (`id`, `name`) VALUES ('id', 'Tiếng In-đô-nê-xia');
INSERT INTO `country` (`id`, `name`) VALUES ('kn', 'Tiếng Kan-na-đa');
INSERT INTO `country` (`id`, `name`) VALUES ('ks', 'Tiếng Kashmiri');
INSERT INTO `country` (`id`, `name`) VALUES ('kk', 'Tiếng Kazakh');
INSERT INTO `country` (`id`, `name`) VALUES ('ia', 'Tiếng Khoa Học Quốc Tế');
INSERT INTO `country` (`id`, `name`) VALUES ('und', 'Tiếng không xác định');
INSERT INTO `country` (`id`, `name`) VALUES ('rw', 'Tiếng Kinyarwanda');
INSERT INTO `country` (`id`, `name`) VALUES ('tlh', 'Tiếng Klingon');
INSERT INTO `country` (`id`, `name`) VALUES ('ku', 'Tiếng Kurd (Iran)');
INSERT INTO `country` (`id`, `name`) VALUES ('ky', 'Tiếng Kyrgyz');
INSERT INTO `country` (`id`, `name`) VALUES ('la', 'Tiếng La-tinh');
INSERT INTO `country` (`id`, `name`) VALUES ('lo', 'Tiếng Lào');
INSERT INTO `country` (`id`, `name`) VALUES ('lv', 'Tiếng Lát-vi-a');
INSERT INTO `country` (`id`, `name`) VALUES ('ln', 'Tiếng Lingala');
INSERT INTO `country` (`id`, `name`) VALUES ('lt', 'Tiếng Lít-va');
INSERT INTO `country` (`id`, `name`) VALUES ('lb', 'Tiếng Luxembourg');
INSERT INTO `country` (`id`, `name`) VALUES ('ms', 'Tiếng Ma-lay-xi-a');
INSERT INTO `country` (`id`, `name`) VALUES ('mk', 'Tiếng Ma-xê-đô-ni-a');
INSERT INTO `country` (`id`, `name`) VALUES ('mg', 'Tiếng Malagasy');
INSERT INTO `country` (`id`, `name`) VALUES ('ml', 'Tiếng Malayalam');
INSERT INTO `country` (`id`, `name`) VALUES ('mt', 'Tiếng Mantơ');
INSERT INTO `country` (`id`, `name`) VALUES ('mi', 'Tiếng Maori');
INSERT INTO `country` (`id`, `name`) VALUES ('mr', 'Tiếng Marathi');
INSERT INTO `country` (`id`, `name`) VALUES ('my', 'Tiếng Miến Điện');
INSERT INTO `country` (`id`, `name`) VALUES ('mn', 'Tiếng Mông Cổ');
INSERT INTO `country` (`id`, `name`) VALUES ('no', 'Tiếng Na Uy');
INSERT INTO `country` (`id`, `name`) VALUES ('nb', 'Tiếng Na Uy (Bokmål)');
INSERT INTO `country` (`id`, `name`) VALUES ('nn', 'Tiếng Na Uy (Nynorsk)');
INSERT INTO `country` (`id`, `name`) VALUES ('af', 'Tiếng Nam Phi');
INSERT INTO `country` (`id`, `name`) VALUES ('bs', 'Tiếng Nam Tư');
INSERT INTO `country` (`id`, `name`) VALUES ('ne', 'Tiếng Nê-pan');
INSERT INTO `country` (`id`, `name`) VALUES ('ru', 'Tiếng Nga');
INSERT INTO `country` (`id`, `name`) VALUES ('ja', 'Tiếng Nhật');
INSERT INTO `country` (`id`, `name`) VALUES ('ny', 'Tiếng Nyanja');
INSERT INTO `country` (`id`, `name`) VALUES ('oc', 'Tiếng Occitan');
INSERT INTO `country` (`id`, `name`) VALUES ('os', 'Tiếng Ossetic');
INSERT INTO `country` (`id`, `name`) VALUES ('or', 'Tiếng Ô-ri-a');
INSERT INTO `country` (`id`, `name`) VALUES ('ps', 'Tiếng Pa-tô');
INSERT INTO `country` (`id`, `name`) VALUES ('sa', 'Tiếng Phạn');
INSERT INTO `country` (`id`, `name`) VALUES ('fr', 'Tiếng Pháp');
INSERT INTO `country` (`id`, `name`) VALUES ('fr_CA', 'Tiếng Pháp (Canada)');
INSERT INTO `country` (`id`, `name`) VALUES ('fi', 'Tiếng Phần Lan');
INSERT INTO `country` (`id`, `name`) VALUES ('fil', 'Tiếng Philipin');
INSERT INTO `country` (`id`, `name`) VALUES ('pa', 'Tiếng Punjabi');
INSERT INTO `country` (`id`, `name`) VALUES ('yue', 'Tiếng Quảng Đông');
INSERT INTO `country` (`id`, `name`) VALUES ('qu', 'Tiếng Quechua');
INSERT INTO `country` (`id`, `name`) VALUES ('eo', 'Tiếng Quốc Tế Ngữ');
INSERT INTO `country` (`id`, `name`) VALUES ('rm', 'Tiếng Rhaeto-Romance');
INSERT INTO `country` (`id`, `name`) VALUES ('ro', 'Tiếng Ru-ma-ni');
INSERT INTO `country` (`id`, `name`) VALUES ('rn', 'Tiếng Rundi');
INSERT INTO `country` (`id`, `name`) VALUES ('sm', 'Tiếng Samoa');
INSERT INTO `country` (`id`, `name`) VALUES ('sg', 'Tiếng Sango');
INSERT INTO `country` (`id`, `name`) VALUES ('cs', 'Tiếng Séc');
INSERT INTO `country` (`id`, `name`) VALUES ('sr', 'Tiếng Séc-bi');
INSERT INTO `country` (`id`, `name`) VALUES ('st', 'Tiếng Sesotho');
INSERT INTO `country` (`id`, `name`) VALUES ('sn', 'Tiếng Shona');
INSERT INTO `country` (`id`, `name`) VALUES ('sd', 'Tiếng Sin-hi');
INSERT INTO `country` (`id`, `name`) VALUES ('si', 'Tiếng Sinhala');
INSERT INTO `country` (`id`, `name`) VALUES ('ss', 'Tiếng Swati');
INSERT INTO `country` (`id`, `name`) VALUES ('tl', 'Tiếng Tagalog');
INSERT INTO `country` (`id`, `name`) VALUES ('ty', 'Tiếng Tahiti');
INSERT INTO `country` (`id`, `name`) VALUES ('tg', 'Tiếng Tajik');
INSERT INTO `country` (`id`, `name`) VALUES ('ta', 'Tiếng Tamil');
INSERT INTO `country` (`id`, `name`) VALUES ('tt', 'Tiếng Tatar');
INSERT INTO `country` (`id`, `name`) VALUES ('es', 'Tiếng Tây Ban Nha');
INSERT INTO `country` (`id`, `name`) VALUES ('es_ES', 'Tiếng Tây Ban Nha (I-bê-ri)');
INSERT INTO `country` (`id`, `name`) VALUES ('es_419', 'Tiếng Tây Ban Nha (Mỹ La tinh)');
INSERT INTO `country` (`id`, `name`) VALUES ('bo', 'Tiếng Tây Tạng');
INSERT INTO `country` (`id`, `name`) VALUES ('te', 'Tiếng Telugu');
INSERT INTO `country` (`id`, `name`) VALUES ('th', 'Tiếng Thái');
INSERT INTO `country` (`id`, `name`) VALUES ('tr', 'Tiếng Thổ Nhĩ Kỳ');
INSERT INTO `country` (`id`, `name`) VALUES ('sv', 'Tiếng Thụy Điển');
INSERT INTO `country` (`id`, `name`) VALUES ('ti', 'Tiếng Tigrigya');
INSERT INTO `country` (`id`, `name`) VALUES ('tpi', 'Tiếng Tok Pisin');
INSERT INTO `country` (`id`, `name`) VALUES ('to', 'Tiếng Tonga');
INSERT INTO `country` (`id`, `name`) VALUES ('zh', 'Tiếng Trung Quốc');
INSERT INTO `country` (`id`, `name`) VALUES ('zh_Hans', 'Tiếng Trung Quốc (Giản thể)');
INSERT INTO `country` (`id`, `name`) VALUES ('zh_Hant', 'Tiếng Trung Quốc (Phồn thể)');
INSERT INTO `country` (`id`, `name`) VALUES ('ts', 'Tiếng Tsonga');
INSERT INTO `country` (`id`, `name`) VALUES ('tn', 'Tiếng Tswana');
INSERT INTO `country` (`id`, `name`) VALUES ('tk', 'Tiếng Tuôc-men');
INSERT INTO `country` (`id`, `name`) VALUES ('tw', 'Tiếng Twi');
INSERT INTO `country` (`id`, `name`) VALUES ('uk', 'Tiếng U-crai-na');
INSERT INTO `country` (`id`, `name`) VALUES ('uz', 'Tiếng U-dơ-bếch');
INSERT INTO `country` (`id`, `name`) VALUES ('ur', 'Tiếng Uđu');
INSERT INTO `country` (`id`, `name`) VALUES ('ug', 'Tiếng Uighur');
INSERT INTO `country` (`id`, `name`) VALUES ('ve', 'Tiếng Venda');
INSERT INTO `country` (`id`, `name`) VALUES ('vi', 'Tiếng Việt');
INSERT INTO `country` (`id`, `name`) VALUES ('wo', 'Tiếng Wolof');
INSERT INTO `country` (`id`, `name`) VALUES ('sh', 'Tiếng Xéc bi - Croatia');
INSERT INTO `country` (`id`, `name`) VALUES ('cy', 'Tiếng Xentơ');
INSERT INTO `country` (`id`, `name`) VALUES ('gd', 'Tiếng Xentơ (Xcốt len)');
INSERT INTO `country` (`id`, `name`) VALUES ('sk', 'Tiếng Xlô-vác');
INSERT INTO `country` (`id`, `name`) VALUES ('sl', 'Tiếng Xlô-ven');
INSERT INTO `country` (`id`, `name`) VALUES ('so', 'Tiếng Xô-ma-li');
INSERT INTO `country` (`id`, `name`) VALUES ('su', 'Tiếng Xu đăng');
INSERT INTO `country` (`id`, `name`) VALUES ('it', 'Tiếng Ý');
INSERT INTO `country` (`id`, `name`) VALUES ('yi', 'Tiếng Y-đit');
INSERT INTO `country` (`id`, `name`) VALUES ('yo', 'Tiếng Yoruba');
INSERT INTO `country` (`id`, `name`) VALUES ('zu', 'Tiếng Zulu');
