CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('ab', 'abkhazeg');
INSERT INTO "country" ("id", "name") VALUES ('af', 'afrikaans');
INSERT INTO "country" ("id", "name") VALUES ('agq', 'aghem');
INSERT INTO "country" ("id", "name") VALUES ('de', 'alamaneg');
INSERT INTO "country" ("id", "name") VALUES ('de_AT', 'alamaneg Aostria');
INSERT INTO "country" ("id", "name") VALUES ('gsw', 'alamaneg Suis');
INSERT INTO "country" ("id", "name") VALUES ('de_CH', 'alamaneg uhel Suis');
INSERT INTO "country" ("id", "name") VALUES ('sq', 'albaneg');
INSERT INTO "country" ("id", "name") VALUES ('am', 'amhareg');
INSERT INTO "country" ("id", "name") VALUES ('ar', 'arabeg');
INSERT INTO "country" ("id", "name") VALUES ('hy', 'armenianeg');
INSERT INTO "country" ("id", "name") VALUES ('as', 'asameg');
INSERT INTO "country" ("id", "name") VALUES ('asa', 'asu');
INSERT INTO "country" ("id", "name") VALUES ('ay', 'aymara');
INSERT INTO "country" ("id", "name") VALUES ('az', 'azeri');
INSERT INTO "country" ("id", "name") VALUES ('bm', 'bambara');
INSERT INTO "country" ("id", "name") VALUES ('bas', 'basaa');
INSERT INTO "country" ("id", "name") VALUES ('be', 'belaruseg');
INSERT INTO "country" ("id", "name") VALUES ('bem', 'bemba');
INSERT INTO "country" ("id", "name") VALUES ('bez', 'bena');
INSERT INTO "country" ("id", "name") VALUES ('bn', 'bengali');
INSERT INTO "country" ("id", "name") VALUES ('my', 'birmaneg');
INSERT INTO "country" ("id", "name") VALUES ('brx', 'bodo');
INSERT INTO "country" ("id", "name") VALUES ('bs', 'bosneg');
INSERT INTO "country" ("id", "name") VALUES ('br', 'brezhoneg');
INSERT INTO "country" ("id", "name") VALUES ('bg', 'bulgareg');
INSERT INTO "country" ("id", "name") VALUES ('da', 'daneg');
INSERT INTO "country" ("id", "name") VALUES ('dv', 'divehi');
INSERT INTO "country" ("id", "name") VALUES ('zxx', 'diyezh');
INSERT INTO "country" ("id", "name") VALUES ('dz', 'dzongkha');
INSERT INTO "country" ("id", "name") VALUES ('efi', 'efik');
INSERT INTO "country" ("id", "name") VALUES ('ebu', 'embu');
INSERT INTO "country" ("id", "name") VALUES ('eo', 'esperanteg');
INSERT INTO "country" ("id", "name") VALUES ('et', 'estoneg');
INSERT INTO "country" ("id", "name") VALUES ('eu', 'euskareg');
INSERT INTO "country" ("id", "name") VALUES ('fj', 'fidjieg');
INSERT INTO "country" ("id", "name") VALUES ('fil', 'filipineg');
INSERT INTO "country" ("id", "name") VALUES ('fi', 'finneg');
INSERT INTO "country" ("id", "name") VALUES ('nl_BE', 'flandrezeg');
INSERT INTO "country" ("id", "name") VALUES ('gl', 'galizeg');
INSERT INTO "country" ("id", "name") VALUES ('fr', 'galleg');
INSERT INTO "country" ("id", "name") VALUES ('fr_CA', 'galleg Kanada');
INSERT INTO "country" ("id", "name") VALUES ('fr_CH', 'galleg Suis');
INSERT INTO "country" ("id", "name") VALUES ('el', 'gresianeg');
INSERT INTO "country" ("id", "name") VALUES ('gn', 'guarani');
INSERT INTO "country" ("id", "name") VALUES ('gu', 'gujarati');
INSERT INTO "country" ("id", "name") VALUES ('ht', 'haitieg');
INSERT INTO "country" ("id", "name") VALUES ('ha', 'haousa');
INSERT INTO "country" ("id", "name") VALUES ('haw', 'hawaieg');
INSERT INTO "country" ("id", "name") VALUES ('he', 'hebraeg');
INSERT INTO "country" ("id", "name") VALUES ('hi', 'hindi');
INSERT INTO "country" ("id", "name") VALUES ('hu', 'hungareg');
INSERT INTO "country" ("id", "name") VALUES ('ig', 'igbo');
INSERT INTO "country" ("id", "name") VALUES ('id', 'indonezeg');
INSERT INTO "country" ("id", "name") VALUES ('is', 'islandeg');
INSERT INTO "country" ("id", "name") VALUES ('it', 'italianeg');
INSERT INTO "country" ("id", "name") VALUES ('ga', 'iwerzhoneg');
INSERT INTO "country" ("id", "name") VALUES ('ja', 'japaneg');
INSERT INTO "country" ("id", "name") VALUES ('jv', 'javaneg');
INSERT INTO "country" ("id", "name") VALUES ('ka', 'jorjianeg');
INSERT INTO "country" ("id", "name") VALUES ('kea', 'kabuverdianu');
INSERT INTO "country" ("id", "name") VALUES ('kn', 'kanareg');
INSERT INTO "country" ("id", "name") VALUES ('yue', 'kantoneg');
INSERT INTO "country" ("id", "name") VALUES ('ks', 'kashmiri');
INSERT INTO "country" ("id", "name") VALUES ('ca', 'katalaneg');
INSERT INTO "country" ("id", "name") VALUES ('kk', 'kazak');
INSERT INTO "country" ("id", "name") VALUES ('qu', 'kechuaeg');
INSERT INTO "country" ("id", "name") VALUES ('cy', 'kembraeg');
INSERT INTO "country" ("id", "name") VALUES ('km', 'khmer');
INSERT INTO "country" ("id", "name") VALUES ('rw', 'kinyarwanda');
INSERT INTO "country" ("id", "name") VALUES ('ky', 'kirgiz');
INSERT INTO "country" ("id", "name") VALUES ('swb', 'komoreg');
INSERT INTO "country" ("id", "name") VALUES ('ko', 'koreaneg');
INSERT INTO "country" ("id", "name") VALUES ('hr', 'kroateg');
INSERT INTO "country" ("id", "name") VALUES ('ku', 'kurdeg');
INSERT INTO "country" ("id", "name") VALUES ('lah', 'lahnda');
INSERT INTO "country" ("id", "name") VALUES ('lo', 'laoseg');
INSERT INTO "country" ("id", "name") VALUES ('la', 'latin');
INSERT INTO "country" ("id", "name") VALUES ('lv', 'latvieg');
INSERT INTO "country" ("id", "name") VALUES ('ln', 'lingala');
INSERT INTO "country" ("id", "name") VALUES ('lt', 'lituaneg');
INSERT INTO "country" ("id", "name") VALUES ('lb', 'luksembourgeg');
INSERT INTO "country" ("id", "name") VALUES ('luy', 'luyia');
INSERT INTO "country" ("id", "name") VALUES ('mk', 'makedoneg');
INSERT INTO "country" ("id", "name") VALUES ('ml', 'malayalam');
INSERT INTO "country" ("id", "name") VALUES ('ms', 'malayseg');
INSERT INTO "country" ("id", "name") VALUES ('mg', 'malgacheg');
INSERT INTO "country" ("id", "name") VALUES ('mt', 'malteg');
INSERT INTO "country" ("id", "name") VALUES ('mi', 'maori');
INSERT INTO "country" ("id", "name") VALUES ('mr', 'marathi');
INSERT INTO "country" ("id", "name") VALUES ('mn', 'mongoleg');
INSERT INTO "country" ("id", "name") VALUES ('nd', 'ndebele an Norzh');
INSERT INTO "country" ("id", "name") VALUES ('nl', 'nederlandeg');
INSERT INTO "country" ("id", "name") VALUES ('ne', 'nepaleg');
INSERT INTO "country" ("id", "name") VALUES ('no', 'norvegeg');
INSERT INTO "country" ("id", "name") VALUES ('nb', 'norvegeg bokmål');
INSERT INTO "country" ("id", "name") VALUES ('nn', 'norvegeg nynorsk');
INSERT INTO "country" ("id", "name") VALUES ('ny', 'nyanja');
INSERT INTO "country" ("id", "name") VALUES ('or', 'oriya');
INSERT INTO "country" ("id", "name") VALUES ('os', 'oseteg');
INSERT INTO "country" ("id", "name") VALUES ('ug', 'ouigoureg');
INSERT INTO "country" ("id", "name") VALUES ('ur', 'ourdou');
INSERT INTO "country" ("id", "name") VALUES ('uz', 'ouzbekeg');
INSERT INTO "country" ("id", "name") VALUES ('ps', 'pachto');
INSERT INTO "country" ("id", "name") VALUES ('fa', 'perseg');
INSERT INTO "country" ("id", "name") VALUES ('pl', 'poloneg');
INSERT INTO "country" ("id", "name") VALUES ('pt', 'portugaleg');
INSERT INTO "country" ("id", "name") VALUES ('pt_BR', 'portugaleg Brazil');
INSERT INTO "country" ("id", "name") VALUES ('pt_PT', 'portugaleg iberek');
INSERT INTO "country" ("id", "name") VALUES ('pa', 'punjabi');
INSERT INTO "country" ("id", "name") VALUES ('rm', 'romañcheg');
INSERT INTO "country" ("id", "name") VALUES ('rof', 'rombo');
INSERT INTO "country" ("id", "name") VALUES ('ro', 'roumaneg');
INSERT INTO "country" ("id", "name") VALUES ('rn', 'rundi');
INSERT INTO "country" ("id", "name") VALUES ('ru', 'rusianeg');
INSERT INTO "country" ("id", "name") VALUES ('rwk', 'rwa');
INSERT INTO "country" ("id", "name") VALUES ('se', 'sámi an Norzh');
INSERT INTO "country" ("id", "name") VALUES ('sm', 'samoan');
INSERT INTO "country" ("id", "name") VALUES ('sg', 'sango');
INSERT INTO "country" ("id", "name") VALUES ('sa', 'sanskriteg');
INSERT INTO "country" ("id", "name") VALUES ('en', 'saozneg');
INSERT INTO "country" ("id", "name") VALUES ('en_AU', 'saozneg Aostralia');
INSERT INTO "country" ("id", "name") VALUES ('en_GB', 'saozneg Breizh-Veur');
INSERT INTO "country" ("id", "name") VALUES ('en_CA', 'saozneg Kanada');
INSERT INTO "country" ("id", "name") VALUES ('en_US', 'saozneg S.U.');
INSERT INTO "country" ("id", "name") VALUES ('sh', 'serb-kroateg');
INSERT INTO "country" ("id", "name") VALUES ('sr', 'serbeg');
INSERT INTO "country" ("id", "name") VALUES ('sn', 'shona');
INSERT INTO "country" ("id", "name") VALUES ('zh', 'sinaeg');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hans', 'sinaeg eeunaet');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hant', 'sinaeg hengounel');
INSERT INTO "country" ("id", "name") VALUES ('sd', 'sindhi');
INSERT INTO "country" ("id", "name") VALUES ('si', 'singhaleg');
INSERT INTO "country" ("id", "name") VALUES ('sk', 'slovakeg');
INSERT INTO "country" ("id", "name") VALUES ('sl', 'sloveneg');
INSERT INTO "country" ("id", "name") VALUES ('so', 'somali');
INSERT INTO "country" ("id", "name") VALUES ('nso', 'sotho an Norzh');
INSERT INTO "country" ("id", "name") VALUES ('st', 'sotho ar Su');
INSERT INTO "country" ("id", "name") VALUES ('es', 'spagnoleg');
INSERT INTO "country" ("id", "name") VALUES ('es_419', 'spagnoleg Amerika latin');
INSERT INTO "country" ("id", "name") VALUES ('es_ES', 'spagnoleg iberek');
INSERT INTO "country" ("id", "name") VALUES ('su', 'sundaneg');
INSERT INTO "country" ("id", "name") VALUES ('sv', 'svedeg');
INSERT INTO "country" ("id", "name") VALUES ('sw', 'swahili');
INSERT INTO "country" ("id", "name") VALUES ('ss', 'swati');
INSERT INTO "country" ("id", "name") VALUES ('tg', 'tadjik');
INSERT INTO "country" ("id", "name") VALUES ('tl', 'tagalog');
INSERT INTO "country" ("id", "name") VALUES ('ty', 'tahitianeg');
INSERT INTO "country" ("id", "name") VALUES ('ta', 'tamileg');
INSERT INTO "country" ("id", "name") VALUES ('cs', 'tchekeg');
INSERT INTO "country" ("id", "name") VALUES ('te', 'telougou');
INSERT INTO "country" ("id", "name") VALUES ('tet', 'tetum');
INSERT INTO "country" ("id", "name") VALUES ('th', 'thai');
INSERT INTO "country" ("id", "name") VALUES ('bo', 'tibetaneg');
INSERT INTO "country" ("id", "name") VALUES ('ti', 'tigrigna');
INSERT INTO "country" ("id", "name") VALUES ('tpi', 'tok pisin');
INSERT INTO "country" ("id", "name") VALUES ('to', 'tonga');
INSERT INTO "country" ("id", "name") VALUES ('ts', 'tsonga');
INSERT INTO "country" ("id", "name") VALUES ('tn', 'tswana');
INSERT INTO "country" ("id", "name") VALUES ('tr', 'turkeg');
INSERT INTO "country" ("id", "name") VALUES ('tk', 'turkmeneg');
INSERT INTO "country" ("id", "name") VALUES ('uk', 'ukraineg');
INSERT INTO "country" ("id", "name") VALUES ('ve', 'venda');
INSERT INTO "country" ("id", "name") VALUES ('vi', 'vietnameg');
INSERT INTO "country" ("id", "name") VALUES ('wae', 'walser');
INSERT INTO "country" ("id", "name") VALUES ('wo', 'wolof');
INSERT INTO "country" ("id", "name") VALUES ('xh', 'xhosa');
INSERT INTO "country" ("id", "name") VALUES ('sah', 'yakouteg');
INSERT INTO "country" ("id", "name") VALUES ('und', 'yezh dianav');
INSERT INTO "country" ("id", "name") VALUES ('yo', 'yorouba');
INSERT INTO "country" ("id", "name") VALUES ('zu', 'zouloueg');
