CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('ab', 'Abkhazia');
INSERT INTO "country" ("id", "name") VALUES ('af', 'Afrikaans');
INSERT INTO "country" ("id", "name") VALUES ('sq', 'Albania');
INSERT INTO "country" ("id", "name") VALUES ('am', 'Amharic');
INSERT INTO "country" ("id", "name") VALUES ('ar', 'Arab');
INSERT INTO "country" ("id", "name") VALUES ('hy', 'Armenia');
INSERT INTO "country" ("id", "name") VALUES ('as', 'Assam');
INSERT INTO "country" ("id", "name") VALUES ('ay', 'Aymara');
INSERT INTO "country" ("id", "name") VALUES ('az', 'Azerbaijan');
INSERT INTO "country" ("id", "name") VALUES ('en_US', 'Bahasa Inggeris AS');
INSERT INTO "country" ("id", "name") VALUES ('ms', 'Bahasa Melayu');
INSERT INTO "country" ("id", "name") VALUES ('und', 'Bahasa Tidak Diketahui');
INSERT INTO "country" ("id", "name") VALUES ('eu', 'Basque');
INSERT INTO "country" ("id", "name") VALUES ('nl', 'Belanda');
INSERT INTO "country" ("id", "name") VALUES ('be', 'Belarus');
INSERT INTO "country" ("id", "name") VALUES ('bn', 'Benggala');
INSERT INTO "country" ("id", "name") VALUES ('nb', 'Bokmål Norway');
INSERT INTO "country" ("id", "name") VALUES ('bs', 'Bosnia');
INSERT INTO "country" ("id", "name") VALUES ('bg', 'Bulgaria');
INSERT INTO "country" ("id", "name") VALUES ('my', 'Burma');
INSERT INTO "country" ("id", "name") VALUES ('ca', 'Catalonia');
INSERT INTO "country" ("id", "name") VALUES ('zh', 'Cina');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hans', 'Cina Ringkas');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hant', 'Cina Tradisional');
INSERT INTO "country" ("id", "name") VALUES ('hr', 'Croat');
INSERT INTO "country" ("id", "name") VALUES ('cs', 'Czech');
INSERT INTO "country" ("id", "name") VALUES ('da', 'Denmark');
INSERT INTO "country" ("id", "name") VALUES ('dv', 'Divehi');
INSERT INTO "country" ("id", "name") VALUES ('dz', 'Dzongkha');
INSERT INTO "country" ("id", "name") VALUES ('efi', 'Efik');
INSERT INTO "country" ("id", "name") VALUES ('eo', 'Esperanto');
INSERT INTO "country" ("id", "name") VALUES ('et', 'Estonia');
INSERT INTO "country" ("id", "name") VALUES ('fo', 'Faroe');
INSERT INTO "country" ("id", "name") VALUES ('fj', 'Fiji');
INSERT INTO "country" ("id", "name") VALUES ('fil', 'Filipina');
INSERT INTO "country" ("id", "name") VALUES ('fi', 'Finland');
INSERT INTO "country" ("id", "name") VALUES ('nl_BE', 'Flemish');
INSERT INTO "country" ("id", "name") VALUES ('fy', 'Frisian');
INSERT INTO "country" ("id", "name") VALUES ('gl', 'Galicia');
INSERT INTO "country" ("id", "name") VALUES ('ka', 'Georgia');
INSERT INTO "country" ("id", "name") VALUES ('el', 'Greek');
INSERT INTO "country" ("id", "name") VALUES ('gn', 'Guarani');
INSERT INTO "country" ("id", "name") VALUES ('gu', 'Gujerat');
INSERT INTO "country" ("id", "name") VALUES ('ht', 'Haiti');
INSERT INTO "country" ("id", "name") VALUES ('ha', 'Hausa');
INSERT INTO "country" ("id", "name") VALUES ('haw', 'Hawaii');
INSERT INTO "country" ("id", "name") VALUES ('hi', 'Hindi');
INSERT INTO "country" ("id", "name") VALUES ('hu', 'Hungary');
INSERT INTO "country" ("id", "name") VALUES ('he', 'Ibrani');
INSERT INTO "country" ("id", "name") VALUES ('is', 'Iceland');
INSERT INTO "country" ("id", "name") VALUES ('ig', 'Igbo');
INSERT INTO "country" ("id", "name") VALUES ('id', 'Indonesia');
INSERT INTO "country" ("id", "name") VALUES ('en', 'Inggeris');
INSERT INTO "country" ("id", "name") VALUES ('en_AU', 'Inggeris Australia');
INSERT INTO "country" ("id", "name") VALUES ('en_GB', 'Inggeris British');
INSERT INTO "country" ("id", "name") VALUES ('en_CA', 'Inggeris Kanada');
INSERT INTO "country" ("id", "name") VALUES ('ga', 'Ireland');
INSERT INTO "country" ("id", "name") VALUES ('it', 'Itali');
INSERT INTO "country" ("id", "name") VALUES ('jv', 'Jawa');
INSERT INTO "country" ("id", "name") VALUES ('ja', 'Jepun');
INSERT INTO "country" ("id", "name") VALUES ('de', 'Jerman');
INSERT INTO "country" ("id", "name") VALUES ('de_AT', 'Jerman Austria');
INSERT INTO "country" ("id", "name") VALUES ('de_CH', 'Jerman Halus Switzerland');
INSERT INTO "country" ("id", "name") VALUES ('gsw', 'Jerman Switzerland');
INSERT INTO "country" ("id", "name") VALUES ('kn', 'Kannada');
INSERT INTO "country" ("id", "name") VALUES ('ks', 'Kashmiri');
INSERT INTO "country" ("id", "name") VALUES ('kk', 'Kazakhstan');
INSERT INTO "country" ("id", "name") VALUES ('km', 'Khmer');
INSERT INTO "country" ("id", "name") VALUES ('rw', 'Kinyarwanda');
INSERT INTO "country" ("id", "name") VALUES ('ky', 'Kirghiz');
INSERT INTO "country" ("id", "name") VALUES ('ko', 'Korea');
INSERT INTO "country" ("id", "name") VALUES ('ku', 'Kurdish');
INSERT INTO "country" ("id", "name") VALUES ('lo', 'Laos');
INSERT INTO "country" ("id", "name") VALUES ('la', 'Latin');
INSERT INTO "country" ("id", "name") VALUES ('lv', 'Latvia');
INSERT INTO "country" ("id", "name") VALUES ('ln', 'Lingala');
INSERT INTO "country" ("id", "name") VALUES ('lt', 'Lithuania');
INSERT INTO "country" ("id", "name") VALUES ('lb', 'Luxembourg');
INSERT INTO "country" ("id", "name") VALUES ('mk', 'Macedonia');
INSERT INTO "country" ("id", "name") VALUES ('mg', 'Malagasy');
INSERT INTO "country" ("id", "name") VALUES ('ml', 'Malayalam');
INSERT INTO "country" ("id", "name") VALUES ('mt', 'Malta');
INSERT INTO "country" ("id", "name") VALUES ('mi', 'Maori');
INSERT INTO "country" ("id", "name") VALUES ('mr', 'Marathi');
INSERT INTO "country" ("id", "name") VALUES ('mn', 'Mongolia');
INSERT INTO "country" ("id", "name") VALUES ('nd', 'Ndebele Utara');
INSERT INTO "country" ("id", "name") VALUES ('ne', 'Nepal');
INSERT INTO "country" ("id", "name") VALUES ('ny', 'Nyanja');
INSERT INTO "country" ("id", "name") VALUES ('nn', 'Nynorsk Norway');
INSERT INTO "country" ("id", "name") VALUES ('or', 'Oriya');
INSERT INTO "country" ("id", "name") VALUES ('os', 'Ossete');
INSERT INTO "country" ("id", "name") VALUES ('fa', 'Parsi');
INSERT INTO "country" ("id", "name") VALUES ('ps', 'Pashto');
INSERT INTO "country" ("id", "name") VALUES ('fr', 'Perancis');
INSERT INTO "country" ("id", "name") VALUES ('fr_CA', 'Perancis Kanada');
INSERT INTO "country" ("id", "name") VALUES ('fr_CH', 'Perancis Switzerland');
INSERT INTO "country" ("id", "name") VALUES ('pl', 'Poland');
INSERT INTO "country" ("id", "name") VALUES ('pt', 'Portugis');
INSERT INTO "country" ("id", "name") VALUES ('pt_BR', 'Portugis Brazil');
INSERT INTO "country" ("id", "name") VALUES ('pt_PT', 'Portugis Iberia');
INSERT INTO "country" ("id", "name") VALUES ('pa', 'Punjabi');
INSERT INTO "country" ("id", "name") VALUES ('qu', 'Quechua');
INSERT INTO "country" ("id", "name") VALUES ('ro', 'Romania');
INSERT INTO "country" ("id", "name") VALUES ('rm', 'Romansh');
INSERT INTO "country" ("id", "name") VALUES ('rn', 'Rundi');
INSERT INTO "country" ("id", "name") VALUES ('ru', 'Rusia');
INSERT INTO "country" ("id", "name") VALUES ('se', 'Sami Utara');
INSERT INTO "country" ("id", "name") VALUES ('sm', 'Samoa');
INSERT INTO "country" ("id", "name") VALUES ('sg', 'Sango');
INSERT INTO "country" ("id", "name") VALUES ('sa', 'Sanskrit');
INSERT INTO "country" ("id", "name") VALUES ('gd', 'Scots Gaelic');
INSERT INTO "country" ("id", "name") VALUES ('es', 'Sepanyol');
INSERT INTO "country" ("id", "name") VALUES ('es_419', 'Sepanyol Amerika Latin');
INSERT INTO "country" ("id", "name") VALUES ('es_ES', 'Sepanyol Iberia');
INSERT INTO "country" ("id", "name") VALUES ('sr', 'Serbia');
INSERT INTO "country" ("id", "name") VALUES ('sh', 'SerboCroatia');
INSERT INTO "country" ("id", "name") VALUES ('sn', 'Shona');
INSERT INTO "country" ("id", "name") VALUES ('sd', 'Sindhi');
INSERT INTO "country" ("id", "name") VALUES ('si', 'Sinhala');
INSERT INTO "country" ("id", "name") VALUES ('sk', 'Slovak');
INSERT INTO "country" ("id", "name") VALUES ('sl', 'Slovenia');
INSERT INTO "country" ("id", "name") VALUES ('so', 'Somali');
INSERT INTO "country" ("id", "name") VALUES ('st', 'Sotho Selatan');
INSERT INTO "country" ("id", "name") VALUES ('nso', 'Sotho Utara');
INSERT INTO "country" ("id", "name") VALUES ('su', 'Sunda');
INSERT INTO "country" ("id", "name") VALUES ('sw', 'Swahili');
INSERT INTO "country" ("id", "name") VALUES ('ss', 'Swati');
INSERT INTO "country" ("id", "name") VALUES ('sv', 'Sweden');
INSERT INTO "country" ("id", "name") VALUES ('ty', 'Tahiti');
INSERT INTO "country" ("id", "name") VALUES ('tg', 'Tajik');
INSERT INTO "country" ("id", "name") VALUES ('ta', 'Tamil');
INSERT INTO "country" ("id", "name") VALUES ('tt', 'Tatar');
INSERT INTO "country" ("id", "name") VALUES ('te', 'Telugu');
INSERT INTO "country" ("id", "name") VALUES ('tet', 'Tetum');
INSERT INTO "country" ("id", "name") VALUES ('th', 'Thai');
INSERT INTO "country" ("id", "name") VALUES ('bo', 'Tibet');
INSERT INTO "country" ("id", "name") VALUES ('zxx', 'Tidak kandungan linguistik');
INSERT INTO "country" ("id", "name") VALUES ('ti', 'Tigrinya');
INSERT INTO "country" ("id", "name") VALUES ('tpi', 'Tok Pisin');
INSERT INTO "country" ("id", "name") VALUES ('to', 'Tonga');
INSERT INTO "country" ("id", "name") VALUES ('ts', 'Tsonga');
INSERT INTO "country" ("id", "name") VALUES ('tn', 'Tswana');
INSERT INTO "country" ("id", "name") VALUES ('tr', 'Turki');
INSERT INTO "country" ("id", "name") VALUES ('tk', 'Turkmen');
INSERT INTO "country" ("id", "name") VALUES ('ug', 'Uighur');
INSERT INTO "country" ("id", "name") VALUES ('uk', 'Ukraine');
INSERT INTO "country" ("id", "name") VALUES ('ur', 'Urdu');
INSERT INTO "country" ("id", "name") VALUES ('uz', 'Uzbekistan');
INSERT INTO "country" ("id", "name") VALUES ('ve', 'Venda');
INSERT INTO "country" ("id", "name") VALUES ('vi', 'Vietnam');
INSERT INTO "country" ("id", "name") VALUES ('cy', 'Wales');
INSERT INTO "country" ("id", "name") VALUES ('wo', 'Wolof');
INSERT INTO "country" ("id", "name") VALUES ('xh', 'Xhosa');
INSERT INTO "country" ("id", "name") VALUES ('yo', 'Yoruba');
INSERT INTO "country" ("id", "name") VALUES ('zu', 'Zulu');
