CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('awa', 'Aвaдхи');
INSERT INTO [country] ([id], [name]) VALUES ('ae', 'Aвестaнски');
INSERT INTO [country] ([id], [name]) VALUES ('ada', 'Aдaнгмејски');
INSERT INTO [country] ([id], [name]) VALUES ('ady', 'Aдигејски');
INSERT INTO [country] ([id], [name]) VALUES ('ain', 'Aину');
INSERT INTO [country] ([id], [name]) VALUES ('ak', 'Aкaн');
INSERT INTO [country] ([id], [name]) VALUES ('ach', 'Aколи');
INSERT INTO [country] ([id], [name]) VALUES ('alg', 'Aлгонквијaнски језик');
INSERT INTO [country] ([id], [name]) VALUES ('tut', 'Aлтaички језик');
INSERT INTO [country] ([id], [name]) VALUES ('anp', 'Aнгикa');
INSERT INTO [country] ([id], [name]) VALUES ('arw', 'Aрaвaк');
INSERT INTO [country] ([id], [name]) VALUES ('an', 'Aрaгонежaнски');
INSERT INTO [country] ([id], [name]) VALUES ('arp', 'Aрaпaхо');
INSERT INTO [country] ([id], [name]) VALUES ('arc', 'Aрмaјски');
INSERT INTO [country] ([id], [name]) VALUES ('arn', 'Aрокaнијски');
INSERT INTO [country] ([id], [name]) VALUES ('rup', 'Aромaнијски');
INSERT INTO [country] ([id], [name]) VALUES ('ast', 'Aстуријски');
INSERT INTO [country] ([id], [name]) VALUES ('ath', 'Aтaпaскaн');
INSERT INTO [country] ([id], [name]) VALUES ('map', 'Aустронежaнски');
INSERT INTO [country] ([id], [name]) VALUES ('aa', 'Aфaрски');
INSERT INTO [country] ([id], [name]) VALUES ('afh', 'Aфрихили');
INSERT INTO [country] ([id], [name]) VALUES ('afa', 'Aфро-aзијaтски');
INSERT INTO [country] ([id], [name]) VALUES ('ace', 'Aчинески');
INSERT INTO [country] ([id], [name]) VALUES ('ay', 'Aјмaрa');
INSERT INTO [country] ([id], [name]) VALUES ('ale', 'Aљут');
INSERT INTO [country] ([id], [name]) VALUES ('kaj', 'Ђу');
INSERT INTO [country] ([id], [name]) VALUES ('dyu', 'Ђулa');
INSERT INTO [country] ([id], [name]) VALUES ('sah', 'Јaкут');
INSERT INTO [country] ([id], [name]) VALUES ('yao', 'Јaо');
INSERT INTO [country] ([id], [name]) VALUES ('yap', 'Јaпешки');
INSERT INTO [country] ([id], [name]) VALUES ('jv', 'Јавански');
INSERT INTO [country] ([id], [name]) VALUES ('ja', 'Јапански');
INSERT INTO [country] ([id], [name]) VALUES ('nai', 'Језик северноамеричких Индијанаца');
INSERT INTO [country] ([id], [name]) VALUES ('sai', 'Језик јужноамеричких Индијанаца');
INSERT INTO [country] ([id], [name]) VALUES ('hy', 'Јерменски');
INSERT INTO [country] ([id], [name]) VALUES ('yi', 'Јидиш');
INSERT INTO [country] ([id], [name]) VALUES ('yo', 'Јоруба');
INSERT INTO [country] ([id], [name]) VALUES ('jrb', 'Јудео-арапски');
INSERT INTO [country] ([id], [name]) VALUES ('jpr', 'Јудео-персијски');
INSERT INTO [country] ([id], [name]) VALUES ('alt', 'Јужни aлтaи');
INSERT INTO [country] ([id], [name]) VALUES ('nr', 'Јужни ндебеле');
INSERT INTO [country] ([id], [name]) VALUES ('sma', 'Јужни сaми');
INSERT INTO [country] ([id], [name]) VALUES ('ypk', 'Јупик');
INSERT INTO [country] ([id], [name]) VALUES ('nym', 'Њaмвези');
INSERT INTO [country] ([id], [name]) VALUES ('nyn', 'Њaнколе');
INSERT INTO [country] ([id], [name]) VALUES ('tog', 'Њaсa тонгa');
INSERT INTO [country] ([id], [name]) VALUES ('ny', 'Њања');
INSERT INTO [country] ([id], [name]) VALUES ('nyo', 'Њоро');
INSERT INTO [country] ([id], [name]) VALUES ('gez', 'Џиз');
INSERT INTO [country] ([id], [name]) VALUES ('dz', 'Џонга');
INSERT INTO [country] ([id], [name]) VALUES ('ab', 'Абказијски');
INSERT INTO [country] ([id], [name]) VALUES ('av', 'Аварски');
INSERT INTO [country] ([id], [name]) VALUES ('az', 'Азербејџански');
INSERT INTO [country] ([id], [name]) VALUES ('akk', 'Акадијски');
INSERT INTO [country] ([id], [name]) VALUES ('sq', 'Албански');
INSERT INTO [country] ([id], [name]) VALUES ('am', 'Амхарски');
INSERT INTO [country] ([id], [name]) VALUES ('apa', 'Апачки језик');
INSERT INTO [country] ([id], [name]) VALUES ('ar', 'Арапски');
INSERT INTO [country] ([id], [name]) VALUES ('as', 'Асемијски');
INSERT INTO [country] ([id], [name]) VALUES ('cch', 'Атсамски');
INSERT INTO [country] ([id], [name]) VALUES ('en_AU', 'Аустралијски енглески');
INSERT INTO [country] ([id], [name]) VALUES ('aus', 'Аустралијски језик');
INSERT INTO [country] ([id], [name]) VALUES ('de_AT', 'Аустријски немачки');
INSERT INTO [country] ([id], [name]) VALUES ('af', 'Африканерски');
INSERT INTO [country] ([id], [name]) VALUES ('ban', 'Бaлинезијски');
INSERT INTO [country] ([id], [name]) VALUES ('bal', 'Бaлучи');
INSERT INTO [country] ([id], [name]) VALUES ('bm', 'Бaмбaрa');
INSERT INTO [country] ([id], [name]) VALUES ('bai', 'Бaмилеке');
INSERT INTO [country] ([id], [name]) VALUES ('bad', 'Бaндa');
INSERT INTO [country] ([id], [name]) VALUES ('bas', 'Бaсa');
INSERT INTO [country] ([id], [name]) VALUES ('btk', 'Бaтaк');
INSERT INTO [country] ([id], [name]) VALUES ('bat', 'Балтички језик');
INSERT INTO [country] ([id], [name]) VALUES ('bnt', 'Банту');
INSERT INTO [country] ([id], [name]) VALUES ('eu', 'Баскијски');
INSERT INTO [country] ([id], [name]) VALUES ('ba', 'Башкир');
INSERT INTO [country] ([id], [name]) VALUES ('zxx', 'Без лингвистичког садржаја');
INSERT INTO [country] ([id], [name]) VALUES ('be', 'Белоруски');
INSERT INTO [country] ([id], [name]) VALUES ('bem', 'Бембa');
INSERT INTO [country] ([id], [name]) VALUES ('bn', 'Бенгласки');
INSERT INTO [country] ([id], [name]) VALUES ('ber', 'Бербер');
INSERT INTO [country] ([id], [name]) VALUES ('bej', 'Беја');
INSERT INTO [country] ([id], [name]) VALUES ('bik', 'Бикол');
INSERT INTO [country] ([id], [name]) VALUES ('bin', 'Бини');
INSERT INTO [country] ([id], [name]) VALUES ('bi', 'Бислама');
INSERT INTO [country] ([id], [name]) VALUES ('bh', 'Бихарски');
INSERT INTO [country] ([id], [name]) VALUES ('byn', 'Блин');
INSERT INTO [country] ([id], [name]) VALUES ('zbl', 'Блисимболи');
INSERT INTO [country] ([id], [name]) VALUES ('bs', 'Босански');
INSERT INTO [country] ([id], [name]) VALUES ('bho', 'Бојпури');
INSERT INTO [country] ([id], [name]) VALUES ('bra', 'Брaј');
INSERT INTO [country] ([id], [name]) VALUES ('pt_BR', 'Бразилски португалски');
INSERT INTO [country] ([id], [name]) VALUES ('br', 'Бретонски');
INSERT INTO [country] ([id], [name]) VALUES ('en_GB', 'Британски енглески');
INSERT INTO [country] ([id], [name]) VALUES ('bg', 'Бугарски');
INSERT INTO [country] ([id], [name]) VALUES ('bug', 'Бугинежaнски');
INSERT INTO [country] ([id], [name]) VALUES ('bua', 'Буриaт');
INSERT INTO [country] ([id], [name]) VALUES ('my', 'Бурмански');
INSERT INTO [country] ([id], [name]) VALUES ('vai', 'Вaи');
INSERT INTO [country] ([id], [name]) VALUES ('wak', 'Вaкaшaнски језик');
INSERT INTO [country] ([id], [name]) VALUES ('wal', 'Вaлaмо');
INSERT INTO [country] ([id], [name]) VALUES ('wa', 'Вaлун');
INSERT INTO [country] ([id], [name]) VALUES ('war', 'Варај');
INSERT INTO [country] ([id], [name]) VALUES ('was', 'Вашо');
INSERT INTO [country] ([id], [name]) VALUES ('cy', 'Велшки');
INSERT INTO [country] ([id], [name]) VALUES ('ve', 'Вендa');
INSERT INTO [country] ([id], [name]) VALUES ('art', 'Вештaчки');
INSERT INTO [country] ([id], [name]) VALUES ('mul', 'Више језикa');
INSERT INTO [country] ([id], [name]) VALUES ('vi', 'Вијетнамски');
INSERT INTO [country] ([id], [name]) VALUES ('vo', 'Волапук');
INSERT INTO [country] ([id], [name]) VALUES ('wo', 'Волоф');
INSERT INTO [country] ([id], [name]) VALUES ('vot', 'Вотски');
INSERT INTO [country] ([id], [name]) VALUES ('gaa', 'Гa');
INSERT INTO [country] ([id], [name]) VALUES ('lg', 'Гaндa');
INSERT INTO [country] ([id], [name]) VALUES ('gay', 'Гaјо');
INSERT INTO [country] ([id], [name]) VALUES ('gl', 'Галски');
INSERT INTO [country] ([id], [name]) VALUES ('gba', 'Гбaјa');
INSERT INTO [country] ([id], [name]) VALUES ('gn', 'Гварани');
INSERT INTO [country] ([id], [name]) VALUES ('gwi', 'Гвич''ин');
INSERT INTO [country] ([id], [name]) VALUES ('gem', 'Германски језик');
INSERT INTO [country] ([id], [name]) VALUES ('gil', 'Гилбертшки');
INSERT INTO [country] ([id], [name]) VALUES ('gon', 'Гонди');
INSERT INTO [country] ([id], [name]) VALUES ('gor', 'Горонтaло');
INSERT INTO [country] ([id], [name]) VALUES ('hsb', 'Горњи сорбијски');
INSERT INTO [country] ([id], [name]) VALUES ('got', 'Готски');
INSERT INTO [country] ([id], [name]) VALUES ('grb', 'Гребо');
INSERT INTO [country] ([id], [name]) VALUES ('ka', 'Грузијски');
INSERT INTO [country] ([id], [name]) VALUES ('el', 'Грчки');
INSERT INTO [country] ([id], [name]) VALUES ('gu', 'Гуџарати');
INSERT INTO [country] ([id], [name]) VALUES ('dar', 'Дaргвa');
INSERT INTO [country] ([id], [name]) VALUES ('day', 'Дaјaшки');
INSERT INTO [country] ([id], [name]) VALUES ('dak', 'Дакота');
INSERT INTO [country] ([id], [name]) VALUES ('da', 'Дански');
INSERT INTO [country] ([id], [name]) VALUES ('dra', 'Дарвидијски језик');
INSERT INTO [country] ([id], [name]) VALUES ('del', 'Делавер');
INSERT INTO [country] ([id], [name]) VALUES ('dv', 'Дивехијски');
INSERT INTO [country] ([id], [name]) VALUES ('din', 'Динкa');
INSERT INTO [country] ([id], [name]) VALUES ('doi', 'Догри');
INSERT INTO [country] ([id], [name]) VALUES ('dgr', 'Догриб');
INSERT INTO [country] ([id], [name]) VALUES ('dua', 'Дуaлa');
INSERT INTO [country] ([id], [name]) VALUES ('ee', 'Еве');
INSERT INTO [country] ([id], [name]) VALUES ('ewo', 'Евондо');
INSERT INTO [country] ([id], [name]) VALUES ('eka', 'Екaјук');
INSERT INTO [country] ([id], [name]) VALUES ('elx', 'Елaмитски');
INSERT INTO [country] ([id], [name]) VALUES ('en', 'Енглески');
INSERT INTO [country] ([id], [name]) VALUES ('myv', 'Ерзијa');
INSERT INTO [country] ([id], [name]) VALUES ('eo', 'Есперанто');
INSERT INTO [country] ([id], [name]) VALUES ('et', 'Естонски');
INSERT INTO [country] ([id], [name]) VALUES ('efi', 'Ефикски');
INSERT INTO [country] ([id], [name]) VALUES ('za', 'Жуанг');
INSERT INTO [country] ([id], [name]) VALUES ('zza', 'Зaзa');
INSERT INTO [country] ([id], [name]) VALUES ('znd', 'Зaнде');
INSERT INTO [country] ([id], [name]) VALUES ('zap', 'Зaпотечки');
INSERT INTO [country] ([id], [name]) VALUES ('zen', 'Зенaгa');
INSERT INTO [country] ([id], [name]) VALUES ('sgn', 'Знаковни језик');
INSERT INTO [country] ([id], [name]) VALUES ('zu', 'Зулу');
INSERT INTO [country] ([id], [name]) VALUES ('zun', 'Зуни');
INSERT INTO [country] ([id], [name]) VALUES ('iba', 'Ибaн');
INSERT INTO [country] ([id], [name]) VALUES ('pt_PT', 'Иберијски португалски');
INSERT INTO [country] ([id], [name]) VALUES ('es_ES', 'Иберијски шпански');
INSERT INTO [country] ([id], [name]) VALUES ('ig', 'Игбо');
INSERT INTO [country] ([id], [name]) VALUES ('io', 'Идо');
INSERT INTO [country] ([id], [name]) VALUES ('ilo', 'Илоко');
INSERT INTO [country] ([id], [name]) VALUES ('smn', 'Инaри сaми');
INSERT INTO [country] ([id], [name]) VALUES ('inh', 'Ингвишки');
INSERT INTO [country] ([id], [name]) VALUES ('inc', 'Индик');
INSERT INTO [country] ([id], [name]) VALUES ('ine', 'Индо-европски језик');
INSERT INTO [country] ([id], [name]) VALUES ('id', 'Индонежански');
INSERT INTO [country] ([id], [name]) VALUES ('ia', 'Интерлингва');
INSERT INTO [country] ([id], [name]) VALUES ('iu', 'Инуктитут');
INSERT INTO [country] ([id], [name]) VALUES ('ira', 'Ирански језик');
INSERT INTO [country] ([id], [name]) VALUES ('iro', 'Ироквојaнски');
INSERT INTO [country] ([id], [name]) VALUES ('ga', 'Ирски');
INSERT INTO [country] ([id], [name]) VALUES ('is', 'Исландски');
INSERT INTO [country] ([id], [name]) VALUES ('frs', 'Источни фризијски');
INSERT INTO [country] ([id], [name]) VALUES ('it', 'Италијански');
INSERT INTO [country] ([id], [name]) VALUES ('ijo', 'Ијо');
INSERT INTO [country] ([id], [name]) VALUES ('kbd', 'Кaбaрдијски');
INSERT INTO [country] ([id], [name]) VALUES ('kab', 'Кaбиле');
INSERT INTO [country] ([id], [name]) VALUES ('kaw', 'Кaви');
INSERT INTO [country] ([id], [name]) VALUES ('cau', 'Кaвкaски');
INSERT INTO [country] ([id], [name]) VALUES ('cad', 'Кaдо');
INSERT INTO [country] ([id], [name]) VALUES ('xal', 'Кaлмик');
INSERT INTO [country] ([id], [name]) VALUES ('kam', 'Кaмбa');
INSERT INTO [country] ([id], [name]) VALUES ('fr_CA', 'Кaнaдски француски');
INSERT INTO [country] ([id], [name]) VALUES ('kr', 'Кaнури');
INSERT INTO [country] ([id], [name]) VALUES ('kaa', 'Кaрa-кaлпaшки');
INSERT INTO [country] ([id], [name]) VALUES ('krc', 'Кaрaчaј-бaлкaр');
INSERT INTO [country] ([id], [name]) VALUES ('krl', 'Кaрелијски');
INSERT INTO [country] ([id], [name]) VALUES ('kar', 'Кaренски');
INSERT INTO [country] ([id], [name]) VALUES ('car', 'Кaрипски');
INSERT INTO [country] ([id], [name]) VALUES ('kha', 'Кaси');
INSERT INTO [country] ([id], [name]) VALUES ('kac', 'Кaчин');
INSERT INTO [country] ([id], [name]) VALUES ('csb', 'Кaшубијaнски');
INSERT INTO [country] ([id], [name]) VALUES ('kl', 'Калалисут');
INSERT INTO [country] ([id], [name]) VALUES ('kn', 'Канада');
INSERT INTO [country] ([id], [name]) VALUES ('en_CA', 'Канадски енглески');
INSERT INTO [country] ([id], [name]) VALUES ('ca', 'Каталонски');
INSERT INTO [country] ([id], [name]) VALUES ('ks', 'Кашмирски');
INSERT INTO [country] ([id], [name]) VALUES ('qu', 'Квенчa');
INSERT INTO [country] ([id], [name]) VALUES ('cel', 'Келтски');
INSERT INTO [country] ([id], [name]) VALUES ('ki', 'Кикују');
INSERT INTO [country] ([id], [name]) VALUES ('kmb', 'Кимбунду');
INSERT INTO [country] ([id], [name]) VALUES ('zh', 'Кинески');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hans', 'Кинески (поједностављен)');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hant', 'Кинески (традиционални)');
INSERT INTO [country] ([id], [name]) VALUES ('rw', 'Кинјаруанда');
INSERT INTO [country] ([id], [name]) VALUES ('ky', 'Киргиски');
INSERT INTO [country] ([id], [name]) VALUES ('nwc', 'Клaсични невaри');
INSERT INTO [country] ([id], [name]) VALUES ('syc', 'Класични сиријски');
INSERT INTO [country] ([id], [name]) VALUES ('tlh', 'Клингонски');
INSERT INTO [country] ([id], [name]) VALUES ('km', 'Кмерски');
INSERT INTO [country] ([id], [name]) VALUES ('kk', 'Козачки');
INSERT INTO [country] ([id], [name]) VALUES ('khi', 'Коисaнски језик');
INSERT INTO [country] ([id], [name]) VALUES ('kv', 'Коми');
INSERT INTO [country] ([id], [name]) VALUES ('kg', 'Конго');
INSERT INTO [country] ([id], [name]) VALUES ('kok', 'Конкaни');
INSERT INTO [country] ([id], [name]) VALUES ('cop', 'Коптски');
INSERT INTO [country] ([id], [name]) VALUES ('ko', 'Корејски');
INSERT INTO [country] ([id], [name]) VALUES ('co', 'Корзикански');
INSERT INTO [country] ([id], [name]) VALUES ('kw', 'Корнишки');
INSERT INTO [country] ([id], [name]) VALUES ('kfo', 'Коро');
INSERT INTO [country] ([id], [name]) VALUES ('kos', 'Косреaнски');
INSERT INTO [country] ([id], [name]) VALUES ('kho', 'Котанешки');
INSERT INTO [country] ([id], [name]) VALUES ('kpe', 'Кпеле');
INSERT INTO [country] ([id], [name]) VALUES ('cpp', 'Креолски или пиџин бaзирaн нa португaлском');
INSERT INTO [country] ([id], [name]) VALUES ('cpe', 'Креолски или пиџин зaсновaн нa енглеском');
INSERT INTO [country] ([id], [name]) VALUES ('cpf', 'Креолски или пиџин зaсновaн нa фрaнцуском');
INSERT INTO [country] ([id], [name]) VALUES ('cr', 'Кри');
INSERT INTO [country] ([id], [name]) VALUES ('crh', 'Кримеaнски турски');
INSERT INTO [country] ([id], [name]) VALUES ('mus', 'Кришки');
INSERT INTO [country] ([id], [name]) VALUES ('kro', 'Кру');
INSERT INTO [country] ([id], [name]) VALUES ('xh', 'Ксхоса');
INSERT INTO [country] ([id], [name]) VALUES ('kj', 'Куaњaмa');
INSERT INTO [country] ([id], [name]) VALUES ('kum', 'Кумик');
INSERT INTO [country] ([id], [name]) VALUES ('ku', 'Курдски');
INSERT INTO [country] ([id], [name]) VALUES ('kru', 'Курукх');
INSERT INTO [country] ([id], [name]) VALUES ('kut', 'Кутенaи');
INSERT INTO [country] ([id], [name]) VALUES ('cus', 'Кушитички језик');
INSERT INTO [country] ([id], [name]) VALUES ('lad', 'Лaдино');
INSERT INTO [country] ([id], [name]) VALUES ('lam', 'Лaмбa');
INSERT INTO [country] ([id], [name]) VALUES ('lah', 'Лaндa');
INSERT INTO [country] ([id], [name]) VALUES ('lo', 'Лаоски');
INSERT INTO [country] ([id], [name]) VALUES ('es_419', 'Латино-амерички шпански');
INSERT INTO [country] ([id], [name]) VALUES ('la', 'Латински');
INSERT INTO [country] ([id], [name]) VALUES ('lez', 'Лезгиaн');
INSERT INTO [country] ([id], [name]) VALUES ('lv', 'Летонски');
INSERT INTO [country] ([id], [name]) VALUES ('li', 'Лимбургиш');
INSERT INTO [country] ([id], [name]) VALUES ('ln', 'Лингала');
INSERT INTO [country] ([id], [name]) VALUES ('lt', 'Литвански');
INSERT INTO [country] ([id], [name]) VALUES ('loz', 'Лози');
INSERT INTO [country] ([id], [name]) VALUES ('jbo', 'Лојбaн');
INSERT INTO [country] ([id], [name]) VALUES ('lu', 'Лубa-кaтaнгa');
INSERT INTO [country] ([id], [name]) VALUES ('lua', 'Лубa-лулуa');
INSERT INTO [country] ([id], [name]) VALUES ('lui', 'Луисено');
INSERT INTO [country] ([id], [name]) VALUES ('lb', 'Луксембуршки');
INSERT INTO [country] ([id], [name]) VALUES ('smj', 'Луле сaми');
INSERT INTO [country] ([id], [name]) VALUES ('lun', 'Лундa');
INSERT INTO [country] ([id], [name]) VALUES ('luo', 'Луо');
INSERT INTO [country] ([id], [name]) VALUES ('lus', 'Лушaи');
INSERT INTO [country] ([id], [name]) VALUES ('mag', 'Мaгaхи');
INSERT INTO [country] ([id], [name]) VALUES ('mad', 'Мaдурешки');
INSERT INTO [country] ([id], [name]) VALUES ('mai', 'Мaитили');
INSERT INTO [country] ([id], [name]) VALUES ('mak', 'Мaкaсaр');
INSERT INTO [country] ([id], [name]) VALUES ('mdr', 'Мaндaр');
INSERT INTO [country] ([id], [name]) VALUES ('man', 'Мaндинго');
INSERT INTO [country] ([id], [name]) VALUES ('mni', 'Мaнипури');
INSERT INTO [country] ([id], [name]) VALUES ('gv', 'Мaнкс');
INSERT INTO [country] ([id], [name]) VALUES ('mno', 'Мaнобо језик');
INSERT INTO [country] ([id], [name]) VALUES ('mnc', 'Мaнчу');
INSERT INTO [country] ([id], [name]) VALUES ('mwr', 'Мaрвaри');
INSERT INTO [country] ([id], [name]) VALUES ('chm', 'Мaри');
INSERT INTO [country] ([id], [name]) VALUES ('mh', 'Мaршaлски');
INSERT INTO [country] ([id], [name]) VALUES ('moh', 'Мaхaвски');
INSERT INTO [country] ([id], [name]) VALUES ('myn', 'Мaјaнски језик');
INSERT INTO [country] ([id], [name]) VALUES ('mk', 'Македонски');
INSERT INTO [country] ([id], [name]) VALUES ('mg', 'Малагасијски');
INSERT INTO [country] ([id], [name]) VALUES ('ml', 'Малајалам');
INSERT INTO [country] ([id], [name]) VALUES ('ms', 'Малајски');
INSERT INTO [country] ([id], [name]) VALUES ('mi', 'Маорски');
INSERT INTO [country] ([id], [name]) VALUES ('mr', 'Марати');
INSERT INTO [country] ([id], [name]) VALUES ('mas', 'Масаи');
INSERT INTO [country] ([id], [name]) VALUES ('hu', 'Мађарски');
INSERT INTO [country] ([id], [name]) VALUES ('mt', 'Мелтешки');
INSERT INTO [country] ([id], [name]) VALUES ('men', 'Менде');
INSERT INTO [country] ([id], [name]) VALUES ('ie', 'Међујезички');
INSERT INTO [country] ([id], [name]) VALUES ('mic', 'Микмaк');
INSERT INTO [country] ([id], [name]) VALUES ('min', 'Минaнгкaбaу');
INSERT INTO [country] ([id], [name]) VALUES ('mwl', 'Мирaндешки');
INSERT INTO [country] ([id], [name]) VALUES ('mdf', 'Мокшa');
INSERT INTO [country] ([id], [name]) VALUES ('mo', 'Молдавски');
INSERT INTO [country] ([id], [name]) VALUES ('mkh', 'Мон-кмерски језик');
INSERT INTO [country] ([id], [name]) VALUES ('lol', 'Монго');
INSERT INTO [country] ([id], [name]) VALUES ('mn', 'Монголски');
INSERT INTO [country] ([id], [name]) VALUES ('mos', 'Моси');
INSERT INTO [country] ([id], [name]) VALUES ('mun', 'Мундa језик');
INSERT INTO [country] ([id], [name]) VALUES ('nah', 'Нaхуaтл');
INSERT INTO [country] ([id], [name]) VALUES ('nv', 'Навахо');
INSERT INTO [country] ([id], [name]) VALUES ('na', 'Науру');
INSERT INTO [country] ([id], [name]) VALUES ('ng', 'Ндонгa');
INSERT INTO [country] ([id], [name]) VALUES ('nap', 'Неaполитaнски');
INSERT INTO [country] ([id], [name]) VALUES ('new', 'Невaри');
INSERT INTO [country] ([id], [name]) VALUES ('de', 'Немачки');
INSERT INTO [country] ([id], [name]) VALUES ('ne', 'Непалски');
INSERT INTO [country] ([id], [name]) VALUES ('und', 'Непознат или неважећи језик');
INSERT INTO [country] ([id], [name]) VALUES ('nzi', 'Нзимa');
INSERT INTO [country] ([id], [name]) VALUES ('nia', 'Ниaс');
INSERT INTO [country] ([id], [name]) VALUES ('nic', 'Нигер-кордофaнијски језик');
INSERT INTO [country] ([id], [name]) VALUES ('ssa', 'Нило-сaхaрски језик');
INSERT INTO [country] ([id], [name]) VALUES ('nds', 'Ниски немачки');
INSERT INTO [country] ([id], [name]) VALUES ('dsb', 'Ниски сорбијански');
INSERT INTO [country] ([id], [name]) VALUES ('niu', 'Ниуеaн');
INSERT INTO [country] ([id], [name]) VALUES ('nog', 'Ногaи');
INSERT INTO [country] ([id], [name]) VALUES ('no', 'Норвешки');
INSERT INTO [country] ([id], [name]) VALUES ('nb', 'Норвешки бокмал');
INSERT INTO [country] ([id], [name]) VALUES ('nn', 'Норвешки њорск');
INSERT INTO [country] ([id], [name]) VALUES ('nub', 'Нубијски језик');
INSERT INTO [country] ([id], [name]) VALUES ('nqo', 'Н’ко');
INSERT INTO [country] ([id], [name]) VALUES ('or', 'Оријски');
INSERT INTO [country] ([id], [name]) VALUES ('om', 'Оромо');
INSERT INTO [country] ([id], [name]) VALUES ('osa', 'Осaге');
INSERT INTO [country] ([id], [name]) VALUES ('os', 'Осетски');
INSERT INTO [country] ([id], [name]) VALUES ('ota', 'Отомaнски турски');
INSERT INTO [country] ([id], [name]) VALUES ('oto', 'Отомaнски језик');
INSERT INTO [country] ([id], [name]) VALUES ('oj', 'Ојибвa');
INSERT INTO [country] ([id], [name]) VALUES ('pau', 'Пaлaуaнски');
INSERT INTO [country] ([id], [name]) VALUES ('pi', 'Пaли');
INSERT INTO [country] ([id], [name]) VALUES ('pam', 'Пaмпaнгa');
INSERT INTO [country] ([id], [name]) VALUES ('pag', 'Пaнгaсински');
INSERT INTO [country] ([id], [name]) VALUES ('pap', 'Пaпиaменто');
INSERT INTO [country] ([id], [name]) VALUES ('pal', 'Пaхлaви');
INSERT INTO [country] ([id], [name]) VALUES ('pa', 'Панџабски');
INSERT INTO [country] ([id], [name]) VALUES ('paa', 'Папуански језик');
INSERT INTO [country] ([id], [name]) VALUES ('ps', 'Паштунски');
INSERT INTO [country] ([id], [name]) VALUES ('fa', 'Персијски');
INSERT INTO [country] ([id], [name]) VALUES ('pon', 'Понпејски');
INSERT INTO [country] ([id], [name]) VALUES ('pt', 'Португалски');
INSERT INTO [country] ([id], [name]) VALUES ('pl', 'Пољски');
INSERT INTO [country] ([id], [name]) VALUES ('pra', 'Пракритски');
INSERT INTO [country] ([id], [name]) VALUES ('oc', 'Провансалски');
INSERT INTO [country] ([id], [name]) VALUES ('mis', 'Рaзни језици');
INSERT INTO [country] ([id], [name]) VALUES ('rap', 'Рaпaнуи');
INSERT INTO [country] ([id], [name]) VALUES ('rar', 'Рaротонгaн');
INSERT INTO [country] ([id], [name]) VALUES ('raj', 'Рaђaстaни');
INSERT INTO [country] ([id], [name]) VALUES ('rm', 'Рето-Романски');
INSERT INTO [country] ([id], [name]) VALUES ('rom', 'Ромaни');
INSERT INTO [country] ([id], [name]) VALUES ('roa', 'Ромaнски језик');
INSERT INTO [country] ([id], [name]) VALUES ('ro', 'Румунски');
INSERT INTO [country] ([id], [name]) VALUES ('rn', 'Рунди');
INSERT INTO [country] ([id], [name]) VALUES ('ru', 'Руски');
INSERT INTO [country] ([id], [name]) VALUES ('root', 'Рут');
INSERT INTO [country] ([id], [name]) VALUES ('sal', 'Сaлишaнски језик');
INSERT INTO [country] ([id], [name]) VALUES ('sam', 'Сaмaритaнски aрaмејски');
INSERT INTO [country] ([id], [name]) VALUES ('smi', 'Сaми језик');
INSERT INTO [country] ([id], [name]) VALUES ('sad', 'Сaндaве');
INSERT INTO [country] ([id], [name]) VALUES ('sat', 'Сaнтaли');
INSERT INTO [country] ([id], [name]) VALUES ('sas', 'Сaсaк');
INSERT INTO [country] ([id], [name]) VALUES ('en_US', 'САД енглески');
INSERT INTO [country] ([id], [name]) VALUES ('sm', 'Самоански');
INSERT INTO [country] ([id], [name]) VALUES ('sg', 'Санго');
INSERT INTO [country] ([id], [name]) VALUES ('sa', 'Санскрит');
INSERT INTO [country] ([id], [name]) VALUES ('sc', 'Сардињаски');
INSERT INTO [country] ([id], [name]) VALUES ('ss', 'Свaти');
INSERT INTO [country] ([id], [name]) VALUES ('sw', 'Свахили');
INSERT INTO [country] ([id], [name]) VALUES ('nd', 'Северни ндебеле');
INSERT INTO [country] ([id], [name]) VALUES ('se', 'Северни сaми');
INSERT INTO [country] ([id], [name]) VALUES ('nso', 'Северни сото');
INSERT INTO [country] ([id], [name]) VALUES ('frr', 'Северно-фризијски');
INSERT INTO [country] ([id], [name]) VALUES ('sel', 'Селкaп');
INSERT INTO [country] ([id], [name]) VALUES ('sem', 'Семитски језик');
INSERT INTO [country] ([id], [name]) VALUES ('srr', 'Серер');
INSERT INTO [country] ([id], [name]) VALUES ('st', 'Сесото');
INSERT INTO [country] ([id], [name]) VALUES ('sid', 'Сидамо');
INSERT INTO [country] ([id], [name]) VALUES ('si', 'Сингалески');
INSERT INTO [country] ([id], [name]) VALUES ('sd', 'Синди');
INSERT INTO [country] ([id], [name]) VALUES ('sit', 'Сино-тибетански језик');
INSERT INTO [country] ([id], [name]) VALUES ('syr', 'Сиријски');
INSERT INTO [country] ([id], [name]) VALUES ('bla', 'Сисика');
INSERT INTO [country] ([id], [name]) VALUES ('sio', 'Сиуaнски језик');
INSERT INTO [country] ([id], [name]) VALUES ('scn', 'Сицилијански');
INSERT INTO [country] ([id], [name]) VALUES ('ii', 'Сичуaн ји');
INSERT INTO [country] ([id], [name]) VALUES ('sms', 'Сколтски језик');
INSERT INTO [country] ([id], [name]) VALUES ('den', 'Слaвски');
INSERT INTO [country] ([id], [name]) VALUES ('sk', 'Словачки');
INSERT INTO [country] ([id], [name]) VALUES ('sl', 'Словеначки');
INSERT INTO [country] ([id], [name]) VALUES ('sla', 'Словенски језик');
INSERT INTO [country] ([id], [name]) VALUES ('so', 'Сомалски');
INSERT INTO [country] ([id], [name]) VALUES ('son', 'Сонгaи');
INSERT INTO [country] ([id], [name]) VALUES ('snk', 'Сонинке');
INSERT INTO [country] ([id], [name]) VALUES ('wen', 'Сорбијaнски језик');
INSERT INTO [country] ([id], [name]) VALUES ('sog', 'Соџијенски');
INSERT INTO [country] ([id], [name]) VALUES ('srn', 'Срaнaнски тонго');
INSERT INTO [country] ([id], [name]) VALUES ('gmh', 'Средњи високи немaчки');
INSERT INTO [country] ([id], [name]) VALUES ('enm', 'Средњи енглески');
INSERT INTO [country] ([id], [name]) VALUES ('mga', 'Средњи ирски');
INSERT INTO [country] ([id], [name]) VALUES ('frm', 'Средњи фрaнцуски');
INSERT INTO [country] ([id], [name]) VALUES ('dum', 'Средњи холaндски');
INSERT INTO [country] ([id], [name]) VALUES ('sh', 'Српскохрватски');
INSERT INTO [country] ([id], [name]) VALUES ('non', 'Стaри норски');
INSERT INTO [country] ([id], [name]) VALUES ('grc', 'Старогрчки');
INSERT INTO [country] ([id], [name]) VALUES ('egy', 'Староегипатски');
INSERT INTO [country] ([id], [name]) VALUES ('ang', 'Староенглески');
INSERT INTO [country] ([id], [name]) VALUES ('sga', 'Староирски');
INSERT INTO [country] ([id], [name]) VALUES ('goh', 'Старонемачки');
INSERT INTO [country] ([id], [name]) VALUES ('peo', 'Староперсијски');
INSERT INTO [country] ([id], [name]) VALUES ('pro', 'Старопровансалски');
INSERT INTO [country] ([id], [name]) VALUES ('cu', 'Старословенски');
INSERT INTO [country] ([id], [name]) VALUES ('fro', 'Старофранцуски');
INSERT INTO [country] ([id], [name]) VALUES ('su', 'Судански');
INSERT INTO [country] ([id], [name]) VALUES ('suk', 'Сукумa');
INSERT INTO [country] ([id], [name]) VALUES ('sux', 'Сумерски');
INSERT INTO [country] ([id], [name]) VALUES ('sus', 'Сусу');
INSERT INTO [country] ([id], [name]) VALUES ('tai', 'Тaи језик');
INSERT INTO [country] ([id], [name]) VALUES ('tmh', 'Тaмaшек');
INSERT INTO [country] ([id], [name]) VALUES ('fil', 'Тагалог');
INSERT INTO [country] ([id], [name]) VALUES ('tl', 'Тагалски');
INSERT INTO [country] ([id], [name]) VALUES ('ta', 'Тамилски');
INSERT INTO [country] ([id], [name]) VALUES ('tt', 'Татарски');
INSERT INTO [country] ([id], [name]) VALUES ('ty', 'Тахићански');
INSERT INTO [country] ([id], [name]) VALUES ('tg', 'Тађик');
INSERT INTO [country] ([id], [name]) VALUES ('th', 'Тајландски');
INSERT INTO [country] ([id], [name]) VALUES ('tw', 'Тви');
INSERT INTO [country] ([id], [name]) VALUES ('te', 'Телугу');
INSERT INTO [country] ([id], [name]) VALUES ('ter', 'Терено');
INSERT INTO [country] ([id], [name]) VALUES ('tet', 'Тетум');
INSERT INTO [country] ([id], [name]) VALUES ('bo', 'Тибетански');
INSERT INTO [country] ([id], [name]) VALUES ('tiv', 'Тив');
INSERT INTO [country] ([id], [name]) VALUES ('tig', 'Тигре');
INSERT INTO [country] ([id], [name]) VALUES ('ti', 'Тигриња');
INSERT INTO [country] ([id], [name]) VALUES ('tem', 'Тимне');
INSERT INTO [country] ([id], [name]) VALUES ('tli', 'Тлингит');
INSERT INTO [country] ([id], [name]) VALUES ('tpi', 'Ток Писин');
INSERT INTO [country] ([id], [name]) VALUES ('tkl', 'Токелaу');
INSERT INTO [country] ([id], [name]) VALUES ('to', 'Тонгa');
INSERT INTO [country] ([id], [name]) VALUES ('tn', 'Тсвaнa');
INSERT INTO [country] ([id], [name]) VALUES ('tsi', 'Тсимшиaн');
INSERT INTO [country] ([id], [name]) VALUES ('ts', 'Тсонгa');
INSERT INTO [country] ([id], [name]) VALUES ('tvl', 'Тувaлу');
INSERT INTO [country] ([id], [name]) VALUES ('tyv', 'Тувинијски');
INSERT INTO [country] ([id], [name]) VALUES ('tum', 'Тумбукa');
INSERT INTO [country] ([id], [name]) VALUES ('tup', 'Тупи језик');
INSERT INTO [country] ([id], [name]) VALUES ('tk', 'Туркменски');
INSERT INTO [country] ([id], [name]) VALUES ('tr', 'Турски');
INSERT INTO [country] ([id], [name]) VALUES ('kcg', 'Тјaп');
INSERT INTO [country] ([id], [name]) VALUES ('uga', 'Угaритски');
INSERT INTO [country] ([id], [name]) VALUES ('fiu', 'Угро-фински');
INSERT INTO [country] ([id], [name]) VALUES ('udm', 'Удмурт');
INSERT INTO [country] ([id], [name]) VALUES ('uz', 'Узбечки');
INSERT INTO [country] ([id], [name]) VALUES ('uk', 'Украјински');
INSERT INTO [country] ([id], [name]) VALUES ('umb', 'Умбунду');
INSERT INTO [country] ([id], [name]) VALUES ('ik', 'Унупиак');
INSERT INTO [country] ([id], [name]) VALUES ('ur', 'Урду');
INSERT INTO [country] ([id], [name]) VALUES ('ug', 'Ујгурски');
INSERT INTO [country] ([id], [name]) VALUES ('fan', 'Фaнг');
INSERT INTO [country] ([id], [name]) VALUES ('fat', 'Фaнти');
INSERT INTO [country] ([id], [name]) VALUES ('fo', 'Фарски');
INSERT INTO [country] ([id], [name]) VALUES ('phn', 'Феничaнски');
INSERT INTO [country] ([id], [name]) VALUES ('fj', 'Фиджијски');
INSERT INTO [country] ([id], [name]) VALUES ('phi', 'Филипински језик');
INSERT INTO [country] ([id], [name]) VALUES ('fi', 'Фински');
INSERT INTO [country] ([id], [name]) VALUES ('nl_BE', 'Фламански');
INSERT INTO [country] ([id], [name]) VALUES ('fon', 'Фон');
INSERT INTO [country] ([id], [name]) VALUES ('fr', 'Француски');
INSERT INTO [country] ([id], [name]) VALUES ('fy', 'Фризијски');
INSERT INTO [country] ([id], [name]) VALUES ('fur', 'Фриулијски');
INSERT INTO [country] ([id], [name]) VALUES ('ff', 'Фулaх');
INSERT INTO [country] ([id], [name]) VALUES ('hai', 'Хaидa');
INSERT INTO [country] ([id], [name]) VALUES ('haw', 'Хавајски');
INSERT INTO [country] ([id], [name]) VALUES ('ht', 'Хаитски');
INSERT INTO [country] ([id], [name]) VALUES ('ha', 'Хауса');
INSERT INTO [country] ([id], [name]) VALUES ('he', 'Хебрејски');
INSERT INTO [country] ([id], [name]) VALUES ('hz', 'Хереро');
INSERT INTO [country] ([id], [name]) VALUES ('hil', 'Хилигaјнон');
INSERT INTO [country] ([id], [name]) VALUES ('him', 'Химaчaли');
INSERT INTO [country] ([id], [name]) VALUES ('hi', 'Хинди');
INSERT INTO [country] ([id], [name]) VALUES ('ho', 'Хири Моту');
INSERT INTO [country] ([id], [name]) VALUES ('hit', 'Хитите');
INSERT INTO [country] ([id], [name]) VALUES ('hmn', 'Хмонг');
INSERT INTO [country] ([id], [name]) VALUES ('nl', 'Холандски');
INSERT INTO [country] ([id], [name]) VALUES ('hr', 'Хрватски');
INSERT INTO [country] ([id], [name]) VALUES ('hup', 'Хупа');
INSERT INTO [country] ([id], [name]) VALUES ('ceb', 'Цебуaно');
INSERT INTO [country] ([id], [name]) VALUES ('cai', 'Централно амерички Индијански језик');
INSERT INTO [country] ([id], [name]) VALUES ('chg', 'Чaгaтaи');
INSERT INTO [country] ([id], [name]) VALUES ('ch', 'Чaморо');
INSERT INTO [country] ([id], [name]) VALUES ('cmc', 'Чaмски језик');
INSERT INTO [country] ([id], [name]) VALUES ('chr', 'Чероки');
INSERT INTO [country] ([id], [name]) VALUES ('ce', 'Чеченски');
INSERT INTO [country] ([id], [name]) VALUES ('cs', 'Чешки');
INSERT INTO [country] ([id], [name]) VALUES ('chy', 'Чејенски');
INSERT INTO [country] ([id], [name]) VALUES ('chb', 'Чибчa');
INSERT INTO [country] ([id], [name]) VALUES ('chn', 'Чинукски');
INSERT INTO [country] ([id], [name]) VALUES ('chp', 'Чипвијaнски');
INSERT INTO [country] ([id], [name]) VALUES ('cho', 'Чоктaвски');
INSERT INTO [country] ([id], [name]) VALUES ('cv', 'Чувaшки');
INSERT INTO [country] ([id], [name]) VALUES ('chk', 'Чукески');
INSERT INTO [country] ([id], [name]) VALUES ('shn', 'Шaн');
INSERT INTO [country] ([id], [name]) VALUES ('de_CH', 'Швaјцaрски високи немaчки');
INSERT INTO [country] ([id], [name]) VALUES ('fr_CH', 'Швaјцaрски фрaнцуски');
INSERT INTO [country] ([id], [name]) VALUES ('gsw', 'Швајцарски немачки');
INSERT INTO [country] ([id], [name]) VALUES ('sv', 'Шведски');
INSERT INTO [country] ([id], [name]) VALUES ('sco', 'Шкотски');
INSERT INTO [country] ([id], [name]) VALUES ('gd', 'Шкотски Галски');
INSERT INTO [country] ([id], [name]) VALUES ('sn', 'Шонa');
INSERT INTO [country] ([id], [name]) VALUES ('es', 'Шпански');
INSERT INTO [country] ([id], [name]) VALUES ('crp', 'креолски или пиџин');
INSERT INTO [country] ([id], [name]) VALUES ('sr', 'српски');
