CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('ab', 'abkhaz');
INSERT INTO [country] ([id], [name]) VALUES ('akk', 'accadi');
INSERT INTO [country] ([id], [name]) VALUES ('ach', 'acoli');
INSERT INTO [country] ([id], [name]) VALUES ('ada', 'adangme');
INSERT INTO [country] ([id], [name]) VALUES ('ady', 'adigué');
INSERT INTO [country] ([id], [name]) VALUES ('aa', 'àfar');
INSERT INTO [country] ([id], [name]) VALUES ('afh', 'afrihili');
INSERT INTO [country] ([id], [name]) VALUES ('af', 'afrikaans');
INSERT INTO [country] ([id], [name]) VALUES ('ay', 'aimara');
INSERT INTO [country] ([id], [name]) VALUES ('ain', 'ainu');
INSERT INTO [country] ([id], [name]) VALUES ('ak', 'àkan');
INSERT INTO [country] ([id], [name]) VALUES ('sq', 'albanès');
INSERT INTO [country] ([id], [name]) VALUES ('de', 'alemany');
INSERT INTO [country] ([id], [name]) VALUES ('de_AT', 'alemany austríac');
INSERT INTO [country] ([id], [name]) VALUES ('gsw', 'alemany suís');
INSERT INTO [country] ([id], [name]) VALUES ('ale', 'aleuta');
INSERT INTO [country] ([id], [name]) VALUES ('goh', 'alt alemany antic');
INSERT INTO [country] ([id], [name]) VALUES ('gmh', 'alt alemany mitjà');
INSERT INTO [country] ([id], [name]) VALUES ('de_CH', 'alt alemany suís');
INSERT INTO [country] ([id], [name]) VALUES ('hsb', 'alt sòrab');
INSERT INTO [country] ([id], [name]) VALUES ('alt', 'altaic meridional');
INSERT INTO [country] ([id], [name]) VALUES ('wal', 'ameto');
INSERT INTO [country] ([id], [name]) VALUES ('am', 'amhàric');
INSERT INTO [country] ([id], [name]) VALUES ('anp', 'angika');
INSERT INTO [country] ([id], [name]) VALUES ('en', 'anglès');
INSERT INTO [country] ([id], [name]) VALUES ('en_US', 'anglès americà');
INSERT INTO [country] ([id], [name]) VALUES ('ang', 'anglès antic');
INSERT INTO [country] ([id], [name]) VALUES ('en_AU', 'anglès australià');
INSERT INTO [country] ([id], [name]) VALUES ('en_GB', 'anglès britànic');
INSERT INTO [country] ([id], [name]) VALUES ('en_CA', 'anglès canadenc');
INSERT INTO [country] ([id], [name]) VALUES ('enm', 'anglès mitjà');
INSERT INTO [country] ([id], [name]) VALUES ('ar', 'àrab');
INSERT INTO [country] ([id], [name]) VALUES ('an', 'aragonès');
INSERT INTO [country] ([id], [name]) VALUES ('arc', 'arameu');
INSERT INTO [country] ([id], [name]) VALUES ('sam', 'arameu samarità');
INSERT INTO [country] ([id], [name]) VALUES ('arp', 'arapaho');
INSERT INTO [country] ([id], [name]) VALUES ('arw', 'arauac');
INSERT INTO [country] ([id], [name]) VALUES ('arn', 'araucà');
INSERT INTO [country] ([id], [name]) VALUES ('hy', 'armeni');
INSERT INTO [country] ([id], [name]) VALUES ('rup', 'aromanès');
INSERT INTO [country] ([id], [name]) VALUES ('root', 'arrel');
INSERT INTO [country] ([id], [name]) VALUES ('as', 'assamès');
INSERT INTO [country] ([id], [name]) VALUES ('ast', 'asturià');
INSERT INTO [country] ([id], [name]) VALUES ('ace', 'atjeh');
INSERT INTO [country] ([id], [name]) VALUES ('cch', 'atsam');
INSERT INTO [country] ([id], [name]) VALUES ('av', 'àvar');
INSERT INTO [country] ([id], [name]) VALUES ('ae', 'avèstic');
INSERT INTO [country] ([id], [name]) VALUES ('awa', 'awadhi');
INSERT INTO [country] ([id], [name]) VALUES ('az', 'àzeri');
INSERT INTO [country] ([id], [name]) VALUES ('nds', 'baix alemany');
INSERT INTO [country] ([id], [name]) VALUES ('dsb', 'baix sòrab');
INSERT INTO [country] ([id], [name]) VALUES ('ba', 'baixkir');
INSERT INTO [country] ([id], [name]) VALUES ('ban', 'balinès');
INSERT INTO [country] ([id], [name]) VALUES ('bal', 'balutxi');
INSERT INTO [country] ([id], [name]) VALUES ('bm', 'bambara');
INSERT INTO [country] ([id], [name]) VALUES ('bai', 'bamileké');
INSERT INTO [country] ([id], [name]) VALUES ('bad', 'banda');
INSERT INTO [country] ([id], [name]) VALUES ('bnt', 'bantu');
INSERT INTO [country] ([id], [name]) VALUES ('bas', 'basa');
INSERT INTO [country] ([id], [name]) VALUES ('eu', 'basc');
INSERT INTO [country] ([id], [name]) VALUES ('btk', 'batak');
INSERT INTO [country] ([id], [name]) VALUES ('bej', 'beja');
INSERT INTO [country] ([id], [name]) VALUES ('bem', 'bemba');
INSERT INTO [country] ([id], [name]) VALUES ('bn', 'bengalí');
INSERT INTO [country] ([id], [name]) VALUES ('ber', 'berber');
INSERT INTO [country] ([id], [name]) VALUES ('bho', 'bhojpuri');
INSERT INTO [country] ([id], [name]) VALUES ('bik', 'bicol');
INSERT INTO [country] ([id], [name]) VALUES ('be', 'bielorús');
INSERT INTO [country] ([id], [name]) VALUES ('bh', 'bihari');
INSERT INTO [country] ([id], [name]) VALUES ('byn', 'bilin');
INSERT INTO [country] ([id], [name]) VALUES ('bin', 'bini');
INSERT INTO [country] ([id], [name]) VALUES ('my', 'birmà');
INSERT INTO [country] ([id], [name]) VALUES ('bi', 'bislama');
INSERT INTO [country] ([id], [name]) VALUES ('bla', 'blackfoot');
INSERT INTO [country] ([id], [name]) VALUES ('bs', 'bosnià');
INSERT INTO [country] ([id], [name]) VALUES ('bra', 'braj');
INSERT INTO [country] ([id], [name]) VALUES ('br', 'bretó');
INSERT INTO [country] ([id], [name]) VALUES ('bug', 'bugui');
INSERT INTO [country] ([id], [name]) VALUES ('bg', 'búlgar');
INSERT INTO [country] ([id], [name]) VALUES ('bua', 'buriat');
INSERT INTO [country] ([id], [name]) VALUES ('kab', 'cabilenc');
INSERT INTO [country] ([id], [name]) VALUES ('cad', 'caddo');
INSERT INTO [country] ([id], [name]) VALUES ('ks', 'caixmiri');
INSERT INTO [country] ([id], [name]) VALUES ('csb', 'caixubi');
INSERT INTO [country] ([id], [name]) VALUES ('xal', 'calmuc');
INSERT INTO [country] ([id], [name]) VALUES ('yue', 'cantonès');
INSERT INTO [country] ([id], [name]) VALUES ('krl', 'carelià');
INSERT INTO [country] ([id], [name]) VALUES ('car', 'carib');
INSERT INTO [country] ([id], [name]) VALUES ('ca', 'català');
INSERT INTO [country] ([id], [name]) VALUES ('ceb', 'cebuà');
INSERT INTO [country] ([id], [name]) VALUES ('ch', 'chamorro');
INSERT INTO [country] ([id], [name]) VALUES ('chr', 'cherokee');
INSERT INTO [country] ([id], [name]) VALUES ('chp', 'chipewyan');
INSERT INTO [country] ([id], [name]) VALUES ('cho', 'choctaw');
INSERT INTO [country] ([id], [name]) VALUES ('chk', 'chuuk');
INSERT INTO [country] ([id], [name]) VALUES ('swb', 'comorià');
INSERT INTO [country] ([id], [name]) VALUES ('cop', 'copte');
INSERT INTO [country] ([id], [name]) VALUES ('ko', 'coreà');
INSERT INTO [country] ([id], [name]) VALUES ('kw', 'còrnic');
INSERT INTO [country] ([id], [name]) VALUES ('co', 'cors');
INSERT INTO [country] ([id], [name]) VALUES ('cr', 'cree');
INSERT INTO [country] ([id], [name]) VALUES ('mus', 'creek');
INSERT INTO [country] ([id], [name]) VALUES ('hr', 'croat');
INSERT INTO [country] ([id], [name]) VALUES ('day', 'daiak');
INSERT INTO [country] ([id], [name]) VALUES ('dak', 'dakota');
INSERT INTO [country] ([id], [name]) VALUES ('da', 'danès');
INSERT INTO [country] ([id], [name]) VALUES ('dar', 'darguà');
INSERT INTO [country] ([id], [name]) VALUES ('del', 'delaware');
INSERT INTO [country] ([id], [name]) VALUES ('din', 'dinka');
INSERT INTO [country] ([id], [name]) VALUES ('dv', 'divehi');
INSERT INTO [country] ([id], [name]) VALUES ('doi', 'dogri');
INSERT INTO [country] ([id], [name]) VALUES ('dgr', 'dogrib');
INSERT INTO [country] ([id], [name]) VALUES ('dua', 'duala');
INSERT INTO [country] ([id], [name]) VALUES ('dz', 'dzongka');
INSERT INTO [country] ([id], [name]) VALUES ('efi', 'efik');
INSERT INTO [country] ([id], [name]) VALUES ('egy', 'egipci antic');
INSERT INTO [country] ([id], [name]) VALUES ('eka', 'ekajuk');
INSERT INTO [country] ([id], [name]) VALUES ('elx', 'elamita');
INSERT INTO [country] ([id], [name]) VALUES ('sco', 'escocès');
INSERT INTO [country] ([id], [name]) VALUES ('cu', 'eslau eclesiàstic');
INSERT INTO [country] ([id], [name]) VALUES ('sk', 'eslovac');
INSERT INTO [country] ([id], [name]) VALUES ('sl', 'eslovè');
INSERT INTO [country] ([id], [name]) VALUES ('es', 'espanyol');
INSERT INTO [country] ([id], [name]) VALUES ('es_ES', 'espanyol d''Espanya');
INSERT INTO [country] ([id], [name]) VALUES ('es_419', 'espanyol d''Hispanoamèrica');
INSERT INTO [country] ([id], [name]) VALUES ('eo', 'esperanto');
INSERT INTO [country] ([id], [name]) VALUES ('et', 'estonià');
INSERT INTO [country] ([id], [name]) VALUES ('ee', 'ewe');
INSERT INTO [country] ([id], [name]) VALUES ('ewo', 'ewondo');
INSERT INTO [country] ([id], [name]) VALUES ('fan', 'fang');
INSERT INTO [country] ([id], [name]) VALUES ('fat', 'fanti');
INSERT INTO [country] ([id], [name]) VALUES ('phn', 'fenici');
INSERT INTO [country] ([id], [name]) VALUES ('fo', 'feroès');
INSERT INTO [country] ([id], [name]) VALUES ('fj', 'fijià');
INSERT INTO [country] ([id], [name]) VALUES ('fil', 'filipí');
INSERT INTO [country] ([id], [name]) VALUES ('fi', 'finès');
INSERT INTO [country] ([id], [name]) VALUES ('nl_BE', 'flamenc');
INSERT INTO [country] ([id], [name]) VALUES ('fon', 'fon');
INSERT INTO [country] ([id], [name]) VALUES ('fr', 'francès');
INSERT INTO [country] ([id], [name]) VALUES ('fro', 'francès antic');
INSERT INTO [country] ([id], [name]) VALUES ('fr_CA', 'francès canadenc');
INSERT INTO [country] ([id], [name]) VALUES ('frm', 'francès mitjà');
INSERT INTO [country] ([id], [name]) VALUES ('fr_CH', 'francès suís');
INSERT INTO [country] ([id], [name]) VALUES ('frs', 'frisó occidental');
INSERT INTO [country] ([id], [name]) VALUES ('fy', 'frisó oriental');
INSERT INTO [country] ([id], [name]) VALUES ('frr', 'frisó septentrional');
INSERT INTO [country] ([id], [name]) VALUES ('fur', 'friülà');
INSERT INTO [country] ([id], [name]) VALUES ('ff', 'ful');
INSERT INTO [country] ([id], [name]) VALUES ('gaa', 'ga');
INSERT INTO [country] ([id], [name]) VALUES ('gd', 'gaèlic escocès');
INSERT INTO [country] ([id], [name]) VALUES ('mga', 'gaèlic irlandès mitjà');
INSERT INTO [country] ([id], [name]) VALUES ('gl', 'gallec');
INSERT INTO [country] ([id], [name]) VALUES ('cy', 'gal·lès');
INSERT INTO [country] ([id], [name]) VALUES ('lg', 'ganda');
INSERT INTO [country] ([id], [name]) VALUES ('gay', 'gayo');
INSERT INTO [country] ([id], [name]) VALUES ('gba', 'gbaya');
INSERT INTO [country] ([id], [name]) VALUES ('ka', 'georgià');
INSERT INTO [country] ([id], [name]) VALUES ('gil', 'gilbertès');
INSERT INTO [country] ([id], [name]) VALUES ('gon', 'gondi');
INSERT INTO [country] ([id], [name]) VALUES ('gor', 'gorontalo');
INSERT INTO [country] ([id], [name]) VALUES ('got', 'gòtic');
INSERT INTO [country] ([id], [name]) VALUES ('grb', 'grebo');
INSERT INTO [country] ([id], [name]) VALUES ('el', 'grec');
INSERT INTO [country] ([id], [name]) VALUES ('grc', 'grec antic');
INSERT INTO [country] ([id], [name]) VALUES ('kl', 'grenlandès');
INSERT INTO [country] ([id], [name]) VALUES ('gn', 'guaraní');
INSERT INTO [country] ([id], [name]) VALUES ('gez', 'gueez');
INSERT INTO [country] ([id], [name]) VALUES ('gu', 'gujarati');
INSERT INTO [country] ([id], [name]) VALUES ('gwi', 'gwichin');
INSERT INTO [country] ([id], [name]) VALUES ('hai', 'haida');
INSERT INTO [country] ([id], [name]) VALUES ('ht', 'haitià');
INSERT INTO [country] ([id], [name]) VALUES ('ha', 'haussa');
INSERT INTO [country] ([id], [name]) VALUES ('haw', 'hawaià');
INSERT INTO [country] ([id], [name]) VALUES ('he', 'hebreu');
INSERT INTO [country] ([id], [name]) VALUES ('hz', 'herero');
INSERT INTO [country] ([id], [name]) VALUES ('hil', 'hiligainon');
INSERT INTO [country] ([id], [name]) VALUES ('him', 'himachali');
INSERT INTO [country] ([id], [name]) VALUES ('hi', 'hindi');
INSERT INTO [country] ([id], [name]) VALUES ('ho', 'hiri motu');
INSERT INTO [country] ([id], [name]) VALUES ('hit', 'hitita');
INSERT INTO [country] ([id], [name]) VALUES ('hmn', 'hmong');
INSERT INTO [country] ([id], [name]) VALUES ('hu', 'hongarès');
INSERT INTO [country] ([id], [name]) VALUES ('hup', 'hupa');
INSERT INTO [country] ([id], [name]) VALUES ('sah', 'iacut');
INSERT INTO [country] ([id], [name]) VALUES ('iba', 'iban');
INSERT INTO [country] ([id], [name]) VALUES ('und', 'idioma desconegut o no vàlid');
INSERT INTO [country] ([id], [name]) VALUES ('io', 'ido');
INSERT INTO [country] ([id], [name]) VALUES ('ig', 'igbo');
INSERT INTO [country] ([id], [name]) VALUES ('ijo', 'ijo');
INSERT INTO [country] ([id], [name]) VALUES ('ilo', 'ilocà');
INSERT INTO [country] ([id], [name]) VALUES ('id', 'indonesi');
INSERT INTO [country] ([id], [name]) VALUES ('inh', 'ingúix');
INSERT INTO [country] ([id], [name]) VALUES ('ia', 'interlingua');
INSERT INTO [country] ([id], [name]) VALUES ('ie', 'interlingue');
INSERT INTO [country] ([id], [name]) VALUES ('iu', 'inuktitut');
INSERT INTO [country] ([id], [name]) VALUES ('ik', 'inupiak');
INSERT INTO [country] ([id], [name]) VALUES ('yo', 'ioruba');
INSERT INTO [country] ([id], [name]) VALUES ('ga', 'irlandès');
INSERT INTO [country] ([id], [name]) VALUES ('sga', 'irlandès antic');
INSERT INTO [country] ([id], [name]) VALUES ('iro', 'iroquès');
INSERT INTO [country] ([id], [name]) VALUES ('is', 'islandès');
INSERT INTO [country] ([id], [name]) VALUES ('it', 'italià');
INSERT INTO [country] ([id], [name]) VALUES ('ja', 'japonès');
INSERT INTO [country] ([id], [name]) VALUES ('jv', 'javanès');
INSERT INTO [country] ([id], [name]) VALUES ('yi', 'jiddisch');
INSERT INTO [country] ([id], [name]) VALUES ('kaj', 'jju');
INSERT INTO [country] ([id], [name]) VALUES ('jrb', 'judeoàrab');
INSERT INTO [country] ([id], [name]) VALUES ('jpr', 'judeopersa');
INSERT INTO [country] ([id], [name]) VALUES ('dyu', 'jula');
INSERT INTO [country] ([id], [name]) VALUES ('kbd', 'kabardí');
INSERT INTO [country] ([id], [name]) VALUES ('kam', 'kamba');
INSERT INTO [country] ([id], [name]) VALUES ('kn', 'kannada');
INSERT INTO [country] ([id], [name]) VALUES ('kr', 'kanuri');
INSERT INTO [country] ([id], [name]) VALUES ('kaa', 'karakalpak');
INSERT INTO [country] ([id], [name]) VALUES ('krc', 'karatxai');
INSERT INTO [country] ([id], [name]) VALUES ('kar', 'karen');
INSERT INTO [country] ([id], [name]) VALUES ('kac', 'katxin');
INSERT INTO [country] ([id], [name]) VALUES ('kaw', 'kawi');
INSERT INTO [country] ([id], [name]) VALUES ('kk', 'kazakh');
INSERT INTO [country] ([id], [name]) VALUES ('kha', 'khasi');
INSERT INTO [country] ([id], [name]) VALUES ('km', 'khmer');
INSERT INTO [country] ([id], [name]) VALUES ('kho', 'khotanès');
INSERT INTO [country] ([id], [name]) VALUES ('ki', 'kikuiu');
INSERT INTO [country] ([id], [name]) VALUES ('kmb', 'kimbundu');
INSERT INTO [country] ([id], [name]) VALUES ('ky', 'kirguís');
INSERT INTO [country] ([id], [name]) VALUES ('tlh', 'klingonià');
INSERT INTO [country] ([id], [name]) VALUES ('kv', 'komi');
INSERT INTO [country] ([id], [name]) VALUES ('kg', 'kongo');
INSERT INTO [country] ([id], [name]) VALUES ('kok', 'konkani');
INSERT INTO [country] ([id], [name]) VALUES ('kfo', 'koro');
INSERT INTO [country] ([id], [name]) VALUES ('kos', 'kosraeà');
INSERT INTO [country] ([id], [name]) VALUES ('kpe', 'kpelle');
INSERT INTO [country] ([id], [name]) VALUES ('kro', 'kru');
INSERT INTO [country] ([id], [name]) VALUES ('kj', 'kuanyama');
INSERT INTO [country] ([id], [name]) VALUES ('kum', 'kúmik');
INSERT INTO [country] ([id], [name]) VALUES ('ku', 'kurd');
INSERT INTO [country] ([id], [name]) VALUES ('kru', 'kurukh');
INSERT INTO [country] ([id], [name]) VALUES ('kut', 'kutenai');
INSERT INTO [country] ([id], [name]) VALUES ('lad', 'ladí');
INSERT INTO [country] ([id], [name]) VALUES ('lam', 'lamba');
INSERT INTO [country] ([id], [name]) VALUES ('lo', 'laosià');
INSERT INTO [country] ([id], [name]) VALUES ('lez', 'lesguià');
INSERT INTO [country] ([id], [name]) VALUES ('lv', 'letó');
INSERT INTO [country] ([id], [name]) VALUES ('li', 'limburguès');
INSERT INTO [country] ([id], [name]) VALUES ('ln', 'lingala');
INSERT INTO [country] ([id], [name]) VALUES ('lt', 'lituà');
INSERT INTO [country] ([id], [name]) VALUES ('la', 'llatí');
INSERT INTO [country] ([id], [name]) VALUES ('afa', 'llengua afroasiàtica');
INSERT INTO [country] ([id], [name]) VALUES ('alg', 'llengua algonquina');
INSERT INTO [country] ([id], [name]) VALUES ('tut', 'llengua altaica');
INSERT INTO [country] ([id], [name]) VALUES ('cai', 'llengua ameríndia d''Amèrica Central');
INSERT INTO [country] ([id], [name]) VALUES ('sai', 'llengua ameríndia meridional');
INSERT INTO [country] ([id], [name]) VALUES ('nai', 'llengua ameríndia septentrional');
INSERT INTO [country] ([id], [name]) VALUES ('apa', 'llengua apatxe');
INSERT INTO [country] ([id], [name]) VALUES ('art', 'llengua artificial');
INSERT INTO [country] ([id], [name]) VALUES ('ath', 'llengua atapascana');
INSERT INTO [country] ([id], [name]) VALUES ('aus', 'llengua australiana');
INSERT INTO [country] ([id], [name]) VALUES ('map', 'llengua austronèsia');
INSERT INTO [country] ([id], [name]) VALUES ('bat', 'llengua bàltica');
INSERT INTO [country] ([id], [name]) VALUES ('cau', 'llengua caucàsica');
INSERT INTO [country] ([id], [name]) VALUES ('cel', 'llengua cèltica');
INSERT INTO [country] ([id], [name]) VALUES ('crp', 'llengua criolla o pidgin');
INSERT INTO [country] ([id], [name]) VALUES ('cpf', 'llengua criolla o pidgin basada en el francès');
INSERT INTO [country] ([id], [name]) VALUES ('cpp', 'llengua criolla o pidgin basada en el portuguès');
INSERT INTO [country] ([id], [name]) VALUES ('cpe', 'llengua criolla o pidgin basada en l''anglès');
INSERT INTO [country] ([id], [name]) VALUES ('cus', 'llengua cuixítica');
INSERT INTO [country] ([id], [name]) VALUES ('sgn', 'llengua de signes');
INSERT INTO [country] ([id], [name]) VALUES ('dra', 'llengua dravídica');
INSERT INTO [country] ([id], [name]) VALUES ('sla', 'llengua eslava');
INSERT INTO [country] ([id], [name]) VALUES ('phi', 'llengua filipina');
INSERT INTO [country] ([id], [name]) VALUES ('fiu', 'llengua finoúgrica');
INSERT INTO [country] ([id], [name]) VALUES ('gem', 'llengua germànica');
INSERT INTO [country] ([id], [name]) VALUES ('inc', 'llengua índica');
INSERT INTO [country] ([id], [name]) VALUES ('ine', 'llengua indoeuropea');
INSERT INTO [country] ([id], [name]) VALUES ('ira', 'llengua irànica');
INSERT INTO [country] ([id], [name]) VALUES ('ypk', 'llengua iupik');
INSERT INTO [country] ([id], [name]) VALUES ('khi', 'llengua khoisan');
INSERT INTO [country] ([id], [name]) VALUES ('myn', 'llengua maia');
INSERT INTO [country] ([id], [name]) VALUES ('mno', 'llengua manobo');
INSERT INTO [country] ([id], [name]) VALUES ('mis', 'llengua miscel·lània');
INSERT INTO [country] ([id], [name]) VALUES ('mkh', 'llengua monkhmer');
INSERT INTO [country] ([id], [name]) VALUES ('mun', 'llengua munda');
INSERT INTO [country] ([id], [name]) VALUES ('nic', 'llengua nigerokurdufaniana');
INSERT INTO [country] ([id], [name]) VALUES ('ssa', 'llengua nilosahariana');
INSERT INTO [country] ([id], [name]) VALUES ('nub', 'llengua nubiana');
INSERT INTO [country] ([id], [name]) VALUES ('oto', 'llengua otomangueana');
INSERT INTO [country] ([id], [name]) VALUES ('paa', 'llengua papú');
INSERT INTO [country] ([id], [name]) VALUES ('roa', 'llengua romànica');
INSERT INTO [country] ([id], [name]) VALUES ('sal', 'llengua salish');
INSERT INTO [country] ([id], [name]) VALUES ('smi', 'llengua sami');
INSERT INTO [country] ([id], [name]) VALUES ('sem', 'llengua semítica');
INSERT INTO [country] ([id], [name]) VALUES ('sit', 'llengua sinotibetana');
INSERT INTO [country] ([id], [name]) VALUES ('sio', 'llengua sioux');
INSERT INTO [country] ([id], [name]) VALUES ('tai', 'llengua tai');
INSERT INTO [country] ([id], [name]) VALUES ('tup', 'llengua tupí');
INSERT INTO [country] ([id], [name]) VALUES ('wak', 'llengua wakash');
INSERT INTO [country] ([id], [name]) VALUES ('jbo', 'lojban');
INSERT INTO [country] ([id], [name]) VALUES ('loz', 'lozi');
INSERT INTO [country] ([id], [name]) VALUES ('lu', 'luba katanga');
INSERT INTO [country] ([id], [name]) VALUES ('lua', 'luba-lulua');
INSERT INTO [country] ([id], [name]) VALUES ('lui', 'luisenyo');
INSERT INTO [country] ([id], [name]) VALUES ('lun', 'lunda');
INSERT INTO [country] ([id], [name]) VALUES ('luo', 'luo');
INSERT INTO [country] ([id], [name]) VALUES ('lb', 'luxemburguès');
INSERT INTO [country] ([id], [name]) VALUES ('mk', 'macedoni');
INSERT INTO [country] ([id], [name]) VALUES ('mad', 'madurès');
INSERT INTO [country] ([id], [name]) VALUES ('mag', 'magahi');
INSERT INTO [country] ([id], [name]) VALUES ('mai', 'maithili');
INSERT INTO [country] ([id], [name]) VALUES ('mak', 'makassar');
INSERT INTO [country] ([id], [name]) VALUES ('ms', 'malai');
INSERT INTO [country] ([id], [name]) VALUES ('ml', 'malaialam');
INSERT INTO [country] ([id], [name]) VALUES ('mg', 'malgaix');
INSERT INTO [country] ([id], [name]) VALUES ('mt', 'maltès');
INSERT INTO [country] ([id], [name]) VALUES ('mdr', 'mandar');
INSERT INTO [country] ([id], [name]) VALUES ('man', 'mandinga');
INSERT INTO [country] ([id], [name]) VALUES ('mni', 'manipurí');
INSERT INTO [country] ([id], [name]) VALUES ('gv', 'manx');
INSERT INTO [country] ([id], [name]) VALUES ('mnc', 'manxú');
INSERT INTO [country] ([id], [name]) VALUES ('mi', 'maori');
INSERT INTO [country] ([id], [name]) VALUES ('mr', 'marathi');
INSERT INTO [country] ([id], [name]) VALUES ('chm', 'mari');
INSERT INTO [country] ([id], [name]) VALUES ('mh', 'marshallès');
INSERT INTO [country] ([id], [name]) VALUES ('mwr', 'marwari');
INSERT INTO [country] ([id], [name]) VALUES ('mas', 'massai');
INSERT INTO [country] ([id], [name]) VALUES ('men', 'mende');
INSERT INTO [country] ([id], [name]) VALUES ('mic', 'micmac');
INSERT INTO [country] ([id], [name]) VALUES ('min', 'minangkabau');
INSERT INTO [country] ([id], [name]) VALUES ('mwl', 'mirandès');
INSERT INTO [country] ([id], [name]) VALUES ('lus', 'mizo');
INSERT INTO [country] ([id], [name]) VALUES ('moh', 'mohawk');
INSERT INTO [country] ([id], [name]) VALUES ('mo', 'moldau');
INSERT INTO [country] ([id], [name]) VALUES ('lol', 'mongo');
INSERT INTO [country] ([id], [name]) VALUES ('mn', 'mongol');
INSERT INTO [country] ([id], [name]) VALUES ('myv', 'mordovià erza');
INSERT INTO [country] ([id], [name]) VALUES ('mdf', 'mordovià moksa');
INSERT INTO [country] ([id], [name]) VALUES ('mos', 'moré');
INSERT INTO [country] ([id], [name]) VALUES ('nqo', 'n’Ko');
INSERT INTO [country] ([id], [name]) VALUES ('nah', 'nàhuatl');
INSERT INTO [country] ([id], [name]) VALUES ('nap', 'napolità');
INSERT INTO [country] ([id], [name]) VALUES ('na', 'nauruà');
INSERT INTO [country] ([id], [name]) VALUES ('nv', 'navaho');
INSERT INTO [country] ([id], [name]) VALUES ('nr', 'ndebele meridional');
INSERT INTO [country] ([id], [name]) VALUES ('nd', 'ndebele septentrional');
INSERT INTO [country] ([id], [name]) VALUES ('ng', 'ndonga');
INSERT INTO [country] ([id], [name]) VALUES ('nl', 'neerlandès');
INSERT INTO [country] ([id], [name]) VALUES ('dum', 'neerlandès mitjà');
INSERT INTO [country] ([id], [name]) VALUES ('ne', 'nepalès');
INSERT INTO [country] ([id], [name]) VALUES ('new', 'newari');
INSERT INTO [country] ([id], [name]) VALUES ('nwc', 'newari clàssic');
INSERT INTO [country] ([id], [name]) VALUES ('nia', 'nias');
INSERT INTO [country] ([id], [name]) VALUES ('niu', 'niueà');
INSERT INTO [country] ([id], [name]) VALUES ('nog', 'nogai');
INSERT INTO [country] ([id], [name]) VALUES ('non', 'nòrdic antic');
INSERT INTO [country] ([id], [name]) VALUES ('no', 'noruec');
INSERT INTO [country] ([id], [name]) VALUES ('nb', 'noruec bokmål');
INSERT INTO [country] ([id], [name]) VALUES ('nn', 'noruec nynorsk');
INSERT INTO [country] ([id], [name]) VALUES ('nym', 'nyamwesi');
INSERT INTO [country] ([id], [name]) VALUES ('ny', 'nyanja');
INSERT INTO [country] ([id], [name]) VALUES ('nyn', 'nyankore');
INSERT INTO [country] ([id], [name]) VALUES ('nyo', 'nyoro');
INSERT INTO [country] ([id], [name]) VALUES ('nzi', 'nzema');
INSERT INTO [country] ([id], [name]) VALUES ('oc', 'occità');
INSERT INTO [country] ([id], [name]) VALUES ('oj', 'ojibwa');
INSERT INTO [country] ([id], [name]) VALUES ('or', 'oriya');
INSERT INTO [country] ([id], [name]) VALUES ('om', 'oromo');
INSERT INTO [country] ([id], [name]) VALUES ('osa', 'osage');
INSERT INTO [country] ([id], [name]) VALUES ('os', 'osset');
INSERT INTO [country] ([id], [name]) VALUES ('pal', 'pahlavi');
INSERT INTO [country] ([id], [name]) VALUES ('ps', 'paixto');
INSERT INTO [country] ([id], [name]) VALUES ('pau', 'palauà');
INSERT INTO [country] ([id], [name]) VALUES ('pi', 'pali');
INSERT INTO [country] ([id], [name]) VALUES ('pam', 'pampangà');
INSERT INTO [country] ([id], [name]) VALUES ('pag', 'pangasi');
INSERT INTO [country] ([id], [name]) VALUES ('pa', 'panjabi');
INSERT INTO [country] ([id], [name]) VALUES ('lah', 'panjabi occidental');
INSERT INTO [country] ([id], [name]) VALUES ('pap', 'papiamento');
INSERT INTO [country] ([id], [name]) VALUES ('fa', 'persa');
INSERT INTO [country] ([id], [name]) VALUES ('peo', 'persa antic');
INSERT INTO [country] ([id], [name]) VALUES ('chn', 'pidgin chinook');
INSERT INTO [country] ([id], [name]) VALUES ('pl', 'polonès');
INSERT INTO [country] ([id], [name]) VALUES ('pon', 'ponapeà');
INSERT INTO [country] ([id], [name]) VALUES ('pt', 'portuguès');
INSERT INTO [country] ([id], [name]) VALUES ('pt_BR', 'portuguès de Brasil');
INSERT INTO [country] ([id], [name]) VALUES ('pt_PT', 'portuguès de Portugal');
INSERT INTO [country] ([id], [name]) VALUES ('pra', 'pràcrit');
INSERT INTO [country] ([id], [name]) VALUES ('pro', 'provençal antic');
INSERT INTO [country] ([id], [name]) VALUES ('qu', 'quètxua');
INSERT INTO [country] ([id], [name]) VALUES ('raj', 'rajasthani');
INSERT INTO [country] ([id], [name]) VALUES ('rap', 'rapanui');
INSERT INTO [country] ([id], [name]) VALUES ('rar', 'rarotongà');
INSERT INTO [country] ([id], [name]) VALUES ('rm', 'retoromànic');
INSERT INTO [country] ([id], [name]) VALUES ('ro', 'romanès');
INSERT INTO [country] ([id], [name]) VALUES ('rom', 'romaní');
INSERT INTO [country] ([id], [name]) VALUES ('rw', 'ruandès');
INSERT INTO [country] ([id], [name]) VALUES ('rn', 'rundi');
INSERT INTO [country] ([id], [name]) VALUES ('ru', 'rus');
INSERT INTO [country] ([id], [name]) VALUES ('smn', 'sami d''Inari');
INSERT INTO [country] ([id], [name]) VALUES ('smj', 'sami lule');
INSERT INTO [country] ([id], [name]) VALUES ('sma', 'sami meridional');
INSERT INTO [country] ([id], [name]) VALUES ('se', 'sami septentrional');
INSERT INTO [country] ([id], [name]) VALUES ('sms', 'sami skolt');
INSERT INTO [country] ([id], [name]) VALUES ('sm', 'samoà');
INSERT INTO [country] ([id], [name]) VALUES ('sad', 'sandawe');
INSERT INTO [country] ([id], [name]) VALUES ('sg', 'sango');
INSERT INTO [country] ([id], [name]) VALUES ('sa', 'sànscrit');
INSERT INTO [country] ([id], [name]) VALUES ('sat', 'santali');
INSERT INTO [country] ([id], [name]) VALUES ('sc', 'sard');
INSERT INTO [country] ([id], [name]) VALUES ('sas', 'sasak');
INSERT INTO [country] ([id], [name]) VALUES ('sel', 'selkup');
INSERT INTO [country] ([id], [name]) VALUES ('zxx', 'sense contingut lingüístic');
INSERT INTO [country] ([id], [name]) VALUES ('sr', 'serbi');
INSERT INTO [country] ([id], [name]) VALUES ('sh', 'serbocroat');
INSERT INTO [country] ([id], [name]) VALUES ('srr', 'serer');
INSERT INTO [country] ([id], [name]) VALUES ('sn', 'shona');
INSERT INTO [country] ([id], [name]) VALUES ('scn', 'sicilià');
INSERT INTO [country] ([id], [name]) VALUES ('sid', 'sidamo');
INSERT INTO [country] ([id], [name]) VALUES ('zbl', 'símbols Bliss');
INSERT INTO [country] ([id], [name]) VALUES ('sd', 'sindhi');
INSERT INTO [country] ([id], [name]) VALUES ('si', 'singalès');
INSERT INTO [country] ([id], [name]) VALUES ('syr', 'siríac');
INSERT INTO [country] ([id], [name]) VALUES ('syc', 'siríac clàssic');
INSERT INTO [country] ([id], [name]) VALUES ('ss', 'siswati');
INSERT INTO [country] ([id], [name]) VALUES ('den', 'slavey');
INSERT INTO [country] ([id], [name]) VALUES ('sog', 'sogdià');
INSERT INTO [country] ([id], [name]) VALUES ('so', 'somali');
INSERT INTO [country] ([id], [name]) VALUES ('son', 'songhai');
INSERT INTO [country] ([id], [name]) VALUES ('snk', 'soninke');
INSERT INTO [country] ([id], [name]) VALUES ('wen', 'sòrab');
INSERT INTO [country] ([id], [name]) VALUES ('st', 'sotho meridional');
INSERT INTO [country] ([id], [name]) VALUES ('nso', 'sotho septentrional');
INSERT INTO [country] ([id], [name]) VALUES ('srn', 'sranan');
INSERT INTO [country] ([id], [name]) VALUES ('sw', 'suahili');
INSERT INTO [country] ([id], [name]) VALUES ('sv', 'suec');
INSERT INTO [country] ([id], [name]) VALUES ('suk', 'sukuma');
INSERT INTO [country] ([id], [name]) VALUES ('sux', 'sumeri');
INSERT INTO [country] ([id], [name]) VALUES ('su', 'sundanès');
INSERT INTO [country] ([id], [name]) VALUES ('sus', 'susú');
INSERT INTO [country] ([id], [name]) VALUES ('tg', 'tadjik');
INSERT INTO [country] ([id], [name]) VALUES ('tl', 'tagàlog');
INSERT INTO [country] ([id], [name]) VALUES ('ty', 'tahitià');
INSERT INTO [country] ([id], [name]) VALUES ('tmh', 'tamazight');
INSERT INTO [country] ([id], [name]) VALUES ('ta', 'tàmil');
INSERT INTO [country] ([id], [name]) VALUES ('tt', 'tàtar');
INSERT INTO [country] ([id], [name]) VALUES ('crh', 'tàtar de Crimea');
INSERT INTO [country] ([id], [name]) VALUES ('te', 'telugu');
INSERT INTO [country] ([id], [name]) VALUES ('tem', 'temne');
INSERT INTO [country] ([id], [name]) VALUES ('ter', 'terena');
INSERT INTO [country] ([id], [name]) VALUES ('tet', 'tetun');
INSERT INTO [country] ([id], [name]) VALUES ('th', 'thai');
INSERT INTO [country] ([id], [name]) VALUES ('bo', 'tibetà');
INSERT INTO [country] ([id], [name]) VALUES ('tig', 'tigre');
INSERT INTO [country] ([id], [name]) VALUES ('ti', 'tigrinya');
INSERT INTO [country] ([id], [name]) VALUES ('tiv', 'tiv');
INSERT INTO [country] ([id], [name]) VALUES ('tli', 'tlingit');
INSERT INTO [country] ([id], [name]) VALUES ('tpi', 'tok pisin');
INSERT INTO [country] ([id], [name]) VALUES ('tkl', 'tokelauès');
INSERT INTO [country] ([id], [name]) VALUES ('tog', 'tonga');
INSERT INTO [country] ([id], [name]) VALUES ('to', 'tongalès');
INSERT INTO [country] ([id], [name]) VALUES ('tsi', 'tsimshià');
INSERT INTO [country] ([id], [name]) VALUES ('ts', 'tsonga');
INSERT INTO [country] ([id], [name]) VALUES ('tn', 'tswana');
INSERT INTO [country] ([id], [name]) VALUES ('tum', 'tumbuka');
INSERT INTO [country] ([id], [name]) VALUES ('tr', 'turc');
INSERT INTO [country] ([id], [name]) VALUES ('ota', 'turc otomà');
INSERT INTO [country] ([id], [name]) VALUES ('tk', 'turcman');
INSERT INTO [country] ([id], [name]) VALUES ('tvl', 'tuvaluà');
INSERT INTO [country] ([id], [name]) VALUES ('tyv', 'tuvinià');
INSERT INTO [country] ([id], [name]) VALUES ('tw', 'twi');
INSERT INTO [country] ([id], [name]) VALUES ('chg', 'txagatai');
INSERT INTO [country] ([id], [name]) VALUES ('cmc', 'txam');
INSERT INTO [country] ([id], [name]) VALUES ('cs', 'txec');
INSERT INTO [country] ([id], [name]) VALUES ('ce', 'txetxè');
INSERT INTO [country] ([id], [name]) VALUES ('chb', 'txibtxa');
INSERT INTO [country] ([id], [name]) VALUES ('cv', 'txuvaix');
INSERT INTO [country] ([id], [name]) VALUES ('kcg', 'tyap');
INSERT INTO [country] ([id], [name]) VALUES ('uk', 'ucraïnès');
INSERT INTO [country] ([id], [name]) VALUES ('udm', 'udmurt');
INSERT INTO [country] ([id], [name]) VALUES ('uga', 'ugarític');
INSERT INTO [country] ([id], [name]) VALUES ('ug', 'uigur');
INSERT INTO [country] ([id], [name]) VALUES ('umb', 'umbundu');
INSERT INTO [country] ([id], [name]) VALUES ('ur', 'urdú');
INSERT INTO [country] ([id], [name]) VALUES ('uz', 'uzbek');
INSERT INTO [country] ([id], [name]) VALUES ('vai', 'vai');
INSERT INTO [country] ([id], [name]) VALUES ('wa', 'való');
INSERT INTO [country] ([id], [name]) VALUES ('ve', 'venda');
INSERT INTO [country] ([id], [name]) VALUES ('vi', 'vietnamita');
INSERT INTO [country] ([id], [name]) VALUES ('vo', 'volapük');
INSERT INTO [country] ([id], [name]) VALUES ('vot', 'vòtic');
INSERT INTO [country] ([id], [name]) VALUES ('war', 'waray-waray');
INSERT INTO [country] ([id], [name]) VALUES ('was', 'washo');
INSERT INTO [country] ([id], [name]) VALUES ('wo', 'wòlof');
INSERT INTO [country] ([id], [name]) VALUES ('shn', 'xan');
INSERT INTO [country] ([id], [name]) VALUES ('chy', 'xeienne');
INSERT INTO [country] ([id], [name]) VALUES ('zh', 'xinès');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hans', 'xinès simplificat');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hant', 'xinès tradicional');
INSERT INTO [country] ([id], [name]) VALUES ('xh', 'xosa');
INSERT INTO [country] ([id], [name]) VALUES ('yao', 'yao');
INSERT INTO [country] ([id], [name]) VALUES ('yap', 'yapeà');
INSERT INTO [country] ([id], [name]) VALUES ('ii', 'yi sichuan');
INSERT INTO [country] ([id], [name]) VALUES ('znd', 'zande');
INSERT INTO [country] ([id], [name]) VALUES ('zap', 'zapoteca');
INSERT INTO [country] ([id], [name]) VALUES ('zza', 'zaza');
INSERT INTO [country] ([id], [name]) VALUES ('zen', 'zenaga');
INSERT INTO [country] ([id], [name]) VALUES ('za', 'zhuang');
INSERT INTO [country] ([id], [name]) VALUES ('zu', 'zulu');
INSERT INTO [country] ([id], [name]) VALUES ('zun', 'zuni');
