CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('zxx', 'ʻikai ha lea');
INSERT INTO [country] ([id], [name]) VALUES ('art', 'lea faʻu');
INSERT INTO [country] ([id], [name]) VALUES ('fr', 'lea fakafalanisē');
INSERT INTO [country] ([id], [name]) VALUES ('fr_CA', 'lea fakafalanisē kānata');
INSERT INTO [country] ([id], [name]) VALUES ('fr_CH', 'lea fakafalanisē suitisālani');
INSERT INTO [country] ([id], [name]) VALUES ('fil', 'lea fakafilipaini');
INSERT INTO [country] ([id], [name]) VALUES ('fi', 'lea fakafinilani');
INSERT INTO [country] ([id], [name]) VALUES ('fj', 'lea fakafisi');
INSERT INTO [country] ([id], [name]) VALUES ('sm', 'lea fakahaʻamoa');
INSERT INTO [country] ([id], [name]) VALUES ('ht', 'lea fakahaiti');
INSERT INTO [country] ([id], [name]) VALUES ('hu', 'lea fakahangakalia');
INSERT INTO [country] ([id], [name]) VALUES ('haw', 'lea fakahauaiʻi');
INSERT INTO [country] ([id], [name]) VALUES ('he', 'lea fakahepelū');
INSERT INTO [country] ([id], [name]) VALUES ('hi', 'lea fakahinitī');
INSERT INTO [country] ([id], [name]) VALUES ('nl', 'lea fakahōlani');
INSERT INTO [country] ([id], [name]) VALUES ('nl_BE', 'lea fakahōlani pelesiume');
INSERT INTO [country] ([id], [name]) VALUES ('ga', 'lea fakaʻaelani');
INSERT INTO [country] ([id], [name]) VALUES ('af', 'lea fakaʻafilikana');
INSERT INTO [country] ([id], [name]) VALUES ('is', 'lea fakaʻaisilani');
INSERT INTO [country] ([id], [name]) VALUES ('sq', 'lea fakaʻalapēnia');
INSERT INTO [country] ([id], [name]) VALUES ('ar', 'lea fakaʻalepea');
INSERT INTO [country] ([id], [name]) VALUES ('hy', 'lea fakaʻaminiume');
INSERT INTO [country] ([id], [name]) VALUES ('ab', 'lea fakaʻapakasi');
INSERT INTO [country] ([id], [name]) VALUES ('az', 'lea fakaʻasapaisani');
INSERT INTO [country] ([id], [name]) VALUES ('eo', 'lea fakaʻesipulanito');
INSERT INTO [country] ([id], [name]) VALUES ('et', 'lea fakaʻesitōnia');
INSERT INTO [country] ([id], [name]) VALUES ('ur', 'lea fakaʻetiu');
INSERT INTO [country] ([id], [name]) VALUES ('sgn', 'lea fakaʻilonga');
INSERT INTO [country] ([id], [name]) VALUES ('or', 'lea fakaʻinitia ʻolāea');
INSERT INTO [country] ([id], [name]) VALUES ('ml', 'lea fakaʻinitia malāialemi');
INSERT INTO [country] ([id], [name]) VALUES ('te', 'lea fakaʻinitia teluku');
INSERT INTO [country] ([id], [name]) VALUES ('id', 'lea fakaʻinitōnesia');
INSERT INTO [country] ([id], [name]) VALUES ('yo', 'lea fakaʻiōlupa');
INSERT INTO [country] ([id], [name]) VALUES ('it', 'lea fakaʻītali');
INSERT INTO [country] ([id], [name]) VALUES ('uk', 'lea fakaʻiukālia');
INSERT INTO [country] ([id], [name]) VALUES ('ug', 'lea fakaʻuika');
INSERT INTO [country] ([id], [name]) VALUES ('wo', 'lea fakaʻuolofo');
INSERT INTO [country] ([id], [name]) VALUES ('uz', 'lea fakaʻusipeki');
INSERT INTO [country] ([id], [name]) VALUES ('el', 'lea fakakalisi');
INSERT INTO [country] ([id], [name]) VALUES ('grc', 'lea fakakalisimuʻa');
INSERT INTO [country] ([id], [name]) VALUES ('kk', 'lea fakakasakiteni');
INSERT INTO [country] ([id], [name]) VALUES ('ky', 'lea fakakekisiteni');
INSERT INTO [country] ([id], [name]) VALUES ('km', 'lea fakakemipōtia');
INSERT INTO [country] ([id], [name]) VALUES ('ks', 'lea fakakesimia');
INSERT INTO [country] ([id], [name]) VALUES ('ca', 'lea fakaketalani');
INSERT INTO [country] ([id], [name]) VALUES ('gil', 'lea fakakilipasi');
INSERT INTO [country] ([id], [name]) VALUES ('ko', 'lea fakakōlea');
INSERT INTO [country] ([id], [name]) VALUES ('swb', 'lea fakakomolo');
INSERT INTO [country] ([id], [name]) VALUES ('hr', 'lea fakakuloisia');
INSERT INTO [country] ([id], [name]) VALUES ('lb', 'lea fakalakisimipeki');
INSERT INTO [country] ([id], [name]) VALUES ('rar', 'lea fakalalotonga');
INSERT INTO [country] ([id], [name]) VALUES ('rap', 'lea fakalapanui');
INSERT INTO [country] ([id], [name]) VALUES ('la', 'lea fakalatina');
INSERT INTO [country] ([id], [name]) VALUES ('lv', 'lea fakalativia');
INSERT INTO [country] ([id], [name]) VALUES ('lo', 'lea fakalau');
INSERT INTO [country] ([id], [name]) VALUES ('lt', 'lea fakalifiuenia');
INSERT INTO [country] ([id], [name]) VALUES ('ro', 'lea fakalōmenia');
INSERT INTO [country] ([id], [name]) VALUES ('rw', 'lea fakaluanita');
INSERT INTO [country] ([id], [name]) VALUES ('ru', 'lea fakalūsia');
INSERT INTO [country] ([id], [name]) VALUES ('ms', 'lea fakamalei');
INSERT INTO [country] ([id], [name]) VALUES ('mk', 'lea fakamasitōnia');
INSERT INTO [country] ([id], [name]) VALUES ('mh', 'lea fakamāsolo');
INSERT INTO [country] ([id], [name]) VALUES ('mg', 'lea fakamatakasika');
INSERT INTO [country] ([id], [name]) VALUES ('mi', 'lea fakamauli');
INSERT INTO [country] ([id], [name]) VALUES ('mt', 'lea fakamolota');
INSERT INTO [country] ([id], [name]) VALUES ('mn', 'lea fakamongokōlia');
INSERT INTO [country] ([id], [name]) VALUES ('na', 'lea fakanaulu');
INSERT INTO [country] ([id], [name]) VALUES ('ne', 'lea fakanepali');
INSERT INTO [country] ([id], [name]) VALUES ('niu', 'lea fakaniuē');
INSERT INTO [country] ([id], [name]) VALUES ('no', 'lea fakanouē');
INSERT INTO [country] ([id], [name]) VALUES ('nn', 'lea fakanouei nosiki');
INSERT INTO [country] ([id], [name]) VALUES ('nb', 'lea fakanouei pokimali');
INSERT INTO [country] ([id], [name]) VALUES ('en', 'lea fakapālangi');
INSERT INTO [country] ([id], [name]) VALUES ('en_US', 'lea fakapālangi ʻamelika');
INSERT INTO [country] ([id], [name]) VALUES ('en_AU', 'lea fakapālangi ʻaositelēlia');
INSERT INTO [country] ([id], [name]) VALUES ('en_CA', 'lea fakapālangi kānata');
INSERT INTO [country] ([id], [name]) VALUES ('be', 'lea fakapelelusi');
INSERT INTO [country] ([id], [name]) VALUES ('my', 'lea fakapema');
INSERT INTO [country] ([id], [name]) VALUES ('bn', 'lea fakapengila');
INSERT INTO [country] ([id], [name]) VALUES ('fa', 'lea fakapēsia');
INSERT INTO [country] ([id], [name]) VALUES ('en_GB', 'lea fakapilitānia');
INSERT INTO [country] ([id], [name]) VALUES ('bg', 'lea fakapokalia');
INSERT INTO [country] ([id], [name]) VALUES ('pl', 'lea fakapōlani');
INSERT INTO [country] ([id], [name]) VALUES ('bs', 'lea fakaposinia');
INSERT INTO [country] ([id], [name]) VALUES ('pt', 'lea fakapotukali');
INSERT INTO [country] ([id], [name]) VALUES ('pt_PT', 'lea fakapotukali ʻaipilieni');
INSERT INTO [country] ([id], [name]) VALUES ('pt_BR', 'lea fakapotukali-palāsili');
INSERT INTO [country] ([id], [name]) VALUES ('dz', 'lea fakaputeni');
INSERT INTO [country] ([id], [name]) VALUES ('jv', 'lea fakasava');
INSERT INTO [country] ([id], [name]) VALUES ('cs', 'lea fakaseki');
INSERT INTO [country] ([id], [name]) VALUES ('si', 'lea fakaselengika');
INSERT INTO [country] ([id], [name]) VALUES ('sr', 'lea fakasēpia');
INSERT INTO [country] ([id], [name]) VALUES ('zh', 'lea fakasiaina');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hans', 'lea fakasiaina fakangofua');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hant', 'lea fakasiaina tukufakaholo');
INSERT INTO [country] ([id], [name]) VALUES ('de', 'lea fakasiamane');
INSERT INTO [country] ([id], [name]) VALUES ('de_AT', 'lea fakasiamani ʻaositulia');
INSERT INTO [country] ([id], [name]) VALUES ('gsw', 'lea fakasiamani suitisālani');
INSERT INTO [country] ([id], [name]) VALUES ('de_CH', 'lea fakasiamani suitisālani ma''olunga');
INSERT INTO [country] ([id], [name]) VALUES ('ja', 'lea fakasiapani');
INSERT INTO [country] ([id], [name]) VALUES ('sco', 'lea fakasikotilani');
INSERT INTO [country] ([id], [name]) VALUES ('es', 'lea fakasīpenisi');
INSERT INTO [country] ([id], [name]) VALUES ('es_ES', 'lea fakasipēnisi ʻaipilieni');
INSERT INTO [country] ([id], [name]) VALUES ('es_419', 'lea fakasipēnisi lātini ʻamelika');
INSERT INTO [country] ([id], [name]) VALUES ('sk', 'lea fakasolāvaki');
INSERT INTO [country] ([id], [name]) VALUES ('sl', 'lea fakasolovenia');
INSERT INTO [country] ([id], [name]) VALUES ('so', 'lea fakasomali');
INSERT INTO [country] ([id], [name]) VALUES ('ka', 'lea fakasōsia');
INSERT INTO [country] ([id], [name]) VALUES ('ss', 'lea fakasuasilani');
INSERT INTO [country] ([id], [name]) VALUES ('sv', 'lea fakasueteni');
INSERT INTO [country] ([id], [name]) VALUES ('zu', 'lea fakasulu');
INSERT INTO [country] ([id], [name]) VALUES ('ty', 'lea fakatahiti');
INSERT INTO [country] ([id], [name]) VALUES ('th', 'lea fakataileni');
INSERT INTO [country] ([id], [name]) VALUES ('bo', 'lea fakataipeti');
INSERT INTO [country] ([id], [name]) VALUES ('tl', 'lea fakatekaloka');
INSERT INTO [country] ([id], [name]) VALUES ('ta', 'lea fakatemole');
INSERT INTO [country] ([id], [name]) VALUES ('da', 'lea fakatenimaʻake');
INSERT INTO [country] ([id], [name]) VALUES ('tet', 'lea fakatētamu');
INSERT INTO [country] ([id], [name]) VALUES ('tg', 'lea fakatetiki');
INSERT INTO [country] ([id], [name]) VALUES ('ti', 'lea fakatikilina');
INSERT INTO [country] ([id], [name]) VALUES ('tr', 'lea fakatoake');
INSERT INTO [country] ([id], [name]) VALUES ('tkl', 'lea fakatokelau');
INSERT INTO [country] ([id], [name]) VALUES ('to', 'lea fakatonga');
INSERT INTO [country] ([id], [name]) VALUES ('xh', 'lea fakatōsa');
INSERT INTO [country] ([id], [name]) VALUES ('tvl', 'lea fakatūvalu');
INSERT INTO [country] ([id], [name]) VALUES ('cy', 'lea fakauēlesi');
INSERT INTO [country] ([id], [name]) VALUES ('ve', 'lea fakavenitā');
INSERT INTO [country] ([id], [name]) VALUES ('vi', 'lea fakavietinemi');
INSERT INTO [country] ([id], [name]) VALUES ('ha', 'lea hausa');
INSERT INTO [country] ([id], [name]) VALUES ('ay', 'lea ʻaimala');
INSERT INTO [country] ([id], [name]) VALUES ('am', 'lea ʻameliki');
INSERT INTO [country] ([id], [name]) VALUES ('as', 'lea ʻasamisi');
INSERT INTO [country] ([id], [name]) VALUES ('efi', 'lea ʻefiki');
INSERT INTO [country] ([id], [name]) VALUES ('ig', 'lea ʻikipō');
INSERT INTO [country] ([id], [name]) VALUES ('os', 'lea ʻosetiki');
INSERT INTO [country] ([id], [name]) VALUES ('gl', 'lea kalisieni');
INSERT INTO [country] ([id], [name]) VALUES ('kn', 'lea kanata');
INSERT INTO [country] ([id], [name]) VALUES ('mis', 'lea kehekehe');
INSERT INTO [country] ([id], [name]) VALUES ('yue', 'lea kenitēnisi');
INSERT INTO [country] ([id], [name]) VALUES ('ku', 'lea kētisi');
INSERT INTO [country] ([id], [name]) VALUES ('gn', 'lea kualani');
INSERT INTO [country] ([id], [name]) VALUES ('qu', 'lea kuetisa');
INSERT INTO [country] ([id], [name]) VALUES ('gu', 'lea kutalati');
INSERT INTO [country] ([id], [name]) VALUES ('rm', 'lea laito-lomēnia');
INSERT INTO [country] ([id], [name]) VALUES ('lah', 'lea lanita');
INSERT INTO [country] ([id], [name]) VALUES ('ln', 'lea lingikala');
INSERT INTO [country] ([id], [name]) VALUES ('rn', 'lea luaniti');
INSERT INTO [country] ([id], [name]) VALUES ('mr', 'lea malati');
INSERT INTO [country] ([id], [name]) VALUES ('nd', 'lea netepele fakatokelau');
INSERT INTO [country] ([id], [name]) VALUES ('eu', 'lea pasiki');
INSERT INTO [country] ([id], [name]) VALUES ('ps', 'lea pasito');
INSERT INTO [country] ([id], [name]) VALUES ('pa', 'lea punusapi');
INSERT INTO [country] ([id], [name]) VALUES ('se', 'lea sami fakatokelau');
INSERT INTO [country] ([id], [name]) VALUES ('sg', 'lea sango');
INSERT INTO [country] ([id], [name]) VALUES ('sa', 'lea sanisukuliti');
INSERT INTO [country] ([id], [name]) VALUES ('su', 'lea sanita');
INSERT INTO [country] ([id], [name]) VALUES ('sh', 'lea sēpia-kuloisia');
INSERT INTO [country] ([id], [name]) VALUES ('sd', 'lea siniti');
INSERT INTO [country] ([id], [name]) VALUES ('nso', 'lea sofo fakatokelau');
INSERT INTO [country] ([id], [name]) VALUES ('st', 'lea sofo fakatonga');
INSERT INTO [country] ([id], [name]) VALUES ('sn', 'lea sona');
INSERT INTO [country] ([id], [name]) VALUES ('ts', 'lea songa');
INSERT INTO [country] ([id], [name]) VALUES ('ny', 'lea sua');
INSERT INTO [country] ([id], [name]) VALUES ('sw', 'lea suahile');
INSERT INTO [country] ([id], [name]) VALUES ('tn', 'lea suana');
INSERT INTO [country] ([id], [name]) VALUES ('und', 'lea taʻeʻiloa');
INSERT INTO [country] ([id], [name]) VALUES ('tk', 'lea tekimeni');
INSERT INTO [country] ([id], [name]) VALUES ('dv', 'lea tivehi');
INSERT INTO [country] ([id], [name]) VALUES ('tpi', 'lea toki pisini');
