CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('ab', 'Abhazca');
INSERT INTO [country] ([id], [name]) VALUES ('ace', 'Achinese');
INSERT INTO [country] ([id], [name]) VALUES ('ach', 'Acoli');
INSERT INTO [country] ([id], [name]) VALUES ('ada', 'Adangme');
INSERT INTO [country] ([id], [name]) VALUES ('ady', 'Adigece');
INSERT INTO [country] ([id], [name]) VALUES ('aa', 'Afar');
INSERT INTO [country] ([id], [name]) VALUES ('afh', 'Afrihili');
INSERT INTO [country] ([id], [name]) VALUES ('af', 'Afrikaan Dili');
INSERT INTO [country] ([id], [name]) VALUES ('afa', 'Afro-Asyatik Diller');
INSERT INTO [country] ([id], [name]) VALUES ('akk', 'Akad Dili');
INSERT INTO [country] ([id], [name]) VALUES ('ak', 'Akan');
INSERT INTO [country] ([id], [name]) VALUES ('ale', 'Aleut');
INSERT INTO [country] ([id], [name]) VALUES ('alg', 'Algonkin Dili');
INSERT INTO [country] ([id], [name]) VALUES ('de', 'Almanca');
INSERT INTO [country] ([id], [name]) VALUES ('tut', 'Altay Dilleri');
INSERT INTO [country] ([id], [name]) VALUES ('en_US', 'Amerikan İngilizcesi');
INSERT INTO [country] ([id], [name]) VALUES ('am', 'Amharca');
INSERT INTO [country] ([id], [name]) VALUES ('anp', 'Angika');
INSERT INTO [country] ([id], [name]) VALUES ('grc', 'Antik Yunanca');
INSERT INTO [country] ([id], [name]) VALUES ('apa', 'Apaçi Dilleri');
INSERT INTO [country] ([id], [name]) VALUES ('an', 'Aragonca');
INSERT INTO [country] ([id], [name]) VALUES ('arc', 'Aramice');
INSERT INTO [country] ([id], [name]) VALUES ('arp', 'Arapaho Dili');
INSERT INTO [country] ([id], [name]) VALUES ('ar', 'Arapça');
INSERT INTO [country] ([id], [name]) VALUES ('arn', 'Araukanya Dili');
INSERT INTO [country] ([id], [name]) VALUES ('arw', 'Arawak Dili');
INSERT INTO [country] ([id], [name]) VALUES ('bho', 'Arayanice');
INSERT INTO [country] ([id], [name]) VALUES ('sq', 'Arnavutça');
INSERT INTO [country] ([id], [name]) VALUES ('as', 'Assamca');
INSERT INTO [country] ([id], [name]) VALUES ('ast', 'Asturyasca');
INSERT INTO [country] ([id], [name]) VALUES ('nds', 'Aşağı Almanca');
INSERT INTO [country] ([id], [name]) VALUES ('dsb', 'Aşağı Sorbça');
INSERT INTO [country] ([id], [name]) VALUES ('ath', 'Atabaşkan Dilleri');
INSERT INTO [country] ([id], [name]) VALUES ('cch', 'Atsam');
INSERT INTO [country] ([id], [name]) VALUES ('av', 'Avar Dili');
INSERT INTO [country] ([id], [name]) VALUES ('ae', 'Avestçe');
INSERT INTO [country] ([id], [name]) VALUES ('aus', 'Avustralya Dilleri');
INSERT INTO [country] ([id], [name]) VALUES ('en_AU', 'Avustralya İngilizcesi');
INSERT INTO [country] ([id], [name]) VALUES ('map', 'Avustronezya Dili');
INSERT INTO [country] ([id], [name]) VALUES ('de_AT', 'Avusturya Almancası');
INSERT INTO [country] ([id], [name]) VALUES ('awa', 'Awadhi');
INSERT INTO [country] ([id], [name]) VALUES ('ay', 'Aymara');
INSERT INTO [country] ([id], [name]) VALUES ('ain', 'Ayni Dili');
INSERT INTO [country] ([id], [name]) VALUES ('az', 'Azerice');
INSERT INTO [country] ([id], [name]) VALUES ('ban', 'Bali Dili');
INSERT INTO [country] ([id], [name]) VALUES ('bat', 'Baltık Dilleri');
INSERT INTO [country] ([id], [name]) VALUES ('bal', 'Baluchi');
INSERT INTO [country] ([id], [name]) VALUES ('bm', 'Bambara');
INSERT INTO [country] ([id], [name]) VALUES ('bai', 'Bamileke Dilleri');
INSERT INTO [country] ([id], [name]) VALUES ('bad', 'Banda Dili');
INSERT INTO [country] ([id], [name]) VALUES ('bnt', 'Bantu Dili');
INSERT INTO [country] ([id], [name]) VALUES ('bas', 'Basa Dili');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hans', 'Basitleştirilmiş Çince');
INSERT INTO [country] ([id], [name]) VALUES ('eu', 'Baskça');
INSERT INTO [country] ([id], [name]) VALUES ('ba', 'Başkırtça');
INSERT INTO [country] ([id], [name]) VALUES ('btk', 'Batak');
INSERT INTO [country] ([id], [name]) VALUES ('fy', 'Batı Frizcesi');
INSERT INTO [country] ([id], [name]) VALUES ('bej', 'Beja Dili');
INSERT INTO [country] ([id], [name]) VALUES ('bem', 'Bemba');
INSERT INTO [country] ([id], [name]) VALUES ('bn', 'Bengalce');
INSERT INTO [country] ([id], [name]) VALUES ('ber', 'Berberi');
INSERT INTO [country] ([id], [name]) VALUES ('be', 'Beyaz Rusça');
INSERT INTO [country] ([id], [name]) VALUES ('bh', 'Bihari');
INSERT INTO [country] ([id], [name]) VALUES ('bik', 'Bikol');
INSERT INTO [country] ([id], [name]) VALUES ('und', 'Bilinmeyen Dil');
INSERT INTO [country] ([id], [name]) VALUES ('bin', 'Bini');
INSERT INTO [country] ([id], [name]) VALUES ('my', 'Birmanya Dili');
INSERT INTO [country] ([id], [name]) VALUES ('bi', 'Bislama');
INSERT INTO [country] ([id], [name]) VALUES ('byn', 'Blin');
INSERT INTO [country] ([id], [name]) VALUES ('zbl', 'Blis Sembolleri');
INSERT INTO [country] ([id], [name]) VALUES ('bs', 'Boşnakça');
INSERT INTO [country] ([id], [name]) VALUES ('bra', 'Braj');
INSERT INTO [country] ([id], [name]) VALUES ('br', 'Bretonca');
INSERT INTO [country] ([id], [name]) VALUES ('pt_BR', 'Brezilya Portekizcesi');
INSERT INTO [country] ([id], [name]) VALUES ('bug', 'Bugis');
INSERT INTO [country] ([id], [name]) VALUES ('bg', 'Bulgarca');
INSERT INTO [country] ([id], [name]) VALUES ('bua', 'Buryat');
INSERT INTO [country] ([id], [name]) VALUES ('dz', 'Butan Dili');
INSERT INTO [country] ([id], [name]) VALUES ('cad', 'Caddo');
INSERT INTO [country] ([id], [name]) VALUES ('car', 'Carib');
INSERT INTO [country] ([id], [name]) VALUES ('jv', 'Cava Dili');
INSERT INTO [country] ([id], [name]) VALUES ('ceb', 'Cebuano');
INSERT INTO [country] ([id], [name]) VALUES ('gem', 'Cermen Dilleri');
INSERT INTO [country] ([id], [name]) VALUES ('cmc', 'Chamic Dilleri');
INSERT INTO [country] ([id], [name]) VALUES ('ch', 'Chamorro');
INSERT INTO [country] ([id], [name]) VALUES ('chb', 'Chibcha');
INSERT INTO [country] ([id], [name]) VALUES ('chn', 'Chinook Jargon');
INSERT INTO [country] ([id], [name]) VALUES ('chp', 'Chipewyan');
INSERT INTO [country] ([id], [name]) VALUES ('cho', 'Choctaw');
INSERT INTO [country] ([id], [name]) VALUES ('chk', 'Chuukese');
INSERT INTO [country] ([id], [name]) VALUES ('cr', 'Cree');
INSERT INTO [country] ([id], [name]) VALUES ('mus', 'Creek');
INSERT INTO [country] ([id], [name]) VALUES ('crp', 'Creole ve Pidgin Dilleri');
INSERT INTO [country] ([id], [name]) VALUES ('chg', 'Çağatay Dili');
INSERT INTO [country] ([id], [name]) VALUES ('ce', 'Çeçence');
INSERT INTO [country] ([id], [name]) VALUES ('cs', 'Çekçe');
INSERT INTO [country] ([id], [name]) VALUES ('chr', 'Çeroki');
INSERT INTO [country] ([id], [name]) VALUES ('mis', 'Çeşitli Diller');
INSERT INTO [country] ([id], [name]) VALUES ('zh', 'Çince');
INSERT INTO [country] ([id], [name]) VALUES ('cv', 'Çuvaşça');
INSERT INTO [country] ([id], [name]) VALUES ('dak', 'Dakota');
INSERT INTO [country] ([id], [name]) VALUES ('da', 'Danca');
INSERT INTO [country] ([id], [name]) VALUES ('dar', 'Dargince');
INSERT INTO [country] ([id], [name]) VALUES ('day', 'Dayak');
INSERT INTO [country] ([id], [name]) VALUES ('del', 'Delaware');
INSERT INTO [country] ([id], [name]) VALUES ('zxx', 'Dilbilim içeriği yok');
INSERT INTO [country] ([id], [name]) VALUES ('din', 'Dinka');
INSERT INTO [country] ([id], [name]) VALUES ('dv', 'Divehi');
INSERT INTO [country] ([id], [name]) VALUES ('doi', 'Dogri');
INSERT INTO [country] ([id], [name]) VALUES ('dgr', 'Dogrib');
INSERT INTO [country] ([id], [name]) VALUES ('frs', 'Doğu Frizcesi');
INSERT INTO [country] ([id], [name]) VALUES ('dra', 'Dravid Dilleri');
INSERT INTO [country] ([id], [name]) VALUES ('dua', 'Duala');
INSERT INTO [country] ([id], [name]) VALUES ('dyu', 'Dyula');
INSERT INTO [country] ([id], [name]) VALUES ('efi', 'Efik');
INSERT INTO [country] ([id], [name]) VALUES ('eka', 'Ekajuk');
INSERT INTO [country] ([id], [name]) VALUES ('elx', 'Elam');
INSERT INTO [country] ([id], [name]) VALUES ('id', 'Endonezce');
INSERT INTO [country] ([id], [name]) VALUES ('hy', 'Ermenice');
INSERT INTO [country] ([id], [name]) VALUES ('myv', 'Erzya');
INSERT INTO [country] ([id], [name]) VALUES ('peo', 'Eski Farsça');
INSERT INTO [country] ([id], [name]) VALUES ('fro', 'Eski Fransızca');
INSERT INTO [country] ([id], [name]) VALUES ('ang', 'Eski İngilizce');
INSERT INTO [country] ([id], [name]) VALUES ('sga', 'Eski İrlandaca');
INSERT INTO [country] ([id], [name]) VALUES ('egy', 'Eski Mısır Dili');
INSERT INTO [country] ([id], [name]) VALUES ('non', 'Eski Norse');
INSERT INTO [country] ([id], [name]) VALUES ('pro', 'Eski Provensal');
INSERT INTO [country] ([id], [name]) VALUES ('goh', 'Eski Yüksek Almanca');
INSERT INTO [country] ([id], [name]) VALUES ('eo', 'Esperanto');
INSERT INTO [country] ([id], [name]) VALUES ('et', 'Estonca');
INSERT INTO [country] ([id], [name]) VALUES ('ee', 'Ewe');
INSERT INTO [country] ([id], [name]) VALUES ('ewo', 'Ewondo');
INSERT INTO [country] ([id], [name]) VALUES ('fan', 'Fang');
INSERT INTO [country] ([id], [name]) VALUES ('fat', 'Fanti');
INSERT INTO [country] ([id], [name]) VALUES ('fo', 'Faroe Dili');
INSERT INTO [country] ([id], [name]) VALUES ('fa', 'Farsça');
INSERT INTO [country] ([id], [name]) VALUES ('nl', 'Felemenkçe');
INSERT INTO [country] ([id], [name]) VALUES ('phn', 'Fenike Dili');
INSERT INTO [country] ([id], [name]) VALUES ('fj', 'Fiji Dili');
INSERT INTO [country] ([id], [name]) VALUES ('phi', 'Filipinler Dilleri');
INSERT INTO [country] ([id], [name]) VALUES ('fil', 'Filipino');
INSERT INTO [country] ([id], [name]) VALUES ('fi', 'Fince');
INSERT INTO [country] ([id], [name]) VALUES ('fiu', 'Finno - Ugrik Diller');
INSERT INTO [country] ([id], [name]) VALUES ('nl_BE', 'Flamanca');
INSERT INTO [country] ([id], [name]) VALUES ('fon', 'Fon');
INSERT INTO [country] ([id], [name]) VALUES ('fr', 'Fransızca');
INSERT INTO [country] ([id], [name]) VALUES ('cpf', 'Fransızca tabanlı Creole ve Pidgin Dilleri');
INSERT INTO [country] ([id], [name]) VALUES ('fur', 'Friulian');
INSERT INTO [country] ([id], [name]) VALUES ('ff', 'Fulah');
INSERT INTO [country] ([id], [name]) VALUES ('gaa', 'Ga');
INSERT INTO [country] ([id], [name]) VALUES ('cy', 'Galce');
INSERT INTO [country] ([id], [name]) VALUES ('gl', 'Galiçyaca');
INSERT INTO [country] ([id], [name]) VALUES ('lg', 'Ganda');
INSERT INTO [country] ([id], [name]) VALUES ('gay', 'Gayo');
INSERT INTO [country] ([id], [name]) VALUES ('gba', 'Gbaya');
INSERT INTO [country] ([id], [name]) VALUES ('gez', 'Geez');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hant', 'Geleneksel Çince');
INSERT INTO [country] ([id], [name]) VALUES ('gon', 'Gondi');
INSERT INTO [country] ([id], [name]) VALUES ('gor', 'Gorontalo');
INSERT INTO [country] ([id], [name]) VALUES ('got', 'Gotça');
INSERT INTO [country] ([id], [name]) VALUES ('grb', 'Grebo');
INSERT INTO [country] ([id], [name]) VALUES ('kl', 'Grönland Dili');
INSERT INTO [country] ([id], [name]) VALUES ('gn', 'Guarani');
INSERT INTO [country] ([id], [name]) VALUES ('gu', 'Gücerat Dili');
INSERT INTO [country] ([id], [name]) VALUES ('alt', 'Güney Altayca');
INSERT INTO [country] ([id], [name]) VALUES ('sai', 'Güney Amerika Yerli Dilleri');
INSERT INTO [country] ([id], [name]) VALUES ('nr', 'Güney Ndebele');
INSERT INTO [country] ([id], [name]) VALUES ('sma', 'Güney Sami');
INSERT INTO [country] ([id], [name]) VALUES ('st', 'Güney Sotho');
INSERT INTO [country] ([id], [name]) VALUES ('ka', 'Gürcüce');
INSERT INTO [country] ([id], [name]) VALUES ('gwi', 'Gwichʼin');
INSERT INTO [country] ([id], [name]) VALUES ('hai', 'Haida');
INSERT INTO [country] ([id], [name]) VALUES ('ht', 'Haiti Dili');
INSERT INTO [country] ([id], [name]) VALUES ('ha', 'Hausa');
INSERT INTO [country] ([id], [name]) VALUES ('haw', 'Hawaii Dili');
INSERT INTO [country] ([id], [name]) VALUES ('hz', 'Herero');
INSERT INTO [country] ([id], [name]) VALUES ('hr', 'Hırvatça');
INSERT INTO [country] ([id], [name]) VALUES ('hil', 'Hiligaynon');
INSERT INTO [country] ([id], [name]) VALUES ('him', 'Himachali');
INSERT INTO [country] ([id], [name]) VALUES ('inc', 'Hint Dilleri');
INSERT INTO [country] ([id], [name]) VALUES ('ine', 'Hint-Avrupa Dilleri');
INSERT INTO [country] ([id], [name]) VALUES ('hi', 'Hintçe');
INSERT INTO [country] ([id], [name]) VALUES ('ho', 'Hiri Motu');
INSERT INTO [country] ([id], [name]) VALUES ('hit', 'Hititçe');
INSERT INTO [country] ([id], [name]) VALUES ('hmn', 'Hmong');
INSERT INTO [country] ([id], [name]) VALUES ('khi', 'Hoisan Dilleri');
INSERT INTO [country] ([id], [name]) VALUES ('kho', 'Hotanca');
INSERT INTO [country] ([id], [name]) VALUES ('hup', 'Hupa');
INSERT INTO [country] ([id], [name]) VALUES ('iba', 'Iban');
INSERT INTO [country] ([id], [name]) VALUES ('io', 'Ido');
INSERT INTO [country] ([id], [name]) VALUES ('ijo', 'Ijo');
INSERT INTO [country] ([id], [name]) VALUES ('ilo', 'Iloko');
INSERT INTO [country] ([id], [name]) VALUES ('smn', 'Inari Sami');
INSERT INTO [country] ([id], [name]) VALUES ('ia', 'Interlingua');
INSERT INTO [country] ([id], [name]) VALUES ('ie', 'Interlingue');
INSERT INTO [country] ([id], [name]) VALUES ('iu', 'Inuktitut');
INSERT INTO [country] ([id], [name]) VALUES ('ik', 'Inupiak');
INSERT INTO [country] ([id], [name]) VALUES ('es_ES', 'İber İspanyolcası');
INSERT INTO [country] ([id], [name]) VALUES ('pt_PT', 'İber Portekizcesi');
INSERT INTO [country] ([id], [name]) VALUES ('he', 'İbranice');
INSERT INTO [country] ([id], [name]) VALUES ('ig', 'İgbo Dili');
INSERT INTO [country] ([id], [name]) VALUES ('en_GB', 'İngiliz İngilizcesi');
INSERT INTO [country] ([id], [name]) VALUES ('en', 'İngilizce');
INSERT INTO [country] ([id], [name]) VALUES ('cpe', 'İngilizce tabanlı Creole ve Pidgin Dilleri');
INSERT INTO [country] ([id], [name]) VALUES ('inh', 'İnguşça');
INSERT INTO [country] ([id], [name]) VALUES ('ira', 'İran Dilleri');
INSERT INTO [country] ([id], [name]) VALUES ('ga', 'İrlanda Dili');
INSERT INTO [country] ([id], [name]) VALUES ('iro', 'İroqua Dili');
INSERT INTO [country] ([id], [name]) VALUES ('gd', 'İskoç Gal Dili');
INSERT INTO [country] ([id], [name]) VALUES ('es', 'İspanyolca');
INSERT INTO [country] ([id], [name]) VALUES ('sv', 'İsveççe');
INSERT INTO [country] ([id], [name]) VALUES ('gsw', 'İsviçre Almancası');
INSERT INTO [country] ([id], [name]) VALUES ('fr_CH', 'İsviçre Fransızcası');
INSERT INTO [country] ([id], [name]) VALUES ('de_CH', 'İsviçre Yüksek Almancası');
INSERT INTO [country] ([id], [name]) VALUES ('sgn', 'İşaret Dilleri');
INSERT INTO [country] ([id], [name]) VALUES ('it', 'İtalyanca');
INSERT INTO [country] ([id], [name]) VALUES ('is', 'İzlandaca');
INSERT INTO [country] ([id], [name]) VALUES ('ja', 'Japonca');
INSERT INTO [country] ([id], [name]) VALUES ('kaj', 'Jju');
INSERT INTO [country] ([id], [name]) VALUES ('kbd', 'Kabardeyce');
INSERT INTO [country] ([id], [name]) VALUES ('kab', 'Kabile');
INSERT INTO [country] ([id], [name]) VALUES ('kac', 'Kaçin');
INSERT INTO [country] ([id], [name]) VALUES ('cau', 'Kafkas Dilleri');
INSERT INTO [country] ([id], [name]) VALUES ('xal', 'Kalmıkça');
INSERT INTO [country] ([id], [name]) VALUES ('kam', 'Kamba');
INSERT INTO [country] ([id], [name]) VALUES ('km', 'Kamboçya Dili');
INSERT INTO [country] ([id], [name]) VALUES ('fr_CA', 'Kanada Fransızcası');
INSERT INTO [country] ([id], [name]) VALUES ('en_CA', 'Kanada İngilizcesi');
INSERT INTO [country] ([id], [name]) VALUES ('kn', 'Kannada');
INSERT INTO [country] ([id], [name]) VALUES ('yue', 'Kantonca');
INSERT INTO [country] ([id], [name]) VALUES ('kr', 'Kanuri');
INSERT INTO [country] ([id], [name]) VALUES ('krc', 'Karaçay-Balkarca');
INSERT INTO [country] ([id], [name]) VALUES ('kaa', 'Karakalpakça');
INSERT INTO [country] ([id], [name]) VALUES ('krl', 'Karelyaca');
INSERT INTO [country] ([id], [name]) VALUES ('kar', 'Karen');
INSERT INTO [country] ([id], [name]) VALUES ('csb', 'Kashubian');
INSERT INTO [country] ([id], [name]) VALUES ('ca', 'Katalanca');
INSERT INTO [country] ([id], [name]) VALUES ('kaw', 'Kawi');
INSERT INTO [country] ([id], [name]) VALUES ('kk', 'Kazakça');
INSERT INTO [country] ([id], [name]) VALUES ('cel', 'Kelt Dilleri');
INSERT INTO [country] ([id], [name]) VALUES ('kw', 'Kernevekçe');
INSERT INTO [country] ([id], [name]) VALUES ('ks', 'Keşmirce');
INSERT INTO [country] ([id], [name]) VALUES ('kha', 'Khasi');
INSERT INTO [country] ([id], [name]) VALUES ('cop', 'Kıptice');
INSERT INTO [country] ([id], [name]) VALUES ('ky', 'Kırgızca');
INSERT INTO [country] ([id], [name]) VALUES ('crh', 'Kırım Türkçesi');
INSERT INTO [country] ([id], [name]) VALUES ('ki', 'Kikuyu');
INSERT INTO [country] ([id], [name]) VALUES ('cu', 'Kilise Slavcası');
INSERT INTO [country] ([id], [name]) VALUES ('kmb', 'Kimbundu');
INSERT INTO [country] ([id], [name]) VALUES ('rw', 'Kinyarwanda');
INSERT INTO [country] ([id], [name]) VALUES ('gil', 'Kiribati Dili');
INSERT INTO [country] ([id], [name]) VALUES ('rn', 'Kirundi');
INSERT INTO [country] ([id], [name]) VALUES ('nwc', 'Klasik Nevari');
INSERT INTO [country] ([id], [name]) VALUES ('syc', 'Klasik Süryanice');
INSERT INTO [country] ([id], [name]) VALUES ('tlh', 'Klingon');
INSERT INTO [country] ([id], [name]) VALUES ('kv', 'Komi');
INSERT INTO [country] ([id], [name]) VALUES ('swb', 'Komorca');
INSERT INTO [country] ([id], [name]) VALUES ('kg', 'Kongo');
INSERT INTO [country] ([id], [name]) VALUES ('kok', 'Konkani');
INSERT INTO [country] ([id], [name]) VALUES ('ko', 'Korece');
INSERT INTO [country] ([id], [name]) VALUES ('kfo', 'Koro');
INSERT INTO [country] ([id], [name]) VALUES ('co', 'Korsikaca');
INSERT INTO [country] ([id], [name]) VALUES ('kos', 'Kosraean');
INSERT INTO [country] ([id], [name]) VALUES ('root', 'Köken');
INSERT INTO [country] ([id], [name]) VALUES ('kpe', 'Kpelle');
INSERT INTO [country] ([id], [name]) VALUES ('kro', 'Kru');
INSERT INTO [country] ([id], [name]) VALUES ('kj', 'Kuanyama');
INSERT INTO [country] ([id], [name]) VALUES ('kum', 'Kumukça');
INSERT INTO [country] ([id], [name]) VALUES ('kru', 'Kurukh');
INSERT INTO [country] ([id], [name]) VALUES ('cus', 'Kuşitik Diller');
INSERT INTO [country] ([id], [name]) VALUES ('kut', 'Kutenai');
INSERT INTO [country] ([id], [name]) VALUES ('nai', 'Kuzey Amerika Yerli Dilleri');
INSERT INTO [country] ([id], [name]) VALUES ('frr', 'Kuzey Frizce');
INSERT INTO [country] ([id], [name]) VALUES ('nd', 'Kuzey Ndebele');
INSERT INTO [country] ([id], [name]) VALUES ('se', 'Kuzey Sami');
INSERT INTO [country] ([id], [name]) VALUES ('nso', 'Kuzey Sotho');
INSERT INTO [country] ([id], [name]) VALUES ('ku', 'Kürtçe');
INSERT INTO [country] ([id], [name]) VALUES ('lad', 'Ladino');
INSERT INTO [country] ([id], [name]) VALUES ('lah', 'Lahnda');
INSERT INTO [country] ([id], [name]) VALUES ('lam', 'Lamba');
INSERT INTO [country] ([id], [name]) VALUES ('lo', 'Laos Dili');
INSERT INTO [country] ([id], [name]) VALUES ('es_419', 'Latin Amerika İspanyolcası');
INSERT INTO [country] ([id], [name]) VALUES ('la', 'Latince');
INSERT INTO [country] ([id], [name]) VALUES ('pl', 'Lehçe');
INSERT INTO [country] ([id], [name]) VALUES ('lv', 'Letonca');
INSERT INTO [country] ([id], [name]) VALUES ('lez', 'Lezgice');
INSERT INTO [country] ([id], [name]) VALUES ('li', 'Limburgca');
INSERT INTO [country] ([id], [name]) VALUES ('ln', 'Lingala');
INSERT INTO [country] ([id], [name]) VALUES ('lt', 'Litvanyaca');
INSERT INTO [country] ([id], [name]) VALUES ('jbo', 'Lojban');
INSERT INTO [country] ([id], [name]) VALUES ('loz', 'Lozi');
INSERT INTO [country] ([id], [name]) VALUES ('lu', 'Luba-Katanga');
INSERT INTO [country] ([id], [name]) VALUES ('lua', 'Luba-Lulua');
INSERT INTO [country] ([id], [name]) VALUES ('lui', 'Luiseno');
INSERT INTO [country] ([id], [name]) VALUES ('smj', 'Lule Sami');
INSERT INTO [country] ([id], [name]) VALUES ('lun', 'Lunda');
INSERT INTO [country] ([id], [name]) VALUES ('luo', 'Luo');
INSERT INTO [country] ([id], [name]) VALUES ('lus', 'Lushai');
INSERT INTO [country] ([id], [name]) VALUES ('lb', 'Lüksemburgca');
INSERT INTO [country] ([id], [name]) VALUES ('hu', 'Macarca');
INSERT INTO [country] ([id], [name]) VALUES ('mad', 'Madura Dili');
INSERT INTO [country] ([id], [name]) VALUES ('mag', 'Magahi');
INSERT INTO [country] ([id], [name]) VALUES ('mai', 'Maithili');
INSERT INTO [country] ([id], [name]) VALUES ('mak', 'Makasar');
INSERT INTO [country] ([id], [name]) VALUES ('mk', 'Makedonca');
INSERT INTO [country] ([id], [name]) VALUES ('mg', 'Malagasi');
INSERT INTO [country] ([id], [name]) VALUES ('ms', 'Malay');
INSERT INTO [country] ([id], [name]) VALUES ('ml', 'Malayalam');
INSERT INTO [country] ([id], [name]) VALUES ('mt', 'Maltaca');
INSERT INTO [country] ([id], [name]) VALUES ('mnc', 'Mançurya Dili');
INSERT INTO [country] ([id], [name]) VALUES ('mdr', 'Mandar');
INSERT INTO [country] ([id], [name]) VALUES ('man', 'Mandingo');
INSERT INTO [country] ([id], [name]) VALUES ('mni', 'Manipuri');
INSERT INTO [country] ([id], [name]) VALUES ('gv', 'Manks');
INSERT INTO [country] ([id], [name]) VALUES ('mno', 'Manobo Dilleri');
INSERT INTO [country] ([id], [name]) VALUES ('mi', 'Maori');
INSERT INTO [country] ([id], [name]) VALUES ('mr', 'Marathi');
INSERT INTO [country] ([id], [name]) VALUES ('chm', 'Mari');
INSERT INTO [country] ([id], [name]) VALUES ('mh', 'Marshall Adaları Dili');
INSERT INTO [country] ([id], [name]) VALUES ('mwr', 'Marvari');
INSERT INTO [country] ([id], [name]) VALUES ('mas', 'Masai');
INSERT INTO [country] ([id], [name]) VALUES ('myn', 'Maya Dilleri');
INSERT INTO [country] ([id], [name]) VALUES ('men', 'Mende');
INSERT INTO [country] ([id], [name]) VALUES ('mic', 'Micmac');
INSERT INTO [country] ([id], [name]) VALUES ('min', 'Minangkabau');
INSERT INTO [country] ([id], [name]) VALUES ('mwl', 'Miranda Dili');
INSERT INTO [country] ([id], [name]) VALUES ('mn', 'Moğolca');
INSERT INTO [country] ([id], [name]) VALUES ('moh', 'Mohavk Dili');
INSERT INTO [country] ([id], [name]) VALUES ('mdf', 'Mokşa Dili');
INSERT INTO [country] ([id], [name]) VALUES ('mo', 'Moldovaca');
INSERT INTO [country] ([id], [name]) VALUES ('mkh', 'Mon-Khmer Dilleri');
INSERT INTO [country] ([id], [name]) VALUES ('lol', 'Mongo');
INSERT INTO [country] ([id], [name]) VALUES ('mos', 'Mossi');
INSERT INTO [country] ([id], [name]) VALUES ('mun', 'Munda Dilleri');
INSERT INTO [country] ([id], [name]) VALUES ('nqo', 'N’Ko');
INSERT INTO [country] ([id], [name]) VALUES ('nah', 'Nahuatl');
INSERT INTO [country] ([id], [name]) VALUES ('nap', 'Napolice');
INSERT INTO [country] ([id], [name]) VALUES ('na', 'Nauru Dili');
INSERT INTO [country] ([id], [name]) VALUES ('nv', 'Navaho Dili');
INSERT INTO [country] ([id], [name]) VALUES ('ng', 'Ndonga');
INSERT INTO [country] ([id], [name]) VALUES ('ne', 'Nepalce');
INSERT INTO [country] ([id], [name]) VALUES ('new', 'Nevari');
INSERT INTO [country] ([id], [name]) VALUES ('nia', 'Nias');
INSERT INTO [country] ([id], [name]) VALUES ('nic', 'Nijer-Kordofan Dilleri');
INSERT INTO [country] ([id], [name]) VALUES ('ssa', 'Nil-Sahara Dilleri');
INSERT INTO [country] ([id], [name]) VALUES ('niu', 'Niuean');
INSERT INTO [country] ([id], [name]) VALUES ('nog', 'Nogayca');
INSERT INTO [country] ([id], [name]) VALUES ('no', 'Norveççe');
INSERT INTO [country] ([id], [name]) VALUES ('nb', 'Norveççe Bokmål');
INSERT INTO [country] ([id], [name]) VALUES ('nn', 'Norveççe Nynorsk');
INSERT INTO [country] ([id], [name]) VALUES ('nub', 'Nubian Dilleri');
INSERT INTO [country] ([id], [name]) VALUES ('nym', 'Nyamvezi');
INSERT INTO [country] ([id], [name]) VALUES ('ny', 'Nyanja');
INSERT INTO [country] ([id], [name]) VALUES ('nyn', 'Nyankole');
INSERT INTO [country] ([id], [name]) VALUES ('tog', 'Nyasa Tonga');
INSERT INTO [country] ([id], [name]) VALUES ('nyo', 'Nyoro');
INSERT INTO [country] ([id], [name]) VALUES ('nzi', 'Nzima');
INSERT INTO [country] ([id], [name]) VALUES ('oj', 'Ojibva Dili');
INSERT INTO [country] ([id], [name]) VALUES ('oc', 'Oksitanca');
INSERT INTO [country] ([id], [name]) VALUES ('or', 'Oriya');
INSERT INTO [country] ([id], [name]) VALUES ('om', 'Oromo');
INSERT INTO [country] ([id], [name]) VALUES ('cai', 'Orta Amerika Yerli Dilleri');
INSERT INTO [country] ([id], [name]) VALUES ('dum', 'Ortaçağ Felemenkçesi');
INSERT INTO [country] ([id], [name]) VALUES ('frm', 'Ortaçağ Fransızcası');
INSERT INTO [country] ([id], [name]) VALUES ('enm', 'Ortaçağ İngilizcesi');
INSERT INTO [country] ([id], [name]) VALUES ('mga', 'Ortaçağ İrlandacası');
INSERT INTO [country] ([id], [name]) VALUES ('gmh', 'Ortaçağ Yüksek Almancası');
INSERT INTO [country] ([id], [name]) VALUES ('osa', 'Osage');
INSERT INTO [country] ([id], [name]) VALUES ('os', 'Osetçe');
INSERT INTO [country] ([id], [name]) VALUES ('ota', 'Osmanlı Türkçesi');
INSERT INTO [country] ([id], [name]) VALUES ('oto', 'Otomi Dilleri');
INSERT INTO [country] ([id], [name]) VALUES ('uz', 'Özbekçe');
INSERT INTO [country] ([id], [name]) VALUES ('pau', 'Palau Dili');
INSERT INTO [country] ([id], [name]) VALUES ('pi', 'Pali');
INSERT INTO [country] ([id], [name]) VALUES ('pam', 'Pampanga');
INSERT INTO [country] ([id], [name]) VALUES ('pag', 'Pangasinan');
INSERT INTO [country] ([id], [name]) VALUES ('pap', 'Papiamento');
INSERT INTO [country] ([id], [name]) VALUES ('paa', 'Papua Dilleri');
INSERT INTO [country] ([id], [name]) VALUES ('pal', 'Pehlevi Dili');
INSERT INTO [country] ([id], [name]) VALUES ('pa', 'Pencap Dili');
INSERT INTO [country] ([id], [name]) VALUES ('ps', 'Peştuca');
INSERT INTO [country] ([id], [name]) VALUES ('pon', 'Pohnpeian');
INSERT INTO [country] ([id], [name]) VALUES ('pt', 'Portekizce');
INSERT INTO [country] ([id], [name]) VALUES ('cpp', 'Portekizce tabanlı Creole ve Pidgin Dilleri');
INSERT INTO [country] ([id], [name]) VALUES ('pra', 'Prakrit Dilleri');
INSERT INTO [country] ([id], [name]) VALUES ('qu', 'Quechua');
INSERT INTO [country] ([id], [name]) VALUES ('raj', 'Rajasthani');
INSERT INTO [country] ([id], [name]) VALUES ('rap', 'Rapanui');
INSERT INTO [country] ([id], [name]) VALUES ('rar', 'Rarotongan');
INSERT INTO [country] ([id], [name]) VALUES ('rm', 'Rhaeto-Roman Dili');
INSERT INTO [country] ([id], [name]) VALUES ('roa', 'Roman Dilleri');
INSERT INTO [country] ([id], [name]) VALUES ('rom', 'Romanca');
INSERT INTO [country] ([id], [name]) VALUES ('ro', 'Romence');
INSERT INTO [country] ([id], [name]) VALUES ('ru', 'Rusça');
INSERT INTO [country] ([id], [name]) VALUES ('sal', 'Salishan Dilleri');
INSERT INTO [country] ([id], [name]) VALUES ('sam', 'Samarit Aramcası');
INSERT INTO [country] ([id], [name]) VALUES ('smi', 'Sami Dilleri');
INSERT INTO [country] ([id], [name]) VALUES ('sm', 'Samoa Dili');
INSERT INTO [country] ([id], [name]) VALUES ('sad', 'Sandave');
INSERT INTO [country] ([id], [name]) VALUES ('sg', 'Sangho');
INSERT INTO [country] ([id], [name]) VALUES ('sa', 'Sanskritçe');
INSERT INTO [country] ([id], [name]) VALUES ('sat', 'Santali');
INSERT INTO [country] ([id], [name]) VALUES ('sc', 'Sardunya Dili');
INSERT INTO [country] ([id], [name]) VALUES ('sas', 'Sasak');
INSERT INTO [country] ([id], [name]) VALUES ('sco', 'Scots');
INSERT INTO [country] ([id], [name]) VALUES ('sel', 'Selkup');
INSERT INTO [country] ([id], [name]) VALUES ('sem', 'Semitik Diller');
INSERT INTO [country] ([id], [name]) VALUES ('srr', 'Serer');
INSERT INTO [country] ([id], [name]) VALUES ('tn', 'Setsvana');
INSERT INTO [country] ([id], [name]) VALUES ('si', 'Seylanca');
INSERT INTO [country] ([id], [name]) VALUES ('shn', 'Shan Dili');
INSERT INTO [country] ([id], [name]) VALUES ('sn', 'Shona');
INSERT INTO [country] ([id], [name]) VALUES ('sh', 'Sırp-Hırvat Dili');
INSERT INTO [country] ([id], [name]) VALUES ('sr', 'Sırpça');
INSERT INTO [country] ([id], [name]) VALUES ('ii', 'Sichuan Yi');
INSERT INTO [country] ([id], [name]) VALUES ('scn', 'Sicilyaca');
INSERT INTO [country] ([id], [name]) VALUES ('sid', 'Sidamo');
INSERT INTO [country] ([id], [name]) VALUES ('bla', 'Siksika');
INSERT INTO [country] ([id], [name]) VALUES ('sd', 'Sindhi');
INSERT INTO [country] ([id], [name]) VALUES ('sit', 'Sino-Tibet Dilleri');
INSERT INTO [country] ([id], [name]) VALUES ('ss', 'Sisvati');
INSERT INTO [country] ([id], [name]) VALUES ('sio', 'Siu Dilleri');
INSERT INTO [country] ([id], [name]) VALUES ('sms', 'Skolt Sami');
INSERT INTO [country] ([id], [name]) VALUES ('sla', 'Slav Dilleri');
INSERT INTO [country] ([id], [name]) VALUES ('den', 'Slavey');
INSERT INTO [country] ([id], [name]) VALUES ('sk', 'Slovakça');
INSERT INTO [country] ([id], [name]) VALUES ('sl', 'Slovence');
INSERT INTO [country] ([id], [name]) VALUES ('sog', 'Sogdiana Dili');
INSERT INTO [country] ([id], [name]) VALUES ('so', 'Somali Dili');
INSERT INTO [country] ([id], [name]) VALUES ('son', 'Songhai');
INSERT INTO [country] ([id], [name]) VALUES ('snk', 'Soninke');
INSERT INTO [country] ([id], [name]) VALUES ('wen', 'Sorb Dilleri');
INSERT INTO [country] ([id], [name]) VALUES ('srn', 'Sranan Tongo');
INSERT INTO [country] ([id], [name]) VALUES ('suk', 'Sukuma');
INSERT INTO [country] ([id], [name]) VALUES ('su', 'Sunda Dili');
INSERT INTO [country] ([id], [name]) VALUES ('sus', 'Susu');
INSERT INTO [country] ([id], [name]) VALUES ('sux', 'Sümerce');
INSERT INTO [country] ([id], [name]) VALUES ('syr', 'Süryanice');
INSERT INTO [country] ([id], [name]) VALUES ('sw', 'Svahili');
INSERT INTO [country] ([id], [name]) VALUES ('chy', 'Şayen Dili');
INSERT INTO [country] ([id], [name]) VALUES ('tg', 'Tacikçe');
INSERT INTO [country] ([id], [name]) VALUES ('ty', 'Tahiti Dili');
INSERT INTO [country] ([id], [name]) VALUES ('tai', 'Tai Dili');
INSERT INTO [country] ([id], [name]) VALUES ('tl', 'Takalotça');
INSERT INTO [country] ([id], [name]) VALUES ('tmh', 'Tamaşek');
INSERT INTO [country] ([id], [name]) VALUES ('ta', 'Tamilce');
INSERT INTO [country] ([id], [name]) VALUES ('tt', 'Tatarca');
INSERT INTO [country] ([id], [name]) VALUES ('th', 'Tayca');
INSERT INTO [country] ([id], [name]) VALUES ('te', 'Telugu');
INSERT INTO [country] ([id], [name]) VALUES ('ter', 'Tereno');
INSERT INTO [country] ([id], [name]) VALUES ('tet', 'Tetum');
INSERT INTO [country] ([id], [name]) VALUES ('bo', 'Tibetçe');
INSERT INTO [country] ([id], [name]) VALUES ('tig', 'Tigre');
INSERT INTO [country] ([id], [name]) VALUES ('ti', 'Tigrinya');
INSERT INTO [country] ([id], [name]) VALUES ('tem', 'Timne');
INSERT INTO [country] ([id], [name]) VALUES ('tiv', 'Tiv');
INSERT INTO [country] ([id], [name]) VALUES ('tli', 'Tlingit');
INSERT INTO [country] ([id], [name]) VALUES ('tpi', 'Tok Pisin');
INSERT INTO [country] ([id], [name]) VALUES ('tkl', 'Tokelau');
INSERT INTO [country] ([id], [name]) VALUES ('to', 'Tonga');
INSERT INTO [country] ([id], [name]) VALUES ('tsi', 'Tsimshian');
INSERT INTO [country] ([id], [name]) VALUES ('ts', 'Tsonga');
INSERT INTO [country] ([id], [name]) VALUES ('tum', 'Tumbuka');
INSERT INTO [country] ([id], [name]) VALUES ('tup', 'Tupi Dilleri');
INSERT INTO [country] ([id], [name]) VALUES ('tyv', 'Tuvaca');
INSERT INTO [country] ([id], [name]) VALUES ('tvl', 'Tuvalu');
INSERT INTO [country] ([id], [name]) VALUES ('tr', 'Türkçe');
INSERT INTO [country] ([id], [name]) VALUES ('tk', 'Türkmence');
INSERT INTO [country] ([id], [name]) VALUES ('tw', 'Tvi');
INSERT INTO [country] ([id], [name]) VALUES ('kcg', 'Tyap');
INSERT INTO [country] ([id], [name]) VALUES ('udm', 'Udmurtça');
INSERT INTO [country] ([id], [name]) VALUES ('uga', 'Ugarit Dili');
INSERT INTO [country] ([id], [name]) VALUES ('uk', 'Ukraynaca');
INSERT INTO [country] ([id], [name]) VALUES ('rup', 'Ulahça');
INSERT INTO [country] ([id], [name]) VALUES ('umb', 'Umbundu');
INSERT INTO [country] ([id], [name]) VALUES ('ur', 'Urduca');
INSERT INTO [country] ([id], [name]) VALUES ('ug', 'Uygurca');
INSERT INTO [country] ([id], [name]) VALUES ('vai', 'Vai');
INSERT INTO [country] ([id], [name]) VALUES ('wak', 'Vakaşan Dilleri');
INSERT INTO [country] ([id], [name]) VALUES ('wal', 'Valamo');
INSERT INTO [country] ([id], [name]) VALUES ('wa', 'Valonca');
INSERT INTO [country] ([id], [name]) VALUES ('war', 'Varay');
INSERT INTO [country] ([id], [name]) VALUES ('was', 'Vaşo');
INSERT INTO [country] ([id], [name]) VALUES ('ve', 'Venda');
INSERT INTO [country] ([id], [name]) VALUES ('vi', 'Vietnamca');
INSERT INTO [country] ([id], [name]) VALUES ('vo', 'Volapük');
INSERT INTO [country] ([id], [name]) VALUES ('wo', 'Volofca');
INSERT INTO [country] ([id], [name]) VALUES ('vot', 'Votic');
INSERT INTO [country] ([id], [name]) VALUES ('jrb', 'Yahudi Arapçası');
INSERT INTO [country] ([id], [name]) VALUES ('jpr', 'Yahudi Farsçası');
INSERT INTO [country] ([id], [name]) VALUES ('sah', 'Yakutça');
INSERT INTO [country] ([id], [name]) VALUES ('yao', 'Yao');
INSERT INTO [country] ([id], [name]) VALUES ('art', 'Yapay Diller');
INSERT INTO [country] ([id], [name]) VALUES ('yap', 'Yapça');
INSERT INTO [country] ([id], [name]) VALUES ('yi', 'Yidiş');
INSERT INTO [country] ([id], [name]) VALUES ('yo', 'Yoruba');
INSERT INTO [country] ([id], [name]) VALUES ('hsb', 'Yukarı Sorbça');
INSERT INTO [country] ([id], [name]) VALUES ('el', 'Yunanca');
INSERT INTO [country] ([id], [name]) VALUES ('ypk', 'Yupik Dili');
INSERT INTO [country] ([id], [name]) VALUES ('znd', 'Zande');
INSERT INTO [country] ([id], [name]) VALUES ('zap', 'Zapotek Dili');
INSERT INTO [country] ([id], [name]) VALUES ('zza', 'Zazaca');
INSERT INTO [country] ([id], [name]) VALUES ('zen', 'Zenaga');
INSERT INTO [country] ([id], [name]) VALUES ('za', 'Zhuang');
INSERT INTO [country] ([id], [name]) VALUES ('xh', 'Zosa');
INSERT INTO [country] ([id], [name]) VALUES ('zu', 'Zulu');
INSERT INTO [country] ([id], [name]) VALUES ('zun', 'Zuni');
