CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('ak', 'Akangowab');
INSERT INTO [country] ([id], [name]) VALUES ('am', 'Amharicgowab');
INSERT INTO [country] ([id], [name]) VALUES ('ar', 'Arabiǁî gowab');
INSERT INTO [country] ([id], [name]) VALUES ('be', 'Belarusanǁî gowab');
INSERT INTO [country] ([id], [name]) VALUES ('bn', 'Bengaliǁî gowab');
INSERT INTO [country] ([id], [name]) VALUES ('bg', 'Bulgariaǁî gowab');
INSERT INTO [country] ([id], [name]) VALUES ('my', 'Burmesǁî gowab');
INSERT INTO [country] ([id], [name]) VALUES ('zh', 'Chineesǁî gowab, Mandarinni');
INSERT INTO [country] ([id], [name]) VALUES ('cs', 'Czechǁî gowab');
INSERT INTO [country] ([id], [name]) VALUES ('de', 'Duits');
INSERT INTO [country] ([id], [name]) VALUES ('en', 'Engels');
INSERT INTO [country] ([id], [name]) VALUES ('fr', 'Frans');
INSERT INTO [country] ([id], [name]) VALUES ('ha', 'Hausagowab');
INSERT INTO [country] ([id], [name]) VALUES ('hi', 'Hindigowab');
INSERT INTO [country] ([id], [name]) VALUES ('nl', 'Hollands');
INSERT INTO [country] ([id], [name]) VALUES ('hu', 'Hungariaǁî gowab');
INSERT INTO [country] ([id], [name]) VALUES ('ig', 'Igbogowab');
INSERT INTO [country] ([id], [name]) VALUES ('id', 'Indonesiaǁî gowab');
INSERT INTO [country] ([id], [name]) VALUES ('it', 'Italians');
INSERT INTO [country] ([id], [name]) VALUES ('ja', 'Japanees');
INSERT INTO [country] ([id], [name]) VALUES ('jv', 'Javanese');
INSERT INTO [country] ([id], [name]) VALUES ('km', 'Khmerǁî gowab, Central');
INSERT INTO [country] ([id], [name]) VALUES ('naq', 'Khoekhoegowab');
INSERT INTO [country] ([id], [name]) VALUES ('ko', 'Koreaǁî gowab');
INSERT INTO [country] ([id], [name]) VALUES ('ms', 'Malayǁî gowab');
INSERT INTO [country] ([id], [name]) VALUES ('ne', 'Nepalǁî gowab');
INSERT INTO [country] ([id], [name]) VALUES ('fa', 'Persiaǁî gowab');
INSERT INTO [country] ([id], [name]) VALUES ('pl', 'Poleǁî gowab');
INSERT INTO [country] ([id], [name]) VALUES ('pt', 'Portugees');
INSERT INTO [country] ([id], [name]) VALUES ('pa', 'Punjabigowab');
INSERT INTO [country] ([id], [name]) VALUES ('ro', 'Romaniaǁî gowab');
INSERT INTO [country] ([id], [name]) VALUES ('ru', 'Russiaǁî gowab');
INSERT INTO [country] ([id], [name]) VALUES ('rw', 'Rwandaǁî gowab');
INSERT INTO [country] ([id], [name]) VALUES ('so', 'Somaliǁî gowab');
INSERT INTO [country] ([id], [name]) VALUES ('es', 'Spaans');
INSERT INTO [country] ([id], [name]) VALUES ('sv', 'Swedeǁî gowab');
INSERT INTO [country] ([id], [name]) VALUES ('ta', 'Tamilǁî gowab');
INSERT INTO [country] ([id], [name]) VALUES ('th', 'Thaiǁî gowab');
INSERT INTO [country] ([id], [name]) VALUES ('tr', 'Turkeǁî gowab');
INSERT INTO [country] ([id], [name]) VALUES ('uk', 'Ukrainiaǁî gowab');
INSERT INTO [country] ([id], [name]) VALUES ('ur', 'Urduǁî gowab');
INSERT INTO [country] ([id], [name]) VALUES ('vi', 'Vietnamǁî gowab');
INSERT INTO [country] ([id], [name]) VALUES ('el', 'Xriks');
INSERT INTO [country] ([id], [name]) VALUES ('yo', 'Yorubab');
INSERT INTO [country] ([id], [name]) VALUES ('zu', 'Zulub');
