CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('de_AT', 'Austrijos vokiečių');
INSERT INTO [country] ([id], [name]) VALUES ('cai', 'Centrinės Amerikos indėnų kalba');
INSERT INTO [country] ([id], [name]) VALUES ('es_ES', 'Iberijos ispanų');
INSERT INTO [country] ([id], [name]) VALUES ('pt_PT', 'Iberijos portugalų');
INSERT INTO [country] ([id], [name]) VALUES ('ira', 'Iraniečių');
INSERT INTO [country] ([id], [name]) VALUES ('en_CA', 'Kanados anglų');
INSERT INTO [country] ([id], [name]) VALUES ('fr_CA', 'Kanados prancūzų');
INSERT INTO [country] ([id], [name]) VALUES ('es_419', 'Lotynų Amerikos ispanų');
INSERT INTO [country] ([id], [name]) VALUES ('mh', 'Maršalo salų');
INSERT INTO [country] ([id], [name]) VALUES ('nic', 'Nigerio kordofanų kalba');
INSERT INTO [country] ([id], [name]) VALUES ('ssa', 'Nilo Sacharos kalba');
INSERT INTO [country] ([id], [name]) VALUES ('nb', 'Norvegijos bokmal');
INSERT INTO [country] ([id], [name]) VALUES ('zxx', 'Nėra kalbinio turinio');
INSERT INTO [country] ([id], [name]) VALUES ('sai', 'Pietų Amerikos indėnų kalba');
INSERT INTO [country] ([id], [name]) VALUES ('goh', 'Senoji Aukštosios Vokietijos');
INSERT INTO [country] ([id], [name]) VALUES ('mga', 'Vidurio Airijos');
INSERT INTO [country] ([id], [name]) VALUES ('enm', 'Vidurio Anglijos');
INSERT INTO [country] ([id], [name]) VALUES ('frm', 'Vidurio Prancūzijos');
INSERT INTO [country] ([id], [name]) VALUES ('dum', 'Vidurio Vokietijos');
INSERT INTO [country] ([id], [name]) VALUES ('gmh', 'Vidurio aukštosios Vokietijos');
INSERT INTO [country] ([id], [name]) VALUES ('ab', 'abchazų');
INSERT INTO [country] ([id], [name]) VALUES ('ach', 'acoli');
INSERT INTO [country] ([id], [name]) VALUES ('ada', 'adangmų');
INSERT INTO [country] ([id], [name]) VALUES ('ady', 'adygėjų');
INSERT INTO [country] ([id], [name]) VALUES ('aa', 'afarų');
INSERT INTO [country] ([id], [name]) VALUES ('afh', 'afrihili');
INSERT INTO [country] ([id], [name]) VALUES ('af', 'afrikanų');
INSERT INTO [country] ([id], [name]) VALUES ('afa', 'afroazijos kalba');
INSERT INTO [country] ([id], [name]) VALUES ('ay', 'aimarų');
INSERT INTO [country] ([id], [name]) VALUES ('ain', 'ainų');
INSERT INTO [country] ([id], [name]) VALUES ('ga', 'airių');
INSERT INTO [country] ([id], [name]) VALUES ('akk', 'akadianų');
INSERT INTO [country] ([id], [name]) VALUES ('ak', 'akanų');
INSERT INTO [country] ([id], [name]) VALUES ('sq', 'albanų');
INSERT INTO [country] ([id], [name]) VALUES ('ale', 'aleutų');
INSERT INTO [country] ([id], [name]) VALUES ('alg', 'algonkuanų kalba');
INSERT INTO [country] ([id], [name]) VALUES ('tut', 'altaikų kalba');
INSERT INTO [country] ([id], [name]) VALUES ('am', 'amharų');
INSERT INTO [country] ([id], [name]) VALUES ('anp', 'angikų');
INSERT INTO [country] ([id], [name]) VALUES ('en', 'anglų');
INSERT INTO [country] ([id], [name]) VALUES ('en_US', 'anglų (amerikiečių)');
INSERT INTO [country] ([id], [name]) VALUES ('en_GB', 'anglų (britų)');
INSERT INTO [country] ([id], [name]) VALUES ('en_AU', 'anglų kalba (australija)');
INSERT INTO [country] ([id], [name]) VALUES ('apa', 'apačių kalba');
INSERT INTO [country] ([id], [name]) VALUES ('ar', 'arabų');
INSERT INTO [country] ([id], [name]) VALUES ('an', 'aragonesų');
INSERT INTO [country] ([id], [name]) VALUES ('arc', 'aramaikų');
INSERT INTO [country] ([id], [name]) VALUES ('arp', 'arapahų');
INSERT INTO [country] ([id], [name]) VALUES ('arn', 'araukanų');
INSERT INTO [country] ([id], [name]) VALUES ('arw', 'aravakų');
INSERT INTO [country] ([id], [name]) VALUES ('hy', 'armėnų');
INSERT INTO [country] ([id], [name]) VALUES ('rup', 'aromanių');
INSERT INTO [country] ([id], [name]) VALUES ('as', 'asamų');
INSERT INTO [country] ([id], [name]) VALUES ('ast', 'asturianų');
INSERT INTO [country] ([id], [name]) VALUES ('ath', 'athapaskanų kalba');
INSERT INTO [country] ([id], [name]) VALUES ('cch', 'atsamų');
INSERT INTO [country] ([id], [name]) VALUES ('de_CH', 'aukštoji Šveicarijos vokiečių');
INSERT INTO [country] ([id], [name]) VALUES ('aus', 'australų kalba');
INSERT INTO [country] ([id], [name]) VALUES ('map', 'austronezų');
INSERT INTO [country] ([id], [name]) VALUES ('awa', 'avadhi');
INSERT INTO [country] ([id], [name]) VALUES ('av', 'avarikų');
INSERT INTO [country] ([id], [name]) VALUES ('ae', 'avestų');
INSERT INTO [country] ([id], [name]) VALUES ('az', 'azerbaidžaniečių');
INSERT INTO [country] ([id], [name]) VALUES ('ace', 'ačinezų');
INSERT INTO [country] ([id], [name]) VALUES ('ban', 'balinezų');
INSERT INTO [country] ([id], [name]) VALUES ('be', 'baltarusių');
INSERT INTO [country] ([id], [name]) VALUES ('bat', 'baltų kalba');
INSERT INTO [country] ([id], [name]) VALUES ('bal', 'baluči');
INSERT INTO [country] ([id], [name]) VALUES ('bm', 'bambarų');
INSERT INTO [country] ([id], [name]) VALUES ('bai', 'bamilekų kalba');
INSERT INTO [country] ([id], [name]) VALUES ('bad', 'bandų');
INSERT INTO [country] ([id], [name]) VALUES ('bnt', 'bantų');
INSERT INTO [country] ([id], [name]) VALUES ('eu', 'baskų');
INSERT INTO [country] ([id], [name]) VALUES ('bas', 'basų');
INSERT INTO [country] ([id], [name]) VALUES ('btk', 'batakų');
INSERT INTO [country] ([id], [name]) VALUES ('bho', 'baučpuri');
INSERT INTO [country] ([id], [name]) VALUES ('ba', 'baškirų');
INSERT INTO [country] ([id], [name]) VALUES ('cu', 'bažnytinė slavų');
INSERT INTO [country] ([id], [name]) VALUES ('bem', 'bembų');
INSERT INTO [country] ([id], [name]) VALUES ('bn', 'bengalų');
INSERT INTO [country] ([id], [name]) VALUES ('ber', 'berberų');
INSERT INTO [country] ([id], [name]) VALUES ('day', 'bidayuh kalba');
INSERT INTO [country] ([id], [name]) VALUES ('bh', 'biharų');
INSERT INTO [country] ([id], [name]) VALUES ('bik', 'bikolų');
INSERT INTO [country] ([id], [name]) VALUES ('bin', 'bini');
INSERT INTO [country] ([id], [name]) VALUES ('my', 'birmiečių');
INSERT INTO [country] ([id], [name]) VALUES ('bi', 'bislama');
INSERT INTO [country] ([id], [name]) VALUES ('byn', 'blin');
INSERT INTO [country] ([id], [name]) VALUES ('bs', 'bosnių');
INSERT INTO [country] ([id], [name]) VALUES ('bra', 'brajų');
INSERT INTO [country] ([id], [name]) VALUES ('br', 'bretonų');
INSERT INTO [country] ([id], [name]) VALUES ('bug', 'buginezų');
INSERT INTO [country] ([id], [name]) VALUES ('bg', 'bulgarų');
INSERT INTO [country] ([id], [name]) VALUES ('bua', 'buriatų');
INSERT INTO [country] ([id], [name]) VALUES ('bej', 'bėjų');
INSERT INTO [country] ([id], [name]) VALUES ('ceb', 'cebuanų');
INSERT INTO [country] ([id], [name]) VALUES ('za', 'chuang');
INSERT INTO [country] ([id], [name]) VALUES ('dak', 'dakotų');
INSERT INTO [country] ([id], [name]) VALUES ('da', 'danų');
INSERT INTO [country] ([id], [name]) VALUES ('dar', 'dargva');
INSERT INTO [country] ([id], [name]) VALUES ('del', 'delavero');
INSERT INTO [country] ([id], [name]) VALUES ('din', 'dinkų');
INSERT INTO [country] ([id], [name]) VALUES ('art', 'dirbtinė kalba');
INSERT INTO [country] ([id], [name]) VALUES ('dv', 'divehi');
INSERT INTO [country] ([id], [name]) VALUES ('doi', 'dogri');
INSERT INTO [country] ([id], [name]) VALUES ('dgr', 'dogribų');
INSERT INTO [country] ([id], [name]) VALUES ('dra', 'dravidų kalba');
INSERT INTO [country] ([id], [name]) VALUES ('dua', 'dualų');
INSERT INTO [country] ([id], [name]) VALUES ('dyu', 'dyulų');
INSERT INTO [country] ([id], [name]) VALUES ('efi', 'efik');
INSERT INTO [country] ([id], [name]) VALUES ('eka', 'ekajuk');
INSERT INTO [country] ([id], [name]) VALUES ('elx', 'elamitų');
INSERT INTO [country] ([id], [name]) VALUES ('nqo', 'enko');
INSERT INTO [country] ([id], [name]) VALUES ('myv', 'erzyjų');
INSERT INTO [country] ([id], [name]) VALUES ('eo', 'esperanto');
INSERT INTO [country] ([id], [name]) VALUES ('et', 'estų');
INSERT INTO [country] ([id], [name]) VALUES ('ee', 'eve');
INSERT INTO [country] ([id], [name]) VALUES ('ewo', 'evondo');
INSERT INTO [country] ([id], [name]) VALUES ('fan', 'fang');
INSERT INTO [country] ([id], [name]) VALUES ('fat', 'fanti');
INSERT INTO [country] ([id], [name]) VALUES ('fo', 'farerų kalba');
INSERT INTO [country] ([id], [name]) VALUES ('fj', 'fidžio');
INSERT INTO [country] ([id], [name]) VALUES ('phi', 'filipinų kalba');
INSERT INTO [country] ([id], [name]) VALUES ('phn', 'finikiečių');
INSERT INTO [country] ([id], [name]) VALUES ('fiu', 'finougrų kalba');
INSERT INTO [country] ([id], [name]) VALUES ('nl_BE', 'flamandų');
INSERT INTO [country] ([id], [name]) VALUES ('fon', 'fon');
INSERT INTO [country] ([id], [name]) VALUES ('fur', 'frulan');
INSERT INTO [country] ([id], [name]) VALUES ('ff', 'fulahų');
INSERT INTO [country] ([id], [name]) VALUES ('gaa', 'ga');
INSERT INTO [country] ([id], [name]) VALUES ('gay', 'gajo');
INSERT INTO [country] ([id], [name]) VALUES ('gl', 'galisų');
INSERT INTO [country] ([id], [name]) VALUES ('lg', 'ganda');
INSERT INTO [country] ([id], [name]) VALUES ('gba', 'gbaja');
INSERT INTO [country] ([id], [name]) VALUES ('gem', 'germanų kalba');
INSERT INTO [country] ([id], [name]) VALUES ('gon', 'gondi');
INSERT INTO [country] ([id], [name]) VALUES ('gor', 'gorontalo');
INSERT INTO [country] ([id], [name]) VALUES ('got', 'gotų');
INSERT INTO [country] ([id], [name]) VALUES ('el', 'graikų');
INSERT INTO [country] ([id], [name]) VALUES ('grb', 'grebo');
INSERT INTO [country] ([id], [name]) VALUES ('ka', 'gruzinų');
INSERT INTO [country] ([id], [name]) VALUES ('gu', 'gudžaratų');
INSERT INTO [country] ([id], [name]) VALUES ('gn', 'gvaranių');
INSERT INTO [country] ([id], [name]) VALUES ('gwi', 'gvičino');
INSERT INTO [country] ([id], [name]) VALUES ('gez', 'gyz');
INSERT INTO [country] ([id], [name]) VALUES ('hai', 'haido');
INSERT INTO [country] ([id], [name]) VALUES ('ht', 'haičio');
INSERT INTO [country] ([id], [name]) VALUES ('ha', 'hausų');
INSERT INTO [country] ([id], [name]) VALUES ('haw', 'havajų');
INSERT INTO [country] ([id], [name]) VALUES ('he', 'hebrajų');
INSERT INTO [country] ([id], [name]) VALUES ('hz', 'herero');
INSERT INTO [country] ([id], [name]) VALUES ('hil', 'hiligainon');
INSERT INTO [country] ([id], [name]) VALUES ('him', 'himačali');
INSERT INTO [country] ([id], [name]) VALUES ('hi', 'hindi');
INSERT INTO [country] ([id], [name]) VALUES ('ho', 'hiri motu');
INSERT INTO [country] ([id], [name]) VALUES ('hit', 'hititų');
INSERT INTO [country] ([id], [name]) VALUES ('hmn', 'hmong');
INSERT INTO [country] ([id], [name]) VALUES ('hup', 'hupa');
INSERT INTO [country] ([id], [name]) VALUES ('iba', 'iban');
INSERT INTO [country] ([id], [name]) VALUES ('io', 'ido');
INSERT INTO [country] ([id], [name]) VALUES ('ig', 'igbo');
INSERT INTO [country] ([id], [name]) VALUES ('ijo', 'ijo');
INSERT INTO [country] ([id], [name]) VALUES ('ilo', 'iloko');
INSERT INTO [country] ([id], [name]) VALUES ('smn', 'inari sami');
INSERT INTO [country] ([id], [name]) VALUES ('ine', 'indoeuropiečių kalba');
INSERT INTO [country] ([id], [name]) VALUES ('id', 'indoneziečių');
INSERT INTO [country] ([id], [name]) VALUES ('inc', 'indų kalba');
INSERT INTO [country] ([id], [name]) VALUES ('inh', 'ingušų');
INSERT INTO [country] ([id], [name]) VALUES ('ie', 'interkalba');
INSERT INTO [country] ([id], [name]) VALUES ('ia', 'interlingva');
INSERT INTO [country] ([id], [name]) VALUES ('iu', 'inukitut');
INSERT INTO [country] ([id], [name]) VALUES ('ik', 'inupiak');
INSERT INTO [country] ([id], [name]) VALUES ('iro', 'irako kalba');
INSERT INTO [country] ([id], [name]) VALUES ('is', 'islandų');
INSERT INTO [country] ([id], [name]) VALUES ('es', 'ispanų');
INSERT INTO [country] ([id], [name]) VALUES ('it', 'italų');
INSERT INTO [country] ([id], [name]) VALUES ('sah', 'jakutų');
INSERT INTO [country] ([id], [name]) VALUES ('yao', 'jao');
INSERT INTO [country] ([id], [name]) VALUES ('yap', 'japezų');
INSERT INTO [country] ([id], [name]) VALUES ('ja', 'japonų');
INSERT INTO [country] ([id], [name]) VALUES ('jv', 'javiečių');
INSERT INTO [country] ([id], [name]) VALUES ('yi', 'jidiš');
INSERT INTO [country] ([id], [name]) VALUES ('yo', 'joruba');
INSERT INTO [country] ([id], [name]) VALUES ('kaj', 'ju');
INSERT INTO [country] ([id], [name]) VALUES ('jrb', 'judėjų arabų');
INSERT INTO [country] ([id], [name]) VALUES ('jpr', 'judėjų persų');
INSERT INTO [country] ([id], [name]) VALUES ('ypk', 'jupik kalba');
INSERT INTO [country] ([id], [name]) VALUES ('kbd', 'kabardinų');
INSERT INTO [country] ([id], [name]) VALUES ('kab', 'kabilo');
INSERT INTO [country] ([id], [name]) VALUES ('cad', 'kado');
INSERT INTO [country] ([id], [name]) VALUES ('kl', 'kalalisut');
INSERT INTO [country] ([id], [name]) VALUES ('xal', 'kalmukų');
INSERT INTO [country] ([id], [name]) VALUES ('kam', 'kamba');
INSERT INTO [country] ([id], [name]) VALUES ('kn', 'kanadų');
INSERT INTO [country] ([id], [name]) VALUES ('kok', 'kankani');
INSERT INTO [country] ([id], [name]) VALUES ('kr', 'kanuri');
INSERT INTO [country] ([id], [name]) VALUES ('kaa', 'karakalpakų');
INSERT INTO [country] ([id], [name]) VALUES ('krc', 'karačiajų balkarijos');
INSERT INTO [country] ([id], [name]) VALUES ('krl', 'karelų');
INSERT INTO [country] ([id], [name]) VALUES ('kar', 'karenų');
INSERT INTO [country] ([id], [name]) VALUES ('car', 'karibų');
INSERT INTO [country] ([id], [name]) VALUES ('kha', 'kasi');
INSERT INTO [country] ([id], [name]) VALUES ('ca', 'katalonų');
INSERT INTO [country] ([id], [name]) VALUES ('cau', 'kaukaziečių kalba');
INSERT INTO [country] ([id], [name]) VALUES ('kaw', 'kavi');
INSERT INTO [country] ([id], [name]) VALUES ('kk', 'kazachų');
INSERT INTO [country] ([id], [name]) VALUES ('kac', 'kačin');
INSERT INTO [country] ([id], [name]) VALUES ('ks', 'kašmyro');
INSERT INTO [country] ([id], [name]) VALUES ('csb', 'kašubų');
INSERT INTO [country] ([id], [name]) VALUES ('mul', 'kelios kalbos');
INSERT INTO [country] ([id], [name]) VALUES ('cel', 'keltų kalba');
INSERT INTO [country] ([id], [name]) VALUES ('qu', 'kečujų');
INSERT INTO [country] ([id], [name]) VALUES ('km', 'khmerų');
INSERT INTO [country] ([id], [name]) VALUES ('ki', 'kikui');
INSERT INTO [country] ([id], [name]) VALUES ('kmb', 'kimbundu');
INSERT INTO [country] ([id], [name]) VALUES ('rw', 'kinjarvanda');
INSERT INTO [country] ([id], [name]) VALUES ('zh', 'kinų');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hans', 'kinų supaprastinta');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hant', 'kinų tradicinė');
INSERT INTO [country] ([id], [name]) VALUES ('ky', 'kirgizų');
INSERT INTO [country] ([id], [name]) VALUES ('gil', 'kiribati');
INSERT INTO [country] ([id], [name]) VALUES ('nwc', 'klasikinė nevari');
INSERT INTO [country] ([id], [name]) VALUES ('syc', 'klasikinė siriečių');
INSERT INTO [country] ([id], [name]) VALUES ('khi', 'koisan kalba');
INSERT INTO [country] ([id], [name]) VALUES ('kv', 'komi');
INSERT INTO [country] ([id], [name]) VALUES ('kg', 'kongo');
INSERT INTO [country] ([id], [name]) VALUES ('cop', 'koptų');
INSERT INTO [country] ([id], [name]) VALUES ('kw', 'kornų');
INSERT INTO [country] ([id], [name]) VALUES ('kfo', 'koro');
INSERT INTO [country] ([id], [name]) VALUES ('co', 'korsikiečių');
INSERT INTO [country] ([id], [name]) VALUES ('ko', 'korėjiečių');
INSERT INTO [country] ([id], [name]) VALUES ('kos', 'kosreanų');
INSERT INTO [country] ([id], [name]) VALUES ('xh', 'kosų');
INSERT INTO [country] ([id], [name]) VALUES ('kho', 'kotanezų');
INSERT INTO [country] ([id], [name]) VALUES ('kpe', 'kpele');
INSERT INTO [country] ([id], [name]) VALUES ('crp', 'kreolų ir pidžinų');
INSERT INTO [country] ([id], [name]) VALUES ('cpe', 'kreolų ir pidžinų kalba pagal anglų');
INSERT INTO [country] ([id], [name]) VALUES ('cpp', 'kreolų ir pidžinų kalba pagal portugalų');
INSERT INTO [country] ([id], [name]) VALUES ('cpf', 'kreolų ir pidžinų kalba pagal prancūzų');
INSERT INTO [country] ([id], [name]) VALUES ('hr', 'kroatų');
INSERT INTO [country] ([id], [name]) VALUES ('kro', 'kru kalba');
INSERT INTO [country] ([id], [name]) VALUES ('cr', 'kry');
INSERT INTO [country] ([id], [name]) VALUES ('mus', 'krykų');
INSERT INTO [country] ([id], [name]) VALUES ('crh', 'krymo turkų');
INSERT INTO [country] ([id], [name]) VALUES ('kj', 'kuaniama');
INSERT INTO [country] ([id], [name]) VALUES ('kum', 'kumik');
INSERT INTO [country] ([id], [name]) VALUES ('ku', 'kurdų');
INSERT INTO [country] ([id], [name]) VALUES ('kru', 'kuruk');
INSERT INTO [country] ([id], [name]) VALUES ('kut', 'kutenai');
INSERT INTO [country] ([id], [name]) VALUES ('cus', 'kušitik kalba');
INSERT INTO [country] ([id], [name]) VALUES ('lad', 'ladino');
INSERT INTO [country] ([id], [name]) VALUES ('lam', 'lamba');
INSERT INTO [country] ([id], [name]) VALUES ('lah', 'landa');
INSERT INTO [country] ([id], [name]) VALUES ('lo', 'laosiečių');
INSERT INTO [country] ([id], [name]) VALUES ('lv', 'latvių');
INSERT INTO [country] ([id], [name]) VALUES ('pl', 'lenkų');
INSERT INTO [country] ([id], [name]) VALUES ('lez', 'lezginų');
INSERT INTO [country] ([id], [name]) VALUES ('lt', 'lietuvių');
INSERT INTO [country] ([id], [name]) VALUES ('li', 'limburgiš');
INSERT INTO [country] ([id], [name]) VALUES ('ln', 'lingala');
INSERT INTO [country] ([id], [name]) VALUES ('lb', 'liuksemburgiečių');
INSERT INTO [country] ([id], [name]) VALUES ('jbo', 'loiban');
INSERT INTO [country] ([id], [name]) VALUES ('la', 'lotynų');
INSERT INTO [country] ([id], [name]) VALUES ('loz', 'lozi');
INSERT INTO [country] ([id], [name]) VALUES ('lu', 'luba katanga');
INSERT INTO [country] ([id], [name]) VALUES ('lua', 'luba lula');
INSERT INTO [country] ([id], [name]) VALUES ('lui', 'luiseno');
INSERT INTO [country] ([id], [name]) VALUES ('smj', 'lule sami');
INSERT INTO [country] ([id], [name]) VALUES ('lun', 'lunda');
INSERT INTO [country] ([id], [name]) VALUES ('luo', 'luo');
INSERT INTO [country] ([id], [name]) VALUES ('lus', 'lušai');
INSERT INTO [country] ([id], [name]) VALUES ('mad', 'madurezų');
INSERT INTO [country] ([id], [name]) VALUES ('mag', 'magahi');
INSERT INTO [country] ([id], [name]) VALUES ('mai', 'maithili');
INSERT INTO [country] ([id], [name]) VALUES ('myn', 'majanų');
INSERT INTO [country] ([id], [name]) VALUES ('mak', 'makasaro');
INSERT INTO [country] ([id], [name]) VALUES ('mk', 'makedonų');
INSERT INTO [country] ([id], [name]) VALUES ('mg', 'malagasijos');
INSERT INTO [country] ([id], [name]) VALUES ('ml', 'malajalių');
INSERT INTO [country] ([id], [name]) VALUES ('ms', 'malajiečių');
INSERT INTO [country] ([id], [name]) VALUES ('mt', 'maltiečių');
INSERT INTO [country] ([id], [name]) VALUES ('mdr', 'mandar');
INSERT INTO [country] ([id], [name]) VALUES ('man', 'mandingo');
INSERT INTO [country] ([id], [name]) VALUES ('mni', 'manipuri');
INSERT INTO [country] ([id], [name]) VALUES ('gv', 'manks');
INSERT INTO [country] ([id], [name]) VALUES ('mno', 'manobo kalba');
INSERT INTO [country] ([id], [name]) VALUES ('mnc', 'manču');
INSERT INTO [country] ([id], [name]) VALUES ('mi', 'maorių');
INSERT INTO [country] ([id], [name]) VALUES ('mr', 'maratų');
INSERT INTO [country] ([id], [name]) VALUES ('chm', 'mari');
INSERT INTO [country] ([id], [name]) VALUES ('mwr', 'marvari');
INSERT INTO [country] ([id], [name]) VALUES ('mas', 'masajų');
INSERT INTO [country] ([id], [name]) VALUES ('men', 'mende');
INSERT INTO [country] ([id], [name]) VALUES ('mic', 'mikmak');
INSERT INTO [country] ([id], [name]) VALUES ('min', 'minankabu');
INSERT INTO [country] ([id], [name]) VALUES ('mwl', 'mirandezų');
INSERT INTO [country] ([id], [name]) VALUES ('moh', 'mohok');
INSERT INTO [country] ([id], [name]) VALUES ('mdf', 'mokša');
INSERT INTO [country] ([id], [name]) VALUES ('mo', 'moldavų');
INSERT INTO [country] ([id], [name]) VALUES ('mkh', 'mon khmer kalba');
INSERT INTO [country] ([id], [name]) VALUES ('lol', 'mongo');
INSERT INTO [country] ([id], [name]) VALUES ('mn', 'mongolų');
INSERT INTO [country] ([id], [name]) VALUES ('mos', 'mosi');
INSERT INTO [country] ([id], [name]) VALUES ('mun', 'munda kalba');
INSERT INTO [country] ([id], [name]) VALUES ('nah', 'nahuatlų');
INSERT INTO [country] ([id], [name]) VALUES ('nn', 'naujoji norvegų');
INSERT INTO [country] ([id], [name]) VALUES ('na', 'naurų');
INSERT INTO [country] ([id], [name]) VALUES ('nv', 'navajų');
INSERT INTO [country] ([id], [name]) VALUES ('ng', 'ndongų');
INSERT INTO [country] ([id], [name]) VALUES ('nap', 'neapoliečių');
INSERT INTO [country] ([id], [name]) VALUES ('und', 'nenustatyta kalba');
INSERT INTO [country] ([id], [name]) VALUES ('ne', 'nepalų');
INSERT INTO [country] ([id], [name]) VALUES ('new', 'nevari');
INSERT INTO [country] ([id], [name]) VALUES ('nym', 'niamvezi');
INSERT INTO [country] ([id], [name]) VALUES ('ny', 'nianja');
INSERT INTO [country] ([id], [name]) VALUES ('nyn', 'niankole');
INSERT INTO [country] ([id], [name]) VALUES ('nia', 'nias');
INSERT INTO [country] ([id], [name]) VALUES ('tog', 'niasa tongos');
INSERT INTO [country] ([id], [name]) VALUES ('nyo', 'nioro');
INSERT INTO [country] ([id], [name]) VALUES ('niu', 'niuenų');
INSERT INTO [country] ([id], [name]) VALUES ('nog', 'nogų');
INSERT INTO [country] ([id], [name]) VALUES ('non', 'norsu');
INSERT INTO [country] ([id], [name]) VALUES ('no', 'norvegų');
INSERT INTO [country] ([id], [name]) VALUES ('nub', 'nubijos kalba');
INSERT INTO [country] ([id], [name]) VALUES ('nzi', 'nzima');
INSERT INTO [country] ([id], [name]) VALUES ('oj', 'ojibva');
INSERT INTO [country] ([id], [name]) VALUES ('nl', 'olandų');
INSERT INTO [country] ([id], [name]) VALUES ('or', 'orijų');
INSERT INTO [country] ([id], [name]) VALUES ('om', 'oromo');
INSERT INTO [country] ([id], [name]) VALUES ('osa', 'osage');
INSERT INTO [country] ([id], [name]) VALUES ('os', 'osetinų');
INSERT INTO [country] ([id], [name]) VALUES ('ota', 'osmanų turkų');
INSERT INTO [country] ([id], [name]) VALUES ('oto', 'otomanų kalba');
INSERT INTO [country] ([id], [name]) VALUES ('pal', 'pahlavi');
INSERT INTO [country] ([id], [name]) VALUES ('pau', 'palau');
INSERT INTO [country] ([id], [name]) VALUES ('pi', 'pali');
INSERT INTO [country] ([id], [name]) VALUES ('pam', 'pampanga');
INSERT INTO [country] ([id], [name]) VALUES ('pa', 'pandžabų');
INSERT INTO [country] ([id], [name]) VALUES ('pag', 'pangasinan');
INSERT INTO [country] ([id], [name]) VALUES ('pap', 'papiemento');
INSERT INTO [country] ([id], [name]) VALUES ('paa', 'papuasų kalba');
INSERT INTO [country] ([id], [name]) VALUES ('fa', 'persų');
INSERT INTO [country] ([id], [name]) VALUES ('alt', 'pietų altajaus');
INSERT INTO [country] ([id], [name]) VALUES ('nr', 'pietų ndebele');
INSERT INTO [country] ([id], [name]) VALUES ('sma', 'pietų sami');
INSERT INTO [country] ([id], [name]) VALUES ('st', 'pietų sesuto');
INSERT INTO [country] ([id], [name]) VALUES ('pon', 'ponapean');
INSERT INTO [country] ([id], [name]) VALUES ('pt', 'portugalų');
INSERT INTO [country] ([id], [name]) VALUES ('pt_BR', 'portugalų (Brazilijos)');
INSERT INTO [country] ([id], [name]) VALUES ('pra', 'prakrit kalba');
INSERT INTO [country] ([id], [name]) VALUES ('fr', 'prancūzų');
INSERT INTO [country] ([id], [name]) VALUES ('oc', 'provansalų');
INSERT INTO [country] ([id], [name]) VALUES ('ps', 'puštūnų');
INSERT INTO [country] ([id], [name]) VALUES ('raj', 'radžastano');
INSERT INTO [country] ([id], [name]) VALUES ('rm', 'raeto romanų');
INSERT INTO [country] ([id], [name]) VALUES ('rap', 'rapanui');
INSERT INTO [country] ([id], [name]) VALUES ('rar', 'rarotongan');
INSERT INTO [country] ([id], [name]) VALUES ('roa', 'romanų kalba');
INSERT INTO [country] ([id], [name]) VALUES ('rom', 'romų kalba');
INSERT INTO [country] ([id], [name]) VALUES ('ro', 'rumunų');
INSERT INTO [country] ([id], [name]) VALUES ('rn', 'rundi');
INSERT INTO [country] ([id], [name]) VALUES ('ru', 'rusų');
INSERT INTO [country] ([id], [name]) VALUES ('frs', 'rytų fryzų');
INSERT INTO [country] ([id], [name]) VALUES ('root', 'rūt');
INSERT INTO [country] ([id], [name]) VALUES ('sal', 'sališan kalba');
INSERT INTO [country] ([id], [name]) VALUES ('sam', 'samarėjų aramių');
INSERT INTO [country] ([id], [name]) VALUES ('sem', 'samitų kalba');
INSERT INTO [country] ([id], [name]) VALUES ('smi', 'samių kalba');
INSERT INTO [country] ([id], [name]) VALUES ('sm', 'samoa');
INSERT INTO [country] ([id], [name]) VALUES ('sad', 'sandavi');
INSERT INTO [country] ([id], [name]) VALUES ('sg', 'sango');
INSERT INTO [country] ([id], [name]) VALUES ('sa', 'sanskritas');
INSERT INTO [country] ([id], [name]) VALUES ('sat', 'santali');
INSERT INTO [country] ([id], [name]) VALUES ('sc', 'sardiniečių');
INSERT INTO [country] ([id], [name]) VALUES ('sas', 'sasak');
INSERT INTO [country] ([id], [name]) VALUES ('sel', 'selkup');
INSERT INTO [country] ([id], [name]) VALUES ('sga', 'senoji airių');
INSERT INTO [country] ([id], [name]) VALUES ('ang', 'senoji anglų');
INSERT INTO [country] ([id], [name]) VALUES ('peo', 'senoji persų');
INSERT INTO [country] ([id], [name]) VALUES ('fro', 'senoji prancūzų');
INSERT INTO [country] ([id], [name]) VALUES ('egy', 'senovės egiptiečių');
INSERT INTO [country] ([id], [name]) VALUES ('grc', 'senovės graikų');
INSERT INTO [country] ([id], [name]) VALUES ('pro', 'senovės provansalų');
INSERT INTO [country] ([id], [name]) VALUES ('sr', 'serbų');
INSERT INTO [country] ([id], [name]) VALUES ('sh', 'serbų-kroatų');
INSERT INTO [country] ([id], [name]) VALUES ('srr', 'sererų');
INSERT INTO [country] ([id], [name]) VALUES ('scn', 'siciliečių');
INSERT INTO [country] ([id], [name]) VALUES ('sid', 'sidamo');
INSERT INTO [country] ([id], [name]) VALUES ('bla', 'siksika');
INSERT INTO [country] ([id], [name]) VALUES ('sd', 'sindų');
INSERT INTO [country] ([id], [name]) VALUES ('si', 'sinhalų');
INSERT INTO [country] ([id], [name]) VALUES ('sit', 'sino tibeto kalba');
INSERT INTO [country] ([id], [name]) VALUES ('sio', 'siouan kalba');
INSERT INTO [country] ([id], [name]) VALUES ('syr', 'sirų');
INSERT INTO [country] ([id], [name]) VALUES ('ii', 'sičuan ji');
INSERT INTO [country] ([id], [name]) VALUES ('sms', 'skolt sami');
INSERT INTO [country] ([id], [name]) VALUES ('den', 'slave');
INSERT INTO [country] ([id], [name]) VALUES ('sla', 'slavų kalba');
INSERT INTO [country] ([id], [name]) VALUES ('sk', 'slovakų');
INSERT INTO [country] ([id], [name]) VALUES ('sl', 'slovėnų');
INSERT INTO [country] ([id], [name]) VALUES ('sog', 'sogdien');
INSERT INTO [country] ([id], [name]) VALUES ('so', 'somalių');
INSERT INTO [country] ([id], [name]) VALUES ('son', 'songhai');
INSERT INTO [country] ([id], [name]) VALUES ('snk', 'soninke');
INSERT INTO [country] ([id], [name]) VALUES ('wen', 'sorbų kalba');
INSERT INTO [country] ([id], [name]) VALUES ('srn', 'sranan tongo');
INSERT INTO [country] ([id], [name]) VALUES ('suk', 'sukuma');
INSERT INTO [country] ([id], [name]) VALUES ('su', 'sundų');
INSERT INTO [country] ([id], [name]) VALUES ('fi', 'suomių');
INSERT INTO [country] ([id], [name]) VALUES ('sus', 'susu');
INSERT INTO [country] ([id], [name]) VALUES ('sw', 'svahili');
INSERT INTO [country] ([id], [name]) VALUES ('ss', 'svati');
INSERT INTO [country] ([id], [name]) VALUES ('dz', 'svazilando');
INSERT INTO [country] ([id], [name]) VALUES ('tg', 'tadžikų');
INSERT INTO [country] ([id], [name]) VALUES ('tl', 'tagalogų');
INSERT INTO [country] ([id], [name]) VALUES ('fil', 'tagalų');
INSERT INTO [country] ([id], [name]) VALUES ('ty', 'taitiečių');
INSERT INTO [country] ([id], [name]) VALUES ('th', 'tajų');
INSERT INTO [country] ([id], [name]) VALUES ('tai', 'tajų kalba');
INSERT INTO [country] ([id], [name]) VALUES ('tmh', 'tamašek');
INSERT INTO [country] ([id], [name]) VALUES ('ta', 'tamilų');
INSERT INTO [country] ([id], [name]) VALUES ('te', 'telugų');
INSERT INTO [country] ([id], [name]) VALUES ('ter', 'tereno');
INSERT INTO [country] ([id], [name]) VALUES ('tet', 'tetum');
INSERT INTO [country] ([id], [name]) VALUES ('bo', 'tibetiečių');
INSERT INTO [country] ([id], [name]) VALUES ('ti', 'tigrajų');
INSERT INTO [country] ([id], [name]) VALUES ('tig', 'tigre');
INSERT INTO [country] ([id], [name]) VALUES ('tem', 'timne');
INSERT INTO [country] ([id], [name]) VALUES ('tiv', 'tiv');
INSERT INTO [country] ([id], [name]) VALUES ('tli', 'tlingit');
INSERT INTO [country] ([id], [name]) VALUES ('tpi', 'tok pisin');
INSERT INTO [country] ([id], [name]) VALUES ('tkl', 'tokelau');
INSERT INTO [country] ([id], [name]) VALUES ('to', 'tonga');
INSERT INTO [country] ([id], [name]) VALUES ('tt', 'totorių');
INSERT INTO [country] ([id], [name]) VALUES ('tsi', 'tsimšian');
INSERT INTO [country] ([id], [name]) VALUES ('ts', 'tsonga');
INSERT INTO [country] ([id], [name]) VALUES ('tn', 'tsvana');
INSERT INTO [country] ([id], [name]) VALUES ('tum', 'tumbuka');
INSERT INTO [country] ([id], [name]) VALUES ('tup', 'tupi kalba');
INSERT INTO [country] ([id], [name]) VALUES ('tk', 'turkmėnų');
INSERT INTO [country] ([id], [name]) VALUES ('tr', 'turkų');
INSERT INTO [country] ([id], [name]) VALUES ('tvl', 'tuvalu');
INSERT INTO [country] ([id], [name]) VALUES ('tyv', 'tuvių');
INSERT INTO [country] ([id], [name]) VALUES ('tw', 'tvi');
INSERT INTO [country] ([id], [name]) VALUES ('kcg', 'tyap');
INSERT INTO [country] ([id], [name]) VALUES ('udm', 'udmurtų');
INSERT INTO [country] ([id], [name]) VALUES ('uga', 'ugaritic');
INSERT INTO [country] ([id], [name]) VALUES ('ug', 'uigūrų');
INSERT INTO [country] ([id], [name]) VALUES ('uk', 'ukrainiečių');
INSERT INTO [country] ([id], [name]) VALUES ('umb', 'umbundu');
INSERT INTO [country] ([id], [name]) VALUES ('ur', 'urdų');
INSERT INTO [country] ([id], [name]) VALUES ('uz', 'uzbekų');
INSERT INTO [country] ([id], [name]) VALUES ('vai', 'vai');
INSERT INTO [country] ([id], [name]) VALUES ('fy', 'vakarų fryzų');
INSERT INTO [country] ([id], [name]) VALUES ('wak', 'vakašan kalba');
INSERT INTO [country] ([id], [name]) VALUES ('wal', 'valamo');
INSERT INTO [country] ([id], [name]) VALUES ('wa', 'valonų');
INSERT INTO [country] ([id], [name]) VALUES ('cy', 'valų');
INSERT INTO [country] ([id], [name]) VALUES ('war', 'varai');
INSERT INTO [country] ([id], [name]) VALUES ('was', 'vašo');
INSERT INTO [country] ([id], [name]) VALUES ('ve', 'venda');
INSERT INTO [country] ([id], [name]) VALUES ('hu', 'vengrų');
INSERT INTO [country] ([id], [name]) VALUES ('vi', 'vietnamiečių');
INSERT INTO [country] ([id], [name]) VALUES ('hsb', 'viršutinė sorbian');
INSERT INTO [country] ([id], [name]) VALUES ('de', 'vokiečių');
INSERT INTO [country] ([id], [name]) VALUES ('vo', 'volapiuk');
INSERT INTO [country] ([id], [name]) VALUES ('wo', 'volof');
INSERT INTO [country] ([id], [name]) VALUES ('vot', 'votik');
INSERT INTO [country] ([id], [name]) VALUES ('znd', 'zande');
INSERT INTO [country] ([id], [name]) VALUES ('zap', 'zapotekų');
INSERT INTO [country] ([id], [name]) VALUES ('zza', 'zaza');
INSERT INTO [country] ([id], [name]) VALUES ('zen', 'zenaga');
INSERT INTO [country] ([id], [name]) VALUES ('zu', 'zulų');
INSERT INTO [country] ([id], [name]) VALUES ('zun', 'zuni');
INSERT INTO [country] ([id], [name]) VALUES ('chg', 'čagatų');
INSERT INTO [country] ([id], [name]) VALUES ('chy', 'čajenų');
INSERT INTO [country] ([id], [name]) VALUES ('cmc', 'čamikų kalba');
INSERT INTO [country] ([id], [name]) VALUES ('ch', 'čamorų');
INSERT INTO [country] ([id], [name]) VALUES ('cs', 'čekų');
INSERT INTO [country] ([id], [name]) VALUES ('chr', 'čerokių');
INSERT INTO [country] ([id], [name]) VALUES ('ce', 'čečėnų');
INSERT INTO [country] ([id], [name]) VALUES ('chb', 'čibča');
INSERT INTO [country] ([id], [name]) VALUES ('chn', 'činuk žargonas');
INSERT INTO [country] ([id], [name]) VALUES ('chp', 'čipvėjų');
INSERT INTO [country] ([id], [name]) VALUES ('cv', 'čiuvašų');
INSERT INTO [country] ([id], [name]) VALUES ('cho', 'čoktau');
INSERT INTO [country] ([id], [name]) VALUES ('chk', 'čukesų');
INSERT INTO [country] ([id], [name]) VALUES ('mis', 'įvairios kalbos');
INSERT INTO [country] ([id], [name]) VALUES ('nai', 'Šiaurės Amerikos indėnų kalba');
INSERT INTO [country] ([id], [name]) VALUES ('fr_CH', 'Šveicarijos prancūzų');
INSERT INTO [country] ([id], [name]) VALUES ('gsw', 'Šveicarijos vokiečių');
INSERT INTO [country] ([id], [name]) VALUES ('shn', 'šan');
INSERT INTO [country] ([id], [name]) VALUES ('frr', 'šiaurinių fryzų');
INSERT INTO [country] ([id], [name]) VALUES ('se', 'šiaurinių samių');
INSERT INTO [country] ([id], [name]) VALUES ('nd', 'šiaurės ndebelų');
INSERT INTO [country] ([id], [name]) VALUES ('nso', 'šiaurės sothų');
INSERT INTO [country] ([id], [name]) VALUES ('sco', 'škotų');
INSERT INTO [country] ([id], [name]) VALUES ('gd', 'škotų (gėlų)');
INSERT INTO [country] ([id], [name]) VALUES ('sn', 'šona');
INSERT INTO [country] ([id], [name]) VALUES ('sux', 'šumerų');
INSERT INTO [country] ([id], [name]) VALUES ('sv', 'švedų');
INSERT INTO [country] ([id], [name]) VALUES ('dsb', 'Žemutinės Serbijos');
INSERT INTO [country] ([id], [name]) VALUES ('nds', 'Žemutinės Vokietijos');
INSERT INTO [country] ([id], [name]) VALUES ('sgn', 'ženklų kalba');
INSERT INTO [country] ([id], [name]) VALUES ('zbl', '„Bliss“ simbolių kalba');
INSERT INTO [country] ([id], [name]) VALUES ('tlh', '„žvaigždžių kelionių“');
