CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('ab', 'abkhazera');
INSERT INTO "country" ("id", "name") VALUES ('af', 'afrikaans');
INSERT INTO "country" ("id", "name") VALUES ('ay', 'aimara');
INSERT INTO "country" ("id", "name") VALUES ('sq', 'albaniera');
INSERT INTO "country" ("id", "name") VALUES ('de', 'alemana');
INSERT INTO "country" ("id", "name") VALUES ('gsw', 'alemana (Suitza)');
INSERT INTO "country" ("id", "name") VALUES ('am', 'amharikera');
INSERT INTO "country" ("id", "name") VALUES ('ar', 'arabiera');
INSERT INTO "country" ("id", "name") VALUES ('hy', 'armeniera');
INSERT INTO "country" ("id", "name") VALUES ('as', 'assamera');
INSERT INTO "country" ("id", "name") VALUES ('az', 'azerbaijanera');
INSERT INTO "country" ("id", "name") VALUES ('bn', 'bengalera');
INSERT INTO "country" ("id", "name") VALUES ('be', 'bielorrusiera');
INSERT INTO "country" ("id", "name") VALUES ('bh', 'bihariera');
INSERT INTO "country" ("id", "name") VALUES ('bs', 'bosniera');
INSERT INTO "country" ("id", "name") VALUES ('br', 'bretoiera');
INSERT INTO "country" ("id", "name") VALUES ('bg', 'bulgariera');
INSERT INTO "country" ("id", "name") VALUES ('my', 'burmatarra');
INSERT INTO "country" ("id", "name") VALUES ('da', 'daniera');
INSERT INTO "country" ("id", "name") VALUES ('dv', 'divehiera');
INSERT INTO "country" ("id", "name") VALUES ('dz', 'dzongkha');
INSERT INTO "country" ("id", "name") VALUES ('efi', 'efikera');
INSERT INTO "country" ("id", "name") VALUES ('rm', 'erromantxera');
INSERT INTO "country" ("id", "name") VALUES ('ro', 'errumaniera');
INSERT INTO "country" ("id", "name") VALUES ('ru', 'errusiera');
INSERT INTO "country" ("id", "name") VALUES ('gd', 'eskoziako gaelikoa');
INSERT INTO "country" ("id", "name") VALUES ('sk', 'eslovakiera');
INSERT INTO "country" ("id", "name") VALUES ('sl', 'esloveniera');
INSERT INTO "country" ("id", "name") VALUES ('es_ES', 'espainiera iberiarra');
INSERT INTO "country" ("id", "name") VALUES ('eo', 'esperantoa');
INSERT INTO "country" ("id", "name") VALUES ('et', 'estoniera');
INSERT INTO "country" ("id", "name") VALUES ('eu', 'euskara');
INSERT INTO "country" ("id", "name") VALUES ('zxx', 'Ez dago eduki linguistikorik');
INSERT INTO "country" ("id", "name") VALUES ('fo', 'faroera');
INSERT INTO "country" ("id", "name") VALUES ('fj', 'fijiera');
INSERT INTO "country" ("id", "name") VALUES ('fi', 'finlandiera');
INSERT INTO "country" ("id", "name") VALUES ('nl_BE', 'flandriera');
INSERT INTO "country" ("id", "name") VALUES ('fr', 'frantsesa');
INSERT INTO "country" ("id", "name") VALUES ('fy', 'frisiera');
INSERT INTO "country" ("id", "name") VALUES ('ga', 'gaelikoa');
INSERT INTO "country" ("id", "name") VALUES ('cy', 'galesera');
INSERT INTO "country" ("id", "name") VALUES ('gl', 'galiziera');
INSERT INTO "country" ("id", "name") VALUES ('es', 'gaztelania');
INSERT INTO "country" ("id", "name") VALUES ('ka', 'georgiera');
INSERT INTO "country" ("id", "name") VALUES ('el', 'greziera');
INSERT INTO "country" ("id", "name") VALUES ('gn', 'guaraniera');
INSERT INTO "country" ("id", "name") VALUES ('gu', 'gujaratera');
INSERT INTO "country" ("id", "name") VALUES ('ht', 'haitiera');
INSERT INTO "country" ("id", "name") VALUES ('ha', 'hausa');
INSERT INTO "country" ("id", "name") VALUES ('haw', 'hawaiiera');
INSERT INTO "country" ("id", "name") VALUES ('he', 'hebreera');
INSERT INTO "country" ("id", "name") VALUES ('st', 'hegoaldeko sothoera');
INSERT INTO "country" ("id", "name") VALUES ('hi', 'hindia');
INSERT INTO "country" ("id", "name") VALUES ('und', 'hizkuntza ezezaguna');
INSERT INTO "country" ("id", "name") VALUES ('hu', 'hungariera');
INSERT INTO "country" ("id", "name") VALUES ('ig', 'igboera');
INSERT INTO "country" ("id", "name") VALUES ('id', 'indonesiera');
INSERT INTO "country" ("id", "name") VALUES ('en', 'ingelesa');
INSERT INTO "country" ("id", "name") VALUES ('en_US', 'ingelesa (AEB)');
INSERT INTO "country" ("id", "name") VALUES ('ia', 'interlingua');
INSERT INTO "country" ("id", "name") VALUES ('ie', 'interlingue');
INSERT INTO "country" ("id", "name") VALUES ('nd', 'iparraldeko ndebeleera');
INSERT INTO "country" ("id", "name") VALUES ('se', 'iparraldeko samiera');
INSERT INTO "country" ("id", "name") VALUES ('is', 'islandiera');
INSERT INTO "country" ("id", "name") VALUES ('it', 'italiera');
INSERT INTO "country" ("id", "name") VALUES ('ja', 'japoniera');
INSERT INTO "country" ("id", "name") VALUES ('jv', 'javera');
INSERT INTO "country" ("id", "name") VALUES ('kn', 'kannada');
INSERT INTO "country" ("id", "name") VALUES ('ks', 'kashmirera');
INSERT INTO "country" ("id", "name") VALUES ('ca', 'katalana');
INSERT INTO "country" ("id", "name") VALUES ('kk', 'kazakhera');
INSERT INTO "country" ("id", "name") VALUES ('km', 'khemerera');
INSERT INTO "country" ("id", "name") VALUES ('rw', 'kinyaruanda');
INSERT INTO "country" ("id", "name") VALUES ('ky', 'kirgizera');
INSERT INTO "country" ("id", "name") VALUES ('tlh', 'klingonera');
INSERT INTO "country" ("id", "name") VALUES ('ko', 'koreera');
INSERT INTO "country" ("id", "name") VALUES ('hr', 'kroaziera');
INSERT INTO "country" ("id", "name") VALUES ('ku', 'kurduera');
INSERT INTO "country" ("id", "name") VALUES ('lo', 'laosera');
INSERT INTO "country" ("id", "name") VALUES ('la', 'latina');
INSERT INTO "country" ("id", "name") VALUES ('es_419', 'latinoamerikako espainiera');
INSERT INTO "country" ("id", "name") VALUES ('lv', 'letoniera');
INSERT INTO "country" ("id", "name") VALUES ('ln', 'lingala');
INSERT INTO "country" ("id", "name") VALUES ('lt', 'lituaniera');
INSERT INTO "country" ("id", "name") VALUES ('lb', 'luxenburgera');
INSERT INTO "country" ("id", "name") VALUES ('ml', 'malayalamera');
INSERT INTO "country" ("id", "name") VALUES ('ms', 'malaysiera');
INSERT INTO "country" ("id", "name") VALUES ('mg', 'malgaxea');
INSERT INTO "country" ("id", "name") VALUES ('mt', 'maltera');
INSERT INTO "country" ("id", "name") VALUES ('mi', 'maoriera');
INSERT INTO "country" ("id", "name") VALUES ('mr', 'marathera');
INSERT INTO "country" ("id", "name") VALUES ('mk', 'mazedoniera');
INSERT INTO "country" ("id", "name") VALUES ('mn', 'mongoliera');
INSERT INTO "country" ("id", "name") VALUES ('nl', 'nederlandera');
INSERT INTO "country" ("id", "name") VALUES ('ne', 'nepalera');
INSERT INTO "country" ("id", "name") VALUES ('nb', 'norvegiako bokmala');
INSERT INTO "country" ("id", "name") VALUES ('no', 'norvegiera');
INSERT INTO "country" ("id", "name") VALUES ('ny', 'nyanja');
INSERT INTO "country" ("id", "name") VALUES ('nn', 'nynorsk norvegiera');
INSERT INTO "country" ("id", "name") VALUES ('oc', 'okzitaniera');
INSERT INTO "country" ("id", "name") VALUES ('or', 'oriya');
INSERT INTO "country" ("id", "name") VALUES ('os', 'osetiera');
INSERT INTO "country" ("id", "name") VALUES ('ps', 'paxtuera');
INSERT INTO "country" ("id", "name") VALUES ('nso', 'pediera');
INSERT INTO "country" ("id", "name") VALUES ('fa', 'pertsiera');
INSERT INTO "country" ("id", "name") VALUES ('pl', 'poloniera');
INSERT INTO "country" ("id", "name") VALUES ('pt', 'portugesa');
INSERT INTO "country" ("id", "name") VALUES ('pt_PT', 'portugesa (Potugal)');
INSERT INTO "country" ("id", "name") VALUES ('pa', 'punjabera');
INSERT INTO "country" ("id", "name") VALUES ('qu', 'quechuera');
INSERT INTO "country" ("id", "name") VALUES ('rn', 'rundiera');
INSERT INTO "country" ("id", "name") VALUES ('sm', 'samoera');
INSERT INTO "country" ("id", "name") VALUES ('sg', 'sangoera');
INSERT INTO "country" ("id", "name") VALUES ('sa', 'sanskritoa');
INSERT INTO "country" ("id", "name") VALUES ('sr', 'serbiera');
INSERT INTO "country" ("id", "name") VALUES ('sh', 'serbokroaziera');
INSERT INTO "country" ("id", "name") VALUES ('sn', 'shonera');
INSERT INTO "country" ("id", "name") VALUES ('sd', 'sindhia');
INSERT INTO "country" ("id", "name") VALUES ('si', 'sinhala');
INSERT INTO "country" ("id", "name") VALUES ('so', 'somaliera');
INSERT INTO "country" ("id", "name") VALUES ('sv', 'suediera');
INSERT INTO "country" ("id", "name") VALUES ('de_CH', 'suitzako aleman garaia');
INSERT INTO "country" ("id", "name") VALUES ('su', 'sundanera');
INSERT INTO "country" ("id", "name") VALUES ('sw', 'swahili');
INSERT INTO "country" ("id", "name") VALUES ('ss', 'swatiera');
INSERT INTO "country" ("id", "name") VALUES ('fil', 'tagalo');
INSERT INTO "country" ("id", "name") VALUES ('tl', 'tagalog');
INSERT INTO "country" ("id", "name") VALUES ('ty', 'tahitiera');
INSERT INTO "country" ("id", "name") VALUES ('tg', 'tajikistanera');
INSERT INTO "country" ("id", "name") VALUES ('ta', 'tamilera');
INSERT INTO "country" ("id", "name") VALUES ('tt', 'tatarera');
INSERT INTO "country" ("id", "name") VALUES ('te', 'telugua');
INSERT INTO "country" ("id", "name") VALUES ('tet', 'tetuma');
INSERT INTO "country" ("id", "name") VALUES ('th', 'thailandiera');
INSERT INTO "country" ("id", "name") VALUES ('bo', 'tibetera');
INSERT INTO "country" ("id", "name") VALUES ('ti', 'tigrinya');
INSERT INTO "country" ("id", "name") VALUES ('tpi', 'tok pisina');
INSERT INTO "country" ("id", "name") VALUES ('to', 'tonga');
INSERT INTO "country" ("id", "name") VALUES ('ts', 'tsongera');
INSERT INTO "country" ("id", "name") VALUES ('tn', 'tswanera');
INSERT INTO "country" ("id", "name") VALUES ('tr', 'turkiera');
INSERT INTO "country" ("id", "name") VALUES ('tk', 'turkmeniera');
INSERT INTO "country" ("id", "name") VALUES ('tw', 'twia');
INSERT INTO "country" ("id", "name") VALUES ('cs', 'txekiera');
INSERT INTO "country" ("id", "name") VALUES ('zh', 'txinera');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hans', 'txinera (soildua)');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hant', 'txinera (tradizionala)');
INSERT INTO "country" ("id", "name") VALUES ('ug', 'uigurrera');
INSERT INTO "country" ("id", "name") VALUES ('uk', 'ukrainera');
INSERT INTO "country" ("id", "name") VALUES ('ur', 'urdu');
INSERT INTO "country" ("id", "name") VALUES ('uz', 'uzbekera');
INSERT INTO "country" ("id", "name") VALUES ('ve', 'vendera');
INSERT INTO "country" ("id", "name") VALUES ('vi', 'vietnamera');
INSERT INTO "country" ("id", "name") VALUES ('wo', 'wolofera');
INSERT INTO "country" ("id", "name") VALUES ('xh', 'xhosa');
INSERT INTO "country" ("id", "name") VALUES ('yi', 'yiddishera');
INSERT INTO "country" ("id", "name") VALUES ('yo', 'yorubera');
INSERT INTO "country" ("id", "name") VALUES ('zu', 'zuluera');
