CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('oc', 'অক্সিটান');
INSERT INTO "country" ("id", "name") VALUES ('und', 'অজানা বা ভুল ভাষা');
INSERT INTO "country" ("id", "name") VALUES ('kaj', 'অজ্জু');
INSERT INTO "country" ("id", "name") VALUES ('ota', 'অটোমান তুর্কি');
INSERT INTO "country" ("id", "name") VALUES ('oto', 'অটোমান ভাষা');
INSERT INTO "country" ("id", "name") VALUES ('ada', 'অদাগ্মে');
INSERT INTO "country" ("id", "name") VALUES ('om', 'অরোমো');
INSERT INTO "country" ("id", "name") VALUES ('de_AT', 'অস্ট্রিয়ান জারমান');
INSERT INTO "country" ("id", "name") VALUES ('aus', 'অস্ট্রেলিয়');
INSERT INTO "country" ("id", "name") VALUES ('en_AU', 'অস্ট্রেলিয়ান ইংরাজী');
INSERT INTO "country" ("id", "name") VALUES ('map', 'অস্ট্রোনেসিয়ান');
INSERT INTO "country" ("id", "name") VALUES ('ace', 'অ্যাচাইনিজ');
INSERT INTO "country" ("id", "name") VALUES ('apa', 'অ্যাপাচি');
INSERT INTO "country" ("id", "name") VALUES ('arn', 'অ্যারোকেনিয়');
INSERT INTO "country" ("id", "name") VALUES ('ain', 'আইনু');
INSERT INTO "country" ("id", "name") VALUES ('pt_PT', 'আইবেরিয়ান পর্তুগিজ');
INSERT INTO "country" ("id", "name") VALUES ('es_ES', 'আইবেরিয়ান স্প্যানিশ');
INSERT INTO "country" ("id", "name") VALUES ('ga', 'আইরিশ');
INSERT INTO "country" ("id", "name") VALUES ('is', 'আইসল্যান্ডীয়');
INSERT INTO "country" ("id", "name") VALUES ('awa', 'আওয়াধি');
INSERT INTO "country" ("id", "name") VALUES ('ak', 'আকান');
INSERT INTO "country" ("id", "name") VALUES ('ach', 'আকোলি');
INSERT INTO "country" ("id", "name") VALUES ('akk', 'আক্কাদিয়ান');
INSERT INTO "country" ("id", "name") VALUES ('anp', 'আঙ্গিকা');
INSERT INTO "country" ("id", "name") VALUES ('az', 'আজারবাইজানীয়');
INSERT INTO "country" ("id", "name") VALUES ('cch', 'আত্সাম');
INSERT INTO "country" ("id", "name") VALUES ('ath', 'আথাপাস্কান');
INSERT INTO "country" ("id", "name") VALUES ('ady', 'আদেগে');
INSERT INTO "country" ("id", "name") VALUES ('aa', 'আফার');
INSERT INTO "country" ("id", "name") VALUES ('af', 'আফ্রিকান্স');
INSERT INTO "country" ("id", "name") VALUES ('afh', 'আফ্রিহিলি');
INSERT INTO "country" ("id", "name") VALUES ('afa', 'আফ্রো-এশিয়াটিক ভাষা');
INSERT INTO "country" ("id", "name") VALUES ('ab', 'আবখাজিয়ান');
INSERT INTO "country" ("id", "name") VALUES ('ae', 'আবেস্তীয়');
INSERT INTO "country" ("id", "name") VALUES ('av', 'আভেরিক');
INSERT INTO "country" ("id", "name") VALUES ('am', 'আমহারিক');
INSERT INTO "country" ("id", "name") VALUES ('ay', 'আয়মারা');
INSERT INTO "country" ("id", "name") VALUES ('ar', 'আরবী');
INSERT INTO "country" ("id", "name") VALUES ('rup', 'আরমেনিয়ান');
INSERT INTO "country" ("id", "name") VALUES ('arw', 'আরাওয়াক');
INSERT INTO "country" ("id", "name") VALUES ('arp', 'আরাপাহো');
INSERT INTO "country" ("id", "name") VALUES ('arc', 'আরামাইক');
INSERT INTO "country" ("id", "name") VALUES ('an', 'আর্গোনিজ');
INSERT INTO "country" ("id", "name") VALUES ('hy', 'আর্মেনিয়');
INSERT INTO "country" ("id", "name") VALUES ('alg', 'আলগোনকিউয়ান ভাষা');
INSERT INTO "country" ("id", "name") VALUES ('tut', 'আলটাইক');
INSERT INTO "country" ("id", "name") VALUES ('sq', 'আলবেনীয়');
INSERT INTO "country" ("id", "name") VALUES ('ale', 'আলেউত');
INSERT INTO "country" ("id", "name") VALUES ('as', 'আসামি');
INSERT INTO "country" ("id", "name") VALUES ('ast', 'আস্তুরিয়');
INSERT INTO "country" ("id", "name") VALUES ('uk', 'ইউক্রেনীয়');
INSERT INTO "country" ("id", "name") VALUES ('ewo', 'ইওন্ডো');
INSERT INTO "country" ("id", "name") VALUES ('ee', 'ইওয়ে');
INSERT INTO "country" ("id", "name") VALUES ('yo', 'ইওরুবা');
INSERT INTO "country" ("id", "name") VALUES ('en', 'ইংরেজি');
INSERT INTO "country" ("id", "name") VALUES ('cpe', 'ইংরেজি জাত ক্রেওল অথবা পিজিন');
INSERT INTO "country" ("id", "name") VALUES ('eka', 'ইকাজুক');
INSERT INTO "country" ("id", "name") VALUES ('ig', 'ইগ্‌বো');
INSERT INTO "country" ("id", "name") VALUES ('inh', 'ইঙ্গুশ');
INSERT INTO "country" ("id", "name") VALUES ('ijo', 'ইজো');
INSERT INTO "country" ("id", "name") VALUES ('io', 'ইডো');
INSERT INTO "country" ("id", "name") VALUES ('it', 'ইতালীয়');
INSERT INTO "country" ("id", "name") VALUES ('smn', 'ইনারি সামি');
INSERT INTO "country" ("id", "name") VALUES ('iu', 'ইনুক্টিটুট');
INSERT INTO "country" ("id", "name") VALUES ('ik', 'ইনুপিয়াক');
INSERT INTO "country" ("id", "name") VALUES ('ie', 'ইন্টারলিঙ্গ');
INSERT INTO "country" ("id", "name") VALUES ('ia', 'ইন্টারলিঙ্গুয়া');
INSERT INTO "country" ("id", "name") VALUES ('ine', 'ইন্দো-ইউরোপীয় ভাষা');
INSERT INTO "country" ("id", "name") VALUES ('id', 'ইন্দোনেশীয়');
INSERT INTO "country" ("id", "name") VALUES ('iba', 'ইবান');
INSERT INTO "country" ("id", "name") VALUES ('yao', 'ইয়াও');
INSERT INTO "country" ("id", "name") VALUES ('sah', 'ইয়াকুট');
INSERT INTO "country" ("id", "name") VALUES ('yap', 'ইয়াপেসে');
INSERT INTO "country" ("id", "name") VALUES ('ypk', 'ইয়ুপিক ভাষা');
INSERT INTO "country" ("id", "name") VALUES ('ira', 'ইরানী ভাষা');
INSERT INTO "country" ("id", "name") VALUES ('iro', 'ইরোকোইয়ান ভাষা');
INSERT INTO "country" ("id", "name") VALUES ('ilo', 'ইলোকো');
INSERT INTO "country" ("id", "name") VALUES ('ug', 'উইঘুর');
INSERT INTO "country" ("id", "name") VALUES ('wo', 'উওলোফ');
INSERT INTO "country" ("id", "name") VALUES ('uga', 'উগারিটিক');
INSERT INTO "country" ("id", "name") VALUES ('hsb', 'উচ্চ সোর্বিয়ান');
INSERT INTO "country" ("id", "name") VALUES ('uz', 'উজবেকীয়');
INSERT INTO "country" ("id", "name") VALUES ('udm', 'উডমুর্ট');
INSERT INTO "country" ("id", "name") VALUES ('or', 'উড়িয়া');
INSERT INTO "country" ("id", "name") VALUES ('sai', 'উত্তর আমেরিকান ইন্ডিয়ান ভাষা');
INSERT INTO "country" ("id", "name") VALUES ('nd', 'উত্তর এন্দেবিলি');
INSERT INTO "country" ("id", "name") VALUES ('frr', 'উত্তরাঞ্চলীয় ফ্রিসিয়ান');
INSERT INTO "country" ("id", "name") VALUES ('se', 'উত্তরাঞ্চলীয় সামি');
INSERT INTO "country" ("id", "name") VALUES ('nso', 'উত্তরাঞ্চলীয় সোথো');
INSERT INTO "country" ("id", "name") VALUES ('nai', 'উত্তৱ আমেরিকার ইন্ডিয়ান ভাষা');
INSERT INTO "country" ("id", "name") VALUES ('umb', 'উম্বুন্দু');
INSERT INTO "country" ("id", "name") VALUES ('ur', 'উর্দু');
INSERT INTO "country" ("id", "name") VALUES ('nqo', 'এন’কো');
INSERT INTO "country" ("id", "name") VALUES ('nzi', 'এন্.জিমা');
INSERT INTO "country" ("id", "name") VALUES ('ng', 'এন্দোঙ্গা');
INSERT INTO "country" ("id", "name") VALUES ('efi', 'এফিক');
INSERT INTO "country" ("id", "name") VALUES ('myv', 'এরজিয়া');
INSERT INTO "country" ("id", "name") VALUES ('elx', 'এলামাইট');
INSERT INTO "country" ("id", "name") VALUES ('et', 'এস্তোনীয়');
INSERT INTO "country" ("id", "name") VALUES ('eo', 'এস্পেরান্তো');
INSERT INTO "country" ("id", "name") VALUES ('oj', 'ওজিবওয়া');
INSERT INTO "country" ("id", "name") VALUES ('wak', 'ওয়াকাশান ভাষা');
INSERT INTO "country" ("id", "name") VALUES ('war', 'ওয়ারে');
INSERT INTO "country" ("id", "name") VALUES ('wal', 'ওয়ালামো');
INSERT INTO "country" ("id", "name") VALUES ('wa', 'ওয়ালুন');
INSERT INTO "country" ("id", "name") VALUES ('was', 'ওয়াশো');
INSERT INTO "country" ("id", "name") VALUES ('cy', 'ওয়েলশ');
INSERT INTO "country" ("id", "name") VALUES ('osa', 'ওসেজ');
INSERT INTO "country" ("id", "name") VALUES ('os', 'ওসেটিক');
INSERT INTO "country" ("id", "name") VALUES ('cau', 'ককেশীয');
INSERT INTO "country" ("id", "name") VALUES ('cop', 'কপটিক');
INSERT INTO "country" ("id", "name") VALUES ('kw', 'কর্ণিশ');
INSERT INTO "country" ("id", "name") VALUES ('co', 'কর্সিকান');
INSERT INTO "country" ("id", "name") VALUES ('kaw', 'কাউই');
INSERT INTO "country" ("id", "name") VALUES ('kac', 'কাচিন');
INSERT INTO "country" ("id", "name") VALUES ('kk', 'কাজাখ');
INSERT INTO "country" ("id", "name") VALUES ('ca', 'কাতালান');
INSERT INTO "country" ("id", "name") VALUES ('kr', 'কানুরি');
INSERT INTO "country" ("id", "name") VALUES ('kn', 'কান্নাড়ী');
INSERT INTO "country" ("id", "name") VALUES ('kab', 'কাবাইলে');
INSERT INTO "country" ("id", "name") VALUES ('kbd', 'কাবার্ডিয়ান');
INSERT INTO "country" ("id", "name") VALUES ('kam', 'কাম্বা');
INSERT INTO "country" ("id", "name") VALUES ('krc', 'কারচে-বাল্কার');
INSERT INTO "country" ("id", "name") VALUES ('kaa', 'কারা-কাল্পাক');
INSERT INTO "country" ("id", "name") VALUES ('kar', 'কারেন');
INSERT INTO "country" ("id", "name") VALUES ('krl', 'কারেলিয়ান');
INSERT INTO "country" ("id", "name") VALUES ('xal', 'কাল্মইক');
INSERT INTO "country" ("id", "name") VALUES ('csb', 'কাশুবিয়ান');
INSERT INTO "country" ("id", "name") VALUES ('ks', 'কাশ্মীরী');
INSERT INTO "country" ("id", "name") VALUES ('ki', 'কিকু্ইয়ু');
INSERT INTO "country" ("id", "name") VALUES ('rw', 'কিনয়ারোয়ান্ডা');
INSERT INTO "country" ("id", "name") VALUES ('kmb', 'কিম্বুন্দু');
INSERT INTO "country" ("id", "name") VALUES ('ky', 'কির্গিজ');
INSERT INTO "country" ("id", "name") VALUES ('kut', 'কুটেনাই');
INSERT INTO "country" ("id", "name") VALUES ('kum', 'কুমিক');
INSERT INTO "country" ("id", "name") VALUES ('kru', 'কুরুখ');
INSERT INTO "country" ("id", "name") VALUES ('ku', 'কুর্দি');
INSERT INTO "country" ("id", "name") VALUES ('cus', 'কুশিতিক ভাষা');
INSERT INTO "country" ("id", "name") VALUES ('art', 'কৃত্রিম');
INSERT INTO "country" ("id", "name") VALUES ('qu', 'কেচুয়া');
INSERT INTO "country" ("id", "name") VALUES ('cel', 'কেল্টিক');
INSERT INTO "country" ("id", "name") VALUES ('kok', 'কোঙ্কানি');
INSERT INTO "country" ("id", "name") VALUES ('kg', 'কোঙ্গো');
INSERT INTO "country" ("id", "name") VALUES ('kv', 'কোমি');
INSERT INTO "country" ("id", "name") VALUES ('kj', 'কোয়ানিয়ামা');
INSERT INTO "country" ("id", "name") VALUES ('ko', 'কোরিয়ান');
INSERT INTO "country" ("id", "name") VALUES ('kfo', 'কোরো');
INSERT INTO "country" ("id", "name") VALUES ('kos', 'কোস্রাইন');
INSERT INTO "country" ("id", "name") VALUES ('kpe', 'ক্‌পেল্লে');
INSERT INTO "country" ("id", "name") VALUES ('cad', 'ক্যাডো');
INSERT INTO "country" ("id", "name") VALUES ('en_CA', 'ক্যানাডিয়ান ইংরেজি');
INSERT INTO "country" ("id", "name") VALUES ('fr_CA', 'ক্যানাডিয়ান ফরাসী');
INSERT INTO "country" ("id", "name") VALUES ('car', 'ক্যারিব');
INSERT INTO "country" ("id", "name") VALUES ('kl', 'ক্যালাল্লিসুট');
INSERT INTO "country" ("id", "name") VALUES ('cr', 'ক্রি');
INSERT INTO "country" ("id", "name") VALUES ('mus', 'ক্রিক');
INSERT INTO "country" ("id", "name") VALUES ('crh', 'ক্রিমিয়ান তুর্কি');
INSERT INTO "country" ("id", "name") VALUES ('kro', 'ক্রু');
INSERT INTO "country" ("id", "name") VALUES ('crp', 'ক্রেওল অথবা পিজিন');
INSERT INTO "country" ("id", "name") VALUES ('hr', 'ক্রোয়েশীয়');
INSERT INTO "country" ("id", "name") VALUES ('tlh', 'ক্লিঙ্গন');
INSERT INTO "country" ("id", "name") VALUES ('km', 'খমের');
INSERT INTO "country" ("id", "name") VALUES ('kha', 'খাশি');
INSERT INTO "country" ("id", "name") VALUES ('kho', 'খোটানিজ');
INSERT INTO "country" ("id", "name") VALUES ('khi', 'খোয়েশান ভাষা');
INSERT INTO "country" ("id", "name") VALUES ('gwi', 'গওইচ্’ইন');
INSERT INTO "country" ("id", "name") VALUES ('got', 'গথিক');
INSERT INTO "country" ("id", "name") VALUES ('gaa', 'গা');
INSERT INTO "country" ("id", "name") VALUES ('gay', 'গায়ো');
INSERT INTO "country" ("id", "name") VALUES ('gil', 'গিলবার্টিজ');
INSERT INTO "country" ("id", "name") VALUES ('gez', 'গীজ');
INSERT INTO "country" ("id", "name") VALUES ('gu', 'গুজরাটি');
INSERT INTO "country" ("id", "name") VALUES ('gn', 'গুয়ারানি');
INSERT INTO "country" ("id", "name") VALUES ('gon', 'গোন্ডি');
INSERT INTO "country" ("id", "name") VALUES ('gor', 'গোরোন্তালো');
INSERT INTO "country" ("id", "name") VALUES ('lg', 'গ্যান্ডা');
INSERT INTO "country" ("id", "name") VALUES ('gl', 'গ্যালিশিয়');
INSERT INTO "country" ("id", "name") VALUES ('el', 'গ্রিক');
INSERT INTO "country" ("id", "name") VALUES ('grb', 'গ্রেবো');
INSERT INTO "country" ("id", "name") VALUES ('cho', 'চকটোও');
INSERT INTO "country" ("id", "name") VALUES ('chg', 'চাগাতাই');
INSERT INTO "country" ("id", "name") VALUES ('cmc', 'চামিক ভাষা');
INSERT INTO "country" ("id", "name") VALUES ('ch', 'চামোরো');
INSERT INTO "country" ("id", "name") VALUES ('cu', 'চার্চ স্লাভিক');
INSERT INTO "country" ("id", "name") VALUES ('chn', 'চিনুক জার্গন');
INSERT INTO "country" ("id", "name") VALUES ('chp', 'চিপেওয়াইয়ান');
INSERT INTO "country" ("id", "name") VALUES ('chb', 'চিবচা');
INSERT INTO "country" ("id", "name") VALUES ('sgn', 'চিহ্ন ভাষা');
INSERT INTO "country" ("id", "name") VALUES ('zh', 'চীনা');
INSERT INTO "country" ("id", "name") VALUES ('chk', 'চুকি');
INSERT INTO "country" ("id", "name") VALUES ('cv', 'চুবাস');
INSERT INTO "country" ("id", "name") VALUES ('cs', 'চেক');
INSERT INTO "country" ("id", "name") VALUES ('ce', 'চেচেন');
INSERT INTO "country" ("id", "name") VALUES ('ceb', 'চেবুয়ানো');
INSERT INTO "country" ("id", "name") VALUES ('chy', 'চেয়েনি');
INSERT INTO "country" ("id", "name") VALUES ('chr', 'চেরোকি');
INSERT INTO "country" ("id", "name") VALUES ('ka', 'জর্জিয়ান');
INSERT INTO "country" ("id", "name") VALUES ('zza', 'জাজা');
INSERT INTO "country" ("id", "name") VALUES ('znd', 'জান্ডে');
INSERT INTO "country" ("id", "name") VALUES ('ja', 'জাপানি');
INSERT INTO "country" ("id", "name") VALUES ('zap', 'জাপোটেক');
INSERT INTO "country" ("id", "name") VALUES ('jv', 'জাভানি');
INSERT INTO "country" ("id", "name") VALUES ('de', 'জার্মান');
INSERT INTO "country" ("id", "name") VALUES ('gem', 'জার্মানিক ভাষা');
INSERT INTO "country" ("id", "name") VALUES ('jrb', 'জুদেও আরবি');
INSERT INTO "country" ("id", "name") VALUES ('jpr', 'জুদেও ফার্সি');
INSERT INTO "country" ("id", "name") VALUES ('zun', 'জুনি');
INSERT INTO "country" ("id", "name") VALUES ('zu', 'জুলু');
INSERT INTO "country" ("id", "name") VALUES ('zen', 'জেনাগা');
INSERT INTO "country" ("id", "name") VALUES ('xh', 'জোসা');
INSERT INTO "country" ("id", "name") VALUES ('za', 'ঝু্য়াঙ');
INSERT INTO "country" ("id", "name") VALUES ('to', 'টঙ্গা');
INSERT INTO "country" ("id", "name") VALUES ('tig', 'টাইগ্রে');
INSERT INTO "country" ("id", "name") VALUES ('tem', 'টাইম্নে');
INSERT INTO "country" ("id", "name") VALUES ('kcg', 'টাইয়াপ');
INSERT INTO "country" ("id", "name") VALUES ('tiv', 'টিভ');
INSERT INTO "country" ("id", "name") VALUES ('tvl', 'টুভালু');
INSERT INTO "country" ("id", "name") VALUES ('tyv', 'টুভিনিয়ান');
INSERT INTO "country" ("id", "name") VALUES ('tpi', 'টোক পিসিন');
INSERT INTO "country" ("id", "name") VALUES ('tkl', 'টোকেলাউ');
INSERT INTO "country" ("id", "name") VALUES ('tw', 'টোয়াই');
INSERT INTO "country" ("id", "name") VALUES ('dak', 'ডাকোটা');
INSERT INTO "country" ("id", "name") VALUES ('nl', 'ডাচ');
INSERT INTO "country" ("id", "name") VALUES ('dyu', 'ডিউলা');
INSERT INTO "country" ("id", "name") VALUES ('din', 'ডিংকা');
INSERT INTO "country" ("id", "name") VALUES ('da', 'ডেনিশ');
INSERT INTO "country" ("id", "name") VALUES ('del', 'ডেলাওয়ের');
INSERT INTO "country" ("id", "name") VALUES ('doi', 'ডোগরি');
INSERT INTO "country" ("id", "name") VALUES ('tai', 'তাই ভাষা');
INSERT INTO "country" ("id", "name") VALUES ('tl', 'তাগালগ');
INSERT INTO "country" ("id", "name") VALUES ('tg', 'তাজিক');
INSERT INTO "country" ("id", "name") VALUES ('tt', 'তাতার');
INSERT INTO "country" ("id", "name") VALUES ('tmh', 'তামাশেক');
INSERT INTO "country" ("id", "name") VALUES ('ta', 'তামিল');
INSERT INTO "country" ("id", "name") VALUES ('ty', 'তাহিতিয়ান');
INSERT INTO "country" ("id", "name") VALUES ('ti', 'তিগরিনিয়া');
INSERT INTO "country" ("id", "name") VALUES ('bo', 'তিব্বতি');
INSERT INTO "country" ("id", "name") VALUES ('tup', 'তুপি ভাষা');
INSERT INTO "country" ("id", "name") VALUES ('tum', 'তুম্বুকা');
INSERT INTO "country" ("id", "name") VALUES ('tk', 'তুর্কমেনী');
INSERT INTO "country" ("id", "name") VALUES ('tr', 'তুর্কী');
INSERT INTO "country" ("id", "name") VALUES ('tet', 'তেতুম');
INSERT INTO "country" ("id", "name") VALUES ('ter', 'তেরেনো');
INSERT INTO "country" ("id", "name") VALUES ('te', 'তেলেগু');
INSERT INTO "country" ("id", "name") VALUES ('tli', 'ত্লিঙ্গিট');
INSERT INTO "country" ("id", "name") VALUES ('th', 'থাই');
INSERT INTO "country" ("id", "name") VALUES ('nr', 'দক্ষিণ এনডেবেলে');
INSERT INTO "country" ("id", "name") VALUES ('sma', 'দক্ষিণাঞ্চলীয় সামি');
INSERT INTO "country" ("id", "name") VALUES ('alt', 'দক্ষিন আলতাই');
INSERT INTO "country" ("id", "name") VALUES ('st', 'দক্ষিন সোথো');
INSERT INTO "country" ("id", "name") VALUES ('day', 'দায়াক');
INSERT INTO "country" ("id", "name") VALUES ('dar', 'দার্গওয়া');
INSERT INTO "country" ("id", "name") VALUES ('dv', 'দিবেহি');
INSERT INTO "country" ("id", "name") VALUES ('dua', 'দুয়ালা');
INSERT INTO "country" ("id", "name") VALUES ('dgr', 'দোগ্রীব');
INSERT INTO "country" ("id", "name") VALUES ('dra', 'দ্রাবীড় ভাষা');
INSERT INTO "country" ("id", "name") VALUES ('nb', 'নরওয়ে বোকমাল');
INSERT INTO "country" ("id", "name") VALUES ('no', 'নরওয়েজীয়');
INSERT INTO "country" ("id", "name") VALUES ('nn', 'নরওয়েজীয়ান নিনর্স্ক');
INSERT INTO "country" ("id", "name") VALUES ('nic', 'নাইজার-কোর্ডোফানিয়ান ভাষা');
INSERT INTO "country" ("id", "name") VALUES ('na', 'নাউরু');
INSERT INTO "country" ("id", "name") VALUES ('nv', 'নাভাজো');
INSERT INTO "country" ("id", "name") VALUES ('ny', 'নায়াঞ্জা');
INSERT INTO "country" ("id", "name") VALUES ('tog', 'নায়াসা টোঙ্গা');
INSERT INTO "country" ("id", "name") VALUES ('nah', 'নাহুৎল');
INSERT INTO "country" ("id", "name") VALUES ('niu', 'নিউয়ান');
INSERT INTO "country" ("id", "name") VALUES ('nds', 'নিম্ন জার্মানি');
INSERT INTO "country" ("id", "name") VALUES ('dsb', 'নিম্নতর সোর্বিয়ান');
INSERT INTO "country" ("id", "name") VALUES ('nia', 'নিয়াস');
INSERT INTO "country" ("id", "name") VALUES ('ssa', 'নিলো-সাহারান ভাষা');
INSERT INTO "country" ("id", "name") VALUES ('nub', 'নুবিয়ান ভাষা');
INSERT INTO "country" ("id", "name") VALUES ('new', 'নেওয়ারি');
INSERT INTO "country" ("id", "name") VALUES ('ne', 'নেপালী');
INSERT INTO "country" ("id", "name") VALUES ('nap', 'নেয়াপোলিটান');
INSERT INTO "country" ("id", "name") VALUES ('nog', 'নোগাই');
INSERT INTO "country" ("id", "name") VALUES ('nyn', 'ন্যায়াঙ্কোলে');
INSERT INTO "country" ("id", "name") VALUES ('nym', 'ন্যায়ামওয়েজি');
INSERT INTO "country" ("id", "name") VALUES ('nyo', 'ন্যোরো');
INSERT INTO "country" ("id", "name") VALUES ('pt', 'পর্তুগীজ');
INSERT INTO "country" ("id", "name") VALUES ('fy', 'পশ্চিম ফ্রিসিয়');
INSERT INTO "country" ("id", "name") VALUES ('ps', 'পশ্তু');
INSERT INTO "country" ("id", "name") VALUES ('pag', 'পাঙ্গাসিনান');
INSERT INTO "country" ("id", "name") VALUES ('pa', 'পাঞ্জাবী');
INSERT INTO "country" ("id", "name") VALUES ('pap', 'পাপিয়ামেন্টো');
INSERT INTO "country" ("id", "name") VALUES ('paa', 'পাপুয়ান ভাষা');
INSERT INTO "country" ("id", "name") VALUES ('pam', 'পাম্পাঙ্গা');
INSERT INTO "country" ("id", "name") VALUES ('pau', 'পালায়ুয়ান');
INSERT INTO "country" ("id", "name") VALUES ('pi', 'পালি');
INSERT INTO "country" ("id", "name") VALUES ('pal', 'পাহ্লাভি');
INSERT INTO "country" ("id", "name") VALUES ('frs', 'পূর্ব ফ্রিসিয়');
INSERT INTO "country" ("id", "name") VALUES ('cpp', 'পোর্তুগিজ-ভিত্তিক ক্রেওল বা পিজন');
INSERT INTO "country" ("id", "name") VALUES ('pl', 'পোলিশ');
INSERT INTO "country" ("id", "name") VALUES ('pon', 'পোহ্নপেইয়ান');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hant', 'প্রথাগত চীনা');
INSERT INTO "country" ("id", "name") VALUES ('pra', 'প্রাকৃত ভাষা');
INSERT INTO "country" ("id", "name") VALUES ('sga', 'প্রাচীন আইরিশ');
INSERT INTO "country" ("id", "name") VALUES ('ang', 'প্রাচীন ইংরেজী');
INSERT INTO "country" ("id", "name") VALUES ('goh', 'প্রাচীন উচ্চ জার্মানি');
INSERT INTO "country" ("id", "name") VALUES ('grc', 'প্রাচীন গ্রীক');
INSERT INTO "country" ("id", "name") VALUES ('non', 'প্রাচীন নর্স');
INSERT INTO "country" ("id", "name") VALUES ('nwc', 'প্রাচীন নেওয়ারী');
INSERT INTO "country" ("id", "name") VALUES ('pro', 'প্রাচীন প্রোভেনসাল');
INSERT INTO "country" ("id", "name") VALUES ('fro', 'প্রাচীন ফরাসি');
INSERT INTO "country" ("id", "name") VALUES ('peo', 'প্রাচীন ফার্সি');
INSERT INTO "country" ("id", "name") VALUES ('egy', 'প্রাচীন মিশরীয়');
INSERT INTO "country" ("id", "name") VALUES ('syc', 'প্রাচীন সিরিও');
INSERT INTO "country" ("id", "name") VALUES ('fon', 'ফন');
INSERT INTO "country" ("id", "name") VALUES ('fr', 'ফরাসি');
INSERT INTO "country" ("id", "name") VALUES ('cpf', 'ফরাসি জাত ক্রেওল অথবা পিজিন');
INSERT INTO "country" ("id", "name") VALUES ('fat', 'ফান্তি');
INSERT INTO "country" ("id", "name") VALUES ('fa', 'ফার্সি');
INSERT INTO "country" ("id", "name") VALUES ('fj', 'ফিজিও');
INSERT INTO "country" ("id", "name") VALUES ('fi', 'ফিনিশ');
INSERT INTO "country" ("id", "name") VALUES ('fiu', 'ফিনো-ইউগ্রিক');
INSERT INTO "country" ("id", "name") VALUES ('phi', 'ফিলিপাইন ভাষা');
INSERT INTO "country" ("id", "name") VALUES ('fil', 'ফিলিপিনো');
INSERT INTO "country" ("id", "name") VALUES ('ff', 'ফুলাহ্');
INSERT INTO "country" ("id", "name") VALUES ('fo', 'ফেরাউনি');
INSERT INTO "country" ("id", "name") VALUES ('phn', 'ফোনিশীয়ান');
INSERT INTO "country" ("id", "name") VALUES ('fan', 'ফ্যাঙ্গ');
INSERT INTO "country" ("id", "name") VALUES ('fur', 'ফ্রিউলিয়ান');
INSERT INTO "country" ("id", "name") VALUES ('nl_BE', 'ফ্লেমিশ');
INSERT INTO "country" ("id", "name") VALUES ('my', 'বর্মি');
INSERT INTO "country" ("id", "name") VALUES ('bs', 'বসনীয়');
INSERT INTO "country" ("id", "name") VALUES ('bn', 'বাংলা');
INSERT INTO "country" ("id", "name") VALUES ('btk', 'বাতাক');
INSERT INTO "country" ("id", "name") VALUES ('bnt', 'বান্টু');
INSERT INTO "country" ("id", "name") VALUES ('bad', 'বান্দা');
INSERT INTO "country" ("id", "name") VALUES ('bm', 'বামবারা');
INSERT INTO "country" ("id", "name") VALUES ('bai', 'বামিলেকে ভাষা');
INSERT INTO "country" ("id", "name") VALUES ('gba', 'বায়া');
INSERT INTO "country" ("id", "name") VALUES ('ban', 'বালিনীয়');
INSERT INTO "country" ("id", "name") VALUES ('bat', 'বাল্টিক ভাষা');
INSERT INTO "country" ("id", "name") VALUES ('ba', 'বাশকির');
INSERT INTO "country" ("id", "name") VALUES ('bas', 'বাসা');
INSERT INTO "country" ("id", "name") VALUES ('eu', 'বাস্ক');
INSERT INTO "country" ("id", "name") VALUES ('bik', 'বিকোল');
INSERT INTO "country" ("id", "name") VALUES ('bin', 'বিনি');
INSERT INTO "country" ("id", "name") VALUES ('mis', 'বিবিধ ভাষা');
INSERT INTO "country" ("id", "name") VALUES ('bi', 'বিসলামা');
INSERT INTO "country" ("id", "name") VALUES ('bh', 'বিহারি');
INSERT INTO "country" ("id", "name") VALUES ('bug', 'বুগিনি');
INSERT INTO "country" ("id", "name") VALUES ('bua', 'বুরিয়াত');
INSERT INTO "country" ("id", "name") VALUES ('bg', 'বুলগেরিয়');
INSERT INTO "country" ("id", "name") VALUES ('bej', 'বেজা');
INSERT INTO "country" ("id", "name") VALUES ('bem', 'বেম্বা');
INSERT INTO "country" ("id", "name") VALUES ('ber', 'বেরবের');
INSERT INTO "country" ("id", "name") VALUES ('be', 'বেলারুশিয়');
INSERT INTO "country" ("id", "name") VALUES ('bal', 'বেলুচী');
INSERT INTO "country" ("id", "name") VALUES ('bra', 'ব্রাজ');
INSERT INTO "country" ("id", "name") VALUES ('pt_BR', 'ব্রাজিলীয় পর্তুগীজ');
INSERT INTO "country" ("id", "name") VALUES ('en_GB', 'ব্রিটিশ ইংরেজী');
INSERT INTO "country" ("id", "name") VALUES ('br', 'ব্রেটোন');
INSERT INTO "country" ("id", "name") VALUES ('byn', 'ব্লিন');
INSERT INTO "country" ("id", "name") VALUES ('zbl', 'ব্লিসসিম্বলস');
INSERT INTO "country" ("id", "name") VALUES ('vai', 'ভাই');
INSERT INTO "country" ("id", "name") VALUES ('inc', 'ভারতীয় ভাষা');
INSERT INTO "country" ("id", "name") VALUES ('zxx', 'ভাষাতাত্তিক বিষয়সূচী বহির্ভুত');
INSERT INTO "country" ("id", "name") VALUES ('vi', 'ভিয়েতনামী');
INSERT INTO "country" ("id", "name") VALUES ('dz', 'ভুটানি');
INSERT INTO "country" ("id", "name") VALUES ('ve', 'ভেন্ডা');
INSERT INTO "country" ("id", "name") VALUES ('bho', 'ভোজপুরি');
INSERT INTO "country" ("id", "name") VALUES ('vot', 'ভোটিক');
INSERT INTO "country" ("id", "name") VALUES ('vo', 'ভোলাপুক');
INSERT INTO "country" ("id", "name") VALUES ('mn', 'মঙ্গোলিয়');
INSERT INTO "country" ("id", "name") VALUES ('mni', 'মণিপুরী');
INSERT INTO "country" ("id", "name") VALUES ('mga', 'মধ্য আইরিশ');
INSERT INTO "country" ("id", "name") VALUES ('enm', 'মধ্য ইংরেজি');
INSERT INTO "country" ("id", "name") VALUES ('dum', 'মধ্য ডাচ');
INSERT INTO "country" ("id", "name") VALUES ('frm', 'মধ্য ফরাসি');
INSERT INTO "country" ("id", "name") VALUES ('cai', 'মধ্য যুক্তরাষ্ঠের আদিবাসীদের ভাষা');
INSERT INTO "country" ("id", "name") VALUES ('gmh', 'মধ্য-উচ্চ জার্মানি');
INSERT INTO "country" ("id", "name") VALUES ('mkh', 'মন-খমের ভাষা');
INSERT INTO "country" ("id", "name") VALUES ('mo', 'মলদাভিয়');
INSERT INTO "country" ("id", "name") VALUES ('mt', 'মল্টিয়');
INSERT INTO "country" ("id", "name") VALUES ('mos', 'মসি');
INSERT INTO "country" ("id", "name") VALUES ('mi', 'মাওরি');
INSERT INTO "country" ("id", "name") VALUES ('mag', 'মাগাহি');
INSERT INTO "country" ("id", "name") VALUES ('mnc', 'মাঞ্চু');
INSERT INTO "country" ("id", "name") VALUES ('mad', 'মাদুরেসে');
INSERT INTO "country" ("id", "name") VALUES ('myn', 'মায়ান ভাষা');
INSERT INTO "country" ("id", "name") VALUES ('mr', 'মারাঠি');
INSERT INTO "country" ("id", "name") VALUES ('chm', 'মারি');
INSERT INTO "country" ("id", "name") VALUES ('mwr', 'মারোয়ারি');
INSERT INTO "country" ("id", "name") VALUES ('mh', 'মার্শালিজ');
INSERT INTO "country" ("id", "name") VALUES ('mg', 'মালাগাসি');
INSERT INTO "country" ("id", "name") VALUES ('ms', 'মালে');
INSERT INTO "country" ("id", "name") VALUES ('ml', 'মালেয়ালাম');
INSERT INTO "country" ("id", "name") VALUES ('mas', 'মাসাই');
INSERT INTO "country" ("id", "name") VALUES ('mic', 'মিকম্যাক');
INSERT INTO "country" ("id", "name") VALUES ('min', 'মিনাঙ্গ্‌কাবাউ');
INSERT INTO "country" ("id", "name") VALUES ('mwl', 'মিরান্ডিজ');
INSERT INTO "country" ("id", "name") VALUES ('mun', 'মুণ্ডা ভাষা');
INSERT INTO "country" ("id", "name") VALUES ('root', 'মূল');
INSERT INTO "country" ("id", "name") VALUES ('men', 'মেন্ডে');
INSERT INTO "country" ("id", "name") VALUES ('mai', 'মৈথিলি');
INSERT INTO "country" ("id", "name") VALUES ('mdf', 'মোকশা');
INSERT INTO "country" ("id", "name") VALUES ('lol', 'মোঙ্গো');
INSERT INTO "country" ("id", "name") VALUES ('moh', 'মোহাওক');
INSERT INTO "country" ("id", "name") VALUES ('mak', 'ম্যাকাসার');
INSERT INTO "country" ("id", "name") VALUES ('gv', 'ম্যাঙ্কস');
INSERT INTO "country" ("id", "name") VALUES ('mdr', 'ম্যাণ্ডার');
INSERT INTO "country" ("id", "name") VALUES ('mno', 'ম্যানোবো ভাষা');
INSERT INTO "country" ("id", "name") VALUES ('man', 'ম্যান্ডিঙ্গো');
INSERT INTO "country" ("id", "name") VALUES ('mk', 'ম্যাসেডোনীয');
INSERT INTO "country" ("id", "name") VALUES ('yi', 'য়িদ্দিশ');
INSERT INTO "country" ("id", "name") VALUES ('en_US', 'যুক্তরাষ্ট্র ইংরেজি');
INSERT INTO "country" ("id", "name") VALUES ('raj', 'রাজস্থানী');
INSERT INTO "country" ("id", "name") VALUES ('rap', 'রাপানুই');
INSERT INTO "country" ("id", "name") VALUES ('rar', 'রারোটোংগান');
INSERT INTO "country" ("id", "name") VALUES ('rn', 'রুন্দি');
INSERT INTO "country" ("id", "name") VALUES ('ru', 'রুশ');
INSERT INTO "country" ("id", "name") VALUES ('rm', 'রেটো-রোমানীয়');
INSERT INTO "country" ("id", "name") VALUES ('roa', 'রোমান ভাষা');
INSERT INTO "country" ("id", "name") VALUES ('rom', 'রোমানি');
INSERT INTO "country" ("id", "name") VALUES ('ro', 'রোমানীয়');
INSERT INTO "country" ("id", "name") VALUES ('lo', 'লাও');
INSERT INTO "country" ("id", "name") VALUES ('la', 'লাটিন');
INSERT INTO "country" ("id", "name") VALUES ('lad', 'লাডিনো');
INSERT INTO "country" ("id", "name") VALUES ('lv', 'লাত্‌ভীয়');
INSERT INTO "country" ("id", "name") VALUES ('lah', 'লান্ডা');
INSERT INTO "country" ("id", "name") VALUES ('lam', 'লাম্বা');
INSERT INTO "country" ("id", "name") VALUES ('ln', 'লিঙ্গালা');
INSERT INTO "country" ("id", "name") VALUES ('lt', 'লিথুয়েনীয');
INSERT INTO "country" ("id", "name") VALUES ('li', 'লিম্বুর্গিশ');
INSERT INTO "country" ("id", "name") VALUES ('lui', 'লুইসেনো');
INSERT INTO "country" ("id", "name") VALUES ('lb', 'লুক্সেমবার্গীয়');
INSERT INTO "country" ("id", "name") VALUES ('lun', 'লুন্ডা');
INSERT INTO "country" ("id", "name") VALUES ('lu', 'লুবা-কাটাঙ্গা');
INSERT INTO "country" ("id", "name") VALUES ('lua', 'লুবা-লুলুয়া');
INSERT INTO "country" ("id", "name") VALUES ('luo', 'লুয়ো');
INSERT INTO "country" ("id", "name") VALUES ('smj', 'লুলে সামি');
INSERT INTO "country" ("id", "name") VALUES ('lus', 'লুশাই');
INSERT INTO "country" ("id", "name") VALUES ('lez', 'লেজঘিয়ান');
INSERT INTO "country" ("id", "name") VALUES ('jbo', 'লোজবান');
INSERT INTO "country" ("id", "name") VALUES ('loz', 'লোজি');
INSERT INTO "country" ("id", "name") VALUES ('es_419', 'ল্যাটিন আমেরিকান স্প্যানিশ');
INSERT INTO "country" ("id", "name") VALUES ('shn', 'শান');
INSERT INTO "country" ("id", "name") VALUES ('sal', 'শালিশান ভাষা');
INSERT INTO "country" ("id", "name") VALUES ('sn', 'শোনা');
INSERT INTO "country" ("id", "name") VALUES ('sa', 'সংষ্কৃত');
INSERT INTO "country" ("id", "name") VALUES ('ts', 'সঙ্গা');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hans', 'সহজ চীনা');
INSERT INTO "country" ("id", "name") VALUES ('sat', 'সাঁওতালি');
INSERT INTO "country" ("id", "name") VALUES ('sg', 'সাঙ্গো');
INSERT INTO "country" ("id", "name") VALUES ('sam', 'সামারিটান আরামিক');
INSERT INTO "country" ("id", "name") VALUES ('smi', 'সামি ভাষা');
INSERT INTO "country" ("id", "name") VALUES ('sm', 'সামোয়ান');
INSERT INTO "country" ("id", "name") VALUES ('sc', 'সার্ডিনিয়ান');
INSERT INTO "country" ("id", "name") VALUES ('sr', 'সার্বীয়');
INSERT INTO "country" ("id", "name") VALUES ('sh', 'সার্বো-ক্রোয়েশিয়');
INSERT INTO "country" ("id", "name") VALUES ('sas', 'সাসাক');
INSERT INTO "country" ("id", "name") VALUES ('sio', 'সিওয়ুয়ান ভাষা');
INSERT INTO "country" ("id", "name") VALUES ('si', 'সিংহলী');
INSERT INTO "country" ("id", "name") VALUES ('bla', 'সিকসিকা');
INSERT INTO "country" ("id", "name") VALUES ('ii', 'সিচুয়ান য়ি');
INSERT INTO "country" ("id", "name") VALUES ('sid', 'সিডামো');
INSERT INTO "country" ("id", "name") VALUES ('sit', 'সিনো-তিব্বোতীয় ভাষা');
INSERT INTO "country" ("id", "name") VALUES ('sd', 'সিন্ধি');
INSERT INTO "country" ("id", "name") VALUES ('tsi', 'সিমশিয়ান');
INSERT INTO "country" ("id", "name") VALUES ('syr', 'সিরিয়াক');
INSERT INTO "country" ("id", "name") VALUES ('scn', 'সিসিলিয়ান');
INSERT INTO "country" ("id", "name") VALUES ('sv', 'সুইডিশ');
INSERT INTO "country" ("id", "name") VALUES ('de_CH', 'সুইস উচ্চ জার্মানি');
INSERT INTO "country" ("id", "name") VALUES ('gsw', 'সুইস জার্মান');
INSERT INTO "country" ("id", "name") VALUES ('fr_CH', 'সুইস ফরাসি');
INSERT INTO "country" ("id", "name") VALUES ('suk', 'সুকুমা');
INSERT INTO "country" ("id", "name") VALUES ('su', 'সুদানী');
INSERT INTO "country" ("id", "name") VALUES ('sux', 'সুমেরীয়');
INSERT INTO "country" ("id", "name") VALUES ('sus', 'সুসু');
INSERT INTO "country" ("id", "name") VALUES ('sem', 'সেমেটিক ভাষা');
INSERT INTO "country" ("id", "name") VALUES ('srr', 'সেরের');
INSERT INTO "country" ("id", "name") VALUES ('sel', 'সেল্কুপ');
INSERT INTO "country" ("id", "name") VALUES ('sog', 'সোগডিয়ান');
INSERT INTO "country" ("id", "name") VALUES ('son', 'সোঙ্গহাই');
INSERT INTO "country" ("id", "name") VALUES ('snk', 'সোনিঙ্কে');
INSERT INTO "country" ("id", "name") VALUES ('so', 'সোমালী');
INSERT INTO "country" ("id", "name") VALUES ('ss', 'সোয়াতি');
INSERT INTO "country" ("id", "name") VALUES ('tn', 'সোয়ানা');
INSERT INTO "country" ("id", "name") VALUES ('sw', 'সোয়াহিলি');
INSERT INTO "country" ("id", "name") VALUES ('wen', 'সোরবিয়ান ভাষা');
INSERT INTO "country" ("id", "name") VALUES ('sco', 'স্কটস');
INSERT INTO "country" ("id", "name") VALUES ('gd', 'স্কটস-গ্যেলিক');
INSERT INTO "country" ("id", "name") VALUES ('sms', 'স্কোল্ট সামি');
INSERT INTO "country" ("id", "name") VALUES ('es', 'স্পেনীয়');
INSERT INTO "country" ("id", "name") VALUES ('sad', 'স্যান্ডাওয়ে');
INSERT INTO "country" ("id", "name") VALUES ('srn', 'স্রানান টোঙ্গো');
INSERT INTO "country" ("id", "name") VALUES ('sk', 'স্লোভাক');
INSERT INTO "country" ("id", "name") VALUES ('sl', 'স্লোভেনীয়');
INSERT INTO "country" ("id", "name") VALUES ('den', 'স্ল্যাভ');
INSERT INTO "country" ("id", "name") VALUES ('sla', 'স্ল্যাভিক ভাষা');
INSERT INTO "country" ("id", "name") VALUES ('hai', 'হাইডা');
INSERT INTO "country" ("id", "name") VALUES ('ht', 'হাইতিয়ান');
INSERT INTO "country" ("id", "name") VALUES ('ha', 'হাউসা');
INSERT INTO "country" ("id", "name") VALUES ('haw', 'হাওয়াইয়ান');
INSERT INTO "country" ("id", "name") VALUES ('hu', 'হাঙ্গেরীয়');
INSERT INTO "country" ("id", "name") VALUES ('hit', 'হিট্টিট');
INSERT INTO "country" ("id", "name") VALUES ('hi', 'হিন্দি');
INSERT INTO "country" ("id", "name") VALUES ('he', 'হিব্রু');
INSERT INTO "country" ("id", "name") VALUES ('him', 'হিমাচালি');
INSERT INTO "country" ("id", "name") VALUES ('ho', 'হিরি মোতু');
INSERT INTO "country" ("id", "name") VALUES ('hil', 'হিলিগ্যায়নোন');
INSERT INTO "country" ("id", "name") VALUES ('hup', 'হুপা');
INSERT INTO "country" ("id", "name") VALUES ('hz', 'হেরেরো');
INSERT INTO "country" ("id", "name") VALUES ('hmn', 'হ্‌মোঙ');
