CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('ab', 'Abcáisis');
INSERT INTO `country` (`id`, `name`) VALUES ('af', 'Afracáinis');
INSERT INTO `country` (`id`, `name`) VALUES ('hy', 'Airméinis');
INSERT INTO `country` (`id`, `name`) VALUES ('ae', 'Aivéistis');
INSERT INTO `country` (`id`, `name`) VALUES ('sq', 'Albáinis');
INSERT INTO `country` (`id`, `name`) VALUES ('am', 'Amarais');
INSERT INTO `country` (`id`, `name`) VALUES ('ar', 'Araibis');
INSERT INTO `country` (`id`, `name`) VALUES ('as', 'Asaimis');
INSERT INTO `country` (`id`, `name`) VALUES ('az', 'Asarbaiseáinis');
INSERT INTO `country` (`id`, `name`) VALUES ('ba', 'Baiscíris');
INSERT INTO `country` (`id`, `name`) VALUES ('eu', 'Bascais');
INSERT INTO `country` (`id`, `name`) VALUES ('be', 'Bealarúisis');
INSERT INTO `country` (`id`, `name`) VALUES ('bn', 'Beangáilis');
INSERT INTO `country` (`id`, `name`) VALUES ('bh', 'Bihairis');
INSERT INTO `country` (`id`, `name`) VALUES ('bs', 'Boisnis');
INSERT INTO `country` (`id`, `name`) VALUES ('cy', 'Breatnais');
INSERT INTO `country` (`id`, `name`) VALUES ('br', 'Briotáinis');
INSERT INTO `country` (`id`, `name`) VALUES ('bg', 'Bulgáiris');
INSERT INTO `country` (`id`, `name`) VALUES ('my', 'Burmais');
INSERT INTO `country` (`id`, `name`) VALUES ('en', 'Béarla');
INSERT INTO `country` (`id`, `name`) VALUES ('ks', 'Caismíris');
INSERT INTO `country` (`id`, `name`) VALUES ('km', 'Cambóidis');
INSERT INTO `country` (`id`, `name`) VALUES ('kn', 'Cannadais');
INSERT INTO `country` (`id`, `name`) VALUES ('kk', 'Casachais');
INSERT INTO `country` (`id`, `name`) VALUES ('ca', 'Catalóinis');
INSERT INTO `country` (`id`, `name`) VALUES ('qu', 'Ceatsuais');
INSERT INTO `country` (`id`, `name`) VALUES ('ky', 'Cirgeasais');
INSERT INTO `country` (`id`, `name`) VALUES ('ku', 'Coirdis');
INSERT INTO `country` (`id`, `name`) VALUES ('kw', 'Cornais');
INSERT INTO `country` (`id`, `name`) VALUES ('co', 'Corsaicis');
INSERT INTO `country` (`id`, `name`) VALUES ('cr', 'Craíais');
INSERT INTO `country` (`id`, `name`) VALUES ('hr', 'Cróitis');
INSERT INTO `country` (`id`, `name`) VALUES ('ko', 'Cóiréis');
INSERT INTO `country` (`id`, `name`) VALUES ('xh', 'Cósais');
INSERT INTO `country` (`id`, `name`) VALUES ('da', 'Danmhairgis');
INSERT INTO `country` (`id`, `name`) VALUES ('he', 'Eabhrais');
INSERT INTO `country` (`id`, `name`) VALUES ('et', 'Eastóinis');
INSERT INTO `country` (`id`, `name`) VALUES ('eo', 'Esperanto');
INSERT INTO `country` (`id`, `name`) VALUES ('fo', 'Faróis');
INSERT INTO `country` (`id`, `name`) VALUES ('fj', 'Fidsis');
INSERT INTO `country` (`id`, `name`) VALUES ('fi', 'Fionlainnis');
INSERT INTO `country` (`id`, `name`) VALUES ('fr', 'Fraincis');
INSERT INTO `country` (`id`, `name`) VALUES ('fy', 'Freaslainnis Iartharach');
INSERT INTO `country` (`id`, `name`) VALUES ('ga', 'Gaeilge');
INSERT INTO `country` (`id`, `name`) VALUES ('gd', 'Gaeilge na hAlban');
INSERT INTO `country` (`id`, `name`) VALUES ('gl', 'Gailísis');
INSERT INTO `country` (`id`, `name`) VALUES ('de', 'Gearmáinis');
INSERT INTO `country` (`id`, `name`) VALUES ('yi', 'Giúdais');
INSERT INTO `country` (`id`, `name`) VALUES ('el', 'Gréigis');
INSERT INTO `country` (`id`, `name`) VALUES ('gn', 'Guaráinis');
INSERT INTO `country` (`id`, `name`) VALUES ('gu', 'Gúisearáitis');
INSERT INTO `country` (`id`, `name`) VALUES ('haw', 'Haváíais');
INSERT INTO `country` (`id`, `name`) VALUES ('hi', 'Hiondúis');
INSERT INTO `country` (`id`, `name`) VALUES ('io', 'Ido');
INSERT INTO `country` (`id`, `name`) VALUES ('id', 'Indinéisis');
INSERT INTO `country` (`id`, `name`) VALUES ('ia', 'Interlingua');
INSERT INTO `country` (`id`, `name`) VALUES ('ie', 'Interlingue');
INSERT INTO `country` (`id`, `name`) VALUES ('ik', 'Inupiaq');
INSERT INTO `country` (`id`, `name`) VALUES ('it', 'Iodáilis');
INSERT INTO `country` (`id`, `name`) VALUES ('iu', 'Ionúitis');
INSERT INTO `country` (`id`, `name`) VALUES ('no', 'Ioruais');
INSERT INTO `country` (`id`, `name`) VALUES ('nb', 'Ioruais Bokmål');
INSERT INTO `country` (`id`, `name`) VALUES ('nn', 'Ioruais Nynorsk');
INSERT INTO `country` (`id`, `name`) VALUES ('jv', 'Iávais');
INSERT INTO `country` (`id`, `name`) VALUES ('tlh', 'Klingon');
INSERT INTO `country` (`id`, `name`) VALUES ('la', 'Laidin');
INSERT INTO `country` (`id`, `name`) VALUES ('lv', 'Laitvis');
INSERT INTO `country` (`id`, `name`) VALUES ('lo', 'Laosais');
INSERT INTO `country` (`id`, `name`) VALUES ('lb', 'Leitseabuirgis');
INSERT INTO `country` (`id`, `name`) VALUES ('lt', 'Liotuáinis');
INSERT INTO `country` (`id`, `name`) VALUES ('mk', 'Macadóinis');
INSERT INTO `country` (`id`, `name`) VALUES ('ml', 'Mailéalaimis');
INSERT INTO `country` (`id`, `name`) VALUES ('ms', 'Malaeis');
INSERT INTO `country` (`id`, `name`) VALUES ('mg', 'Malagásais');
INSERT INTO `country` (`id`, `name`) VALUES ('mt', 'Maltais');
INSERT INTO `country` (`id`, `name`) VALUES ('gv', 'Mannainis');
INSERT INTO `country` (`id`, `name`) VALUES ('mi', 'Maorais');
INSERT INTO `country` (`id`, `name`) VALUES ('mr', 'Maraitis');
INSERT INTO `country` (`id`, `name`) VALUES ('mo', 'Moldáivis');
INSERT INTO `country` (`id`, `name`) VALUES ('mn', 'Mongóilis');
INSERT INTO `country` (`id`, `name`) VALUES ('nv', 'Navachóis');
INSERT INTO `country` (`id`, `name`) VALUES ('ne', 'Neipealais');
INSERT INTO `country` (`id`, `name`) VALUES ('na', 'Nárúis');
INSERT INTO `country` (`id`, `name`) VALUES ('oc', 'Ocatáinis');
INSERT INTO `country` (`id`, `name`) VALUES ('nl', 'Ollainnis');
INSERT INTO `country` (`id`, `name`) VALUES ('or', 'Oraisis');
INSERT INTO `country` (`id`, `name`) VALUES ('ps', 'Paistis');
INSERT INTO `country` (`id`, `name`) VALUES ('fa', 'Peirsis');
INSERT INTO `country` (`id`, `name`) VALUES ('pl', 'Polainnis');
INSERT INTO `country` (`id`, `name`) VALUES ('pt', 'Portaingéilis');
INSERT INTO `country` (`id`, `name`) VALUES ('pt_BR', 'Portaingéilis Bhrasaíleach');
INSERT INTO `country` (`id`, `name`) VALUES ('pt_PT', 'Portaingéilis Ibéireach');
INSERT INTO `country` (`id`, `name`) VALUES ('pa', 'Puinseáibis');
INSERT INTO `country` (`id`, `name`) VALUES ('ro', 'Rómáinis');
INSERT INTO `country` (`id`, `name`) VALUES ('ru', 'Rúisis');
INSERT INTO `country` (`id`, `name`) VALUES ('sc', 'Sairdínis');
INSERT INTO `country` (`id`, `name`) VALUES ('sm', 'Samóis');
INSERT INTO `country` (`id`, `name`) VALUES ('sa', 'Sanscrait');
INSERT INTO `country` (`id`, `name`) VALUES ('ja', 'Seapáinis');
INSERT INTO `country` (`id`, `name`) VALUES ('cs', 'Seicis');
INSERT INTO `country` (`id`, `name`) VALUES ('sh', 'Seirbea-Chróitis');
INSERT INTO `country` (`id`, `name`) VALUES ('sr', 'Seirbis');
INSERT INTO `country` (`id`, `name`) VALUES ('ka', 'Seoirsis');
INSERT INTO `country` (`id`, `name`) VALUES ('sd', 'Sindis');
INSERT INTO `country` (`id`, `name`) VALUES ('si', 'Siolóinis');
INSERT INTO `country` (`id`, `name`) VALUES ('ce', 'Sisinis');
INSERT INTO `country` (`id`, `name`) VALUES ('cu', 'Slavais na hEaglaise');
INSERT INTO `country` (`id`, `name`) VALUES ('sl', 'Slóivéinis');
INSERT INTO `country` (`id`, `name`) VALUES ('sk', 'Slóvaicis');
INSERT INTO `country` (`id`, `name`) VALUES ('so', 'Somáilis');
INSERT INTO `country` (`id`, `name`) VALUES ('es', 'Spáinnis');
INSERT INTO `country` (`id`, `name`) VALUES ('sv', 'Sualainnis');
INSERT INTO `country` (`id`, `name`) VALUES ('su', 'Sundais');
INSERT INTO `country` (`id`, `name`) VALUES ('cv', 'Suvaisis');
INSERT INTO `country` (`id`, `name`) VALUES ('sw', 'Svahaílis');
INSERT INTO `country` (`id`, `name`) VALUES ('se', 'Sáimis Thuaidh');
INSERT INTO `country` (`id`, `name`) VALUES ('zh', 'Sínis');
INSERT INTO `country` (`id`, `name`) VALUES ('zh_Hans', 'Sínis Shimplithe');
INSERT INTO `country` (`id`, `name`) VALUES ('zh_Hant', 'Sínis Thraidisiúnta');
INSERT INTO `country` (`id`, `name`) VALUES ('st', 'Sótais Dheisceartach');
INSERT INTO `country` (`id`, `name`) VALUES ('zu', 'Súlúis');
INSERT INTO `country` (`id`, `name`) VALUES ('tl', 'Tagálaigis');
INSERT INTO `country` (`id`, `name`) VALUES ('ty', 'Taihítis');
INSERT INTO `country` (`id`, `name`) VALUES ('ta', 'Tamailis');
INSERT INTO `country` (`id`, `name`) VALUES ('tt', 'Tatarais');
INSERT INTO `country` (`id`, `name`) VALUES ('und', 'Teanga Anaithnid nó Neamhbhailí');
INSERT INTO `country` (`id`, `name`) VALUES ('te', 'Teileagúis');
INSERT INTO `country` (`id`, `name`) VALUES ('bo', 'Tibéadais');
INSERT INTO `country` (`id`, `name`) VALUES ('ti', 'Tigrinis');
INSERT INTO `country` (`id`, `name`) VALUES ('tr', 'Tuircis');
INSERT INTO `country` (`id`, `name`) VALUES ('tk', 'Tuircméinis');
INSERT INTO `country` (`id`, `name`) VALUES ('tw', 'Tvís');
INSERT INTO `country` (`id`, `name`) VALUES ('th', 'Téalainnis');
INSERT INTO `country` (`id`, `name`) VALUES ('hu', 'Ungáiris');
INSERT INTO `country` (`id`, `name`) VALUES ('ur', 'Urdais');
INSERT INTO `country` (`id`, `name`) VALUES ('wa', 'Vallúnais');
INSERT INTO `country` (`id`, `name`) VALUES ('vi', 'Vítneamais');
INSERT INTO `country` (`id`, `name`) VALUES ('aa', 'aa');
INSERT INTO `country` (`id`, `name`) VALUES ('fil', 'fil');
INSERT INTO `country` (`id`, `name`) VALUES ('ln', 'ln');
INSERT INTO `country` (`id`, `name`) VALUES ('ug', 'ug');
INSERT INTO `country` (`id`, `name`) VALUES ('is', 'Íoslainnis');
INSERT INTO `country` (`id`, `name`) VALUES ('os', 'Óiséitis');
INSERT INTO `country` (`id`, `name`) VALUES ('uk', 'Úcráinis');
INSERT INTO `country` (`id`, `name`) VALUES ('uz', 'Úisbéicis');
