CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('zxx', 'Akukho okuqukethwe kolimi');
INSERT INTO "country" ("id", "name") VALUES ('se', 'e-Northern Sami');
INSERT INTO "country" ("id", "name") VALUES ('en_GB', 'i-British English');
INSERT INTO "country" ("id", "name") VALUES ('en_CA', 'i-Canadian English');
INSERT INTO "country" ("id", "name") VALUES ('fr_CA', 'i-Canadian French');
INSERT INTO "country" ("id", "name") VALUES ('nl', 'i-Dutch');
INSERT INTO "country" ("id", "name") VALUES ('lo', 'i-Lao');
INSERT INTO "country" ("id", "name") VALUES ('nb', 'i-Norwegian Bokmål');
INSERT INTO "country" ("id", "name") VALUES ('nn', 'i-Norwegian Nynorsk');
INSERT INTO "country" ("id", "name") VALUES ('gd', 'i-Scottish Gaelic');
INSERT INTO "country" ("id", "name") VALUES ('si', 'i-Sinhala');
INSERT INTO "country" ("id", "name") VALUES ('en_US', 'i-U.S. English');
INSERT INTO "country" ("id", "name") VALUES ('ab', 'isi-Abkhazian');
INSERT INTO "country" ("id", "name") VALUES ('ar', 'isi-Alabhu');
INSERT INTO "country" ("id", "name") VALUES ('sq', 'isi-Albania');
INSERT INTO "country" ("id", "name") VALUES ('am', 'isi-Amharic');
INSERT INTO "country" ("id", "name") VALUES ('hy', 'isi-Armenia');
INSERT INTO "country" ("id", "name") VALUES ('as', 'isi-Assamese');
INSERT INTO "country" ("id", "name") VALUES ('de_AT', 'isi-Austrian German');
INSERT INTO "country" ("id", "name") VALUES ('en_AU', 'isi-Austrillian English');
INSERT INTO "country" ("id", "name") VALUES ('ay', 'isi-Aymara');
INSERT INTO "country" ("id", "name") VALUES ('az', 'isi-Azerbaijani');
INSERT INTO "country" ("id", "name") VALUES ('eu', 'isi-Basque');
INSERT INTO "country" ("id", "name") VALUES ('be', 'isi-Belarusian');
INSERT INTO "country" ("id", "name") VALUES ('bn', 'isi-Bengali');
INSERT INTO "country" ("id", "name") VALUES ('bs', 'isi-Bosnian');
INSERT INTO "country" ("id", "name") VALUES ('pt_BR', 'isi-Brazillian Portuguese');
INSERT INTO "country" ("id", "name") VALUES ('bg', 'isi-Bulgari');
INSERT INTO "country" ("id", "name") VALUES ('my', 'isi-Burmese');
INSERT INTO "country" ("id", "name") VALUES ('ca', 'isi-Catalan');
INSERT INTO "country" ("id", "name") VALUES ('zh', 'isi-Chinese');
INSERT INTO "country" ("id", "name") VALUES ('hr', 'isi-Croatian');
INSERT INTO "country" ("id", "name") VALUES ('cs', 'isi-Czech');
INSERT INTO "country" ("id", "name") VALUES ('da', 'isi-Danish');
INSERT INTO "country" ("id", "name") VALUES ('dv', 'isi-Divehi');
INSERT INTO "country" ("id", "name") VALUES ('dz', 'isi-Dzongkha');
INSERT INTO "country" ("id", "name") VALUES ('efi', 'isi-Efik');
INSERT INTO "country" ("id", "name") VALUES ('eo', 'isi-Esperanto');
INSERT INTO "country" ("id", "name") VALUES ('et', 'isi-Estonia');
INSERT INTO "country" ("id", "name") VALUES ('fo', 'isi-Faroese');
INSERT INTO "country" ("id", "name") VALUES ('fj', 'isi-Fijian');
INSERT INTO "country" ("id", "name") VALUES ('fil', 'isi-Filipino');
INSERT INTO "country" ("id", "name") VALUES ('fi', 'isi-Finnish');
INSERT INTO "country" ("id", "name") VALUES ('nl_BE', 'isi-Flemish');
INSERT INTO "country" ("id", "name") VALUES ('gl', 'isi-Galicia');
INSERT INTO "country" ("id", "name") VALUES ('ka', 'isi-Georgian');
INSERT INTO "country" ("id", "name") VALUES ('el', 'isi-Greek');
INSERT INTO "country" ("id", "name") VALUES ('gn', 'isi-Guarani');
INSERT INTO "country" ("id", "name") VALUES ('gu', 'isi-Gujarati');
INSERT INTO "country" ("id", "name") VALUES ('ht', 'isi-Haitian');
INSERT INTO "country" ("id", "name") VALUES ('ha', 'isi-Hausa');
INSERT INTO "country" ("id", "name") VALUES ('haw', 'isi-Hawaiian');
INSERT INTO "country" ("id", "name") VALUES ('he', 'isi-Hebrew');
INSERT INTO "country" ("id", "name") VALUES ('hu', 'isi-Hungarian');
INSERT INTO "country" ("id", "name") VALUES ('pt_PT', 'isi-Iberian Portuguese');
INSERT INTO "country" ("id", "name") VALUES ('es_ES', 'isi-Iberian Spanish');
INSERT INTO "country" ("id", "name") VALUES ('is', 'isi-Icelandic');
INSERT INTO "country" ("id", "name") VALUES ('ig', 'isi-Igbo');
INSERT INTO "country" ("id", "name") VALUES ('id', 'isi-Indonesian');
INSERT INTO "country" ("id", "name") VALUES ('ga', 'isi-Irish');
INSERT INTO "country" ("id", "name") VALUES ('it', 'isi-Italian');
INSERT INTO "country" ("id", "name") VALUES ('ja', 'isi-Japanese');
INSERT INTO "country" ("id", "name") VALUES ('jv', 'isi-Javanese');
INSERT INTO "country" ("id", "name") VALUES ('kn', 'isi-Kannada');
INSERT INTO "country" ("id", "name") VALUES ('ks', 'isi-Kashmiri');
INSERT INTO "country" ("id", "name") VALUES ('kk', 'isi-Kazakh');
INSERT INTO "country" ("id", "name") VALUES ('km', 'isi-Khmer');
INSERT INTO "country" ("id", "name") VALUES ('rw', 'isi-Kinyarwanda');
INSERT INTO "country" ("id", "name") VALUES ('ky', 'isi-Kirghiz');
INSERT INTO "country" ("id", "name") VALUES ('ko', 'isi-Korean');
INSERT INTO "country" ("id", "name") VALUES ('ku', 'isi-Kurdish');
INSERT INTO "country" ("id", "name") VALUES ('la', 'isi-Latin');
INSERT INTO "country" ("id", "name") VALUES ('es_419', 'isi-Latin American Spanish');
INSERT INTO "country" ("id", "name") VALUES ('lv', 'isi-Latvia');
INSERT INTO "country" ("id", "name") VALUES ('ln', 'isi-Lingala');
INSERT INTO "country" ("id", "name") VALUES ('lt', 'isi-Lithuanian');
INSERT INTO "country" ("id", "name") VALUES ('lb', 'isi-Luxembourgish');
INSERT INTO "country" ("id", "name") VALUES ('mk', 'isi-Macedonia');
INSERT INTO "country" ("id", "name") VALUES ('mg', 'isi-Malagasy');
INSERT INTO "country" ("id", "name") VALUES ('ms', 'isi-Malay');
INSERT INTO "country" ("id", "name") VALUES ('ml', 'isi-Malayalam');
INSERT INTO "country" ("id", "name") VALUES ('mt', 'isi-Malta');
INSERT INTO "country" ("id", "name") VALUES ('mi', 'isi-Maori');
INSERT INTO "country" ("id", "name") VALUES ('mr', 'isi-Marathi');
INSERT INTO "country" ("id", "name") VALUES ('mn', 'isi-Mongolian');
INSERT INTO "country" ("id", "name") VALUES ('ne', 'isi-Nepali');
INSERT INTO "country" ("id", "name") VALUES ('nd', 'isi-North Ndebele');
INSERT INTO "country" ("id", "name") VALUES ('nso', 'isi-Northern Sotho');
INSERT INTO "country" ("id", "name") VALUES ('ny', 'isi-Nyanja');
INSERT INTO "country" ("id", "name") VALUES ('or', 'isi-Oriya');
INSERT INTO "country" ("id", "name") VALUES ('os', 'isi-Ossetic');
INSERT INTO "country" ("id", "name") VALUES ('ps', 'isi-Pashto');
INSERT INTO "country" ("id", "name") VALUES ('fa', 'isi-Persian');
INSERT INTO "country" ("id", "name") VALUES ('pl', 'isi-Polish');
INSERT INTO "country" ("id", "name") VALUES ('pt', 'isi-Portuguese');
INSERT INTO "country" ("id", "name") VALUES ('pa', 'isi-Punjabi');
INSERT INTO "country" ("id", "name") VALUES ('qu', 'isi-Quechua');
INSERT INTO "country" ("id", "name") VALUES ('ro', 'isi-Romanian');
INSERT INTO "country" ("id", "name") VALUES ('rm', 'isi-Romansh');
INSERT INTO "country" ("id", "name") VALUES ('rn', 'isi-Rundi');
INSERT INTO "country" ("id", "name") VALUES ('ru', 'isi-Russian');
INSERT INTO "country" ("id", "name") VALUES ('sm', 'isi-Samoan');
INSERT INTO "country" ("id", "name") VALUES ('sg', 'isi-Sango');
INSERT INTO "country" ("id", "name") VALUES ('sa', 'isi-Sanskrit');
INSERT INTO "country" ("id", "name") VALUES ('sr', 'isi-Serbian');
INSERT INTO "country" ("id", "name") VALUES ('sd', 'isi-Sindhi');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hans', 'isi-Sipmlified Chinese');
INSERT INTO "country" ("id", "name") VALUES ('sk', 'isi-Slovak');
INSERT INTO "country" ("id", "name") VALUES ('sl', 'isi-Slovenian');
INSERT INTO "country" ("id", "name") VALUES ('so', 'isi-Somali');
INSERT INTO "country" ("id", "name") VALUES ('su', 'isi-Sundanese');
INSERT INTO "country" ("id", "name") VALUES ('sv', 'isi-Swedish');
INSERT INTO "country" ("id", "name") VALUES ('fr_CH', 'isi-Swiss French');
INSERT INTO "country" ("id", "name") VALUES ('gsw', 'isi-Swiss German');
INSERT INTO "country" ("id", "name") VALUES ('de_CH', 'isi-Swiss High German');
INSERT INTO "country" ("id", "name") VALUES ('ty', 'isi-Tahitian');
INSERT INTO "country" ("id", "name") VALUES ('tg', 'isi-Tajik');
INSERT INTO "country" ("id", "name") VALUES ('ta', 'isi-Tamil');
INSERT INTO "country" ("id", "name") VALUES ('tt', 'isi-Tatar');
INSERT INTO "country" ("id", "name") VALUES ('te', 'isi-Telugu');
INSERT INTO "country" ("id", "name") VALUES ('tet', 'isi-Tetum');
INSERT INTO "country" ("id", "name") VALUES ('th', 'isi-Thai');
INSERT INTO "country" ("id", "name") VALUES ('bo', 'isi-Tibetan');
INSERT INTO "country" ("id", "name") VALUES ('ti', 'isi-Tigrinya');
INSERT INTO "country" ("id", "name") VALUES ('tpi', 'isi-Tok Pisin');
INSERT INTO "country" ("id", "name") VALUES ('to', 'isi-Tonga');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hant', 'isi-Traditional Chinese');
INSERT INTO "country" ("id", "name") VALUES ('ts', 'isi-Tsonga');
INSERT INTO "country" ("id", "name") VALUES ('tn', 'isi-Tswana');
INSERT INTO "country" ("id", "name") VALUES ('tr', 'isi-Turkish');
INSERT INTO "country" ("id", "name") VALUES ('tk', 'isi-Turkmen');
INSERT INTO "country" ("id", "name") VALUES ('ug', 'isi-Uighur');
INSERT INTO "country" ("id", "name") VALUES ('uk', 'isi-Ukrainian');
INSERT INTO "country" ("id", "name") VALUES ('ur', 'isi-Urdu');
INSERT INTO "country" ("id", "name") VALUES ('uz', 'isi-Uzbek');
INSERT INTO "country" ("id", "name") VALUES ('ve', 'isi-Venda');
INSERT INTO "country" ("id", "name") VALUES ('vi', 'isi-Vietnamese');
INSERT INTO "country" ("id", "name") VALUES ('cy', 'isi-Welsh');
INSERT INTO "country" ("id", "name") VALUES ('fy', 'isi-Western Frisian');
INSERT INTO "country" ("id", "name") VALUES ('wo', 'isi-Wolof');
INSERT INTO "country" ("id", "name") VALUES ('yo', 'isi-Yoruba');
INSERT INTO "country" ("id", "name") VALUES ('af', 'isiBhunu');
INSERT INTO "country" ("id", "name") VALUES ('fr', 'isiFulentshi');
INSERT INTO "country" ("id", "name") VALUES ('hi', 'isiHindi');
INSERT INTO "country" ("id", "name") VALUES ('de', 'isiJalimani');
INSERT INTO "country" ("id", "name") VALUES ('en', 'isiNgisi');
INSERT INTO "country" ("id", "name") VALUES ('sn', 'isiShona');
INSERT INTO "country" ("id", "name") VALUES ('es', 'isiSpeyini');
INSERT INTO "country" ("id", "name") VALUES ('st', 'isiSuthu');
INSERT INTO "country" ("id", "name") VALUES ('sw', 'isiSwahili');
INSERT INTO "country" ("id", "name") VALUES ('ss', 'isiSwati');
INSERT INTO "country" ("id", "name") VALUES ('xh', 'isiXhosa');
INSERT INTO "country" ("id", "name") VALUES ('zu', 'isiZulu');
INSERT INTO "country" ("id", "name") VALUES ('und', 'Ulimi olungaziwa');
