CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('ab', 'абхазиски');
INSERT INTO [country] ([id], [name]) VALUES ('awa', 'авади');
INSERT INTO [country] ([id], [name]) VALUES ('av', 'аварски');
INSERT INTO [country] ([id], [name]) VALUES ('ae', 'авестан');
INSERT INTO [country] ([id], [name]) VALUES ('aus', 'австралиски');
INSERT INTO [country] ([id], [name]) VALUES ('map', 'австронезиски');
INSERT INTO [country] ([id], [name]) VALUES ('ada', 'адангме');
INSERT INTO [country] ([id], [name]) VALUES ('ady', 'адиге');
INSERT INTO [country] ([id], [name]) VALUES ('az', 'азербејџански');
INSERT INTO [country] ([id], [name]) VALUES ('ain', 'аину');
INSERT INTO [country] ([id], [name]) VALUES ('akk', 'акадијски');
INSERT INTO [country] ([id], [name]) VALUES ('ak', 'акан');
INSERT INTO [country] ([id], [name]) VALUES ('ace', 'акинески');
INSERT INTO [country] ([id], [name]) VALUES ('ach', 'аколи');
INSERT INTO [country] ([id], [name]) VALUES ('sq', 'албански');
INSERT INTO [country] ([id], [name]) VALUES ('alg', 'алгонквијански');
INSERT INTO [country] ([id], [name]) VALUES ('ale', 'алеут');
INSERT INTO [country] ([id], [name]) VALUES ('tut', 'алтајски');
INSERT INTO [country] ([id], [name]) VALUES ('en_US', 'американски англиски');
INSERT INTO [country] ([id], [name]) VALUES ('am', 'амхариски');
INSERT INTO [country] ([id], [name]) VALUES ('anp', 'ангика');
INSERT INTO [country] ([id], [name]) VALUES ('en', 'англиски');
INSERT INTO [country] ([id], [name]) VALUES ('en_AU', 'англиски (во Австралија)');
INSERT INTO [country] ([id], [name]) VALUES ('en_GB', 'англиски (во Велика Британија)');
INSERT INTO [country] ([id], [name]) VALUES ('en_CA', 'англиски (во Канада)');
INSERT INTO [country] ([id], [name]) VALUES ('cpe', 'англиски креолски');
INSERT INTO [country] ([id], [name]) VALUES ('apa', 'апачи');
INSERT INTO [country] ([id], [name]) VALUES ('arw', 'аравак');
INSERT INTO [country] ([id], [name]) VALUES ('an', 'арагонески');
INSERT INTO [country] ([id], [name]) VALUES ('arc', 'арамејски');
INSERT INTO [country] ([id], [name]) VALUES ('arp', 'арапахо');
INSERT INTO [country] ([id], [name]) VALUES ('ar', 'арапски');
INSERT INTO [country] ([id], [name]) VALUES ('arn', 'арокенски');
INSERT INTO [country] ([id], [name]) VALUES ('as', 'асамски');
INSERT INTO [country] ([id], [name]) VALUES ('ast', 'астуриски');
INSERT INTO [country] ([id], [name]) VALUES ('ath', 'атапаски');
INSERT INTO [country] ([id], [name]) VALUES ('aa', 'афар');
INSERT INTO [country] ([id], [name]) VALUES ('af', 'африкански');
INSERT INTO [country] ([id], [name]) VALUES ('afh', 'африхили');
INSERT INTO [country] ([id], [name]) VALUES ('afa', 'афроазијатски');
INSERT INTO [country] ([id], [name]) VALUES ('cch', 'ацам');
INSERT INTO [country] ([id], [name]) VALUES ('ay', 'ајмара');
INSERT INTO [country] ([id], [name]) VALUES ('ban', 'балинезе');
INSERT INTO [country] ([id], [name]) VALUES ('bat', 'балтички');
INSERT INTO [country] ([id], [name]) VALUES ('bal', 'балучи');
INSERT INTO [country] ([id], [name]) VALUES ('bm', 'бамбара');
INSERT INTO [country] ([id], [name]) VALUES ('bai', 'бамилеке');
INSERT INTO [country] ([id], [name]) VALUES ('bad', 'банда');
INSERT INTO [country] ([id], [name]) VALUES ('bnt', 'банту');
INSERT INTO [country] ([id], [name]) VALUES ('bas', 'баса');
INSERT INTO [country] ([id], [name]) VALUES ('eu', 'баскиски');
INSERT INTO [country] ([id], [name]) VALUES ('btk', 'батак');
INSERT INTO [country] ([id], [name]) VALUES ('ba', 'башкирски');
INSERT INTO [country] ([id], [name]) VALUES ('zxx', 'без лингвистичка содржина');
INSERT INTO [country] ([id], [name]) VALUES ('be', 'белоруски');
INSERT INTO [country] ([id], [name]) VALUES ('bem', 'бемба');
INSERT INTO [country] ([id], [name]) VALUES ('bn', 'бенгалски');
INSERT INTO [country] ([id], [name]) VALUES ('ber', 'бербер');
INSERT INTO [country] ([id], [name]) VALUES ('bej', 'беха');
INSERT INTO [country] ([id], [name]) VALUES ('bik', 'бикол');
INSERT INTO [country] ([id], [name]) VALUES ('bin', 'бини');
INSERT INTO [country] ([id], [name]) VALUES ('bi', 'бислама');
INSERT INTO [country] ([id], [name]) VALUES ('bh', 'бихари');
INSERT INTO [country] ([id], [name]) VALUES ('byn', 'блин');
INSERT INTO [country] ([id], [name]) VALUES ('zbl', 'блисимболс');
INSERT INTO [country] ([id], [name]) VALUES ('bs', 'босански');
INSERT INTO [country] ([id], [name]) VALUES ('bho', 'бојпури');
INSERT INTO [country] ([id], [name]) VALUES ('bra', 'брај');
INSERT INTO [country] ([id], [name]) VALUES ('br', 'бретонски');
INSERT INTO [country] ([id], [name]) VALUES ('bg', 'бугарски');
INSERT INTO [country] ([id], [name]) VALUES ('bua', 'буријат');
INSERT INTO [country] ([id], [name]) VALUES ('my', 'бурмански');
INSERT INTO [country] ([id], [name]) VALUES ('bug', 'буџински');
INSERT INTO [country] ([id], [name]) VALUES ('vai', 'ваи');
INSERT INTO [country] ([id], [name]) VALUES ('wak', 'вакашански');
INSERT INTO [country] ([id], [name]) VALUES ('wal', 'валамо');
INSERT INTO [country] ([id], [name]) VALUES ('wa', 'валунски');
INSERT INTO [country] ([id], [name]) VALUES ('war', 'вареј');
INSERT INTO [country] ([id], [name]) VALUES ('was', 'вашо');
INSERT INTO [country] ([id], [name]) VALUES ('cy', 'велшки');
INSERT INTO [country] ([id], [name]) VALUES ('ve', 'венда');
INSERT INTO [country] ([id], [name]) VALUES ('art', 'вештачки');
INSERT INTO [country] ([id], [name]) VALUES ('vi', 'виетнамски');
INSERT INTO [country] ([id], [name]) VALUES ('rup', 'влашки');
INSERT INTO [country] ([id], [name]) VALUES ('vo', 'волапјок');
INSERT INTO [country] ([id], [name]) VALUES ('wo', 'волофски');
INSERT INTO [country] ([id], [name]) VALUES ('vot', 'вотски');
INSERT INTO [country] ([id], [name]) VALUES ('gaa', 'га');
INSERT INTO [country] ([id], [name]) VALUES ('gl', 'галициски');
INSERT INTO [country] ([id], [name]) VALUES ('lg', 'ганда');
INSERT INTO [country] ([id], [name]) VALUES ('gay', 'гајо');
INSERT INTO [country] ([id], [name]) VALUES ('gba', 'гбаја');
INSERT INTO [country] ([id], [name]) VALUES ('gwi', 'гвишин');
INSERT INTO [country] ([id], [name]) VALUES ('de', 'германски');
INSERT INTO [country] ([id], [name]) VALUES ('de_AT', 'германски (во Австрија)');
INSERT INTO [country] ([id], [name]) VALUES ('de_CH', 'германски (во Швајцарија)');
INSERT INTO [country] ([id], [name]) VALUES ('gem', 'германски јазици');
INSERT INTO [country] ([id], [name]) VALUES ('gez', 'гиз');
INSERT INTO [country] ([id], [name]) VALUES ('gil', 'гилбертански');
INSERT INTO [country] ([id], [name]) VALUES ('gon', 'гонди');
INSERT INTO [country] ([id], [name]) VALUES ('hsb', 'горносорбиски');
INSERT INTO [country] ([id], [name]) VALUES ('gor', 'горонтало');
INSERT INTO [country] ([id], [name]) VALUES ('got', 'готски');
INSERT INTO [country] ([id], [name]) VALUES ('grb', 'грево');
INSERT INTO [country] ([id], [name]) VALUES ('ka', 'грузиски');
INSERT INTO [country] ([id], [name]) VALUES ('el', 'грчки');
INSERT INTO [country] ([id], [name]) VALUES ('gn', 'гуарани');
INSERT INTO [country] ([id], [name]) VALUES ('gu', 'гуџарати');
INSERT INTO [country] ([id], [name]) VALUES ('dak', 'дакота');
INSERT INTO [country] ([id], [name]) VALUES ('da', 'дански');
INSERT INTO [country] ([id], [name]) VALUES ('dar', 'даргва');
INSERT INTO [country] ([id], [name]) VALUES ('day', 'дајак');
INSERT INTO [country] ([id], [name]) VALUES ('del', 'делавер');
INSERT INTO [country] ([id], [name]) VALUES ('dv', 'дивехи');
INSERT INTO [country] ([id], [name]) VALUES ('din', 'динка');
INSERT INTO [country] ([id], [name]) VALUES ('doi', 'догри');
INSERT INTO [country] ([id], [name]) VALUES ('dgr', 'догриб');
INSERT INTO [country] ([id], [name]) VALUES ('nds', 'долногермански');
INSERT INTO [country] ([id], [name]) VALUES ('dsb', 'долносорбиски');
INSERT INTO [country] ([id], [name]) VALUES ('dra', 'дравидијски');
INSERT INTO [country] ([id], [name]) VALUES ('mis', 'други јазици');
INSERT INTO [country] ([id], [name]) VALUES ('dua', 'дуала');
INSERT INTO [country] ([id], [name]) VALUES ('ee', 'еве');
INSERT INTO [country] ([id], [name]) VALUES ('ewo', 'евондо');
INSERT INTO [country] ([id], [name]) VALUES ('jrb', 'еврејско арапски');
INSERT INTO [country] ([id], [name]) VALUES ('jpr', 'еврејско персиски');
INSERT INTO [country] ([id], [name]) VALUES ('eka', 'екајук');
INSERT INTO [country] ([id], [name]) VALUES ('elx', 'еламит');
INSERT INTO [country] ([id], [name]) VALUES ('myv', 'ержа');
INSERT INTO [country] ([id], [name]) VALUES ('hy', 'ерменски');
INSERT INTO [country] ([id], [name]) VALUES ('eo', 'есперанто');
INSERT INTO [country] ([id], [name]) VALUES ('et', 'естонски');
INSERT INTO [country] ([id], [name]) VALUES ('efi', 'ефик');
INSERT INTO [country] ([id], [name]) VALUES ('chn', 'жаргон чинук');
INSERT INTO [country] ([id], [name]) VALUES ('kaj', 'жжи');
INSERT INTO [country] ([id], [name]) VALUES ('za', 'жуанг');
INSERT INTO [country] ([id], [name]) VALUES ('zza', 'заза');
INSERT INTO [country] ([id], [name]) VALUES ('znd', 'зандиски');
INSERT INTO [country] ([id], [name]) VALUES ('zap', 'запотек');
INSERT INTO [country] ([id], [name]) VALUES ('zen', 'зенага');
INSERT INTO [country] ([id], [name]) VALUES ('sgn', 'знаковни јазици');
INSERT INTO [country] ([id], [name]) VALUES ('zu', 'зулу');
INSERT INTO [country] ([id], [name]) VALUES ('zun', 'зуни');
INSERT INTO [country] ([id], [name]) VALUES ('iba', 'ибан');
INSERT INTO [country] ([id], [name]) VALUES ('ig', 'игбо');
INSERT INTO [country] ([id], [name]) VALUES ('io', 'идо');
INSERT INTO [country] ([id], [name]) VALUES ('ilo', 'илоко');
INSERT INTO [country] ([id], [name]) VALUES ('smn', 'инари сами');
INSERT INTO [country] ([id], [name]) VALUES ('inh', 'ингуш');
INSERT INTO [country] ([id], [name]) VALUES ('inc', 'индиски јазици');
INSERT INTO [country] ([id], [name]) VALUES ('ine', 'индоевропски');
INSERT INTO [country] ([id], [name]) VALUES ('id', 'индонезиски');
INSERT INTO [country] ([id], [name]) VALUES ('ie', 'интерлинг');
INSERT INTO [country] ([id], [name]) VALUES ('ia', 'интерлингва');
INSERT INTO [country] ([id], [name]) VALUES ('iu', 'инуктитут');
INSERT INTO [country] ([id], [name]) VALUES ('ik', 'инупијак');
INSERT INTO [country] ([id], [name]) VALUES ('ira', 'ирански');
INSERT INTO [country] ([id], [name]) VALUES ('iro', 'ироквијански јазици');
INSERT INTO [country] ([id], [name]) VALUES ('ga', 'ирски');
INSERT INTO [country] ([id], [name]) VALUES ('is', 'исландски');
INSERT INTO [country] ([id], [name]) VALUES ('frs', 'источен фризиски');
INSERT INTO [country] ([id], [name]) VALUES ('it', 'италијански');
INSERT INTO [country] ([id], [name]) VALUES ('ijo', 'ихо');
INSERT INTO [country] ([id], [name]) VALUES ('kbd', 'кабардиски');
INSERT INTO [country] ([id], [name]) VALUES ('kab', 'кабиле');
INSERT INTO [country] ([id], [name]) VALUES ('kaw', 'кави');
INSERT INTO [country] ([id], [name]) VALUES ('cau', 'кавкаски');
INSERT INTO [country] ([id], [name]) VALUES ('cad', 'кадо');
INSERT INTO [country] ([id], [name]) VALUES ('kk', 'казакстански');
INSERT INTO [country] ([id], [name]) VALUES ('kl', 'калалисут');
INSERT INTO [country] ([id], [name]) VALUES ('xal', 'калмик');
INSERT INTO [country] ([id], [name]) VALUES ('kam', 'камба');
INSERT INTO [country] ([id], [name]) VALUES ('km', 'камбоџански');
INSERT INTO [country] ([id], [name]) VALUES ('kn', 'каннада');
INSERT INTO [country] ([id], [name]) VALUES ('kr', 'канури');
INSERT INTO [country] ([id], [name]) VALUES ('kaa', 'кара калпак');
INSERT INTO [country] ([id], [name]) VALUES ('krc', 'карашај-балкар');
INSERT INTO [country] ([id], [name]) VALUES ('krl', 'карелијски');
INSERT INTO [country] ([id], [name]) VALUES ('kar', 'карен');
INSERT INTO [country] ([id], [name]) VALUES ('car', 'кариб');
INSERT INTO [country] ([id], [name]) VALUES ('kha', 'каси');
INSERT INTO [country] ([id], [name]) VALUES ('ca', 'каталонски');
INSERT INTO [country] ([id], [name]) VALUES ('kac', 'кашин');
INSERT INTO [country] ([id], [name]) VALUES ('ks', 'кашмирски');
INSERT INTO [country] ([id], [name]) VALUES ('csb', 'кашубиски');
INSERT INTO [country] ([id], [name]) VALUES ('qu', 'кечуа');
INSERT INTO [country] ([id], [name]) VALUES ('ki', 'кикују');
INSERT INTO [country] ([id], [name]) VALUES ('kmb', 'кимбунду');
INSERT INTO [country] ([id], [name]) VALUES ('zh', 'кинески');
INSERT INTO [country] ([id], [name]) VALUES ('ky', 'киргистански');
INSERT INTO [country] ([id], [name]) VALUES ('rw', 'кињарванда');
INSERT INTO [country] ([id], [name]) VALUES ('nwc', 'класичен невари');
INSERT INTO [country] ([id], [name]) VALUES ('syc', 'класичен сиријак');
INSERT INTO [country] ([id], [name]) VALUES ('tlh', 'клингонски');
INSERT INTO [country] ([id], [name]) VALUES ('kos', 'козрејски');
INSERT INTO [country] ([id], [name]) VALUES ('kv', 'коми');
INSERT INTO [country] ([id], [name]) VALUES ('kg', 'конго');
INSERT INTO [country] ([id], [name]) VALUES ('kok', 'конкани');
INSERT INTO [country] ([id], [name]) VALUES ('cop', 'коптски');
INSERT INTO [country] ([id], [name]) VALUES ('ko', 'корејски');
INSERT INTO [country] ([id], [name]) VALUES ('co', 'корзикански');
INSERT INTO [country] ([id], [name]) VALUES ('kw', 'корнуолски келтски');
INSERT INTO [country] ([id], [name]) VALUES ('kfo', 'коро');
INSERT INTO [country] ([id], [name]) VALUES ('kho', 'котанески');
INSERT INTO [country] ([id], [name]) VALUES ('khi', 'којсански јазици');
INSERT INTO [country] ([id], [name]) VALUES ('kpe', 'кпеле');
INSERT INTO [country] ([id], [name]) VALUES ('crp', 'креолски');
INSERT INTO [country] ([id], [name]) VALUES ('cr', 'кри');
INSERT INTO [country] ([id], [name]) VALUES ('mus', 'крик');
INSERT INTO [country] ([id], [name]) VALUES ('crh', 'кримско турски');
INSERT INTO [country] ([id], [name]) VALUES ('kro', 'кру');
INSERT INTO [country] ([id], [name]) VALUES ('kj', 'куањама');
INSERT INTO [country] ([id], [name]) VALUES ('kum', 'кумик');
INSERT INTO [country] ([id], [name]) VALUES ('ku', 'курдски');
INSERT INTO [country] ([id], [name]) VALUES ('kru', 'курук');
INSERT INTO [country] ([id], [name]) VALUES ('kut', 'кутенајски');
INSERT INTO [country] ([id], [name]) VALUES ('cus', 'кушитски');
INSERT INTO [country] ([id], [name]) VALUES ('lad', 'ладино');
INSERT INTO [country] ([id], [name]) VALUES ('lam', 'ламба');
INSERT INTO [country] ([id], [name]) VALUES ('lah', 'ланда');
INSERT INTO [country] ([id], [name]) VALUES ('lo', 'лао');
INSERT INTO [country] ([id], [name]) VALUES ('lv', 'латвиски');
INSERT INTO [country] ([id], [name]) VALUES ('la', 'латински');
INSERT INTO [country] ([id], [name]) VALUES ('lez', 'лежгијски');
INSERT INTO [country] ([id], [name]) VALUES ('li', 'лимбуршки');
INSERT INTO [country] ([id], [name]) VALUES ('ln', 'лингала');
INSERT INTO [country] ([id], [name]) VALUES ('lt', 'литвански');
INSERT INTO [country] ([id], [name]) VALUES ('loz', 'лози');
INSERT INTO [country] ([id], [name]) VALUES ('jbo', 'лојбански');
INSERT INTO [country] ([id], [name]) VALUES ('lu', 'луба-катанга');
INSERT INTO [country] ([id], [name]) VALUES ('lua', 'луба-лулуа');
INSERT INTO [country] ([id], [name]) VALUES ('lui', 'луизено');
INSERT INTO [country] ([id], [name]) VALUES ('lb', 'луксембуршки');
INSERT INTO [country] ([id], [name]) VALUES ('smj', 'луле сами');
INSERT INTO [country] ([id], [name]) VALUES ('lun', 'лунда');
INSERT INTO [country] ([id], [name]) VALUES ('luo', 'луо');
INSERT INTO [country] ([id], [name]) VALUES ('lus', 'лушајски');
INSERT INTO [country] ([id], [name]) VALUES ('mag', 'магахи');
INSERT INTO [country] ([id], [name]) VALUES ('mad', 'мадурески');
INSERT INTO [country] ([id], [name]) VALUES ('mai', 'маитхили');
INSERT INTO [country] ([id], [name]) VALUES ('mak', 'макасарски');
INSERT INTO [country] ([id], [name]) VALUES ('mk', 'македонски');
INSERT INTO [country] ([id], [name]) VALUES ('ml', 'малајалам');
INSERT INTO [country] ([id], [name]) VALUES ('mg', 'малгашки');
INSERT INTO [country] ([id], [name]) VALUES ('ms', 'малезиски');
INSERT INTO [country] ([id], [name]) VALUES ('mt', 'малтешки');
INSERT INTO [country] ([id], [name]) VALUES ('mdr', 'мандар');
INSERT INTO [country] ([id], [name]) VALUES ('man', 'мандинго');
INSERT INTO [country] ([id], [name]) VALUES ('mni', 'манипури');
INSERT INTO [country] ([id], [name]) VALUES ('gv', 'манкс');
INSERT INTO [country] ([id], [name]) VALUES ('mno', 'манобо');
INSERT INTO [country] ([id], [name]) VALUES ('mnc', 'манчу');
INSERT INTO [country] ([id], [name]) VALUES ('mi', 'маорски');
INSERT INTO [country] ([id], [name]) VALUES ('mr', 'марати');
INSERT INTO [country] ([id], [name]) VALUES ('mwr', 'марвари');
INSERT INTO [country] ([id], [name]) VALUES ('chm', 'мари');
INSERT INTO [country] ([id], [name]) VALUES ('mh', 'маршалски');
INSERT INTO [country] ([id], [name]) VALUES ('mas', 'масаи');
INSERT INTO [country] ([id], [name]) VALUES ('myn', 'мајански јазици');
INSERT INTO [country] ([id], [name]) VALUES ('men', 'мендески');
INSERT INTO [country] ([id], [name]) VALUES ('mic', 'микмек');
INSERT INTO [country] ([id], [name]) VALUES ('min', 'минанкабау');
INSERT INTO [country] ([id], [name]) VALUES ('mwl', 'мирандески');
INSERT INTO [country] ([id], [name]) VALUES ('mdf', 'мокша');
INSERT INTO [country] ([id], [name]) VALUES ('mo', 'молдавски');
INSERT INTO [country] ([id], [name]) VALUES ('mkh', 'мон-кмерски јазици');
INSERT INTO [country] ([id], [name]) VALUES ('lol', 'монго');
INSERT INTO [country] ([id], [name]) VALUES ('mn', 'монголски');
INSERT INTO [country] ([id], [name]) VALUES ('mos', 'моси');
INSERT INTO [country] ([id], [name]) VALUES ('moh', 'мохак');
INSERT INTO [country] ([id], [name]) VALUES ('mun', 'мунда јазици');
INSERT INTO [country] ([id], [name]) VALUES ('nv', 'навахо');
INSERT INTO [country] ([id], [name]) VALUES ('na', 'науру');
INSERT INTO [country] ([id], [name]) VALUES ('nah', 'нахуатл');
INSERT INTO [country] ([id], [name]) VALUES ('niu', 'најуан');
INSERT INTO [country] ([id], [name]) VALUES ('ng', 'ндонга');
INSERT INTO [country] ([id], [name]) VALUES ('nap', 'неаполски');
INSERT INTO [country] ([id], [name]) VALUES ('new', 'невари');
INSERT INTO [country] ([id], [name]) VALUES ('ne', 'непалски');
INSERT INTO [country] ([id], [name]) VALUES ('und', 'непознат или неважечки јазик');
INSERT INTO [country] ([id], [name]) VALUES ('nzi', 'нзима');
INSERT INTO [country] ([id], [name]) VALUES ('nic', 'нигер-кордофаниски јазици');
INSERT INTO [country] ([id], [name]) VALUES ('ssa', 'нилско-сахарски јазици');
INSERT INTO [country] ([id], [name]) VALUES ('nia', 'нијас');
INSERT INTO [country] ([id], [name]) VALUES ('nqo', 'нко');
INSERT INTO [country] ([id], [name]) VALUES ('nog', 'ногај');
INSERT INTO [country] ([id], [name]) VALUES ('no', 'норвешки');
INSERT INTO [country] ([id], [name]) VALUES ('nb', 'норвешки бокмал');
INSERT INTO [country] ([id], [name]) VALUES ('nn', 'норвешки ниноршк');
INSERT INTO [country] ([id], [name]) VALUES ('nub', 'нубијски јазици');
INSERT INTO [country] ([id], [name]) VALUES ('oc', 'окситански');
INSERT INTO [country] ([id], [name]) VALUES ('or', 'орија');
INSERT INTO [country] ([id], [name]) VALUES ('om', 'оромо');
INSERT INTO [country] ([id], [name]) VALUES ('osa', 'осаж');
INSERT INTO [country] ([id], [name]) VALUES ('os', 'осетиски');
INSERT INTO [country] ([id], [name]) VALUES ('ota', 'отомански турски');
INSERT INTO [country] ([id], [name]) VALUES ('oto', 'отомиски јазици');
INSERT INTO [country] ([id], [name]) VALUES ('oj', 'оџибва');
INSERT INTO [country] ([id], [name]) VALUES ('pal', 'палависки');
INSERT INTO [country] ([id], [name]) VALUES ('pau', 'палауански');
INSERT INTO [country] ([id], [name]) VALUES ('pi', 'пали');
INSERT INTO [country] ([id], [name]) VALUES ('pam', 'пампанга');
INSERT INTO [country] ([id], [name]) VALUES ('pag', 'пангасинан');
INSERT INTO [country] ([id], [name]) VALUES ('pap', 'папиаменто');
INSERT INTO [country] ([id], [name]) VALUES ('paa', 'папуански');
INSERT INTO [country] ([id], [name]) VALUES ('ps', 'пашто');
INSERT INTO [country] ([id], [name]) VALUES ('fa', 'персиски');
INSERT INTO [country] ([id], [name]) VALUES ('mul', 'повеќе јазици');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hans', 'поедноставен кинески');
INSERT INTO [country] ([id], [name]) VALUES ('pl', 'полски');
INSERT INTO [country] ([id], [name]) VALUES ('pon', 'понпејански');
INSERT INTO [country] ([id], [name]) VALUES ('pt', 'португалски');
INSERT INTO [country] ([id], [name]) VALUES ('pt_BR', 'португалски (во Бразил)');
INSERT INTO [country] ([id], [name]) VALUES ('pt_PT', 'португалски (во Португалија)');
INSERT INTO [country] ([id], [name]) VALUES ('cpp', 'португалски креолски');
INSERT INTO [country] ([id], [name]) VALUES ('pra', 'пракритски јазици');
INSERT INTO [country] ([id], [name]) VALUES ('pa', 'пунџаби');
INSERT INTO [country] ([id], [name]) VALUES ('rap', 'рапануи');
INSERT INTO [country] ([id], [name]) VALUES ('rar', 'раротонган');
INSERT INTO [country] ([id], [name]) VALUES ('raj', 'раџастански');
INSERT INTO [country] ([id], [name]) VALUES ('rm', 'реторомански');
INSERT INTO [country] ([id], [name]) VALUES ('ro', 'романски');
INSERT INTO [country] ([id], [name]) VALUES ('roa', 'романски јазици');
INSERT INTO [country] ([id], [name]) VALUES ('rom', 'ромски');
INSERT INTO [country] ([id], [name]) VALUES ('rn', 'рундиски');
INSERT INTO [country] ([id], [name]) VALUES ('ru', 'руски');
INSERT INTO [country] ([id], [name]) VALUES ('root', 'рутски');
INSERT INTO [country] ([id], [name]) VALUES ('sal', 'салишански јазици');
INSERT INTO [country] ([id], [name]) VALUES ('sam', 'самариќански арамејски');
INSERT INTO [country] ([id], [name]) VALUES ('smi', 'самиски јазици');
INSERT INTO [country] ([id], [name]) VALUES ('sm', 'самоански');
INSERT INTO [country] ([id], [name]) VALUES ('sg', 'санго');
INSERT INTO [country] ([id], [name]) VALUES ('sad', 'сандаве');
INSERT INTO [country] ([id], [name]) VALUES ('sa', 'санскрит');
INSERT INTO [country] ([id], [name]) VALUES ('sat', 'сантали');
INSERT INTO [country] ([id], [name]) VALUES ('sc', 'сардиниски');
INSERT INTO [country] ([id], [name]) VALUES ('sas', 'сасак');
INSERT INTO [country] ([id], [name]) VALUES ('ss', 'свати');
INSERT INTO [country] ([id], [name]) VALUES ('sw', 'свахили');
INSERT INTO [country] ([id], [name]) VALUES ('ceb', 'себуано');
INSERT INTO [country] ([id], [name]) VALUES ('nd', 'северен ндебеле');
INSERT INTO [country] ([id], [name]) VALUES ('se', 'северен самиски');
INSERT INTO [country] ([id], [name]) VALUES ('nso', 'северен сото');
INSERT INTO [country] ([id], [name]) VALUES ('frr', 'северен фризиски');
INSERT INTO [country] ([id], [name]) VALUES ('nai', 'северноамерикански индијански јазици');
INSERT INTO [country] ([id], [name]) VALUES ('sel', 'селкап');
INSERT INTO [country] ([id], [name]) VALUES ('cel', 'селтички');
INSERT INTO [country] ([id], [name]) VALUES ('sem', 'семитски');
INSERT INTO [country] ([id], [name]) VALUES ('srr', 'серер');
INSERT INTO [country] ([id], [name]) VALUES ('st', 'сесото');
INSERT INTO [country] ([id], [name]) VALUES ('sid', 'сидамо');
INSERT INTO [country] ([id], [name]) VALUES ('bla', 'сиксика');
INSERT INTO [country] ([id], [name]) VALUES ('sd', 'синди');
INSERT INTO [country] ([id], [name]) VALUES ('sit', 'синотибетански');
INSERT INTO [country] ([id], [name]) VALUES ('si', 'синхалиски');
INSERT INTO [country] ([id], [name]) VALUES ('syr', 'сиријак');
INSERT INTO [country] ([id], [name]) VALUES ('scn', 'сицилијански');
INSERT INTO [country] ([id], [name]) VALUES ('ii', 'сичуан ји');
INSERT INTO [country] ([id], [name]) VALUES ('sio', 'сијуски јазици');
INSERT INTO [country] ([id], [name]) VALUES ('sms', 'сколт сами');
INSERT INTO [country] ([id], [name]) VALUES ('sco', 'скоц');
INSERT INTO [country] ([id], [name]) VALUES ('den', 'славски');
INSERT INTO [country] ([id], [name]) VALUES ('sk', 'словачки');
INSERT INTO [country] ([id], [name]) VALUES ('sl', 'словенечки јазик');
INSERT INTO [country] ([id], [name]) VALUES ('sla', 'словенски јазици');
INSERT INTO [country] ([id], [name]) VALUES ('sog', 'согдијен');
INSERT INTO [country] ([id], [name]) VALUES ('so', 'сомалиски');
INSERT INTO [country] ([id], [name]) VALUES ('son', 'сонгај');
INSERT INTO [country] ([id], [name]) VALUES ('snk', 'сонинке');
INSERT INTO [country] ([id], [name]) VALUES ('wen', 'сорбиски');
INSERT INTO [country] ([id], [name]) VALUES ('srn', 'срански тонго');
INSERT INTO [country] ([id], [name]) VALUES ('gmh', 'среден горногермански');
INSERT INTO [country] ([id], [name]) VALUES ('enm', 'средноанглиски');
INSERT INTO [country] ([id], [name]) VALUES ('mga', 'средноирски');
INSERT INTO [country] ([id], [name]) VALUES ('frm', 'среднофранцуски');
INSERT INTO [country] ([id], [name]) VALUES ('dum', 'среднохоландски');
INSERT INTO [country] ([id], [name]) VALUES ('sr', 'српски');
INSERT INTO [country] ([id], [name]) VALUES ('sh', 'српско-хрватски');
INSERT INTO [country] ([id], [name]) VALUES ('ang', 'стар англиски');
INSERT INTO [country] ([id], [name]) VALUES ('goh', 'стар високогермански');
INSERT INTO [country] ([id], [name]) VALUES ('sga', 'стар ирски');
INSERT INTO [country] ([id], [name]) VALUES ('non', 'стар норски');
INSERT INTO [country] ([id], [name]) VALUES ('peo', 'стар персиски');
INSERT INTO [country] ([id], [name]) VALUES ('pro', 'стар провенчал');
INSERT INTO [country] ([id], [name]) VALUES ('fro', 'стар француски');
INSERT INTO [country] ([id], [name]) VALUES ('grc', 'старогрчки');
INSERT INTO [country] ([id], [name]) VALUES ('egy', 'староегипетски');
INSERT INTO [country] ([id], [name]) VALUES ('suk', 'сукума');
INSERT INTO [country] ([id], [name]) VALUES ('sux', 'сумериски');
INSERT INTO [country] ([id], [name]) VALUES ('su', 'сунданески');
INSERT INTO [country] ([id], [name]) VALUES ('sus', 'сусу');
INSERT INTO [country] ([id], [name]) VALUES ('tl', 'тагалог');
INSERT INTO [country] ([id], [name]) VALUES ('tai', 'таи');
INSERT INTO [country] ([id], [name]) VALUES ('tmh', 'тамашек');
INSERT INTO [country] ([id], [name]) VALUES ('ta', 'тамилски');
INSERT INTO [country] ([id], [name]) VALUES ('tt', 'татарски');
INSERT INTO [country] ([id], [name]) VALUES ('ty', 'тахитски');
INSERT INTO [country] ([id], [name]) VALUES ('th', 'тајландски');
INSERT INTO [country] ([id], [name]) VALUES ('tg', 'таџикистански');
INSERT INTO [country] ([id], [name]) VALUES ('tw', 'тви');
INSERT INTO [country] ([id], [name]) VALUES ('te', 'телугу');
INSERT INTO [country] ([id], [name]) VALUES ('ter', 'терено');
INSERT INTO [country] ([id], [name]) VALUES ('tet', 'тетум');
INSERT INTO [country] ([id], [name]) VALUES ('bo', 'тибетски');
INSERT INTO [country] ([id], [name]) VALUES ('tiv', 'тив');
INSERT INTO [country] ([id], [name]) VALUES ('tig', 'тигре');
INSERT INTO [country] ([id], [name]) VALUES ('ti', 'тигрејски');
INSERT INTO [country] ([id], [name]) VALUES ('tem', 'тимне');
INSERT INTO [country] ([id], [name]) VALUES ('tli', 'тлингит');
INSERT INTO [country] ([id], [name]) VALUES ('tpi', 'ток писин');
INSERT INTO [country] ([id], [name]) VALUES ('tkl', 'токелау');
INSERT INTO [country] ([id], [name]) VALUES ('to', 'тонга');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hant', 'традиционален кинески');
INSERT INTO [country] ([id], [name]) VALUES ('tvl', 'тувалу');
INSERT INTO [country] ([id], [name]) VALUES ('tyv', 'тувинијански');
INSERT INTO [country] ([id], [name]) VALUES ('tum', 'тумбука');
INSERT INTO [country] ([id], [name]) VALUES ('tup', 'туписки јазици');
INSERT INTO [country] ([id], [name]) VALUES ('tk', 'туркменистански');
INSERT INTO [country] ([id], [name]) VALUES ('tr', 'турски');
INSERT INTO [country] ([id], [name]) VALUES ('kcg', 'тјап');
INSERT INTO [country] ([id], [name]) VALUES ('uga', 'угаритски');
INSERT INTO [country] ([id], [name]) VALUES ('udm', 'удмурт');
INSERT INTO [country] ([id], [name]) VALUES ('uz', 'узбекистански');
INSERT INTO [country] ([id], [name]) VALUES ('uk', 'украински');
INSERT INTO [country] ([id], [name]) VALUES ('umb', 'умбунду');
INSERT INTO [country] ([id], [name]) VALUES ('hu', 'унгарски');
INSERT INTO [country] ([id], [name]) VALUES ('ur', 'урду');
INSERT INTO [country] ([id], [name]) VALUES ('ug', 'ујгурски');
INSERT INTO [country] ([id], [name]) VALUES ('fan', 'фанг');
INSERT INTO [country] ([id], [name]) VALUES ('fat', 'фанти');
INSERT INTO [country] ([id], [name]) VALUES ('fo', 'фарски');
INSERT INTO [country] ([id], [name]) VALUES ('phn', 'феникиски');
INSERT INTO [country] ([id], [name]) VALUES ('fil', 'филипински');
INSERT INTO [country] ([id], [name]) VALUES ('phi', 'филипински јазик');
INSERT INTO [country] ([id], [name]) VALUES ('fiu', 'финоугриски');
INSERT INTO [country] ([id], [name]) VALUES ('fi', 'фински');
INSERT INTO [country] ([id], [name]) VALUES ('fj', 'фиџиски');
INSERT INTO [country] ([id], [name]) VALUES ('fon', 'фон');
INSERT INTO [country] ([id], [name]) VALUES ('fr', 'француски');
INSERT INTO [country] ([id], [name]) VALUES ('fr_CA', 'француски (во Канада)');
INSERT INTO [country] ([id], [name]) VALUES ('fr_CH', 'француски (во Швајцарија)');
INSERT INTO [country] ([id], [name]) VALUES ('cpf', 'француски креолски');
INSERT INTO [country] ([id], [name]) VALUES ('fy', 'фризиски');
INSERT INTO [country] ([id], [name]) VALUES ('fur', 'фрулијански');
INSERT INTO [country] ([id], [name]) VALUES ('ff', 'фула');
INSERT INTO [country] ([id], [name]) VALUES ('haw', 'хавајски');
INSERT INTO [country] ([id], [name]) VALUES ('ht', 'хаитски');
INSERT INTO [country] ([id], [name]) VALUES ('ha', 'хауза');
INSERT INTO [country] ([id], [name]) VALUES ('xh', 'хауса');
INSERT INTO [country] ([id], [name]) VALUES ('hai', 'хајда');
INSERT INTO [country] ([id], [name]) VALUES ('he', 'хебрејски');
INSERT INTO [country] ([id], [name]) VALUES ('hz', 'хереро');
INSERT INTO [country] ([id], [name]) VALUES ('hil', 'хилигајнон');
INSERT INTO [country] ([id], [name]) VALUES ('him', 'химашали');
INSERT INTO [country] ([id], [name]) VALUES ('hi', 'хинди');
INSERT INTO [country] ([id], [name]) VALUES ('ho', 'хири моту');
INSERT INTO [country] ([id], [name]) VALUES ('hit', 'хитите');
INSERT INTO [country] ([id], [name]) VALUES ('hmn', 'хмонг');
INSERT INTO [country] ([id], [name]) VALUES ('nl', 'холандски');
INSERT INTO [country] ([id], [name]) VALUES ('nl_BE', 'холандски (во Белгија)');
INSERT INTO [country] ([id], [name]) VALUES ('hr', 'хрватски');
INSERT INTO [country] ([id], [name]) VALUES ('hup', 'хупа');
INSERT INTO [country] ([id], [name]) VALUES ('tn', 'цвана');
INSERT INTO [country] ([id], [name]) VALUES ('cai', 'централноамерикански индијански');
INSERT INTO [country] ([id], [name]) VALUES ('tsi', 'цимшијански');
INSERT INTO [country] ([id], [name]) VALUES ('ts', 'цонга');
INSERT INTO [country] ([id], [name]) VALUES ('cu', 'црковнословенски');
INSERT INTO [country] ([id], [name]) VALUES ('chg', 'чагатај');
INSERT INTO [country] ([id], [name]) VALUES ('ch', 'чаморо');
INSERT INTO [country] ([id], [name]) VALUES ('cmc', 'чамски');
INSERT INTO [country] ([id], [name]) VALUES ('ce', 'чеченски');
INSERT INTO [country] ([id], [name]) VALUES ('cs', 'чешки');
INSERT INTO [country] ([id], [name]) VALUES ('chy', 'чејенски');
INSERT INTO [country] ([id], [name]) VALUES ('chb', 'чибча');
INSERT INTO [country] ([id], [name]) VALUES ('chp', 'чипујан');
INSERT INTO [country] ([id], [name]) VALUES ('chr', 'чироки');
INSERT INTO [country] ([id], [name]) VALUES ('cho', 'чокто');
INSERT INTO [country] ([id], [name]) VALUES ('cv', 'чувашки');
INSERT INTO [country] ([id], [name]) VALUES ('chk', 'чуук');
INSERT INTO [country] ([id], [name]) VALUES ('shn', 'шан');
INSERT INTO [country] ([id], [name]) VALUES ('gsw', 'швајцарско германски');
INSERT INTO [country] ([id], [name]) VALUES ('sv', 'шведски');
INSERT INTO [country] ([id], [name]) VALUES ('gd', 'шкотско галски');
INSERT INTO [country] ([id], [name]) VALUES ('sn', 'шона');
INSERT INTO [country] ([id], [name]) VALUES ('es', 'шпански');
INSERT INTO [country] ([id], [name]) VALUES ('es_419', 'шпански (во Латинска Америка)');
INSERT INTO [country] ([id], [name]) VALUES ('es_ES', 'шпански (во Португалија)');
INSERT INTO [country] ([id], [name]) VALUES ('jv', 'јавански');
INSERT INTO [country] ([id], [name]) VALUES ('sah', 'јакутски');
INSERT INTO [country] ([id], [name]) VALUES ('yao', 'јао');
INSERT INTO [country] ([id], [name]) VALUES ('yap', 'јапезе');
INSERT INTO [country] ([id], [name]) VALUES ('ja', 'јапонски');
INSERT INTO [country] ([id], [name]) VALUES ('yi', 'јидски');
INSERT INTO [country] ([id], [name]) VALUES ('yo', 'јоруба');
INSERT INTO [country] ([id], [name]) VALUES ('alt', 'јужен алтај');
INSERT INTO [country] ([id], [name]) VALUES ('nr', 'јужен ндебелески');
INSERT INTO [country] ([id], [name]) VALUES ('sma', 'јужен сами');
INSERT INTO [country] ([id], [name]) VALUES ('sai', 'јужноамерикански индијански');
INSERT INTO [country] ([id], [name]) VALUES ('ypk', 'јуписки јазици');
INSERT INTO [country] ([id], [name]) VALUES ('nym', 'њамвези');
INSERT INTO [country] ([id], [name]) VALUES ('nyn', 'њанколе');
INSERT INTO [country] ([id], [name]) VALUES ('tog', 'њаса тонга');
INSERT INTO [country] ([id], [name]) VALUES ('ny', 'њања');
INSERT INTO [country] ([id], [name]) VALUES ('nyo', 'њоро');
INSERT INTO [country] ([id], [name]) VALUES ('dz', 'џонга');
INSERT INTO [country] ([id], [name]) VALUES ('dyu', 'џула');
