CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('ab', 'abhaščina');
INSERT INTO "country" ("id", "name") VALUES ('ada', 'adangmejščina');
INSERT INTO "country" ("id", "name") VALUES ('ady', 'adigejščina');
INSERT INTO "country" ("id", "name") VALUES ('aa', 'afarščina');
INSERT INTO "country" ("id", "name") VALUES ('afh', 'afrihili');
INSERT INTO "country" ("id", "name") VALUES ('af', 'afrikanščina');
INSERT INTO "country" ("id", "name") VALUES ('afa', 'afroazijski jezik');
INSERT INTO "country" ("id", "name") VALUES ('ain', 'ainujščina');
INSERT INTO "country" ("id", "name") VALUES ('ay', 'ajmarščina');
INSERT INTO "country" ("id", "name") VALUES ('akk', 'akadščina');
INSERT INTO "country" ("id", "name") VALUES ('ak', 'akanščina');
INSERT INTO "country" ("id", "name") VALUES ('sq', 'albanščina');
INSERT INTO "country" ("id", "name") VALUES ('ale', 'aleutščina');
INSERT INTO "country" ("id", "name") VALUES ('alg', 'algonkinski jezik');
INSERT INTO "country" ("id", "name") VALUES ('tut', 'altajski jezik');
INSERT INTO "country" ("id", "name") VALUES ('am', 'amharščina');
INSERT INTO "country" ("id", "name") VALUES ('oj', 'anašinabščina');
INSERT INTO "country" ("id", "name") VALUES ('anp', 'angikaščina');
INSERT INTO "country" ("id", "name") VALUES ('cpe', 'angleška kreolščina ali pidžinščina');
INSERT INTO "country" ("id", "name") VALUES ('en', 'angleščina');
INSERT INTO "country" ("id", "name") VALUES ('en_GB', 'angleščina (VB)');
INSERT INTO "country" ("id", "name") VALUES ('en_US', 'angleščina (ZDA)');
INSERT INTO "country" ("id", "name") VALUES ('apa', 'apaški jezik');
INSERT INTO "country" ("id", "name") VALUES ('ar', 'arabščina');
INSERT INTO "country" ("id", "name") VALUES ('an', 'aragonščina');
INSERT INTO "country" ("id", "name") VALUES ('arc', 'aramejščina');
INSERT INTO "country" ("id", "name") VALUES ('arp', 'arapaščina');
INSERT INTO "country" ("id", "name") VALUES ('arw', 'aravaščina');
INSERT INTO "country" ("id", "name") VALUES ('arn', 'aravkanščina');
INSERT INTO "country" ("id", "name") VALUES ('hy', 'armenščina');
INSERT INTO "country" ("id", "name") VALUES ('rup', 'aromunščina');
INSERT INTO "country" ("id", "name") VALUES ('as', 'asamščina');
INSERT INTO "country" ("id", "name") VALUES ('ast', 'asturijščina');
INSERT INTO "country" ("id", "name") VALUES ('ath', 'atabaški jezik');
INSERT INTO "country" ("id", "name") VALUES ('awa', 'avadščina');
INSERT INTO "country" ("id", "name") VALUES ('av', 'avarščina');
INSERT INTO "country" ("id", "name") VALUES ('ae', 'avestijščina');
INSERT INTO "country" ("id", "name") VALUES ('aus', 'avstralski jezik');
INSERT INTO "country" ("id", "name") VALUES ('map', 'avstronezijski jezik');
INSERT INTO "country" ("id", "name") VALUES ('az', 'azerbajdžanščina');
INSERT INTO "country" ("id", "name") VALUES ('ace', 'ačejščina');
INSERT INTO "country" ("id", "name") VALUES ('ach', 'ačolijščina');
INSERT INTO "country" ("id", "name") VALUES ('ban', 'balijščina');
INSERT INTO "country" ("id", "name") VALUES ('bat', 'baltski jezik');
INSERT INTO "country" ("id", "name") VALUES ('bm', 'bambarščina');
INSERT INTO "country" ("id", "name") VALUES ('bai', 'bamilekejski jezik');
INSERT INTO "country" ("id", "name") VALUES ('bad', 'bandaški jezik');
INSERT INTO "country" ("id", "name") VALUES ('bnt', 'bantujščina');
INSERT INTO "country" ("id", "name") VALUES ('bas', 'basa');
INSERT INTO "country" ("id", "name") VALUES ('eu', 'baskovščina');
INSERT INTO "country" ("id", "name") VALUES ('btk', 'bataški jezik');
INSERT INTO "country" ("id", "name") VALUES ('ba', 'baškirščina');
INSERT INTO "country" ("id", "name") VALUES ('bej', 'bedža');
INSERT INTO "country" ("id", "name") VALUES ('be', 'beloruščina');
INSERT INTO "country" ("id", "name") VALUES ('bal', 'beludžijščina');
INSERT INTO "country" ("id", "name") VALUES ('bem', 'bemba');
INSERT INTO "country" ("id", "name") VALUES ('bn', 'bengalščina');
INSERT INTO "country" ("id", "name") VALUES ('ber', 'berberščina');
INSERT INTO "country" ("id", "name") VALUES ('bh', 'biharščina');
INSERT INTO "country" ("id", "name") VALUES ('bik', 'bikolski jezik');
INSERT INTO "country" ("id", "name") VALUES ('bi', 'bislamščina');
INSERT INTO "country" ("id", "name") VALUES ('byn', 'blinščina');
INSERT INTO "country" ("id", "name") VALUES ('bho', 'bodžpuri');
INSERT INTO "country" ("id", "name") VALUES ('bg', 'bolgarščina');
INSERT INTO "country" ("id", "name") VALUES ('bs', 'bosanščina');
INSERT INTO "country" ("id", "name") VALUES ('bra', 'bradžbakanščina');
INSERT INTO "country" ("id", "name") VALUES ('pt_BR', 'brazilska portugalščina');
INSERT INTO "country" ("id", "name") VALUES ('br', 'bretonščina');
INSERT INTO "country" ("id", "name") VALUES ('zxx', 'brez jezikoslovne vsebine');
INSERT INTO "country" ("id", "name") VALUES ('bug', 'buginščina');
INSERT INTO "country" ("id", "name") VALUES ('bua', 'burjatščina');
INSERT INTO "country" ("id", "name") VALUES ('my', 'burmanščina');
INSERT INTO "country" ("id", "name") VALUES ('cmc', 'camski jezik');
INSERT INTO "country" ("id", "name") VALUES ('tn', 'cvanščina');
INSERT INTO "country" ("id", "name") VALUES ('day', 'dajaščina');
INSERT INTO "country" ("id", "name") VALUES ('dak', 'dakotščina');
INSERT INTO "country" ("id", "name") VALUES ('da', 'danščina');
INSERT INTO "country" ("id", "name") VALUES ('dar', 'darginščina');
INSERT INTO "country" ("id", "name") VALUES ('del', 'delavarščina');
INSERT INTO "country" ("id", "name") VALUES ('din', 'dinka');
INSERT INTO "country" ("id", "name") VALUES ('dyu', 'diula');
INSERT INTO "country" ("id", "name") VALUES ('dv', 'diveščina');
INSERT INTO "country" ("id", "name") VALUES ('doi', 'dogri');
INSERT INTO "country" ("id", "name") VALUES ('dgr', 'dogrib');
INSERT INTO "country" ("id", "name") VALUES ('dsb', 'dolnja lužiška srbščina');
INSERT INTO "country" ("id", "name") VALUES ('dra', 'dravidski jezik');
INSERT INTO "country" ("id", "name") VALUES ('mis', 'drugi jeziki');
INSERT INTO "country" ("id", "name") VALUES ('dua', 'duala');
INSERT INTO "country" ("id", "name") VALUES ('dz', 'dzonka');
INSERT INTO "country" ("id", "name") VALUES ('bin', 'edo');
INSERT INTO "country" ("id", "name") VALUES ('efi', 'efiščina');
INSERT INTO "country" ("id", "name") VALUES ('eka', 'ekajuk');
INSERT INTO "country" ("id", "name") VALUES ('elx', 'elamščina');
INSERT INTO "country" ("id", "name") VALUES ('myv', 'erzjanščina');
INSERT INTO "country" ("id", "name") VALUES ('eo', 'esperanto');
INSERT INTO "country" ("id", "name") VALUES ('et', 'estonščina');
INSERT INTO "country" ("id", "name") VALUES ('gez', 'etiopščina');
INSERT INTO "country" ("id", "name") VALUES ('ee', 'evenščina');
INSERT INTO "country" ("id", "name") VALUES ('ewo', 'evondovščina');
INSERT INTO "country" ("id", "name") VALUES ('fan', 'fangijščina');
INSERT INTO "country" ("id", "name") VALUES ('fat', 'fantijščina');
INSERT INTO "country" ("id", "name") VALUES ('phn', 'feničanščina');
INSERT INTO "country" ("id", "name") VALUES ('fo', 'ferščina');
INSERT INTO "country" ("id", "name") VALUES ('fj', 'fidžijščina');
INSERT INTO "country" ("id", "name") VALUES ('phi', 'filipinski jezik');
INSERT INTO "country" ("id", "name") VALUES ('fil', 'filipinščina');
INSERT INTO "country" ("id", "name") VALUES ('fi', 'finščina');
INSERT INTO "country" ("id", "name") VALUES ('nl_BE', 'flamščina');
INSERT INTO "country" ("id", "name") VALUES ('fon', 'fonščina');
INSERT INTO "country" ("id", "name") VALUES ('cpf', 'francoska kreolščina ali pidžinščina');
INSERT INTO "country" ("id", "name") VALUES ('fr', 'francoščina');
INSERT INTO "country" ("id", "name") VALUES ('fy', 'frizijščina');
INSERT INTO "country" ("id", "name") VALUES ('ff', 'fulščina');
INSERT INTO "country" ("id", "name") VALUES ('fur', 'furlanščina');
INSERT INTO "country" ("id", "name") VALUES ('gaa', 'ga');
INSERT INTO "country" ("id", "name") VALUES ('gay', 'gajščina');
INSERT INTO "country" ("id", "name") VALUES ('gl', 'galicijščina');
INSERT INTO "country" ("id", "name") VALUES ('lg', 'ganda');
INSERT INTO "country" ("id", "name") VALUES ('gba', 'gbajščina');
INSERT INTO "country" ("id", "name") VALUES ('gem', 'germanski jezik');
INSERT INTO "country" ("id", "name") VALUES ('gon', 'gondi');
INSERT INTO "country" ("id", "name") VALUES ('hsb', 'gornja lužiška srbščina');
INSERT INTO "country" ("id", "name") VALUES ('gor', 'gorontalščina');
INSERT INTO "country" ("id", "name") VALUES ('got', 'gotščina');
INSERT INTO "country" ("id", "name") VALUES ('grb', 'grebščina');
INSERT INTO "country" ("id", "name") VALUES ('kl', 'grenlandščina');
INSERT INTO "country" ("id", "name") VALUES ('ka', 'gruzinščina');
INSERT INTO "country" ("id", "name") VALUES ('el', 'grščina');
INSERT INTO "country" ("id", "name") VALUES ('gu', 'gudžaratščina');
INSERT INTO "country" ("id", "name") VALUES ('gn', 'gvaranijščina');
INSERT INTO "country" ("id", "name") VALUES ('gwi', 'gwi');
INSERT INTO "country" ("id", "name") VALUES ('hai', 'haidščina');
INSERT INTO "country" ("id", "name") VALUES ('ht', 'haitijska kreolščina');
INSERT INTO "country" ("id", "name") VALUES ('haw', 'havajščina');
INSERT INTO "country" ("id", "name") VALUES ('ha', 'havščina');
INSERT INTO "country" ("id", "name") VALUES ('he', 'hebrejščina');
INSERT INTO "country" ("id", "name") VALUES ('hz', 'herero');
INSERT INTO "country" ("id", "name") VALUES ('hit', 'hetitščina');
INSERT INTO "country" ("id", "name") VALUES ('hil', 'hiligajnonščina');
INSERT INTO "country" ("id", "name") VALUES ('him', 'himačalščina');
INSERT INTO "country" ("id", "name") VALUES ('hi', 'hindujščina');
INSERT INTO "country" ("id", "name") VALUES ('ho', 'hiri motu');
INSERT INTO "country" ("id", "name") VALUES ('hmn', 'hmonščina');
INSERT INTO "country" ("id", "name") VALUES ('hr', 'hrvaščina');
INSERT INTO "country" ("id", "name") VALUES ('hup', 'hupa');
INSERT INTO "country" ("id", "name") VALUES ('iba', 'ibanščina');
INSERT INTO "country" ("id", "name") VALUES ('pt_PT', 'iberska portugalščina');
INSERT INTO "country" ("id", "name") VALUES ('es_ES', 'iberska španščina');
INSERT INTO "country" ("id", "name") VALUES ('io', 'ido');
INSERT INTO "country" ("id", "name") VALUES ('ig', 'igboščina');
INSERT INTO "country" ("id", "name") VALUES ('ii', 'ii');
INSERT INTO "country" ("id", "name") VALUES ('ijo', 'ijo');
INSERT INTO "country" ("id", "name") VALUES ('ilo', 'ilokanščina');
INSERT INTO "country" ("id", "name") VALUES ('smn', 'inarska samijščina');
INSERT INTO "country" ("id", "name") VALUES ('inc', 'indijski jezik');
INSERT INTO "country" ("id", "name") VALUES ('ine', 'indoevropski jezik');
INSERT INTO "country" ("id", "name") VALUES ('id', 'indonezijščina');
INSERT INTO "country" ("id", "name") VALUES ('inh', 'inguščina');
INSERT INTO "country" ("id", "name") VALUES ('ia', 'interlingva');
INSERT INTO "country" ("id", "name") VALUES ('ie', 'interlingve');
INSERT INTO "country" ("id", "name") VALUES ('iu', 'inuktitutščina');
INSERT INTO "country" ("id", "name") VALUES ('ik', 'inupiaščina');
INSERT INTO "country" ("id", "name") VALUES ('ira', 'iranski jezik');
INSERT INTO "country" ("id", "name") VALUES ('iro', 'irokeški jezik');
INSERT INTO "country" ("id", "name") VALUES ('ga', 'irščina');
INSERT INTO "country" ("id", "name") VALUES ('is', 'islandščina');
INSERT INTO "country" ("id", "name") VALUES ('it', 'italijanščina');
INSERT INTO "country" ("id", "name") VALUES ('sah', 'jakutščina');
INSERT INTO "country" ("id", "name") VALUES ('yao', 'jaojščina');
INSERT INTO "country" ("id", "name") VALUES ('ja', 'japonščina');
INSERT INTO "country" ("id", "name") VALUES ('yap', 'japščina');
INSERT INTO "country" ("id", "name") VALUES ('jv', 'javanščina');
INSERT INTO "country" ("id", "name") VALUES ('kro', 'jezik kru');
INSERT INTO "country" ("id", "name") VALUES ('yi', 'jidiš');
INSERT INTO "country" ("id", "name") VALUES ('yo', 'jorubščina');
INSERT INTO "country" ("id", "name") VALUES ('jrb', 'judovska arabščina');
INSERT INTO "country" ("id", "name") VALUES ('jpr', 'judovska perzijščina');
INSERT INTO "country" ("id", "name") VALUES ('ypk', 'jupiški jezik');
INSERT INTO "country" ("id", "name") VALUES ('alt', 'južna altajščina');
INSERT INTO "country" ("id", "name") VALUES ('nr', 'južna ndebelščina');
INSERT INTO "country" ("id", "name") VALUES ('sma', 'južna samijščina');
INSERT INTO "country" ("id", "name") VALUES ('kbd', 'kabardinščina');
INSERT INTO "country" ("id", "name") VALUES ('kab', 'kabilščina');
INSERT INTO "country" ("id", "name") VALUES ('cad', 'kadoščina');
INSERT INTO "country" ("id", "name") VALUES ('kaj', 'kaj');
INSERT INTO "country" ("id", "name") VALUES ('xal', 'kalmiščina');
INSERT INTO "country" ("id", "name") VALUES ('kam', 'kamba');
INSERT INTO "country" ("id", "name") VALUES ('kn', 'kanada');
INSERT INTO "country" ("id", "name") VALUES ('kr', 'kanurščina');
INSERT INTO "country" ("id", "name") VALUES ('kaa', 'karakalpaščina');
INSERT INTO "country" ("id", "name") VALUES ('krc', 'karačaj-balkarščina');
INSERT INTO "country" ("id", "name") VALUES ('krl', 'karelščina');
INSERT INTO "country" ("id", "name") VALUES ('kar', 'karenščina');
INSERT INTO "country" ("id", "name") VALUES ('car', 'karibski jezik');
INSERT INTO "country" ("id", "name") VALUES ('kha', 'kasi');
INSERT INTO "country" ("id", "name") VALUES ('ca', 'katalonščina');
INSERT INTO "country" ("id", "name") VALUES ('kaw', 'kavi');
INSERT INTO "country" ("id", "name") VALUES ('cau', 'kavkaški jezik');
INSERT INTO "country" ("id", "name") VALUES ('kk', 'kazaščina');
INSERT INTO "country" ("id", "name") VALUES ('kac', 'kačinščina');
INSERT INTO "country" ("id", "name") VALUES ('ks', 'kašmirščina');
INSERT INTO "country" ("id", "name") VALUES ('csb', 'kašubščina');
INSERT INTO "country" ("id", "name") VALUES ('cel', 'keltski jezik');
INSERT INTO "country" ("id", "name") VALUES ('qu', 'kečuanščina');
INSERT INTO "country" ("id", "name") VALUES ('kfo', 'kfo');
INSERT INTO "country" ("id", "name") VALUES ('ki', 'kikujščina');
INSERT INTO "country" ("id", "name") VALUES ('kmb', 'kimbundu');
INSERT INTO "country" ("id", "name") VALUES ('ky', 'kirgiščina');
INSERT INTO "country" ("id", "name") VALUES ('gil', 'kiribatščina');
INSERT INTO "country" ("id", "name") VALUES ('sit', 'kitajsko-tibetanski jezik');
INSERT INTO "country" ("id", "name") VALUES ('zh', 'kitajščina');
INSERT INTO "country" ("id", "name") VALUES ('nwc', 'klasična nevarščina');
INSERT INTO "country" ("id", "name") VALUES ('syc', 'klasična sirščina');
INSERT INTO "country" ("id", "name") VALUES ('tlh', 'klingonščina');
INSERT INTO "country" ("id", "name") VALUES ('km', 'kmerščina');
INSERT INTO "country" ("id", "name") VALUES ('nb', 'knjižna norveščina');
INSERT INTO "country" ("id", "name") VALUES ('khi', 'koisanski jezik');
INSERT INTO "country" ("id", "name") VALUES ('kv', 'komijščina');
INSERT INTO "country" ("id", "name") VALUES ('kg', 'kongovščina');
INSERT INTO "country" ("id", "name") VALUES ('kok', 'konkanščina');
INSERT INTO "country" ("id", "name") VALUES ('cop', 'koptščina');
INSERT INTO "country" ("id", "name") VALUES ('ko', 'korejščina');
INSERT INTO "country" ("id", "name") VALUES ('kw', 'kornijščina');
INSERT INTO "country" ("id", "name") VALUES ('co', 'korziščina');
INSERT INTO "country" ("id", "name") VALUES ('kos', 'kosrajščina');
INSERT INTO "country" ("id", "name") VALUES ('mno', 'kotabatski manobo');
INSERT INTO "country" ("id", "name") VALUES ('kho', 'kotanščina');
INSERT INTO "country" ("id", "name") VALUES ('kpe', 'kpelejščina');
INSERT INTO "country" ("id", "name") VALUES ('crp', 'kreolščina ali pidžinščina');
INSERT INTO "country" ("id", "name") VALUES ('cr', 'krijščina');
INSERT INTO "country" ("id", "name") VALUES ('crh', 'krimska tatarščina');
INSERT INTO "country" ("id", "name") VALUES ('kum', 'kumiščina');
INSERT INTO "country" ("id", "name") VALUES ('ku', 'kurdščina');
INSERT INTO "country" ("id", "name") VALUES ('kru', 'kuruk');
INSERT INTO "country" ("id", "name") VALUES ('kut', 'kutenajščina');
INSERT INTO "country" ("id", "name") VALUES ('cus', 'kušitščina');
INSERT INTO "country" ("id", "name") VALUES ('kj', 'kvanjama');
INSERT INTO "country" ("id", "name") VALUES ('lad', 'ladinščina');
INSERT INTO "country" ("id", "name") VALUES ('lam', 'lamba');
INSERT INTO "country" ("id", "name") VALUES ('lah', 'landa');
INSERT INTO "country" ("id", "name") VALUES ('lo', 'laoščina');
INSERT INTO "country" ("id", "name") VALUES ('es_419', 'latinskoameriška španščina');
INSERT INTO "country" ("id", "name") VALUES ('la', 'latinščina');
INSERT INTO "country" ("id", "name") VALUES ('lv', 'latvijščina');
INSERT INTO "country" ("id", "name") VALUES ('lez', 'lezginščina');
INSERT INTO "country" ("id", "name") VALUES ('li', 'limburščina');
INSERT INTO "country" ("id", "name") VALUES ('ln', 'lingala');
INSERT INTO "country" ("id", "name") VALUES ('lt', 'litovščina');
INSERT INTO "country" ("id", "name") VALUES ('jbo', 'lojban');
INSERT INTO "country" ("id", "name") VALUES ('loz', 'lozi');
INSERT INTO "country" ("id", "name") VALUES ('lu', 'luba-katanga');
INSERT INTO "country" ("id", "name") VALUES ('lua', 'luba-lulua');
INSERT INTO "country" ("id", "name") VALUES ('lui', 'luisenščina');
INSERT INTO "country" ("id", "name") VALUES ('lb', 'luksemburščina');
INSERT INTO "country" ("id", "name") VALUES ('smj', 'luleška samijščina');
INSERT INTO "country" ("id", "name") VALUES ('lun', 'lunda');
INSERT INTO "country" ("id", "name") VALUES ('luo', 'luo');
INSERT INTO "country" ("id", "name") VALUES ('lus', 'lushai');
INSERT INTO "country" ("id", "name") VALUES ('wen', 'lužiško srbski jezik');
INSERT INTO "country" ("id", "name") VALUES ('mad', 'madurščina');
INSERT INTO "country" ("id", "name") VALUES ('hu', 'madžarščina');
INSERT INTO "country" ("id", "name") VALUES ('mag', 'magadščina');
INSERT INTO "country" ("id", "name") VALUES ('mai', 'maitili');
INSERT INTO "country" ("id", "name") VALUES ('myn', 'majevski jezik');
INSERT INTO "country" ("id", "name") VALUES ('mak', 'makasarščina');
INSERT INTO "country" ("id", "name") VALUES ('mk', 'makedonščina');
INSERT INTO "country" ("id", "name") VALUES ('mg', 'malagaščina');
INSERT INTO "country" ("id", "name") VALUES ('ml', 'malajalamščina');
INSERT INTO "country" ("id", "name") VALUES ('ms', 'malajščina');
INSERT INTO "country" ("id", "name") VALUES ('tog', 'malavijska tongščina');
INSERT INTO "country" ("id", "name") VALUES ('mt', 'malteščina');
INSERT INTO "country" ("id", "name") VALUES ('mdr', 'mandarščina');
INSERT INTO "country" ("id", "name") VALUES ('man', 'mandingo');
INSERT INTO "country" ("id", "name") VALUES ('mnc', 'mandžurščina');
INSERT INTO "country" ("id", "name") VALUES ('mni', 'manipurščina');
INSERT INTO "country" ("id", "name") VALUES ('gv', 'manščina');
INSERT INTO "country" ("id", "name") VALUES ('mi', 'maorščina');
INSERT INTO "country" ("id", "name") VALUES ('mr', 'maratščina');
INSERT INTO "country" ("id", "name") VALUES ('chm', 'marijščina');
INSERT INTO "country" ("id", "name") VALUES ('mh', 'marshallovščina');
INSERT INTO "country" ("id", "name") VALUES ('mwr', 'marvarščina');
INSERT INTO "country" ("id", "name") VALUES ('mas', 'masajščina');
INSERT INTO "country" ("id", "name") VALUES ('men', 'mende');
INSERT INTO "country" ("id", "name") VALUES ('mic', 'mikmaščina');
INSERT INTO "country" ("id", "name") VALUES ('min', 'minangkabau');
INSERT INTO "country" ("id", "name") VALUES ('mwl', 'mirandeščina');
INSERT INTO "country" ("id", "name") VALUES ('moh', 'mohoščina');
INSERT INTO "country" ("id", "name") VALUES ('mdf', 'mokšavščina');
INSERT INTO "country" ("id", "name") VALUES ('mo', 'moldavščina');
INSERT INTO "country" ("id", "name") VALUES ('lol', 'mongo');
INSERT INTO "country" ("id", "name") VALUES ('mn', 'mongolščina');
INSERT INTO "country" ("id", "name") VALUES ('mkh', 'monsko-kmerski jezik');
INSERT INTO "country" ("id", "name") VALUES ('mos', 'mosijščina');
INSERT INTO "country" ("id", "name") VALUES ('mun', 'mundski jezik');
INSERT INTO "country" ("id", "name") VALUES ('mus', 'mus');
INSERT INTO "country" ("id", "name") VALUES ('nah', 'nahuatl');
INSERT INTO "country" ("id", "name") VALUES ('nap', 'napolitanščina');
INSERT INTO "country" ("id", "name") VALUES ('na', 'naurujščina');
INSERT INTO "country" ("id", "name") VALUES ('nv', 'navajščina');
INSERT INTO "country" ("id", "name") VALUES ('de', 'nemščina');
INSERT INTO "country" ("id", "name") VALUES ('gsw', 'nemščina (Švica)');
INSERT INTO "country" ("id", "name") VALUES ('ne', 'nepalščina');
INSERT INTO "country" ("id", "name") VALUES ('new', 'nevarščina');
INSERT INTO "country" ("id", "name") VALUES ('und', 'neznan ali neveljaven jezik');
INSERT INTO "country" ("id", "name") VALUES ('ng', 'ng');
INSERT INTO "country" ("id", "name") VALUES ('nia', 'niaščina');
INSERT INTO "country" ("id", "name") VALUES ('nic', 'nigrsko-kordofanski jezik');
INSERT INTO "country" ("id", "name") VALUES ('ssa', 'nilsko-saharski jezik');
INSERT INTO "country" ("id", "name") VALUES ('niu', 'niuejščina');
INSERT INTO "country" ("id", "name") VALUES ('nds', 'nizka nemščina');
INSERT INTO "country" ("id", "name") VALUES ('nl', 'nizozemščina');
INSERT INTO "country" ("id", "name") VALUES ('nym', 'njamveščina');
INSERT INTO "country" ("id", "name") VALUES ('nyn', 'njankole');
INSERT INTO "country" ("id", "name") VALUES ('ny', 'njanščina');
INSERT INTO "country" ("id", "name") VALUES ('nyo', 'njoro');
INSERT INTO "country" ("id", "name") VALUES ('nog', 'nogajščina');
INSERT INTO "country" ("id", "name") VALUES ('no', 'norveščina');
INSERT INTO "country" ("id", "name") VALUES ('nn', 'novonorveščina');
INSERT INTO "country" ("id", "name") VALUES ('nqo', 'nqo');
INSERT INTO "country" ("id", "name") VALUES ('nub', 'nubijski jezik');
INSERT INTO "country" ("id", "name") VALUES ('nzi', 'nzima');
INSERT INTO "country" ("id", "name") VALUES ('oc', 'okcitanščina');
INSERT INTO "country" ("id", "name") VALUES ('or', 'orijščina');
INSERT INTO "country" ("id", "name") VALUES ('om', 'oromo');
INSERT INTO "country" ("id", "name") VALUES ('osa', 'osage');
INSERT INTO "country" ("id", "name") VALUES ('os', 'osetinščina');
INSERT INTO "country" ("id", "name") VALUES ('ota', 'otomanska turščina');
INSERT INTO "country" ("id", "name") VALUES ('oto', 'otomijski jezik');
INSERT INTO "country" ("id", "name") VALUES ('pal', 'pal');
INSERT INTO "country" ("id", "name") VALUES ('pau', 'palavanščina');
INSERT INTO "country" ("id", "name") VALUES ('pi', 'palijščina');
INSERT INTO "country" ("id", "name") VALUES ('pam', 'pampanščina');
INSERT INTO "country" ("id", "name") VALUES ('pa', 'pandžabščina');
INSERT INTO "country" ("id", "name") VALUES ('pag', 'pangasinanščina');
INSERT INTO "country" ("id", "name") VALUES ('pap', 'papiamentu');
INSERT INTO "country" ("id", "name") VALUES ('paa', 'papuanski jezik');
INSERT INTO "country" ("id", "name") VALUES ('ps', 'paštu');
INSERT INTO "country" ("id", "name") VALUES ('fa', 'perzijščina');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hans', 'poenostavljena kitajščina');
INSERT INTO "country" ("id", "name") VALUES ('pl', 'poljščina');
INSERT INTO "country" ("id", "name") VALUES ('pon', 'ponpejščina');
INSERT INTO "country" ("id", "name") VALUES ('cpp', 'portugalska kreolščina ali pidžinščina');
INSERT INTO "country" ("id", "name") VALUES ('pt', 'portugalščina');
INSERT INTO "country" ("id", "name") VALUES ('pra', 'prakritski jezik');
INSERT INTO "country" ("id", "name") VALUES ('raj', 'radžastanščina');
INSERT INTO "country" ("id", "name") VALUES ('rap', 'rapanujščina');
INSERT INTO "country" ("id", "name") VALUES ('rar', 'rarotongščina');
INSERT INTO "country" ("id", "name") VALUES ('rm', 'retoromanščina');
INSERT INTO "country" ("id", "name") VALUES ('roa', 'romanski jezik');
INSERT INTO "country" ("id", "name") VALUES ('ro', 'romunščina');
INSERT INTO "country" ("id", "name") VALUES ('rom', 'romščina');
INSERT INTO "country" ("id", "name") VALUES ('root', 'root');
INSERT INTO "country" ("id", "name") VALUES ('rw', 'ruandščina');
INSERT INTO "country" ("id", "name") VALUES ('rn', 'rundščina');
INSERT INTO "country" ("id", "name") VALUES ('ru', 'ruščina');
INSERT INTO "country" ("id", "name") VALUES ('sad', 'sad');
INSERT INTO "country" ("id", "name") VALUES ('sai', 'sai');
INSERT INTO "country" ("id", "name") VALUES ('sal', 'sal');
INSERT INTO "country" ("id", "name") VALUES ('sam', 'samaritanska aramejščina');
INSERT INTO "country" ("id", "name") VALUES ('smi', 'samijski jezik');
INSERT INTO "country" ("id", "name") VALUES ('sms', 'samijščina Skolt');
INSERT INTO "country" ("id", "name") VALUES ('sm', 'samoanščina');
INSERT INTO "country" ("id", "name") VALUES ('sg', 'sango');
INSERT INTO "country" ("id", "name") VALUES ('sa', 'sanskrt');
INSERT INTO "country" ("id", "name") VALUES ('sat', 'santalščina');
INSERT INTO "country" ("id", "name") VALUES ('sc', 'sardinščina');
INSERT INTO "country" ("id", "name") VALUES ('sas', 'sasaščina');
INSERT INTO "country" ("id", "name") VALUES ('ceb', 'sebuanščina');
INSERT INTO "country" ("id", "name") VALUES ('sel', 'selkupščina');
INSERT INTO "country" ("id", "name") VALUES ('sem', 'semitski jezik');
INSERT INTO "country" ("id", "name") VALUES ('srr', 'sererščina');
INSERT INTO "country" ("id", "name") VALUES ('st', 'sesoto');
INSERT INTO "country" ("id", "name") VALUES ('frr', 'severna frizijščina');
INSERT INTO "country" ("id", "name") VALUES ('nd', 'severna ndebelščina');
INSERT INTO "country" ("id", "name") VALUES ('se', 'severna samijščina');
INSERT INTO "country" ("id", "name") VALUES ('nso', 'severna sotščina');
INSERT INTO "country" ("id", "name") VALUES ('nai', 'severnoameriški indijanski jezik');
INSERT INTO "country" ("id", "name") VALUES ('scn', 'sicilijanščina');
INSERT INTO "country" ("id", "name") VALUES ('sid', 'sidamščina');
INSERT INTO "country" ("id", "name") VALUES ('sio', 'sijuščina');
INSERT INTO "country" ("id", "name") VALUES ('bla', 'siksika');
INSERT INTO "country" ("id", "name") VALUES ('sd', 'sindščina');
INSERT INTO "country" ("id", "name") VALUES ('si', 'singalščina');
INSERT INTO "country" ("id", "name") VALUES ('syr', 'sirščina');
INSERT INTO "country" ("id", "name") VALUES ('den', 'slavejščina');
INSERT INTO "country" ("id", "name") VALUES ('sla', 'slovanski jezik');
INSERT INTO "country" ("id", "name") VALUES ('sk', 'slovaščina');
INSERT INTO "country" ("id", "name") VALUES ('sl', 'slovenščina');
INSERT INTO "country" ("id", "name") VALUES ('snk', 'snk');
INSERT INTO "country" ("id", "name") VALUES ('sog', 'sog');
INSERT INTO "country" ("id", "name") VALUES ('so', 'somalščina');
INSERT INTO "country" ("id", "name") VALUES ('son', 'songajščina');
INSERT INTO "country" ("id", "name") VALUES ('sh', 'srbohrvaščina');
INSERT INTO "country" ("id", "name") VALUES ('sr', 'srbščina');
INSERT INTO "country" ("id", "name") VALUES ('enm', 'srednja angleščina');
INSERT INTO "country" ("id", "name") VALUES ('frm', 'srednja francoščina');
INSERT INTO "country" ("id", "name") VALUES ('mga', 'srednja irščina');
INSERT INTO "country" ("id", "name") VALUES ('dum', 'srednja nizozemščina');
INSERT INTO "country" ("id", "name") VALUES ('gmh', 'srednja visoka nemščina');
INSERT INTO "country" ("id", "name") VALUES ('cai', 'srednjeameriški indijanski jezik');
INSERT INTO "country" ("id", "name") VALUES ('ang', 'stara angleščina');
INSERT INTO "country" ("id", "name") VALUES ('cu', 'stara cerkvena slovanščina');
INSERT INTO "country" ("id", "name") VALUES ('egy', 'stara egipčanščina');
INSERT INTO "country" ("id", "name") VALUES ('fro', 'stara francoščina');
INSERT INTO "country" ("id", "name") VALUES ('grc', 'stara grščina');
INSERT INTO "country" ("id", "name") VALUES ('sga', 'stara irščina');
INSERT INTO "country" ("id", "name") VALUES ('non', 'stara nordijščina');
INSERT INTO "country" ("id", "name") VALUES ('peo', 'stara perzijščina');
INSERT INTO "country" ("id", "name") VALUES ('pro', 'stara provansalščina');
INSERT INTO "country" ("id", "name") VALUES ('goh', 'stara visoka nemščina');
INSERT INTO "country" ("id", "name") VALUES ('suk', 'sukuma');
INSERT INTO "country" ("id", "name") VALUES ('sux', 'sumerščina');
INSERT INTO "country" ("id", "name") VALUES ('su', 'sundanščina');
INSERT INTO "country" ("id", "name") VALUES ('srn', 'surinamska kreolščina');
INSERT INTO "country" ("id", "name") VALUES ('sus', 'susujščina');
INSERT INTO "country" ("id", "name") VALUES ('sw', 'svahili');
INSERT INTO "country" ("id", "name") VALUES ('ss', 'svazijščina');
INSERT INTO "country" ("id", "name") VALUES ('tg', 'tadžiščina');
INSERT INTO "country" ("id", "name") VALUES ('tl', 'tagalogščina');
INSERT INTO "country" ("id", "name") VALUES ('ty', 'tahitščina');
INSERT INTO "country" ("id", "name") VALUES ('tai', 'tajski jezik');
INSERT INTO "country" ("id", "name") VALUES ('th', 'tajščina');
INSERT INTO "country" ("id", "name") VALUES ('tmh', 'tamajaščina');
INSERT INTO "country" ("id", "name") VALUES ('ta', 'tamilščina');
INSERT INTO "country" ("id", "name") VALUES ('tt', 'tatarščina');
INSERT INTO "country" ("id", "name") VALUES ('te', 'telugijščina');
INSERT INTO "country" ("id", "name") VALUES ('tem', 'temnejščina');
INSERT INTO "country" ("id", "name") VALUES ('ter', 'ter');
INSERT INTO "country" ("id", "name") VALUES ('tet', 'tetumščina');
INSERT INTO "country" ("id", "name") VALUES ('bo', 'tibetanščina');
INSERT INTO "country" ("id", "name") VALUES ('ti', 'tigrajščina');
INSERT INTO "country" ("id", "name") VALUES ('tig', 'tigrejščina');
INSERT INTO "country" ("id", "name") VALUES ('tiv', 'tivščina');
INSERT INTO "country" ("id", "name") VALUES ('kcg', 'tjapska nigerijščina');
INSERT INTO "country" ("id", "name") VALUES ('tli', 'tlingitščina');
INSERT INTO "country" ("id", "name") VALUES ('tpi', 'tok pisin');
INSERT INTO "country" ("id", "name") VALUES ('tkl', 'tokelavščina');
INSERT INTO "country" ("id", "name") VALUES ('to', 'tongščina');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hant', 'tradicionalna kitajščina');
INSERT INTO "country" ("id", "name") VALUES ('chk', 'trukeščina');
INSERT INTO "country" ("id", "name") VALUES ('tsi', 'tsimščina');
INSERT INTO "country" ("id", "name") VALUES ('ts', 'tsonga');
INSERT INTO "country" ("id", "name") VALUES ('tum', 'tumbukščina');
INSERT INTO "country" ("id", "name") VALUES ('tup', 'tupijski jezik');
INSERT INTO "country" ("id", "name") VALUES ('tk', 'turkmenščina');
INSERT INTO "country" ("id", "name") VALUES ('tr', 'turščina');
INSERT INTO "country" ("id", "name") VALUES ('tvl', 'tuvalujščina');
INSERT INTO "country" ("id", "name") VALUES ('tyv', 'tuvinščina');
INSERT INTO "country" ("id", "name") VALUES ('tw', 'tvi');
INSERT INTO "country" ("id", "name") VALUES ('udm', 'udmurtščina');
INSERT INTO "country" ("id", "name") VALUES ('uga', 'ugaritski jezik');
INSERT INTO "country" ("id", "name") VALUES ('fiu', 'ugrofinski jezik');
INSERT INTO "country" ("id", "name") VALUES ('ug', 'ujgurščina');
INSERT INTO "country" ("id", "name") VALUES ('uk', 'ukrajinščina');
INSERT INTO "country" ("id", "name") VALUES ('umb', 'umbundščina');
INSERT INTO "country" ("id", "name") VALUES ('art', 'umetni jezik');
INSERT INTO "country" ("id", "name") VALUES ('ur', 'urdujščina');
INSERT INTO "country" ("id", "name") VALUES ('uz', 'uzbeščina');
INSERT INTO "country" ("id", "name") VALUES ('vai', 'vajščina');
INSERT INTO "country" ("id", "name") VALUES ('wak', 'vakaški jezik');
INSERT INTO "country" ("id", "name") VALUES ('wal', 'valamščina');
INSERT INTO "country" ("id", "name") VALUES ('cy', 'valižanščina');
INSERT INTO "country" ("id", "name") VALUES ('wa', 'valonščina');
INSERT INTO "country" ("id", "name") VALUES ('war', 'varajščina');
INSERT INTO "country" ("id", "name") VALUES ('was', 'vašajščina');
INSERT INTO "country" ("id", "name") VALUES ('ve', 'venda');
INSERT INTO "country" ("id", "name") VALUES ('mul', 'več jezikov');
INSERT INTO "country" ("id", "name") VALUES ('vi', 'vietnamščina');
INSERT INTO "country" ("id", "name") VALUES ('de_CH', 'visoka nemščina (Švica)');
INSERT INTO "country" ("id", "name") VALUES ('vo', 'volapuk');
INSERT INTO "country" ("id", "name") VALUES ('wo', 'volofščina');
INSERT INTO "country" ("id", "name") VALUES ('vot', 'votjaščina');
INSERT INTO "country" ("id", "name") VALUES ('frs', 'vzhodna frizijščina');
INSERT INTO "country" ("id", "name") VALUES ('xh', 'xhosa');
INSERT INTO "country" ("id", "name") VALUES ('za', 'za');
INSERT INTO "country" ("id", "name") VALUES ('znd', 'zandejščina');
INSERT INTO "country" ("id", "name") VALUES ('zap', 'zapoteščina');
INSERT INTO "country" ("id", "name") VALUES ('zza', 'zazajščina');
INSERT INTO "country" ("id", "name") VALUES ('zen', 'zenaščina');
INSERT INTO "country" ("id", "name") VALUES ('sgn', 'znakovni jezik');
INSERT INTO "country" ("id", "name") VALUES ('zbl', 'znakovni jezik Bliss');
INSERT INTO "country" ("id", "name") VALUES ('zu', 'zulujščina');
INSERT INTO "country" ("id", "name") VALUES ('zun', 'zunijščina');
INSERT INTO "country" ("id", "name") VALUES ('chg', 'čagatajščina');
INSERT INTO "country" ("id", "name") VALUES ('ch', 'čamorščina');
INSERT INTO "country" ("id", "name") VALUES ('chy', 'čejenščina');
INSERT INTO "country" ("id", "name") VALUES ('chr', 'čerokeščina');
INSERT INTO "country" ("id", "name") VALUES ('ce', 'čečenščina');
INSERT INTO "country" ("id", "name") VALUES ('cs', 'češčina');
INSERT INTO "country" ("id", "name") VALUES ('chb', 'čibčevščina');
INSERT INTO "country" ("id", "name") VALUES ('chn', 'činuški žargon');
INSERT INTO "country" ("id", "name") VALUES ('chp', 'čipevščina');
INSERT INTO "country" ("id", "name") VALUES ('cho', 'čoktavščina');
INSERT INTO "country" ("id", "name") VALUES ('cv', 'čuvaščina');
INSERT INTO "country" ("id", "name") VALUES ('shn', 'šanščina');
INSERT INTO "country" ("id", "name") VALUES ('gd', 'škotska gelščina');
INSERT INTO "country" ("id", "name") VALUES ('sco', 'škotščina');
INSERT INTO "country" ("id", "name") VALUES ('sn', 'šonščina');
INSERT INTO "country" ("id", "name") VALUES ('es', 'španščina');
INSERT INTO "country" ("id", "name") VALUES ('sv', 'švedščina');
