CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('rom', 'rom');
INSERT INTO `country` (`id`, `name`) VALUES ('es_419', 'أسبانية أمريكا اللاتينية');
INSERT INTO `country` (`id`, `name`) VALUES ('en_US', 'إنجليزية الولايات المتحدة');
INSERT INTO `country` (`id`, `name`) VALUES ('eo', 'اسبرانتو');
INSERT INTO `country` (`id`, `name`) VALUES ('arc', 'الآرامية');
INSERT INTO `country` (`id`, `name`) VALUES ('sam', 'الآرامية السومارية');
INSERT INTO `country` (`id`, `name`) VALUES ('ain', 'الآينوية');
INSERT INTO `country` (`id`, `name`) VALUES ('ab', 'الأبخازية');
INSERT INTO `country` (`id`, `name`) VALUES ('cch', 'الأتسام');
INSERT INTO `country` (`id`, `name`) VALUES ('ace', 'الأتشينيزية');
INSERT INTO `country` (`id`, `name`) VALUES ('ada', 'الأدانجمية');
INSERT INTO `country` (`id`, `name`) VALUES ('udm', 'الأدمرت');
INSERT INTO `country` (`id`, `name`) VALUES ('ady', 'الأديجه');
INSERT INTO `country` (`id`, `name`) VALUES ('az', 'الأذرية');
INSERT INTO `country` (`id`, `name`) VALUES ('arp', 'الأراباهو');
INSERT INTO `country` (`id`, `name`) VALUES ('an', 'الأراجونية');
INSERT INTO `country` (`id`, `name`) VALUES ('arw', 'الأراواكية');
INSERT INTO `country` (`id`, `name`) VALUES ('ur', 'الأردية');
INSERT INTO `country` (`id`, `name`) VALUES ('hy', 'الأرمينية');
INSERT INTO `country` (`id`, `name`) VALUES ('arn', 'الأروكانية');
INSERT INTO `country` (`id`, `name`) VALUES ('rup', 'الأرومانيان');
INSERT INTO `country` (`id`, `name`) VALUES ('as', 'الأسامية');
INSERT INTO `country` (`id`, `name`) VALUES ('es', 'الأسبانية');
INSERT INTO `country` (`id`, `name`) VALUES ('es_ES', 'الأسبانية الأيبيرية');
INSERT INTO `country` (`id`, `name`) VALUES ('ast', 'الأسترية');
INSERT INTO `country` (`id`, `name`) VALUES ('et', 'الأستونية');
INSERT INTO `country` (`id`, `name`) VALUES ('sco', 'الأسكتلندية');
INSERT INTO `country` (`id`, `name`) VALUES ('ug', 'الأغورية');
INSERT INTO `country` (`id`, `name`) VALUES ('aa', 'الأفارية');
INSERT INTO `country` (`id`, `name`) VALUES ('av', 'الأفاريكية');
INSERT INTO `country` (`id`, `name`) VALUES ('af', 'الأفريقية');
INSERT INTO `country` (`id`, `name`) VALUES ('afh', 'الأفريهيلية');
INSERT INTO `country` (`id`, `name`) VALUES ('ae', 'الأفستية');
INSERT INTO `country` (`id`, `name`) VALUES ('akk', 'الأكادية');
INSERT INTO `country` (`id`, `name`) VALUES ('ak', 'الأكانية');
INSERT INTO `country` (`id`, `name`) VALUES ('ach', 'الأكولية');
INSERT INTO `country` (`id`, `name`) VALUES ('sq', 'الألبانية');
INSERT INTO `country` (`id`, `name`) VALUES ('tut', 'الألطائية - أخرى');
INSERT INTO `country` (`id`, `name`) VALUES ('alt', 'الألطائية الجنوبية');
INSERT INTO `country` (`id`, `name`) VALUES ('de', 'الألمانية');
INSERT INTO `country` (`id`, `name`) VALUES ('nds', 'الألمانية السفلى');
INSERT INTO `country` (`id`, `name`) VALUES ('gsw', 'الألمانية السويسرية');
INSERT INTO `country` (`id`, `name`) VALUES ('de_CH', 'الألمانية العليا السويسرية');
INSERT INTO `country` (`id`, `name`) VALUES ('goh', 'الألمانية العليا القديمة');
INSERT INTO `country` (`id`, `name`) VALUES ('gmh', 'الألمانية العليا الوسطى');
INSERT INTO `country` (`id`, `name`) VALUES ('de_AT', 'الألمانية النمساوية');
INSERT INTO `country` (`id`, `name`) VALUES ('ale', 'الأليوتية');
INSERT INTO `country` (`id`, `name`) VALUES ('umb', 'الأمبندو');
INSERT INTO `country` (`id`, `name`) VALUES ('am', 'الأمهرية');
INSERT INTO `country` (`id`, `name`) VALUES ('anp', 'الأنجيكا');
INSERT INTO `country` (`id`, `name`) VALUES ('id', 'الأندونيسية');
INSERT INTO `country` (`id`, `name`) VALUES ('awa', 'الأوادية');
INSERT INTO `country` (`id`, `name`) VALUES ('oj', 'الأوجيبوا');
INSERT INTO `country` (`id`, `name`) VALUES ('om', 'الأورومو');
INSERT INTO `country` (`id`, `name`) VALUES ('or', 'الأورييا');
INSERT INTO `country` (`id`, `name`) VALUES ('osa', 'الأوساج');
INSERT INTO `country` (`id`, `name`) VALUES ('map', 'الأوسترونيسيان');
INSERT INTO `country` (`id`, `name`) VALUES ('os', 'الأوسيتيك');
INSERT INTO `country` (`id`, `name`) VALUES ('uk', 'الأوكرانية');
INSERT INTO `country` (`id`, `name`) VALUES ('oc', 'الأوكيتانية');
INSERT INTO `country` (`id`, `name`) VALUES ('ga', 'الأيرلندية');
INSERT INTO `country` (`id`, `name`) VALUES ('sga', 'الأيرلندية القديمة');
INSERT INTO `country` (`id`, `name`) VALUES ('mga', 'الأيرلندية الوسطى');
INSERT INTO `country` (`id`, `name`) VALUES ('is', 'الأيسلاندية');
INSERT INTO `country` (`id`, `name`) VALUES ('ay', 'الأيمارا');
INSERT INTO `country` (`id`, `name`) VALUES ('en_CA', 'الإنجليزية الكندية');
INSERT INTO `country` (`id`, `name`) VALUES ('lad', 'الاسباعبرية');
INSERT INTO `country` (`id`, `name`) VALUES ('efi', 'الافيك');
INSERT INTO `country` (`id`, `name`) VALUES ('eka', 'الاكاجك');
INSERT INTO `country` (`id`, `name`) VALUES ('elx', 'الامايت');
INSERT INTO `country` (`id`, `name`) VALUES ('ie', 'الانترلينج');
INSERT INTO `country` (`id`, `name`) VALUES ('en', 'الانجليزية');
INSERT INTO `country` (`id`, `name`) VALUES ('en_AU', 'الانجليزية الأسترالية');
INSERT INTO `country` (`id`, `name`) VALUES ('en_GB', 'الانجليزية البريطانية');
INSERT INTO `country` (`id`, `name`) VALUES ('ang', 'الانجليزية القديمة');
INSERT INTO `country` (`id`, `name`) VALUES ('enm', 'الانجليزية الوسطى');
INSERT INTO `country` (`id`, `name`) VALUES ('inh', 'الانجوشية');
INSERT INTO `country` (`id`, `name`) VALUES ('uz', 'الاوزباكية');
INSERT INTO `country` (`id`, `name`) VALUES ('iba', 'الايبان');
INSERT INTO `country` (`id`, `name`) VALUES ('ig', 'الايجبو');
INSERT INTO `country` (`id`, `name`) VALUES ('ijo', 'الايجو');
INSERT INTO `country` (`id`, `name`) VALUES ('io', 'الايدو');
INSERT INTO `country` (`id`, `name`) VALUES ('ira', 'الايرانية');
INSERT INTO `country` (`id`, `name`) VALUES ('it', 'الايطالية');
INSERT INTO `country` (`id`, `name`) VALUES ('ilo', 'الايلوكو');
INSERT INTO `country` (`id`, `name`) VALUES ('smn', 'الاينارى سامى');
INSERT INTO `country` (`id`, `name`) VALUES ('ik', 'الاينبياك');
INSERT INTO `country` (`id`, `name`) VALUES ('iu', 'الاينكتيتت');
INSERT INTO `country` (`id`, `name`) VALUES ('ewo', 'الايوندو');
INSERT INTO `country` (`id`, `name`) VALUES ('ee', 'الايوي');
INSERT INTO `country` (`id`, `name`) VALUES ('pap', 'البابيامينتو');
INSERT INTO `country` (`id`, `name`) VALUES ('btk', 'الباتاكية');
INSERT INTO `country` (`id`, `name`) VALUES ('bas', 'الباسا');
INSERT INTO `country` (`id`, `name`) VALUES ('ba', 'الباشكيرية');
INSERT INTO `country` (`id`, `name`) VALUES ('pau', 'البالوان');
INSERT INTO `country` (`id`, `name`) VALUES ('pi', 'البالية');
INSERT INTO `country` (`id`, `name`) VALUES ('bm', 'البامبارا');
INSERT INTO `country` (`id`, `name`) VALUES ('pam', 'البامبانجا');
INSERT INTO `country` (`id`, `name`) VALUES ('bnt', 'البانتو');
INSERT INTO `country` (`id`, `name`) VALUES ('pag', 'البانجاسينان');
INSERT INTO `country` (`id`, `name`) VALUES ('bad', 'الباندا');
INSERT INTO `country` (`id`, `name`) VALUES ('bug', 'البجينيزية');
INSERT INTO `country` (`id`, `name`) VALUES ('bra', 'البراجية');
INSERT INTO `country` (`id`, `name`) VALUES ('ber', 'البربرية');
INSERT INTO `country` (`id`, `name`) VALUES ('pt', 'البرتغالية');
INSERT INTO `country` (`id`, `name`) VALUES ('pt_PT', 'البرتغالية الأيبيرية');
INSERT INTO `country` (`id`, `name`) VALUES ('pt_BR', 'البرتغالية البرازيلية');
INSERT INTO `country` (`id`, `name`) VALUES ('pro', 'البروفانسية القديمة');
INSERT INTO `country` (`id`, `name`) VALUES ('bua', 'البرياتية');
INSERT INTO `country` (`id`, `name`) VALUES ('br', 'البريتونية');
INSERT INTO `country` (`id`, `name`) VALUES ('ps', 'البشتونية');
INSERT INTO `country` (`id`, `name`) VALUES ('bat', 'البلطيقية - أخرى');
INSERT INTO `country` (`id`, `name`) VALUES ('bg', 'البلغارية');
INSERT INTO `country` (`id`, `name`) VALUES ('bal', 'البلوشية');
INSERT INTO `country` (`id`, `name`) VALUES ('byn', 'البلينية');
INSERT INTO `country` (`id`, `name`) VALUES ('pa', 'البنجابية');
INSERT INTO `country` (`id`, `name`) VALUES ('bn', 'البنغالية');
INSERT INTO `country` (`id`, `name`) VALUES ('pal', 'البهلوية');
INSERT INTO `country` (`id`, `name`) VALUES ('bho', 'البهوجبرية');
INSERT INTO `country` (`id`, `name`) VALUES ('my', 'البورمية');
INSERT INTO `country` (`id`, `name`) VALUES ('bs', 'البوسنية');
INSERT INTO `country` (`id`, `name`) VALUES ('nb', 'البوكمالية النرويجية');
INSERT INTO `country` (`id`, `name`) VALUES ('pl', 'البولندية');
INSERT INTO `country` (`id`, `name`) VALUES ('pon', 'البوهنبيايان');
INSERT INTO `country` (`id`, `name`) VALUES ('bej', 'البيجا');
INSERT INTO `country` (`id`, `name`) VALUES ('bi', 'البيسلامية');
INSERT INTO `country` (`id`, `name`) VALUES ('bik', 'البيكولية');
INSERT INTO `country` (`id`, `name`) VALUES ('be', 'البيلوروسية');
INSERT INTO `country` (`id`, `name`) VALUES ('bem', 'البيمبا');
INSERT INTO `country` (`id`, `name`) VALUES ('bin', 'البينية');
INSERT INTO `country` (`id`, `name`) VALUES ('bh', 'البيهارية');
INSERT INTO `country` (`id`, `name`) VALUES ('tl', 'التاغالوغية');
INSERT INTO `country` (`id`, `name`) VALUES ('tmh', 'التاماشيك');
INSERT INTO `country` (`id`, `name`) VALUES ('tum', 'التامبوكا');
INSERT INTO `country` (`id`, `name`) VALUES ('ta', 'التاميلية');
INSERT INTO `country` (`id`, `name`) VALUES ('ty', 'التاهيتية');
INSERT INTO `country` (`id`, `name`) VALUES ('th', 'التايلاندية');
INSERT INTO `country` (`id`, `name`) VALUES ('bo', 'التبتية');
INSERT INTO `country` (`id`, `name`) VALUES ('tt', 'التتارية');
INSERT INTO `country` (`id`, `name`) VALUES ('tk', 'التركمانية');
INSERT INTO `country` (`id`, `name`) VALUES ('tr', 'التركية');
INSERT INTO `country` (`id`, `name`) VALUES ('ota', 'التركية العثمانية');
INSERT INTO `country` (`id`, `name`) VALUES ('tn', 'التسوانية');
INSERT INTO `country` (`id`, `name`) VALUES ('tsi', 'التسيمشيان');
INSERT INTO `country` (`id`, `name`) VALUES ('chg', 'التشاجاتاى');
INSERT INTO `country` (`id`, `name`) VALUES ('ch', 'التشامورو');
INSERT INTO `country` (`id`, `name`) VALUES ('cv', 'التشفاش');
INSERT INTO `country` (`id`, `name`) VALUES ('chk', 'التشكيزية');
INSERT INTO `country` (`id`, `name`) VALUES ('chb', 'التشيبشا');
INSERT INTO `country` (`id`, `name`) VALUES ('cs', 'التشيكية');
INSERT INTO `country` (`id`, `name`) VALUES ('tli', 'التلينغيتية');
INSERT INTO `country` (`id`, `name`) VALUES ('tvl', 'التوفالو');
INSERT INTO `country` (`id`, `name`) VALUES ('tpi', 'التوك بيسين');
INSERT INTO `country` (`id`, `name`) VALUES ('tkl', 'التوكيلاو');
INSERT INTO `country` (`id`, `name`) VALUES ('tw', 'التوي');
INSERT INTO `country` (`id`, `name`) VALUES ('tet', 'التيتم');
INSERT INTO `country` (`id`, `name`) VALUES ('tig', 'التيجر');
INSERT INTO `country` (`id`, `name`) VALUES ('ti', 'التيجرينيا');
INSERT INTO `country` (`id`, `name`) VALUES ('ter', 'التيرينو');
INSERT INTO `country` (`id`, `name`) VALUES ('tiv', 'التيف');
INSERT INTO `country` (`id`, `name`) VALUES ('te', 'التيلجو');
INSERT INTO `country` (`id`, `name`) VALUES ('tem', 'التيمن');
INSERT INTO `country` (`id`, `name`) VALUES ('gaa', 'الجا');
INSERT INTO `country` (`id`, `name`) VALUES ('gl', 'الجاليكية');
INSERT INTO `country` (`id`, `name`) VALUES ('lg', 'الجاندا');
INSERT INTO `country` (`id`, `name`) VALUES ('jv', 'الجاوية');
INSERT INTO `country` (`id`, `name`) VALUES ('gay', 'الجايو');
INSERT INTO `country` (`id`, `name`) VALUES ('gba', 'الجبيا');
INSERT INTO `country` (`id`, `name`) VALUES ('root', 'الجذر');
INSERT INTO `country` (`id`, `name`) VALUES ('grb', 'الجريبو');
INSERT INTO `country` (`id`, `name`) VALUES ('gon', 'الجندى');
INSERT INTO `country` (`id`, `name`) VALUES ('kaj', 'الجو');
INSERT INTO `country` (`id`, `name`) VALUES ('gn', 'الجوارانى');
INSERT INTO `country` (`id`, `name`) VALUES ('ka', 'الجورجية');
INSERT INTO `country` (`id`, `name`) VALUES ('gor', 'الجورونتالو');
INSERT INTO `country` (`id`, `name`) VALUES ('jrb', 'الجيدو العربى');
INSERT INTO `country` (`id`, `name`) VALUES ('jpr', 'الجيدو الفارسى');
INSERT INTO `country` (`id`, `name`) VALUES ('gez', 'الجيز');
INSERT INTO `country` (`id`, `name`) VALUES ('hit', 'الحثية');
INSERT INTO `country` (`id`, `name`) VALUES ('km', 'الخميرية');
INSERT INTO `country` (`id`, `name`) VALUES ('kho', 'الخوتانيز');
INSERT INTO `country` (`id`, `name`) VALUES ('khi', 'الخويسان - أخرى');
INSERT INTO `country` (`id`, `name`) VALUES ('dar', 'الدارجوا');
INSERT INTO `country` (`id`, `name`) VALUES ('dak', 'الداكوتا');
INSERT INTO `country` (`id`, `name`) VALUES ('da', 'الدانماركية');
INSERT INTO `country` (`id`, `name`) VALUES ('dyu', 'الدايلا');
INSERT INTO `country` (`id`, `name`) VALUES ('dra', 'الدرافيدين - أخرى');
INSERT INTO `country` (`id`, `name`) VALUES ('din', 'الدنكا');
INSERT INTO `country` (`id`, `name`) VALUES ('doi', 'الدوجرى');
INSERT INTO `country` (`id`, `name`) VALUES ('dgr', 'الدوجريب');
INSERT INTO `country` (`id`, `name`) VALUES ('day', 'الدياك');
INSERT INTO `country` (`id`, `name`) VALUES ('del', 'الديلوير');
INSERT INTO `country` (`id`, `name`) VALUES ('dua', 'الديولا');
INSERT INTO `country` (`id`, `name`) VALUES ('rap', 'الرابانى');
INSERT INTO `country` (`id`, `name`) VALUES ('raj', 'الراجاسثانية');
INSERT INTO `country` (`id`, `name`) VALUES ('rar', 'الراروتونجانى');
INSERT INTO `country` (`id`, `name`) VALUES ('rn', 'الرندى');
INSERT INTO `country` (`id`, `name`) VALUES ('rm', 'الرهايتو-رومانس');
INSERT INTO `country` (`id`, `name`) VALUES ('ru', 'الروسية');
INSERT INTO `country` (`id`, `name`) VALUES ('roa', 'الرومانسية - أخرى');
INSERT INTO `country` (`id`, `name`) VALUES ('ro', 'الرومانية');
INSERT INTO `country` (`id`, `name`) VALUES ('zap', 'الزابوتيك');
INSERT INTO `country` (`id`, `name`) VALUES ('znd', 'الزاند');
INSERT INTO `country` (`id`, `name`) VALUES ('za', 'الزهيونج');
INSERT INTO `country` (`id`, `name`) VALUES ('zu', 'الزولو');
INSERT INTO `country` (`id`, `name`) VALUES ('dz', 'الزونخاية');
INSERT INTO `country` (`id`, `name`) VALUES ('zun', 'الزونية');
INSERT INTO `country` (`id`, `name`) VALUES ('zen', 'الزيناجا');
INSERT INTO `country` (`id`, `name`) VALUES ('sas', 'الساساك');
INSERT INTO `country` (`id`, `name`) VALUES ('sm', 'الساموائية');
INSERT INTO `country` (`id`, `name`) VALUES ('sma', 'السامي الجنوبى');
INSERT INTO `country` (`id`, `name`) VALUES ('se', 'السامي الشمالى');
INSERT INTO `country` (`id`, `name`) VALUES ('sem', 'السامية - أخرى');
INSERT INTO `country` (`id`, `name`) VALUES ('sat', 'السانتالى');
INSERT INTO `country` (`id`, `name`) VALUES ('sg', 'السانجو');
INSERT INTO `country` (`id`, `name`) VALUES ('sad', 'السانداوى');
INSERT INTO `country` (`id`, `name`) VALUES ('srn', 'السرانان تونجو');
INSERT INTO `country` (`id`, `name`) VALUES ('sc', 'السردينية');
INSERT INTO `country` (`id`, `name`) VALUES ('srr', 'السرر');
INSERT INTO `country` (`id`, `name`) VALUES ('syr', 'السريانية');
INSERT INTO `country` (`id`, `name`) VALUES ('si', 'السريلانكية');
INSERT INTO `country` (`id`, `name`) VALUES ('sms', 'السكولت سامى');
INSERT INTO `country` (`id`, `name`) VALUES ('den', 'السلافية');
INSERT INTO `country` (`id`, `name`) VALUES ('sla', 'السلافية - أخرى');
INSERT INTO `country` (`id`, `name`) VALUES ('cel', 'السلتية - أخرى');
INSERT INTO `country` (`id`, `name`) VALUES ('sk', 'السلوفاكية');
INSERT INTO `country` (`id`, `name`) VALUES ('sl', 'السلوفانية');
INSERT INTO `country` (`id`, `name`) VALUES ('sa', 'السنسكريتية');
INSERT INTO `country` (`id`, `name`) VALUES ('ss', 'السواتى');
INSERT INTO `country` (`id`, `name`) VALUES ('sw', 'السواحلية');
INSERT INTO `country` (`id`, `name`) VALUES ('st', 'السوتو الجنوبية');
INSERT INTO `country` (`id`, `name`) VALUES ('nso', 'السوتو الشمالية');
INSERT INTO `country` (`id`, `name`) VALUES ('sog', 'السوجدين');
INSERT INTO `country` (`id`, `name`) VALUES ('su', 'السودانية');
INSERT INTO `country` (`id`, `name`) VALUES ('sus', 'السوسو');
INSERT INTO `country` (`id`, `name`) VALUES ('suk', 'السوكوما');
INSERT INTO `country` (`id`, `name`) VALUES ('sux', 'السومارية');
INSERT INTO `country` (`id`, `name`) VALUES ('ts', 'السونجا');
INSERT INTO `country` (`id`, `name`) VALUES ('son', 'السونجهاى');
INSERT INTO `country` (`id`, `name`) VALUES ('snk', 'السونينك');
INSERT INTO `country` (`id`, `name`) VALUES ('sv', 'السويدية');
INSERT INTO `country` (`id`, `name`) VALUES ('ceb', 'السيبيونو');
INSERT INTO `country` (`id`, `name`) VALUES ('ii', 'السيتشيون يى');
INSERT INTO `country` (`id`, `name`) VALUES ('sid', 'السيدامو');
INSERT INTO `country` (`id`, `name`) VALUES ('bla', 'السيكسيكية');
INSERT INTO `country` (`id`, `name`) VALUES ('sel', 'السيلكب');
INSERT INTO `country` (`id`, `name`) VALUES ('sd', 'السيندى');
INSERT INTO `country` (`id`, `name`) VALUES ('shn', 'الشانية');
INSERT INTO `country` (`id`, `name`) VALUES ('chy', 'الشايان');
INSERT INTO `country` (`id`, `name`) VALUES ('cho', 'الشوكتو');
INSERT INTO `country` (`id`, `name`) VALUES ('sn', 'الشونا');
INSERT INTO `country` (`id`, `name`) VALUES ('chp', 'الشيباوايان');
INSERT INTO `country` (`id`, `name`) VALUES ('chr', 'الشيروكى');
INSERT INTO `country` (`id`, `name`) VALUES ('ce', 'الشيشانية');
INSERT INTO `country` (`id`, `name`) VALUES ('chn', 'الشينوك جارجون');
INSERT INTO `country` (`id`, `name`) VALUES ('sr', 'الصربية');
INSERT INTO `country` (`id`, `name`) VALUES ('dsb', 'الصربية السفلى');
INSERT INTO `country` (`id`, `name`) VALUES ('hsb', 'الصربية العليا');
INSERT INTO `country` (`id`, `name`) VALUES ('scn', 'الصقلية');
INSERT INTO `country` (`id`, `name`) VALUES ('art', 'الصناعية - أخرى');
INSERT INTO `country` (`id`, `name`) VALUES ('so', 'الصومالية');
INSERT INTO `country` (`id`, `name`) VALUES ('zh', 'الصينية');
INSERT INTO `country` (`id`, `name`) VALUES ('zh_Hant', 'الصينية التقليدية');
INSERT INTO `country` (`id`, `name`) VALUES ('sit', 'الصينية التيبتية - أخرى');
INSERT INTO `country` (`id`, `name`) VALUES ('zh_Hans', 'الصينية المبسطة');
INSERT INTO `country` (`id`, `name`) VALUES ('tg', 'الطاجيكية');
INSERT INTO `country` (`id`, `name`) VALUES ('he', 'العبرية');
INSERT INTO `country` (`id`, `name`) VALUES ('ar', 'العربية');
INSERT INTO `country` (`id`, `name`) VALUES ('gu', 'الغوجاراتية');
INSERT INTO `country` (`id`, `name`) VALUES ('gd', 'الغيلية الأسكتلندية');
INSERT INTO `country` (`id`, `name`) VALUES ('paa', 'الغينية - أخرى');
INSERT INTO `country` (`id`, `name`) VALUES ('fa', 'الفارسية');
INSERT INTO `country` (`id`, `name`) VALUES ('peo', 'الفارسية القديمة');
INSERT INTO `country` (`id`, `name`) VALUES ('fo', 'الفارويز');
INSERT INTO `country` (`id`, `name`) VALUES ('fat', 'الفانتى');
INSERT INTO `country` (`id`, `name`) VALUES ('fan', 'الفانج');
INSERT INTO `country` (`id`, `name`) VALUES ('vai', 'الفاى');
INSERT INTO `country` (`id`, `name`) VALUES ('fr', 'الفرنسية');
INSERT INTO `country` (`id`, `name`) VALUES ('fr_CH', 'الفرنسية السويسرية');
INSERT INTO `country` (`id`, `name`) VALUES ('fro', 'الفرنسية القديمة');
INSERT INTO `country` (`id`, `name`) VALUES ('fr_CA', 'الفرنسية الكندية');
INSERT INTO `country` (`id`, `name`) VALUES ('frm', 'الفرنسية الوسطى');
INSERT INTO `country` (`id`, `name`) VALUES ('fy', 'الفريزيان');
INSERT INTO `country` (`id`, `name`) VALUES ('frs', 'الفريزينية الشرقية');
INSERT INTO `country` (`id`, `name`) VALUES ('frr', 'الفريزينية الشمالية');
INSERT INTO `country` (`id`, `name`) VALUES ('fur', 'الفريلايان');
INSERT INTO `country` (`id`, `name`) VALUES ('fil', 'الفلبينية');
INSERT INTO `country` (`id`, `name`) VALUES ('ff', 'الفلة');
INSERT INTO `country` (`id`, `name`) VALUES ('phi', 'الفليبينية - أخرى');
INSERT INTO `country` (`id`, `name`) VALUES ('fi', 'الفنلندية');
INSERT INTO `country` (`id`, `name`) VALUES ('vot', 'الفوتيك');
INSERT INTO `country` (`id`, `name`) VALUES ('fon', 'الفون');
INSERT INTO `country` (`id`, `name`) VALUES ('vi', 'الفيتنامية');
INSERT INTO `country` (`id`, `name`) VALUES ('fj', 'الفيجية');
INSERT INTO `country` (`id`, `name`) VALUES ('ve', 'الفيندا');
INSERT INTO `country` (`id`, `name`) VALUES ('phn', 'الفينيقية');
INSERT INTO `country` (`id`, `name`) VALUES ('kab', 'القبيلية');
INSERT INTO `country` (`id`, `name`) VALUES ('got', 'القوطية');
INSERT INTO `country` (`id`, `name`) VALUES ('cau', 'القوقازية - أخرى');
INSERT INTO `country` (`id`, `name`) VALUES ('ky', 'القيرغستانية');
INSERT INTO `country` (`id`, `name`) VALUES ('kbd', 'الكاباردايان');
INSERT INTO `country` (`id`, `name`) VALUES ('ca', 'الكاتالوينية');
INSERT INTO `country` (`id`, `name`) VALUES ('kac', 'الكاتشين');
INSERT INTO `country` (`id`, `name`) VALUES ('cad', 'الكادو');
INSERT INTO `country` (`id`, `name`) VALUES ('kaa', 'الكارا-كالباك');
INSERT INTO `country` (`id`, `name`) VALUES ('krc', 'الكاراتشاي-بالكار');
INSERT INTO `country` (`id`, `name`) VALUES ('car', 'الكاريبية');
INSERT INTO `country` (`id`, `name`) VALUES ('kar', 'الكاريين');
INSERT INTO `country` (`id`, `name`) VALUES ('kk', 'الكازاخستانية');
INSERT INTO `country` (`id`, `name`) VALUES ('kha', 'الكازية');
INSERT INTO `country` (`id`, `name`) VALUES ('csb', 'الكاشبايان');
INSERT INTO `country` (`id`, `name`) VALUES ('ks', 'الكاشميرية');
INSERT INTO `country` (`id`, `name`) VALUES ('kl', 'الكالاليست');
INSERT INTO `country` (`id`, `name`) VALUES ('xal', 'الكالميك');
INSERT INTO `country` (`id`, `name`) VALUES ('kam', 'الكامبا');
INSERT INTO `country` (`id`, `name`) VALUES ('kn', 'الكانادا');
INSERT INTO `country` (`id`, `name`) VALUES ('kr', 'الكانيوري');
INSERT INTO `country` (`id`, `name`) VALUES ('kpe', 'الكبيل');
INSERT INTO `country` (`id`, `name`) VALUES ('kut', 'الكتيناي');
INSERT INTO `country` (`id`, `name`) VALUES ('ku', 'الكردية');
INSERT INTO `country` (`id`, `name`) VALUES ('kro', 'الكرو');
INSERT INTO `country` (`id`, `name`) VALUES ('hr', 'الكرواتية');
INSERT INTO `country` (`id`, `name`) VALUES ('cr', 'الكرى');
INSERT INTO `country` (`id`, `name`) VALUES ('mus', 'الكريك');
INSERT INTO `country` (`id`, `name`) VALUES ('krl', 'الكريلية');
INSERT INTO `country` (`id`, `name`) VALUES ('crp', 'الكرييولى و اللغات المبسطة الأخرى للتفاهم بين الشعوب - أخرى');
INSERT INTO `country` (`id`, `name`) VALUES ('cpe', 'الكرييولى و اللغات المبسطة الأخرى للتفاهم بين الشعوب على أساس الأنجليزية');
INSERT INTO `country` (`id`, `name`) VALUES ('cpp', 'الكرييولى و اللغات المبسطة الأخرى للتفاهم بين الشعوب على أساس البرتغالية');
INSERT INTO `country` (`id`, `name`) VALUES ('cpf', 'الكرييولى و اللغات المبسطة الأخرى للتفاهم بين الشعوب على أساس الفرنسية');
INSERT INTO `country` (`id`, `name`) VALUES ('cus', 'الكشيتيك - أخرى');
INSERT INTO `country` (`id`, `name`) VALUES ('tlh', 'الكلينجون');
INSERT INTO `country` (`id`, `name`) VALUES ('kum', 'الكميك');
INSERT INTO `country` (`id`, `name`) VALUES ('co', 'الكورسيكية');
INSERT INTO `country` (`id`, `name`) VALUES ('kw', 'الكورنية');
INSERT INTO `country` (`id`, `name`) VALUES ('kfo', 'الكورو');
INSERT INTO `country` (`id`, `name`) VALUES ('ko', 'الكورية');
INSERT INTO `country` (`id`, `name`) VALUES ('kos', 'الكوسراين');
INSERT INTO `country` (`id`, `name`) VALUES ('kv', 'الكومي');
INSERT INTO `country` (`id`, `name`) VALUES ('kg', 'الكونغو');
INSERT INTO `country` (`id`, `name`) VALUES ('kok', 'الكونكانية');
INSERT INTO `country` (`id`, `name`) VALUES ('kaw', 'الكوي');
INSERT INTO `country` (`id`, `name`) VALUES ('qu', 'الكويتشوا');
INSERT INTO `country` (`id`, `name`) VALUES ('ki', 'الكيكيو');
INSERT INTO `country` (`id`, `name`) VALUES ('kmb', 'الكيمبندو');
INSERT INTO `country` (`id`, `name`) VALUES ('rw', 'الكينيارواندا');
INSERT INTO `country` (`id`, `name`) VALUES ('kj', 'الكيونياما');
INSERT INTO `country` (`id`, `name`) VALUES ('lv', 'اللاتفية');
INSERT INTO `country` (`id`, `name`) VALUES ('la', 'اللاتينية');
INSERT INTO `country` (`id`, `name`) VALUES ('lam', 'اللامبا');
INSERT INTO `country` (`id`, `name`) VALUES ('lah', 'اللاهندا');
INSERT INTO `country` (`id`, `name`) VALUES ('lo', 'اللاوية');
INSERT INTO `country` (`id`, `name`) VALUES ('lu', 'اللبا-كاتانجا');
INSERT INTO `country` (`id`, `name`) VALUES ('lua', 'اللبا-لؤلؤ');
INSERT INTO `country` (`id`, `name`) VALUES ('lt', 'اللتوانية');
INSERT INTO `country` (`id`, `name`) VALUES ('lus', 'اللشاي');
INSERT INTO `country` (`id`, `name`) VALUES ('apa', 'اللغات الأباتشية');
INSERT INTO `country` (`id`, `name`) VALUES ('ath', 'اللغات الأزباسكانية');
INSERT INTO `country` (`id`, `name`) VALUES ('aus', 'اللغات الأسترالية');
INSERT INTO `country` (`id`, `name`) VALUES ('alg', 'اللغات الأمريكية الهندية');
INSERT INTO `country` (`id`, `name`) VALUES ('oto', 'اللغات الأوتومية');
INSERT INTO `country` (`id`, `name`) VALUES ('iro', 'اللغات الايروكويانية');
INSERT INTO `country` (`id`, `name`) VALUES ('bai', 'اللغات الباميليكية');
INSERT INTO `country` (`id`, `name`) VALUES ('pra', 'اللغات البراقريطية');
INSERT INTO `country` (`id`, `name`) VALUES ('cmc', 'اللغات التشاميكية');
INSERT INTO `country` (`id`, `name`) VALUES ('tup', 'اللغات التوبية');
INSERT INTO `country` (`id`, `name`) VALUES ('smi', 'اللغات السامية - أخرى');
INSERT INTO `country` (`id`, `name`) VALUES ('wen', 'اللغات الصربية');
INSERT INTO `country` (`id`, `name`) VALUES ('mul', 'اللغات المتعددة');
INSERT INTO `country` (`id`, `name`) VALUES ('mis', 'اللغات المتنوعة');
INSERT INTO `country` (`id`, `name`) VALUES ('nub', 'اللغات النوبية');
INSERT INTO `country` (`id`, `name`) VALUES ('ypk', 'اللغات اليوبيكية');
INSERT INTO `country` (`id`, `name`) VALUES ('myv', 'اللغة الارزية');
INSERT INTO `country` (`id`, `name`) VALUES ('ban', 'اللغة البالية');
INSERT INTO `country` (`id`, `name`) VALUES ('nap', 'اللغة النابولية');
INSERT INTO `country` (`id`, `name`) VALUES ('luo', 'اللو');
INSERT INTO `country` (`id`, `name`) VALUES ('jbo', 'اللوجبان');
INSERT INTO `country` (`id`, `name`) VALUES ('loz', 'اللوزى');
INSERT INTO `country` (`id`, `name`) VALUES ('lui', 'اللوسينو');
INSERT INTO `country` (`id`, `name`) VALUES ('lb', 'اللوكسمبرجية');
INSERT INTO `country` (`id`, `name`) VALUES ('smj', 'اللول سامى');
INSERT INTO `country` (`id`, `name`) VALUES ('lun', 'اللوندا');
INSERT INTO `country` (`id`, `name`) VALUES ('lez', 'الليزجهايانية');
INSERT INTO `country` (`id`, `name`) VALUES ('li', 'الليمبرجيشية');
INSERT INTO `country` (`id`, `name`) VALUES ('ln', 'اللينجالا');
INSERT INTO `country` (`id`, `name`) VALUES ('ia', 'اللّغة الوسيطة');
INSERT INTO `country` (`id`, `name`) VALUES ('mag', 'الماجا');
INSERT INTO `country` (`id`, `name`) VALUES ('mad', 'المادريز');
INSERT INTO `country` (`id`, `name`) VALUES ('mr', 'الماراثى');
INSERT INTO `country` (`id`, `name`) VALUES ('mh', 'المارشالية');
INSERT INTO `country` (`id`, `name`) VALUES ('mwr', 'الماروارى');
INSERT INTO `country` (`id`, `name`) VALUES ('chm', 'الماري');
INSERT INTO `country` (`id`, `name`) VALUES ('mas', 'الماساي');
INSERT INTO `country` (`id`, `name`) VALUES ('mak', 'الماكاسار');
INSERT INTO `country` (`id`, `name`) VALUES ('mg', 'المالاجاشية');
INSERT INTO `country` (`id`, `name`) VALUES ('dv', 'المالديفية');
INSERT INTO `country` (`id`, `name`) VALUES ('mt', 'المالطية');
INSERT INTO `country` (`id`, `name`) VALUES ('ml', 'الماليالام');
INSERT INTO `country` (`id`, `name`) VALUES ('mdr', 'الماندار');
INSERT INTO `country` (`id`, `name`) VALUES ('man', 'الماندينغ');
INSERT INTO `country` (`id`, `name`) VALUES ('mnc', 'المانشو');
INSERT INTO `country` (`id`, `name`) VALUES ('mni', 'المانيبرى');
INSERT INTO `country` (`id`, `name`) VALUES ('mi', 'الماورية');
INSERT INTO `country` (`id`, `name`) VALUES ('mai', 'المايثيلي');
INSERT INTO `country` (`id`, `name`) VALUES ('egy', 'المصرية القديمة');
INSERT INTO `country` (`id`, `name`) VALUES ('mk', 'المقدونية');
INSERT INTO `country` (`id`, `name`) VALUES ('mn', 'المنغولية');
INSERT INTO `country` (`id`, `name`) VALUES ('gv', 'المنكية');
INSERT INTO `country` (`id`, `name`) VALUES ('mos', 'الموسي');
INSERT INTO `country` (`id`, `name`) VALUES ('mdf', 'الموكشا');
INSERT INTO `country` (`id`, `name`) VALUES ('mo', 'المولدوفية');
INSERT INTO `country` (`id`, `name`) VALUES ('mkh', 'المون خمير- أخرى');
INSERT INTO `country` (`id`, `name`) VALUES ('moh', 'الموهوك');
INSERT INTO `country` (`id`, `name`) VALUES ('mwl', 'الميرانديز');
INSERT INTO `country` (`id`, `name`) VALUES ('mic', 'الميكماكيونية');
INSERT INTO `country` (`id`, `name`) VALUES ('min', 'المينانجكاباو');
INSERT INTO `country` (`id`, `name`) VALUES ('men', 'الميند');
INSERT INTO `country` (`id`, `name`) VALUES ('nv', 'النافاجو');
INSERT INTO `country` (`id`, `name`) VALUES ('nah', 'الناهيوتل');
INSERT INTO `country` (`id`, `name`) VALUES ('ng', 'الندونجا');
INSERT INTO `country` (`id`, `name`) VALUES ('nr', 'النديبيل الجنوبى');
INSERT INTO `country` (`id`, `name`) VALUES ('nd', 'النديبيل الشمالى');
INSERT INTO `country` (`id`, `name`) VALUES ('no', 'النرويجية');
INSERT INTO `country` (`id`, `name`) VALUES ('nzi', 'النزيما');
INSERT INTO `country` (`id`, `name`) VALUES ('nwc', 'النوارية التقليدية');
INSERT INTO `country` (`id`, `name`) VALUES ('nog', 'النوجاى');
INSERT INTO `country` (`id`, `name`) VALUES ('non', 'النورس القديم');
INSERT INTO `country` (`id`, `name`) VALUES ('na', 'النورو');
INSERT INTO `country` (`id`, `name`) VALUES ('nia', 'النياس');
INSERT INTO `country` (`id`, `name`) VALUES ('nym', 'النيامويزى');
INSERT INTO `country` (`id`, `name`) VALUES ('ny', 'النيانجا، التشيتشوا، التشوا');
INSERT INTO `country` (`id`, `name`) VALUES ('nyn', 'النيانكول');
INSERT INTO `country` (`id`, `name`) VALUES ('ne', 'النيبالية');
INSERT INTO `country` (`id`, `name`) VALUES ('nic', 'النيجر - كوردوفانايان');
INSERT INTO `country` (`id`, `name`) VALUES ('ssa', 'النيلية الصحراوية - أخرى');
INSERT INTO `country` (`id`, `name`) VALUES ('nn', 'النينورسك النرويجي');
INSERT INTO `country` (`id`, `name`) VALUES ('new', 'النيواري');
INSERT INTO `country` (`id`, `name`) VALUES ('nyo', 'النيورو');
INSERT INTO `country` (`id`, `name`) VALUES ('niu', 'النيوي');
INSERT INTO `country` (`id`, `name`) VALUES ('ht', 'الهايتية');
INSERT INTO `country` (`id`, `name`) VALUES ('hup', 'الهبا');
INSERT INTO `country` (`id`, `name`) VALUES ('hmn', 'الهمونجية');
INSERT INTO `country` (`id`, `name`) VALUES ('hi', 'الهندية');
INSERT INTO `country` (`id`, `name`) VALUES ('inc', 'الهندية - أخرى');
INSERT INTO `country` (`id`, `name`) VALUES ('sai', 'الهندية الأمريكية الجنوبية - أخرى');
INSERT INTO `country` (`id`, `name`) VALUES ('nai', 'الهندية الأمريكية الشمالية - أخرى');
INSERT INTO `country` (`id`, `name`) VALUES ('cai', 'الهندية الأمريكية الوسطى - أخرى');
INSERT INTO `country` (`id`, `name`) VALUES ('ine', 'الهندية الأوروبية - أخرى');
INSERT INTO `country` (`id`, `name`) VALUES ('hu', 'الهنغارية');
INSERT INTO `country` (`id`, `name`) VALUES ('ha', 'الهوسا');
INSERT INTO `country` (`id`, `name`) VALUES ('nl', 'الهولندية');
INSERT INTO `country` (`id`, `name`) VALUES ('dum', 'الهولندية الوسطى');
INSERT INTO `country` (`id`, `name`) VALUES ('hai', 'الهيدا');
INSERT INTO `country` (`id`, `name`) VALUES ('ho', 'الهيرى موتو');
INSERT INTO `country` (`id`, `name`) VALUES ('hz', 'الهيريرو');
INSERT INTO `country` (`id`, `name`) VALUES ('hil', 'الهيليجينون');
INSERT INTO `country` (`id`, `name`) VALUES ('him', 'الهيماتشالى');
INSERT INTO `country` (`id`, `name`) VALUES ('war', 'الواراى');
INSERT INTO `country` (`id`, `name`) VALUES ('was', 'الواشو');
INSERT INTO `country` (`id`, `name`) VALUES ('wal', 'الوالامو');
INSERT INTO `country` (`id`, `name`) VALUES ('cy', 'الولزية');
INSERT INTO `country` (`id`, `name`) VALUES ('wo', 'الولوف');
INSERT INTO `country` (`id`, `name`) VALUES ('wa', 'الولونية');
INSERT INTO `country` (`id`, `name`) VALUES ('ja', 'اليابانية');
INSERT INTO `country` (`id`, `name`) VALUES ('yap', 'اليابيز');
INSERT INTO `country` (`id`, `name`) VALUES ('sah', 'الياكت');
INSERT INTO `country` (`id`, `name`) VALUES ('yao', 'الياو');
INSERT INTO `country` (`id`, `name`) VALUES ('uga', 'اليجاريتيك');
INSERT INTO `country` (`id`, `name`) VALUES ('yi', 'اليديشية');
INSERT INTO `country` (`id`, `name`) VALUES ('yo', 'اليوروبية');
INSERT INTO `country` (`id`, `name`) VALUES ('el', 'اليونانية');
INSERT INTO `country` (`id`, `name`) VALUES ('grc', 'اليونانية القديمة');
INSERT INTO `country` (`id`, `name`) VALUES ('nqo', 'انكو');
INSERT INTO `country` (`id`, `name`) VALUES ('zxx', 'بدون محتوى لغوي');
INSERT INTO `country` (`id`, `name`) VALUES ('tai', 'تاى - أخرى');
INSERT INTO `country` (`id`, `name`) VALUES ('crh', 'تركى كريمين، لغة توركية كريمينية');
INSERT INTO `country` (`id`, `name`) VALUES ('to', 'تونجا - جزر تونجا');
INSERT INTO `country` (`id`, `name`) VALUES ('tog', 'تونجا - نياسا');
INSERT INTO `country` (`id`, `name`) VALUES ('syc', 'سريانية تقليدية');
INSERT INTO `country` (`id`, `name`) VALUES ('cu', 'سلافية كنسية');
INSERT INTO `country` (`id`, `name`) VALUES ('und', 'غير محدده');
INSERT INTO `country` (`id`, `name`) VALUES ('fiu', 'فينو أجرايان - أخرى');
INSERT INTO `country` (`id`, `name`) VALUES ('cop', 'قبطية');
INSERT INTO `country` (`id`, `name`) VALUES ('sgn', 'لغات الإشارة');
INSERT INTO `country` (`id`, `name`) VALUES ('sio', 'لغات السيويون');
INSERT INTO `country` (`id`, `name`) VALUES ('myn', 'لغات المايا');
INSERT INTO `country` (`id`, `name`) VALUES ('mun', 'لغات المندا');
INSERT INTO `country` (`id`, `name`) VALUES ('wak', 'لغات الواكاشان');
INSERT INTO `country` (`id`, `name`) VALUES ('sal', 'لغات ساليشان');
INSERT INTO `country` (`id`, `name`) VALUES ('mno', 'لغات مانوبو');
INSERT INTO `country` (`id`, `name`) VALUES ('afa', 'لغة أفرو آسيوية');
INSERT INTO `country` (`id`, `name`) VALUES ('haw', 'لغة أهل الهاواى');
INSERT INTO `country` (`id`, `name`) VALUES ('gil', 'لغة أهل جبل طارق');
INSERT INTO `country` (`id`, `name`) VALUES ('eu', 'لغة الباسك');
INSERT INTO `country` (`id`, `name`) VALUES ('ms', 'لغة الملايو');
INSERT INTO `country` (`id`, `name`) VALUES ('gem', 'لغة جرمانية');
INSERT INTO `country` (`id`, `name`) VALUES ('lol', 'منغولى');
