CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('ab', 'abkazijski');
INSERT INTO "country" ("id", "name") VALUES ('ace', 'ačineski');
INSERT INTO "country" ("id", "name") VALUES ('ada', 'adangmejski');
INSERT INTO "country" ("id", "name") VALUES ('ady', 'adigejski');
INSERT INTO "country" ("id", "name") VALUES ('aa', 'afarski');
INSERT INTO "country" ("id", "name") VALUES ('afh', 'afrihili');
INSERT INTO "country" ("id", "name") VALUES ('af', 'afrikanerski');
INSERT INTO "country" ("id", "name") VALUES ('afa', 'afro-azijatski');
INSERT INTO "country" ("id", "name") VALUES ('ain', 'ainu');
INSERT INTO "country" ("id", "name") VALUES ('ay', 'ajmara');
INSERT INTO "country" ("id", "name") VALUES ('akk', 'akadijski');
INSERT INTO "country" ("id", "name") VALUES ('ak', 'akan');
INSERT INTO "country" ("id", "name") VALUES ('ach', 'akoli');
INSERT INTO "country" ("id", "name") VALUES ('sq', 'albanski');
INSERT INTO "country" ("id", "name") VALUES ('alg', 'algonkvijanski jezik');
INSERT INTO "country" ("id", "name") VALUES ('tut', 'altaički jezik');
INSERT INTO "country" ("id", "name") VALUES ('ale', 'aljut');
INSERT INTO "country" ("id", "name") VALUES ('am', 'amharski');
INSERT INTO "country" ("id", "name") VALUES ('anp', 'angika');
INSERT INTO "country" ("id", "name") VALUES ('apa', 'apački jezik');
INSERT INTO "country" ("id", "name") VALUES ('an', 'aragonežanski');
INSERT INTO "country" ("id", "name") VALUES ('arp', 'arapaho');
INSERT INTO "country" ("id", "name") VALUES ('ar', 'arapski');
INSERT INTO "country" ("id", "name") VALUES ('arw', 'aravak');
INSERT INTO "country" ("id", "name") VALUES ('arc', 'armajski');
INSERT INTO "country" ("id", "name") VALUES ('arn', 'arokanijski');
INSERT INTO "country" ("id", "name") VALUES ('rup', 'aromanijski');
INSERT INTO "country" ("id", "name") VALUES ('as', 'asemijski');
INSERT INTO "country" ("id", "name") VALUES ('ast', 'asturijski');
INSERT INTO "country" ("id", "name") VALUES ('ath', 'atapaskan');
INSERT INTO "country" ("id", "name") VALUES ('cch', 'atsam');
INSERT INTO "country" ("id", "name") VALUES ('aus', 'australijski jezik');
INSERT INTO "country" ("id", "name") VALUES ('map', 'austronežanski');
INSERT INTO "country" ("id", "name") VALUES ('awa', 'avadhi');
INSERT INTO "country" ("id", "name") VALUES ('av', 'avarski');
INSERT INTO "country" ("id", "name") VALUES ('ae', 'avestanski');
INSERT INTO "country" ("id", "name") VALUES ('az', 'azerbejdžanski');
INSERT INTO "country" ("id", "name") VALUES ('ban', 'balinezijski');
INSERT INTO "country" ("id", "name") VALUES ('bat', 'baltički jezik');
INSERT INTO "country" ("id", "name") VALUES ('bal', 'baluči');
INSERT INTO "country" ("id", "name") VALUES ('bm', 'bambara');
INSERT INTO "country" ("id", "name") VALUES ('bai', 'bamileke');
INSERT INTO "country" ("id", "name") VALUES ('bad', 'banda');
INSERT INTO "country" ("id", "name") VALUES ('bnt', 'bantu');
INSERT INTO "country" ("id", "name") VALUES ('bas', 'basa');
INSERT INTO "country" ("id", "name") VALUES ('eu', 'baskijski');
INSERT INTO "country" ("id", "name") VALUES ('ba', 'baškir');
INSERT INTO "country" ("id", "name") VALUES ('btk', 'batak');
INSERT INTO "country" ("id", "name") VALUES ('bej', 'beja');
INSERT INTO "country" ("id", "name") VALUES ('be', 'beloruski');
INSERT INTO "country" ("id", "name") VALUES ('bem', 'bemba');
INSERT INTO "country" ("id", "name") VALUES ('bn', 'bengalski');
INSERT INTO "country" ("id", "name") VALUES ('ber', 'berber');
INSERT INTO "country" ("id", "name") VALUES ('zxx', 'bez lingvističkog sadržaja');
INSERT INTO "country" ("id", "name") VALUES ('bh', 'biharski');
INSERT INTO "country" ("id", "name") VALUES ('bik', 'bikol');
INSERT INTO "country" ("id", "name") VALUES ('bin', 'bini');
INSERT INTO "country" ("id", "name") VALUES ('bi', 'bislama');
INSERT INTO "country" ("id", "name") VALUES ('byn', 'blin');
INSERT INTO "country" ("id", "name") VALUES ('zbl', 'blisimboli');
INSERT INTO "country" ("id", "name") VALUES ('bho', 'bojpuri');
INSERT INTO "country" ("id", "name") VALUES ('bs', 'bosanski');
INSERT INTO "country" ("id", "name") VALUES ('bra', 'braj');
INSERT INTO "country" ("id", "name") VALUES ('br', 'bretonski');
INSERT INTO "country" ("id", "name") VALUES ('bg', 'bugarski');
INSERT INTO "country" ("id", "name") VALUES ('bug', 'buginežanskii');
INSERT INTO "country" ("id", "name") VALUES ('bua', 'buriat');
INSERT INTO "country" ("id", "name") VALUES ('my', 'burmanski');
INSERT INTO "country" ("id", "name") VALUES ('ceb', 'cebuano');
INSERT INTO "country" ("id", "name") VALUES ('chg', 'čagatai');
INSERT INTO "country" ("id", "name") VALUES ('ch', 'čamoro');
INSERT INTO "country" ("id", "name") VALUES ('cmc', 'čamski jezik');
INSERT INTO "country" ("id", "name") VALUES ('ce', 'čečenski');
INSERT INTO "country" ("id", "name") VALUES ('chy', 'čejenski');
INSERT INTO "country" ("id", "name") VALUES ('chr', 'čeroki');
INSERT INTO "country" ("id", "name") VALUES ('cs', 'češki');
INSERT INTO "country" ("id", "name") VALUES ('chb', 'čibča');
INSERT INTO "country" ("id", "name") VALUES ('chn', 'činukski');
INSERT INTO "country" ("id", "name") VALUES ('chp', 'čipvijanski');
INSERT INTO "country" ("id", "name") VALUES ('cho', 'čoktavski');
INSERT INTO "country" ("id", "name") VALUES ('chk', 'čukeski');
INSERT INTO "country" ("id", "name") VALUES ('cv', 'čuvaški');
INSERT INTO "country" ("id", "name") VALUES ('day', 'dajaški');
INSERT INTO "country" ("id", "name") VALUES ('dak', 'dakota');
INSERT INTO "country" ("id", "name") VALUES ('da', 'danski');
INSERT INTO "country" ("id", "name") VALUES ('dar', 'dargva');
INSERT INTO "country" ("id", "name") VALUES ('del', 'delaver');
INSERT INTO "country" ("id", "name") VALUES ('din', 'dinka');
INSERT INTO "country" ("id", "name") VALUES ('dv', 'divehijski');
INSERT INTO "country" ("id", "name") VALUES ('doi', 'dogri');
INSERT INTO "country" ("id", "name") VALUES ('dgr', 'dogrib');
INSERT INTO "country" ("id", "name") VALUES ('dra', 'dravidijski jezik');
INSERT INTO "country" ("id", "name") VALUES ('dua', 'duala');
INSERT INTO "country" ("id", "name") VALUES ('gez', 'džiz');
INSERT INTO "country" ("id", "name") VALUES ('dz', 'džonga');
INSERT INTO "country" ("id", "name") VALUES ('dyu', 'đula');
INSERT INTO "country" ("id", "name") VALUES ('efi', 'efikski');
INSERT INTO "country" ("id", "name") VALUES ('eka', 'ekajuk');
INSERT INTO "country" ("id", "name") VALUES ('elx', 'elamitski');
INSERT INTO "country" ("id", "name") VALUES ('en', 'engleski');
INSERT INTO "country" ("id", "name") VALUES ('myv', 'erzija');
INSERT INTO "country" ("id", "name") VALUES ('eo', 'esperanto');
INSERT INTO "country" ("id", "name") VALUES ('et', 'estonski');
INSERT INTO "country" ("id", "name") VALUES ('ee', 'eve');
INSERT INTO "country" ("id", "name") VALUES ('ewo', 'evondo');
INSERT INTO "country" ("id", "name") VALUES ('fan', 'fang');
INSERT INTO "country" ("id", "name") VALUES ('fat', 'fanti');
INSERT INTO "country" ("id", "name") VALUES ('fo', 'farski');
INSERT INTO "country" ("id", "name") VALUES ('phn', 'feničanski');
INSERT INTO "country" ("id", "name") VALUES ('fj', 'fidžijski');
INSERT INTO "country" ("id", "name") VALUES ('fil', 'filipinski');
INSERT INTO "country" ("id", "name") VALUES ('phi', 'filipinski jezik');
INSERT INTO "country" ("id", "name") VALUES ('fi', 'finski');
INSERT INTO "country" ("id", "name") VALUES ('nl_BE', 'flamanski');
INSERT INTO "country" ("id", "name") VALUES ('fon', 'fon');
INSERT INTO "country" ("id", "name") VALUES ('fr', 'francuski');
INSERT INTO "country" ("id", "name") VALUES ('fur', 'friulijski');
INSERT INTO "country" ("id", "name") VALUES ('fy', 'frizijski');
INSERT INTO "country" ("id", "name") VALUES ('ff', 'fulah');
INSERT INTO "country" ("id", "name") VALUES ('gaa', 'ga');
INSERT INTO "country" ("id", "name") VALUES ('gay', 'gajo');
INSERT INTO "country" ("id", "name") VALUES ('gl', 'galski');
INSERT INTO "country" ("id", "name") VALUES ('lg', 'ganda');
INSERT INTO "country" ("id", "name") VALUES ('gba', 'gbaja');
INSERT INTO "country" ("id", "name") VALUES ('gem', 'germanski jezik');
INSERT INTO "country" ("id", "name") VALUES ('gil', 'gilbertški');
INSERT INTO "country" ("id", "name") VALUES ('gon', 'gondi');
INSERT INTO "country" ("id", "name") VALUES ('hsb', 'gornji sorbijski');
INSERT INTO "country" ("id", "name") VALUES ('gor', 'gorontalo');
INSERT INTO "country" ("id", "name") VALUES ('got', 'gotski');
INSERT INTO "country" ("id", "name") VALUES ('el', 'grčki');
INSERT INTO "country" ("id", "name") VALUES ('grb', 'grebo');
INSERT INTO "country" ("id", "name") VALUES ('ka', 'gruzijski');
INSERT INTO "country" ("id", "name") VALUES ('gu', 'gudžarati');
INSERT INTO "country" ("id", "name") VALUES ('gn', 'gvarani');
INSERT INTO "country" ("id", "name") VALUES ('ht', 'haićanski');
INSERT INTO "country" ("id", "name") VALUES ('hai', 'haida');
INSERT INTO "country" ("id", "name") VALUES ('ha', 'hausa');
INSERT INTO "country" ("id", "name") VALUES ('haw', 'havajski');
INSERT INTO "country" ("id", "name") VALUES ('he', 'hebrejski');
INSERT INTO "country" ("id", "name") VALUES ('hz', 'herero');
INSERT INTO "country" ("id", "name") VALUES ('hil', 'hiligajnon');
INSERT INTO "country" ("id", "name") VALUES ('him', 'himačali');
INSERT INTO "country" ("id", "name") VALUES ('hi', 'hindi');
INSERT INTO "country" ("id", "name") VALUES ('ho', 'hiri motu');
INSERT INTO "country" ("id", "name") VALUES ('hit', 'hitite');
INSERT INTO "country" ("id", "name") VALUES ('hmn', 'hmong');
INSERT INTO "country" ("id", "name") VALUES ('nl', 'holandski');
INSERT INTO "country" ("id", "name") VALUES ('hr', 'hrvatski');
INSERT INTO "country" ("id", "name") VALUES ('hup', 'hupa');
INSERT INTO "country" ("id", "name") VALUES ('iba', 'iban');
INSERT INTO "country" ("id", "name") VALUES ('io', 'ido');
INSERT INTO "country" ("id", "name") VALUES ('ig', 'igbo');
INSERT INTO "country" ("id", "name") VALUES ('ijo', 'ijo');
INSERT INTO "country" ("id", "name") VALUES ('ilo', 'iloko');
INSERT INTO "country" ("id", "name") VALUES ('smn', 'inari sami');
INSERT INTO "country" ("id", "name") VALUES ('inc', 'indik');
INSERT INTO "country" ("id", "name") VALUES ('ine', 'indo-evropski jezik');
INSERT INTO "country" ("id", "name") VALUES ('id', 'indonezijski');
INSERT INTO "country" ("id", "name") VALUES ('inh', 'ingušetski');
INSERT INTO "country" ("id", "name") VALUES ('ia', 'interlingva');
INSERT INTO "country" ("id", "name") VALUES ('ie', 'interlingve');
INSERT INTO "country" ("id", "name") VALUES ('iu', 'inuktitut');
INSERT INTO "country" ("id", "name") VALUES ('ik', 'inupiak');
INSERT INTO "country" ("id", "name") VALUES ('ira', 'iranski jezik');
INSERT INTO "country" ("id", "name") VALUES ('iro', 'irokvojanski');
INSERT INTO "country" ("id", "name") VALUES ('ga', 'irski');
INSERT INTO "country" ("id", "name") VALUES ('is', 'islandski');
INSERT INTO "country" ("id", "name") VALUES ('frs', 'istočni frizijski');
INSERT INTO "country" ("id", "name") VALUES ('sah', 'jakut');
INSERT INTO "country" ("id", "name") VALUES ('yao', 'jao');
INSERT INTO "country" ("id", "name") VALUES ('ja', 'japanski');
INSERT INTO "country" ("id", "name") VALUES ('yap', 'japeški');
INSERT INTO "country" ("id", "name") VALUES ('jv', 'javanski');
INSERT INTO "country" ("id", "name") VALUES ('hy', 'jermenski');
INSERT INTO "country" ("id", "name") VALUES ('cai', 'jezik centralno-američkih indijanaca');
INSERT INTO "country" ("id", "name") VALUES ('sai', 'jezik južno-američkih indijanaca');
INSERT INTO "country" ("id", "name") VALUES ('nai', 'jezik severno-američkih indijanaca');
INSERT INTO "country" ("id", "name") VALUES ('sgn', 'jezik znakova');
INSERT INTO "country" ("id", "name") VALUES ('yi', 'jidiš');
INSERT INTO "country" ("id", "name") VALUES ('yo', 'jorubanski');
INSERT INTO "country" ("id", "name") VALUES ('jrb', 'judeo-arapski');
INSERT INTO "country" ("id", "name") VALUES ('jpr', 'judeo-persijski');
INSERT INTO "country" ("id", "name") VALUES ('ypk', 'jupik');
INSERT INTO "country" ("id", "name") VALUES ('alt', 'južni altai');
INSERT INTO "country" ("id", "name") VALUES ('nr', 'južni ndebele');
INSERT INTO "country" ("id", "name") VALUES ('sma', 'južni sami');
INSERT INTO "country" ("id", "name") VALUES ('kbd', 'kabardijski');
INSERT INTO "country" ("id", "name") VALUES ('kab', 'kabile');
INSERT INTO "country" ("id", "name") VALUES ('kac', 'kačin');
INSERT INTO "country" ("id", "name") VALUES ('cad', 'kado');
INSERT INTO "country" ("id", "name") VALUES ('kl', 'kalalisutski');
INSERT INTO "country" ("id", "name") VALUES ('xal', 'kalmik');
INSERT INTO "country" ("id", "name") VALUES ('kam', 'kamba');
INSERT INTO "country" ("id", "name") VALUES ('kn', 'kanada');
INSERT INTO "country" ("id", "name") VALUES ('kr', 'kanuri');
INSERT INTO "country" ("id", "name") VALUES ('kaa', 'kara-kalpaški');
INSERT INTO "country" ("id", "name") VALUES ('krc', 'karačaj-balkar');
INSERT INTO "country" ("id", "name") VALUES ('krl', 'karelijski');
INSERT INTO "country" ("id", "name") VALUES ('kar', 'karenski');
INSERT INTO "country" ("id", "name") VALUES ('car', 'karipski');
INSERT INTO "country" ("id", "name") VALUES ('kha', 'kasi');
INSERT INTO "country" ("id", "name") VALUES ('ks', 'kašmiri');
INSERT INTO "country" ("id", "name") VALUES ('csb', 'kašubijanski');
INSERT INTO "country" ("id", "name") VALUES ('ca', 'katalonski');
INSERT INTO "country" ("id", "name") VALUES ('kaw', 'kavi');
INSERT INTO "country" ("id", "name") VALUES ('cau', 'kavkaski');
INSERT INTO "country" ("id", "name") VALUES ('cel', 'keltski jezik');
INSERT INTO "country" ("id", "name") VALUES ('xh', 'khosa');
INSERT INTO "country" ("id", "name") VALUES ('ki', 'kikuju');
INSERT INTO "country" ("id", "name") VALUES ('kmb', 'kimbundu');
INSERT INTO "country" ("id", "name") VALUES ('zh', 'kineski');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hans', 'kineski (pojednostavljen)');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hant', 'kineski (tradicionalni)');
INSERT INTO "country" ("id", "name") VALUES ('rw', 'kinjarvanda');
INSERT INTO "country" ("id", "name") VALUES ('ky', 'kirgiski');
INSERT INTO "country" ("id", "name") VALUES ('nwc', 'klasični nevari');
INSERT INTO "country" ("id", "name") VALUES ('syc', 'klasični sirijski');
INSERT INTO "country" ("id", "name") VALUES ('tlh', 'klingonski');
INSERT INTO "country" ("id", "name") VALUES ('km', 'kmerski');
INSERT INTO "country" ("id", "name") VALUES ('khi', 'koisanski jezik');
INSERT INTO "country" ("id", "name") VALUES ('kv', 'komi');
INSERT INTO "country" ("id", "name") VALUES ('kg', 'kongo');
INSERT INTO "country" ("id", "name") VALUES ('kok', 'konkani');
INSERT INTO "country" ("id", "name") VALUES ('cop', 'koptski');
INSERT INTO "country" ("id", "name") VALUES ('ko', 'korejski');
INSERT INTO "country" ("id", "name") VALUES ('kw', 'korniški');
INSERT INTO "country" ("id", "name") VALUES ('kfo', 'koro');
INSERT INTO "country" ("id", "name") VALUES ('co', 'korzikanski');
INSERT INTO "country" ("id", "name") VALUES ('kos', 'kosreanski');
INSERT INTO "country" ("id", "name") VALUES ('kho', 'kotanizijski');
INSERT INTO "country" ("id", "name") VALUES ('kk', 'kozački');
INSERT INTO "country" ("id", "name") VALUES ('kpe', 'kpele');
INSERT INTO "country" ("id", "name") VALUES ('crp', 'kreolski ili pidžin');
INSERT INTO "country" ("id", "name") VALUES ('cpp', 'kreolski ili pidžin baziran na portugalskom');
INSERT INTO "country" ("id", "name") VALUES ('cpe', 'kreolski ili pidžin zasnovan na engleskom');
INSERT INTO "country" ("id", "name") VALUES ('cpf', 'kreolski ili pidžin zasnovan na francuskom');
INSERT INTO "country" ("id", "name") VALUES ('cr', 'kri');
INSERT INTO "country" ("id", "name") VALUES ('crh', 'krimeanski turski');
INSERT INTO "country" ("id", "name") VALUES ('mus', 'kriški');
INSERT INTO "country" ("id", "name") VALUES ('kro', 'kru');
INSERT INTO "country" ("id", "name") VALUES ('kj', 'kuanjama');
INSERT INTO "country" ("id", "name") VALUES ('kum', 'kumik');
INSERT INTO "country" ("id", "name") VALUES ('ku', 'kurdski');
INSERT INTO "country" ("id", "name") VALUES ('kru', 'kurukh');
INSERT INTO "country" ("id", "name") VALUES ('cus', 'kušitički jezik');
INSERT INTO "country" ("id", "name") VALUES ('kut', 'kutenai');
INSERT INTO "country" ("id", "name") VALUES ('qu', 'kvenča');
INSERT INTO "country" ("id", "name") VALUES ('lad', 'ladino');
INSERT INTO "country" ("id", "name") VALUES ('lam', 'lamba');
INSERT INTO "country" ("id", "name") VALUES ('lah', 'landa');
INSERT INTO "country" ("id", "name") VALUES ('lo', 'laoški');
INSERT INTO "country" ("id", "name") VALUES ('la', 'latinski');
INSERT INTO "country" ("id", "name") VALUES ('lv', 'letonski');
INSERT INTO "country" ("id", "name") VALUES ('lez', 'lezgian');
INSERT INTO "country" ("id", "name") VALUES ('li', 'limburgiš');
INSERT INTO "country" ("id", "name") VALUES ('ln', 'lingala');
INSERT INTO "country" ("id", "name") VALUES ('lt', 'litvanski');
INSERT INTO "country" ("id", "name") VALUES ('jbo', 'lojban');
INSERT INTO "country" ("id", "name") VALUES ('loz', 'lozi');
INSERT INTO "country" ("id", "name") VALUES ('lu', 'luba-katanga');
INSERT INTO "country" ("id", "name") VALUES ('lua', 'luba-lulua');
INSERT INTO "country" ("id", "name") VALUES ('lui', 'luiseno');
INSERT INTO "country" ("id", "name") VALUES ('lb', 'luksemburški');
INSERT INTO "country" ("id", "name") VALUES ('smj', 'lule sami');
INSERT INTO "country" ("id", "name") VALUES ('lun', 'lunda');
INSERT INTO "country" ("id", "name") VALUES ('luo', 'luo');
INSERT INTO "country" ("id", "name") VALUES ('lus', 'lušai');
INSERT INTO "country" ("id", "name") VALUES ('mad', 'madureški');
INSERT INTO "country" ("id", "name") VALUES ('hu', 'mađarski');
INSERT INTO "country" ("id", "name") VALUES ('mag', 'magahi');
INSERT INTO "country" ("id", "name") VALUES ('moh', 'mahavski');
INSERT INTO "country" ("id", "name") VALUES ('mai', 'maitili');
INSERT INTO "country" ("id", "name") VALUES ('myn', 'majanski jezik');
INSERT INTO "country" ("id", "name") VALUES ('mak', 'makasar');
INSERT INTO "country" ("id", "name") VALUES ('mk', 'makedonski');
INSERT INTO "country" ("id", "name") VALUES ('mg', 'malagazijski');
INSERT INTO "country" ("id", "name") VALUES ('ml', 'malajalam');
INSERT INTO "country" ("id", "name") VALUES ('ms', 'malajski');
INSERT INTO "country" ("id", "name") VALUES ('mnc', 'manču');
INSERT INTO "country" ("id", "name") VALUES ('mdr', 'mandar');
INSERT INTO "country" ("id", "name") VALUES ('man', 'mandingo');
INSERT INTO "country" ("id", "name") VALUES ('mni', 'manipuri');
INSERT INTO "country" ("id", "name") VALUES ('gv', 'manks');
INSERT INTO "country" ("id", "name") VALUES ('mno', 'manobo jezik');
INSERT INTO "country" ("id", "name") VALUES ('mi', 'maorski');
INSERT INTO "country" ("id", "name") VALUES ('mr', 'marati');
INSERT INTO "country" ("id", "name") VALUES ('chm', 'mari');
INSERT INTO "country" ("id", "name") VALUES ('mh', 'maršalski');
INSERT INTO "country" ("id", "name") VALUES ('mwr', 'marvari');
INSERT INTO "country" ("id", "name") VALUES ('mas', 'masai');
INSERT INTO "country" ("id", "name") VALUES ('mt', 'melteški');
INSERT INTO "country" ("id", "name") VALUES ('men', 'mende');
INSERT INTO "country" ("id", "name") VALUES ('mic', 'mikmak');
INSERT INTO "country" ("id", "name") VALUES ('min', 'minangkabau');
INSERT INTO "country" ("id", "name") VALUES ('mwl', 'mirandeški');
INSERT INTO "country" ("id", "name") VALUES ('mdf', 'mokša');
INSERT INTO "country" ("id", "name") VALUES ('mo', 'moldavski');
INSERT INTO "country" ("id", "name") VALUES ('mkh', 'mon-kmerski jezik');
INSERT INTO "country" ("id", "name") VALUES ('lol', 'mongo');
INSERT INTO "country" ("id", "name") VALUES ('mn', 'mongolski');
INSERT INTO "country" ("id", "name") VALUES ('mos', 'mosi');
INSERT INTO "country" ("id", "name") VALUES ('mun', 'munda jezik');
INSERT INTO "country" ("id", "name") VALUES ('nqo', 'n’ko');
INSERT INTO "country" ("id", "name") VALUES ('nah', 'nahuatl');
INSERT INTO "country" ("id", "name") VALUES ('na', 'nauru');
INSERT INTO "country" ("id", "name") VALUES ('nv', 'navaho');
INSERT INTO "country" ("id", "name") VALUES ('ng', 'ndonga');
INSERT INTO "country" ("id", "name") VALUES ('nap', 'neapolitanski');
INSERT INTO "country" ("id", "name") VALUES ('ne', 'nepalski');
INSERT INTO "country" ("id", "name") VALUES ('und', 'nepoznati ili nevažeći jezik');
INSERT INTO "country" ("id", "name") VALUES ('new', 'nevari');
INSERT INTO "country" ("id", "name") VALUES ('nia', 'nias');
INSERT INTO "country" ("id", "name") VALUES ('nic', 'niger-kordofanijski jezik');
INSERT INTO "country" ("id", "name") VALUES ('ssa', 'nilo-saharski jezik');
INSERT INTO "country" ("id", "name") VALUES ('nds', 'niski nemački');
INSERT INTO "country" ("id", "name") VALUES ('dsb', 'niski sorbijanski');
INSERT INTO "country" ("id", "name") VALUES ('niu', 'niuean');
INSERT INTO "country" ("id", "name") VALUES ('nog', 'nogai');
INSERT INTO "country" ("id", "name") VALUES ('no', 'norveški');
INSERT INTO "country" ("id", "name") VALUES ('nb', 'norveški bokmål');
INSERT INTO "country" ("id", "name") VALUES ('nn', 'norveški njorsk');
INSERT INTO "country" ("id", "name") VALUES ('nub', 'nubijski jezik');
INSERT INTO "country" ("id", "name") VALUES ('nzi', 'nzima');
INSERT INTO "country" ("id", "name") VALUES ('nym', 'njamvezi');
INSERT INTO "country" ("id", "name") VALUES ('nyn', 'njankole');
INSERT INTO "country" ("id", "name") VALUES ('ny', 'njanja');
INSERT INTO "country" ("id", "name") VALUES ('tog', 'njasa tonga');
INSERT INTO "country" ("id", "name") VALUES ('de', 'njemački');
INSERT INTO "country" ("id", "name") VALUES ('nyo', 'njoro');
INSERT INTO "country" ("id", "name") VALUES ('oj', 'ojibva');
INSERT INTO "country" ("id", "name") VALUES ('or', 'orijski');
INSERT INTO "country" ("id", "name") VALUES ('om', 'oromo');
INSERT INTO "country" ("id", "name") VALUES ('osa', 'osage');
INSERT INTO "country" ("id", "name") VALUES ('os', 'osetski');
INSERT INTO "country" ("id", "name") VALUES ('oto', 'otomanski jezik');
INSERT INTO "country" ("id", "name") VALUES ('ota', 'otomanski turski');
INSERT INTO "country" ("id", "name") VALUES ('pal', 'pahlavi');
INSERT INTO "country" ("id", "name") VALUES ('pau', 'palauanski');
INSERT INTO "country" ("id", "name") VALUES ('pi', 'pali');
INSERT INTO "country" ("id", "name") VALUES ('pam', 'pampanga');
INSERT INTO "country" ("id", "name") VALUES ('pa', 'pandžabski');
INSERT INTO "country" ("id", "name") VALUES ('pag', 'pangasinski');
INSERT INTO "country" ("id", "name") VALUES ('pap', 'papiamento');
INSERT INTO "country" ("id", "name") VALUES ('paa', 'papuanski jezik');
INSERT INTO "country" ("id", "name") VALUES ('ps', 'paštunski');
INSERT INTO "country" ("id", "name") VALUES ('fa', 'persijski');
INSERT INTO "country" ("id", "name") VALUES ('pl', 'poljski');
INSERT INTO "country" ("id", "name") VALUES ('pon', 'ponpejski');
INSERT INTO "country" ("id", "name") VALUES ('pt', 'portugalski');
INSERT INTO "country" ("id", "name") VALUES ('pra', 'prakritski jezik');
INSERT INTO "country" ("id", "name") VALUES ('oc', 'provansalski');
INSERT INTO "country" ("id", "name") VALUES ('raj', 'rađastani');
INSERT INTO "country" ("id", "name") VALUES ('rap', 'rapanui');
INSERT INTO "country" ("id", "name") VALUES ('rar', 'rarotongan');
INSERT INTO "country" ("id", "name") VALUES ('mis', 'razni jezici');
INSERT INTO "country" ("id", "name") VALUES ('rm', 'reto-romanski');
INSERT INTO "country" ("id", "name") VALUES ('rom', 'romani');
INSERT INTO "country" ("id", "name") VALUES ('roa', 'romanski jezik');
INSERT INTO "country" ("id", "name") VALUES ('ro', 'rumunski');
INSERT INTO "country" ("id", "name") VALUES ('root', 'run');
INSERT INTO "country" ("id", "name") VALUES ('rn', 'rundi');
INSERT INTO "country" ("id", "name") VALUES ('ru', 'ruski');
INSERT INTO "country" ("id", "name") VALUES ('sal', 'sališanski jezik');
INSERT INTO "country" ("id", "name") VALUES ('sam', 'samaritanski aramejski');
INSERT INTO "country" ("id", "name") VALUES ('smi', 'sami jezik');
INSERT INTO "country" ("id", "name") VALUES ('sm', 'samoanski');
INSERT INTO "country" ("id", "name") VALUES ('sad', 'sandave');
INSERT INTO "country" ("id", "name") VALUES ('sg', 'sango');
INSERT INTO "country" ("id", "name") VALUES ('sa', 'sanskrit');
INSERT INTO "country" ("id", "name") VALUES ('sat', 'santali');
INSERT INTO "country" ("id", "name") VALUES ('sc', 'sardinijski');
INSERT INTO "country" ("id", "name") VALUES ('sas', 'sasak');
INSERT INTO "country" ("id", "name") VALUES ('sel', 'selkap');
INSERT INTO "country" ("id", "name") VALUES ('sem', 'semitski jezik');
INSERT INTO "country" ("id", "name") VALUES ('srr', 'serer');
INSERT INTO "country" ("id", "name") VALUES ('st', 'sesoto');
INSERT INTO "country" ("id", "name") VALUES ('nd', 'severni ndebele');
INSERT INTO "country" ("id", "name") VALUES ('se', 'severni sami');
INSERT INTO "country" ("id", "name") VALUES ('nso', 'severni soto');
INSERT INTO "country" ("id", "name") VALUES ('frr', 'severno-frizijski');
INSERT INTO "country" ("id", "name") VALUES ('scn', 'sicilijanski');
INSERT INTO "country" ("id", "name") VALUES ('ii', 'sičuan ji');
INSERT INTO "country" ("id", "name") VALUES ('sid', 'sidamo');
INSERT INTO "country" ("id", "name") VALUES ('bla', 'siksika');
INSERT INTO "country" ("id", "name") VALUES ('sd', 'sindi');
INSERT INTO "country" ("id", "name") VALUES ('si', 'singaleski');
INSERT INTO "country" ("id", "name") VALUES ('sit', 'sino-tibetanski jezik');
INSERT INTO "country" ("id", "name") VALUES ('syr', 'sirijski');
INSERT INTO "country" ("id", "name") VALUES ('sio', 'siuanski jezik');
INSERT INTO "country" ("id", "name") VALUES ('sms', 'skoltski jezik');
INSERT INTO "country" ("id", "name") VALUES ('den', 'slavski');
INSERT INTO "country" ("id", "name") VALUES ('sk', 'slovački');
INSERT INTO "country" ("id", "name") VALUES ('sl', 'slovenački');
INSERT INTO "country" ("id", "name") VALUES ('sla', 'slovenski jezik');
INSERT INTO "country" ("id", "name") VALUES ('sog', 'sodžijenski');
INSERT INTO "country" ("id", "name") VALUES ('so', 'somalski');
INSERT INTO "country" ("id", "name") VALUES ('son', 'songai');
INSERT INTO "country" ("id", "name") VALUES ('snk', 'soninke');
INSERT INTO "country" ("id", "name") VALUES ('wen', 'sorbijanski jezik');
INSERT INTO "country" ("id", "name") VALUES ('srn', 'srananski tongo');
INSERT INTO "country" ("id", "name") VALUES ('enm', 'srednji engleski');
INSERT INTO "country" ("id", "name") VALUES ('frm', 'srednji francuski');
INSERT INTO "country" ("id", "name") VALUES ('dum', 'srednji holandski');
INSERT INTO "country" ("id", "name") VALUES ('mga', 'srednji irski');
INSERT INTO "country" ("id", "name") VALUES ('gmh', 'srednji visoki nemački');
INSERT INTO "country" ("id", "name") VALUES ('sr', 'srpski');
INSERT INTO "country" ("id", "name") VALUES ('sh', 'srpskohrvatski');
INSERT INTO "country" ("id", "name") VALUES ('non', 'stari norski');
INSERT INTO "country" ("id", "name") VALUES ('egy', 'staroegipatski');
INSERT INTO "country" ("id", "name") VALUES ('ang', 'staroengleski');
INSERT INTO "country" ("id", "name") VALUES ('fro', 'starofrancuski');
INSERT INTO "country" ("id", "name") VALUES ('grc', 'starogrčki');
INSERT INTO "country" ("id", "name") VALUES ('sga', 'staroirski');
INSERT INTO "country" ("id", "name") VALUES ('goh', 'staronemački');
INSERT INTO "country" ("id", "name") VALUES ('peo', 'staropersijski');
INSERT INTO "country" ("id", "name") VALUES ('pro', 'staroprovansalski');
INSERT INTO "country" ("id", "name") VALUES ('cu', 'staroslovenski');
INSERT INTO "country" ("id", "name") VALUES ('su', 'sudanski');
INSERT INTO "country" ("id", "name") VALUES ('suk', 'sukuma');
INSERT INTO "country" ("id", "name") VALUES ('sux', 'sumerski');
INSERT INTO "country" ("id", "name") VALUES ('sus', 'susu');
INSERT INTO "country" ("id", "name") VALUES ('sw', 'svahili');
INSERT INTO "country" ("id", "name") VALUES ('ss', 'svati');
INSERT INTO "country" ("id", "name") VALUES ('shn', 'šan');
INSERT INTO "country" ("id", "name") VALUES ('sco', 'škotski');
INSERT INTO "country" ("id", "name") VALUES ('gd', 'škotski galski');
INSERT INTO "country" ("id", "name") VALUES ('sn', 'šona');
INSERT INTO "country" ("id", "name") VALUES ('es', 'španjolski');
INSERT INTO "country" ("id", "name") VALUES ('gsw', 'švajcarsko nemački');
INSERT INTO "country" ("id", "name") VALUES ('sv', 'švedski');
INSERT INTO "country" ("id", "name") VALUES ('tg', 'tađik');
INSERT INTO "country" ("id", "name") VALUES ('tl', 'tagalski');
INSERT INTO "country" ("id", "name") VALUES ('ty', 'tahićanski');
INSERT INTO "country" ("id", "name") VALUES ('tai', 'tai jezik');
INSERT INTO "country" ("id", "name") VALUES ('th', 'tajlandski');
INSERT INTO "country" ("id", "name") VALUES ('it', 'talijanski');
INSERT INTO "country" ("id", "name") VALUES ('tmh', 'tamašek');
INSERT INTO "country" ("id", "name") VALUES ('ta', 'tamilski');
INSERT INTO "country" ("id", "name") VALUES ('tt', 'tatarski');
INSERT INTO "country" ("id", "name") VALUES ('te', 'telugu');
INSERT INTO "country" ("id", "name") VALUES ('ter', 'tereno');
INSERT INTO "country" ("id", "name") VALUES ('tet', 'tetum');
INSERT INTO "country" ("id", "name") VALUES ('bo', 'tibetanski');
INSERT INTO "country" ("id", "name") VALUES ('tig', 'tigre');
INSERT INTO "country" ("id", "name") VALUES ('ti', 'tigrinja');
INSERT INTO "country" ("id", "name") VALUES ('tem', 'timne');
INSERT INTO "country" ("id", "name") VALUES ('tiv', 'tiv');
INSERT INTO "country" ("id", "name") VALUES ('kcg', 'tjap');
INSERT INTO "country" ("id", "name") VALUES ('tli', 'tlingit');
INSERT INTO "country" ("id", "name") VALUES ('tpi', 'tok pisin');
INSERT INTO "country" ("id", "name") VALUES ('tkl', 'tokelau');
INSERT INTO "country" ("id", "name") VALUES ('to', 'tonga');
INSERT INTO "country" ("id", "name") VALUES ('tsi', 'tsimšian');
INSERT INTO "country" ("id", "name") VALUES ('ts', 'tsonga');
INSERT INTO "country" ("id", "name") VALUES ('tn', 'tsvana');
INSERT INTO "country" ("id", "name") VALUES ('tum', 'tumbuka');
INSERT INTO "country" ("id", "name") VALUES ('tup', 'tupi jezik');
INSERT INTO "country" ("id", "name") VALUES ('tk', 'turkmenski');
INSERT INTO "country" ("id", "name") VALUES ('tr', 'turski');
INSERT INTO "country" ("id", "name") VALUES ('tvl', 'tuvalu');
INSERT INTO "country" ("id", "name") VALUES ('tyv', 'tuvinijski');
INSERT INTO "country" ("id", "name") VALUES ('tw', 'tvi');
INSERT INTO "country" ("id", "name") VALUES ('udm', 'udmurt');
INSERT INTO "country" ("id", "name") VALUES ('uga', 'ugaritski');
INSERT INTO "country" ("id", "name") VALUES ('fiu', 'ugro-finski jezik');
INSERT INTO "country" ("id", "name") VALUES ('ug', 'ujgurski');
INSERT INTO "country" ("id", "name") VALUES ('uk', 'ukrajinski');
INSERT INTO "country" ("id", "name") VALUES ('umb', 'umbundu');
INSERT INTO "country" ("id", "name") VALUES ('ur', 'urdu');
INSERT INTO "country" ("id", "name") VALUES ('uz', 'uzbečki');
INSERT INTO "country" ("id", "name") VALUES ('vai', 'vai');
INSERT INTO "country" ("id", "name") VALUES ('wak', 'vakašanski jezik');
INSERT INTO "country" ("id", "name") VALUES ('wal', 'valamo');
INSERT INTO "country" ("id", "name") VALUES ('wa', 'valun');
INSERT INTO "country" ("id", "name") VALUES ('war', 'varej');
INSERT INTO "country" ("id", "name") VALUES ('was', 'vašo');
INSERT INTO "country" ("id", "name") VALUES ('cy', 'velški');
INSERT INTO "country" ("id", "name") VALUES ('ve', 'venda');
INSERT INTO "country" ("id", "name") VALUES ('art', 'veštački');
INSERT INTO "country" ("id", "name") VALUES ('vi', 'vijetnamski');
INSERT INTO "country" ("id", "name") VALUES ('vo', 'volapük');
INSERT INTO "country" ("id", "name") VALUES ('wo', 'volof');
INSERT INTO "country" ("id", "name") VALUES ('vot', 'votski');
INSERT INTO "country" ("id", "name") VALUES ('znd', 'zande');
INSERT INTO "country" ("id", "name") VALUES ('zap', 'zapotečki');
INSERT INTO "country" ("id", "name") VALUES ('zza', 'zaza');
INSERT INTO "country" ("id", "name") VALUES ('zen', 'zenaga');
INSERT INTO "country" ("id", "name") VALUES ('za', 'zuang');
INSERT INTO "country" ("id", "name") VALUES ('zu', 'zulu');
INSERT INTO "country" ("id", "name") VALUES ('zun', 'zuni');
INSERT INTO "country" ("id", "name") VALUES ('kaj', 'žju');
