CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('ab', 'abcházština');
INSERT INTO `country` (`id`, `name`) VALUES ('ach', 'ačoli');
INSERT INTO `country` (`id`, `name`) VALUES ('ada', 'adangme');
INSERT INTO `country` (`id`, `name`) VALUES ('ady', 'adygčina');
INSERT INTO `country` (`id`, `name`) VALUES ('aa', 'afarčina');
INSERT INTO `country` (`id`, `name`) VALUES ('afh', 'afrihili');
INSERT INTO `country` (`id`, `name`) VALUES ('af', 'afrikánčina');
INSERT INTO `country` (`id`, `name`) VALUES ('afa', 'afroázijské jazyky');
INSERT INTO `country` (`id`, `name`) VALUES ('ain', 'ainčina');
INSERT INTO `country` (`id`, `name`) VALUES ('ak', 'akančina');
INSERT INTO `country` (`id`, `name`) VALUES ('akk', 'akkadčina');
INSERT INTO `country` (`id`, `name`) VALUES ('sq', 'albánčina');
INSERT INTO `country` (`id`, `name`) VALUES ('ale', 'aleutčina');
INSERT INTO `country` (`id`, `name`) VALUES ('alg', 'algonkinské jazyky');
INSERT INTO `country` (`id`, `name`) VALUES ('tut', 'altajské jazyky');
INSERT INTO `country` (`id`, `name`) VALUES ('en_US', 'americká angličtina');
INSERT INTO `country` (`id`, `name`) VALUES ('am', 'amharčina');
INSERT INTO `country` (`id`, `name`) VALUES ('anp', 'angika');
INSERT INTO `country` (`id`, `name`) VALUES ('en', 'angličtina');
INSERT INTO `country` (`id`, `name`) VALUES ('apa', 'apačské jazyky');
INSERT INTO `country` (`id`, `name`) VALUES ('ar', 'arabčina');
INSERT INTO `country` (`id`, `name`) VALUES ('an', 'aragónčina');
INSERT INTO `country` (`id`, `name`) VALUES ('arp', 'arapaho');
INSERT INTO `country` (`id`, `name`) VALUES ('arn', 'araukánčina');
INSERT INTO `country` (`id`, `name`) VALUES ('arw', 'arawačtina');
INSERT INTO `country` (`id`, `name`) VALUES ('hy', 'arménčina');
INSERT INTO `country` (`id`, `name`) VALUES ('as', 'ásámčina');
INSERT INTO `country` (`id`, `name`) VALUES ('ast', 'astúrčina');
INSERT INTO `country` (`id`, `name`) VALUES ('ath', 'athabaské jazyky');
INSERT INTO `country` (`id`, `name`) VALUES ('en_AU', 'austrálska angličtina');
INSERT INTO `country` (`id`, `name`) VALUES ('aus', 'austrálske jazyky');
INSERT INTO `country` (`id`, `name`) VALUES ('map', 'austronézske jazyky');
INSERT INTO `country` (`id`, `name`) VALUES ('awa', 'avadhčina');
INSERT INTO `country` (`id`, `name`) VALUES ('av', 'avarčina');
INSERT INTO `country` (`id`, `name`) VALUES ('ae', 'avestčina');
INSERT INTO `country` (`id`, `name`) VALUES ('ay', 'aymarčina');
INSERT INTO `country` (`id`, `name`) VALUES ('az', 'azerbajdžančina');
INSERT INTO `country` (`id`, `name`) VALUES ('ban', 'balijčina');
INSERT INTO `country` (`id`, `name`) VALUES ('bat', 'baltské jazyky');
INSERT INTO `country` (`id`, `name`) VALUES ('bal', 'balúčtina');
INSERT INTO `country` (`id`, `name`) VALUES ('bm', 'bambarčina');
INSERT INTO `country` (`id`, `name`) VALUES ('bai', 'bamileke');
INSERT INTO `country` (`id`, `name`) VALUES ('bnt', 'bantuské jazyky');
INSERT INTO `country` (`id`, `name`) VALUES ('my', 'barmčina');
INSERT INTO `country` (`id`, `name`) VALUES ('bas', 'basa');
INSERT INTO `country` (`id`, `name`) VALUES ('eu', 'baskičtina');
INSERT INTO `country` (`id`, `name`) VALUES ('ba', 'baskirčina');
INSERT INTO `country` (`id`, `name`) VALUES ('btk', 'batacké jazyky');
INSERT INTO `country` (`id`, `name`) VALUES ('bej', 'bedža');
INSERT INTO `country` (`id`, `name`) VALUES ('bem', 'bemba');
INSERT INTO `country` (`id`, `name`) VALUES ('bn', 'bengálčina');
INSERT INTO `country` (`id`, `name`) VALUES ('ber', 'berberské jazyky');
INSERT INTO `country` (`id`, `name`) VALUES ('zxx', 'bez jazykového obsahu');
INSERT INTO `country` (`id`, `name`) VALUES ('bho', 'bhódžpurčina');
INSERT INTO `country` (`id`, `name`) VALUES ('be', 'bieloruština');
INSERT INTO `country` (`id`, `name`) VALUES ('bh', 'bihárske jazyky');
INSERT INTO `country` (`id`, `name`) VALUES ('bik', 'bikol');
INSERT INTO `country` (`id`, `name`) VALUES ('bin', 'bini');
INSERT INTO `country` (`id`, `name`) VALUES ('bi', 'bislama');
INSERT INTO `country` (`id`, `name`) VALUES ('byn', 'blin');
INSERT INTO `country` (`id`, `name`) VALUES ('nb', 'bokmål');
INSERT INTO `country` (`id`, `name`) VALUES ('bs', 'bosniačtina');
INSERT INTO `country` (`id`, `name`) VALUES ('bra', 'bradžčina');
INSERT INTO `country` (`id`, `name`) VALUES ('pt_BR', 'brazílska portugalčina');
INSERT INTO `country` (`id`, `name`) VALUES ('br', 'bretónčina');
INSERT INTO `country` (`id`, `name`) VALUES ('en_GB', 'britská angličtina');
INSERT INTO `country` (`id`, `name`) VALUES ('bug', 'bugiština');
INSERT INTO `country` (`id`, `name`) VALUES ('bg', 'bulharčina');
INSERT INTO `country` (`id`, `name`) VALUES ('bua', 'buriatčina');
INSERT INTO `country` (`id`, `name`) VALUES ('ceb', 'cebuánčina');
INSERT INTO `country` (`id`, `name`) VALUES ('cu', 'cirkevná slovančina');
INSERT INTO `country` (`id`, `name`) VALUES ('chg', 'čagatajčina');
INSERT INTO `country` (`id`, `name`) VALUES ('cmc', 'čamaské jazyky');
INSERT INTO `country` (`id`, `name`) VALUES ('ch', 'čamorčina');
INSERT INTO `country` (`id`, `name`) VALUES ('ce', 'čečenčina');
INSERT INTO `country` (`id`, `name`) VALUES ('chy', 'čejenčina');
INSERT INTO `country` (`id`, `name`) VALUES ('chr', 'čerokí');
INSERT INTO `country` (`id`, `name`) VALUES ('cs', 'čeština');
INSERT INTO `country` (`id`, `name`) VALUES ('ny', 'čewa');
INSERT INTO `country` (`id`, `name`) VALUES ('chb', 'čibča');
INSERT INTO `country` (`id`, `name`) VALUES ('zh', 'čínština');
INSERT INTO `country` (`id`, `name`) VALUES ('chn', 'činucký žargón');
INSERT INTO `country` (`id`, `name`) VALUES ('chp', 'čipevajčina');
INSERT INTO `country` (`id`, `name`) VALUES ('cho', 'čoktavčina');
INSERT INTO `country` (`id`, `name`) VALUES ('za', 'čuangčina');
INSERT INTO `country` (`id`, `name`) VALUES ('cv', 'čuvaština');
INSERT INTO `country` (`id`, `name`) VALUES ('dak', 'dakotčina');
INSERT INTO `country` (`id`, `name`) VALUES ('da', 'dánčina');
INSERT INTO `country` (`id`, `name`) VALUES ('dar', 'darginčina');
INSERT INTO `country` (`id`, `name`) VALUES ('del', 'delawarčina');
INSERT INTO `country` (`id`, `name`) VALUES ('din', 'dinka');
INSERT INTO `country` (`id`, `name`) VALUES ('dv', 'divehi');
INSERT INTO `country` (`id`, `name`) VALUES ('doi', 'dógrí');
INSERT INTO `country` (`id`, `name`) VALUES ('dgr', 'dogribčina');
INSERT INTO `country` (`id`, `name`) VALUES ('dra', 'drávidské jazyky');
INSERT INTO `country` (`id`, `name`) VALUES ('dua', 'duala');
INSERT INTO `country` (`id`, `name`) VALUES ('dyu', 'ďula');
INSERT INTO `country` (`id`, `name`) VALUES ('dz', 'dzongkä');
INSERT INTO `country` (`id`, `name`) VALUES ('efi', 'efik');
INSERT INTO `country` (`id`, `name`) VALUES ('eka', 'ekadžuk');
INSERT INTO `country` (`id`, `name`) VALUES ('elx', 'elamčina');
INSERT INTO `country` (`id`, `name`) VALUES ('myv', 'erzjančina');
INSERT INTO `country` (`id`, `name`) VALUES ('eo', 'esperanto');
INSERT INTO `country` (`id`, `name`) VALUES ('et', 'estónčina');
INSERT INTO `country` (`id`, `name`) VALUES ('ee', 'eweština');
INSERT INTO `country` (`id`, `name`) VALUES ('ewo', 'ewondo');
INSERT INTO `country` (`id`, `name`) VALUES ('fo', 'faerčina');
INSERT INTO `country` (`id`, `name`) VALUES ('fan', 'fangčina');
INSERT INTO `country` (`id`, `name`) VALUES ('fat', 'fanti');
INSERT INTO `country` (`id`, `name`) VALUES ('fj', 'fidžijčina');
INSERT INTO `country` (`id`, `name`) VALUES ('fil', 'filipínčina');
INSERT INTO `country` (`id`, `name`) VALUES ('fi', 'fínčina');
INSERT INTO `country` (`id`, `name`) VALUES ('nl_BE', 'flámčina');
INSERT INTO `country` (`id`, `name`) VALUES ('fon', 'fončina');
INSERT INTO `country` (`id`, `name`) VALUES ('fr', 'francúzština');
INSERT INTO `country` (`id`, `name`) VALUES ('fur', 'friulčina');
INSERT INTO `country` (`id`, `name`) VALUES ('ff', 'fulbčina');
INSERT INTO `country` (`id`, `name`) VALUES ('gaa', 'ga');
INSERT INTO `country` (`id`, `name`) VALUES ('gl', 'galícijčina');
INSERT INTO `country` (`id`, `name`) VALUES ('lg', 'gandčina');
INSERT INTO `country` (`id`, `name`) VALUES ('gay', 'gayo');
INSERT INTO `country` (`id`, `name`) VALUES ('gba', 'gbaja');
INSERT INTO `country` (`id`, `name`) VALUES ('gem', 'germánske jazyky');
INSERT INTO `country` (`id`, `name`) VALUES ('got', 'gótčina');
INSERT INTO `country` (`id`, `name`) VALUES ('el', 'gréčtina');
INSERT INTO `country` (`id`, `name`) VALUES ('kl', 'grónska eskimáčtina');
INSERT INTO `country` (`id`, `name`) VALUES ('ka', 'gruzínčina');
INSERT INTO `country` (`id`, `name`) VALUES ('gn', 'guaraní');
INSERT INTO `country` (`id`, `name`) VALUES ('gu', 'gudžarátčina');
INSERT INTO `country` (`id`, `name`) VALUES ('ht', 'haitský');
INSERT INTO `country` (`id`, `name`) VALUES ('ha', 'hauština');
INSERT INTO `country` (`id`, `name`) VALUES ('haw', 'havajčina');
INSERT INTO `country` (`id`, `name`) VALUES ('he', 'hebrejčina');
INSERT INTO `country` (`id`, `name`) VALUES ('hz', 'herero');
INSERT INTO `country` (`id`, `name`) VALUES ('hi', 'hindčina');
INSERT INTO `country` (`id`, `name`) VALUES ('ho', 'hiri motu');
INSERT INTO `country` (`id`, `name`) VALUES ('nl', 'holandčina');
INSERT INTO `country` (`id`, `name`) VALUES ('hr', 'chorvátčina');
INSERT INTO `country` (`id`, `name`) VALUES ('pt_PT', 'iberská portugalčina');
INSERT INTO `country` (`id`, `name`) VALUES ('es_ES', 'iberská španielčina');
INSERT INTO `country` (`id`, `name`) VALUES ('ig', 'igboština');
INSERT INTO `country` (`id`, `name`) VALUES ('ine', 'indoeurópske jazyky');
INSERT INTO `country` (`id`, `name`) VALUES ('id', 'indonézština');
INSERT INTO `country` (`id`, `name`) VALUES ('ia', 'interlingua');
INSERT INTO `country` (`id`, `name`) VALUES ('ie', 'interlingue');
INSERT INTO `country` (`id`, `name`) VALUES ('ira', 'iránske jazyky');
INSERT INTO `country` (`id`, `name`) VALUES ('ga', 'írčina');
INSERT INTO `country` (`id`, `name`) VALUES ('is', 'islandčina');
INSERT INTO `country` (`id`, `name`) VALUES ('ja', 'japončina');
INSERT INTO `country` (`id`, `name`) VALUES ('jv', 'jávčina');
INSERT INTO `country` (`id`, `name`) VALUES ('sai', 'jazyk juhoamerických indiánov');
INSERT INTO `country` (`id`, `name`) VALUES ('nai', 'jazyk severoamerických indiánov');
INSERT INTO `country` (`id`, `name`) VALUES ('cai', 'jazyk stredoamerických indiánov');
INSERT INTO `country` (`id`, `name`) VALUES ('yi', 'jidiš');
INSERT INTO `country` (`id`, `name`) VALUES ('yo', 'jorubčina');
INSERT INTO `country` (`id`, `name`) VALUES ('st', 'južná sothčina');
INSERT INTO `country` (`id`, `name`) VALUES ('mh', 'kajin-majol');
INSERT INTO `country` (`id`, `name`) VALUES ('km', 'kambodžská khmérčina');
INSERT INTO `country` (`id`, `name`) VALUES ('en_CA', 'kanadská angličtina');
INSERT INTO `country` (`id`, `name`) VALUES ('fr_CA', 'kanadská francúzština');
INSERT INTO `country` (`id`, `name`) VALUES ('kn', 'kannadčina');
INSERT INTO `country` (`id`, `name`) VALUES ('kr', 'kanurijčina');
INSERT INTO `country` (`id`, `name`) VALUES ('car', 'karibský');
INSERT INTO `country` (`id`, `name`) VALUES ('ks', 'kašmírčina');
INSERT INTO `country` (`id`, `name`) VALUES ('ca', 'katalánčina');
INSERT INTO `country` (`id`, `name`) VALUES ('cau', 'kaukazské jazyky');
INSERT INTO `country` (`id`, `name`) VALUES ('kk', 'kazaština');
INSERT INTO `country` (`id`, `name`) VALUES ('qu', 'kečuánčina');
INSERT INTO `country` (`id`, `name`) VALUES ('cel', 'keltské jazyky');
INSERT INTO `country` (`id`, `name`) VALUES ('ky', 'kirgizština');
INSERT INTO `country` (`id`, `name`) VALUES ('tlh', 'klingónčina');
INSERT INTO `country` (`id`, `name`) VALUES ('kv', 'komijčina');
INSERT INTO `country` (`id`, `name`) VALUES ('kg', 'konžština');
INSERT INTO `country` (`id`, `name`) VALUES ('ko', 'kórejčina');
INSERT INTO `country` (`id`, `name`) VALUES ('kw', 'kornčina');
INSERT INTO `country` (`id`, `name`) VALUES ('co', 'korzičtina');
INSERT INTO `country` (`id`, `name`) VALUES ('cr', 'krí');
INSERT INTO `country` (`id`, `name`) VALUES ('kj', 'kuaňama');
INSERT INTO `country` (`id`, `name`) VALUES ('ku', 'kurdčina');
INSERT INTO `country` (`id`, `name`) VALUES ('lo', 'laoština');
INSERT INTO `country` (`id`, `name`) VALUES ('la', 'latinčina');
INSERT INTO `country` (`id`, `name`) VALUES ('es_419', 'latinskoamerická španielčina');
INSERT INTO `country` (`id`, `name`) VALUES ('ln', 'lingalčina');
INSERT INTO `country` (`id`, `name`) VALUES ('lt', 'litovčina');
INSERT INTO `country` (`id`, `name`) VALUES ('lv', 'lotyština');
INSERT INTO `country` (`id`, `name`) VALUES ('lu', 'luba-katanga');
INSERT INTO `country` (`id`, `name`) VALUES ('lb', 'luxemburčina');
INSERT INTO `country` (`id`, `name`) VALUES ('mk', 'macedónčina');
INSERT INTO `country` (`id`, `name`) VALUES ('hu', 'maďarčina');
INSERT INTO `country` (`id`, `name`) VALUES ('ml', 'malajálamčina');
INSERT INTO `country` (`id`, `name`) VALUES ('ms', 'malajčina');
INSERT INTO `country` (`id`, `name`) VALUES ('mg', 'malgaština');
INSERT INTO `country` (`id`, `name`) VALUES ('mt', 'maltčina');
INSERT INTO `country` (`id`, `name`) VALUES ('gv', 'mančina');
INSERT INTO `country` (`id`, `name`) VALUES ('mi', 'maorijčina');
INSERT INTO `country` (`id`, `name`) VALUES ('mr', 'maráthčina');
INSERT INTO `country` (`id`, `name`) VALUES ('myn', 'mayské jazyky');
INSERT INTO `country` (`id`, `name`) VALUES ('mo', 'moldavčina');
INSERT INTO `country` (`id`, `name`) VALUES ('lol', 'mongo');
INSERT INTO `country` (`id`, `name`) VALUES ('mn', 'mongolčina');
INSERT INTO `country` (`id`, `name`) VALUES ('na', 'nauru');
INSERT INTO `country` (`id`, `name`) VALUES ('nv', 'navajo');
INSERT INTO `country` (`id`, `name`) VALUES ('ng', 'ndonga');
INSERT INTO `country` (`id`, `name`) VALUES ('de', 'nemčina');
INSERT INTO `country` (`id`, `name`) VALUES ('ne', 'nepálčina');
INSERT INTO `country` (`id`, `name`) VALUES ('und', 'neznámy alebo neplatný jazyk');
INSERT INTO `country` (`id`, `name`) VALUES ('no', 'nórčina');
INSERT INTO `country` (`id`, `name`) VALUES ('nn', 'nórsky nynorsk');
INSERT INTO `country` (`id`, `name`) VALUES ('oj', 'odžibva');
INSERT INTO `country` (`id`, `name`) VALUES ('oc', 'okcitánčina');
INSERT INTO `country` (`id`, `name`) VALUES ('om', 'oromčina');
INSERT INTO `country` (`id`, `name`) VALUES ('os', 'osetčina');
INSERT INTO `country` (`id`, `name`) VALUES ('pi', 'pálí');
INSERT INTO `country` (`id`, `name`) VALUES ('pa', 'pandžábčina');
INSERT INTO `country` (`id`, `name`) VALUES ('paa', 'papuánsky');
INSERT INTO `country` (`id`, `name`) VALUES ('ps', 'paštúnčina');
INSERT INTO `country` (`id`, `name`) VALUES ('fa', 'perzština');
INSERT INTO `country` (`id`, `name`) VALUES ('pl', 'poľština');
INSERT INTO `country` (`id`, `name`) VALUES ('pt', 'portugalčina');
INSERT INTO `country` (`id`, `name`) VALUES ('de_AT', 'rakúska nemčina');
INSERT INTO `country` (`id`, `name`) VALUES ('rm', 'rétorománčina');
INSERT INTO `country` (`id`, `name`) VALUES ('ro', 'rumunčina');
INSERT INTO `country` (`id`, `name`) VALUES ('rn', 'rundčina');
INSERT INTO `country` (`id`, `name`) VALUES ('ru', 'ruština');
INSERT INTO `country` (`id`, `name`) VALUES ('rw', 'rwandčina');
INSERT INTO `country` (`id`, `name`) VALUES ('sm', 'samojčina');
INSERT INTO `country` (`id`, `name`) VALUES ('sg', 'sango');
INSERT INTO `country` (`id`, `name`) VALUES ('sa', 'sanskrit');
INSERT INTO `country` (`id`, `name`) VALUES ('sc', 'sardínčina');
INSERT INTO `country` (`id`, `name`) VALUES ('se', 'severná saamčina');
INSERT INTO `country` (`id`, `name`) VALUES ('nso', 'severná sothčina');
INSERT INTO `country` (`id`, `name`) VALUES ('nd', 'severné ndbele');
INSERT INTO `country` (`id`, `name`) VALUES ('scn', 'sicílčina');
INSERT INTO `country` (`id`, `name`) VALUES ('sd', 'sindhčina');
INSERT INTO `country` (`id`, `name`) VALUES ('si', 'sinhalčina');
INSERT INTO `country` (`id`, `name`) VALUES ('den', 'slovančina');
INSERT INTO `country` (`id`, `name`) VALUES ('sk', 'slovenčina');
INSERT INTO `country` (`id`, `name`) VALUES ('sla', 'slovenský jazyk');
INSERT INTO `country` (`id`, `name`) VALUES ('sl', 'slovinčina');
INSERT INTO `country` (`id`, `name`) VALUES ('so', 'somálčina');
INSERT INTO `country` (`id`, `name`) VALUES ('sr', 'srbčina');
INSERT INTO `country` (`id`, `name`) VALUES ('sh', 'srbochorvátčina');
INSERT INTO `country` (`id`, `name`) VALUES ('egy', 'staroegyptský');
INSERT INTO `country` (`id`, `name`) VALUES ('grc', 'starogréčtina');
INSERT INTO `country` (`id`, `name`) VALUES ('sux', 'sumerčina');
INSERT INTO `country` (`id`, `name`) VALUES ('su', 'sundčina');
INSERT INTO `country` (`id`, `name`) VALUES ('ss', 'svazijčina');
INSERT INTO `country` (`id`, `name`) VALUES ('sw', 'swahilčina');
INSERT INTO `country` (`id`, `name`) VALUES ('syr', 'sýrčina');
INSERT INTO `country` (`id`, `name`) VALUES ('gd', 'škótčina');
INSERT INTO `country` (`id`, `name`) VALUES ('sn', 'šončina');
INSERT INTO `country` (`id`, `name`) VALUES ('es', 'španielčina');
INSERT INTO `country` (`id`, `name`) VALUES ('fr_CH', 'švajčiarska francúzština');
INSERT INTO `country` (`id`, `name`) VALUES ('gsw', 'švajčiarska nemčina');
INSERT INTO `country` (`id`, `name`) VALUES ('de_CH', 'švajčiarska spisovná nemčina');
INSERT INTO `country` (`id`, `name`) VALUES ('sv', 'švédčina');
INSERT INTO `country` (`id`, `name`) VALUES ('tg', 'tadžičtina');
INSERT INTO `country` (`id`, `name`) VALUES ('tl', 'tagalčina');
INSERT INTO `country` (`id`, `name`) VALUES ('ty', 'tahitčina');
INSERT INTO `country` (`id`, `name`) VALUES ('it', 'taliančina');
INSERT INTO `country` (`id`, `name`) VALUES ('ta', 'tamilčina');
INSERT INTO `country` (`id`, `name`) VALUES ('tt', 'tatárčina');
INSERT INTO `country` (`id`, `name`) VALUES ('te', 'telugčina');
INSERT INTO `country` (`id`, `name`) VALUES ('tet', 'tetum');
INSERT INTO `country` (`id`, `name`) VALUES ('th', 'thajčina');
INSERT INTO `country` (`id`, `name`) VALUES ('bo', 'tibetčina');
INSERT INTO `country` (`id`, `name`) VALUES ('ti', 'tigrejčina');
INSERT INTO `country` (`id`, `name`) VALUES ('tpi', 'tok pisin');
INSERT INTO `country` (`id`, `name`) VALUES ('to', 'tonžtina');
INSERT INTO `country` (`id`, `name`) VALUES ('zh_Hant', 'tradičná čínština');
INSERT INTO `country` (`id`, `name`) VALUES ('ts', 'tsonga');
INSERT INTO `country` (`id`, `name`) VALUES ('tn', 'tswančina');
INSERT INTO `country` (`id`, `name`) VALUES ('tr', 'turečtina');
INSERT INTO `country` (`id`, `name`) VALUES ('tk', 'turkménčina');
INSERT INTO `country` (`id`, `name`) VALUES ('tw', 'twi');
INSERT INTO `country` (`id`, `name`) VALUES ('fiu', 'ugrofínske jazyky');
INSERT INTO `country` (`id`, `name`) VALUES ('ug', 'ujgurčina');
INSERT INTO `country` (`id`, `name`) VALUES ('uk', 'ukrajinčina');
INSERT INTO `country` (`id`, `name`) VALUES ('art', 'umelý jazyk');
INSERT INTO `country` (`id`, `name`) VALUES ('ur', 'urdčina');
INSERT INTO `country` (`id`, `name`) VALUES ('or', 'uríjčina');
INSERT INTO `country` (`id`, `name`) VALUES ('uz', 'uzbečtina');
INSERT INTO `country` (`id`, `name`) VALUES ('wa', 'valónčina');
INSERT INTO `country` (`id`, `name`) VALUES ('ve', 'vendčina');
INSERT INTO `country` (`id`, `name`) VALUES ('vi', 'vietnamčina');
INSERT INTO `country` (`id`, `name`) VALUES ('vo', 'volapük');
INSERT INTO `country` (`id`, `name`) VALUES ('frs', 'východná frízština');
INSERT INTO `country` (`id`, `name`) VALUES ('cy', 'waleština');
INSERT INTO `country` (`id`, `name`) VALUES ('wo', 'wolof');
INSERT INTO `country` (`id`, `name`) VALUES ('xh', 'xhosa');
INSERT INTO `country` (`id`, `name`) VALUES ('fy', 'západná frízština');
INSERT INTO `country` (`id`, `name`) VALUES ('zh_Hans', 'zjednodušená čínština');
INSERT INTO `country` (`id`, `name`) VALUES ('sgn', 'znaková reč');
INSERT INTO `country` (`id`, `name`) VALUES ('zu', 'zuluština');
