CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('lb', 'Lucemburština');
INSERT INTO [country] ([id], [name]) VALUES ('om', 'Oromo (Afan)');
INSERT INTO [country] ([id], [name]) VALUES ('ps', 'Pashto (Pushto)');
INSERT INTO [country] ([id], [name]) VALUES ('ab', 'abcházština');
INSERT INTO [country] ([id], [name]) VALUES ('ace', 'acehština');
INSERT INTO [country] ([id], [name]) VALUES ('ada', 'adangme');
INSERT INTO [country] ([id], [name]) VALUES ('ady', 'adygejština');
INSERT INTO [country] ([id], [name]) VALUES ('aa', 'afarština');
INSERT INTO [country] ([id], [name]) VALUES ('afh', 'afrihili');
INSERT INTO [country] ([id], [name]) VALUES ('af', 'afrikánština');
INSERT INTO [country] ([id], [name]) VALUES ('afa', 'afroasijské jazyky (jiné)');
INSERT INTO [country] ([id], [name]) VALUES ('ain', 'ainština');
INSERT INTO [country] ([id], [name]) VALUES ('ak', 'akanština');
INSERT INTO [country] ([id], [name]) VALUES ('akk', 'akkadština');
INSERT INTO [country] ([id], [name]) VALUES ('sq', 'albánština');
INSERT INTO [country] ([id], [name]) VALUES ('ale', 'aleutština');
INSERT INTO [country] ([id], [name]) VALUES ('alg', 'algonkinské jazyky (jiné)');
INSERT INTO [country] ([id], [name]) VALUES ('tut', 'altajské jazyky (jiné)');
INSERT INTO [country] ([id], [name]) VALUES ('am', 'amharština');
INSERT INTO [country] ([id], [name]) VALUES ('anp', 'angika');
INSERT INTO [country] ([id], [name]) VALUES ('en_CA', 'anglicky (Kanada)');
INSERT INTO [country] ([id], [name]) VALUES ('en', 'angličtina');
INSERT INTO [country] ([id], [name]) VALUES ('en_US', 'angličtina (USA)');
INSERT INTO [country] ([id], [name]) VALUES ('apa', 'apačské jazyky');
INSERT INTO [country] ([id], [name]) VALUES ('ar', 'arabština');
INSERT INTO [country] ([id], [name]) VALUES ('an', 'aragonština');
INSERT INTO [country] ([id], [name]) VALUES ('arc', 'aramejština');
INSERT INTO [country] ([id], [name]) VALUES ('arp', 'arapažština');
INSERT INTO [country] ([id], [name]) VALUES ('arn', 'araukánština');
INSERT INTO [country] ([id], [name]) VALUES ('arw', 'arawacké jazyky');
INSERT INTO [country] ([id], [name]) VALUES ('hy', 'arménština');
INSERT INTO [country] ([id], [name]) VALUES ('as', 'assaméština');
INSERT INTO [country] ([id], [name]) VALUES ('ath', 'athapaskánské jazyky');
INSERT INTO [country] ([id], [name]) VALUES ('aus', 'australské jazyky');
INSERT INTO [country] ([id], [name]) VALUES ('map', 'austronéské jazyky (jiné)');
INSERT INTO [country] ([id], [name]) VALUES ('av', 'avarština');
INSERT INTO [country] ([id], [name]) VALUES ('ae', 'avestánština');
INSERT INTO [country] ([id], [name]) VALUES ('awa', 'awadhština');
INSERT INTO [country] ([id], [name]) VALUES ('ay', 'aymárština');
INSERT INTO [country] ([id], [name]) VALUES ('az', 'azerbajdžánština');
INSERT INTO [country] ([id], [name]) VALUES ('ach', 'ačoli');
INSERT INTO [country] ([id], [name]) VALUES ('ban', 'balijština');
INSERT INTO [country] ([id], [name]) VALUES ('bat', 'baltské jazyky (jiné)');
INSERT INTO [country] ([id], [name]) VALUES ('bal', 'balúčština');
INSERT INTO [country] ([id], [name]) VALUES ('bm', 'bambarština');
INSERT INTO [country] ([id], [name]) VALUES ('bai', 'bamileke (jiné)');
INSERT INTO [country] ([id], [name]) VALUES ('bad', 'banda');
INSERT INTO [country] ([id], [name]) VALUES ('bnt', 'bantuské jazyky (jiné)');
INSERT INTO [country] ([id], [name]) VALUES ('my', 'barmština');
INSERT INTO [country] ([id], [name]) VALUES ('bas', 'basa');
INSERT INTO [country] ([id], [name]) VALUES ('ba', 'baskirština');
INSERT INTO [country] ([id], [name]) VALUES ('eu', 'baskičtina');
INSERT INTO [country] ([id], [name]) VALUES ('btk', 'batačtina');
INSERT INTO [country] ([id], [name]) VALUES ('bej', 'bedža');
INSERT INTO [country] ([id], [name]) VALUES ('bem', 'bembštiva');
INSERT INTO [country] ([id], [name]) VALUES ('bn', 'bengálština');
INSERT INTO [country] ([id], [name]) VALUES ('ber', 'berberské jazyky (jiné)');
INSERT INTO [country] ([id], [name]) VALUES ('bho', 'bhojpurština');
INSERT INTO [country] ([id], [name]) VALUES ('dz', 'bhútánština');
INSERT INTO [country] ([id], [name]) VALUES ('bh', 'biharština');
INSERT INTO [country] ([id], [name]) VALUES ('bik', 'bikolština');
INSERT INTO [country] ([id], [name]) VALUES ('bin', 'bini');
INSERT INTO [country] ([id], [name]) VALUES ('bi', 'bislámština');
INSERT INTO [country] ([id], [name]) VALUES ('bs', 'bosenština');
INSERT INTO [country] ([id], [name]) VALUES ('bra', 'bradžština');
INSERT INTO [country] ([id], [name]) VALUES ('br', 'bretaňština');
INSERT INTO [country] ([id], [name]) VALUES ('bug', 'bugiština');
INSERT INTO [country] ([id], [name]) VALUES ('bg', 'bulharština');
INSERT INTO [country] ([id], [name]) VALUES ('bua', 'burjatština');
INSERT INTO [country] ([id], [name]) VALUES ('be', 'běloruština');
INSERT INTO [country] ([id], [name]) VALUES ('cad', 'caddo');
INSERT INTO [country] ([id], [name]) VALUES ('ceb', 'cebuánština');
INSERT INTO [country] ([id], [name]) VALUES ('chr', 'cherokee');
INSERT INTO [country] ([id], [name]) VALUES ('hit', 'chetitština');
INSERT INTO [country] ([id], [name]) VALUES ('chp', 'chipewyan');
INSERT INTO [country] ([id], [name]) VALUES ('cho', 'choctawština');
INSERT INTO [country] ([id], [name]) VALUES ('hr', 'chorvatština');
INSERT INTO [country] ([id], [name]) VALUES ('kho', 'chotánština');
INSERT INTO [country] ([id], [name]) VALUES ('day', 'dajáčtina');
INSERT INTO [country] ([id], [name]) VALUES ('dak', 'dakotština');
INSERT INTO [country] ([id], [name]) VALUES ('del', 'delaware');
INSERT INTO [country] ([id], [name]) VALUES ('din', 'dinkština');
INSERT INTO [country] ([id], [name]) VALUES ('dv', 'divehi');
INSERT INTO [country] ([id], [name]) VALUES ('dyu', 'djula');
INSERT INTO [country] ([id], [name]) VALUES ('dgr', 'dogrib');
INSERT INTO [country] ([id], [name]) VALUES ('nds', 'dolnoněmčina');
INSERT INTO [country] ([id], [name]) VALUES ('dra', 'drávidské jazyky (jiné)');
INSERT INTO [country] ([id], [name]) VALUES ('dua', 'dualština');
INSERT INTO [country] ([id], [name]) VALUES ('da', 'dánština');
INSERT INTO [country] ([id], [name]) VALUES ('doi', 'dórgí');
INSERT INTO [country] ([id], [name]) VALUES ('efi', 'efik');
INSERT INTO [country] ([id], [name]) VALUES ('egy', 'egyptština stará');
INSERT INTO [country] ([id], [name]) VALUES ('eka', 'ekajuk');
INSERT INTO [country] ([id], [name]) VALUES ('elx', 'elamitština');
INSERT INTO [country] ([id], [name]) VALUES ('eo', 'esperanto');
INSERT INTO [country] ([id], [name]) VALUES ('et', 'estonština');
INSERT INTO [country] ([id], [name]) VALUES ('ee', 'eweština');
INSERT INTO [country] ([id], [name]) VALUES ('ewo', 'ewondo');
INSERT INTO [country] ([id], [name]) VALUES ('fo', 'faerština');
INSERT INTO [country] ([id], [name]) VALUES ('fan', 'fang');
INSERT INTO [country] ([id], [name]) VALUES ('fat', 'fantština');
INSERT INTO [country] ([id], [name]) VALUES ('fj', 'fidži');
INSERT INTO [country] ([id], [name]) VALUES ('phi', 'filipínské jazyky (jiné)');
INSERT INTO [country] ([id], [name]) VALUES ('fi', 'finština');
INSERT INTO [country] ([id], [name]) VALUES ('fr_CA', 'francouzsky (Kanada)');
INSERT INTO [country] ([id], [name]) VALUES ('fr', 'francouzština');
INSERT INTO [country] ([id], [name]) VALUES ('fy', 'fríština');
INSERT INTO [country] ([id], [name]) VALUES ('ff', 'fulahština');
INSERT INTO [country] ([id], [name]) VALUES ('fur', 'furlandština');
INSERT INTO [country] ([id], [name]) VALUES ('phn', 'féničtina');
INSERT INTO [country] ([id], [name]) VALUES ('gaa', 'ga');
INSERT INTO [country] ([id], [name]) VALUES ('lg', 'ganda');
INSERT INTO [country] ([id], [name]) VALUES ('gay', 'gayo');
INSERT INTO [country] ([id], [name]) VALUES ('gba', 'gbaja');
INSERT INTO [country] ([id], [name]) VALUES ('gez', 'geez');
INSERT INTO [country] ([id], [name]) VALUES ('gem', 'germánské jazyky (jiné)');
INSERT INTO [country] ([id], [name]) VALUES ('gor', 'gorontalo');
INSERT INTO [country] ([id], [name]) VALUES ('grb', 'grebo');
INSERT INTO [country] ([id], [name]) VALUES ('ka', 'gruzínština');
INSERT INTO [country] ([id], [name]) VALUES ('kl', 'grónština');
INSERT INTO [country] ([id], [name]) VALUES ('gn', 'guaranština');
INSERT INTO [country] ([id], [name]) VALUES ('gu', 'gujaratština');
INSERT INTO [country] ([id], [name]) VALUES ('gwi', 'gwichʼin');
INSERT INTO [country] ([id], [name]) VALUES ('gon', 'góndština');
INSERT INTO [country] ([id], [name]) VALUES ('got', 'gótština');
INSERT INTO [country] ([id], [name]) VALUES ('hai', 'haida');
INSERT INTO [country] ([id], [name]) VALUES ('gl', 'haličština');
INSERT INTO [country] ([id], [name]) VALUES ('ha', 'hausa');
INSERT INTO [country] ([id], [name]) VALUES ('haw', 'havajský');
INSERT INTO [country] ([id], [name]) VALUES ('he', 'hebrejština');
INSERT INTO [country] ([id], [name]) VALUES ('hz', 'herero');
INSERT INTO [country] ([id], [name]) VALUES ('hil', 'hiligayonština');
INSERT INTO [country] ([id], [name]) VALUES ('him', 'himáčalština');
INSERT INTO [country] ([id], [name]) VALUES ('hi', 'hindština');
INSERT INTO [country] ([id], [name]) VALUES ('ho', 'hiri motu');
INSERT INTO [country] ([id], [name]) VALUES ('hmn', 'hmongština');
INSERT INTO [country] ([id], [name]) VALUES ('gmh', 'hornoněmčina stará');
INSERT INTO [country] ([id], [name]) VALUES ('hup', 'hupa');
INSERT INTO [country] ([id], [name]) VALUES ('iba', 'iban');
INSERT INTO [country] ([id], [name]) VALUES ('ijo', 'idžo');
INSERT INTO [country] ([id], [name]) VALUES ('ig', 'igboština');
INSERT INTO [country] ([id], [name]) VALUES ('ilo', 'ilokánština');
INSERT INTO [country] ([id], [name]) VALUES ('inc', 'indické jazyky (jiné)');
INSERT INTO [country] ([id], [name]) VALUES ('ine', 'indoevropské jazyky (jiné)');
INSERT INTO [country] ([id], [name]) VALUES ('id', 'indonéština');
INSERT INTO [country] ([id], [name]) VALUES ('inh', 'inguština');
INSERT INTO [country] ([id], [name]) VALUES ('ia', 'interlingua');
INSERT INTO [country] ([id], [name]) VALUES ('ie', 'interlingue');
INSERT INTO [country] ([id], [name]) VALUES ('iu', 'inuktitutština');
INSERT INTO [country] ([id], [name]) VALUES ('ik', 'inupiakština');
INSERT INTO [country] ([id], [name]) VALUES ('iro', 'irokézské jazyky (jiné)');
INSERT INTO [country] ([id], [name]) VALUES ('ga', 'irština');
INSERT INTO [country] ([id], [name]) VALUES ('is', 'islandština');
INSERT INTO [country] ([id], [name]) VALUES ('it', 'italština');
INSERT INTO [country] ([id], [name]) VALUES ('sah', 'jakutština');
INSERT INTO [country] ([id], [name]) VALUES ('yao', 'jaoština');
INSERT INTO [country] ([id], [name]) VALUES ('ja', 'japonština');
INSERT INTO [country] ([id], [name]) VALUES ('jv', 'javánština');
INSERT INTO [country] ([id], [name]) VALUES ('yi', 'jidiš');
INSERT INTO [country] ([id], [name]) VALUES ('sai', 'jihoamerické indiánské jazyky (jiné)');
INSERT INTO [country] ([id], [name]) VALUES ('kbd', 'kabardinština');
INSERT INTO [country] ([id], [name]) VALUES ('kab', 'kabylština');
INSERT INTO [country] ([id], [name]) VALUES ('xal', 'kalmyčtina');
INSERT INTO [country] ([id], [name]) VALUES ('km', 'kambodžština');
INSERT INTO [country] ([id], [name]) VALUES ('kam', 'kambština');
INSERT INTO [country] ([id], [name]) VALUES ('kn', 'kannadština');
INSERT INTO [country] ([id], [name]) VALUES ('kr', 'kanuri');
INSERT INTO [country] ([id], [name]) VALUES ('kaa', 'karakalpačtina');
INSERT INTO [country] ([id], [name]) VALUES ('kar', 'karenština');
INSERT INTO [country] ([id], [name]) VALUES ('car', 'karibština');
INSERT INTO [country] ([id], [name]) VALUES ('ca', 'katalánština');
INSERT INTO [country] ([id], [name]) VALUES ('cau', 'kavkazské jazyky (jiné)');
INSERT INTO [country] ([id], [name]) VALUES ('kaw', 'kawi');
INSERT INTO [country] ([id], [name]) VALUES ('kk', 'kazachština');
INSERT INTO [country] ([id], [name]) VALUES ('kac', 'kačijština');
INSERT INTO [country] ([id], [name]) VALUES ('ks', 'kašmírština');
INSERT INTO [country] ([id], [name]) VALUES ('cel', 'keltské jazyky (jiné)');
INSERT INTO [country] ([id], [name]) VALUES ('qu', 'kečuánština');
INSERT INTO [country] ([id], [name]) VALUES ('khi', 'khoisanské jazyky (jiné)');
INSERT INTO [country] ([id], [name]) VALUES ('kha', 'khásí');
INSERT INTO [country] ([id], [name]) VALUES ('ki', 'kikujština');
INSERT INTO [country] ([id], [name]) VALUES ('kmb', 'kimbundština');
INSERT INTO [country] ([id], [name]) VALUES ('rw', 'kinyarwandština');
INSERT INTO [country] ([id], [name]) VALUES ('ky', 'kirgizština');
INSERT INTO [country] ([id], [name]) VALUES ('gil', 'kiribatština');
INSERT INTO [country] ([id], [name]) VALUES ('rn', 'kirundi');
INSERT INTO [country] ([id], [name]) VALUES ('tlh', 'klingonština');
INSERT INTO [country] ([id], [name]) VALUES ('kv', 'komijština');
INSERT INTO [country] ([id], [name]) VALUES ('kg', 'konžština');
INSERT INTO [country] ([id], [name]) VALUES ('cop', 'koptština');
INSERT INTO [country] ([id], [name]) VALUES ('ko', 'korejština');
INSERT INTO [country] ([id], [name]) VALUES ('kw', 'kornština');
INSERT INTO [country] ([id], [name]) VALUES ('co', 'korsičtina');
INSERT INTO [country] ([id], [name]) VALUES ('kos', 'kosrajština');
INSERT INTO [country] ([id], [name]) VALUES ('kpe', 'kpelle');
INSERT INTO [country] ([id], [name]) VALUES ('crp', 'kreolština a jiné pidginy');
INSERT INTO [country] ([id], [name]) VALUES ('cpe', 'kreolština a jiné pidginy na základě angličtiny');
INSERT INTO [country] ([id], [name]) VALUES ('cpf', 'kreolština a jiné pidginy na základě francouzštiny');
INSERT INTO [country] ([id], [name]) VALUES ('cpp', 'kreolština a jiné pidginy na základě portugalštiny');
INSERT INTO [country] ([id], [name]) VALUES ('kro', 'kru');
INSERT INTO [country] ([id], [name]) VALUES ('kru', 'krukukhština');
INSERT INTO [country] ([id], [name]) VALUES ('crh', 'krymská turečtina');
INSERT INTO [country] ([id], [name]) VALUES ('cr', 'krí');
INSERT INTO [country] ([id], [name]) VALUES ('kj', 'kuaňamština');
INSERT INTO [country] ([id], [name]) VALUES ('kum', 'kumyčtina');
INSERT INTO [country] ([id], [name]) VALUES ('ku', 'kurdština');
INSERT INTO [country] ([id], [name]) VALUES ('kut', 'kutenai');
INSERT INTO [country] ([id], [name]) VALUES ('kok', 'kónkánština');
INSERT INTO [country] ([id], [name]) VALUES ('cus', 'kúšitské jazyky (jiné)');
INSERT INTO [country] ([id], [name]) VALUES ('lad', 'ladinština');
INSERT INTO [country] ([id], [name]) VALUES ('lah', 'lahndština');
INSERT INTO [country] ([id], [name]) VALUES ('lam', 'lambština');
INSERT INTO [country] ([id], [name]) VALUES ('lo', 'laoština');
INSERT INTO [country] ([id], [name]) VALUES ('la', 'latina');
INSERT INTO [country] ([id], [name]) VALUES ('lez', 'lezginština');
INSERT INTO [country] ([id], [name]) VALUES ('ln', 'lingalština');
INSERT INTO [country] ([id], [name]) VALUES ('lt', 'litevština');
INSERT INTO [country] ([id], [name]) VALUES ('lus', 'lišáí');
INSERT INTO [country] ([id], [name]) VALUES ('lv', 'lotyština');
INSERT INTO [country] ([id], [name]) VALUES ('loz', 'lozština');
INSERT INTO [country] ([id], [name]) VALUES ('lua', 'luba-luluaština');
INSERT INTO [country] ([id], [name]) VALUES ('lu', 'lubu-katanžština');
INSERT INTO [country] ([id], [name]) VALUES ('lui', 'luiseňo');
INSERT INTO [country] ([id], [name]) VALUES ('lun', 'lundština');
INSERT INTO [country] ([id], [name]) VALUES ('luo', 'luoština');
INSERT INTO [country] ([id], [name]) VALUES ('wen', 'lužickosrbské jazyky');
INSERT INTO [country] ([id], [name]) VALUES ('mad', 'madurština');
INSERT INTO [country] ([id], [name]) VALUES ('mag', 'magadhiština');
INSERT INTO [country] ([id], [name]) VALUES ('mai', 'maithiliština');
INSERT INTO [country] ([id], [name]) VALUES ('mak', 'makasarština');
INSERT INTO [country] ([id], [name]) VALUES ('mk', 'makedonština');
INSERT INTO [country] ([id], [name]) VALUES ('ml', 'malabarština');
INSERT INTO [country] ([id], [name]) VALUES ('ms', 'malajština');
INSERT INTO [country] ([id], [name]) VALUES ('mg', 'malgaština');
INSERT INTO [country] ([id], [name]) VALUES ('mt', 'maltština');
INSERT INTO [country] ([id], [name]) VALUES ('mdr', 'mandar');
INSERT INTO [country] ([id], [name]) VALUES ('man', 'mandingština');
INSERT INTO [country] ([id], [name]) VALUES ('mnc', 'mandžuština');
INSERT INTO [country] ([id], [name]) VALUES ('mni', 'manipurština');
INSERT INTO [country] ([id], [name]) VALUES ('mno', 'manobo jazyky');
INSERT INTO [country] ([id], [name]) VALUES ('gv', 'manština');
INSERT INTO [country] ([id], [name]) VALUES ('mi', 'maorština');
INSERT INTO [country] ([id], [name]) VALUES ('mr', 'marathi');
INSERT INTO [country] ([id], [name]) VALUES ('chm', 'marijština');
INSERT INTO [country] ([id], [name]) VALUES ('mh', 'maršálština');
INSERT INTO [country] ([id], [name]) VALUES ('mas', 'masajština');
INSERT INTO [country] ([id], [name]) VALUES ('myn', 'mayské jazyky');
INSERT INTO [country] ([id], [name]) VALUES ('hu', 'maďarština');
INSERT INTO [country] ([id], [name]) VALUES ('men', 'mende');
INSERT INTO [country] ([id], [name]) VALUES ('mic', 'micmac');
INSERT INTO [country] ([id], [name]) VALUES ('min', 'minangkabau');
INSERT INTO [country] ([id], [name]) VALUES ('moh', 'mohawk');
INSERT INTO [country] ([id], [name]) VALUES ('mo', 'moldavština');
INSERT INTO [country] ([id], [name]) VALUES ('mkh', 'mon-khmerské jazyky (jiné)');
INSERT INTO [country] ([id], [name]) VALUES ('mn', 'mongolština');
INSERT INTO [country] ([id], [name]) VALUES ('lol', 'mongština');
INSERT INTO [country] ([id], [name]) VALUES ('mos', 'mosi');
INSERT INTO [country] ([id], [name]) VALUES ('mun', 'mundské jazyky (jiné)');
INSERT INTO [country] ([id], [name]) VALUES ('mus', 'muskogee (creek)');
INSERT INTO [country] ([id], [name]) VALUES ('mwr', 'márvárština');
INSERT INTO [country] ([id], [name]) VALUES ('nah', 'nahuatl');
INSERT INTO [country] ([id], [name]) VALUES ('na', 'nauru');
INSERT INTO [country] ([id], [name]) VALUES ('nv', 'navažština');
INSERT INTO [country] ([id], [name]) VALUES ('nr', 'ndebele (Jižní Afrika)');
INSERT INTO [country] ([id], [name]) VALUES ('nd', 'ndebele (Zimbabwe)');
INSERT INTO [country] ([id], [name]) VALUES ('ng', 'ndondština');
INSERT INTO [country] ([id], [name]) VALUES ('nap', 'neapolština');
INSERT INTO [country] ([id], [name]) VALUES ('ne', 'nepálština');
INSERT INTO [country] ([id], [name]) VALUES ('und', 'neznámý nebo neplatný jazyk');
INSERT INTO [country] ([id], [name]) VALUES ('nia', 'nias');
INSERT INTO [country] ([id], [name]) VALUES ('nic', 'nigero-kordofánské jazyky (jiné)');
INSERT INTO [country] ([id], [name]) VALUES ('ssa', 'nilo-saharské jazyky (jiné)');
INSERT INTO [country] ([id], [name]) VALUES ('niu', 'niue');
INSERT INTO [country] ([id], [name]) VALUES ('nl', 'nizozemština');
INSERT INTO [country] ([id], [name]) VALUES ('no', 'norština');
INSERT INTO [country] ([id], [name]) VALUES ('nb', 'norština (Bokmål)');
INSERT INTO [country] ([id], [name]) VALUES ('nn', 'norština (nynorsk)');
INSERT INTO [country] ([id], [name]) VALUES ('non', 'norština historická');
INSERT INTO [country] ([id], [name]) VALUES ('nyn', 'nyakolština');
INSERT INTO [country] ([id], [name]) VALUES ('nyo', 'nyorština');
INSERT INTO [country] ([id], [name]) VALUES ('nzi', 'nzima');
INSERT INTO [country] ([id], [name]) VALUES ('new', 'névárština');
INSERT INTO [country] ([id], [name]) VALUES ('nub', 'núbijské jazyky');
INSERT INTO [country] ([id], [name]) VALUES ('de_AT', 'německy (Rakousko)');
INSERT INTO [country] ([id], [name]) VALUES ('de', 'němčina');
INSERT INTO [country] ([id], [name]) VALUES ('oc', 'occitan');
INSERT INTO [country] ([id], [name]) VALUES ('oj', 'odžibvejština');
INSERT INTO [country] ([id], [name]) VALUES ('or', 'oriya');
INSERT INTO [country] ([id], [name]) VALUES ('osa', 'osage');
INSERT INTO [country] ([id], [name]) VALUES ('os', 'osetština');
INSERT INTO [country] ([id], [name]) VALUES ('ota', 'osmanská turečtina');
INSERT INTO [country] ([id], [name]) VALUES ('oto', 'otomijské jazyky');
INSERT INTO [country] ([id], [name]) VALUES ('pal', 'pahlaví');
INSERT INTO [country] ([id], [name]) VALUES ('pau', 'palauština');
INSERT INTO [country] ([id], [name]) VALUES ('pag', 'pangasinan');
INSERT INTO [country] ([id], [name]) VALUES ('pam', 'papangau');
INSERT INTO [country] ([id], [name]) VALUES ('pap', 'papiamento');
INSERT INTO [country] ([id], [name]) VALUES ('paa', 'papuánské jazyky (jiné)');
INSERT INTO [country] ([id], [name]) VALUES ('pa', 'paňdžábština');
INSERT INTO [country] ([id], [name]) VALUES ('fa', 'perština');
INSERT INTO [country] ([id], [name]) VALUES ('pon', 'pohnpeiština');
INSERT INTO [country] ([id], [name]) VALUES ('pl', 'polština');
INSERT INTO [country] ([id], [name]) VALUES ('pt', 'portugalština');
INSERT INTO [country] ([id], [name]) VALUES ('pro', 'provensálština');
INSERT INTO [country] ([id], [name]) VALUES ('pra', 'prákritské jazyky');
INSERT INTO [country] ([id], [name]) VALUES ('pi', 'pálí');
INSERT INTO [country] ([id], [name]) VALUES ('rap', 'rapanuiština');
INSERT INTO [country] ([id], [name]) VALUES ('rar', 'rarotongaština');
INSERT INTO [country] ([id], [name]) VALUES ('roa', 'románské jazyky (jiné)');
INSERT INTO [country] ([id], [name]) VALUES ('rom', 'romština');
INSERT INTO [country] ([id], [name]) VALUES ('ro', 'rumunština');
INSERT INTO [country] ([id], [name]) VALUES ('ru', 'ruština');
INSERT INTO [country] ([id], [name]) VALUES ('raj', 'rádžastánština');
INSERT INTO [country] ([id], [name]) VALUES ('rm', 'rétorománština');
INSERT INTO [country] ([id], [name]) VALUES ('mis', 'různé jazyky');
INSERT INTO [country] ([id], [name]) VALUES ('sal', 'salishské jazyky');
INSERT INTO [country] ([id], [name]) VALUES ('sam', 'samarština');
INSERT INTO [country] ([id], [name]) VALUES ('smi', 'sami jazyky');
INSERT INTO [country] ([id], [name]) VALUES ('sm', 'samoyština');
INSERT INTO [country] ([id], [name]) VALUES ('sad', 'sandawština');
INSERT INTO [country] ([id], [name]) VALUES ('sg', 'sangho');
INSERT INTO [country] ([id], [name]) VALUES ('sa', 'sanskrt');
INSERT INTO [country] ([id], [name]) VALUES ('sat', 'santálí');
INSERT INTO [country] ([id], [name]) VALUES ('sc', 'sardština');
INSERT INTO [country] ([id], [name]) VALUES ('sas', 'sasakština');
INSERT INTO [country] ([id], [name]) VALUES ('sel', 'selkupština');
INSERT INTO [country] ([id], [name]) VALUES ('sem', 'semitské jazyky (jiné)');
INSERT INTO [country] ([id], [name]) VALUES ('srr', 'serer');
INSERT INTO [country] ([id], [name]) VALUES ('st', 'sesotho');
INSERT INTO [country] ([id], [name]) VALUES ('tn', 'setswanština');
INSERT INTO [country] ([id], [name]) VALUES ('nso', 'severní sotho');
INSERT INTO [country] ([id], [name]) VALUES ('nai', 'severoamerické indiánské jazyky (jiné)');
INSERT INTO [country] ([id], [name]) VALUES ('sn', 'shona');
INSERT INTO [country] ([id], [name]) VALUES ('sid', 'sidamo');
INSERT INTO [country] ([id], [name]) VALUES ('bla', 'siksika');
INSERT INTO [country] ([id], [name]) VALUES ('sd', 'sindhi');
INSERT INTO [country] ([id], [name]) VALUES ('si', 'sinhálština');
INSERT INTO [country] ([id], [name]) VALUES ('sio', 'siouxské jazyky');
INSERT INTO [country] ([id], [name]) VALUES ('ss', 'siswatština');
INSERT INTO [country] ([id], [name]) VALUES ('gd', 'skotská galština');
INSERT INTO [country] ([id], [name]) VALUES ('sco', 'skotština');
INSERT INTO [country] ([id], [name]) VALUES ('den', 'slave');
INSERT INTO [country] ([id], [name]) VALUES ('sla', 'slovanský jazyk');
INSERT INTO [country] ([id], [name]) VALUES ('sk', 'slovenština');
INSERT INTO [country] ([id], [name]) VALUES ('sl', 'slovinština');
INSERT INTO [country] ([id], [name]) VALUES ('sog', 'sogdština');
INSERT INTO [country] ([id], [name]) VALUES ('so', 'somálština');
INSERT INTO [country] ([id], [name]) VALUES ('son', 'songhajština');
INSERT INTO [country] ([id], [name]) VALUES ('snk', 'sonikština');
INSERT INTO [country] ([id], [name]) VALUES ('sh', 'srbochorvatština');
INSERT INTO [country] ([id], [name]) VALUES ('sr', 'srbština');
INSERT INTO [country] ([id], [name]) VALUES ('ang', 'staroangličtina');
INSERT INTO [country] ([id], [name]) VALUES ('fro', 'starofrancouzština');
INSERT INTO [country] ([id], [name]) VALUES ('sga', 'staroirština');
INSERT INTO [country] ([id], [name]) VALUES ('peo', 'staroperština');
INSERT INTO [country] ([id], [name]) VALUES ('cu', 'staroslověnština');
INSERT INTO [country] ([id], [name]) VALUES ('grc', 'starořečtina');
INSERT INTO [country] ([id], [name]) VALUES ('goh', 'stará hornoněmčina');
INSERT INTO [country] ([id], [name]) VALUES ('cai', 'středoamerické indiánské jazyky (jiné)');
INSERT INTO [country] ([id], [name]) VALUES ('enm', 'středoangličtina');
INSERT INTO [country] ([id], [name]) VALUES ('frm', 'středofrancouzština');
INSERT INTO [country] ([id], [name]) VALUES ('dum', 'středoholandština');
INSERT INTO [country] ([id], [name]) VALUES ('mga', 'středoirština');
INSERT INTO [country] ([id], [name]) VALUES ('suk', 'sukuma');
INSERT INTO [country] ([id], [name]) VALUES ('sux', 'sumerský');
INSERT INTO [country] ([id], [name]) VALUES ('su', 'sundanština');
INSERT INTO [country] ([id], [name]) VALUES ('sus', 'susu');
INSERT INTO [country] ([id], [name]) VALUES ('sw', 'svahilština');
INSERT INTO [country] ([id], [name]) VALUES ('syr', 'syrština');
INSERT INTO [country] ([id], [name]) VALUES ('tl', 'tagalog');
INSERT INTO [country] ([id], [name]) VALUES ('fil', 'tagalogština');
INSERT INTO [country] ([id], [name]) VALUES ('ty', 'tahitština');
INSERT INTO [country] ([id], [name]) VALUES ('tmh', 'tamašek');
INSERT INTO [country] ([id], [name]) VALUES ('ta', 'tamilština');
INSERT INTO [country] ([id], [name]) VALUES ('tt', 'tatarština');
INSERT INTO [country] ([id], [name]) VALUES ('te', 'telugština');
INSERT INTO [country] ([id], [name]) VALUES ('tem', 'temne');
INSERT INTO [country] ([id], [name]) VALUES ('ter', 'tereno');
INSERT INTO [country] ([id], [name]) VALUES ('tet', 'tetumština');
INSERT INTO [country] ([id], [name]) VALUES ('tai', 'thajské jazyky (jiné)');
INSERT INTO [country] ([id], [name]) VALUES ('th', 'thajština');
INSERT INTO [country] ([id], [name]) VALUES ('sit', 'tibetočínské jazyky (jiné)');
INSERT INTO [country] ([id], [name]) VALUES ('bo', 'tibetština');
INSERT INTO [country] ([id], [name]) VALUES ('tig', 'tigrejština');
INSERT INTO [country] ([id], [name]) VALUES ('ti', 'tigrinijština');
INSERT INTO [country] ([id], [name]) VALUES ('tiv', 'tivština');
INSERT INTO [country] ([id], [name]) VALUES ('tli', 'tlingit');
INSERT INTO [country] ([id], [name]) VALUES ('tpi', 'tok pisin');
INSERT INTO [country] ([id], [name]) VALUES ('tkl', 'tokelauština');
INSERT INTO [country] ([id], [name]) VALUES ('to', 'tonga');
INSERT INTO [country] ([id], [name]) VALUES ('tsi', 'tsimshijské jazyky');
INSERT INTO [country] ([id], [name]) VALUES ('ts', 'tsonga');
INSERT INTO [country] ([id], [name]) VALUES ('tum', 'tumbukština');
INSERT INTO [country] ([id], [name]) VALUES ('tr', 'turečtina');
INSERT INTO [country] ([id], [name]) VALUES ('tk', 'turkmenština');
INSERT INTO [country] ([id], [name]) VALUES ('tvl', 'tuvalština');
INSERT INTO [country] ([id], [name]) VALUES ('tyv', 'tuvinština');
INSERT INTO [country] ([id], [name]) VALUES ('tw', 'twi');
INSERT INTO [country] ([id], [name]) VALUES ('tg', 'tádžičtina');
INSERT INTO [country] ([id], [name]) VALUES ('udm', 'udmurtština');
INSERT INTO [country] ([id], [name]) VALUES ('uga', 'ugaritština');
INSERT INTO [country] ([id], [name]) VALUES ('fiu', 'ugrofinské jazyky (jiné)');
INSERT INTO [country] ([id], [name]) VALUES ('ug', 'uighurština');
INSERT INTO [country] ([id], [name]) VALUES ('uk', 'ukrajinština');
INSERT INTO [country] ([id], [name]) VALUES ('umb', 'umbundu');
INSERT INTO [country] ([id], [name]) VALUES ('art', 'umělé jazyky (jiné)');
INSERT INTO [country] ([id], [name]) VALUES ('ur', 'urdština');
INSERT INTO [country] ([id], [name]) VALUES ('uz', 'uzbečtina');
INSERT INTO [country] ([id], [name]) VALUES ('vai', 'vai');
INSERT INTO [country] ([id], [name]) VALUES ('wa', 'valonština');
INSERT INTO [country] ([id], [name]) VALUES ('cy', 'velština');
INSERT INTO [country] ([id], [name]) VALUES ('ve', 'vendština');
INSERT INTO [country] ([id], [name]) VALUES ('vi', 'vietnamština');
INSERT INTO [country] ([id], [name]) VALUES ('vo', 'volapuk');
INSERT INTO [country] ([id], [name]) VALUES ('vot', 'votiatština');
INSERT INTO [country] ([id], [name]) VALUES ('mul', 'více jazyků');
INSERT INTO [country] ([id], [name]) VALUES ('wak', 'wakashské jazyky');
INSERT INTO [country] ([id], [name]) VALUES ('wal', 'walamština');
INSERT INTO [country] ([id], [name]) VALUES ('war', 'waray');
INSERT INTO [country] ([id], [name]) VALUES ('was', 'washo');
INSERT INTO [country] ([id], [name]) VALUES ('wo', 'wolof');
INSERT INTO [country] ([id], [name]) VALUES ('xh', 'xhosa');
INSERT INTO [country] ([id], [name]) VALUES ('yap', 'yapese');
INSERT INTO [country] ([id], [name]) VALUES ('yo', 'yoruba');
INSERT INTO [country] ([id], [name]) VALUES ('ypk', 'yupik');
INSERT INTO [country] ([id], [name]) VALUES ('znd', 'zandština');
INSERT INTO [country] ([id], [name]) VALUES ('zap', 'zapotéčtina');
INSERT INTO [country] ([id], [name]) VALUES ('zen', 'zenaga');
INSERT INTO [country] ([id], [name]) VALUES ('za', 'zhuang');
INSERT INTO [country] ([id], [name]) VALUES ('sgn', 'znakové jazyky');
INSERT INTO [country] ([id], [name]) VALUES ('zu', 'zulu');
INSERT INTO [country] ([id], [name]) VALUES ('zun', 'zunijština');
INSERT INTO [country] ([id], [name]) VALUES ('ira', 'íránské jazyky (jiné)');
INSERT INTO [country] ([id], [name]) VALUES ('chg', 'čagatajština');
INSERT INTO [country] ([id], [name]) VALUES ('ch', 'čamoro');
INSERT INTO [country] ([id], [name]) VALUES ('cmc', 'čamština');
INSERT INTO [country] ([id], [name]) VALUES ('chy', 'čejenština');
INSERT INTO [country] ([id], [name]) VALUES ('ce', 'čečenština');
INSERT INTO [country] ([id], [name]) VALUES ('cs', 'čeština');
INSERT INTO [country] ([id], [name]) VALUES ('chb', 'čibča');
INSERT INTO [country] ([id], [name]) VALUES ('chn', 'činuk pidžin');
INSERT INTO [country] ([id], [name]) VALUES ('chk', 'čukština');
INSERT INTO [country] ([id], [name]) VALUES ('cv', 'čuvašština');
INSERT INTO [country] ([id], [name]) VALUES ('zh', 'čínština');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hant', 'čínština (tradiční)');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hans', 'čínština (zjednodušená)');
INSERT INTO [country] ([id], [name]) VALUES ('nym', 'ňamwežština');
INSERT INTO [country] ([id], [name]) VALUES ('ny', 'ňandžština');
INSERT INTO [country] ([id], [name]) VALUES ('el', 'řečtina');
INSERT INTO [country] ([id], [name]) VALUES ('shn', 'šanština');
INSERT INTO [country] ([id], [name]) VALUES ('es', 'španělština');
INSERT INTO [country] ([id], [name]) VALUES ('sv', 'švédština');
