CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('ab', 'абхазский');
INSERT INTO `country` (`id`, `name`) VALUES ('awa', 'авадхи');
INSERT INTO `country` (`id`, `name`) VALUES ('av', 'аварский');
INSERT INTO `country` (`id`, `name`) VALUES ('ae', 'авестийский');
INSERT INTO `country` (`id`, `name`) VALUES ('en_AU', 'австралийский английский');
INSERT INTO `country` (`id`, `name`) VALUES ('aus', 'австралийский язык');
INSERT INTO `country` (`id`, `name`) VALUES ('de_AT', 'австрийский немецкий');
INSERT INTO `country` (`id`, `name`) VALUES ('map', 'австронезийский');
INSERT INTO `country` (`id`, `name`) VALUES ('ada', 'адангме');
INSERT INTO `country` (`id`, `name`) VALUES ('ady', 'адыгейский');
INSERT INTO `country` (`id`, `name`) VALUES ('az', 'азербайджанский');
INSERT INTO `country` (`id`, `name`) VALUES ('ay', 'аймара');
INSERT INTO `country` (`id`, `name`) VALUES ('ain', 'айну');
INSERT INTO `country` (`id`, `name`) VALUES ('ak', 'акан');
INSERT INTO `country` (`id`, `name`) VALUES ('akk', 'аккадский');
INSERT INTO `country` (`id`, `name`) VALUES ('sq', 'албанский');
INSERT INTO `country` (`id`, `name`) VALUES ('alg', 'алгонкинские языки');
INSERT INTO `country` (`id`, `name`) VALUES ('ale', 'алеутский');
INSERT INTO `country` (`id`, `name`) VALUES ('tut', 'алтайский язык');
INSERT INTO `country` (`id`, `name`) VALUES ('en_US', 'американский английский');
INSERT INTO `country` (`id`, `name`) VALUES ('am', 'амхарский');
INSERT INTO `country` (`id`, `name`) VALUES ('anp', 'ангика');
INSERT INTO `country` (`id`, `name`) VALUES ('en', 'английский');
INSERT INTO `country` (`id`, `name`) VALUES ('cpe', 'англо-креольские и пиджин');
INSERT INTO `country` (`id`, `name`) VALUES ('apa', 'апачские языки');
INSERT INTO `country` (`id`, `name`) VALUES ('ar', 'арабский');
INSERT INTO `country` (`id`, `name`) VALUES ('arw', 'аравакский');
INSERT INTO `country` (`id`, `name`) VALUES ('an', 'арагонский');
INSERT INTO `country` (`id`, `name`) VALUES ('arc', 'арамейский');
INSERT INTO `country` (`id`, `name`) VALUES ('arp', 'арапахо');
INSERT INTO `country` (`id`, `name`) VALUES ('arn', 'арауканский');
INSERT INTO `country` (`id`, `name`) VALUES ('hy', 'армянский');
INSERT INTO `country` (`id`, `name`) VALUES ('rup', 'арумынский');
INSERT INTO `country` (`id`, `name`) VALUES ('as', 'ассамский');
INSERT INTO `country` (`id`, `name`) VALUES ('ast', 'астурийский');
INSERT INTO `country` (`id`, `name`) VALUES ('ath', 'атапачские языки');
INSERT INTO `country` (`id`, `name`) VALUES ('cch', 'атсам');
INSERT INTO `country` (`id`, `name`) VALUES ('aa', 'афар');
INSERT INTO `country` (`id`, `name`) VALUES ('afa', 'афразийский язык');
INSERT INTO `country` (`id`, `name`) VALUES ('af', 'африкаанс');
INSERT INTO `country` (`id`, `name`) VALUES ('afh', 'африхили');
INSERT INTO `country` (`id`, `name`) VALUES ('nah', 'ацтекский');
INSERT INTO `country` (`id`, `name`) VALUES ('ace', 'ачехский');
INSERT INTO `country` (`id`, `name`) VALUES ('ach', 'ачоли');
INSERT INTO `country` (`id`, `name`) VALUES ('ban', 'балийский');
INSERT INTO `country` (`id`, `name`) VALUES ('bat', 'балтийский язык');
INSERT INTO `country` (`id`, `name`) VALUES ('bm', 'бамбарийский');
INSERT INTO `country` (`id`, `name`) VALUES ('bai', 'бамилеке языки');
INSERT INTO `country` (`id`, `name`) VALUES ('bad', 'банда');
INSERT INTO `country` (`id`, `name`) VALUES ('bnt', 'банту');
INSERT INTO `country` (`id`, `name`) VALUES ('bas', 'баса');
INSERT INTO `country` (`id`, `name`) VALUES ('eu', 'баскский');
INSERT INTO `country` (`id`, `name`) VALUES ('btk', 'батакский');
INSERT INTO `country` (`id`, `name`) VALUES ('ba', 'башкирский');
INSERT INTO `country` (`id`, `name`) VALUES ('bej', 'беджа');
INSERT INTO `country` (`id`, `name`) VALUES ('zxx', 'без языкового содержания');
INSERT INTO `country` (`id`, `name`) VALUES ('be', 'белорусский');
INSERT INTO `country` (`id`, `name`) VALUES ('bal', 'белуджский');
INSERT INTO `country` (`id`, `name`) VALUES ('nl_BE', 'бельгийский фламандский');
INSERT INTO `country` (`id`, `name`) VALUES ('bem', 'бемба');
INSERT INTO `country` (`id`, `name`) VALUES ('bn', 'бенгальский');
INSERT INTO `country` (`id`, `name`) VALUES ('ber', 'берберский');
INSERT INTO `country` (`id`, `name`) VALUES ('bik', 'бикольский');
INSERT INTO `country` (`id`, `name`) VALUES ('byn', 'билин (блин)');
INSERT INTO `country` (`id`, `name`) VALUES ('bin', 'бини');
INSERT INTO `country` (`id`, `name`) VALUES ('my', 'бирманский');
INSERT INTO `country` (`id`, `name`) VALUES ('bi', 'бислама');
INSERT INTO `country` (`id`, `name`) VALUES ('bh', 'бихари');
INSERT INTO `country` (`id`, `name`) VALUES ('zbl', 'блиссимволика');
INSERT INTO `country` (`id`, `name`) VALUES ('bg', 'болгарский');
INSERT INTO `country` (`id`, `name`) VALUES ('bs', 'боснийский');
INSERT INTO `country` (`id`, `name`) VALUES ('pt_BR', 'бразильский португальский');
INSERT INTO `country` (`id`, `name`) VALUES ('bra', 'брауи');
INSERT INTO `country` (`id`, `name`) VALUES ('br', 'бретонский');
INSERT INTO `country` (`id`, `name`) VALUES ('en_GB', 'британский английский');
INSERT INTO `country` (`id`, `name`) VALUES ('bug', 'бугийский');
INSERT INTO `country` (`id`, `name`) VALUES ('bua', 'бурятский');
INSERT INTO `country` (`id`, `name`) VALUES ('bho', 'бходжпури');
INSERT INTO `country` (`id`, `name`) VALUES ('vai', 'ваи');
INSERT INTO `country` (`id`, `name`) VALUES ('wak', 'вакашские языки');
INSERT INTO `country` (`id`, `name`) VALUES ('cy', 'валлийский');
INSERT INTO `country` (`id`, `name`) VALUES ('wa', 'валлонский');
INSERT INTO `country` (`id`, `name`) VALUES ('war', 'варай');
INSERT INTO `country` (`id`, `name`) VALUES ('was', 'вашо');
INSERT INTO `country` (`id`, `name`) VALUES ('hu', 'венгерский');
INSERT INTO `country` (`id`, `name`) VALUES ('ve', 'венда');
INSERT INTO `country` (`id`, `name`) VALUES ('hsb', 'верхнелужицкий');
INSERT INTO `country` (`id`, `name`) VALUES ('vot', 'водский');
INSERT INTO `country` (`id`, `name`) VALUES ('wal', 'воламо');
INSERT INTO `country` (`id`, `name`) VALUES ('vo', 'волапюк');
INSERT INTO `country` (`id`, `name`) VALUES ('wo', 'волоф');
INSERT INTO `country` (`id`, `name`) VALUES ('frs', 'восточный фризский');
INSERT INTO `country` (`id`, `name`) VALUES ('vi', 'вьетнамский');
INSERT INTO `country` (`id`, `name`) VALUES ('gaa', 'га');
INSERT INTO `country` (`id`, `name`) VALUES ('haw', 'гавайский');
INSERT INTO `country` (`id`, `name`) VALUES ('ht', 'гаитянский');
INSERT INTO `country` (`id`, `name`) VALUES ('gay', 'гайо');
INSERT INTO `country` (`id`, `name`) VALUES ('gl', 'галисийский');
INSERT INTO `country` (`id`, `name`) VALUES ('lg', 'ганда');
INSERT INTO `country` (`id`, `name`) VALUES ('gba', 'гбая');
INSERT INTO `country` (`id`, `name`) VALUES ('gwi', 'гвичин');
INSERT INTO `country` (`id`, `name`) VALUES ('hz', 'гереро');
INSERT INTO `country` (`id`, `name`) VALUES ('gem', 'германский язык');
INSERT INTO `country` (`id`, `name`) VALUES ('gez', 'геэз');
INSERT INTO `country` (`id`, `name`) VALUES ('gil', 'гильбертский');
INSERT INTO `country` (`id`, `name`) VALUES ('nl', 'голландский');
INSERT INTO `country` (`id`, `name`) VALUES ('gon', 'гонди');
INSERT INTO `country` (`id`, `name`) VALUES ('gor', 'горонтало');
INSERT INTO `country` (`id`, `name`) VALUES ('got', 'готский');
INSERT INTO `country` (`id`, `name`) VALUES ('grb', 'гребо');
INSERT INTO `country` (`id`, `name`) VALUES ('kl', 'гренландский');
INSERT INTO `country` (`id`, `name`) VALUES ('el', 'греческий');
INSERT INTO `country` (`id`, `name`) VALUES ('ka', 'грузинский');
INSERT INTO `country` (`id`, `name`) VALUES ('gn', 'гуарани');
INSERT INTO `country` (`id`, `name`) VALUES ('gu', 'гуджарати');
INSERT INTO `country` (`id`, `name`) VALUES ('gd', 'гэльский');
INSERT INTO `country` (`id`, `name`) VALUES ('dak', 'дакота');
INSERT INTO `country` (`id`, `name`) VALUES ('dar', 'даргва');
INSERT INTO `country` (`id`, `name`) VALUES ('da', 'датский');
INSERT INTO `country` (`id`, `name`) VALUES ('day', 'даяк');
INSERT INTO `country` (`id`, `name`) VALUES ('del', 'делаварский');
INSERT INTO `country` (`id`, `name`) VALUES ('dz', 'дзонг-кэ');
INSERT INTO `country` (`id`, `name`) VALUES ('din', 'динка');
INSERT INTO `country` (`id`, `name`) VALUES ('dyu', 'диула (дьюла)');
INSERT INTO `country` (`id`, `name`) VALUES ('doi', 'догри');
INSERT INTO `country` (`id`, `name`) VALUES ('dgr', 'догриб');
INSERT INTO `country` (`id`, `name`) VALUES ('dra', 'дравидийский язык');
INSERT INTO `country` (`id`, `name`) VALUES ('goh', 'древневерхненемецкий');
INSERT INTO `country` (`id`, `name`) VALUES ('grc', 'древнегреческий');
INSERT INTO `country` (`id`, `name`) VALUES ('egy', 'древнеегипетский');
INSERT INTO `country` (`id`, `name`) VALUES ('dua', 'дуала');
INSERT INTO `country` (`id`, `name`) VALUES ('jrb', 'еврейско-арабский');
INSERT INTO `country` (`id`, `name`) VALUES ('jpr', 'еврейско-персидский');
INSERT INTO `country` (`id`, `name`) VALUES ('zza', 'заза');
INSERT INTO `country` (`id`, `name`) VALUES ('znd', 'занде');
INSERT INTO `country` (`id`, `name`) VALUES ('zen', 'зенагский');
INSERT INTO `country` (`id`, `name`) VALUES ('zu', 'зулу');
INSERT INTO `country` (`id`, `name`) VALUES ('zun', 'зуньи');
INSERT INTO `country` (`id`, `name`) VALUES ('iba', 'ибанский');
INSERT INTO `country` (`id`, `name`) VALUES ('he', 'иврит');
INSERT INTO `country` (`id`, `name`) VALUES ('ig', 'игбо');
INSERT INTO `country` (`id`, `name`) VALUES ('ijo', 'иджо');
INSERT INTO `country` (`id`, `name`) VALUES ('yi', 'идиш');
INSERT INTO `country` (`id`, `name`) VALUES ('io', 'идо');
INSERT INTO `country` (`id`, `name`) VALUES ('ilo', 'илоко');
INSERT INTO `country` (`id`, `name`) VALUES ('smn', 'инари-саамский');
INSERT INTO `country` (`id`, `name`) VALUES ('inh', 'ингушский');
INSERT INTO `country` (`id`, `name`) VALUES ('inc', 'индийский язык');
INSERT INTO `country` (`id`, `name`) VALUES ('ine', 'индоевропейский язык');
INSERT INTO `country` (`id`, `name`) VALUES ('id', 'индонезийский');
INSERT INTO `country` (`id`, `name`) VALUES ('ia', 'интерлингва');
INSERT INTO `country` (`id`, `name`) VALUES ('ie', 'интерлингве');
INSERT INTO `country` (`id`, `name`) VALUES ('iu', 'инуктитут');
INSERT INTO `country` (`id`, `name`) VALUES ('ik', 'инупиак');
INSERT INTO `country` (`id`, `name`) VALUES ('ira', 'иранский язык');
INSERT INTO `country` (`id`, `name`) VALUES ('ga', 'ирландский');
INSERT INTO `country` (`id`, `name`) VALUES ('iro', 'ирокезские языки');
INSERT INTO `country` (`id`, `name`) VALUES ('art', 'искусственный язык');
INSERT INTO `country` (`id`, `name`) VALUES ('is', 'исландский');
INSERT INTO `country` (`id`, `name`) VALUES ('es', 'испанский');
INSERT INTO `country` (`id`, `name`) VALUES ('es_ES', 'испанский иберийский');
INSERT INTO `country` (`id`, `name`) VALUES ('it', 'итальянский');
INSERT INTO `country` (`id`, `name`) VALUES ('yo', 'йоруба');
INSERT INTO `country` (`id`, `name`) VALUES ('kbd', 'кабардинский');
INSERT INTO `country` (`id`, `name`) VALUES ('kab', 'кабильский');
INSERT INTO `country` (`id`, `name`) VALUES ('kaw', 'кави');
INSERT INTO `country` (`id`, `name`) VALUES ('cau', 'кавказский язык');
INSERT INTO `country` (`id`, `name`) VALUES ('cad', 'каддо');
INSERT INTO `country` (`id`, `name`) VALUES ('kaj', 'каджи');
INSERT INTO `country` (`id`, `name`) VALUES ('kk', 'казахский');
INSERT INTO `country` (`id`, `name`) VALUES ('xal', 'калмыцкий');
INSERT INTO `country` (`id`, `name`) VALUES ('kam', 'камба');
INSERT INTO `country` (`id`, `name`) VALUES ('en_CA', 'канадский английский');
INSERT INTO `country` (`id`, `name`) VALUES ('fr_CA', 'канадский французский');
INSERT INTO `country` (`id`, `name`) VALUES ('kn', 'каннада');
INSERT INTO `country` (`id`, `name`) VALUES ('yue', 'кантонский');
INSERT INTO `country` (`id`, `name`) VALUES ('kr', 'канури');
INSERT INTO `country` (`id`, `name`) VALUES ('kaa', 'каракалпакский');
INSERT INTO `country` (`id`, `name`) VALUES ('krc', 'карачаево-балкарский');
INSERT INTO `country` (`id`, `name`) VALUES ('krl', 'карельский');
INSERT INTO `country` (`id`, `name`) VALUES ('kar', 'каренский');
INSERT INTO `country` (`id`, `name`) VALUES ('car', 'кариб');
INSERT INTO `country` (`id`, `name`) VALUES ('ca', 'каталанский');
INSERT INTO `country` (`id`, `name`) VALUES ('kac', 'качинский');
INSERT INTO `country` (`id`, `name`) VALUES ('ks', 'кашмири');
INSERT INTO `country` (`id`, `name`) VALUES ('csb', 'кашубианский');
INSERT INTO `country` (`id`, `name`) VALUES ('ceb', 'кебуано');
INSERT INTO `country` (`id`, `name`) VALUES ('cel', 'кельтские другие');
INSERT INTO `country` (`id`, `name`) VALUES ('qu', 'кечуа');
INSERT INTO `country` (`id`, `name`) VALUES ('ki', 'кикуйю');
INSERT INTO `country` (`id`, `name`) VALUES ('kmb', 'кимбундийский');
INSERT INTO `country` (`id`, `name`) VALUES ('rw', 'киньяруанда');
INSERT INTO `country` (`id`, `name`) VALUES ('ky', 'киргизский');
INSERT INTO `country` (`id`, `name`) VALUES ('zh', 'китайский');
INSERT INTO `country` (`id`, `name`) VALUES ('syc', 'классический сирийский');
INSERT INTO `country` (`id`, `name`) VALUES ('tlh', 'клингонский');
INSERT INTO `country` (`id`, `name`) VALUES ('khi', 'койсанский язык');
INSERT INTO `country` (`id`, `name`) VALUES ('kv', 'коми');
INSERT INTO `country` (`id`, `name`) VALUES ('swb', 'коморский');
INSERT INTO `country` (`id`, `name`) VALUES ('kg', 'конго');
INSERT INTO `country` (`id`, `name`) VALUES ('kok', 'конкани');
INSERT INTO `country` (`id`, `name`) VALUES ('cop', 'коптский');
INSERT INTO `country` (`id`, `name`) VALUES ('ko', 'корейский');
INSERT INTO `country` (`id`, `name`) VALUES ('root', 'корневой язык');
INSERT INTO `country` (`id`, `name`) VALUES ('kw', 'корнийский');
INSERT INTO `country` (`id`, `name`) VALUES ('kfo', 'коро');
INSERT INTO `country` (`id`, `name`) VALUES ('co', 'корсиканский');
INSERT INTO `country` (`id`, `name`) VALUES ('kos', 'косраенский');
INSERT INTO `country` (`id`, `name`) VALUES ('kpe', 'кпелле');
INSERT INTO `country` (`id`, `name`) VALUES ('crp', 'креольские и пиджины');
INSERT INTO `country` (`id`, `name`) VALUES ('cr', 'криийский');
INSERT INTO `country` (`id`, `name`) VALUES ('mus', 'крик');
INSERT INTO `country` (`id`, `name`) VALUES ('kro', 'кру');
INSERT INTO `country` (`id`, `name`) VALUES ('crh', 'крымско-татарский');
INSERT INTO `country` (`id`, `name`) VALUES ('xh', 'ксоза');
INSERT INTO `country` (`id`, `name`) VALUES ('kum', 'кумыкский');
INSERT INTO `country` (`id`, `name`) VALUES ('kj', 'кунама');
INSERT INTO `country` (`id`, `name`) VALUES ('ku', 'курдский');
INSERT INTO `country` (`id`, `name`) VALUES ('kru', 'курух');
INSERT INTO `country` (`id`, `name`) VALUES ('kut', 'кутенаи');
INSERT INTO `country` (`id`, `name`) VALUES ('cus', 'кушитский язык');
INSERT INTO `country` (`id`, `name`) VALUES ('kha', 'кхаси');
INSERT INTO `country` (`id`, `name`) VALUES ('km', 'кхмерский');
INSERT INTO `country` (`id`, `name`) VALUES ('lad', 'ладино');
INSERT INTO `country` (`id`, `name`) VALUES ('lam', 'ламба');
INSERT INTO `country` (`id`, `name`) VALUES ('lo', 'лаосский');
INSERT INTO `country` (`id`, `name`) VALUES ('es_419', 'латиноамериканский испанский');
INSERT INTO `country` (`id`, `name`) VALUES ('la', 'латинский');
INSERT INTO `country` (`id`, `name`) VALUES ('lv', 'латышский');
INSERT INTO `country` (`id`, `name`) VALUES ('lah', 'лахнда');
INSERT INTO `country` (`id`, `name`) VALUES ('lez', 'лезгинский');
INSERT INTO `country` (`id`, `name`) VALUES ('li', 'лимбургский');
INSERT INTO `country` (`id`, `name`) VALUES ('ln', 'лингала');
INSERT INTO `country` (`id`, `name`) VALUES ('lt', 'литовский');
INSERT INTO `country` (`id`, `name`) VALUES ('jbo', 'ложбан');
INSERT INTO `country` (`id`, `name`) VALUES ('loz', 'лози');
INSERT INTO `country` (`id`, `name`) VALUES ('lu', 'луба-катанга');
INSERT INTO `country` (`id`, `name`) VALUES ('lua', 'луба-лулуа');
INSERT INTO `country` (`id`, `name`) VALUES ('wen', 'лужицкие языки');
INSERT INTO `country` (`id`, `name`) VALUES ('lui', 'луисеньо');
INSERT INTO `country` (`id`, `name`) VALUES ('smj', 'луле-саамский');
INSERT INTO `country` (`id`, `name`) VALUES ('lun', 'лунда');
INSERT INTO `country` (`id`, `name`) VALUES ('luo', 'луо (Кения и Танзания)');
INSERT INTO `country` (`id`, `name`) VALUES ('lus', 'лушай');
INSERT INTO `country` (`id`, `name`) VALUES ('lb', 'люксембургский');
INSERT INTO `country` (`id`, `name`) VALUES ('mag', 'магахи');
INSERT INTO `country` (`id`, `name`) VALUES ('mad', 'мадурский');
INSERT INTO `country` (`id`, `name`) VALUES ('mai', 'майтхили');
INSERT INTO `country` (`id`, `name`) VALUES ('myn', 'майя языки');
INSERT INTO `country` (`id`, `name`) VALUES ('mak', 'макассарский');
INSERT INTO `country` (`id`, `name`) VALUES ('mk', 'македонский');
INSERT INTO `country` (`id`, `name`) VALUES ('mg', 'малагасийский');
INSERT INTO `country` (`id`, `name`) VALUES ('ms', 'малайский');
INSERT INTO `country` (`id`, `name`) VALUES ('ml', 'малаялам');
INSERT INTO `country` (`id`, `name`) VALUES ('dv', 'мальдивский');
INSERT INTO `country` (`id`, `name`) VALUES ('mt', 'мальтийский');
INSERT INTO `country` (`id`, `name`) VALUES ('mdr', 'мандарский');
INSERT INTO `country` (`id`, `name`) VALUES ('man', 'мандинго');
INSERT INTO `country` (`id`, `name`) VALUES ('mni', 'манипурский');
INSERT INTO `country` (`id`, `name`) VALUES ('mno', 'манобо языки');
INSERT INTO `country` (`id`, `name`) VALUES ('mnc', 'маньчжурский');
INSERT INTO `country` (`id`, `name`) VALUES ('mi', 'маори');
INSERT INTO `country` (`id`, `name`) VALUES ('mr', 'маратхи');
INSERT INTO `country` (`id`, `name`) VALUES ('mwr', 'марвари');
INSERT INTO `country` (`id`, `name`) VALUES ('chm', 'марийский (черемисский)');
INSERT INTO `country` (`id`, `name`) VALUES ('mh', 'маршалльский');
INSERT INTO `country` (`id`, `name`) VALUES ('mas', 'масаи');
INSERT INTO `country` (`id`, `name`) VALUES ('men', 'менде');
INSERT INTO `country` (`id`, `name`) VALUES ('mic', 'микмак');
INSERT INTO `country` (`id`, `name`) VALUES ('min', 'минангкабау');
INSERT INTO `country` (`id`, `name`) VALUES ('mwl', 'мирандийский');
INSERT INTO `country` (`id`, `name`) VALUES ('mdf', 'мокшанский');
INSERT INTO `country` (`id`, `name`) VALUES ('mo', 'молдавский');
INSERT INTO `country` (`id`, `name`) VALUES ('lol', 'монго');
INSERT INTO `country` (`id`, `name`) VALUES ('mn', 'монгольский');
INSERT INTO `country` (`id`, `name`) VALUES ('mkh', 'монкхмерский язык');
INSERT INTO `country` (`id`, `name`) VALUES ('mos', 'моси');
INSERT INTO `country` (`id`, `name`) VALUES ('moh', 'мохаук');
INSERT INTO `country` (`id`, `name`) VALUES ('mun', 'мунда языки');
INSERT INTO `country` (`id`, `name`) VALUES ('gv', 'мэнский');
INSERT INTO `country` (`id`, `name`) VALUES ('nv', 'навахо');
INSERT INTO `country` (`id`, `name`) VALUES ('na', 'науру');
INSERT INTO `country` (`id`, `name`) VALUES ('nr', 'ндебели южный');
INSERT INTO `country` (`id`, `name`) VALUES ('ng', 'ндонга');
INSERT INTO `country` (`id`, `name`) VALUES ('nap', 'неаполитанский');
INSERT INTO `country` (`id`, `name`) VALUES ('nwc', 'невари (классический)');
INSERT INTO `country` (`id`, `name`) VALUES ('new', 'неварский');
INSERT INTO `country` (`id`, `name`) VALUES ('und', 'неизвестный или недействительный язык');
INSERT INTO `country` (`id`, `name`) VALUES ('de', 'немецкий');
INSERT INTO `country` (`id`, `name`) VALUES ('ne', 'непальский');
INSERT INTO `country` (`id`, `name`) VALUES ('nzi', 'нзима');
INSERT INTO `country` (`id`, `name`) VALUES ('nia', 'ниас');
INSERT INTO `country` (`id`, `name`) VALUES ('nic', 'нигер-кордофанский язык');
INSERT INTO `country` (`id`, `name`) VALUES ('nds', 'нижнегерманский');
INSERT INTO `country` (`id`, `name`) VALUES ('dsb', 'нижнелужицкий');
INSERT INTO `country` (`id`, `name`) VALUES ('ssa', 'нило-сахарский язык');
INSERT INTO `country` (`id`, `name`) VALUES ('niu', 'ниуэ');
INSERT INTO `country` (`id`, `name`) VALUES ('nqo', 'нко');
INSERT INTO `country` (`id`, `name`) VALUES ('nog', 'ногайский');
INSERT INTO `country` (`id`, `name`) VALUES ('no', 'норвежский');
INSERT INTO `country` (`id`, `name`) VALUES ('nb', 'норвежский букмол');
INSERT INTO `country` (`id`, `name`) VALUES ('nn', 'норвежский нюнорск');
INSERT INTO `country` (`id`, `name`) VALUES ('nub', 'нубийские языки');
INSERT INTO `country` (`id`, `name`) VALUES ('nyo', 'ньоро');
INSERT INTO `country` (`id`, `name`) VALUES ('nym', 'ньямвези');
INSERT INTO `country` (`id`, `name`) VALUES ('ny', 'ньянджа');
INSERT INTO `country` (`id`, `name`) VALUES ('nyn', 'ньянколе');
INSERT INTO `country` (`id`, `name`) VALUES ('tog', 'ньяса (тонга)');
INSERT INTO `country` (`id`, `name`) VALUES ('oj', 'оджибва');
INSERT INTO `country` (`id`, `name`) VALUES ('oc', 'окситанский');
INSERT INTO `country` (`id`, `name`) VALUES ('or', 'ория');
INSERT INTO `country` (`id`, `name`) VALUES ('om', 'оромо');
INSERT INTO `country` (`id`, `name`) VALUES ('osa', 'оседжи');
INSERT INTO `country` (`id`, `name`) VALUES ('os', 'осетинский');
INSERT INTO `country` (`id`, `name`) VALUES ('oto', 'отомангские языки');
INSERT INTO `country` (`id`, `name`) VALUES ('pau', 'палау');
INSERT INTO `country` (`id`, `name`) VALUES ('pi', 'пали');
INSERT INTO `country` (`id`, `name`) VALUES ('pam', 'пампанга');
INSERT INTO `country` (`id`, `name`) VALUES ('pag', 'пангасинан');
INSERT INTO `country` (`id`, `name`) VALUES ('pa', 'панджаби');
INSERT INTO `country` (`id`, `name`) VALUES ('paa', 'папуасский язык');
INSERT INTO `country` (`id`, `name`) VALUES ('pap', 'папьяменто');
INSERT INTO `country` (`id`, `name`) VALUES ('fa', 'персидский');
INSERT INTO `country` (`id`, `name`) VALUES ('pal', 'пехлевийский');
INSERT INTO `country` (`id`, `name`) VALUES ('pl', 'польский');
INSERT INTO `country` (`id`, `name`) VALUES ('pon', 'понапе');
INSERT INTO `country` (`id`, `name`) VALUES ('cpp', 'португало-креольские и пиджины');
INSERT INTO `country` (`id`, `name`) VALUES ('pt', 'португальский');
INSERT INTO `country` (`id`, `name`) VALUES ('pt_PT', 'португальский иберийский');
INSERT INTO `country` (`id`, `name`) VALUES ('pra', 'пракриты языки');
INSERT INTO `country` (`id`, `name`) VALUES ('ps', 'пушту');
INSERT INTO `country` (`id`, `name`) VALUES ('raj', 'раджастхани');
INSERT INTO `country` (`id`, `name`) VALUES ('rap', 'рапануи');
INSERT INTO `country` (`id`, `name`) VALUES ('rar', 'раротонганский');
INSERT INTO `country` (`id`, `name`) VALUES ('rm', 'ретороманский');
INSERT INTO `country` (`id`, `name`) VALUES ('roa', 'романский язык');
INSERT INTO `country` (`id`, `name`) VALUES ('ro', 'румынский');
INSERT INTO `country` (`id`, `name`) VALUES ('rn', 'рунди');
INSERT INTO `country` (`id`, `name`) VALUES ('ru', 'русский');
INSERT INTO `country` (`id`, `name`) VALUES ('smi', 'саамские языки');
INSERT INTO `country` (`id`, `name`) VALUES ('sma', 'саамский (южный)');
INSERT INTO `country` (`id`, `name`) VALUES ('sal', 'салишские языки');
INSERT INTO `country` (`id`, `name`) VALUES ('sam', 'самаритянский арамейский');
INSERT INTO `country` (`id`, `name`) VALUES ('sm', 'самоанский');
INSERT INTO `country` (`id`, `name`) VALUES ('sg', 'санго');
INSERT INTO `country` (`id`, `name`) VALUES ('sad', 'сандаве');
INSERT INTO `country` (`id`, `name`) VALUES ('sa', 'санскрит');
INSERT INTO `country` (`id`, `name`) VALUES ('sat', 'сантали');
INSERT INTO `country` (`id`, `name`) VALUES ('zap', 'сапотекский');
INSERT INTO `country` (`id`, `name`) VALUES ('sc', 'сардинский');
INSERT INTO `country` (`id`, `name`) VALUES ('sas', 'сасаки');
INSERT INTO `country` (`id`, `name`) VALUES ('ss', 'свази');
INSERT INTO `country` (`id`, `name`) VALUES ('se', 'северносаамский');
INSERT INTO `country` (`id`, `name`) VALUES ('nd', 'северный ндебели');
INSERT INTO `country` (`id`, `name`) VALUES ('sel', 'селькупский');
INSERT INTO `country` (`id`, `name`) VALUES ('sem', 'семитский язык');
INSERT INTO `country` (`id`, `name`) VALUES ('sr', 'сербский');
INSERT INTO `country` (`id`, `name`) VALUES ('sh', 'сербскохорватский');
INSERT INTO `country` (`id`, `name`) VALUES ('srr', 'серер');
INSERT INTO `country` (`id`, `name`) VALUES ('sid', 'сидама');
INSERT INTO `country` (`id`, `name`) VALUES ('bla', 'сиксика');
INSERT INTO `country` (`id`, `name`) VALUES ('si', 'сингальский');
INSERT INTO `country` (`id`, `name`) VALUES ('sd', 'синдхи');
INSERT INTO `country` (`id`, `name`) VALUES ('sit', 'синотибетский язык');
INSERT INTO `country` (`id`, `name`) VALUES ('syr', 'сирийский');
INSERT INTO `country` (`id`, `name`) VALUES ('sio', 'сиу языки');
INSERT INTO `country` (`id`, `name`) VALUES ('scn', 'сицилийский');
INSERT INTO `country` (`id`, `name`) VALUES ('sms', 'скольт-саамский');
INSERT INTO `country` (`id`, `name`) VALUES ('den', 'славянский');
INSERT INTO `country` (`id`, `name`) VALUES ('sla', 'славянский язык');
INSERT INTO `country` (`id`, `name`) VALUES ('sk', 'словацкий');
INSERT INTO `country` (`id`, `name`) VALUES ('sl', 'словенский');
INSERT INTO `country` (`id`, `name`) VALUES ('mis', 'смешанные языки');
INSERT INTO `country` (`id`, `name`) VALUES ('sog', 'согдийский');
INSERT INTO `country` (`id`, `name`) VALUES ('so', 'сомали');
INSERT INTO `country` (`id`, `name`) VALUES ('son', 'сонгаи');
INSERT INTO `country` (`id`, `name`) VALUES ('snk', 'сонинке');
INSERT INTO `country` (`id`, `name`) VALUES ('nso', 'сото северный');
INSERT INTO `country` (`id`, `name`) VALUES ('st', 'сото южный');
INSERT INTO `country` (`id`, `name`) VALUES ('srn', 'сранан тонго');
INSERT INTO `country` (`id`, `name`) VALUES ('enm', 'среднеанглийский');
INSERT INTO `country` (`id`, `name`) VALUES ('gmh', 'средневерхненемецкий');
INSERT INTO `country` (`id`, `name`) VALUES ('mga', 'среднеирландский');
INSERT INTO `country` (`id`, `name`) VALUES ('dum', 'средненидерландский');
INSERT INTO `country` (`id`, `name`) VALUES ('frm', 'среднефранцузский');
INSERT INTO `country` (`id`, `name`) VALUES ('ang', 'староанглийский');
INSERT INTO `country` (`id`, `name`) VALUES ('sga', 'староирландский');
INSERT INTO `country` (`id`, `name`) VALUES ('non', 'старонорвежский');
INSERT INTO `country` (`id`, `name`) VALUES ('peo', 'староперсидский');
INSERT INTO `country` (`id`, `name`) VALUES ('pro', 'старопровансальский');
INSERT INTO `country` (`id`, `name`) VALUES ('ota', 'старотурецкий');
INSERT INTO `country` (`id`, `name`) VALUES ('fro', 'старофранцузский');
INSERT INTO `country` (`id`, `name`) VALUES ('sw', 'суахили');
INSERT INTO `country` (`id`, `name`) VALUES ('suk', 'сукума');
INSERT INTO `country` (`id`, `name`) VALUES ('su', 'сунданский');
INSERT INTO `country` (`id`, `name`) VALUES ('sus', 'сусу');
INSERT INTO `country` (`id`, `name`) VALUES ('ii', 'сычуань');
INSERT INTO `country` (`id`, `name`) VALUES ('tl', 'тагалог');
INSERT INTO `country` (`id`, `name`) VALUES ('tg', 'таджикский');
INSERT INTO `country` (`id`, `name`) VALUES ('ty', 'таитянский');
INSERT INTO `country` (`id`, `name`) VALUES ('th', 'тайский');
INSERT INTO `country` (`id`, `name`) VALUES ('tai', 'тайский язык');
INSERT INTO `country` (`id`, `name`) VALUES ('tmh', 'тамашек');
INSERT INTO `country` (`id`, `name`) VALUES ('ta', 'тамильский');
INSERT INTO `country` (`id`, `name`) VALUES ('tt', 'татарский');
INSERT INTO `country` (`id`, `name`) VALUES ('tw', 'тви');
INSERT INTO `country` (`id`, `name`) VALUES ('te', 'телугу');
INSERT INTO `country` (`id`, `name`) VALUES ('tem', 'темне');
INSERT INTO `country` (`id`, `name`) VALUES ('ter', 'терено');
INSERT INTO `country` (`id`, `name`) VALUES ('tet', 'тетум');
INSERT INTO `country` (`id`, `name`) VALUES ('bo', 'тибетский');
INSERT INTO `country` (`id`, `name`) VALUES ('tiv', 'тиви');
INSERT INTO `country` (`id`, `name`) VALUES ('tig', 'тигре');
INSERT INTO `country` (`id`, `name`) VALUES ('ti', 'тигринья');
INSERT INTO `country` (`id`, `name`) VALUES ('tli', 'тлингит');
INSERT INTO `country` (`id`, `name`) VALUES ('tpi', 'ток-писин');
INSERT INTO `country` (`id`, `name`) VALUES ('tkl', 'токелайский');
INSERT INTO `country` (`id`, `name`) VALUES ('to', 'тонга');
INSERT INTO `country` (`id`, `name`) VALUES ('zh_Hant', 'традиционный китайский');
INSERT INTO `country` (`id`, `name`) VALUES ('tn', 'тсвана');
INSERT INTO `country` (`id`, `name`) VALUES ('ts', 'тсонга');
INSERT INTO `country` (`id`, `name`) VALUES ('tvl', 'тувалу');
INSERT INTO `country` (`id`, `name`) VALUES ('tyv', 'тувинский');
INSERT INTO `country` (`id`, `name`) VALUES ('tum', 'тумбука');
INSERT INTO `country` (`id`, `name`) VALUES ('tup', 'тупи');
INSERT INTO `country` (`id`, `name`) VALUES ('tr', 'турецкий');
INSERT INTO `country` (`id`, `name`) VALUES ('tk', 'туркменский');
INSERT INTO `country` (`id`, `name`) VALUES ('kcg', 'тьяп');
INSERT INTO `country` (`id`, `name`) VALUES ('uga', 'угаритский');
INSERT INTO `country` (`id`, `name`) VALUES ('udm', 'удмуртский');
INSERT INTO `country` (`id`, `name`) VALUES ('uz', 'узбекский');
INSERT INTO `country` (`id`, `name`) VALUES ('ug', 'уйгурский');
INSERT INTO `country` (`id`, `name`) VALUES ('uk', 'украинский');
INSERT INTO `country` (`id`, `name`) VALUES ('umb', 'умбунду');
INSERT INTO `country` (`id`, `name`) VALUES ('zh_Hans', 'упрощенный китайский');
INSERT INTO `country` (`id`, `name`) VALUES ('ur', 'урду');
INSERT INTO `country` (`id`, `name`) VALUES ('fan', 'фанг');
INSERT INTO `country` (`id`, `name`) VALUES ('fat', 'фанти');
INSERT INTO `country` (`id`, `name`) VALUES ('fo', 'фарерский');
INSERT INTO `country` (`id`, `name`) VALUES ('fj', 'фиджи');
INSERT INTO `country` (`id`, `name`) VALUES ('fil', 'филиппинский');
INSERT INTO `country` (`id`, `name`) VALUES ('phi', 'филиппинский язык');
INSERT INTO `country` (`id`, `name`) VALUES ('phn', 'финикийский');
INSERT INTO `country` (`id`, `name`) VALUES ('fiu', 'финно-угорский язык');
INSERT INTO `country` (`id`, `name`) VALUES ('fi', 'финский');
INSERT INTO `country` (`id`, `name`) VALUES ('fon', 'фон');
INSERT INTO `country` (`id`, `name`) VALUES ('cpf', 'франко-креольские и пиджины');
INSERT INTO `country` (`id`, `name`) VALUES ('fr', 'французский');
INSERT INTO `country` (`id`, `name`) VALUES ('fy', 'фризский');
INSERT INTO `country` (`id`, `name`) VALUES ('frr', 'фризский северный');
INSERT INTO `country` (`id`, `name`) VALUES ('fur', 'фриульский');
INSERT INTO `country` (`id`, `name`) VALUES ('ff', 'фулах');
INSERT INTO `country` (`id`, `name`) VALUES ('hai', 'хайда');
INSERT INTO `country` (`id`, `name`) VALUES ('ha', 'хауса');
INSERT INTO `country` (`id`, `name`) VALUES ('hit', 'хеттский');
INSERT INTO `country` (`id`, `name`) VALUES ('hil', 'хилигайнон');
INSERT INTO `country` (`id`, `name`) VALUES ('him', 'химачали');
INSERT INTO `country` (`id`, `name`) VALUES ('hi', 'хинди');
INSERT INTO `country` (`id`, `name`) VALUES ('ho', 'хиримоту');
INSERT INTO `country` (`id`, `name`) VALUES ('hmn', 'хмонг');
INSERT INTO `country` (`id`, `name`) VALUES ('hr', 'хорватский');
INSERT INTO `country` (`id`, `name`) VALUES ('kho', 'хотанский');
INSERT INTO `country` (`id`, `name`) VALUES ('hup', 'хупа');
INSERT INTO `country` (`id`, `name`) VALUES ('cu', 'церковнославянский');
INSERT INTO `country` (`id`, `name`) VALUES ('tsi', 'цимшиан');
INSERT INTO `country` (`id`, `name`) VALUES ('rom', 'цыганский');
INSERT INTO `country` (`id`, `name`) VALUES ('chg', 'чагатайский');
INSERT INTO `country` (`id`, `name`) VALUES ('ch', 'чаморро');
INSERT INTO `country` (`id`, `name`) VALUES ('cmc', 'чамский язык');
INSERT INTO `country` (`id`, `name`) VALUES ('chy', 'чейенн');
INSERT INTO `country` (`id`, `name`) VALUES ('chr', 'чероки');
INSERT INTO `country` (`id`, `name`) VALUES ('ce', 'чеченский');
INSERT INTO `country` (`id`, `name`) VALUES ('cs', 'чешский');
INSERT INTO `country` (`id`, `name`) VALUES ('za', 'чжуань');
INSERT INTO `country` (`id`, `name`) VALUES ('chb', 'чибча');
INSERT INTO `country` (`id`, `name`) VALUES ('chn', 'чинук жаргон');
INSERT INTO `country` (`id`, `name`) VALUES ('chp', 'чипевайян');
INSERT INTO `country` (`id`, `name`) VALUES ('cho', 'чоктав');
INSERT INTO `country` (`id`, `name`) VALUES ('cv', 'чувашский');
INSERT INTO `country` (`id`, `name`) VALUES ('chk', 'чукотский');
INSERT INTO `country` (`id`, `name`) VALUES ('shn', 'шанский');
INSERT INTO `country` (`id`, `name`) VALUES ('sv', 'шведский');
INSERT INTO `country` (`id`, `name`) VALUES ('de_CH', 'швейцарский верхненемецкий');
INSERT INTO `country` (`id`, `name`) VALUES ('gsw', 'швейцарский немецкий');
INSERT INTO `country` (`id`, `name`) VALUES ('fr_CH', 'швейцарский французский');
INSERT INTO `country` (`id`, `name`) VALUES ('sn', 'шона');
INSERT INTO `country` (`id`, `name`) VALUES ('sco', 'шотландский');
INSERT INTO `country` (`id`, `name`) VALUES ('sux', 'шумерский');
INSERT INTO `country` (`id`, `name`) VALUES ('ee', 'эве');
INSERT INTO `country` (`id`, `name`) VALUES ('ewo', 'эвондо');
INSERT INTO `country` (`id`, `name`) VALUES ('eka', 'экаджук');
INSERT INTO `country` (`id`, `name`) VALUES ('elx', 'эламский');
INSERT INTO `country` (`id`, `name`) VALUES ('myv', 'эрзя');
INSERT INTO `country` (`id`, `name`) VALUES ('eo', 'эсперанто');
INSERT INTO `country` (`id`, `name`) VALUES ('et', 'эстонский');
INSERT INTO `country` (`id`, `name`) VALUES ('efi', 'эфик');
INSERT INTO `country` (`id`, `name`) VALUES ('alt', 'южноалтайский');
INSERT INTO `country` (`id`, `name`) VALUES ('ypk', 'юпикский язык');
INSERT INTO `country` (`id`, `name`) VALUES ('jv', 'яванский');
INSERT INTO `country` (`id`, `name`) VALUES ('sgn', 'язык глухонемых');
INSERT INTO `country` (`id`, `name`) VALUES ('nai', 'язык индейцев Северной Америки');
INSERT INTO `country` (`id`, `name`) VALUES ('cai', 'язык индейцев Центральной Америки');
INSERT INTO `country` (`id`, `name`) VALUES ('sai', 'язык индейцев Южной Америки');
INSERT INTO `country` (`id`, `name`) VALUES ('sah', 'якутский');
INSERT INTO `country` (`id`, `name`) VALUES ('yao', 'яо');
INSERT INTO `country` (`id`, `name`) VALUES ('yap', 'яп');
INSERT INTO `country` (`id`, `name`) VALUES ('ja', 'японский');
