CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('ab', 'آبخازی');
INSERT INTO "country" ("id", "name") VALUES ('ach', 'آچولیایی');
INSERT INTO "country" ("id", "name") VALUES ('ace', 'آچئی');
INSERT INTO "country" ("id", "name") VALUES ('ada', 'آدانگمه‌ای');
INSERT INTO "country" ("id", "name") VALUES ('ady', 'آدیجیایی');
INSERT INTO "country" ("id", "name") VALUES ('arp', 'آراپاهویی');
INSERT INTO "country" ("id", "name") VALUES ('an', 'آراگونی');
INSERT INTO "country" ("id", "name") VALUES ('arc', 'آرامی');
INSERT INTO "country" ("id", "name") VALUES ('sam', 'آرامی سامری');
INSERT INTO "country" ("id", "name") VALUES ('arw', 'آراواکی');
INSERT INTO "country" ("id", "name") VALUES ('arn', 'آروکانیایی');
INSERT INTO "country" ("id", "name") VALUES ('as', 'آسامی');
INSERT INTO "country" ("id", "name") VALUES ('os', 'آسی');
INSERT INTO "country" ("id", "name") VALUES ('aa', 'آفاری');
INSERT INTO "country" ("id", "name") VALUES ('af', 'آفریکانس');
INSERT INTO "country" ("id", "name") VALUES ('afh', 'آفریهیلی');
INSERT INTO "country" ("id", "name") VALUES ('ak', 'آکان');
INSERT INTO "country" ("id", "name") VALUES ('akk', 'آکدی');
INSERT INTO "country" ("id", "name") VALUES ('sq', 'آلبانیایی');
INSERT INTO "country" ("id", "name") VALUES ('alt', 'آلتایی جنوبی');
INSERT INTO "country" ("id", "name") VALUES ('de', 'آلمانی');
INSERT INTO "country" ("id", "name") VALUES ('de_AT', 'آلمانی اتریش');
INSERT INTO "country" ("id", "name") VALUES ('nds', 'آلمانی سفلی');
INSERT INTO "country" ("id", "name") VALUES ('gsw', 'آلمانی سوئیسی');
INSERT INTO "country" ("id", "name") VALUES ('goh', 'آلمانی علیای باستان');
INSERT INTO "country" ("id", "name") VALUES ('de_CH', 'آلمانی علیای سوئیس');
INSERT INTO "country" ("id", "name") VALUES ('gmh', 'آلمانی علیای میانه');
INSERT INTO "country" ("id", "name") VALUES ('ale', 'آلئوتی');
INSERT INTO "country" ("id", "name") VALUES ('anp', 'آنگیکا');
INSERT INTO "country" ("id", "name") VALUES ('av', 'آواری');
INSERT INTO "country" ("id", "name") VALUES ('iba', 'آیبن');
INSERT INTO "country" ("id", "name") VALUES ('ga', 'آیرلندی');
INSERT INTO "country" ("id", "name") VALUES ('is', 'آیسلندی');
INSERT INTO "country" ("id", "name") VALUES ('ay', 'آیمارایی');
INSERT INTO "country" ("id", "name") VALUES ('ain', 'آینویی');
INSERT INTO "country" ("id", "name") VALUES ('ur', 'اردو');
INSERT INTO "country" ("id", "name") VALUES ('myv', 'ارزیایی');
INSERT INTO "country" ("id", "name") VALUES ('hy', 'ارمنی');
INSERT INTO "country" ("id", "name") VALUES ('uz', 'ازبکی');
INSERT INTO "country" ("id", "name") VALUES ('es_ES', 'اسپانیایی اسپانیا');
INSERT INTO "country" ("id", "name") VALUES ('es_419', 'اسپانیایی امریکای لاتین');
INSERT INTO "country" ("id", "name") VALUES ('eo', 'اسپرانتو');
INSERT INTO "country" ("id", "name") VALUES ('et', 'استونیایی');
INSERT INTO "country" ("id", "name") VALUES ('sco', 'اسکاتلندی');
INSERT INTO "country" ("id", "name") VALUES ('cu', 'اسلاوی کلیسایی');
INSERT INTO "country" ("id", "name") VALUES ('sk', 'اسلواکی');
INSERT INTO "country" ("id", "name") VALUES ('sl', 'اسلووینیایی');
INSERT INTO "country" ("id", "name") VALUES ('efi', 'افیکی');
INSERT INTO "country" ("id", "name") VALUES ('eka', 'اکاجوک');
INSERT INTO "country" ("id", "name") VALUES ('ie', 'اکسیدنتال');
INSERT INTO "country" ("id", "name") VALUES ('umb', 'امبوندویی');
INSERT INTO "country" ("id", "name") VALUES ('am', 'امهری');
INSERT INTO "country" ("id", "name") VALUES ('nr', 'انده‌بله‌ای جنوبی');
INSERT INTO "country" ("id", "name") VALUES ('nd', 'انده‌بله‌ای شمالی');
INSERT INTO "country" ("id", "name") VALUES ('ng', 'اندونگایی');
INSERT INTO "country" ("id", "name") VALUES ('id', 'اندونیزیایی');
INSERT INTO "country" ("id", "name") VALUES ('en', 'انگلیسی');
INSERT INTO "country" ("id", "name") VALUES ('en_AU', 'انگلیسی استرالیا');
INSERT INTO "country" ("id", "name") VALUES ('en_US', 'انگلیسی امریکا');
INSERT INTO "country" ("id", "name") VALUES ('ang', 'انگلیسی باستان');
INSERT INTO "country" ("id", "name") VALUES ('en_GB', 'انگلیسی بریتانیا');
INSERT INTO "country" ("id", "name") VALUES ('en_CA', 'انگلیسی کانادا');
INSERT INTO "country" ("id", "name") VALUES ('enm', 'انگلیسی میانه');
INSERT INTO "country" ("id", "name") VALUES ('ewo', 'اواندو');
INSERT INTO "country" ("id", "name") VALUES ('oj', 'اوجیبوایی');
INSERT INTO "country" ("id", "name") VALUES ('udm', 'اودمورتی');
INSERT INTO "country" ("id", "name") VALUES ('om', 'اورومویی');
INSERT INTO "country" ("id", "name") VALUES ('or', 'اوریه‌ای');
INSERT INTO "country" ("id", "name") VALUES ('ae', 'اوستایی');
INSERT INTO "country" ("id", "name") VALUES ('osa', 'اوسیجی');
INSERT INTO "country" ("id", "name") VALUES ('uk', 'اوکراینی');
INSERT INTO "country" ("id", "name") VALUES ('oc', 'اوکیتایی');
INSERT INTO "country" ("id", "name") VALUES ('uga', 'اوگاریتی');
INSERT INTO "country" ("id", "name") VALUES ('ee', 'اوه‌ای');
INSERT INTO "country" ("id", "name") VALUES ('ug', 'اویغوری');
INSERT INTO "country" ("id", "name") VALUES ('it', 'ایتالوی');
INSERT INTO "country" ("id", "name") VALUES ('ijo', 'ایجویی');
INSERT INTO "country" ("id", "name") VALUES ('io', 'ایدو');
INSERT INTO "country" ("id", "name") VALUES ('sga', 'ایرلندی باستان');
INSERT INTO "country" ("id", "name") VALUES ('mga', 'ایرلندی میانه');
INSERT INTO "country" ("id", "name") VALUES ('ig', 'ایگبویی');
INSERT INTO "country" ("id", "name") VALUES ('ilo', 'ایلوکویی');
INSERT INTO "country" ("id", "name") VALUES ('inh', 'اینگوشی');
INSERT INTO "country" ("id", "name") VALUES ('ik', 'اینوپیک');
INSERT INTO "country" ("id", "name") VALUES ('iu', 'اینوکتیتوت');
INSERT INTO "country" ("id", "name") VALUES ('btk', 'باتاکی');
INSERT INTO "country" ("id", "name") VALUES ('bas', 'باسایی');
INSERT INTO "country" ("id", "name") VALUES ('eu', 'باسکی');
INSERT INTO "country" ("id", "name") VALUES ('ba', 'باشغیری');
INSERT INTO "country" ("id", "name") VALUES ('ban', 'بالیایی');
INSERT INTO "country" ("id", "name") VALUES ('bm', 'بامبارایی');
INSERT INTO "country" ("id", "name") VALUES ('bnt', 'بانتویی');
INSERT INTO "country" ("id", "name") VALUES ('bad', 'باندایی');
INSERT INTO "country" ("id", "name") VALUES ('bej', 'بجایی');
INSERT INTO "country" ("id", "name") VALUES ('zxx', 'بدون محتوای زبانی');
INSERT INTO "country" ("id", "name") VALUES ('bra', 'براج');
INSERT INTO "country" ("id", "name") VALUES ('ber', 'بربری');
INSERT INTO "country" ("id", "name") VALUES ('br', 'برتانیایی');
INSERT INTO "country" ("id", "name") VALUES ('my', 'برمه‌ای');
INSERT INTO "country" ("id", "name") VALUES ('bg', 'بلغاری');
INSERT INTO "country" ("id", "name") VALUES ('bal', 'بلوچی');
INSERT INTO "country" ("id", "name") VALUES ('be', 'بلوروسی');
INSERT INTO "country" ("id", "name") VALUES ('byn', 'بلین');
INSERT INTO "country" ("id", "name") VALUES ('bem', 'بمبایی');
INSERT INTO "country" ("id", "name") VALUES ('bn', 'بنگالی');
INSERT INTO "country" ("id", "name") VALUES ('bho', 'بوجپوری');
INSERT INTO "country" ("id", "name") VALUES ('bua', 'بوریاتی');
INSERT INTO "country" ("id", "name") VALUES ('bs', 'بوسنیایی');
INSERT INTO "country" ("id", "name") VALUES ('nb', 'بوکسمال نروژی');
INSERT INTO "country" ("id", "name") VALUES ('bug', 'بوگیایی');
INSERT INTO "country" ("id", "name") VALUES ('bi', 'بیسلاما');
INSERT INTO "country" ("id", "name") VALUES ('bik', 'بیکولی');
INSERT INTO "country" ("id", "name") VALUES ('bin', 'بینی');
INSERT INTO "country" ("id", "name") VALUES ('bh', 'بیهاری');
INSERT INTO "country" ("id", "name") VALUES ('pap', 'پاپیامنتو');
INSERT INTO "country" ("id", "name") VALUES ('pau', 'پالائویی');
INSERT INTO "country" ("id", "name") VALUES ('pi', 'پالی');
INSERT INTO "country" ("id", "name") VALUES ('pam', 'پامپانگایی');
INSERT INTO "country" ("id", "name") VALUES ('pon', 'پانپیی');
INSERT INTO "country" ("id", "name") VALUES ('pag', 'پانگاسینانی');
INSERT INTO "country" ("id", "name") VALUES ('pt_BR', 'پرتغالی برزیل');
INSERT INTO "country" ("id", "name") VALUES ('pt_PT', 'پرتغالی پرتغال');
INSERT INTO "country" ("id", "name") VALUES ('pt', 'پرتگالی');
INSERT INTO "country" ("id", "name") VALUES ('pro', 'پرووانسی باستان');
INSERT INTO "country" ("id", "name") VALUES ('ps', 'پشتو');
INSERT INTO "country" ("id", "name") VALUES ('pa', 'پنجابی');
INSERT INTO "country" ("id", "name") VALUES ('pal', 'پهلوی');
INSERT INTO "country" ("id", "name") VALUES ('pl', 'پولندی');
INSERT INTO "country" ("id", "name") VALUES ('tt', 'تاتاری');
INSERT INTO "country" ("id", "name") VALUES ('tg', 'تاجکی');
INSERT INTO "country" ("id", "name") VALUES ('srn', 'تاکی‌تاکی');
INSERT INTO "country" ("id", "name") VALUES ('tl', 'تاگالوگی');
INSERT INTO "country" ("id", "name") VALUES ('tmh', 'تاماشقی');
INSERT INTO "country" ("id", "name") VALUES ('ta', 'تامیلی');
INSERT INTO "country" ("id", "name") VALUES ('ty', 'تاهیتیایی');
INSERT INTO "country" ("id", "name") VALUES ('th', 'تایلندی');
INSERT INTO "country" ("id", "name") VALUES ('bo', 'تبتی');
INSERT INTO "country" ("id", "name") VALUES ('tet', 'تتومی');
INSERT INTO "country" ("id", "name") VALUES ('tk', 'ترکمنی');
INSERT INTO "country" ("id", "name") VALUES ('az', 'ترکی آذربایجانی');
INSERT INTO "country" ("id", "name") VALUES ('tr', 'ترکی استانبولی');
INSERT INTO "country" ("id", "name") VALUES ('ota', 'ترکی عثمانی');
INSERT INTO "country" ("id", "name") VALUES ('crh', 'ترکی کریمه');
INSERT INTO "country" ("id", "name") VALUES ('ter', 'ترنو');
INSERT INTO "country" ("id", "name") VALUES ('tn', 'تسوانایی');
INSERT INTO "country" ("id", "name") VALUES ('ts', 'تسونگایی');
INSERT INTO "country" ("id", "name") VALUES ('tsi', 'تسیم‌شیانی');
INSERT INTO "country" ("id", "name") VALUES ('te', 'تلوگویی');
INSERT INTO "country" ("id", "name") VALUES ('tli', 'تلین‌گیتی');
INSERT INTO "country" ("id", "name") VALUES ('tem', 'تمنه‌ای');
INSERT INTO "country" ("id", "name") VALUES ('tpi', 'توک‌پیسینی');
INSERT INTO "country" ("id", "name") VALUES ('tum', 'تومبوکایی');
INSERT INTO "country" ("id", "name") VALUES ('to', 'تونگایی');
INSERT INTO "country" ("id", "name") VALUES ('tog', 'تونگایی نیاسا');
INSERT INTO "country" ("id", "name") VALUES ('tvl', 'تووالویی');
INSERT INTO "country" ("id", "name") VALUES ('tyv', 'تووایی');
INSERT INTO "country" ("id", "name") VALUES ('tw', 'توی‌یایی');
INSERT INTO "country" ("id", "name") VALUES ('tig', 'تیگره‌ای');
INSERT INTO "country" ("id", "name") VALUES ('ti', 'تیگرینیایی');
INSERT INTO "country" ("id", "name") VALUES ('tiv', 'تیوی');
INSERT INTO "country" ("id", "name") VALUES ('ja', 'جاپانی');
INSERT INTO "country" ("id", "name") VALUES ('jv', 'جاوه‌ای');
INSERT INTO "country" ("id", "name") VALUES ('chg', 'جغتایی');
INSERT INTO "country" ("id", "name") VALUES ('kaj', 'جو');
INSERT INTO "country" ("id", "name") VALUES ('dz', 'جونخایی');
INSERT INTO "country" ("id", "name") VALUES ('ch', 'چامورویی');
INSERT INTO "country" ("id", "name") VALUES ('ce', 'چچنی');
INSERT INTO "country" ("id", "name") VALUES ('chr', 'چروکیایی');
INSERT INTO "country" ("id", "name") VALUES ('cs', 'چکی');
INSERT INTO "country" ("id", "name") VALUES ('za', 'چوانگی');
INSERT INTO "country" ("id", "name") VALUES ('cho', 'چوکتویی');
INSERT INTO "country" ("id", "name") VALUES ('chk', 'چوکی');
INSERT INTO "country" ("id", "name") VALUES ('cv', 'چوواشی');
INSERT INTO "country" ("id", "name") VALUES ('chb', 'چیبچا');
INSERT INTO "country" ("id", "name") VALUES ('chp', 'چیپه‌ویه‌ای');
INSERT INTO "country" ("id", "name") VALUES ('zh', 'چینی');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hans', 'چینی ساده‌شده');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hant', 'چینی سنتی');
INSERT INTO "country" ("id", "name") VALUES ('kha', 'خاسیایی');
INSERT INTO "country" ("id", "name") VALUES ('kho', 'ختنی');
INSERT INTO "country" ("id", "name") VALUES ('km', 'خمری');
INSERT INTO "country" ("id", "name") VALUES ('xh', 'خوسایی');
INSERT INTO "country" ("id", "name") VALUES ('dar', 'دارقینی');
INSERT INTO "country" ("id", "name") VALUES ('dak', 'داکوتایی');
INSERT INTO "country" ("id", "name") VALUES ('da', 'دانمارکی');
INSERT INTO "country" ("id", "name") VALUES ('day', 'دایاک');
INSERT INTO "country" ("id", "name") VALUES ('dyu', 'دایولایی');
INSERT INTO "country" ("id", "name") VALUES ('fa', 'دری');
INSERT INTO "country" ("id", "name") VALUES ('del', 'دلاواری');
INSERT INTO "country" ("id", "name") VALUES ('dua', 'دوآلایی');
INSERT INTO "country" ("id", "name") VALUES ('doi', 'دوگری');
INSERT INTO "country" ("id", "name") VALUES ('dgr', 'دوگریب');
INSERT INTO "country" ("id", "name") VALUES ('din', 'دینکایی');
INSERT INTO "country" ("id", "name") VALUES ('rap', 'راپانویی');
INSERT INTO "country" ("id", "name") VALUES ('raj', 'راجستانی');
INSERT INTO "country" ("id", "name") VALUES ('rar', 'راروتونگایی');
INSERT INTO "country" ("id", "name") VALUES ('ru', 'روسی');
INSERT INTO "country" ("id", "name") VALUES ('rm', 'رومانش');
INSERT INTO "country" ("id", "name") VALUES ('rom', 'رومانویی');
INSERT INTO "country" ("id", "name") VALUES ('ro', 'رومانیایی');
INSERT INTO "country" ("id", "name") VALUES ('rn', 'روندیایی');
INSERT INTO "country" ("id", "name") VALUES ('root', 'ریشه');
INSERT INTO "country" ("id", "name") VALUES ('zap', 'زاپوتکی');
INSERT INTO "country" ("id", "name") VALUES ('zza', 'زازایی');
INSERT INTO "country" ("id", "name") VALUES ('znd', 'زانده‌ای');
INSERT INTO "country" ("id", "name") VALUES ('apa', 'زبان آپاچیایی');
INSERT INTO "country" ("id", "name") VALUES ('ath', 'زبان آتاپاسکایی');
INSERT INTO "country" ("id", "name") VALUES ('map', 'زبان آسترونیزیایی');
INSERT INTO "country" ("id", "name") VALUES ('tut', 'زبان آلتاییک');
INSERT INTO "country" ("id", "name") VALUES ('alg', 'زبان آلگونکینی');
INSERT INTO "country" ("id", "name") VALUES ('oto', 'زبان اتومیایی');
INSERT INTO "country" ("id", "name") VALUES ('aus', 'زبان استرالیایی');
INSERT INTO "country" ("id", "name") VALUES ('sla', 'زبان اسلاوی');
INSERT INTO "country" ("id", "name") VALUES ('sgn', 'زبان اشاره');
INSERT INTO "country" ("id", "name") VALUES ('afa', 'زبان افریقا و آسیایی');
INSERT INTO "country" ("id", "name") VALUES ('ira', 'زبان ایرانی');
INSERT INTO "country" ("id", "name") VALUES ('iro', 'زبان ایروکوایی');
INSERT INTO "country" ("id", "name") VALUES ('bat', 'زبان بالتیکی');
INSERT INTO "country" ("id", "name") VALUES ('paa', 'زبان پاپوایی');
INSERT INTO "country" ("id", "name") VALUES ('pra', 'زبان پراکریتی');
INSERT INTO "country" ("id", "name") VALUES ('tai', 'زبان تایی');
INSERT INTO "country" ("id", "name") VALUES ('tup', 'زبان توپیایی');
INSERT INTO "country" ("id", "name") VALUES ('sit', 'زبان چین و تبتی');
INSERT INTO "country" ("id", "name") VALUES ('khi', 'زبان خواسی');
INSERT INTO "country" ("id", "name") VALUES ('dra', 'زبان دراویدی');
INSERT INTO "country" ("id", "name") VALUES ('roa', 'زبان رومیایی');
INSERT INTO "country" ("id", "name") VALUES ('gem', 'زبان ژرمنی');
INSERT INTO "country" ("id", "name") VALUES ('art', 'زبان ساختگی');
INSERT INTO "country" ("id", "name") VALUES ('sal', 'زبان سالیشی');
INSERT INTO "country" ("id", "name") VALUES ('sem', 'زبان سامی');
INSERT INTO "country" ("id", "name") VALUES ('sai', 'زبان سرخپوستی امریکای جنوبی');
INSERT INTO "country" ("id", "name") VALUES ('nai', 'زبان سرخپوستی امریکای شمالی');
INSERT INTO "country" ("id", "name") VALUES ('cai', 'زبان سرخپوستی امریکای مرکزی');
INSERT INTO "country" ("id", "name") VALUES ('cel', 'زبان سلتی');
INSERT INTO "country" ("id", "name") VALUES ('sio', 'زبان سویی');
INSERT INTO "country" ("id", "name") VALUES ('wen', 'زبان صُربی');
INSERT INTO "country" ("id", "name") VALUES ('phi', 'زبان فیلیپینی');
INSERT INTO "country" ("id", "name") VALUES ('fiu', 'زبان فین و اوگرایی');
INSERT INTO "country" ("id", "name") VALUES ('cau', 'زبان قفقازی');
INSERT INTO "country" ("id", "name") VALUES ('cus', 'زبان کوشی');
INSERT INTO "country" ("id", "name") VALUES ('mno', 'زبان مانوبو');
INSERT INTO "country" ("id", "name") VALUES ('myn', 'زبان مایایی');
INSERT INTO "country" ("id", "name") VALUES ('mis', 'زبان متفرقه');
INSERT INTO "country" ("id", "name") VALUES ('mkh', 'زبان مون‌خمری');
INSERT INTO "country" ("id", "name") VALUES ('mun', 'زبان موندایی');
INSERT INTO "country" ("id", "name") VALUES ('und', 'زبان نامشخص');
INSERT INTO "country" ("id", "name") VALUES ('nub', 'زبان نوبیایی');
INSERT INTO "country" ("id", "name") VALUES ('ssa', 'زبان نیلی و صحرایی');
INSERT INTO "country" ("id", "name") VALUES ('ine', 'زبان هند و اروپایی');
INSERT INTO "country" ("id", "name") VALUES ('inc', 'زبان هندیک');
INSERT INTO "country" ("id", "name") VALUES ('wak', 'زبان واکاشی');
INSERT INTO "country" ("id", "name") VALUES ('ypk', 'زبان یوپیکی');
INSERT INTO "country" ("id", "name") VALUES ('zen', 'زناگا');
INSERT INTO "country" ("id", "name") VALUES ('zu', 'زولویی');
INSERT INTO "country" ("id", "name") VALUES ('zun', 'زونیایی');
INSERT INTO "country" ("id", "name") VALUES ('sc', 'ساردینیایی');
INSERT INTO "country" ("id", "name") VALUES ('sas', 'ساساکی');
INSERT INTO "country" ("id", "name") VALUES ('sm', 'ساموآیی');
INSERT INTO "country" ("id", "name") VALUES ('se', 'سامی شمالی');
INSERT INTO "country" ("id", "name") VALUES ('sat', 'سانتالی');
INSERT INTO "country" ("id", "name") VALUES ('sad', 'سانداوه‌ای');
INSERT INTO "country" ("id", "name") VALUES ('sg', 'سانگویی');
INSERT INTO "country" ("id", "name") VALUES ('ceb', 'سبویی');
INSERT INTO "country" ("id", "name") VALUES ('syr', 'سریانی');
INSERT INTO "country" ("id", "name") VALUES ('syc', 'سریانی کلاسیک');
INSERT INTO "country" ("id", "name") VALUES ('srr', 'سریری');
INSERT INTO "country" ("id", "name") VALUES ('sog', 'سغدی');
INSERT INTO "country" ("id", "name") VALUES ('sel', 'سلکوپی');
INSERT INTO "country" ("id", "name") VALUES ('sd', 'سندی');
INSERT INTO "country" ("id", "name") VALUES ('sa', 'سنسکریت');
INSERT INTO "country" ("id", "name") VALUES ('sw', 'سواحلی');
INSERT INTO "country" ("id", "name") VALUES ('ss', 'سوازیایی');
INSERT INTO "country" ("id", "name") VALUES ('st', 'سوتویی جنوبی');
INSERT INTO "country" ("id", "name") VALUES ('nso', 'سوتویی شمالی');
INSERT INTO "country" ("id", "name") VALUES ('sus', 'سوسویی');
INSERT INTO "country" ("id", "name") VALUES ('suk', 'سوکومایی');
INSERT INTO "country" ("id", "name") VALUES ('so', 'سومالیایی');
INSERT INTO "country" ("id", "name") VALUES ('sux', 'سومری');
INSERT INTO "country" ("id", "name") VALUES ('su', 'سوندایی');
INSERT INTO "country" ("id", "name") VALUES ('son', 'سونغایی');
INSERT INTO "country" ("id", "name") VALUES ('snk', 'سونینکه‌ای');
INSERT INTO "country" ("id", "name") VALUES ('sv', 'سویدنی');
INSERT INTO "country" ("id", "name") VALUES ('sid', 'سیدامویی');
INSERT INTO "country" ("id", "name") VALUES ('scn', 'سیسیلی');
INSERT INTO "country" ("id", "name") VALUES ('si', 'سینهالی');
INSERT INTO "country" ("id", "name") VALUES ('shn', 'شانی');
INSERT INTO "country" ("id", "name") VALUES ('chy', 'شایانی');
INSERT INTO "country" ("id", "name") VALUES ('sn', 'شونایی');
INSERT INTO "country" ("id", "name") VALUES ('sh', 'صرب و کرواتی');
INSERT INTO "country" ("id", "name") VALUES ('sr', 'صربی');
INSERT INTO "country" ("id", "name") VALUES ('dsb', 'صُربی سفلی');
INSERT INTO "country" ("id", "name") VALUES ('hsb', 'صُربی علیا');
INSERT INTO "country" ("id", "name") VALUES ('he', 'عبری');
INSERT INTO "country" ("id", "name") VALUES ('ar', 'عربی');
INSERT INTO "country" ("id", "name") VALUES ('jrb', 'عربی یهودی');
INSERT INTO "country" ("id", "name") VALUES ('elx', 'عیلامی');
INSERT INTO "country" ("id", "name") VALUES ('peo', 'فارسی باستان');
INSERT INTO "country" ("id", "name") VALUES ('jpr', 'فارسی یهودی');
INSERT INTO "country" ("id", "name") VALUES ('fo', 'فارویی');
INSERT INTO "country" ("id", "name") VALUES ('fat', 'فانتیایی');
INSERT INTO "country" ("id", "name") VALUES ('fan', 'فانکی');
INSERT INTO "country" ("id", "name") VALUES ('fr', 'فرانسوی');
INSERT INTO "country" ("id", "name") VALUES ('fro', 'فرانسوی باستان');
INSERT INTO "country" ("id", "name") VALUES ('fr_CH', 'فرانسوی سوئیس');
INSERT INTO "country" ("id", "name") VALUES ('fr_CA', 'فرانسوی کانادا');
INSERT INTO "country" ("id", "name") VALUES ('frm', 'فرانسوی میانه');
INSERT INTO "country" ("id", "name") VALUES ('frs', 'فریزی شرقی');
INSERT INTO "country" ("id", "name") VALUES ('frr', 'فریزی شمالی');
INSERT INTO "country" ("id", "name") VALUES ('fy', 'فریزی غربی');
INSERT INTO "country" ("id", "name") VALUES ('fur', 'فریولیایی');
INSERT INTO "country" ("id", "name") VALUES ('nl_BE', 'فلمنگی');
INSERT INTO "country" ("id", "name") VALUES ('fi', 'فنلندی');
INSERT INTO "country" ("id", "name") VALUES ('phn', 'فنیقی');
INSERT INTO "country" ("id", "name") VALUES ('ff', 'فولایی');
INSERT INTO "country" ("id", "name") VALUES ('fon', 'فونی');
INSERT INTO "country" ("id", "name") VALUES ('fj', 'فیجیایی');
INSERT INTO "country" ("id", "name") VALUES ('fil', 'فیلیپینی');
INSERT INTO "country" ("id", "name") VALUES ('kab', 'قبایلی');
INSERT INTO "country" ("id", "name") VALUES ('cop', 'قبطی');
INSERT INTO "country" ("id", "name") VALUES ('ky', 'قرغزی');
INSERT INTO "country" ("id", "name") VALUES ('krc', 'قره‌چایی‐بالکاری');
INSERT INTO "country" ("id", "name") VALUES ('kaa', 'قره‌قالپاقی');
INSERT INTO "country" ("id", "name") VALUES ('kk', 'قزاقی');
INSERT INTO "country" ("id", "name") VALUES ('xal', 'قلموقی');
INSERT INTO "country" ("id", "name") VALUES ('kbd', 'کاباردینی');
INSERT INTO "country" ("id", "name") VALUES ('ca', 'کاتالان');
INSERT INTO "country" ("id", "name") VALUES ('kac', 'کاچینی');
INSERT INTO "country" ("id", "name") VALUES ('cad', 'کادویی');
INSERT INTO "country" ("id", "name") VALUES ('kar', 'کارنی');
INSERT INTO "country" ("id", "name") VALUES ('car', 'کاریبی');
INSERT INTO "country" ("id", "name") VALUES ('csb', 'کاشوبی');
INSERT INTO "country" ("id", "name") VALUES ('kam', 'کامبایی');
INSERT INTO "country" ("id", "name") VALUES ('kn', 'کاناده‌ای');
INSERT INTO "country" ("id", "name") VALUES ('yue', 'کانتونیز');
INSERT INTO "country" ("id", "name") VALUES ('kr', 'کانوریایی');
INSERT INTO "country" ("id", "name") VALUES ('kaw', 'کاویایی');
INSERT INTO "country" ("id", "name") VALUES ('kpe', 'کپله‌ای');
INSERT INTO "country" ("id", "name") VALUES ('qu', 'کچوایی');
INSERT INTO "country" ("id", "name") VALUES ('ku', 'کردی');
INSERT INTO "country" ("id", "name") VALUES ('kw', 'کرنوالی');
INSERT INTO "country" ("id", "name") VALUES ('hr', 'کروشیایی');
INSERT INTO "country" ("id", "name") VALUES ('kro', 'کرویی');
INSERT INTO "country" ("id", "name") VALUES ('cr', 'کریایی');
INSERT INTO "country" ("id", "name") VALUES ('mus', 'کریکی');
INSERT INTO "country" ("id", "name") VALUES ('crp', 'کریول یا پیجین');
INSERT INTO "country" ("id", "name") VALUES ('cpe', 'کریول یا پیجین مبتنی بر انگلیسی');
INSERT INTO "country" ("id", "name") VALUES ('cpp', 'کریول یا پیجین مبتنی بر پرتغالی');
INSERT INTO "country" ("id", "name") VALUES ('cpf', 'کریول یا پیجین مبتنی بر فرانسوی');
INSERT INTO "country" ("id", "name") VALUES ('ks', 'کشمیری');
INSERT INTO "country" ("id", "name") VALUES ('tlh', 'کلینگون');
INSERT INTO "country" ("id", "name") VALUES ('kok', 'کنکانی');
INSERT INTO "country" ("id", "name") VALUES ('kg', 'کنگویی');
INSERT INTO "country" ("id", "name") VALUES ('kj', 'کوانیاما');
INSERT INTO "country" ("id", "name") VALUES ('kut', 'کوتنی');
INSERT INTO "country" ("id", "name") VALUES ('co', 'کورسی');
INSERT INTO "country" ("id", "name") VALUES ('kfo', 'کورو');
INSERT INTO "country" ("id", "name") VALUES ('kru', 'کوروخی');
INSERT INTO "country" ("id", "name") VALUES ('ko', 'کوریایی');
INSERT INTO "country" ("id", "name") VALUES ('swb', 'کوموری');
INSERT INTO "country" ("id", "name") VALUES ('kv', 'کومیایی');
INSERT INTO "country" ("id", "name") VALUES ('kum', 'کومیکی');
INSERT INTO "country" ("id", "name") VALUES ('ki', 'کیکویویی');
INSERT INTO "country" ("id", "name") VALUES ('kmb', 'کیمبوندویی');
INSERT INTO "country" ("id", "name") VALUES ('rw', 'کینیارواندایی');
INSERT INTO "country" ("id", "name") VALUES ('gl', 'گالیسیایی');
INSERT INTO "country" ("id", "name") VALUES ('lg', 'گاندایی');
INSERT INTO "country" ("id", "name") VALUES ('gay', 'گایویی');
INSERT INTO "country" ("id", "name") VALUES ('gaa', 'گایی');
INSERT INTO "country" ("id", "name") VALUES ('gba', 'گبایایی');
INSERT INTO "country" ("id", "name") VALUES ('gu', 'گجراتی');
INSERT INTO "country" ("id", "name") VALUES ('ka', 'گرجی');
INSERT INTO "country" ("id", "name") VALUES ('grb', 'گریبویی');
INSERT INTO "country" ("id", "name") VALUES ('kl', 'گرینلندی');
INSERT INTO "country" ("id", "name") VALUES ('gn', 'گوارانی');
INSERT INTO "country" ("id", "name") VALUES ('got', 'گوتی');
INSERT INTO "country" ("id", "name") VALUES ('gor', 'گورونتالو');
INSERT INTO "country" ("id", "name") VALUES ('gon', 'گوندی');
INSERT INTO "country" ("id", "name") VALUES ('gwi', 'گویچ این');
INSERT INTO "country" ("id", "name") VALUES ('gez', 'گی‌ئزی');
INSERT INTO "country" ("id", "name") VALUES ('gil', 'گیلبرتی');
INSERT INTO "country" ("id", "name") VALUES ('gd', 'گیلی اسکاتلندی');
INSERT INTO "country" ("id", "name") VALUES ('la', 'لاتینی');
INSERT INTO "country" ("id", "name") VALUES ('lad', 'لادینو');
INSERT INTO "country" ("id", "name") VALUES ('lam', 'لامبا');
INSERT INTO "country" ("id", "name") VALUES ('lah', 'لاهندا');
INSERT INTO "country" ("id", "name") VALUES ('lo', 'لائوسی');
INSERT INTO "country" ("id", "name") VALUES ('lv', 'لتونیایی');
INSERT INTO "country" ("id", "name") VALUES ('lez', 'لزگی');
INSERT INTO "country" ("id", "name") VALUES ('lu', 'لوبایی‐کاتانگا');
INSERT INTO "country" ("id", "name") VALUES ('lua', 'لوبایی‐لولوا');
INSERT INTO "country" ("id", "name") VALUES ('jbo', 'لوجبان');
INSERT INTO "country" ("id", "name") VALUES ('loz', 'لوزیایی');
INSERT INTO "country" ("id", "name") VALUES ('lus', 'لوشه‌ای');
INSERT INTO "country" ("id", "name") VALUES ('lb', 'لوگزامبورگی');
INSERT INTO "country" ("id", "name") VALUES ('lun', 'لوندایی');
INSERT INTO "country" ("id", "name") VALUES ('lui', 'لویسنو');
INSERT INTO "country" ("id", "name") VALUES ('luo', 'لوئویی');
INSERT INTO "country" ("id", "name") VALUES ('lt', 'لیتوانیایی');
INSERT INTO "country" ("id", "name") VALUES ('li', 'لیمبورگی');
INSERT INTO "country" ("id", "name") VALUES ('ln', 'لینگالا');
INSERT INTO "country" ("id", "name") VALUES ('mad', 'مادورایی');
INSERT INTO "country" ("id", "name") VALUES ('mh', 'مارشالی');
INSERT INTO "country" ("id", "name") VALUES ('mwr', 'مارواری');
INSERT INTO "country" ("id", "name") VALUES ('chm', 'ماریایی');
INSERT INTO "country" ("id", "name") VALUES ('mas', 'ماسایی');
INSERT INTO "country" ("id", "name") VALUES ('mos', 'ماسیایی');
INSERT INTO "country" ("id", "name") VALUES ('mak', 'ماکاسار');
INSERT INTO "country" ("id", "name") VALUES ('mag', 'ماگاهیایی');
INSERT INTO "country" ("id", "name") VALUES ('mg', 'مالاگاسیایی');
INSERT INTO "country" ("id", "name") VALUES ('ml', 'مالایالامی');
INSERT INTO "country" ("id", "name") VALUES ('ms', 'مالایی');
INSERT INTO "country" ("id", "name") VALUES ('mt', 'مالتی');
INSERT INTO "country" ("id", "name") VALUES ('dv', 'مالدیوی');
INSERT INTO "country" ("id", "name") VALUES ('mnc', 'مانچویی');
INSERT INTO "country" ("id", "name") VALUES ('mdr', 'ماندار');
INSERT INTO "country" ("id", "name") VALUES ('man', 'ماندینگویی');
INSERT INTO "country" ("id", "name") VALUES ('gv', 'مانی');
INSERT INTO "country" ("id", "name") VALUES ('mai', 'مایدیلی');
INSERT INTO "country" ("id", "name") VALUES ('mi', 'مائوریایی');
INSERT INTO "country" ("id", "name") VALUES ('hu', 'مجاری');
INSERT INTO "country" ("id", "name") VALUES ('mr', 'مراتی');
INSERT INTO "country" ("id", "name") VALUES ('egy', 'مصری کهن');
INSERT INTO "country" ("id", "name") VALUES ('mn', 'مغلی');
INSERT INTO "country" ("id", "name") VALUES ('mk', 'مقدونی');
INSERT INTO "country" ("id", "name") VALUES ('mdf', 'مکشایی');
INSERT INTO "country" ("id", "name") VALUES ('men', 'منده‌ای');
INSERT INTO "country" ("id", "name") VALUES ('ho', 'موتویی هیری');
INSERT INTO "country" ("id", "name") VALUES ('mo', 'مولداویایی');
INSERT INTO "country" ("id", "name") VALUES ('lol', 'مونگویی');
INSERT INTO "country" ("id", "name") VALUES ('moh', 'موهاکی');
INSERT INTO "country" ("id", "name") VALUES ('ia', 'میان‌زبان');
INSERT INTO "country" ("id", "name") VALUES ('mni', 'میته‌ای');
INSERT INTO "country" ("id", "name") VALUES ('mic', 'میکماکی');
INSERT INTO "country" ("id", "name") VALUES ('min', 'مینانگ‌کابویی');
INSERT INTO "country" ("id", "name") VALUES ('nap', 'ناپلی');
INSERT INTO "country" ("id", "name") VALUES ('no', 'نارویژی');
INSERT INTO "country" ("id", "name") VALUES ('nah', 'ناواتلی');
INSERT INTO "country" ("id", "name") VALUES ('nv', 'ناواهویی');
INSERT INTO "country" ("id", "name") VALUES ('na', 'نائورویی');
INSERT INTO "country" ("id", "name") VALUES ('non', 'نرس باستان');
INSERT INTO "country" ("id", "name") VALUES ('nn', 'نرس جدید نروژی');
INSERT INTO "country" ("id", "name") VALUES ('nzi', 'نزیمایی');
INSERT INTO "country" ("id", "name") VALUES ('nog', 'نغایی');
INSERT INTO "country" ("id", "name") VALUES ('new', 'نواریایی');
INSERT INTO "country" ("id", "name") VALUES ('nwc', 'نواریایی کلاسیک');
INSERT INTO "country" ("id", "name") VALUES ('nia', 'نیاسی');
INSERT INTO "country" ("id", "name") VALUES ('nym', 'نیام‌وزیایی');
INSERT INTO "country" ("id", "name") VALUES ('ny', 'نیانجایی');
INSERT INTO "country" ("id", "name") VALUES ('nyn', 'نیانکوله‌ای');
INSERT INTO "country" ("id", "name") VALUES ('ne', 'نیپالی');
INSERT INTO "country" ("id", "name") VALUES ('nyo', 'نیورویی');
INSERT INTO "country" ("id", "name") VALUES ('niu', 'نیویی');
INSERT INTO "country" ("id", "name") VALUES ('nl', 'هالندی');
INSERT INTO "country" ("id", "name") VALUES ('haw', 'هاوائیایی');
INSERT INTO "country" ("id", "name") VALUES ('hai', 'هایدایی');
INSERT INTO "country" ("id", "name") VALUES ('ht', 'هائیتیایی');
INSERT INTO "country" ("id", "name") VALUES ('hz', 'هریرویی');
INSERT INTO "country" ("id", "name") VALUES ('es', 'هسپانوی');
INSERT INTO "country" ("id", "name") VALUES ('dum', 'هلندی میانه');
INSERT INTO "country" ("id", "name") VALUES ('hmn', 'همونگ');
INSERT INTO "country" ("id", "name") VALUES ('hi', 'هندی');
INSERT INTO "country" ("id", "name") VALUES ('hup', 'هوپا');
INSERT INTO "country" ("id", "name") VALUES ('ha', 'هوسیایی');
INSERT INTO "country" ("id", "name") VALUES ('hit', 'هیتی');
INSERT INTO "country" ("id", "name") VALUES ('hil', 'هیلی‌گاینونی');
INSERT INTO "country" ("id", "name") VALUES ('him', 'هیماچالی');
INSERT INTO "country" ("id", "name") VALUES ('war', 'وارایی');
INSERT INTO "country" ("id", "name") VALUES ('was', 'واشویی');
INSERT INTO "country" ("id", "name") VALUES ('wal', 'والامو');
INSERT INTO "country" ("id", "name") VALUES ('wa', 'والونی');
INSERT INTO "country" ("id", "name") VALUES ('vot', 'وتی');
INSERT INTO "country" ("id", "name") VALUES ('vo', 'ولاپوک');
INSERT INTO "country" ("id", "name") VALUES ('wo', 'ولوفی');
INSERT INTO "country" ("id", "name") VALUES ('ve', 'وندایی');
INSERT INTO "country" ("id", "name") VALUES ('vai', 'ویایی');
INSERT INTO "country" ("id", "name") VALUES ('vi', 'ویتنامی');
INSERT INTO "country" ("id", "name") VALUES ('cy', 'ویلزی');
INSERT INTO "country" ("id", "name") VALUES ('yap', 'یاپی');
INSERT INTO "country" ("id", "name") VALUES ('sah', 'یاقوتی');
INSERT INTO "country" ("id", "name") VALUES ('yao', 'یائویی');
INSERT INTO "country" ("id", "name") VALUES ('yi', 'یدی');
INSERT INTO "country" ("id", "name") VALUES ('yo', 'یوروبایی');
INSERT INTO "country" ("id", "name") VALUES ('el', 'یونانی');
INSERT INTO "country" ("id", "name") VALUES ('grc', 'یونانی کهن');
INSERT INTO "country" ("id", "name") VALUES ('ii', 'یی سیچوان');
