CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('cai', 'Indíánamál Mið-Ameríku (önnur)');
INSERT INTO [country] ([id], [name]) VALUES ('nai', 'Indíánamál Norður-Ameríku (önnur)');
INSERT INTO [country] ([id], [name]) VALUES ('sai', 'Indíánamál Suður-Ameríku (önnur)');
INSERT INTO [country] ([id], [name]) VALUES ('nds', 'Lágþýska; Lágsaxneska');
INSERT INTO [country] ([id], [name]) VALUES ('ny', 'Njanja; Sísjeva; Sjeva');
INSERT INTO [country] ([id], [name]) VALUES ('nqo', 'N’Ko');
INSERT INTO [country] ([id], [name]) VALUES ('oc', 'Okkitíska (eftir 1500); Próvensalska');
INSERT INTO [country] ([id], [name]) VALUES ('tog', 'Tongverska (Nyasa)');
INSERT INTO [country] ([id], [name]) VALUES ('to', 'Tongverska (Tongaeyjar)');
INSERT INTO [country] ([id], [name]) VALUES ('ab', 'abkasíska');
INSERT INTO [country] ([id], [name]) VALUES ('ada', 'adangme');
INSERT INTO [country] ([id], [name]) VALUES ('ady', 'adýge');
INSERT INTO [country] ([id], [name]) VALUES ('afh', 'afríhílí');
INSERT INTO [country] ([id], [name]) VALUES ('af', 'afríkanska');
INSERT INTO [country] ([id], [name]) VALUES ('afa', 'afróasísk mál (önnur)');
INSERT INTO [country] ([id], [name]) VALUES ('aa', 'afár');
INSERT INTO [country] ([id], [name]) VALUES ('ak', 'akan');
INSERT INTO [country] ([id], [name]) VALUES ('akk', 'akkadíska');
INSERT INTO [country] ([id], [name]) VALUES ('ace', 'akkíska');
INSERT INTO [country] ([id], [name]) VALUES ('ach', 'akólí');
INSERT INTO [country] ([id], [name]) VALUES ('sq', 'albanska');
INSERT INTO [country] ([id], [name]) VALUES ('ale', 'aleúska');
INSERT INTO [country] ([id], [name]) VALUES ('alg', 'algonkvínsk mál');
INSERT INTO [country] ([id], [name]) VALUES ('tut', 'altaísk mál (önnur)');
INSERT INTO [country] ([id], [name]) VALUES ('art', 'alþjóðamál (önnur)');
INSERT INTO [country] ([id], [name]) VALUES ('am', 'amharíska');
INSERT INTO [country] ([id], [name]) VALUES ('anp', 'angíka');
INSERT INTO [country] ([id], [name]) VALUES ('apa', 'apatsjamál');
INSERT INTO [country] ([id], [name]) VALUES ('ar', 'arabíska');
INSERT INTO [country] ([id], [name]) VALUES ('an', 'aragonska');
INSERT INTO [country] ([id], [name]) VALUES ('arc', 'arameíska');
INSERT INTO [country] ([id], [name]) VALUES ('arp', 'arapahó');
INSERT INTO [country] ([id], [name]) VALUES ('arw', 'aravakska');
INSERT INTO [country] ([id], [name]) VALUES ('hy', 'armenska');
INSERT INTO [country] ([id], [name]) VALUES ('arn', 'arákaníska');
INSERT INTO [country] ([id], [name]) VALUES ('rup', 'arúmenska');
INSERT INTO [country] ([id], [name]) VALUES ('az', 'aserska');
INSERT INTO [country] ([id], [name]) VALUES ('as', 'assamska');
INSERT INTO [country] ([id], [name]) VALUES ('ast', 'astúríska');
INSERT INTO [country] ([id], [name]) VALUES ('ath', 'atapaskísk mál');
INSERT INTO [country] ([id], [name]) VALUES ('cch', 'atsam');
INSERT INTO [country] ([id], [name]) VALUES ('frs', 'austurfrísneska');
INSERT INTO [country] ([id], [name]) VALUES ('de_AT', 'austurrísk þýska');
INSERT INTO [country] ([id], [name]) VALUES ('awa', 'avadí');
INSERT INTO [country] ([id], [name]) VALUES ('av', 'avaríska');
INSERT INTO [country] ([id], [name]) VALUES ('ae', 'avestíska');
INSERT INTO [country] ([id], [name]) VALUES ('ay', 'aímara');
INSERT INTO [country] ([id], [name]) VALUES ('ain', 'aínu (Japan)');
INSERT INTO [country] ([id], [name]) VALUES ('bat', 'baltnesk mál (önnur)');
INSERT INTO [country] ([id], [name]) VALUES ('ban', 'balíska');
INSERT INTO [country] ([id], [name]) VALUES ('bal', 'balúkí');
INSERT INTO [country] ([id], [name]) VALUES ('bm', 'bambara');
INSERT INTO [country] ([id], [name]) VALUES ('bai', 'bamílekemál');
INSERT INTO [country] ([id], [name]) VALUES ('bad', 'banda');
INSERT INTO [country] ([id], [name]) VALUES ('en_US', 'bandarísk enska');
INSERT INTO [country] ([id], [name]) VALUES ('bnt', 'bantúmál');
INSERT INTO [country] ([id], [name]) VALUES ('bas', 'basa');
INSERT INTO [country] ([id], [name]) VALUES ('eu', 'baskneska');
INSERT INTO [country] ([id], [name]) VALUES ('ba', 'baskír');
INSERT INTO [country] ([id], [name]) VALUES ('btk', 'batak');
INSERT INTO [country] ([id], [name]) VALUES ('bej', 'beja');
INSERT INTO [country] ([id], [name]) VALUES ('bem', 'bemba');
INSERT INTO [country] ([id], [name]) VALUES ('bn', 'bengalska');
INSERT INTO [country] ([id], [name]) VALUES ('ber', 'berbamál');
INSERT INTO [country] ([id], [name]) VALUES ('zbl', 'blisstákn');
INSERT INTO [country] ([id], [name]) VALUES ('byn', 'blín');
INSERT INTO [country] ([id], [name]) VALUES ('bho', 'bojpúrí');
INSERT INTO [country] ([id], [name]) VALUES ('bs', 'bosníska');
INSERT INTO [country] ([id], [name]) VALUES ('pt_BR', 'brasílísk portúgalska');
INSERT INTO [country] ([id], [name]) VALUES ('bra', 'braí');
INSERT INTO [country] ([id], [name]) VALUES ('en_GB', 'bresk enska');
INSERT INTO [country] ([id], [name]) VALUES ('br', 'bretónska');
INSERT INTO [country] ([id], [name]) VALUES ('my', 'burmneska');
INSERT INTO [country] ([id], [name]) VALUES ('bh', 'bíharí');
INSERT INTO [country] ([id], [name]) VALUES ('bik', 'bíkol');
INSERT INTO [country] ([id], [name]) VALUES ('bin', 'bíní');
INSERT INTO [country] ([id], [name]) VALUES ('bi', 'bíslama');
INSERT INTO [country] ([id], [name]) VALUES ('bug', 'búgíska');
INSERT INTO [country] ([id], [name]) VALUES ('bg', 'búlgarska');
INSERT INTO [country] ([id], [name]) VALUES ('bua', 'búríat');
INSERT INTO [country] ([id], [name]) VALUES ('day', 'dajak');
INSERT INTO [country] ([id], [name]) VALUES ('dak', 'dakóta');
INSERT INTO [country] ([id], [name]) VALUES ('da', 'danska');
INSERT INTO [country] ([id], [name]) VALUES ('dar', 'dargva');
INSERT INTO [country] ([id], [name]) VALUES ('del', 'delaver');
INSERT INTO [country] ([id], [name]) VALUES ('din', 'dinka');
INSERT INTO [country] ([id], [name]) VALUES ('dyu', 'djúla');
INSERT INTO [country] ([id], [name]) VALUES ('doi', 'dogrí');
INSERT INTO [country] ([id], [name]) VALUES ('dgr', 'dogríb');
INSERT INTO [country] ([id], [name]) VALUES ('dra', 'dravidísk mál (önnur)');
INSERT INTO [country] ([id], [name]) VALUES ('dz', 'dsongka');
INSERT INTO [country] ([id], [name]) VALUES ('dv', 'dívehí');
INSERT INTO [country] ([id], [name]) VALUES ('dua', 'dúala');
INSERT INTO [country] ([id], [name]) VALUES ('efi', 'efík');
INSERT INTO [country] ([id], [name]) VALUES ('et', 'eistneska');
INSERT INTO [country] ([id], [name]) VALUES ('eka', 'ekajúk');
INSERT INTO [country] ([id], [name]) VALUES ('zxx', 'ekkert tungutengt efni');
INSERT INTO [country] ([id], [name]) VALUES ('elx', 'elamít');
INSERT INTO [country] ([id], [name]) VALUES ('smn', 'enaresamíska');
INSERT INTO [country] ([id], [name]) VALUES ('en', 'enska');
INSERT INTO [country] ([id], [name]) VALUES ('myv', 'ersja');
INSERT INTO [country] ([id], [name]) VALUES ('eo', 'esperantó');
INSERT INTO [country] ([id], [name]) VALUES ('ee', 'eve');
INSERT INTO [country] ([id], [name]) VALUES ('ewo', 'evondó');
INSERT INTO [country] ([id], [name]) VALUES ('fan', 'fang');
INSERT INTO [country] ([id], [name]) VALUES ('fat', 'fantí');
INSERT INTO [country] ([id], [name]) VALUES ('phi', 'filippseysk mál (önnur)');
INSERT INTO [country] ([id], [name]) VALUES ('fil', 'filipínska');
INSERT INTO [country] ([id], [name]) VALUES ('fi', 'finnska');
INSERT INTO [country] ([id], [name]) VALUES ('fiu', 'finnskúgrísk mál (önnur)');
INSERT INTO [country] ([id], [name]) VALUES ('nl_BE', 'flæmska');
INSERT INTO [country] ([id], [name]) VALUES ('egy', 'fornegypska');
INSERT INTO [country] ([id], [name]) VALUES ('ang', 'fornenska (um 450-1100)');
INSERT INTO [country] ([id], [name]) VALUES ('fro', 'fornfranska (842 - um 1400)');
INSERT INTO [country] ([id], [name]) VALUES ('grc', 'forngríska (til 1453)');
INSERT INTO [country] ([id], [name]) VALUES ('goh', 'fornháþýska (um 750-1050)');
INSERT INTO [country] ([id], [name]) VALUES ('peo', 'fornpersneska');
INSERT INTO [country] ([id], [name]) VALUES ('pro', 'fornpróvensalska (til 1500)');
INSERT INTO [country] ([id], [name]) VALUES ('sga', 'fornírska (til 900)');
INSERT INTO [country] ([id], [name]) VALUES ('fr', 'franska');
INSERT INTO [country] ([id], [name]) VALUES ('fy', 'frísneska');
INSERT INTO [country] ([id], [name]) VALUES ('fur', 'fríúlska');
INSERT INTO [country] ([id], [name]) VALUES ('fo', 'færeyska');
INSERT INTO [country] ([id], [name]) VALUES ('fj', 'fídjeyska');
INSERT INTO [country] ([id], [name]) VALUES ('fon', 'fón');
INSERT INTO [country] ([id], [name]) VALUES ('phn', 'fönikíska');
INSERT INTO [country] ([id], [name]) VALUES ('ff', 'fúla');
INSERT INTO [country] ([id], [name]) VALUES ('gaa', 'ga');
INSERT INTO [country] ([id], [name]) VALUES ('gay', 'gajó');
INSERT INTO [country] ([id], [name]) VALUES ('gl', 'gallegska');
INSERT INTO [country] ([id], [name]) VALUES ('lg', 'ganda');
INSERT INTO [country] ([id], [name]) VALUES ('gba', 'gbaja');
INSERT INTO [country] ([id], [name]) VALUES ('ka', 'georgíska');
INSERT INTO [country] ([id], [name]) VALUES ('grb', 'gerbó');
INSERT INTO [country] ([id], [name]) VALUES ('gem', 'germönsk mál (önnur)');
INSERT INTO [country] ([id], [name]) VALUES ('gil', 'gilberska');
INSERT INTO [country] ([id], [name]) VALUES ('gon', 'gondí');
INSERT INTO [country] ([id], [name]) VALUES ('gor', 'gorontaló');
INSERT INTO [country] ([id], [name]) VALUES ('got', 'gotneska');
INSERT INTO [country] ([id], [name]) VALUES ('kl', 'grænlenska');
INSERT INTO [country] ([id], [name]) VALUES ('gn', 'gvaraní');
INSERT INTO [country] ([id], [name]) VALUES ('gwi', 'gvísín');
INSERT INTO [country] ([id], [name]) VALUES ('jrb', 'gyðingaarabíska');
INSERT INTO [country] ([id], [name]) VALUES ('jpr', 'gyðingapersneska');
INSERT INTO [country] ([id], [name]) VALUES ('gez', 'gís');
INSERT INTO [country] ([id], [name]) VALUES ('gu', 'gújaratí');
INSERT INTO [country] ([id], [name]) VALUES ('haw', 'havaíska');
INSERT INTO [country] ([id], [name]) VALUES ('hai', 'haída');
INSERT INTO [country] ([id], [name]) VALUES ('ht', 'haítíska');
INSERT INTO [country] ([id], [name]) VALUES ('he', 'hebreska');
INSERT INTO [country] ([id], [name]) VALUES ('hz', 'hereró');
INSERT INTO [country] ([id], [name]) VALUES ('hit', 'hettitíska');
INSERT INTO [country] ([id], [name]) VALUES ('hi', 'hindí');
INSERT INTO [country] ([id], [name]) VALUES ('hmn', 'hmong');
INSERT INTO [country] ([id], [name]) VALUES ('nl', 'hollenska');
INSERT INTO [country] ([id], [name]) VALUES ('be', 'hvítrússneska');
INSERT INTO [country] ([id], [name]) VALUES ('ha', 'hása');
INSERT INTO [country] ([id], [name]) VALUES ('hsb', 'hásorbneska');
INSERT INTO [country] ([id], [name]) VALUES ('hil', 'híligaínon');
INSERT INTO [country] ([id], [name]) VALUES ('him', 'hímasjalí');
INSERT INTO [country] ([id], [name]) VALUES ('ho', 'hírímótú');
INSERT INTO [country] ([id], [name]) VALUES ('hup', 'húpa');
INSERT INTO [country] ([id], [name]) VALUES ('inc', 'indversk mál (önnur)');
INSERT INTO [country] ([id], [name]) VALUES ('ine', 'indóevrópsk mál (önnur)');
INSERT INTO [country] ([id], [name]) VALUES ('id', 'indónesíska');
INSERT INTO [country] ([id], [name]) VALUES ('inh', 'ingús');
INSERT INTO [country] ([id], [name]) VALUES ('ia', 'interlingva');
INSERT INTO [country] ([id], [name]) VALUES ('ie', 'interlingve');
INSERT INTO [country] ([id], [name]) VALUES ('iu', 'inúktitút');
INSERT INTO [country] ([id], [name]) VALUES ('sah', 'jakút');
INSERT INTO [country] ([id], [name]) VALUES ('ja', 'japanska');
INSERT INTO [country] ([id], [name]) VALUES ('yap', 'japíska');
INSERT INTO [country] ([id], [name]) VALUES ('jv', 'javanska');
INSERT INTO [country] ([id], [name]) VALUES ('yao', 'jaó');
INSERT INTO [country] ([id], [name]) VALUES ('yi', 'jiddíska');
INSERT INTO [country] ([id], [name]) VALUES ('kaj', 'jju');
INSERT INTO [country] ([id], [name]) VALUES ('yo', 'jórúba');
INSERT INTO [country] ([id], [name]) VALUES ('ypk', 'júpísk mál');
INSERT INTO [country] ([id], [name]) VALUES ('kbd', 'kabardíska');
INSERT INTO [country] ([id], [name]) VALUES ('kab', 'kabíle');
INSERT INTO [country] ([id], [name]) VALUES ('cad', 'kaddó');
INSERT INTO [country] ([id], [name]) VALUES ('xal', 'kalmúkska');
INSERT INTO [country] ([id], [name]) VALUES ('kam', 'kamba');
INSERT INTO [country] ([id], [name]) VALUES ('ch', 'kamorró');
INSERT INTO [country] ([id], [name]) VALUES ('cmc', 'kamísk mál');
INSERT INTO [country] ([id], [name]) VALUES ('en_CA', 'kanadísk enska');
INSERT INTO [country] ([id], [name]) VALUES ('fr_CA', 'kanadísk franska');
INSERT INTO [country] ([id], [name]) VALUES ('kn', 'kannada');
INSERT INTO [country] ([id], [name]) VALUES ('kr', 'kanúrí');
INSERT INTO [country] ([id], [name]) VALUES ('kaa', 'karakalpak');
INSERT INTO [country] ([id], [name]) VALUES ('krc', 'karasaíbalkar');
INSERT INTO [country] ([id], [name]) VALUES ('kar', 'karen');
INSERT INTO [country] ([id], [name]) VALUES ('krl', 'karélska');
INSERT INTO [country] ([id], [name]) VALUES ('car', 'karíbamál');
INSERT INTO [country] ([id], [name]) VALUES ('kk', 'kasakska');
INSERT INTO [country] ([id], [name]) VALUES ('ks', 'kasmírska');
INSERT INTO [country] ([id], [name]) VALUES ('kha', 'kasí');
INSERT INTO [country] ([id], [name]) VALUES ('kac', 'kasín');
INSERT INTO [country] ([id], [name]) VALUES ('csb', 'kasúbíska');
INSERT INTO [country] ([id], [name]) VALUES ('ca', 'katalónska');
INSERT INTO [country] ([id], [name]) VALUES ('kaw', 'kaví');
INSERT INTO [country] ([id], [name]) VALUES ('ceb', 'kebúanó');
INSERT INTO [country] ([id], [name]) VALUES ('cel', 'keltnesk (önnur)');
INSERT INTO [country] ([id], [name]) VALUES ('kmb', 'kimbúndú');
INSERT INTO [country] ([id], [name]) VALUES ('ky', 'kirgiska');
INSERT INTO [country] ([id], [name]) VALUES ('cu', 'kirkjuslavneska');
INSERT INTO [country] ([id], [name]) VALUES ('nwc', 'klassísk nevaríska');
INSERT INTO [country] ([id], [name]) VALUES ('syc', 'klassísk sýrlenska');
INSERT INTO [country] ([id], [name]) VALUES ('tlh', 'klingónska');
INSERT INTO [country] ([id], [name]) VALUES ('km', 'kmer');
INSERT INTO [country] ([id], [name]) VALUES ('kv', 'komíska');
INSERT INTO [country] ([id], [name]) VALUES ('kg', 'kongó');
INSERT INTO [country] ([id], [name]) VALUES ('kok', 'konkaní');
INSERT INTO [country] ([id], [name]) VALUES ('cop', 'koptíska');
INSERT INTO [country] ([id], [name]) VALUES ('kw', 'korníska');
INSERT INTO [country] ([id], [name]) VALUES ('kfo', 'koro');
INSERT INTO [country] ([id], [name]) VALUES ('co', 'korsíska');
INSERT INTO [country] ([id], [name]) VALUES ('kos', 'kosraska');
INSERT INTO [country] ([id], [name]) VALUES ('kho', 'kotaska');
INSERT INTO [country] ([id], [name]) VALUES ('khi', 'koímál (önnur)');
INSERT INTO [country] ([id], [name]) VALUES ('kpe', 'kpelle');
INSERT INTO [country] ([id], [name]) VALUES ('crp', 'kreól- og pidginmál (önnur)');
INSERT INTO [country] ([id], [name]) VALUES ('cpe', 'kreól- og pidginmál á enskum grunni');
INSERT INTO [country] ([id], [name]) VALUES ('cpf', 'kreól- og pidginmál á frönskum grunni');
INSERT INTO [country] ([id], [name]) VALUES ('cpp', 'kreól- og pidginmál á portúgölskum grunni');
INSERT INTO [country] ([id], [name]) VALUES ('cr', 'krí');
INSERT INTO [country] ([id], [name]) VALUES ('mus', 'krík');
INSERT INTO [country] ([id], [name]) VALUES ('crh', 'krímtyrkneska');
INSERT INTO [country] ([id], [name]) VALUES ('hr', 'króatíska');
INSERT INTO [country] ([id], [name]) VALUES ('kro', 'krú');
INSERT INTO [country] ([id], [name]) VALUES ('qu', 'kvesjúa');
INSERT INTO [country] ([id], [name]) VALUES ('cau', 'kákasusmál (önnur)');
INSERT INTO [country] ([id], [name]) VALUES ('ki', 'kíkújú');
INSERT INTO [country] ([id], [name]) VALUES ('rw', 'kínjarvanda');
INSERT INTO [country] ([id], [name]) VALUES ('zh', 'kínverska');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hans', 'kínverska (einfölduð)');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hant', 'kínverska (hefðbundin)');
INSERT INTO [country] ([id], [name]) VALUES ('ko', 'kóreska');
INSERT INTO [country] ([id], [name]) VALUES ('kj', 'kúanjama');
INSERT INTO [country] ([id], [name]) VALUES ('kum', 'kúmík');
INSERT INTO [country] ([id], [name]) VALUES ('ku', 'kúrdneska');
INSERT INTO [country] ([id], [name]) VALUES ('kru', 'kúrúk');
INSERT INTO [country] ([id], [name]) VALUES ('cus', 'kúsitísk mál (önnur)');
INSERT INTO [country] ([id], [name]) VALUES ('kut', 'kútenaí');
INSERT INTO [country] ([id], [name]) VALUES ('lad', 'ladínska');
INSERT INTO [country] ([id], [name]) VALUES ('lam', 'lamba');
INSERT INTO [country] ([id], [name]) VALUES ('lah', 'landa');
INSERT INTO [country] ([id], [name]) VALUES ('es_419', 'latnesk-amerísk spænska');
INSERT INTO [country] ([id], [name]) VALUES ('la', 'latína');
INSERT INTO [country] ([id], [name]) VALUES ('lo', 'laó');
INSERT INTO [country] ([id], [name]) VALUES ('lez', 'lesgíska');
INSERT INTO [country] ([id], [name]) VALUES ('lv', 'lettneska');
INSERT INTO [country] ([id], [name]) VALUES ('li', 'limbúrgíska');
INSERT INTO [country] ([id], [name]) VALUES ('ln', 'lingala');
INSERT INTO [country] ([id], [name]) VALUES ('lt', 'litháíska');
INSERT INTO [country] ([id], [name]) VALUES ('jbo', 'lojban');
INSERT INTO [country] ([id], [name]) VALUES ('loz', 'losí');
INSERT INTO [country] ([id], [name]) VALUES ('dsb', 'lágsorbneska');
INSERT INTO [country] ([id], [name]) VALUES ('lu', 'lúbakatanga');
INSERT INTO [country] ([id], [name]) VALUES ('lua', 'lúbalúlúa');
INSERT INTO [country] ([id], [name]) VALUES ('lui', 'lúisenó');
INSERT INTO [country] ([id], [name]) VALUES ('smj', 'lúlesamíska');
INSERT INTO [country] ([id], [name]) VALUES ('lun', 'lúnda');
INSERT INTO [country] ([id], [name]) VALUES ('lus', 'lúsaí');
INSERT INTO [country] ([id], [name]) VALUES ('lb', 'lúxemborgíska');
INSERT INTO [country] ([id], [name]) VALUES ('luo', 'lúó');
INSERT INTO [country] ([id], [name]) VALUES ('mad', 'madúrska');
INSERT INTO [country] ([id], [name]) VALUES ('mag', 'magahí');
INSERT INTO [country] ([id], [name]) VALUES ('myn', 'majamál');
INSERT INTO [country] ([id], [name]) VALUES ('mak', 'makasar');
INSERT INTO [country] ([id], [name]) VALUES ('mk', 'makedónska');
INSERT INTO [country] ([id], [name]) VALUES ('mg', 'malagasíska');
INSERT INTO [country] ([id], [name]) VALUES ('ml', 'malajalam');
INSERT INTO [country] ([id], [name]) VALUES ('ms', 'malaíska');
INSERT INTO [country] ([id], [name]) VALUES ('mt', 'maltneska');
INSERT INTO [country] ([id], [name]) VALUES ('mdr', 'mandar');
INSERT INTO [country] ([id], [name]) VALUES ('man', 'mandingó');
INSERT INTO [country] ([id], [name]) VALUES ('mnc', 'mansjú');
INSERT INTO [country] ([id], [name]) VALUES ('gv', 'manx');
INSERT INTO [country] ([id], [name]) VALUES ('mni', 'manípúrí');
INSERT INTO [country] ([id], [name]) VALUES ('mno', 'manóbómál');
INSERT INTO [country] ([id], [name]) VALUES ('mr', 'maratí');
INSERT INTO [country] ([id], [name]) VALUES ('mul', 'margvísleg mál');
INSERT INTO [country] ([id], [name]) VALUES ('mh', 'marshallska');
INSERT INTO [country] ([id], [name]) VALUES ('mwr', 'marvarí');
INSERT INTO [country] ([id], [name]) VALUES ('chm', 'marí');
INSERT INTO [country] ([id], [name]) VALUES ('mas', 'masaí');
INSERT INTO [country] ([id], [name]) VALUES ('mai', 'maítílí');
INSERT INTO [country] ([id], [name]) VALUES ('mi', 'maórí');
INSERT INTO [country] ([id], [name]) VALUES ('men', 'mende');
INSERT INTO [country] ([id], [name]) VALUES ('mic', 'mikmak');
INSERT INTO [country] ([id], [name]) VALUES ('mwl', 'mirandesíska');
INSERT INTO [country] ([id], [name]) VALUES ('enm', 'miðenska (1100-1500)');
INSERT INTO [country] ([id], [name]) VALUES ('frm', 'miðfranska (um 1400-1600)');
INSERT INTO [country] ([id], [name]) VALUES ('dum', 'miðhollenska (um 1050-1350)');
INSERT INTO [country] ([id], [name]) VALUES ('gmh', 'miðháþýska (um 1050-1500');
INSERT INTO [country] ([id], [name]) VALUES ('mga', 'miðírska (900-1200)');
INSERT INTO [country] ([id], [name]) VALUES ('mdf', 'moksa');
INSERT INTO [country] ([id], [name]) VALUES ('mo', 'moldóvska');
INSERT INTO [country] ([id], [name]) VALUES ('lol', 'mongó');
INSERT INTO [country] ([id], [name]) VALUES ('mn', 'mongólska');
INSERT INTO [country] ([id], [name]) VALUES ('mkh', 'monkmermál (önnur)');
INSERT INTO [country] ([id], [name]) VALUES ('mos', 'mossí');
INSERT INTO [country] ([id], [name]) VALUES ('min', 'mínangkabá');
INSERT INTO [country] ([id], [name]) VALUES ('moh', 'móhíska');
INSERT INTO [country] ([id], [name]) VALUES ('mun', 'múndamál');
INSERT INTO [country] ([id], [name]) VALUES ('nah', 'nahúatl');
INSERT INTO [country] ([id], [name]) VALUES ('nap', 'napólíska');
INSERT INTO [country] ([id], [name]) VALUES ('nv', 'navahó');
INSERT INTO [country] ([id], [name]) VALUES ('ng', 'ndonga');
INSERT INTO [country] ([id], [name]) VALUES ('ne', 'nepalska');
INSERT INTO [country] ([id], [name]) VALUES ('new', 'nevarí');
INSERT INTO [country] ([id], [name]) VALUES ('nym', 'njamvesí');
INSERT INTO [country] ([id], [name]) VALUES ('nyn', 'njankóle');
INSERT INTO [country] ([id], [name]) VALUES ('nyo', 'njóró');
INSERT INTO [country] ([id], [name]) VALUES ('non', 'norræna');
INSERT INTO [country] ([id], [name]) VALUES ('no', 'norska');
INSERT INTO [country] ([id], [name]) VALUES ('nb', 'norskt bókmál');
INSERT INTO [country] ([id], [name]) VALUES ('frr', 'norðurfrísneska');
INSERT INTO [country] ([id], [name]) VALUES ('nd', 'norðurndebele');
INSERT INTO [country] ([id], [name]) VALUES ('se', 'norðursamíska');
INSERT INTO [country] ([id], [name]) VALUES ('nso', 'norðursótó');
INSERT INTO [country] ([id], [name]) VALUES ('nzi', 'nsíma');
INSERT INTO [country] ([id], [name]) VALUES ('na', 'nárúska');
INSERT INTO [country] ([id], [name]) VALUES ('nia', 'nías');
INSERT INTO [country] ([id], [name]) VALUES ('nic', 'nígerkordófanmál (önnur)');
INSERT INTO [country] ([id], [name]) VALUES ('ssa', 'nílósaharamál (önnur)');
INSERT INTO [country] ([id], [name]) VALUES ('niu', 'níveska');
INSERT INTO [country] ([id], [name]) VALUES ('nog', 'nógaí');
INSERT INTO [country] ([id], [name]) VALUES ('nub', 'núbísk mál');
INSERT INTO [country] ([id], [name]) VALUES ('el', 'nýgríska (1453-)');
INSERT INTO [country] ([id], [name]) VALUES ('nn', 'nýnorska');
INSERT INTO [country] ([id], [name]) VALUES ('oj', 'ojibva');
INSERT INTO [country] ([id], [name]) VALUES ('os', 'ossetíska');
INSERT INTO [country] ([id], [name]) VALUES ('pal', 'palaví');
INSERT INTO [country] ([id], [name]) VALUES ('pau', 'paláska');
INSERT INTO [country] ([id], [name]) VALUES ('pi', 'palí');
INSERT INTO [country] ([id], [name]) VALUES ('pam', 'pampanga');
INSERT INTO [country] ([id], [name]) VALUES ('pag', 'pangasínmál');
INSERT INTO [country] ([id], [name]) VALUES ('pap', 'papíamentó');
INSERT INTO [country] ([id], [name]) VALUES ('paa', 'papúsk mál (önnur)');
INSERT INTO [country] ([id], [name]) VALUES ('ps', 'pastú');
INSERT INTO [country] ([id], [name]) VALUES ('fa', 'persneska');
INSERT INTO [country] ([id], [name]) VALUES ('pon', 'ponpeiska');
INSERT INTO [country] ([id], [name]) VALUES ('pt', 'portúgalska');
INSERT INTO [country] ([id], [name]) VALUES ('pra', 'prakrítmál');
INSERT INTO [country] ([id], [name]) VALUES ('pl', 'pólska');
INSERT INTO [country] ([id], [name]) VALUES ('pa', 'púnjabí');
INSERT INTO [country] ([id], [name]) VALUES ('raj', 'rajastaní');
INSERT INTO [country] ([id], [name]) VALUES ('rap', 'rapanúí');
INSERT INTO [country] ([id], [name]) VALUES ('rar', 'rarótongska');
INSERT INTO [country] ([id], [name]) VALUES ('rm', 'retórómanska');
INSERT INTO [country] ([id], [name]) VALUES ('rom', 'romaní');
INSERT INTO [country] ([id], [name]) VALUES ('roa', 'rómönsk mál (önnur)');
INSERT INTO [country] ([id], [name]) VALUES ('root', 'rót');
INSERT INTO [country] ([id], [name]) VALUES ('ro', 'rúmenska');
INSERT INTO [country] ([id], [name]) VALUES ('rn', 'rúndí');
INSERT INTO [country] ([id], [name]) VALUES ('ru', 'rússneska');
INSERT INTO [country] ([id], [name]) VALUES ('sal', 'salísmál');
INSERT INTO [country] ([id], [name]) VALUES ('sam', 'samversk arameíska');
INSERT INTO [country] ([id], [name]) VALUES ('smi', 'samísk mál (önnur)');
INSERT INTO [country] ([id], [name]) VALUES ('sm', 'samóska');
INSERT INTO [country] ([id], [name]) VALUES ('sad', 'sandave');
INSERT INTO [country] ([id], [name]) VALUES ('znd', 'sande');
INSERT INTO [country] ([id], [name]) VALUES ('sg', 'sangó');
INSERT INTO [country] ([id], [name]) VALUES ('sa', 'sanskrít');
INSERT INTO [country] ([id], [name]) VALUES ('sat', 'santalí');
INSERT INTO [country] ([id], [name]) VALUES ('zap', 'sapótek');
INSERT INTO [country] ([id], [name]) VALUES ('sc', 'sardínska');
INSERT INTO [country] ([id], [name]) VALUES ('sas', 'sasak');
INSERT INTO [country] ([id], [name]) VALUES ('sel', 'selkúp');
INSERT INTO [country] ([id], [name]) VALUES ('sem', 'semísk mál (önnur)');
INSERT INTO [country] ([id], [name]) VALUES ('zen', 'senaga');
INSERT INTO [country] ([id], [name]) VALUES ('sr', 'serbneska');
INSERT INTO [country] ([id], [name]) VALUES ('sh', 'serbókróatíska');
INSERT INTO [country] ([id], [name]) VALUES ('srr', 'serer');
INSERT INTO [country] ([id], [name]) VALUES ('sn', 'shóna');
INSERT INTO [country] ([id], [name]) VALUES ('scn', 'sikileyska');
INSERT INTO [country] ([id], [name]) VALUES ('bla', 'siksika');
INSERT INTO [country] ([id], [name]) VALUES ('sd', 'sindí');
INSERT INTO [country] ([id], [name]) VALUES ('si', 'singalesíska');
INSERT INTO [country] ([id], [name]) VALUES ('chg', 'sjagataí');
INSERT INTO [country] ([id], [name]) VALUES ('shn', 'sjan');
INSERT INTO [country] ([id], [name]) VALUES ('chr', 'sjerókí');
INSERT INTO [country] ([id], [name]) VALUES ('chy', 'sjeyen');
INSERT INTO [country] ([id], [name]) VALUES ('cho', 'sjoktá');
INSERT INTO [country] ([id], [name]) VALUES ('chk', 'sjúkíska');
INSERT INTO [country] ([id], [name]) VALUES ('cv', 'sjúvas');
INSERT INTO [country] ([id], [name]) VALUES ('sms', 'skoltesamíska');
INSERT INTO [country] ([id], [name]) VALUES ('gd', 'skosk gelíska');
INSERT INTO [country] ([id], [name]) VALUES ('sco', 'skoska');
INSERT INTO [country] ([id], [name]) VALUES ('sla', 'slavnesk mál (önnur)');
INSERT INTO [country] ([id], [name]) VALUES ('den', 'slavneska');
INSERT INTO [country] ([id], [name]) VALUES ('sk', 'slóvakíska');
INSERT INTO [country] ([id], [name]) VALUES ('sl', 'slóvenska');
INSERT INTO [country] ([id], [name]) VALUES ('sog', 'sogdíen');
INSERT INTO [country] ([id], [name]) VALUES ('son', 'songhaí');
INSERT INTO [country] ([id], [name]) VALUES ('wen', 'sorbnesk mál');
INSERT INTO [country] ([id], [name]) VALUES ('es', 'spænska');
INSERT INTO [country] ([id], [name]) VALUES ('srn', 'sranan tongo');
INSERT INTO [country] ([id], [name]) VALUES ('alt', 'suðuraltaíska');
INSERT INTO [country] ([id], [name]) VALUES ('nr', 'suðurndebele');
INSERT INTO [country] ([id], [name]) VALUES ('sma', 'suðursamíska');
INSERT INTO [country] ([id], [name]) VALUES ('st', 'suðursótó');
INSERT INTO [country] ([id], [name]) VALUES ('sw', 'svahílí');
INSERT INTO [country] ([id], [name]) VALUES ('ss', 'svatí');
INSERT INTO [country] ([id], [name]) VALUES ('fr_CH', 'svissnesk franska');
INSERT INTO [country] ([id], [name]) VALUES ('de_CH', 'svissnesk háþýska');
INSERT INTO [country] ([id], [name]) VALUES ('gsw', 'svissnesk þýska');
INSERT INTO [country] ([id], [name]) VALUES ('sv', 'sænska');
INSERT INTO [country] ([id], [name]) VALUES ('chb', 'síbsja');
INSERT INTO [country] ([id], [name]) VALUES ('sid', 'sídamó');
INSERT INTO [country] ([id], [name]) VALUES ('sit', 'sínótíbesk mál');
INSERT INTO [country] ([id], [name]) VALUES ('chn', 'sínúk');
INSERT INTO [country] ([id], [name]) VALUES ('chp', 'sípevíska');
INSERT INTO [country] ([id], [name]) VALUES ('ii', 'sísúanjí');
INSERT INTO [country] ([id], [name]) VALUES ('sio', 'síúmál');
INSERT INTO [country] ([id], [name]) VALUES ('so', 'sómalska');
INSERT INTO [country] ([id], [name]) VALUES ('snk', 'sóninke');
INSERT INTO [country] ([id], [name]) VALUES ('xh', 'sósa');
INSERT INTO [country] ([id], [name]) VALUES ('za', 'súang');
INSERT INTO [country] ([id], [name]) VALUES ('suk', 'súkúma');
INSERT INTO [country] ([id], [name]) VALUES ('zu', 'súlú');
INSERT INTO [country] ([id], [name]) VALUES ('sux', 'súmerska');
INSERT INTO [country] ([id], [name]) VALUES ('su', 'súndanska');
INSERT INTO [country] ([id], [name]) VALUES ('zun', 'súní');
INSERT INTO [country] ([id], [name]) VALUES ('sus', 'súsú');
INSERT INTO [country] ([id], [name]) VALUES ('syr', 'sýrlenska');
INSERT INTO [country] ([id], [name]) VALUES ('tg', 'tadsjikska');
INSERT INTO [country] ([id], [name]) VALUES ('tl', 'tagalog');
INSERT INTO [country] ([id], [name]) VALUES ('ty', 'tahítíska');
INSERT INTO [country] ([id], [name]) VALUES ('tmh', 'tamasjek');
INSERT INTO [country] ([id], [name]) VALUES ('ta', 'tamílska');
INSERT INTO [country] ([id], [name]) VALUES ('tt', 'tatarska');
INSERT INTO [country] ([id], [name]) VALUES ('th', 'taílenska');
INSERT INTO [country] ([id], [name]) VALUES ('tai', 'taímál (önnur)');
INSERT INTO [country] ([id], [name]) VALUES ('te', 'telúgú');
INSERT INTO [country] ([id], [name]) VALUES ('ter', 'terenó');
INSERT INTO [country] ([id], [name]) VALUES ('tet', 'tetúm');
INSERT INTO [country] ([id], [name]) VALUES ('tli', 'tlingit');
INSERT INTO [country] ([id], [name]) VALUES ('tpi', 'tokpisin');
INSERT INTO [country] ([id], [name]) VALUES ('tsi', 'tsimsíska');
INSERT INTO [country] ([id], [name]) VALUES ('ce', 'tsjetsjenska');
INSERT INTO [country] ([id], [name]) VALUES ('ts', 'tsonga');
INSERT INTO [country] ([id], [name]) VALUES ('tn', 'tsúana');
INSERT INTO [country] ([id], [name]) VALUES ('tw', 'tví');
INSERT INTO [country] ([id], [name]) VALUES ('kcg', 'tyap');
INSERT INTO [country] ([id], [name]) VALUES ('tr', 'tyrkneska');
INSERT INTO [country] ([id], [name]) VALUES ('ota', 'tyrkneska, ottóman (1500-1928)');
INSERT INTO [country] ([id], [name]) VALUES ('sgn', 'táknmál');
INSERT INTO [country] ([id], [name]) VALUES ('cs', 'tékkneska');
INSERT INTO [country] ([id], [name]) VALUES ('bo', 'tíbeska');
INSERT INTO [country] ([id], [name]) VALUES ('tig', 'tígre');
INSERT INTO [country] ([id], [name]) VALUES ('ti', 'tígrinja');
INSERT INTO [country] ([id], [name]) VALUES ('tem', 'tímne');
INSERT INTO [country] ([id], [name]) VALUES ('tiv', 'tív');
INSERT INTO [country] ([id], [name]) VALUES ('tkl', 'tókeláska');
INSERT INTO [country] ([id], [name]) VALUES ('tum', 'túmbúka');
INSERT INTO [country] ([id], [name]) VALUES ('tup', 'túpímál');
INSERT INTO [country] ([id], [name]) VALUES ('tk', 'túrkmenska');
INSERT INTO [country] ([id], [name]) VALUES ('tvl', 'túvalúska');
INSERT INTO [country] ([id], [name]) VALUES ('tyv', 'túvínska');
INSERT INTO [country] ([id], [name]) VALUES ('hu', 'ungverska');
INSERT INTO [country] ([id], [name]) VALUES ('wak', 'vakasmál');
INSERT INTO [country] ([id], [name]) VALUES ('wal', 'valamó');
INSERT INTO [country] ([id], [name]) VALUES ('wa', 'vallónska');
INSERT INTO [country] ([id], [name]) VALUES ('war', 'varaí');
INSERT INTO [country] ([id], [name]) VALUES ('was', 'vasjó');
INSERT INTO [country] ([id], [name]) VALUES ('vai', 'vaí');
INSERT INTO [country] ([id], [name]) VALUES ('cy', 'velska');
INSERT INTO [country] ([id], [name]) VALUES ('ve', 'venda');
INSERT INTO [country] ([id], [name]) VALUES ('vo', 'volapyk');
INSERT INTO [country] ([id], [name]) VALUES ('wo', 'volof');
INSERT INTO [country] ([id], [name]) VALUES ('vot', 'votíska');
INSERT INTO [country] ([id], [name]) VALUES ('vi', 'víetnamska');
INSERT INTO [country] ([id], [name]) VALUES ('zza', 'zázáíska');
INSERT INTO [country] ([id], [name]) VALUES ('map', 'ástrónesíska');
INSERT INTO [country] ([id], [name]) VALUES ('en_AU', 'áströlsk enska');
INSERT INTO [country] ([id], [name]) VALUES ('aus', 'áströlsk mál');
INSERT INTO [country] ([id], [name]) VALUES ('iba', 'íban');
INSERT INTO [country] ([id], [name]) VALUES ('pt_PT', 'íberísk portúgalska');
INSERT INTO [country] ([id], [name]) VALUES ('es_ES', 'íberísk spænska');
INSERT INTO [country] ([id], [name]) VALUES ('io', 'ídó');
INSERT INTO [country] ([id], [name]) VALUES ('ig', 'ígbó');
INSERT INTO [country] ([id], [name]) VALUES ('ijo', 'íjó');
INSERT INTO [country] ([id], [name]) VALUES ('ilo', 'ílokó');
INSERT INTO [country] ([id], [name]) VALUES ('ik', 'ínúpíak');
INSERT INTO [country] ([id], [name]) VALUES ('ira', 'íranska');
INSERT INTO [country] ([id], [name]) VALUES ('ga', 'írska');
INSERT INTO [country] ([id], [name]) VALUES ('iro', 'írókesk mál');
INSERT INTO [country] ([id], [name]) VALUES ('is', 'íslenska');
INSERT INTO [country] ([id], [name]) VALUES ('it', 'ítalska');
INSERT INTO [country] ([id], [name]) VALUES ('or', 'óría');
INSERT INTO [country] ([id], [name]) VALUES ('om', 'órómó');
INSERT INTO [country] ([id], [name]) VALUES ('osa', 'ósage');
INSERT INTO [country] ([id], [name]) VALUES ('oto', 'ótommál');
INSERT INTO [country] ([id], [name]) VALUES ('und', 'óþekkt eða ógilt tungumál');
INSERT INTO [country] ([id], [name]) VALUES ('udm', 'údmúrt');
INSERT INTO [country] ([id], [name]) VALUES ('uga', 'úgarítíska');
INSERT INTO [country] ([id], [name]) VALUES ('uk', 'úkraínska');
INSERT INTO [country] ([id], [name]) VALUES ('umb', 'úmbúndú');
INSERT INTO [country] ([id], [name]) VALUES ('ur', 'úrdú');
INSERT INTO [country] ([id], [name]) VALUES ('uz', 'úsbekska');
INSERT INTO [country] ([id], [name]) VALUES ('ug', 'úígúr');
INSERT INTO [country] ([id], [name]) VALUES ('mis', 'ýmis mál');
INSERT INTO [country] ([id], [name]) VALUES ('de', 'þýska');
