CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('av', 'Άβαρικ');
INSERT INTO [country] ([id], [name]) VALUES ('ae', 'Αβεστάν');
INSERT INTO [country] ([id], [name]) VALUES ('en', 'Αγγλικά');
INSERT INTO [country] ([id], [name]) VALUES ('en_AU', 'Αγγλικά Αυστραλίας');
INSERT INTO [country] ([id], [name]) VALUES ('en_US', 'Αγγλικά Η.Π.Α.');
INSERT INTO [country] ([id], [name]) VALUES ('en_GB', 'Αγγλικά Ηνωμένου Βασιλείου');
INSERT INTO [country] ([id], [name]) VALUES ('en_CA', 'Αγγλικά Καναδά');
INSERT INTO [country] ([id], [name]) VALUES ('und', 'Άγνωστη ή ακατάλληλη γλώσσα');
INSERT INTO [country] ([id], [name]) VALUES ('awa', 'Αγουαντί');
INSERT INTO [country] ([id], [name]) VALUES ('az', 'Αζερμπαϊτζανικά');
INSERT INTO [country] ([id], [name]) VALUES ('ay', 'Αϊμάρα');
INSERT INTO [country] ([id], [name]) VALUES ('ain', 'Αϊνού');
INSERT INTO [country] ([id], [name]) VALUES ('ht', 'Αϊτιανά');
INSERT INTO [country] ([id], [name]) VALUES ('ak', 'Ακάν');
INSERT INTO [country] ([id], [name]) VALUES ('akk', 'Ακάντιαν');
INSERT INTO [country] ([id], [name]) VALUES ('ach', 'Ακολί');
INSERT INTO [country] ([id], [name]) VALUES ('sq', 'Αλβανικά');
INSERT INTO [country] ([id], [name]) VALUES ('ale', 'Αλούτ');
INSERT INTO [country] ([id], [name]) VALUES ('tut', 'Αλταϊκή γλώσσα');
INSERT INTO [country] ([id], [name]) VALUES ('am', 'Αμαρικά');
INSERT INTO [country] ([id], [name]) VALUES ('ab', 'Αμπχαζικά');
INSERT INTO [country] ([id], [name]) VALUES ('frs', 'Ανατολικά Φριζιανά');
INSERT INTO [country] ([id], [name]) VALUES ('anp', 'Ανγκικά');
INSERT INTO [country] ([id], [name]) VALUES ('ada', 'Αντάνγκμε');
INSERT INTO [country] ([id], [name]) VALUES ('ady', 'Αντιγκέα');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hans', 'Απλοποιημένα Κινεζικά');
INSERT INTO [country] ([id], [name]) VALUES ('ar', 'Αραβικά');
INSERT INTO [country] ([id], [name]) VALUES ('an', 'Αραγκονικά');
INSERT INTO [country] ([id], [name]) VALUES ('arw', 'Αραγουάκ');
INSERT INTO [country] ([id], [name]) VALUES ('arc', 'Αραμαϊκά');
INSERT INTO [country] ([id], [name]) VALUES ('arp', 'Αράπαχο');
INSERT INTO [country] ([id], [name]) VALUES ('hy', 'Αρμενικά');
INSERT INTO [country] ([id], [name]) VALUES ('rup', 'Αρομανικά');
INSERT INTO [country] ([id], [name]) VALUES ('arn', 'Αρουκάνιαν');
INSERT INTO [country] ([id], [name]) VALUES ('egy', 'Αρχαία Αιγυπτιακά');
INSERT INTO [country] ([id], [name]) VALUES ('grc', 'Αρχαία Ελληνικά');
INSERT INTO [country] ([id], [name]) VALUES ('peo', 'Αρχαία Περσικά');
INSERT INTO [country] ([id], [name]) VALUES ('as', 'Ασαμεζικά');
INSERT INTO [country] ([id], [name]) VALUES ('asa', 'Άσου');
INSERT INTO [country] ([id], [name]) VALUES ('ast', 'Αστουριανά');
INSERT INTO [country] ([id], [name]) VALUES ('cch', 'Ατσάμ');
INSERT INTO [country] ([id], [name]) VALUES ('aus', 'Αυστραλιανή γλώσσα');
INSERT INTO [country] ([id], [name]) VALUES ('aa', 'Αφάρ');
INSERT INTO [country] ([id], [name]) VALUES ('af', 'Αφρικάανς');
INSERT INTO [country] ([id], [name]) VALUES ('afh', 'Αφριχίλι');
INSERT INTO [country] ([id], [name]) VALUES ('afa', 'Αφροασιατική γλώσσα');
INSERT INTO [country] ([id], [name]) VALUES ('ace', 'Αχινίζ');
INSERT INTO [country] ([id], [name]) VALUES ('vai', 'Βάι');
INSERT INTO [country] ([id], [name]) VALUES ('wae', 'Βάλσερ');
INSERT INTO [country] ([id], [name]) VALUES ('bat', 'Βαλτική γλώσσα');
INSERT INTO [country] ([id], [name]) VALUES ('eu', 'Βασκικά');
INSERT INTO [country] ([id], [name]) VALUES ('ve', 'Βένδα');
INSERT INTO [country] ([id], [name]) VALUES ('vi', 'Βιετναμεζικά');
INSERT INTO [country] ([id], [name]) VALUES ('my', 'Βιρμανικά');
INSERT INTO [country] ([id], [name]) VALUES ('vo', 'Βόλαπικ');
INSERT INTO [country] ([id], [name]) VALUES ('se', 'Βόρεια Σάμι');
INSERT INTO [country] ([id], [name]) VALUES ('nso', 'Βόρεια Σόθο');
INSERT INTO [country] ([id], [name]) VALUES ('frr', 'Βόρεια Φριζιανά');
INSERT INTO [country] ([id], [name]) VALUES ('bs', 'Βοσνιακά');
INSERT INTO [country] ([id], [name]) VALUES ('vot', 'Βότικ');
INSERT INTO [country] ([id], [name]) VALUES ('bg', 'Βουλγαρικά');
INSERT INTO [country] ([id], [name]) VALUES ('br', 'Βρετονικά');
INSERT INTO [country] ([id], [name]) VALUES ('gl', 'Γαλικιανά');
INSERT INTO [country] ([id], [name]) VALUES ('fr', 'Γαλλικά');
INSERT INTO [country] ([id], [name]) VALUES ('fr_CH', 'Γαλλικά Ελβετίας');
INSERT INTO [country] ([id], [name]) VALUES ('fr_CA', 'Γαλλικά Καναδά');
INSERT INTO [country] ([id], [name]) VALUES ('de', 'Γερμανικά');
INSERT INTO [country] ([id], [name]) VALUES ('de_AT', 'Γερμανικά Αυστρίας');
INSERT INTO [country] ([id], [name]) VALUES ('de_CH', 'Γερμανικά Ελβετίας');
INSERT INTO [country] ([id], [name]) VALUES ('gem', 'Γερμανική γλώσσα');
INSERT INTO [country] ([id], [name]) VALUES ('ka', 'Γεωργιανά');
INSERT INTO [country] ([id], [name]) VALUES ('ee', 'Γι');
INSERT INTO [country] ([id], [name]) VALUES ('sah', 'Γιακούτ');
INSERT INTO [country] ([id], [name]) VALUES ('yao', 'Γιάο');
INSERT INTO [country] ([id], [name]) VALUES ('yap', 'Γιαπίζ');
INSERT INTO [country] ([id], [name]) VALUES ('yi', 'Γίντις');
INSERT INTO [country] ([id], [name]) VALUES ('yo', 'Γιορούμπα');
INSERT INTO [country] ([id], [name]) VALUES ('gaa', 'Γκα');
INSERT INTO [country] ([id], [name]) VALUES ('gay', 'Γκάγιο');
INSERT INTO [country] ([id], [name]) VALUES ('lg', 'Γκάντα');
INSERT INTO [country] ([id], [name]) VALUES ('gez', 'Γκιζ');
INSERT INTO [country] ([id], [name]) VALUES ('gil', 'Γκιλμπερτίζ');
INSERT INTO [country] ([id], [name]) VALUES ('gba', 'Γκμπάγια');
INSERT INTO [country] ([id], [name]) VALUES ('gon', 'Γκόντι');
INSERT INTO [country] ([id], [name]) VALUES ('gor', 'Γκοροντάλο');
INSERT INTO [country] ([id], [name]) VALUES ('gn', 'Γκουαρανί');
INSERT INTO [country] ([id], [name]) VALUES ('gu', 'Γκουγιαράτι');
INSERT INTO [country] ([id], [name]) VALUES ('gwi', 'Γκουίτσιν');
INSERT INTO [country] ([id], [name]) VALUES ('grb', 'Γκρίμπο');
INSERT INTO [country] ([id], [name]) VALUES ('ath', 'Γλώσσα Αθαπάσκαν');
INSERT INTO [country] ([id], [name]) VALUES ('alg', 'Γλώσσα Αλγκονκιάν');
INSERT INTO [country] ([id], [name]) VALUES ('hsb', 'Γλώσσα Άνω Λουσατίας');
INSERT INTO [country] ([id], [name]) VALUES ('apa', 'Γλώσσα Απάτσι');
INSERT INTO [country] ([id], [name]) VALUES ('ypk', 'Γλώσσα Γιούπικ');
INSERT INTO [country] ([id], [name]) VALUES ('wak', 'Γλώσσα Γουακασάν');
INSERT INTO [country] ([id], [name]) VALUES ('iro', 'Γλώσσα Ιροκόιαν');
INSERT INTO [country] ([id], [name]) VALUES ('dsb', 'Γλώσσα Κάτω Λουσατίας');
INSERT INTO [country] ([id], [name]) VALUES ('khi', 'Γλώσσα Κοϊσάν');
INSERT INTO [country] ([id], [name]) VALUES ('cus', 'Γλώσσα Κουσιτίκ');
INSERT INTO [country] ([id], [name]) VALUES ('myn', 'Γλώσσα Μάγιαν');
INSERT INTO [country] ([id], [name]) VALUES ('mno', 'Γλώσσα Μανόμπο');
INSERT INTO [country] ([id], [name]) VALUES ('mkh', 'Γλώσσα Μον-Χμερ');
INSERT INTO [country] ([id], [name]) VALUES ('mun', 'Γλώσσα Μούντα');
INSERT INTO [country] ([id], [name]) VALUES ('bai', 'Γλώσσα Μπαμιλέκ');
INSERT INTO [country] ([id], [name]) VALUES ('nic', 'Γλώσσα Νίγηρα-Κορδοφάνιαν');
INSERT INTO [country] ([id], [name]) VALUES ('nub', 'Γλώσσα Νούμπιαν');
INSERT INTO [country] ([id], [name]) VALUES ('dra', 'Γλώσσα Ντραβίδιαν');
INSERT INTO [country] ([id], [name]) VALUES ('pra', 'Γλώσσα Πράκριτ');
INSERT INTO [country] ([id], [name]) VALUES ('sal', 'Γλώσσα Σαλισάν');
INSERT INTO [country] ([id], [name]) VALUES ('smi', 'Γλώσσα Σάμι');
INSERT INTO [country] ([id], [name]) VALUES ('sio', 'Γλώσσα Σιουάν');
INSERT INTO [country] ([id], [name]) VALUES ('kea', 'Γλώσσα του Πράσινου Ακρωτηρίου');
INSERT INTO [country] ([id], [name]) VALUES ('tup', 'Γλώσσα Τούπι');
INSERT INTO [country] ([id], [name]) VALUES ('got', 'Γοτθικά');
INSERT INTO [country] ([id], [name]) VALUES ('wal', 'Γουάλαμο');
INSERT INTO [country] ([id], [name]) VALUES ('wa', 'Γουαλούν');
INSERT INTO [country] ([id], [name]) VALUES ('war', 'Γουάρει');
INSERT INTO [country] ([id], [name]) VALUES ('was', 'Γουασό');
INSERT INTO [country] ([id], [name]) VALUES ('wo', 'Γουόλοφ');
INSERT INTO [country] ([id], [name]) VALUES ('da', 'Δανικά');
INSERT INTO [country] ([id], [name]) VALUES ('wen', 'Διάλεκτος Άνω Λουσατίας');
INSERT INTO [country] ([id], [name]) VALUES ('mis', 'Διάφορες γλώσσες');
INSERT INTO [country] ([id], [name]) VALUES ('fy', 'Δυτικά Φριζιανά');
INSERT INTO [country] ([id], [name]) VALUES ('he', 'Εβραϊκά');
INSERT INTO [country] ([id], [name]) VALUES ('ewo', 'Εγουόντο');
INSERT INTO [country] ([id], [name]) VALUES ('eka', 'Εκατζούκ');
INSERT INTO [country] ([id], [name]) VALUES ('cu', 'Εκκλησιαστικά Σλαβικά');
INSERT INTO [country] ([id], [name]) VALUES ('elx', 'Ελαμάιτ');
INSERT INTO [country] ([id], [name]) VALUES ('gsw', 'Ελβετικά Γερμανικά');
INSERT INTO [country] ([id], [name]) VALUES ('el', 'Ελληνικά');
INSERT INTO [country] ([id], [name]) VALUES ('ebu', 'Έμπου');
INSERT INTO [country] ([id], [name]) VALUES ('myv', 'Έρζυα');
INSERT INTO [country] ([id], [name]) VALUES ('et', 'Εσθονικά');
INSERT INTO [country] ([id], [name]) VALUES ('eo', 'Εσπεράντο');
INSERT INTO [country] ([id], [name]) VALUES ('efi', 'Εφίκ');
INSERT INTO [country] ([id], [name]) VALUES ('zza', 'Ζάζα');
INSERT INTO [country] ([id], [name]) VALUES ('znd', 'Ζάντε');
INSERT INTO [country] ([id], [name]) VALUES ('zap', 'Ζάποτεκ');
INSERT INTO [country] ([id], [name]) VALUES ('zen', 'Ζενάγκα');
INSERT INTO [country] ([id], [name]) VALUES ('xh', 'Ζόσα');
INSERT INTO [country] ([id], [name]) VALUES ('za', 'Ζουάνγκ');
INSERT INTO [country] ([id], [name]) VALUES ('zu', 'Ζουλού');
INSERT INTO [country] ([id], [name]) VALUES ('zun', 'Ζούνι');
INSERT INTO [country] ([id], [name]) VALUES ('bo', 'Θιβετιανά');
INSERT INTO [country] ([id], [name]) VALUES ('jv', 'Ιαβανεζικά');
INSERT INTO [country] ([id], [name]) VALUES ('ja', 'Ιαπωνικά');
INSERT INTO [country] ([id], [name]) VALUES ('ig', 'Ίγκμπο');
INSERT INTO [country] ([id], [name]) VALUES ('chn', 'Ιδιωματικά Σινούκ');
INSERT INTO [country] ([id], [name]) VALUES ('ijo', 'Ιζό');
INSERT INTO [country] ([id], [name]) VALUES ('ilo', 'Ιλόκο');
INSERT INTO [country] ([id], [name]) VALUES ('iba', 'Ιμπάν');
INSERT INTO [country] ([id], [name]) VALUES ('smn', 'Ινάρι Σάμι');
INSERT INTO [country] ([id], [name]) VALUES ('inh', 'Ινγκούς');
INSERT INTO [country] ([id], [name]) VALUES ('nai', 'Ινδιανική γλώσσα Βόρειας Αμερικής');
INSERT INTO [country] ([id], [name]) VALUES ('cai', 'Ινδιανική γλώσσα Κεντρικής Αμερικής');
INSERT INTO [country] ([id], [name]) VALUES ('sai', 'Ινδιανική γλώσσα Νότιας Αμερικής');
INSERT INTO [country] ([id], [name]) VALUES ('inc', 'Ινδική γλώσσα');
INSERT INTO [country] ([id], [name]) VALUES ('ine', 'Ινδοευρωπαϊκή γλώσσα');
INSERT INTO [country] ([id], [name]) VALUES ('id', 'Ινδονησιακά');
INSERT INTO [country] ([id], [name]) VALUES ('iu', 'Ινουκτιτούτ');
INSERT INTO [country] ([id], [name]) VALUES ('ik', 'Ινουπιάκ');
INSERT INTO [country] ([id], [name]) VALUES ('ia', 'Ιντερλίνγκουα');
INSERT INTO [country] ([id], [name]) VALUES ('ie', 'Ιντερλίνγκουε');
INSERT INTO [country] ([id], [name]) VALUES ('io', 'Ίντο');
INSERT INTO [country] ([id], [name]) VALUES ('jrb', 'Ιουδαϊκά-Αραβικά');
INSERT INTO [country] ([id], [name]) VALUES ('jpr', 'Ιουδαϊκά-Περσικά');
INSERT INTO [country] ([id], [name]) VALUES ('ira', 'Ιρανική γλώσσα');
INSERT INTO [country] ([id], [name]) VALUES ('ga', 'Ιρλανδικά');
INSERT INTO [country] ([id], [name]) VALUES ('is', 'Ισλανδικά');
INSERT INTO [country] ([id], [name]) VALUES ('es', 'Ισπανικά');
INSERT INTO [country] ([id], [name]) VALUES ('es_ES', 'Ισπανικά Ιβηρικής');
INSERT INTO [country] ([id], [name]) VALUES ('es_419', 'Ισπανικά Λατινικής Αμερικής');
INSERT INTO [country] ([id], [name]) VALUES ('it', 'Ιταλικά');
INSERT INTO [country] ([id], [name]) VALUES ('kk', 'Καζακικά');
INSERT INTO [country] ([id], [name]) VALUES ('kl', 'Καλααλισούτ');
INSERT INTO [country] ([id], [name]) VALUES ('xal', 'Καλμίκ');
INSERT INTO [country] ([id], [name]) VALUES ('ch', 'Καμόρρο');
INSERT INTO [country] ([id], [name]) VALUES ('kam', 'Κάμπα');
INSERT INTO [country] ([id], [name]) VALUES ('kbd', 'Καμπαρντιανά');
INSERT INTO [country] ([id], [name]) VALUES ('kab', 'Καμπίλε');
INSERT INTO [country] ([id], [name]) VALUES ('km', 'Καμποτζιανά');
INSERT INTO [country] ([id], [name]) VALUES ('kn', 'Κανάντα');
INSERT INTO [country] ([id], [name]) VALUES ('kr', 'Κανούρι');
INSERT INTO [country] ([id], [name]) VALUES ('cad', 'Κάντο');
INSERT INTO [country] ([id], [name]) VALUES ('yue', 'Καντονέζικα');
INSERT INTO [country] ([id], [name]) VALUES ('kaw', 'Κάουι');
INSERT INTO [country] ([id], [name]) VALUES ('kaa', 'Κάρα-Καλπάκ');
INSERT INTO [country] ([id], [name]) VALUES ('krc', 'Καρατσάι-Μπαλκάρ');
INSERT INTO [country] ([id], [name]) VALUES ('krl', 'Καρελιακά');
INSERT INTO [country] ([id], [name]) VALUES ('kar', 'Καρέν');
INSERT INTO [country] ([id], [name]) VALUES ('car', 'Καρίμπ');
INSERT INTO [country] ([id], [name]) VALUES ('kha', 'Κάσι');
INSERT INTO [country] ([id], [name]) VALUES ('ks', 'Κασμίρι');
INSERT INTO [country] ([id], [name]) VALUES ('csb', 'Κασούμπιαν');
INSERT INTO [country] ([id], [name]) VALUES ('ca', 'Καταλανικά');
INSERT INTO [country] ([id], [name]) VALUES ('kac', 'Κατσίν');
INSERT INTO [country] ([id], [name]) VALUES ('nds', 'Κάτω Γερμανικά');
INSERT INTO [country] ([id], [name]) VALUES ('cau', 'Καυκάσια γλώσσα');
INSERT INTO [country] ([id], [name]) VALUES ('cel', 'Κελτική γλώσσα');
INSERT INTO [country] ([id], [name]) VALUES ('ceb', 'Κεμπουάνο');
INSERT INTO [country] ([id], [name]) VALUES ('qu', 'Κετσούα');
INSERT INTO [country] ([id], [name]) VALUES ('ki', 'Κικούγιου');
INSERT INTO [country] ([id], [name]) VALUES ('kmb', 'Κιμπούντου');
INSERT INTO [country] ([id], [name]) VALUES ('zh', 'Κινεζικά');
INSERT INTO [country] ([id], [name]) VALUES ('rw', 'Κινιαρβάντα');
INSERT INTO [country] ([id], [name]) VALUES ('nwc', 'Κλασικά Νεουάρι');
INSERT INTO [country] ([id], [name]) VALUES ('syc', 'Κλασικά Συριακά');
INSERT INTO [country] ([id], [name]) VALUES ('tlh', 'Κλίνγκον');
INSERT INTO [country] ([id], [name]) VALUES ('kv', 'Κόμι');
INSERT INTO [country] ([id], [name]) VALUES ('swb', 'Κομόρρια');
INSERT INTO [country] ([id], [name]) VALUES ('kg', 'Κονγκό');
INSERT INTO [country] ([id], [name]) VALUES ('kok', 'Κονκάνι');
INSERT INTO [country] ([id], [name]) VALUES ('cop', 'Κοπτικά');
INSERT INTO [country] ([id], [name]) VALUES ('ko', 'Κορεατικά');
INSERT INTO [country] ([id], [name]) VALUES ('kw', 'Κόρνις');
INSERT INTO [country] ([id], [name]) VALUES ('kfo', 'Κόρο');
INSERT INTO [country] ([id], [name]) VALUES ('co', 'Κορσικανικά');
INSERT INTO [country] ([id], [name]) VALUES ('kos', 'Κοσραενικά');
INSERT INTO [country] ([id], [name]) VALUES ('kho', 'Κοτανικά');
INSERT INTO [country] ([id], [name]) VALUES ('kj', 'Κουανιγιάμα');
INSERT INTO [country] ([id], [name]) VALUES ('kum', 'Κουμγιούκ');
INSERT INTO [country] ([id], [name]) VALUES ('ku', 'Κουρδικά');
INSERT INTO [country] ([id], [name]) VALUES ('kru', 'Κουρούχ');
INSERT INTO [country] ([id], [name]) VALUES ('kut', 'Κουτενάι');
INSERT INTO [country] ([id], [name]) VALUES ('kpe', 'Κπέλε');
INSERT INTO [country] ([id], [name]) VALUES ('crp', 'Κρεόλ ή Πίντγκιν');
INSERT INTO [country] ([id], [name]) VALUES ('cpe', 'Κρεόλ ή Πίντγκιν βάσει Αγγλικών');
INSERT INTO [country] ([id], [name]) VALUES ('cpf', 'Κρεόλ ή Πίντγκιν βάσει Γαλλικών');
INSERT INTO [country] ([id], [name]) VALUES ('cpp', 'Κρεόλ και Πίντγκιν βάσει Πορτογαλικών');
INSERT INTO [country] ([id], [name]) VALUES ('cr', 'Κρι');
INSERT INTO [country] ([id], [name]) VALUES ('mus', 'Κρικ');
INSERT INTO [country] ([id], [name]) VALUES ('hr', 'Κροατικά');
INSERT INTO [country] ([id], [name]) VALUES ('kro', 'Κρου');
INSERT INTO [country] ([id], [name]) VALUES ('ky', 'Κυργιζικά');
INSERT INTO [country] ([id], [name]) VALUES ('lad', 'Λαδίνο');
INSERT INTO [country] ([id], [name]) VALUES ('lez', 'Λαζγκιάν');
INSERT INTO [country] ([id], [name]) VALUES ('lam', 'Λάμπα');
INSERT INTO [country] ([id], [name]) VALUES ('lo', 'Λαοθιανά');
INSERT INTO [country] ([id], [name]) VALUES ('la', 'Λατινικά');
INSERT INTO [country] ([id], [name]) VALUES ('lah', 'Λάχδα');
INSERT INTO [country] ([id], [name]) VALUES ('lv', 'Λετονικά');
INSERT INTO [country] ([id], [name]) VALUES ('be', 'Λευκορωσικά');
INSERT INTO [country] ([id], [name]) VALUES ('lt', 'Λιθουανικά');
INSERT INTO [country] ([id], [name]) VALUES ('li', 'Λιμβουργιανά');
INSERT INTO [country] ([id], [name]) VALUES ('ln', 'Λινγκάλα');
INSERT INTO [country] ([id], [name]) VALUES ('loz', 'Λόζι');
INSERT INTO [country] ([id], [name]) VALUES ('jbo', 'Λόζμπαν');
INSERT INTO [country] ([id], [name]) VALUES ('lui', 'Λουισένο');
INSERT INTO [country] ([id], [name]) VALUES ('smj', 'Λούλε Σάμι');
INSERT INTO [country] ([id], [name]) VALUES ('lu', 'Λούμπα-Κατάνγκα');
INSERT INTO [country] ([id], [name]) VALUES ('lua', 'Λούμπα-Λουλούα');
INSERT INTO [country] ([id], [name]) VALUES ('lun', 'Λούντα');
INSERT INTO [country] ([id], [name]) VALUES ('lb', 'Λουξεμβουργικά');
INSERT INTO [country] ([id], [name]) VALUES ('luo', 'Λούο');
INSERT INTO [country] ([id], [name]) VALUES ('lus', 'Λουσάι');
INSERT INTO [country] ([id], [name]) VALUES ('luy', 'Λουχία');
INSERT INTO [country] ([id], [name]) VALUES ('mag', 'Μαγκάχι');
INSERT INTO [country] ([id], [name]) VALUES ('mai', 'Μαϊτχίλι');
INSERT INTO [country] ([id], [name]) VALUES ('mak', 'Μακαζάρ');
INSERT INTO [country] ([id], [name]) VALUES ('mg', 'Μαλαγάσι');
INSERT INTO [country] ([id], [name]) VALUES ('ml', 'Μαλαγιαλάμ');
INSERT INTO [country] ([id], [name]) VALUES ('ms', 'Μαλάι');
INSERT INTO [country] ([id], [name]) VALUES ('mt', 'Μαλτεζικά');
INSERT INTO [country] ([id], [name]) VALUES ('mdr', 'Μανδάρ');
INSERT INTO [country] ([id], [name]) VALUES ('mni', 'Μανιπούρι');
INSERT INTO [country] ([id], [name]) VALUES ('gv', 'Μανξ');
INSERT INTO [country] ([id], [name]) VALUES ('man', 'Μαντίνγκο');
INSERT INTO [country] ([id], [name]) VALUES ('mad', 'Μαντουρίζ');
INSERT INTO [country] ([id], [name]) VALUES ('mnc', 'Μαντσού');
INSERT INTO [country] ([id], [name]) VALUES ('mi', 'Μάορι');
INSERT INTO [country] ([id], [name]) VALUES ('mr', 'Μαράθι');
INSERT INTO [country] ([id], [name]) VALUES ('mwr', 'Μαργουάρι');
INSERT INTO [country] ([id], [name]) VALUES ('chm', 'Μάρι');
INSERT INTO [country] ([id], [name]) VALUES ('mh', 'Μάρσαλ');
INSERT INTO [country] ([id], [name]) VALUES ('mas', 'Μασάι');
INSERT INTO [country] ([id], [name]) VALUES ('men', 'Μέντε');
INSERT INTO [country] ([id], [name]) VALUES ('enm', 'Μέσα Αγγλικά');
INSERT INTO [country] ([id], [name]) VALUES ('gmh', 'Μέσα Άνω Γερμανικά');
INSERT INTO [country] ([id], [name]) VALUES ('frm', 'Μέσα Γαλλικά');
INSERT INTO [country] ([id], [name]) VALUES ('mga', 'Μέσα Ιρλανδικά');
INSERT INTO [country] ([id], [name]) VALUES ('dum', 'Μέσα Ολλανδικά');
INSERT INTO [country] ([id], [name]) VALUES ('mic', 'Μικμάκ');
INSERT INTO [country] ([id], [name]) VALUES ('min', 'Μινανγκαμπάου');
INSERT INTO [country] ([id], [name]) VALUES ('mwl', 'Μιραντεζικά');
INSERT INTO [country] ([id], [name]) VALUES ('mn', 'Μογγολικά');
INSERT INTO [country] ([id], [name]) VALUES ('mdf', 'Μόκσα');
INSERT INTO [country] ([id], [name]) VALUES ('mo', 'Μολδαβικά');
INSERT INTO [country] ([id], [name]) VALUES ('lol', 'Μόνγκο');
INSERT INTO [country] ([id], [name]) VALUES ('mos', 'Μόσι');
INSERT INTO [country] ([id], [name]) VALUES ('moh', 'Μοχόκ');
INSERT INTO [country] ([id], [name]) VALUES ('ban', 'Μπαλινίζ');
INSERT INTO [country] ([id], [name]) VALUES ('bal', 'Μπαλούτσι');
INSERT INTO [country] ([id], [name]) VALUES ('bm', 'Μπαμπάρα');
INSERT INTO [country] ([id], [name]) VALUES ('bad', 'Μπάντα');
INSERT INTO [country] ([id], [name]) VALUES ('bnt', 'Μπαντού');
INSERT INTO [country] ([id], [name]) VALUES ('bas', 'Μπάσα');
INSERT INTO [country] ([id], [name]) VALUES ('ba', 'Μπασκίρ');
INSERT INTO [country] ([id], [name]) VALUES ('btk', 'Μπατάκ');
INSERT INTO [country] ([id], [name]) VALUES ('bej', 'Μπέζα');
INSERT INTO [country] ([id], [name]) VALUES ('bem', 'Μπέμπα');
INSERT INTO [country] ([id], [name]) VALUES ('bez', 'Μπένα');
INSERT INTO [country] ([id], [name]) VALUES ('bn', 'Μπενγκάλι');
INSERT INTO [country] ([id], [name]) VALUES ('ber', 'Μπέρμπερ');
INSERT INTO [country] ([id], [name]) VALUES ('bik', 'Μπικόλ');
INSERT INTO [country] ([id], [name]) VALUES ('bin', 'Μπίνι');
INSERT INTO [country] ([id], [name]) VALUES ('bi', 'Μπισλάμα');
INSERT INTO [country] ([id], [name]) VALUES ('bh', 'Μπιχάρι');
INSERT INTO [country] ([id], [name]) VALUES ('byn', 'Μπλιν');
INSERT INTO [country] ([id], [name]) VALUES ('bho', 'Μποζπούρι');
INSERT INTO [country] ([id], [name]) VALUES ('brx', 'Μπόντο');
INSERT INTO [country] ([id], [name]) VALUES ('bug', 'Μπουγκίζ');
INSERT INTO [country] ([id], [name]) VALUES ('bua', 'Μπουριάτ');
INSERT INTO [country] ([id], [name]) VALUES ('bra', 'Μπρατζ');
INSERT INTO [country] ([id], [name]) VALUES ('nqo', 'Ν''Κο');
INSERT INTO [country] ([id], [name]) VALUES ('nv', 'Νάβαχο');
INSERT INTO [country] ([id], [name]) VALUES ('na', 'Ναούρου');
INSERT INTO [country] ([id], [name]) VALUES ('nap', 'Ναπολιτανικά');
INSERT INTO [country] ([id], [name]) VALUES ('nah', 'Ναχουάτλ');
INSERT INTO [country] ([id], [name]) VALUES ('new', 'Νεγουάρι');
INSERT INTO [country] ([id], [name]) VALUES ('ne', 'Νεπάλι');
INSERT INTO [country] ([id], [name]) VALUES ('nzi', 'Νζίμα');
INSERT INTO [country] ([id], [name]) VALUES ('nym', 'Νιαμγουέζι');
INSERT INTO [country] ([id], [name]) VALUES ('nyn', 'Νιανκόλε');
INSERT INTO [country] ([id], [name]) VALUES ('ny', 'Νιάντζα');
INSERT INTO [country] ([id], [name]) VALUES ('nia', 'Νίας');
INSERT INTO [country] ([id], [name]) VALUES ('tog', 'Νιάσα Τόνγκα');
INSERT INTO [country] ([id], [name]) VALUES ('ssa', 'Νιλο-Σαχαριανή γλώσσα');
INSERT INTO [country] ([id], [name]) VALUES ('nyo', 'Νιόρο');
INSERT INTO [country] ([id], [name]) VALUES ('niu', 'Νιούεαν');
INSERT INTO [country] ([id], [name]) VALUES ('nog', 'Νογκάι');
INSERT INTO [country] ([id], [name]) VALUES ('sgn', 'Νοηματική γλώσσα');
INSERT INTO [country] ([id], [name]) VALUES ('no', 'Νορβηγικά');
INSERT INTO [country] ([id], [name]) VALUES ('nb', 'Νορβηγικά Μποκμάλ');
INSERT INTO [country] ([id], [name]) VALUES ('nn', 'Νορβηγικά Νινόρσκ');
INSERT INTO [country] ([id], [name]) VALUES ('alt', 'Νότια Αλαταϊκά');
INSERT INTO [country] ([id], [name]) VALUES ('sma', 'Νότια Σάμι');
INSERT INTO [country] ([id], [name]) VALUES ('st', 'Νότια Σόθο');
INSERT INTO [country] ([id], [name]) VALUES ('day', 'Νταγιάκ');
INSERT INTO [country] ([id], [name]) VALUES ('dak', 'Ντακότα');
INSERT INTO [country] ([id], [name]) VALUES ('dar', 'Ντάργκουα');
INSERT INTO [country] ([id], [name]) VALUES ('del', 'Ντέλαγουερ');
INSERT INTO [country] ([id], [name]) VALUES ('nd', 'Ντεμπέλε Βορρά');
INSERT INTO [country] ([id], [name]) VALUES ('nr', 'Ντεμπέλε Νότου');
INSERT INTO [country] ([id], [name]) VALUES ('dz', 'Ντζόνγκχα');
INSERT INTO [country] ([id], [name]) VALUES ('dv', 'Ντιβέχι');
INSERT INTO [country] ([id], [name]) VALUES ('din', 'Ντίνκα');
INSERT INTO [country] ([id], [name]) VALUES ('dyu', 'Ντογιούλα');
INSERT INTO [country] ([id], [name]) VALUES ('doi', 'Ντόγκρι');
INSERT INTO [country] ([id], [name]) VALUES ('dgr', 'Ντόγκριμπ');
INSERT INTO [country] ([id], [name]) VALUES ('ng', 'Ντόνγκα');
INSERT INTO [country] ([id], [name]) VALUES ('dua', 'Ντουάλα');
INSERT INTO [country] ([id], [name]) VALUES ('oj', 'Οζιβίγουα');
INSERT INTO [country] ([id], [name]) VALUES ('ota', 'Οθωμανικά Τουρκικά');
INSERT INTO [country] ([id], [name]) VALUES ('oto', 'Οθωμανική γλώσσα');
INSERT INTO [country] ([id], [name]) VALUES ('oc', 'Οκσιτανικά');
INSERT INTO [country] ([id], [name]) VALUES ('nl', 'Ολλανδικά');
INSERT INTO [country] ([id], [name]) VALUES ('or', 'Ορίγια');
INSERT INTO [country] ([id], [name]) VALUES ('om', 'Ορόμο');
INSERT INTO [country] ([id], [name]) VALUES ('osa', 'Οσάζ');
INSERT INTO [country] ([id], [name]) VALUES ('os', 'Οσετικά');
INSERT INTO [country] ([id], [name]) VALUES ('map', 'Οστρονέζιαν');
INSERT INTO [country] ([id], [name]) VALUES ('cy', 'Ουαλικά');
INSERT INTO [country] ([id], [name]) VALUES ('hu', 'Ουγγρικά');
INSERT INTO [country] ([id], [name]) VALUES ('uga', 'Ουγκαρίτικ');
INSERT INTO [country] ([id], [name]) VALUES ('uz', 'Ουζμπεκικά');
INSERT INTO [country] ([id], [name]) VALUES ('ug', 'Ουιγουρικά');
INSERT INTO [country] ([id], [name]) VALUES ('uk', 'Ουκρανικά');
INSERT INTO [country] ([id], [name]) VALUES ('umb', 'Ουμπούντου');
INSERT INTO [country] ([id], [name]) VALUES ('udm', 'Ουντμούρτ');
INSERT INTO [country] ([id], [name]) VALUES ('ur', 'Ουρντού');
INSERT INTO [country] ([id], [name]) VALUES ('ang', 'Παλαιά Αγγλικά');
INSERT INTO [country] ([id], [name]) VALUES ('goh', 'Παλαιά Άνω Γερμανικά');
INSERT INTO [country] ([id], [name]) VALUES ('fro', 'Παλαιά Γαλλικά');
INSERT INTO [country] ([id], [name]) VALUES ('sga', 'Παλαιά Ιρλανδικά');
INSERT INTO [country] ([id], [name]) VALUES ('non', 'Παλαιά Νορβηγικά');
INSERT INTO [country] ([id], [name]) VALUES ('pro', 'Παλαιά Προβενσιάλ');
INSERT INTO [country] ([id], [name]) VALUES ('pau', 'Παλάουαν');
INSERT INTO [country] ([id], [name]) VALUES ('pi', 'Πάλι');
INSERT INTO [country] ([id], [name]) VALUES ('pam', 'Παμπάνγκα');
INSERT INTO [country] ([id], [name]) VALUES ('pag', 'Πανγκασινάν');
INSERT INTO [country] ([id], [name]) VALUES ('pa', 'Παντζαπικά');
INSERT INTO [country] ([id], [name]) VALUES ('pap', 'Παπιαμέντο');
INSERT INTO [country] ([id], [name]) VALUES ('paa', 'Παπούα');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hant', 'Παραδοσιακά Κινεζικά');
INSERT INTO [country] ([id], [name]) VALUES ('ps', 'Πάστο');
INSERT INTO [country] ([id], [name]) VALUES ('pal', 'Παχλάβι');
INSERT INTO [country] ([id], [name]) VALUES ('fa', 'Περσικά');
INSERT INTO [country] ([id], [name]) VALUES ('pl', 'Πολωνικά');
INSERT INTO [country] ([id], [name]) VALUES ('pt', 'Πορτογαλικά');
INSERT INTO [country] ([id], [name]) VALUES ('pt_BR', 'Πορτογαλικά Βραζιλίας');
INSERT INTO [country] ([id], [name]) VALUES ('pt_PT', 'Πορτογαλικά Ιβηρικής');
INSERT INTO [country] ([id], [name]) VALUES ('pon', 'Ποχπέιαν');
INSERT INTO [country] ([id], [name]) VALUES ('raj', 'Ραζασθάνι');
INSERT INTO [country] ([id], [name]) VALUES ('rap', 'Ραπανούι');
INSERT INTO [country] ([id], [name]) VALUES ('rar', 'Ραροτονγκάν');
INSERT INTO [country] ([id], [name]) VALUES ('rm', 'Ρετο-Ρομανικά');
INSERT INTO [country] ([id], [name]) VALUES ('rom', 'Ρομανί');
INSERT INTO [country] ([id], [name]) VALUES ('roa', 'Ρομανική γλώσσα');
INSERT INTO [country] ([id], [name]) VALUES ('rof', 'Ρόμπο');
INSERT INTO [country] ([id], [name]) VALUES ('rwk', 'Ρουά');
INSERT INTO [country] ([id], [name]) VALUES ('ro', 'Ρουμανικά');
INSERT INTO [country] ([id], [name]) VALUES ('rn', 'Ρούντι');
INSERT INTO [country] ([id], [name]) VALUES ('root', 'Ρουτ');
INSERT INTO [country] ([id], [name]) VALUES ('ru', 'Ρωσικά');
INSERT INTO [country] ([id], [name]) VALUES ('sam', 'Σαμαρίτικα Αραμαϊκά');
INSERT INTO [country] ([id], [name]) VALUES ('sm', 'Σαμόαν');
INSERT INTO [country] ([id], [name]) VALUES ('shn', 'Σαν');
INSERT INTO [country] ([id], [name]) VALUES ('sg', 'Σάνγκο');
INSERT INTO [country] ([id], [name]) VALUES ('sa', 'Σανσκριτικά');
INSERT INTO [country] ([id], [name]) VALUES ('sad', 'Σαντάγουε');
INSERT INTO [country] ([id], [name]) VALUES ('sat', 'Σαντάλι');
INSERT INTO [country] ([id], [name]) VALUES ('sc', 'Σαρδινικά');
INSERT INTO [country] ([id], [name]) VALUES ('sas', 'Σασάκ');
INSERT INTO [country] ([id], [name]) VALUES ('chy', 'Σεγιέν');
INSERT INTO [country] ([id], [name]) VALUES ('sel', 'Σελκούπ');
INSERT INTO [country] ([id], [name]) VALUES ('sr', 'Σερβικά');
INSERT INTO [country] ([id], [name]) VALUES ('sh', 'Σερβοκροατικά');
INSERT INTO [country] ([id], [name]) VALUES ('srr', 'Σερέρ');
INSERT INTO [country] ([id], [name]) VALUES ('sem', 'Σημητική γλώσσα');
INSERT INTO [country] ([id], [name]) VALUES ('scn', 'Σικελιανά');
INSERT INTO [country] ([id], [name]) VALUES ('ii', 'Σικουάν Γι');
INSERT INTO [country] ([id], [name]) VALUES ('bla', 'Σικσίκα');
INSERT INTO [country] ([id], [name]) VALUES ('sit', 'Σινοθιβετιανή γλώσσα');
INSERT INTO [country] ([id], [name]) VALUES ('sid', 'Σιντάμο');
INSERT INTO [country] ([id], [name]) VALUES ('sd', 'Σίντι');
INSERT INTO [country] ([id], [name]) VALUES ('si', 'Σινχαλεζικά');
INSERT INTO [country] ([id], [name]) VALUES ('sms', 'Σκολτ Σάμι');
INSERT INTO [country] ([id], [name]) VALUES ('sco', 'Σκωτικά');
INSERT INTO [country] ([id], [name]) VALUES ('gd', 'Σκωτικά Κελτικά');
INSERT INTO [country] ([id], [name]) VALUES ('den', 'Σλαβικά');
INSERT INTO [country] ([id], [name]) VALUES ('sla', 'Σλαβική γλώσσα');
INSERT INTO [country] ([id], [name]) VALUES ('mk', 'Σλαβομακεδονικά');
INSERT INTO [country] ([id], [name]) VALUES ('sk', 'Σλοβακικά');
INSERT INTO [country] ([id], [name]) VALUES ('sl', 'Σλοβενικά');
INSERT INTO [country] ([id], [name]) VALUES ('sog', 'Σογκντιέν');
INSERT INTO [country] ([id], [name]) VALUES ('so', 'Σομάλι');
INSERT INTO [country] ([id], [name]) VALUES ('son', 'Σονγκχάι');
INSERT INTO [country] ([id], [name]) VALUES ('snk', 'Σονίνκε');
INSERT INTO [country] ([id], [name]) VALUES ('ss', 'Σουάτι');
INSERT INTO [country] ([id], [name]) VALUES ('sw', 'Σουαχίλι');
INSERT INTO [country] ([id], [name]) VALUES ('su', 'Σουδανικά');
INSERT INTO [country] ([id], [name]) VALUES ('sv', 'Σουηδικά');
INSERT INTO [country] ([id], [name]) VALUES ('suk', 'Σουκούμα');
INSERT INTO [country] ([id], [name]) VALUES ('sux', 'Σουμερικά');
INSERT INTO [country] ([id], [name]) VALUES ('sus', 'Σούσου');
INSERT INTO [country] ([id], [name]) VALUES ('srn', 'Σρανάρ Τόνγκο');
INSERT INTO [country] ([id], [name]) VALUES ('zbl', 'Σύμβολα Bliss');
INSERT INTO [country] ([id], [name]) VALUES ('syr', 'Συριακά');
INSERT INTO [country] ([id], [name]) VALUES ('sn', 'Σχόνα');
INSERT INTO [country] ([id], [name]) VALUES ('tl', 'Ταγκαλόγκ');
INSERT INTO [country] ([id], [name]) VALUES ('th', 'Ταϊλανδικά');
INSERT INTO [country] ([id], [name]) VALUES ('tai', 'Ταϊλανδική γλώσσα');
INSERT INTO [country] ([id], [name]) VALUES ('ty', 'Ταϊτιανά');
INSERT INTO [country] ([id], [name]) VALUES ('tmh', 'Ταμασέκ');
INSERT INTO [country] ([id], [name]) VALUES ('ta', 'Ταμίλ');
INSERT INTO [country] ([id], [name]) VALUES ('tt', 'Τατάρ');
INSERT INTO [country] ([id], [name]) VALUES ('tg', 'Τατζίκ');
INSERT INTO [country] ([id], [name]) VALUES ('te', 'Τελούγκου');
INSERT INTO [country] ([id], [name]) VALUES ('ter', 'Τερένο');
INSERT INTO [country] ([id], [name]) VALUES ('tet', 'Τέτουμ');
INSERT INTO [country] ([id], [name]) VALUES ('art', 'Τεχνητή γλώσσα');
INSERT INTO [country] ([id], [name]) VALUES ('kaj', 'Τζου');
INSERT INTO [country] ([id], [name]) VALUES ('tiv', 'Τιβ');
INSERT INTO [country] ([id], [name]) VALUES ('tig', 'Τίγκρε');
INSERT INTO [country] ([id], [name]) VALUES ('ti', 'Τιγκρίνυα');
INSERT INTO [country] ([id], [name]) VALUES ('tem', 'Τίμνε');
INSERT INTO [country] ([id], [name]) VALUES ('tli', 'Τλίνγκιτ');
INSERT INTO [country] ([id], [name]) VALUES ('tpi', 'Τοκ Πισίν');
INSERT INTO [country] ([id], [name]) VALUES ('tkl', 'Τοκελάου');
INSERT INTO [country] ([id], [name]) VALUES ('to', 'Τόνγκα');
INSERT INTO [country] ([id], [name]) VALUES ('kcg', 'Τουάπ');
INSERT INTO [country] ([id], [name]) VALUES ('tvl', 'Τουβαλού');
INSERT INTO [country] ([id], [name]) VALUES ('tyv', 'Τουβίνιαν');
INSERT INTO [country] ([id], [name]) VALUES ('tw', 'Τούι');
INSERT INTO [country] ([id], [name]) VALUES ('tum', 'Τουμπούκα');
INSERT INTO [country] ([id], [name]) VALUES ('tr', 'Τουρκικά');
INSERT INTO [country] ([id], [name]) VALUES ('crh', 'Τουρκικά Κριμαίας');
INSERT INTO [country] ([id], [name]) VALUES ('tk', 'Τουρκμενικά');
INSERT INTO [country] ([id], [name]) VALUES ('chg', 'Τσαγκατάι');
INSERT INTO [country] ([id], [name]) VALUES ('chr', 'Τσερόκι');
INSERT INTO [country] ([id], [name]) VALUES ('ce', 'Τσέτσνιαν');
INSERT INTO [country] ([id], [name]) VALUES ('cs', 'Τσεχικά');
INSERT INTO [country] ([id], [name]) VALUES ('tn', 'Τσιγουάνα');
INSERT INTO [country] ([id], [name]) VALUES ('chb', 'Τσίμπτσα');
INSERT INTO [country] ([id], [name]) VALUES ('tsi', 'Τσίμσιαν');
INSERT INTO [country] ([id], [name]) VALUES ('chp', 'Τσίπιουαν');
INSERT INTO [country] ([id], [name]) VALUES ('cho', 'Τσοκτάου');
INSERT INTO [country] ([id], [name]) VALUES ('ts', 'Τσόνγκα');
INSERT INTO [country] ([id], [name]) VALUES ('chk', 'Τσουκίζι');
INSERT INTO [country] ([id], [name]) VALUES ('fan', 'Φανγκ');
INSERT INTO [country] ([id], [name]) VALUES ('fat', 'Φάντι');
INSERT INTO [country] ([id], [name]) VALUES ('fo', 'Φαρόε');
INSERT INTO [country] ([id], [name]) VALUES ('fil', 'Φιλιππινεζικά');
INSERT INTO [country] ([id], [name]) VALUES ('phi', 'Φιλιππινεζική γλώσσα');
INSERT INTO [country] ([id], [name]) VALUES ('fi', 'Φινλανδικά');
INSERT INTO [country] ([id], [name]) VALUES ('fiu', 'Φιννο-Ούγκριαν');
INSERT INTO [country] ([id], [name]) VALUES ('fj', 'Φίτζι');
INSERT INTO [country] ([id], [name]) VALUES ('nl_BE', 'Φλαμανδικά');
INSERT INTO [country] ([id], [name]) VALUES ('phn', 'Φοινικικά');
INSERT INTO [country] ([id], [name]) VALUES ('fon', 'Φον');
INSERT INTO [country] ([id], [name]) VALUES ('ff', 'Φουλάχ');
INSERT INTO [country] ([id], [name]) VALUES ('fur', 'Φριούλιαν');
INSERT INTO [country] ([id], [name]) VALUES ('haw', 'Χαβανεζικά');
INSERT INTO [country] ([id], [name]) VALUES ('hai', 'Χάιντα');
INSERT INTO [country] ([id], [name]) VALUES ('cmc', 'Χαμική γλώσσα');
INSERT INTO [country] ([id], [name]) VALUES ('ha', 'Χάουσα');
INSERT INTO [country] ([id], [name]) VALUES ('hz', 'Χερέρο');
INSERT INTO [country] ([id], [name]) VALUES ('hil', 'Χιλιγκαγιόν');
INSERT INTO [country] ([id], [name]) VALUES ('him', 'Χιματσάλι');
INSERT INTO [country] ([id], [name]) VALUES ('hi', 'Χίντι');
INSERT INTO [country] ([id], [name]) VALUES ('ho', 'Χίρι Μότου');
INSERT INTO [country] ([id], [name]) VALUES ('hit', 'Χιτίτε');
INSERT INTO [country] ([id], [name]) VALUES ('hmn', 'Χμονγκ');
INSERT INTO [country] ([id], [name]) VALUES ('cv', 'Χουβάς');
INSERT INTO [country] ([id], [name]) VALUES ('hup', 'Χούπα');
INSERT INTO [country] ([id], [name]) VALUES ('zxx', 'Χωρίς γλωσσολογικό περιεχόμενο');
