CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('ab', 'abjasio');
INSERT INTO "country" ("id", "name") VALUES ('akk', 'acadio');
INSERT INTO "country" ("id", "name") VALUES ('ace', 'acehnés');
INSERT INTO "country" ("id", "name") VALUES ('ach', 'acoli');
INSERT INTO "country" ("id", "name") VALUES ('ada', 'adangme');
INSERT INTO "country" ("id", "name") VALUES ('ady', 'adigeo');
INSERT INTO "country" ("id", "name") VALUES ('aa', 'afar');
INSERT INTO "country" ("id", "name") VALUES ('afh', 'afrihili');
INSERT INTO "country" ("id", "name") VALUES ('af', 'afrikaans');
INSERT INTO "country" ("id", "name") VALUES ('ay', 'aimara');
INSERT INTO "country" ("id", "name") VALUES ('ain', 'ainu');
INSERT INTO "country" ("id", "name") VALUES ('ak', 'akan');
INSERT INTO "country" ("id", "name") VALUES ('sq', 'albanés');
INSERT INTO "country" ("id", "name") VALUES ('de', 'alemán');
INSERT INTO "country" ("id", "name") VALUES ('de_AT', 'alemán austríaco');
INSERT INTO "country" ("id", "name") VALUES ('goh', 'alemán de la alta edad antigua');
INSERT INTO "country" ("id", "name") VALUES ('gmh', 'alemán de la alta edad media');
INSERT INTO "country" ("id", "name") VALUES ('gsw', 'alemán suizo');
INSERT INTO "country" ("id", "name") VALUES ('ale', 'aleutiano');
INSERT INTO "country" ("id", "name") VALUES ('alt', 'altái meridional');
INSERT INTO "country" ("id", "name") VALUES ('de_CH', 'alto alemán de Suiza');
INSERT INTO "country" ("id", "name") VALUES ('am', 'amárico');
INSERT INTO "country" ("id", "name") VALUES ('anp', 'angika');
INSERT INTO "country" ("id", "name") VALUES ('ar', 'árabe');
INSERT INTO "country" ("id", "name") VALUES ('an', 'aragonés');
INSERT INTO "country" ("id", "name") VALUES ('arw', 'arahuaco');
INSERT INTO "country" ("id", "name") VALUES ('arc', 'arameo');
INSERT INTO "country" ("id", "name") VALUES ('sam', 'arameo samaritano');
INSERT INTO "country" ("id", "name") VALUES ('arp', 'arapaho');
INSERT INTO "country" ("id", "name") VALUES ('arn', 'araucano');
INSERT INTO "country" ("id", "name") VALUES ('hy', 'armenio');
INSERT INTO "country" ("id", "name") VALUES ('rup', 'arrumano');
INSERT INTO "country" ("id", "name") VALUES ('as', 'asamés');
INSERT INTO "country" ("id", "name") VALUES ('ast', 'asturiano');
INSERT INTO "country" ("id", "name") VALUES ('cch', 'atsam');
INSERT INTO "country" ("id", "name") VALUES ('awa', 'avadhi');
INSERT INTO "country" ("id", "name") VALUES ('av', 'avar');
INSERT INTO "country" ("id", "name") VALUES ('ae', 'avéstico');
INSERT INTO "country" ("id", "name") VALUES ('az', 'azerí');
INSERT INTO "country" ("id", "name") VALUES ('nds', 'bajo alemán');
INSERT INTO "country" ("id", "name") VALUES ('ban', 'balinés');
INSERT INTO "country" ("id", "name") VALUES ('bal', 'baluchi');
INSERT INTO "country" ("id", "name") VALUES ('bm', 'bambara');
INSERT INTO "country" ("id", "name") VALUES ('bad', 'banda');
INSERT INTO "country" ("id", "name") VALUES ('bnt', 'bantú');
INSERT INTO "country" ("id", "name") VALUES ('bas', 'basa');
INSERT INTO "country" ("id", "name") VALUES ('ba', 'bashkir');
INSERT INTO "country" ("id", "name") VALUES ('btk', 'batak');
INSERT INTO "country" ("id", "name") VALUES ('bej', 'beja');
INSERT INTO "country" ("id", "name") VALUES ('bem', 'bemba');
INSERT INTO "country" ("id", "name") VALUES ('bn', 'bengalí');
INSERT INTO "country" ("id", "name") VALUES ('ber', 'bereber');
INSERT INTO "country" ("id", "name") VALUES ('bho', 'bhojpuri');
INSERT INTO "country" ("id", "name") VALUES ('bik', 'bicol');
INSERT INTO "country" ("id", "name") VALUES ('be', 'bielorruso');
INSERT INTO "country" ("id", "name") VALUES ('bh', 'bihari');
INSERT INTO "country" ("id", "name") VALUES ('bin', 'bini');
INSERT INTO "country" ("id", "name") VALUES ('my', 'birmano');
INSERT INTO "country" ("id", "name") VALUES ('bi', 'bislama');
INSERT INTO "country" ("id", "name") VALUES ('byn', 'blin');
INSERT INTO "country" ("id", "name") VALUES ('nb', 'bokmal noruego');
INSERT INTO "country" ("id", "name") VALUES ('bs', 'bosnio');
INSERT INTO "country" ("id", "name") VALUES ('bra', 'braj');
INSERT INTO "country" ("id", "name") VALUES ('br', 'bretón');
INSERT INTO "country" ("id", "name") VALUES ('bug', 'buginés');
INSERT INTO "country" ("id", "name") VALUES ('bg', 'búlgaro');
INSERT INTO "country" ("id", "name") VALUES ('bua', 'buriat');
INSERT INTO "country" ("id", "name") VALUES ('kab', 'cabila');
INSERT INTO "country" ("id", "name") VALUES ('ks', 'cachemiro');
INSERT INTO "country" ("id", "name") VALUES ('cad', 'caddo');
INSERT INTO "country" ("id", "name") VALUES ('kn', 'canarés');
INSERT INTO "country" ("id", "name") VALUES ('yue', 'cantonés');
INSERT INTO "country" ("id", "name") VALUES ('krl', 'carelio');
INSERT INTO "country" ("id", "name") VALUES ('car', 'caribe');
INSERT INTO "country" ("id", "name") VALUES ('csb', 'casubio');
INSERT INTO "country" ("id", "name") VALUES ('ca', 'catalán');
INSERT INTO "country" ("id", "name") VALUES ('ceb', 'cebuano');
INSERT INTO "country" ("id", "name") VALUES ('chg', 'chagatái');
INSERT INTO "country" ("id", "name") VALUES ('ch', 'chamorro');
INSERT INTO "country" ("id", "name") VALUES ('ce', 'checheno');
INSERT INTO "country" ("id", "name") VALUES ('cs', 'checo');
INSERT INTO "country" ("id", "name") VALUES ('chr', 'cherokee');
INSERT INTO "country" ("id", "name") VALUES ('chy', 'cheyene');
INSERT INTO "country" ("id", "name") VALUES ('chb', 'chibcha');
INSERT INTO "country" ("id", "name") VALUES ('zh', 'chino');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hans', 'chino simplificado');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hant', 'chino tradicional');
INSERT INTO "country" ("id", "name") VALUES ('chp', 'chipewyan');
INSERT INTO "country" ("id", "name") VALUES ('cho', 'choctaw');
INSERT INTO "country" ("id", "name") VALUES ('cv', 'chuvash');
INSERT INTO "country" ("id", "name") VALUES ('si', 'cingalés');
INSERT INTO "country" ("id", "name") VALUES ('swb', 'comorense');
INSERT INTO "country" ("id", "name") VALUES ('cop', 'copto');
INSERT INTO "country" ("id", "name") VALUES ('ko', 'coreano');
INSERT INTO "country" ("id", "name") VALUES ('kw', 'córnico');
INSERT INTO "country" ("id", "name") VALUES ('co', 'corso');
INSERT INTO "country" ("id", "name") VALUES ('cr', 'cree');
INSERT INTO "country" ("id", "name") VALUES ('mus', 'creek');
INSERT INTO "country" ("id", "name") VALUES ('hr', 'croata');
INSERT INTO "country" ("id", "name") VALUES ('dak', 'dakota');
INSERT INTO "country" ("id", "name") VALUES ('da', 'danés');
INSERT INTO "country" ("id", "name") VALUES ('dar', 'dargva');
INSERT INTO "country" ("id", "name") VALUES ('day', 'dayak');
INSERT INTO "country" ("id", "name") VALUES ('del', 'delaware');
INSERT INTO "country" ("id", "name") VALUES ('din', 'dinka');
INSERT INTO "country" ("id", "name") VALUES ('dyu', 'diula');
INSERT INTO "country" ("id", "name") VALUES ('dv', 'divehi');
INSERT INTO "country" ("id", "name") VALUES ('doi', 'dogri');
INSERT INTO "country" ("id", "name") VALUES ('dgr', 'dogrib');
INSERT INTO "country" ("id", "name") VALUES ('dua', 'duala');
INSERT INTO "country" ("id", "name") VALUES ('dz', 'dzongkha');
INSERT INTO "country" ("id", "name") VALUES ('efi', 'efik');
INSERT INTO "country" ("id", "name") VALUES ('egy', 'egipcio antiguo');
INSERT INTO "country" ("id", "name") VALUES ('eka', 'ekajuk');
INSERT INTO "country" ("id", "name") VALUES ('elx', 'elamita');
INSERT INTO "country" ("id", "name") VALUES ('myv', 'erzya');
INSERT INTO "country" ("id", "name") VALUES ('sco', 'escocés');
INSERT INTO "country" ("id", "name") VALUES ('cu', 'eslavo eclesiástico');
INSERT INTO "country" ("id", "name") VALUES ('sk', 'eslovaco');
INSERT INTO "country" ("id", "name") VALUES ('sl', 'esloveno');
INSERT INTO "country" ("id", "name") VALUES ('es', 'español');
INSERT INTO "country" ("id", "name") VALUES ('es_ES', 'español de España');
INSERT INTO "country" ("id", "name") VALUES ('es_419', 'español latinoamericano');
INSERT INTO "country" ("id", "name") VALUES ('eo', 'esperanto');
INSERT INTO "country" ("id", "name") VALUES ('et', 'estonio');
INSERT INTO "country" ("id", "name") VALUES ('ee', 'ewe');
INSERT INTO "country" ("id", "name") VALUES ('ewo', 'ewondo');
INSERT INTO "country" ("id", "name") VALUES ('fan', 'fang');
INSERT INTO "country" ("id", "name") VALUES ('fat', 'fanti');
INSERT INTO "country" ("id", "name") VALUES ('phn', 'fenicio');
INSERT INTO "country" ("id", "name") VALUES ('fo', 'feroés');
INSERT INTO "country" ("id", "name") VALUES ('fj', 'fidjiano');
INSERT INTO "country" ("id", "name") VALUES ('fil', 'filipino');
INSERT INTO "country" ("id", "name") VALUES ('fi', 'finés');
INSERT INTO "country" ("id", "name") VALUES ('nl_BE', 'flamenco');
INSERT INTO "country" ("id", "name") VALUES ('fon', 'fon');
INSERT INTO "country" ("id", "name") VALUES ('fr', 'francés');
INSERT INTO "country" ("id", "name") VALUES ('fro', 'francés antiguo');
INSERT INTO "country" ("id", "name") VALUES ('fr_CA', 'francés canadiense');
INSERT INTO "country" ("id", "name") VALUES ('fr_CH', 'francés de Suiza');
INSERT INTO "country" ("id", "name") VALUES ('frm', 'francés medieval');
INSERT INTO "country" ("id", "name") VALUES ('fy', 'frisón occidental');
INSERT INTO "country" ("id", "name") VALUES ('frs', 'frisón oriental');
INSERT INTO "country" ("id", "name") VALUES ('frr', 'frisón septentrional');
INSERT INTO "country" ("id", "name") VALUES ('fur', 'friulano');
INSERT INTO "country" ("id", "name") VALUES ('ff', 'fula');
INSERT INTO "country" ("id", "name") VALUES ('gaa', 'ga');
INSERT INTO "country" ("id", "name") VALUES ('gd', 'gaélico escocés');
INSERT INTO "country" ("id", "name") VALUES ('gv', 'gaélico manés');
INSERT INTO "country" ("id", "name") VALUES ('cy', 'galés');
INSERT INTO "country" ("id", "name") VALUES ('gl', 'gallego');
INSERT INTO "country" ("id", "name") VALUES ('lg', 'ganda');
INSERT INTO "country" ("id", "name") VALUES ('gay', 'gayo');
INSERT INTO "country" ("id", "name") VALUES ('gba', 'gbaya');
INSERT INTO "country" ("id", "name") VALUES ('gez', 'geez');
INSERT INTO "country" ("id", "name") VALUES ('ka', 'georgiano');
INSERT INTO "country" ("id", "name") VALUES ('gil', 'gilbertés');
INSERT INTO "country" ("id", "name") VALUES ('gon', 'gondi');
INSERT INTO "country" ("id", "name") VALUES ('gor', 'gorontalo');
INSERT INTO "country" ("id", "name") VALUES ('got', 'gótico');
INSERT INTO "country" ("id", "name") VALUES ('grb', 'grebo');
INSERT INTO "country" ("id", "name") VALUES ('el', 'griego');
INSERT INTO "country" ("id", "name") VALUES ('grc', 'griego antiguo');
INSERT INTO "country" ("id", "name") VALUES ('kl', 'groenlandés');
INSERT INTO "country" ("id", "name") VALUES ('gn', 'guaraní');
INSERT INTO "country" ("id", "name") VALUES ('gu', 'gujarati');
INSERT INTO "country" ("id", "name") VALUES ('hai', 'haida');
INSERT INTO "country" ("id", "name") VALUES ('ht', 'haitiano');
INSERT INTO "country" ("id", "name") VALUES ('ha', 'hausa');
INSERT INTO "country" ("id", "name") VALUES ('haw', 'hawaiano');
INSERT INTO "country" ("id", "name") VALUES ('he', 'hebreo');
INSERT INTO "country" ("id", "name") VALUES ('hz', 'herero');
INSERT INTO "country" ("id", "name") VALUES ('hil', 'hiligaynon');
INSERT INTO "country" ("id", "name") VALUES ('him', 'himachali');
INSERT INTO "country" ("id", "name") VALUES ('hi', 'hindi');
INSERT INTO "country" ("id", "name") VALUES ('ho', 'hiri motu');
INSERT INTO "country" ("id", "name") VALUES ('hit', 'hitita');
INSERT INTO "country" ("id", "name") VALUES ('hmn', 'hmong');
INSERT INTO "country" ("id", "name") VALUES ('hu', 'húngaro');
INSERT INTO "country" ("id", "name") VALUES ('hup', 'hupa');
INSERT INTO "country" ("id", "name") VALUES ('iba', 'iban');
INSERT INTO "country" ("id", "name") VALUES ('io', 'ido');
INSERT INTO "country" ("id", "name") VALUES ('ig', 'igbo');
INSERT INTO "country" ("id", "name") VALUES ('ijo', 'ijo');
INSERT INTO "country" ("id", "name") VALUES ('ilo', 'ilocano');
INSERT INTO "country" ("id", "name") VALUES ('id', 'indonesio');
INSERT INTO "country" ("id", "name") VALUES ('en', 'inglés');
INSERT INTO "country" ("id", "name") VALUES ('ang', 'inglés antiguo');
INSERT INTO "country" ("id", "name") VALUES ('en_AU', 'inglés australiano');
INSERT INTO "country" ("id", "name") VALUES ('en_GB', 'inglés británico');
INSERT INTO "country" ("id", "name") VALUES ('en_CA', 'inglés canadiense');
INSERT INTO "country" ("id", "name") VALUES ('en_US', 'inglés estadounidense');
INSERT INTO "country" ("id", "name") VALUES ('enm', 'inglés medieval');
INSERT INTO "country" ("id", "name") VALUES ('inh', 'ingush');
INSERT INTO "country" ("id", "name") VALUES ('ia', 'interlingua');
INSERT INTO "country" ("id", "name") VALUES ('ie', 'interlingue');
INSERT INTO "country" ("id", "name") VALUES ('iu', 'inuktitut');
INSERT INTO "country" ("id", "name") VALUES ('ik', 'inupiaq');
INSERT INTO "country" ("id", "name") VALUES ('ga', 'irlandés');
INSERT INTO "country" ("id", "name") VALUES ('sga', 'irlandés antiguo');
INSERT INTO "country" ("id", "name") VALUES ('mga', 'irlandés medieval');
INSERT INTO "country" ("id", "name") VALUES ('is', 'islandés');
INSERT INTO "country" ("id", "name") VALUES ('it', 'italiano');
INSERT INTO "country" ("id", "name") VALUES ('ja', 'japonés');
INSERT INTO "country" ("id", "name") VALUES ('jv', 'javanés');
INSERT INTO "country" ("id", "name") VALUES ('km', 'jemer');
INSERT INTO "country" ("id", "name") VALUES ('chn', 'jerga chinuk');
INSERT INTO "country" ("id", "name") VALUES ('kaj', 'jju');
INSERT INTO "country" ("id", "name") VALUES ('jrb', 'judeo-árabe');
INSERT INTO "country" ("id", "name") VALUES ('jpr', 'judeo-persa');
INSERT INTO "country" ("id", "name") VALUES ('kbd', 'kabardiano');
INSERT INTO "country" ("id", "name") VALUES ('kac', 'kachin');
INSERT INTO "country" ("id", "name") VALUES ('xal', 'kalmyk');
INSERT INTO "country" ("id", "name") VALUES ('kam', 'kamba');
INSERT INTO "country" ("id", "name") VALUES ('kr', 'kanuri');
INSERT INTO "country" ("id", "name") VALUES ('krc', 'karachay-balkar');
INSERT INTO "country" ("id", "name") VALUES ('kaa', 'karakalpako');
INSERT INTO "country" ("id", "name") VALUES ('kar', 'karen');
INSERT INTO "country" ("id", "name") VALUES ('kaw', 'kawi');
INSERT INTO "country" ("id", "name") VALUES ('kk', 'kazajo');
INSERT INTO "country" ("id", "name") VALUES ('kha', 'khasi');
INSERT INTO "country" ("id", "name") VALUES ('ki', 'kikuyu');
INSERT INTO "country" ("id", "name") VALUES ('kmb', 'kimbundu');
INSERT INTO "country" ("id", "name") VALUES ('rw', 'kinyarwanda');
INSERT INTO "country" ("id", "name") VALUES ('ky', 'kirghiz');
INSERT INTO "country" ("id", "name") VALUES ('rn', 'kiroundi');
INSERT INTO "country" ("id", "name") VALUES ('tlh', 'klingon');
INSERT INTO "country" ("id", "name") VALUES ('kv', 'komi');
INSERT INTO "country" ("id", "name") VALUES ('kg', 'kongo');
INSERT INTO "country" ("id", "name") VALUES ('kok', 'konkani');
INSERT INTO "country" ("id", "name") VALUES ('kfo', 'koro');
INSERT INTO "country" ("id", "name") VALUES ('kos', 'kosraeano');
INSERT INTO "country" ("id", "name") VALUES ('kho', 'kotanés');
INSERT INTO "country" ("id", "name") VALUES ('kpe', 'kpelle');
INSERT INTO "country" ("id", "name") VALUES ('kro', 'kru');
INSERT INTO "country" ("id", "name") VALUES ('kj', 'kuanyama');
INSERT INTO "country" ("id", "name") VALUES ('kum', 'kumyk');
INSERT INTO "country" ("id", "name") VALUES ('ku', 'kurdo');
INSERT INTO "country" ("id", "name") VALUES ('kru', 'kurukh');
INSERT INTO "country" ("id", "name") VALUES ('gwi', 'kutchin');
INSERT INTO "country" ("id", "name") VALUES ('kut', 'kutenai');
INSERT INTO "country" ("id", "name") VALUES ('lad', 'ladino');
INSERT INTO "country" ("id", "name") VALUES ('lah', 'lahnda');
INSERT INTO "country" ("id", "name") VALUES ('lam', 'lamba');
INSERT INTO "country" ("id", "name") VALUES ('lo', 'laosiano');
INSERT INTO "country" ("id", "name") VALUES ('la', 'latín');
INSERT INTO "country" ("id", "name") VALUES ('afa', 'lengua afroasiática');
INSERT INTO "country" ("id", "name") VALUES ('tut', 'lengua altaica');
INSERT INTO "country" ("id", "name") VALUES ('art', 'lengua artificial');
INSERT INTO "country" ("id", "name") VALUES ('map', 'lengua austronesia');
INSERT INTO "country" ("id", "name") VALUES ('bat', 'lengua báltica');
INSERT INTO "country" ("id", "name") VALUES ('cau', 'lengua caucásica');
INSERT INTO "country" ("id", "name") VALUES ('cel', 'lengua celta');
INSERT INTO "country" ("id", "name") VALUES ('crp', 'lengua criolla o pidgin');
INSERT INTO "country" ("id", "name") VALUES ('cpf', 'lengua criolla o pidgin basada en el francés');
INSERT INTO "country" ("id", "name") VALUES ('cpe', 'lengua criolla o pidgin basada en el inglés');
INSERT INTO "country" ("id", "name") VALUES ('cpp', 'lengua criolla o pidgin basada en el portugués');
INSERT INTO "country" ("id", "name") VALUES ('cus', 'lengua cusita');
INSERT INTO "country" ("id", "name") VALUES ('und', 'lengua desconocida');
INSERT INTO "country" ("id", "name") VALUES ('dra', 'lengua dravídica');
INSERT INTO "country" ("id", "name") VALUES ('sla', 'lengua eslava');
INSERT INTO "country" ("id", "name") VALUES ('phi', 'lengua filipina');
INSERT INTO "country" ("id", "name") VALUES ('fiu', 'lengua finoúgria');
INSERT INTO "country" ("id", "name") VALUES ('gem', 'lengua germánica');
INSERT INTO "country" ("id", "name") VALUES ('cai', 'lengua india centroamericana');
INSERT INTO "country" ("id", "name") VALUES ('nai', 'lengua india norteamericana');
INSERT INTO "country" ("id", "name") VALUES ('sai', 'lengua india sudamericana');
INSERT INTO "country" ("id", "name") VALUES ('inc', 'lengua índica');
INSERT INTO "country" ("id", "name") VALUES ('ine', 'lengua indoeuropea');
INSERT INTO "country" ("id", "name") VALUES ('ira', 'lengua irania');
INSERT INTO "country" ("id", "name") VALUES ('khi', 'lengua joisana');
INSERT INTO "country" ("id", "name") VALUES ('mkh', 'lengua mon-jemer');
INSERT INTO "country" ("id", "name") VALUES ('nic', 'lengua níger-cordofana');
INSERT INTO "country" ("id", "name") VALUES ('ssa', 'lengua nilo-sahariana');
INSERT INTO "country" ("id", "name") VALUES ('paa', 'lengua papú');
INSERT INTO "country" ("id", "name") VALUES ('roa', 'lengua romance');
INSERT INTO "country" ("id", "name") VALUES ('smi', 'lengua sami');
INSERT INTO "country" ("id", "name") VALUES ('sem', 'lengua semítica');
INSERT INTO "country" ("id", "name") VALUES ('sit', 'lengua sino-tibetana');
INSERT INTO "country" ("id", "name") VALUES ('tai', 'lengua tai');
INSERT INTO "country" ("id", "name") VALUES ('sgn', 'lenguajes de signos');
INSERT INTO "country" ("id", "name") VALUES ('alg', 'lenguas algonquinas');
INSERT INTO "country" ("id", "name") VALUES ('apa', 'lenguas apache');
INSERT INTO "country" ("id", "name") VALUES ('ath', 'lenguas atabascas');
INSERT INTO "country" ("id", "name") VALUES ('aus', 'lenguas australianas');
INSERT INTO "country" ("id", "name") VALUES ('bai', 'lenguas bamileke');
INSERT INTO "country" ("id", "name") VALUES ('cmc', 'lenguas chámicas');
INSERT INTO "country" ("id", "name") VALUES ('iro', 'lenguas iroquesas');
INSERT INTO "country" ("id", "name") VALUES ('mno', 'lenguas manobo');
INSERT INTO "country" ("id", "name") VALUES ('mun', 'lenguas munda');
INSERT INTO "country" ("id", "name") VALUES ('nub', 'lenguas nubias');
INSERT INTO "country" ("id", "name") VALUES ('oto', 'lenguas otomanas');
INSERT INTO "country" ("id", "name") VALUES ('pra', 'lenguas prácritas');
INSERT INTO "country" ("id", "name") VALUES ('sal', 'lenguas salish');
INSERT INTO "country" ("id", "name") VALUES ('sio', 'lenguas sioux');
INSERT INTO "country" ("id", "name") VALUES ('wen', 'lenguas sorbias');
INSERT INTO "country" ("id", "name") VALUES ('tup', 'lenguas tupí');
INSERT INTO "country" ("id", "name") VALUES ('mis', 'lenguas varias');
INSERT INTO "country" ("id", "name") VALUES ('wak', 'lenguas wakasha');
INSERT INTO "country" ("id", "name") VALUES ('ypk', 'lenguas yupik');
INSERT INTO "country" ("id", "name") VALUES ('lv', 'letón');
INSERT INTO "country" ("id", "name") VALUES ('lez', 'lezgiano');
INSERT INTO "country" ("id", "name") VALUES ('li', 'limburgués');
INSERT INTO "country" ("id", "name") VALUES ('ln', 'lingala');
INSERT INTO "country" ("id", "name") VALUES ('lt', 'lituano');
INSERT INTO "country" ("id", "name") VALUES ('jbo', 'lojban');
INSERT INTO "country" ("id", "name") VALUES ('loz', 'lozi');
INSERT INTO "country" ("id", "name") VALUES ('lu', 'luba-katanga');
INSERT INTO "country" ("id", "name") VALUES ('lua', 'luba-lulua');
INSERT INTO "country" ("id", "name") VALUES ('lui', 'luiseño');
INSERT INTO "country" ("id", "name") VALUES ('lun', 'lunda');
INSERT INTO "country" ("id", "name") VALUES ('luo', 'luo');
INSERT INTO "country" ("id", "name") VALUES ('lus', 'lushai');
INSERT INTO "country" ("id", "name") VALUES ('lb', 'luxemburgués');
INSERT INTO "country" ("id", "name") VALUES ('mak', 'macasar');
INSERT INTO "country" ("id", "name") VALUES ('mk', 'macedonio');
INSERT INTO "country" ("id", "name") VALUES ('mad', 'madurés');
INSERT INTO "country" ("id", "name") VALUES ('mag', 'magahi');
INSERT INTO "country" ("id", "name") VALUES ('mai', 'maithili');
INSERT INTO "country" ("id", "name") VALUES ('ml', 'malayalam');
INSERT INTO "country" ("id", "name") VALUES ('ms', 'malayo');
INSERT INTO "country" ("id", "name") VALUES ('mg', 'malgache');
INSERT INTO "country" ("id", "name") VALUES ('mt', 'maltés');
INSERT INTO "country" ("id", "name") VALUES ('mnc', 'manchú');
INSERT INTO "country" ("id", "name") VALUES ('mdr', 'mandar');
INSERT INTO "country" ("id", "name") VALUES ('man', 'mandingo');
INSERT INTO "country" ("id", "name") VALUES ('mni', 'manipuri');
INSERT INTO "country" ("id", "name") VALUES ('mi', 'maorí');
INSERT INTO "country" ("id", "name") VALUES ('mr', 'marathi');
INSERT INTO "country" ("id", "name") VALUES ('chm', 'marí');
INSERT INTO "country" ("id", "name") VALUES ('mh', 'marshalés');
INSERT INTO "country" ("id", "name") VALUES ('mwr', 'marwari');
INSERT INTO "country" ("id", "name") VALUES ('mas', 'masai');
INSERT INTO "country" ("id", "name") VALUES ('myn', 'maya');
INSERT INTO "country" ("id", "name") VALUES ('men', 'mende');
INSERT INTO "country" ("id", "name") VALUES ('mic', 'micmac');
INSERT INTO "country" ("id", "name") VALUES ('min', 'minangkabau');
INSERT INTO "country" ("id", "name") VALUES ('mwl', 'mirandés');
INSERT INTO "country" ("id", "name") VALUES ('moh', 'mohawk');
INSERT INTO "country" ("id", "name") VALUES ('mdf', 'moksha');
INSERT INTO "country" ("id", "name") VALUES ('mo', 'moldavo');
INSERT INTO "country" ("id", "name") VALUES ('lol', 'mongo');
INSERT INTO "country" ("id", "name") VALUES ('mn', 'mongol');
INSERT INTO "country" ("id", "name") VALUES ('mos', 'mossi');
INSERT INTO "country" ("id", "name") VALUES ('nqo', 'n’ko');
INSERT INTO "country" ("id", "name") VALUES ('nah', 'náhuatl');
INSERT INTO "country" ("id", "name") VALUES ('nap', 'napolitano');
INSERT INTO "country" ("id", "name") VALUES ('na', 'nauruano');
INSERT INTO "country" ("id", "name") VALUES ('nv', 'navajo');
INSERT INTO "country" ("id", "name") VALUES ('nr', 'ndebele meridional');
INSERT INTO "country" ("id", "name") VALUES ('nd', 'ndebele septentrional');
INSERT INTO "country" ("id", "name") VALUES ('ng', 'ndonga');
INSERT INTO "country" ("id", "name") VALUES ('nl', 'neerlandés');
INSERT INTO "country" ("id", "name") VALUES ('dum', 'neerlandés medieval');
INSERT INTO "country" ("id", "name") VALUES ('ne', 'nepalí');
INSERT INTO "country" ("id", "name") VALUES ('new', 'newari');
INSERT INTO "country" ("id", "name") VALUES ('nwc', 'newari clásico');
INSERT INTO "country" ("id", "name") VALUES ('nia', 'nias');
INSERT INTO "country" ("id", "name") VALUES ('niu', 'niueano');
INSERT INTO "country" ("id", "name") VALUES ('nog', 'nogai');
INSERT INTO "country" ("id", "name") VALUES ('non', 'nórdico antiguo');
INSERT INTO "country" ("id", "name") VALUES ('no', 'noruego');
INSERT INTO "country" ("id", "name") VALUES ('nym', 'nyamwezi');
INSERT INTO "country" ("id", "name") VALUES ('ny', 'nyanja');
INSERT INTO "country" ("id", "name") VALUES ('nyn', 'nyankole');
INSERT INTO "country" ("id", "name") VALUES ('nn', 'nynorsk noruego');
INSERT INTO "country" ("id", "name") VALUES ('nyo', 'nyoro');
INSERT INTO "country" ("id", "name") VALUES ('nzi', 'nzima');
INSERT INTO "country" ("id", "name") VALUES ('oc', 'occitano');
INSERT INTO "country" ("id", "name") VALUES ('oj', 'ojibwa');
INSERT INTO "country" ("id", "name") VALUES ('or', 'oriya');
INSERT INTO "country" ("id", "name") VALUES ('om', 'oromo');
INSERT INTO "country" ("id", "name") VALUES ('osa', 'osage');
INSERT INTO "country" ("id", "name") VALUES ('os', 'osético');
INSERT INTO "country" ("id", "name") VALUES ('pal', 'pahlavi');
INSERT INTO "country" ("id", "name") VALUES ('pau', 'palauano');
INSERT INTO "country" ("id", "name") VALUES ('pi', 'pali');
INSERT INTO "country" ("id", "name") VALUES ('pam', 'pampanga');
INSERT INTO "country" ("id", "name") VALUES ('pag', 'pangasinán');
INSERT INTO "country" ("id", "name") VALUES ('pap', 'papiamento');
INSERT INTO "country" ("id", "name") VALUES ('ps', 'pashto');
INSERT INTO "country" ("id", "name") VALUES ('fa', 'persa');
INSERT INTO "country" ("id", "name") VALUES ('peo', 'persa antiguo');
INSERT INTO "country" ("id", "name") VALUES ('pon', 'pohnpeiano');
INSERT INTO "country" ("id", "name") VALUES ('pl', 'polaco');
INSERT INTO "country" ("id", "name") VALUES ('pt', 'portugués');
INSERT INTO "country" ("id", "name") VALUES ('pt_BR', 'portugués de Brasil');
INSERT INTO "country" ("id", "name") VALUES ('pt_PT', 'portugués de Portugal');
INSERT INTO "country" ("id", "name") VALUES ('pro', 'provenzal antiguo');
INSERT INTO "country" ("id", "name") VALUES ('pa', 'punjabí');
INSERT INTO "country" ("id", "name") VALUES ('qu', 'quechua');
INSERT INTO "country" ("id", "name") VALUES ('root', 'raíz');
INSERT INTO "country" ("id", "name") VALUES ('raj', 'rajasthani');
INSERT INTO "country" ("id", "name") VALUES ('rap', 'rapanui');
INSERT INTO "country" ("id", "name") VALUES ('rar', 'rarotongano');
INSERT INTO "country" ("id", "name") VALUES ('rm', 'retorrománico');
INSERT INTO "country" ("id", "name") VALUES ('rom', 'romaní');
INSERT INTO "country" ("id", "name") VALUES ('ro', 'rumano');
INSERT INTO "country" ("id", "name") VALUES ('ru', 'ruso');
INSERT INTO "country" ("id", "name") VALUES ('sah', 'sakha');
INSERT INTO "country" ("id", "name") VALUES ('smn', 'sami inari');
INSERT INTO "country" ("id", "name") VALUES ('smj', 'sami lule');
INSERT INTO "country" ("id", "name") VALUES ('sma', 'sami meridional');
INSERT INTO "country" ("id", "name") VALUES ('se', 'sami septentrional');
INSERT INTO "country" ("id", "name") VALUES ('sms', 'sami skolt');
INSERT INTO "country" ("id", "name") VALUES ('sm', 'samoano');
INSERT INTO "country" ("id", "name") VALUES ('sad', 'sandawe');
INSERT INTO "country" ("id", "name") VALUES ('sg', 'sango');
INSERT INTO "country" ("id", "name") VALUES ('sa', 'sánscrito');
INSERT INTO "country" ("id", "name") VALUES ('sat', 'santali');
INSERT INTO "country" ("id", "name") VALUES ('sc', 'sardo');
INSERT INTO "country" ("id", "name") VALUES ('sas', 'sasak');
INSERT INTO "country" ("id", "name") VALUES ('sel', 'selkup');
INSERT INTO "country" ("id", "name") VALUES ('sr', 'serbio');
INSERT INTO "country" ("id", "name") VALUES ('sh', 'serbocroata');
INSERT INTO "country" ("id", "name") VALUES ('srr', 'serer');
INSERT INTO "country" ("id", "name") VALUES ('st', 'sesotho meridional');
INSERT INTO "country" ("id", "name") VALUES ('tn', 'setchwana');
INSERT INTO "country" ("id", "name") VALUES ('shn', 'shan');
INSERT INTO "country" ("id", "name") VALUES ('sn', 'shona');
INSERT INTO "country" ("id", "name") VALUES ('ii', 'sichuan yi');
INSERT INTO "country" ("id", "name") VALUES ('scn', 'siciliano');
INSERT INTO "country" ("id", "name") VALUES ('sid', 'sidamo');
INSERT INTO "country" ("id", "name") VALUES ('bla', 'siksika');
INSERT INTO "country" ("id", "name") VALUES ('zbl', 'símbolos Bliss');
INSERT INTO "country" ("id", "name") VALUES ('zxx', 'sin contenido lingüístico');
INSERT INTO "country" ("id", "name") VALUES ('sd', 'sindhi');
INSERT INTO "country" ("id", "name") VALUES ('syr', 'siriaco');
INSERT INTO "country" ("id", "name") VALUES ('syc', 'siríaco clásico');
INSERT INTO "country" ("id", "name") VALUES ('ss', 'siswati');
INSERT INTO "country" ("id", "name") VALUES ('den', 'slave');
INSERT INTO "country" ("id", "name") VALUES ('sog', 'sogdiano');
INSERT INTO "country" ("id", "name") VALUES ('so', 'somalí');
INSERT INTO "country" ("id", "name") VALUES ('son', 'songhai');
INSERT INTO "country" ("id", "name") VALUES ('snk', 'soninké');
INSERT INTO "country" ("id", "name") VALUES ('dsb', 'sorbio inferior');
INSERT INTO "country" ("id", "name") VALUES ('hsb', 'sorbio superior');
INSERT INTO "country" ("id", "name") VALUES ('nso', 'sotho septentrional');
INSERT INTO "country" ("id", "name") VALUES ('srn', 'sranan tongo');
INSERT INTO "country" ("id", "name") VALUES ('sv', 'sueco');
INSERT INTO "country" ("id", "name") VALUES ('suk', 'sukuma');
INSERT INTO "country" ("id", "name") VALUES ('sux', 'sumerio');
INSERT INTO "country" ("id", "name") VALUES ('su', 'sundanés');
INSERT INTO "country" ("id", "name") VALUES ('sus', 'susu');
INSERT INTO "country" ("id", "name") VALUES ('sw', 'swahili');
INSERT INTO "country" ("id", "name") VALUES ('tl', 'tagalo');
INSERT INTO "country" ("id", "name") VALUES ('ty', 'tahitiano');
INSERT INTO "country" ("id", "name") VALUES ('th', 'tailandés');
INSERT INTO "country" ("id", "name") VALUES ('tmh', 'tamashek');
INSERT INTO "country" ("id", "name") VALUES ('ta', 'tamil');
INSERT INTO "country" ("id", "name") VALUES ('tt', 'tártaro');
INSERT INTO "country" ("id", "name") VALUES ('crh', 'tártaro de Crimea');
INSERT INTO "country" ("id", "name") VALUES ('tg', 'tayiko');
INSERT INTO "country" ("id", "name") VALUES ('te', 'telugu');
INSERT INTO "country" ("id", "name") VALUES ('tem', 'temne');
INSERT INTO "country" ("id", "name") VALUES ('ter', 'tereno');
INSERT INTO "country" ("id", "name") VALUES ('tet', 'tetún');
INSERT INTO "country" ("id", "name") VALUES ('bo', 'tibetano');
INSERT INTO "country" ("id", "name") VALUES ('tig', 'tigré');
INSERT INTO "country" ("id", "name") VALUES ('ti', 'tigriña');
INSERT INTO "country" ("id", "name") VALUES ('tiv', 'tiv');
INSERT INTO "country" ("id", "name") VALUES ('tli', 'tlingit');
INSERT INTO "country" ("id", "name") VALUES ('tpi', 'tok pisin');
INSERT INTO "country" ("id", "name") VALUES ('tkl', 'tokelauano');
INSERT INTO "country" ("id", "name") VALUES ('tog', 'tonga del Nyasa');
INSERT INTO "country" ("id", "name") VALUES ('to', 'tongano');
INSERT INTO "country" ("id", "name") VALUES ('chk', 'trukés');
INSERT INTO "country" ("id", "name") VALUES ('tsi', 'tsimshiano');
INSERT INTO "country" ("id", "name") VALUES ('ts', 'tsonga');
INSERT INTO "country" ("id", "name") VALUES ('tum', 'tumbuka');
INSERT INTO "country" ("id", "name") VALUES ('tr', 'turco');
INSERT INTO "country" ("id", "name") VALUES ('ota', 'turco otomano');
INSERT INTO "country" ("id", "name") VALUES ('tk', 'turcomano');
INSERT INTO "country" ("id", "name") VALUES ('tvl', 'tuvaluano');
INSERT INTO "country" ("id", "name") VALUES ('tyv', 'tuviniano');
INSERT INTO "country" ("id", "name") VALUES ('tw', 'twi');
INSERT INTO "country" ("id", "name") VALUES ('kcg', 'tyap');
INSERT INTO "country" ("id", "name") VALUES ('uk', 'ucraniano');
INSERT INTO "country" ("id", "name") VALUES ('udm', 'udmurt');
INSERT INTO "country" ("id", "name") VALUES ('uga', 'ugarítico');
INSERT INTO "country" ("id", "name") VALUES ('ug', 'uigur');
INSERT INTO "country" ("id", "name") VALUES ('umb', 'umbundu');
INSERT INTO "country" ("id", "name") VALUES ('wo', 'uolof');
INSERT INTO "country" ("id", "name") VALUES ('ur', 'urdu');
INSERT INTO "country" ("id", "name") VALUES ('uz', 'uzbeko');
INSERT INTO "country" ("id", "name") VALUES ('vai', 'vai');
INSERT INTO "country" ("id", "name") VALUES ('wa', 'valón');
INSERT INTO "country" ("id", "name") VALUES ('eu', 'vasco');
INSERT INTO "country" ("id", "name") VALUES ('ve', 'venda');
INSERT INTO "country" ("id", "name") VALUES ('vi', 'vietnamita');
INSERT INTO "country" ("id", "name") VALUES ('vo', 'volapük');
INSERT INTO "country" ("id", "name") VALUES ('vot', 'vótico');
INSERT INTO "country" ("id", "name") VALUES ('wal', 'walamo');
INSERT INTO "country" ("id", "name") VALUES ('war', 'waray');
INSERT INTO "country" ("id", "name") VALUES ('was', 'washo');
INSERT INTO "country" ("id", "name") VALUES ('xh', 'xhosa');
INSERT INTO "country" ("id", "name") VALUES ('yao', 'yao');
INSERT INTO "country" ("id", "name") VALUES ('yap', 'yapés');
INSERT INTO "country" ("id", "name") VALUES ('yi', 'yídish');
INSERT INTO "country" ("id", "name") VALUES ('yo', 'yoruba');
INSERT INTO "country" ("id", "name") VALUES ('znd', 'zande');
INSERT INTO "country" ("id", "name") VALUES ('zap', 'zapoteco');
INSERT INTO "country" ("id", "name") VALUES ('zza', 'zazaki');
INSERT INTO "country" ("id", "name") VALUES ('zen', 'zenaga');
INSERT INTO "country" ("id", "name") VALUES ('za', 'zhuang');
INSERT INTO "country" ("id", "name") VALUES ('zu', 'zulú');
INSERT INTO "country" ("id", "name") VALUES ('zun', 'zuni');
