CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('bi', 'Bislama');
INSERT INTO "country" ("id", "name") VALUES ('gwi', 'Gwichʼin');
INSERT INTO "country" ("id", "name") VALUES ('ab', 'abchaski');
INSERT INTO "country" ("id", "name") VALUES ('ace', 'aceh');
INSERT INTO "country" ("id", "name") VALUES ('ach', 'aczoli');
INSERT INTO "country" ("id", "name") VALUES ('ada', 'adangme');
INSERT INTO "country" ("id", "name") VALUES ('ady', 'adygejski');
INSERT INTO "country" ("id", "name") VALUES ('aa', 'afar');
INSERT INTO "country" ("id", "name") VALUES ('afh', 'afrihili');
INSERT INTO "country" ("id", "name") VALUES ('af', 'afrikaans');
INSERT INTO "country" ("id", "name") VALUES ('afa', 'afro-azjatycki');
INSERT INTO "country" ("id", "name") VALUES ('ay', 'ajmara');
INSERT INTO "country" ("id", "name") VALUES ('ain', 'ajnu');
INSERT INTO "country" ("id", "name") VALUES ('akk', 'akadyjski');
INSERT INTO "country" ("id", "name") VALUES ('ak', 'akan');
INSERT INTO "country" ("id", "name") VALUES ('sq', 'albański');
INSERT INTO "country" ("id", "name") VALUES ('ale', 'aleucki');
INSERT INTO "country" ("id", "name") VALUES ('am', 'amharski');
INSERT INTO "country" ("id", "name") VALUES ('en', 'angielski');
INSERT INTO "country" ("id", "name") VALUES ('en_US', 'angielski (USA)');
INSERT INTO "country" ("id", "name") VALUES ('cpe', 'angielski kreolski lub pidżin');
INSERT INTO "country" ("id", "name") VALUES ('anp', 'angika');
INSERT INTO "country" ("id", "name") VALUES ('ar', 'arabski');
INSERT INTO "country" ("id", "name") VALUES ('an', 'aragoński');
INSERT INTO "country" ("id", "name") VALUES ('arc', 'aramejski');
INSERT INTO "country" ("id", "name") VALUES ('arp', 'arapaho');
INSERT INTO "country" ("id", "name") VALUES ('arn', 'araukański');
INSERT INTO "country" ("id", "name") VALUES ('arw', 'arawak');
INSERT INTO "country" ("id", "name") VALUES ('rup', 'arumuński');
INSERT INTO "country" ("id", "name") VALUES ('as', 'asamski');
INSERT INTO "country" ("id", "name") VALUES ('ast', 'asturyjski');
INSERT INTO "country" ("id", "name") VALUES ('cch', 'atsam');
INSERT INTO "country" ("id", "name") VALUES ('de_AT', 'austriacki niemiecki');
INSERT INTO "country" ("id", "name") VALUES ('map', 'austronezyjski');
INSERT INTO "country" ("id", "name") VALUES ('awa', 'awadhi');
INSERT INTO "country" ("id", "name") VALUES ('av', 'awarski');
INSERT INTO "country" ("id", "name") VALUES ('ae', 'awestyjski');
INSERT INTO "country" ("id", "name") VALUES ('znd', 'azande');
INSERT INTO "country" ("id", "name") VALUES ('az', 'azerski');
INSERT INTO "country" ("id", "name") VALUES ('tut', 'ałtajski');
INSERT INTO "country" ("id", "name") VALUES ('ban', 'balijski');
INSERT INTO "country" ("id", "name") VALUES ('bm', 'bambara');
INSERT INTO "country" ("id", "name") VALUES ('bnt', 'bantu');
INSERT INTO "country" ("id", "name") VALUES ('bas', 'basa');
INSERT INTO "country" ("id", "name") VALUES ('eu', 'baskijski');
INSERT INTO "country" ("id", "name") VALUES ('ba', 'baszkirski');
INSERT INTO "country" ("id", "name") VALUES ('btk', 'batak');
INSERT INTO "country" ("id", "name") VALUES ('bat', 'bałtycki');
INSERT INTO "country" ("id", "name") VALUES ('bej', 'bedża');
INSERT INTO "country" ("id", "name") VALUES ('bal', 'beludżi');
INSERT INTO "country" ("id", "name") VALUES ('bem', 'bemba');
INSERT INTO "country" ("id", "name") VALUES ('bn', 'bengalski');
INSERT INTO "country" ("id", "name") VALUES ('ber', 'berberski');
INSERT INTO "country" ("id", "name") VALUES ('bho', 'bhodźpuri');
INSERT INTO "country" ("id", "name") VALUES ('be', 'białoruski');
INSERT INTO "country" ("id", "name") VALUES ('bh', 'biharski');
INSERT INTO "country" ("id", "name") VALUES ('bik', 'bikol');
INSERT INTO "country" ("id", "name") VALUES ('bin', 'bini');
INSERT INTO "country" ("id", "name") VALUES ('my', 'birmański');
INSERT INTO "country" ("id", "name") VALUES ('byn', 'blin');
INSERT INTO "country" ("id", "name") VALUES ('zbl', 'bliss');
INSERT INTO "country" ("id", "name") VALUES ('bs', 'bośniacki');
INSERT INTO "country" ("id", "name") VALUES ('bra', 'bradź');
INSERT INTO "country" ("id", "name") VALUES ('zxx', 'brak treści o charakterze lingwistycznym');
INSERT INTO "country" ("id", "name") VALUES ('pt_BR', 'brazylyjski portugalski');
INSERT INTO "country" ("id", "name") VALUES ('br', 'bretoński');
INSERT INTO "country" ("id", "name") VALUES ('en_GB', 'brytyjski angielski');
INSERT INTO "country" ("id", "name") VALUES ('bug', 'bugiński');
INSERT INTO "country" ("id", "name") VALUES ('bua', 'buriacki');
INSERT INTO "country" ("id", "name") VALUES ('bg', 'bułgarski');
INSERT INTO "country" ("id", "name") VALUES ('ceb', 'cebuano');
INSERT INTO "country" ("id", "name") VALUES ('cel', 'celtycki');
INSERT INTO "country" ("id", "name") VALUES ('ch', 'chamorro');
INSERT INTO "country" ("id", "name") VALUES ('chp', 'chipewyan');
INSERT INTO "country" ("id", "name") VALUES ('zh', 'chiński');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hant', 'chiński (tradycyjny)');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hans', 'chiński (uproszczony)');
INSERT INTO "country" ("id", "name") VALUES ('sit', 'chińsko-tybetański');
INSERT INTO "country" ("id", "name") VALUES ('cho', 'choctaw');
INSERT INTO "country" ("id", "name") VALUES ('hr', 'chorwacki');
INSERT INTO "country" ("id", "name") VALUES ('kho', 'chotański');
INSERT INTO "country" ("id", "name") VALUES ('mus', 'creek');
INSERT INTO "country" ("id", "name") VALUES ('rom', 'cygański');
INSERT INTO "country" ("id", "name") VALUES ('chg', 'czagatajski');
INSERT INTO "country" ("id", "name") VALUES ('cmc', 'czam');
INSERT INTO "country" ("id", "name") VALUES ('ce', 'czeczeński');
INSERT INTO "country" ("id", "name") VALUES ('cs', 'czeski');
INSERT INTO "country" ("id", "name") VALUES ('chb', 'czibcza');
INSERT INTO "country" ("id", "name") VALUES ('chr', 'czirokezki');
INSERT INTO "country" ("id", "name") VALUES ('za', 'czuang');
INSERT INTO "country" ("id", "name") VALUES ('cv', 'czuwaski');
INSERT INTO "country" ("id", "name") VALUES ('day', 'dajak');
INSERT INTO "country" ("id", "name") VALUES ('dak', 'dakota');
INSERT INTO "country" ("id", "name") VALUES ('dar', 'dargwijski');
INSERT INTO "country" ("id", "name") VALUES ('del', 'delaware');
INSERT INTO "country" ("id", "name") VALUES ('din', 'dinka');
INSERT INTO "country" ("id", "name") VALUES ('doi', 'dogri');
INSERT INTO "country" ("id", "name") VALUES ('dgr', 'dogrib');
INSERT INTO "country" ("id", "name") VALUES ('nds', 'dolnosaksoński');
INSERT INTO "country" ("id", "name") VALUES ('dsb', 'dolnołużycki');
INSERT INTO "country" ("id", "name") VALUES ('dra', 'drawidyjski');
INSERT INTO "country" ("id", "name") VALUES ('dua', 'duala');
INSERT INTO "country" ("id", "name") VALUES ('da', 'duński');
INSERT INTO "country" ("id", "name") VALUES ('dyu', 'dyula');
INSERT INTO "country" ("id", "name") VALUES ('dz', 'dzongkha');
INSERT INTO "country" ("id", "name") VALUES ('efi', 'efik');
INSERT INTO "country" ("id", "name") VALUES ('eka', 'ekajuk');
INSERT INTO "country" ("id", "name") VALUES ('elx', 'elamicki');
INSERT INTO "country" ("id", "name") VALUES ('myv', 'erzya');
INSERT INTO "country" ("id", "name") VALUES ('eo', 'esperanto');
INSERT INTO "country" ("id", "name") VALUES ('et', 'estoński');
INSERT INTO "country" ("id", "name") VALUES ('ee', 'ewe');
INSERT INTO "country" ("id", "name") VALUES ('ewo', 'ewondo');
INSERT INTO "country" ("id", "name") VALUES ('fan', 'fang');
INSERT INTO "country" ("id", "name") VALUES ('fat', 'fanti');
INSERT INTO "country" ("id", "name") VALUES ('fo', 'farerski');
INSERT INTO "country" ("id", "name") VALUES ('phn', 'fenicki');
INSERT INTO "country" ("id", "name") VALUES ('fj', 'fidżijski');
INSERT INTO "country" ("id", "name") VALUES ('fil', 'filipino');
INSERT INTO "country" ("id", "name") VALUES ('phi', 'filipiński');
INSERT INTO "country" ("id", "name") VALUES ('fi', 'fiński');
INSERT INTO "country" ("id", "name") VALUES ('nl_BE', 'flamandzki (Belgia)');
INSERT INTO "country" ("id", "name") VALUES ('fon', 'fon');
INSERT INTO "country" ("id", "name") VALUES ('fr', 'francuski');
INSERT INTO "country" ("id", "name") VALUES ('cpf', 'francuski kreolski lub pidżin');
INSERT INTO "country" ("id", "name") VALUES ('fur', 'friulijski');
INSERT INTO "country" ("id", "name") VALUES ('fy', 'fryzyjski');
INSERT INTO "country" ("id", "name") VALUES ('frs', 'fryzyjski wschodni');
INSERT INTO "country" ("id", "name") VALUES ('ff', 'fulani');
INSERT INTO "country" ("id", "name") VALUES ('gaa', 'ga');
INSERT INTO "country" ("id", "name") VALUES ('gl', 'galisyjski');
INSERT INTO "country" ("id", "name") VALUES ('lg', 'ganda');
INSERT INTO "country" ("id", "name") VALUES ('gay', 'gayo');
INSERT INTO "country" ("id", "name") VALUES ('gba', 'gbaya');
INSERT INTO "country" ("id", "name") VALUES ('gem', 'germański');
INSERT INTO "country" ("id", "name") VALUES ('gil', 'gilbertański');
INSERT INTO "country" ("id", "name") VALUES ('got', 'gocki');
INSERT INTO "country" ("id", "name") VALUES ('gon', 'gondi');
INSERT INTO "country" ("id", "name") VALUES ('gor', 'gorontalo');
INSERT INTO "country" ("id", "name") VALUES ('grb', 'grebo');
INSERT INTO "country" ("id", "name") VALUES ('el', 'grecki');
INSERT INTO "country" ("id", "name") VALUES ('kl', 'grenlandzki');
INSERT INTO "country" ("id", "name") VALUES ('ka', 'gruziński');
INSERT INTO "country" ("id", "name") VALUES ('gn', 'guarani');
INSERT INTO "country" ("id", "name") VALUES ('gu', 'gudźaracki');
INSERT INTO "country" ("id", "name") VALUES ('gez', 'gyyz');
INSERT INTO "country" ("id", "name") VALUES ('hsb', 'górnołużycki');
INSERT INTO "country" ("id", "name") VALUES ('hai', 'haida');
INSERT INTO "country" ("id", "name") VALUES ('ht', 'haitański');
INSERT INTO "country" ("id", "name") VALUES ('ha', 'hausa');
INSERT INTO "country" ("id", "name") VALUES ('haw', 'hawajski');
INSERT INTO "country" ("id", "name") VALUES ('he', 'hebrajski');
INSERT INTO "country" ("id", "name") VALUES ('hz', 'herero');
INSERT INTO "country" ("id", "name") VALUES ('hit', 'hetycki');
INSERT INTO "country" ("id", "name") VALUES ('hil', 'hiligajnon');
INSERT INTO "country" ("id", "name") VALUES ('him', 'himachali');
INSERT INTO "country" ("id", "name") VALUES ('hi', 'hindi');
INSERT INTO "country" ("id", "name") VALUES ('ho', 'hiri motu');
INSERT INTO "country" ("id", "name") VALUES ('es', 'hiszpański');
INSERT INTO "country" ("id", "name") VALUES ('es_419', 'hiszpański (Ameryka Łacińska)');
INSERT INTO "country" ("id", "name") VALUES ('hmn', 'hmongijski');
INSERT INTO "country" ("id", "name") VALUES ('hup', 'hupa');
INSERT INTO "country" ("id", "name") VALUES ('iba', 'ibanag');
INSERT INTO "country" ("id", "name") VALUES ('io', 'ido');
INSERT INTO "country" ("id", "name") VALUES ('ig', 'igbo');
INSERT INTO "country" ("id", "name") VALUES ('ijo', 'ijo');
INSERT INTO "country" ("id", "name") VALUES ('ilo', 'ilokano');
INSERT INTO "country" ("id", "name") VALUES ('inc', 'indoaryjski');
INSERT INTO "country" ("id", "name") VALUES ('ine', 'indoeuropejski');
INSERT INTO "country" ("id", "name") VALUES ('id', 'indonezyjski');
INSERT INTO "country" ("id", "name") VALUES ('inh', 'inguski');
INSERT INTO "country" ("id", "name") VALUES ('mis', 'inny język');
INSERT INTO "country" ("id", "name") VALUES ('ia', 'interlingua');
INSERT INTO "country" ("id", "name") VALUES ('ie', 'interlingue');
INSERT INTO "country" ("id", "name") VALUES ('iu', 'inuktitut');
INSERT INTO "country" ("id", "name") VALUES ('ik', 'inupiak');
INSERT INTO "country" ("id", "name") VALUES ('ira', 'irański');
INSERT INTO "country" ("id", "name") VALUES ('ga', 'irlandzki');
INSERT INTO "country" ("id", "name") VALUES ('iro', 'irokeski');
INSERT INTO "country" ("id", "name") VALUES ('is', 'islandzki');
INSERT INTO "country" ("id", "name") VALUES ('sah', 'jakucki');
INSERT INTO "country" ("id", "name") VALUES ('ja', 'japoński');
INSERT INTO "country" ("id", "name") VALUES ('yap', 'japski');
INSERT INTO "country" ("id", "name") VALUES ('jv', 'jawajski');
INSERT INTO "country" ("id", "name") VALUES ('yi', 'jidysz');
INSERT INTO "country" ("id", "name") VALUES ('kaj', 'jju');
INSERT INTO "country" ("id", "name") VALUES ('yo', 'joruba');
INSERT INTO "country" ("id", "name") VALUES ('jrb', 'judeoarabski');
INSERT INTO "country" ("id", "name") VALUES ('jpr', 'judeoperski');
INSERT INTO "country" ("id", "name") VALUES ('ypk', 'jupik');
INSERT INTO "country" ("id", "name") VALUES ('apa', 'język Apaczów');
INSERT INTO "country" ("id", "name") VALUES ('ath', 'język Atapasków');
INSERT INTO "country" ("id", "name") VALUES ('chy', 'język Czejenów');
INSERT INTO "country" ("id", "name") VALUES ('sai', 'język Indian południowoamerykańskich');
INSERT INTO "country" ("id", "name") VALUES ('nai', 'język Indian północnoamerykańskich');
INSERT INTO "country" ("id", "name") VALUES ('cai', 'język Indian środkowoamerykańskich');
INSERT INTO "country" ("id", "name") VALUES ('myn', 'język Majów');
INSERT INTO "country" ("id", "name") VALUES ('aus', 'język australijski');
INSERT INTO "country" ("id", "name") VALUES ('bai', 'język bamileke');
INSERT INTO "country" ("id", "name") VALUES ('bad', 'język banda');
INSERT INTO "country" ("id", "name") VALUES ('root', 'język rdzenny');
INSERT INTO "country" ("id", "name") VALUES ('alg', 'języki algonkin');
INSERT INTO "country" ("id", "name") VALUES ('kbd', 'kabardyjski');
INSERT INTO "country" ("id", "name") VALUES ('kab', 'kabylski');
INSERT INTO "country" ("id", "name") VALUES ('kac', 'kaczin');
INSERT INTO "country" ("id", "name") VALUES ('cad', 'kaddo');
INSERT INTO "country" ("id", "name") VALUES ('kam', 'kamba');
INSERT INTO "country" ("id", "name") VALUES ('en_CA', 'kanadyjski angielski');
INSERT INTO "country" ("id", "name") VALUES ('fr_CA', 'kanadyjski francuski');
INSERT INTO "country" ("id", "name") VALUES ('kn', 'kannada');
INSERT INTO "country" ("id", "name") VALUES ('kr', 'kanuri');
INSERT INTO "country" ("id", "name") VALUES ('krc', 'karaczajsko-bałkarski');
INSERT INTO "country" ("id", "name") VALUES ('kaa', 'karakałpacki');
INSERT INTO "country" ("id", "name") VALUES ('krl', 'karelski');
INSERT INTO "country" ("id", "name") VALUES ('kar', 'kareński');
INSERT INTO "country" ("id", "name") VALUES ('car', 'karibi');
INSERT INTO "country" ("id", "name") VALUES ('ks', 'kaszmirski');
INSERT INTO "country" ("id", "name") VALUES ('csb', 'kaszubski');
INSERT INTO "country" ("id", "name") VALUES ('ca', 'kataloński');
INSERT INTO "country" ("id", "name") VALUES ('cau', 'kaukaski');
INSERT INTO "country" ("id", "name") VALUES ('kaw', 'kawi');
INSERT INTO "country" ("id", "name") VALUES ('kk', 'kazachski');
INSERT INTO "country" ("id", "name") VALUES ('xal', 'kałmucki');
INSERT INTO "country" ("id", "name") VALUES ('qu', 'keczua');
INSERT INTO "country" ("id", "name") VALUES ('kha', 'khasi');
INSERT INTO "country" ("id", "name") VALUES ('km', 'khmerski');
INSERT INTO "country" ("id", "name") VALUES ('khi', 'khoisan');
INSERT INTO "country" ("id", "name") VALUES ('xh', 'khosa');
INSERT INTO "country" ("id", "name") VALUES ('ki', 'kikuju');
INSERT INTO "country" ("id", "name") VALUES ('kmb', 'kimbundu');
INSERT INTO "country" ("id", "name") VALUES ('rw', 'kinya-ruanda');
INSERT INTO "country" ("id", "name") VALUES ('ky', 'kirgiski');
INSERT INTO "country" ("id", "name") VALUES ('tlh', 'klingoński');
INSERT INTO "country" ("id", "name") VALUES ('kv', 'komi');
INSERT INTO "country" ("id", "name") VALUES ('kg', 'kongo');
INSERT INTO "country" ("id", "name") VALUES ('kok', 'konkani');
INSERT INTO "country" ("id", "name") VALUES ('cop', 'koptyjski');
INSERT INTO "country" ("id", "name") VALUES ('ko', 'koreański');
INSERT INTO "country" ("id", "name") VALUES ('kw', 'kornijski');
INSERT INTO "country" ("id", "name") VALUES ('kfo', 'koro');
INSERT INTO "country" ("id", "name") VALUES ('co', 'korsykański');
INSERT INTO "country" ("id", "name") VALUES ('kos', 'kosrae');
INSERT INTO "country" ("id", "name") VALUES ('kpe', 'kpelle');
INSERT INTO "country" ("id", "name") VALUES ('crp', 'kreolski lub pidżin');
INSERT INTO "country" ("id", "name") VALUES ('cr', 'kri');
INSERT INTO "country" ("id", "name") VALUES ('kro', 'kru');
INSERT INTO "country" ("id", "name") VALUES ('crh', 'krymski turecki');
INSERT INTO "country" ("id", "name") VALUES ('kum', 'kumycki');
INSERT INTO "country" ("id", "name") VALUES ('ku', 'kurdyjski');
INSERT INTO "country" ("id", "name") VALUES ('kru', 'kurukh');
INSERT INTO "country" ("id", "name") VALUES ('cus', 'kuszycki');
INSERT INTO "country" ("id", "name") VALUES ('kut', 'kutenai');
INSERT INTO "country" ("id", "name") VALUES ('kj', 'kwanyama');
INSERT INTO "country" ("id", "name") VALUES ('lad', 'ladyński');
INSERT INTO "country" ("id", "name") VALUES ('lah', 'lahnda');
INSERT INTO "country" ("id", "name") VALUES ('lam', 'lamba');
INSERT INTO "country" ("id", "name") VALUES ('lo', 'laotański');
INSERT INTO "country" ("id", "name") VALUES ('smi', 'lapoński');
INSERT INTO "country" ("id", "name") VALUES ('smn', 'lapoński Inari');
INSERT INTO "country" ("id", "name") VALUES ('smj', 'lapoński Lule');
INSERT INTO "country" ("id", "name") VALUES ('sms', 'lapoński Skolt');
INSERT INTO "country" ("id", "name") VALUES ('sma', 'lapoński południowy');
INSERT INTO "country" ("id", "name") VALUES ('se', 'lapoński północny');
INSERT INTO "country" ("id", "name") VALUES ('lez', 'lezgijski');
INSERT INTO "country" ("id", "name") VALUES ('li', 'limburgijski');
INSERT INTO "country" ("id", "name") VALUES ('ln', 'lingala');
INSERT INTO "country" ("id", "name") VALUES ('lt', 'litewski');
INSERT INTO "country" ("id", "name") VALUES ('jbo', 'lojban');
INSERT INTO "country" ("id", "name") VALUES ('loz', 'lozi');
INSERT INTO "country" ("id", "name") VALUES ('lu', 'luba-katanga');
INSERT INTO "country" ("id", "name") VALUES ('lua', 'luba-lulua');
INSERT INTO "country" ("id", "name") VALUES ('lui', 'luiseno');
INSERT INTO "country" ("id", "name") VALUES ('lb', 'luksemburski');
INSERT INTO "country" ("id", "name") VALUES ('lun', 'lunda');
INSERT INTO "country" ("id", "name") VALUES ('luo', 'luo');
INSERT INTO "country" ("id", "name") VALUES ('lus', 'lushai');
INSERT INTO "country" ("id", "name") VALUES ('mk', 'macedoński');
INSERT INTO "country" ("id", "name") VALUES ('mad', 'madurajski');
INSERT INTO "country" ("id", "name") VALUES ('mag', 'magahi');
INSERT INTO "country" ("id", "name") VALUES ('mai', 'maithili');
INSERT INTO "country" ("id", "name") VALUES ('mak', 'makasar');
INSERT INTO "country" ("id", "name") VALUES ('ml', 'malajalam');
INSERT INTO "country" ("id", "name") VALUES ('ms', 'malajski');
INSERT INTO "country" ("id", "name") VALUES ('dv', 'malediwski');
INSERT INTO "country" ("id", "name") VALUES ('mg', 'malgaski');
INSERT INTO "country" ("id", "name") VALUES ('mt', 'maltański');
INSERT INTO "country" ("id", "name") VALUES ('mnc', 'manchu');
INSERT INTO "country" ("id", "name") VALUES ('mdr', 'mandar');
INSERT INTO "country" ("id", "name") VALUES ('man', 'mandingo');
INSERT INTO "country" ("id", "name") VALUES ('mni', 'manipuryjski');
INSERT INTO "country" ("id", "name") VALUES ('mno', 'manobo');
INSERT INTO "country" ("id", "name") VALUES ('gv', 'manx');
INSERT INTO "country" ("id", "name") VALUES ('mi', 'maoryjski');
INSERT INTO "country" ("id", "name") VALUES ('mr', 'marathi');
INSERT INTO "country" ("id", "name") VALUES ('mh', 'marshall');
INSERT INTO "country" ("id", "name") VALUES ('mwr', 'marwari');
INSERT INTO "country" ("id", "name") VALUES ('chm', 'maryjski');
INSERT INTO "country" ("id", "name") VALUES ('mas', 'masajski');
INSERT INTO "country" ("id", "name") VALUES ('men', 'mende');
INSERT INTO "country" ("id", "name") VALUES ('mic', 'micmac');
INSERT INTO "country" ("id", "name") VALUES ('sgn', 'migowy');
INSERT INTO "country" ("id", "name") VALUES ('min', 'minangkabu');
INSERT INTO "country" ("id", "name") VALUES ('mwl', 'mirandese');
INSERT INTO "country" ("id", "name") VALUES ('moh', 'mohawk');
INSERT INTO "country" ("id", "name") VALUES ('mdf', 'moksha');
INSERT INTO "country" ("id", "name") VALUES ('mkh', 'mon-khmer');
INSERT INTO "country" ("id", "name") VALUES ('lol', 'mongo');
INSERT INTO "country" ("id", "name") VALUES ('mn', 'mongolski');
INSERT INTO "country" ("id", "name") VALUES ('mos', 'mossi');
INSERT INTO "country" ("id", "name") VALUES ('mo', 'mołdawski');
INSERT INTO "country" ("id", "name") VALUES ('mun', 'mundajski');
INSERT INTO "country" ("id", "name") VALUES ('nah', 'nahuatl');
INSERT INTO "country" ("id", "name") VALUES ('na', 'nauru');
INSERT INTO "country" ("id", "name") VALUES ('nv', 'nawaho');
INSERT INTO "country" ("id", "name") VALUES ('nr', 'ndebele południowy');
INSERT INTO "country" ("id", "name") VALUES ('nd', 'ndebele północny');
INSERT INTO "country" ("id", "name") VALUES ('ng', 'ndonga');
INSERT INTO "country" ("id", "name") VALUES ('nap', 'neapolitański');
INSERT INTO "country" ("id", "name") VALUES ('ne', 'nepalski');
INSERT INTO "country" ("id", "name") VALUES ('new', 'newarski');
INSERT INTO "country" ("id", "name") VALUES ('nwc', 'newarski klasyczny');
INSERT INTO "country" ("id", "name") VALUES ('nym', 'niamwezi');
INSERT INTO "country" ("id", "name") VALUES ('nia', 'nias');
INSERT INTO "country" ("id", "name") VALUES ('nl', 'niderlandzki');
INSERT INTO "country" ("id", "name") VALUES ('de', 'niemiecki');
INSERT INTO "country" ("id", "name") VALUES ('und', 'nieznany lub niepoprawny język');
INSERT INTO "country" ("id", "name") VALUES ('nic', 'nigrokordofański');
INSERT INTO "country" ("id", "name") VALUES ('ssa', 'nilosaharyjski');
INSERT INTO "country" ("id", "name") VALUES ('niu', 'niue');
INSERT INTO "country" ("id", "name") VALUES ('ny', 'njandża');
INSERT INTO "country" ("id", "name") VALUES ('nog', 'nogajski');
INSERT INTO "country" ("id", "name") VALUES ('no', 'norweski');
INSERT INTO "country" ("id", "name") VALUES ('nb', 'norweski Bokmål');
INSERT INTO "country" ("id", "name") VALUES ('nn', 'norweski Nynorsk');
INSERT INTO "country" ("id", "name") VALUES ('nub', 'nubijski');
INSERT INTO "country" ("id", "name") VALUES ('nyn', 'nyankole');
INSERT INTO "country" ("id", "name") VALUES ('nyo', 'nyoro');
INSERT INTO "country" ("id", "name") VALUES ('nzi', 'nzema');
INSERT INTO "country" ("id", "name") VALUES ('nqo', 'n’ko');
INSERT INTO "country" ("id", "name") VALUES ('oj', 'odżibwa');
INSERT INTO "country" ("id", "name") VALUES ('or', 'orija');
INSERT INTO "country" ("id", "name") VALUES ('hy', 'ormiański');
INSERT INTO "country" ("id", "name") VALUES ('om', 'oromski');
INSERT INTO "country" ("id", "name") VALUES ('osa', 'osage');
INSERT INTO "country" ("id", "name") VALUES ('os', 'osetyjski');
INSERT INTO "country" ("id", "name") VALUES ('ota', 'osmańsko-turecki');
INSERT INTO "country" ("id", "name") VALUES ('oto', 'otomi');
INSERT INTO "country" ("id", "name") VALUES ('pal', 'pahlavi');
INSERT INTO "country" ("id", "name") VALUES ('pau', 'palau');
INSERT INTO "country" ("id", "name") VALUES ('pi', 'palijski');
INSERT INTO "country" ("id", "name") VALUES ('pam', 'pampango');
INSERT INTO "country" ("id", "name") VALUES ('pag', 'pangasino');
INSERT INTO "country" ("id", "name") VALUES ('pap', 'papiamento');
INSERT INTO "country" ("id", "name") VALUES ('paa', 'papuaski');
INSERT INTO "country" ("id", "name") VALUES ('ps', 'paszto');
INSERT INTO "country" ("id", "name") VALUES ('pa', 'pendżabski');
INSERT INTO "country" ("id", "name") VALUES ('fa', 'perski');
INSERT INTO "country" ("id", "name") VALUES ('pl', 'polski');
INSERT INTO "country" ("id", "name") VALUES ('pon', 'ponpejski');
INSERT INTO "country" ("id", "name") VALUES ('pt', 'portugalski');
INSERT INTO "country" ("id", "name") VALUES ('cpp', 'portugalski kreolski lub pidżin');
INSERT INTO "country" ("id", "name") VALUES ('alt', 'południowoałtajski');
INSERT INTO "country" ("id", "name") VALUES ('pra', 'prakryty');
INSERT INTO "country" ("id", "name") VALUES ('oc', 'prowansalski');
INSERT INTO "country" ("id", "name") VALUES ('frr', 'północnofryzyjski');
INSERT INTO "country" ("id", "name") VALUES ('raj', 'radźasthani');
INSERT INTO "country" ("id", "name") VALUES ('rap', 'rapanui');
INSERT INTO "country" ("id", "name") VALUES ('rar', 'rarotonga');
INSERT INTO "country" ("id", "name") VALUES ('rm', 'retoromański');
INSERT INTO "country" ("id", "name") VALUES ('roa', 'romański');
INSERT INTO "country" ("id", "name") VALUES ('ru', 'rosyjski');
INSERT INTO "country" ("id", "name") VALUES ('ro', 'rumuński');
INSERT INTO "country" ("id", "name") VALUES ('rn', 'rundi');
INSERT INTO "country" ("id", "name") VALUES ('sal', 'salisz');
INSERT INTO "country" ("id", "name") VALUES ('sam', 'samarytański aramejski');
INSERT INTO "country" ("id", "name") VALUES ('sm', 'samoański');
INSERT INTO "country" ("id", "name") VALUES ('sad', 'sandawe');
INSERT INTO "country" ("id", "name") VALUES ('sg', 'sango');
INSERT INTO "country" ("id", "name") VALUES ('sa', 'sanskryt');
INSERT INTO "country" ("id", "name") VALUES ('sat', 'santali');
INSERT INTO "country" ("id", "name") VALUES ('sc', 'sardyński');
INSERT INTO "country" ("id", "name") VALUES ('sas', 'sasak');
INSERT INTO "country" ("id", "name") VALUES ('sel', 'selkupski');
INSERT INTO "country" ("id", "name") VALUES ('sem', 'semicki');
INSERT INTO "country" ("id", "name") VALUES ('sr', 'serbski');
INSERT INTO "country" ("id", "name") VALUES ('sh', 'serbsko-chorwacki');
INSERT INTO "country" ("id", "name") VALUES ('srr', 'serer');
INSERT INTO "country" ("id", "name") VALUES ('tn', 'setswana');
INSERT INTO "country" ("id", "name") VALUES ('shn', 'shan');
INSERT INTO "country" ("id", "name") VALUES ('sid', 'sidamo');
INSERT INTO "country" ("id", "name") VALUES ('bla', 'siksika');
INSERT INTO "country" ("id", "name") VALUES ('sd', 'sindhi');
INSERT INTO "country" ("id", "name") VALUES ('sio', 'siouański');
INSERT INTO "country" ("id", "name") VALUES ('ss', 'siswati');
INSERT INTO "country" ("id", "name") VALUES ('den', 'slave');
INSERT INTO "country" ("id", "name") VALUES ('sog', 'sogdyjski');
INSERT INTO "country" ("id", "name") VALUES ('so', 'somalijski');
INSERT INTO "country" ("id", "name") VALUES ('son', 'songhaj');
INSERT INTO "country" ("id", "name") VALUES ('snk', 'soninke');
INSERT INTO "country" ("id", "name") VALUES ('st', 'sotho południowy');
INSERT INTO "country" ("id", "name") VALUES ('nso', 'sotho północny');
INSERT INTO "country" ("id", "name") VALUES ('srn', 'sranan tongo');
INSERT INTO "country" ("id", "name") VALUES ('cu', 'staro-cerkiewno-słowiański');
INSERT INTO "country" ("id", "name") VALUES ('goh', 'staro-wysoko-niemiecki');
INSERT INTO "country" ("id", "name") VALUES ('ang', 'staroangielski');
INSERT INTO "country" ("id", "name") VALUES ('fro', 'starofrancuski');
INSERT INTO "country" ("id", "name") VALUES ('grc', 'starogrecki');
INSERT INTO "country" ("id", "name") VALUES ('sga', 'staroirlandzki');
INSERT INTO "country" ("id", "name") VALUES ('non', 'staronordyjski');
INSERT INTO "country" ("id", "name") VALUES ('peo', 'staroperski');
INSERT INTO "country" ("id", "name") VALUES ('pro', 'staroprowansalski');
INSERT INTO "country" ("id", "name") VALUES ('egy', 'starożytny egipski');
INSERT INTO "country" ("id", "name") VALUES ('sw', 'suahili');
INSERT INTO "country" ("id", "name") VALUES ('suk', 'sukuma');
INSERT INTO "country" ("id", "name") VALUES ('sux', 'sumeryjski');
INSERT INTO "country" ("id", "name") VALUES ('su', 'sundajski');
INSERT INTO "country" ("id", "name") VALUES ('sus', 'susu');
INSERT INTO "country" ("id", "name") VALUES ('scn', 'sycylijski');
INSERT INTO "country" ("id", "name") VALUES ('ii', 'syczuański');
INSERT INTO "country" ("id", "name") VALUES ('si', 'syngaleski');
INSERT INTO "country" ("id", "name") VALUES ('syc', 'syriacki');
INSERT INTO "country" ("id", "name") VALUES ('syr', 'syryjski');
INSERT INTO "country" ("id", "name") VALUES ('sco', 'szkocki');
INSERT INTO "country" ("id", "name") VALUES ('gd', 'szkocki gaelicki');
INSERT INTO "country" ("id", "name") VALUES ('sn', 'szona');
INSERT INTO "country" ("id", "name") VALUES ('art', 'sztuczny');
INSERT INTO "country" ("id", "name") VALUES ('gsw', 'szwajcarski niemiecki');
INSERT INTO "country" ("id", "name") VALUES ('sv', 'szwedzki');
INSERT INTO "country" ("id", "name") VALUES ('sk', 'słowacki');
INSERT INTO "country" ("id", "name") VALUES ('sl', 'słoweński');
INSERT INTO "country" ("id", "name") VALUES ('sla', 'słowiański');
INSERT INTO "country" ("id", "name") VALUES ('tg', 'tadżycki');
INSERT INTO "country" ("id", "name") VALUES ('tl', 'tagalski');
INSERT INTO "country" ("id", "name") VALUES ('ty', 'tahitański');
INSERT INTO "country" ("id", "name") VALUES ('tai', 'tai');
INSERT INTO "country" ("id", "name") VALUES ('th', 'tajski');
INSERT INTO "country" ("id", "name") VALUES ('tmh', 'tamaszek');
INSERT INTO "country" ("id", "name") VALUES ('ta', 'tamilski');
INSERT INTO "country" ("id", "name") VALUES ('tt', 'tatarski');
INSERT INTO "country" ("id", "name") VALUES ('te', 'telugu');
INSERT INTO "country" ("id", "name") VALUES ('tem', 'temne');
INSERT INTO "country" ("id", "name") VALUES ('ter', 'tereno');
INSERT INTO "country" ("id", "name") VALUES ('tet', 'tetum');
INSERT INTO "country" ("id", "name") VALUES ('tig', 'tigre');
INSERT INTO "country" ("id", "name") VALUES ('ti', 'tigrinia');
INSERT INTO "country" ("id", "name") VALUES ('tiv', 'tiw');
INSERT INTO "country" ("id", "name") VALUES ('tli', 'tlingit');
INSERT INTO "country" ("id", "name") VALUES ('tpi', 'tok pisin');
INSERT INTO "country" ("id", "name") VALUES ('tkl', 'tokelau');
INSERT INTO "country" ("id", "name") VALUES ('to', 'tonga');
INSERT INTO "country" ("id", "name") VALUES ('tog', 'tonga (Niasa)');
INSERT INTO "country" ("id", "name") VALUES ('chk', 'truk');
INSERT INTO "country" ("id", "name") VALUES ('tsi', 'tsimshian');
INSERT INTO "country" ("id", "name") VALUES ('ts', 'tsonga');
INSERT INTO "country" ("id", "name") VALUES ('tum', 'tumbuka');
INSERT INTO "country" ("id", "name") VALUES ('tup', 'tupi');
INSERT INTO "country" ("id", "name") VALUES ('tr', 'turecki');
INSERT INTO "country" ("id", "name") VALUES ('tk', 'turkmeński');
INSERT INTO "country" ("id", "name") VALUES ('tvl', 'tuvalu');
INSERT INTO "country" ("id", "name") VALUES ('tyv', 'tuwiński');
INSERT INTO "country" ("id", "name") VALUES ('tw', 'twi');
INSERT INTO "country" ("id", "name") VALUES ('kcg', 'tyap');
INSERT INTO "country" ("id", "name") VALUES ('bo', 'tybetański');
INSERT INTO "country" ("id", "name") VALUES ('udm', 'udmurcki');
INSERT INTO "country" ("id", "name") VALUES ('uga', 'ugarycki');
INSERT INTO "country" ("id", "name") VALUES ('fiu', 'ugrofiński');
INSERT INTO "country" ("id", "name") VALUES ('ug', 'ujgurski');
INSERT INTO "country" ("id", "name") VALUES ('uk', 'ukraiński');
INSERT INTO "country" ("id", "name") VALUES ('umb', 'umbundu');
INSERT INTO "country" ("id", "name") VALUES ('ur', 'urdu');
INSERT INTO "country" ("id", "name") VALUES ('uz', 'uzbecki');
INSERT INTO "country" ("id", "name") VALUES ('ve', 'venda');
INSERT INTO "country" ("id", "name") VALUES ('vo', 'volapuk');
INSERT INTO "country" ("id", "name") VALUES ('vai', 'wai');
INSERT INTO "country" ("id", "name") VALUES ('wak', 'wakasz');
INSERT INTO "country" ("id", "name") VALUES ('wal', 'walamo');
INSERT INTO "country" ("id", "name") VALUES ('cy', 'walijski');
INSERT INTO "country" ("id", "name") VALUES ('wa', 'waloński');
INSERT INTO "country" ("id", "name") VALUES ('war', 'waraj');
INSERT INTO "country" ("id", "name") VALUES ('was', 'washo');
INSERT INTO "country" ("id", "name") VALUES ('mul', 'wiele języków');
INSERT INTO "country" ("id", "name") VALUES ('vi', 'wietnamski');
INSERT INTO "country" ("id", "name") VALUES ('wo', 'wolof');
INSERT INTO "country" ("id", "name") VALUES ('vot', 'wotiacki');
INSERT INTO "country" ("id", "name") VALUES ('de_CH', 'wysokoniemiecki (Szwajcaria)');
INSERT INTO "country" ("id", "name") VALUES ('hu', 'węgierski');
INSERT INTO "country" ("id", "name") VALUES ('it', 'włoski');
INSERT INTO "country" ("id", "name") VALUES ('yao', 'yao');
INSERT INTO "country" ("id", "name") VALUES ('zap', 'zapotecki');
INSERT INTO "country" ("id", "name") VALUES ('zza', 'zazaki');
INSERT INTO "country" ("id", "name") VALUES ('zen', 'zenaga');
INSERT INTO "country" ("id", "name") VALUES ('zu', 'zulu');
INSERT INTO "country" ("id", "name") VALUES ('zun', 'zuni');
INSERT INTO "country" ("id", "name") VALUES ('la', 'łaciński');
INSERT INTO "country" ("id", "name") VALUES ('lv', 'łotewski');
INSERT INTO "country" ("id", "name") VALUES ('wen', 'łużycki');
INSERT INTO "country" ("id", "name") VALUES ('gmh', 'średnio-wysoko-niemiecki');
INSERT INTO "country" ("id", "name") VALUES ('enm', 'średnioangielski');
INSERT INTO "country" ("id", "name") VALUES ('frm', 'średniofrancuski');
INSERT INTO "country" ("id", "name") VALUES ('mga', 'średnioirlandzki');
INSERT INTO "country" ("id", "name") VALUES ('dum', 'średniowieczny niderlandzki');
INSERT INTO "country" ("id", "name") VALUES ('chn', 'żargon Chinook');
