CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('ab', 'abchasian');
INSERT INTO [country] ([id], [name]) VALUES ('akk', 'accadic');
INSERT INTO [country] ([id], [name]) VALUES ('ace', 'aceh');
INSERT INTO [country] ([id], [name]) VALUES ('ach', 'acoli');
INSERT INTO [country] ([id], [name]) VALUES ('ady', 'adygai');
INSERT INTO [country] ([id], [name]) VALUES ('aa', 'afar');
INSERT INTO [country] ([id], [name]) VALUES ('afh', 'afrihili');
INSERT INTO [country] ([id], [name]) VALUES ('af', 'afrikaans');
INSERT INTO [country] ([id], [name]) VALUES ('ain', 'ainu');
INSERT INTO [country] ([id], [name]) VALUES ('ak', 'akan');
INSERT INTO [country] ([id], [name]) VALUES ('sq', 'albanais');
INSERT INTO [country] ([id], [name]) VALUES ('ale', 'aleutic');
INSERT INTO [country] ([id], [name]) VALUES ('alt', 'altaic dal sid');
INSERT INTO [country] ([id], [name]) VALUES ('am', 'amaric');
INSERT INTO [country] ([id], [name]) VALUES ('ada', 'andangme');
INSERT INTO [country] ([id], [name]) VALUES ('anp', 'angika');
INSERT INTO [country] ([id], [name]) VALUES ('ar', 'arab');
INSERT INTO [country] ([id], [name]) VALUES ('an', 'aragonais');
INSERT INTO [country] ([id], [name]) VALUES ('arc', 'arameic');
INSERT INTO [country] ([id], [name]) VALUES ('sam', 'arameic samaritan');
INSERT INTO [country] ([id], [name]) VALUES ('arp', 'arapaho');
INSERT INTO [country] ([id], [name]) VALUES ('arn', 'araucanic');
INSERT INTO [country] ([id], [name]) VALUES ('arw', 'arawak');
INSERT INTO [country] ([id], [name]) VALUES ('hy', 'armen');
INSERT INTO [country] ([id], [name]) VALUES ('rup', 'aromunic');
INSERT INTO [country] ([id], [name]) VALUES ('az', 'aserbeidschanic');
INSERT INTO [country] ([id], [name]) VALUES ('as', 'assami');
INSERT INTO [country] ([id], [name]) VALUES ('ast', 'asturian');
INSERT INTO [country] ([id], [name]) VALUES ('cch', 'atsam');
INSERT INTO [country] ([id], [name]) VALUES ('map', 'austronesian');
INSERT INTO [country] ([id], [name]) VALUES ('hsb', 'aut sorb');
INSERT INTO [country] ([id], [name]) VALUES ('av', 'avaric');
INSERT INTO [country] ([id], [name]) VALUES ('ae', 'avestic');
INSERT INTO [country] ([id], [name]) VALUES ('awa', 'awadhi');
INSERT INTO [country] ([id], [name]) VALUES ('ay', 'aymara');
INSERT INTO [country] ([id], [name]) VALUES ('ban', 'balinais');
INSERT INTO [country] ([id], [name]) VALUES ('bm', 'bambara');
INSERT INTO [country] ([id], [name]) VALUES ('bad', 'banda');
INSERT INTO [country] ([id], [name]) VALUES ('bnt', 'bantu');
INSERT INTO [country] ([id], [name]) VALUES ('bas', 'basaa');
INSERT INTO [country] ([id], [name]) VALUES ('eu', 'basc');
INSERT INTO [country] ([id], [name]) VALUES ('ba', 'baschkir');
INSERT INTO [country] ([id], [name]) VALUES ('dsb', 'bass sorb');
INSERT INTO [country] ([id], [name]) VALUES ('nds', 'bass tudestg');
INSERT INTO [country] ([id], [name]) VALUES ('btk', 'batak');
INSERT INTO [country] ([id], [name]) VALUES ('bej', 'bedscha');
INSERT INTO [country] ([id], [name]) VALUES ('bal', 'belutschi');
INSERT INTO [country] ([id], [name]) VALUES ('bem', 'bemba');
INSERT INTO [country] ([id], [name]) VALUES ('bn', 'bengal');
INSERT INTO [country] ([id], [name]) VALUES ('ber', 'berb');
INSERT INTO [country] ([id], [name]) VALUES ('bho', 'bhojpuri');
INSERT INTO [country] ([id], [name]) VALUES ('be', 'bieloruss');
INSERT INTO [country] ([id], [name]) VALUES ('bh', 'bihari');
INSERT INTO [country] ([id], [name]) VALUES ('bik', 'bikol');
INSERT INTO [country] ([id], [name]) VALUES ('bin', 'bini');
INSERT INTO [country] ([id], [name]) VALUES ('my', 'birman');
INSERT INTO [country] ([id], [name]) VALUES ('bi', 'bislama');
INSERT INTO [country] ([id], [name]) VALUES ('byn', 'blin');
INSERT INTO [country] ([id], [name]) VALUES ('bs', 'bosniac');
INSERT INTO [country] ([id], [name]) VALUES ('bra', 'braj');
INSERT INTO [country] ([id], [name]) VALUES ('br', 'breton');
INSERT INTO [country] ([id], [name]) VALUES ('bug', 'bugi');
INSERT INTO [country] ([id], [name]) VALUES ('bg', 'bulgar');
INSERT INTO [country] ([id], [name]) VALUES ('bua', 'buriat');
INSERT INTO [country] ([id], [name]) VALUES ('cad', 'caddo');
INSERT INTO [country] ([id], [name]) VALUES ('km', 'cambodschan');
INSERT INTO [country] ([id], [name]) VALUES ('krl', 'carelian');
INSERT INTO [country] ([id], [name]) VALUES ('car', 'caribic');
INSERT INTO [country] ([id], [name]) VALUES ('kk', 'casac');
INSERT INTO [country] ([id], [name]) VALUES ('ca', 'catalan');
INSERT INTO [country] ([id], [name]) VALUES ('ceb', 'cebuano');
INSERT INTO [country] ([id], [name]) VALUES ('ch', 'chamorro');
INSERT INTO [country] ([id], [name]) VALUES ('chr', 'cherokee');
INSERT INTO [country] ([id], [name]) VALUES ('chy', 'cheyenne');
INSERT INTO [country] ([id], [name]) VALUES ('chb', 'chibcha');
INSERT INTO [country] ([id], [name]) VALUES ('zh', 'chinais');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hans', 'chinais simplifitgà');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hant', 'chinais tradiziunal');
INSERT INTO [country] ([id], [name]) VALUES ('chp', 'chipewyan');
INSERT INTO [country] ([id], [name]) VALUES ('cho', 'choctaw');
INSERT INTO [country] ([id], [name]) VALUES ('chk', 'chuukais');
INSERT INTO [country] ([id], [name]) VALUES ('cop', 'coptic');
INSERT INTO [country] ([id], [name]) VALUES ('ko', 'corean');
INSERT INTO [country] ([id], [name]) VALUES ('kw', 'cornic');
INSERT INTO [country] ([id], [name]) VALUES ('co', 'cors');
INSERT INTO [country] ([id], [name]) VALUES ('cr', 'cree');
INSERT INTO [country] ([id], [name]) VALUES ('mus', 'creek');
INSERT INTO [country] ([id], [name]) VALUES ('cpf', 'creol u pidgin che sa basan sin il franzos');
INSERT INTO [country] ([id], [name]) VALUES ('cpp', 'creol u pidgin che sa basan sin il portugais');
INSERT INTO [country] ([id], [name]) VALUES ('cpe', 'creol u pidgin che sa basan sin l''englais');
INSERT INTO [country] ([id], [name]) VALUES ('crp', 'creolic u pidgin');
INSERT INTO [country] ([id], [name]) VALUES ('hr', 'croat');
INSERT INTO [country] ([id], [name]) VALUES ('ku', 'curd');
INSERT INTO [country] ([id], [name]) VALUES ('dak', 'dakota');
INSERT INTO [country] ([id], [name]) VALUES ('da', 'danais');
INSERT INTO [country] ([id], [name]) VALUES ('dar', 'dargwa');
INSERT INTO [country] ([id], [name]) VALUES ('day', 'dayak');
INSERT INTO [country] ([id], [name]) VALUES ('del', 'delaware');
INSERT INTO [country] ([id], [name]) VALUES ('din', 'dinka');
INSERT INTO [country] ([id], [name]) VALUES ('dyu', 'diula');
INSERT INTO [country] ([id], [name]) VALUES ('mis', 'diversas linguas');
INSERT INTO [country] ([id], [name]) VALUES ('doi', 'dogri');
INSERT INTO [country] ([id], [name]) VALUES ('dgr', 'dogrib');
INSERT INTO [country] ([id], [name]) VALUES ('dua', 'duala');
INSERT INTO [country] ([id], [name]) VALUES ('dz', 'dzongkha');
INSERT INTO [country] ([id], [name]) VALUES ('he', 'ebraic');
INSERT INTO [country] ([id], [name]) VALUES ('efi', 'efik');
INSERT INTO [country] ([id], [name]) VALUES ('egy', 'egipzian vegl');
INSERT INTO [country] ([id], [name]) VALUES ('eka', 'ekajuk');
INSERT INTO [country] ([id], [name]) VALUES ('elx', 'elamitic');
INSERT INTO [country] ([id], [name]) VALUES ('en', 'englais');
INSERT INTO [country] ([id], [name]) VALUES ('en_US', 'englais american');
INSERT INTO [country] ([id], [name]) VALUES ('en_AU', 'englais australian');
INSERT INTO [country] ([id], [name]) VALUES ('en_GB', 'englais britannic');
INSERT INTO [country] ([id], [name]) VALUES ('en_CA', 'englais canadais');
INSERT INTO [country] ([id], [name]) VALUES ('enm', 'englais mesaun');
INSERT INTO [country] ([id], [name]) VALUES ('ang', 'englais vegl');
INSERT INTO [country] ([id], [name]) VALUES ('myv', 'erzya');
INSERT INTO [country] ([id], [name]) VALUES ('eo', 'esperanto');
INSERT INTO [country] ([id], [name]) VALUES ('et', 'eston');
INSERT INTO [country] ([id], [name]) VALUES ('hit', 'ettitic');
INSERT INTO [country] ([id], [name]) VALUES ('ee', 'ewe');
INSERT INTO [country] ([id], [name]) VALUES ('ewo', 'ewondo');
INSERT INTO [country] ([id], [name]) VALUES ('fan', 'fang');
INSERT INTO [country] ([id], [name]) VALUES ('fat', 'fanti');
INSERT INTO [country] ([id], [name]) VALUES ('phn', 'fenizian');
INSERT INTO [country] ([id], [name]) VALUES ('fo', 'ferrais');
INSERT INTO [country] ([id], [name]) VALUES ('fj', 'fidschian');
INSERT INTO [country] ([id], [name]) VALUES ('fil', 'filippino');
INSERT INTO [country] ([id], [name]) VALUES ('fi', 'finlandais');
INSERT INTO [country] ([id], [name]) VALUES ('nl_BE', 'flam');
INSERT INTO [country] ([id], [name]) VALUES ('fon', 'fon');
INSERT INTO [country] ([id], [name]) VALUES ('fr', 'franzos');
INSERT INTO [country] ([id], [name]) VALUES ('fr_CA', 'franzos canadais');
INSERT INTO [country] ([id], [name]) VALUES ('frm', 'franzos mesaun');
INSERT INTO [country] ([id], [name]) VALUES ('fr_CH', 'franzos svizzer');
INSERT INTO [country] ([id], [name]) VALUES ('fro', 'franzos vegl');
INSERT INTO [country] ([id], [name]) VALUES ('fy', 'fris');
INSERT INTO [country] ([id], [name]) VALUES ('frs', 'fris da l''ost');
INSERT INTO [country] ([id], [name]) VALUES ('frr', 'fris dal nord');
INSERT INTO [country] ([id], [name]) VALUES ('fur', 'friulan');
INSERT INTO [country] ([id], [name]) VALUES ('ff', 'fulah');
INSERT INTO [country] ([id], [name]) VALUES ('gaa', 'ga');
INSERT INTO [country] ([id], [name]) VALUES ('gd', 'gaelic scot');
INSERT INTO [country] ([id], [name]) VALUES ('gl', 'galician');
INSERT INTO [country] ([id], [name]) VALUES ('lg', 'ganda');
INSERT INTO [country] ([id], [name]) VALUES ('gay', 'gayo');
INSERT INTO [country] ([id], [name]) VALUES ('gba', 'gbaya');
INSERT INTO [country] ([id], [name]) VALUES ('gez', 'geez');
INSERT INTO [country] ([id], [name]) VALUES ('ka', 'georgian');
INSERT INTO [country] ([id], [name]) VALUES ('ja', 'giapunais');
INSERT INTO [country] ([id], [name]) VALUES ('gil', 'gilbertais');
INSERT INTO [country] ([id], [name]) VALUES ('jrb', 'giudaic-arab');
INSERT INTO [country] ([id], [name]) VALUES ('jpr', 'giudaic-persian');
INSERT INTO [country] ([id], [name]) VALUES ('gon', 'gondi');
INSERT INTO [country] ([id], [name]) VALUES ('gor', 'gorontalo');
INSERT INTO [country] ([id], [name]) VALUES ('got', 'gotic');
INSERT INTO [country] ([id], [name]) VALUES ('grb', 'grebo');
INSERT INTO [country] ([id], [name]) VALUES ('el', 'grec');
INSERT INTO [country] ([id], [name]) VALUES ('grc', 'grec vegl');
INSERT INTO [country] ([id], [name]) VALUES ('kl', 'grönlandais');
INSERT INTO [country] ([id], [name]) VALUES ('gn', 'guarani');
INSERT INTO [country] ([id], [name]) VALUES ('gu', 'gujarati');
INSERT INTO [country] ([id], [name]) VALUES ('gwi', 'gwichʼin');
INSERT INTO [country] ([id], [name]) VALUES ('hai', 'haida');
INSERT INTO [country] ([id], [name]) VALUES ('ht', 'haitian');
INSERT INTO [country] ([id], [name]) VALUES ('ha', 'haussa');
INSERT INTO [country] ([id], [name]) VALUES ('haw', 'hawaian');
INSERT INTO [country] ([id], [name]) VALUES ('hz', 'herero');
INSERT INTO [country] ([id], [name]) VALUES ('hil', 'hiligaynon');
INSERT INTO [country] ([id], [name]) VALUES ('him', 'himachali');
INSERT INTO [country] ([id], [name]) VALUES ('hi', 'hindi');
INSERT INTO [country] ([id], [name]) VALUES ('ho', 'hiri motu');
INSERT INTO [country] ([id], [name]) VALUES ('hmn', 'hmong');
INSERT INTO [country] ([id], [name]) VALUES ('hup', 'hupa');
INSERT INTO [country] ([id], [name]) VALUES ('iba', 'iban');
INSERT INTO [country] ([id], [name]) VALUES ('io', 'ido');
INSERT INTO [country] ([id], [name]) VALUES ('ig', 'igbo');
INSERT INTO [country] ([id], [name]) VALUES ('ijo', 'ijo');
INSERT INTO [country] ([id], [name]) VALUES ('ilo', 'ilocano');
INSERT INTO [country] ([id], [name]) VALUES ('id', 'indonais');
INSERT INTO [country] ([id], [name]) VALUES ('inh', 'ingush');
INSERT INTO [country] ([id], [name]) VALUES ('ia', 'interlingua');
INSERT INTO [country] ([id], [name]) VALUES ('ie', 'interlingue');
INSERT INTO [country] ([id], [name]) VALUES ('iu', 'inuktitut');
INSERT INTO [country] ([id], [name]) VALUES ('ik', 'inupiak');
INSERT INTO [country] ([id], [name]) VALUES ('ga', 'irlandais');
INSERT INTO [country] ([id], [name]) VALUES ('mga', 'irlandais mesaun');
INSERT INTO [country] ([id], [name]) VALUES ('sga', 'irlandais vegl');
INSERT INTO [country] ([id], [name]) VALUES ('is', 'islandais');
INSERT INTO [country] ([id], [name]) VALUES ('sah', 'jakut');
INSERT INTO [country] ([id], [name]) VALUES ('jv', 'javanais');
INSERT INTO [country] ([id], [name]) VALUES ('yi', 'jiddic');
INSERT INTO [country] ([id], [name]) VALUES ('kaj', 'jju');
INSERT INTO [country] ([id], [name]) VALUES ('kbd', 'kabardic');
INSERT INTO [country] ([id], [name]) VALUES ('kab', 'kabyle');
INSERT INTO [country] ([id], [name]) VALUES ('kac', 'kachin');
INSERT INTO [country] ([id], [name]) VALUES ('xal', 'kalmuk');
INSERT INTO [country] ([id], [name]) VALUES ('kam', 'kamba');
INSERT INTO [country] ([id], [name]) VALUES ('kn', 'kannada');
INSERT INTO [country] ([id], [name]) VALUES ('kr', 'kanuri');
INSERT INTO [country] ([id], [name]) VALUES ('krc', 'karachay-balkar');
INSERT INTO [country] ([id], [name]) VALUES ('kaa', 'karakalpak');
INSERT INTO [country] ([id], [name]) VALUES ('kar', 'karen');
INSERT INTO [country] ([id], [name]) VALUES ('csb', 'kaschubic');
INSERT INTO [country] ([id], [name]) VALUES ('ks', 'kashmiri');
INSERT INTO [country] ([id], [name]) VALUES ('kaw', 'kawi');
INSERT INTO [country] ([id], [name]) VALUES ('kha', 'khasi');
INSERT INTO [country] ([id], [name]) VALUES ('kho', 'khotanais');
INSERT INTO [country] ([id], [name]) VALUES ('ki', 'kikuyu');
INSERT INTO [country] ([id], [name]) VALUES ('kmb', 'kimbundu');
INSERT INTO [country] ([id], [name]) VALUES ('cy', 'kimric');
INSERT INTO [country] ([id], [name]) VALUES ('rw', 'kinyarwanda');
INSERT INTO [country] ([id], [name]) VALUES ('ky', 'kirghis');
INSERT INTO [country] ([id], [name]) VALUES ('tlh', 'klingonic');
INSERT INTO [country] ([id], [name]) VALUES ('kv', 'komi');
INSERT INTO [country] ([id], [name]) VALUES ('kg', 'kongo');
INSERT INTO [country] ([id], [name]) VALUES ('kok', 'konkani');
INSERT INTO [country] ([id], [name]) VALUES ('kfo', 'koro');
INSERT INTO [country] ([id], [name]) VALUES ('kos', 'kosraean');
INSERT INTO [country] ([id], [name]) VALUES ('kpe', 'kpelle');
INSERT INTO [country] ([id], [name]) VALUES ('kro', 'kru');
INSERT INTO [country] ([id], [name]) VALUES ('kj', 'kuanyama');
INSERT INTO [country] ([id], [name]) VALUES ('kum', 'kumuk');
INSERT INTO [country] ([id], [name]) VALUES ('kru', 'kurukh');
INSERT INTO [country] ([id], [name]) VALUES ('kut', 'kutenai');
INSERT INTO [country] ([id], [name]) VALUES ('lad', 'ladino');
INSERT INTO [country] ([id], [name]) VALUES ('lah', 'lahnda');
INSERT INTO [country] ([id], [name]) VALUES ('lam', 'lamba');
INSERT INTO [country] ([id], [name]) VALUES ('lo', 'laot');
INSERT INTO [country] ([id], [name]) VALUES ('la', 'latin');
INSERT INTO [country] ([id], [name]) VALUES ('lv', 'letton');
INSERT INTO [country] ([id], [name]) VALUES ('lez', 'lezghian');
INSERT INTO [country] ([id], [name]) VALUES ('li', 'limburgais');
INSERT INTO [country] ([id], [name]) VALUES ('ln', 'lingala');
INSERT INTO [country] ([id], [name]) VALUES ('myn', 'lingau maya');
INSERT INTO [country] ([id], [name]) VALUES ('afa', 'lingua afro-asiatica');
INSERT INTO [country] ([id], [name]) VALUES ('art', 'lingua artifiziala');
INSERT INTO [country] ([id], [name]) VALUES ('bat', 'lingua baltica');
INSERT INTO [country] ([id], [name]) VALUES ('bai', 'lingua bamileka');
INSERT INTO [country] ([id], [name]) VALUES ('ira', 'lingua da l''Iran');
INSERT INTO [country] ([id], [name]) VALUES ('sgn', 'lingua da segns');
INSERT INTO [country] ([id], [name]) VALUES ('dra', 'lingua dravidica');
INSERT INTO [country] ([id], [name]) VALUES ('phi', 'lingua filippina');
INSERT INTO [country] ([id], [name]) VALUES ('gem', 'lingua germana');
INSERT INTO [country] ([id], [name]) VALUES ('inc', 'lingua indiana');
INSERT INTO [country] ([id], [name]) VALUES ('nai', 'lingua indiana da l''America dal Nord');
INSERT INTO [country] ([id], [name]) VALUES ('sai', 'lingua indiana da l''America dal Sid');
INSERT INTO [country] ([id], [name]) VALUES ('ine', 'lingua indoeuropeica');
INSERT INTO [country] ([id], [name]) VALUES ('khi', 'lingua khoisan');
INSERT INTO [country] ([id], [name]) VALUES ('mkh', 'lingua mon-khmer');
INSERT INTO [country] ([id], [name]) VALUES ('mun', 'lingua munda');
INSERT INTO [country] ([id], [name]) VALUES ('nic', 'lingua niger-cordofanica');
INSERT INTO [country] ([id], [name]) VALUES ('ssa', 'lingua nilo-sahariana');
INSERT INTO [country] ([id], [name]) VALUES ('paa', 'lingua papuana');
INSERT INTO [country] ([id], [name]) VALUES ('roa', 'lingua romana');
INSERT INTO [country] ([id], [name]) VALUES ('sal', 'lingua salish');
INSERT INTO [country] ([id], [name]) VALUES ('smi', 'lingua sami');
INSERT INTO [country] ([id], [name]) VALUES ('sem', 'lingua semitica');
INSERT INTO [country] ([id], [name]) VALUES ('sla', 'lingua slava');
INSERT INTO [country] ([id], [name]) VALUES ('tai', 'lingua tai');
INSERT INTO [country] ([id], [name]) VALUES ('tog', 'lingua tsonga');
INSERT INTO [country] ([id], [name]) VALUES ('fiu', 'lingua ungrofinnica');
INSERT INTO [country] ([id], [name]) VALUES ('alg', 'linguas algonchinas');
INSERT INTO [country] ([id], [name]) VALUES ('tut', 'linguas altaicas');
INSERT INTO [country] ([id], [name]) VALUES ('apa', 'linguas apachas');
INSERT INTO [country] ([id], [name]) VALUES ('ath', 'linguas athapascas');
INSERT INTO [country] ([id], [name]) VALUES ('aus', 'linguas australianas');
INSERT INTO [country] ([id], [name]) VALUES ('und', 'linguas betg determinadas');
INSERT INTO [country] ([id], [name]) VALUES ('cel', 'linguas celticas');
INSERT INTO [country] ([id], [name]) VALUES ('cmc', 'linguas chamicas');
INSERT INTO [country] ([id], [name]) VALUES ('cus', 'linguas cuschiticas');
INSERT INTO [country] ([id], [name]) VALUES ('cau', 'linguas dal Caucasus');
INSERT INTO [country] ([id], [name]) VALUES ('cai', 'linguas dals Indians da l''America centrala');
INSERT INTO [country] ([id], [name]) VALUES ('iro', 'linguas irochesas');
INSERT INTO [country] ([id], [name]) VALUES ('nub', 'linguas nubicas');
INSERT INTO [country] ([id], [name]) VALUES ('oto', 'linguas otomangue');
INSERT INTO [country] ([id], [name]) VALUES ('sit', 'linguas sino-tibetanas');
INSERT INTO [country] ([id], [name]) VALUES ('sio', 'linguas sioux');
INSERT INTO [country] ([id], [name]) VALUES ('tup', 'linguas tupi');
INSERT INTO [country] ([id], [name]) VALUES ('wak', 'linguas wakash');
INSERT INTO [country] ([id], [name]) VALUES ('ypk', 'linguas yupik');
INSERT INTO [country] ([id], [name]) VALUES ('lt', 'lituan');
INSERT INTO [country] ([id], [name]) VALUES ('jbo', 'lojban');
INSERT INTO [country] ([id], [name]) VALUES ('lol', 'lomongo');
INSERT INTO [country] ([id], [name]) VALUES ('loz', 'lozi');
INSERT INTO [country] ([id], [name]) VALUES ('lu', 'luba-katanga');
INSERT INTO [country] ([id], [name]) VALUES ('lua', 'luba-lulua');
INSERT INTO [country] ([id], [name]) VALUES ('lui', 'luiseno');
INSERT INTO [country] ([id], [name]) VALUES ('lun', 'lunda');
INSERT INTO [country] ([id], [name]) VALUES ('luo', 'luo');
INSERT INTO [country] ([id], [name]) VALUES ('lus', 'lushai');
INSERT INTO [country] ([id], [name]) VALUES ('lb', 'luxemburgais');
INSERT INTO [country] ([id], [name]) VALUES ('mk', 'macedon');
INSERT INTO [country] ([id], [name]) VALUES ('mad', 'madurais');
INSERT INTO [country] ([id], [name]) VALUES ('mag', 'magahi');
INSERT INTO [country] ([id], [name]) VALUES ('mai', 'maithili');
INSERT INTO [country] ([id], [name]) VALUES ('mak', 'makassar');
INSERT INTO [country] ([id], [name]) VALUES ('mg', 'malagassi');
INSERT INTO [country] ([id], [name]) VALUES ('ms', 'malaic');
INSERT INTO [country] ([id], [name]) VALUES ('ml', 'malayalam');
INSERT INTO [country] ([id], [name]) VALUES ('dv', 'maledivic');
INSERT INTO [country] ([id], [name]) VALUES ('mt', 'maltais');
INSERT INTO [country] ([id], [name]) VALUES ('mnc', 'manchu');
INSERT INTO [country] ([id], [name]) VALUES ('mdr', 'mandar');
INSERT INTO [country] ([id], [name]) VALUES ('man', 'mandingo');
INSERT INTO [country] ([id], [name]) VALUES ('mni', 'manipuri');
INSERT INTO [country] ([id], [name]) VALUES ('mno', 'manobo');
INSERT INTO [country] ([id], [name]) VALUES ('gv', 'manx');
INSERT INTO [country] ([id], [name]) VALUES ('mi', 'maori');
INSERT INTO [country] ([id], [name]) VALUES ('mr', 'marathi');
INSERT INTO [country] ([id], [name]) VALUES ('chm', 'mari');
INSERT INTO [country] ([id], [name]) VALUES ('mh', 'marschallais');
INSERT INTO [country] ([id], [name]) VALUES ('mwr', 'marwari');
INSERT INTO [country] ([id], [name]) VALUES ('mas', 'masai');
INSERT INTO [country] ([id], [name]) VALUES ('umb', 'mbundu');
INSERT INTO [country] ([id], [name]) VALUES ('men', 'mende');
INSERT INTO [country] ([id], [name]) VALUES ('mic', 'micmac');
INSERT INTO [country] ([id], [name]) VALUES ('min', 'minangkabau');
INSERT INTO [country] ([id], [name]) VALUES ('mwl', 'mirandais');
INSERT INTO [country] ([id], [name]) VALUES ('moh', 'mohawk');
INSERT INTO [country] ([id], [name]) VALUES ('mdf', 'moksha');
INSERT INTO [country] ([id], [name]) VALUES ('mo', 'moldav');
INSERT INTO [country] ([id], [name]) VALUES ('mn', 'mongolic');
INSERT INTO [country] ([id], [name]) VALUES ('mos', 'mossi');
INSERT INTO [country] ([id], [name]) VALUES ('nqo', 'n''ko');
INSERT INTO [country] ([id], [name]) VALUES ('zxx', 'nagins cuntegns linguistics');
INSERT INTO [country] ([id], [name]) VALUES ('nah', 'nahuatl');
INSERT INTO [country] ([id], [name]) VALUES ('na', 'nauru');
INSERT INTO [country] ([id], [name]) VALUES ('nv', 'navajo');
INSERT INTO [country] ([id], [name]) VALUES ('nd', 'ndebele dal nord');
INSERT INTO [country] ([id], [name]) VALUES ('nr', 'ndebele dal sid');
INSERT INTO [country] ([id], [name]) VALUES ('ng', 'ndonga');
INSERT INTO [country] ([id], [name]) VALUES ('nap', 'neapolitan');
INSERT INTO [country] ([id], [name]) VALUES ('ne', 'nepalais');
INSERT INTO [country] ([id], [name]) VALUES ('new', 'newari');
INSERT INTO [country] ([id], [name]) VALUES ('nwc', 'newari classic');
INSERT INTO [country] ([id], [name]) VALUES ('nia', 'nias');
INSERT INTO [country] ([id], [name]) VALUES ('niu', 'niue');
INSERT INTO [country] ([id], [name]) VALUES ('nog', 'nogai');
INSERT INTO [country] ([id], [name]) VALUES ('non', 'nordic vegl');
INSERT INTO [country] ([id], [name]) VALUES ('nb', 'norvegais bokmål');
INSERT INTO [country] ([id], [name]) VALUES ('no', 'norvegiais');
INSERT INTO [country] ([id], [name]) VALUES ('nn', 'norvegiais nynorsk');
INSERT INTO [country] ([id], [name]) VALUES ('nym', 'nyamwezi');
INSERT INTO [country] ([id], [name]) VALUES ('ny', 'nyanja');
INSERT INTO [country] ([id], [name]) VALUES ('nyn', 'nyankole');
INSERT INTO [country] ([id], [name]) VALUES ('nyo', 'nyoro');
INSERT INTO [country] ([id], [name]) VALUES ('nzi', 'nzima');
INSERT INTO [country] ([id], [name]) VALUES ('oc', 'occitan');
INSERT INTO [country] ([id], [name]) VALUES ('oj', 'ojibwa');
INSERT INTO [country] ([id], [name]) VALUES ('nl', 'ollandais');
INSERT INTO [country] ([id], [name]) VALUES ('dum', 'ollandais mesaun');
INSERT INTO [country] ([id], [name]) VALUES ('or', 'oriya');
INSERT INTO [country] ([id], [name]) VALUES ('om', 'oromo');
INSERT INTO [country] ([id], [name]) VALUES ('osa', 'osage');
INSERT INTO [country] ([id], [name]) VALUES ('os', 'ossetic');
INSERT INTO [country] ([id], [name]) VALUES ('pal', 'pahlavi');
INSERT INTO [country] ([id], [name]) VALUES ('pau', 'palau');
INSERT INTO [country] ([id], [name]) VALUES ('pi', 'pali');
INSERT INTO [country] ([id], [name]) VALUES ('pam', 'pampanga');
INSERT INTO [country] ([id], [name]) VALUES ('pag', 'pangasinan');
INSERT INTO [country] ([id], [name]) VALUES ('pap', 'papiamento');
INSERT INTO [country] ([id], [name]) VALUES ('ps', 'paschto');
INSERT INTO [country] ([id], [name]) VALUES ('chn', 'patuà chinook');
INSERT INTO [country] ([id], [name]) VALUES ('fa', 'persian');
INSERT INTO [country] ([id], [name]) VALUES ('peo', 'persian vegl');
INSERT INTO [country] ([id], [name]) VALUES ('pl', 'polac');
INSERT INTO [country] ([id], [name]) VALUES ('pon', 'ponapean');
INSERT INTO [country] ([id], [name]) VALUES ('pt', 'portugais');
INSERT INTO [country] ([id], [name]) VALUES ('pt_BR', 'portugais brasilian');
INSERT INTO [country] ([id], [name]) VALUES ('pt_PT', 'portugais iberian');
INSERT INTO [country] ([id], [name]) VALUES ('pra', 'prakrit');
INSERT INTO [country] ([id], [name]) VALUES ('pro', 'provenzal vegl');
INSERT INTO [country] ([id], [name]) VALUES ('pa', 'punjabi');
INSERT INTO [country] ([id], [name]) VALUES ('qu', 'quechua');
INSERT INTO [country] ([id], [name]) VALUES ('raj', 'rajasthani');
INSERT INTO [country] ([id], [name]) VALUES ('rap', 'rapanui');
INSERT INTO [country] ([id], [name]) VALUES ('rar', 'rarotonga');
INSERT INTO [country] ([id], [name]) VALUES ('rom', 'romani');
INSERT INTO [country] ([id], [name]) VALUES ('rm', 'rumantsch');
INSERT INTO [country] ([id], [name]) VALUES ('ro', 'rumen');
INSERT INTO [country] ([id], [name]) VALUES ('rn', 'rundi');
INSERT INTO [country] ([id], [name]) VALUES ('ru', 'russ');
INSERT INTO [country] ([id], [name]) VALUES ('se', 'sami dal nord');
INSERT INTO [country] ([id], [name]) VALUES ('sma', 'sami dal sid');
INSERT INTO [country] ([id], [name]) VALUES ('smn', 'sami inari');
INSERT INTO [country] ([id], [name]) VALUES ('smj', 'sami lule');
INSERT INTO [country] ([id], [name]) VALUES ('sms', 'sami skolt');
INSERT INTO [country] ([id], [name]) VALUES ('sm', 'samoan');
INSERT INTO [country] ([id], [name]) VALUES ('sad', 'sandawe');
INSERT INTO [country] ([id], [name]) VALUES ('sg', 'sango');
INSERT INTO [country] ([id], [name]) VALUES ('sa', 'sanscrit');
INSERT INTO [country] ([id], [name]) VALUES ('sat', 'santali');
INSERT INTO [country] ([id], [name]) VALUES ('sc', 'sard');
INSERT INTO [country] ([id], [name]) VALUES ('sas', 'sasak');
INSERT INTO [country] ([id], [name]) VALUES ('sco', 'scot');
INSERT INTO [country] ([id], [name]) VALUES ('sel', 'selkup');
INSERT INTO [country] ([id], [name]) VALUES ('sr', 'serb');
INSERT INTO [country] ([id], [name]) VALUES ('sh', 'serbo-croat');
INSERT INTO [country] ([id], [name]) VALUES ('srr', 'serer');
INSERT INTO [country] ([id], [name]) VALUES ('shn', 'shan');
INSERT INTO [country] ([id], [name]) VALUES ('sn', 'shona');
INSERT INTO [country] ([id], [name]) VALUES ('ii', 'sichuan yi');
INSERT INTO [country] ([id], [name]) VALUES ('scn', 'sicilian');
INSERT INTO [country] ([id], [name]) VALUES ('sid', 'sidamo');
INSERT INTO [country] ([id], [name]) VALUES ('bla', 'siksika');
INSERT INTO [country] ([id], [name]) VALUES ('zbl', 'simbols da Bliss');
INSERT INTO [country] ([id], [name]) VALUES ('sd', 'sindhi');
INSERT INTO [country] ([id], [name]) VALUES ('si', 'singalais');
INSERT INTO [country] ([id], [name]) VALUES ('syr', 'siric');
INSERT INTO [country] ([id], [name]) VALUES ('syc', 'siric classic');
INSERT INTO [country] ([id], [name]) VALUES ('cu', 'slav da baselgia');
INSERT INTO [country] ([id], [name]) VALUES ('den', 'slavey');
INSERT INTO [country] ([id], [name]) VALUES ('sk', 'slovac');
INSERT INTO [country] ([id], [name]) VALUES ('sl', 'sloven');
INSERT INTO [country] ([id], [name]) VALUES ('sog', 'sogdian');
INSERT INTO [country] ([id], [name]) VALUES ('so', 'somali');
INSERT INTO [country] ([id], [name]) VALUES ('son', 'songhai');
INSERT INTO [country] ([id], [name]) VALUES ('snk', 'soninke');
INSERT INTO [country] ([id], [name]) VALUES ('wen', 'sorb');
INSERT INTO [country] ([id], [name]) VALUES ('nso', 'sotho dal nord');
INSERT INTO [country] ([id], [name]) VALUES ('st', 'sotho dal sid');
INSERT INTO [country] ([id], [name]) VALUES ('es', 'spagnol');
INSERT INTO [country] ([id], [name]) VALUES ('es_ES', 'spagnol iberic');
INSERT INTO [country] ([id], [name]) VALUES ('es_419', 'spagnol latinamerican');
INSERT INTO [country] ([id], [name]) VALUES ('srn', 'sranan tongo');
INSERT INTO [country] ([id], [name]) VALUES ('sw', 'suahili');
INSERT INTO [country] ([id], [name]) VALUES ('suk', 'sukuma');
INSERT INTO [country] ([id], [name]) VALUES ('sux', 'sumeric');
INSERT INTO [country] ([id], [name]) VALUES ('su', 'sundanais');
INSERT INTO [country] ([id], [name]) VALUES ('sus', 'susu');
INSERT INTO [country] ([id], [name]) VALUES ('sv', 'svedais');
INSERT INTO [country] ([id], [name]) VALUES ('ss', 'swazi');
INSERT INTO [country] ([id], [name]) VALUES ('tg', 'tadjik');
INSERT INTO [country] ([id], [name]) VALUES ('tl', 'tagalog');
INSERT INTO [country] ([id], [name]) VALUES ('ty', 'tahitian');
INSERT INTO [country] ([id], [name]) VALUES ('th', 'tailandais');
INSERT INTO [country] ([id], [name]) VALUES ('it', 'talian');
INSERT INTO [country] ([id], [name]) VALUES ('tmh', 'tamasheq');
INSERT INTO [country] ([id], [name]) VALUES ('ta', 'tamil');
INSERT INTO [country] ([id], [name]) VALUES ('tt', 'tatar');
INSERT INTO [country] ([id], [name]) VALUES ('te', 'telugu');
INSERT INTO [country] ([id], [name]) VALUES ('tem', 'temne');
INSERT INTO [country] ([id], [name]) VALUES ('ter', 'tereno');
INSERT INTO [country] ([id], [name]) VALUES ('tet', 'tetum');
INSERT INTO [country] ([id], [name]) VALUES ('bo', 'tibetan');
INSERT INTO [country] ([id], [name]) VALUES ('tig', 'tigre');
INSERT INTO [country] ([id], [name]) VALUES ('ti', 'tigrinya');
INSERT INTO [country] ([id], [name]) VALUES ('tr', 'tirc');
INSERT INTO [country] ([id], [name]) VALUES ('crh', 'tirc crimean');
INSERT INTO [country] ([id], [name]) VALUES ('ota', 'tirc ottoman');
INSERT INTO [country] ([id], [name]) VALUES ('tiv', 'tiv');
INSERT INTO [country] ([id], [name]) VALUES ('tli', 'tlingit');
INSERT INTO [country] ([id], [name]) VALUES ('tpi', 'tok pisin');
INSERT INTO [country] ([id], [name]) VALUES ('tkl', 'tokelau');
INSERT INTO [country] ([id], [name]) VALUES ('to', 'tonga');
INSERT INTO [country] ([id], [name]) VALUES ('chg', 'tschagataic');
INSERT INTO [country] ([id], [name]) VALUES ('cs', 'tschec');
INSERT INTO [country] ([id], [name]) VALUES ('ce', 'tschetschen');
INSERT INTO [country] ([id], [name]) VALUES ('cv', 'tschuvasch');
INSERT INTO [country] ([id], [name]) VALUES ('tsi', 'tsimshian');
INSERT INTO [country] ([id], [name]) VALUES ('ts', 'tsonga');
INSERT INTO [country] ([id], [name]) VALUES ('tn', 'tswana');
INSERT INTO [country] ([id], [name]) VALUES ('de', 'tudestg');
INSERT INTO [country] ([id], [name]) VALUES ('de_AT', 'tudestg austriac');
INSERT INTO [country] ([id], [name]) VALUES ('gmh', 'tudestg mesaun');
INSERT INTO [country] ([id], [name]) VALUES ('gsw', 'tudestg svizzer');
INSERT INTO [country] ([id], [name]) VALUES ('tum', 'tumbuka');
INSERT INTO [country] ([id], [name]) VALUES ('tk', 'turkmen');
INSERT INTO [country] ([id], [name]) VALUES ('tvl', 'tuvalu');
INSERT INTO [country] ([id], [name]) VALUES ('tyv', 'tuvinian');
INSERT INTO [country] ([id], [name]) VALUES ('tw', 'twi');
INSERT INTO [country] ([id], [name]) VALUES ('kcg', 'tyap');
INSERT INTO [country] ([id], [name]) VALUES ('uk', 'ucranais');
INSERT INTO [country] ([id], [name]) VALUES ('udm', 'udmurt');
INSERT INTO [country] ([id], [name]) VALUES ('uga', 'ugaritic');
INSERT INTO [country] ([id], [name]) VALUES ('ug', 'uiguric');
INSERT INTO [country] ([id], [name]) VALUES ('hu', 'ungarais');
INSERT INTO [country] ([id], [name]) VALUES ('ur', 'urdu');
INSERT INTO [country] ([id], [name]) VALUES ('uz', 'usbec');
INSERT INTO [country] ([id], [name]) VALUES ('vai', 'vai');
INSERT INTO [country] ([id], [name]) VALUES ('wa', 'vallon');
INSERT INTO [country] ([id], [name]) VALUES ('goh', 'vegl tudestg da scrittira');
INSERT INTO [country] ([id], [name]) VALUES ('ve', 'venda');
INSERT INTO [country] ([id], [name]) VALUES ('vi', 'vietnamais');
INSERT INTO [country] ([id], [name]) VALUES ('vo', 'volapuk');
INSERT INTO [country] ([id], [name]) VALUES ('vot', 'votic');
INSERT INTO [country] ([id], [name]) VALUES ('wal', 'walamo');
INSERT INTO [country] ([id], [name]) VALUES ('war', 'waray');
INSERT INTO [country] ([id], [name]) VALUES ('was', 'washo');
INSERT INTO [country] ([id], [name]) VALUES ('wo', 'wolof');
INSERT INTO [country] ([id], [name]) VALUES ('xh', 'xhosa');
INSERT INTO [country] ([id], [name]) VALUES ('yao', 'yao');
INSERT INTO [country] ([id], [name]) VALUES ('yap', 'yapais');
INSERT INTO [country] ([id], [name]) VALUES ('yo', 'yoruba');
INSERT INTO [country] ([id], [name]) VALUES ('znd', 'zande');
INSERT INTO [country] ([id], [name]) VALUES ('zap', 'zapotec');
INSERT INTO [country] ([id], [name]) VALUES ('zza', 'zaza');
INSERT INTO [country] ([id], [name]) VALUES ('zen', 'zenaga');
INSERT INTO [country] ([id], [name]) VALUES ('za', 'zhuang');
INSERT INTO [country] ([id], [name]) VALUES ('zu', 'zulu');
INSERT INTO [country] ([id], [name]) VALUES ('zun', 'zuni');
