CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('ab', 'abhază');
INSERT INTO `country` (`id`, `name`) VALUES ('af', 'afrikaans');
INSERT INTO `country` (`id`, `name`) VALUES ('ain', 'ainu');
INSERT INTO `country` (`id`, `name`) VALUES ('akk', 'akkadiană');
INSERT INTO `country` (`id`, `name`) VALUES ('sq', 'albaneză');
INSERT INTO `country` (`id`, `name`) VALUES ('ale', 'aleută');
INSERT INTO `country` (`id`, `name`) VALUES ('alt', 'altaică meridională');
INSERT INTO `country` (`id`, `name`) VALUES ('am', 'amharică');
INSERT INTO `country` (`id`, `name`) VALUES ('ar', 'arabă');
INSERT INTO `country` (`id`, `name`) VALUES ('an', 'aragoneză');
INSERT INTO `country` (`id`, `name`) VALUES ('arc', 'aramaică');
INSERT INTO `country` (`id`, `name`) VALUES ('sam', 'aramaică samariteană');
INSERT INTO `country` (`id`, `name`) VALUES ('hy', 'armeană');
INSERT INTO `country` (`id`, `name`) VALUES ('rup', 'aromână');
INSERT INTO `country` (`id`, `name`) VALUES ('as', 'asameză');
INSERT INTO `country` (`id`, `name`) VALUES ('ast', 'asturiană');
INSERT INTO `country` (`id`, `name`) VALUES ('map', 'austroneziană');
INSERT INTO `country` (`id`, `name`) VALUES ('av', 'avară');
INSERT INTO `country` (`id`, `name`) VALUES ('ay', 'aymara');
INSERT INTO `country` (`id`, `name`) VALUES ('az', 'azeră');
INSERT INTO `country` (`id`, `name`) VALUES ('bnt', 'bantu');
INSERT INTO `country` (`id`, `name`) VALUES ('eu', 'bască');
INSERT INTO `country` (`id`, `name`) VALUES ('ba', 'bașkiră');
INSERT INTO `country` (`id`, `name`) VALUES ('bn', 'bengaleză');
INSERT INTO `country` (`id`, `name`) VALUES ('ber', 'berberă');
INSERT INTO `country` (`id`, `name`) VALUES ('be', 'bielorusă');
INSERT INTO `country` (`id`, `name`) VALUES ('bh', 'bihari');
INSERT INTO `country` (`id`, `name`) VALUES ('my', 'birmaneză');
INSERT INTO `country` (`id`, `name`) VALUES ('bs', 'bosniacă');
INSERT INTO `country` (`id`, `name`) VALUES ('br', 'bretonă');
INSERT INTO `country` (`id`, `name`) VALUES ('bg', 'bulgară');
INSERT INTO `country` (`id`, `name`) VALUES ('xal', 'calmucă');
INSERT INTO `country` (`id`, `name`) VALUES ('yue', 'cantoneză');
INSERT INTO `country` (`id`, `name`) VALUES ('ks', 'cașmireză');
INSERT INTO `country` (`id`, `name`) VALUES ('ca', 'catalană');
INSERT INTO `country` (`id`, `name`) VALUES ('ce', 'cecenă');
INSERT INTO `country` (`id`, `name`) VALUES ('cs', 'cehă');
INSERT INTO `country` (`id`, `name`) VALUES ('zh', 'chineză');
INSERT INTO `country` (`id`, `name`) VALUES ('zh_Hans', 'chineză simplificată');
INSERT INTO `country` (`id`, `name`) VALUES ('zh_Hant', 'chineză tradițională');
INSERT INTO `country` (`id`, `name`) VALUES ('cv', 'ciuvașă');
INSERT INTO `country` (`id`, `name`) VALUES ('swb', 'comoreză');
INSERT INTO `country` (`id`, `name`) VALUES ('kg', 'congoleză');
INSERT INTO `country` (`id`, `name`) VALUES ('cop', 'coptă');
INSERT INTO `country` (`id`, `name`) VALUES ('ko', 'coreeană');
INSERT INTO `country` (`id`, `name`) VALUES ('co', 'corsicană');
INSERT INTO `country` (`id`, `name`) VALUES ('hr', 'croată');
INSERT INTO `country` (`id`, `name`) VALUES ('da', 'daneză');
INSERT INTO `country` (`id`, `name`) VALUES ('dv', 'divehi');
INSERT INTO `country` (`id`, `name`) VALUES ('dz', 'dzongkha');
INSERT INTO `country` (`id`, `name`) VALUES ('he', 'ebraică');
INSERT INTO `country` (`id`, `name`) VALUES ('efi', 'efik');
INSERT INTO `country` (`id`, `name`) VALUES ('egy', 'egipteană veche');
INSERT INTO `country` (`id`, `name`) VALUES ('elx', 'elamită');
INSERT INTO `country` (`id`, `name`) VALUES ('en', 'engleză');
INSERT INTO `country` (`id`, `name`) VALUES ('en_US', 'engleză americană');
INSERT INTO `country` (`id`, `name`) VALUES ('en_AU', 'engleză australiană');
INSERT INTO `country` (`id`, `name`) VALUES ('en_GB', 'engleză britanică');
INSERT INTO `country` (`id`, `name`) VALUES ('en_CA', 'engleză canadiană');
INSERT INTO `country` (`id`, `name`) VALUES ('ang', 'engleză veche');
INSERT INTO `country` (`id`, `name`) VALUES ('eo', 'esperanto');
INSERT INTO `country` (`id`, `name`) VALUES ('et', 'estoniană');
INSERT INTO `country` (`id`, `name`) VALUES ('zxx', 'fară conținut lingvistic');
INSERT INTO `country` (`id`, `name`) VALUES ('fo', 'faroeză');
INSERT INTO `country` (`id`, `name`) VALUES ('phn', 'feniciană');
INSERT INTO `country` (`id`, `name`) VALUES ('fj', 'fijiană');
INSERT INTO `country` (`id`, `name`) VALUES ('fil', 'filipineză');
INSERT INTO `country` (`id`, `name`) VALUES ('fi', 'finlandeză');
INSERT INTO `country` (`id`, `name`) VALUES ('nl_BE', 'flamandă');
INSERT INTO `country` (`id`, `name`) VALUES ('fr', 'franceză');
INSERT INTO `country` (`id`, `name`) VALUES ('fr_CA', 'franceză canadiană');
INSERT INTO `country` (`id`, `name`) VALUES ('fr_CH', 'franceză elvețiană');
INSERT INTO `country` (`id`, `name`) VALUES ('fro', 'franceză veche');
INSERT INTO `country` (`id`, `name`) VALUES ('fy', 'frizonă occidentală');
INSERT INTO `country` (`id`, `name`) VALUES ('frs', 'frizonă orientală');
INSERT INTO `country` (`id`, `name`) VALUES ('gd', 'gaelică scoțiană');
INSERT INTO `country` (`id`, `name`) VALUES ('gl', 'galiciană');
INSERT INTO `country` (`id`, `name`) VALUES ('ka', 'georgiană');
INSERT INTO `country` (`id`, `name`) VALUES ('de', 'germană');
INSERT INTO `country` (`id`, `name`) VALUES ('de_AT', 'germană austriacă');
INSERT INTO `country` (`id`, `name`) VALUES ('gsw', 'germană elvețiană');
INSERT INTO `country` (`id`, `name`) VALUES ('de_CH', 'germană standard elvețiană');
INSERT INTO `country` (`id`, `name`) VALUES ('got', 'gotică');
INSERT INTO `country` (`id`, `name`) VALUES ('el', 'greacă');
INSERT INTO `country` (`id`, `name`) VALUES ('grc', 'greacă veche');
INSERT INTO `country` (`id`, `name`) VALUES ('gn', 'guarani');
INSERT INTO `country` (`id`, `name`) VALUES ('gu', 'gujarati');
INSERT INTO `country` (`id`, `name`) VALUES ('ht', 'haitiană');
INSERT INTO `country` (`id`, `name`) VALUES ('ha', 'hausa');
INSERT INTO `country` (`id`, `name`) VALUES ('haw', 'hawaiană');
INSERT INTO `country` (`id`, `name`) VALUES ('hi', 'hindi');
INSERT INTO `country` (`id`, `name`) VALUES ('hit', 'hitită');
INSERT INTO `country` (`id`, `name`) VALUES ('yi', 'idiș');
INSERT INTO `country` (`id`, `name`) VALUES ('ig', 'igbo');
INSERT INTO `country` (`id`, `name`) VALUES ('id', 'indoneziană');
INSERT INTO `country` (`id`, `name`) VALUES ('ia', 'interlingua');
INSERT INTO `country` (`id`, `name`) VALUES ('ie', 'interlingue');
INSERT INTO `country` (`id`, `name`) VALUES ('ik', 'inupiak');
INSERT INTO `country` (`id`, `name`) VALUES ('ga', 'irlandeză');
INSERT INTO `country` (`id`, `name`) VALUES ('sga', 'irlandeză veche');
INSERT INTO `country` (`id`, `name`) VALUES ('is', 'islandeză');
INSERT INTO `country` (`id`, `name`) VALUES ('it', 'italiană');
INSERT INTO `country` (`id`, `name`) VALUES ('jrb', 'iudeo-arabă');
INSERT INTO `country` (`id`, `name`) VALUES ('jpr', 'iudeo-persană');
INSERT INTO `country` (`id`, `name`) VALUES ('ja', 'japoneză');
INSERT INTO `country` (`id`, `name`) VALUES ('jv', 'javaneză');
INSERT INTO `country` (`id`, `name`) VALUES ('kl', 'kalaallisut');
INSERT INTO `country` (`id`, `name`) VALUES ('kn', 'kannada');
INSERT INTO `country` (`id`, `name`) VALUES ('kk', 'kazahă');
INSERT INTO `country` (`id`, `name`) VALUES ('km', 'khmeră');
INSERT INTO `country` (`id`, `name`) VALUES ('rw', 'kinyarwanda');
INSERT INTO `country` (`id`, `name`) VALUES ('rn', 'kirundi');
INSERT INTO `country` (`id`, `name`) VALUES ('ky', 'kîrgîză');
INSERT INTO `country` (`id`, `name`) VALUES ('tlh', 'klingoniană');
INSERT INTO `country` (`id`, `name`) VALUES ('ku', 'kurdă');
INSERT INTO `country` (`id`, `name`) VALUES ('lo', 'laoțiană');
INSERT INTO `country` (`id`, `name`) VALUES ('la', 'latină');
INSERT INTO `country` (`id`, `name`) VALUES ('lv', 'letonă');
INSERT INTO `country` (`id`, `name`) VALUES ('sgn', 'limbaj mimico-gestual');
INSERT INTO `country` (`id`, `name`) VALUES ('afa', 'limbă afro-asiatică');
INSERT INTO `country` (`id`, `name`) VALUES ('tut', 'limbă altaică');
INSERT INTO `country` (`id`, `name`) VALUES ('apa', 'limbă apașă');
INSERT INTO `country` (`id`, `name`) VALUES ('art', 'limbă artificială');
INSERT INTO `country` (`id`, `name`) VALUES ('aus', 'limbă australiană');
INSERT INTO `country` (`id`, `name`) VALUES ('bat', 'limbă baltică');
INSERT INTO `country` (`id`, `name`) VALUES ('cau', 'limbă caucaziană');
INSERT INTO `country` (`id`, `name`) VALUES ('cel', 'limbă celtică');
INSERT INTO `country` (`id`, `name`) VALUES ('cai', 'limbă central-amerindiană');
INSERT INTO `country` (`id`, `name`) VALUES ('dra', 'limbă dravidiană');
INSERT INTO `country` (`id`, `name`) VALUES ('phi', 'limbă filipineză');
INSERT INTO `country` (`id`, `name`) VALUES ('fiu', 'limbă fino-ugrică');
INSERT INTO `country` (`id`, `name`) VALUES ('gem', 'limbă germanică');
INSERT INTO `country` (`id`, `name`) VALUES ('inc', 'limbă indiană');
INSERT INTO `country` (`id`, `name`) VALUES ('ine', 'limbă indo-europeană');
INSERT INTO `country` (`id`, `name`) VALUES ('ira', 'limbă iraniană');
INSERT INTO `country` (`id`, `name`) VALUES ('myn', 'limbă mayașă');
INSERT INTO `country` (`id`, `name`) VALUES ('mun', 'limbă munda');
INSERT INTO `country` (`id`, `name`) VALUES ('und', 'limbă necunoscută sau nevalidă');
INSERT INTO `country` (`id`, `name`) VALUES ('nai', 'limbă nord-amerindiană');
INSERT INTO `country` (`id`, `name`) VALUES ('nub', 'limbă nubiană');
INSERT INTO `country` (`id`, `name`) VALUES ('oto', 'limbă otomi');
INSERT INTO `country` (`id`, `name`) VALUES ('paa', 'limbă papuașă');
INSERT INTO `country` (`id`, `name`) VALUES ('roa', 'limbă romanică');
INSERT INTO `country` (`id`, `name`) VALUES ('sem', 'limbă semitică');
INSERT INTO `country` (`id`, `name`) VALUES ('sit', 'limbă sino-tibetană');
INSERT INTO `country` (`id`, `name`) VALUES ('sla', 'limbă slavă');
INSERT INTO `country` (`id`, `name`) VALUES ('sai', 'limbă sud-amerindiană');
INSERT INTO `country` (`id`, `name`) VALUES ('tai', 'limbă thai');
INSERT INTO `country` (`id`, `name`) VALUES ('mis', 'limbi diverse');
INSERT INTO `country` (`id`, `name`) VALUES ('ln', 'lingala');
INSERT INTO `country` (`id`, `name`) VALUES ('lt', 'lituaniană');
INSERT INTO `country` (`id`, `name`) VALUES ('lb', 'luxemburgheză');
INSERT INTO `country` (`id`, `name`) VALUES ('mk', 'macedoneană');
INSERT INTO `country` (`id`, `name`) VALUES ('hu', 'maghiară');
INSERT INTO `country` (`id`, `name`) VALUES ('ms', 'malay');
INSERT INTO `country` (`id`, `name`) VALUES ('ml', 'malayalam');
INSERT INTO `country` (`id`, `name`) VALUES ('mg', 'malgașă');
INSERT INTO `country` (`id`, `name`) VALUES ('mt', 'malteză');
INSERT INTO `country` (`id`, `name`) VALUES ('mnc', 'manciuriană');
INSERT INTO `country` (`id`, `name`) VALUES ('mi', 'maori');
INSERT INTO `country` (`id`, `name`) VALUES ('mr', 'marathi');
INSERT INTO `country` (`id`, `name`) VALUES ('mwl', 'mirandeză');
INSERT INTO `country` (`id`, `name`) VALUES ('mo', 'moldovenească');
INSERT INTO `country` (`id`, `name`) VALUES ('mn', 'mongolă');
INSERT INTO `country` (`id`, `name`) VALUES ('nap', 'napolitană');
INSERT INTO `country` (`id`, `name`) VALUES ('nv', 'navajo');
INSERT INTO `country` (`id`, `name`) VALUES ('nd', 'ndebele de nord');
INSERT INTO `country` (`id`, `name`) VALUES ('ne', 'nepaleză');
INSERT INTO `country` (`id`, `name`) VALUES ('nb', 'norvegiana bokmål');
INSERT INTO `country` (`id`, `name`) VALUES ('no', 'norvegiană');
INSERT INTO `country` (`id`, `name`) VALUES ('nn', 'norvegiană nynorsk');
INSERT INTO `country` (`id`, `name`) VALUES ('ny', 'nyanja');
INSERT INTO `country` (`id`, `name`) VALUES ('oc', 'occitană');
INSERT INTO `country` (`id`, `name`) VALUES ('nl', 'olandeză');
INSERT INTO `country` (`id`, `name`) VALUES ('or', 'oriya');
INSERT INTO `country` (`id`, `name`) VALUES ('om', 'oromo');
INSERT INTO `country` (`id`, `name`) VALUES ('os', 'osetă');
INSERT INTO `country` (`id`, `name`) VALUES ('pi', 'pali');
INSERT INTO `country` (`id`, `name`) VALUES ('ps', 'pașto');
INSERT INTO `country` (`id`, `name`) VALUES ('fa', 'persană');
INSERT INTO `country` (`id`, `name`) VALUES ('peo', 'persană veche');
INSERT INTO `country` (`id`, `name`) VALUES ('pl', 'poloneză');
INSERT INTO `country` (`id`, `name`) VALUES ('pt', 'portugheză');
INSERT INTO `country` (`id`, `name`) VALUES ('pt_BR', 'portugheză braziliană');
INSERT INTO `country` (`id`, `name`) VALUES ('pt_PT', 'portugheză iberică');
INSERT INTO `country` (`id`, `name`) VALUES ('pro', 'provensală veche');
INSERT INTO `country` (`id`, `name`) VALUES ('pa', 'punjabi');
INSERT INTO `country` (`id`, `name`) VALUES ('qu', 'quechua');
INSERT INTO `country` (`id`, `name`) VALUES ('rm', 'retoromană');
INSERT INTO `country` (`id`, `name`) VALUES ('ro', 'română');
INSERT INTO `country` (`id`, `name`) VALUES ('ru', 'rusă');
INSERT INTO `country` (`id`, `name`) VALUES ('sah', 'sakha');
INSERT INTO `country` (`id`, `name`) VALUES ('se', 'sami de nord');
INSERT INTO `country` (`id`, `name`) VALUES ('sm', 'samoană');
INSERT INTO `country` (`id`, `name`) VALUES ('sg', 'sango');
INSERT INTO `country` (`id`, `name`) VALUES ('sa', 'sanscrită');
INSERT INTO `country` (`id`, `name`) VALUES ('sc', 'sardiniană');
INSERT INTO `country` (`id`, `name`) VALUES ('sr', 'sârbă');
INSERT INTO `country` (`id`, `name`) VALUES ('sh', 'sârbo-croată');
INSERT INTO `country` (`id`, `name`) VALUES ('sco', 'scots');
INSERT INTO `country` (`id`, `name`) VALUES ('st', 'sesotho');
INSERT INTO `country` (`id`, `name`) VALUES ('tn', 'setswana');
INSERT INTO `country` (`id`, `name`) VALUES ('sn', 'shona');
INSERT INTO `country` (`id`, `name`) VALUES ('scn', 'siciliană');
INSERT INTO `country` (`id`, `name`) VALUES ('sd', 'sindhi');
INSERT INTO `country` (`id`, `name`) VALUES ('si', 'singaleză');
INSERT INTO `country` (`id`, `name`) VALUES ('syr', 'siriacă');
INSERT INTO `country` (`id`, `name`) VALUES ('cu', 'slavonă');
INSERT INTO `country` (`id`, `name`) VALUES ('sk', 'slovacă');
INSERT INTO `country` (`id`, `name`) VALUES ('sl', 'slovenă');
INSERT INTO `country` (`id`, `name`) VALUES ('so', 'somaleză');
INSERT INTO `country` (`id`, `name`) VALUES ('nso', 'sotho de nord');
INSERT INTO `country` (`id`, `name`) VALUES ('es', 'spaniolă');
INSERT INTO `country` (`id`, `name`) VALUES ('es_ES', 'spaniolă iberică');
INSERT INTO `country` (`id`, `name`) VALUES ('es_419', 'spaniolă latino-americană');
INSERT INTO `country` (`id`, `name`) VALUES ('sv', 'suedeză');
INSERT INTO `country` (`id`, `name`) VALUES ('sux', 'sumeriană');
INSERT INTO `country` (`id`, `name`) VALUES ('su', 'sundaneză');
INSERT INTO `country` (`id`, `name`) VALUES ('sw', 'swahili');
INSERT INTO `country` (`id`, `name`) VALUES ('ss', 'swati');
INSERT INTO `country` (`id`, `name`) VALUES ('tg', 'tadjică');
INSERT INTO `country` (`id`, `name`) VALUES ('tl', 'tagalog');
INSERT INTO `country` (`id`, `name`) VALUES ('ty', 'tahitiană');
INSERT INTO `country` (`id`, `name`) VALUES ('ta', 'tamilă');
INSERT INTO `country` (`id`, `name`) VALUES ('tt', 'tătară');
INSERT INTO `country` (`id`, `name`) VALUES ('te', 'telugu');
INSERT INTO `country` (`id`, `name`) VALUES ('tet', 'tetum');
INSERT INTO `country` (`id`, `name`) VALUES ('th', 'thailandeză');
INSERT INTO `country` (`id`, `name`) VALUES ('bo', 'tibetană');
INSERT INTO `country` (`id`, `name`) VALUES ('ti', 'tigrinya');
INSERT INTO `country` (`id`, `name`) VALUES ('tpi', 'tok pisin');
INSERT INTO `country` (`id`, `name`) VALUES ('to', 'tonga');
INSERT INTO `country` (`id`, `name`) VALUES ('ts', 'tsonga');
INSERT INTO `country` (`id`, `name`) VALUES ('tr', 'turcă');
INSERT INTO `country` (`id`, `name`) VALUES ('ota', 'turcă otomană');
INSERT INTO `country` (`id`, `name`) VALUES ('tk', 'turkmenă');
INSERT INTO `country` (`id`, `name`) VALUES ('tw', 'twi');
INSERT INTO `country` (`id`, `name`) VALUES ('uk', 'ucraineană');
INSERT INTO `country` (`id`, `name`) VALUES ('ug', 'uigură');
INSERT INTO `country` (`id`, `name`) VALUES ('ur', 'urdu');
INSERT INTO `country` (`id`, `name`) VALUES ('uz', 'uzbecă');
INSERT INTO `country` (`id`, `name`) VALUES ('wa', 'valonă');
INSERT INTO `country` (`id`, `name`) VALUES ('cy', 'velșă');
INSERT INTO `country` (`id`, `name`) VALUES ('ve', 'venda');
INSERT INTO `country` (`id`, `name`) VALUES ('vi', 'vietnameză');
INSERT INTO `country` (`id`, `name`) VALUES ('vo', 'volapuk');
INSERT INTO `country` (`id`, `name`) VALUES ('wo', 'wolof');
INSERT INTO `country` (`id`, `name`) VALUES ('xh', 'xhosa');
INSERT INTO `country` (`id`, `name`) VALUES ('yo', 'yoruba');
INSERT INTO `country` (`id`, `name`) VALUES ('zap', 'zapotecă');
INSERT INTO `country` (`id`, `name`) VALUES ('zu', 'zulu');
