CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('ab', 'abhaasi');
INSERT INTO `country` (`id`, `name`) VALUES ('ada', 'adangme');
INSERT INTO `country` (`id`, `name`) VALUES ('ady', 'adõgee');
INSERT INTO `country` (`id`, `name`) VALUES ('aa', 'afari');
INSERT INTO `country` (`id`, `name`) VALUES ('afh', 'afrihili');
INSERT INTO `country` (`id`, `name`) VALUES ('af', 'afrikaani');
INSERT INTO `country` (`id`, `name`) VALUES ('afa', 'afroaasia keel');
INSERT INTO `country` (`id`, `name`) VALUES ('ay', 'aimara');
INSERT INTO `country` (`id`, `name`) VALUES ('ain', 'ainu');
INSERT INTO `country` (`id`, `name`) VALUES ('akk', 'akadi');
INSERT INTO `country` (`id`, `name`) VALUES ('ak', 'akani');
INSERT INTO `country` (`id`, `name`) VALUES ('ach', 'akoli');
INSERT INTO `country` (`id`, `name`) VALUES ('nds', 'alamsaksa');
INSERT INTO `country` (`id`, `name`) VALUES ('dsb', 'alamsorbi');
INSERT INTO `country` (`id`, `name`) VALUES ('sq', 'albaania');
INSERT INTO `country` (`id`, `name`) VALUES ('gsw', 'alemanni');
INSERT INTO `country` (`id`, `name`) VALUES ('ale', 'aleuudi');
INSERT INTO `country` (`id`, `name`) VALUES ('alg', 'algonkini keel');
INSERT INTO `country` (`id`, `name`) VALUES ('alt', 'altai');
INSERT INTO `country` (`id`, `name`) VALUES ('tut', 'altai keel');
INSERT INTO `country` (`id`, `name`) VALUES ('kj', 'ambo');
INSERT INTO `country` (`id`, `name`) VALUES ('am', 'amhari');
INSERT INTO `country` (`id`, `name`) VALUES ('anp', 'angika');
INSERT INTO `country` (`id`, `name`) VALUES ('apa', 'apatši keel');
INSERT INTO `country` (`id`, `name`) VALUES ('ar', 'araabia');
INSERT INTO `country` (`id`, `name`) VALUES ('an', 'aragoni');
INSERT INTO `country` (`id`, `name`) VALUES ('arc', 'aramea');
INSERT INTO `country` (`id`, `name`) VALUES ('arp', 'arapaho');
INSERT INTO `country` (`id`, `name`) VALUES ('arn', 'araukaani');
INSERT INTO `country` (`id`, `name`) VALUES ('arw', 'aravaki');
INSERT INTO `country` (`id`, `name`) VALUES ('hy', 'armeenia');
INSERT INTO `country` (`id`, `name`) VALUES ('rup', 'aromuuni');
INSERT INTO `country` (`id`, `name`) VALUES ('az', 'aserbaidžaani');
INSERT INTO `country` (`id`, `name`) VALUES ('as', 'assami');
INSERT INTO `country` (`id`, `name`) VALUES ('ast', 'astuuria');
INSERT INTO `country` (`id`, `name`) VALUES ('ath', 'atapaski keeled');
INSERT INTO `country` (`id`, `name`) VALUES ('cch', 'atsami');
INSERT INTO `country` (`id`, `name`) VALUES ('ace', 'atšehi');
INSERT INTO `country` (`id`, `name`) VALUES ('aus', 'austraali keel');
INSERT INTO `country` (`id`, `name`) VALUES ('map', 'austroneesia keel');
INSERT INTO `country` (`id`, `name`) VALUES ('av', 'avaari');
INSERT INTO `country` (`id`, `name`) VALUES ('awa', 'avadhi');
INSERT INTO `country` (`id`, `name`) VALUES ('ae', 'avesta');
INSERT INTO `country` (`id`, `name`) VALUES ('ban', 'bali');
INSERT INTO `country` (`id`, `name`) VALUES ('bat', 'balti keel');
INSERT INTO `country` (`id`, `name`) VALUES ('bm', 'bambara');
INSERT INTO `country` (`id`, `name`) VALUES ('bai', 'bamileke keel');
INSERT INTO `country` (`id`, `name`) VALUES ('bad', 'banda');
INSERT INTO `country` (`id`, `name`) VALUES ('bnt', 'bantu');
INSERT INTO `country` (`id`, `name`) VALUES ('bas', 'basa');
INSERT INTO `country` (`id`, `name`) VALUES ('eu', 'baski');
INSERT INTO `country` (`id`, `name`) VALUES ('ba', 'baškiiri');
INSERT INTO `country` (`id`, `name`) VALUES ('btk', 'bataki');
INSERT INTO `country` (`id`, `name`) VALUES ('bej', 'bedža');
INSERT INTO `country` (`id`, `name`) VALUES ('pau', 'belau');
INSERT INTO `country` (`id`, `name`) VALUES ('bal', 'belutši');
INSERT INTO `country` (`id`, `name`) VALUES ('bem', 'bemba');
INSERT INTO `country` (`id`, `name`) VALUES ('bn', 'bengali');
INSERT INTO `country` (`id`, `name`) VALUES ('ber', 'berberi');
INSERT INTO `country` (`id`, `name`) VALUES ('bho', 'bhodžpuri');
INSERT INTO `country` (`id`, `name`) VALUES ('dz', 'bhutani');
INSERT INTO `country` (`id`, `name`) VALUES ('bh', 'bihaari');
INSERT INTO `country` (`id`, `name`) VALUES ('bik', 'bikoli');
INSERT INTO `country` (`id`, `name`) VALUES ('byn', 'bilini');
INSERT INTO `country` (`id`, `name`) VALUES ('my', 'birma');
INSERT INTO `country` (`id`, `name`) VALUES ('bi', 'bislama');
INSERT INTO `country` (`id`, `name`) VALUES ('bs', 'bosnia');
INSERT INTO `country` (`id`, `name`) VALUES ('bra', 'bradži');
INSERT INTO `country` (`id`, `name`) VALUES ('br', 'bretooni');
INSERT INTO `country` (`id`, `name`) VALUES ('bug', 'bugi');
INSERT INTO `country` (`id`, `name`) VALUES ('bg', 'bulgaaria');
INSERT INTO `country` (`id`, `name`) VALUES ('bua', 'burjaadi');
INSERT INTO `country` (`id`, `name`) VALUES ('day', 'dajaki');
INSERT INTO `country` (`id`, `name`) VALUES ('dar', 'dargi');
INSERT INTO `country` (`id`, `name`) VALUES ('del', 'delavari');
INSERT INTO `country` (`id`, `name`) VALUES ('din', 'dinka');
INSERT INTO `country` (`id`, `name`) VALUES ('dyu', 'djula');
INSERT INTO `country` (`id`, `name`) VALUES ('doi', 'dogri');
INSERT INTO `country` (`id`, `name`) VALUES ('dgr', 'dogribi');
INSERT INTO `country` (`id`, `name`) VALUES ('dra', 'draviidi keel');
INSERT INTO `country` (`id`, `name`) VALUES ('dua', 'duala');
INSERT INTO `country` (`id`, `name`) VALUES ('bin', 'edo');
INSERT INTO `country` (`id`, `name`) VALUES ('elx', 'eelami');
INSERT INTO `country` (`id`, `name`) VALUES ('et', 'eesti');
INSERT INTO `country` (`id`, `name`) VALUES ('eka', 'ekadžuki');
INSERT INTO `country` (`id`, `name`) VALUES ('myv', 'ersa');
INSERT INTO `country` (`id`, `name`) VALUES ('eo', 'esperanto');
INSERT INTO `country` (`id`, `name`) VALUES ('gez', 'etioopia');
INSERT INTO `country` (`id`, `name`) VALUES ('ee', 'eve');
INSERT INTO `country` (`id`, `name`) VALUES ('ewo', 'evondo');
INSERT INTO `country` (`id`, `name`) VALUES ('fan', 'fangi');
INSERT INTO `country` (`id`, `name`) VALUES ('fat', 'fanti');
INSERT INTO `country` (`id`, `name`) VALUES ('fj', 'fidži');
INSERT INTO `country` (`id`, `name`) VALUES ('phi', 'filipiini keel');
INSERT INTO `country` (`id`, `name`) VALUES ('fil', 'filipino');
INSERT INTO `country` (`id`, `name`) VALUES ('nl_BE', 'flaami');
INSERT INTO `country` (`id`, `name`) VALUES ('phn', 'foiniikia');
INSERT INTO `country` (`id`, `name`) VALUES ('fon', 'foni');
INSERT INTO `country` (`id`, `name`) VALUES ('fur', 'friuuli');
INSERT INTO `country` (`id`, `name`) VALUES ('ff', 'fulbe');
INSERT INTO `country` (`id`, `name`) VALUES ('fo', 'fääri');
INSERT INTO `country` (`id`, `name`) VALUES ('gd', 'gaeli');
INSERT INTO `country` (`id`, `name`) VALUES ('gay', 'gajo');
INSERT INTO `country` (`id`, `name`) VALUES ('gl', 'galeegi');
INSERT INTO `country` (`id`, `name`) VALUES ('lg', 'ganda');
INSERT INTO `country` (`id`, `name`) VALUES ('gba', 'gbaja');
INSERT INTO `country` (`id`, `name`) VALUES ('gem', 'germaani keel');
INSERT INTO `country` (`id`, `name`) VALUES ('gon', 'gondi');
INSERT INTO `country` (`id`, `name`) VALUES ('got', 'gooti');
INSERT INTO `country` (`id`, `name`) VALUES ('gor', 'gorontalo');
INSERT INTO `country` (`id`, `name`) VALUES ('grb', 'grebo');
INSERT INTO `country` (`id`, `name`) VALUES ('ka', 'gruusia');
INSERT INTO `country` (`id`, `name`) VALUES ('kl', 'grööni');
INSERT INTO `country` (`id`, `name`) VALUES ('gn', 'guaranii');
INSERT INTO `country` (`id`, `name`) VALUES ('gu', 'gudžarati');
INSERT INTO `country` (`id`, `name`) VALUES ('gwi', 'gvitšini');
INSERT INTO `country` (`id`, `name`) VALUES ('hai', 'haida');
INSERT INTO `country` (`id`, `name`) VALUES ('ht', 'haiti');
INSERT INTO `country` (`id`, `name`) VALUES ('ha', 'hausa');
INSERT INTO `country` (`id`, `name`) VALUES ('haw', 'havai');
INSERT INTO `country` (`id`, `name`) VALUES ('he', 'heebrea');
INSERT INTO `country` (`id`, `name`) VALUES ('hz', 'herero');
INSERT INTO `country` (`id`, `name`) VALUES ('hit', 'heti');
INSERT INTO `country` (`id`, `name`) VALUES ('zh', 'hiina');
INSERT INTO `country` (`id`, `name`) VALUES ('zh_Hans', 'hiina keel - lihtsustatud');
INSERT INTO `country` (`id`, `name`) VALUES ('zh_Hant', 'hiina keel - traditsiooniline');
INSERT INTO `country` (`id`, `name`) VALUES ('sit', 'hiina-tiibeti keel');
INSERT INTO `country` (`id`, `name`) VALUES ('hil', 'hiligainoni');
INSERT INTO `country` (`id`, `name`) VALUES ('him', 'himtšali');
INSERT INTO `country` (`id`, `name`) VALUES ('hi', 'hindi');
INSERT INTO `country` (`id`, `name`) VALUES ('es', 'hispaania');
INSERT INTO `country` (`id`, `name`) VALUES ('es_ES', 'hispaania (Ibeeria)');
INSERT INTO `country` (`id`, `name`) VALUES ('hmn', 'hmongi');
INSERT INTO `country` (`id`, `name`) VALUES ('nl', 'hollandi');
INSERT INTO `country` (`id`, `name`) VALUES ('hr', 'horvaadi');
INSERT INTO `country` (`id`, `name`) VALUES ('hup', 'hupa');
INSERT INTO `country` (`id`, `name`) VALUES ('iba', 'ibani');
INSERT INTO `country` (`id`, `name`) VALUES ('efi', 'ibibio');
INSERT INTO `country` (`id`, `name`) VALUES ('ig', 'ibo');
INSERT INTO `country` (`id`, `name`) VALUES ('frs', 'idafriisi');
INSERT INTO `country` (`id`, `name`) VALUES ('io', 'ido');
INSERT INTO `country` (`id`, `name`) VALUES ('ijo', 'idžo');
INSERT INTO `country` (`id`, `name`) VALUES ('ga', 'iiri');
INSERT INTO `country` (`id`, `name`) VALUES ('ilo', 'iloko');
INSERT INTO `country` (`id`, `name`) VALUES ('smn', 'inari saami');
INSERT INTO `country` (`id`, `name`) VALUES ('inc', 'india keel');
INSERT INTO `country` (`id`, `name`) VALUES ('ine', 'indoeuroopa keel');
INSERT INTO `country` (`id`, `name`) VALUES ('id', 'indoneesia');
INSERT INTO `country` (`id`, `name`) VALUES ('en', 'inglise');
INSERT INTO `country` (`id`, `name`) VALUES ('en_GB', 'inglise (Briti)');
INSERT INTO `country` (`id`, `name`) VALUES ('en_US', 'inglise (USA)');
INSERT INTO `country` (`id`, `name`) VALUES ('cpe', 'inglispõhjalised kreool- ja pidžinkeeled');
INSERT INTO `country` (`id`, `name`) VALUES ('inh', 'inguši');
INSERT INTO `country` (`id`, `name`) VALUES ('ik', 'injupiaki');
INSERT INTO `country` (`id`, `name`) VALUES ('ia', 'interlingua');
INSERT INTO `country` (`id`, `name`) VALUES ('ie', 'interlingue');
INSERT INTO `country` (`id`, `name`) VALUES ('iu', 'inuktituti');
INSERT INTO `country` (`id`, `name`) VALUES ('ira', 'iraani keeled');
INSERT INTO `country` (`id`, `name`) VALUES ('iro', 'irokeesi keel');
INSERT INTO `country` (`id`, `name`) VALUES ('is', 'islandi');
INSERT INTO `country` (`id`, `name`) VALUES ('it', 'itaalia');
INSERT INTO `country` (`id`, `name`) VALUES ('ja', 'jaapani');
INSERT INTO `country` (`id`, `name`) VALUES ('jv', 'jaava');
INSERT INTO `country` (`id`, `name`) VALUES ('sah', 'jakuudi');
INSERT INTO `country` (`id`, `name`) VALUES ('yao', 'jao');
INSERT INTO `country` (`id`, `name`) VALUES ('yap', 'japi');
INSERT INTO `country` (`id`, `name`) VALUES ('yi', 'jidiši');
INSERT INTO `country` (`id`, `name`) VALUES ('kaj', 'jju');
INSERT INTO `country` (`id`, `name`) VALUES ('yo', 'joruba');
INSERT INTO `country` (`id`, `name`) VALUES ('ypk', 'jupiki keel');
INSERT INTO `country` (`id`, `name`) VALUES ('jrb', 'juudiaraabia');
INSERT INTO `country` (`id`, `name`) VALUES ('jpr', 'juudipärsia');
INSERT INTO `country` (`id`, `name`) VALUES ('kaw', 'kaavi');
INSERT INTO `country` (`id`, `name`) VALUES ('kbd', 'kabardi-tšerkessi');
INSERT INTO `country` (`id`, `name`) VALUES ('kab', 'kabiili');
INSERT INTO `country` (`id`, `name`) VALUES ('cad', 'kado');
INSERT INTO `country` (`id`, `name`) VALUES ('xal', 'kalmõki');
INSERT INTO `country` (`id`, `name`) VALUES ('kam', 'kamba');
INSERT INTO `country` (`id`, `name`) VALUES ('kn', 'kannada');
INSERT INTO `country` (`id`, `name`) VALUES ('yue', 'kantoni');
INSERT INTO `country` (`id`, `name`) VALUES ('kr', 'kanuri');
INSERT INTO `country` (`id`, `name`) VALUES ('kaa', 'karakalpaki');
INSERT INTO `country` (`id`, `name`) VALUES ('krc', 'karatšai-balkaari');
INSERT INTO `country` (`id`, `name`) VALUES ('kar', 'kareni keel');
INSERT INTO `country` (`id`, `name`) VALUES ('car', 'kariibi');
INSERT INTO `country` (`id`, `name`) VALUES ('krl', 'karjala');
INSERT INTO `country` (`id`, `name`) VALUES ('kk', 'kasahhi');
INSERT INTO `country` (`id`, `name`) VALUES ('ks', 'kašmiiri');
INSERT INTO `country` (`id`, `name`) VALUES ('csb', 'kašuubi');
INSERT INTO `country` (`id`, `name`) VALUES ('ca', 'katalaani');
INSERT INTO `country` (`id`, `name`) VALUES ('kac', 'katšini');
INSERT INTO `country` (`id`, `name`) VALUES ('cau', 'kaukaasia keel');
INSERT INTO `country` (`id`, `name`) VALUES ('cel', 'keldi keel');
INSERT INTO `country` (`id`, `name`) VALUES ('cai', 'Kesk-Ameerika indiaani keel');
INSERT INTO `country` (`id`, `name`) VALUES ('dum', 'keskhollandi');
INSERT INTO `country` (`id`, `name`) VALUES ('mga', 'keskiiri');
INSERT INTO `country` (`id`, `name`) VALUES ('enm', 'keskinglise');
INSERT INTO `country` (`id`, `name`) VALUES ('frm', 'keskprantsuse');
INSERT INTO `country` (`id`, `name`) VALUES ('gmh', 'keskülemsaksa');
INSERT INTO `country` (`id`, `name`) VALUES ('qu', 'ketšua');
INSERT INTO `country` (`id`, `name`) VALUES ('kha', 'khasi');
INSERT INTO `country` (`id`, `name`) VALUES ('km', 'khmeeri');
INSERT INTO `country` (`id`, `name`) VALUES ('khi', 'khoisani keel');
INSERT INTO `country` (`id`, `name`) VALUES ('ki', 'kikuju');
INSERT INTO `country` (`id`, `name`) VALUES ('ky', 'kirgiisi');
INSERT INTO `country` (`id`, `name`) VALUES ('gil', 'kiribati');
INSERT INTO `country` (`id`, `name`) VALUES ('cu', 'kirikuslaavi');
INSERT INTO `country` (`id`, `name`) VALUES ('tlh', 'klingoni');
INSERT INTO `country` (`id`, `name`) VALUES ('sms', 'koltasaami');
INSERT INTO `country` (`id`, `name`) VALUES ('kv', 'komi');
INSERT INTO `country` (`id`, `name`) VALUES ('swb', 'komoori');
INSERT INTO `country` (`id`, `name`) VALUES ('kg', 'kongo');
INSERT INTO `country` (`id`, `name`) VALUES ('kok', 'konkani');
INSERT INTO `country` (`id`, `name`) VALUES ('xh', 'koosa');
INSERT INTO `country` (`id`, `name`) VALUES ('cop', 'kopti');
INSERT INTO `country` (`id`, `name`) VALUES ('ko', 'korea');
INSERT INTO `country` (`id`, `name`) VALUES ('kw', 'korni');
INSERT INTO `country` (`id`, `name`) VALUES ('kfo', 'koro');
INSERT INTO `country` (`id`, `name`) VALUES ('co', 'korsika');
INSERT INTO `country` (`id`, `name`) VALUES ('kos', 'kosrae');
INSERT INTO `country` (`id`, `name`) VALUES ('kpe', 'kpelle');
INSERT INTO `country` (`id`, `name`) VALUES ('el', 'kreeka');
INSERT INTO `country` (`id`, `name`) VALUES ('crp', 'kreool- või pidžinkeel');
INSERT INTO `country` (`id`, `name`) VALUES ('cr', 'krii');
INSERT INTO `country` (`id`, `name`) VALUES ('crh', 'krimmitatari');
INSERT INTO `country` (`id`, `name`) VALUES ('kro', 'kruu');
INSERT INTO `country` (`id`, `name`) VALUES ('kum', 'kumõki');
INSERT INTO `country` (`id`, `name`) VALUES ('ku', 'kurdi');
INSERT INTO `country` (`id`, `name`) VALUES ('kut', 'kutenai');
INSERT INTO `country` (`id`, `name`) VALUES ('cy', 'kõmri');
INSERT INTO `country` (`id`, `name`) VALUES ('lad', 'ladiino');
INSERT INTO `country` (`id`, `name`) VALUES ('la', 'ladina');
INSERT INTO `country` (`id`, `name`) VALUES ('lah', 'lahnda');
INSERT INTO `country` (`id`, `name`) VALUES ('lam', 'lamba');
INSERT INTO `country` (`id`, `name`) VALUES ('lo', 'lao');
INSERT INTO `country` (`id`, `name`) VALUES ('lt', 'leedu');
INSERT INTO `country` (`id`, `name`) VALUES ('lez', 'lesgi');
INSERT INTO `country` (`id`, `name`) VALUES ('lb', 'letseburgi');
INSERT INTO `country` (`id`, `name`) VALUES ('li', 'limburgi');
INSERT INTO `country` (`id`, `name`) VALUES ('ln', 'lingala');
INSERT INTO `country` (`id`, `name`) VALUES ('jbo', 'lojbani');
INSERT INTO `country` (`id`, `name`) VALUES ('loz', 'lozi');
INSERT INTO `country` (`id`, `name`) VALUES ('lu', 'luba');
INSERT INTO `country` (`id`, `name`) VALUES ('lui', 'luisenjo');
INSERT INTO `country` (`id`, `name`) VALUES ('smj', 'lule saami');
INSERT INTO `country` (`id`, `name`) VALUES ('lua', 'lulua');
INSERT INTO `country` (`id`, `name`) VALUES ('lun', 'lunda');
INSERT INTO `country` (`id`, `name`) VALUES ('luo', 'luo');
INSERT INTO `country` (`id`, `name`) VALUES ('lus', 'lušei');
INSERT INTO `country` (`id`, `name`) VALUES ('sai', 'Lõuna-Ameerika indiaani keel');
INSERT INTO `country` (`id`, `name`) VALUES ('nr', 'lõunandebele');
INSERT INTO `country` (`id`, `name`) VALUES ('sma', 'lõunasaami');
INSERT INTO `country` (`id`, `name`) VALUES ('st', 'lõunasotho');
INSERT INTO `country` (`id`, `name`) VALUES ('lv', 'läti');
INSERT INTO `country` (`id`, `name`) VALUES ('fy', 'läänefriisi');
INSERT INTO `country` (`id`, `name`) VALUES ('mad', 'madura');
INSERT INTO `country` (`id`, `name`) VALUES ('mag', 'magali');
INSERT INTO `country` (`id`, `name`) VALUES ('myn', 'maia keeled');
INSERT INTO `country` (`id`, `name`) VALUES ('mai', 'maithili');
INSERT INTO `country` (`id`, `name`) VALUES ('mak', 'makassari');
INSERT INTO `country` (`id`, `name`) VALUES ('mk', 'makedoonia');
INSERT INTO `country` (`id`, `name`) VALUES ('mg', 'malagassi');
INSERT INTO `country` (`id`, `name`) VALUES ('ms', 'malai');
INSERT INTO `country` (`id`, `name`) VALUES ('ml', 'malajalami');
INSERT INTO `country` (`id`, `name`) VALUES ('dv', 'maldiivi');
INSERT INTO `country` (`id`, `name`) VALUES ('man', 'malinke');
INSERT INTO `country` (`id`, `name`) VALUES ('mt', 'malta');
INSERT INTO `country` (`id`, `name`) VALUES ('mdr', 'mandari');
INSERT INTO `country` (`id`, `name`) VALUES ('mnc', 'mandžu');
INSERT INTO `country` (`id`, `name`) VALUES ('mni', 'manipuri');
INSERT INTO `country` (`id`, `name`) VALUES ('mno', 'manobo keel');
INSERT INTO `country` (`id`, `name`) VALUES ('mi', 'maoori');
INSERT INTO `country` (`id`, `name`) VALUES ('mr', 'marathi');
INSERT INTO `country` (`id`, `name`) VALUES ('chm', 'mari');
INSERT INTO `country` (`id`, `name`) VALUES ('mh', 'maršalli');
INSERT INTO `country` (`id`, `name`) VALUES ('mwr', 'marvari');
INSERT INTO `country` (`id`, `name`) VALUES ('mas', 'masai');
INSERT INTO `country` (`id`, `name`) VALUES ('mus', 'maskogi');
INSERT INTO `country` (`id`, `name`) VALUES ('kmb', 'mbundu');
INSERT INTO `country` (`id`, `name`) VALUES ('men', 'mende');
INSERT INTO `country` (`id`, `name`) VALUES ('mic', 'mikmaki');
INSERT INTO `country` (`id`, `name`) VALUES ('min', 'minangkabau');
INSERT INTO `country` (`id`, `name`) VALUES ('mwl', 'miranda');
INSERT INTO `country` (`id`, `name`) VALUES ('zxx', 'mittekeeleline');
INSERT INTO `country` (`id`, `name`) VALUES ('moh', 'mohoogi');
INSERT INTO `country` (`id`, `name`) VALUES ('mdf', 'mokša');
INSERT INTO `country` (`id`, `name`) VALUES ('mo', 'moldova');
INSERT INTO `country` (`id`, `name`) VALUES ('lol', 'mongo');
INSERT INTO `country` (`id`, `name`) VALUES ('mn', 'mongoli');
INSERT INTO `country` (`id`, `name`) VALUES ('mkh', 'moni-khmeeri keel');
INSERT INTO `country` (`id`, `name`) VALUES ('mos', 'more');
INSERT INTO `country` (`id`, `name`) VALUES ('ho', 'motu');
INSERT INTO `country` (`id`, `name`) VALUES ('egy', 'muinasegiptuse');
INSERT INTO `country` (`id`, `name`) VALUES ('mun', 'munda keel');
INSERT INTO `country` (`id`, `name`) VALUES ('rom', 'mustlaskeel');
INSERT INTO `country` (`id`, `name`) VALUES ('cus', 'muu kuši keel');
INSERT INTO `country` (`id`, `name`) VALUES ('smi', 'muu saami');
INSERT INTO `country` (`id`, `name`) VALUES ('art', 'muu tehiskeel');
INSERT INTO `country` (`id`, `name`) VALUES ('gv', 'mänksi');
INSERT INTO `country` (`id`, `name`) VALUES ('und', 'määramata');
INSERT INTO `country` (`id`, `name`) VALUES ('nah', 'nahua');
INSERT INTO `country` (`id`, `name`) VALUES ('nap', 'napoli');
INSERT INTO `country` (`id`, `name`) VALUES ('na', 'nauru');
INSERT INTO `country` (`id`, `name`) VALUES ('nv', 'navaho');
INSERT INTO `country` (`id`, `name`) VALUES ('ng', 'ndonga');
INSERT INTO `country` (`id`, `name`) VALUES ('ne', 'nepali');
INSERT INTO `country` (`id`, `name`) VALUES ('new', 'nevari');
INSERT INTO `country` (`id`, `name`) VALUES ('nia', 'niasi');
INSERT INTO `country` (`id`, `name`) VALUES ('nic', 'Nigeri-Kordofani keel');
INSERT INTO `country` (`id`, `name`) VALUES ('ssa', 'Niiluse-Sahara keel');
INSERT INTO `country` (`id`, `name`) VALUES ('niu', 'niue');
INSERT INTO `country` (`id`, `name`) VALUES ('nym', 'njamvesi');
INSERT INTO `country` (`id`, `name`) VALUES ('ny', 'njandža');
INSERT INTO `country` (`id`, `name`) VALUES ('nyo', 'njoro');
INSERT INTO `country` (`id`, `name`) VALUES ('nyn', 'nkole');
INSERT INTO `country` (`id`, `name`) VALUES ('nqo', 'nkoo');
INSERT INTO `country` (`id`, `name`) VALUES ('nog', 'nogai');
INSERT INTO `country` (`id`, `name`) VALUES ('no', 'norra');
INSERT INTO `country` (`id`, `name`) VALUES ('nb', 'norra bokmål');
INSERT INTO `country` (`id`, `name`) VALUES ('nn', 'norra nynorsk');
INSERT INTO `country` (`id`, `name`) VALUES ('nzi', 'nzima');
INSERT INTO `country` (`id`, `name`) VALUES ('nub', 'nuubia keel');
INSERT INTO `country` (`id`, `name`) VALUES ('oj', 'odžibvei');
INSERT INTO `country` (`id`, `name`) VALUES ('oc', 'oksitaani');
INSERT INTO `country` (`id`, `name`) VALUES ('kru', 'oraoni');
INSERT INTO `country` (`id`, `name`) VALUES ('or', 'oria');
INSERT INTO `country` (`id`, `name`) VALUES ('om', 'oromo');
INSERT INTO `country` (`id`, `name`) VALUES ('osa', 'oseidži');
INSERT INTO `country` (`id`, `name`) VALUES ('ota', 'osmanitürgi');
INSERT INTO `country` (`id`, `name`) VALUES ('os', 'osseedi');
INSERT INTO `country` (`id`, `name`) VALUES ('oto', 'otomi keel');
INSERT INTO `country` (`id`, `name`) VALUES ('pi', 'paali');
INSERT INTO `country` (`id`, `name`) VALUES ('paa', 'paapua keel');
INSERT INTO `country` (`id`, `name`) VALUES ('pal', 'pahlavi');
INSERT INTO `country` (`id`, `name`) VALUES ('pam', 'pampanga');
INSERT INTO `country` (`id`, `name`) VALUES ('pa', 'pandžabi');
INSERT INTO `country` (`id`, `name`) VALUES ('pag', 'pangasinani');
INSERT INTO `country` (`id`, `name`) VALUES ('pap', 'papiamento');
INSERT INTO `country` (`id`, `name`) VALUES ('nso', 'pedi');
INSERT INTO `country` (`id`, `name`) VALUES ('pl', 'poola');
INSERT INTO `country` (`id`, `name`) VALUES ('pon', 'poonpei');
INSERT INTO `country` (`id`, `name`) VALUES ('pt', 'portugali');
INSERT INTO `country` (`id`, `name`) VALUES ('pt_PT', 'portugali (Ibeeria)');
INSERT INTO `country` (`id`, `name`) VALUES ('cpp', 'portugalipõhjalised kreooli-/pidžinkeeled');
INSERT INTO `country` (`id`, `name`) VALUES ('pra', 'praakriti keel');
INSERT INTO `country` (`id`, `name`) VALUES ('fr', 'prantsuse');
INSERT INTO `country` (`id`, `name`) VALUES ('cpf', 'prantsuspõhjalised kreool- ja pidžinkeeled');
INSERT INTO `country` (`id`, `name`) VALUES ('ps', 'puštu');
INSERT INTO `country` (`id`, `name`) VALUES ('nai', 'Põhja-Ameerika indiaani keel');
INSERT INTO `country` (`id`, `name`) VALUES ('frr', 'põhjafriisi');
INSERT INTO `country` (`id`, `name`) VALUES ('nd', 'põhjandebele');
INSERT INTO `country` (`id`, `name`) VALUES ('se', 'põhjasaami');
INSERT INTO `country` (`id`, `name`) VALUES ('fa', 'pärsia');
INSERT INTO `country` (`id`, `name`) VALUES ('raj', 'radžastani');
INSERT INTO `country` (`id`, `name`) VALUES ('rap', 'rapanui');
INSERT INTO `country` (`id`, `name`) VALUES ('rar', 'rarotonga');
INSERT INTO `country` (`id`, `name`) VALUES ('rm', 'retoromaani');
INSERT INTO `country` (`id`, `name`) VALUES ('roa', 'romaani keel');
INSERT INTO `country` (`id`, `name`) VALUES ('sv', 'rootsi');
INSERT INTO `country` (`id`, `name`) VALUES ('rw', 'ruanda');
INSERT INTO `country` (`id`, `name`) VALUES ('ro', 'rumeenia');
INSERT INTO `country` (`id`, `name`) VALUES ('rn', 'rundi');
INSERT INTO `country` (`id`, `name`) VALUES ('kho', 'saki');
INSERT INTO `country` (`id`, `name`) VALUES ('de', 'saksa');
INSERT INTO `country` (`id`, `name`) VALUES ('de_CH', 'saksa (kõrgsaksa)');
INSERT INTO `country` (`id`, `name`) VALUES ('sal', 'sališi keel');
INSERT INTO `country` (`id`, `name`) VALUES ('sam', 'samaaria aramea');
INSERT INTO `country` (`id`, `name`) VALUES ('sm', 'samoa');
INSERT INTO `country` (`id`, `name`) VALUES ('sad', 'sandave');
INSERT INTO `country` (`id`, `name`) VALUES ('sg', 'sango');
INSERT INTO `country` (`id`, `name`) VALUES ('sa', 'sanskriti');
INSERT INTO `country` (`id`, `name`) VALUES ('sat', 'santali');
INSERT INTO `country` (`id`, `name`) VALUES ('zap', 'sapoteegi');
INSERT INTO `country` (`id`, `name`) VALUES ('sc', 'sardiinia');
INSERT INTO `country` (`id`, `name`) VALUES ('sas', 'sasaki');
INSERT INTO `country` (`id`, `name`) VALUES ('ceb', 'sebu');
INSERT INTO `country` (`id`, `name`) VALUES ('sem', 'semi keel');
INSERT INTO `country` (`id`, `name`) VALUES ('sr', 'serbia');
INSERT INTO `country` (`id`, `name`) VALUES ('sh', 'serbia-horvaadi');
INSERT INTO `country` (`id`, `name`) VALUES ('srr', 'sereri');
INSERT INTO `country` (`id`, `name`) VALUES ('ii', 'sichuani jii');
INSERT INTO `country` (`id`, `name`) VALUES ('sid', 'sidamo');
INSERT INTO `country` (`id`, `name`) VALUES ('bla', 'siksika');
INSERT INTO `country` (`id`, `name`) VALUES ('sd', 'sindhi');
INSERT INTO `country` (`id`, `name`) VALUES ('si', 'singali');
INSERT INTO `country` (`id`, `name`) VALUES ('scn', 'sitsiilia');
INSERT INTO `country` (`id`, `name`) VALUES ('dak', 'siuu');
INSERT INTO `country` (`id`, `name`) VALUES ('sio', 'siuu keel');
INSERT INTO `country` (`id`, `name`) VALUES ('sla', 'slaavi keel');
INSERT INTO `country` (`id`, `name`) VALUES ('den', 'sleivi');
INSERT INTO `country` (`id`, `name`) VALUES ('sk', 'slovaki');
INSERT INTO `country` (`id`, `name`) VALUES ('sl', 'sloveeni');
INSERT INTO `country` (`id`, `name`) VALUES ('sog', 'sogdi');
INSERT INTO `country` (`id`, `name`) VALUES ('so', 'somaali');
INSERT INTO `country` (`id`, `name`) VALUES ('son', 'songai');
INSERT INTO `country` (`id`, `name`) VALUES ('snk', 'soninke');
INSERT INTO `country` (`id`, `name`) VALUES ('fi', 'soome');
INSERT INTO `country` (`id`, `name`) VALUES ('fiu', 'soomeugri keel');
INSERT INTO `country` (`id`, `name`) VALUES ('wen', 'sorbi keel');
INSERT INTO `country` (`id`, `name`) VALUES ('srn', 'sranani');
INSERT INTO `country` (`id`, `name`) VALUES ('sw', 'suahiili');
INSERT INTO `country` (`id`, `name`) VALUES ('suk', 'sukuma');
INSERT INTO `country` (`id`, `name`) VALUES ('sux', 'sumeri');
INSERT INTO `country` (`id`, `name`) VALUES ('su', 'sunda');
INSERT INTO `country` (`id`, `name`) VALUES ('zun', 'sunji');
INSERT INTO `country` (`id`, `name`) VALUES ('sus', 'susu');
INSERT INTO `country` (`id`, `name`) VALUES ('zu', 'suulu');
INSERT INTO `country` (`id`, `name`) VALUES ('ss', 'svaasi');
INSERT INTO `country` (`id`, `name`) VALUES ('sel', 'sölkupi');
INSERT INTO `country` (`id`, `name`) VALUES ('syr', 'süüria');
INSERT INTO `country` (`id`, `name`) VALUES ('chy', 'šaieeni');
INSERT INTO `country` (`id`, `name`) VALUES ('shn', 'šani');
INSERT INTO `country` (`id`, `name`) VALUES ('sn', 'šona');
INSERT INTO `country` (`id`, `name`) VALUES ('sco', 'šoti');
INSERT INTO `country` (`id`, `name`) VALUES ('znd', 'zande');
INSERT INTO `country` (`id`, `name`) VALUES ('zen', 'zenaga');
INSERT INTO `country` (`id`, `name`) VALUES ('da', 'taani');
INSERT INTO `country` (`id`, `name`) VALUES ('tg', 'tadžiki');
INSERT INTO `country` (`id`, `name`) VALUES ('tl', 'tagalogi');
INSERT INTO `country` (`id`, `name`) VALUES ('ty', 'tahiti');
INSERT INTO `country` (`id`, `name`) VALUES ('th', 'tai');
INSERT INTO `country` (`id`, `name`) VALUES ('tai', 'tai keel');
INSERT INTO `country` (`id`, `name`) VALUES ('tmh', 'tamašeki');
INSERT INTO `country` (`id`, `name`) VALUES ('ta', 'tamili');
INSERT INTO `country` (`id`, `name`) VALUES ('tt', 'tatari');
INSERT INTO `country` (`id`, `name`) VALUES ('te', 'telugu');
INSERT INTO `country` (`id`, `name`) VALUES ('tem', 'temne');
INSERT INTO `country` (`id`, `name`) VALUES ('ter', 'tereno');
INSERT INTO `country` (`id`, `name`) VALUES ('tet', 'tetumi');
INSERT INTO `country` (`id`, `name`) VALUES ('tig', 'tigree');
INSERT INTO `country` (`id`, `name`) VALUES ('ti', 'tigrinja');
INSERT INTO `country` (`id`, `name`) VALUES ('bo', 'tiibeti');
INSERT INTO `country` (`id`, `name`) VALUES ('tiv', 'tivi');
INSERT INTO `country` (`id`, `name`) VALUES ('tli', 'tlingiti');
INSERT INTO `country` (`id`, `name`) VALUES ('tkl', 'tokelau');
INSERT INTO `country` (`id`, `name`) VALUES ('to', 'tonga');
INSERT INTO `country` (`id`, `name`) VALUES ('ts', 'tsonga');
INSERT INTO `country` (`id`, `name`) VALUES ('tn', 'tsvana');
INSERT INTO `country` (`id`, `name`) VALUES ('chg', 'tšagatai');
INSERT INTO `country` (`id`, `name`) VALUES ('cmc', 'tšami keeled');
INSERT INTO `country` (`id`, `name`) VALUES ('ch', 'tšamorro');
INSERT INTO `country` (`id`, `name`) VALUES ('cs', 'tšehhi');
INSERT INTO `country` (`id`, `name`) VALUES ('chr', 'tšerokii');
INSERT INTO `country` (`id`, `name`) VALUES ('ce', 'tšetšeeni');
INSERT INTO `country` (`id`, `name`) VALUES ('chb', 'tšibtša');
INSERT INTO `country` (`id`, `name`) VALUES ('tsi', 'tšimši');
INSERT INTO `country` (`id`, `name`) VALUES ('chn', 'tšinuki žargoon');
INSERT INTO `country` (`id`, `name`) VALUES ('chp', 'tšipevai');
INSERT INTO `country` (`id`, `name`) VALUES ('tog', 'tšitonga');
INSERT INTO `country` (`id`, `name`) VALUES ('cho', 'tšokto');
INSERT INTO `country` (`id`, `name`) VALUES ('za', 'tšuangi');
INSERT INTO `country` (`id`, `name`) VALUES ('chk', 'tšuugi');
INSERT INTO `country` (`id`, `name`) VALUES ('cv', 'tšuvaši');
INSERT INTO `country` (`id`, `name`) VALUES ('tum', 'tumbuka');
INSERT INTO `country` (`id`, `name`) VALUES ('tup', 'tupii keeled');
INSERT INTO `country` (`id`, `name`) VALUES ('tvl', 'tuvalu');
INSERT INTO `country` (`id`, `name`) VALUES ('tw', 'tvii');
INSERT INTO `country` (`id`, `name`) VALUES ('tyv', 'tõva');
INSERT INTO `country` (`id`, `name`) VALUES ('tr', 'türgi');
INSERT INTO `country` (`id`, `name`) VALUES ('tk', 'türkmeeni');
INSERT INTO `country` (`id`, `name`) VALUES ('kcg', 'tyapi');
INSERT INTO `country` (`id`, `name`) VALUES ('udm', 'udmurdi');
INSERT INTO `country` (`id`, `name`) VALUES ('uga', 'ugariti');
INSERT INTO `country` (`id`, `name`) VALUES ('ug', 'uiguuri');
INSERT INTO `country` (`id`, `name`) VALUES ('uk', 'ukraina');
INSERT INTO `country` (`id`, `name`) VALUES ('umb', 'umbundu');
INSERT INTO `country` (`id`, `name`) VALUES ('hu', 'ungari');
INSERT INTO `country` (`id`, `name`) VALUES ('ur', 'urdu');
INSERT INTO `country` (`id`, `name`) VALUES ('uz', 'usbeki');
INSERT INTO `country` (`id`, `name`) VALUES ('tpi', 'uusmelaneesia');
INSERT INTO `country` (`id`, `name`) VALUES ('vot', 'vadja');
INSERT INTO `country` (`id`, `name`) VALUES ('vai', 'vai');
INSERT INTO `country` (`id`, `name`) VALUES ('wak', 'vakaši keel');
INSERT INTO `country` (`id`, `name`) VALUES ('be', 'valgevene');
INSERT INTO `country` (`id`, `name`) VALUES ('wa', 'vallooni');
INSERT INTO `country` (`id`, `name`) VALUES ('sga', 'vanaiiri');
INSERT INTO `country` (`id`, `name`) VALUES ('ang', 'vanainglise');
INSERT INTO `country` (`id`, `name`) VALUES ('grc', 'vanakreeka');
INSERT INTO `country` (`id`, `name`) VALUES ('nwc', 'vananevari');
INSERT INTO `country` (`id`, `name`) VALUES ('fro', 'vanaprantsuse');
INSERT INTO `country` (`id`, `name`) VALUES ('pro', 'vanaprovansi');
INSERT INTO `country` (`id`, `name`) VALUES ('non', 'vanapõhjala');
INSERT INTO `country` (`id`, `name`) VALUES ('peo', 'vanapärsia');
INSERT INTO `country` (`id`, `name`) VALUES ('goh', 'vanaülemsaksa');
INSERT INTO `country` (`id`, `name`) VALUES ('war', 'varai');
INSERT INTO `country` (`id`, `name`) VALUES ('was', 'vašo');
INSERT INTO `country` (`id`, `name`) VALUES ('ve', 'venda');
INSERT INTO `country` (`id`, `name`) VALUES ('ru', 'vene');
INSERT INTO `country` (`id`, `name`) VALUES ('vi', 'vietnami');
INSERT INTO `country` (`id`, `name`) VALUES ('sgn', 'viipekeel');
INSERT INTO `country` (`id`, `name`) VALUES ('wal', 'volamo');
INSERT INTO `country` (`id`, `name`) VALUES ('vo', 'volapüki');
INSERT INTO `country` (`id`, `name`) VALUES ('wo', 'volofi');
INSERT INTO `country` (`id`, `name`) VALUES ('mis', 'üksikkeeled');
INSERT INTO `country` (`id`, `name`) VALUES ('hsb', 'ülemsorbi');
