CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('ak', 'Akan');
INSERT INTO [country] ([id], [name]) VALUES ('am', 'Amarik');
INSERT INTO [country] ([id], [name]) VALUES ('ar', 'Arabik');
INSERT INTO [country] ([id], [name]) VALUES ('be', 'Belarus kasa');
INSERT INTO [country] ([id], [name]) VALUES ('bn', 'Bengali kasa');
INSERT INTO [country] ([id], [name]) VALUES ('my', 'Bɛɛmis kasa');
INSERT INTO [country] ([id], [name]) VALUES ('en', 'Borɔfo');
INSERT INTO [country] ([id], [name]) VALUES ('bg', 'Bɔlgeria kasa');
INSERT INTO [country] ([id], [name]) VALUES ('nl', 'Dɛɛkye');
INSERT INTO [country] ([id], [name]) VALUES ('fr', 'Frɛnkye');
INSERT INTO [country] ([id], [name]) VALUES ('el', 'Greek kasa');
INSERT INTO [country] ([id], [name]) VALUES ('de', 'Gyaaman');
INSERT INTO [country] ([id], [name]) VALUES ('jv', 'Gyabanis kasa');
INSERT INTO [country] ([id], [name]) VALUES ('ja', 'Gyapan kasa');
INSERT INTO [country] ([id], [name]) VALUES ('hu', 'Hangri kasa');
INSERT INTO [country] ([id], [name]) VALUES ('ha', 'Hausa');
INSERT INTO [country] ([id], [name]) VALUES ('hi', 'Hindi');
INSERT INTO [country] ([id], [name]) VALUES ('ig', 'Igbo');
INSERT INTO [country] ([id], [name]) VALUES ('id', 'Indonihyia kasa');
INSERT INTO [country] ([id], [name]) VALUES ('it', 'Italy kasa');
INSERT INTO [country] ([id], [name]) VALUES ('km', 'Kambodia kasa');
INSERT INTO [country] ([id], [name]) VALUES ('ko', 'Korea kasa');
INSERT INTO [country] ([id], [name]) VALUES ('zh', 'Kyaena kasa');
INSERT INTO [country] ([id], [name]) VALUES ('cs', 'Kyɛk kasa');
INSERT INTO [country] ([id], [name]) VALUES ('ms', 'Malay kasa');
INSERT INTO [country] ([id], [name]) VALUES ('ne', 'Nɛpal kasa');
INSERT INTO [country] ([id], [name]) VALUES ('fa', 'Pɛɛhyia kasa');
INSERT INTO [country] ([id], [name]) VALUES ('pl', 'Pɔland kasa');
INSERT INTO [country] ([id], [name]) VALUES ('pt', 'Pɔɔtugal kasa');
INSERT INTO [country] ([id], [name]) VALUES ('pa', 'Pungyabi kasa');
INSERT INTO [country] ([id], [name]) VALUES ('ru', 'Rahyia kasa');
INSERT INTO [country] ([id], [name]) VALUES ('rw', 'Rewanda kasa');
INSERT INTO [country] ([id], [name]) VALUES ('ro', 'Romenia kasa');
INSERT INTO [country] ([id], [name]) VALUES ('so', 'Somalia kasa');
INSERT INTO [country] ([id], [name]) VALUES ('es', 'Spain kasa');
INSERT INTO [country] ([id], [name]) VALUES ('sv', 'Sweden kasa');
INSERT INTO [country] ([id], [name]) VALUES ('th', 'Taeland kasa');
INSERT INTO [country] ([id], [name]) VALUES ('ta', 'Tamil kasa');
INSERT INTO [country] ([id], [name]) VALUES ('tr', 'Tɛɛki kasa');
INSERT INTO [country] ([id], [name]) VALUES ('uk', 'Ukren kasa');
INSERT INTO [country] ([id], [name]) VALUES ('ur', 'Urdu kasa');
INSERT INTO [country] ([id], [name]) VALUES ('vi', 'Viɛtnam kasa');
INSERT INTO [country] ([id], [name]) VALUES ('yo', 'Yoruba');
INSERT INTO [country] ([id], [name]) VALUES ('zu', 'Zulu');
