CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('ab', 'abkhasisk');
INSERT INTO `country` (`id`, `name`) VALUES ('ace', 'achinesisk');
INSERT INTO `country` (`id`, `name`) VALUES ('ach', 'acoli');
INSERT INTO `country` (`id`, `name`) VALUES ('ada', 'adangme');
INSERT INTO `country` (`id`, `name`) VALUES ('ady', 'adyghe');
INSERT INTO `country` (`id`, `name`) VALUES ('aa', 'afar');
INSERT INTO `country` (`id`, `name`) VALUES ('afh', 'afrihili');
INSERT INTO `country` (`id`, `name`) VALUES ('af', 'afrikaans');
INSERT INTO `country` (`id`, `name`) VALUES ('afa', 'afroasiatisk språk');
INSERT INTO `country` (`id`, `name`) VALUES ('agq', 'aghem');
INSERT INTO `country` (`id`, `name`) VALUES ('ain', 'ainu');
INSERT INTO `country` (`id`, `name`) VALUES ('ak', 'akan');
INSERT INTO `country` (`id`, `name`) VALUES ('akk', 'akkadisk');
INSERT INTO `country` (`id`, `name`) VALUES ('sq', 'albansk');
INSERT INTO `country` (`id`, `name`) VALUES ('ale', 'aleutisk');
INSERT INTO `country` (`id`, `name`) VALUES ('alg', 'algonkinsk språk');
INSERT INTO `country` (`id`, `name`) VALUES ('tut', 'altaisk språk');
INSERT INTO `country` (`id`, `name`) VALUES ('en_US', 'amerikansk engelsk');
INSERT INTO `country` (`id`, `name`) VALUES ('am', 'amharisk');
INSERT INTO `country` (`id`, `name`) VALUES ('anp', 'angika');
INSERT INTO `country` (`id`, `name`) VALUES ('mis', 'annet språk');
INSERT INTO `country` (`id`, `name`) VALUES ('apa', 'apachespråk');
INSERT INTO `country` (`id`, `name`) VALUES ('ar', 'arabisk');
INSERT INTO `country` (`id`, `name`) VALUES ('an', 'aragonsk');
INSERT INTO `country` (`id`, `name`) VALUES ('arc', 'arameisk');
INSERT INTO `country` (`id`, `name`) VALUES ('arp', 'arapaho');
INSERT INTO `country` (`id`, `name`) VALUES ('arn', 'araukansk');
INSERT INTO `country` (`id`, `name`) VALUES ('arw', 'arawak');
INSERT INTO `country` (`id`, `name`) VALUES ('hy', 'armensk');
INSERT INTO `country` (`id`, `name`) VALUES ('rup', 'aromansk');
INSERT INTO `country` (`id`, `name`) VALUES ('az', 'aserbajdsjansk');
INSERT INTO `country` (`id`, `name`) VALUES ('as', 'assamisk');
INSERT INTO `country` (`id`, `name`) VALUES ('ast', 'asturisk');
INSERT INTO `country` (`id`, `name`) VALUES ('asa', 'asu');
INSERT INTO `country` (`id`, `name`) VALUES ('ath', 'athapaskansk språk');
INSERT INTO `country` (`id`, `name`) VALUES ('cch', 'atsam');
INSERT INTO `country` (`id`, `name`) VALUES ('en_AU', 'australsk engelsk');
INSERT INTO `country` (`id`, `name`) VALUES ('aus', 'australsk språk');
INSERT INTO `country` (`id`, `name`) VALUES ('map', 'austronesisk språk');
INSERT INTO `country` (`id`, `name`) VALUES ('av', 'avarisk');
INSERT INTO `country` (`id`, `name`) VALUES ('ae', 'avestisk');
INSERT INTO `country` (`id`, `name`) VALUES ('awa', 'awadhi');
INSERT INTO `country` (`id`, `name`) VALUES ('ay', 'aymara');
INSERT INTO `country` (`id`, `name`) VALUES ('ksf', 'bafia');
INSERT INTO `country` (`id`, `name`) VALUES ('ban', 'balinesisk');
INSERT INTO `country` (`id`, `name`) VALUES ('bat', 'baltisk språk');
INSERT INTO `country` (`id`, `name`) VALUES ('bal', 'baluchi');
INSERT INTO `country` (`id`, `name`) VALUES ('bm', 'bambara');
INSERT INTO `country` (`id`, `name`) VALUES ('bai', 'bamilekisk språk');
INSERT INTO `country` (`id`, `name`) VALUES ('bad', 'banda');
INSERT INTO `country` (`id`, `name`) VALUES ('bnt', 'bantu');
INSERT INTO `country` (`id`, `name`) VALUES ('bas', 'basa');
INSERT INTO `country` (`id`, `name`) VALUES ('ba', 'basjkirsk');
INSERT INTO `country` (`id`, `name`) VALUES ('eu', 'baskisk');
INSERT INTO `country` (`id`, `name`) VALUES ('btk', 'batak');
INSERT INTO `country` (`id`, `name`) VALUES ('bej', 'beja');
INSERT INTO `country` (`id`, `name`) VALUES ('bem', 'bemba');
INSERT INTO `country` (`id`, `name`) VALUES ('bez', 'bena');
INSERT INTO `country` (`id`, `name`) VALUES ('bn', 'bengali');
INSERT INTO `country` (`id`, `name`) VALUES ('ber', 'berbisk');
INSERT INTO `country` (`id`, `name`) VALUES ('bho', 'bhojpuri');
INSERT INTO `country` (`id`, `name`) VALUES ('bh', 'bihari');
INSERT INTO `country` (`id`, `name`) VALUES ('bik', 'bikol');
INSERT INTO `country` (`id`, `name`) VALUES ('bin', 'bini');
INSERT INTO `country` (`id`, `name`) VALUES ('bi', 'bislama');
INSERT INTO `country` (`id`, `name`) VALUES ('byn', 'blin');
INSERT INTO `country` (`id`, `name`) VALUES ('zbl', 'blissymboler');
INSERT INTO `country` (`id`, `name`) VALUES ('brx', 'bodo');
INSERT INTO `country` (`id`, `name`) VALUES ('bs', 'bosnisk');
INSERT INTO `country` (`id`, `name`) VALUES ('bra', 'braj');
INSERT INTO `country` (`id`, `name`) VALUES ('pt_BR', 'brasiliansk portugisisk');
INSERT INTO `country` (`id`, `name`) VALUES ('br', 'bretonsk');
INSERT INTO `country` (`id`, `name`) VALUES ('en_GB', 'britisk engelsk');
INSERT INTO `country` (`id`, `name`) VALUES ('bug', 'buginesisk');
INSERT INTO `country` (`id`, `name`) VALUES ('bg', 'bulgarsk');
INSERT INTO `country` (`id`, `name`) VALUES ('bua', 'buriat');
INSERT INTO `country` (`id`, `name`) VALUES ('my', 'burmesisk');
INSERT INTO `country` (`id`, `name`) VALUES ('cad', 'caddo');
INSERT INTO `country` (`id`, `name`) VALUES ('en_CA', 'canadisk engelsk');
INSERT INTO `country` (`id`, `name`) VALUES ('fr_CA', 'canadisk fransk');
INSERT INTO `country` (`id`, `name`) VALUES ('ceb', 'cebuansk');
INSERT INTO `country` (`id`, `name`) VALUES ('chg', 'chagatai');
INSERT INTO `country` (`id`, `name`) VALUES ('ch', 'chamorro');
INSERT INTO `country` (`id`, `name`) VALUES ('chr', 'cherokee');
INSERT INTO `country` (`id`, `name`) VALUES ('chy', 'cheyenne');
INSERT INTO `country` (`id`, `name`) VALUES ('chb', 'chibcha');
INSERT INTO `country` (`id`, `name`) VALUES ('chn', 'chinook');
INSERT INTO `country` (`id`, `name`) VALUES ('chp', 'chipewiansk');
INSERT INTO `country` (`id`, `name`) VALUES ('cho', 'choctaw');
INSERT INTO `country` (`id`, `name`) VALUES ('chk', 'chuukesisk');
INSERT INTO `country` (`id`, `name`) VALUES ('cr', 'cree');
INSERT INTO `country` (`id`, `name`) VALUES ('mus', 'creek');
INSERT INTO `country` (`id`, `name`) VALUES ('dak', 'dakota');
INSERT INTO `country` (`id`, `name`) VALUES ('da', 'dansk');
INSERT INTO `country` (`id`, `name`) VALUES ('dar', 'dargwa');
INSERT INTO `country` (`id`, `name`) VALUES ('day', 'dayak');
INSERT INTO `country` (`id`, `name`) VALUES ('del', 'delaware');
INSERT INTO `country` (`id`, `name`) VALUES ('din', 'dinka');
INSERT INTO `country` (`id`, `name`) VALUES ('dv', 'divehi');
INSERT INTO `country` (`id`, `name`) VALUES ('doi', 'dogri');
INSERT INTO `country` (`id`, `name`) VALUES ('dgr', 'dogrib');
INSERT INTO `country` (`id`, `name`) VALUES ('dra', 'dravidisk språk');
INSERT INTO `country` (`id`, `name`) VALUES ('dua', 'duala');
INSERT INTO `country` (`id`, `name`) VALUES ('dyu', 'dyula');
INSERT INTO `country` (`id`, `name`) VALUES ('dz', 'dzongkha');
INSERT INTO `country` (`id`, `name`) VALUES ('efi', 'efik');
INSERT INTO `country` (`id`, `name`) VALUES ('eka', 'ekajuk');
INSERT INTO `country` (`id`, `name`) VALUES ('elx', 'elamittisk');
INSERT INTO `country` (`id`, `name`) VALUES ('smn', 'enaresamisk');
INSERT INTO `country` (`id`, `name`) VALUES ('en', 'engelsk');
INSERT INTO `country` (`id`, `name`) VALUES ('cpe', 'engelskbasert kreol- eller pidginspråk');
INSERT INTO `country` (`id`, `name`) VALUES ('myv', 'erzya');
INSERT INTO `country` (`id`, `name`) VALUES ('eo', 'esperanto');
INSERT INTO `country` (`id`, `name`) VALUES ('et', 'estisk');
INSERT INTO `country` (`id`, `name`) VALUES ('ee', 'ewe');
INSERT INTO `country` (`id`, `name`) VALUES ('ewo', 'ewondo');
INSERT INTO `country` (`id`, `name`) VALUES ('fan', 'fang');
INSERT INTO `country` (`id`, `name`) VALUES ('fat', 'fanti');
INSERT INTO `country` (`id`, `name`) VALUES ('fj', 'fijiansk');
INSERT INTO `country` (`id`, `name`) VALUES ('fil', 'filippinsk');
INSERT INTO `country` (`id`, `name`) VALUES ('phi', 'filippinsk språk');
INSERT INTO `country` (`id`, `name`) VALUES ('fi', 'finsk');
INSERT INTO `country` (`id`, `name`) VALUES ('fiu', 'finsk-ugrisk språk');
INSERT INTO `country` (`id`, `name`) VALUES ('nl_BE', 'flamsk');
INSERT INTO `country` (`id`, `name`) VALUES ('fon', 'fon');
INSERT INTO `country` (`id`, `name`) VALUES ('zh_Hans', 'forenklet kinesisk');
INSERT INTO `country` (`id`, `name`) VALUES ('fr', 'fransk');
INSERT INTO `country` (`id`, `name`) VALUES ('cpf', 'franskbasert kreol- eller pidginspråk');
INSERT INTO `country` (`id`, `name`) VALUES ('fur', 'friuliansk');
INSERT INTO `country` (`id`, `name`) VALUES ('ff', 'fulani');
INSERT INTO `country` (`id`, `name`) VALUES ('fo', 'færøysk');
INSERT INTO `country` (`id`, `name`) VALUES ('phn', 'fønikisk');
INSERT INTO `country` (`id`, `name`) VALUES ('gaa', 'ga');
INSERT INTO `country` (`id`, `name`) VALUES ('gl', 'galisisk');
INSERT INTO `country` (`id`, `name`) VALUES ('egy', 'gammelegyptisk');
INSERT INTO `country` (`id`, `name`) VALUES ('ang', 'gammelengelsk');
INSERT INTO `country` (`id`, `name`) VALUES ('fro', 'gammelfransk');
INSERT INTO `country` (`id`, `name`) VALUES ('grc', 'gammelgresk');
INSERT INTO `country` (`id`, `name`) VALUES ('goh', 'gammelhøytysk');
INSERT INTO `country` (`id`, `name`) VALUES ('sga', 'gammelirsk');
INSERT INTO `country` (`id`, `name`) VALUES ('non', 'gammelnorsk');
INSERT INTO `country` (`id`, `name`) VALUES ('peo', 'gammelpersisk');
INSERT INTO `country` (`id`, `name`) VALUES ('pro', 'gammelprovençalsk');
INSERT INTO `country` (`id`, `name`) VALUES ('lg', 'ganda');
INSERT INTO `country` (`id`, `name`) VALUES ('gay', 'gayo');
INSERT INTO `country` (`id`, `name`) VALUES ('gba', 'gbaya');
INSERT INTO `country` (`id`, `name`) VALUES ('ka', 'georgisk');
INSERT INTO `country` (`id`, `name`) VALUES ('gem', 'germansk språk');
INSERT INTO `country` (`id`, `name`) VALUES ('gez', 'ges');
INSERT INTO `country` (`id`, `name`) VALUES ('gon', 'gondi');
INSERT INTO `country` (`id`, `name`) VALUES ('gor', 'gorontalo');
INSERT INTO `country` (`id`, `name`) VALUES ('got', 'gotisk');
INSERT INTO `country` (`id`, `name`) VALUES ('grb', 'grebo');
INSERT INTO `country` (`id`, `name`) VALUES ('el', 'gresk');
INSERT INTO `country` (`id`, `name`) VALUES ('kl', 'grønlandsk');
INSERT INTO `country` (`id`, `name`) VALUES ('gn', 'guarani');
INSERT INTO `country` (`id`, `name`) VALUES ('gu', 'gujarati');
INSERT INTO `country` (`id`, `name`) VALUES ('gwi', 'gwichin');
INSERT INTO `country` (`id`, `name`) VALUES ('hai', 'haida');
INSERT INTO `country` (`id`, `name`) VALUES ('ht', 'haitisk');
INSERT INTO `country` (`id`, `name`) VALUES ('ha', 'hausa');
INSERT INTO `country` (`id`, `name`) VALUES ('haw', 'hawaiisk');
INSERT INTO `country` (`id`, `name`) VALUES ('he', 'hebraisk');
INSERT INTO `country` (`id`, `name`) VALUES ('hz', 'herero');
INSERT INTO `country` (`id`, `name`) VALUES ('hit', 'hettittisk');
INSERT INTO `country` (`id`, `name`) VALUES ('hil', 'hiligaynon');
INSERT INTO `country` (`id`, `name`) VALUES ('him', 'himachali');
INSERT INTO `country` (`id`, `name`) VALUES ('hi', 'hindi');
INSERT INTO `country` (`id`, `name`) VALUES ('ho', 'hiri motu');
INSERT INTO `country` (`id`, `name`) VALUES ('hmn', 'hmong');
INSERT INTO `country` (`id`, `name`) VALUES ('hup', 'hupa');
INSERT INTO `country` (`id`, `name`) VALUES ('be', 'hviterussisk');
INSERT INTO `country` (`id`, `name`) VALUES ('hsb', 'høysorbisk');
INSERT INTO `country` (`id`, `name`) VALUES ('iba', 'iban');
INSERT INTO `country` (`id`, `name`) VALUES ('pt_PT', 'iberisk portugisisk');
INSERT INTO `country` (`id`, `name`) VALUES ('es_ES', 'iberisk spansk');
INSERT INTO `country` (`id`, `name`) VALUES ('ig', 'ibo');
INSERT INTO `country` (`id`, `name`) VALUES ('io', 'ido');
INSERT INTO `country` (`id`, `name`) VALUES ('ijo', 'ijo');
INSERT INTO `country` (`id`, `name`) VALUES ('ilo', 'iloko');
INSERT INTO `country` (`id`, `name`) VALUES ('inc', 'indisk språk');
INSERT INTO `country` (`id`, `name`) VALUES ('ine', 'indoeuropeisk språk');
INSERT INTO `country` (`id`, `name`) VALUES ('id', 'indonesisk');
INSERT INTO `country` (`id`, `name`) VALUES ('inh', 'ingusjisk');
INSERT INTO `country` (`id`, `name`) VALUES ('ia', 'interlingua');
INSERT INTO `country` (`id`, `name`) VALUES ('ie', 'interlingue');
INSERT INTO `country` (`id`, `name`) VALUES ('iu', 'inuktitut');
INSERT INTO `country` (`id`, `name`) VALUES ('ik', 'inupiak');
INSERT INTO `country` (`id`, `name`) VALUES ('ira', 'iransk språk');
INSERT INTO `country` (`id`, `name`) VALUES ('iro', 'irokansk språk');
INSERT INTO `country` (`id`, `name`) VALUES ('ga', 'irsk');
INSERT INTO `country` (`id`, `name`) VALUES ('is', 'islandsk');
INSERT INTO `country` (`id`, `name`) VALUES ('it', 'italiensk');
INSERT INTO `country` (`id`, `name`) VALUES ('sah', 'jakutsk');
INSERT INTO `country` (`id`, `name`) VALUES ('ja', 'japansk');
INSERT INTO `country` (`id`, `name`) VALUES ('jv', 'javanesisk');
INSERT INTO `country` (`id`, `name`) VALUES ('yi', 'jiddisk');
INSERT INTO `country` (`id`, `name`) VALUES ('kaj', 'jju');
INSERT INTO `country` (`id`, `name`) VALUES ('dyo', 'jola-fonyi');
INSERT INTO `country` (`id`, `name`) VALUES ('yo', 'joruba');
INSERT INTO `country` (`id`, `name`) VALUES ('ypk', 'jupisk språk');
INSERT INTO `country` (`id`, `name`) VALUES ('jrb', 'jødearabisk');
INSERT INTO `country` (`id`, `name`) VALUES ('jpr', 'jødepersisk');
INSERT INTO `country` (`id`, `name`) VALUES ('kbd', 'kabardisk');
INSERT INTO `country` (`id`, `name`) VALUES ('kab', 'kabylsk');
INSERT INTO `country` (`id`, `name`) VALUES ('kac', 'kachin');
INSERT INTO `country` (`id`, `name`) VALUES ('xal', 'kalmyk');
INSERT INTO `country` (`id`, `name`) VALUES ('kam', 'kamba');
INSERT INTO `country` (`id`, `name`) VALUES ('cmc', 'kamisk språk');
INSERT INTO `country` (`id`, `name`) VALUES ('kn', 'kannada');
INSERT INTO `country` (`id`, `name`) VALUES ('yue', 'kantonesisk');
INSERT INTO `country` (`id`, `name`) VALUES ('kr', 'kanuri');
INSERT INTO `country` (`id`, `name`) VALUES ('kea', 'kappverdisk');
INSERT INTO `country` (`id`, `name`) VALUES ('krc', 'karachay-balkar');
INSERT INTO `country` (`id`, `name`) VALUES ('kaa', 'karakalpakisk');
INSERT INTO `country` (`id`, `name`) VALUES ('krl', 'karelsk');
INSERT INTO `country` (`id`, `name`) VALUES ('kar', 'karensk');
INSERT INTO `country` (`id`, `name`) VALUES ('car', 'karibisk');
INSERT INTO `country` (`id`, `name`) VALUES ('kk', 'kasakhisk');
INSERT INTO `country` (`id`, `name`) VALUES ('ks', 'kasjmiri');
INSERT INTO `country` (`id`, `name`) VALUES ('csb', 'kasjubisk');
INSERT INTO `country` (`id`, `name`) VALUES ('ca', 'katalansk');
INSERT INTO `country` (`id`, `name`) VALUES ('cau', 'kaukasisk språk');
INSERT INTO `country` (`id`, `name`) VALUES ('kaw', 'kawi');
INSERT INTO `country` (`id`, `name`) VALUES ('cel', 'keltisk språk');
INSERT INTO `country` (`id`, `name`) VALUES ('kha', 'khasi');
INSERT INTO `country` (`id`, `name`) VALUES ('km', 'khmer');
INSERT INTO `country` (`id`, `name`) VALUES ('khi', 'khoisanspråk');
INSERT INTO `country` (`id`, `name`) VALUES ('kho', 'khotanesisk');
INSERT INTO `country` (`id`, `name`) VALUES ('ebu', 'kiembu');
INSERT INTO `country` (`id`, `name`) VALUES ('kg', 'kikongo');
INSERT INTO `country` (`id`, `name`) VALUES ('ki', 'kikuyu');
INSERT INTO `country` (`id`, `name`) VALUES ('kmb', 'kimbundu');
INSERT INTO `country` (`id`, `name`) VALUES ('zh', 'kinesisk');
INSERT INTO `country` (`id`, `name`) VALUES ('rw', 'kinjarwanda');
INSERT INTO `country` (`id`, `name`) VALUES ('ky', 'kirgisisk');
INSERT INTO `country` (`id`, `name`) VALUES ('gil', 'kiribatisk');
INSERT INTO `country` (`id`, `name`) VALUES ('cu', 'kirkeslavisk');
INSERT INTO `country` (`id`, `name`) VALUES ('nwc', 'klassisk newari');
INSERT INTO `country` (`id`, `name`) VALUES ('syc', 'klassisk syrisk');
INSERT INTO `country` (`id`, `name`) VALUES ('tlh', 'klingon');
INSERT INTO `country` (`id`, `name`) VALUES ('kv', 'komi');
INSERT INTO `country` (`id`, `name`) VALUES ('swb', 'komorisk');
INSERT INTO `country` (`id`, `name`) VALUES ('kok', 'konkani');
INSERT INTO `country` (`id`, `name`) VALUES ('cop', 'koptisk');
INSERT INTO `country` (`id`, `name`) VALUES ('ko', 'koreansk');
INSERT INTO `country` (`id`, `name`) VALUES ('kw', 'kornisk');
INSERT INTO `country` (`id`, `name`) VALUES ('kfo', 'koro');
INSERT INTO `country` (`id`, `name`) VALUES ('co', 'korsikansk');
INSERT INTO `country` (`id`, `name`) VALUES ('kos', 'kosraeansk');
INSERT INTO `country` (`id`, `name`) VALUES ('kpe', 'kpelle');
INSERT INTO `country` (`id`, `name`) VALUES ('crp', 'kreol- eller pidginspråk');
INSERT INTO `country` (`id`, `name`) VALUES ('crh', 'krimtatarisk');
INSERT INTO `country` (`id`, `name`) VALUES ('hr', 'kroatisk');
INSERT INTO `country` (`id`, `name`) VALUES ('kro', 'kru');
INSERT INTO `country` (`id`, `name`) VALUES ('kj', 'kuanyama');
INSERT INTO `country` (`id`, `name`) VALUES ('kum', 'kumyk');
INSERT INTO `country` (`id`, `name`) VALUES ('art', 'kunstig språk');
INSERT INTO `country` (`id`, `name`) VALUES ('ku', 'kurdisk');
INSERT INTO `country` (`id`, `name`) VALUES ('kru', 'kurukh');
INSERT INTO `country` (`id`, `name`) VALUES ('cus', 'kusjitisk språk');
INSERT INTO `country` (`id`, `name`) VALUES ('kut', 'kutenai');
INSERT INTO `country` (`id`, `name`) VALUES ('nmg', 'kwasio');
INSERT INTO `country` (`id`, `name`) VALUES ('lad', 'ladinsk');
INSERT INTO `country` (`id`, `name`) VALUES ('lah', 'lahnda');
INSERT INTO `country` (`id`, `name`) VALUES ('lam', 'lamba');
INSERT INTO `country` (`id`, `name`) VALUES ('lo', 'laotisk');
INSERT INTO `country` (`id`, `name`) VALUES ('la', 'latin');
INSERT INTO `country` (`id`, `name`) VALUES ('es_419', 'latinamerikansk spansk');
INSERT INTO `country` (`id`, `name`) VALUES ('lv', 'latvisk');
INSERT INTO `country` (`id`, `name`) VALUES ('dsb', 'lavsorbisk');
INSERT INTO `country` (`id`, `name`) VALUES ('nds', 'lavtysk');
INSERT INTO `country` (`id`, `name`) VALUES ('lez', 'lezghian');
INSERT INTO `country` (`id`, `name`) VALUES ('li', 'limburgisk');
INSERT INTO `country` (`id`, `name`) VALUES ('ln', 'lingala');
INSERT INTO `country` (`id`, `name`) VALUES ('lt', 'litauisk');
INSERT INTO `country` (`id`, `name`) VALUES ('jbo', 'lojban');
INSERT INTO `country` (`id`, `name`) VALUES ('loz', 'lozi');
INSERT INTO `country` (`id`, `name`) VALUES ('lu', 'luba-katanga');
INSERT INTO `country` (`id`, `name`) VALUES ('lua', 'luba-lulua');
INSERT INTO `country` (`id`, `name`) VALUES ('lui', 'luiseno');
INSERT INTO `country` (`id`, `name`) VALUES ('smj', 'lulesamisk');
INSERT INTO `country` (`id`, `name`) VALUES ('lun', 'lunda');
INSERT INTO `country` (`id`, `name`) VALUES ('luo', 'luo');
INSERT INTO `country` (`id`, `name`) VALUES ('lus', 'lushai');
INSERT INTO `country` (`id`, `name`) VALUES ('lb', 'luxemburgsk');
INSERT INTO `country` (`id`, `name`) VALUES ('mg', 'madagassisk');
INSERT INTO `country` (`id`, `name`) VALUES ('mad', 'maduresisk');
INSERT INTO `country` (`id`, `name`) VALUES ('mag', 'magahi');
INSERT INTO `country` (`id`, `name`) VALUES ('mai', 'maithili');
INSERT INTO `country` (`id`, `name`) VALUES ('mak', 'makasar');
INSERT INTO `country` (`id`, `name`) VALUES ('mk', 'makedonsk');
INSERT INTO `country` (`id`, `name`) VALUES ('mgh', 'makhuwa-meetto');
INSERT INTO `country` (`id`, `name`) VALUES ('ml', 'malayalam');
INSERT INTO `country` (`id`, `name`) VALUES ('ms', 'malayisk');
INSERT INTO `country` (`id`, `name`) VALUES ('mt', 'maltesisk');
INSERT INTO `country` (`id`, `name`) VALUES ('mdr', 'mandar');
INSERT INTO `country` (`id`, `name`) VALUES ('man', 'mandingo');
INSERT INTO `country` (`id`, `name`) VALUES ('mnc', 'mandsju');
INSERT INTO `country` (`id`, `name`) VALUES ('mni', 'manipuri');
INSERT INTO `country` (`id`, `name`) VALUES ('mno', 'manobospråk');
INSERT INTO `country` (`id`, `name`) VALUES ('gv', 'manx');
INSERT INTO `country` (`id`, `name`) VALUES ('mi', 'maori');
INSERT INTO `country` (`id`, `name`) VALUES ('mr', 'marathi');
INSERT INTO `country` (`id`, `name`) VALUES ('chm', 'mari');
INSERT INTO `country` (`id`, `name`) VALUES ('mh', 'marshallesisk');
INSERT INTO `country` (`id`, `name`) VALUES ('mwr', 'marwari');
INSERT INTO `country` (`id`, `name`) VALUES ('mas', 'masai');
INSERT INTO `country` (`id`, `name`) VALUES ('myn', 'mayaspråk');
INSERT INTO `country` (`id`, `name`) VALUES ('enm', 'mellomengelsk');
INSERT INTO `country` (`id`, `name`) VALUES ('frm', 'mellomfransk');
INSERT INTO `country` (`id`, `name`) VALUES ('gmh', 'mellomhøytysk');
INSERT INTO `country` (`id`, `name`) VALUES ('mga', 'mellomirsk');
INSERT INTO `country` (`id`, `name`) VALUES ('dum', 'mellomnederlandsk');
INSERT INTO `country` (`id`, `name`) VALUES ('men', 'mende');
INSERT INTO `country` (`id`, `name`) VALUES ('mic', 'micmac');
INSERT INTO `country` (`id`, `name`) VALUES ('min', 'minangkabau');
INSERT INTO `country` (`id`, `name`) VALUES ('mwl', 'mirandesisk');
INSERT INTO `country` (`id`, `name`) VALUES ('moh', 'mohawk');
INSERT INTO `country` (`id`, `name`) VALUES ('mdf', 'moksha');
INSERT INTO `country` (`id`, `name`) VALUES ('mo', 'moldavisk');
INSERT INTO `country` (`id`, `name`) VALUES ('mkh', 'mon-khmerspråk');
INSERT INTO `country` (`id`, `name`) VALUES ('lol', 'mongo');
INSERT INTO `country` (`id`, `name`) VALUES ('mn', 'mongolsk');
INSERT INTO `country` (`id`, `name`) VALUES ('mos', 'mossi');
INSERT INTO `country` (`id`, `name`) VALUES ('mua', 'mundang');
INSERT INTO `country` (`id`, `name`) VALUES ('mun', 'mundaspråk');
INSERT INTO `country` (`id`, `name`) VALUES ('nah', 'nahuatl');
INSERT INTO `country` (`id`, `name`) VALUES ('nap', 'napolitansk');
INSERT INTO `country` (`id`, `name`) VALUES ('na', 'nauru');
INSERT INTO `country` (`id`, `name`) VALUES ('nv', 'navajo');
INSERT INTO `country` (`id`, `name`) VALUES ('ng', 'ndonga');
INSERT INTO `country` (`id`, `name`) VALUES ('nl', 'nederlandsk');
INSERT INTO `country` (`id`, `name`) VALUES ('ne', 'nepalsk');
INSERT INTO `country` (`id`, `name`) VALUES ('new', 'newari');
INSERT INTO `country` (`id`, `name`) VALUES ('nia', 'nias');
INSERT INTO `country` (`id`, `name`) VALUES ('nic', 'niger-kordofiansk språk');
INSERT INTO `country` (`id`, `name`) VALUES ('ssa', 'nilo-saharaspråk');
INSERT INTO `country` (`id`, `name`) VALUES ('niu', 'niueansk');
INSERT INTO `country` (`id`, `name`) VALUES ('nqo', 'nkå');
INSERT INTO `country` (`id`, `name`) VALUES ('nog', 'nogai');
INSERT INTO `country` (`id`, `name`) VALUES ('nd', 'nord-ndebele');
INSERT INTO `country` (`id`, `name`) VALUES ('nso', 'nord-sotho');
INSERT INTO `country` (`id`, `name`) VALUES ('nai', 'nordamerikansk indiansk språk');
INSERT INTO `country` (`id`, `name`) VALUES ('frr', 'nordfrisisk');
INSERT INTO `country` (`id`, `name`) VALUES ('se', 'nordsamisk');
INSERT INTO `country` (`id`, `name`) VALUES ('no', 'norsk');
INSERT INTO `country` (`id`, `name`) VALUES ('nb', 'norsk bokmål');
INSERT INTO `country` (`id`, `name`) VALUES ('nn', 'norsk nynorsk');
INSERT INTO `country` (`id`, `name`) VALUES ('nub', 'nubisk språk');
INSERT INTO `country` (`id`, `name`) VALUES ('nus', 'nuer');
INSERT INTO `country` (`id`, `name`) VALUES ('nym', 'nyamwezi');
INSERT INTO `country` (`id`, `name`) VALUES ('ny', 'nyanja');
INSERT INTO `country` (`id`, `name`) VALUES ('nyn', 'nyankole');
INSERT INTO `country` (`id`, `name`) VALUES ('tog', 'nyasa-tongansk');
INSERT INTO `country` (`id`, `name`) VALUES ('nyo', 'nyoro');
INSERT INTO `country` (`id`, `name`) VALUES ('nzi', 'nzima');
INSERT INTO `country` (`id`, `name`) VALUES ('oj', 'ojibwa');
INSERT INTO `country` (`id`, `name`) VALUES ('oc', 'oksitansk');
INSERT INTO `country` (`id`, `name`) VALUES ('luy', 'oluluyia');
INSERT INTO `country` (`id`, `name`) VALUES ('or', 'oriya');
INSERT INTO `country` (`id`, `name`) VALUES ('om', 'oromo');
INSERT INTO `country` (`id`, `name`) VALUES ('osa', 'osage');
INSERT INTO `country` (`id`, `name`) VALUES ('os', 'ossetisk');
INSERT INTO `country` (`id`, `name`) VALUES ('oto', 'otomisk språk');
INSERT INTO `country` (`id`, `name`) VALUES ('ota', 'ottomansk tyrkisk');
INSERT INTO `country` (`id`, `name`) VALUES ('pal', 'pahlavi');
INSERT INTO `country` (`id`, `name`) VALUES ('pau', 'palauisk');
INSERT INTO `country` (`id`, `name`) VALUES ('pi', 'pali');
INSERT INTO `country` (`id`, `name`) VALUES ('pam', 'pampanga');
INSERT INTO `country` (`id`, `name`) VALUES ('pag', 'pangasinan');
INSERT INTO `country` (`id`, `name`) VALUES ('pa', 'panjabi');
INSERT INTO `country` (`id`, `name`) VALUES ('pap', 'papiamento');
INSERT INTO `country` (`id`, `name`) VALUES ('paa', 'papuisk språk');
INSERT INTO `country` (`id`, `name`) VALUES ('ps', 'pashto');
INSERT INTO `country` (`id`, `name`) VALUES ('fa', 'persisk');
INSERT INTO `country` (`id`, `name`) VALUES ('pl', 'polsk');
INSERT INTO `country` (`id`, `name`) VALUES ('pon', 'ponapisk');
INSERT INTO `country` (`id`, `name`) VALUES ('pt', 'portugisisk');
INSERT INTO `country` (`id`, `name`) VALUES ('cpp', 'portugisiskbasert kreol- eller pidginspråk');
INSERT INTO `country` (`id`, `name`) VALUES ('pra', 'prakritspråk');
INSERT INTO `country` (`id`, `name`) VALUES ('qu', 'quechua');
INSERT INTO `country` (`id`, `name`) VALUES ('raj', 'rajasthani');
INSERT INTO `country` (`id`, `name`) VALUES ('rap', 'rapanui');
INSERT INTO `country` (`id`, `name`) VALUES ('rar', 'rarotongansk');
INSERT INTO `country` (`id`, `name`) VALUES ('rm', 'retoromansk');
INSERT INTO `country` (`id`, `name`) VALUES ('rom', 'romani');
INSERT INTO `country` (`id`, `name`) VALUES ('roa', 'romansk språk');
INSERT INTO `country` (`id`, `name`) VALUES ('rof', 'rombo');
INSERT INTO `country` (`id`, `name`) VALUES ('root', 'rot');
INSERT INTO `country` (`id`, `name`) VALUES ('ro', 'rumensk');
INSERT INTO `country` (`id`, `name`) VALUES ('rn', 'rundi');
INSERT INTO `country` (`id`, `name`) VALUES ('ru', 'russisk');
INSERT INTO `country` (`id`, `name`) VALUES ('rwk', 'rwa');
INSERT INTO `country` (`id`, `name`) VALUES ('sal', 'salishansk språk');
INSERT INTO `country` (`id`, `name`) VALUES ('sam', 'samaritansk arameisk');
INSERT INTO `country` (`id`, `name`) VALUES ('smi', 'samisk språk');
INSERT INTO `country` (`id`, `name`) VALUES ('sm', 'samoansk');
INSERT INTO `country` (`id`, `name`) VALUES ('sad', 'sandawe');
INSERT INTO `country` (`id`, `name`) VALUES ('sg', 'sango');
INSERT INTO `country` (`id`, `name`) VALUES ('sbp', 'sangu');
INSERT INTO `country` (`id`, `name`) VALUES ('sa', 'sanskrit');
INSERT INTO `country` (`id`, `name`) VALUES ('sat', 'santali');
INSERT INTO `country` (`id`, `name`) VALUES ('sc', 'sardinsk');
INSERT INTO `country` (`id`, `name`) VALUES ('sas', 'sasak');
INSERT INTO `country` (`id`, `name`) VALUES ('sel', 'selkupisk');
INSERT INTO `country` (`id`, `name`) VALUES ('sem', 'semittisk språk');
INSERT INTO `country` (`id`, `name`) VALUES ('cai', 'sentralamerikansk indiansk språk');
INSERT INTO `country` (`id`, `name`) VALUES ('sr', 'serbisk');
INSERT INTO `country` (`id`, `name`) VALUES ('sh', 'serbokroatisk');
INSERT INTO `country` (`id`, `name`) VALUES ('srr', 'serer');
INSERT INTO `country` (`id`, `name`) VALUES ('tn', 'setswana');
INSERT INTO `country` (`id`, `name`) VALUES ('shn', 'shan');
INSERT INTO `country` (`id`, `name`) VALUES ('sn', 'shona');
INSERT INTO `country` (`id`, `name`) VALUES ('ii', 'sichuan-yi');
INSERT INTO `country` (`id`, `name`) VALUES ('scn', 'siciliansk');
INSERT INTO `country` (`id`, `name`) VALUES ('sid', 'sidamo');
INSERT INTO `country` (`id`, `name`) VALUES ('bla', 'siksika');
INSERT INTO `country` (`id`, `name`) VALUES ('sd', 'sindhi');
INSERT INTO `country` (`id`, `name`) VALUES ('si', 'singalesisk');
INSERT INTO `country` (`id`, `name`) VALUES ('sit', 'sino-tibetansk språk');
INSERT INTO `country` (`id`, `name`) VALUES ('sio', 'siouxspråk');
INSERT INTO `country` (`id`, `name`) VALUES ('sms', 'skoltesamisk');
INSERT INTO `country` (`id`, `name`) VALUES ('sco', 'skotsk');
INSERT INTO `country` (`id`, `name`) VALUES ('gd', 'skotsk gælisk');
INSERT INTO `country` (`id`, `name`) VALUES ('den', 'slavisk');
INSERT INTO `country` (`id`, `name`) VALUES ('sla', 'slavisk språk');
INSERT INTO `country` (`id`, `name`) VALUES ('sk', 'slovakisk');
INSERT INTO `country` (`id`, `name`) VALUES ('sl', 'slovensk');
INSERT INTO `country` (`id`, `name`) VALUES ('sog', 'sogdisk');
INSERT INTO `country` (`id`, `name`) VALUES ('so', 'somali');
INSERT INTO `country` (`id`, `name`) VALUES ('son', 'songhai');
INSERT INTO `country` (`id`, `name`) VALUES ('snk', 'soninke');
INSERT INTO `country` (`id`, `name`) VALUES ('wen', 'sorbisk språk');
INSERT INTO `country` (`id`, `name`) VALUES ('es', 'spansk');
INSERT INTO `country` (`id`, `name`) VALUES ('srn', 'sranan tongo');
INSERT INTO `country` (`id`, `name`) VALUES ('suk', 'sukuma');
INSERT INTO `country` (`id`, `name`) VALUES ('sux', 'sumerisk');
INSERT INTO `country` (`id`, `name`) VALUES ('su', 'sundanesisk');
INSERT INTO `country` (`id`, `name`) VALUES ('sus', 'susu');
INSERT INTO `country` (`id`, `name`) VALUES ('gsw', 'sveitsertysk');
INSERT INTO `country` (`id`, `name`) VALUES ('fr_CH', 'sveitsisk fransk');
INSERT INTO `country` (`id`, `name`) VALUES ('de_CH', 'sveitsisk høytysk');
INSERT INTO `country` (`id`, `name`) VALUES ('sv', 'svensk');
INSERT INTO `country` (`id`, `name`) VALUES ('sw', 'swahili');
INSERT INTO `country` (`id`, `name`) VALUES ('ss', 'swati');
INSERT INTO `country` (`id`, `name`) VALUES ('syr', 'syrisk');
INSERT INTO `country` (`id`, `name`) VALUES ('nr', 'sør-ndebele');
INSERT INTO `country` (`id`, `name`) VALUES ('st', 'sør-sotho');
INSERT INTO `country` (`id`, `name`) VALUES ('alt', 'søraltaisk');
INSERT INTO `country` (`id`, `name`) VALUES ('sai', 'søramerikansk indiansk språk');
INSERT INTO `country` (`id`, `name`) VALUES ('sma', 'sørsamisk');
INSERT INTO `country` (`id`, `name`) VALUES ('tg', 'tadsjikisk');
INSERT INTO `country` (`id`, `name`) VALUES ('tl', 'tagalog');
INSERT INTO `country` (`id`, `name`) VALUES ('ty', 'tahitisk');
INSERT INTO `country` (`id`, `name`) VALUES ('tai', 'taispråk');
INSERT INTO `country` (`id`, `name`) VALUES ('tmh', 'tamasjek');
INSERT INTO `country` (`id`, `name`) VALUES ('ta', 'tamil');
INSERT INTO `country` (`id`, `name`) VALUES ('twq', 'tasawaq');
INSERT INTO `country` (`id`, `name`) VALUES ('tt', 'tatarisk');
INSERT INTO `country` (`id`, `name`) VALUES ('sgn', 'tegnspråk');
INSERT INTO `country` (`id`, `name`) VALUES ('te', 'telugu');
INSERT INTO `country` (`id`, `name`) VALUES ('tem', 'temne');
INSERT INTO `country` (`id`, `name`) VALUES ('ter', 'tereno');
INSERT INTO `country` (`id`, `name`) VALUES ('tet', 'tetum');
INSERT INTO `country` (`id`, `name`) VALUES ('th', 'thai');
INSERT INTO `country` (`id`, `name`) VALUES ('bo', 'tibetansk');
INSERT INTO `country` (`id`, `name`) VALUES ('tig', 'tigré');
INSERT INTO `country` (`id`, `name`) VALUES ('ti', 'tigrinja');
INSERT INTO `country` (`id`, `name`) VALUES ('tiv', 'tiv');
INSERT INTO `country` (`id`, `name`) VALUES ('tli', 'tlingit');
INSERT INTO `country` (`id`, `name`) VALUES ('tpi', 'tok pisin');
INSERT INTO `country` (`id`, `name`) VALUES ('tkl', 'tokelau');
INSERT INTO `country` (`id`, `name`) VALUES ('to', 'tongansk');
INSERT INTO `country` (`id`, `name`) VALUES ('zh_Hant', 'tradisjonell kinesisk');
INSERT INTO `country` (`id`, `name`) VALUES ('tsi', 'tsimshian');
INSERT INTO `country` (`id`, `name`) VALUES ('cs', 'tsjekkisk');
INSERT INTO `country` (`id`, `name`) VALUES ('ce', 'tsjetsjensk');
INSERT INTO `country` (`id`, `name`) VALUES ('cv', 'tsjuvansk');
INSERT INTO `country` (`id`, `name`) VALUES ('ts', 'tsonga');
INSERT INTO `country` (`id`, `name`) VALUES ('tum', 'tumbuka');
INSERT INTO `country` (`id`, `name`) VALUES ('tup', 'tupispråk');
INSERT INTO `country` (`id`, `name`) VALUES ('tk', 'turkmensk');
INSERT INTO `country` (`id`, `name`) VALUES ('tvl', 'tuvalu');
INSERT INTO `country` (`id`, `name`) VALUES ('tyv', 'tuvinisk');
INSERT INTO `country` (`id`, `name`) VALUES ('tw', 'twi');
INSERT INTO `country` (`id`, `name`) VALUES ('kcg', 'tyap');
INSERT INTO `country` (`id`, `name`) VALUES ('tr', 'tyrkisk');
INSERT INTO `country` (`id`, `name`) VALUES ('de', 'tysk');
INSERT INTO `country` (`id`, `name`) VALUES ('udm', 'udmurt');
INSERT INTO `country` (`id`, `name`) VALUES ('uga', 'ugaritisk');
INSERT INTO `country` (`id`, `name`) VALUES ('ug', 'uigurisk');
INSERT INTO `country` (`id`, `name`) VALUES ('und', 'ukjent språk');
INSERT INTO `country` (`id`, `name`) VALUES ('uk', 'ukrainsk');
INSERT INTO `country` (`id`, `name`) VALUES ('umb', 'umbundu');
INSERT INTO `country` (`id`, `name`) VALUES ('hu', 'ungarsk');
INSERT INTO `country` (`id`, `name`) VALUES ('ur', 'urdu');
INSERT INTO `country` (`id`, `name`) VALUES ('uz', 'usbekisk');
INSERT INTO `country` (`id`, `name`) VALUES ('zxx', 'uten språklig innhold');
INSERT INTO `country` (`id`, `name`) VALUES ('vai', 'vai');
INSERT INTO `country` (`id`, `name`) VALUES ('wa', 'vallonsk');
INSERT INTO `country` (`id`, `name`) VALUES ('ve', 'venda');
INSERT INTO `country` (`id`, `name`) VALUES ('fy', 'vestfrisisk');
INSERT INTO `country` (`id`, `name`) VALUES ('vi', 'vietnamesisk');
INSERT INTO `country` (`id`, `name`) VALUES ('vo', 'volapyk');
INSERT INTO `country` (`id`, `name`) VALUES ('vot', 'votisk');
INSERT INTO `country` (`id`, `name`) VALUES ('wak', 'wakasjansk språk');
INSERT INTO `country` (`id`, `name`) VALUES ('wal', 'walamo');
INSERT INTO `country` (`id`, `name`) VALUES ('cy', 'walisisk');
INSERT INTO `country` (`id`, `name`) VALUES ('war', 'waray');
INSERT INTO `country` (`id`, `name`) VALUES ('was', 'washo');
INSERT INTO `country` (`id`, `name`) VALUES ('wo', 'wolof');
INSERT INTO `country` (`id`, `name`) VALUES ('xh', 'xhosa');
INSERT INTO `country` (`id`, `name`) VALUES ('yav', 'yangben');
INSERT INTO `country` (`id`, `name`) VALUES ('yao', 'yao');
INSERT INTO `country` (`id`, `name`) VALUES ('yap', 'yapesisk');
INSERT INTO `country` (`id`, `name`) VALUES ('znd', 'zande');
INSERT INTO `country` (`id`, `name`) VALUES ('zap', 'zapotec');
INSERT INTO `country` (`id`, `name`) VALUES ('dje', 'zarma');
INSERT INTO `country` (`id`, `name`) VALUES ('zza', 'zaza');
INSERT INTO `country` (`id`, `name`) VALUES ('zen', 'zenaga');
INSERT INTO `country` (`id`, `name`) VALUES ('za', 'zhuang');
INSERT INTO `country` (`id`, `name`) VALUES ('zu', 'zulu');
INSERT INTO `country` (`id`, `name`) VALUES ('zun', 'zuni');
INSERT INTO `country` (`id`, `name`) VALUES ('de_AT', 'østerriksk tysk');
INSERT INTO `country` (`id`, `name`) VALUES ('frs', 'østfrisisk');
