CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('ab', 'абхазская');
INSERT INTO `country` (`id`, `name`) VALUES ('av', 'аварская');
INSERT INTO `country` (`id`, `name`) VALUES ('ady', 'адыгейская');
INSERT INTO `country` (`id`, `name`) VALUES ('az', 'азербайджанская');
INSERT INTO `country` (`id`, `name`) VALUES ('ay', 'аймара');
INSERT INTO `country` (`id`, `name`) VALUES ('akk', 'акадзкая');
INSERT INTO `country` (`id`, `name`) VALUES ('sq', 'албанская');
INSERT INTO `country` (`id`, `name`) VALUES ('ale', 'алеуцкая');
INSERT INTO `country` (`id`, `name`) VALUES ('tut', 'алтайская мова');
INSERT INTO `country` (`id`, `name`) VALUES ('am', 'амхарская');
INSERT INTO `country` (`id`, `name`) VALUES ('en', 'англійская');
INSERT INTO `country` (`id`, `name`) VALUES ('en_AU', 'англійская (аўстрал.)');
INSERT INTO `country` (`id`, `name`) VALUES ('en_GB', 'англійская (Вялікабрытанія)');
INSERT INTO `country` (`id`, `name`) VALUES ('en_US', 'англійская (ЗША)');
INSERT INTO `country` (`id`, `name`) VALUES ('en_CA', 'англійская (канад.)');
INSERT INTO `country` (`id`, `name`) VALUES ('ar', 'арабская');
INSERT INTO `country` (`id`, `name`) VALUES ('an', 'арагонская');
INSERT INTO `country` (`id`, `name`) VALUES ('arc', 'арамейская');
INSERT INTO `country` (`id`, `name`) VALUES ('hy', 'армянская');
INSERT INTO `country` (`id`, `name`) VALUES ('as', 'асамская');
INSERT INTO `country` (`id`, `name`) VALUES ('ast', 'астурыйская');
INSERT INTO `country` (`id`, `name`) VALUES ('aus', 'аўстралійская');
INSERT INTO `country` (`id`, `name`) VALUES ('map', 'аўстранезійская');
INSERT INTO `country` (`id`, `name`) VALUES ('afa', 'афра-азіяцкая мова');
INSERT INTO `country` (`id`, `name`) VALUES ('af', 'афрыкаанс');
INSERT INTO `country` (`id`, `name`) VALUES ('bg', 'балгарская');
INSERT INTO `country` (`id`, `name`) VALUES ('eu', 'баскская');
INSERT INTO `country` (`id`, `name`) VALUES ('bs', 'баснійская');
INSERT INTO `country` (`id`, `name`) VALUES ('ba', 'башкірская');
INSERT INTO `country` (`id`, `name`) VALUES ('be', 'беларуская');
INSERT INTO `country` (`id`, `name`) VALUES ('bn', 'бенгальская');
INSERT INTO `country` (`id`, `name`) VALUES ('bh', 'біхары');
INSERT INTO `country` (`id`, `name`) VALUES ('br', 'брэтонская');
INSERT INTO `country` (`id`, `name`) VALUES ('bua', 'бурацкая');
INSERT INTO `country` (`id`, `name`) VALUES ('vi', 'в\'етнамская');
INSERT INTO `country` (`id`, `name`) VALUES ('cy', 'валійская');
INSERT INTO `country` (`id`, `name`) VALUES ('hu', 'венгерская');
INSERT INTO `country` (`id`, `name`) VALUES ('nl', 'галандская');
INSERT INTO `country` (`id`, `name`) VALUES ('gl', 'галісійская');
INSERT INTO `country` (`id`, `name`) VALUES ('ka', 'грузінская');
INSERT INTO `country` (`id`, `name`) VALUES ('el', 'грэцкая');
INSERT INTO `country` (`id`, `name`) VALUES ('gn', 'гуарані');
INSERT INTO `country` (`id`, `name`) VALUES ('gu', 'гуяраці');
INSERT INTO `country` (`id`, `name`) VALUES ('da', 'дацкая');
INSERT INTO `country` (`id`, `name`) VALUES ('sgn', 'знакавая мова');
INSERT INTO `country` (`id`, `name`) VALUES ('zu', 'зулу');
INSERT INTO `country` (`id`, `name`) VALUES ('yi', 'ідыш');
INSERT INTO `country` (`id`, `name`) VALUES ('id', 'інданезійская');
INSERT INTO `country` (`id`, `name`) VALUES ('ia', 'інтэрлінгва');
INSERT INTO `country` (`id`, `name`) VALUES ('ie', 'інтэрлінгве');
INSERT INTO `country` (`id`, `name`) VALUES ('ga', 'ірландская');
INSERT INTO `country` (`id`, `name`) VALUES ('is', 'ісландская');
INSERT INTO `country` (`id`, `name`) VALUES ('es', 'іспанская');
INSERT INTO `country` (`id`, `name`) VALUES ('es_419', 'іспанская (лацінаамер.)');
INSERT INTO `country` (`id`, `name`) VALUES ('it', 'італьянская');
INSERT INTO `country` (`id`, `name`) VALUES ('he', 'іўрыт');
INSERT INTO `country` (`id`, `name`) VALUES ('kk', 'казахская');
INSERT INTO `country` (`id`, `name`) VALUES ('kn', 'каннада');
INSERT INTO `country` (`id`, `name`) VALUES ('ko', 'карэйская');
INSERT INTO `country` (`id`, `name`) VALUES ('ca', 'каталонская');
INSERT INTO `country` (`id`, `name`) VALUES ('cau', 'каўказская мова');
INSERT INTO `country` (`id`, `name`) VALUES ('cel', 'кельцкая мова');
INSERT INTO `country` (`id`, `name`) VALUES ('zh', 'кітайская');
INSERT INTO `country` (`id`, `name`) VALUES ('tlh', 'клінгон');
INSERT INTO `country` (`id`, `name`) VALUES ('cop', 'копцкая');
INSERT INTO `country` (`id`, `name`) VALUES ('ku', 'курдская');
INSERT INTO `country` (`id`, `name`) VALUES ('lo', 'лаоская');
INSERT INTO `country` (`id`, `name`) VALUES ('lv', 'латышская');
INSERT INTO `country` (`id`, `name`) VALUES ('la', 'лацінская');
INSERT INTO `country` (`id`, `name`) VALUES ('ln', 'лінгала');
INSERT INTO `country` (`id`, `name`) VALUES ('lt', 'літоўская');
INSERT INTO `country` (`id`, `name`) VALUES ('mk', 'македонская');
INSERT INTO `country` (`id`, `name`) VALUES ('ms', 'малайская');
INSERT INTO `country` (`id`, `name`) VALUES ('ml', 'малаяламская');
INSERT INTO `country` (`id`, `name`) VALUES ('mo', 'малдаўская');
INSERT INTO `country` (`id`, `name`) VALUES ('mt', 'мальтыйская');
INSERT INTO `country` (`id`, `name`) VALUES ('mn', 'мангольская');
INSERT INTO `country` (`id`, `name`) VALUES ('mr', 'маратхі');
INSERT INTO `country` (`id`, `name`) VALUES ('cai', 'мова індзейцаў Цэнтральнай Амерыкі');
INSERT INTO `country` (`id`, `name`) VALUES ('no', 'нарвежская');
INSERT INTO `country` (`id`, `name`) VALUES ('nn', 'нарвежская (нюнорск)');
INSERT INTO `country` (`id`, `name`) VALUES ('nb', 'нарвэская букмал');
INSERT INTO `country` (`id`, `name`) VALUES ('und', 'невядомая мова');
INSERT INTO `country` (`id`, `name`) VALUES ('ne', 'непальская');
INSERT INTO `country` (`id`, `name`) VALUES ('de', 'нямецкая');
INSERT INTO `country` (`id`, `name`) VALUES ('de_AT', 'нямецкая (аўстр.)');
INSERT INTO `country` (`id`, `name`) VALUES ('de_CH', 'нямецкая (швейц.)');
INSERT INTO `country` (`id`, `name`) VALUES ('pa', 'панджабі');
INSERT INTO `country` (`id`, `name`) VALUES ('pt', 'партугальская');
INSERT INTO `country` (`id`, `name`) VALUES ('pt_BR', 'партугальская (бразіл.)');
INSERT INTO `country` (`id`, `name`) VALUES ('pl', 'польская');
INSERT INTO `country` (`id`, `name`) VALUES ('oc', 'правансальская');
INSERT INTO `country` (`id`, `name`) VALUES ('ps', 'пушту');
INSERT INTO `country` (`id`, `name`) VALUES ('ro', 'румынская');
INSERT INTO `country` (`id`, `name`) VALUES ('ru', 'руская');
INSERT INTO `country` (`id`, `name`) VALUES ('so', 'самалійская');
INSERT INTO `country` (`id`, `name`) VALUES ('sa', 'санскрыт');
INSERT INTO `country` (`id`, `name`) VALUES ('sh', 'сербска-харвацкая');
INSERT INTO `country` (`id`, `name`) VALUES ('sr', 'сербская');
INSERT INTO `country` (`id`, `name`) VALUES ('si', 'сінгальская');
INSERT INTO `country` (`id`, `name`) VALUES ('sd', 'сіндхі');
INSERT INTO `country` (`id`, `name`) VALUES ('sk', 'славацкая');
INSERT INTO `country` (`id`, `name`) VALUES ('sl', 'славенская');
INSERT INTO `country` (`id`, `name`) VALUES ('sla', 'славянская мова');
INSERT INTO `country` (`id`, `name`) VALUES ('zh_Hans', 'спрошчаная кітайская');
INSERT INTO `country` (`id`, `name`) VALUES ('ang', 'стараанглійская');
INSERT INTO `country` (`id`, `name`) VALUES ('grc', 'старагрэцкая');
INSERT INTO `country` (`id`, `name`) VALUES ('fro', 'старафранцузская');
INSERT INTO `country` (`id`, `name`) VALUES ('egy', 'стараэгіпецкая');
INSERT INTO `country` (`id`, `name`) VALUES ('sw', 'суахілі');
INSERT INTO `country` (`id`, `name`) VALUES ('su', 'суданская');
INSERT INTO `country` (`id`, `name`) VALUES ('fil', 'тагальская');
INSERT INTO `country` (`id`, `name`) VALUES ('th', 'тайская');
INSERT INTO `country` (`id`, `name`) VALUES ('ta', 'тамільская');
INSERT INTO `country` (`id`, `name`) VALUES ('tt', 'татарская');
INSERT INTO `country` (`id`, `name`) VALUES ('zh_Hant', 'традыцыйная кітайская');
INSERT INTO `country` (`id`, `name`) VALUES ('tk', 'туркменская');
INSERT INTO `country` (`id`, `name`) VALUES ('tr', 'турэцкая');
INSERT INTO `country` (`id`, `name`) VALUES ('ti', 'тыгрынья');
INSERT INTO `country` (`id`, `name`) VALUES ('te', 'тэлугу');
INSERT INTO `country` (`id`, `name`) VALUES ('uz', 'узбекская');
INSERT INTO `country` (`id`, `name`) VALUES ('ug', 'уйгурская');
INSERT INTO `country` (`id`, `name`) VALUES ('uk', 'украінская');
INSERT INTO `country` (`id`, `name`) VALUES ('ur', 'урду');
INSERT INTO `country` (`id`, `name`) VALUES ('fa', 'фарсі');
INSERT INTO `country` (`id`, `name`) VALUES ('fo', 'фарэрская');
INSERT INTO `country` (`id`, `name`) VALUES ('fi', 'фінская');
INSERT INTO `country` (`id`, `name`) VALUES ('nl_BE', 'фламандская');
INSERT INTO `country` (`id`, `name`) VALUES ('fr', 'французская');
INSERT INTO `country` (`id`, `name`) VALUES ('fr_CA', 'французская (канад.)');
INSERT INTO `country` (`id`, `name`) VALUES ('fr_CH', 'французская (швейц.)');
INSERT INTO `country` (`id`, `name`) VALUES ('fy', 'фрызская');
INSERT INTO `country` (`id`, `name`) VALUES ('hr', 'харвацкая');
INSERT INTO `country` (`id`, `name`) VALUES ('hi', 'хіндзі');
INSERT INTO `country` (`id`, `name`) VALUES ('xh', 'хоса');
INSERT INTO `country` (`id`, `name`) VALUES ('ce', 'чачэнская');
INSERT INTO `country` (`id`, `name`) VALUES ('cv', 'чувашская');
INSERT INTO `country` (`id`, `name`) VALUES ('cs', 'чэшская');
INSERT INTO `country` (`id`, `name`) VALUES ('gd', 'шатландская гэльская');
INSERT INTO `country` (`id`, `name`) VALUES ('sv', 'шведская');
INSERT INTO `country` (`id`, `name`) VALUES ('art', 'штучная мова');
INSERT INTO `country` (`id`, `name`) VALUES ('eo', 'эсперанта');
INSERT INTO `country` (`id`, `name`) VALUES ('et', 'эстонская');
INSERT INTO `country` (`id`, `name`) VALUES ('jv', 'яванская');
INSERT INTO `country` (`id`, `name`) VALUES ('sah', 'якуцкая');
INSERT INTO `country` (`id`, `name`) VALUES ('ja', 'японская');
