CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('fr', 'Fala');
INSERT INTO `country` (`id`, `name`) VALUES ('de', 'Jáman');
INSERT INTO `country` (`id`, `name`) VALUES ('ak', 'Kiɛl akan');
INSERT INTO `country` (`id`, `name`) VALUES ('am', 'Kiɛl amaria');
INSERT INTO `country` (`id`, `name`) VALUES ('ar', 'Kiɛl b\'árabe');
INSERT INTO `country` (`id`, `name`) VALUES ('hi', 'Kiɛl b\'indien');
INSERT INTO `country` (`id`, `name`) VALUES ('hu', 'Kiɛl b\'ɔ́ngrois');
INSERT INTO `country` (`id`, `name`) VALUES ('uk', 'Kiɛl b\'ukrɛ̄nien');
INSERT INTO `country` (`id`, `name`) VALUES ('be', 'Kiɛl belarussie');
INSERT INTO `country` (`id`, `name`) VALUES ('bn', 'Kiɛl bengalia');
INSERT INTO `country` (`id`, `name`) VALUES ('my', 'Kiɛl birmania');
INSERT INTO `country` (`id`, `name`) VALUES ('zh', 'Kiɛl bó chinois');
INSERT INTO `country` (`id`, `name`) VALUES ('el', 'Kiɛl bó grɛk');
INSERT INTO `country` (`id`, `name`) VALUES ('ja', 'Kiɛl bó japonɛ̌');
INSERT INTO `country` (`id`, `name`) VALUES ('jv', 'Kiɛl bó javanɛ̌');
INSERT INTO `country` (`id`, `name`) VALUES ('km', 'Kiɛl bó mɛr');
INSERT INTO `country` (`id`, `name`) VALUES ('pt', 'Kiɛl bó pɔ̄rtugɛ̂');
INSERT INTO `country` (`id`, `name`) VALUES ('ro', 'Kiɛl bó rumɛ̂n');
INSERT INTO `country` (`id`, `name`) VALUES ('sv', 'Kiɛl bó suedois');
INSERT INTO `country` (`id`, `name`) VALUES ('cs', 'Kiɛl bó tchɛk');
INSERT INTO `country` (`id`, `name`) VALUES ('tr', 'Kiɛl bó turk');
INSERT INTO `country` (`id`, `name`) VALUES ('nl', 'Kiɛl bóllandais');
INSERT INTO `country` (`id`, `name`) VALUES ('bg', 'Kiɛl bulgaria');
INSERT INTO `country` (`id`, `name`) VALUES ('ig', 'Kiɛl ikbo');
INSERT INTO `country` (`id`, `name`) VALUES ('id', 'Kiɛl indonesie');
INSERT INTO `country` (`id`, `name`) VALUES ('it', 'Kiɛl italia');
INSERT INTO `country` (`id`, `name`) VALUES ('ko', 'Kiɛl koré');
INSERT INTO `country` (`id`, `name`) VALUES ('ms', 'Kiɛl Malɛ̌siā');
INSERT INTO `country` (`id`, `name`) VALUES ('ha', 'Kiɛl máwúsá');
INSERT INTO `country` (`id`, `name`) VALUES ('ne', 'Kiɛl nepal');
INSERT INTO `country` (`id`, `name`) VALUES ('pa', 'Kiɛl pɛndjabi');
INSERT INTO `country` (`id`, `name`) VALUES ('fa', 'Kiɛl pɛrsia');
INSERT INTO `country` (`id`, `name`) VALUES ('pl', 'Kiɛl pɔlɔŋe');
INSERT INTO `country` (`id`, `name`) VALUES ('ru', 'Kiɛl russia');
INSERT INTO `country` (`id`, `name`) VALUES ('rw', 'Kiɛl rwandā');
INSERT INTO `country` (`id`, `name`) VALUES ('so', 'Kiɛl somaliā');
INSERT INTO `country` (`id`, `name`) VALUES ('ta', 'Kiɛl tamul');
INSERT INTO `country` (`id`, `name`) VALUES ('th', 'Kiɛl thaï');
INSERT INTO `country` (`id`, `name`) VALUES ('ur', 'Kiɛl úrdu');
INSERT INTO `country` (`id`, `name`) VALUES ('vi', 'Kiɛl viɛtnam');
INSERT INTO `country` (`id`, `name`) VALUES ('en', 'Ngɛ̄lɛ̄n');
INSERT INTO `country` (`id`, `name`) VALUES ('es', 'Paŋá');
INSERT INTO `country` (`id`, `name`) VALUES ('yo', 'Yorúbâ');
INSERT INTO `country` (`id`, `name`) VALUES ('zu', 'Zulu');
