CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('ady', 'ადიღეური');
INSERT INTO [country] ([id], [name]) VALUES ('ae', 'ავესტა');
INSERT INTO [country] ([id], [name]) VALUES ('en_AU', 'ავსტრალიური ინგლისური');
INSERT INTO [country] ([id], [name]) VALUES ('ast', 'ავსტრიული');
INSERT INTO [country] ([id], [name]) VALUES ('de_AT', 'ავსტრიული გერმანული');
INSERT INTO [country] ([id], [name]) VALUES ('az', 'აზერბაიჯანული');
INSERT INTO [country] ([id], [name]) VALUES ('ain', 'აინუ');
INSERT INTO [country] ([id], [name]) VALUES ('sq', 'ალბანური');
INSERT INTO [country] ([id], [name]) VALUES ('ale', 'ალეუტური');
INSERT INTO [country] ([id], [name]) VALUES ('en_US', 'ამერიკული ინგლისური');
INSERT INTO [country] ([id], [name]) VALUES ('ar', 'არაბული');
INSERT INTO [country] ([id], [name]) VALUES ('arc', 'არამეული');
INSERT INTO [country] ([id], [name]) VALUES ('as', 'ასამური');
INSERT INTO [country] ([id], [name]) VALUES ('af', 'აფრიკული');
INSERT INTO [country] ([id], [name]) VALUES ('ab', 'აფხაზური');
INSERT INTO [country] ([id], [name]) VALUES ('eu', 'ბასკური');
INSERT INTO [country] ([id], [name]) VALUES ('be', 'ბელორუსული');
INSERT INTO [country] ([id], [name]) VALUES ('el', 'ბერძნული');
INSERT INTO [country] ([id], [name]) VALUES ('bh', 'ბიჰარი');
INSERT INTO [country] ([id], [name]) VALUES ('bs', 'ბოსნიური');
INSERT INTO [country] ([id], [name]) VALUES ('pt_BR', 'ბრაზილიური პორტუგალიური');
INSERT INTO [country] ([id], [name]) VALUES ('br', 'ბრეტონული');
INSERT INTO [country] ([id], [name]) VALUES ('en_GB', 'ბრიტანული ინგლისური');
INSERT INTO [country] ([id], [name]) VALUES ('bg', 'ბულგარული');
INSERT INTO [country] ([id], [name]) VALUES ('bua', 'ბურიატული');
INSERT INTO [country] ([id], [name]) VALUES ('gl', 'გალური');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hans', 'გამარტივებული ჩინური');
INSERT INTO [country] ([id], [name]) VALUES ('de', 'გერმანული');
INSERT INTO [country] ([id], [name]) VALUES ('gn', 'გუარანი');
INSERT INTO [country] ([id], [name]) VALUES ('gu', 'გუჯარათი');
INSERT INTO [country] ([id], [name]) VALUES ('da', 'დანიური');
INSERT INTO [country] ([id], [name]) VALUES ('he', 'ებრაული');
INSERT INTO [country] ([id], [name]) VALUES ('egy', 'ეგვიპტური');
INSERT INTO [country] ([id], [name]) VALUES ('es', 'ესპანური');
INSERT INTO [country] ([id], [name]) VALUES ('eo', 'ესპერანტო');
INSERT INTO [country] ([id], [name]) VALUES ('et', 'ესტონური');
INSERT INTO [country] ([id], [name]) VALUES ('vi', 'ვიეტნამური');
INSERT INTO [country] ([id], [name]) VALUES ('zu', 'ზულუ');
INSERT INTO [country] ([id], [name]) VALUES ('tw', 'თუი');
INSERT INTO [country] ([id], [name]) VALUES ('tk', 'თურქმენული');
INSERT INTO [country] ([id], [name]) VALUES ('tr', 'თურქული');
INSERT INTO [country] ([id], [name]) VALUES ('jv', 'იავანური');
INSERT INTO [country] ([id], [name]) VALUES ('ja', 'იაპონური');
INSERT INTO [country] ([id], [name]) VALUES ('pt_PT', 'იბერიულ-პორტუგალიური');
INSERT INTO [country] ([id], [name]) VALUES ('es_ES', 'იბერიული ესპანური');
INSERT INTO [country] ([id], [name]) VALUES ('yi', 'იდიში');
INSERT INTO [country] ([id], [name]) VALUES ('en', 'ინგლისური');
INSERT INTO [country] ([id], [name]) VALUES ('ine', 'ინდო-ევროპული სხვა');
INSERT INTO [country] ([id], [name]) VALUES ('id', 'ინდონეზიური');
INSERT INTO [country] ([id], [name]) VALUES ('ie', 'ინტერლინგი');
INSERT INTO [country] ([id], [name]) VALUES ('ia', 'ინტერლინგუალური');
INSERT INTO [country] ([id], [name]) VALUES ('ga', 'ირლანდიური');
INSERT INTO [country] ([id], [name]) VALUES ('is', 'ისლანდიური');
INSERT INTO [country] ([id], [name]) VALUES ('it', 'იტალიური');
INSERT INTO [country] ([id], [name]) VALUES ('cau', 'კავკასიური სხვა');
INSERT INTO [country] ([id], [name]) VALUES ('km', 'კამბოჯიური');
INSERT INTO [country] ([id], [name]) VALUES ('en_CA', 'კანადური ინგლისური');
INSERT INTO [country] ([id], [name]) VALUES ('fr_CA', 'კანადური ფრანგული');
INSERT INTO [country] ([id], [name]) VALUES ('ca', 'კატალანური');
INSERT INTO [country] ([id], [name]) VALUES ('cel', 'კელტური სხვა');
INSERT INTO [country] ([id], [name]) VALUES ('tlh', 'კლინგონი');
INSERT INTO [country] ([id], [name]) VALUES ('kg', 'კონგო');
INSERT INTO [country] ([id], [name]) VALUES ('ko', 'კორეული');
INSERT INTO [country] ([id], [name]) VALUES ('es_419', 'ლათინურ ამერიკული ესპანური');
INSERT INTO [country] ([id], [name]) VALUES ('la', 'ლათინური');
INSERT INTO [country] ([id], [name]) VALUES ('lo', 'ლაოსური');
INSERT INTO [country] ([id], [name]) VALUES ('lv', 'ლატვიური');
INSERT INTO [country] ([id], [name]) VALUES ('ln', 'ლინგალა');
INSERT INTO [country] ([id], [name]) VALUES ('lt', 'ლიტვური');
INSERT INTO [country] ([id], [name]) VALUES ('lb', 'ლუქსემბურგული');
INSERT INTO [country] ([id], [name]) VALUES ('myn', 'მაიას ენები');
INSERT INTO [country] ([id], [name]) VALUES ('mk', 'მაკედონიური');
INSERT INTO [country] ([id], [name]) VALUES ('ms', 'მალაიზიური');
INSERT INTO [country] ([id], [name]) VALUES ('mo', 'მოლდოვური');
INSERT INTO [country] ([id], [name]) VALUES ('mn', 'მონღოლური');
INSERT INTO [country] ([id], [name]) VALUES ('nv', 'ნავახო');
INSERT INTO [country] ([id], [name]) VALUES ('nap', 'ნეაპოლიტანური');
INSERT INTO [country] ([id], [name]) VALUES ('ne', 'ნეპალური');
INSERT INTO [country] ([id], [name]) VALUES ('no', 'ნორვეგიული');
INSERT INTO [country] ([id], [name]) VALUES ('nn', 'ნორვეგიული ნინორსკი');
INSERT INTO [country] ([id], [name]) VALUES ('or', 'ორიული');
INSERT INTO [country] ([id], [name]) VALUES ('os', 'ოსური');
INSERT INTO [country] ([id], [name]) VALUES ('oc', 'ოციტანური');
INSERT INTO [country] ([id], [name]) VALUES ('pl', 'პოლონური');
INSERT INTO [country] ([id], [name]) VALUES ('pt', 'პორტუგალიური');
INSERT INTO [country] ([id], [name]) VALUES ('pra', 'პრაკრიტის ენები');
INSERT INTO [country] ([id], [name]) VALUES ('ps', 'პუშტუ');
INSERT INTO [country] ([id], [name]) VALUES ('ro', 'რუმინული');
INSERT INTO [country] ([id], [name]) VALUES ('ru', 'რუსული');
INSERT INTO [country] ([id], [name]) VALUES ('cu', 'საეკლესიო სლავური');
INSERT INTO [country] ([id], [name]) VALUES ('st', 'სამხრეთ სოთოს ენა');
INSERT INTO [country] ([id], [name]) VALUES ('sa', 'სანსკრიტი');
INSERT INTO [country] ([id], [name]) VALUES ('sc', 'სარდინიული');
INSERT INTO [country] ([id], [name]) VALUES ('sh', 'სერბულ-ხორვატული');
INSERT INTO [country] ([id], [name]) VALUES ('sr', 'სერბული');
INSERT INTO [country] ([id], [name]) VALUES ('sd', 'სინდური');
INSERT INTO [country] ([id], [name]) VALUES ('si', 'სინჰალური');
INSERT INTO [country] ([id], [name]) VALUES ('scn', 'სიცილიური');
INSERT INTO [country] ([id], [name]) VALUES ('sla', 'სლავური სხვა');
INSERT INTO [country] ([id], [name]) VALUES ('sk', 'სლოვაკური');
INSERT INTO [country] ([id], [name]) VALUES ('sl', 'სლოვენური');
INSERT INTO [country] ([id], [name]) VALUES ('so', 'სომალიური');
INSERT INTO [country] ([id], [name]) VALUES ('hy', 'სომხური');
INSERT INTO [country] ([id], [name]) VALUES ('fa', 'სპარსული');
INSERT INTO [country] ([id], [name]) VALUES ('sw', 'სუაჰილი');
INSERT INTO [country] ([id], [name]) VALUES ('th', 'ტაილანდური');
INSERT INTO [country] ([id], [name]) VALUES ('tg', 'ტაჯიკური');
INSERT INTO [country] ([id], [name]) VALUES ('bo', 'ტიბეტური');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hant', 'ტრადიციული ჩინური');
INSERT INTO [country] ([id], [name]) VALUES ('tn', 'ტსვანა');
INSERT INTO [country] ([id], [name]) VALUES ('udm', 'უდმურტიული');
INSERT INTO [country] ([id], [name]) VALUES ('cy', 'უელსური');
INSERT INTO [country] ([id], [name]) VALUES ('uz', 'უზბეკური');
INSERT INTO [country] ([id], [name]) VALUES ('ug', 'უიგურული');
INSERT INTO [country] ([id], [name]) VALUES ('uk', 'უკრაინული');
INSERT INTO [country] ([id], [name]) VALUES ('hu', 'უნგრული');
INSERT INTO [country] ([id], [name]) VALUES ('ur', 'ურდუ');
INSERT INTO [country] ([id], [name]) VALUES ('und', 'უცნობი ან არასწორი ენა');
INSERT INTO [country] ([id], [name]) VALUES ('fil', 'ფილიპინური');
INSERT INTO [country] ([id], [name]) VALUES ('fi', 'ფინური');
INSERT INTO [country] ([id], [name]) VALUES ('nl_BE', 'ფლომანდიური');
INSERT INTO [country] ([id], [name]) VALUES ('fr', 'ფრანგული');
INSERT INTO [country] ([id], [name]) VALUES ('ka', 'ქართული');
INSERT INTO [country] ([id], [name]) VALUES ('xh', 'ქსოზა');
INSERT INTO [country] ([id], [name]) VALUES ('ku', 'ქურთული');
INSERT INTO [country] ([id], [name]) VALUES ('kk', 'ყაზახური');
INSERT INTO [country] ([id], [name]) VALUES ('ky', 'ყირგიზული');
INSERT INTO [country] ([id], [name]) VALUES ('sv', 'შვედური');
INSERT INTO [country] ([id], [name]) VALUES ('gsw', 'შვეიცარიული გერმანული');
INSERT INTO [country] ([id], [name]) VALUES ('de_CH', 'შვეიცარიული მაღალი გერმანული');
INSERT INTO [country] ([id], [name]) VALUES ('fr_CH', 'შვეიცარიული ფრანგული');
INSERT INTO [country] ([id], [name]) VALUES ('gd', 'შოტლანდიურ-გალური');
INSERT INTO [country] ([id], [name]) VALUES ('sux', 'შუმერული');
INSERT INTO [country] ([id], [name]) VALUES ('ce', 'ჩეჩნური');
INSERT INTO [country] ([id], [name]) VALUES ('cs', 'ჩეხური');
INSERT INTO [country] ([id], [name]) VALUES ('zh', 'ჩინური');
INSERT INTO [country] ([id], [name]) VALUES ('grc', 'ძველი ბერძნული');
INSERT INTO [country] ([id], [name]) VALUES ('goh', 'ძველი გერმანული');
INSERT INTO [country] ([id], [name]) VALUES ('ang', 'ძველი ინგლისური');
INSERT INTO [country] ([id], [name]) VALUES ('sga', 'ძველი ირლანდიური');
INSERT INTO [country] ([id], [name]) VALUES ('peo', 'ძველი სპარსული');
INSERT INTO [country] ([id], [name]) VALUES ('fro', 'ძველი ფრანგული');
INSERT INTO [country] ([id], [name]) VALUES ('art', 'ხელოვნური სხვა');
INSERT INTO [country] ([id], [name]) VALUES ('hr', 'ხორვატიული');
INSERT INTO [country] ([id], [name]) VALUES ('hi', 'ჰინდი');
INSERT INTO [country] ([id], [name]) VALUES ('nl', 'ჰოლანდიური');
