CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('ab', 'abhāzu');
INSERT INTO "country" ("id", "name") VALUES ('ace', 'ačinu');
INSERT INTO "country" ("id", "name") VALUES ('ach', 'ačolu');
INSERT INTO "country" ("id", "name") VALUES ('ada', 'adangmu');
INSERT INTO "country" ("id", "name") VALUES ('ady', 'adigu');
INSERT INTO "country" ("id", "name") VALUES ('aa', 'afāru');
INSERT INTO "country" ("id", "name") VALUES ('afh', 'afrihili');
INSERT INTO "country" ("id", "name") VALUES ('af', 'afrikandu');
INSERT INTO "country" ("id", "name") VALUES ('afa', 'afroaziātu valodas');
INSERT INTO "country" ("id", "name") VALUES ('ay', 'aimaru');
INSERT INTO "country" ("id", "name") VALUES ('ain', 'ainu');
INSERT INTO "country" ("id", "name") VALUES ('akk', 'akadiešu');
INSERT INTO "country" ("id", "name") VALUES ('ak', 'akanu');
INSERT INTO "country" ("id", "name") VALUES ('sq', 'albāņu');
INSERT INTO "country" ("id", "name") VALUES ('ale', 'aleutu');
INSERT INTO "country" ("id", "name") VALUES ('alg', 'algonkinu valodas');
INSERT INTO "country" ("id", "name") VALUES ('tut', 'altajiešu valodas');
INSERT INTO "country" ("id", "name") VALUES ('am', 'amharu');
INSERT INTO "country" ("id", "name") VALUES ('anp', 'angika');
INSERT INTO "country" ("id", "name") VALUES ('cpe', 'angliskās kreoliskās valodas un pidžinvalodas');
INSERT INTO "country" ("id", "name") VALUES ('en', 'angļu');
INSERT INTO "country" ("id", "name") VALUES ('apa', 'apaču valodas');
INSERT INTO "country" ("id", "name") VALUES ('ar', 'arābu');
INSERT INTO "country" ("id", "name") VALUES ('an', 'aragoniešu');
INSERT INTO "country" ("id", "name") VALUES ('arc', 'aramiešu');
INSERT INTO "country" ("id", "name") VALUES ('arp', 'arapahu');
INSERT INTO "country" ("id", "name") VALUES ('arn', 'araukāņu');
INSERT INTO "country" ("id", "name") VALUES ('arw', 'aravaku');
INSERT INTO "country" ("id", "name") VALUES ('hy', 'armēņu');
INSERT INTO "country" ("id", "name") VALUES ('rup', 'aromūnu');
INSERT INTO "country" ("id", "name") VALUES ('as', 'asamiešu');
INSERT INTO "country" ("id", "name") VALUES ('ast', 'astūriešu');
INSERT INTO "country" ("id", "name") VALUES ('en_US', 'ASV angļu');
INSERT INTO "country" ("id", "name") VALUES ('ath', 'atapasku valodas');
INSERT INTO "country" ("id", "name") VALUES ('hsb', 'augšsorbu');
INSERT INTO "country" ("id", "name") VALUES ('aus', 'austrāliešu valodas');
INSERT INTO "country" ("id", "name") VALUES ('en_AU', 'Austrālijas angļu');
INSERT INTO "country" ("id", "name") VALUES ('de_AT', 'Austrijas vācu');
INSERT INTO "country" ("id", "name") VALUES ('map', 'austronēziešu valoda');
INSERT INTO "country" ("id", "name") VALUES ('frs', 'austrumfrīzu');
INSERT INTO "country" ("id", "name") VALUES ('awa', 'avadhu');
INSERT INTO "country" ("id", "name") VALUES ('av', 'avāru');
INSERT INTO "country" ("id", "name") VALUES ('ae', 'avesta');
INSERT INTO "country" ("id", "name") VALUES ('az', 'azerbaidžāņu');
INSERT INTO "country" ("id", "name") VALUES ('ban', 'baliešu');
INSERT INTO "country" ("id", "name") VALUES ('be', 'baltkrievu');
INSERT INTO "country" ("id", "name") VALUES ('bat', 'baltu valodas');
INSERT INTO "country" ("id", "name") VALUES ('bm', 'bambaru');
INSERT INTO "country" ("id", "name") VALUES ('bai', 'bamileku valodas');
INSERT INTO "country" ("id", "name") VALUES ('bad', 'bandu');
INSERT INTO "country" ("id", "name") VALUES ('bnt', 'bantu');
INSERT INTO "country" ("id", "name") VALUES ('eu', 'basku');
INSERT INTO "country" ("id", "name") VALUES ('bas', 'basu');
INSERT INTO "country" ("id", "name") VALUES ('ba', 'baškīru');
INSERT INTO "country" ("id", "name") VALUES ('btk', 'bataku');
INSERT INTO "country" ("id", "name") VALUES ('cu', 'baznīcslāvu');
INSERT INTO "country" ("id", "name") VALUES ('bej', 'bedžu');
INSERT INTO "country" ("id", "name") VALUES ('bal', 'beludžu');
INSERT INTO "country" ("id", "name") VALUES ('bem', 'bembu');
INSERT INTO "country" ("id", "name") VALUES ('bn', 'bengāļu');
INSERT INTO "country" ("id", "name") VALUES ('ber', 'berberu');
INSERT INTO "country" ("id", "name") VALUES ('zxx', 'bez lingvistiska satura');
INSERT INTO "country" ("id", "name") VALUES ('bho', 'bhodžpūru');
INSERT INTO "country" ("id", "name") VALUES ('bh', 'biharu');
INSERT INTO "country" ("id", "name") VALUES ('bik', 'bikolu');
INSERT INTO "country" ("id", "name") VALUES ('byn', 'bilinu');
INSERT INTO "country" ("id", "name") VALUES ('bin', 'binu');
INSERT INTO "country" ("id", "name") VALUES ('my', 'birmiešu');
INSERT INTO "country" ("id", "name") VALUES ('bi', 'bišlamā');
INSERT INTO "country" ("id", "name") VALUES ('bs', 'bosniešu');
INSERT INTO "country" ("id", "name") VALUES ('bra', 'bradžiešu');
INSERT INTO "country" ("id", "name") VALUES ('pt_BR', 'Brazīlijas portugāļu');
INSERT INTO "country" ("id", "name") VALUES ('br', 'bretoņu');
INSERT INTO "country" ("id", "name") VALUES ('bug', 'bugu');
INSERT INTO "country" ("id", "name") VALUES ('bg', 'bulgāru');
INSERT INTO "country" ("id", "name") VALUES ('bua', 'burjatu');
INSERT INTO "country" ("id", "name") VALUES ('cai', 'Centrālamerikas indiāņu valodas');
INSERT INTO "country" ("id", "name") VALUES ('tsi', 'cimšiāņu');
INSERT INTO "country" ("id", "name") VALUES ('ts', 'congu');
INSERT INTO "country" ("id", "name") VALUES ('tn', 'cvanu');
INSERT INTO "country" ("id", "name") VALUES ('cmc', 'čamiešu valodas');
INSERT INTO "country" ("id", "name") VALUES ('ch', 'čamorru');
INSERT INTO "country" ("id", "name") VALUES ('ce', 'čečenu');
INSERT INTO "country" ("id", "name") VALUES ('cs', 'čehu');
INSERT INTO "country" ("id", "name") VALUES ('chb', 'čibču');
INSERT INTO "country" ("id", "name") VALUES ('ny', 'čičeva');
INSERT INTO "country" ("id", "name") VALUES ('rom', 'čigānu');
INSERT INTO "country" ("id", "name") VALUES ('chn', 'činuku žargons');
INSERT INTO "country" ("id", "name") VALUES ('chp', 'čipevaianu');
INSERT INTO "country" ("id", "name") VALUES ('cho', 'čoktavu');
INSERT INTO "country" ("id", "name") VALUES ('chk', 'čūku');
INSERT INTO "country" ("id", "name") VALUES ('cv', 'čuvašu');
INSERT INTO "country" ("id", "name") VALUES ('day', 'dajaku');
INSERT INTO "country" ("id", "name") VALUES ('dak', 'dakotu');
INSERT INTO "country" ("id", "name") VALUES ('da', 'dāņu');
INSERT INTO "country" ("id", "name") VALUES ('dar', 'dargu');
INSERT INTO "country" ("id", "name") VALUES ('mis', 'dažādas valodas');
INSERT INTO "country" ("id", "name") VALUES ('del', 'delavēru');
INSERT INTO "country" ("id", "name") VALUES ('alt', 'dienvidaltajiešu');
INSERT INTO "country" ("id", "name") VALUES ('sai', 'Dienvidamerikas indiāņu');
INSERT INTO "country" ("id", "name") VALUES ('nr', 'dienvidndebelu');
INSERT INTO "country" ("id", "name") VALUES ('sma', 'dienvidsāmu');
INSERT INTO "country" ("id", "name") VALUES ('st', 'dienvidsotu');
INSERT INTO "country" ("id", "name") VALUES ('din', 'dinku');
INSERT INTO "country" ("id", "name") VALUES ('dyu', 'diūlu');
INSERT INTO "country" ("id", "name") VALUES ('dgr', 'dogribu');
INSERT INTO "country" ("id", "name") VALUES ('doi', 'dogru');
INSERT INTO "country" ("id", "name") VALUES ('dra', 'dravīdu valodas');
INSERT INTO "country" ("id", "name") VALUES ('dua', 'dualu');
INSERT INTO "country" ("id", "name") VALUES ('dz', 'dzongke');
INSERT INTO "country" ("id", "name") VALUES ('chg', 'džagatajs');
INSERT INTO "country" ("id", "name") VALUES ('za', 'džuanu');
INSERT INTO "country" ("id", "name") VALUES ('efi', 'efiku');
INSERT INTO "country" ("id", "name") VALUES ('egy', 'ēģiptiešu');
INSERT INTO "country" ("id", "name") VALUES ('eka', 'ekadžuku');
INSERT INTO "country" ("id", "name") VALUES ('elx', 'elamiešu');
INSERT INTO "country" ("id", "name") VALUES ('myv', 'erzju');
INSERT INTO "country" ("id", "name") VALUES ('eo', 'esperanto');
INSERT INTO "country" ("id", "name") VALUES ('ewo', 'evondu');
INSERT INTO "country" ("id", "name") VALUES ('ee', 'evu');
INSERT INTO "country" ("id", "name") VALUES ('fan', 'fangu');
INSERT INTO "country" ("id", "name") VALUES ('fat', 'fantu');
INSERT INTO "country" ("id", "name") VALUES ('phn', 'feniķiešu');
INSERT INTO "country" ("id", "name") VALUES ('fo', 'fēru');
INSERT INTO "country" ("id", "name") VALUES ('fj', 'fidžiešu');
INSERT INTO "country" ("id", "name") VALUES ('fil', 'filipīniešu');
INSERT INTO "country" ("id", "name") VALUES ('phi', 'filipīniešu valodas');
INSERT INTO "country" ("id", "name") VALUES ('nl_BE', 'flāmu');
INSERT INTO "country" ("id", "name") VALUES ('fon', 'fonu');
INSERT INTO "country" ("id", "name") VALUES ('cpf', 'franciskās kreoliskās valodas un pidžinvalodas');
INSERT INTO "country" ("id", "name") VALUES ('fr', 'franču');
INSERT INTO "country" ("id", "name") VALUES ('fur', 'friūlu');
INSERT INTO "country" ("id", "name") VALUES ('ff', 'fulu');
INSERT INTO "country" ("id", "name") VALUES ('gaa', 'ga');
INSERT INTO "country" ("id", "name") VALUES ('gay', 'gajo');
INSERT INTO "country" ("id", "name") VALUES ('gl', 'galisiešu');
INSERT INTO "country" ("id", "name") VALUES ('lg', 'gandu');
INSERT INTO "country" ("id", "name") VALUES ('gba', 'gbaju');
INSERT INTO "country" ("id", "name") VALUES ('gd', 'gēlu');
INSERT INTO "country" ("id", "name") VALUES ('gez', 'gēzu');
INSERT INTO "country" ("id", "name") VALUES ('gon', 'gondu valodas');
INSERT INTO "country" ("id", "name") VALUES ('gor', 'gorontalu');
INSERT INTO "country" ("id", "name") VALUES ('got', 'gotu');
INSERT INTO "country" ("id", "name") VALUES ('grb', 'grebo');
INSERT INTO "country" ("id", "name") VALUES ('kl', 'grenlandiešu');
INSERT INTO "country" ("id", "name") VALUES ('el', 'grieķu');
INSERT INTO "country" ("id", "name") VALUES ('ka', 'gruzīnu');
INSERT INTO "country" ("id", "name") VALUES ('gu', 'gudžaratu');
INSERT INTO "country" ("id", "name") VALUES ('gn', 'gvaranu');
INSERT INTO "country" ("id", "name") VALUES ('gem', 'ģermāņu valodas');
INSERT INTO "country" ("id", "name") VALUES ('hai', 'haidu');
INSERT INTO "country" ("id", "name") VALUES ('ht', 'haitiešu');
INSERT INTO "country" ("id", "name") VALUES ('ha', 'hausu');
INSERT INTO "country" ("id", "name") VALUES ('haw', 'havajiešu');
INSERT INTO "country" ("id", "name") VALUES ('hz', 'hereru');
INSERT INTO "country" ("id", "name") VALUES ('hit', 'hetu');
INSERT INTO "country" ("id", "name") VALUES ('hil', 'hiligainonu');
INSERT INTO "country" ("id", "name") VALUES ('him', 'himačali');
INSERT INTO "country" ("id", "name") VALUES ('hi', 'hindi');
INSERT INTO "country" ("id", "name") VALUES ('ho', 'hirimotu');
INSERT INTO "country" ("id", "name") VALUES ('hmn', 'hmongu');
INSERT INTO "country" ("id", "name") VALUES ('nl', 'holandiešu');
INSERT INTO "country" ("id", "name") VALUES ('hr', 'horvātu');
INSERT INTO "country" ("id", "name") VALUES ('khi', 'hosjanu valodas');
INSERT INTO "country" ("id", "name") VALUES ('kho', 'hotaniešu');
INSERT INTO "country" ("id", "name") VALUES ('hup', 'hupu');
INSERT INTO "country" ("id", "name") VALUES ('iba', 'ibanu');
INSERT INTO "country" ("id", "name") VALUES ('pt_PT', 'ibēriešu portugāļu');
INSERT INTO "country" ("id", "name") VALUES ('es_ES', 'ibēriešu spāņu');
INSERT INTO "country" ("id", "name") VALUES ('io', 'ido');
INSERT INTO "country" ("id", "name") VALUES ('ijo', 'idžbu');
INSERT INTO "country" ("id", "name") VALUES ('et', 'igauņu');
INSERT INTO "country" ("id", "name") VALUES ('ig', 'igbo');
INSERT INTO "country" ("id", "name") VALUES ('ilo', 'iloku');
INSERT INTO "country" ("id", "name") VALUES ('smn', 'inari sāmu');
INSERT INTO "country" ("id", "name") VALUES ('inc', 'indoāriešu valodas');
INSERT INTO "country" ("id", "name") VALUES ('ine', 'indoeiropiešu valodas');
INSERT INTO "country" ("id", "name") VALUES ('id', 'indonēziešu');
INSERT INTO "country" ("id", "name") VALUES ('inh', 'ingušu');
INSERT INTO "country" ("id", "name") VALUES ('ia', 'interlingva');
INSERT INTO "country" ("id", "name") VALUES ('ie', 'interlingve');
INSERT INTO "country" ("id", "name") VALUES ('iu', 'inuītu');
INSERT INTO "country" ("id", "name") VALUES ('ik', 'inupiaku');
INSERT INTO "country" ("id", "name") VALUES ('ira', 'irāņu valodas');
INSERT INTO "country" ("id", "name") VALUES ('chr', 'irokēzu');
INSERT INTO "country" ("id", "name") VALUES ('iro', 'irokēzu valodas');
INSERT INTO "country" ("id", "name") VALUES ('ga', 'īru');
INSERT INTO "country" ("id", "name") VALUES ('is', 'īslandiešu');
INSERT INTO "country" ("id", "name") VALUES ('it', 'itāļu');
INSERT INTO "country" ("id", "name") VALUES ('he', 'ivrits');
INSERT INTO "country" ("id", "name") VALUES ('sah', 'jakutu');
INSERT INTO "country" ("id", "name") VALUES ('yao', 'jao');
INSERT INTO "country" ("id", "name") VALUES ('ja', 'japāņu');
INSERT INTO "country" ("id", "name") VALUES ('yap', 'japiešu');
INSERT INTO "country" ("id", "name") VALUES ('nn', 'jaunnorvēģu');
INSERT INTO "country" ("id", "name") VALUES ('jv', 'javiešu');
INSERT INTO "country" ("id", "name") VALUES ('yi', 'jidišs');
INSERT INTO "country" ("id", "name") VALUES ('ypk', 'jopiku valodas');
INSERT INTO "country" ("id", "name") VALUES ('yo', 'jorubu');
INSERT INTO "country" ("id", "name") VALUES ('jrb', 'jūdarābu');
INSERT INTO "country" ("id", "name") VALUES ('jpr', 'jūdpersiešu');
INSERT INTO "country" ("id", "name") VALUES ('kbd', 'kabardiešu');
INSERT INTO "country" ("id", "name") VALUES ('kab', 'kabilu');
INSERT INTO "country" ("id", "name") VALUES ('kac', 'kačinu');
INSERT INTO "country" ("id", "name") VALUES ('cad', 'kadu');
INSERT INTO "country" ("id", "name") VALUES ('xal', 'kalmiku');
INSERT INTO "country" ("id", "name") VALUES ('kam', 'kambu');
INSERT INTO "country" ("id", "name") VALUES ('en_CA', 'Kanādas angļu');
INSERT INTO "country" ("id", "name") VALUES ('fr_CA', 'Kanādas franču');
INSERT INTO "country" ("id", "name") VALUES ('kn', 'kannadu');
INSERT INTO "country" ("id", "name") VALUES ('yue', 'kantoniešu');
INSERT INTO "country" ("id", "name") VALUES ('kr', 'kanuru');
INSERT INTO "country" ("id", "name") VALUES ('krc', 'karačaju un balkāru');
INSERT INTO "country" ("id", "name") VALUES ('kaa', 'karakalpaku');
INSERT INTO "country" ("id", "name") VALUES ('krl', 'karēļu');
INSERT INTO "country" ("id", "name") VALUES ('kar', 'karenu');
INSERT INTO "country" ("id", "name") VALUES ('car', 'karību');
INSERT INTO "country" ("id", "name") VALUES ('ks', 'kašmiriešu');
INSERT INTO "country" ("id", "name") VALUES ('csb', 'kašubu');
INSERT INTO "country" ("id", "name") VALUES ('ca', 'katalāņu');
INSERT INTO "country" ("id", "name") VALUES ('cau', 'kaukāziešu valodas');
INSERT INTO "country" ("id", "name") VALUES ('kaw', 'kāvi');
INSERT INTO "country" ("id", "name") VALUES ('kk', 'kazahu');
INSERT INTO "country" ("id", "name") VALUES ('qu', 'kečvu');
INSERT INTO "country" ("id", "name") VALUES ('kha', 'khasu');
INSERT INTO "country" ("id", "name") VALUES ('km', 'khmeru');
INSERT INTO "country" ("id", "name") VALUES ('xh', 'khosu');
INSERT INTO "country" ("id", "name") VALUES ('ki', 'kikuju');
INSERT INTO "country" ("id", "name") VALUES ('kmb', 'kimbundu');
INSERT INTO "country" ("id", "name") VALUES ('rw', 'kiņaruanda');
INSERT INTO "country" ("id", "name") VALUES ('ky', 'kirgīzu');
INSERT INTO "country" ("id", "name") VALUES ('gil', 'kiribatiešu');
INSERT INTO "country" ("id", "name") VALUES ('nwc', 'klasiskā nevaru');
INSERT INTO "country" ("id", "name") VALUES ('syc', 'klasiskā sīriešu');
INSERT INTO "country" ("id", "name") VALUES ('tlh', 'klingoņu');
INSERT INTO "country" ("id", "name") VALUES ('kv', 'komiešu');
INSERT INTO "country" ("id", "name") VALUES ('swb', 'komoru');
INSERT INTO "country" ("id", "name") VALUES ('kg', 'kongu');
INSERT INTO "country" ("id", "name") VALUES ('kok', 'konkanu');
INSERT INTO "country" ("id", "name") VALUES ('cop', 'koptu');
INSERT INTO "country" ("id", "name") VALUES ('ko', 'korejiešu');
INSERT INTO "country" ("id", "name") VALUES ('kw', 'korniešu');
INSERT INTO "country" ("id", "name") VALUES ('co', 'korsikāņu');
INSERT INTO "country" ("id", "name") VALUES ('kfo', 'koru');
INSERT INTO "country" ("id", "name") VALUES ('kos', 'kosrājiešu');
INSERT INTO "country" ("id", "name") VALUES ('kpe', 'kpellu');
INSERT INTO "country" ("id", "name") VALUES ('crp', 'kreoliskās valodas un pidžinvalodas');
INSERT INTO "country" ("id", "name") VALUES ('cr', 'krī');
INSERT INTO "country" ("id", "name") VALUES ('ru', 'krievu');
INSERT INTO "country" ("id", "name") VALUES ('mus', 'krīku');
INSERT INTO "country" ("id", "name") VALUES ('crh', 'Krimas tatāru');
INSERT INTO "country" ("id", "name") VALUES ('kro', 'krū');
INSERT INTO "country" ("id", "name") VALUES ('gwi', 'kučinu');
INSERT INTO "country" ("id", "name") VALUES ('kum', 'kumiku');
INSERT INTO "country" ("id", "name") VALUES ('ku', 'kurdu');
INSERT INTO "country" ("id", "name") VALUES ('kru', 'kuruhu');
INSERT INTO "country" ("id", "name") VALUES ('cus', 'kušītu valodas');
INSERT INTO "country" ("id", "name") VALUES ('kut', 'kutenaju');
INSERT INTO "country" ("id", "name") VALUES ('kj', 'kvaņamu');
INSERT INTO "country" ("id", "name") VALUES ('cel', 'ķeltu valoda');
INSERT INTO "country" ("id", "name") VALUES ('zh', 'ķīniešu');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hant', 'ķīniešu tradicionālā');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hans', 'ķīniešu vienkāršotā');
INSERT INTO "country" ("id", "name") VALUES ('lad', 'ladino');
INSERT INTO "country" ("id", "name") VALUES ('lam', 'lambu');
INSERT INTO "country" ("id", "name") VALUES ('lah', 'landu');
INSERT INTO "country" ("id", "name") VALUES ('lo', 'laosiešu');
INSERT INTO "country" ("id", "name") VALUES ('es_419', 'Latīņamerikas spāņu');
INSERT INTO "country" ("id", "name") VALUES ('la', 'latīņu');
INSERT INTO "country" ("id", "name") VALUES ('lv', 'latviešu');
INSERT INTO "country" ("id", "name") VALUES ('dsb', 'lejassorbu');
INSERT INTO "country" ("id", "name") VALUES ('nds', 'lejasvācu');
INSERT INTO "country" ("id", "name") VALUES ('lez', 'lezgīnu');
INSERT INTO "country" ("id", "name") VALUES ('en_GB', 'Lielbritānijas angļu');
INSERT INTO "country" ("id", "name") VALUES ('lt', 'lietuviešu');
INSERT INTO "country" ("id", "name") VALUES ('li', 'limburgiešu');
INSERT INTO "country" ("id", "name") VALUES ('ln', 'lingala');
INSERT INTO "country" ("id", "name") VALUES ('loz', 'lozu');
INSERT INTO "country" ("id", "name") VALUES ('jbo', 'ložbans');
INSERT INTO "country" ("id", "name") VALUES ('lu', 'lubakatanga');
INSERT INTO "country" ("id", "name") VALUES ('lua', 'lubalulva');
INSERT INTO "country" ("id", "name") VALUES ('lui', 'luisenu');
INSERT INTO "country" ("id", "name") VALUES ('lb', 'luksemburgiešu');
INSERT INTO "country" ("id", "name") VALUES ('smj', 'luleo sāmu');
INSERT INTO "country" ("id", "name") VALUES ('lun', 'lundu');
INSERT INTO "country" ("id", "name") VALUES ('luo', 'luo');
INSERT INTO "country" ("id", "name") VALUES ('lus', 'lušeju');
INSERT INTO "country" ("id", "name") VALUES ('mad', 'maduriešu');
INSERT INTO "country" ("id", "name") VALUES ('mag', 'magahiešu');
INSERT INTO "country" ("id", "name") VALUES ('myn', 'maiju valodas');
INSERT INTO "country" ("id", "name") VALUES ('mai', 'maithili');
INSERT INTO "country" ("id", "name") VALUES ('mak', 'makasaru');
INSERT INTO "country" ("id", "name") VALUES ('art', 'mākslīgās valodas');
INSERT INTO "country" ("id", "name") VALUES ('mk', 'maķedoniešu');
INSERT INTO "country" ("id", "name") VALUES ('mg', 'malagasu');
INSERT INTO "country" ("id", "name") VALUES ('ml', 'malajalu');
INSERT INTO "country" ("id", "name") VALUES ('ms', 'malajiešu');
INSERT INTO "country" ("id", "name") VALUES ('dv', 'maldīviešu');
INSERT INTO "country" ("id", "name") VALUES ('mt', 'maltiešu');
INSERT INTO "country" ("id", "name") VALUES ('mdr', 'mandaru');
INSERT INTO "country" ("id", "name") VALUES ('man', 'mandingu');
INSERT INTO "country" ("id", "name") VALUES ('mnc', 'mandžūru');
INSERT INTO "country" ("id", "name") VALUES ('mni', 'manipūru');
INSERT INTO "country" ("id", "name") VALUES ('mno', 'manobu valodas');
INSERT INTO "country" ("id", "name") VALUES ('mi', 'maoru');
INSERT INTO "country" ("id", "name") VALUES ('mr', 'maratu');
INSERT INTO "country" ("id", "name") VALUES ('chm', 'mariešu');
INSERT INTO "country" ("id", "name") VALUES ('mh', 'māršaliešu');
INSERT INTO "country" ("id", "name") VALUES ('mwr', 'marvaru');
INSERT INTO "country" ("id", "name") VALUES ('mas', 'masaju');
INSERT INTO "country" ("id", "name") VALUES ('men', 'mendu');
INSERT INTO "country" ("id", "name") VALUES ('gv', 'meniešu');
INSERT INTO "country" ("id", "name") VALUES ('mic', 'mikmaku');
INSERT INTO "country" ("id", "name") VALUES ('min', 'minangkabavu');
INSERT INTO "country" ("id", "name") VALUES ('mwl', 'mirandiešu');
INSERT INTO "country" ("id", "name") VALUES ('moh', 'mohauku');
INSERT INTO "country" ("id", "name") VALUES ('mdf', 'mokšu');
INSERT INTO "country" ("id", "name") VALUES ('mo', 'moldāvu');
INSERT INTO "country" ("id", "name") VALUES ('mn', 'mongoļu');
INSERT INTO "country" ("id", "name") VALUES ('lol', 'mongu');
INSERT INTO "country" ("id", "name") VALUES ('mkh', 'monkhmeru valodas');
INSERT INTO "country" ("id", "name") VALUES ('mos', 'mosu');
INSERT INTO "country" ("id", "name") VALUES ('mun', 'mundu valodas');
INSERT INTO "country" ("id", "name") VALUES ('na', 'nauruiešu');
INSERT INTO "country" ("id", "name") VALUES ('nv', 'navahu');
INSERT INTO "country" ("id", "name") VALUES ('nah', 'navatlu');
INSERT INTO "country" ("id", "name") VALUES ('ng', 'ndongu');
INSERT INTO "country" ("id", "name") VALUES ('nap', 'neapoliešu');
INSERT INTO "country" ("id", "name") VALUES ('ne', 'nepāliešu');
INSERT INTO "country" ("id", "name") VALUES ('new', 'nevaru');
INSERT INTO "country" ("id", "name") VALUES ('und', 'nezināma vai nederīga valoda');
INSERT INTO "country" ("id", "name") VALUES ('nic', 'nigēriešu-kordofāņu valodas');
INSERT INTO "country" ("id", "name") VALUES ('ssa', 'nīlas-sahāras valodas');
INSERT INTO "country" ("id", "name") VALUES ('niu', 'niuāņu');
INSERT INTO "country" ("id", "name") VALUES ('tog', 'njasas tongu');
INSERT INTO "country" ("id", "name") VALUES ('nia', 'njasu');
INSERT INTO "country" ("id", "name") VALUES ('nqo', 'nko');
INSERT INTO "country" ("id", "name") VALUES ('nog', 'nogaju');
INSERT INTO "country" ("id", "name") VALUES ('no', 'norvēģu');
INSERT INTO "country" ("id", "name") VALUES ('nb', 'norvēģu bukmols');
INSERT INTO "country" ("id", "name") VALUES ('nub', 'nūbiešu valodas');
INSERT INTO "country" ("id", "name") VALUES ('nzi', 'nzemu');
INSERT INTO "country" ("id", "name") VALUES ('nym', 'ņamvezu');
INSERT INTO "country" ("id", "name") VALUES ('nyn', 'ņankolu');
INSERT INTO "country" ("id", "name") VALUES ('nyo', 'ņoru');
INSERT INTO "country" ("id", "name") VALUES ('oj', 'odžibvu');
INSERT INTO "country" ("id", "name") VALUES ('oc', 'oksitāņu');
INSERT INTO "country" ("id", "name") VALUES ('or', 'oriju');
INSERT INTO "country" ("id", "name") VALUES ('om', 'oromu');
INSERT INTO "country" ("id", "name") VALUES ('os', 'osetīnu');
INSERT INTO "country" ("id", "name") VALUES ('oto', 'otomu valodas');
INSERT INTO "country" ("id", "name") VALUES ('pau', 'palaviešu');
INSERT INTO "country" ("id", "name") VALUES ('pi', 'pāli');
INSERT INTO "country" ("id", "name") VALUES ('pam', 'pampanganu');
INSERT INTO "country" ("id", "name") VALUES ('pa', 'pandžabu');
INSERT INTO "country" ("id", "name") VALUES ('pag', 'pangasinanu');
INSERT INTO "country" ("id", "name") VALUES ('pap', 'papjamento');
INSERT INTO "country" ("id", "name") VALUES ('paa', 'papuasu valodas');
INSERT INTO "country" ("id", "name") VALUES ('pal', 'pehlevi');
INSERT INTO "country" ("id", "name") VALUES ('fa', 'persiešu');
INSERT INTO "country" ("id", "name") VALUES ('pl', 'poļu');
INSERT INTO "country" ("id", "name") VALUES ('pon', 'ponapiešu');
INSERT INTO "country" ("id", "name") VALUES ('cpp', 'portugāliskās kreoliskās valodas un pidžinvalodas');
INSERT INTO "country" ("id", "name") VALUES ('pt', 'portugāļu');
INSERT INTO "country" ("id", "name") VALUES ('pra', 'prākrita valodas');
INSERT INTO "country" ("id", "name") VALUES ('ps', 'puštu');
INSERT INTO "country" ("id", "name") VALUES ('raj', 'radžastāņu');
INSERT INTO "country" ("id", "name") VALUES ('rap', 'rapanuju');
INSERT INTO "country" ("id", "name") VALUES ('rar', 'rarotongiešu');
INSERT INTO "country" ("id", "name") VALUES ('rm', 'retoromāņu');
INSERT INTO "country" ("id", "name") VALUES ('fy', 'rietumfrīzu');
INSERT INTO "country" ("id", "name") VALUES ('roa', 'romāņu valoda');
INSERT INTO "country" ("id", "name") VALUES ('ro', 'rumāņu');
INSERT INTO "country" ("id", "name") VALUES ('rn', 'rundu');
INSERT INTO "country" ("id", "name") VALUES ('root', 'sakne');
INSERT INTO "country" ("id", "name") VALUES ('sal', 'sališu valodas');
INSERT INTO "country" ("id", "name") VALUES ('sam', 'samārijas aramiešu');
INSERT INTO "country" ("id", "name") VALUES ('sm', 'samoāņu');
INSERT INTO "country" ("id", "name") VALUES ('smi', 'sāmu valodas');
INSERT INTO "country" ("id", "name") VALUES ('sad', 'sandavu');
INSERT INTO "country" ("id", "name") VALUES ('sg', 'sangu');
INSERT INTO "country" ("id", "name") VALUES ('sa', 'sanskrits');
INSERT INTO "country" ("id", "name") VALUES ('sat', 'santalu');
INSERT INTO "country" ("id", "name") VALUES ('zap', 'sapoteku');
INSERT INTO "country" ("id", "name") VALUES ('sc', 'sardīniešu');
INSERT INTO "country" ("id", "name") VALUES ('sas', 'sasaku');
INSERT INTO "country" ("id", "name") VALUES ('ceb', 'sebuāņu');
INSERT INTO "country" ("id", "name") VALUES ('sel', 'selkupu');
INSERT INTO "country" ("id", "name") VALUES ('sem', 'semītu valodas');
INSERT INTO "country" ("id", "name") VALUES ('ang', 'senangļu');
INSERT INTO "country" ("id", "name") VALUES ('goh', 'senaugšvācu');
INSERT INTO "country" ("id", "name") VALUES ('fro', 'senfranču');
INSERT INTO "country" ("id", "name") VALUES ('grc', 'sengrieķu');
INSERT INTO "country" ("id", "name") VALUES ('sga', 'senīru');
INSERT INTO "country" ("id", "name") VALUES ('non', 'sennorvēģu');
INSERT INTO "country" ("id", "name") VALUES ('peo', 'senpersu');
INSERT INTO "country" ("id", "name") VALUES ('pro', 'senprovansiešu');
INSERT INTO "country" ("id", "name") VALUES ('sr', 'serbu');
INSERT INTO "country" ("id", "name") VALUES ('sh', 'serbu-horvātu');
INSERT INTO "country" ("id", "name") VALUES ('srr', 'serēru');
INSERT INTO "country" ("id", "name") VALUES ('scn', 'sicīliešu');
INSERT INTO "country" ("id", "name") VALUES ('ii', 'Sičuaņas ji');
INSERT INTO "country" ("id", "name") VALUES ('sid', 'sidamu');
INSERT INTO "country" ("id", "name") VALUES ('bla', 'siksiku');
INSERT INTO "country" ("id", "name") VALUES ('sd', 'sindhu');
INSERT INTO "country" ("id", "name") VALUES ('si', 'singāļu');
INSERT INTO "country" ("id", "name") VALUES ('sit', 'sinotibetiešu valodas');
INSERT INTO "country" ("id", "name") VALUES ('syr', 'sīriešu');
INSERT INTO "country" ("id", "name") VALUES ('sio', 'siū valodas');
INSERT INTO "country" ("id", "name") VALUES ('sms', 'skoltsāmu');
INSERT INTO "country" ("id", "name") VALUES ('sco', 'skotu');
INSERT INTO "country" ("id", "name") VALUES ('sla', 'slāvu');
INSERT INTO "country" ("id", "name") VALUES ('den', 'sleivu');
INSERT INTO "country" ("id", "name") VALUES ('sk', 'slovāku');
INSERT INTO "country" ("id", "name") VALUES ('sl', 'slovēņu');
INSERT INTO "country" ("id", "name") VALUES ('sog', 'sogdiešu');
INSERT INTO "country" ("id", "name") VALUES ('so', 'somāļu');
INSERT INTO "country" ("id", "name") VALUES ('fi', 'somu');
INSERT INTO "country" ("id", "name") VALUES ('fiu', 'somugru valodas');
INSERT INTO "country" ("id", "name") VALUES ('son', 'songaju');
INSERT INTO "country" ("id", "name") VALUES ('snk', 'soninku');
INSERT INTO "country" ("id", "name") VALUES ('wen', 'sorbu');
INSERT INTO "country" ("id", "name") VALUES ('es', 'spāņu');
INSERT INTO "country" ("id", "name") VALUES ('srn', 'sranantogo');
INSERT INTO "country" ("id", "name") VALUES ('suk', 'sukumu');
INSERT INTO "country" ("id", "name") VALUES ('su', 'sundaniešu');
INSERT INTO "country" ("id", "name") VALUES ('sus', 'susu');
INSERT INTO "country" ("id", "name") VALUES ('sw', 'svahili');
INSERT INTO "country" ("id", "name") VALUES ('ss', 'svatu');
INSERT INTO "country" ("id", "name") VALUES ('shn', 'šanu');
INSERT INTO "country" ("id", "name") VALUES ('chy', 'šejenu');
INSERT INTO "country" ("id", "name") VALUES ('sn', 'šonu');
INSERT INTO "country" ("id", "name") VALUES ('sux', 'šumeru');
INSERT INTO "country" ("id", "name") VALUES ('de_CH', 'Šveices augšvācu');
INSERT INTO "country" ("id", "name") VALUES ('fr_CH', 'Šveices franču');
INSERT INTO "country" ("id", "name") VALUES ('gsw', 'Šveices vācu');
INSERT INTO "country" ("id", "name") VALUES ('tg', 'tadžiku');
INSERT INTO "country" ("id", "name") VALUES ('tl', 'tagalu');
INSERT INTO "country" ("id", "name") VALUES ('ty', 'taitiešu');
INSERT INTO "country" ("id", "name") VALUES ('th', 'taju');
INSERT INTO "country" ("id", "name") VALUES ('tai', 'taju valodas');
INSERT INTO "country" ("id", "name") VALUES ('ta', 'tamilu');
INSERT INTO "country" ("id", "name") VALUES ('tt', 'tatāru');
INSERT INTO "country" ("id", "name") VALUES ('te', 'telugu');
INSERT INTO "country" ("id", "name") VALUES ('tem', 'temnu');
INSERT INTO "country" ("id", "name") VALUES ('ter', 'tereno');
INSERT INTO "country" ("id", "name") VALUES ('tet', 'tetumu');
INSERT INTO "country" ("id", "name") VALUES ('bo', 'tibetiešu');
INSERT INTO "country" ("id", "name") VALUES ('ti', 'tigrinja');
INSERT INTO "country" ("id", "name") VALUES ('tig', 'tigru');
INSERT INTO "country" ("id", "name") VALUES ('tiv', 'tivu');
INSERT INTO "country" ("id", "name") VALUES ('tli', 'tlinkitu');
INSERT INTO "country" ("id", "name") VALUES ('tkl', 'tokelaviešu');
INSERT INTO "country" ("id", "name") VALUES ('tpi', 'tokpisins');
INSERT INTO "country" ("id", "name") VALUES ('to', 'tongu');
INSERT INTO "country" ("id", "name") VALUES ('tmh', 'tuaregu');
INSERT INTO "country" ("id", "name") VALUES ('tum', 'tumbuku');
INSERT INTO "country" ("id", "name") VALUES ('tup', 'tupu valodas');
INSERT INTO "country" ("id", "name") VALUES ('tk', 'turkmēņu');
INSERT INTO "country" ("id", "name") VALUES ('tr', 'turku');
INSERT INTO "country" ("id", "name") VALUES ('ota', 'turku osmaņu');
INSERT INTO "country" ("id", "name") VALUES ('tvl', 'tuvaliešu');
INSERT INTO "country" ("id", "name") VALUES ('tyv', 'tuviešu');
INSERT INTO "country" ("id", "name") VALUES ('tw', 'tvī');
INSERT INTO "country" ("id", "name") VALUES ('udm', 'udmurtu');
INSERT INTO "country" ("id", "name") VALUES ('uga', 'ugaritiešu');
INSERT INTO "country" ("id", "name") VALUES ('ug', 'uiguru');
INSERT INTO "country" ("id", "name") VALUES ('uk', 'ukraiņu');
INSERT INTO "country" ("id", "name") VALUES ('umb', 'umbundu');
INSERT INTO "country" ("id", "name") VALUES ('hu', 'ungāru');
INSERT INTO "country" ("id", "name") VALUES ('ur', 'urdu');
INSERT INTO "country" ("id", "name") VALUES ('uz', 'uzbeku');
INSERT INTO "country" ("id", "name") VALUES ('de', 'vācu');
INSERT INTO "country" ("id", "name") VALUES ('vai', 'vaju');
INSERT INTO "country" ("id", "name") VALUES ('wak', 'vakašu valodas');
INSERT INTO "country" ("id", "name") VALUES ('wal', 'valamu');
INSERT INTO "country" ("id", "name") VALUES ('wa', 'valoņu');
INSERT INTO "country" ("id", "name") VALUES ('war', 'varaju');
INSERT INTO "country" ("id", "name") VALUES ('was', 'vašo');
INSERT INTO "country" ("id", "name") VALUES ('osa', 'važāžu');
INSERT INTO "country" ("id", "name") VALUES ('cy', 'velsiešu');
INSERT INTO "country" ("id", "name") VALUES ('ve', 'vendu');
INSERT INTO "country" ("id", "name") VALUES ('enm', 'vidusangļu');
INSERT INTO "country" ("id", "name") VALUES ('gmh', 'vidusaugšvācu');
INSERT INTO "country" ("id", "name") VALUES ('frm', 'vidusfranču');
INSERT INTO "country" ("id", "name") VALUES ('dum', 'vidusholandiešu');
INSERT INTO "country" ("id", "name") VALUES ('mga', 'vidusīru');
INSERT INTO "country" ("id", "name") VALUES ('vi', 'vjetnamiešu');
INSERT INTO "country" ("id", "name") VALUES ('vo', 'volapiks');
INSERT INTO "country" ("id", "name") VALUES ('wo', 'volofu');
INSERT INTO "country" ("id", "name") VALUES ('vot', 'votu');
INSERT INTO "country" ("id", "name") VALUES ('znd', 'zandē');
INSERT INTO "country" ("id", "name") VALUES ('zen', 'zenagu');
INSERT INTO "country" ("id", "name") VALUES ('nai', 'Ziemeļamerikas indiāņu valodas');
INSERT INTO "country" ("id", "name") VALUES ('frr', 'ziemeļfrīzu');
INSERT INTO "country" ("id", "name") VALUES ('nd', 'ziemeļndebelu');
INSERT INTO "country" ("id", "name") VALUES ('se', 'ziemeļsāmu');
INSERT INTO "country" ("id", "name") VALUES ('nso', 'ziemeļsotu');
INSERT INTO "country" ("id", "name") VALUES ('sgn', 'zīmju valodas');
INSERT INTO "country" ("id", "name") VALUES ('zu', 'zulu');
INSERT INTO "country" ("id", "name") VALUES ('zun', 'zunju');
INSERT INTO "country" ("id", "name") VALUES ('sv', 'zviedru');
