CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('kac', 'ကချင်');
INSERT INTO `country` (`id`, `name`) VALUES ('fr_CA', 'ကနေဒါ ပြင်သစ်');
INSERT INTO `country` (`id`, `name`) VALUES ('en_CA', 'ကနေဒါ အင်္ဂလိပ်');
INSERT INTO `country` (`id`, `name`) VALUES ('kar', 'ကရင်');
INSERT INTO `country` (`id`, `name`) VALUES ('ko', 'ကိုးရီးယား');
INSERT INTO `country` (`id`, `name`) VALUES ('cau', 'ကောက်ကေးရှပ် ဘာသာစကား');
INSERT INTO `country` (`id`, `name`) VALUES ('ku', 'ကဒ်');
INSERT INTO `country` (`id`, `name`) VALUES ('kn', 'ကန်နာဒါ');
INSERT INTO `country` (`id`, `name`) VALUES ('kg', 'ကွန်ဂို');
INSERT INTO `country` (`id`, `name`) VALUES ('km', 'ခမာ');
INSERT INTO `country` (`id`, `name`) VALUES ('cr', 'ခရီး');
INSERT INTO `country` (`id`, `name`) VALUES ('hr', 'ခရိုအေရှန်');
INSERT INTO `country` (`id`, `name`) VALUES ('kha', 'ခါစီ');
INSERT INTO `country` (`id`, `name`) VALUES ('chr', 'ချာရိုကီ');
INSERT INTO `country` (`id`, `name`) VALUES ('ce', 'ချေချင်း');
INSERT INTO `country` (`id`, `name`) VALUES ('cs', 'ချက်');
INSERT INTO `country` (`id`, `name`) VALUES ('el', 'ဂရိ');
INSERT INTO `country` (`id`, `name`) VALUES ('gu', 'ဂူဂျာရသီ');
INSERT INTO `country` (`id`, `name`) VALUES ('ja', 'ဂျပန်');
INSERT INTO `country` (`id`, `name`) VALUES ('jv', 'ဂျာဗားနီးစ်');
INSERT INTO `country` (`id`, `name`) VALUES ('de', 'ဂျာမန်');
INSERT INTO `country` (`id`, `name`) VALUES ('gem', 'ဂျာမန် အခြေခံဘာသာစကား');
INSERT INTO `country` (`id`, `name`) VALUES ('jpr', 'ဂျူဒီယို-ပါရှန်');
INSERT INTO `country` (`id`, `name`) VALUES ('jrb', 'ဂျူဒီယို-အာရေဗျ');
INSERT INTO `country` (`id`, `name`) VALUES ('ka', 'ဂျော်ဂျီယန်');
INSERT INTO `country` (`id`, `name`) VALUES ('sco', 'စကော့');
INSERT INTO `country` (`id`, `name`) VALUES ('es', 'စပိန်');
INSERT INTO `country` (`id`, `name`) VALUES ('sl', 'စလိုဗေးနီးယမ်း');
INSERT INTO `country` (`id`, `name`) VALUES ('sk', 'စလိုဗက်');
INSERT INTO `country` (`id`, `name`) VALUES ('sla', 'စလိုဗစ် ဘာသာစကား');
INSERT INTO `country` (`id`, `name`) VALUES ('ii', 'စီချွမ် ရီ');
INSERT INTO `country` (`id`, `name`) VALUES ('sd', 'စင်ဒီ');
INSERT INTO `country` (`id`, `name`) VALUES ('smi', 'ဆာမိ ဘာသာစကား');
INSERT INTO `country` (`id`, `name`) VALUES ('sr', 'ဆားဗီးယန်း');
INSERT INTO `country` (`id`, `name`) VALUES ('su', 'ဆူဒန်');
INSERT INTO `country` (`id`, `name`) VALUES ('so', 'ဆိုမာလီ');
INSERT INTO `country` (`id`, `name`) VALUES ('si', 'ဆင်ဟာလ');
INSERT INTO `country` (`id`, `name`) VALUES ('sv', 'ဆွီဒင်');
INSERT INTO `country` (`id`, `name`) VALUES ('gsw', 'ဆွစ် ဂျာမန်');
INSERT INTO `country` (`id`, `name`) VALUES ('fr_CH', 'ဆွစ် ပြင်သစ်');
INSERT INTO `country` (`id`, `name`) VALUES ('de_CH', 'ဆွစ် အမြင့် ဂျာမန်');
INSERT INTO `country` (`id`, `name`) VALUES ('zu', 'ဇူလူ');
INSERT INTO `country` (`id`, `name`) VALUES ('ta', 'တမီးလ်');
INSERT INTO `country` (`id`, `name`) VALUES ('zh', 'တရုတ်');
INSERT INTO `country` (`id`, `name`) VALUES ('sit', 'တရုတ်-တိဘက် ဘာသာစကား');
INSERT INTO `country` (`id`, `name`) VALUES ('bo', 'တိဘက်');
INSERT INTO `country` (`id`, `name`) VALUES ('tup', 'တူပီ ဘာသာစကား');
INSERT INTO `country` (`id`, `name`) VALUES ('sai', 'တောင် အမေရိကန် အိန္ဒြိယ ဘာသာစကား');
INSERT INTO `country` (`id`, `name`) VALUES ('sma', 'တောင်ပိုင်း ဆာမိ');
INSERT INTO `country` (`id`, `name`) VALUES ('tai', 'တိုင် ဘာသာစကား');
INSERT INTO `country` (`id`, `name`) VALUES ('th', 'ထိုင်း');
INSERT INTO `country` (`id`, `name`) VALUES ('dak', 'ဒါကိုတာ');
INSERT INTO `country` (`id`, `name`) VALUES ('del', 'ဒီလာဝဲ');
INSERT INTO `country` (`id`, `name`) VALUES ('nl', 'ဒတ်ချ်');
INSERT INTO `country` (`id`, `name`) VALUES ('da', 'ဒိန်းမတ်');
INSERT INTO `country` (`id`, `name`) VALUES ('dz', 'ဒွန်ကာ');
INSERT INTO `country` (`id`, `name`) VALUES ('ne', 'နီပေါလ်');
INSERT INTO `country` (`id`, `name`) VALUES ('no', 'နော်ဝေး');
INSERT INTO `country` (`id`, `name`) VALUES ('paa', 'ပါပူရန် ဘာသာစကား');
INSERT INTO `country` (`id`, `name`) VALUES ('fa', 'ပါရှန်');
INSERT INTO `country` (`id`, `name`) VALUES ('peo', 'ပါရှန် အဟောင်း');
INSERT INTO `country` (`id`, `name`) VALUES ('pi', 'ပါဠိ');
INSERT INTO `country` (`id`, `name`) VALUES ('pt', 'ပေါ်တူဂီ');
INSERT INTO `country` (`id`, `name`) VALUES ('cpp', 'ပေါ်တူဂီ အခြေခံ အနောက်အိန္ဒြိယ ကျွန်းစုသား သို့မဟုတ် ဗန်းစကား');
INSERT INTO `country` (`id`, `name`) VALUES ('pl', 'ပိုလန်');
INSERT INTO `country` (`id`, `name`) VALUES ('pa', 'ပန်ဂျာပီ');
INSERT INTO `country` (`id`, `name`) VALUES ('fr', 'ပြင်သစ်');
INSERT INTO `country` (`id`, `name`) VALUES ('fro', 'ပြင်သစ်ဟောင်း');
INSERT INTO `country` (`id`, `name`) VALUES ('fil', 'ဖိလစ်ပီနို');
INSERT INTO `country` (`id`, `name`) VALUES ('phi', 'ဖိလစ်ပိုင် ဘာသာစကား');
INSERT INTO `country` (`id`, `name`) VALUES ('fj', 'ဖီဂျီ');
INSERT INTO `country` (`id`, `name`) VALUES ('fi', 'ဖင်နစ်ရှ်');
INSERT INTO `country` (`id`, `name`) VALUES ('my', 'ဗမာ');
INSERT INTO `country` (`id`, `name`) VALUES ('vi', 'ဗီယက်နမ်');
INSERT INTO `country` (`id`, `name`) VALUES ('en_GB', 'ဗြိတိသျှ အင်္ဂလိပ်');
INSERT INTO `country` (`id`, `name`) VALUES ('pt_BR', 'ဘရာဇီး ပေါ်တူဂီ');
INSERT INTO `country` (`id`, `name`) VALUES ('bas', 'ဘာဆာ');
INSERT INTO `country` (`id`, `name`) VALUES ('ban', 'ဘာလီ');
INSERT INTO `country` (`id`, `name`) VALUES ('zxx', 'ဘာသာစကား နှင့် ပတ်သက် သောအရာမရှိ');
INSERT INTO `country` (`id`, `name`) VALUES ('be', 'ဘီလာရု');
INSERT INTO `country` (`id`, `name`) VALUES ('bg', 'ဘူဂေးရီးယား');
INSERT INTO `country` (`id`, `name`) VALUES ('bs', 'ဘော့စ်နီးယား');
INSERT INTO `country` (`id`, `name`) VALUES ('bat', 'ဘော်လတစ် ဘာသာစကား');
INSERT INTO `country` (`id`, `name`) VALUES ('bn', 'ဘင်္ဂါလီ');
INSERT INTO `country` (`id`, `name`) VALUES ('mno', 'မနိုဘို ဘာသာစကား');
INSERT INTO `country` (`id`, `name`) VALUES ('ms', 'မလေး');
INSERT INTO `country` (`id`, `name`) VALUES ('ml', 'မလေးရာလမ်');
INSERT INTO `country` (`id`, `name`) VALUES ('und', 'မသိ သို့မဟုတ် မရှိ သော ဘာသာစကား');
INSERT INTO `country` (`id`, `name`) VALUES ('mr', 'မာရသီ');
INSERT INTO `country` (`id`, `name`) VALUES ('root', 'မူလရင်းမြစ်');
INSERT INTO `country` (`id`, `name`) VALUES ('mnc', 'မန်ချူး');
INSERT INTO `country` (`id`, `name`) VALUES ('frr', 'မြောက်ပိုင်း ဖရီစီရန်');
INSERT INTO `country` (`id`, `name`) VALUES ('mkh', 'မွန်-ခမာ ဘာသာစကား');
INSERT INTO `country` (`id`, `name`) VALUES ('mn', 'မွန်ဂိုလီးယန်း');
INSERT INTO `country` (`id`, `name`) VALUES ('uk', 'ယူကရိန်း');
INSERT INTO `country` (`id`, `name`) VALUES ('ru', 'ရုရှ');
INSERT INTO `country` (`id`, `name`) VALUES ('ro', 'ရိုမေနီယား');
INSERT INTO `country` (`id`, `name`) VALUES ('zh_Hans', 'ရိုးရှင်းသော တရုတ်');
INSERT INTO `country` (`id`, `name`) VALUES ('zh_Hant', 'ရှေးရိုးစဉ်လာ တရုတ်');
INSERT INTO `country` (`id`, `name`) VALUES ('grc', 'ရှေးဟောင်း ဂရိ');
INSERT INTO `country` (`id`, `name`) VALUES ('egy', 'ရှေးဟောင်း အီဂျစ်');
INSERT INTO `country` (`id`, `name`) VALUES ('shn', 'ရှမ်း');
INSERT INTO `country` (`id`, `name`) VALUES ('lo', 'လာအို');
INSERT INTO `country` (`id`, `name`) VALUES ('la', 'လက်တင်');
INSERT INTO `country` (`id`, `name`) VALUES ('es_419', 'လက်တင်အမေရိက စပိန်');
INSERT INTO `country` (`id`, `name`) VALUES ('cy', 'ဝေလ');
INSERT INTO `country` (`id`, `name`) VALUES ('sa', 'သင်္သကရိုက်');
INSERT INTO `country` (`id`, `name`) VALUES ('haw', 'ဟာဝေယံ');
INSERT INTO `country` (`id`, `name`) VALUES ('he', 'ဟီးဘရူး');
INSERT INTO `country` (`id`, `name`) VALUES ('hu', 'ဟန်ဂေရီ');
INSERT INTO `country` (`id`, `name`) VALUES ('hi', 'ဟိန္ဒီ');
INSERT INTO `country` (`id`, `name`) VALUES ('sgn', 'အချက်ပြ ဘာသာစကား');
INSERT INTO `country` (`id`, `name`) VALUES ('fy', 'အနောက်ပိုင်း ဖရီစီရန်');
INSERT INTO `country` (`id`, `name`) VALUES ('nds', 'အနိမ့် ဂျာမန်');
INSERT INTO `country` (`id`, `name`) VALUES ('en_US', 'အမေရိကန် အင်္ဂလိပ်');
INSERT INTO `country` (`id`, `name`) VALUES ('mis', 'အမျိုးမျိုးသော ဘာသာစကား');
INSERT INTO `country` (`id`, `name`) VALUES ('art', 'အယောင်ဆောင် ဘာသာစကား');
INSERT INTO `country` (`id`, `name`) VALUES ('frs', 'အရှေ့ပိုင်း ဖရီစီရန်');
INSERT INTO `country` (`id`, `name`) VALUES ('dum', 'အလယ်ပိုင်း ဒတ်ချ်');
INSERT INTO `country` (`id`, `name`) VALUES ('enm', 'အလယ်ပိုင်း အင်္ဂလိပ်');
INSERT INTO `country` (`id`, `name`) VALUES ('mga', 'အလယ်ပိုင်း အိုင်းရစ်');
INSERT INTO `country` (`id`, `name`) VALUES ('frm', 'အလယ်ပိုင်းပြင်သစ်');
INSERT INTO `country` (`id`, `name`) VALUES ('gmh', 'အလယ်ပိုင်းအမြင့်ဂျာမန်');
INSERT INTO `country` (`id`, `name`) VALUES ('ar', 'အာရေဗီ');
INSERT INTO `country` (`id`, `name`) VALUES ('it', 'အီတလီ');
INSERT INTO `country` (`id`, `name`) VALUES ('ira', 'အီရန် အခြေခံ ဘာသာစကား');
INSERT INTO `country` (`id`, `name`) VALUES ('de_AT', 'ဩစတြီးယ ဂျာမန်');
INSERT INTO `country` (`id`, `name`) VALUES ('en_AU', 'ဩစတြေးလျှ အင်္ဂလိပ်');
INSERT INTO `country` (`id`, `name`) VALUES ('et', 'အက်စ်တိုးနီးရန်း');
INSERT INTO `country` (`id`, `name`) VALUES ('en', 'အင်္ဂလိပ်');
INSERT INTO `country` (`id`, `name`) VALUES ('ang', 'အင်္ဂလိပ်စာဟောင်း');
INSERT INTO `country` (`id`, `name`) VALUES ('ine', 'အင်ဒို ဥရောပ ဘာသာစကား');
INSERT INTO `country` (`id`, `name`) VALUES ('id', 'အင်ဒိုနီးရှား');
INSERT INTO `country` (`id`, `name`) VALUES ('ga', 'အိုင်းရစ်');
INSERT INTO `country` (`id`, `name`) VALUES ('sga', 'အိုင်းရစ် ဟောင်း');
INSERT INTO `country` (`id`, `name`) VALUES ('sq', 'အယ်လ်ဘေးနီးယန်း');
