CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('az', 'азарбежан');
INSERT INTO "country" ("id", "name") VALUES ('sq', 'албани');
INSERT INTO "country" ("id", "name") VALUES ('am', 'амхарик');
INSERT INTO "country" ("id", "name") VALUES ('en', 'англи');
INSERT INTO "country" ("id", "name") VALUES ('ar', 'араб');
INSERT INTO "country" ("id", "name") VALUES ('hy', 'армен');
INSERT INTO "country" ("id", "name") VALUES ('as', 'ассам үндэстэн');
INSERT INTO "country" ("id", "name") VALUES ('ps', 'афган');
INSERT INTO "country" ("id", "name") VALUES ('af', 'африк');
INSERT INTO "country" ("id", "name") VALUES ('sw', 'африкийн свахили хэл');
INSERT INTO "country" ("id", "name") VALUES ('ne', 'балба');
INSERT INTO "country" ("id", "name") VALUES ('eu', 'баск');
INSERT INTO "country" ("id", "name") VALUES ('be', 'беларусь');
INSERT INTO "country" ("id", "name") VALUES ('bn', 'бенгаль');
INSERT INTO "country" ("id", "name") VALUES ('bh', 'бихари хэл');
INSERT INTO "country" ("id", "name") VALUES ('bg', 'болгар');
INSERT INTO "country" ("id", "name") VALUES ('bs', 'босниа');
INSERT INTO "country" ("id", "name") VALUES ('br', 'бретон');
INSERT INTO "country" ("id", "name") VALUES ('vi', 'вьетнам');
INSERT INTO "country" ("id", "name") VALUES ('gl', 'галик');
INSERT INTO "country" ("id", "name") VALUES ('de', 'герман');
INSERT INTO "country" ("id", "name") VALUES ('nl', 'голланд');
INSERT INTO "country" ("id", "name") VALUES ('fy', 'голландын фрисиан хэл');
INSERT INTO "country" ("id", "name") VALUES ('el', 'грек');
INSERT INTO "country" ("id", "name") VALUES ('gn', 'гуарани');
INSERT INTO "country" ("id", "name") VALUES ('ka', 'гүрж');
INSERT INTO "country" ("id", "name") VALUES ('da', 'дани');
INSERT INTO "country" ("id", "name") VALUES ('zu', 'зулу');
INSERT INTO "country" ("id", "name") VALUES ('yi', 'иддиш');
INSERT INTO "country" ("id", "name") VALUES ('id', 'индонези');
INSERT INTO "country" ("id", "name") VALUES ('ia', 'интерлингво');
INSERT INTO "country" ("id", "name") VALUES ('ga', 'ирланд');
INSERT INTO "country" ("id", "name") VALUES ('is', 'исланд');
INSERT INTO "country" ("id", "name") VALUES ('es', 'испани');
INSERT INTO "country" ("id", "name") VALUES ('it', 'итали');
INSERT INTO "country" ("id", "name") VALUES ('km', 'камбуч');
INSERT INTO "country" ("id", "name") VALUES ('kn', 'каннада');
INSERT INTO "country" ("id", "name") VALUES ('ca', 'каталан');
INSERT INTO "country" ("id", "name") VALUES ('he', 'кипр');
INSERT INTO "country" ("id", "name") VALUES ('ky', 'киргиз');
INSERT INTO "country" ("id", "name") VALUES ('tlh', 'клингон хэл');
INSERT INTO "country" ("id", "name") VALUES ('ku', 'курд');
INSERT INTO "country" ("id", "name") VALUES ('lo', 'лаотиан');
INSERT INTO "country" ("id", "name") VALUES ('lv', 'латви');
INSERT INTO "country" ("id", "name") VALUES ('la', 'латин');
INSERT INTO "country" ("id", "name") VALUES ('ln', 'лингала');
INSERT INTO "country" ("id", "name") VALUES ('lt', 'литви');
INSERT INTO "country" ("id", "name") VALUES ('mk', 'македони');
INSERT INTO "country" ("id", "name") VALUES ('ms', 'малай');
INSERT INTO "country" ("id", "name") VALUES ('ml', 'малайлам');
INSERT INTO "country" ("id", "name") VALUES ('mt', 'малти');
INSERT INTO "country" ("id", "name") VALUES ('mn', 'монгол');
INSERT INTO "country" ("id", "name") VALUES ('no', 'норвеги');
INSERT INTO "country" ("id", "name") VALUES ('nn', 'норвеги (нынорск)');
INSERT INTO "country" ("id", "name") VALUES ('ie', 'нэгдмэл хэл');
INSERT INTO "country" ("id", "name") VALUES ('or', 'ория');
INSERT INTO "country" ("id", "name") VALUES ('ru', 'орос');
INSERT INTO "country" ("id", "name") VALUES ('ur', 'пакистаны урду');
INSERT INTO "country" ("id", "name") VALUES ('pa', 'пенжаби');
INSERT INTO "country" ("id", "name") VALUES ('fa', 'перс');
INSERT INTO "country" ("id", "name") VALUES ('pl', 'польш');
INSERT INTO "country" ("id", "name") VALUES ('pt', 'португали');
INSERT INTO "country" ("id", "name") VALUES ('pt_BR', 'португали (бразил)');
INSERT INTO "country" ("id", "name") VALUES ('pt_PT', 'португали (португали)');
INSERT INTO "country" ("id", "name") VALUES ('ro', 'румын');
INSERT INTO "country" ("id", "name") VALUES ('sa', 'санскирит');
INSERT INTO "country" ("id", "name") VALUES ('sr', 'серби');
INSERT INTO "country" ("id", "name") VALUES ('st', 'сесото');
INSERT INTO "country" ("id", "name") VALUES ('sd', 'синдхи');
INSERT INTO "country" ("id", "name") VALUES ('sk', 'словак');
INSERT INTO "country" ("id", "name") VALUES ('sl', 'словени');
INSERT INTO "country" ("id", "name") VALUES ('ko', 'солонгос');
INSERT INTO "country" ("id", "name") VALUES ('so', 'сомали');
INSERT INTO "country" ("id", "name") VALUES ('su', 'сунданес хэл');
INSERT INTO "country" ("id", "name") VALUES ('fil', 'тагало');
INSERT INTO "country" ("id", "name") VALUES ('th', 'тай');
INSERT INTO "country" ("id", "name") VALUES ('ta', 'тамил');
INSERT INTO "country" ("id", "name") VALUES ('tw', 'тви');
INSERT INTO "country" ("id", "name") VALUES ('ti', 'тикрина');
INSERT INTO "country" ("id", "name") VALUES ('tr', 'турк');
INSERT INTO "country" ("id", "name") VALUES ('tk', 'туркмен');
INSERT INTO "country" ("id", "name") VALUES ('te', 'тэлүгү');
INSERT INTO "country" ("id", "name") VALUES ('uz', 'узбек');
INSERT INTO "country" ("id", "name") VALUES ('ug', 'уйгур');
INSERT INTO "country" ("id", "name") VALUES ('uk', 'украин');
INSERT INTO "country" ("id", "name") VALUES ('hu', 'унгар');
INSERT INTO "country" ("id", "name") VALUES ('cy', 'уэлс');
INSERT INTO "country" ("id", "name") VALUES ('fi', 'финлянд');
INSERT INTO "country" ("id", "name") VALUES ('fr', 'франц');
INSERT INTO "country" ("id", "name") VALUES ('oc', 'францын окситан');
INSERT INTO "country" ("id", "name") VALUES ('fo', 'фөриэс хэл');
INSERT INTO "country" ("id", "name") VALUES ('hi', 'хинди');
INSERT INTO "country" ("id", "name") VALUES ('hr', 'хорвати');
INSERT INTO "country" ("id", "name") VALUES ('sh', 'хорватын серб');
INSERT INTO "country" ("id", "name") VALUES ('xh', 'хоса');
INSERT INTO "country" ("id", "name") VALUES ('zh', 'хятад');
INSERT INTO "country" ("id", "name") VALUES ('cs', 'чех');
INSERT INTO "country" ("id", "name") VALUES ('sv', 'швед');
INSERT INTO "country" ("id", "name") VALUES ('gd', 'шотланд келт');
INSERT INTO "country" ("id", "name") VALUES ('si', 'шри ланк');
INSERT INTO "country" ("id", "name") VALUES ('gu', 'энэтхэгийн гужарати');
INSERT INTO "country" ("id", "name") VALUES ('mr', 'энэтхэгийн марати');
INSERT INTO "country" ("id", "name") VALUES ('eo', 'эсперанто');
INSERT INTO "country" ("id", "name") VALUES ('et', 'эстони');
INSERT INTO "country" ("id", "name") VALUES ('jv', 'ява');
INSERT INTO "country" ("id", "name") VALUES ('ja', 'япон');
