CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('ab', 'abkhaze');
INSERT INTO [country] ([id], [name]) VALUES ('ace', 'aceh');
INSERT INTO [country] ([id], [name]) VALUES ('ach', 'acoli');
INSERT INTO [country] ([id], [name]) VALUES ('ada', 'adangme');
INSERT INTO [country] ([id], [name]) VALUES ('ady', 'adyghéen');
INSERT INTO [country] ([id], [name]) VALUES ('aa', 'afar');
INSERT INTO [country] ([id], [name]) VALUES ('afh', 'afrihili');
INSERT INTO [country] ([id], [name]) VALUES ('af', 'afrikaans');
INSERT INTO [country] ([id], [name]) VALUES ('ak', 'akan');
INSERT INTO [country] ([id], [name]) VALUES ('akk', 'akkadien');
INSERT INTO [country] ([id], [name]) VALUES ('sq', 'albanais');
INSERT INTO [country] ([id], [name]) VALUES ('de', 'allemand');
INSERT INTO [country] ([id], [name]) VALUES ('de_AT', 'allemand autrichien');
INSERT INTO [country] ([id], [name]) VALUES ('de_CH', 'allemand suisse');
INSERT INTO [country] ([id], [name]) VALUES ('alt', 'altaï du Sud');
INSERT INTO [country] ([id], [name]) VALUES ('gsw', 'alémanique');
INSERT INTO [country] ([id], [name]) VALUES ('ale', 'aléoute');
INSERT INTO [country] ([id], [name]) VALUES ('am', 'amharique');
INSERT INTO [country] ([id], [name]) VALUES ('ang', 'ancien anglais');
INSERT INTO [country] ([id], [name]) VALUES ('fro', 'ancien français');
INSERT INTO [country] ([id], [name]) VALUES ('goh', 'ancien haut allemand');
INSERT INTO [country] ([id], [name]) VALUES ('sga', 'ancien irlandais');
INSERT INTO [country] ([id], [name]) VALUES ('anp', 'angika');
INSERT INTO [country] ([id], [name]) VALUES ('en', 'anglais');
INSERT INTO [country] ([id], [name]) VALUES ('en_US', 'anglais américain');
INSERT INTO [country] ([id], [name]) VALUES ('en_AU', 'anglais australien');
INSERT INTO [country] ([id], [name]) VALUES ('en_GB', 'anglais britannique');
INSERT INTO [country] ([id], [name]) VALUES ('en_CA', 'anglais canadien');
INSERT INTO [country] ([id], [name]) VALUES ('ar', 'arabe');
INSERT INTO [country] ([id], [name]) VALUES ('an', 'aragonais');
INSERT INTO [country] ([id], [name]) VALUES ('arc', 'araméen');
INSERT INTO [country] ([id], [name]) VALUES ('sam', 'araméen samaritain');
INSERT INTO [country] ([id], [name]) VALUES ('arp', 'arapaho');
INSERT INTO [country] ([id], [name]) VALUES ('arn', 'araukan');
INSERT INTO [country] ([id], [name]) VALUES ('arw', 'arawak');
INSERT INTO [country] ([id], [name]) VALUES ('hy', 'arménien');
INSERT INTO [country] ([id], [name]) VALUES ('as', 'assamais');
INSERT INTO [country] ([id], [name]) VALUES ('ast', 'asturien');
INSERT INTO [country] ([id], [name]) VALUES ('cch', 'atsam');
INSERT INTO [country] ([id], [name]) VALUES ('av', 'avar');
INSERT INTO [country] ([id], [name]) VALUES ('ae', 'avestique');
INSERT INTO [country] ([id], [name]) VALUES ('awa', 'awadhi');
INSERT INTO [country] ([id], [name]) VALUES ('ay', 'aymara');
INSERT INTO [country] ([id], [name]) VALUES ('az', 'azéri');
INSERT INTO [country] ([id], [name]) VALUES ('ain', 'aïnou');
INSERT INTO [country] ([id], [name]) VALUES ('ba', 'bachkir');
INSERT INTO [country] ([id], [name]) VALUES ('ban', 'balinais');
INSERT INTO [country] ([id], [name]) VALUES ('bal', 'baloutchi');
INSERT INTO [country] ([id], [name]) VALUES ('bm', 'bambara');
INSERT INTO [country] ([id], [name]) VALUES ('bad', 'banda');
INSERT INTO [country] ([id], [name]) VALUES ('bnt', 'bantou');
INSERT INTO [country] ([id], [name]) VALUES ('nds', 'bas-allemand');
INSERT INTO [country] ([id], [name]) VALUES ('dsb', 'bas-sorabe');
INSERT INTO [country] ([id], [name]) VALUES ('eu', 'basque');
INSERT INTO [country] ([id], [name]) VALUES ('bas', 'bassa');
INSERT INTO [country] ([id], [name]) VALUES ('btk', 'batak');
INSERT INTO [country] ([id], [name]) VALUES ('bej', 'bedja');
INSERT INTO [country] ([id], [name]) VALUES ('bem', 'bemba');
INSERT INTO [country] ([id], [name]) VALUES ('bn', 'bengali');
INSERT INTO [country] ([id], [name]) VALUES ('ber', 'berbère');
INSERT INTO [country] ([id], [name]) VALUES ('bho', 'bhojpuri');
INSERT INTO [country] ([id], [name]) VALUES ('bi', 'bichelamar');
INSERT INTO [country] ([id], [name]) VALUES ('bh', 'bihari');
INSERT INTO [country] ([id], [name]) VALUES ('bik', 'bikol');
INSERT INTO [country] ([id], [name]) VALUES ('bin', 'bini');
INSERT INTO [country] ([id], [name]) VALUES ('my', 'birman');
INSERT INTO [country] ([id], [name]) VALUES ('be', 'biélorusse');
INSERT INTO [country] ([id], [name]) VALUES ('byn', 'blin');
INSERT INTO [country] ([id], [name]) VALUES ('bs', 'bosniaque');
INSERT INTO [country] ([id], [name]) VALUES ('bua', 'bouriate');
INSERT INTO [country] ([id], [name]) VALUES ('bra', 'braj');
INSERT INTO [country] ([id], [name]) VALUES ('br', 'breton');
INSERT INTO [country] ([id], [name]) VALUES ('bug', 'bugi');
INSERT INTO [country] ([id], [name]) VALUES ('bg', 'bulgare');
INSERT INTO [country] ([id], [name]) VALUES ('cad', 'caddo');
INSERT INTO [country] ([id], [name]) VALUES ('car', 'caribe');
INSERT INTO [country] ([id], [name]) VALUES ('krl', 'carélien');
INSERT INTO [country] ([id], [name]) VALUES ('ca', 'catalan');
INSERT INTO [country] ([id], [name]) VALUES ('ceb', 'cebuano');
INSERT INTO [country] ([id], [name]) VALUES ('ch', 'chamorro');
INSERT INTO [country] ([id], [name]) VALUES ('chr', 'cherokee');
INSERT INTO [country] ([id], [name]) VALUES ('chy', 'cheyenne');
INSERT INTO [country] ([id], [name]) VALUES ('chb', 'chibcha');
INSERT INTO [country] ([id], [name]) VALUES ('zh', 'chinois');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hans', 'chinois simplifié');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hant', 'chinois traditionnel');
INSERT INTO [country] ([id], [name]) VALUES ('chp', 'chipewyan');
INSERT INTO [country] ([id], [name]) VALUES ('cho', 'choctaw');
INSERT INTO [country] ([id], [name]) VALUES ('chk', 'chuuk');
INSERT INTO [country] ([id], [name]) VALUES ('cop', 'copte');
INSERT INTO [country] ([id], [name]) VALUES ('kw', 'cornique');
INSERT INTO [country] ([id], [name]) VALUES ('co', 'corse');
INSERT INTO [country] ([id], [name]) VALUES ('ko', 'coréen');
INSERT INTO [country] ([id], [name]) VALUES ('cr', 'cree');
INSERT INTO [country] ([id], [name]) VALUES ('mus', 'creek');
INSERT INTO [country] ([id], [name]) VALUES ('hr', 'croate');
INSERT INTO [country] ([id], [name]) VALUES ('crp', 'créole ou pidgin');
INSERT INTO [country] ([id], [name]) VALUES ('cpe', 'créole ou pidgin anglais');
INSERT INTO [country] ([id], [name]) VALUES ('cpf', 'créole ou pidgin français');
INSERT INTO [country] ([id], [name]) VALUES ('cpp', 'créole ou pidgin portugais');
INSERT INTO [country] ([id], [name]) VALUES ('dak', 'dakota');
INSERT INTO [country] ([id], [name]) VALUES ('da', 'danois');
INSERT INTO [country] ([id], [name]) VALUES ('dar', 'dargwa');
INSERT INTO [country] ([id], [name]) VALUES ('day', 'dayak');
INSERT INTO [country] ([id], [name]) VALUES ('del', 'delaware');
INSERT INTO [country] ([id], [name]) VALUES ('din', 'dinka');
INSERT INTO [country] ([id], [name]) VALUES ('dyu', 'dioula');
INSERT INTO [country] ([id], [name]) VALUES ('doi', 'dogri');
INSERT INTO [country] ([id], [name]) VALUES ('dgr', 'dogrib');
INSERT INTO [country] ([id], [name]) VALUES ('dua', 'douala');
INSERT INTO [country] ([id], [name]) VALUES ('dz', 'dzongkha');
INSERT INTO [country] ([id], [name]) VALUES ('efi', 'efik');
INSERT INTO [country] ([id], [name]) VALUES ('eka', 'ekajuk');
INSERT INTO [country] ([id], [name]) VALUES ('myv', 'erzya');
INSERT INTO [country] ([id], [name]) VALUES ('es', 'espagnol');
INSERT INTO [country] ([id], [name]) VALUES ('es_ES', 'espagnol ibérique');
INSERT INTO [country] ([id], [name]) VALUES ('es_419', 'espagnol latino-américain');
INSERT INTO [country] ([id], [name]) VALUES ('eo', 'espéranto');
INSERT INTO [country] ([id], [name]) VALUES ('et', 'estonien');
INSERT INTO [country] ([id], [name]) VALUES ('fan', 'fang');
INSERT INTO [country] ([id], [name]) VALUES ('fat', 'fanti');
INSERT INTO [country] ([id], [name]) VALUES ('fj', 'fidjien');
INSERT INTO [country] ([id], [name]) VALUES ('fil', 'filipino');
INSERT INTO [country] ([id], [name]) VALUES ('fi', 'finnois');
INSERT INTO [country] ([id], [name]) VALUES ('fon', 'fon');
INSERT INTO [country] ([id], [name]) VALUES ('fr', 'français');
INSERT INTO [country] ([id], [name]) VALUES ('fr_CA', 'français canadien');
INSERT INTO [country] ([id], [name]) VALUES ('fr_CH', 'français suisse');
INSERT INTO [country] ([id], [name]) VALUES ('fur', 'frioulan');
INSERT INTO [country] ([id], [name]) VALUES ('fy', 'frison');
INSERT INTO [country] ([id], [name]) VALUES ('frr', 'frison du Nord');
INSERT INTO [country] ([id], [name]) VALUES ('frs', 'frison oriental');
INSERT INTO [country] ([id], [name]) VALUES ('fo', 'féroïen');
INSERT INTO [country] ([id], [name]) VALUES ('gaa', 'ga');
INSERT INTO [country] ([id], [name]) VALUES ('gl', 'galicien');
INSERT INTO [country] ([id], [name]) VALUES ('cy', 'gallois');
INSERT INTO [country] ([id], [name]) VALUES ('lg', 'ganda');
INSERT INTO [country] ([id], [name]) VALUES ('gay', 'gayo');
INSERT INTO [country] ([id], [name]) VALUES ('gd', 'gaélique écossais');
INSERT INTO [country] ([id], [name]) VALUES ('gba', 'gbaya');
INSERT INTO [country] ([id], [name]) VALUES ('gil', 'gilbertais');
INSERT INTO [country] ([id], [name]) VALUES ('gon', 'gondi');
INSERT INTO [country] ([id], [name]) VALUES ('gor', 'gorontalo');
INSERT INTO [country] ([id], [name]) VALUES ('got', 'gotique');
INSERT INTO [country] ([id], [name]) VALUES ('gu', 'goudjarâtî');
INSERT INTO [country] ([id], [name]) VALUES ('grb', 'grebo');
INSERT INTO [country] ([id], [name]) VALUES ('el', 'grec');
INSERT INTO [country] ([id], [name]) VALUES ('grc', 'grec ancien');
INSERT INTO [country] ([id], [name]) VALUES ('kl', 'groenlandais');
INSERT INTO [country] ([id], [name]) VALUES ('gn', 'guarani');
INSERT INTO [country] ([id], [name]) VALUES ('gez', 'guèze');
INSERT INTO [country] ([id], [name]) VALUES ('gwi', 'gwichʼin');
INSERT INTO [country] ([id], [name]) VALUES ('ka', 'géorgien');
INSERT INTO [country] ([id], [name]) VALUES ('hai', 'haida');
INSERT INTO [country] ([id], [name]) VALUES ('ha', 'haoussa');
INSERT INTO [country] ([id], [name]) VALUES ('hsb', 'haut-sorabe');
INSERT INTO [country] ([id], [name]) VALUES ('haw', 'hawaïen');
INSERT INTO [country] ([id], [name]) VALUES ('ht', 'haïtien');
INSERT INTO [country] ([id], [name]) VALUES ('hil', 'hiligaynon');
INSERT INTO [country] ([id], [name]) VALUES ('him', 'himachali');
INSERT INTO [country] ([id], [name]) VALUES ('hi', 'hindi');
INSERT INTO [country] ([id], [name]) VALUES ('ho', 'hiri motu');
INSERT INTO [country] ([id], [name]) VALUES ('hit', 'hittite');
INSERT INTO [country] ([id], [name]) VALUES ('hmn', 'hmong');
INSERT INTO [country] ([id], [name]) VALUES ('hu', 'hongrois');
INSERT INTO [country] ([id], [name]) VALUES ('hup', 'hupa');
INSERT INTO [country] ([id], [name]) VALUES ('he', 'hébreu');
INSERT INTO [country] ([id], [name]) VALUES ('hz', 'héréro');
INSERT INTO [country] ([id], [name]) VALUES ('sah', 'iakoute');
INSERT INTO [country] ([id], [name]) VALUES ('iba', 'iban');
INSERT INTO [country] ([id], [name]) VALUES ('io', 'ido');
INSERT INTO [country] ([id], [name]) VALUES ('ig', 'igbo');
INSERT INTO [country] ([id], [name]) VALUES ('ijo', 'ijo');
INSERT INTO [country] ([id], [name]) VALUES ('ilo', 'ilokano');
INSERT INTO [country] ([id], [name]) VALUES ('id', 'indonésien');
INSERT INTO [country] ([id], [name]) VALUES ('und', 'indéterminé');
INSERT INTO [country] ([id], [name]) VALUES ('inh', 'ingouche');
INSERT INTO [country] ([id], [name]) VALUES ('ia', 'interlingua');
INSERT INTO [country] ([id], [name]) VALUES ('ie', 'interlingue');
INSERT INTO [country] ([id], [name]) VALUES ('iu', 'inuktitut');
INSERT INTO [country] ([id], [name]) VALUES ('ik', 'inupiaq');
INSERT INTO [country] ([id], [name]) VALUES ('ga', 'irlandais');
INSERT INTO [country] ([id], [name]) VALUES ('is', 'islandais');
INSERT INTO [country] ([id], [name]) VALUES ('it', 'italien');
INSERT INTO [country] ([id], [name]) VALUES ('ja', 'japonais');
INSERT INTO [country] ([id], [name]) VALUES ('chn', 'jargon chinook');
INSERT INTO [country] ([id], [name]) VALUES ('jv', 'javanais');
INSERT INTO [country] ([id], [name]) VALUES ('kaj', 'jju');
INSERT INTO [country] ([id], [name]) VALUES ('jrb', 'judéo-arabe');
INSERT INTO [country] ([id], [name]) VALUES ('jpr', 'judéo-persan');
INSERT INTO [country] ([id], [name]) VALUES ('kbd', 'kabardin');
INSERT INTO [country] ([id], [name]) VALUES ('kab', 'kabyle');
INSERT INTO [country] ([id], [name]) VALUES ('kac', 'kachin');
INSERT INTO [country] ([id], [name]) VALUES ('csb', 'kachoube');
INSERT INTO [country] ([id], [name]) VALUES ('xal', 'kalmouk');
INSERT INTO [country] ([id], [name]) VALUES ('kam', 'kamba');
INSERT INTO [country] ([id], [name]) VALUES ('kn', 'kannada');
INSERT INTO [country] ([id], [name]) VALUES ('kr', 'kanouri');
INSERT INTO [country] ([id], [name]) VALUES ('kaa', 'karakalpak');
INSERT INTO [country] ([id], [name]) VALUES ('krc', 'karatchaï balkar');
INSERT INTO [country] ([id], [name]) VALUES ('kar', 'karen');
INSERT INTO [country] ([id], [name]) VALUES ('kaw', 'kawi');
INSERT INTO [country] ([id], [name]) VALUES ('kk', 'kazakh');
INSERT INTO [country] ([id], [name]) VALUES ('kha', 'khasi');
INSERT INTO [country] ([id], [name]) VALUES ('km', 'khmer');
INSERT INTO [country] ([id], [name]) VALUES ('kho', 'khotanais');
INSERT INTO [country] ([id], [name]) VALUES ('kmb', 'kiMboundou');
INSERT INTO [country] ([id], [name]) VALUES ('ki', 'kikuyu');
INSERT INTO [country] ([id], [name]) VALUES ('ky', 'kirghize');
INSERT INTO [country] ([id], [name]) VALUES ('tlh', 'klingon');
INSERT INTO [country] ([id], [name]) VALUES ('kv', 'komi');
INSERT INTO [country] ([id], [name]) VALUES ('kg', 'kongo');
INSERT INTO [country] ([id], [name]) VALUES ('kok', 'konkani');
INSERT INTO [country] ([id], [name]) VALUES ('kfo', 'koro');
INSERT INTO [country] ([id], [name]) VALUES ('kum', 'koumyk');
INSERT INTO [country] ([id], [name]) VALUES ('kpe', 'kpellé');
INSERT INTO [country] ([id], [name]) VALUES ('kro', 'krou');
INSERT INTO [country] ([id], [name]) VALUES ('kj', 'kuanyama');
INSERT INTO [country] ([id], [name]) VALUES ('ku', 'kurde');
INSERT INTO [country] ([id], [name]) VALUES ('kru', 'kurukh');
INSERT INTO [country] ([id], [name]) VALUES ('kos', 'kusaien');
INSERT INTO [country] ([id], [name]) VALUES ('kut', 'kutenai');
INSERT INTO [country] ([id], [name]) VALUES ('ks', 'kâshmîrî');
INSERT INTO [country] ([id], [name]) VALUES ('lad', 'ladino');
INSERT INTO [country] ([id], [name]) VALUES ('lah', 'lahnda');
INSERT INTO [country] ([id], [name]) VALUES ('lam', 'lamba');
INSERT INTO [country] ([id], [name]) VALUES ('afa', 'langue afro-asiatique');
INSERT INTO [country] ([id], [name]) VALUES ('alg', 'langue algonquienne');
INSERT INTO [country] ([id], [name]) VALUES ('tut', 'langue altaïque');
INSERT INTO [country] ([id], [name]) VALUES ('cai', 'langue amérindienne centrale');
INSERT INTO [country] ([id], [name]) VALUES ('nai', 'langue amérindienne du Nord');
INSERT INTO [country] ([id], [name]) VALUES ('sai', 'langue amérindienne du Sud');
INSERT INTO [country] ([id], [name]) VALUES ('apa', 'langue apache');
INSERT INTO [country] ([id], [name]) VALUES ('art', 'langue artificielle');
INSERT INTO [country] ([id], [name]) VALUES ('ath', 'langue athapascane');
INSERT INTO [country] ([id], [name]) VALUES ('aus', 'langue australienne');
INSERT INTO [country] ([id], [name]) VALUES ('bat', 'langue balte');
INSERT INTO [country] ([id], [name]) VALUES ('bai', 'langue bamilékée');
INSERT INTO [country] ([id], [name]) VALUES ('cau', 'langue caucasienne');
INSERT INTO [country] ([id], [name]) VALUES ('cel', 'langue celtique');
INSERT INTO [country] ([id], [name]) VALUES ('cmc', 'langue chame');
INSERT INTO [country] ([id], [name]) VALUES ('cus', 'langue couchitique');
INSERT INTO [country] ([id], [name]) VALUES ('sgn', 'langue des signes');
INSERT INTO [country] ([id], [name]) VALUES ('mis', 'langue diverse');
INSERT INTO [country] ([id], [name]) VALUES ('dra', 'langue dravidienne');
INSERT INTO [country] ([id], [name]) VALUES ('fiu', 'langue finno-ougrienne');
INSERT INTO [country] ([id], [name]) VALUES ('gem', 'langue germanique');
INSERT INTO [country] ([id], [name]) VALUES ('inc', 'langue indo-aryenne');
INSERT INTO [country] ([id], [name]) VALUES ('ine', 'langue indo-européenne');
INSERT INTO [country] ([id], [name]) VALUES ('ira', 'langue iranienne');
INSERT INTO [country] ([id], [name]) VALUES ('iro', 'langue iroquoienne');
INSERT INTO [country] ([id], [name]) VALUES ('khi', 'langue khoïsan');
INSERT INTO [country] ([id], [name]) VALUES ('mno', 'langue manobo');
INSERT INTO [country] ([id], [name]) VALUES ('myn', 'langue maya');
INSERT INTO [country] ([id], [name]) VALUES ('mkh', 'langue mon-khmère');
INSERT INTO [country] ([id], [name]) VALUES ('mun', 'langue mounda');
INSERT INTO [country] ([id], [name]) VALUES ('nic', 'langue nigéro-congolaise');
INSERT INTO [country] ([id], [name]) VALUES ('ssa', 'langue nilo-saharienne');
INSERT INTO [country] ([id], [name]) VALUES ('nub', 'langue nubienne');
INSERT INTO [country] ([id], [name]) VALUES ('oto', 'langue otomangue');
INSERT INTO [country] ([id], [name]) VALUES ('paa', 'langue papoue');
INSERT INTO [country] ([id], [name]) VALUES ('phi', 'langue philippine');
INSERT INTO [country] ([id], [name]) VALUES ('qu', 'langue quechua');
INSERT INTO [country] ([id], [name]) VALUES ('roa', 'langue romane');
INSERT INTO [country] ([id], [name]) VALUES ('sal', 'langue salishenne');
INSERT INTO [country] ([id], [name]) VALUES ('smi', 'langue samie');
INSERT INTO [country] ([id], [name]) VALUES ('sit', 'langue sino-tibétaine');
INSERT INTO [country] ([id], [name]) VALUES ('sio', 'langue sioux');
INSERT INTO [country] ([id], [name]) VALUES ('sla', 'langue slave');
INSERT INTO [country] ([id], [name]) VALUES ('wen', 'langue sorabe');
INSERT INTO [country] ([id], [name]) VALUES ('sem', 'langue sémitique');
INSERT INTO [country] ([id], [name]) VALUES ('tai', 'langue taï');
INSERT INTO [country] ([id], [name]) VALUES ('tup', 'langue tupi');
INSERT INTO [country] ([id], [name]) VALUES ('pra', 'langues prâkrit');
INSERT INTO [country] ([id], [name]) VALUES ('wak', 'langues wakashennes');
INSERT INTO [country] ([id], [name]) VALUES ('ypk', 'langues yupik');
INSERT INTO [country] ([id], [name]) VALUES ('lo', 'lao');
INSERT INTO [country] ([id], [name]) VALUES ('la', 'latin');
INSERT INTO [country] ([id], [name]) VALUES ('lv', 'letton');
INSERT INTO [country] ([id], [name]) VALUES ('lez', 'lezghien');
INSERT INTO [country] ([id], [name]) VALUES ('li', 'limbourgeois');
INSERT INTO [country] ([id], [name]) VALUES ('ln', 'lingala');
INSERT INTO [country] ([id], [name]) VALUES ('lt', 'lituanien');
INSERT INTO [country] ([id], [name]) VALUES ('jbo', 'lojban');
INSERT INTO [country] ([id], [name]) VALUES ('loz', 'lozi');
INSERT INTO [country] ([id], [name]) VALUES ('lu', 'luba-katanga');
INSERT INTO [country] ([id], [name]) VALUES ('lua', 'luba-lulua');
INSERT INTO [country] ([id], [name]) VALUES ('lui', 'luiseno');
INSERT INTO [country] ([id], [name]) VALUES ('lun', 'lunda');
INSERT INTO [country] ([id], [name]) VALUES ('luo', 'luo');
INSERT INTO [country] ([id], [name]) VALUES ('lus', 'lushai');
INSERT INTO [country] ([id], [name]) VALUES ('lb', 'luxembourgeois');
INSERT INTO [country] ([id], [name]) VALUES ('mk', 'macédonien');
INSERT INTO [country] ([id], [name]) VALUES ('mad', 'madurais');
INSERT INTO [country] ([id], [name]) VALUES ('mag', 'magahi');
INSERT INTO [country] ([id], [name]) VALUES ('mai', 'maithili');
INSERT INTO [country] ([id], [name]) VALUES ('mak', 'makassar');
INSERT INTO [country] ([id], [name]) VALUES ('ms', 'malais');
INSERT INTO [country] ([id], [name]) VALUES ('ml', 'malayalam');
INSERT INTO [country] ([id], [name]) VALUES ('map', 'malayo-polynésien');
INSERT INTO [country] ([id], [name]) VALUES ('dv', 'maldivien');
INSERT INTO [country] ([id], [name]) VALUES ('mg', 'malgache');
INSERT INTO [country] ([id], [name]) VALUES ('mt', 'maltais');
INSERT INTO [country] ([id], [name]) VALUES ('mdr', 'mandar');
INSERT INTO [country] ([id], [name]) VALUES ('mnc', 'mandchou');
INSERT INTO [country] ([id], [name]) VALUES ('man', 'mandingue');
INSERT INTO [country] ([id], [name]) VALUES ('mni', 'manipuri');
INSERT INTO [country] ([id], [name]) VALUES ('gv', 'manx');
INSERT INTO [country] ([id], [name]) VALUES ('mi', 'maori');
INSERT INTO [country] ([id], [name]) VALUES ('mr', 'marathe');
INSERT INTO [country] ([id], [name]) VALUES ('chm', 'mari');
INSERT INTO [country] ([id], [name]) VALUES ('mh', 'marshall');
INSERT INTO [country] ([id], [name]) VALUES ('mwr', 'marwarî');
INSERT INTO [country] ([id], [name]) VALUES ('mas', 'masai');
INSERT INTO [country] ([id], [name]) VALUES ('men', 'mendé');
INSERT INTO [country] ([id], [name]) VALUES ('mic', 'micmac');
INSERT INTO [country] ([id], [name]) VALUES ('min', 'minangkabau');
INSERT INTO [country] ([id], [name]) VALUES ('mwl', 'mirandais');
INSERT INTO [country] ([id], [name]) VALUES ('moh', 'mohawk');
INSERT INTO [country] ([id], [name]) VALUES ('mdf', 'moksa');
INSERT INTO [country] ([id], [name]) VALUES ('mo', 'moldave');
INSERT INTO [country] ([id], [name]) VALUES ('lol', 'mongo');
INSERT INTO [country] ([id], [name]) VALUES ('mn', 'mongol');
INSERT INTO [country] ([id], [name]) VALUES ('mos', 'moré');
INSERT INTO [country] ([id], [name]) VALUES ('enm', 'moyen anglais');
INSERT INTO [country] ([id], [name]) VALUES ('frm', 'moyen français');
INSERT INTO [country] ([id], [name]) VALUES ('gmh', 'moyen haut-allemand');
INSERT INTO [country] ([id], [name]) VALUES ('mga', 'moyen irlandais');
INSERT INTO [country] ([id], [name]) VALUES ('dum', 'moyen néerlandais');
INSERT INTO [country] ([id], [name]) VALUES ('mul', 'multilingue');
INSERT INTO [country] ([id], [name]) VALUES ('nah', 'nahuatl');
INSERT INTO [country] ([id], [name]) VALUES ('nap', 'napolitain');
INSERT INTO [country] ([id], [name]) VALUES ('na', 'nauruan');
INSERT INTO [country] ([id], [name]) VALUES ('nv', 'navaho');
INSERT INTO [country] ([id], [name]) VALUES ('ng', 'ndonga');
INSERT INTO [country] ([id], [name]) VALUES ('nd', 'ndébélé du Nord');
INSERT INTO [country] ([id], [name]) VALUES ('nr', 'ndébélé du Sud');
INSERT INTO [country] ([id], [name]) VALUES ('new', 'newari');
INSERT INTO [country] ([id], [name]) VALUES ('nwc', 'newarî classique');
INSERT INTO [country] ([id], [name]) VALUES ('nia', 'nias');
INSERT INTO [country] ([id], [name]) VALUES ('niu', 'niué');
INSERT INTO [country] ([id], [name]) VALUES ('nog', 'nogaï');
INSERT INTO [country] ([id], [name]) VALUES ('no', 'norvégien');
INSERT INTO [country] ([id], [name]) VALUES ('nb', 'norvégien bokmål');
INSERT INTO [country] ([id], [name]) VALUES ('nn', 'norvégien nynorsk');
INSERT INTO [country] ([id], [name]) VALUES ('nym', 'nyamwezi');
INSERT INTO [country] ([id], [name]) VALUES ('ny', 'nyanja');
INSERT INTO [country] ([id], [name]) VALUES ('nyn', 'nyankolé');
INSERT INTO [country] ([id], [name]) VALUES ('nyo', 'nyoro');
INSERT INTO [country] ([id], [name]) VALUES ('nzi', 'nzema');
INSERT INTO [country] ([id], [name]) VALUES ('nl', 'néerlandais');
INSERT INTO [country] ([id], [name]) VALUES ('nl_BE', 'néerlandais belge');
INSERT INTO [country] ([id], [name]) VALUES ('ne', 'népalais');
INSERT INTO [country] ([id], [name]) VALUES ('nqo', 'n’ko');
INSERT INTO [country] ([id], [name]) VALUES ('oc', 'occitan');
INSERT INTO [country] ([id], [name]) VALUES ('oj', 'ojibwa');
INSERT INTO [country] ([id], [name]) VALUES ('or', 'oriya');
INSERT INTO [country] ([id], [name]) VALUES ('om', 'oromo');
INSERT INTO [country] ([id], [name]) VALUES ('osa', 'osage');
INSERT INTO [country] ([id], [name]) VALUES ('os', 'ossète');
INSERT INTO [country] ([id], [name]) VALUES ('udm', 'oudmourte');
INSERT INTO [country] ([id], [name]) VALUES ('uga', 'ougaritique');
INSERT INTO [country] ([id], [name]) VALUES ('ur', 'ourdou');
INSERT INTO [country] ([id], [name]) VALUES ('uz', 'ouzbek');
INSERT INTO [country] ([id], [name]) VALUES ('ug', 'ouïgour');
INSERT INTO [country] ([id], [name]) VALUES ('ps', 'pachto');
INSERT INTO [country] ([id], [name]) VALUES ('pal', 'pahlavi');
INSERT INTO [country] ([id], [name]) VALUES ('pau', 'palau');
INSERT INTO [country] ([id], [name]) VALUES ('pi', 'pali');
INSERT INTO [country] ([id], [name]) VALUES ('pam', 'pampangan');
INSERT INTO [country] ([id], [name]) VALUES ('pag', 'pangasinan');
INSERT INTO [country] ([id], [name]) VALUES ('pap', 'papiamento');
INSERT INTO [country] ([id], [name]) VALUES ('pa', 'pendjabi');
INSERT INTO [country] ([id], [name]) VALUES ('fa', 'persan');
INSERT INTO [country] ([id], [name]) VALUES ('peo', 'persan ancien');
INSERT INTO [country] ([id], [name]) VALUES ('ff', 'peul');
INSERT INTO [country] ([id], [name]) VALUES ('phn', 'phénicien');
INSERT INTO [country] ([id], [name]) VALUES ('pon', 'pohnpei');
INSERT INTO [country] ([id], [name]) VALUES ('pl', 'polonais');
INSERT INTO [country] ([id], [name]) VALUES ('pt', 'portugais');
INSERT INTO [country] ([id], [name]) VALUES ('pt_BR', 'portugais brésilien');
INSERT INTO [country] ([id], [name]) VALUES ('pt_PT', 'portugais ibérique');
INSERT INTO [country] ([id], [name]) VALUES ('pro', 'provençal ancien');
INSERT INTO [country] ([id], [name]) VALUES ('root', 'racine');
INSERT INTO [country] ([id], [name]) VALUES ('raj', 'rajasthani');
INSERT INTO [country] ([id], [name]) VALUES ('rap', 'rapanui');
INSERT INTO [country] ([id], [name]) VALUES ('rar', 'rarotongien');
INSERT INTO [country] ([id], [name]) VALUES ('rm', 'rhéto-roman');
INSERT INTO [country] ([id], [name]) VALUES ('ro', 'roumain');
INSERT INTO [country] ([id], [name]) VALUES ('rn', 'roundi');
INSERT INTO [country] ([id], [name]) VALUES ('ru', 'russe');
INSERT INTO [country] ([id], [name]) VALUES ('rw', 'rwanda');
INSERT INTO [country] ([id], [name]) VALUES ('smj', 'sami de Lule');
INSERT INTO [country] ([id], [name]) VALUES ('se', 'sami du Nord');
INSERT INTO [country] ([id], [name]) VALUES ('sma', 'sami du Sud');
INSERT INTO [country] ([id], [name]) VALUES ('smn', 'sami d’Inari');
INSERT INTO [country] ([id], [name]) VALUES ('sms', 'sami skolt');
INSERT INTO [country] ([id], [name]) VALUES ('sm', 'samoan');
INSERT INTO [country] ([id], [name]) VALUES ('sad', 'sandawe');
INSERT INTO [country] ([id], [name]) VALUES ('sg', 'sangho');
INSERT INTO [country] ([id], [name]) VALUES ('zxx', 'sans contenu linguistique');
INSERT INTO [country] ([id], [name]) VALUES ('sa', 'sanskrit');
INSERT INTO [country] ([id], [name]) VALUES ('sat', 'santal');
INSERT INTO [country] ([id], [name]) VALUES ('sc', 'sarde');
INSERT INTO [country] ([id], [name]) VALUES ('sas', 'sasak');
INSERT INTO [country] ([id], [name]) VALUES ('sel', 'selkoupe');
INSERT INTO [country] ([id], [name]) VALUES ('sr', 'serbe');
INSERT INTO [country] ([id], [name]) VALUES ('sh', 'serbo-croate');
INSERT INTO [country] ([id], [name]) VALUES ('st', 'sesotho');
INSERT INTO [country] ([id], [name]) VALUES ('shn', 'shan');
INSERT INTO [country] ([id], [name]) VALUES ('sn', 'shona');
INSERT INTO [country] ([id], [name]) VALUES ('scn', 'sicilien');
INSERT INTO [country] ([id], [name]) VALUES ('sid', 'sidamo');
INSERT INTO [country] ([id], [name]) VALUES ('bla', 'siksika');
INSERT INTO [country] ([id], [name]) VALUES ('sd', 'sindhî');
INSERT INTO [country] ([id], [name]) VALUES ('si', 'singhalais');
INSERT INTO [country] ([id], [name]) VALUES ('den', 'slavey');
INSERT INTO [country] ([id], [name]) VALUES ('cu', 'slavon d’église');
INSERT INTO [country] ([id], [name]) VALUES ('sk', 'slovaque');
INSERT INTO [country] ([id], [name]) VALUES ('sl', 'slovène');
INSERT INTO [country] ([id], [name]) VALUES ('sog', 'sogdien');
INSERT INTO [country] ([id], [name]) VALUES ('so', 'somali');
INSERT INTO [country] ([id], [name]) VALUES ('son', 'songhai');
INSERT INTO [country] ([id], [name]) VALUES ('snk', 'soninké');
INSERT INTO [country] ([id], [name]) VALUES ('nso', 'sotho du Nord');
INSERT INTO [country] ([id], [name]) VALUES ('su', 'soundanais');
INSERT INTO [country] ([id], [name]) VALUES ('sus', 'soussou');
INSERT INTO [country] ([id], [name]) VALUES ('srn', 'sranan tongo');
INSERT INTO [country] ([id], [name]) VALUES ('suk', 'sukuma');
INSERT INTO [country] ([id], [name]) VALUES ('sux', 'sumérien');
INSERT INTO [country] ([id], [name]) VALUES ('sv', 'suédois');
INSERT INTO [country] ([id], [name]) VALUES ('sw', 'swahili');
INSERT INTO [country] ([id], [name]) VALUES ('ss', 'swati');
INSERT INTO [country] ([id], [name]) VALUES ('zbl', 'symboles Bliss');
INSERT INTO [country] ([id], [name]) VALUES ('syr', 'syriaque');
INSERT INTO [country] ([id], [name]) VALUES ('syc', 'syriaque classique');
INSERT INTO [country] ([id], [name]) VALUES ('srr', 'sérère');
INSERT INTO [country] ([id], [name]) VALUES ('tg', 'tadjik');
INSERT INTO [country] ([id], [name]) VALUES ('tl', 'tagalog');
INSERT INTO [country] ([id], [name]) VALUES ('ty', 'tahitien');
INSERT INTO [country] ([id], [name]) VALUES ('tmh', 'tamacheq');
INSERT INTO [country] ([id], [name]) VALUES ('ta', 'tamoul');
INSERT INTO [country] ([id], [name]) VALUES ('tt', 'tatar');
INSERT INTO [country] ([id], [name]) VALUES ('chg', 'tchaghataï');
INSERT INTO [country] ([id], [name]) VALUES ('cv', 'tchouvache');
INSERT INTO [country] ([id], [name]) VALUES ('cs', 'tchèque');
INSERT INTO [country] ([id], [name]) VALUES ('ce', 'tchétchène');
INSERT INTO [country] ([id], [name]) VALUES ('tem', 'temne');
INSERT INTO [country] ([id], [name]) VALUES ('ter', 'tereno');
INSERT INTO [country] ([id], [name]) VALUES ('tet', 'tetum');
INSERT INTO [country] ([id], [name]) VALUES ('th', 'thaï');
INSERT INTO [country] ([id], [name]) VALUES ('bo', 'tibétain');
INSERT INTO [country] ([id], [name]) VALUES ('ti', 'tigrigna');
INSERT INTO [country] ([id], [name]) VALUES ('tig', 'tigré');
INSERT INTO [country] ([id], [name]) VALUES ('tiv', 'tiv');
INSERT INTO [country] ([id], [name]) VALUES ('tli', 'tlingit');
INSERT INTO [country] ([id], [name]) VALUES ('tpi', 'tok pisin');
INSERT INTO [country] ([id], [name]) VALUES ('tkl', 'tokelau');
INSERT INTO [country] ([id], [name]) VALUES ('tog', 'tonga nyasa');
INSERT INTO [country] ([id], [name]) VALUES ('to', 'tongan');
INSERT INTO [country] ([id], [name]) VALUES ('tyv', 'touva');
INSERT INTO [country] ([id], [name]) VALUES ('tsi', 'tsimshian');
INSERT INTO [country] ([id], [name]) VALUES ('ts', 'tsonga');
INSERT INTO [country] ([id], [name]) VALUES ('tn', 'tswana');
INSERT INTO [country] ([id], [name]) VALUES ('tum', 'tumbuka');
INSERT INTO [country] ([id], [name]) VALUES ('tr', 'turc');
INSERT INTO [country] ([id], [name]) VALUES ('crh', 'turc de Crimée');
INSERT INTO [country] ([id], [name]) VALUES ('ota', 'turc ottoman');
INSERT INTO [country] ([id], [name]) VALUES ('tk', 'turkmène');
INSERT INTO [country] ([id], [name]) VALUES ('tvl', 'tuvalu');
INSERT INTO [country] ([id], [name]) VALUES ('tw', 'twi');
INSERT INTO [country] ([id], [name]) VALUES ('kcg', 'tyap');
INSERT INTO [country] ([id], [name]) VALUES ('rom', 'tzigane');
INSERT INTO [country] ([id], [name]) VALUES ('te', 'télougou');
INSERT INTO [country] ([id], [name]) VALUES ('uk', 'ukrainien');
INSERT INTO [country] ([id], [name]) VALUES ('umb', 'umbundu');
INSERT INTO [country] ([id], [name]) VALUES ('rup', 'valaque');
INSERT INTO [country] ([id], [name]) VALUES ('vai', 'vaï');
INSERT INTO [country] ([id], [name]) VALUES ('ve', 'venda');
INSERT INTO [country] ([id], [name]) VALUES ('vi', 'vietnamien');
INSERT INTO [country] ([id], [name]) VALUES ('non', 'vieux norrois');
INSERT INTO [country] ([id], [name]) VALUES ('vo', 'volapuk');
INSERT INTO [country] ([id], [name]) VALUES ('vot', 'vote');
INSERT INTO [country] ([id], [name]) VALUES ('wal', 'walamo');
INSERT INTO [country] ([id], [name]) VALUES ('wa', 'wallon');
INSERT INTO [country] ([id], [name]) VALUES ('war', 'waray');
INSERT INTO [country] ([id], [name]) VALUES ('was', 'washo');
INSERT INTO [country] ([id], [name]) VALUES ('wo', 'wolof');
INSERT INTO [country] ([id], [name]) VALUES ('xh', 'xhosa');
INSERT INTO [country] ([id], [name]) VALUES ('yao', 'yao');
INSERT INTO [country] ([id], [name]) VALUES ('yap', 'yapois');
INSERT INTO [country] ([id], [name]) VALUES ('ii', 'yi de Sichuan');
INSERT INTO [country] ([id], [name]) VALUES ('yi', 'yiddish');
INSERT INTO [country] ([id], [name]) VALUES ('yo', 'yoruba');
INSERT INTO [country] ([id], [name]) VALUES ('znd', 'zandé');
INSERT INTO [country] ([id], [name]) VALUES ('zap', 'zapotèque');
INSERT INTO [country] ([id], [name]) VALUES ('zza', 'zazaki');
INSERT INTO [country] ([id], [name]) VALUES ('zen', 'zenaga');
INSERT INTO [country] ([id], [name]) VALUES ('za', 'zhuang');
INSERT INTO [country] ([id], [name]) VALUES ('zu', 'zoulou');
INSERT INTO [country] ([id], [name]) VALUES ('zun', 'zuni');
INSERT INTO [country] ([id], [name]) VALUES ('sco', 'écossais');
INSERT INTO [country] ([id], [name]) VALUES ('egy', 'égyptien ancien');
INSERT INTO [country] ([id], [name]) VALUES ('elx', 'élamite');
INSERT INTO [country] ([id], [name]) VALUES ('ewo', 'éwondo');
INSERT INTO [country] ([id], [name]) VALUES ('ee', 'éwé');
