CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('ab', 'Abchazisch');
INSERT INTO `country` (`id`, `name`) VALUES ('ada', 'Adangme');
INSERT INTO `country` (`id`, `name`) VALUES ('ady', 'Adyghe');
INSERT INTO `country` (`id`, `name`) VALUES ('aa', 'Afar');
INSERT INTO `country` (`id`, `name`) VALUES ('afh', 'Afrihili');
INSERT INTO `country` (`id`, `name`) VALUES ('af', 'Afrikaans');
INSERT INTO `country` (`id`, `name`) VALUES ('afa', 'Afro-Aziatische taal');
INSERT INTO `country` (`id`, `name`) VALUES ('ain', 'Ainu');
INSERT INTO `country` (`id`, `name`) VALUES ('ak', 'Akan');
INSERT INTO `country` (`id`, `name`) VALUES ('akk', 'Akkadisch');
INSERT INTO `country` (`id`, `name`) VALUES ('ach', 'Akoli');
INSERT INTO `country` (`id`, `name`) VALUES ('sq', 'Albanees');
INSERT INTO `country` (`id`, `name`) VALUES ('ale', 'Aleut');
INSERT INTO `country` (`id`, `name`) VALUES ('alg', 'Algonkium-taal');
INSERT INTO `country` (`id`, `name`) VALUES ('tut', 'Altaïsche taal');
INSERT INTO `country` (`id`, `name`) VALUES ('en_US', 'Amerikaans Engels');
INSERT INTO `country` (`id`, `name`) VALUES ('am', 'Amhaars');
INSERT INTO `country` (`id`, `name`) VALUES ('anp', 'Angika');
INSERT INTO `country` (`id`, `name`) VALUES ('apa', 'Apache-taal');
INSERT INTO `country` (`id`, `name`) VALUES ('ar', 'Arabisch');
INSERT INTO `country` (`id`, `name`) VALUES ('an', 'Aragonees');
INSERT INTO `country` (`id`, `name`) VALUES ('arc', 'Aramees');
INSERT INTO `country` (`id`, `name`) VALUES ('arp', 'Arapaho');
INSERT INTO `country` (`id`, `name`) VALUES ('arn', 'Araukaans');
INSERT INTO `country` (`id`, `name`) VALUES ('arw', 'Arawak');
INSERT INTO `country` (`id`, `name`) VALUES ('hy', 'Armeens');
INSERT INTO `country` (`id`, `name`) VALUES ('rup', 'Aromaniaans');
INSERT INTO `country` (`id`, `name`) VALUES ('as', 'Assamees');
INSERT INTO `country` (`id`, `name`) VALUES ('ast', 'Asturisch');
INSERT INTO `country` (`id`, `name`) VALUES ('ath', 'Athapascaanse taal');
INSERT INTO `country` (`id`, `name`) VALUES ('ace', 'Atjees');
INSERT INTO `country` (`id`, `name`) VALUES ('cch', 'Atsam');
INSERT INTO `country` (`id`, `name`) VALUES ('en_AU', 'Australisch Engels');
INSERT INTO `country` (`id`, `name`) VALUES ('aus', 'Australische taal');
INSERT INTO `country` (`id`, `name`) VALUES ('map', 'Austronesisch');
INSERT INTO `country` (`id`, `name`) VALUES ('av', 'Avarisch');
INSERT INTO `country` (`id`, `name`) VALUES ('ae', 'Avestisch');
INSERT INTO `country` (`id`, `name`) VALUES ('awa', 'Awadhi');
INSERT INTO `country` (`id`, `name`) VALUES ('ay', 'Aymara');
INSERT INTO `country` (`id`, `name`) VALUES ('az', 'Azerbeidzjaans');
INSERT INTO `country` (`id`, `name`) VALUES ('ban', 'Balinees');
INSERT INTO `country` (`id`, `name`) VALUES ('bal', 'Baloetsji');
INSERT INTO `country` (`id`, `name`) VALUES ('bat', 'Baltische taal');
INSERT INTO `country` (`id`, `name`) VALUES ('bm', 'Bambara');
INSERT INTO `country` (`id`, `name`) VALUES ('bai', 'Bamileke-taal');
INSERT INTO `country` (`id`, `name`) VALUES ('bad', 'Banda');
INSERT INTO `country` (`id`, `name`) VALUES ('bnt', 'Bantoe');
INSERT INTO `country` (`id`, `name`) VALUES ('bas', 'Basa');
INSERT INTO `country` (`id`, `name`) VALUES ('ba', 'Basjkiers');
INSERT INTO `country` (`id`, `name`) VALUES ('eu', 'Baskisch');
INSERT INTO `country` (`id`, `name`) VALUES ('btk', 'Batak');
INSERT INTO `country` (`id`, `name`) VALUES ('bej', 'Beja');
INSERT INTO `country` (`id`, `name`) VALUES ('bem', 'Bemba');
INSERT INTO `country` (`id`, `name`) VALUES ('bn', 'Bengalees');
INSERT INTO `country` (`id`, `name`) VALUES ('ber', 'Berber');
INSERT INTO `country` (`id`, `name`) VALUES ('bho', 'Bhojpuri');
INSERT INTO `country` (`id`, `name`) VALUES ('bh', 'Bihari');
INSERT INTO `country` (`id`, `name`) VALUES ('bik', 'Bikol');
INSERT INTO `country` (`id`, `name`) VALUES ('bin', 'Bini');
INSERT INTO `country` (`id`, `name`) VALUES ('my', 'Birmees');
INSERT INTO `country` (`id`, `name`) VALUES ('bi', 'Bislama');
INSERT INTO `country` (`id`, `name`) VALUES ('byn', 'Blin');
INSERT INTO `country` (`id`, `name`) VALUES ('zbl', 'Blissymbolen');
INSERT INTO `country` (`id`, `name`) VALUES ('bs', 'Bosnisch');
INSERT INTO `country` (`id`, `name`) VALUES ('bra', 'Braj');
INSERT INTO `country` (`id`, `name`) VALUES ('pt_BR', 'Braziliaans Portugees');
INSERT INTO `country` (`id`, `name`) VALUES ('br', 'Bretons');
INSERT INTO `country` (`id`, `name`) VALUES ('en_GB', 'Brits Engels');
INSERT INTO `country` (`id`, `name`) VALUES ('bug', 'Buginees');
INSERT INTO `country` (`id`, `name`) VALUES ('bg', 'Bulgaars');
INSERT INTO `country` (`id`, `name`) VALUES ('bua', 'Buriat');
INSERT INTO `country` (`id`, `name`) VALUES ('cad', 'Caddo');
INSERT INTO `country` (`id`, `name`) VALUES ('en_CA', 'Canadees Engels');
INSERT INTO `country` (`id`, `name`) VALUES ('fr_CA', 'Canadees Frans');
INSERT INTO `country` (`id`, `name`) VALUES ('car', 'Caribisch');
INSERT INTO `country` (`id`, `name`) VALUES ('ca', 'Catalaans');
INSERT INTO `country` (`id`, `name`) VALUES ('ceb', 'Cebuano');
INSERT INTO `country` (`id`, `name`) VALUES ('chg', 'Chagatai');
INSERT INTO `country` (`id`, `name`) VALUES ('cmc', 'Chamische taal');
INSERT INTO `country` (`id`, `name`) VALUES ('ch', 'Chamorro');
INSERT INTO `country` (`id`, `name`) VALUES ('chr', 'Cherokee');
INSERT INTO `country` (`id`, `name`) VALUES ('chy', 'Cheyenne');
INSERT INTO `country` (`id`, `name`) VALUES ('chb', 'Chibcha');
INSERT INTO `country` (`id`, `name`) VALUES ('zh', 'Chinees');
INSERT INTO `country` (`id`, `name`) VALUES ('chn', 'Chinook-jargon');
INSERT INTO `country` (`id`, `name`) VALUES ('chp', 'Chipewyan');
INSERT INTO `country` (`id`, `name`) VALUES ('cho', 'Choctaw');
INSERT INTO `country` (`id`, `name`) VALUES ('chk', 'Chuukees');
INSERT INTO `country` (`id`, `name`) VALUES ('kw', 'Cornish');
INSERT INTO `country` (`id`, `name`) VALUES ('co', 'Corsicaans');
INSERT INTO `country` (`id`, `name`) VALUES ('cr', 'Cree');
INSERT INTO `country` (`id`, `name`) VALUES ('mus', 'Creek');
INSERT INTO `country` (`id`, `name`) VALUES ('crp', 'Creools of Pidgin');
INSERT INTO `country` (`id`, `name`) VALUES ('day', 'Dajak');
INSERT INTO `country` (`id`, `name`) VALUES ('dak', 'Dakota');
INSERT INTO `country` (`id`, `name`) VALUES ('dar', 'Dargwa');
INSERT INTO `country` (`id`, `name`) VALUES ('da', 'Deens');
INSERT INTO `country` (`id`, `name`) VALUES ('del', 'Delaware');
INSERT INTO `country` (`id`, `name`) VALUES ('din', 'Dinka');
INSERT INTO `country` (`id`, `name`) VALUES ('dv', 'Divehi');
INSERT INTO `country` (`id`, `name`) VALUES ('mis', 'Diverse talen');
INSERT INTO `country` (`id`, `name`) VALUES ('doi', 'Dogri');
INSERT INTO `country` (`id`, `name`) VALUES ('dgr', 'Dogrib');
INSERT INTO `country` (`id`, `name`) VALUES ('dra', 'Dravidische taal');
INSERT INTO `country` (`id`, `name`) VALUES ('dua', 'Duala');
INSERT INTO `country` (`id`, `name`) VALUES ('de', 'Duits');
INSERT INTO `country` (`id`, `name`) VALUES ('dyu', 'Dyula');
INSERT INTO `country` (`id`, `name`) VALUES ('dz', 'Dzongkha');
INSERT INTO `country` (`id`, `name`) VALUES ('efi', 'Efik');
INSERT INTO `country` (`id`, `name`) VALUES ('eka', 'Ekajuk');
INSERT INTO `country` (`id`, `name`) VALUES ('elx', 'Elamitisch');
INSERT INTO `country` (`id`, `name`) VALUES ('en', 'Engels');
INSERT INTO `country` (`id`, `name`) VALUES ('myv', 'Erzja');
INSERT INTO `country` (`id`, `name`) VALUES ('eo', 'Esperanto');
INSERT INTO `country` (`id`, `name`) VALUES ('et', 'Estlands');
INSERT INTO `country` (`id`, `name`) VALUES ('ee', 'Ewe');
INSERT INTO `country` (`id`, `name`) VALUES ('ewo', 'Ewondo');
INSERT INTO `country` (`id`, `name`) VALUES ('fo', 'Faeröers');
INSERT INTO `country` (`id`, `name`) VALUES ('fan', 'Fang');
INSERT INTO `country` (`id`, `name`) VALUES ('fat', 'Fanti');
INSERT INTO `country` (`id`, `name`) VALUES ('fj', 'Fijisch');
INSERT INTO `country` (`id`, `name`) VALUES ('fil', 'Filippijns');
INSERT INTO `country` (`id`, `name`) VALUES ('phi', 'Filippijnse taal');
INSERT INTO `country` (`id`, `name`) VALUES ('fi', 'Fins');
INSERT INTO `country` (`id`, `name`) VALUES ('fiu', 'Fins-Oegrische taal');
INSERT INTO `country` (`id`, `name`) VALUES ('phn', 'Foenicisch');
INSERT INTO `country` (`id`, `name`) VALUES ('fon', 'Fon');
INSERT INTO `country` (`id`, `name`) VALUES ('fr', 'Frans');
INSERT INTO `country` (`id`, `name`) VALUES ('fur', 'Friulisch');
INSERT INTO `country` (`id`, `name`) VALUES ('ff', 'Fulah');
INSERT INTO `country` (`id`, `name`) VALUES ('gaa', 'Ga');
INSERT INTO `country` (`id`, `name`) VALUES ('gl', 'Galicisch');
INSERT INTO `country` (`id`, `name`) VALUES ('lg', 'Ganda');
INSERT INTO `country` (`id`, `name`) VALUES ('gay', 'Gayo');
INSERT INTO `country` (`id`, `name`) VALUES ('gba', 'Gbaya');
INSERT INTO `country` (`id`, `name`) VALUES ('sgn', 'Gebarentaal');
INSERT INTO `country` (`id`, `name`) VALUES ('zxx', 'Geen linguïstische inhoud');
INSERT INTO `country` (`id`, `name`) VALUES ('gez', 'Geez');
INSERT INTO `country` (`id`, `name`) VALUES ('ka', 'Georgisch');
INSERT INTO `country` (`id`, `name`) VALUES ('gem', 'Germaanse taal');
INSERT INTO `country` (`id`, `name`) VALUES ('gil', 'Gilbertees');
INSERT INTO `country` (`id`, `name`) VALUES ('gon', 'Gondi');
INSERT INTO `country` (`id`, `name`) VALUES ('gor', 'Gorontalo');
INSERT INTO `country` (`id`, `name`) VALUES ('got', 'Gothisch');
INSERT INTO `country` (`id`, `name`) VALUES ('grb', 'Grebo');
INSERT INTO `country` (`id`, `name`) VALUES ('el', 'Grieks');
INSERT INTO `country` (`id`, `name`) VALUES ('kl', 'Groenlands');
INSERT INTO `country` (`id`, `name`) VALUES ('gn', 'Guarani');
INSERT INTO `country` (`id`, `name`) VALUES ('gu', 'Gujarati');
INSERT INTO `country` (`id`, `name`) VALUES ('gwi', 'Gwichʼin');
INSERT INTO `country` (`id`, `name`) VALUES ('hai', 'Haida');
INSERT INTO `country` (`id`, `name`) VALUES ('ht', 'Haïtiaans');
INSERT INTO `country` (`id`, `name`) VALUES ('ha', 'Hausa');
INSERT INTO `country` (`id`, `name`) VALUES ('haw', 'Hawaïaans');
INSERT INTO `country` (`id`, `name`) VALUES ('he', 'Hebreeuws');
INSERT INTO `country` (`id`, `name`) VALUES ('hz', 'Herero');
INSERT INTO `country` (`id`, `name`) VALUES ('hit', 'Hettitisch');
INSERT INTO `country` (`id`, `name`) VALUES ('hil', 'Hiligaynon');
INSERT INTO `country` (`id`, `name`) VALUES ('him', 'Himachali');
INSERT INTO `country` (`id`, `name`) VALUES ('hi', 'Hindi');
INSERT INTO `country` (`id`, `name`) VALUES ('ho', 'Hiri Motu');
INSERT INTO `country` (`id`, `name`) VALUES ('hmn', 'Hmong');
INSERT INTO `country` (`id`, `name`) VALUES ('hu', 'Hongaars');
INSERT INTO `country` (`id`, `name`) VALUES ('hup', 'Hupa');
INSERT INTO `country` (`id`, `name`) VALUES ('iba', 'Iban');
INSERT INTO `country` (`id`, `name`) VALUES ('pt_PT', 'Iberisch Portugees');
INSERT INTO `country` (`id`, `name`) VALUES ('es_ES', 'Iberisch Spaans');
INSERT INTO `country` (`id`, `name`) VALUES ('io', 'Ido');
INSERT INTO `country` (`id`, `name`) VALUES ('ga', 'Iers');
INSERT INTO `country` (`id`, `name`) VALUES ('ig', 'Igbo');
INSERT INTO `country` (`id`, `name`) VALUES ('ijo', 'Ijo');
INSERT INTO `country` (`id`, `name`) VALUES ('is', 'IJslands');
INSERT INTO `country` (`id`, `name`) VALUES ('ilo', 'Iloko');
INSERT INTO `country` (`id`, `name`) VALUES ('smn', 'Inari Sami');
INSERT INTO `country` (`id`, `name`) VALUES ('inc', 'Indische taal');
INSERT INTO `country` (`id`, `name`) VALUES ('ine', 'Indo-Europese taal');
INSERT INTO `country` (`id`, `name`) VALUES ('id', 'Indonesisch');
INSERT INTO `country` (`id`, `name`) VALUES ('inh', 'Ingoesj');
INSERT INTO `country` (`id`, `name`) VALUES ('ia', 'Interlingua');
INSERT INTO `country` (`id`, `name`) VALUES ('ie', 'Interlingue');
INSERT INTO `country` (`id`, `name`) VALUES ('iu', 'Inuktitut');
INSERT INTO `country` (`id`, `name`) VALUES ('ik', 'Inupiaq');
INSERT INTO `country` (`id`, `name`) VALUES ('ira', 'Iraanse taal');
INSERT INTO `country` (`id`, `name`) VALUES ('iro', 'Irokese taal');
INSERT INTO `country` (`id`, `name`) VALUES ('it', 'Italiaans');
INSERT INTO `country` (`id`, `name`) VALUES ('sah', 'Jakoets');
INSERT INTO `country` (`id`, `name`) VALUES ('ja', 'Japans');
INSERT INTO `country` (`id`, `name`) VALUES ('jv', 'Javaans');
INSERT INTO `country` (`id`, `name`) VALUES ('yi', 'Jiddisch');
INSERT INTO `country` (`id`, `name`) VALUES ('kaj', 'Jju');
INSERT INTO `country` (`id`, `name`) VALUES ('jrb', 'Judeo-Arabisch');
INSERT INTO `country` (`id`, `name`) VALUES ('jpr', 'Judeo-Perzisch');
INSERT INTO `country` (`id`, `name`) VALUES ('kbd', 'Kabardisch');
INSERT INTO `country` (`id`, `name`) VALUES ('kea', 'Kabuverdianu');
INSERT INTO `country` (`id`, `name`) VALUES ('kab', 'Kabyle');
INSERT INTO `country` (`id`, `name`) VALUES ('kac', 'Kachin');
INSERT INTO `country` (`id`, `name`) VALUES ('xal', 'Kalmyk');
INSERT INTO `country` (`id`, `name`) VALUES ('kam', 'Kamba');
INSERT INTO `country` (`id`, `name`) VALUES ('kn', 'Kannada');
INSERT INTO `country` (`id`, `name`) VALUES ('yue', 'Kantonees');
INSERT INTO `country` (`id`, `name`) VALUES ('kr', 'Kanuri');
INSERT INTO `country` (`id`, `name`) VALUES ('krc', 'Karachay-Balkar');
INSERT INTO `country` (`id`, `name`) VALUES ('kaa', 'Karakalpaks');
INSERT INTO `country` (`id`, `name`) VALUES ('krl', 'Karelisch');
INSERT INTO `country` (`id`, `name`) VALUES ('kar', 'Karen');
INSERT INTO `country` (`id`, `name`) VALUES ('ks', 'Kasjmiri');
INSERT INTO `country` (`id`, `name`) VALUES ('csb', 'Kasjoebisch');
INSERT INTO `country` (`id`, `name`) VALUES ('cau', 'Kaukasische taal');
INSERT INTO `country` (`id`, `name`) VALUES ('kaw', 'Kawi');
INSERT INTO `country` (`id`, `name`) VALUES ('kk', 'Kazachs');
INSERT INTO `country` (`id`, `name`) VALUES ('cel', 'Keltische taal');
INSERT INTO `country` (`id`, `name`) VALUES ('cu', 'Kerkslavisch');
INSERT INTO `country` (`id`, `name`) VALUES ('kha', 'Khasi');
INSERT INTO `country` (`id`, `name`) VALUES ('km', 'Khmer');
INSERT INTO `country` (`id`, `name`) VALUES ('khi', 'Khoisan-taal');
INSERT INTO `country` (`id`, `name`) VALUES ('kho', 'Khotanees');
INSERT INTO `country` (`id`, `name`) VALUES ('ki', 'Kikuyu');
INSERT INTO `country` (`id`, `name`) VALUES ('kmb', 'Kimbundu');
INSERT INTO `country` (`id`, `name`) VALUES ('rw', 'Kinyarwanda');
INSERT INTO `country` (`id`, `name`) VALUES ('ky', 'Kirgizisch');
INSERT INTO `country` (`id`, `name`) VALUES ('rn', 'Kirundi');
INSERT INTO `country` (`id`, `name`) VALUES ('nwc', 'Klassiek Newari');
INSERT INTO `country` (`id`, `name`) VALUES ('syc', 'Klassiek Syrisch');
INSERT INTO `country` (`id`, `name`) VALUES ('tlh', 'Klingon');
INSERT INTO `country` (`id`, `name`) VALUES ('kum', 'Koemuks');
INSERT INTO `country` (`id`, `name`) VALUES ('ku', 'Koerdisch');
INSERT INTO `country` (`id`, `name`) VALUES ('cus', 'Koesjitische taal');
INSERT INTO `country` (`id`, `name`) VALUES ('kv', 'Komi');
INSERT INTO `country` (`id`, `name`) VALUES ('kg', 'Kongo');
INSERT INTO `country` (`id`, `name`) VALUES ('kok', 'Konkani');
INSERT INTO `country` (`id`, `name`) VALUES ('cop', 'Koptisch');
INSERT INTO `country` (`id`, `name`) VALUES ('ko', 'Koreaans');
INSERT INTO `country` (`id`, `name`) VALUES ('kfo', 'Koro');
INSERT INTO `country` (`id`, `name`) VALUES ('kos', 'Kosraeaans');
INSERT INTO `country` (`id`, `name`) VALUES ('kpe', 'Kpelle');
INSERT INTO `country` (`id`, `name`) VALUES ('crh', 'Krim-Tataars');
INSERT INTO `country` (`id`, `name`) VALUES ('hr', 'Kroatisch');
INSERT INTO `country` (`id`, `name`) VALUES ('kro', 'Kru');
INSERT INTO `country` (`id`, `name`) VALUES ('kj', 'Kuanyama');
INSERT INTO `country` (`id`, `name`) VALUES ('art', 'Kunstmatige taal');
INSERT INTO `country` (`id`, `name`) VALUES ('kru', 'Kurukh');
INSERT INTO `country` (`id`, `name`) VALUES ('kut', 'Kutenai');
INSERT INTO `country` (`id`, `name`) VALUES ('nds', 'Laagduits');
INSERT INTO `country` (`id`, `name`) VALUES ('lad', 'Ladino');
INSERT INTO `country` (`id`, `name`) VALUES ('lah', 'Lahnda');
INSERT INTO `country` (`id`, `name`) VALUES ('lam', 'Lamba');
INSERT INTO `country` (`id`, `name`) VALUES ('lo', 'Laotiaans');
INSERT INTO `country` (`id`, `name`) VALUES ('la', 'Latijn');
INSERT INTO `country` (`id`, `name`) VALUES ('es_419', 'Latijns-Amerikaans Spaans');
INSERT INTO `country` (`id`, `name`) VALUES ('lv', 'Letlands');
INSERT INTO `country` (`id`, `name`) VALUES ('lez', 'Lezgisch');
INSERT INTO `country` (`id`, `name`) VALUES ('li', 'Limburgs');
INSERT INTO `country` (`id`, `name`) VALUES ('ln', 'Lingala');
INSERT INTO `country` (`id`, `name`) VALUES ('lt', 'Litouws');
INSERT INTO `country` (`id`, `name`) VALUES ('jbo', 'Lojban');
INSERT INTO `country` (`id`, `name`) VALUES ('loz', 'Lozi');
INSERT INTO `country` (`id`, `name`) VALUES ('lu', 'Luba-Katanga');
INSERT INTO `country` (`id`, `name`) VALUES ('lua', 'Luba-Lulua');
INSERT INTO `country` (`id`, `name`) VALUES ('lui', 'Luiseno');
INSERT INTO `country` (`id`, `name`) VALUES ('smj', 'Lule Sami');
INSERT INTO `country` (`id`, `name`) VALUES ('lun', 'Lunda');
INSERT INTO `country` (`id`, `name`) VALUES ('luo', 'Luo');
INSERT INTO `country` (`id`, `name`) VALUES ('lus', 'Lushai');
INSERT INTO `country` (`id`, `name`) VALUES ('lb', 'Luxemburgs');
INSERT INTO `country` (`id`, `name`) VALUES ('mk', 'Macedonisch');
INSERT INTO `country` (`id`, `name`) VALUES ('mad', 'Madurees');
INSERT INTO `country` (`id`, `name`) VALUES ('mag', 'Magahi');
INSERT INTO `country` (`id`, `name`) VALUES ('mai', 'Maithili');
INSERT INTO `country` (`id`, `name`) VALUES ('mak', 'Makassaars');
INSERT INTO `country` (`id`, `name`) VALUES ('mg', 'Malagasisch');
INSERT INTO `country` (`id`, `name`) VALUES ('ml', 'Malayalam');
INSERT INTO `country` (`id`, `name`) VALUES ('ms', 'Maleis');
INSERT INTO `country` (`id`, `name`) VALUES ('mt', 'Maltees');
INSERT INTO `country` (`id`, `name`) VALUES ('mdr', 'Mandar');
INSERT INTO `country` (`id`, `name`) VALUES ('man', 'Mandingo');
INSERT INTO `country` (`id`, `name`) VALUES ('mni', 'Manipoeri');
INSERT INTO `country` (`id`, `name`) VALUES ('mno', 'Manobo-taal');
INSERT INTO `country` (`id`, `name`) VALUES ('mnc', 'Mantsjoe');
INSERT INTO `country` (`id`, `name`) VALUES ('gv', 'Manx');
INSERT INTO `country` (`id`, `name`) VALUES ('mi', 'Maori');
INSERT INTO `country` (`id`, `name`) VALUES ('mr', 'Marathi');
INSERT INTO `country` (`id`, `name`) VALUES ('chm', 'Mari');
INSERT INTO `country` (`id`, `name`) VALUES ('mh', 'Marshallees');
INSERT INTO `country` (`id`, `name`) VALUES ('mwr', 'Marwari');
INSERT INTO `country` (`id`, `name`) VALUES ('mas', 'Masai');
INSERT INTO `country` (`id`, `name`) VALUES ('myn', 'Mayan-taal');
INSERT INTO `country` (`id`, `name`) VALUES ('men', 'Mende');
INSERT INTO `country` (`id`, `name`) VALUES ('mic', 'Mi\'kmaq');
INSERT INTO `country` (`id`, `name`) VALUES ('enm', 'Middelengels');
INSERT INTO `country` (`id`, `name`) VALUES ('frm', 'Middelfrans');
INSERT INTO `country` (`id`, `name`) VALUES ('gmh', 'Middelhoogduits');
INSERT INTO `country` (`id`, `name`) VALUES ('mga', 'Middeliers');
INSERT INTO `country` (`id`, `name`) VALUES ('dum', 'Middelnederlands');
INSERT INTO `country` (`id`, `name`) VALUES ('cai', 'Midden-Amerikaans Indiaanse taal');
INSERT INTO `country` (`id`, `name`) VALUES ('min', 'Minangkabau');
INSERT INTO `country` (`id`, `name`) VALUES ('mwl', 'Mirandees');
INSERT INTO `country` (`id`, `name`) VALUES ('moh', 'Mohawk');
INSERT INTO `country` (`id`, `name`) VALUES ('mdf', 'Moksha');
INSERT INTO `country` (`id`, `name`) VALUES ('mo', 'Moldavisch');
INSERT INTO `country` (`id`, `name`) VALUES ('mkh', 'Mon-Khmer-taal');
INSERT INTO `country` (`id`, `name`) VALUES ('lol', 'Mongo');
INSERT INTO `country` (`id`, `name`) VALUES ('mn', 'Mongools');
INSERT INTO `country` (`id`, `name`) VALUES ('mos', 'Mossi');
INSERT INTO `country` (`id`, `name`) VALUES ('mun', 'Munda-taal');
INSERT INTO `country` (`id`, `name`) VALUES ('nqo', 'N’ko');
INSERT INTO `country` (`id`, `name`) VALUES ('nah', 'Nahuatl');
INSERT INTO `country` (`id`, `name`) VALUES ('nap', 'Napolitaans');
INSERT INTO `country` (`id`, `name`) VALUES ('na', 'Nauruaans');
INSERT INTO `country` (`id`, `name`) VALUES ('nv', 'Navajo');
INSERT INTO `country` (`id`, `name`) VALUES ('ng', 'Ndonga');
INSERT INTO `country` (`id`, `name`) VALUES ('nl', 'Nederlands');
INSERT INTO `country` (`id`, `name`) VALUES ('dsb', 'Nedersorbisch');
INSERT INTO `country` (`id`, `name`) VALUES ('ne', 'Nepalees');
INSERT INTO `country` (`id`, `name`) VALUES ('new', 'Newari');
INSERT INTO `country` (`id`, `name`) VALUES ('nia', 'Nias');
INSERT INTO `country` (`id`, `name`) VALUES ('nic', 'Niger-Kordofanische taal');
INSERT INTO `country` (`id`, `name`) VALUES ('ssa', 'Nilo-Saharaanse taal');
INSERT INTO `country` (`id`, `name`) VALUES ('niu', 'Niueaans');
INSERT INTO `country` (`id`, `name`) VALUES ('nog', 'Nogai');
INSERT INTO `country` (`id`, `name`) VALUES ('nai', 'Noord-Amerikaans Indiaanse taal');
INSERT INTO `country` (`id`, `name`) VALUES ('frr', 'Noord-Fries');
INSERT INTO `country` (`id`, `name`) VALUES ('nd', 'Noord-Ndbele');
INSERT INTO `country` (`id`, `name`) VALUES ('se', 'Noord-Samisch');
INSERT INTO `country` (`id`, `name`) VALUES ('nso', 'Noord-Sotho');
INSERT INTO `country` (`id`, `name`) VALUES ('no', 'Noors');
INSERT INTO `country` (`id`, `name`) VALUES ('nb', 'Noors - Bokmål');
INSERT INTO `country` (`id`, `name`) VALUES ('nn', 'Noors - Nynorsk');
INSERT INTO `country` (`id`, `name`) VALUES ('nub', 'Nubische taal');
INSERT INTO `country` (`id`, `name`) VALUES ('nym', 'Nyamwezi');
INSERT INTO `country` (`id`, `name`) VALUES ('ny', 'Nyanja');
INSERT INTO `country` (`id`, `name`) VALUES ('nyn', 'Nyankole');
INSERT INTO `country` (`id`, `name`) VALUES ('tog', 'Nyasa Tonga');
INSERT INTO `country` (`id`, `name`) VALUES ('nyo', 'Nyoro');
INSERT INTO `country` (`id`, `name`) VALUES ('nzi', 'Nzima');
INSERT INTO `country` (`id`, `name`) VALUES ('oc', 'Occitaans');
INSERT INTO `country` (`id`, `name`) VALUES ('udm', 'Oedmoerts');
INSERT INTO `country` (`id`, `name`) VALUES ('uga', 'Oegaritisch');
INSERT INTO `country` (`id`, `name`) VALUES ('ug', 'Oeigoers');
INSERT INTO `country` (`id`, `name`) VALUES ('uk', 'Oekraïens');
INSERT INTO `country` (`id`, `name`) VALUES ('uz', 'Oezbeeks');
INSERT INTO `country` (`id`, `name`) VALUES ('oj', 'Ojibwa');
INSERT INTO `country` (`id`, `name`) VALUES ('und', 'Onbekende taal');
INSERT INTO `country` (`id`, `name`) VALUES ('frs', 'Oost-Fries');
INSERT INTO `country` (`id`, `name`) VALUES ('de_AT', 'Oostenrijks Duits');
INSERT INTO `country` (`id`, `name`) VALUES ('cpe', 'Op Engels gebaseerd Creools of Pidgin');
INSERT INTO `country` (`id`, `name`) VALUES ('cpf', 'Op Frans gebaseerd Creools of Pidgin');
INSERT INTO `country` (`id`, `name`) VALUES ('cpp', 'Op Portugees gebaseerd Creools of Pidgin');
INSERT INTO `country` (`id`, `name`) VALUES ('hsb', 'Oppersorbisch');
INSERT INTO `country` (`id`, `name`) VALUES ('or', 'Oriya');
INSERT INTO `country` (`id`, `name`) VALUES ('om', 'Oromo');
INSERT INTO `country` (`id`, `name`) VALUES ('osa', 'Osage');
INSERT INTO `country` (`id`, `name`) VALUES ('os', 'Ossetisch');
INSERT INTO `country` (`id`, `name`) VALUES ('oto', 'Otomi-taal');
INSERT INTO `country` (`id`, `name`) VALUES ('ota', 'Ottomaans-Turks');
INSERT INTO `country` (`id`, `name`) VALUES ('egy', 'Oudegyptisch');
INSERT INTO `country` (`id`, `name`) VALUES ('ang', 'Oudengels');
INSERT INTO `country` (`id`, `name`) VALUES ('fro', 'Oudfrans');
INSERT INTO `country` (`id`, `name`) VALUES ('grc', 'Oudgrieks');
INSERT INTO `country` (`id`, `name`) VALUES ('goh', 'Oudhoogduits');
INSERT INTO `country` (`id`, `name`) VALUES ('sga', 'Oudiers');
INSERT INTO `country` (`id`, `name`) VALUES ('non', 'Oudnoors');
INSERT INTO `country` (`id`, `name`) VALUES ('peo', 'Oudperzisch');
INSERT INTO `country` (`id`, `name`) VALUES ('pro', 'Oudprovençaals');
INSERT INTO `country` (`id`, `name`) VALUES ('pal', 'Pahlavi');
INSERT INTO `country` (`id`, `name`) VALUES ('pau', 'Palauaans');
INSERT INTO `country` (`id`, `name`) VALUES ('pi', 'Pali');
INSERT INTO `country` (`id`, `name`) VALUES ('pam', 'Pampanga');
INSERT INTO `country` (`id`, `name`) VALUES ('pag', 'Pangasinan');
INSERT INTO `country` (`id`, `name`) VALUES ('pap', 'Papiaments');
INSERT INTO `country` (`id`, `name`) VALUES ('paa', 'Papoeataal');
INSERT INTO `country` (`id`, `name`) VALUES ('ps', 'Pasjtoe');
INSERT INTO `country` (`id`, `name`) VALUES ('fa', 'Perzisch');
INSERT INTO `country` (`id`, `name`) VALUES ('pon', 'Pohnpeiaans');
INSERT INTO `country` (`id`, `name`) VALUES ('pl', 'Pools');
INSERT INTO `country` (`id`, `name`) VALUES ('pt', 'Portugees');
INSERT INTO `country` (`id`, `name`) VALUES ('pra', 'Prakrit-taal');
INSERT INTO `country` (`id`, `name`) VALUES ('pa', 'Punjabi');
INSERT INTO `country` (`id`, `name`) VALUES ('qu', 'Quechua');
INSERT INTO `country` (`id`, `name`) VALUES ('raj', 'Rajasthani');
INSERT INTO `country` (`id`, `name`) VALUES ('rap', 'Rapanui');
INSERT INTO `country` (`id`, `name`) VALUES ('rar', 'Rarotongan');
INSERT INTO `country` (`id`, `name`) VALUES ('rm', 'Reto-Romaans');
INSERT INTO `country` (`id`, `name`) VALUES ('ro', 'Roemeens');
INSERT INTO `country` (`id`, `name`) VALUES ('roa', 'Romaanse taal');
INSERT INTO `country` (`id`, `name`) VALUES ('rom', 'Romani');
INSERT INTO `country` (`id`, `name`) VALUES ('root', 'Root');
INSERT INTO `country` (`id`, `name`) VALUES ('ru', 'Russisch');
INSERT INTO `country` (`id`, `name`) VALUES ('sal', 'Salishan-taal');
INSERT INTO `country` (`id`, `name`) VALUES ('sam', 'Samaritaans-Aramees');
INSERT INTO `country` (`id`, `name`) VALUES ('smi', 'Sami-taal');
INSERT INTO `country` (`id`, `name`) VALUES ('sm', 'Samoaans');
INSERT INTO `country` (`id`, `name`) VALUES ('sad', 'Sandawe');
INSERT INTO `country` (`id`, `name`) VALUES ('sg', 'Sango');
INSERT INTO `country` (`id`, `name`) VALUES ('sa', 'Sanskriet');
INSERT INTO `country` (`id`, `name`) VALUES ('sat', 'Santali');
INSERT INTO `country` (`id`, `name`) VALUES ('sc', 'Sardinisch');
INSERT INTO `country` (`id`, `name`) VALUES ('sas', 'Sasak');
INSERT INTO `country` (`id`, `name`) VALUES ('sco', 'Schots');
INSERT INTO `country` (`id`, `name`) VALUES ('gd', 'Schots Gaelic');
INSERT INTO `country` (`id`, `name`) VALUES ('sel', 'Selkup');
INSERT INTO `country` (`id`, `name`) VALUES ('sem', 'Semitische taal');
INSERT INTO `country` (`id`, `name`) VALUES ('srr', 'Serer');
INSERT INTO `country` (`id`, `name`) VALUES ('sr', 'Servisch');
INSERT INTO `country` (`id`, `name`) VALUES ('sh', 'Servokroatisch');
INSERT INTO `country` (`id`, `name`) VALUES ('shn', 'Shan');
INSERT INTO `country` (`id`, `name`) VALUES ('swb', 'Shimaore');
INSERT INTO `country` (`id`, `name`) VALUES ('sn', 'Shona');
INSERT INTO `country` (`id`, `name`) VALUES ('ii', 'Sichuan Yi');
INSERT INTO `country` (`id`, `name`) VALUES ('scn', 'Siciliaans');
INSERT INTO `country` (`id`, `name`) VALUES ('sid', 'Sidamo');
INSERT INTO `country` (`id`, `name`) VALUES ('bla', 'Siksika');
INSERT INTO `country` (`id`, `name`) VALUES ('sd', 'Sindhi');
INSERT INTO `country` (`id`, `name`) VALUES ('si', 'Singalees');
INSERT INTO `country` (`id`, `name`) VALUES ('sit', 'Sino-Tibetaanse taal');
INSERT INTO `country` (`id`, `name`) VALUES ('sio', 'Siouaanse talen');
INSERT INTO `country` (`id`, `name`) VALUES ('sms', 'Skolt Sami');
INSERT INTO `country` (`id`, `name`) VALUES ('den', 'Slave');
INSERT INTO `country` (`id`, `name`) VALUES ('sla', 'Slavische taal');
INSERT INTO `country` (`id`, `name`) VALUES ('sl', 'Sloveens');
INSERT INTO `country` (`id`, `name`) VALUES ('sk', 'Slowaaks');
INSERT INTO `country` (`id`, `name`) VALUES ('sux', 'Soemerisch');
INSERT INTO `country` (`id`, `name`) VALUES ('su', 'Soendanees');
INSERT INTO `country` (`id`, `name`) VALUES ('sus', 'Soesoe');
INSERT INTO `country` (`id`, `name`) VALUES ('sog', 'Sogdisch');
INSERT INTO `country` (`id`, `name`) VALUES ('so', 'Somalisch');
INSERT INTO `country` (`id`, `name`) VALUES ('son', 'Songhai');
INSERT INTO `country` (`id`, `name`) VALUES ('snk', 'Soninke');
INSERT INTO `country` (`id`, `name`) VALUES ('wen', 'Sorbische taal');
INSERT INTO `country` (`id`, `name`) VALUES ('es', 'Spaans');
INSERT INTO `country` (`id`, `name`) VALUES ('srn', 'Sranantongo');
INSERT INTO `country` (`id`, `name`) VALUES ('suk', 'Sukuma');
INSERT INTO `country` (`id`, `name`) VALUES ('sw', 'Swahili');
INSERT INTO `country` (`id`, `name`) VALUES ('ss', 'Swazi');
INSERT INTO `country` (`id`, `name`) VALUES ('syr', 'Syriac');
INSERT INTO `country` (`id`, `name`) VALUES ('tg', 'Tadzjieks');
INSERT INTO `country` (`id`, `name`) VALUES ('tl', 'Tagalog');
INSERT INTO `country` (`id`, `name`) VALUES ('ty', 'Tahitisch');
INSERT INTO `country` (`id`, `name`) VALUES ('tai', 'Tai-taal');
INSERT INTO `country` (`id`, `name`) VALUES ('tmh', 'Tamashek');
INSERT INTO `country` (`id`, `name`) VALUES ('ta', 'Tamil');
INSERT INTO `country` (`id`, `name`) VALUES ('tt', 'Tataars');
INSERT INTO `country` (`id`, `name`) VALUES ('te', 'Teloegoe');
INSERT INTO `country` (`id`, `name`) VALUES ('ter', 'Tereno');
INSERT INTO `country` (`id`, `name`) VALUES ('tet', 'Tetun');
INSERT INTO `country` (`id`, `name`) VALUES ('th', 'Thais');
INSERT INTO `country` (`id`, `name`) VALUES ('bo', 'Tibetaans');
INSERT INTO `country` (`id`, `name`) VALUES ('tig', 'Tigre');
INSERT INTO `country` (`id`, `name`) VALUES ('ti', 'Tigrinya');
INSERT INTO `country` (`id`, `name`) VALUES ('tem', 'Timne');
INSERT INTO `country` (`id`, `name`) VALUES ('tiv', 'Tiv');
INSERT INTO `country` (`id`, `name`) VALUES ('tli', 'Tlingit');
INSERT INTO `country` (`id`, `name`) VALUES ('tum', 'Toemboeka');
INSERT INTO `country` (`id`, `name`) VALUES ('tpi', 'Tok Pisin');
INSERT INTO `country` (`id`, `name`) VALUES ('tkl', 'Tokelaus');
INSERT INTO `country` (`id`, `name`) VALUES ('to', 'Tongaans');
INSERT INTO `country` (`id`, `name`) VALUES ('zh_Hant', 'Traditioneel Chinees');
INSERT INTO `country` (`id`, `name`) VALUES ('tsi', 'Tsimshian');
INSERT INTO `country` (`id`, `name`) VALUES ('cs', 'Tsjechisch');
INSERT INTO `country` (`id`, `name`) VALUES ('ce', 'Tsjetsjeens');
INSERT INTO `country` (`id`, `name`) VALUES ('cv', 'Tsjoevasjisch');
INSERT INTO `country` (`id`, `name`) VALUES ('ts', 'Tsonga');
INSERT INTO `country` (`id`, `name`) VALUES ('tn', 'Tswana');
INSERT INTO `country` (`id`, `name`) VALUES ('tup', 'Tupi-taal');
INSERT INTO `country` (`id`, `name`) VALUES ('tk', 'Turkmeens');
INSERT INTO `country` (`id`, `name`) VALUES ('tr', 'Turks');
INSERT INTO `country` (`id`, `name`) VALUES ('tvl', 'Tuvaluaans');
INSERT INTO `country` (`id`, `name`) VALUES ('tyv', 'Tuvinisch');
INSERT INTO `country` (`id`, `name`) VALUES ('tw', 'Twi');
INSERT INTO `country` (`id`, `name`) VALUES ('kcg', 'Tyap');
INSERT INTO `country` (`id`, `name`) VALUES ('umb', 'Umbundu');
INSERT INTO `country` (`id`, `name`) VALUES ('ur', 'Urdu');
INSERT INTO `country` (`id`, `name`) VALUES ('vai', 'Vai');
INSERT INTO `country` (`id`, `name`) VALUES ('ve', 'Venda');
INSERT INTO `country` (`id`, `name`) VALUES ('zh_Hans', 'Vereenvoudigd Chinees');
INSERT INTO `country` (`id`, `name`) VALUES ('vi', 'Vietnamees');
INSERT INTO `country` (`id`, `name`) VALUES ('nl_BE', 'Vlaams');
INSERT INTO `country` (`id`, `name`) VALUES ('vo', 'Volapük');
INSERT INTO `country` (`id`, `name`) VALUES ('vot', 'Votisch');
INSERT INTO `country` (`id`, `name`) VALUES ('wa', 'Waals');
INSERT INTO `country` (`id`, `name`) VALUES ('wak', 'Wakashan-taal');
INSERT INTO `country` (`id`, `name`) VALUES ('wal', 'Walamo');
INSERT INTO `country` (`id`, `name`) VALUES ('war', 'Waray');
INSERT INTO `country` (`id`, `name`) VALUES ('was', 'Washo');
INSERT INTO `country` (`id`, `name`) VALUES ('cy', 'Welsh');
INSERT INTO `country` (`id`, `name`) VALUES ('fy', 'West-Fries');
INSERT INTO `country` (`id`, `name`) VALUES ('be', 'Wit-Russisch');
INSERT INTO `country` (`id`, `name`) VALUES ('wo', 'Wolof');
INSERT INTO `country` (`id`, `name`) VALUES ('xh', 'Xhosa');
INSERT INTO `country` (`id`, `name`) VALUES ('yao', 'Yao');
INSERT INTO `country` (`id`, `name`) VALUES ('yap', 'Yapees');
INSERT INTO `country` (`id`, `name`) VALUES ('yo', 'Yoruba');
INSERT INTO `country` (`id`, `name`) VALUES ('ypk', 'Yupik-talen');
INSERT INTO `country` (`id`, `name`) VALUES ('znd', 'Zande');
INSERT INTO `country` (`id`, `name`) VALUES ('zap', 'Zapotec');
INSERT INTO `country` (`id`, `name`) VALUES ('zza', 'Zaza');
INSERT INTO `country` (`id`, `name`) VALUES ('zen', 'Zenaga');
INSERT INTO `country` (`id`, `name`) VALUES ('za', 'Zhuang');
INSERT INTO `country` (`id`, `name`) VALUES ('alt', 'Zuid-Altaïsch');
INSERT INTO `country` (`id`, `name`) VALUES ('sai', 'Zuid-Amerikaans Indiaanse taal');
INSERT INTO `country` (`id`, `name`) VALUES ('nr', 'Zuid-Ndbele');
INSERT INTO `country` (`id`, `name`) VALUES ('sma', 'Zuid-Samisch');
INSERT INTO `country` (`id`, `name`) VALUES ('st', 'Zuid-Sotho');
INSERT INTO `country` (`id`, `name`) VALUES ('zu', 'Zulu');
INSERT INTO `country` (`id`, `name`) VALUES ('zun', 'Zuni');
INSERT INTO `country` (`id`, `name`) VALUES ('sv', 'Zweeds');
INSERT INTO `country` (`id`, `name`) VALUES ('gsw', 'Zwitsers Duits');
INSERT INTO `country` (`id`, `name`) VALUES ('fr_CH', 'Zwitsers Frans');
INSERT INTO `country` (`id`, `name`) VALUES ('de_CH', 'Zwitsers Hoogduits');
