CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('am', 'ಅಂಹರಿಕ್');
INSERT INTO "country" ("id", "name") VALUES ('ak', 'ಅಕನ್');
INSERT INTO "country" ("id", "name") VALUES ('ach', 'ಅಕೋಲಿ');
INSERT INTO "country" ("id", "name") VALUES ('akk', 'ಅಕ್ಕಾಡಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('ace', 'ಅಛಿನೀಸ್');
INSERT INTO "country" ("id", "name") VALUES ('az', 'ಅಜರ್‌ಬೈಜಾನಿ');
INSERT INTO "country" ("id", "name") VALUES ('cch', 'ಅಟ್ಸಮ್');
INSERT INTO "country" ("id", "name") VALUES ('ada', 'ಅಡಂಗ್‌ಮೆ');
INSERT INTO "country" ("id", "name") VALUES ('ady', 'ಅಡೈಘೆ');
INSERT INTO "country" ("id", "name") VALUES ('ath', 'ಅಥಪಾಸ್ಕನ್ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('und', 'ಅಪರಿಚಿತ ಅಥವಾ ಅಮಾನ್ಯ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('apa', 'ಅಪಾಚಿ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('hsb', 'ಅಪ್ಪರ್ ಸರ್ಬಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('aa', 'ಅಫಾರ್');
INSERT INTO "country" ("id", "name") VALUES ('ab', 'ಅಬ್ಖಾಜಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('ay', 'ಅಯ್ಮಾರಾ');
INSERT INTO "country" ("id", "name") VALUES ('an', 'ಅರಗೊನೀಸ್');
INSERT INTO "country" ("id", "name") VALUES ('arp', 'ಅರಪಾಹೋ');
INSERT INTO "country" ("id", "name") VALUES ('arc', 'ಅರಾಮಿಕ್');
INSERT INTO "country" ("id", "name") VALUES ('arw', 'ಅರಾವಾಕ್');
INSERT INTO "country" ("id", "name") VALUES ('ar', 'ಅರೇಬಿಕ್');
INSERT INTO "country" ("id", "name") VALUES ('rup', 'ಅರೋಮಾನಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('arn', 'ಅರೌಕೇನಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('hy', 'ಅರ್ಮೇನಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('ale', 'ಅಲೆಯುಟ್');
INSERT INTO "country" ("id", "name") VALUES ('alg', 'ಅಲ್ಗೊಂಕ್ವಿಯನ್ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('sq', 'ಅಲ್ಬೇನಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('awa', 'ಅವಧಿ');
INSERT INTO "country" ("id", "name") VALUES ('av', 'ಅವರಿಕ್');
INSERT INTO "country" ("id", "name") VALUES ('ae', 'ಅವೆಸ್ಟನ್');
INSERT INTO "country" ("id", "name") VALUES ('as', 'ಅಸ್ಸಾಮೀಸ್');
INSERT INTO "country" ("id", "name") VALUES ('anp', 'ಆಂಗಿಕಾ');
INSERT INTO "country" ("id", "name") VALUES ('oc', 'ಆಕ್ಸಿಟಾನ್');
INSERT INTO "country" ("id", "name") VALUES ('af', 'ಆಫ್ರಿಕಾನ್ಸ್');
INSERT INTO "country" ("id", "name") VALUES ('afh', 'ಆಫ್ರಿಹಿಲಿ');
INSERT INTO "country" ("id", "name") VALUES ('afa', 'ಆಫ್ರೋ-ಏಶಿಯಾಟಿಕ್ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('tut', 'ಆಲ್ಟಾಯಿಕ್ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('ast', 'ಆಸ್ಟುರಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('de_AT', 'ಆಸ್ಟ್ರಿಯನ್ ಜರ್ಮನ್');
INSERT INTO "country" ("id", "name") VALUES ('en_AU', 'ಆಸ್ಟ್ರೇಲಿಯನ್ ಇಂಗ್ಲೀಷ್');
INSERT INTO "country" ("id", "name") VALUES ('aus', 'ಆಸ್ಟ್ರೇಲಿಯನ್ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('map', 'ಆಸ್ಟ್ರೋನೇಷ್ಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('inh', 'ಇಂಗುಷ್');
INSERT INTO "country" ("id", "name") VALUES ('en', 'ಇಂಗ್ಲೀಷ್');
INSERT INTO "country" ("id", "name") VALUES ('cpe', 'ಇಂಗ್ಲೀಷ್-ಮೂಲದ ಕ್ರಿಯೋಲ್ ಅಥವಾ ಪಿಡ್ಗಿನ್');
INSERT INTO "country" ("id", "name") VALUES ('ia', 'ಇಂಟರ್ಲಿಂಗುವಾ');
INSERT INTO "country" ("id", "name") VALUES ('ie', 'ಇಂಟರ್ಲಿಂಗ್');
INSERT INTO "country" ("id", "name") VALUES ('ine', 'ಇಂಡೋ-ಯೂರೋಪಿಯನ್ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('id', 'ಇಂಡೋನೇಶಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('ig', 'ಇಗ್ಬೊ');
INSERT INTO "country" ("id", "name") VALUES ('ijo', 'ಇಜೋ');
INSERT INTO "country" ("id", "name") VALUES ('it', 'ಇಟಾಲಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('io', 'ಇಡೊ');
INSERT INTO "country" ("id", "name") VALUES ('smn', 'ಇನರಿ ಸಾಮಿ');
INSERT INTO "country" ("id", "name") VALUES ('iu', 'ಇನುಕ್ಟಿಟುಟ್');
INSERT INTO "country" ("id", "name") VALUES ('ik', 'ಇನುಪಿಯಾಕ್');
INSERT INTO "country" ("id", "name") VALUES ('iba', 'ಇಬಾನ್');
INSERT INTO "country" ("id", "name") VALUES ('ira', 'ಇರಾನಿಯನ್ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('iro', 'ಇರೋಕ್ವಿಯನ್ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('ilo', 'ಇಲ್ಲಿಕೋ');
INSERT INTO "country" ("id", "name") VALUES ('ewo', 'ಇವಾಂಡೋ');
INSERT INTO "country" ("id", "name") VALUES ('umb', 'ಉಂಬುಂಡು');
INSERT INTO "country" ("id", "name") VALUES ('uk', 'ಉಕ್ರೈನಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('uga', 'ಉಗಾರಿಟಿಕ್');
INSERT INTO "country" ("id", "name") VALUES ('uz', 'ಉಜ್ಬೇಕ್');
INSERT INTO "country" ("id", "name") VALUES ('udm', 'ಉಡ್‌ಮುರ್ಟ್');
INSERT INTO "country" ("id", "name") VALUES ('nai', 'ಉತ್ತರ ಅಮೇರಿಕದ ಇಂಡಿಯನ್ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('nd', 'ಉತ್ತರ ದೆಬೆಲೆ');
INSERT INTO "country" ("id", "name") VALUES ('frr', 'ಉತ್ತರ ಫ್ರಿಸಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('se', 'ಉತ್ತರ ಸಾಮಿ');
INSERT INTO "country" ("id", "name") VALUES ('nso', 'ಉತ್ತರ ಸೋಥೋ');
INSERT INTO "country" ("id", "name") VALUES ('ug', 'ಉಯಿಘರ್');
INSERT INTO "country" ("id", "name") VALUES ('ur', 'ಉರ್ದು');
INSERT INTO "country" ("id", "name") VALUES ('eka', 'ಎಕಾಜುಕ್');
INSERT INTO "country" ("id", "name") VALUES ('nqo', 'ಎನ್‌ಕೋ');
INSERT INTO "country" ("id", "name") VALUES ('efi', 'ಎಫಿಕ್');
INSERT INTO "country" ("id", "name") VALUES ('myv', 'ಎರ್‌ಝ್ಯಾ');
INSERT INTO "country" ("id", "name") VALUES ('elx', 'ಎಲಾಮೈಟ್');
INSERT INTO "country" ("id", "name") VALUES ('et', 'ಎಸ್ಟೊನಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('eo', 'ಎಸ್ಪೆರಾಂಟೊ');
INSERT INTO "country" ("id", "name") VALUES ('ee', 'ಏವ್');
INSERT INTO "country" ("id", "name") VALUES ('ain', 'ಐನು');
INSERT INTO "country" ("id", "name") VALUES ('pt_PT', 'ಐಬೀರಿಯನ್ ಪೋರ್ಚುಗೀಸ್');
INSERT INTO "country" ("id", "name") VALUES ('es_ES', 'ಐಬೇರಿಯನ್ ಸ್ಪ್ಯಾನಿಶ್');
INSERT INTO "country" ("id", "name") VALUES ('ga', 'ಐರಿಷ್');
INSERT INTO "country" ("id", "name") VALUES ('is', 'ಐಸ್‌ಲ್ಯಾಂಡಿಕ್');
INSERT INTO "country" ("id", "name") VALUES ('oj', 'ಒಜಿಬ್ವಾ');
INSERT INTO "country" ("id", "name") VALUES ('ota', 'ಒಟ್ಟೋಮನ್ ತುರ್ಕಿಷ್');
INSERT INTO "country" ("id", "name") VALUES ('oto', 'ಒಟ್ಟೋಮನ್ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('om', 'ಒರೊಮೊ');
INSERT INTO "country" ("id", "name") VALUES ('os', 'ಒಸ್ಸೆಟಿಕ್');
INSERT INTO "country" ("id", "name") VALUES ('or', 'ಓರಿಯಾ');
INSERT INTO "country" ("id", "name") VALUES ('osa', 'ಓಸಾಜ್');
INSERT INTO "country" ("id", "name") VALUES ('kam', 'ಕಂಬಾ');
INSERT INTO "country" ("id", "name") VALUES ('cau', 'ಕಕೇಶಿಯನ್ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('kac', 'ಕಚಿನ್');
INSERT INTO "country" ("id", "name") VALUES ('kk', 'ಕಝಕ್');
INSERT INTO "country" ("id", "name") VALUES ('kr', 'ಕನುರಿ');
INSERT INTO "country" ("id", "name") VALUES ('kn', 'ಕನ್ನಡ');
INSERT INTO "country" ("id", "name") VALUES ('kpe', 'ಕಪೆಲ್ಲೆ');
INSERT INTO "country" ("id", "name") VALUES ('kbd', 'ಕಬರ್ಡಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('kab', 'ಕಬೈಲ್');
INSERT INTO "country" ("id", "name") VALUES ('ch', 'ಕಮೊರೊ');
INSERT INTO "country" ("id", "name") VALUES ('krc', 'ಕರಚಯ್-ಬಲ್ಕಾರ್');
INSERT INTO "country" ("id", "name") VALUES ('kar', 'ಕರೆನ್');
INSERT INTO "country" ("id", "name") VALUES ('krl', 'ಕರೇಲಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('kl', 'ಕಲಾಲ್ಲಿಸುಟ್');
INSERT INTO "country" ("id", "name") VALUES ('xal', 'ಕಲ್‌ಮೈಕ್');
INSERT INTO "country" ("id", "name") VALUES ('csb', 'ಕಶುಬಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('kg', 'ಕಾಂಗೋ');
INSERT INTO "country" ("id", "name") VALUES ('lad', 'ಕಾಡಿನೋ');
INSERT INTO "country" ("id", "name") VALUES ('kaa', 'ಕಾರಾ-ಕಲ್ಪಾಕ್');
INSERT INTO "country" ("id", "name") VALUES ('car', 'ಕಾರಿಬ್');
INSERT INTO "country" ("id", "name") VALUES ('kaw', 'ಕಾವಿ');
INSERT INTO "country" ("id", "name") VALUES ('ks', 'ಕಾಶ್ಮೀರಿ');
INSERT INTO "country" ("id", "name") VALUES ('kmb', 'ಕಿಂಬುಂಡು');
INSERT INTO "country" ("id", "name") VALUES ('ki', 'ಕಿಕುಯು');
INSERT INTO "country" ("id", "name") VALUES ('mwl', 'ಕಿರಾಂಡೀಸ್');
INSERT INTO "country" ("id", "name") VALUES ('ky', 'ಕಿರ್ಜಿಝ್');
INSERT INTO "country" ("id", "name") VALUES ('rw', 'ಕೀನ್ಯಾರುವಾಂಡಾ');
INSERT INTO "country" ("id", "name") VALUES ('kut', 'ಕುಟೇನಾಯ್');
INSERT INTO "country" ("id", "name") VALUES ('kum', 'ಕುಮೈಕ್');
INSERT INTO "country" ("id", "name") VALUES ('kru', 'ಕುರುಖ್');
INSERT INTO "country" ("id", "name") VALUES ('ku', 'ಕುರ್ದಿಷ್');
INSERT INTO "country" ("id", "name") VALUES ('cus', 'ಕುಷಿಟಿಕ್ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('art', 'ಕೃತಕ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('ca', 'ಕೆಟಲಾನ್');
INSERT INTO "country" ("id", "name") VALUES ('en_CA', 'ಕೆನೆಡಿಯನ್ ಇಂಗ್ಲೀಷ್');
INSERT INTO "country" ("id", "name") VALUES ('fr_CA', 'ಕೆನೆಡಿಯನ್ ಫ್ರೆಂಚ್');
INSERT INTO "country" ("id", "name") VALUES ('kok', 'ಕೊಂಕಣಿ');
INSERT INTO "country" ("id", "name") VALUES ('cop', 'ಕೊಪ್ಟಿಕ್');
INSERT INTO "country" ("id", "name") VALUES ('co', 'ಕೊರ್ಸಿಕನ್');
INSERT INTO "country" ("id", "name") VALUES ('kos', 'ಕೊಸರಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('kv', 'ಕೋಮಿ');
INSERT INTO "country" ("id", "name") VALUES ('ko', 'ಕೋರಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('kfo', 'ಕೋರೋ');
INSERT INTO "country" ("id", "name") VALUES ('kw', 'ಕೋರ್ನಿಷ್');
INSERT INTO "country" ("id", "name") VALUES ('cad', 'ಕ್ಯಾಡ್ಡೋ');
INSERT INTO "country" ("id", "name") VALUES ('crh', 'ಕ್ರಿಮೀಯನ್ ಟರ್ಕಿಷ್');
INSERT INTO "country" ("id", "name") VALUES ('crp', 'ಕ್ರಿಯೋಲ್ ಅಥವಾ ಪಿಡ್ಗಿನ್');
INSERT INTO "country" ("id", "name") VALUES ('cr', 'ಕ್ರೀ');
INSERT INTO "country" ("id", "name") VALUES ('mus', 'ಕ್ರೀಕ್');
INSERT INTO "country" ("id", "name") VALUES ('kro', 'ಕ್ರು');
INSERT INTO "country" ("id", "name") VALUES ('hr', 'ಕ್ರೊಯೇಶಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('tlh', 'ಕ್ಲಿಂಗೋನ್');
INSERT INTO "country" ("id", "name") VALUES ('kj', 'ಕ್ವಾನ್‌ಯಾಮಾ');
INSERT INTO "country" ("id", "name") VALUES ('qu', 'ಕ್ವೆಚುವಾ');
INSERT INTO "country" ("id", "name") VALUES ('km', 'ಖಮೇರ್');
INSERT INTO "country" ("id", "name") VALUES ('kha', 'ಖಾಸಿ');
INSERT INTO "country" ("id", "name") VALUES ('khi', 'ಖೋಇಸನ್ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('kho', 'ಖೋಟಾನೀಸ್');
INSERT INTO "country" ("id", "name") VALUES ('lg', 'ಗಂಡಾ');
INSERT INTO "country" ("id", "name") VALUES ('gaa', 'ಗಾ');
INSERT INTO "country" ("id", "name") VALUES ('gay', 'ಗಾಯೋ');
INSERT INTO "country" ("id", "name") VALUES ('gil', 'ಗಿಲ್ಬರ್ಟೀಸ್');
INSERT INTO "country" ("id", "name") VALUES ('gez', 'ಗೀಝ್');
INSERT INTO "country" ("id", "name") VALUES ('gu', 'ಗುಜರಾತಿ');
INSERT INTO "country" ("id", "name") VALUES ('gon', 'ಗೊಂಡಿ');
INSERT INTO "country" ("id", "name") VALUES ('gor', 'ಗೊರೊಂಟಾಲೋ');
INSERT INTO "country" ("id", "name") VALUES ('got', 'ಗೋಥಿಕ್');
INSERT INTO "country" ("id", "name") VALUES ('gn', 'ಗೌರಾನಿ');
INSERT INTO "country" ("id", "name") VALUES ('gba', 'ಗ್ಬಾಯಾ');
INSERT INTO "country" ("id", "name") VALUES ('gl', 'ಗ್ಯಾಲಿಶಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('el', 'ಗ್ರೀಕ್');
INSERT INTO "country" ("id", "name") VALUES ('grb', 'ಗ್ರೇಬೋ');
INSERT INTO "country" ("id", "name") VALUES ('gwi', 'ಗ್ವಿಚ್‌ಇನ್');
INSERT INTO "country" ("id", "name") VALUES ('chg', 'ಚಗಟಾಯ್');
INSERT INTO "country" ("id", "name") VALUES ('cu', 'ಚರ್ಚ್ ಸ್ಲಾವಿಕ್');
INSERT INTO "country" ("id", "name") VALUES ('cmc', 'ಚಾಮಿಕ್ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('chn', 'ಚಿನೂಕ್ ಜಾರ್ಗೋನ್');
INSERT INTO "country" ("id", "name") VALUES ('chp', 'ಚಿಪೆವ್ಯಾನ್');
INSERT INTO "country" ("id", "name") VALUES ('chb', 'ಚಿಬ್ಚಾ');
INSERT INTO "country" ("id", "name") VALUES ('chy', 'ಚೀಯೆನ್ನೇ');
INSERT INTO "country" ("id", "name") VALUES ('chr', 'ಚೀರೋಕೀ');
INSERT INTO "country" ("id", "name") VALUES ('cv', 'ಚುವಾಶ್');
INSERT INTO "country" ("id", "name") VALUES ('chk', 'ಚೂಕಿಸೆ');
INSERT INTO "country" ("id", "name") VALUES ('ce', 'ಚೆಚನ್');
INSERT INTO "country" ("id", "name") VALUES ('zh', 'ಚೈನೀಸ್');
INSERT INTO "country" ("id", "name") VALUES ('cho', 'ಚೋಕ್ಟಾವ್');
INSERT INTO "country" ("id", "name") VALUES ('ja', 'ಜಪಾನೀಸ್');
INSERT INTO "country" ("id", "name") VALUES ('gem', 'ಜರ್ಮನಿಕ್ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('de', 'ಜರ್ಮನ್');
INSERT INTO "country" ("id", "name") VALUES ('jv', 'ಜವಾನೀಸ್');
INSERT INTO "country" ("id", "name") VALUES ('zza', 'ಜಾಝಾ');
INSERT INTO "country" ("id", "name") VALUES ('ka', 'ಜಾರ್ಜಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('nzi', 'ಜೀಮಾ');
INSERT INTO "country" ("id", "name") VALUES ('zu', 'ಜುಲು');
INSERT INTO "country" ("id", "name") VALUES ('jrb', 'ಜೂಡಿಯೋ-ಅರೇಬಿಕ್');
INSERT INTO "country" ("id", "name") VALUES ('jpr', 'ಜೂಡಿಯೋ-ಪರ್ಶಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('cs', 'ಜೆಕ್');
INSERT INTO "country" ("id", "name") VALUES ('dz', 'ಜೋಂಗ್‌ಖಾ');
INSERT INTO "country" ("id", "name") VALUES ('kaj', 'ಜ್ಜು');
INSERT INTO "country" ("id", "name") VALUES ('znd', 'ಝಂಡೇ');
INSERT INTO "country" ("id", "name") VALUES ('zun', 'ಝೂನಿ');
INSERT INTO "country" ("id", "name") VALUES ('za', 'ಝೂವಾಂಗ್');
INSERT INTO "country" ("id", "name") VALUES ('zen', 'ಝೆನಾಗಾ');
INSERT INTO "country" ("id", "name") VALUES ('zap', 'ಝೋಪೊಟೆಕ್');
INSERT INTO "country" ("id", "name") VALUES ('tmh', 'ಟಮಾಷೆಕ್');
INSERT INTO "country" ("id", "name") VALUES ('tr', 'ಟರ್ಕಿಶ್');
INSERT INTO "country" ("id", "name") VALUES ('tk', 'ಟರ್ಕ್‌ಮೆನ್');
INSERT INTO "country" ("id", "name") VALUES ('tt', 'ಟಾಟರ್');
INSERT INTO "country" ("id", "name") VALUES ('bo', 'ಟಿಬೇಟಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('tem', 'ಟಿಮ್ನೆ');
INSERT INTO "country" ("id", "name") VALUES ('tiv', 'ಟಿವ್');
INSERT INTO "country" ("id", "name") VALUES ('tum', 'ಟುಂಬುಕ');
INSERT INTO "country" ("id", "name") VALUES ('tvl', 'ಟುವಾಲು');
INSERT INTO "country" ("id", "name") VALUES ('tyv', 'ಟುವಿನಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('tup', 'ಟೂಪಿ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('ter', 'ಟೆರೆನೋ');
INSERT INTO "country" ("id", "name") VALUES ('tet', 'ಟೇಟಮ್');
INSERT INTO "country" ("id", "name") VALUES ('ti', 'ಟೈಗ್ರಿನ್ಯಾ');
INSERT INTO "country" ("id", "name") VALUES ('tig', 'ಟೈಗ್ರೆ');
INSERT INTO "country" ("id", "name") VALUES ('to', 'ಟೊಂಗಾ');
INSERT INTO "country" ("id", "name") VALUES ('tkl', 'ಟೊಕೆಲಾವ್');
INSERT INTO "country" ("id", "name") VALUES ('tpi', 'ಟೋಕ್ ಪಿಸಿನ್');
INSERT INTO "country" ("id", "name") VALUES ('tl', 'ಟ್ಯಾಗಲೋಗ್');
INSERT INTO "country" ("id", "name") VALUES ('kcg', 'ಟ್ಯಾಪ್');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hant', 'ಟ್ರೆಡೀಶನಲ್ ಚೈನೀಸ್');
INSERT INTO "country" ("id", "name") VALUES ('tli', 'ಟ್ಲಿಂಗಿಟ್');
INSERT INTO "country" ("id", "name") VALUES ('tw', 'ಟ್ವಿ');
INSERT INTO "country" ("id", "name") VALUES ('dak', 'ಡಕೋಟ');
INSERT INTO "country" ("id", "name") VALUES ('nl', 'ಡಚ್');
INSERT INTO "country" ("id", "name") VALUES ('din', 'ಡಿಂಕಾ');
INSERT INTO "country" ("id", "name") VALUES ('dua', 'ಡುವಾಲಾ');
INSERT INTO "country" ("id", "name") VALUES ('del', 'ಡೆಲಾವೇರ್');
INSERT INTO "country" ("id", "name") VALUES ('ng', 'ಡೋಂಗಾ');
INSERT INTO "country" ("id", "name") VALUES ('doi', 'ಡೋಗ್ರಿ');
INSERT INTO "country" ("id", "name") VALUES ('dgr', 'ಡೋಗ್ರಿಬ್');
INSERT INTO "country" ("id", "name") VALUES ('da', 'ಡ್ಯಾನಿಶ್');
INSERT INTO "country" ("id", "name") VALUES ('dyu', 'ಡ್ಯೂಲಾ');
INSERT INTO "country" ("id", "name") VALUES ('dra', 'ಡ್ರಾವಿಡಿಯನ್ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('ta', 'ತಮಿಳು');
INSERT INTO "country" ("id", "name") VALUES ('ty', 'ತಹಿತಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('tg', 'ತಾಜಿಕ್');
INSERT INTO "country" ("id", "name") VALUES ('te', 'ತೆಲುಗು');
INSERT INTO "country" ("id", "name") VALUES ('th', 'ಥಾಯಿ');
INSERT INTO "country" ("id", "name") VALUES ('tai', 'ಥಾಯ್ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('sai', 'ದಕ್ಷಿಣ ಅಮೇರಿಕದ ಇಂಡಿಯನ್ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('alt', 'ದಕ್ಷಿಣ ಅಲ್ಟಾಯ್');
INSERT INTO "country" ("id", "name") VALUES ('nr', 'ದಕ್ಷಿಣ ದೆಬೆಲೆ');
INSERT INTO "country" ("id", "name") VALUES ('sma', 'ದಕ್ಷಿಣ ಸಾಮಿ');
INSERT INTO "country" ("id", "name") VALUES ('st', 'ದಕ್ಷಿಣ ಸೋಥೋ');
INSERT INTO "country" ("id", "name") VALUES ('dar', 'ದರ್ಗ್ವಾ');
INSERT INTO "country" ("id", "name") VALUES ('day', 'ದಾಯಕ್');
INSERT INTO "country" ("id", "name") VALUES ('dv', 'ದಿವೆಹಿ');
INSERT INTO "country" ("id", "name") VALUES ('nv', 'ನವಾಜೊ');
INSERT INTO "country" ("id", "name") VALUES ('nah', 'ನಹೌಟಿ');
INSERT INTO "country" ("id", "name") VALUES ('no', 'ನಾರ್ವೇಜಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('nn', 'ನಾರ್ವೇಜಿಯನ್ ನೂನಾರ್ಸ್ಕ್');
INSERT INTO "country" ("id", "name") VALUES ('nap', 'ನಿಯಾಪೊಲಿಟನ್');
INSERT INTO "country" ("id", "name") VALUES ('nia', 'ನಿಯಾಸ್');
INSERT INTO "country" ("id", "name") VALUES ('niu', 'ನಿಯುವನ್');
INSERT INTO "country" ("id", "name") VALUES ('ssa', 'ನಿಲೋ-ಸಹಾರನ್ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('nub', 'ನುಬಿಯನ್ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('ne', 'ನೇಪಾಳಿ');
INSERT INTO "country" ("id", "name") VALUES ('new', 'ನೇವಾರೀ');
INSERT INTO "country" ("id", "name") VALUES ('nic', 'ನೈಗರ್-ಕೊರ್ಡೊಫನಿಯನ್ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('nog', 'ನೊಗಾಯ್');
INSERT INTO "country" ("id", "name") VALUES ('nb', 'ನೋರ್ವೇಜಿಯನ್ ಬೊಕ್ಮಲ್');
INSERT INTO "country" ("id", "name") VALUES ('na', 'ನೌರು');
INSERT INTO "country" ("id", "name") VALUES ('ny', 'ನ್ಯಾಂಜಾ');
INSERT INTO "country" ("id", "name") VALUES ('nyn', 'ನ್ಯಾನ್‌ಕೋಲೆ');
INSERT INTO "country" ("id", "name") VALUES ('nym', 'ನ್ಯಾಮ್‌ವೆಂಜಿ');
INSERT INTO "country" ("id", "name") VALUES ('tog', 'ನ್ಯಾಸಾ ಟೋಂಗಾ');
INSERT INTO "country" ("id", "name") VALUES ('nyo', 'ನ್ಯೋರೋ');
INSERT INTO "country" ("id", "name") VALUES ('pag', 'ಪಂಗಾಸಿನನ್');
INSERT INTO "country" ("id", "name") VALUES ('pa', 'ಪಂಜಾಬಿ');
INSERT INTO "country" ("id", "name") VALUES ('pam', 'ಪಂಪಾಂಗಾ');
INSERT INTO "country" ("id", "name") VALUES ('paa', 'ಪಪುವನ್ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('fa', 'ಪರ್ಶಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('pau', 'ಪಲುಆನ್');
INSERT INTO "country" ("id", "name") VALUES ('fy', 'ಪಶ್ಚಿಮ ಫ್ರಿಸಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('pal', 'ಪಹ್ಲವಿ');
INSERT INTO "country" ("id", "name") VALUES ('pap', 'ಪಾಪಿಯಮೆಂಟೋ');
INSERT INTO "country" ("id", "name") VALUES ('pi', 'ಪಾಲಿ');
INSERT INTO "country" ("id", "name") VALUES ('ps', 'ಪಾಷ್ಟೋ');
INSERT INTO "country" ("id", "name") VALUES ('frs', 'ಪೂರ್ವ ಫ್ರಿಸಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('pon', 'ಪೋನ್‌‌ಪಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('pt', 'ಪೋರ್ಚುಗೀಸ್');
INSERT INTO "country" ("id", "name") VALUES ('cpp', 'ಪೋರ್ಚುಗೀಸ್- ಮೂಲದ ಕ್ರಿಯೋಲ್ ಅಥವಾ ಪಿಡ್ಗಿನ್');
INSERT INTO "country" ("id", "name") VALUES ('pl', 'ಪೋಲಿಶ್');
INSERT INTO "country" ("id", "name") VALUES ('pra', 'ಪ್ರಾಕೃತ್ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('ang', 'ಪ್ರಾಚೀನ ಇಂಗ್ಲೀಷ್');
INSERT INTO "country" ("id", "name") VALUES ('egy', 'ಪ್ರಾಚೀನ ಈಜಿಪ್ಟಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('sga', 'ಪ್ರಾಚೀನ ಐರಿಷ್');
INSERT INTO "country" ("id", "name") VALUES ('grc', 'ಪ್ರಾಚೀನ ಗ್ರೀಕ್');
INSERT INTO "country" ("id", "name") VALUES ('non', 'ಪ್ರಾಚೀನ ನೋರ್ಸ್');
INSERT INTO "country" ("id", "name") VALUES ('peo', 'ಪ್ರಾಚೀನ ಪರ್ಶಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('pro', 'ಪ್ರಾಚೀನ ಪ್ರೊವೆನ್ಶಿಯಲ್');
INSERT INTO "country" ("id", "name") VALUES ('fro', 'ಪ್ರಾಚೀನ ಫ್ರೆಂಚ್');
INSERT INTO "country" ("id", "name") VALUES ('goh', 'ಪ್ರಾಚೀನ ಹೈ ಜರ್ಮನ್');
INSERT INTO "country" ("id", "name") VALUES ('fo', 'ಫರೋಸಿ');
INSERT INTO "country" ("id", "name") VALUES ('fat', 'ಫಾಂಟಿ');
INSERT INTO "country" ("id", "name") VALUES ('fj', 'ಫಿಜಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('fi', 'ಫಿನ್ನಿಶ್');
INSERT INTO "country" ("id", "name") VALUES ('fiu', 'ಫಿನ್ನೋ-ಉಗ್ರಿಯನ್ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('fil', 'ಫಿಲಿಪಿನೊ');
INSERT INTO "country" ("id", "name") VALUES ('phi', 'ಫಿಲಿಫೈನ್ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('phn', 'ಫೀನಿಷಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('ff', 'ಫುಲಾಹ್');
INSERT INTO "country" ("id", "name") VALUES ('fan', 'ಫೆಂಗ್');
INSERT INTO "country" ("id", "name") VALUES ('fon', 'ಫೋನ್');
INSERT INTO "country" ("id", "name") VALUES ('fur', 'ಫ್ರಿಯುಲಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('fr', 'ಫ್ರೆಂಚ್');
INSERT INTO "country" ("id", "name") VALUES ('cpf', 'ಫ್ರೆಂಚ್-ಮೂಲದ ಕ್ರಿಯೋಲ್ ಅಥವಾ ಪಿಡ್ಗಿನ್');
INSERT INTO "country" ("id", "name") VALUES ('nl_BE', 'ಫ್ಲೆಮಿಷ್');
INSERT INTO "country" ("id", "name") VALUES ('bnt', 'ಬಂಟು');
INSERT INTO "country" ("id", "name") VALUES ('bm', 'ಬಂಬಾರಾ');
INSERT INTO "country" ("id", "name") VALUES ('btk', 'ಬಟಾಕ್');
INSERT INTO "country" ("id", "name") VALUES ('bai', 'ಬಮಿಲೇಕೆ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('my', 'ಬರ್ಮೀಸ್');
INSERT INTO "country" ("id", "name") VALUES ('ban', 'ಬಲಿನೀಸ್');
INSERT INTO "country" ("id", "name") VALUES ('bal', 'ಬಲೂಚಿ');
INSERT INTO "country" ("id", "name") VALUES ('bg', 'ಬಲ್ಗೇರಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('ba', 'ಬಶ್ಕಿರ್');
INSERT INTO "country" ("id", "name") VALUES ('bas', 'ಬಸಾ');
INSERT INTO "country" ("id", "name") VALUES ('mul', 'ಬಹುಸಂಖ್ಯೆಯ ಭಾಷೆಗಳು');
INSERT INTO "country" ("id", "name") VALUES ('bad', 'ಬಾಂಡಾ');
INSERT INTO "country" ("id", "name") VALUES ('bat', 'ಬಾಲ್ಟಿಕ್ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('eu', 'ಬಾಸ್ಕ್');
INSERT INTO "country" ("id", "name") VALUES ('bik', 'ಬಿಕೊಲ್');
INSERT INTO "country" ("id", "name") VALUES ('bin', 'ಬಿನಿ');
INSERT INTO "country" ("id", "name") VALUES ('bi', 'ಬಿಸ್ಲಾಮಾ');
INSERT INTO "country" ("id", "name") VALUES ('bh', 'ಬಿಹಾರಿ');
INSERT INTO "country" ("id", "name") VALUES ('bug', 'ಬುಗಿನೀಸ್');
INSERT INTO "country" ("id", "name") VALUES ('bua', 'ಬುರಿಯಟ್');
INSERT INTO "country" ("id", "name") VALUES ('bn', 'ಬೆಂಗಾಲಿ');
INSERT INTO "country" ("id", "name") VALUES ('bem', 'ಬೆಂಬಾ');
INSERT INTO "country" ("id", "name") VALUES ('ber', 'ಬೆರ್ಬರ್');
INSERT INTO "country" ("id", "name") VALUES ('be', 'ಬೆಲರೂಸಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('bej', 'ಬೇಜಾ');
INSERT INTO "country" ("id", "name") VALUES ('bs', 'ಬೋಸ್ನಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('bra', 'ಬ್ರಾಜ್');
INSERT INTO "country" ("id", "name") VALUES ('en_GB', 'ಬ್ರಿಟಿಷ್ ಇಂಗ್ಲೀಷ್');
INSERT INTO "country" ("id", "name") VALUES ('pt_BR', 'ಬ್ರೆಜಿಲಿಯನ್ ಪೋರ್ಚುಗೀಸ್');
INSERT INTO "country" ("id", "name") VALUES ('br', 'ಬ್ರೆಟನ್');
INSERT INTO "country" ("id", "name") VALUES ('byn', 'ಬ್ಲಿನ್');
INSERT INTO "country" ("id", "name") VALUES ('zbl', 'ಬ್ಲಿಸ್‌ಸಿಂಬಲ್ಸ್');
INSERT INTO "country" ("id", "name") VALUES ('inc', 'ಭಾರತೀಯ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('bho', 'ಭೋಜಪುರಿ');
INSERT INTO "country" ("id", "name") VALUES ('mn', 'ಮಂಗೋಲಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('mnc', 'ಮಂಚು');
INSERT INTO "country" ("id", "name") VALUES ('man', 'ಮಂಡಿಂಗೊ');
INSERT INTO "country" ("id", "name") VALUES ('mdr', 'ಮಂದಾರ್');
INSERT INTO "country" ("id", "name") VALUES ('mak', 'ಮಕಾಸರ್');
INSERT INTO "country" ("id", "name") VALUES ('mag', 'ಮಗಾಹಿ');
INSERT INTO "country" ("id", "name") VALUES ('mni', 'ಮಣಿಪುರಿ');
INSERT INTO "country" ("id", "name") VALUES ('mad', 'ಮದುರೀಸ್');
INSERT INTO "country" ("id", "name") VALUES ('cai', 'ಮಧ್ಯ ಅಮೇರಿಕನ್ ಇಂಡಿಯನ್ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('enm', 'ಮಧ್ಯ ಇಂಗ್ಲೀಷ್');
INSERT INTO "country" ("id", "name") VALUES ('mga', 'ಮಧ್ಯ ಐರಿಷ್');
INSERT INTO "country" ("id", "name") VALUES ('dum', 'ಮಧ್ಯ ಡಚ್');
INSERT INTO "country" ("id", "name") VALUES ('frm', 'ಮಧ್ಯ ಫ್ರೆಂಚ್');
INSERT INTO "country" ("id", "name") VALUES ('gmh', 'ಮಧ್ಯ ಹೈ ಜರ್ಮನ್');
INSERT INTO "country" ("id", "name") VALUES ('mno', 'ಮನೋಬೋ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('myn', 'ಮಯನ್ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('mr', 'ಮರಾಠಿ');
INSERT INTO "country" ("id", "name") VALUES ('mg', 'ಮಲಗಾಸಿ');
INSERT INTO "country" ("id", "name") VALUES ('ms', 'ಮಲಯ');
INSERT INTO "country" ("id", "name") VALUES ('ml', 'ಮಲೆಯಾಳಂ');
INSERT INTO "country" ("id", "name") VALUES ('mas', 'ಮಸಾಯ್');
INSERT INTO "country" ("id", "name") VALUES ('chm', 'ಮಾರಿ');
INSERT INTO "country" ("id", "name") VALUES ('mwr', 'ಮಾರ್ವಾಡಿ');
INSERT INTO "country" ("id", "name") VALUES ('mh', 'ಮಾರ್ಶಲ್ಲೀಸ್');
INSERT INTO "country" ("id", "name") VALUES ('mt', 'ಮಾಲ್ಟೀಸ್');
INSERT INTO "country" ("id", "name") VALUES ('mo', 'ಮಾಲ್ಡೀವಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('mi', 'ಮಾವೋರಿ');
INSERT INTO "country" ("id", "name") VALUES ('mic', 'ಮಿಕ್‌ಮ್ಯಾಕ್');
INSERT INTO "country" ("id", "name") VALUES ('min', 'ಮಿನಂಗ್‌ಕಬಾವು');
INSERT INTO "country" ("id", "name") VALUES ('mun', 'ಮುಂಡಾ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('men', 'ಮೆಂಡೆ');
INSERT INTO "country" ("id", "name") VALUES ('mk', 'ಮೆಸಿಡೋನಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('mai', 'ಮೈಥಿಲಿ');
INSERT INTO "country" ("id", "name") VALUES ('lol', 'ಮೊಂಗೋ');
INSERT INTO "country" ("id", "name") VALUES ('mos', 'ಮೊಸ್ಸಿ');
INSERT INTO "country" ("id", "name") VALUES ('moh', 'ಮೊಹಾವ್ಕ್');
INSERT INTO "country" ("id", "name") VALUES ('hmn', 'ಮೋಂಗ್');
INSERT INTO "country" ("id", "name") VALUES ('mdf', 'ಮೋಕ್ಷ');
INSERT INTO "country" ("id", "name") VALUES ('mkh', 'ಮೋನ್-ಖಮೇರ್ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('gv', 'ಮ್ಯಾಂಕ್ಸ್');
INSERT INTO "country" ("id", "name") VALUES ('yap', 'ಯಪೀಸೆ');
INSERT INTO "country" ("id", "name") VALUES ('yao', 'ಯಾಓ');
INSERT INTO "country" ("id", "name") VALUES ('sah', 'ಯಾಕುಟ್');
INSERT INTO "country" ("id", "name") VALUES ('zxx', 'ಯಾವುದೇ ಭಾಷಾಸಂಬಂಧಿ ವಿಷಯವಿಲ್ಲ');
INSERT INTO "country" ("id", "name") VALUES ('yi', 'ಯಿಡ್ಡಿಷ್');
INSERT INTO "country" ("id", "name") VALUES ('en_US', 'ಯು.ಎಸ್. ಇಂಗ್ಲೀಷ್');
INSERT INTO "country" ("id", "name") VALUES ('ypk', 'ಯೂಪಿಕ್ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('yo', 'ಯೊರುಬಾ');
INSERT INTO "country" ("id", "name") VALUES ('ru', 'ರಶಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('rm', 'ರಹೇಟೋ-ರೋಮ್ಯಾನ್ಸ್');
INSERT INTO "country" ("id", "name") VALUES ('raj', 'ರಾಜಾಸ್ಥಾನಿ');
INSERT INTO "country" ("id", "name") VALUES ('rap', 'ರಾಪಾನುಯಿ');
INSERT INTO "country" ("id", "name") VALUES ('rar', 'ರಾರೋಟೊಂಗನ್');
INSERT INTO "country" ("id", "name") VALUES ('rn', 'ರುಂಡಿ');
INSERT INTO "country" ("id", "name") VALUES ('root', 'ರೂಟ್');
INSERT INTO "country" ("id", "name") VALUES ('ro', 'ರೊಮ್ಯಾನಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('roa', 'ರೋಮನ್ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('rom', 'ರೋಮಾನಿ');
INSERT INTO "country" ("id", "name") VALUES ('lam', 'ಲಂಬಾ');
INSERT INTO "country" ("id", "name") VALUES ('lb', 'ಲಕ್ಸಂಬರ್ಗ್');
INSERT INTO "country" ("id", "name") VALUES ('lv', 'ಲಟ್ವಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('lah', 'ಲಹಂಡಾ');
INSERT INTO "country" ("id", "name") VALUES ('lo', 'ಲಾವೋ');
INSERT INTO "country" ("id", "name") VALUES ('ln', 'ಲಿಂಗಾಲ');
INSERT INTO "country" ("id", "name") VALUES ('li', 'ಲಿಂಬರ್ಗಿಶ್');
INSERT INTO "country" ("id", "name") VALUES ('lt', 'ಲಿಥುವೇನಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('lun', 'ಲುಂಡಾ');
INSERT INTO "country" ("id", "name") VALUES ('luo', 'ಲುವೋ');
INSERT INTO "country" ("id", "name") VALUES ('lus', 'ಲುಶಾಯ್');
INSERT INTO "country" ("id", "name") VALUES ('lu', 'ಲೂಬಾ-ಕಟಾಂಗಾ');
INSERT INTO "country" ("id", "name") VALUES ('lua', 'ಲೂಬಾ-ಲುಲುಆ');
INSERT INTO "country" ("id", "name") VALUES ('lui', 'ಲೂಯಿಸೆನೋ');
INSERT INTO "country" ("id", "name") VALUES ('smj', 'ಲೂಲ್ ಸಾಮಿ');
INSERT INTO "country" ("id", "name") VALUES ('lez', 'ಲೆಜ್ಘಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('jbo', 'ಲೊಜ್ಬಾನ್');
INSERT INTO "country" ("id", "name") VALUES ('nds', 'ಲೋ ಜರ್ಮನ್');
INSERT INTO "country" ("id", "name") VALUES ('loz', 'ಲೋಜಿ');
INSERT INTO "country" ("id", "name") VALUES ('dsb', 'ಲೋವರ್ ಸೋರ್ಬಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('la', 'ಲ್ಯಾಟಿನ್');
INSERT INTO "country" ("id", "name") VALUES ('es_419', 'ಲ್ಯಾಟಿನ್ ಅಮೇರಿಕನ್ ಸ್ಪ್ಯಾನಿಶ್');
INSERT INTO "country" ("id", "name") VALUES ('war', 'ವರಾಯ್');
INSERT INTO "country" ("id", "name") VALUES ('wal', 'ವಲಾಮೋ');
INSERT INTO "country" ("id", "name") VALUES ('wak', 'ವಾಕಾಷನ್ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('vai', 'ವಾಯಿ');
INSERT INTO "country" ("id", "name") VALUES ('wa', 'ವಾಲೂನ್');
INSERT INTO "country" ("id", "name") VALUES ('was', 'ವಾಷೋ');
INSERT INTO "country" ("id", "name") VALUES ('vi', 'ವಿಯೇಟ್ನಾಮೀಸ್');
INSERT INTO "country" ("id", "name") VALUES ('ve', 'ವೆಂಡಾ');
INSERT INTO "country" ("id", "name") VALUES ('cy', 'ವೆಲ್ಶ್');
INSERT INTO "country" ("id", "name") VALUES ('vot', 'ವೋಟಿಕ್');
INSERT INTO "country" ("id", "name") VALUES ('vo', 'ವೋಲಾಪುಕ್');
INSERT INTO "country" ("id", "name") VALUES ('wo', 'ವೋಲೋಫ್');
INSERT INTO "country" ("id", "name") VALUES ('shn', 'ಶಾನ್');
INSERT INTO "country" ("id", "name") VALUES ('nwc', 'ಶಾಸ್ತ್ರೀಯ ನೇವಾರಿ');
INSERT INTO "country" ("id", "name") VALUES ('syc', 'ಶಾಸ್ತ್ರೀಯ ಸಿರಿಯಕ್');
INSERT INTO "country" ("id", "name") VALUES ('sn', 'ಶೋನಾ');
INSERT INTO "country" ("id", "name") VALUES ('xh', 'ಷೋಸಾ');
INSERT INTO "country" ("id", "name") VALUES ('sgn', 'ಸಂಜ್ಞಾ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('sad', 'ಸಂಡಾವೇ');
INSERT INTO "country" ("id", "name") VALUES ('sat', 'ಸಂತಾಲಿ');
INSERT INTO "country" ("id", "name") VALUES ('sa', 'ಸಂಸ್ಕೃತ');
INSERT INTO "country" ("id", "name") VALUES ('sam', 'ಸಮರಿಟನ್ ಅರಾಮಿಕ್');
INSERT INTO "country" ("id", "name") VALUES ('sm', 'ಸಮೋವನ್');
INSERT INTO "country" ("id", "name") VALUES ('mis', 'ಸಮ್ಮಿಶ್ರ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('sc', 'ಸರ್ಡೀನಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('sr', 'ಸರ್ಬಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('sh', 'ಸರ್ಬೋ-ಕ್ರೊಯೇಶಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('sal', 'ಸಲಿಷನ್ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('sas', 'ಸಸಾಕ್');
INSERT INTO "country" ("id", "name") VALUES ('sg', 'ಸಾಂಗೋ');
INSERT INTO "country" ("id", "name") VALUES ('smi', 'ಸಾಮಿ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('sd', 'ಸಿಂಧಿ');
INSERT INTO "country" ("id", "name") VALUES ('zh_Hans', 'ಸಿಂಪ್ಲಿಫೈಡ್ ಚೈನೀಸ್');
INSERT INTO "country" ("id", "name") VALUES ('tsi', 'ಸಿಂಶಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('si', 'ಸಿಂಹಳ');
INSERT INTO "country" ("id", "name") VALUES ('bla', 'ಸಿಕ್ಸಿಕಾ');
INSERT INTO "country" ("id", "name") VALUES ('ii', 'ಸಿಚುಅನ್ ಯಿ');
INSERT INTO "country" ("id", "name") VALUES ('sid', 'ಸಿಡಾಮೋ');
INSERT INTO "country" ("id", "name") VALUES ('syr', 'ಸಿರಿಯಕ್');
INSERT INTO "country" ("id", "name") VALUES ('sio', 'ಸಿವುಅನ್ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('scn', 'ಸಿಸಿಲಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('su', 'ಸುಂಡಾನೀಸ್');
INSERT INTO "country" ("id", "name") VALUES ('suk', 'ಸುಕುಮಾ');
INSERT INTO "country" ("id", "name") VALUES ('sux', 'ಸುಮೇರಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('sus', 'ಸುಸು');
INSERT INTO "country" ("id", "name") VALUES ('ceb', 'ಸೆಬುಆನೋ');
INSERT INTO "country" ("id", "name") VALUES ('sem', 'ಸೆಮಿಟಿಕ್ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('sel', 'ಸೆಲ್ಕಪ್');
INSERT INTO "country" ("id", "name") VALUES ('cel', 'ಸೆಲ್ಟಿಕ್ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('srr', 'ಸೇರೇರ್');
INSERT INTO "country" ("id", "name") VALUES ('sit', 'ಸೈನೋ-ಟಿಬೇಟಿಯನ್ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('ts', 'ಸೋಂಗಾ');
INSERT INTO "country" ("id", "name") VALUES ('son', 'ಸೋಂಘಾಯ್');
INSERT INTO "country" ("id", "name") VALUES ('sog', 'ಸೋಗ್ಡಿಏನ್');
INSERT INTO "country" ("id", "name") VALUES ('snk', 'ಸೋನಿಂಕೆ');
INSERT INTO "country" ("id", "name") VALUES ('so', 'ಸೋಮಾಲಿ');
INSERT INTO "country" ("id", "name") VALUES ('wen', 'ಸೋರ್ಬಿಯನ್ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('gd', 'ಸ್ಕಾಟಿಶ್ ಗ್ಯಾಲಿಕ್');
INSERT INTO "country" ("id", "name") VALUES ('sms', 'ಸ್ಕೋಟ್ ಸಾಮಿ');
INSERT INTO "country" ("id", "name") VALUES ('sco', 'ಸ್ಕೋಟ್ಸ್');
INSERT INTO "country" ("id", "name") VALUES ('es', 'ಸ್ಪ್ಯಾನಿಷ್');
INSERT INTO "country" ("id", "name") VALUES ('srn', 'ಸ್ರಾನನ್ ಟೋಂಗೋ');
INSERT INTO "country" ("id", "name") VALUES ('sla', 'ಸ್ಲಾವಿಕ್ ಭಾಷೆ');
INSERT INTO "country" ("id", "name") VALUES ('den', 'ಸ್ಲೇವ್');
INSERT INTO "country" ("id", "name") VALUES ('sk', 'ಸ್ಲೋವಾಕ್');
INSERT INTO "country" ("id", "name") VALUES ('sl', 'ಸ್ಲೋವೇನಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('sw', 'ಸ್ವಹಿಲಿ');
INSERT INTO "country" ("id", "name") VALUES ('ss', 'ಸ್ವಾತಿ');
INSERT INTO "country" ("id", "name") VALUES ('tn', 'ಸ್ವಾನಾ');
INSERT INTO "country" ("id", "name") VALUES ('gsw', 'ಸ್ವಿಸ್ ಜರ್ಮನ್');
INSERT INTO "country" ("id", "name") VALUES ('fr_CH', 'ಸ್ವಿಸ್ ಫ್ರೆಂಚ್');
INSERT INTO "country" ("id", "name") VALUES ('de_CH', 'ಸ್ವಿಸ್ ಹೈ ಜರ್ಮನ್');
INSERT INTO "country" ("id", "name") VALUES ('sv', 'ಸ್ವೀಡಿಷ್');
INSERT INTO "country" ("id", "name") VALUES ('hu', 'ಹಂಗೇರಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('haw', 'ಹವಾಯಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('hi', 'ಹಿಂದಿ');
INSERT INTO "country" ("id", "name") VALUES ('hit', 'ಹಿಟ್ಟಿಟೆ');
INSERT INTO "country" ("id", "name") VALUES ('him', 'ಹಿಮಾಚಲಿ');
INSERT INTO "country" ("id", "name") VALUES ('ho', 'ಹಿರಿ ಮೊಟು');
INSERT INTO "country" ("id", "name") VALUES ('hil', 'ಹಿಲಿಗೇನನ್');
INSERT INTO "country" ("id", "name") VALUES ('he', 'ಹೀಬ್ರ್ಯೂ');
INSERT INTO "country" ("id", "name") VALUES ('hup', 'ಹೂಪಾ');
INSERT INTO "country" ("id", "name") VALUES ('hz', 'ಹೆರೆರೊ');
INSERT INTO "country" ("id", "name") VALUES ('hai', 'ಹೈಡಾ');
INSERT INTO "country" ("id", "name") VALUES ('ht', 'ಹೈತಿಯನ್');
INSERT INTO "country" ("id", "name") VALUES ('ha', 'ಹೌಸಾ');
