CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('kn', 'ཀ་ན་ཌ');
INSERT INTO [country] ([id], [name]) VALUES ('ks', 'ཀེཤ་མི་རི');
INSERT INTO [country] ([id], [name]) VALUES ('ko', 'ཀོ་རིཡན');
INSERT INTO [country] ([id], [name]) VALUES ('km', 'ཁེ་མར');
INSERT INTO [country] ([id], [name]) VALUES ('el', 'གིརིཀ');
INSERT INTO [country] ([id], [name]) VALUES ('grc', 'གིརིཀ, སྔ་དུས་ཀྱི (༡༤༥༣)');
INSERT INTO [country] ([id], [name]) VALUES ('cs', 'ཅེཀ');
INSERT INTO [country] ([id], [name]) VALUES ('de', 'ཇཱར་མཱན');
INSERT INTO [country] ([id], [name]) VALUES ('nl', 'ཌཆ');
INSERT INTO [country] ([id], [name]) VALUES ('da', 'ཌེ་ནིཤ');
INSERT INTO [country] ([id], [name]) VALUES ('ta', 'ཏ་མིལ');
INSERT INTO [country] ([id], [name]) VALUES ('te', 'ཏེ་ལུ་གུ');
INSERT INTO [country] ([id], [name]) VALUES ('th', 'ཐཱའེ');
INSERT INTO [country] ([id], [name]) VALUES ('dv', 'དི་བེ་ཧི');
INSERT INTO [country] ([id], [name]) VALUES ('new', 'ནི་ཝ་རི');
INSERT INTO [country] ([id], [name]) VALUES ('ne', 'ནེ་པ་ལི');
INSERT INTO [country] ([id], [name]) VALUES ('no', 'ནོར་ཝི་ཇི་ཡན');
INSERT INTO [country] ([id], [name]) VALUES ('pi', 'པ་ལི');
INSERT INTO [country] ([id], [name]) VALUES ('fa', 'པར་ཤི་ཡན');
INSERT INTO [country] ([id], [name]) VALUES ('pa', 'པཱན་ཇ་བི');
INSERT INTO [country] ([id], [name]) VALUES ('fr', 'ཕེ་རེནཆེ');
INSERT INTO [country] ([id], [name]) VALUES ('art', 'བཟོ་བཟོཝ (གཞན)');
INSERT INTO [country] ([id], [name]) VALUES ('my', 'བར་མིསི');
INSERT INTO [country] ([id], [name]) VALUES ('bh', 'བི་ཧ་ལི');
INSERT INTO [country] ([id], [name]) VALUES ('bn', 'བེངྒ་ལི');
INSERT INTO [country] ([id], [name]) VALUES ('bo', 'བོད་ཁ');
INSERT INTO [country] ([id], [name]) VALUES ('mni', 'མ་ནི་པུ་རི');
INSERT INTO [country] ([id], [name]) VALUES ('mr', 'མ་ར་ཐི');
INSERT INTO [country] ([id], [name]) VALUES ('ml', 'མ་ལ་ཡ་ལམ');
INSERT INTO [country] ([id], [name]) VALUES ('mnc', 'མཱན་ཅུ');
INSERT INTO [country] ([id], [name]) VALUES ('ru', 'ར་ཤི་ཡན');
INSERT INTO [country] ([id], [name]) VALUES ('zh', 'རགྱ་མི་ཁ');
INSERT INTO [country] ([id], [name]) VALUES ('dz', 'རྫོང་ཁ');
INSERT INTO [country] ([id], [name]) VALUES ('lo', 'ལའོ');
INSERT INTO [country] ([id], [name]) VALUES ('si', 'སིན་ཧ་ལིསི');
INSERT INTO [country] ([id], [name]) VALUES ('es', 'སིཔེ་ནིཤ');
INSERT INTO [country] ([id], [name]) VALUES ('mn', 'སོག་པོའི་ཁ');
INSERT INTO [country] ([id], [name]) VALUES ('sa', 'སཾསྐྲྀཏ');
INSERT INTO [country] ([id], [name]) VALUES ('he', 'ཧི་བུརུ');
INSERT INTO [country] ([id], [name]) VALUES ('him', 'ཧི་མ་ཅ་ལི');
INSERT INTO [country] ([id], [name]) VALUES ('hi', 'ཧིན་དི');
INSERT INTO [country] ([id], [name]) VALUES ('as', 'ཨ་ས་མི་སི');
INSERT INTO [country] ([id], [name]) VALUES ('ga', 'ཨའི་རིཤ');
INSERT INTO [country] ([id], [name]) VALUES ('egy', 'ཨི་ཇིཔ་ཤཱན (སྔ་དུས་ཀྱི)');
INSERT INTO [country] ([id], [name]) VALUES ('it', 'ཨི་ཊ་ལི་རན');
INSERT INTO [country] ([id], [name]) VALUES ('en', 'ཨིང་ལིཤ');
INSERT INTO [country] ([id], [name]) VALUES ('inc', 'ཨིན་ཌིཀ (གཞན)');
INSERT INTO [country] ([id], [name]) VALUES ('ur', 'ཨུར་དུ');
INSERT INTO [country] ([id], [name]) VALUES ('ar', 'ཨེ་ར་སྦིག');
INSERT INTO [country] ([id], [name]) VALUES ('or', 'ཨོ་རི་ཡ');
