CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('no', 'Af Noorwiijiyaan');
INSERT INTO "country" ("id", "name") VALUES ('und', 'Af aan la aqoon ama aan sax ahayn');
INSERT INTO "country" ("id", "name") VALUES ('af', 'Afrikaanays');
INSERT INTO "country" ("id", "name") VALUES ('sq', 'Albaaniyaan');
INSERT INTO "country" ("id", "name") VALUES ('am', 'Amhari');
INSERT INTO "country" ("id", "name") VALUES ('hy', 'Armeeniyaan');
INSERT INTO "country" ("id", "name") VALUES ('as', 'Asaamiis');
INSERT INTO "country" ("id", "name") VALUES ('ga', 'Ayrish');
INSERT INTO "country" ("id", "name") VALUES ('is', 'Ayslandays');
INSERT INTO "country" ("id", "name") VALUES ('az', 'Azerbaijan');
INSERT INTO "country" ("id", "name") VALUES ('bn', 'Bangaali');
INSERT INTO "country" ("id", "name") VALUES ('ps', 'Bashtuu');
INSERT INTO "country" ("id", "name") VALUES ('eu', 'Basquu');
INSERT INTO "country" ("id", "name") VALUES ('be', 'Beleruusiyaan');
INSERT INTO "country" ("id", "name") VALUES ('br', 'Bereton');
INSERT INTO "country" ("id", "name") VALUES ('bh', 'Bixaari');
INSERT INTO "country" ("id", "name") VALUES ('pl', 'Boolish');
INSERT INTO "country" ("id", "name") VALUES ('pt', 'Boortaqiis');
INSERT INTO "country" ("id", "name") VALUES ('pt_PT', 'Boortaqiis (Boortuqaal)');
INSERT INTO "country" ("id", "name") VALUES ('pt_BR', 'Boortaqiiska Baraasiil');
INSERT INTO "country" ("id", "name") VALUES ('bs', 'Boosniya');
INSERT INTO "country" ("id", "name") VALUES ('bg', 'Bulgeeriyaan');
INSERT INTO "country" ("id", "name") VALUES ('pa', 'Bunjaabi');
INSERT INTO "country" ("id", "name") VALUES ('ar', 'Carabi');
INSERT INTO "country" ("id", "name") VALUES ('he', 'Cibri');
INSERT INTO "country" ("id", "name") VALUES ('da', 'Danmarkays');
INSERT INTO "country" ("id", "name") VALUES ('fa', 'Faarisi');
INSERT INTO "country" ("id", "name") VALUES ('fr', 'Faransiis');
INSERT INTO "country" ("id", "name") VALUES ('fr_CH', 'Faransiis (Iswiiserlaand)');
INSERT INTO "country" ("id", "name") VALUES ('fo', 'Farowsi');
INSERT INTO "country" ("id", "name") VALUES ('fi', 'Fiinlaandees');
INSERT INTO "country" ("id", "name") VALUES ('vi', 'Fiitnaamays');
INSERT INTO "country" ("id", "name") VALUES ('fy', 'Firiisiyan Galbeed');
INSERT INTO "country" ("id", "name") VALUES ('gl', 'Galiisiyaan');
INSERT INTO "country" ("id", "name") VALUES ('el', 'Giriik');
INSERT INTO "country" ("id", "name") VALUES ('gu', 'Gujaraati');
INSERT INTO "country" ("id", "name") VALUES ('gn', 'Guraani');
INSERT INTO "country" ("id", "name") VALUES ('hu', 'Hangariyaan');
INSERT INTO "country" ("id", "name") VALUES ('hi', 'Hindi');
INSERT INTO "country" ("id", "name") VALUES ('nl', 'Holandays');
INSERT INTO "country" ("id", "name") VALUES ('xh', 'Hoosta');
INSERT INTO "country" ("id", "name") VALUES ('id', 'Indunuusiyaan');
INSERT INTO "country" ("id", "name") VALUES ('en', 'Ingiriisi');
INSERT INTO "country" ("id", "name") VALUES ('en_GB', 'Ingiriisi (Boqortooyada Midowday)');
INSERT INTO "country" ("id", "name") VALUES ('en_US', 'Ingiriisi (Maraykan)');
INSERT INTO "country" ("id", "name") VALUES ('ie', 'Interlingue');
INSERT INTO "country" ("id", "name") VALUES ('ia', 'Interlinguwa');
INSERT INTO "country" ("id", "name") VALUES ('es', 'Isbaanish');
INSERT INTO "country" ("id", "name") VALUES ('es_ES', 'Isbaanish (Isbayn)');
INSERT INTO "country" ("id", "name") VALUES ('es_419', 'Isbaanishka Laatiin Ameerika');
INSERT INTO "country" ("id", "name") VALUES ('eo', 'Isberento');
INSERT INTO "country" ("id", "name") VALUES ('gd', 'Iskot Giilik');
INSERT INTO "country" ("id", "name") VALUES ('sl', 'Islofeeniyaan');
INSERT INTO "country" ("id", "name") VALUES ('sk', 'Isloofaak');
INSERT INTO "country" ("id", "name") VALUES ('et', 'Istooniyaan');
INSERT INTO "country" ("id", "name") VALUES ('ja', 'Jabbaaniis');
INSERT INTO "country" ("id", "name") VALUES ('jv', 'Jafaaniis');
INSERT INTO "country" ("id", "name") VALUES ('de', 'Jarmal');
INSERT INTO "country" ("id", "name") VALUES ('de_CH', 'Jarmal (Iswiiserlaand)');
INSERT INTO "country" ("id", "name") VALUES ('zh', 'Jayniis');
INSERT INTO "country" ("id", "name") VALUES ('cs', 'Jeeg');
INSERT INTO "country" ("id", "name") VALUES ('ka', 'Joorijiyaan');
INSERT INTO "country" ("id", "name") VALUES ('km', 'Kamboodhian');
INSERT INTO "country" ("id", "name") VALUES ('kn', 'Kannadays');
INSERT INTO "country" ("id", "name") VALUES ('ca', 'Katalaan');
INSERT INTO "country" ("id", "name") VALUES ('tlh', 'Kiligoon');
INSERT INTO "country" ("id", "name") VALUES ('ky', 'Kirgiis');
INSERT INTO "country" ("id", "name") VALUES ('hr', 'Koro\'eeshiyaan');
INSERT INTO "country" ("id", "name") VALUES ('ku', 'Kurdishka');
INSERT INTO "country" ("id", "name") VALUES ('ko', 'Kuuriyaan');
INSERT INTO "country" ("id", "name") VALUES ('lv', 'Laatfiyaan');
INSERT INTO "country" ("id", "name") VALUES ('la', 'Laatiin');
INSERT INTO "country" ("id", "name") VALUES ('lo', 'Laothian');
INSERT INTO "country" ("id", "name") VALUES ('ln', 'Lingala');
INSERT INTO "country" ("id", "name") VALUES ('lt', 'Lituwaanays');
INSERT INTO "country" ("id", "name") VALUES ('mr', 'Maarati');
INSERT INTO "country" ("id", "name") VALUES ('ms', 'Malaay');
INSERT INTO "country" ("id", "name") VALUES ('ml', 'Malayalam');
INSERT INTO "country" ("id", "name") VALUES ('mt', 'Maltiis');
INSERT INTO "country" ("id", "name") VALUES ('mn', 'Mangooli');
INSERT INTO "country" ("id", "name") VALUES ('mk', 'Masadooniyaan');
INSERT INTO "country" ("id", "name") VALUES ('ne', 'Nebaali');
INSERT INTO "country" ("id", "name") VALUES ('nn', 'Nowrwejiyan (naynoroski)');
INSERT INTO "country" ("id", "name") VALUES ('oc', 'Okitaan');
INSERT INTO "country" ("id", "name") VALUES ('or', 'Oriya');
INSERT INTO "country" ("id", "name") VALUES ('ro', 'Romanka');
INSERT INTO "country" ("id", "name") VALUES ('ru', 'Ruush');
INSERT INTO "country" ("id", "name") VALUES ('sd', 'SINDHI');
INSERT INTO "country" ("id", "name") VALUES ('sa', 'Sanskrit');
INSERT INTO "country" ("id", "name") VALUES ('sw', 'Sawaaxili');
INSERT INTO "country" ("id", "name") VALUES ('sr', 'Seerbiyaan');
INSERT INTO "country" ("id", "name") VALUES ('sh', 'Serbiyaan');
INSERT INTO "country" ("id", "name") VALUES ('st', 'Sesooto');
INSERT INTO "country" ("id", "name") VALUES ('si', 'Sinhaleys');
INSERT INTO "country" ("id", "name") VALUES ('so', 'Soomaali');
INSERT INTO "country" ("id", "name") VALUES ('su', 'Suudaaniis');
INSERT INTO "country" ("id", "name") VALUES ('sv', 'Swiidhis');
INSERT INTO "country" ("id", "name") VALUES ('th', 'Taaylandays');
INSERT INTO "country" ("id", "name") VALUES ('fil', 'Tagalog');
INSERT INTO "country" ("id", "name") VALUES ('it', 'Talyaani');
INSERT INTO "country" ("id", "name") VALUES ('ta', 'Tamiil');
INSERT INTO "country" ("id", "name") VALUES ('te', 'Teluugu');
INSERT INTO "country" ("id", "name") VALUES ('ti', 'Tigrinya');
INSERT INTO "country" ("id", "name") VALUES ('tw', 'Tiwiyan');
INSERT INTO "country" ("id", "name") VALUES ('tr', 'Turkish');
INSERT INTO "country" ("id", "name") VALUES ('tk', 'Turkumaanish');
INSERT INTO "country" ("id", "name") VALUES ('ug', 'UIGHUR');
INSERT INTO "country" ("id", "name") VALUES ('ur', 'Urduu');
INSERT INTO "country" ("id", "name") VALUES ('uz', 'Usbakis');
INSERT INTO "country" ("id", "name") VALUES ('cy', 'Welsh');
INSERT INTO "country" ("id", "name") VALUES ('yi', 'Yadhish');
INSERT INTO "country" ("id", "name") VALUES ('uk', 'Yukreeniyaan');
INSERT INTO "country" ("id", "name") VALUES ('zu', 'Zuulu');
