CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('af', 'Afrikaans');
INSERT INTO [country] ([id], [name]) VALUES ('sq', 'Albanés');
INSERT INTO [country] ([id], [name]) VALUES ('de', 'Alemán');
INSERT INTO [country] ([id], [name]) VALUES ('de_AT', 'Alemán de Austria');
INSERT INTO [country] ([id], [name]) VALUES ('de_CH', 'Alemán suízo');
INSERT INTO [country] ([id], [name]) VALUES ('am', 'Amárico');
INSERT INTO [country] ([id], [name]) VALUES ('an', 'Aragonés');
INSERT INTO [country] ([id], [name]) VALUES ('arc', 'Arameo');
INSERT INTO [country] ([id], [name]) VALUES ('hy', 'Armenio');
INSERT INTO [country] ([id], [name]) VALUES ('as', 'Assamés');
INSERT INTO [country] ([id], [name]) VALUES ('ast', 'Asturiano');
INSERT INTO [country] ([id], [name]) VALUES ('az', 'Azerbaiano');
INSERT INTO [country] ([id], [name]) VALUES ('bn', 'Bengalí');
INSERT INTO [country] ([id], [name]) VALUES ('be', 'Bielorruso');
INSERT INTO [country] ([id], [name]) VALUES ('bh', 'Bihariano');
INSERT INTO [country] ([id], [name]) VALUES ('bs', 'Bosnio');
INSERT INTO [country] ([id], [name]) VALUES ('br', 'Bretón');
INSERT INTO [country] ([id], [name]) VALUES ('bg', 'Búlgaro');
INSERT INTO [country] ([id], [name]) VALUES ('km', 'Cambodiano');
INSERT INTO [country] ([id], [name]) VALUES ('es_ES', 'Castelán');
INSERT INTO [country] ([id], [name]) VALUES ('ca', 'Catalán');
INSERT INTO [country] ([id], [name]) VALUES ('cs', 'Checo');
INSERT INTO [country] ([id], [name]) VALUES ('zh', 'Chinés');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hans', 'Chinés simplificado');
INSERT INTO [country] ([id], [name]) VALUES ('zh_Hant', 'Chinés tradicional');
INSERT INTO [country] ([id], [name]) VALUES ('tlh', 'Clingon');
INSERT INTO [country] ([id], [name]) VALUES ('ko', 'Coreano');
INSERT INTO [country] ([id], [name]) VALUES ('hr', 'Croata');
INSERT INTO [country] ([id], [name]) VALUES ('da', 'Dinamarqués');
INSERT INTO [country] ([id], [name]) VALUES ('cu', 'Eslavo eclesiástico');
INSERT INTO [country] ([id], [name]) VALUES ('sk', 'Eslovaco');
INSERT INTO [country] ([id], [name]) VALUES ('sl', 'Esloveno');
INSERT INTO [country] ([id], [name]) VALUES ('es', 'Español');
INSERT INTO [country] ([id], [name]) VALUES ('es_419', 'Español latinoamericano');
INSERT INTO [country] ([id], [name]) VALUES ('eo', 'Esperanto');
INSERT INTO [country] ([id], [name]) VALUES ('et', 'Estoniano');
INSERT INTO [country] ([id], [name]) VALUES ('egy', 'Exipcio antigo');
INSERT INTO [country] ([id], [name]) VALUES ('fo', 'Faroés');
INSERT INTO [country] ([id], [name]) VALUES ('fil', 'Filipino');
INSERT INTO [country] ([id], [name]) VALUES ('fi', 'Finés');
INSERT INTO [country] ([id], [name]) VALUES ('nl_BE', 'Flamenco');
INSERT INTO [country] ([id], [name]) VALUES ('fr', 'Francés');
INSERT INTO [country] ([id], [name]) VALUES ('fr_CA', 'Francés canadiano');
INSERT INTO [country] ([id], [name]) VALUES ('fr_CH', 'Francés suízo');
INSERT INTO [country] ([id], [name]) VALUES ('fy', 'Frisón');
INSERT INTO [country] ([id], [name]) VALUES ('cy', 'Galés');
INSERT INTO [country] ([id], [name]) VALUES ('gd', 'Gaélico escocés');
INSERT INTO [country] ([id], [name]) VALUES ('el', 'Grego');
INSERT INTO [country] ([id], [name]) VALUES ('grc', 'Grego antigo');
INSERT INTO [country] ([id], [name]) VALUES ('gn', 'Guaraní');
INSERT INTO [country] ([id], [name]) VALUES ('gu', 'Guxaratiano');
INSERT INTO [country] ([id], [name]) VALUES ('he', 'Hebreo');
INSERT INTO [country] ([id], [name]) VALUES ('hi', 'Hindi');
INSERT INTO [country] ([id], [name]) VALUES ('nl', 'Holandés');
INSERT INTO [country] ([id], [name]) VALUES ('hu', 'Húngaro');
INSERT INTO [country] ([id], [name]) VALUES ('id', 'Indonesio');
INSERT INTO [country] ([id], [name]) VALUES ('en', 'Inglés');
INSERT INTO [country] ([id], [name]) VALUES ('en_US', 'Inglés americano');
INSERT INTO [country] ([id], [name]) VALUES ('en_AU', 'Inglés australiano');
INSERT INTO [country] ([id], [name]) VALUES ('en_GB', 'Inglés británico');
INSERT INTO [country] ([id], [name]) VALUES ('en_CA', 'Inglés canadiano');
INSERT INTO [country] ([id], [name]) VALUES ('ia', 'Interlingua');
INSERT INTO [country] ([id], [name]) VALUES ('ga', 'Irlandés');
INSERT INTO [country] ([id], [name]) VALUES ('is', 'Islandés');
INSERT INTO [country] ([id], [name]) VALUES ('it', 'Italiano');
INSERT INTO [country] ([id], [name]) VALUES ('kn', 'Kannada');
INSERT INTO [country] ([id], [name]) VALUES ('ku', 'Kurdo');
INSERT INTO [country] ([id], [name]) VALUES ('ky', 'Kyrgiz');
INSERT INTO [country] ([id], [name]) VALUES ('lo', 'Laotiano');
INSERT INTO [country] ([id], [name]) VALUES ('la', 'Latín');
INSERT INTO [country] ([id], [name]) VALUES ('lv', 'Letón');
INSERT INTO [country] ([id], [name]) VALUES ('ln', 'Lingala');
INSERT INTO [country] ([id], [name]) VALUES ('afa', 'Lingua afro-asiática');
INSERT INTO [country] ([id], [name]) VALUES ('alg', 'Lingua algonquina');
INSERT INTO [country] ([id], [name]) VALUES ('tut', 'Lingua altaica');
INSERT INTO [country] ([id], [name]) VALUES ('apa', 'Lingua apache');
INSERT INTO [country] ([id], [name]) VALUES ('art', 'Lingua artificial');
INSERT INTO [country] ([id], [name]) VALUES ('aus', 'Lingua australiana');
INSERT INTO [country] ([id], [name]) VALUES ('bat', 'Lingua báltica');
INSERT INTO [country] ([id], [name]) VALUES ('cau', 'Lingua caucásica');
INSERT INTO [country] ([id], [name]) VALUES ('cel', 'Lingua céltica');
INSERT INTO [country] ([id], [name]) VALUES ('sgn', 'Lingua de signos');
INSERT INTO [country] ([id], [name]) VALUES ('und', 'Lingua descoñecida ou non válida');
INSERT INTO [country] ([id], [name]) VALUES ('ssa', 'Lingua do Nilo-Sáhara');
INSERT INTO [country] ([id], [name]) VALUES ('sla', 'Lingua eslávica');
INSERT INTO [country] ([id], [name]) VALUES ('phi', 'Lingua filipina');
INSERT INTO [country] ([id], [name]) VALUES ('fiu', 'Lingua finno-úgrica');
INSERT INTO [country] ([id], [name]) VALUES ('cai', 'Lingua india centroamericana');
INSERT INTO [country] ([id], [name]) VALUES ('nai', 'Lingua india norteamericana');
INSERT INTO [country] ([id], [name]) VALUES ('sai', 'Lingua india sudamericana');
INSERT INTO [country] ([id], [name]) VALUES ('ine', 'Lingua indoeuropea');
INSERT INTO [country] ([id], [name]) VALUES ('mis', 'Lingua miscelánea');
INSERT INTO [country] ([id], [name]) VALUES ('nub', 'Lingua nubia');
INSERT INTO [country] ([id], [name]) VALUES ('roa', 'Lingua románica');
INSERT INTO [country] ([id], [name]) VALUES ('sem', 'Lingua semita');
INSERT INTO [country] ([id], [name]) VALUES ('gem', 'Lingua xermánica');
INSERT INTO [country] ([id], [name]) VALUES ('inc', 'Lingua índica');
INSERT INTO [country] ([id], [name]) VALUES ('lt', 'Lituano');
INSERT INTO [country] ([id], [name]) VALUES ('mk', 'Macedonio');
INSERT INTO [country] ([id], [name]) VALUES ('ml', 'Malaialam');
INSERT INTO [country] ([id], [name]) VALUES ('ms', 'Malaio');
INSERT INTO [country] ([id], [name]) VALUES ('mt', 'Maltés');
INSERT INTO [country] ([id], [name]) VALUES ('mr', 'Marathi');
INSERT INTO [country] ([id], [name]) VALUES ('mn', 'Mongol');
INSERT INTO [country] ([id], [name]) VALUES ('ne', 'Nepalí');
INSERT INTO [country] ([id], [name]) VALUES ('no', 'Noruegués');
INSERT INTO [country] ([id], [name]) VALUES ('nb', 'Noruegués Bokmal');
INSERT INTO [country] ([id], [name]) VALUES ('nn', 'Noruegués nynorsk');
INSERT INTO [country] ([id], [name]) VALUES ('oc', 'Occitano');
INSERT INTO [country] ([id], [name]) VALUES ('or', 'Orissa');
INSERT INTO [country] ([id], [name]) VALUES ('ps', 'Pashto');
INSERT INTO [country] ([id], [name]) VALUES ('fa', 'Persa');
INSERT INTO [country] ([id], [name]) VALUES ('pl', 'Polaco');
INSERT INTO [country] ([id], [name]) VALUES ('pt', 'Portugués');
INSERT INTO [country] ([id], [name]) VALUES ('pt_BR', 'Portugués brasileiro');
INSERT INTO [country] ([id], [name]) VALUES ('pt_PT', 'Portugués ibérico');
INSERT INTO [country] ([id], [name]) VALUES ('pa', 'Punjabi');
INSERT INTO [country] ([id], [name]) VALUES ('ro', 'Romanés');
INSERT INTO [country] ([id], [name]) VALUES ('ru', 'Ruso');
INSERT INTO [country] ([id], [name]) VALUES ('zxx', 'Sen contido lingüístico');
INSERT INTO [country] ([id], [name]) VALUES ('sr', 'Serbio');
INSERT INTO [country] ([id], [name]) VALUES ('sh', 'Serbocroata');
INSERT INTO [country] ([id], [name]) VALUES ('st', 'Sesotho');
INSERT INTO [country] ([id], [name]) VALUES ('sd', 'Sindhi');
INSERT INTO [country] ([id], [name]) VALUES ('si', 'Sinhalés');
INSERT INTO [country] ([id], [name]) VALUES ('so', 'Somalí');
INSERT INTO [country] ([id], [name]) VALUES ('su', 'Sondanés');
INSERT INTO [country] ([id], [name]) VALUES ('sw', 'Suaxili');
INSERT INTO [country] ([id], [name]) VALUES ('sv', 'Sueco');
INSERT INTO [country] ([id], [name]) VALUES ('sa', 'Sánscrito');
INSERT INTO [country] ([id], [name]) VALUES ('tl', 'Tagalo');
INSERT INTO [country] ([id], [name]) VALUES ('th', 'Tailandés');
INSERT INTO [country] ([id], [name]) VALUES ('ta', 'Tamil');
INSERT INTO [country] ([id], [name]) VALUES ('te', 'Telugu');
INSERT INTO [country] ([id], [name]) VALUES ('ti', 'Tigriña');
INSERT INTO [country] ([id], [name]) VALUES ('tr', 'Turco');
INSERT INTO [country] ([id], [name]) VALUES ('tw', 'Twi');
INSERT INTO [country] ([id], [name]) VALUES ('uk', 'Ucraíno');
INSERT INTO [country] ([id], [name]) VALUES ('ug', 'Uighur');
INSERT INTO [country] ([id], [name]) VALUES ('ur', 'Urdú');
INSERT INTO [country] ([id], [name]) VALUES ('uz', 'Uzbeco');
INSERT INTO [country] ([id], [name]) VALUES ('mul', 'Varias linguas');
INSERT INTO [country] ([id], [name]) VALUES ('vi', 'Vietnamita');
INSERT INTO [country] ([id], [name]) VALUES ('ja', 'Xaponés');
INSERT INTO [country] ([id], [name]) VALUES ('jv', 'Xavanés');
INSERT INTO [country] ([id], [name]) VALUES ('ka', 'Xeorxiano');
INSERT INTO [country] ([id], [name]) VALUES ('xh', 'Xhosa');
INSERT INTO [country] ([id], [name]) VALUES ('yi', 'Yiddish');
INSERT INTO [country] ([id], [name]) VALUES ('zu', 'Zulú');
INSERT INTO [country] ([id], [name]) VALUES ('gl', 'galego');
INSERT INTO [country] ([id], [name]) VALUES ('ar', 'Árabe');
INSERT INTO [country] ([id], [name]) VALUES ('eu', 'Éuscaro');
